### ISSUE TITLE
"no such collation sequence: WIN32CASE" error with SQLite db created by mORMot

### ISSUE THREAD

**Issue by edwinyzh** [HeidiSQL/HeidiSQL#1000]
## Steps to reproduce this issue

1. Open a db created with [mORMot](https://github.com/synopse/mORMot);
2. Select a table and switch to the "Data" tab;
3. Try delete a row;
4. Then I get "no such collation sequence: WIN32CASE"

## Current behavior

Getting the "no such collation sequence: WIN32CASE" error dialog.

## Expected behavior

The selected row should be deleted.

## Possible solution

I know mORMot uses custom collation for the table it created, and this will affect how the official sqlite3.dll can operate on the db, but in the same case, [SQLiteStudio ](https://sqlitestudio.pl/index.rvt)can delete the row successfully. So I think there is a workaround.

## Environment
Db created by mORMot.

* **HeidiSQL version:** 
11.0.0.5919 (64 Bit)

* **Operating system:** 
Win7 64bit Home.

**Comment by ansgarbecker** [comment]
Congratulations to the 1000th issue here :)

Could you please try to find the exact query which SQLiteStudio uses to delete a row? There must be something different there. Or it probably sets a collation on the connection when connecting.

**Comment by edwinyzh** [comment]
Hey, I didn't notice it's the 1000th issue!

I checked just now, but SQLiteStudio doesn't seem to let me see the SQL it uses to delete a row.

**Comment by ansgarbecker** [comment]
Hm SQLitebrowser had the same issue some years ago, and they solved it by calling `sqlite3_collation_needed()` and `sqlite3_create_collation()`, see https://github.com/sqlitebrowser/sqlitebrowser/commit/cf33f3054e613f0a7ac20c5edf4c35ffe994e2bf 

If that commit is still in the code of SQLitebrowser, I suppose you get this message prompt "Collation needed! Proceed?" when opening your database?

**Comment by edwinyzh** [comment]
I think you confused SQLiteBrowser and SQLiteStudio? :D

**Comment by ansgarbecker** [comment]
Indeed, I mixed them up. However, is there a similar message in SQLiteStudio?

**Comment by edwinyzh** [comment]
No messages shown up before the deletion, it just delete the record.

**Comment by ansgarbecker** [comment]
Hm this is not very helpful. There seem to be custom collations in SQLite, which HeidiSQL does not support yet. As of your report, I know these exist, but how common are they?

**Comment by edwinyzh** [comment]
@ansgarbecker,
I'm not sure, but according the SQLite FAQ #18 I assume it's common, because every app needs UNICODE support, right?

> (18) Case-insensitive matching of Unicode characters does not work.
> 
> The default configuration of SQLite only supports case-insensitive comparisons of ASCII characters. The reason for this is that doing full Unicode case-insensitive comparisons and case conversions requires tables and logic that would nearly double the size of the SQLite library. The SQLite developers reason that any application that needs full Unicode case support probably already has the necessary tables and functions and so SQLite should not take up space to duplicate this ability.
> Instead of providing full Unicode case support by default, SQLite provides the ability to link against external Unicode comparison and conversion routines. The application can overload the built-in NOCASE collating sequence (using sqlite3_create_collation()) and the built-in like(), upper(), and lower() functions (using sqlite3_create_function()). The SQLite source code includes an "ICU" extension that does these overloads. Or, developers can write their own overloads based on their own Unicode-aware comparison routines already contained within their project.

**Comment by edwinyzh** [comment]
Info 2:
And a [Google search of "custom collation"](https://www.google.com/search?q=sqlite+custom+collation+site%3Astackoverflow.com&oq=sqlite+custom+collation+site%3Astackoverflow.com&aqs=chrome..69i57.9999j0j1&sourceid=chrome&ie=UTF-8) against stackoverflow.com **returns 2,650 results**

**Comment by ansgarbecker** [comment]
Ok, then I should deal with custom collations in some way.
Could you please post a minimal database file with such a custom collation here?

**Comment by edwinyzh** [comment]
The attached test.db3 (in the .zip archive) was created by the mORMot tests project, it contains some custom collations.
[test.zip](https://github.com/HeidiSQL/HeidiSQL/files/4518326/test.zip)

**Comment by ansgarbecker** [comment]
Thanks so far. I get a similar error when trying to delete rows from `AuthUser`:

![grafik](https://user-images.githubusercontent.com/7986591/80026028-c40e4900-84e1-11ea-8e9e-fda8d4062fec.png)

**Comment by ansgarbecker** [comment]
I have problems with implementing that `sqlite3_collation_needed()`, so I [posted a question at so](https://stackoverflow.com/questions/61380023/delphi-callback-procedure-for-sqlite3-collation-needed).

**Comment by ansgarbecker** [comment]
This is now fixed and works for me, and it was quite fun to do that, had to learn more about pointers, especially a self-pointer. There seems to be much confusion about these self-pointers on the net.
Please update and test yourself.

**Comment by ansgarbecker** [comment]
![grafik](https://user-images.githubusercontent.com/7986591/80303122-86921000-87ae-11ea-85e9-4c71f611c1ac.png)

**Comment by edwinyzh** [comment]
Great @ansgarbecker !  I'll test it. What self-pointer do you mean? Do you mean the "self" keyword?

**Comment by edwinyzh** [comment]
It's not released under https://www.heidisql.com/download.php, right?

**Comment by ansgarbecker** [comment]
It's just a nightly build yet, not an official release, see https://www.heidisql.com/download.php#nightlybuilds

By that self-pointer I meant an memory address pointer to the instance of my `TSQLiteConnection` class. I'm apparently not the only one having problems with that, according to [this thread](https://stackoverflow.com/questions/3824136/delphi-self-pointer-usage). Additionally, I had to find out how the sqlite3.dll (which is written in C++) wanted the pointer from withing my Delphi code. In the end it was easier than I thought, but the way to find out was hard.

**Comment by ansgarbecker** [comment]
By the way, to get the nighlty build, please use the auto-updater in Help > "Check for updates"
