### ISSUE TITLE
Cannot edit/view trigger in MSSQL

### ISSUE THREAD

**Issue by michalwoz** [HeidiSQL/HeidiSQL#1004]
## Steps to reproduce this issue

1. Step 1; Connect to MSSQL DB with trigger defined
2. Step 2; click dbo.trigger in tree
3. Then I get

```
SHOW TRIGGERS FROM "dbname";
/* SQL Error (156): Incorrect syntax near the keyword 'FROM'. */
```

## Current behavior

![image](https://user-images.githubusercontent.com/31922455/79979976-af5e9080-84a2-11ea-8fea-acef03e5b0a4.png)

## Expected behavior

edit trigger possibility

## Environment

* **HeidiSQL version:** 11.0.0.5958
  
* **Database system and version:** MSSQL 2016
  
* **Operating system:** Win10 x64

**Comment by ansgarbecker** [comment]
Duplicate to #42
