### ISSUE TITLE
Apply button is not enabled when toggling certain options in Preferences

### ISSUE THREAD

**Issue by al2k4** [HeidiSQL/HeidiSQL#1005]
## Steps to reproduce this issue

1. Open Preferences window
2. Go to "Data editors" tab
3. Toggle any of the checkboxes in the second group, either "Remember filters, ..." or "Show values in foreign key columns"

## Current behavior

Apply button remains greyed out

## Expected behavior

Apply button is enabled

## Environment

* **HeidiSQL version:** 11.0.0.5964

**Comment by ansgarbecker** [comment]
Thanks for the hint! Think I got them all now.
