### ISSUE TITLE
Bug "Broken NetType value (255)"

### ISSUE THREAD

**Issue by bagoesz21** [HeidiSQL/HeidiSQL#1008]
## Steps to reproduce this issue

1. I update the latest version (11.0.*).
2. And then, i'm open the app, i got error.
3. "Broken NetType value (255) found in settings for session mysql"
4. Then, the app is force close.

## Environment

* **HeidiSQL version: 11.0.0 ** 
  
* **Operating system: Windows 10 x64 **

**Comment by gustaflindqvist** [comment]
I'm getting this as well with the latest version 11.0.0.5919. I added a new connection in the settings just when I clicked update. So I guess I have a corrupt settings with NetType larger then 255 within settings.

**Comment by ansgarbecker** [comment]
Build 11.0.0.6097 is the latest version, while 5919 is the latest stable release. Be sure you were not downgrading to that one.

**Comment by bagoesz21** [comment]
how to fix it ?

**Comment by ansgarbecker** [comment]
Update HeidiSQL to the latest build 6097. Not the latest release. Then report back if that fixed the issue.

**Comment by gustaflindqvist** [comment]
> ase. Then report back if that fixed the issue.

I have updated to latest build 6097. Still getting error with the corrupt setting:

> Broken "NetType" value (255) found in settings for session "DB consent log". Please report that on https://github.com/HeidiSQL/HeidiSQLuery”

**Comment by ansgarbecker** [comment]
Ok, then we need to go deeper here. Please
* start `regedit.exe`
* navigate to `HKEY_CURRENT_USER\Software\HeidiSQL\Servers\DB consent log\`
* watch out for the value named `NetType`, which is probably really "255", but please post the value here
* **do not post any more values or your sensitive data here**

**Comment by gustaflindqvist** [comment]
Doh! That solved it for me. But I removed the `DB consent log` from Servers and didn't catch the `NetType` value. 🤦

**Comment by ansgarbecker** [comment]
Where exactly did you paste that "r2dbc" url? Did you perhaps create that session in the regisztry, outside HeidiSQL?

**Comment by gustaflindqvist** [comment]
> Where exactly did you paste that "r2dbc" url? Did you perhaps create that session in the regisztry, outside HeidiSQL?

No I didn't. It all went into the hostname field in the settings before I clicked ok to update HeidiSQL.

**Comment by ansgarbecker** [comment]
I don't know how to reproduce this, so I'll close it. Just shout if you get the error and know how to reproduce.
