### ISSUE TITLE
"Provider not found" on opening SQL Server connection through drop-down menu

### ISSUE THREAD

**Issue by moving-bits** [HeidiSQL/HeidiSQL#1010]
## Steps to reproduce this issue
I have several DB connections in connection manager, e. g.
- MariaDB server (127.0.0.1)
- MariaDB server (172.x.x.x)
- MS SQL server (hostname\instancename)
- MS SQL server (hostname)
- SQLite (local file name)

Each of them (except SQLite) with several databases, which show up in the left pane tree after opening the connection to the server.

## Current behavior
- When I open the MS SQL connection from the separate connection manager window, everything is fine,
- whereas when I open the MS SQL connection from the session manager button's submenu I get an error message:

![grafik](https://user-images.githubusercontent.com/3754370/80576573-b8e97a80-8a05-11ea-8eb0-a63b1849203e.png)

Mark: The error window title shows "127.0.0.1", although the connection I tried to open is not a local DB server. (But I do have a connection to my local MariaDB server open at that time, otherwise I would not have been able to use the session manager button.)

Opening connections from session manager submenu works for MariaDB servers, but not for MS SQL Server connections.

If I have several open connections, the error window above shows the currently active connection name (where the cursor was placed in the left pane when pressing the session manager button) in the window title.

## Expected behavior

Opening a SQL Server DB from a different server should either work using the session manager button or not being offered in case of technical constraints.

## Environment

- HeidiSQL 11.0.0.5968 running on Windows 10
- MariaDB (local + remote servers)
- SQL Server (remote)
- SQLite connections (local)

(Does HeidiSQL come with its own connection layer to SQL Server or do you need some version information provided by me for this?)

**Comment by ansgarbecker** [comment]
> whereas when I open the MS SQL connection from the session manager button's submenu I get an error message:

Please just describe which "button's submenu" you mean, probably with a screenshot

**Comment by moving-bits** [comment]
I'm talking about this button:

![grafik](https://user-images.githubusercontent.com/3754370/80583210-39ad7400-8a10-11ea-8c3e-db3952999fa0.png)

(left-most button in standard config, labelled "Sitzungs-Manager anzeigen")

I click on the little arrow-symbol, a list of configured connections opens, I select an MS SQL Server based on => error. Works if selecting an MariaDB / MySQL-based connection.

**Comment by ansgarbecker** [comment]
Ah I see.. Then there must be some difference in the back of that button.

**Comment by ansgarbecker** [comment]
@moving-bits could you please verify the issue persists with the latest build (6107)? I somehow cannot reproduce it here, with all kinds of variations in my SQL Server session. I cant recall I fixed something wrt this issue, but maybe it was magically fixed due to some related change.

**Comment by moving-bits** [comment]
@ansgarbecker Thanks for the follow-up.

I've updated to 11.0.0.6107 and rechecked today:

On opening the SQL-Server connection using the connection manager I get a warning about an outdated TLS version, but then the connection opens (and works):

![grafik](https://user-images.githubusercontent.com/3754370/97163548-1c6c1f00-1781-11eb-84b5-011637017845.png)

(BTW: Somewhat confusing that "127.0.0.1" is shown in the popup's title, although the server address for the SQL server connection is different. But I do have an active connection to a local MariaDB server.)

Whereas when I try to open the very same connection directly from within the main screen (see screenshot in https://github.com/HeidiSQL/HeidiSQL/issues/1010#issuecomment-621102655) I still receive the error message mentioned above:

![grafik](https://user-images.githubusercontent.com/3754370/97164038-d82d4e80-1781-11eb-83ca-20277cbd114e.png)

Not sure which driver it is using. The "ODBC-Datenquellen-Administrator" lists two entries for SQL-Server:
- ODBC Driver 17 for SQL Server (version 2017.176.01.01 / MSODBCSQL17.DLL 13.07.2020)
- SQL Server (version 10.00.18362.01 / SQLSRV32.DLL 19.03.2019)

(Both are listed for 32 bit ODBC and 64 bit ODBC)

Anything else I should check?

**Comment by ansgarbecker** [comment]
Thanks for double-checking. I managed to reproduce that, by deleting the registry session setting for "Library":

![grafik](https://user-images.githubusercontent.com/7986591/97216698-82c76080-17c6-11eb-9bb5-2f7c9c4b33b9.png)

This library settings is still quite new, and you likely did not save your HeidiSQL session since I added that setting. Now the dropdown menu on the session manager auto-selects the first one if your registry folder does not yet have that setting (SQLOLEDB). This way that worked when you used the session manager. The button-dropdown on the main window did not yet have such  a fallback, so it was using an empty string as the default library => that refers to "unbekannt" in the error.
Now I fixed that by setting the default to the newer, more secure library MSOLEDBSQL. You will probably get a connection error with that default after updating. Just select the other one in that case and you're done.

**Comment by ansgarbecker** [comment]
By the way, if you like some more fun with that library setting: there is a registry hack, so when you manually add a dword value in `HKEY_CURRENT_USER\Software\HeidiSQL` and set it to decimal/1, you will see all providers available on your system:
![grafik](https://user-images.githubusercontent.com/7986591/97217546-beaef580-17c7-11eb-9161-de68ce7dc62f.png)

**Comment by moving-bits** [comment]
Thanks for providing a fix. I'll recheck as soon as I'm back on that dev machine.

**Comment by lukinhaspm** [comment]
Theres some problem, miss all my session list!
@ansgarbecker 
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/5442163/bugreport.txt)

**Comment by lukinhaspm** [comment]
I can't create connections as well...
![image](https://user-images.githubusercontent.com/11230133/97241971-5cf38900-17d1-11eb-8a2b-2cb838e53f86.png)

**Comment by ansgarbecker** [comment]
Sorry, my fault! Should have just fixed this issue. Fixed build is just compiling, ready in 2 minutes for you to update. Note if you cannot do the update due to the crash, you can still download the latest build into your HeidiSQL directory.

**Comment by moving-bits** [comment]
Fix confirmed for both the original issue #1010 and the bug introduced by version 6107 trying to fix it.

> Now I fixed that by setting the default to the newer, more secure library MSOLEDBSQL. You will probably get a connection error with that default after updating. Just select the other one in that case and you're done.

No error occurred, it just worked :-)
Even though the reg key "Library" does not exist in `HKEY_CURRENT_USER\Software\HeidiSQL`. (Even not after having opened connections from connection manager as well as using the button-dropdown.)

Anyway, thanks @ansgarbecker for fixing this issue!

**Comment by lukinhaspm** [comment]
Thanks!
