### ISSUE TITLE
[Suggestion] Add support for remote SQLite db?

### ISSUE THREAD

**Issue by edwinyzh** [HeidiSQL/HeidiSQL#1018]
Is it possible to run HeidiSQL in local machine and edit a remote SQLite DB through something like SSH Tunnel?

That'll be a dream! :)

**Comment by ansgarbecker** [comment]
If you somehow make the SQLite database file accessible to HeidiSQL, I see no reason why that should not work. But an SSH tunnel is not the right thing here. You will need some SMB share on your Linux box, so you can access it from Windows through a network drive. Probably go through this: https://www.fosslinux.com/19265/how-to-share-and-transfer-files-between-linux-and-windows.htm

**Comment by edwinyzh** [comment]
The SQLite official site stated that accessing a SQLite db might corrupt it thus it should be avoid. I was thinking of the [remote db access ability provided by mORMot](http://blog.synopse.info/post/2014/11/18/HTTP-remote-access-for-SynDB-SQL-execution), does HeidiSQL architecture provide some kind of abstraction that allows one to add such a 'remote SQLite' support?

**Comment by ansgarbecker** [comment]
No, that would be an entire new approach to develop.

**Comment by edwinyzh** [comment]
I see, thanks!
