### ISSUE TITLE
Naming conflict of helpers.pas

### ISSUE THREAD

**Issue by tgoncuoglu** [HeidiSQL/HeidiSQL#102]
Currently there is a naming conflict of **helpers.pas** unit with **FMX.Canvas.GPU.Helpers** unit of FireMonkey. The result of this conflict is seen when you compile HeidiSQL in a recent version of Delphi, you will get the error: 

[dcc64 Fatal Error] F2092 Program or unit 'helpers' recursively uses itself

A simple fix is to rename the unit "helpers" to something else that will not conflict with a system unit, such as "heidi_helpers" or anything you see appropiate.

**Comment by ansgarbecker** [comment]
`apphelpers` is it now...
Should be ok for Tokyo, or?

**Comment by tgoncuoglu** [comment]
should be, but let me confirm please.

**Comment by tgoncuoglu** [comment]
yes, that works with tokyo. Thank you.
