### ISSUE TITLE
Columns dragged out of connection window disappear

### ISSUE THREAD

**Issue by deining** [HeidiSQL/HeidiSQL#1021]
## Steps to reproduce this issue

1. Open connection manager. Left windows show list of connection entries, columns are `Connection name`, `Host`, `Comment`, `Last connected`
2. You can rearrange these columns by dragging them around with the mouse. This can be considered a useful feature.
3. You can also drag these columns out of the window, which causes the columns to disappear. This way you might end up with an empty screen, though entries are present (but invisible now):

![image](https://user-images.githubusercontent.com/18169566/81302135-3fdbca00-907a-11ea-9144-ba87394ddaa0.png)

## Expected behavior

Dragging columns out of the window should be prohibited/should have no effect.

Edge case / minor issue, maybe this can be corrected with little effort.

**Comment by ansgarbecker** [comment]
This is not so minor as one could think, as it's quite tricky to get the columns back when all are hidden. Also, the issue was on most other trees/lists in the app as well. Fixed in the next build.
