### ISSUE TITLE
PostgreSQL - User manager syntax error

### ISSUE THREAD

**Issue by G3ph4z** [HeidiSQL/HeidiSQL#103]
## Expected behavior

Open dialog for editing the users

## Current behavior

Error messages

## Failure information (for bugs)

![image](https://user-images.githubusercontent.com/26697727/35247323-44bbd9cc-ffca-11e7-955c-7cd12ece931a.png)

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. Connect to Postgresql
2. Click to "manage users"

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.5.0.5196 (64bit)
* Database system + version: PostgreSQL 10.1
* Operating system: Windows 10 x64

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by ansgarbecker** [comment]
See issue #80

**Comment by id0612** [comment]
I am preparing to feedback this question, but I have already found it. I checked the relevant comments. Did not solve this problem well or optimize the experience.

I recommend two options:
1. Good support for compatibility;
2. Give a clear, friendly reminder if you don't support it. Don't let people think it's a mistake.

**Comment by ansgarbecker** [comment]
Please refer to issue #80 - I just pushed a change for it.
