### ISSUE TITLE
default collation

### ISSUE THREAD

**Issue by kriit24** [HeidiSQL/HeidiSQL#1030]
## Issue

1. when i create new table the default collation is latin_swedish_1, but db collation is utf8_general_ci;
2. [print screen](https://www.heidisql.com/uploads/36152-1-____2020-04-29_06h05_44.png);

## Environment

* **HeidiSQL version: 11.0.0.5969** 
  
* **Database system and version:10.2.30-MariaDB** 
  
* **Operating system:Linux 4.4.159-1 x86_64**

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.
