### ISSUE TITLE
MSSQL wrong server instance

### ISSUE THREAD

**Issue by KN4CK3R** [HeidiSQL/HeidiSQL#1032]
## Steps to reproduce this issue

I have created a connection like this:
![grafik](https://user-images.githubusercontent.com/1666336/81822003-e15b9380-9532-11ea-8f02-3964ea93fe93.png)

## Current behavior

The data I see with this connection is from a different server instance than the one I specified:
![grafik](https://user-images.githubusercontent.com/1666336/81822790-d6553300-9533-11ea-85ff-2ad336dbf793.png)

## Expected behavior

Here is the same query from Server Management Studio:
![grafik](https://user-images.githubusercontent.com/1666336/81822227-1d8ef400-9533-11ea-9550-fa8059d718ed.png)

## Environment

* **HeidiSQL version:** 11.0.0.5980
* **Database system and version:** SQL Server 13.0.5101.9

**Comment by ansgarbecker** [comment]
So there are multiple server instances on one server?

In case of MSSQL TCP/IP, the port is relevant, at least if it's not "0". You should verify it's the right one.

**Comment by KN4CK3R** [comment]
Thank you, the port was different for this instance. But how does the Management Studio find the correct port? Everything it needs is the `hostname\instance`:
![grafik](https://user-images.githubusercontent.com/1666336/81896294-a0a45e80-95b4-11ea-89e4-45883248b871.png)

**Comment by ansgarbecker** [comment]
Good question, I have no clue. We should probably ask someone at Microsoft :)

**Comment by KN4CK3R** [comment]
> TCP port 2382 is used for connection requests to a named instance of Analysis Services. Much like the SQL Server Browser service does for the relational database engine on UDP 1434, the SQL Server Browser listens on TCP 2382 for requests for Analysis Services named instances. Analysis Services then redirects the request to the appropriate port for the named instance.
(https://www.itprotoday.com/sql-server/sql-server-tcp-and-udp-ports)

https://docs.microsoft.com/en-us/sql/tools/configuration-manager/sql-server-browser-service

If you're bored... 😏

**Comment by ansgarbecker** [comment]
Ah that makes sense. But such effort just for the benefit to be able to leave the port away.. tss

**Comment by KN4CK3R** [comment]
I can't write Pascal code so here is a sample implementation in C#. It should be easy to understand:

```csharp
Dictionary<string, Dictionary<string, string>> GetInstances(string ip)
{
	using var socket = new Socket(SocketType.Dgram, ProtocolType.Udp);
	socket.Connect(ip, 1434);

	socket.Send(new byte[] { 3 });

	var buffer = new byte[16 * 1024 - 1];
	var length = socket.Receive(buffer);

	return ParseInstances(buffer[..length]);
}

Dictionary<string, Dictionary<string, string>> ParseInstances(ReadOnlySpan<byte> message)
{
	var result = new Dictionary<string, Dictionary<string, string>>();

	// \x05\x15\x01ServerName;<Server>;InstanceName;<Instance>;IsClustered;<Yes/No>;Version;<Version>;tcp;<Port>;;
	if (message.Length > 3 && message[0] == 5)
	{
		var str = Encoding.UTF8.GetString(message[3..]);

		var instanceMap = new Dictionary<string, string>();
		string name = null;
		foreach (var token in str.Split(';'))
		{
			if (name != null)
			{
				instanceMap.Add(name, token);
				name = null;
			}
			else
			{
				if (token.Length == 0)
				{
					if (instanceMap.Count == 0)
					{
						break;
					}

					result.Add(instanceMap["InstanceName"].ToUpper(), instanceMap);

					instanceMap = new Dictionary<string, string>();

					continue;
				}
				name = token;
			}
		}
	}

	return result;
}

var instances = GetInstances("asgard");
var port = instances["INSTANCE"]["tcp"];
```

Attached is the response the server sends (`socket.Receive(buffer)`):
[response.zip](https://github.com/HeidiSQL/HeidiSQL/files/4725781/response.zip)

Maybe you want to add this to Heidi. 👍
