### ISSUE TITLE
No longer a valid donor

### ISSUE THREAD

**Issue by spyke01** [HeidiSQL/HeidiSQL#1034]
## Steps to reproduce this issue

1. Step 1; Load app and select database to connect to
2. Step 2; Donate button appears at top right
3. Step 3; Go to Help->About
4. Step 4; Email address is still in the "I have donated..." box
5. Step 5; Click ok
6. Step 6; Receive popup that says "Not a valid donor email address"
7. Step 7; Click ok and then re-donate
8. Step 8; Attempt steps 1-5 and receive same error message as step 6

## Current behavior

Receiving error message that I am not a don't after two different donations. I also updated from the main build to the current nightly build and had the same result.

## Expected behavior

Email address should be accepted and the donation button disappear.

## Possible solution

If donations expire then this should be notated.

## Environment

* **HeidiSQL version:** 11.0 and 11.0.0.5980 (64-bit)
* **Operating system:** Windows 10 Version	10.0.18363 Build 18363

**Comment by ansgarbecker** [comment]
This is not a bug in HeidiSQL. The minimum donation has lately increased from 50ct to 1€ . The amount in your donation (summed) is between these values, so it was enough until some days ago, but now no longer.

**Comment by spyke01** [comment]
Thanks after donating 1€ the message went away.
