### ISSUE TITLE
Cannot show PostgreSQL schema info which contains large table with over 2,147,483,647 rows

### ISSUE THREAD

**Issue by kitora** [HeidiSQL/HeidiSQL#1038]
## Steps to reproduce this issue

1. Open PostgreSQL connection.
2. Select schema in left tree view.
3. Then I get error log in console view

## Current behavior

Printed error log like as
```
SELECT *, NULL AS data_length, relpages * 1024 AS index_length, c.reltuples, obj_description(c.oid) AS comment FROM "information_schema"."tables" AS t LEFT JOIN "pg_namespace" n ON t.table_schema = n.nspname LEFT JOIN "pg_class" c ON n.oid = c.relnamespace AND c.relname=t.table_name WHERE t."table_schema"='MySchemaName';
/* ERROR:  integer out of range */
```
## Expected behavior

With no error, tables are shown in tree view.

## Environment

* **HeidiSQL version:**  11.0.0.5985
  
* **Database system and version:** PostgreSQL 10 ( Ubuntu 10.13-1.pgdg18.04+1 )
  
* **Operating system:** Ubuntu 18.04 LTS

**Comment by ansgarbecker** [comment]
I suppose the "integer out of range" is generated by the server. Could you please fire the quoted query in a query tab and watch out if that returns the same error?

**Comment by ansgarbecker** [comment]
Already found a solution, casting `relpages` to `bigint` now. Please try the next build.

Related: https://www.heidisql.com/forum.php?t=17959

**Comment by ansgarbecker** [comment]
Is that working for you with the current build?
