### ISSUE TITLE
Load large file (directly) into MySQL 8.0.20 on Windows 10 aborts/hangs after 830M/860M of 8G

### ISSUE THREAD

**Issue by caugner** [HeidiSQL/HeidiSQL#1040]
## Steps to reproduce this issue

1. Connect to MySQL 8.0 (using `libmariadb.dll`, `libmysql.dll` or `libmysql-6.1.dll`)
2. Load a large file (`mysqldump` export) *directly* and wait

## Current behavior

HeidiSQL aborts the import (import window disappears, taskbar blinks) after 830M/860M and UI hangs (menu can still be opened and databases can still be selected, but the app doesn't close properly).

What I noticed: For `libmysql.dll` and `libmysql-6.1.dll` the partial database first showed up with a size of 832M and later (after killing the instance via the task manager) as 862M (`libmysql-6.1.dll`) or 872M (`libmariadb.dll`). For `libmariadb.dll` it was 832M before and after the "restart".

**Update**: Actually, half an hour later the `libmariadb.dll` import showed up as 884M.

## Expected behavior

HeidiSQL should load the file completely.

## Possible solution

(No idea, import via `mysql` on the command-line works without problems.)

## Environment

* **HeidiSQL version:** 11.0.0.5919 (64 Bit)
* **Database system and version:** MySQL 8.0.20
* **Operating system:** Windows 10 Pro 1909

**Comment by caugner** [comment]
@ansgarbecker Would it be possible to add `libmysql` 8.0 to the installer like in ae95c2f14ac8686ff24af10318c100a7c236bcf5?

**Comment by ansgarbecker** [comment]
If that helps here, yes. I just want to avoid providing a myriad of libraries of which the user does not know which one to select. But if it's named libmysql-8.0.dll, then why not.
I only have problems in finding the dlls ons their website. There seem to be only msi packages, no zips any more. And the msi packages only allow me to install either 32bit or 64bit, not both of them, even not after each other. Wtf?

**Comment by caugner** [comment]
> If that helps here, yes.

I'm actually not sure. I tried placing the `libmysql.dll` from my 8.0.20 installation in the HeidiSQL folder, but it won't allow me to connect (even though I don't have tls/certificates configured):
![grafik](https://user-images.githubusercontent.com/495429/82831886-e537d000-9eb9-11ea-9725-561bec00a2a9.png)

When I enable "Enable plaintext authentification", HeidiSQL even crashes right away upon connecting.

> I only have problems in finding the dlls ons their website.

You can find a DLL in the "Windows (x86, 64-bit), ZIP Archive" on https://dev.mysql.com/downloads/mysql/, which should work for 32bit and 64bit I guess?

**Comment by ansgarbecker** [comment]
To return to you initial issue: you compared the size of the database for verifying whether it's complete. Don't do that. Run a `SELECT COUNT(*) FROM ...` for the relevant tables instead. Maybe it was just the progress dialog which was brokenly staying on top. Maybe the row count in your table was correct?

**Comment by caugner** [comment]
I have now monitored the import with `SHOW PROCESSLIST`. As soon as the dialog disappears and (HeidiSQL starts hanging) the corresponding mysql connection is continuously sleeping (for 20 seconds).

According to `SHOW TABLES`, only the first couple of tables exist. `SELECT COUNT(*)` does not finish on the newest table. It seems to stil be locked/in use by HeidiSQL, as confirmed by `SHOW OPEN TABLES WHERE In_use > 0`.

Any ideas? Can I make HeidiSQL be more verbose about what it's doing somehow?

**Comment by ansgarbecker** [comment]
Verbose about what?
That `SELECT COUNT(*)` takes some time? Or it never finishes?

**Comment by caugner** [comment]
> Verbose about what?

About why it closes the progress dialog. I was thinking of a debug mode or similar.

> That SELECT COUNT(*) takes some time? Or it never finishes?

It never finishes. Still not now. (Have kept HeidiSQL running since earlier.)

**Comment by ansgarbecker** [comment]
Recently I enhanced the load/run files logic, especially for multiple files. And added some more messages to the log panel about what happened. So you should update to the latest build. Please retry the import again and tell if that helps for the issue here (aborts/hangs after x MB).

**Comment by caugner** [comment]
Thank you, indeed I'm getting an error message now:

![grafik](https://user-images.githubusercontent.com/495429/84679697-e8aafe00-af31-11ea-960e-280967deda7a.png)

I wonder though why the `mysql` binary is able to import the same file without problems.

**Comment by ansgarbecker** [comment]
In that case let's go on in #1048 , which is quite new and needs a sample file anyway. And it's about exactly that error.
