### ISSUE TITLE
Filtering capabilities on: Host - Processess

### ISSUE THREAD

**Issue by eRadical** [HeidiSQL/HeidiSQL#1041]
## Feature request

1. Host
2. Processess

## Current behavior
There are no filtering capabilities in this tab.

## Expected behavior
It would be nice to have some filtering capabilities here:
- possibility to hide connections in „Sleep” state - this would be a big plus
- possibility to filter by DB, User, optionally Host
- possibility to search in Info...

## Environment
Fedora [latest] - through Wine

* **HeidiSQL version:** 
11.0

**Comment by ansgarbecker** [comment]
You probably have not yet enabled the bottom filter box:

![grafik](https://user-images.githubusercontent.com/7986591/82933099-b8eb8480-9f89-11ea-9497-fa300256eb8f.png)

You can activate it in Edit > Filter panel.

**Comment by eRadical** [comment]
This is awesome.

This app never ceases to amaze me!
