### ISSUE TITLE
Can't connect to SqlServer , is working on old version of heidi

### ISSUE THREAD

**Issue by jairgza** [HeidiSQL/HeidiSQL#1044]
Hi
I just updated heidi 9.5 to the latest build 11,  and cannot connect to sql server

1.- Download latest  heidi 11, start with a fresh install
2.- Just add a new session Microsoft SQL Server (named pipes) using localhost\SQLExpress with  "sa" and password
3.- Try to open

I get an error dialog:
![errordialog](https://user-images.githubusercontent.com/14021653/83293021-bc148980-a1b0-11ea-84a0-6cf406543465.png)

I try with user authentication and tcp protocol, different combinations.
Try heidi night build too.

The same configuration works on heidi 9.5 
I'm on windows 10 
SqlExpress 2014

thanks  :)

**Comment by ansgarbecker** [comment]
Most important seems to be the selected provider/library.

**Comment by jairgza** [comment]
With MSOLEDB have the error;
with SQLOLEDB  have a security warning recommending download oledb driver (which I already have),  but I can connect anyway ,  so for me it's ok  :)

I noticed that these issues were discussed in this thread:
https://github.com/HeidiSQL/HeidiSQL/issues/237
https://github.com/HeidiSQL/HeidiSQL/issues/587
