### ISSUE TITLE
EXCLUIR UMA TABELA DIRETAMENTE NO HeidiSql

### ISSUE THREAD

**Issue by Maia1949** [HeidiSQL/HeidiSQL#1046]
## Steps to reproduce this issue

1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by Maia1949** [comment]
Quando exclui uma tabela diretamente no HeidiSql, o banco de dados é recolhido, precisando fechar o HeidiSql e abri-lo de novo para verificar tal exclusão.

Outro problema é que, quando inclui uma tabela, esta só aparece no HeidiSql, se fecha-lo e abri-lo novamente.

Obrigado e Abraço!!!

**Comment by Maia1949** [comment]
Retificando um erro na mensagem enviada anteriormente, que é o seguinte:

Quando exclui uma tabela diretamente no HeidiSql, o banco de dados é recolhido e é necessário  fecha-lo e abri-lo novamente, para aparecer tal tabela.

Outro problema é que, quando inclui uma tabela, esta só aparece no HeidiSql, se fecha-lo e abri-lo, também novamente.

Obrigado e Abraço !!!

**Comment by lukinhaspm** [comment]
After you delete, select de database and click in REFRESH (double green
arrows) ... done

Lucas Augusto Milanes
Skype: Lucas Augusto Milanes
Cel:     +55 (11) 98160-3130


Em ter., 2 de jun. de 2020 às 12:42, Maia1949 <notifications@github.com>
escreveu:

**Comment by Maia1949** [comment]
Olá. Boa tarde! Já tentei, mas não atualiza. Ok?

**Comment by lukinhaspm** [comment]
I recommend you:
- Follow the template to open an issue
and
- Write in english
How you closed the issue, everybody think it's OK now
OK?

**Comment by Maia1949** [comment]
Lucas. Obrigado por entrar em contato comigo.
É a primeira vez que uso, mas já fiz o que você recomendou, que clicar em atualizar e não atualiza, quando é os problemas que tanscrevi.

**Comment by Maia1949** [comment]
que uso, retificando o erro.
