### ISSUE TITLE
Protocol mismatch; server version = 11, client version = 10

### ISSUE THREAD

**Issue by sunnyphp** [HeidiSQL/HeidiSQL#1049]
## Steps to reproduce this issue

1. Try to connect
4. Then I get error

## Current behavior

Error using library `libmariadb.dll`: Empty (no text)
Error using library `libmysql-6.1.dll`: Protocol mismatch; server version = 11, client version = 10
Error using library `libmysql.dll`: Protocol mismatch; server version = 11, client version = 10

## Expected behavior

Successful connection

## Possible solution

Update mysql client library

## Environment

* **HeidiSQL version:** 
Latest from official site:
`Version 11.0.0.5919 (64 Bit), Build date: 2020-03-17 17:05:04`
And then updated to nightly build:
`Version 11.0.0.5994 (64 Bit), Build date: 2020-06-04 05:55:27`

* **Database system and version:** 
MySQL Docker image (latest from https://hub.docker.com/_/mysql):
`mysql  Ver 8.0.20 for Linux on x86_64 (MySQL Community Server - GPL)`

* **Operating system:** 
`Windows 7 Ultimate edition, 64 bit` on client
Arch `Linux 698bddd75505 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux` on host

**Comment by ansgarbecker** [comment]
Could you please download the latest built "32+64 bit installer", from the [nightly builds section](https://www.heidisql.com/download.php#nightlybuilds), so you not only get an updated heidisql.exe but also updated dlls.

**Comment by sunnyphp** [comment]
Download and install nightly build - nothing changes.

**Comment by sunnyphp** [comment]
Ports was configured wrong. I'm trying connect to X protocol on port 33060:
https://dev.mysql.com/doc/mysql-port-reference/en/mysql-ports-reference-tables.html
Sorry for disturbing.

**Comment by ansgarbecker** [comment]
Hehe, glad to have that fixed.

**Comment by francoataffarel** [comment]
> Ports was configured wrong. I'm trying connect to X protocol on port 33060: https://dev.mysql.com/doc/mysql-port-reference/en/mysql-ports-reference-tables.html Sorry for disturbing.

how you resolve this ?
