### ISSUE TITLE
materialized view in PostgreSQL not visible

### ISSUE THREAD

**Issue by wschoonveld** [HeidiSQL/HeidiSQL#105]
## Expected behavior

Materialized views in PostgreSQL are not visible in the object tree on the left side. It is also not a recognized object type in the tree.

## Current behavior

Materialized views can be queried on a Postgres database and will give the expected results, but the object is not shown in the tree.

## Failure information (for bugs)

Using this query the materialized views can be shown from the system tables:
SELECT n.nspname as "Schema",  c.relname as "Name", c.relkind
FROM pg_catalog.pg_class c
LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
 WHERE c.relkind IN ('m')

**Comment by ansgarbecker** [comment]
See #40
