### ISSUE TITLE
Foreign key disappeared in mysql 4.1

### ISSUE THREAD

**Issue by marcodiell** [HeidiSQL/HeidiSQL#1050]
Version 11.0.0.5595 
Foreign key disappeared in mysql 4.1
![image](https://user-images.githubusercontent.com/66488211/83907142-4756c780-a73b-11ea-8df5-fbb470216a89.png)

Using an old version they appear normally
![image](https://user-images.githubusercontent.com/66488211/83907325-9bfa4280-a73b-11ea-9e33-5a164a15cb52.png)

**Comment by ansgarbecker** [comment]
What's the old version number?
And please ensure you use the latest build.

**Comment by marcodiell** [comment]
What's the old version number?
**Latest version before 2020 example V10.2.0.5599 is ok**

And please ensure you use the latest build.
**Latest build Foreign key disappeared in mysql 4.1**

**Comment by lukinhaspm** [comment]
try to update...

[image: image.png]

Lucas Augusto Milanes
Skype: Lucas Augusto Milanes
Cel:     +55 (11) 98160-3130


Em sex., 5 de jun. de 2020 às 15:37, marcodiell <notifications@github.com>
escreveu:

**Comment by marcodiell** [comment]
as mentioned, is updated. Only in old versions they work.

**Comment by ansgarbecker** [comment]
@marcodiell please just tell us the HeidiSQL build you used when you mentioned "latest build". It should be 6000 or greater.

**Comment by marcodiell** [comment]
@ansgarbecker

![image](https://user-images.githubusercontent.com/66488211/84928156-54ad7380-b0a4-11ea-85c9-257b83634236.png)

**Comment by ansgarbecker** [comment]
Ok, so the current builds with my new implementation foreign keys no longer show foreign keys on MySQL 4.1. I'm afraid support for such old servers is very limited, and there are plenty of issues to solve for newer servers. Please use an older HeidiSQL version if you still want to work with foreign keys on MySQL 4.1. Or upgrade your MySQL server.
