### ISSUE TITLE
Icons disappeared in v.5999

### ISSUE THREAD

**Issue by budiony** [HeidiSQL/HeidiSQL#1052]
## Steps to reproduce this issue

1. Install the update  5999
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4742435/bugreport.txt)
![explorer_QVQtsvIy1V](https://user-images.githubusercontent.com/8297417/83974132-a19a8880-a8f3-11ea-93ac-fe2e5ce1b52b.png)

2. Start HeidiSQL

4. Icons not present anymore, attempt to load different set (Silk, or Icons8) produces error

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by budiony** [comment]
One more thing, using style theme "Windows", not Windows10.

**Comment by ansgarbecker** [comment]
Please update to the next build (available in a few minutes). For me that fixed the removed icons.

**Comment by budiony** [comment]
I confirm that in build 6002 the issue is resolved. Thank you for your quick response.
