### ISSUE TITLE
SQLite crash while listing large table

### ISSUE THREAD

**Issue by DavidG-Aus** [HeidiSQL/HeidiSQL#1053]
1. Step 1;  Open SQLite database (local disk)
2. Step 2; Select table with >2000 records (my case 14,000)
3. Step N; Select 'Show All'
     Search for some text
4. Then I get...  a crash.

## Environment

Windows 10 Home. 

* **HeidiSQL version:** 
  

Latest - downloaded today.

* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
Please attach the crash report here. (click "save bugreport")

**Comment by DavidG-Aus** [comment]
What is shown above is only a small part of what I entered - doesn't include exception report. Is the detail visible to you?
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4750378/bugreport.txt)

**Comment by ansgarbecker** [comment]
Yes, thanks. I suppose the search/replace logic is causing this. Is that reproducible each time you access that table?

Pasting from crash report:
```
version            : 11.0.0.6002
exception number   : 1
exception class    : EArgumentOutOfRangeException
exception message  : Argument out of range.

main thread ($3b48):
00b56127 heidisql.exe dbconnection    7356  +5 TSQLiteQuery.Col
00b58776 heidisql.exe dbconnection    7915  +8 TDBQuery.HasFullData
00b58144 heidisql.exe dbconnection    7873  +3 TDBQuery.EnsureFullRow
00e4962d heidisql.exe Main            5245  +7 TMainForm.AnyGridEnsureFullRow
00ce00de heidisql.exe searchreplace    393 +53 TfrmSearchReplace.DoSearchReplaceData
00cdf74f heidisql.exe searchreplace    288 +22 TfrmSearchReplace.DoSearchReplace
006cd6d1 heidisql.exe Vcl.Controls             TControl.Click
```

**Comment by DavidG-Aus** [comment]
Yes 100% repeatable but not only on search. If I just scroll down in the same table I get a crash too but not sure if that is 100% repeatable.

**Comment by ansgarbecker** [comment]
Ok, thanks for the really quick feedback. I'll go through this and try to find a fix.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build. Please verify.
