### ISSUE TITLE
Combinated installer (32/64 bit) seems to be a 64 bit application

### ISSUE THREAD

**Issue by jmar83** [HeidiSQL/HeidiSQL#1056]
I tested it on a 32 bit system:

![](https://i.ibb.co/y01bMS5/Unbenannt.jpg)

I think a 32/64 bit installer should be compiled in 32 bit, but later it should decide if it install

a.) 32 bit version on 32 bit system

AND

b.) 64 bit version on 64 bit system

For example, i think the combinated installer for M$ Win10 does the same: It always starts in 32 bit mode for compatibility for both platforms 32 and 64 bits...

Regards, Jan

**Comment by ansgarbecker** [comment]
No, the installer is a 32bit executable. According to your screenshot, I guess you are running in on some older Windows than the supported Win7, 8 and 10?

**Comment by jmar83** [comment]
Yes its and old windows server 2003 32bit... i understand it that i will not run with it, but that message is a lil bit confusing...
