### ISSUE TITLE
11.0 is not High DPI aware, 10.1 is?

### ISSUE THREAD

**Issue by raelb** [HeidiSQL/HeidiSQL#1058]
Hello,
I was using the 10.1 x64 portable version, and it was High DPI aware, i.e. showing crisp fonts:
![image](https://user-images.githubusercontent.com/13108198/84598992-09f6e600-ae6f-11ea-8e6c-b004aaf42656.png)

I just downloaded the HeidiSQL_11.0_64_Portable.zip version, and it is not High DPI aware, i.e. it does not show crisp fonts, and slightly blurred text:
![image](https://user-images.githubusercontent.com/13108198/84599022-41659280-ae6f-11ea-81ce-31d4559b00bb.png)

I got the same result (blurry text) using the latest nightly build. (heidisql64.r6008.exe)

Is this something you are aware of?

* **Operating system:** 
Windows 10 x64, Windows Scaling at 150%

**Comment by ansgarbecker** [comment]
Yes, I am very aware of that. I gave up supporting high DPI settings, due to many new issues that introduced. See https://github.com/HeidiSQL/HeidiSQL/issues?q=label%3Ahigh-dpi
