### ISSUE TITLE
Download older versions of portable install?

### ISSUE THREAD

**Issue by raelb** [HeidiSQL/HeidiSQL#1059]
Hello,
Is it possible to download an older version of the portable installer?
I'm wanting 10.3 x64
Thanks

**Comment by ansgarbecker** [comment]
Previous packages mostly follow the same naming convention, so you can get it here:
https://www.heidisql.com/downloads/releases/HeidiSQL_10.3_64_Portable.zip
I don't think I should provide links on the download page, as that would blow up the page with normally unrelated links.

**Comment by raelb** [comment]
That's perfect, thanks

**Comment by ansgarbecker** [comment]
I have the impression the portable releases are mostly or widely used by Wine and/or Mac users. Could that be true? I am asking because these users often don't have the alternative to use the installer, as that probably does not run.

**Comment by raelb** [comment]
Oh, in my case I am on Windows, I was trying to locate which was last version that had high DPI support. I didn't think to look at release history, or know if it was mentioned. Now, I see that is was mentioned.
If there is an option, I sometimes will try the portable version before committing to an installed version.

**Comment by ansgarbecker** [comment]
Ah I see. I just modified the download page, added links to previous portable files, under the "Previous releases" link.
