### ISSUE TITLE
Non-recoverable crash possibly due to "Application language" setting, SynTextDrawer/SynEdit

### ISSUE THREAD

**Issue by lieszkol** [HeidiSQL/HeidiSQL#106]
## Expected behavior
Application doesn't crash

## Current behavior
Every few minutes HeidiSQL error screen comes up and Heidi crashes. 

## Failure information (for bugs)
This seems to be related to the "Application language" setting. I don't get the bug if it is set to "English". If it is set to "Auto detect", then every few minutes Heidi loses the connection to the database, tries to reconnect a few times (unsuccessfully), and then crashes (three times the error window is displayed, and after the last window is shown there is no option to continue).
Seems to happen more often if I'm connected through SSH.

### Steps to reproduce
Open HeidiSQl, do some work, and there it goes...

### Context
[bugreport0126_1.txt](https://github.com/HeidiSQL/HeidiSQL/files/1667483/bugreport0126_1.txt)

Windows 7 64 bit with format set to "English (United States) BUT location is set to "Hungary"

* HeidiSQL version:9.5.0.5226
* Database system + version: MySQL 5.7, MariaDB 10.2
* Operating system: Win 7 64 bit

### Failure Logs
Tail of Heidi log always shows reconnection attempt:
/* 2018-01-26 11:00:07 [Mana Node11 SSH] */ /* Closing plink.exe process #19944 ... */
/* 2018-01-26 11:00:07 [Mana Node11 SSH] */ /* Connection to localhost closed at 2018-01-26 11:00:07 */
/* 2018-01-26 11:00:07 [Mana Node11 SSH] */ /* Connecting to localhost via MariaDB (SSH tunnel), username laci, using password: Yes ... */
/* 2018-01-26 11:00:08 [Mana Node11 SSH] */ /* Attempt to create plink.exe process, waiting 4s for response ... */
/* 2018-01-26 11:00:08 [Mana Node11 SSH] */ /* C:\Program Files (x86)\PuTTY\plink.exe -ssh laci@172.104.28.14 -P 22 -i "B:\ProductsLocal\ManaEnergy\ssh\laci-private-key.ppk" -N -L 3309:localhost:3306 */
/* 2018-01-26 11:00:13 [Mana Node11 SSH] */ /* Connected. Thread-ID: 12 */
/* 2018-01-26 11:00:14 [Mana

###
/* 2018-01-26 10:40:11 [Mana Node11 SSH] */ /* SQL Error (2013): Lost connection to MySQL server during query */
/* 2018-01-26 10:40:11 [Mana Node11 SSH] */ /* Closing plink.exe process #5236 ... */
/* 2018-01-26 10:40:11 [Mana Node11 SSH] */ /* Connection to localhost closed at 2018-01-26 10:40:11 */
/* 2018-01-26 10:40:11 [Mana Node11 SSH] */ /* Connecting to localhost via MariaDB (SSH tunnel), username laci, using password: Yes ... */
/* 2018-01-26 10:40:12 [Mana Node11 SSH] */ /* Attempt to create plink.exe process, waiting 4s for response ... */
/* 2018-01-26 10:40:12 [Mana Node11 SSH] */ /* C:\Program Files (x86)\PuTTY\plink.exe -ssh laci@172.104.28.14 -P 22 -i "B:\ProductsLocal\ManaEnergy\ssh\laci-private-key.ppk" -N -L 3307:localhost:3306 */
/* 2018-01-26 10:40:16 [Mana Node11 SSH] */ /* SQL Error (2013): Lost connection to MySQL server at 'reading initial communication packet', system error: 0 */
/* 2018-01-26 10:40:17 [Mana Node11 SSH] */ /* Closing plink.exe process #17508 ... */
/* 2018-01-26 10:40:17 [Mana Node11 SSH] */ /* Connecting to localhost via MariaDB (SSH tunnel), username laci, using password: Yes ... */
/* 2018-01-26 10:40:18 [Mana Node11 SSH] */ /* Attempt to create plink.exe process, waiting 4s for response ... */
/* 2018-01-26 10:40:18 [Mana Node11 SSH] */ /* C:\Program Files (x86)\PuTTY\plink.exe -ssh laci@172.104.28.14 -P 22 -i "B:\ProductsLocal\ManaEnergy\ssh\laci-private-key.ppk" -N -L 3307:localhost:3306 */
/* 2018-01-26 10:40:23 [Mana Node11 SSH] */ /* Connected. Thread-ID: 9 */
/* 2018-01-26 10:40:23 [Mana Node11 SSH] */ /* Characterset: utf8mb4 */

####
/* 2018-01-26 10:45:27 [Mana Node11 SSH] */ /* Closing plink.exe process #21696 ... */
/* 2018-01-26 10:45:27 [Mana Node11 SSH] */ /* Connection to localhost closed at 2018-01-26 10:45:27 */
/* 2018-01-26 10:45:27 [Mana Node11 SSH] */ /* Connecting to localhost via MariaDB (SSH tunnel), username laci, using password: Yes ... */
/* 2018-01-26 10:45:28 [Mana Node11 SSH] */ /* Attempt to create plink.exe process, waiting 4s for response ... */
/* 2018-01-26 10:45:28 [Mana Node11 SSH] */ /* C:\Program Files (x86)\PuTTY\plink.exe -ssh laci@172.104.28.14 -P 22 -i "B:\ProductsLocal\ManaEnergy\ssh\laci-private-key.ppk" -N -L 3308:localhost:3306 */
/* 2018-01-26 10:45:33 [Mana Node11 SSH] 

Please include any relevant log snippets or files here.

**Comment by ansgarbecker** [comment]
Same as issue #48 - I'll reopen that one again.

**Comment by lieszkol** [comment]
Yes I wan't sure. Thank you so much! This has been frustrating me ever since I've started using Heidi. I'm just glad there's a solution/work-around :-)

I think it's worth investigating because other people might be having the same issue and, like me, it may take them a long time to figure it out.
