### ISSUE TITLE
Is there table structure comparison and synchronization and data synchronization?

### ISSUE THREAD

**Issue by yuwenlong** [HeidiSQL/HeidiSQL#1063]
Is there table structure comparison and synchronization and data synchronization?

**Comment by ansgarbecker** [comment]
You can use the SQL export to synchronize two databases, or two servers. Like described in the [help document](https://www.heidisql.com/help.php#sqlexport). Please ask questions in the forum, this is an issue tracker, for bug reports and feature requests. You may have noticed that while you deleted the issue template.
