### ISSUE TITLE
Quick Filter - filtering on NULL values broke

### ISSUE THREAD

**Issue by thadin** [HeidiSQL/HeidiSQL#1065]
## Steps to reproduce this issue
1. Right click in a data grid
2. Select Quick Filter
3. Select in the middle section (that generally requires input) either IS NULL or IS NOT NULL

## Current behavior
Since a few updates back, these filter options require me to enter an input. Regardless of what input I give, nothing happens.

## Expected behavior
The selected quick filter IS (NOT) NULL being applied to the column you right clicked on, without asking me for an input.

## Environment

* **HeidiSQL version:** 11.0.0.6013 (64 Bit)
* **Database system and version:** MySQL 5.7.29
* **Operating system:** Windows 10 (1903)

I'm using the dark Material theme.

**Comment by ansgarbecker** [comment]
Related to #444, for which I seem to have broken these both NULL filters.

**Comment by yphastos** [comment]
Sorry to post into a closed bug but I think is a minor issue not needing a new bug.

In my opinion, in the quick filter options, the icons in `IS NULL` and `IS NOT NULL` options should be interchanged: 

![image](https://user-images.githubusercontent.com/13773388/87097067-e7f04980-c209-11ea-81a3-8a349488930f.png)

`IS NULL` should be the dashed circle as in an empty field
and `IS NOT NULL` should be the solid line circle, as in having content.

also, the last option with a red cross is empty and thus confusing, it should say something like 'clear filters'

![image](https://user-images.githubusercontent.com/13773388/87097418-d2c7ea80-c20a-11ea-80e8-3ec717e29e9e.png)

**Comment by ansgarbecker** [comment]
Confirmed - and just fixed both of these.
