### ISSUE TITLE
The column view and the create script always show the COLLATE value

### ISSUE THREAD

**Issue by yokesnowwolf** [HeidiSQL/HeidiSQL#1069]
## Steps to reproduce this issue

1. connect to any database and double click any table that has the varchar type column;
2. view the colums grid you will see the COLLATE column always show the value with varchar type column;
3. click the "create code", view the script, it's the same;

## Current behavior

All the varchar type column show the COLLATE values in the colum grid view and create script.

## Expected behavior

The old version will show with blank when the column COLLATE value is same as the schema.
I haven't upgraded the version for too long. The show is this part of the upgrade plan?

## Environment

* **HeidiSQL version:** 
  
11.0.0.5919 and 11.0.0.6013

* **Database system and version:** 
  
mysql 5.7.26-log and 8.0.16

**Comment by ansgarbecker** [comment]
You aren't reporting a bug here, this is just a harmless difference to previous versions.

If I am missing something here, and there is a real bug, the please explain.
