### ISSUE TITLE
slow string column sorting

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#107]
hey @ansgarbecker,

first, huge thanks for writing and maintaining HeidiSQL, it is excellent and i donate periodically :)

i noticed that sorting by a VARCHAR column in the data grid is rather slow compared to sorting by an INT or DATE column. for just 13000 rows it feels like ~500ms vs instantaneous for the other data types. is this something that can be further optimized by using a better algo?

running build 5226 on Windows 10

thanks!

**Comment by ansgarbecker** [comment]
In the data grid, the sorting is done by adding an `ORDER BY youcolumn` clause to the internal `SELECT` command.

Is it that query that you want to be optimized, or...?

**Comment by leeoniya** [comment]
sorry, i didn't realize this simply used the DB's ORDER BY. should have looked more carefully.

**Comment by ansgarbecker** [comment]
No problem. I hope this is not too confusing, as the other grids mostly use an internal string comparison.
