### ISSUE TITLE
Support TIMESTAMP WITH/WITHOUT TIMEZONE column types

### ISSUE THREAD

**Issue by fushihara** [HeidiSQL/HeidiSQL#1071]
## Steps to reproduce this issue

Timestamp type with timezone is displayed as timestamp without timezone in table column screen and creation script

1. Step 1;create any table column of "timestamp with time zone" and "timestamp without time zone" with postgresql
↓pgadmin4
![image](https://user-images.githubusercontent.com/1039534/85607699-53291000-b68f-11ea-8dd9-9cb960910890.png)

2. display only "timestamp without time zone"
![image](https://user-images.githubusercontent.com/1039534/85607723-591ef100-b68f-11ea-85e0-75e15b5743b4.png)

3 sql export script only "timestamp without time zone"

```
-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
-- Server OS:                    
-- HeidiSQL Version:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table public.test-table
DROP TABLE IF EXISTS "test-table";
CREATE TABLE IF NOT EXISTS "test-table" (
	"id" INTEGER NULL DEFAULT NULL,
	"without time zone" TIMESTAMP NULL DEFAULT NULL,
	"with time zone" TIMESTAMP NULL DEFAULT NULL
);

-- Dumping data for table public.test-table: 0 rows
DELETE FROM "test-table";
/*!40000 ALTER TABLE "test-table" DISABLE KEYS */;
/*!40000 ALTER TABLE "test-table" ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

```

![image](https://user-images.githubusercontent.com/1039534/85607967-95525180-b68f-11ea-88ff-85c367224d41.png)

HeidiSQL version：Version 11.0.0.5919 (64 Bit)

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
Please verify that issue with the latest build.

**Comment by fushihara** [comment]
I'm sorry, I confirmed that there is no change in the situation with the latest version.
![image](https://user-images.githubusercontent.com/1039534/85922351-8355f600-b8bd-11ea-924d-d07cca99b599.png)
