### ISSUE TITLE
In the postgresql, when the quick filter is used for a column with capital letters, the SQL part is incorrect

### ISSUE THREAD

**Issue by fushihara** [HeidiSQL/HeidiSQL#1072]
## Steps to reproduce this issue

1. Step 1;create "Test" column any database at postgresql
![image](https://user-images.githubusercontent.com/1039534/85609954-85d40800-b691-11ea-8a37-1ba80ed9a497.png)

2. Step 2;select data tab, open context menu -> quick filter 「Test in 'a'」
![image](https://user-images.githubusercontent.com/1039534/85609971-89678f00-b691-11ea-91d6-0809e8b8bd23.png)

3. Step N; column "test" does not  exist error.
![image](https://user-images.githubusercontent.com/1039534/85609992-8d93ac80-b691-11ea-9676-c744c52f747d.png)

Just as the table name is enclosed in double quotes from the beginning, I want the column names to be enclosed in double quotes as well.
The solution is written in the hint, is there a disadvantage to doing this?

## Environment

* **HeidiSQL version:** Version 11.0.0.5919 (64 Bit)
  
* **Database system and version:** ostgreSQL 12.3 
  
* **Operating system:** Windows 10 pro 64bit . version 1903 build 18362.418

**Comment by ansgarbecker** [comment]
So PostgreSQL complaints about a wrong written column name when I write it correct?

Same thing here: please verify with the latest HeidiSQL build first.

**Comment by fushihara** [comment]
According to the official postgresql documentation, identifiers not enclosed in double quotes are converted to lower case.
https://www.postgresql.org/docs/current/sql-syntax-lexical.html#:~:text=always%20folded%20to%20lower%20case
＞ Quoting an identifier also makes it case-sensitive, whereas unquoted names are always folded to lower case.

In the example image, I am searching for a Test column that starts with an uppercase letter, but in fact I am searching for a lowercased test column
![image](https://user-images.githubusercontent.com/1039534/85922418-fe1f1100-b8bd-11ea-89f8-f40c14766566.png)

If you search Test with a query enclosed in double quotes, the Test column that starts with correct capital letters will be searched
![image](https://user-images.githubusercontent.com/1039534/85922641-f7919900-b8bf-11ea-8b48-1ccea590feee.png)

**Comment by ansgarbecker** [comment]
Fixed in the next build.
