### ISSUE TITLE
Add column and table comments in SQL export

### ISSUE THREAD

**Issue by fushihara** [HeidiSQL/HeidiSQL#1073]
## Steps to reproduce this issue

1. Set comments on database tables and columns.This time I am using postgresql
![image](https://user-images.githubusercontent.com/1039534/85612592-fda33200-b693-11ea-8a76-312e7946fb0b.png)
![image](https://user-images.githubusercontent.com/1039534/85612602-00058c00-b694-11ea-81e1-6006973a5d7d.png)

2. sql export this table.
![image](https://user-images.githubusercontent.com/1039534/85612650-0b58b780-b694-11ea-93cb-35c63f89c0a0.png)

3. No comments are included in the exported sql minutes
```
-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
-- Server OS:                    
-- HeidiSQL Version:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table public.test-table
CREATE TABLE IF NOT EXISTS "test-table" (
	"id" INTEGER NULL DEFAULT NULL,
	"without time zone" TIMESTAMP NULL DEFAULT NULL,
	"with time zone" TIMESTAMP NULL DEFAULT NULL,
	"Test" VARCHAR NULL DEFAULT NULL,
	INDEX "test-table_id_idx" ("id")
);

-- Data exporting was unselected.

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

```

## Current behavior
I tried various combinations of output data and options, but no comments were output.

## Expected behavior
A comment creation command is added to the output SQL

## Possible solution
Function addition

## Environment

* **HeidiSQL version:** Version 11.0.0.5919 (64 Bit)
  
* **Database system and version:** postgreSQL 12.3
  
* **Operating system:** Windows 10 pro 64bit . version 1903 build 18362.418

**Comment by ansgarbecker** [comment]
Please verify with the latest build of HeidiSQL.

**Comment by fushihara** [comment]
sorry. I have confirmed that it will be reproduced with the latest version of the build.
![image](https://user-images.githubusercontent.com/1039534/85922715-6cfd6980-b8c0-11ea-8701-0f54b59f26f6.png)
![image](https://user-images.githubusercontent.com/1039534/85922719-6ec72d00-b8c0-11ea-8523-ba7abc24f900.png)

```sql
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

CREATE TABLE IF NOT EXISTS "test-table" (
	"id" INTEGER NULL DEFAULT NULL,
	"without time zone" TIMESTAMP NULL DEFAULT NULL,
	"with time zone" TIMESTAMP NULL DEFAULT NULL,
	"Test" VARCHAR NULL DEFAULT NULL,
	"test" VARCHAR NULL DEFAULT NULL,
	INDEX "test-table_id_idx" ("id")
);

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

```

**Comment by ansgarbecker** [comment]
Related: #859

**Comment by ansgarbecker** [comment]
Let's gather these export issues for PostgreSQL in #1100 . Missing comments are just one issue of many I'm afraid.
