### ISSUE TITLE
Session Manager needs scrollbars

### ISSUE THREAD

**Issue by Germs2004** [HeidiSQL/HeidiSQL#1074]
## Steps to reproduce this issue

1. Open HeidiSQL.  You should see the Session Manager.
2. Shrink the Session Manager window to its smallest size.
3. Select "PostgreSQL (TCP/IP)"
4. Notice that you do not see the "Database" or "Comments" box, and there's no clue that any GUI elements are hidden.  If you fail to select a database on this screen and click Connect, you'll connect to the PostgreSQL instance but see no databases, making you think HeidiSQL is broken.  There needs to be scrollbars on the Session Manager window that appear any time there are off-screen elements, and also, you may want to change the minimum allowable size of the window so that it cannot possibly hide critical fields like the "database" field.

## Current behavior

The "Database" and "Comments" fields apparently don't exist because they aren't visible and there's no scroll bar.  The only way I found them is by Googling why HeidiSQL isn't showing me any databases on my PostgreSQL server, and someone said you have to select a database on the Session Manager.  My Session Manager did not have a database field, until I luckily noticed I could grab the lower-right corner of the window and resize it to make the database field appear.

![image](https://user-images.githubusercontent.com/5519340/85623536-8e4b2500-b636-11ea-8742-f51463ffa94c.png)

## Expected behavior

Any time GUI elements are hidden on a panel due to the panel being sized too small, you MUST have scrollbars so users will know that there is more to see.

![image](https://user-images.githubusercontent.com/5519340/85624071-55f81680-b637-11ea-82eb-f543c588ec3b.png)

## Possible solution

Add scrollbars to the Session Manager and increase the minimum allowable size so that the Session Manager window cannot be shrunk to the point where the database field cannot be seen.

You may also like to make the "Database" field required for PostgreSQL servers so that the user will understand that it must be selected right then.  With MySQL, we can select the database later once connected, so it's important to help users understand that HeidiSQL treats PostgreSQL databases differently.

## Environment

* **HeidiSQL version:** 
Version 11.0 (yours: 11.0.0.6015)

* **Database system and version:** 
PostgreSQL

* **Operating system:** 
Windows 10 Pro x64 v1909

**Comment by ansgarbecker** [comment]
I just set a minimum window height, so it is forced to show all controls, including those on the Advanced tab.
