### ISSUE TITLE
PostgreSQL not loading the selected database

### ISSUE THREAD

**Issue by Germs2004** [HeidiSQL/HeidiSQL#1075]
## Steps to reproduce this issue

1. Open HeidiSQL
2. Select PostgreSQL (TCP/IP)
3. Enter the hostname, user, password
4. Click the down arrow by the Database textbox, and it will show you the list of databases on the server
5. Select a database
6. Click Open

It connects me to the PostgreSQL instance, but appears to connect to the "postgres" database even though I selected a different database.  I cannot see any tables belonging to my actual selected database, just the built-in postgresql databases.  It's unusable.

HeidiSQL should show the tables belonging to the database I selected on the Session Manager screen, as one would expect.

## Possible solution

The obvious: connect to the correct database and display the tables for that selected database on the left side of the screen, instead of showing only the tables for the postgres database.

## Environment

* **HeidiSQL version:** 
11.0.0.6015
  
* **Database system and version:** 
PostgreSQL 12
  
* **Operating system:** 
Windows 10 Pro x64 v1909

**Comment by ansgarbecker** [comment]
Are you sure you selected a database? Whatever you select as database is actually put into the connection string and passed in "dbname" to [PQconnectdb](https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-CONNSTRING)

**Comment by Germs2004** [comment]
> Are you sure you selected a database?

Yes, I'm pretty sure I did it right, though I am a new user:
Step 1) Select the database
![image](https://user-images.githubusercontent.com/5519340/85758509-644d3d80-b6de-11ea-84b4-1aed012eb833.png)

Step 2) Click Open
![image](https://user-images.githubusercontent.com/5519340/85758089-0587c400-b6de-11ea-8262-34c6b5e8d0bc.png)

Step 3) See no tables
![image](https://user-images.githubusercontent.com/5519340/85758434-53043100-b6de-11ea-8abf-ea5ae2e6eae0.png)

**Comment by lukinhaspm** [comment]
Expand "public" and it will be all user tables in Database...

**Comment by Germs2004** [comment]
Sorry, no luck:

![image](https://user-images.githubusercontent.com/5519340/85760091-82676d80-b6df-11ea-8c1b-cfab9fb7df4e.png)


I checked with pgAdmin to make sure there were tables in the database named ttrss, and there are:
![image](https://user-images.githubusercontent.com/5519340/85760211-9e6b0f00-b6df-11ea-89e5-8202f638c8ef.png)

**Comment by Germs2004** [comment]
I fixed it.  I went to Preferences, clicked "Restore defaults", and restarted HeidiSQL.  Now, the theme is back to light (I used to have a dark theme), and when I connect to my PostgreSQL server, it shows all the correct tables under "Public."  There may have been something interesting in the preferences that was causing the problem, but I don't know what it was since it all got reset.  I could test a few settings to try to reproduce the problem if anyone has specific settings in mind.

**Comment by ansgarbecker** [comment]
That's the "Show favorites only" button. You may have accidentally clicked it. The Material theme is not so clearly distinguishible for pressed buttons, but it was pressed on your side, as you can see here:

![grafik](https://user-images.githubusercontent.com/7986591/85762747-56b2aa80-b714-11ea-8f0b-fcc5ef6fdbf5.png)
