### ISSUE TITLE
data view will not be updated while change the table on left side

### ISSUE THREAD

**Issue by martijintro** [HeidiSQL/HeidiSQL#1076]
Hi

Version:

![image](https://user-images.githubusercontent.com/42765391/85861905-4f95a600-b7c1-11ea-95b4-047884c90820.png)

Is it a feature, a bug or a setting that the tables data view will not be updated while change the table on left side?

That was very confusing, because is was thinking my program does not work because your application has still shown a null value in a field... after ~1 hour i've found the reason - no "auto update" while changing the table in combination with the "Data" tab.

thank you for your feedback.

regards, jan

**Comment by ansgarbecker** [comment]
Please add a reproduction recipe, as I cannot reproduce that here.
