### ISSUE TITLE
Export grid rows dialog should retain selected encoding when toggling Excel CSV

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#1077]
## Steps to reproduce this issue

1. Open Export grid rows dialog
2. Select UTF-8
3. Select Excel CSV as output format
4. Encoding switches to ASCII
5. Select JSON as output format, encoding remains ASCII

## Current behavior

Only Excel CSV auto-switches to ASCII encoding, and then retains that selection when choosing other output formats.

## Expected behavior

Don't auto-switch encoding.

## Possible solution

I frequently switch between Excel/CSV export and JSON export. I would prefer to always use UTF-8, but the encoding auto-toggle frequently lands me in an undesirable JSON/ASCII combo. Maybe just leaving the selected encoding alone would be acceptable? I don't think that excel would choke on UTF-8 encoded csv files in 2020?

## Environment

* **HeidiSQL version:** any
  
* **Database system and version:**  MySQL
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
>  I don't think that excel would choke on UTF-8 encoded csv files in 2020?

In 2012 that was the case, which is the reason for that auto-switch. See my modification: 694a99f13ad42a2e6eeb3b95f57e6fadc439c42c . According to https://en.wikipedia.org/wiki/Comma-separated_values#Application_support , this is supposedly still the case for Excel 2019. You could do some check here?

**Comment by leeoniya** [comment]
> (e.g., as of 2019 Excel still cannot export CSV files in the commonly used UTF-8 character encoding). 

it may not be able to *export* them, but i think it has no problem importing them. i don't have Excel, but i've asked a coworker to test whether it screws up an € symbol when opening a simple csv.

**Comment by ansgarbecker** [comment]
I suppose your coworker said that utf-8 worked for him? If so, that sounds reasonable to stick to utf-8 then.

**Comment by leeoniya** [comment]
i'll let you know. he was out of the office when i pinged him.

**Comment by leeoniya** [comment]
ok, so the story is that Excel needs UTF8 w/BOM to work properly, which i think is a better default than ANSI.

since you don't have any options for BOM on the export dialog anyways, the most seamless option would be to have a UTF8 default for all exports and silently insert the BOM when Excel CSV is selected....and probably only when writing to a file since i don't think the BOM is necessary when pasting into excel from a clipboard with CSV contents (i'll test this at some point later, but this is probably not super critical).

alternatively add a BOM checkmark and toggle it when Excel CSV is selected, but clear it when another format is selected and force the user to toggle it manually if they really need it for other formats.

**Comment by leeoniya** [comment]
ping @ansgarbecker 

this might knock out #800 as well?

**Comment by ansgarbecker** [comment]
Just did that - silently inserting a BOM in Excel/utf8 mode.

Very confusing though that Delphi's `TEncoding.UTF8` does not write that BOM itself, at least in conjunction with the `TStringStream` HeidiSQL uses. I had to explicitly add the 3 bytes to the beginning of the stream.

**Comment by leeoniya** [comment]
great, thanks!
