### ISSUE TITLE
keyboard entry into foreign-keyed columns is unusable

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#1078]
## Steps to reproduce this issue

1. Drop down any column with a foreign key into another table
2. Sorting is done on the reference table's ref-column+1
3. Typing "1" repeatedly will never select "MasterCard" in the screenshot below
4. It is also impossible to type "Mast" to reach that entry

![image](https://user-images.githubusercontent.com/43234/85952714-e03ec400-b930-11ea-92a1-02482bf76b2b.png)

## Expected behavior

It should be possible to type "Mast" to select the "1" entry. And typing "1" should properly cycle MasterCard as the selected item.

My preference would additionally be to leave the sorting by the foreign-keyed column rather than the foreign-keyed column+1, since our entries in that table are naturally ordered by frequency, so Visa and MasterCard being at the top of the list is very preferable and would have potentially eliminated my need to type "Visa" which appears somewhere at the bottom when sorted alphabetically. This would be a good global option to have in the preferences.

## Environment

* **HeidiSQL version:** latest
  
* **Database system and version:** MySQL
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
The current drop-down approach won't get more modifications. I planned to create a better foreign key finder, see #762
