### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by i-panov** [HeidiSQL/HeidiSQL#108]
## Current behavior

Error "Access violation at address...". It does not always happen, but very often. For example, for select-queries.

### Context

* HeidiSQL version: 9.5.0.5196 (64 bit)
* Database system + version: mysql 5.6 x64
* Operating system: Windows 7

### Failure Logs

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1673011/bugreport.txt)

**Comment by ansgarbecker** [comment]
Same as #57
