### ISSUE TITLE
MariaDB user greyed out when using _ in IP address

### ISSUE THREAD

**Issue by tobias-gruenewald** [HeidiSQL/HeidiSQL#1080]
## Steps to reproduce this issue

1. Use a MariaDB (probably also MySQL) server with --skip-name-resolve
2. Connect to this database server with HeidiSQL client
3. open user management in HeidiSQL
4. observe that users are greyed out that have an IP address host part with an uderscore (_)
5. observe an error message at the bottom: user inactive because of --skip-name-resolve

## Current behavior

see above

## Expected behavior

Using an underscore wildcard character in IP address hostnames is a valid setup according to documentation and works perfectly fine with --skip-name-resolve. An underscore does not imply that the hostname is not an IP address.

## Possible solution

Do not filter out hostnames that are IP addresses with underscores (_) when --skip-name-resolve is set. The same is already working for the percent (%) wildcard character.

## Environment

* **HeidiSQL version:** 
11.0.0.5919

* **Database system and version:** 
MariaDB 10.4.

**Comment by ansgarbecker** [comment]
I just modified the detection of valid ip address patterns not requiring name resolving. Please check if the next build works for you, I have no server with skip-name-resolve at my hands currently. Next build should be ready in 20 minutes.

**Comment by tobias-gruenewald** [comment]
I can confirm that build 6030 fixed this. Users can now be edited, if the hostname contains an IP address with _ wildcard.

Thanks for the quick resolution and for the great tool!
