### ISSUE TITLE
Duplicating a MySQL user does not copy the password

### ISSUE THREAD

**Issue by tobias-gruenewald** [HeidiSQL/HeidiSQL#1081]
## Steps to reproduce this issue

1. Connecto to MariaDB/MySQL server
2. Open user management
3. Duplicate an existing user
4. Modify username or hostname or permissions as required
5. Save user

## Current behavior

The new user is created with copied privileges but without a password. It's possible to manually copy the password hash in the mysql.user table, but this would not replicate across Galera clusters. The user manager has no option to enter a hashed password, so it cannot be used to set it, if it is unknown. So the only way is to use a manual SQL statement to read the hash from the user table and use it in a MODIFY USER statement.

## Expected behavior

User manager duplicate operation should be able to read the password hash from the mysql.user table and set it when creating the new user.
According to revision 4747 I found in an older forum thread, this should have been implemented a long time ago. But it seems it's been gone along the way again.

## Possible solution

Currently the duplicate user operation performs the following:
CREATE USER '<user>'@'<host>';
GRANT <copied privileges> ON <copied database> TO '<user>'@'<host>';
FLUSH PRIVILEGES;

It should use the following CREATE statement:
CREATE USER '<user>'@'<host>' IDENTIFIED BY PASSWORD <copied hash>;

## Environment

* **HeidiSQL version:** 
11.0.0.6030

* **Database system and version:** 
MariaDB 10.4

**Comment by ansgarbecker** [comment]
Please update to the next build in a few minutes and recheck.

The output of `SHOW GRANTS` is missing an `IDENTIFIED BY PASSWORD xyz` with the hashed password on MySQL 5.7.6, while MariaDB still includes it. My fix in 0ec226ce47cb2252ce51473c76c815b962d4ee24 ignored these for MariaDB as well, which I just restricted to MySQL only. So I think this is fixed now. Otherwise please shout.

**Comment by tobias-gruenewald** [comment]
Can confirm that this works now with the latest build. Thanks
