### ISSUE TITLE
Broken space into start screen

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#1082]
## Steps to reproduce this issue

1. Step 1; Open Heidi
2. Step 2; See the space between labels and fields...

![image](https://user-images.githubusercontent.com/11230133/86617447-98054e80-bf8d-11ea-8280-74dd6c86c3c9.png)

try to resize

![image](https://user-images.githubusercontent.com/11230133/86617596-d7cc3600-bf8d-11ea-844f-5cdeeceb8488.png)

maybe because this?

![image](https://user-images.githubusercontent.com/11230133/86618344-1f06f680-bf8f-11ea-812a-c7e65099e5fb.png)

## Environment

* **HeidiSQL version:** 11.0.0.6141
* **Operating system:** Windows 10 64x

**Comment by ansgarbecker** [comment]
Labels need more space in various languages. I widened these for Russion text, e.g., see #957 . We can discuss that there, but I don't believe there is a "better" way of doing that.

**Comment by lukinhaspm** [comment]
OK, thanks
