### ISSUE TITLE
[Feature Request] Lixux Distro

### ISSUE THREAD

**Issue by mbnoimi** [HeidiSQL/HeidiSQL#1085]
Hi,

This is very old request came back from death.

PLEASE create a native distro for Linux. Lazarus currently much stable now. WINE really suck it's very buggy specially when the user want to deal with UTF8 (I became unable to use HeidiSQL because of WINE sucking).

**Comment by mbnoimi** [comment]
BTW, I was using MySQL Workbench as alternative to HeidiSQL but when it comes to MariaDB I've to use HeidiSQL. Unfortunately HeidiSQL still living on Windows island without caring about the other world :(

**Comment by ansgarbecker** [comment]
You deleted the whole issue template - don't do that.

Anyway, this is not a feature request, but a request for a whole rewrite of HeidiSQL. This is beyond of what I can do currently. I already gave Lazarus a try, with disappointing results. See https://github.com/HeidiSQL/HeidiSQL/issues/213#issuecomment-431126992

> Unfortunately HeidiSQL still living on Windows island without caring about the other world

I am always giving the Wine issues a high priority, so this is not true.
