### ISSUE TITLE
Auto-create folders when exporting sql to disk

### ISSUE THREAD

**Issue by Dwza** [HeidiSQL/HeidiSQL#1086]
Actually I use HeidiSql every time when I want to make backups from different systems. It's a very nice tool.
Now to keep everyting nice ordered I have an export folder where I store my exports. But in some cases... there are to many files in one folder so I would like to seperate them in some kind.

Is it possible to let HeidiSQL create folders and not throwing an exception because the folder does'nt exist?

Because I would love to have a export path like: `c:\Users\dwza\sqlBackups\%db\%y\%m\%d\%db_live_%y%m%d.sql`
So everyting would be nicely sorted and could be found nicely as well :D

**Comment by ansgarbecker** [comment]
You mean these `%..` patterns should auto-create non-existent folders, or?

**Comment by Dwza** [comment]
correct :)

**Comment by peter17ji** [comment]
> 
> 
> You mean these `%..` patterns should auto-create non-existent folders, or?

Yes. I need this enhancement too.

**Comment by ansgarbecker** [comment]
Done for the next build.
