### ISSUE TITLE
MySQL 8: integer display width deprecated

### ISSUE THREAD

**Issue by carmel** [HeidiSQL/HeidiSQL#1088]
## Steps to reproduce this issue

1. run sql script as follow:
```sql
CREATE TABLE `refer_map1` (
	`id` VARCHAR(32) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`typ` TINYINT(3,0) NOT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB
;
```  
it will report error: 
`/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',0) NOT NULL,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
' at line 3 */`

## Current behavior

![image](https://user-images.githubusercontent.com/36031579/87495202-59ede600-c683-11ea-84da-2ce8fd89152f.png)

## Environment

* **HeidiSQL version:**   11.0.0.5919(64 bit)
  
* **Database system and version:**  MySQL 8.0
  
* **Operating system:**   Windows 7

**Comment by carmel** [comment]
HeidiSQL  generated create statement:  
![image](https://user-images.githubusercontent.com/36031579/87495832-ea78f600-c684-11ea-90ed-94ff00e962d8.png)

**Comment by carmel** [comment]
HeidiSQL generated create statement:
![image](https://user-images.githubusercontent.com/36031579/87496041-58252200-c685-11ea-9377-11f0e31cad8f.png)

**Comment by carmel** [comment]
> ## Steps to reproduce this issue
> 1. run sql script as follow:
> 
> ```sql
> CREATE TABLE `refer_map1` (
> 	`id` VARCHAR(32) NOT NULL COLLATE 'utf8mb4_unicode_ci',
> 	`typ` TINYINT(3,0) NOT NULL,
> 	PRIMARY KEY (`id`) USING BTREE
> )
> COLLATE='utf8mb4_unicode_ci'
> ENGINE=InnoDB
> ;
> ```
> 
> it will report error:
> `/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',0) NOT NULL, PRIMARY KEY (`id`) USING BTREE ) COLLATE='utf8mb4_unicode_ci' ' at line 3 */`
> 
> ## Current behavior
> ![image](https://user-images.githubusercontent.com/36031579/87495202-59ede600-c683-11ea-84da-2ce8fd89152f.png)
> 
> ## Expected behavior
> ## Possible solution
> ## Environment
> * **HeidiSQL version:**   11.0.0.5919(64 bit)
> * **Database system and version:**  MySQL 8.0
> * **Operating system:**   Windows 7

HeidiSQL generated create statement:
![2020-07-15_102356](https://user-images.githubusercontent.com/36031579/87496171-9f131780-c685-11ea-8e18-9c14931f3240.png)

**Comment by ansgarbecker** [comment]
Please update to the latest build.

**Comment by carmel** [comment]
Already the latest version, as you see： version 11.0.0.5919

**Comment by carmel** [comment]
> Please update to the latest build.

Already the latest version, as you see： version 11.0.0.5919

**Comment by ansgarbecker** [comment]
No, that is the latest _release_. You need the latest nightly _build_, please check via Help > Check for updates.

**Comment by carmel** [comment]
@ansgarbecker Thanks for your precious time to reply to me. I know what to do next!

**Comment by carmel** [comment]
![image](https://user-images.githubusercontent.com/36031579/87510906-042b3500-c6a7-11ea-819b-b03924d10a11.png)

By the way, will the problem prompted by this warning be resolved in the future?

**Comment by carmel** [comment]
By the way, will the problem prompted by this warning be resolved in the future?

![image](https://user-images.githubusercontent.com/36031579/87511025-405e9580-c6a7-11ea-9a47-c3231491109e.png)
![image](https://user-images.githubusercontent.com/36031579/87511091-59674680-c6a7-11ea-960f-305299931a33.png)
