### ISSUE TITLE
[Wine] Session manager buttons not displaying correctly

### ISSUE THREAD

**Issue by pedromntomas** [HeidiSQL/HeidiSQL#1089]
## Steps to reproduce this issue

1. Open session manager

## Current behavior

![image](https://user-images.githubusercontent.com/5527553/87789443-fa383c00-c836-11ea-870e-a28363ad8327.png)
The bottom buttons are overlapped by the boxes above them.
It seems to me that this issue appeared after there was an adjustment to the boxes height a few weeks ago.

## Expected behavior

Buttons appear correctly without overlaps.

## Environment

* **HeidiSQL version:** 11.0.0.6051
  

* **Operating system:** Ubuntu 20.04, Gnome shell 3.63.3, Wine 5.0.1

**Comment by ansgarbecker** [comment]
I increased the minimum height and width recently, maybe this can be fixed by just resizing the window once, plus a restart of HeidiSQL?

**Comment by pedromntomas** [comment]
No, no matter how I resize the window, it stays the same.

**Comment by ansgarbecker** [comment]
And I suppose that issue was not present in the last release 11.0? Or even in one nightly build you know of?

**Comment by pedromntomas** [comment]
Build 6015 doesn't have this issue, build 6016 have this issue. This one it's from the commit you mentioned.

**Comment by ansgarbecker** [comment]
I see it now on Ubuntu, build 6015:
![grafik](https://user-images.githubusercontent.com/7986591/87797678-56a55680-c84b-11ea-80c6-4d84e4d08261.png)

... and in 6016 (well, just confirming your report):
![grafik](https://user-images.githubusercontent.com/7986591/87797790-776dac00-c84b-11ea-9548-f070f06d649d.png)

Looks as if the buttons were moved up.

**Comment by pedromntomas** [comment]
Superb! Thanks :D
