### ISSUE TITLE
Session Manager off screen when after multi-screen-setup

### ISSUE THREAD

**Issue by jorese** [HeidiSQL/HeidiSQL#109]
## Expected behavior
It would be nive if the session manager checks if it is off screen before showing

## Current behavior
Last time HeidiSQL was used the session manager was on an extended desktop screen.
When starting HeidiSQL next time on only one screen it is hard to figure out that it is the session-manager-modal-window that is off screen, and kind of hard to get it back

### Steps to reproduce
1. Start HeidiSQL with extended desktop
2. Move session manager to the extended part
3. Exit HeidiSQL and change to one-screen-setup
4. Start - Good Luck

### Context
* HeidiSQL version: v9.5.0.5220
* Database system + version: MariaDB (probably doesn't matter)
* Operating system: Windows 10

**Comment by ansgarbecker** [comment]
This should already be fixed, since build 5226 and a26d68d23c2d7d921642891a4989756c8ee7a50b.

See the [recent report in the forum](https://www.heidisql.com/forum.php?t=24822).
