### ISSUE TITLE
[Wine] Sorting arrows icons don't appear when sorting a table column

### ISSUE THREAD

**Issue by pedromntomas** [HeidiSQL/HeidiSQL#1090]
## Steps to reproduce this issue

1. Open HeidiSQL and open any database
2. Select any table
3. Sort any column
4. Instead of an arrow icon to appear in the column header, a symbol shows up.

## Current behavior

![image](https://user-images.githubusercontent.com/5527553/87790189-14264e80-c838-11ea-99c8-0da319c69777.png)
The sorting arrows don't appear when sorting columns.
In the picture, column `user_id` is sorted descending and column `status` is sorted ascending.
This happens for both of icon packs.

## Expected behavior

Sorting arrows appear correctly.

## Environment

* **HeidiSQL version:** 11.0.0.6051
  

* **Operating system:** Ubuntu 20.04, Gnome shell 3.63.3, Wine 5.0.1

**Comment by ansgarbecker** [comment]
That can't be true... looks like a font issue. See #618 for the reason to change it. The sort arrows are now text characters ▲ and ▼ - these seem not to be contained in the font which Wine uses, and/or which is set in Tools > Preferences > Grid formatting:
![grafik](https://user-images.githubusercontent.com/7986591/87791745-16da7100-c843-11ea-988a-41d87d0a6bd1.png)

**Comment by pedromntomas** [comment]
Yes, it seems it's a font issue.
I was using Noto sans as a font and the icons didn't appear. I changed the font to Fira code and voilá, they appeared:
![image](https://user-images.githubusercontent.com/5527553/87792357-ae3bc600-c83b-11ea-8c30-451e00501578.png)

**Comment by ansgarbecker** [comment]
Hm, I fear many other WIne users will have  that rectangle, like you did. Is that "Noto sans" some default font on Ubuntu ? I could use a different character on Wine, if that makes sense.

**Comment by leeoniya** [comment]
is it possible to just force a known-good font for the sorting bits?

**Comment by pedromntomas** [comment]
Noto sans it's a font downloaded from google fonts. The default font on Ubuntu is "Ubuntu" and even that font doesn't show the icons.

**Comment by ansgarbecker** [comment]
Probably that Ubuntu font has some nice alternative arrow characters - I found that font [here](https://design.ubuntu.com/font/), but I have no clue how to browse through its supported characters.

**Comment by leeoniya** [comment]
> but I have no clue how to browse through its supported characters.

https://www.babelstone.co.uk/Software/BabelMap.html

**Comment by ansgarbecker** [comment]
> isn't Courier New available basically everywhere? (or any "web-safe" font?

Not so for Courier New I'm afraid, and also not the working `Fira code`:
![grafik](https://user-images.githubusercontent.com/7986591/87802011-d84bb300-c850-11ea-8a11-690a13edd353.png)

**Comment by ansgarbecker** [comment]
In the next build, on Wine HeidiSQL uses these: ↑ ↓
Of course this can fail as well, I'm just hoping not for many as with the other arrows.

**Comment by pedromntomas** [comment]
Nice! And i think it works also with Noto sans that i'm using.

**Comment by ansgarbecker** [comment]
Not sure if that fix is sufficient for most Wine users. Just shout if you have  a better idea.

**Comment by kakenbok** [comment]
The arrows in the db tables overview (sort table name) work properly.

The arrows in a particular table (sort column) do not work.

**Comment by evs-xsarus** [comment]
Can confirm this is still a problem for 12.1.0.63537:

DB Tables overview is correct:

![image](https://user-images.githubusercontent.com/44158071/189053774-326e12a5-a0a5-4ef5-8a20-a42263aec04d.png)

Data tab is wrong when using 'Ubuntu Mono'

![image](https://user-images.githubusercontent.com/44158071/189053862-35a08278-43d5-4c9f-b628-ef17e85354fa.png)

Another font shows the different arrows:

![image](https://user-images.githubusercontent.com/44158071/189053991-fce8c6e9-3726-47d0-8a9e-c310046a4719.png)

Proposal:

![image](https://user-images.githubusercontent.com/44158071/189055191-1e2c209d-4dfa-4a97-8050-8f9e137b1c47.png)

Used arrows:

Up - https://unicode-table.com/en/2191/
Up triangle - https://unicode-table.com/en/25B2/
Down - https://unicode-table.com/en/2193/
Down triangle - https://unicode-table.com/en/25BC/
