### ISSUE TITLE
Not a valid donor email address

### ISSUE THREAD

**Issue by plakhin** [HeidiSQL/HeidiSQL#1092]
After updating to 11.0.0.6053 (64 Bit) today  I'm receiving "Not a valid donor email address" error when entering my email. 
I don't remember previous version  build number, but it was also a nightly build about week or two old and it didn't have this error.

**Comment by ansgarbecker** [comment]
That's because I'm now letting donations below 50€ to hide that button for 2 years only now.

Thanks for understanding!

**Comment by plakhin** [comment]
@ansgarbecker for what time 1€ donation is valid? I donated about 10 days ago and started to receive the same error today.
Are there any information regarding donation amount and valid time somewhere?
