### ISSUE TITLE
SQL server table creation using 'NULL' instead of NULL as default value.

### ISSUE THREAD

**Issue by fcarelse** [HeidiSQL/HeidiSQL#1095]
## Steps to reproduce this issue

1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by fcarelse** [comment]
I used a query in HEIDISQL:
CREATE TABLE "Sessions" (
	"id" INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	"key" VARCHAR(50) NULL DEFAULT NULL,
	"status" VARCHAR(20) NULL DEFAULT NULL,
	"timeout" DATE NULL DEFAULT NULL,
	"expiry" DATE NULL DEFAULT NULL,
	"data" TEXT NULL DEFAULT NULL,
	"modifiedOn" DATE NULL DEFAULT NULL,
	"createdOn" DATE NULL DEFAULT NULL
);

All the constraints were set to 'NULL' not the null value for default row value.

**Comment by ansgarbecker** [comment]
Please edit your initial post here, and fill out as many of the fields you can. This is otherwise not a valid report and will be closed.
