### ISSUE TITLE
 Wish: Theming individual sessions

### ISSUE THREAD

**Issue by guldevec** [HeidiSQL/HeidiSQL#1098]
Would love to see a way of theming a session / DB connection with a different color so as to differentiate between open sessions
I regularly have a development session open and a production session open and while careful, come close to interfering the live production data.  I name my session currently like ======= P R O D U C T I O N ====== and that's my trick

**Comment by ansgarbecker** [comment]
That's already doable, with a session color for the tree:

![grafik](https://user-images.githubusercontent.com/7986591/88137222-5f9b7c80-cbeb-11ea-98fa-b7bde60b7111.png)

**Comment by guldevec** [comment]
ahhh - Doh...  thanks @ansgarbecker  my Advanced dialog wasn't opening that far...
