### ISSUE TITLE
Support for CHARACTER SET for column and procedure parameter

### ISSUE THREAD

**Issue by xmedeko** [HeidiSQL/HeidiSQL#11]
## Expected behavior

I would like to have set in GUI different `CHARACTER SET` for a column and for a procedure parameter.

## Current behavior

Cannot set it by GUI. The HeidiSQL allows to change table column `COLLATE` only.

### Context

* HeidiSQL version: 9.4.0.5185
* Database system + version: MariaDB 10.0.31
* Operating system: Windows 10

**Comment by ansgarbecker** [comment]
I believe we can close this.
* Table columns can have a collation, which implies a specific character set
* Procedure parameters can have a character set in the datatype definition, like in the screenshot below
![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/f81986b1-a83b-4e50-90dd-1289e8aee905)


Please shout if there is something important left here. And sorry for the really long delay.
