### ISSUE TITLE
"Run current query" should take selection into account

### ISSUE THREAD

**Issue by GPHemsley** [HeidiSQL/HeidiSQL#1106]
(Tangentially related to #1105.)

## Steps to reproduce this issue

1. Have a query in a query tab where a subset of it is a valid query.
2. Select a portion of a valid query with the cursor.
3. Run "Run current query" (Ctrl+Shift+F9).

## Current behavior

HeidiSQL uses its internal query chunker to identify the query to run, often resulting in a query being run other than the intended query.

## Expected behavior

Only the portion of the query in the selection is run.

## Possible solution

There are many ways to go about supporting the highlighted query.

PL/SQL Developer (for Oracle) has a single query execution mode (equivalent to HeidiSQL's F9) that simply takes selection into account: if a partial query is selected, run that; otherwise, run the whole query.

Because HeidiSQL has two query execution modes, there are multiple options: support query selection execution in F9 mode only, in Ctrl+Shift+F9 mode only, in both modes, or in a new third mode.

## Environment

* **HeidiSQL version:** Version 11.0.0.6057 (64 Bit)

**Comment by ansgarbecker** [comment]
For running the selected text, please use "Run selection":

![grafik](https://user-images.githubusercontent.com/7986591/88759239-a00a7580-d16a-11ea-952e-e933a237bb66.png)

The "Run current query" has nothing to do with the selection. Let's not mix that up.

**Comment by GPHemsley** [comment]
Oh wow, I don't know how I missed that. Thanks.
