### ISSUE TITLE
Wrong row count with MySQL 8

### ISSUE THREAD

**Issue by svanlaere** [HeidiSQL/HeidiSQL#1108]
## Steps to reproduce this issue

1. Rows count is wrong when used with MySQL 8. (Database tab)

Not tested with other MySQL versions, rows count is correct with MariaDB 10.1.41

## Environment

* **HeidiSQL version:** 
Revision11.0.0.6061
* **Database system and version:** 
MySQL 8.0.21
* **Operating system:** 
Windows 10 Pro

**Comment by ansgarbecker** [comment]
Please check if that row count is wrong due to the estimation done by the server for innodb tables.

**Comment by svanlaere** [comment]
Executing query "SELECT COUNT(*) FROM comments;" returns correct value.
What method does Heidi use to get the count?

**Comment by ansgarbecker** [comment]
HeidiSQL fires `SHOW TABLE STATUS` to get the row count.

**Comment by svanlaere** [comment]
Okay when I run `SHOW TABLE STATUS` is show the wrong count for each table.
When I run `ANALYZE TABLE` for each table the problem gets resolved.

**Comment by ansgarbecker** [comment]
You can also put that into a auto-loaded session script for your heidisql session.
However, this makes the process slower, so that's nothing which I would put in Heidisql itself.
