### ISSUE TITLE
SHOW CREATE TRIGGER causes error on autocomplete in MySQL prior to 5.1

### ISSUE THREAD

**Issue by als2002** [HeidiSQL/HeidiSQL#111]
## Expected behavior
When entering <database name>. I expect to receive list of tables to choose. : 
select * from database.

## Current behavior
It fails, if Mysql version is prior to 5.1, where  "show create trigger statement" was introduced, and <database name> contains triggers.
It is possible to continue, closing error message.

## Failure information (for bugs)

Last info in mysql query log is:
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1685144/bugreport.txt)
SHOW CREATE TABLE `powerbi`.`akcijas_prognoze`;SHOW CREATE TRIGGER `powerbi`.`akcijas_prognoze_before_insert`;
/* SQL Error (1064) in statement #2: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'TRIGGER `powerbi`.`akcijas_prognoze_before_insert`' at line 1 */

### Steps to reproduce
edit query , engaging autocomplete to retrieve table list from database with triggers

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.5.0.5196
* Database system + version: MySQL Community Server (GPL) 5.0.67
* Operating system: redhat-linux-gnu

### Failure Logs

 
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1685164/bugreport.txt)

**Comment by ansgarbecker** [comment]
So one can have a trigger in a < 5.1 server, but `SHOW CREATE TRIGGER` fails? Weird..

Do you know an alternative way to retrieve the trigger code?

**Comment by als2002** [comment]
Yep. Triggers were added in 5.0, and `show create trigger` in 5.1. 
> Do you know an alternative way to retrieve the trigger code?
1. Maybe  it is safe to just skip triggers' source retrieval for autocomplete, because at the moment it fails, only list of table names is actually needed?
2. Source and other data can be retrieved from `INFORMATION_SCHEMA.TRIGGERS` table: `ACTION_STATEMENT` field contains source code.

```sql
select * from information_schema.TRIGGERS t
where t.TRIGGER_SCHEMA = 'dbname' 
  and t.TRIGGER_NAME = 'trigger_name'`
```
