### ISSUE TITLE
ROW_COUNT() does not work ›for MariaDB

### ISSUE THREAD

**Issue by SmokeGlider** [HeidiSQL/HeidiSQL#1110]
## Steps to reproduce this issue

Step 1: Start up HeidiSQL and connect to MariaDB and open a new query tab

Step 2: On the Query tab add the following code and run it

```
CREATE DATABASE IF NOT EXISTS bug_test_db
  CHARACTER SET = 'latin1'
  COLLATE = 'latin1_general_ci';	

USE bug_test_db;

CREATE TABLE IF NOT EXISTS bug_test_table
(	
	id TINYINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`name` VARCHAR(30) NOT NULL
);


INSERT INTO bug_test_table(`name`) VALUES ('Test Row');

INSERT INTO bug_test_table(`name`) VALUES ('Test Row 2'), ('Test ROW 3');
SELECT ROW_COUNT();

UPDATE bug_test_table
SET `name` = 'Test Row Again'
WHERE id IN (1);
SELECT ROW_COUNT();

DELETE 
FROM bug_test_table
WHERE id IN (1,2,3);
SELECT ROW_COUNT();
```

Step 3: Then look at results panes

 

in the Results #1 pane you get

ROW_COUNT()
0

in the Results #2 pane you get

ROW_COUNT()
0

In the Results #3 pane you get

ROW_COUNT()
0

## Current behavior

For INSERT, UPDATES and DELETES, ROW_COUNT returns 0 

## Expected behavior

As per the description of ROW_COUNT() on MariaDB documentation page:

https://mariadb.com/kb/en/row_count/

ROW_COUNT() returns the number of rows updated, inserted or deleted by the preceding statement. 

Therefore,

Results #1 pane should be displaying

ROW_COUNT()
2

Results #2 pane should be displaying

ROW_COUNT()
1

Results #3 pane should be displaying
ROW_COUNT()
3

Expected the results would be a positive integer representing the row count of the affects rows due to the statements executed and only be zero if no rows were affected. See attached screen shot when using MariaDB's command line interface. The results of an INSERT statement are as expected.

## Possible solution

I don't know. Code fix?

## Environment

I'm running a clean install of windows 10 pro 
![Screen Shot 2020-07-30 at 3 40 22 PM](https://user-images.githubusercontent.com/69017555/88981577-1dbda680-d27b-11ea-9f5a-234c03b597cd.png)
and newly install MariaDB and HeidiSQL.

* **HeidiSQL version:** 

Version 11.0.0.6062 (32 bit)
Compiled on 2020-07-29 05:40:33

  
* **Database system and version:** 

MariaDB

10.5.4-MariaDB

  
* **Operating system:** 

Windows 10 Pro with latest updates

**Comment by ansgarbecker** [comment]
This is caused by HeidiSQL calling `mysql_ping()` prior to any query, and was reported before, [in the forum](https://www.heidisql.com/forum.php?t=9791).

You can however work around that, by sending queries as a batch:

![grafik](https://user-images.githubusercontent.com/7986591/89004202-f0680b80-d301-11ea-8dbe-dda091074393.png)

**Comment by kompa3** [comment]
I was struggling with exactly the same issue. Thanks @ansgarbecker for the explanation! It saved my day!

**Comment by ansgarbecker** [comment]
Thanks for your feedback.
I guess I can close the ticket. Solution is to use "Send queries one by one" option.
