### ISSUE TITLE
Query tab resizes after minimize then maximize

### ISSUE THREAD

**Issue by WesleyM77** [HeidiSQL/HeidiSQL#1113]
## Steps to reproduce this issue

1. Open a Query tab
2. Drag the bottom of it to make it bigger
3. Minimize HeidiSQL to toolbar
4. Click to refocus/maximize HeidiSQL from the toolbar
5. Observe the query tab having been resized

## Current behavior

Unexpected resize of ALL tabs on maximize following minimize. Not sure when this started happening. Maybe a week or so now.

## Expected behavior

Maximize after minimize to preserve query tab size

## Environment

* **HeidiSQL version:** 
11.0.0.6067
* **Operating system:** 
Windows 10 Version 1909 OS Build 18363.959

**Comment by ansgarbecker** [comment]
Just tried to reproduce that here, with a fourth query tab having 19 visible lines, after minimize/maximize still 19. Increasing to 39 lines does the same. Please post a screen of the sizes, so I can dig into that.

**Comment by WesleyM77** [comment]
Is this what you need?
![2020-08-04_16-57-02](https://user-images.githubusercontent.com/22208037/89344257-9a81c380-d673-11ea-9cae-b580392806fc.gif)

**Comment by WesleyM77** [comment]
After some more investigation, here's the steps I found in order to get this to _stop_ happening:

1.  Open a fresh HeidiSQL session.
2.  Observe the above behavior by increasing a query tab's height, minimizing, and maximizing to get the query tab height to reset.
3.  Restore down (the button between minimize and close).
    - Now, if you were to maximize at this point, you could still compete step 2.
4.  Drag the bottom right corner of the window to make the window larger.
5.  Maximize.
6.  Drag query tab to a larger height.
7.  Minimize, then Maximize.
8.  No longer observe auto-resizing of query tab behavior.


I hope this is clear enough to help reproduce and possibly find a cause.

**Comment by HerrimanCoder** [comment]
I have the same problem, it's super annoying.

**Comment by nrazon** [comment]
This is still an issue, My heidisql resizes all my query tabs to "2 lines height" when I minimize and maximize  every time.
Any progress on fixing this problem?

**Comment by ansgarbecker** [comment]
Next build does no longer reduce the height of query tabs. Only the log panel is reduced if it would otherwise overlap a query editor.

Before:
![resize-mainform-old](https://user-images.githubusercontent.com/7986591/110098978-13c7cd00-7da1-11eb-9500-ea44543b5069.gif)

New behaviour:
![resize-mainform-new](https://user-images.githubusercontent.com/7986591/110099011-1cb89e80-7da1-11eb-8d93-adc54beab627.gif)

**Comment by WesleyM77** [comment]
That looks to be working great! Thank you very much!
