### ISSUE TITLE
MySQL(SSH tunnel) does not work with plink > v0.70

### ISSUE THREAD

**Issue by cleanerleon** [HeidiSQL/HeidiSQL#1114]
1. Step 1;
download plink > v0.70
2. Step 2;
create a session of MySQL(SSH tunnel) and open it, the database will not be connected

## Possible solution
add '-no-antispoof' in plink command line if the version is greater than 0.70, which will prompt "Access granted. Press Return to begin session". Please refer to https://stackoverflow.com/questions/57735695/how-to-submit-plink-access-granted-press-return-to-begin-session-prompt-autom

## Environment

* **HeidiSQL version:** 
Version 11.0.0.5919 (64 Bit)
Version 11.0.0.6071 (64 Bit)

**Comment by ansgarbecker** [comment]
Grrr, why do so many users ignore the issue template? You need to state the HeidiSQL version please. Also, try plink 0.73, which will be shipped within the next release.

**Comment by cleanerleon** [comment]
> Grrr, why do so many users ignore the issue template? You need to state the HeidiSQL version please. Also, try plink 0.73, which will be shipped within the next release.

Sorry, I have just added the version. I tried the newest one Version 11.0.0.6071 (64 Bit) and plink 0.73, the bug still appears.

**Comment by ansgarbecker** [comment]
Please try the next build in half an hour. That prompt should then be logged to the log panel and just skipped without waiting. I'm just not yet sure whether that prompt text is again going to the error or the normal pipe, so my modification may not work.

Adding that `-no-antispoof` parameter would break compatibility to older plink versions, which then just exit with an "unknown option" error.

**Comment by cleanerleon** [comment]
> Please try the next build in half an hour. That prompt should then be logged to the log panel and just skipped without waiting. I'm just not yet sure whether that prompt text is again going to the error or the normal pipe, so my modification may not work.
> 
> Adding that `-no-antispoof` parameter would break compatibility to older plink versions, which then just exit with an "unknown option" error.

OK
maybe you can run 'plink' and get the version ...
```
C:\Users\clean>d:\Apps\putty\plink.exe
Plink: command-line connection utility
Release 0.73
Usage: plink [options] [user@]host [command]
```

**Comment by ansgarbecker** [comment]
Yes, that version query could be part of a future release. For now I'd like to keep the text compare approach.

**Comment by cleanerleon** [comment]
> Yes, that version query could be part of a future release. For now I'd like to keep the text compare approach.

I have tried Version 11.0.0.6077 (64 Bit) with plink 0.73, it still cannot connect the database

**Comment by ansgarbecker** [comment]
Please make a screenshot of what HeidiSQL shows you when trying to connect. I can't reproduce this here. For some reason, I don't get this "press return" output in HeidiSQL, although it shows up when executing plink manually.

**Comment by cleanerleon** [comment]
![image](https://user-images.githubusercontent.com/20467191/89708582-05e8cf80-d9ab-11ea-9043-995ddbe18ca7.png)
plink 0.73 requires to press return to start session, or the tunnel will not be established, and HeidiSQL shows
![image](https://user-images.githubusercontent.com/20467191/89708677-aa6b1180-d9ab-11ea-9be3-e7b6f88ab286.png)


![image](https://user-images.githubusercontent.com/20467191/89708625-48aaa780-d9ab-11ea-9cd9-4136678a83e2.png)
plink 0.70 don't prompt this

**Comment by ansgarbecker** [comment]
I wonder why I still cannot see that "can't connect". Can you connect to a MySQL TCP/IP session on localhost after pressing return with the plink 0.73 command opened in the shell?

**Comment by ansgarbecker** [comment]
Please also activate debug logging (Tools > Preferences > Logging > "Debug messages"). Afterwards try to connect, and watch out for "plink" output in the log panel (and paste it here without sensitive data).

**Comment by cleanerleon** [comment]
I can connect to a MySQL TCP/IP session on localhost after pressing return with the plink 0.73 command opened in the shell. 

the debug log shows
> /* 2020-08-09 01:48:32 [cmes] */ /* Connecting to 127.0.0.1 via MariaDB (SSH tunnel), username root, using password: Yes ... */
/* 2020-08-09 01:48:34 [cmes] */ /* Attempt to create plink.exe process, waiting 30s for response ... */
/* 2020-08-09 01:48:34 [cmes] */ /* D:\Apps\putty\plink.73.exe -ssh guest@xxx -pw "******" -P 22022 -N -L 3307:127.0.0.1:3306 */
/* 2020-08-09 01:48:36 [cmes] */ /* PLink output after 1200 ms. OutPipe: ""  ErrorPipe: "Using username "guest".
" */
/* 2020-08-09 01:48:36 [cmes] */ /* PLink: Using username "guest".
 */
/* 2020-08-09 01:48:40 [cmes] */ /* Can't connect to MySQL server on '127.0.

The establishment of the connection to my server is very slow, it first shows 
```Using username "guest".```, 
and after about 15 seconds it shows 
```Access granted. Press Return to begin session.```
I have set plink timeout to 30 manually, however, it seems real timeout is 1200 ms.

for plink 0.70, it works fine
>/* 2020-08-09 01:50:21 [cmes] */ /* Connecting to 127.0.0.1 via MariaDB (SSH tunnel), username root, using password: Yes ... */
/* 2020-08-09 01:50:23 [cmes] */ /* Attempt to create plink.exe process, waiting 30s for response ... */
/* 2020-08-09 01:50:23 [cmes] */ /* D:\Apps\putty\plink.70.exe -ssh guest@xxx -pw "******" -P 22022 -N -L 3307:127.0.0.1:3306 */
/* 2020-08-09 01:50:55 [cmes] */ /* Ping server ... */
/* 2020-08-09 01:50:55 [cmes] */ /* Ping server ... */
/* 2020-08-09 01:50:55 [cmes] */ /* Ping server ... */
/* 2020-08-09 01:50:55 [cmes] */ SELECT CONNECTION_ID();

**Comment by ansgarbecker** [comment]
Then it's a problem of that 15 seconds without plink output. The plink.exe timeout in the "SSH tunnel" tab is just for the first handshake. After the first output (e.g. "Using username xyz") HeidiSQL just waits 2s for the next text output - these 2s are hardcoded. I think I am going to remove that from the code, so Heidi just waits as long as the user wants (in your case 30s).

**Comment by ansgarbecker** [comment]
Please update HeidiSQL to the current nightly build and try again with your 30s timeout.

**Comment by cleanerleon** [comment]
Version 11.0.0.6080 (64 Bit) works now, thank you.
