### ISSUE TITLE
MSSQL row operations (UPDATE, DELETE) fail when primary key is nvarchar

### ISSUE THREAD

**Issue by nummacway** [HeidiSQL/HeidiSQL#1115]
**Describe the bug**
I have a table which has a nvarchar column as a part of its key.

**To Reproduce**
1. Create an MSSQL table with a key that includes an nvarchar column.
2. Insert a row where the nvarchar value is non-ANSI.
3. Delete or update the row.
4. Warning: No row was affected, because the query would be something like this: `UPDATE table SET "key"=N'☺' WHERE "key"='🙈';` (Note the missing capital N in front of the second literal)

**Expected behavior**
Affects a row. Heidi needs to add an N in front of the WHERE clause string literal, like it does when inserting.

`UPDATE table SET "key"=N'☺' WHERE "key"=N'🙈';`

It currently even uses the correct syntax for the new values in an UPDATE, but does not use national varchars in the WHERE clause.

**Environment:**
 - HeidiSQL version: 11.0.0.6077 (current nightly)
 - Database type and version: MSSQL

Note: In table in which I encountered the issue, the primary key consists of more than just the nvarchar column. I did not test my syntax above, it was just to point out the issue.

**Comment by ansgarbecker** [comment]
If I add that `N` prefix to the quoted string, I get another message when updating an `NTEXT` column value:
```sql
UPDATE TOP(1) "master"."dbo"."anse" SET "id"='111' WHERE  "id" IS NULL AND "name"=N'ddd';
/* SQL Error (402): The data types ntext and nvarchar are incompatible in the equal to operator */
```
Do I really have to cast that literal using `CAST('ddd' AS NTEXT)`? If I do that, I even get "_data types ntext and ntext are incompatible in the equal to operator_" ... wtf?

**Comment by nummacway** [comment]
The maximum maximum-size of a key value is 900 bytes. SQL Server should prevent you from using non-in-place types in keys (ntext, text, nvarchar(max), varchar(max), image, varbinary(max)). Also, you are not supposed to use text, image and ntext at all in SQL Server 2012 and newer.
Which version of SQL Server are you using? Did you manage to make an ntext column part of a key?

**Comment by ansgarbecker** [comment]
Ok that makes sense, except for "not supposed to use ... ntext" - is that true? What is the alternative datatype then for large text?

I am using SQL Server Express 2017. That `NTEXT` column is not part of a key, and my table does not have any key. That's where HeidiSQL just uses all columns in its `WHERE` clause, as a (unsafe!) fallback. Perhaps it's better to block `UPDATE`s and `DELETE`s on tables without a sufficient key?

**Comment by nummacway** [comment]
ntext has been replaced by nvarchar(max), text by varchar(max) and image by varbinary(max). I know that you cannot compare ntext, text and image. Maybe you can compare nvarchar(max), varchar(max) and maybe even varbinary(max) at least for non-key columns? I haven't tried that.

I wouldn't necessarily block those features for tables without a key, but maybe a warning or a setting would be appropriate. You might still want to block those features if column types are non-comparable (ntext, text, image, and maybe more).

My OP was about tables that have a key, though.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build. I created this test table:

```
CREATE TABLE "textkey" (
	"name" NVARCHAR(50) NOT NULL COLLATE 'Latin1_General_CI_AS',
	"age" INT NOT NULL DEFAULT '0',
	PRIMARY KEY ("name")
);
```

And updated a row in the data grid, now with that "N" prefix in the WHERE clause:

    UPDATE "master"."dbo"."textkey" SET "age"='19' WHERE  "name"=N'helge🙈';

The right row was affected and I can see the modified age.
