### ISSUE TITLE
ProxySQL Admin Error

### ISSUE THREAD

**Issue by coboware** [HeidiSQL/HeidiSQL#1116]
When connecting to a proxysql loadbalancer admin interface (6032)
and selecting users get a sql error

Client on windows 10

FLUSH PRIVILEGES;
/* SQL Fout (1045): ProxySQL Admin Error: near "FLUSH": syntax error */

Proxy sql doesnot understand FLUSH PRIVILEGES;
https://github.com/sysown/proxysql/wiki/Users-configuration

**Comment by ansgarbecker** [comment]
Yes, there are plenty of commands which ProxySQL does not support. So you cannot use HeidiSQL for managing users here. I suppose you clicked on the "User manager" menu item or button?
Is there a reason why you did not use the issue template?
