### ISSUE TITLE
Display output servers list in more logical and alphabetical order

### ISSUE THREAD

**Issue by rickyheijnen** [HeidiSQL/HeidiSQL#1119]
**Is your feature request related to a problem? Please describe.**
I have around 50 servers in my HeidiSQL. When I use the export tool and want to output directly to another server (e.g. from staging to local server), the list of servers in the output dropdown is not sorted logically. Servers in the root folder are showed first, but not even in alphabetical order. Subfolders and servers are showed at last, but in reversed order.

**Describe the solution you'd like**
At least sort the list alphabetically so it's easier to find the server I need. For example use the same order as in the session manager.

**Describe alternatives you've considered**
For me personally; I use a lot of folders and subfolders to group projects with multiple servers (production, testing, local). It would be nice to first show the servers in the dropdown that are in the same subfolder as the one I'm exporting.

**Comment by ansgarbecker** [comment]
Thanks for respecting the issue template 👍

**Comment by rickyheijnen** [comment]
I see the same order is used in the menu that pops on to File > Connect to. There seems no logic in the order that is used. Please change it to alphabetically. Thank you 👍

**Comment by ansgarbecker** [comment]
Should be alphabtically in all menus now:
* drop down menu on connect button
* Main menu File > Connect to
* SQL export target combo box
