### ISSUE TITLE
Postgre - data window show error

### ISSUE THREAD

**Issue by yucikala** [HeidiSQL/HeidiSQL#1120]
when I want to see a data at postrge table:
![obrazek](https://user-images.githubusercontent.com/45132609/89778813-70665080-db0e-11ea-9dd0-ff81e6d30593.png)

tabke strcucture:
CREATE TABLE "Organization" (
	"Id" INTEGER NOT NULL,
	"Created" TIMESTAMP NOT NULL,
	"CreatedBy" INTEGER NOT NULL,
	"Modified" TIMESTAMP NULL DEFAULT NULL,
	"ModifiedBy" INTEGER NULL DEFAULT NULL,
	"ParentId" INTEGER NULL DEFAULT NULL,
	"ExternalId" TEXT NULL DEFAULT NULL,
	"Description" TEXT NULL DEFAULT NULL,
	"Logo" BYTEA NULL DEFAULT NULL,
	"Phone" TEXT NULL DEFAULT NULL,
	"Mail" TEXT NULL DEFAULT NULL,
	"IsInternal" BOOLEAN NOT NULL,
	"UseMultiFactor" BOOLEAN NOT NULL,
	"Name" TEXT NULL DEFAULT NULL,
	INDEX "IX_Organization_ParentId" ("ParentId"),
	PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Organization_Organization_ParentId" FOREIGN KEY ("ParentId") REFERENCES "public"."Organization" ("Id") ON UPDATE NO ACTION ON DELETE RESTRICT
)
;

**Comment by ansgarbecker** [comment]
Please rewrite this report using the bug report template.
