### ISSUE TITLE
Postgre - data window show error

### ISSUE THREAD

**Issue by yucikala** [HeidiSQL/HeidiSQL#1121]
when I want to see a data at postrge table:
obrazek
![obrazek](https://user-images.githubusercontent.com/45132609/89837378-23fc2e80-db69-11ea-9771-8eec4d3fe06a.png)

tabke strcucture:
CREATE TABLE "Organization" (
"Id" INTEGER NOT NULL,
"Created" TIMESTAMP NOT NULL,
"CreatedBy" INTEGER NOT NULL,
"Modified" TIMESTAMP NULL DEFAULT NULL,
"ModifiedBy" INTEGER NULL DEFAULT NULL,
"ParentId" INTEGER NULL DEFAULT NULL,
"ExternalId" TEXT NULL DEFAULT NULL,
"Description" TEXT NULL DEFAULT NULL,
"Logo" BYTEA NULL DEFAULT NULL,
"Phone" TEXT NULL DEFAULT NULL,
"Mail" TEXT NULL DEFAULT NULL,
"IsInternal" BOOLEAN NOT NULL,
"UseMultiFactor" BOOLEAN NOT NULL,
"Name" TEXT NULL DEFAULT NULL,
INDEX "IX_Organization_ParentId" ("ParentId"),
PRIMARY KEY ("Id"),
CONSTRAINT "FK_Organization_Organization_ParentId" FOREIGN KEY ("ParentId") REFERENCES "public"."Organization" ("Id") ON UPDATE NO ACTION ON DELETE RESTRICT
);

**Comment by ansgarbecker** [comment]
Please rewrite this report _using the bug report template_. This one is just a copy of #1120.

Reports which don't use the issue template will be closed.

**Comment by yucikala** [comment]
I dont know, where you want to have this report. Only I find this with bug template....

**Comment by ansgarbecker** [comment]
When you click on "New issue", click on "Bug report" > "Get started", then fill out the issue template:
![grafik](https://user-images.githubusercontent.com/7986591/89868938-e244a580-dbb3-11ea-9d82-381c3181e97c.png)
Please do not delete the template. Fill it with answers to the contained questions.
