### ISSUE TITLE
Data tab SQL error with LEFT([BYTEA column], 256)

### ISSUE THREAD

**Issue by yucikala** [HeidiSQL/HeidiSQL#1122]
**Describe the bug**
When i want to see a data - i get an error
![obrazek](https://user-images.githubusercontent.com/45132609/89895381-fc927980-dbdb-11ea-842b-84247bdaad06.png)

**To Reproduce**
1. Log to postre database
2. Click on table
3. click on Data panel

**Expected behavior**
No error message. 

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/45132609/89895728-9823ea00-dbdc-11ea-91cc-b057ee28ebc4.png)

**Environment:**
 - OS: Win 10 64bit 
 - HeidiSQL version [e.g. 11.0.0.6080]
 - Database type and version PostgreSQL 10.4 (Debian 10.4-2.pgdg70+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit

**Comment by ingpconci** [comment]
I've found the same error after updated the Heidisql.
I have a binary column.
Environment:
OS: Win 10 64bit
HeidiSQL version [e.g. 11.0.0.6081]
DB: PostgreSQL 12.3.0 on Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-112-generic x86_64)
![image](https://user-images.githubusercontent.com/8488830/89898722-7c6f1280-dbe1-11ea-8e55-37c986dd1c0f.png)

**Comment by ansgarbecker** [comment]
@yucikala please report the definition of that table.

**Comment by ingpconci** [comment]
I've verified the error with 2 Postgres installation:
1. Postgres 10.12 ; libpg10.dll
2. Postgres 12.3: libpg12.dll
My table is:
`
CREATE TABLE "appuser"."user" (
  "id" serial4,
  "email" varchar(256) NOT NULL,
  "password" varchar(256) NOT NULL,
  "firstname" varchar(45),
  "lastname" varchar(45),
  "usericon" bytea,
  "enabled" bool NOT NULL DEFAULT false,
  "usertype_id" int4 NOT NULL,
  "userstatus_id" int4 NOT NULL,
  "registration_time" timestamptz,
  "email_confirmation_token" varchar(256),
  "password_reminder_token" varchar(256),
  "organization_id" int4,
  CONSTRAINT "_copy_11" PRIMARY KEY ("id"),
  CONSTRAINT "unique_user_email" UNIQUE ("email")
);
`
The error in Heidi console is;
SELECT  "id",  "email",  "password",  "firstname",  "lastname",  LEFT("usericon", 256),  "enabled",  "usertype_id",  "userstatus_id",  "registration_time",  "email_confirmation_token",  "password_reminder_token",  "organization_id" FROM "appuser"."user" LIMIT 1000;
/* ERROR:  function left(bytea, integer) does not exist
LINE 1: ..."email",  "password",  "firstname",  "lastname",  LEFT("user...                                                       ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts. */

**Comment by ansgarbecker** [comment]
Should be fixed in the next build, in half an hour.

Please update to the upcoming nightly build and verifiy whether this looks fixed for you as well.

**Comment by ingpconci** [comment]
I try with the new version and now the program show the records.
But I try to import a png file on the binary field usericon 
![image](https://user-images.githubusercontent.com/8488830/89945015-fecaf700-dc20-11ea-9395-ab4c34348429.png)
the program crashed

`executable         : heidisql.exe
exec. date/time    : 2020-08-11 22:12
version            : 11.0.0.6082
compiled with      : Delphi 10.4 Sydney
madExcept version  : 5.0.99
callstack crc      : $586c79bc, $1d033b51, $1d033b51
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 0000000000C21506 in module 'heidisql.exe'. Write of address 0000000000000080.

main thread ($50a0):
00c21506 heidisql.exe grideditlinks    276  +2 TBaseGridEditorLink.Destroy
00c22034 heidisql.exe grideditlinks    478  +1 THexEditorLink.Destroy
0041ad52 heidisql.exe System                   TInterfacedObject._Release
00418f3b heidisql.exe System                   @IntfClear
0096b364 heidisql.exe VirtualTrees   19851 +29 TBaseVirtualTree.DoEdit
009668e6 heidisql.exe VirtualTrees   17863  +7 TBaseVirtualTree.WMTimer
0040ed32 heidisql.exe System                   TObject.Dispatch
006ccfbd heidisql.exe Vcl.Controls             TControl.WndProc
006d422b heidisql.exe Vcl.Controls             TWinControl.WndProc
00979e9c heidisql.exe VirtualTrees   25646 +32 TBaseVirtualTree.WndProc
006d33fa heidisql.exe Vcl.Controls             TWinControl.MainWndProc
00568793 heidisql.exe System.Classes           StdWndProc
7ff95d35 USER32.dll                            DispatchMessageW
0088b1ee heidisql.exe Vcl.Forms                TApplication.ProcessMessage
0088b263 heidisql.exe Vcl.Forms                TApplication.HandleMessage
0088b6b1 heidisql.exe Vcl.Forms                TApplication.Run
00f16838 heidisql.exe heidisql         103 +41 initialization
7ff95dcd KERNEL32.DLL                          BaseThreadInitThunk
7ff95f1f ntdll.dll                             RtlUserThreadStart`

**Comment by ansgarbecker** [comment]
Thanks for your feedback. That crash has nothing to do with the LEFT issue reported here. You may file a new bug report for that thing - but please respect the issue template!
