### ISSUE TITLE
Exporting rows from table of Postgres

### ISSUE THREAD

**Issue by Setitch** [HeidiSQL/HeidiSQL#1124]
**Describe the bug**
Exporting rows from data tab for table makes very strange (but understandable) errors.

**To Reproduce**
1. Have table named as "guidelines-division" (to table name that requires name escaping)
2. Go into data tab of that table
3. Select any rows (non zero)
4. Right click and and use:  Export grid rows
5. Select sql insert and go

**What was returned (example row)**
INSERT INTO """guidelines-divisions""" ("guidelineId", "value") VALUES (1, 'IM');

**Expected behavior**
INSERT INTO "guidelines-divisions" ("guidelineId", "value") VALUES (1, 'IM');

**Environment:**
 - OS: [Windows 10]
 - HeidiSQL version [11.0.0.5919]
 - Database type and version [Postgres 11.6]

**Comment by ansgarbecker** [comment]
Same here - please retry with the latest HeidiSQL build.

**Comment by Setitch** [comment]
**With newest version - outcome is exactly the same**
```
INSERT INTO """guidelines-divisions""" ("guidelineId", "value") VALUES (11, 'IM');
INSERT INTO """guidelines-divisions""" ("guidelineId", "value") VALUES (12, 'IM');
INSERT INTO """guidelines-divisions""" ("guidelineId", "value") VALUES (13, 'IM');
INSERT INTO """guidelines-divisions""" ("guidelineId", "value") VALUES (14, 'IM');
```

**Comment by ansgarbecker** [comment]
This is due to `SELECT 123::regclass` returns identifiers already quoted. I will unquote these before proceeding in the code.
