### ISSUE TITLE
can't edit view after modified source table

### ISSUE THREAD

**Issue by sergiokessler** [HeidiSQL/HeidiSQL#1130]
**Describe the bug**
If you modify a table (rename a field name), you cannot edit the view in HeidiSQL anymore.

**To Reproduce**
1. run a `alter table foo rename a to c`
2. Click on view using field `foo.a`
3. See error
4. You can't edit the source of the view anymore

**Expected behavior**
An error, but let me access the source of the view so I can fix it.

**Screenshots**
N/A

**Environment:**
 - HeidiSQL version 11.0.0.6062
 - Database type Mysql 5.7

**Comment by ansgarbecker** [comment]
What's the error message here? Screenshot would also be nice.

**Comment by sergiokessler** [comment]
you do something like this:

`ALTER TABLE foo
	CHANGE COLUMN bar bar_renamed VARCHAR(16) NOT NULL COLLATE 'utf8mb4_bin';`

and when you then select the VIEW that uses the field `foo.bar`, you see something like this:

![image](https://user-images.githubusercontent.com/14111329/90201839-66647c00-ddb2-11ea-850d-372ae11bd7ac.png)

and you **cannnot** edit the view to fix it
and that's the problem, I'm ok with the error...

**Comment by sergiokessler** [comment]
Also, it should be easy to copy & paste the error message...

**Comment by ansgarbecker** [comment]
In these message dialogs, you can press <kbd>Ctrl+C</kbd> to copy it as text. That's not only doable in HeidiSQL, but in most Windows programs.

So, the view editor should be accessible although there is an SQL error? Well, probably in this particular query, it may not have huge consequences to ignore errors. But you should notice that the error is happening on the second of 5 queries which are used to initialize the view editor. I just tried them all but only the second one throws that error:

```sql
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='test5' AND TABLE_NAME='ort_da_v' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `ort_da_v` FROM `test5`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='test5'   AND TABLE_NAME='ort_da_v'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='test5'   AND TABLE_NAME='ort_da_v'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE VIEW `test5`.`ort_da_v`;
SELECT CAST(LOAD_FILE(CONCAT(IFNULL(@@GLOBAL.datadir, CONCAT(@@GLOBAL.basedir, 'data/')), 'test5/ort_da_v.frm')) AS CHAR CHARACTER SET utf8);
```
I can probably let HeidiSQL proceed after errors in that special query.

**Comment by ansgarbecker** [comment]
Please update HeidiSQL to the latest build and retry.

By the way: to make a screenshot of a message dialog or any window, just press <kbd>Alt+Print</kbd> (or use a screenshot tool like [Greenshot](https://getgreenshot.org/)).

**Comment by sergiokessler** [comment]
ok, I've updated HeidiSQL and it's fixed, thanks !! ☺️
