### ISSUE TITLE
REQ: Code folding

### ISSUE THREAD

**Issue by tkdennis** [HeidiSQL/HeidiSQL#1132]
**Is your feature request related to a problem? Please describe.**
I have long scripts that are hard to find code sections

**Describe the solution you'd like**
I would like code folding to be implemented:
\#region (header stuff)
    (code here)
\#endregion

\#region (different header stuff)
    (different code here)
\#endregion

**Describe alternatives you've considered**
I've tried to remember the line numbers but I forget and still takes a long time to scroll looking for headers or do Search for header keyword and find too much code words. I currently use a different editor to fold code and see the headers to copy/paste into search.

**Additional context**
This is perfect!! https://www.heidisql.com/forum.php?t=36736#p36744

**Comment by ansgarbecker** [comment]
So, the next build will have a new button for enabling support for code folding:

![grafik](https://user-images.githubusercontent.com/7986591/90332843-b0bb4800-dfc0-11ea-89c0-3e7f3b886e52.png)

Note that word-wrapping is disabled when code-folding is enabled. This is a known limitation in SynEdit, but should not harm too many users.

I think I need to add this button also into a new main menu, named "SQL" or similar. There are few commands you already found in the shortcuts which would be neat to have them in such a menu, such as "Fold all" and "Unfold all". Also some other items like "Run", "Run current query" and these should be there.

**Comment by tkdennis** [comment]
Thank you!!!

**Comment by ansgarbecker** [comment]
I'm scratching my head as I don't have a clue how to translate "Code folding" into German.

**Comment by tkdennis** [comment]
There may not be a translation?

https://german.stackexchange.com/questions/3506/translation-of-it-term-code-folding

**Comment by tkdennis** [comment]
FYI - I downloaded Nightly build 11.0.0.6094, cold folding works great! Thank you!!
