### ISSUE TITLE
[sqlite] Drop table disabled in context menu

### ISSUE THREAD

**Issue by Madjosz** [HeidiSQL/HeidiSQL#1133]
**Describe the bug**
Currently there is no possibility to drop tables in SQLite in the UI. The entry in the context menu is disabled, although it is possible to drop the table with `DROP TABLE "tablename";`.

**To Reproduce**
1. Create an new table
2. Right click on the table
3. See that "Drop ..." is disabled
4. Fail to ever get rid of it without using plain SQL.

**Expected behavior**
The option should be enabled and provide the functionality to drop the table

**Screenshots**
![grafik](https://user-images.githubusercontent.com/28844868/90508273-b4cd9e00-e157-11ea-89be-3e65f827ca67.png)

**Environment:**
 - OS: Windows 10 Pro 1903 Build 18362.959
 - HeidiSQL version 11.0.0.6089 (64-bit)
 - SQLite

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.

**Comment by Madjosz** [comment]
Confirmed works. Thank you and keep up the good work!
