### ISSUE TITLE
[sqlite] Table with empty name leads to odd behaviour

### ISSUE THREAD

**Issue by Madjosz** [HeidiSQL/HeidiSQL#1134]
**Describe the bug**
SQLite allows the table name to be the empty string. This leads to odd behaviour in the UI:

- When creating a new table with blank name, the "Save" button is disabled (like in e.g. MySQL)
- When clicking on another table/database, the dialog "Save new table?" open, allowing to save the table without a name (this is also possible in MySQL but there the database will reject empty names)
- A new table with empty name will appear.
- When clicking on "Edit", no columns are visible in the table editor, although one can see them in the "data" tab and also can insert values into the columns.

**To Reproduce**
1. Rightclick on an SQLite database
2. Select "Create new -> Table"
3. Add a column in the table editor
4. Notice the disabled "Save" button
5. Click on any other table or the database session
6. The "Save new table?" dialog appears
7. Select "Yes"
8. Select new table with empty name
9. Notice no columns displayed in the table editor

**Expected behavior**
Since the empty name is a valid table identifier in SQLite it should be supported properly

**Screenshots**
![grafik](https://user-images.githubusercontent.com/28844868/90511681-1c3a1c80-e15d-11ea-9929-9127d99efebd.png)

**Environment:**
 - OS: Windows 10 Pro 1903 build 18362.959
 - HeidiSQL version 11.0.0.6089 (64-bit)
 - SQLite

**Comment by ansgarbecker** [comment]
Empty table names are so odd, I won't support that. Sorry.

**Comment by Madjosz** [comment]
I understand your point. Consider then to include a check for the "Save new table?" dialog to avoid creting tables with empty names. As I said, in MySQL it is also possible, only the server will reject your request.

**Comment by ansgarbecker** [comment]
Yes, that save prompt should just say "lose changes?" or similar, as long as there is no name.

**Comment by semenenkov** [comment]
BTW, SQLite also allows empty **column** names. That's not a request to fix something, just a note that it may also cause some issues.
