### ISSUE TITLE
Add "Create code" in views like "Create Code" in Tables/Functions/Procedures

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#1135]
**Is your feature request related to a problem? Please describe.**
Would like to add a CREATE CODE in views, its helps what parameters will be used in a simple create view, I had problens when I migrate some views using default values.

**Describe the solution you'd like**
Add a create area, like we have in TABLES, PROCEDURES, FUNCTIONS

**Describe alternatives you've considered**

**Additional context**
Like this (tables)
![image](https://user-images.githubusercontent.com/11230133/90658213-ac3d9c00-e219-11ea-85a0-ec9687e69f65.png)

or this (procedures)
![image](https://user-images.githubusercontent.com/11230133/90658294-ca0b0100-e219-11ea-80a6-0cadb74c349f.png)

Here (views)
![image](https://user-images.githubusercontent.com/11230133/90658251-ba8bb800-e219-11ea-86f6-506265b4811b.png)

**Comment by ansgarbecker** [comment]
Done for the next build:
![grafik](https://user-images.githubusercontent.com/7986591/102685977-c21d9680-41e4-11eb-8e04-34876be5802a.png)

**Comment by lukinhaspm** [comment]
I Know I'm late, but THANKS... hahahaha
I only see this now...!
