### ISSUE TITLE
Error viewing data tab with MSSQL

### ISSUE THREAD

**Issue by hrunting** [HeidiSQL/HeidiSQL#1136]
When I try to view the Data tab of MS SQL tables, I receive the following error:

`SQL Error (8116): Argument data type ntext is invalid for argument 1 of left function.`

The SQL that fails is:

`SELECT TOP 1000  "a",  "b",  "c",  "d", LEFT("e", 256),  "f",  "g",  "h",  "i",  "j",  "k" FROM "xxx"."yyy"."zzz";`

This appears to only happen with tables that have fields defined with the "NTEXT" data type. MS SQL Server version is 12.0.4232.0, and I am using the 18.4 version of the Microsoft OLE DB Driver for SQL Server. HeidiSQL version is 11.0.0.6093.

**Comment by mftun** [comment]
For TEXT type (without N) same error.

**Comment by lakebranch** [comment]
From what I understand, TEXT and NTEXT will be deprecated in a future version of MSSQL but I'm guessing we will be stuck with them for a long time for compatibility reasons. The previous sentence was mostly written as a disguised +1 (I'm also experiencing the error with the TEXT data type). :)

**Comment by ug-code** [comment]
my HeidiSQL version is 11.0.0.6094.
 I still get an error 
![image](https://user-images.githubusercontent.com/17679067/91158709-b9ea9a00-e6cf-11ea-97e7-eb70818b3592.png)

**Comment by lakebranch** [comment]
Is there something I can do to help with this issue? It's preventing me from using the data tab in many of my connections since they use the TEXT (without N) type. A workaround is to write the query manually in a query tab for every table.

**Comment by ansgarbecker** [comment]
No, it's up to me fixing this - you can just sit and wait :)
I did not realize there are so many TEXT columns in the world. Will try to get it fixed soon.

**Comment by fivevalve** [comment]
In case you don't know:
11.0.0.5919 uses this for TEXT columns (works ok):
LEFT(CAST("<colname>" AS NVARCHAR(256)), 256)
Some newer version changed to just (error):
LEFT("<colname>", 256)

**Comment by fivevalve** [comment]
Commit e8248c41776970183774e96f0bd0aac4720d1950 on 2020-08-22 shows "Closes #1136." but this still happens for TEXT columns in heidisql64.r6099.exe (11.0.0.6099).  Shows in source/dbconnection.pas line 9204:
      if DataType.Index in [dtUnknown, dtNtext] then
probably needs (I'm guessing about type)
      if DataType.Index in [dtUnknown, dtNtext, dtText] then

**Comment by ansgarbecker** [comment]
`TEXT` fields now also get a `CAST(... AS NVARCHAR(256))` in the `LEFT()` clause. Horrible workaround for an avoidable incompatibility on the Microsoft side.
