### ISSUE TITLE
Query editor has some problem rendering Khmer Unicode and Thai font 

### ISSUE THREAD

**Issue by steviejs** [HeidiSQL/HeidiSQL#1137]
**Describe the bug**
Query editor has some problem rendering Khmer Unicode and Thai font as it appears to have too much space in between the characters. 

Here below is the text for your testing: 
```sql
/* សម្រាប់ធ្វើការរក្សាទុកទិន្នន័យ  This comment line appear too much space for KHMER Unicode font */
/* บรรทัดความคิดเห็นนี้มีช่องว่างขนาดใหญ่เกินไป Seems to have similar space problem with Thai font */
/* 此评论行的空格太大 It seems OK with chinese font*/ 
```

Recommended Khmer Unicode Font: Khmer OS Content or Khmer OS Siem Reap

![CorrectRenderingOnNotePad](https://user-images.githubusercontent.com/69964467/90755789-bdfc6d80-e305-11ea-9001-52e48fae25cd.PNG)
![HeidiSQL-QueryEditor](https://user-images.githubusercontent.com/69964467/90755800-c48ae500-e305-11ea-9642-896ae11c77bb.PNG)

**Environment:**
 - OS: Windows 10
 - HeidiSQL version [11.0.0.6093]
 - Database type and version [MySQL 8.0.20]

**Comment by ansgarbecker** [comment]
I think this is an issue with international characters in the SQL editors, which are instances of the SynEdit component. I can reproduce that when comparing with Notepad, while using the same font and size as in Heidi's editors (Consolas/10pt in both):

![grafik](https://user-images.githubusercontent.com/7986591/90863853-fea0c900-e38f-11ea-97c8-39a8c7ad0727.png)

I cannot fix that in HeidiSQL itself. You will have to report that in the [SynEdit project](https://github.com/SynEdit/SynEdit), or provide a pull request with a bugfix for them.
