### ISSUE TITLE
nightly 9.5.0.5227 crashes on Windows XP

### ISSUE THREAD

**Issue by FBachofner** [HeidiSQL/HeidiSQL#114]
nightly 9.5.0.5227 crashes on Windows XP SP3

This version was created to address Windows 10 issues.  Is Windows XP not going to be supported going forward?

[ 9.5.0.5226 nightly still seems to work fine on XP ]

**Comment by ansgarbecker** [comment]
I'll try to support XP as long as I can. I am just not testing it any longer, so thanks for the quick feedback.

**Comment by FBachofner** [comment]
Hi Ansgar:

You're welcome.
I'll keep an eye out for you in future nightlies.

I bet after Firefox completely drops XP esr (extended service release) support in May 2018, Windows XP usage will plummet.

**Comment by ansgarbecker** [comment]
Anyway, I decided to support it, as there seem to be third world countries in which XP is still heavily in use.

Should work now again, in the new build.

**Comment by FBachofner** [comment]
The crash on open is definitely fixed with HeidiSQL_9.5.0.5229
I'll keep testing to see whether there are any other issues.

Thanks Ansgar!
