### ISSUE TITLE
application freeze after update to Windows 10 Version 2004

### ISSUE THREAD

**Issue by EugenNY** [HeidiSQL/HeidiSQL#1140]
Hello. I have been using HeidiSQL on Windows 10 for a few years daily, and this is the first time it completly freezes on me.
It happened directly after a Windows 10 upgrade to version 2004.
1. Launch HeidiSQL
2. connect to MySQL db
3. Here is the connection log
```
/* Connecting to localhost via MySQL (TCP/IP), username myuser, using password: Yes ... */
SELECT CONNECTION_ID();
/* Characterset: utf8mb4 */
SHOW /*!50002 GLOBAL */ STATUS;
SELECT NOW();
SHOW VARIABLES;
/* Connected. Thread-ID: 124681435 */
SHOW OPEN TABLES FROM mydbname WHERE `in_use`!=0;
/* Entering session "db01" */
```
4. now a double-click on the database name in the left pane to make it show you all the tables will result in a freeze
5. you can see how its doing the following commands before freezing:
```
SELECT `DEFAULT_COLLECTION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME` = 'mydbname`;
SHOW TABLE STATUS FROM `mydbname`;
```
and thats all you get. after the last line the application is entirely frozen and I have to kill the process.

This happened with a ~1 month old HeidiSQL version and after an update to v11.0.0.6094

MySQL version should be 5.6.10 (its an AWS RDS instance)
```
aurora_version	1.19.0
innodb_version	1.2.10
protocol_version	10
slave_type_conversions	
version	5.6.10
version_comment	MySQL Community Server (GPL)
version_compile_machine	x86_64
version_compile_os	Linux
```
I tried libmaria and libmysql but none work.

Using Windows 10 Pro on a recent ThinkPad with 16GB RAM.

**Comment by ansgarbecker** [comment]
Was there a reason why you deleted the issue template?

**Comment by anscosta68** [comment]
hi, i use heidiSQL a long time and after update to the last version 11  it always crash in windows 10 pro 64bits,.
I work for a while and suddenly the software crash.

**Comment by EugenNY** [comment]
closing this. after a while the problem had disappeared. i couldnt tell why. perhaps infact the AWS RDS instance was freezing?
still, i think the UI thread shouldnt freeze.

p.s. i thought i had made a good bug description. it was easier to be free in expressing the problem.
