### ISSUE TITLE
Hope to increase the table structure comparison synchronization and table data comparison synchronization like Navicat, thank you! 

### ISSUE THREAD

**Issue by yuwenlong** [HeidiSQL/HeidiSQL#1143]
**Is your feature request related to a problem? Please describe.**
When the new function developed is online, I need to write and execute new SQL statements, add columns and indexes, I feel frustrated.

**Describe the solution you'd like**
Hope to increase the table structure comparison synchronization and table data comparison synchronization like Navicat, thank you! 

**Describe alternatives you've considered**
Please refer to Navicat.

**Additional context**
![image](https://user-images.githubusercontent.com/11555324/91681188-31ad3e80-eb80-11ea-89e1-0cd3356eeb61.png)

**Comment by ansgarbecker** [comment]
You will need to describe **in detail** what you want to see in HeidiSQL. "Please refer to Navicat" is not sufficient.

**Comment by yuwenlong** [comment]
Hope to increase the table structure comparison synchronization and table data comparison synchronization like Navicat, thank you!

**Comment by ansgarbecker** [comment]
Description is insufficient here. Again, please describe in detail what you want to see in HeidiSQL. "Please refer to Navicat" or "like Navicat" is not sufficient.
