### ISSUE TITLE
Cannot edit column values in temporal tables

### ISSUE THREAD

**Issue by stefanfrings2** [HeidiSQL/HeidiSQL#1144]
I cannot edit any column value in temporal tables.

Steps to reproduce:

CREATE TABLE test (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(40)
) ENGINE=InnoDB WITH SYSTEM VERSIONING;

INSERT INTO test (id,username) VALUES
  (1,'Maria'),
  (2,'Heidi');

Refresh the tree view on the left side. Navigate to the table and display its content -> OK

Double click on any value (e.g. Heidi) and try to edit it. I see a blinking text cursor, but the field seems to be write protected because I cannot enter any character. 

Right click on the table and select the command to insert a new row. An error message appears: "Selected columns don't contain a sufficient set of key columns to allow editing ...".

Heidi SQL 11.0.0.5919 64bit in Debin 10 with wine

**Comment by ansgarbecker** [comment]
Please rewrite the issue, using the issue template. And please refer to the latest build (not latest release) of HeidiSQL (currently 11.0.0.6096).
