### ISSUE TITLE
escaped underscore in database name

### ISSUE THREAD

**Issue by sergiokessler** [HeidiSQL/HeidiSQL#1147]
**Describe the bug**
The escaped underscore character `_` is causing havoc with other tools

**To Reproduce**
1. Go to Tools -> User manager -> (select user) -> Add object with underscore in it

![image](https://user-images.githubusercontent.com/14111329/92418192-9d714780-f13c-11ea-86d5-3d39fde9c9e8.png)

the problem is that different database management tools are confused with the permissions granted by Heidi, because they see `foo\_bar` different than `foo_bar`

(using mysql 8)

**Expected behavior**
`_` should not be escaped in the database name

**Comment by ansgarbecker** [comment]
Grants should be correctly set, not in a way other tools expect it in a broken way. `foo_bar` also allows database names like 'foo1bar' or 'fooAbar', or whatever. While `foo\_bar` allows exactly and only 'foo_bar'.

You should file a bug report in the ticket system of these tools.
