### ISSUE TITLE
Limit Number of Rows per Insert Statement when exporting a table

### ISSUE THREAD

**Issue by ubermanl** [HeidiSQL/HeidiSQL#1148]
It would be awesome to be able to indicate the maximum amount of rows when exporting a table or a set of tables.

Ii. MSSqlServer only allows 1000 Rows per insert, otherwise indicates :

> The number of row value expressions in the INSERT statement exceeds the maximum allowed number of 1000 row values.

For example, the check already exists, to limit chunks of inserts to certain amount of KB, perhaps something similar, but representing rows instead of text size.

**Comment by ansgarbecker** [comment]
Please rewrite the report using the issue template.
