### ISSUE TITLE
Table Field Regex filter would better be cleared when user switches tables

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#1149]
**Is your feature request related to a problem? Please describe.**
Currently Regex filters in HeidiSQL tabs aren't cleared everywhere when we switch tables or databases or servers. It could be annoying when you apply filter to find some column in a complex table structure view and then switch to another table. Filter keeps its value that applied silently to that table structure view hiding its columns.

**Describe the solution you'd like**
Make all regex filters to be auto-clearable on switching table/database/server

**Describe alternatives you've considered**
May be make a checkbox like "keep filter value" unchecked by default.

**Additional context**
![image](https://user-images.githubusercontent.com/43061117/92594404-61102980-f2ab-11ea-91f4-83d2252c7be7.png)

**Comment by ansgarbecker** [comment]
Done in the next build.
