### ISSUE TITLE
Ability to sort columns by name in table structure

### ISSUE THREAD

**Issue by Hannessa** [HeidiSQL/HeidiSQL#115]
## Expected behavior

When you have many columns in a table, it would be very useful to be able to sort columns by name when viewing the table structure, without the risk of modifying the structure (i.e. you should not be able to save your changes, and the column id:s should remain unchanged). This would help you locate columns much more quickly in large tables with 50+ columns.

Screenshot and an old discussion can be found here:
https://sourceforge.net/p/heidisql/tickets/1373/

My suggestion is that this type of sorting should not modify the table structure ("Save" button should still be grayed out), and basically work just like sorting when viewing data, which is just for viewing purposes. If possible, the sort order could be remembered by HeidiSQL internally for that table, but if that means a lot of extra work, it could just reset the order next time you view the table structure. The order of columns should not carry over to the Data tab when viewing data, or at least that's not my main request.

I can understand if this is a bit tricky to implement considering there's the ability to reorder columns permanently by drag-and-drop, which is nice to have as well. But I think it would be a very useful feature to have.

## Current behavior

Sorting columns by name in the table structure is not possible.

**Comment by lukinhaspm** [comment]
I agree with your suggestion. Keeping the number of column in table to sort in default view will be great too.

**Comment by rentalhost** [comment]
I think that this solution is pretty hard to implement, once that the column "new position" could confuses the Table editor on defines the `AFTER` keyword. I think that the best solution here is avoid long tables - I know that legacy system probably uses few tables with a lot of columns, but I too think that it should be treated as exception for now.

**Comment by ansgarbecker** [comment]
There is also the filter panel, with regular expression support, with default shortcut <kbd>Ctrl+Alt+F</kbd>

I think the implementation is not a big deal here, but that can confuse many people due to seeing a column order which is different from the physical one. On the other hand we already have column numbers on the very left.

**Comment by penCsharpener** [comment]
being able to sort columns by clicking on the column header would be useful but even better and maybe easier to implement is to make the filter `ctrl+alt+F` permanently visible. I never new about it until reading this hear. I don't think it would overload the UI either if that ever was  concern. Also as a daily Heidi user I'm used to having the filter at the top, not the bottom of the grid. 
This is going into a different direction. Should I create an issue for this?

**Comment by ansgarbecker** [comment]
@penCsharpener I guess your point is really different, and should be discussed in a new issue, if it's still worth it.
