### ISSUE TITLE
Switching between 2 query tabs multiple times closes tab

### ISSUE THREAD

**Issue by imqqmi** [HeidiSQL/HeidiSQL#1151]
**Describe the bug**
When switching between 2 query tabs repeatedly (without hitting the close X button) it will close one of the tabs. Anywhere between 8-20x switching will close one tab.

**To Reproduce**
1. Load sql file from snippets in the first query tab (the unclosable one)
2. Create two new empty query tabs
3. click the empty tabs at about 1 second rate from one to the other and back until a tab closes (takes about 8-20 times)

**Expected behavior**
Tabs should only close when hitting the close button, not upon switching tabs. So clicking on the tab title shouldn't close the tab even when switching 1000x.

**Screenshots**

**Environment:**
- Windows 10 version 1909 (os build 18363.959)
- HeidiDB version 11.0.0.5919
- MariaDB 10.4.8

**Comment by ansgarbecker** [comment]
I just tried that, switched 30 times back and forth, without one of them getting closed. Are you sure you did not click faster than 1s - in which case that may have been a double click, which closes a tab? If you leave less than [GetDoubleClickTime](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdoubleclicktime) between clicks, it's a doubleclick.
Or you perhaps hit the "x" button on the tab.

**Comment by WesleyM77** [comment]
Is the double click to close an option/preference? I can imagine some people wanting to disable that, myself included.

**Comment by imqqmi** [comment]
Weird, after reloading the application I can't seem to reproduce it. When it does it again, I will record a video. 

I definitely didn't click the close button, nor did I double click. I've reproduced it about 10x before commiting this as a issue to make sure.
If a quick click-click action from one tab to the next is seen as double click then that could also be a problem.

**Comment by ansgarbecker** [comment]
Some investigations:
* GetDoubleClickTime is 410 ms on my Win10 Pro. I did not change it yet, nor do I know where to change that. Scratching my head why it's not 400ms.. hohum
* A double click on a tab is only triggered if you a) do it quicker than these 410ms, and with the second click on the same tab. It does not trigger if you click on different tabs, even not if you manage to do it quick enough
* if it's really worth it, I can add an option to turn off tab closing by doubleclick. That checkbox option should live in _Tools > Preferences > Files_, and _Files_ should anyway be renamed to _Tabs_

**Comment by WesleyM77** [comment]
Personally, I don't often accidentally double click tabs, but it's happened to me a few times. I'd appreciate the option, but won't lose sleep over it if you don't feel it's worth the time.

**Comment by mario-nexa** [comment]
Please Ansgar, add an option to turn off tab closing by doubleclick. 
PS: thank you for the great software!!!

**Comment by ansgarbecker** [comment]
New checkbox option created in Tools > Preferences > Files and Tabs: "Close tab on doubleclick and middleclick"
