### ISSUE TITLE
"Library libpq-10.dll" could not be loaded

### ISSUE THREAD

**Issue by exoRift** [HeidiSQL/HeidiSQL#1153]
I have installed Heidi and I tried uninstalling and reinstalling, but any time I try to connect to connect to a database, I get this error, (Also happens with libpq-12)

![image](https://user-images.githubusercontent.com/20345400/92856783-d53cf100-f3c1-11ea-8485-219ec8fa85ff.png)

**Environment:**
 - OS: Windows 10
 - HeidiSQL version: 11.0.0.6097
 - Database type and version: Postgres 12.4

**Comment by ansgarbecker** [comment]
Please use the issue template for reports.

The message already gives the hint that a runtime library may be missing. Please install it and retry.

**Comment by exoRift** [comment]
I did though
