### ISSUE TITLE
EAccessViolation exception ......

### ISSUE THREAD

**Issue by uuxii** [HeidiSQL/HeidiSQL#1156]
When some tables been modified ，some execption are throw... 
the bugreport.txt :

date/time          : 2020-09-13, 17:42:00, 789ms
computer name      : DESKTOP-SK71K17
user name          : VKER
registered owner   : VKER
operating system   : Windows 10 x64 build 18363
system language    : Chinese (Simplified)
system up time     : 1 day 2 hours
program up time    : 10 minutes 41 seconds
processors         : 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
physical memory    : 9015/12182 MB (free/total)
free disk space    : (C:) 56.24 GB
display mode       : 2560x1440, 32 bit
process id         : $23b0
allocated memory   : 162.09 MB
largest free block : 131025.95 GB
executable         : heidisql.exe
exec. date/time    : 2020-09-12 15:10
version            : 11.0.0.6097
compiled with      : Delphi 10.4 Sydney
madExcept version  : 5.0.99
callstack crc      : $92a795cf, $872df029, $872df029
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 00000000009801F5 in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF.

main thread ($b08):
009801f5 heidisql.exe VirtualTrees   28602   +7 TBaseVirtualTree.GetNodeData
00ef410e heidisql.exe Main            8987   +7 TMainForm.DBtreeInitNode
0096c789 heidisql.exe VirtualTrees   20367   +2 TBaseVirtualTree.DoInitNode
00972f2d heidisql.exe VirtualTrees   22860  +12 TBaseVirtualTree.InitNode
0097d4ad heidisql.exe VirtualTrees   26962   +5 TBaseVirtualTree.GetDisplayRect
00982396 heidisql.exe VirtualTrees   29770   +7 TBaseVirtualTree.InvalidateNode
0098f65d heidisql.exe VirtualTrees   34591   +1 TCustomVirtualStringTree.InvalidateNode
0096b8fb heidisql.exe VirtualTrees   19991  +29 TBaseVirtualTree.DoFocusNode
00972788 heidisql.exe VirtualTrees   22678 +261 TBaseVirtualTree.HandleMouseDown
00965525 heidisql.exe VirtualTrees   17341   +6 TBaseVirtualTree.WMLButtonDown
0040ed32 heidisql.exe System                    TObject.Dispatch
00979e02 heidisql.exe VirtualTrees   25633  +19 TBaseVirtualTree.WndProc
006d33fa heidisql.exe Vcl.Controls              TWinControl.MainWndProc
00568793 heidisql.exe System.Classes            StdWndProc
7ff99a1a USER32.dll                             DispatchMessageW
0088b1ee heidisql.exe Vcl.Forms                 TApplication.ProcessMessage
0088b263 heidisql.exe Vcl.Forms                 TApplication.HandleMessage
0088b6b1 heidisql.exe Vcl.Forms                 TApplication.Run
00f17978 heidisql.exe heidisql         103  +41 initialization
7ff99a34 KERNEL32.DLL                           BaseThreadInitThunk
7ff99c0a ntdll.dll                              RtlUserThreadStart

the picture:      http://uuxii.cc/execption.png

**Comment by ansgarbecker** [comment]
Please retry with v12.0
