### ISSUE TITLE
Geometry data Type

### ISSUE THREAD

**Issue by Amphibitus** [HeidiSQL/HeidiSQL#1157]
I like to work with HeidiSQL. Realy a great job.  
Mainly I work  with geometry Databases (MARIADB, SQLITE (Geopackage) etc.)

The GEOMETRY type data by heidisql ,it's hard to view,

![grafik](https://user-images.githubusercontent.com/7237786/93080288-bd998d00-f68d-11ea-8671-079ba9e14303.png)

here a sample, to make it better

![grafik](https://user-images.githubusercontent.com/7237786/93080597-3b5d9880-f68e-11ea-9ec3-a82f4e615366.png)

**Comment by ansgarbecker** [comment]
Please rewrite the issue report, and use the feature request template for it.

**Comment by ansgarbecker** [comment]
Even better: leave a comment in the already opened #373
