### ISSUE TITLE
insert database name to sql query on doubleclick

### ISSUE THREAD

**Issue by yucikala** [HeidiSQL/HeidiSQL#1159]
**Describe the bug**
When i make doubleclick on database name, it open tables (correct), and insert databse name to sql query (and very often damage query).

**To Reproduce**
1. open sql query tab
2. Make double click on database name
4. See  database name at query tab

**Expected behavior**
Open only tables

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/45132609/93261803-83221400-f7a3-11ea-8e1e-b655fcbaf694.png)

**Environment:**
![obrazek](https://user-images.githubusercontent.com/45132609/93261875-9b922e80-f7a3-11ea-903f-54de28e02692.png)

**Comment by ansgarbecker** [comment]
This is intentionally, you should either
* click the expand/collapse symbol left besides the name
* or activate "Tree style options" > "Auto expand on click" (via right click in the tree)
* or disable text insertion in "Tree style options" > "Doubleclick inserts node text":

![grafik](https://user-images.githubusercontent.com/7986591/93297269-3d8c3800-f7f1-11ea-8514-ed858ce00d1b.png)
