### ISSUE TITLE
User Interface does not correctly display Unsigned status of column

### ISSUE THREAD

**Issue by ffvictor** [HeidiSQL/HeidiSQL#1161]
**Describe the bug**
When creating rows with Unsigned fields in MySQL, the user interface does not show checked checkboxes in the table layout editor. Only when you enable zerofill, the UI shows the checkboxes as checked.

**To Reproduce**
1. Create a table with unsigned fields (see screenshot1)
2. Open table editor and observe missing checkboxes in UI (screenshot2)

**Expected behavior**
Checkboxes should reflect unsigned-ness of rows.

**Screenshots**
![image](https://user-images.githubusercontent.com/59561259/93718520-3e202800-fb7d-11ea-9025-ce8d7a20c93c.png)
![image](https://user-images.githubusercontent.com/59561259/93718527-51cb8e80-fb7d-11ea-8cc8-afbceda922bd.png)

**Environment:**
 - OS: Windows 10 x64
 - HeidiSQL version: 11.0.0.5919 portable x64
 - Database type and version: MySQL8.0.21

**Comment by ansgarbecker** [comment]
When reporting issues, please only use the latest build. 5919 is the latest stable release, but 180 changes behind the current state of the builds.

**Comment by ffvictor** [comment]
Cannot reproduce in 11.0.0.6097. Closing issue. Sorry for any trouble :)

**Comment by ansgarbecker** [comment]
Thanks for the update!
