### ISSUE TITLE
Unicde byte order mark (BOM) problem

### ISSUE THREAD

**Issue by snio89** [HeidiSQL/HeidiSQL#1162]
**Describe the bug**
Unicode byte order mark (BOM) under some environments makes issues that are hard to be analyzed.

**To Reproduce**
[Screenshot 1]

1. Type in Windows notepad: INSERT INTO a VALUE (SELECT * FROM n WHERE b="﻿c")
1. Ctrl-C and Ctrl-V to the HeidiSQL query editor.
2. A space appears between the last quote and parenthesis.
3. Moving cursor to the space makes one additional parenthesis which actually does not exist.

Explanation:
Quote before c was actually \u0022\ufeff, not \u0022.
Changing the first quote as \u0022, without BOM, solved the problem.

[Screenshot 2]

1. Type in Windows notepad: INSERT INTO aaa VALUE ("pr~~", "~~")
2. Ctrl-C and Ctrl-V to the HeidiSQL query editor and execute. (The last two rows of the screenshot are inserted.)
3. Check inserted values: the first value is ascii 239 (acute accent), not 112 (p).

Explanation:
"p becomes \u0022\ufeff\u0070. Therefore, \ufeff\u0070 is inserted and the first character becomes \ufeff.

[Possible solution]
Ignore BOM within the query editor would be a solution.

**Expected behavior**
No additional parenthesis. / The first character is p.

**Screenshots**
![heidi SQL BOM](https://user-images.githubusercontent.com/49800701/93832903-141c5200-fcb2-11ea-8907-cb887d3bf5fe.png)

![heidi SQL BOM 2](https://user-images.githubusercontent.com/49800701/93833148-c81ddd00-fcb2-11ea-9315-9741c5fb58b1.png)

**Environment:**
 - OS: Windows 10 1809 (Korean Language)
 - HeidiSQL 11.0.0.6097
 - Database: MariaDB 10.3.21

**Comment by ansgarbecker** [comment]
Just confirmed that mysterious thing in HeidiSQL, by copying the SQL text from your report above.

But I just realize your text above has a "**z**ero **w**idth **no**-**b**reak **s**pace" character between the first double quote and the "c" character. Notepad++ reveals it:
![grafik](https://github.com/user-attachments/assets/3f6654f2-559e-4a6d-b606-27106a9b5df8)

Removing that zwnbsp char fixes the issue for me. Copying the text then and pasting it in HeidiSQL looks normal then.
