### ISSUE TITLE
Invalid ALTER TABLE SQL 

### ISSUE THREAD

**Issue by janhsh** [HeidiSQL/HeidiSQL#1165]
**Describe the bug**
Heidi creates invalid SQL on ALTER TABLE for a modification of text / enum fields with comments and default value

**To Reproduce**
1. Create a table with an ENUM field and with a default value and a comment
2. Modify the field to add a value to the ENUM field
==> the generated SQL produces an error

**Expected behavior**
To correct the problem, put the default value in quotes

**Screenshots**

![2020-09-23 12_06_48-fngvmcadbwrkd01 - Connexion Bureau à distance](https://user-images.githubusercontent.com/17854448/94000328-53709e80-fd97-11ea-8390-5b33f6e50381.jpg)

**Comment by ansgarbecker** [comment]
Please report the HeidiSQL version in which this is happening. Also, the server version might be relevant here.
