### ISSUE TITLE
Default enum columns value is not quoted in CREATE code and ALTER code tabs

### ISSUE THREAD

**Issue by lucapasquini** [HeidiSQL/HeidiSQL#1168]
**Describe the bug**
SQL generation for enum columns is often missing single quote escaping.

**To Reproduce**
- Create a "test_table" with a "test_enum" ENUM column (note: the "CREATE code" tab quotes the enum value correctly at this point), save it.
- Go to the newly created table, select it and go to "CREATE code" tab, it shows `test_enum` [...]ENUM('Y','N') NOT NULL DEFAULT Y COLLATE 'utf8_general_ci'[...]
- Add a Z value to the enum, go to "ALTER code" tab, it shows [...]CHANGE COLUMN `test_enum` `test_enum` ENUM('Y','N','Z') NOT NULL DEFAULT Y COLLATE 'utf8_general_ci' FIRST[...]

**Expected behavior**
The generated code should always be [...]ENUM('Y','N') NOT NULL DEFAULT 'Y' COLLATE 'utf8_general_ci'[...]

**Environment:**
 - OS: Windows 10
 - HeidiSQL version 11.0.0.5919
 - Database 10.1.33-MariaDB

**Comment by ansgarbecker** [comment]
Probably a duplicate to #1165.

5919 is not the latest build. Please update HeidiSQL to the latest build, re-check if issue persists and report back please.

**Comment by lucapasquini** [comment]
Sorry, I downloaded the latest stable update to test it. Tested with 6098, the problem is gone!
