### ISSUE TITLE
Default to deleted treeview node's parent after refresh

### ISSUE THREAD

**Issue by igitur** [HeidiSQL/HeidiSQL#117]
## Current behavior

Example use case: I'm often run my database migrations outside of HeidiSQL. These migrations would sometimes add or delete views (or tables or stored procedures). I would run the UP migration, refresh the schema in HeidiSQL, then notice I made some errors and have to revert the migration by running the DOWN migration and repeat the process. This is a fairly common practice when developing database migrations.

In HeidiSQL, if I had a view selected that was deleted by the migration and I press F5 to refresh the schema, the treeview collapses back all the way to the database node.

## Expected behavior

When the selected node is deleted, make the new selected node the parent node of the deleted node, instead of collapsing the treeview down to the database node

In the case of a deleted view make the new selected item the `Views` treeview node and keep the node expanded. The benefit is that if I reverse the migration and the view is created again, I can press F5 in HeidiSQL and immediately see the new node, instead of having to expand the database and `Views` node again.

### Steps to reproduce

I think all the required info is mentioned above. Let me know if you need anything else.

**Comment by ansgarbecker** [comment]
See #16
