### ISSUE TITLE
 Chinese font display error

### ISSUE THREAD

**Issue by alecLen** [HeidiSQL/HeidiSQL#1171]
Chinese font display error, like this 
![image](https://user-images.githubusercontent.com/17896206/94363211-4f27e680-00f3-11eb-8737-b13955ca9366.png)
The font display is rotated 90 degrees counterclockwise
The normal display should look like this
“玩家信息表自增ID”

**Environment:**
 - OS:  Windows 10
 - HeidiSQL version: 11.0.0.6050
 - Database type and version: mysql 8.0.12

**Comment by ansgarbecker** [comment]
Please leave a reproduction recipe. Next time, also respect the issue template.
