### ISSUE TITLE
Show the list of collation types in alphabetical order

### ISSUE THREAD

**Issue by rickyheijnen** [HeidiSQL/HeidiSQL#1178]
**Is your feature request related to a problem? Please describe.**
When editing the columns of a table, the dropdown of collation types is not sorted alphabetically, and typing is not possible. That makes it sometimes hard to find the right one.

**Describe the solution you'd like**
Please show the list of collation types in alphabetical order or make it possible to filter while typing.

**Comment by ansgarbecker** [comment]
I recently made the sorting in the collation drop-down alphabetically. See #828 

You can type text to filter items, by the way. You just need to be quick enough, otherwise filtering starts at the left of the items again.
