### ISSUE TITLE
Export databases as SQL file: SET NAMES utf8 causes warnings in MySQL 8

### ISSUE THREAD

**Issue by Maelstorm1973** [HeidiSQL/HeidiSQL#1184]
**Describe the bug**

When exporting databases as SQL files, HeidiSQL inserts the following line at the beginning of the SQL file which causes MySQL to issue warnings.

`/*!40101 SET NAMES utf8 */;`

The warning that is issued is as follows:

**Warning (Code 3719): 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.**

So when I change utf8 to utf8mb4, clear the databases, and then reinsert and re-export, the above line is back in the exported SQL file and is causing the warning again.  I did some research as to why this is throwing a warning and it seems that the motivation behind the change is that UTF8MB3 can only use up to three bytes when storing Unicode characters while UTF8MB4 can store characters using 4 bytes, and therefore can store more character planes in the encoding.

**To Reproduce**
1. Menu -> Tools -> Export database as SQL
2. Select a database, or a few databases.
3. Check create on both database(s) and table(s).
4. Select insert for data option.
5. Type/select an appropriate filename.
6. Click export.
7. Open the resulting export file in a text editor to observe the above mentioned line.
8. Open a command window and start the mysql.exe client.
9. Drop the database in question.
10. Source the exported file.
11. Observe the warning.

**Expected behavior**
When all references are changed from utf8 to utf8mb4, HeidiSQL shouldn't be adding utf8 into the export file.

**Screenshots**

**Environment:**
 - OS: Windows 10 Pro RTM x64
 - HeidiSQL version 11.0.0.5919
 - Database type and version: MySQL 8.0.21

**Comment by ansgarbecker** [comment]
Please update to the latest build of HeidiSQL and reproduce. I guess I did not change it but there are over 100 changes on top of your used version, so please always use the latest build when reporting bugs.

**Comment by Maelstorm1973** [comment]
I downloaded and installed version 11.0.0.6100 and the issue is still present.  I see the line with SET NAME utf8 at the beginning of the SQL file.

`-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.21 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             11.0.0.6100
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
`

**Comment by ansgarbecker** [comment]
I'm just stumbling about this issue. I think I will keep that "SET NAMES utf8" command, which makes the dump compatible to older servers. I think the warning is not a reason to break downward compatibility.
