### ISSUE TITLE
Exporting database as SQL file: enable/disable keys produce warnings

### ISSUE THREAD

**Issue by Maelstorm1973** [HeidiSQL/HeidiSQL#1185]
**Describe the bug**

When exporting one or more databases with tables and data, HeidiSQL is inserting the following lines in error when the table engine is InnoDB.
```
/*!40000 ALTER TABLE `config` DISABLE KEYS */;
INSERT INTO .......
/*!40000 ALTER TABLE `config` ENABLE KEYS */;
```

This causes MySQL to report the following notices each time one of them is encountered.  So there ends up being two notices per table if data is inserted.

**Note (Code 1031): Table storage engine for 'table name' doesn't have this option**

**To Reproduce**
1. Go to Menu -> Tools -> Export database as SQL
2. Select one or more databases.
3. Select create option for both database(s) and table(s).
4. Set data mode to insert.
5. Select/type an appropriate filename.
6. Click export.
7. Open a command prompt and start mysql.exe
8. Drop the database in question.
9. Load (source) the file back into the database.
10. Observe the notices.

**Expected behavior**

No insertion of enable/disable keys directives in export file when exporting databases/tables with data and the table engine is InnoDB.

**Screenshots**

**Environment:**
 - OS: Windows 10 Pro RTM x64
 - HeidiSQL version: 11.0.0.5919
 - Database type and version: MySQL 8.0.21

**Comment by Maelstorm1973** [comment]
Per the other bug that I reported, the HeidiSQL version that I'm using is now 11.0.0.6100 and the problem persists.

**Comment by allnamesaretaken2** [comment]
I can confirm the problem. It is especially annoying when I try to export sequences. Heidi doesn't use SETVAL-statements for sequences but handles them like tables. And theirfor generates the DISABLE KEY-comment.

Here is the generated code for a sequence called s_parameter

/*!40000 ALTER TABLE `s_parameter` DISABLE KEYS */; <- this just doesn't work with InnoDB.
INSERT IGNORE INTO `s_parameter` (`next_not_cached_value`, `minimum_value`, `maximum_value`, `start_value`, `increment`, `cache_size`, `cycle_option`, `cycle_count`) VALUES
	(68, 1, 99999, 1, 1, 0, 0, 0);
/*!40000 ALTER TABLE `s_parameter` ENABLE KEYS */;
