### ISSUE TITLE
SQLite3: Enable loading of extensions

### ISSUE THREAD

**Issue by piula** [HeidiSQL/HeidiSQL#1186]
**Is your feature request related to a problem? Please describe.**

SQLite has a mechanism for loading extensions, e.g. for providing additional mathematical functions, geospatial data, etc. (see https://sqlite.org/loadext.html for more information).

For security reasons, this mechanism is disabled by default and has to be enabled before first use (see https://sqlite.org/c3ref/enable_load_extension.html).

Afterwards, one can either use a DLL call or "SELECT load_extension(xxx)" to load an extension.

**Describe the solution you'd like**

To me, there are severeal kinds of solutions:

Most simple, but dangerous: Just call "sqlite3_enable_load_extension(sqlite3 *db, int onoff)" with parameter onoff==1 on every connection.

Simple: In the "advanced" tab of the session manager, just add a checkbox of whether or not to allow loading extensions and send the appropriate API call.

Elegant, but most complicated: Provide a dialog in which one can select extension files. HeidiSQL could then enable all given extensions automatically.

In solutions 1 and 2, only the extension interface would be active, but the user would still have to do a "SELECT load_extension". In solution 3, HeidiSQL would take care about loading all extensions.

To me, solution 1 or 2 would absolutely be sufficient.

**Comment by ansgarbecker** [comment]
I would vote for option 1. I don't see a security advantage if the user would have to activate that per checkbox.

**Comment by piula** [comment]
Thank you. It would be very useful if it could be added.

**Comment by ansgarbecker** [comment]
Like so?

![grafik](https://user-images.githubusercontent.com/7986591/95781339-e97c5280-0ccd-11eb-967e-d59e07ab2354.png)

Just pushed that for the next nightly build, compiled in half an hour.

**Comment by piula** [comment]
Works perfectly! Thank you very much :+1: 
![Untitled](https://user-images.githubusercontent.com/45537815/95784712-a2459000-0cd4-11eb-888d-82e1ab4e1204.png)
