### ISSUE TITLE
Making an int column to be Nullable gives syntax error

### ISSUE THREAD

**Issue by amsharma9** [HeidiSQL/HeidiSQL#1187]
**Describe the bug**
Trying to make an INT data type column which was "not null" earlier to nullable gives syntax error. The SQL being executed is:
ALTER TABLE `co_access_control_t`
	CHANGE COLUMN `co_role_iid` `co_role_iid` INT(10,0) NULL DEFAULT NULL AFTER `co_access_ctrl_iid`;

The issue is INT(10,0). If I copy above SQL, remove that zero and execute it manually, it works. 

**To Reproduce**
1. Click on a table,
2. In right pane, edit a column which was not null, Tick NULL
3. Click Save at bottom

**Expected behavior**
Should not give error.

**Environment:**
 - OS: Windows 10 64bit
 - HeidiSQL version 11.0.0.5919
 - Database type and version MySQL 8.0.20

**Comment by ansgarbecker** [comment]
Please retry with the latest _build_ of HeidiSQL. 5919 is the latest _release_.

**Comment by amsharma9** [comment]
> Please retry with the latest _build_ of HeidiSQL. 5919 is the latest _release_.

I didn't understand this. I am using 5919 itself. I downloaded the Revision 6101 and it worked fine.

**Comment by ansgarbecker** [comment]
So this issue can be consideres as fixed. It will be contained in the next stable release. You can continue using that build 6101 up to then.
