### ISSUE TITLE
Export Inserts for SQL Server Max 1000 Row Values

### ISSUE THREAD

**Issue by ubermanl** [HeidiSQL/HeidiSQL#1189]
**Describe the bug**
When exporting a Table from MSSQLSERVER with the insert data option turned on, the generated SQL for that table exceeds SqlServer's insert limit with the following message:
```
Msg 10738, Level 15, State 1, Line 1016
The number of row value expressions in the INSERT statement exceeds the maximum allowed number of 1000 row values.
```

**To Reproduce**
1. Open SqlServer Management Studio, and connect to a database.
2. Create the following table and populate it with dummy records by executing the following script
```tsql
create table dbo.test
(id int)

declare @_value int
set @_value = 0
while @_value < 10000
begin
	insert into dbo.test values(@_value)
	set @_value = @_value + 1
end 
```
3. Now connect with HeidiSql to the same database and navigate to the **test** table
4. Right click the table and choose **Export Database as Sql**
5. In the Table Tools screen, configure as following image 
![image](https://user-images.githubusercontent.com/1846840/96293019-766e2700-0fc0-11eb-8257-5810caa38f1f.png)
6. Hit Export

**Expected behavior**
Output script should contain one insert with a maximum of 1000 row values, "Max Insert Size" is expressed in KB and not in Rows.
Instead it contains one insert statement with the 10.000 rows.

**Screenshots**
Output Script
![image](https://user-images.githubusercontent.com/1846840/96293499-3b202800-0fc1-11eb-87d2-3ed5a2a4771e.png)
... script continues ...
![image](https://user-images.githubusercontent.com/1846840/96293521-48d5ad80-0fc1-11eb-94a1-8b7583e4fdd7.png)

SqlServer Output
![image](https://user-images.githubusercontent.com/1846840/96293591-60149b00-0fc1-11eb-8a45-9b1eb5b392d7.png)

**Environment:**
 - OS: Windows 10
 - HeidiSQL version 11.0.0.6104
 - Database type and version Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0

**Comment by WesleyM77** [comment]
I'm having a hard time understanding your expected result. The max insert size refers to kilobytes, not rows. Being that your table is a single column of integers, I wouldn't expect Heidi to break at the 1000 row mark as there's no mechanism to handle what you're requesting. I'd say this is more of a feature request for having the option to limit rows per insert. Would you agree?

**Comment by ubermanl** [comment]
Hey, thanks for the feedback.
Sure, it can be treated as a feature to limit row quantity and not size in kb. Please let me know if some rewriting is needed.
About the sample table, its just a test one, i’ve come across this problem when exporting a large table from sql server and re importing the generated script into another sql server instance.

**Comment by ansgarbecker** [comment]
@ubermanl you could try to set the INSERT size to 1KB - that should never exceed 1000 rows.

**Comment by ansgarbecker** [comment]
SQL export is now limited to 1,000 rows in MSSQL mode, same as CSV import limit (see #326). Please try the next build.

All other servers get an INSERT limit of 10,000 now (which I could finetune if that's too low or high, not sure).
