### ISSUE TITLE
Win 10 is detected as Win 8 in about dialog

### ISSUE THREAD

**Issue by zufuliu** [HeidiSQL/HeidiSQL#119]
## Expected behavior

Win 10 is detected as `Environment: Windows v10.0`. It seems some `supportedOS` GUIDs is missing from application manifest, some useful links from MSDN:
* [Operating System Version](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx)
* [Targeting your application for Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx)
* [Application Manifests](https://msdn.microsoft.com/en-us/library/windows/desktop/aa374191(v=vs.85).aspx)

## Current behavior

In About HeidiSQL dialog, Win 10 is detected as `Environment: Windows v6.2`, which is Win 8.

### Context

* HeidiSQL version:  Version 9.5.0.5239 (64 Bit)
* Database system + version:
* Operating system: Windows 10.0.16299.214

**Comment by ansgarbecker** [comment]
It could be that this is due to the Delphi XE5 compiler and its libraries, which did not know about Win10 when XE5 was released. Well, there is surely some other, more stable way to find the current Windows version.

**Comment by zufuliu** [comment]
In the table footer note in page [Operating System Version](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx), MSDN says "Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2). To manifest your applications for Windows 8.1 or Windows 10, refer to [Targeting your application for Windows](https://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx)."

**Comment by ansgarbecker** [comment]
Thanks for your investigations. Yes, [Heidi's manifest file](https://github.com/HeidiSQL/HeidiSQL/blob/master/res/manifest.xml) doesn't even contain a `compatibility` section, therefore isn't targeted for any of the newer Windows versions.

By the way, is there a better way of linking a source file from an issue comment, instead of using the absolute github link? I am used to do that but that feels wrong: `[link text](https://github.com/HeidiSQL/HeidiSQL/blob/master/somefile.txt)`

**Comment by zufuliu** [comment]
It seems it's [Heidi's manifest file](../blob/master/res/manifest.xml):
```
[Heidi's manifest file](../blob/master/res/manifest.xml)
```

as answered in https://stackoverflow.com/questions/16534692/github-issues-reference-a-file-in-the-repo

**Comment by ansgarbecker** [comment]
Should be better now. My Win10 shows _Environment: Windows v10.0_ now.
