### ISSUE TITLE
Views with SQLite

### ISSUE THREAD

**Issue by piula** [HeidiSQL/HeidiSQL#1196]
**Is your feature request related to a problem? Please describe.**

Using r6107, with SQLite databases, only tables are shown. It would be helpful to include views as well.

Independently from that, trying to create a new view (right click on database -> create new -> view) results in a program crash.

**Describe the solution you'd like**

Both the tree view and the "database" tab should list views, too.

**Comment by piula** [comment]
If you are retrieving the list of tables with <code>SELECT name FROM sqlite_master WHERE type='table';</code>, you similarly can get the list of views with <code><code>SELECT name FROM sqlite_master WHERE type='view';</code>

**Comment by ansgarbecker** [comment]
Next build lists views in the database tab, shows them in the view editor and in the data tab. Please note that altering views is most likely failing due to the incompatible SQL syntax HeidiSQL uses (mostly MySQL syntax).
