### ISSUE TITLE
not contains ascii 39 code in default value for enum column in "CREATE" tab from table view for MySQL DB

### ISSUE THREAD

**Issue by wirelesss** [HeidiSQL/HeidiSQL#1197]
When it shows "CREATE" tab from table view, for MySQL DB.
in the generated script:
-when it has attribute/column with ENUM type with any default value, it hasn't : (ascii code: 39 in borders of constant),
  It would be default value with ( ' ) : like as ->'Constant'<-
![rev_1](https://user-images.githubusercontent.com/7864302/97100385-e20b6080-1660-11eb-9b26-2e0af02e3a15.png)
please check the attached image.
![rev_1](https://user-images.githubusercontent.com/7864302/97100354-7f19c980-1660-11eb-8583-acd261afb48f.png)
Then I want to run the "CREATE" generated script, is not valid script because not contains (ascii code: 39) in borders of
default value for Enum column.
Please add (ascii code: 39) in borders of constant in the CREATE generated script ( in CREATE tab from table view)
Thanks in advance

**Comment by ansgarbecker** [comment]
Please use the latest HeidiSQL build when reporting issues. And please rewrite the report using the bug report template.
