### ISSUE TITLE
Error after automatic upgrade 11.0.0.6110

### ISSUE THREAD

**Issue by id0612** [HeidiSQL/HeidiSQL#1199]
**Describe the bug**
After automatic upgrade, it crashes directly on startup, and after closing the dialog box, the session list is empty.

**Expected behavior**
Compatible with lower version upgrade, automatically update configuration file if necessary.

**Screenshots**
![image](https://user-images.githubusercontent.com/2449459/97244429-ad9bce00-1833-11eb-9f58-978330908b61.png)

![image](https://user-images.githubusercontent.com/2449459/97244712-5fd39580-1834-11eb-965f-623fbf5a5a31.png)

**Environment:**
 - OS: Windows 10
 - HeidiSQL version 11.0.0.6110

**Comment by lukinhaspm** [comment]
same here

**Comment by id0612** [comment]
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/5442334/bugreport.txt)

**Comment by id0612** [comment]
Exception Message: Attempt to read session Settings with no session path.

**Comment by jjasoncool** [comment]
same issue

**Comment by sombraguerrero** [comment]
Here's an actual bug report file.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/5443532/bugreport.txt)

**Comment by ansgarbecker** [comment]
Sorry, my fault! Should have just fixed #1010. Fixed build is just compiling, ready in 2 minutes for you to update. Note if you cannot do the update due to the crash, you can still download the latest build into your HeidiSQL directory.

**Comment by id0612** [comment]
> Here's an actual bug report file.
> [bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/5443532/bugreport.txt)

Yes

**Comment by id0612** [comment]
> Sorry, my fault! Should have just fixed #1010. Fixed build is just compiling, ready in 2 minutes for you to update. Note if you cannot do the update due to the crash, you can still download the latest build into your HeidiSQL directory.

OK， I will try.

**Comment by id0612** [comment]
Great. Problem solved.

**Comment by lukinhaspm** [comment]
ok now
