### ISSUE TITLE
Panel in Window-Dark Theme is not dark

### ISSUE THREAD

**Issue by connect-technologies** [HeidiSQL/HeidiSQL#1201]
**Describe the bug**
The left database/Tables overview - Treeview is still with white background and white font-color

**To Reproduce**
1. select 'Windows-Dark' theme
2. restart heidi
3. treeview is white on white

**Expected behavior**
dark mode

**Screenshots**
<img src="https://connectaupair.world/elon/heidi.png">

**Environment:**
 - OS: win10
 - HeidiSQL version 11.0.0.6111

**Comment by ansgarbecker** [comment]
Please check your session settings - you likely have set some white background color for your session:
![grafik](https://user-images.githubusercontent.com/7986591/97403807-5fe79a00-18f5-11eb-942d-a186af2e31f5.png)

**Comment by connect-technologies** [comment]
Yes thanks. Can't remember to have set this.
