### ISSUE TITLE
Problem with SSH tunnel and 64 bit version on Windows10 - caching_sha2_password' load failure

### ISSUE THREAD

**Issue by Xtravaganz** [HeidiSQL/HeidiSQL#1205]
**Describe the bug**

- heidisql plugin 'caching_sha2_password' load failure

**To Reproduce**

*** setup 64bit ***
- Install HeidiSQLPortable 64bit
- Install plink.exe
- Create a ppk key with Putty
- Settings for SSH Tunnel
- try to connect with diffrent dlls (mariadb and mysql)
- both have as result the error : caching_sha2_password' load failure

*** setup 32bit ***
- same setup
- no error

**Environment:**
 - OS: Windows 10
 - newest HeidiSQL portable version
 - mysql  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by ansgarbecker** [comment]
Last portable is not really up-to-date. At least libmariadb.dll got an update after the v11.0 release. Please re-test once I released the next v11.1 version with a new portable package.

**Comment by ansgarbecker** [comment]
Ah, in what way is the SSH tunnel relevant? Doesn't that happen with a normal connection without a tunnel?

**Comment by Xtravaganz** [comment]
> 
> 
> Ah, in what way is the SSH tunnel relevant? Doesn't that happen with a normal connection without a tunnel?



> 
> 
> Ah, in what way is the SSH tunnel relevant? Doesn't that happen with a normal connection without a tunnel?

To be on the safe side, MySQL is only open via localhost, so you don't have to open the port for SQL and can conveniently use Mysql via the SSH service.

**Comment by Xtravaganz** [comment]
> 
> 
> Last portable is not really up-to-date. At least libmariadb.dll got an update after the v11.0 release. Please re-test once I released the next v11.1 version with a new portable package.

Will test it tomorrow.

**Comment by ansgarbecker** [comment]
You cannot test tomorrow, you have to wait for me to release the v11.1 first.

Is the issue happening with a normal connection as well, without SSH tunnel? Or does it only occurr with an SSH tunnel?

**Comment by Xtravaganz** [comment]
> 
> 
> You cannot test tomorrow, you have to wait for me to release the v11.1 first.
> 
> Is the issue happening with a normal connection as well, without SSH tunnel? Or does it only occurr with an SSH tunnel?

Yeah, i will wait.
When i remember correct, yes.

**Comment by ansgarbecker** [comment]
I release v11.1 in the meantime. Please update and retry.
Please note that this new release comes with its own plink.exe, which you should prefer over a separate one. To use HeidiSQL's own plink.exe, go to "SSH tunnel" tab and set it to just "plink.exe" without path:
![grafik](https://user-images.githubusercontent.com/7986591/98156023-7aaea580-1ed7-11eb-98f7-e0552ee5ee5c.png)

**Comment by Xtravaganz** [comment]
# No change in the 64 bit version:

![grafik](https://user-images.githubusercontent.com/636411/98431088-c1a4c280-20b2-11eb-87cf-3938227d8502.png)

# 32bit portable works fine:

![grafik](https://user-images.githubusercontent.com/636411/98431197-74752080-20b3-11eb-8b35-5384c81a875e.png)

# Thanks:

this saves unnecessary downloading and clicking

**Comment by ansgarbecker** [comment]
@Xtravaganz did the issue somehow resolve or change in any way with the current 12.3 release?

**Comment by ansgarbecker** [comment]
Guessing this issue is solved, as there are no other reports saying the same.
