### ISSUE TITLE
Exception when pressing F9 to rerun SQL query while grid has focus

### ISSUE THREAD

**Issue by robertoarnetoli** [HeidiSQL/HeidiSQL#1206]
**Exception when pressing F9**
exception class    : EAccessViolation
exception message  : Access violation at address 0000000001010C60 in module 'heidisql.exe'. Execution of address 0000000001010C60.

**To Reproduce**
1. Run any query (expecting to receive only a few rows back)
2. Click anywhere in the area just below the data results grid 
3. Press F9 to rerun the query

**Expected behavior**
The query should rerun and refreshed data should appear on the data grid

**Environment:**
 - OS: Windows 2012 R2 x64 build 9600
 - HeidiSQL version 11.1.0.6116
 - Database type and version MySQL 5.7.x

**Comment by ansgarbecker** [comment]
Is there something special with your query, probably a really huge result? I cannot reproduce this with any of my queries.

**Comment by robertoarnetoli** [comment]
no large query. It happens even with a simple query as `SELECT 1` or `SHOW PROCESSLIST`
Step 1 - run simple query
![image](https://user-images.githubusercontent.com/4313298/98293207-393cf980-1fae-11eb-9d65-1c5145418240.png)
Step 2 - click in the area below the data grid (red dot)
![image](https://user-images.githubusercontent.com/4313298/98293295-5b367c00-1fae-11eb-94ab-aa3a9190ab8a.png)
Step 3 - press F9
![image](https://user-images.githubusercontent.com/4313298/98293746-1ced8c80-1faf-11eb-8463-2a74a046a3da.png)
and get the error

**Comment by ansgarbecker** [comment]
Yes, I can reproduce that now. Setting focus on the grid is important for reproducing.

**Comment by ansgarbecker** [comment]
With v12.6 I cannot reproduce that error here. I'm not sure when or what exactly fixed this, but I guess it was one of my bugfixes for the last release.
