### ISSUE TITLE
double click icon on desk can't show current  instance when the single mode is on !

### ISSUE THREAD

**Issue by netmou** [HeidiSQL/HeidiSQL#1207]
**Describe the bug**
double click icon on desk can't show current  instance when the single mode is on

**To Reproduce**
 1. set the single mode is on
2. colse all process
3. open a instance
4. min the instance view
5. double click icon on desk

**Expected behavior**
the curren instance should show on the top level 

**Screenshots**

**Environment:**
 - OS: Windows 10,
 - HeidiSQL version 11.6 64
 - mysql 5.7

**Comment by netmou** [comment]
/* 进入会话 "本地MySQL" */
/* 拒绝访问。 */
/* 无法启动第二个应用实例 - 在 工具 > 首选项 > 常规 设置中已禁止 */
/* 无法启动第二个应用实例 - 在 工具 > 首选项 > 常规 设置中已禁止 */
/* 无法启动第二个应用实例 - 在 工具 > 首选项 > 常规 设置中已禁止 */

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.
