### ISSUE TITLE
Subdirectory support for snippets

### ISSUE THREAD

**Issue by nick-traeger** [HeidiSQL/HeidiSQL#121]
Hello,
it would be nice, if HeidiSQL supports subdirectories for the snippets.

**Comment by ansgarbecker** [comment]
Here are some earlier ideas about enhancing the snippet list:
* https://www.heidisql.com/forum.php?t=23606
* http://ibb.co/iptQka
* https://www.heidisql.com/forum.php?t=20749

**Comment by ansgarbecker** [comment]
I recently added a filter box above the whole box with the filters, functions, columns etc. And I already spent some hours for getting subdirectories to work here, but that went into much more effort than I thought. So I'm closing this, as with the filter box we already have a workaround for finding stuff more easily.
