### ISSUE TITLE
[wine] SysErrorMessage() doesn't return a string

### ISSUE THREAD

**Issue by gcarreno** [HeidiSQL/HeidiSQL#1216]
Hey @ansgarbecker 

**Describe the bug**
`SysErrorMessage()` doesn't return a string for whatever error `Windows.GetLastError()` is returning.

**To Reproduce**
1. under `wine` Check for updates.

**Expected behavior**
The expected result is having the error string having an error message on the () pair at the end of it

**Suggestion**
Remove the call to `SysErrorMessage()` for the time being?

**Screenshots**
![HeidiSQL-NoMessageGetLastError](https://user-images.githubusercontent.com/81799/98872893-499e1a00-246f-11eb-8311-27a0f3ab0272.png)

**Environment:**
 - OS: Ubuntu/Wine5.0
 - HeidiSQL:  11.1.0.6120]

**Comment by ansgarbecker** [comment]
Let's please stick in #1215

**Comment by gcarreno** [comment]
Hey @ansgarbecker 

Yeap, you're absolutely right. I got a bit trigger happy, I'm really sorry.

Cheers,
Gus
