### ISSUE TITLE
Update plink to latest version 0.74

### ISSUE THREAD

**Issue by gemal** [HeidiSQL/HeidiSQL#1218]
Heidisql currently uses 0.73 while version 0.74 is available

**Comment by ansgarbecker** [comment]
Please use the issue template the next time.

We have to take care if the new plink version has some changes which may break Heidi's stdout-parser. But I don't guess so.

**Comment by gemal** [comment]
Something did not work with this pull or is it not yet out?
![image](https://user-images.githubusercontent.com/69105/104705383-1f403580-571a-11eb-8ef3-43dc2c0d28bd.png)

or will it first be available in 11.2?

**Comment by ansgarbecker** [comment]
Yes, next release will have it.
But also the nightly installer has it, just not when you only update the nightly build / heidisql.exe.
