### ISSUE TITLE
SQL-Editor: comment not recognized, if followed by TAB

### ISSUE THREAD

**Issue by UweAtWork** [HeidiSQL/HeidiSQL#1219]
"SELECT --<Tab>1; " ==> wrong
"SELECT --<Space>1;" ==> OK

**Comment by ansgarbecker** [comment]
What about using the issue template?

Comment syntax is highly subjective to server versions, so please at least specify on which server a tab is allowed or required after the two minus characters.

**Comment by UweAtWork** [comment]
> What about using the issue template?

In this case I thought it´s a lot of overhead for such a trivial thing.
But I should have put the examples in a code-block. 
Some portions have been interpreted as XML-TAGs

```
"SELECT --<TAB>1; " ==> wrong
"SELECT --<SPACE>1;" ==> OK
```

Same MariaDB-Server:
"heidisql64.r5771.exe": TAB works
"heidisql64.r6128.exe": TAB does not work

**Comment by ansgarbecker** [comment]
This topic has quite a longer history, even there were reports in the SynEdit project regarding this. So I'd like to finally fix this rock solid, finally.

* MariaDB says the _space_ is required, see here: https://mariadb.com/kb/en/comment-syntax/
But I think the documentation is wrong, as on my v10.3 server the tab is also allowed. Could you please  check that with your server?
* MS SQL, SQLite and PostgreSQL all seem to require nothing after the double-minus: `--comment` just works

**Comment by UweAtWork** [comment]
"So I'd like to finally fix this rock solid." Cool - thank you!

We have Server Version 10.3.27 and 10.1.48 - both accept space and tab after double-minus and hash.
In a few days we will upgrade to 10.4.x.

**Comment by ansgarbecker** [comment]
For MySQL and MariaDB, the next build allows the double-minus followed by a tab char. Actually, any ASCII character from Dec 0 .. 32 is accepted.

I guess this solves it.

**Comment by UweAtWork** [comment]
Thank you - Build 6130 works like a charm :-)
