### ISSUE TITLE
Portable package should NOT include a portable_settings.txt file

### ISSUE THREAD

**Issue by mdcclxv** [HeidiSQL/HeidiSQL#122]
## Expected behavior

Portable package should NOT include a portable_settings.txt file.

## Current behavior

Portable package DOES include a portable_settings.txt file.

## Failure information (for bugs)

When unpacking the portable package over the old version, the portable_settings.txt file gets overwritten, thus loosing all sessions and, more important, all customizations, like syntax highlighting. Very annoying!

### Steps to reproduce

Bug is self explanatory.

### Context

* HeidiSQL version: 9.5.0.5196
* Database system + version: irrelevant
* Operating system: irrelevant

**Comment by ansgarbecker** [comment]
Understand.
But that's a problem: Without that file, HeidiSQL runs in normal instead of portable mode.
Suggestions?

**Comment by mdcclxv** [comment]
The portable_settings.txt file should have a setting pointing to a user_settings.txt, which contains the user customizations. This file will not exist in the portable package, it will be created by Heidi when user customizes something. This way I can even play with multiple customization profiles, if I wish, and the conflict that just happened to me is eliminated.

**Comment by mdcclxv** [comment]
Or better yet, you should just use an empty file, let's call it portable.lock, and test its existence for portable mode. Nothing in this file. This will be included in the portable package, while portable_settings.txt should be optional and contain user's customizations generated by Heidi at runtime.

**Comment by ansgarbecker** [comment]
Nice idea, sounds consistent. And even backward compatible, for users like you who have an existing portable_settings.txt file.

**Comment by ansgarbecker** [comment]
Next build expects the portable.lock to be present, or the portable_settings.txt. In future releases, there is no need to provide an empty portable_settings.txt in the zip file, which potentially overwrites the user's settings.

**Comment by mdcclxv** [comment]
Just did an update, lost all my settings ... again :(
Empty portable_settings.txt is still included.

**Comment by ansgarbecker** [comment]
So you downloaded the old portable package?

You need to use the nightly build when testing new things.

**Comment by mdcclxv** [comment]
> 
> 
> So you downloaded the old portable package?
> 
> You need to use the nightly build when testing new things.

Nope, I've updated via About -> Check for updates, but yes, when I checked for existence of the "portable_settings.txt" I did look into the old portable package, the one on the download page. My bad.
