### ISSUE TITLE
Can´t edit value if (MariaDB Galera-)clustered

### ISSUE THREAD

**Issue by UweAtWork** [HeidiSQL/HeidiSQL#1220]
HeidiSQL does not allow me to modify data, if data is located on MariaDB Galera Cluster.

Steps to reproduce: run the following query on a MariaDB Galera Cluster and repeat it on a non clustered MariaDB system:

```
USE mysql;
CREATE OR REPLACE TEMPORARY TABLE tt_data SELECT 156319 AS id, 0 AS my_value;
SELECT * FROM tt_data;
```

Cant´t edit "my_value" on clustered System, but I can edit it on a single-node system.
(The conenctions have been opened in the same HeidiSQL process.)

**Environment**

Except clustering, environment is identical:

```
[Content]
Verbindungstyp: MariaDB (TCP/IP)
Verbunden: Ja
Server Betriebssystem: Linux
Server Version: 10.3.27-MariaDB-log - MariaDB Server
Verbindungs Port: 3306
Komprimierungs Protokoll: Nein
Unicode aktiviert: Ja
SSL aktiviert: Nein
Bibliotheksversion (I:\bin\HeidiSQL\libmariadb.dll): 10.4.12
```

**Comment by UweAtWork** [comment]
HeidiSQL Version 11.1.0.6116

**Comment by UweAtWork** [comment]
As of now (with Build 6130), I can´t reproduce this issue.

**Comment by ansgarbecker** [comment]
Oh, thanks for the feedback then!
