### ISSUE TITLE
SQL export to server may fail

### ISSUE THREAD

**Issue by davekc** [HeidiSQL/HeidiSQL#1222]
**Describe the bug**
SQL export a table with a field containing the word 'type' to server output may fail

**To Reproduce**
Here's a test table:
CREATE TABLE IF NOT EXISTS `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `the type of` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;

This will work using SQL statement:
INSERT INTO `test` (`id`, `the type of`) VALUES (1, 1),

Using SQL export to a server output we will get:
SQL Error (1054): Unknown column 'the type of' in 'field list'

![HeidiSQL](https://user-images.githubusercontent.com/11339519/99400556-161b1f80-28b5-11eb-8253-8cdafcc9016d.png)

The created table will become:
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `the ENGINE of` tinyint(4) DEFAULT NULL

Strangely, it will work perfectly if the field is `the type` or `type of`. But not `the type of`.

**Environment:**
 - OS: Windows 10
 - HeidiSQL version 11.1.0.6128
 - Database type and version MariaDB 10.3.27

**Comment by ansgarbecker** [comment]
Reason is a hardcoded replacement of old `TYPE=...` clause on the table itself, to `ENGINE=...`.
Old ticket: https://sourceforge.net/p/heidisql/tickets/2688/
Commit: 990535228f1a4aadad96902cb0bbc883c698937a

Quite broken, and even silly to support such old server versions any longer. I think I'll remove that replacement.

**Comment by davekc** [comment]
That was quick! Great to read it was an easy one... thanks!
