### ISSUE TITLE
Request for verified checksum for major releases

### ISSUE THREAD

**Issue by insanityinside** [HeidiSQL/HeidiSQL#1223]
I'm currently maintaining the [Chocolatey package for HeidiSQL](https://chocolatey.org/packages/HeidiSQL), and they're now requesting verifiable checksums for the releases (using SHA1 at present).

Would it be possible to have you hash your major release binaries and post them on the website when you upload them? (Or have it automated on your end, whichever is easier!)

Unfortunately this isn't something I can do externally. I've been manually downloading and running a hash on the files for verification, but I've been caught out with [this new policy](https://github.com/chocolatey/package-validator/wiki/VerificationFileMissing). Basically, users need to be able to visit the source of the binaries to verify the checksum for themselves where necessary. I understand the rationale, to avoid compromised builds, though it's a little inconvenient to set up. Sorry about that, I'm a volunteer myself helping out where I can with a brilliant bit of software.

**Comment by ansgarbecker** [comment]
No problem, I am thankful someone else moderates the Chocolatey package.

I have just modified the creation of the installer, so it creates a `*.sha1.txt` file at the end, placing it in the same directory where the installer resides. So for the current v11.1 release it's this one:
https://www.heidisql.com/installers/HeidiSQL_11.1.0.6116_Setup.sha1.txt

The content of that file is just the SHA1 checksum, calculated using PHP's `sha1_file()` function, nothing else. So this should probably help in automating the download.

For the official (current) release, that file is also linked on the [download page](https://www.heidisql.com/download.php). (2nd link in the list)

Is that sufficient that way?

**Comment by insanityinside** [comment]
That's perfect, matches the hashes I've put in the installer, just so I can add the link to the documentation. Thanks for the assistance! :)

**Comment by striezel** [comment]
> I have just modified the creation of the installer, so it creates a `*.sha1.txt` file at the end, placing it in the same directory where the installer resides. So for the current v11.1 release it's this one: https://www.heidisql.com/installers/HeidiSQL_11.1.0.6116_Setup.sha1.txt

@ansgarbecker It looks like those SHA-1 checksum files are no longer generated. There is no such file for the current release 12.11.0.7065 of HeidiSQL on the download page (https://www.heidisql.com/download.php). Could you please check what went wrong and re-add the checksum files? Thanks.

**Comment by ansgarbecker** [comment]
@striezel yes these checksum files are currently no longer created. This is due to the messy newer code signing mechanism, which has to use an USB device, and so has to be done manually by me. As this part is no longer done within my auto-build process, the previously generated checksums would be wrong in the end.

Would it be sufficient if I re-add the checksum files for the official releases? If possible I want to avoid checksums for the nightly builds and all the other files I am providing.
Normally the code signing certificate should verify the file even more securely than such a checksum can do.

**Comment by striezel** [comment]
> [@striezel](https://github.com/striezel) yes these checksum files are currently no longer created. This is due to the messy newer code signing mechanism, which has to use an USB device, and so has to be done manually by me. As this part is no longer done within my auto-build process, the previously generated checksums would be wrong in the end.

Ah, I see. Not being able to use automation for that is unpleasant. :(

However, the checksums of the older releases have not changed (I only checked HeidiSQL_12.10.0.7000_Setup.exe and HeidiSQL_12.9.0.6999_Setup.exe so far), but their checksum files seem to be gone, too.

> Would it be sufficient if I re-add the checksum files for the official releases? If possible I want to avoid checksums for the nightly builds and all the other files I am providing.

**Yes.** Checksum files for the official releases are enough for me. I don't care that much about nightly builds, so I do not need checksum files for those.

**Comment by ansgarbecker** [comment]
Thanks for your feedback.
Checksum file for the release files are created and linked on the download page again.
For the current v12.11 installer: https://www.heidisql.com/downloads/installers/HeidiSQL_12.11.0.7065_Setup.sha1.txt

**Comment by ansgarbecker** [comment]
Nah, I mixed up the urls... it's https://www.heidisql.com/installers/HeidiSQL_12.11.0.7065_Setup.sha1.txt (without the /downloads, although both work but the one without is linked)

**Comment by striezel** [comment]
Thank you, much appreciated. 👍
