### ISSUE TITLE
HeidiSql website complains for adsblocking even thou the adsblocker is disabled in firefox

### ISSUE THREAD

**Issue by rajmondburgaj** [HeidiSQL/HeidiSQL#1225]
Even thou I disable the ads blocker in the website still it complains in Firefox. Check the image below:

![image](https://user-images.githubusercontent.com/7545874/99566845-b06e8680-29cd-11eb-85b2-8a683c2d7439.png)

Not sure if this is the best place to report such problem but I am not sure where else either!

The same thing does not happen in chrome.

**Comment by ansgarbecker** [comment]
Yes, that logic was a bit broken, and I just tried to simplify and fix it for all browsers. Not 100% sure but my tests were all successfull now. Can you please retry now?

**Comment by rajmondburgaj** [comment]
I get the same to be honest, tried using a private window as well but somehow is not able to detect that i have the adblocker disabled.

**Comment by ansgarbecker** [comment]
Are you sure you were using Firefox last time? I have no such issue here with Win10 / Firefox 83.0 / AdblockPlus 3.10. Is your network probably filtering ads already?
Well, my self baken detection of ad-blocking may be broken for other users even if it works for me. I am a bit lost with that - isn't there a more reliable method for detecting ad blockers?

**Comment by ansgarbecker** [comment]
I hope I could solve the issue - right now the ad block detection should be more reliable, without depending on some specific variables which might not have been set even if the user has no blocker.
Would be nice if you give it one more test.

**Comment by rajmondburgaj** [comment]
Hi, thanks a lot for your effort and time, yes I can confirm now it is fixed. When I stop the adblocker for this website I am able to download the new updates.

**Comment by ansgarbecker** [comment]
Thanks for the update!
