### ISSUE TITLE
import a 100MB mysql sql file too slowly ,is autocommit has set to 0  ?

### ISSUE THREAD

**Issue by netmou** [HeidiSQL/HeidiSQL#1227]
i think,like navcat , its a good idea to set autocommit = 0 before import sql-file,
![image](https://user-images.githubusercontent.com/7068058/99645199-e113f600-2a89-11eb-980f-f02d5dca0605.png)

**Comment by WesleyM77** [comment]
Can you resubmit your issue using one of the issue templates?

**Comment by netmou** [comment]
this is not a bug ,just a suggest : add a sql statement "set autocommit = 0;" before import to  database to improve the efficient.
import a 100MB mysql sql file use heidisql may need 2.5hours ,but use navicat may 10 minites, so it is essential

**Comment by ansgarbecker** [comment]
Yes, the question came up in the forum as well.
Please use the feature request template from the "new issue" page.

**Comment by ansgarbecker** [comment]
Duplicate of #1262
