### ISSUE TITLE
SQL Error (10713) while using MERGE INTO

### ISSUE THREAD

**Issue by YetAnotherRussian** [HeidiSQL/HeidiSQL#1229]
**Describe the bug**
SQL Error (10713) while using MERGE INTO

**Steps to reproduce:**
1. Connect to MS-SQL server (10.50.6000 is used)
2. Execute the query

```
USE [Test_db]

	PRINT 'Updating LTs in Local'
	MERGE INTO Local as target
	USING (		SELECT NULL as ID_LT, 'ru-ru' as Language, 211 as Number, 'Б' as Text UNION ALL
				SELECT NULL as ID_LT, 'ru-ru' as Language, 212 as Number, 'М' as Text UNION ALL
				SELECT NULL as ID_LT, 'ru-ru' as Language, 213 as Number, 'С' as Text UNION ALL
				SELECT NULL as ID_LT, 'ru-ru' as Language, 214 as Number, 'Б' as Text UNION ALL
				SELECT NULL as ID_LT, 'ru-ru' as Language, 215 as Number, 'С' as Text UNION ALL
				SELECT NULL as ID_LT, 'ru-ru' as Language, 216 as Number, 'С' as Text UNION ALL
				SELECT NULL as ID_LT, 'ru-ru' as Language, 217 as Number, 'Й' as Text
	) as Source (ID_LT, Language, Number, Text)
	ON ISNULL(target.ID_LT, 0) = ISNULL(source.ID_LT, 0) AND target.Language = source.Language AND target.Number = source.Number
	WHEN MATCHED AND target.Text <> source.Text THEN
		 UPDATE SET Text = source.Text
	WHEN NOT MATCHED BY TARGET THEN
		 INSERT (ID_LT, Language, Number, Text) VALUES (ID_LT, Language, Number, Text);
GO
```

**Actual behavior**
SQL Error (10713)

**Expected behavior**
No issues (Microsoft SQL Server Management Studio 10.50.6000.3410 works OK)

**Environment:**
 - OS: Win10 2004
 - HeidiSQL 11.1.0.6116
 - MS-SQL server (10.50.6000)

**Comment by ansgarbecker** [comment]
Your script does not separate queries with semicolon, maybe that's the cause?
HeidiSQL needs semicolons at the end of each query. Also, that `GO` is specific to the MSSMS client if I recall right.

**Comment by YetAnotherRussian** [comment]
https://www.irisclasson.com/2020/09/08/sql-error-10713-a-merge-statement-must-be-terminated-by-a-semi-colon/

Oh... That was not expected...

**Comment by ansgarbecker** [comment]
Oh well. I thought you would at least be able to run the merge query alone:

`MERGE INTO ... , Number, Text);`

So it's separated from the `PRINT/USE/GO` commands.

I think we can close that.
