### ISSUE TITLE
Table data not refreshed

### ISSUE THREAD

**Issue by Praetorian11** [HeidiSQL/HeidiSQL#1231]
**Describe the bug**
Table data not refreshed after Refresh command

**To Reproduce**
1. Alter table column in Query tab
2. Switch to Table tab
3. Go to table list bar on the left side
3. Use right mouse button and choose Refresh
4. In the console I can see SQL to retrieve table definition, but grid on Table tab is not refreshed. I have to exit and run application.

**Expected behavior**
When I choose Refresh command, the grid should be updated.

**Comment by ansgarbecker** [comment]
Well, that refresh is done on the table list, not on the table editor. The retrieved table definition is not used for the table editor, for good reasons - you may have pending changes there which you want to save.

But you don't need to restart HeidiSQL. You can just switch to another table and then back to the first one. All columns are retrieved then.

**Comment by Praetorian11** [comment]
Yes, I also tried those steps, but the table is not refreshed.
1. Query tab: ALTER TABLE "dbo"."TAssetsArch"	ALTER COLUMN "Description" VARCHAR(60)
2. Switch to Table tab
3. Select another table
4. Switch back to origin table
5. Altered column is not changed on Table tab

**Comment by ansgarbecker** [comment]
Oh, now I see - the refresh is required but is effective only after switching the table. That should not be the case. Initializing the table editor should be sufficient to get a fresh view of the table.

**Comment by ansgarbecker** [comment]
Oh I see this is a duplicate to issue #319 . Just shout if it's different.
