### ISSUE TITLE
Multiple PostgreSql databases filtering not working

### ISSUE THREAD

**Issue by rasputino** [HeidiSQL/HeidiSQL#1235]
**PostgreSql multiple databases filtering not working**
Configuring multiple databases in PostgreSql not working although  I configured them with a semicolon separator. I think that it doesn't detect the semicolon separator and tries to filter them like just one of them.

**To Reproduce**
1. Configure a PostgreSql connection
2. Check the PostgreSql connection works good without any database filtering (or with just one)
3. Set two or more databases separated by semicolon

**Screenshots**
![2020-11-24 08_52_40-Session manager](https://user-images.githubusercontent.com/2887216/100064320-a962d080-2e32-11eb-903f-e648f579de35.png)

**Environment:**
 - OS: Windows 10
 - HeidiSQL version [e.g. 11.1.0.6116]
 - Database type and version: PostgreSQL 10.15 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit

**Comment by ansgarbecker** [comment]
Please note in PostgreSQL mode the field is named "Database", not "Databases". This must be a single database as it is used in the internal call to `PQconnectdb`, like documented here: https://www.postgresql.org/docs/9.1/libpq-connect.html

If you think there is a way to pass multiple databases in the PostgreSQL connection, feel free to tell how that can be done.

**Comment by kb-ig** [comment]
Think you for pointing out that the field get's called "Database", indicating that only one can be selected. Perhaps the misleading placeholder in the dropdown could be changed (or removed) when in PostgreSQL mode
![image](https://user-images.githubusercontent.com/91877080/146023792-c88fc354-5116-4c2c-b2e9-61edd550341d.png)

**Comment by ansgarbecker** [comment]
Fixed for the next release, and already in the nightlies, through 829b89db2d3bb2de4f5faf725230486e6075ee2a

![grafik](https://user-images.githubusercontent.com/7986591/146029855-e3ee3e7a-6b55-472a-ba26-498db3b74c0b.png)

**Comment by WuJiY** [comment]
like DBeaver?
