### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by PaulExChandler** [HeidiSQL/HeidiSQL#1236]
When closing the program, the attached crash resulted.
MariaDB was being used on a remote server.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/5599665/bugreport.txt)

**Comment by ansgarbecker** [comment]
That crash was raised with an old version.

Please update HeidiSQL to the latest build. Reopen this issue if you get a crash again.
