### ISSUE TITLE
Crash when using drop down menu option "Explain current query"

### ISSUE THREAD

**Issue by richardeaxon** [HeidiSQL/HeidiSQL#1239]
**Describe the bug**
Application crash on using menu option.

**To Reproduce**
1. Open HeidiSQL and open a saved session
2. Click on 'Query' dropdown menu
3. Click on 'Explain current query'
4. See crash

**Expected behavior**
Crash should not occur.

**Screenshots**
N/A

**Environment:**
 - OS: Windows 10
 - HeidiSQL version: 11.0.0.x and also on 11.1.0.6116 
 - Database type and version: MariaDB 10.4.14

**Comment by ansgarbecker** [comment]
Fixed in the next build.
