### ISSUE TITLE
Username length limit, max 48 of 80 characters

### ISSUE THREAD

**Issue by id333k** [HeidiSQL/HeidiSQL#124]
Hello,
If username is more than 48 characters, can't connect to mariadb server.
I have usernames of 80 characters (max allowed by mariadb) and it is possible to conect with another clients. (for example MySQL Workbench, DBeaver). Hope, it will be possible to connect with HeidiSQL too.
Passwords of 100 characters work well.
Thanks.
P.S. I'm not paranoid, just security measures. 
MariaDB 10.3.4
HeidiSQL 9.5.0.5245
Connection type: MySQL (via SSH tunnel)

**Comment by ansgarbecker** [comment]
Where exactly do you experience that issue?

I just successfully created such a user name with 75 characters in HeidiSQL's user manager, on MariaDB 10.2, and then connected with that user:
> _1234567890123456789012345678901234567890123456789012345678901234567890_73

**Comment by id333k** [comment]
I installed MariaDB 10.2.12 (clean installation)
CentOS Linux release 7.4.1708 (Core)
Console (via SSH from root): MariaDB [(none)]> grant all on *.* to '_1234567890123456789012345678901234567890123456789012345678901234567890_73'@'%' identified by 'EMUXKR7MAAS8DVQ';
flush privileges;
Connection type: MySQL (TCP/IP) (directly on 3306 port)
Result: Access denied for user '_1234567890123456789012345678901234567890123456789012345678901234567890_73' (using password: YES)
Another clients can connect successful with this username & password.
HeidiSQL 9.5.0.5245 (64 Bit)
Microsoft Windows [Version 10.0.16299.125] 64 Bit

**Comment by id333k** [comment]
Some kind of mysticism with your program.
My algorithm of actions, step by step.
Step1 (70 characters): `grant all on *.* to 'RW2O5PBWFI5GKHQ8TL0AEC670FV82CKFT6D698786VI2S7DNDJBQ00M6YQGW3G52HZAGR3'@'%' identified by '78W8IR8UMUGLPIJ';`
`flush privileges;`
Result: Access denied for user 'RW2O5PBWFI5GKHQ8TL0AEC670FV82CKFT6D698786VI2S7DNDJBQ00M6YQGW3G52HZAGR3' (using password: YES)
Other clients: sucessfull.
Step2 (49 characters): `grant all on *.* to 'RW2O5PBWFI5GKHQ8TL0AEC670FV82CKFT6D698786VI2S7DND'@'%' identified by '78W8IR8UMUGLPIJ';`
`flush privileges;`
Result: Access denied for user 'RW2O5PBWFI5GKHQ8TL0AEC670FV82CKFT6D698786VI2S7DND' (using password: YES)
Other clients: sucessfull.
Step3 (48 characters): `grant all on *.* to 'RW2O5PBWFI5GKHQ8TL0AEC670FV82CKFT6D698786VI2S7DN'@'%' identified by '78W8IR8UMUGLPIJ';`
`flush privileges;`
Result: Successful connection.
From now on, I can connect successfully by username from the first, second and third steps and even with your username (74 characters): _1234567890123456789012345678901234567890123456789012345678901234567890_73
But I still can't connect with username of 80 characters and can't connect if I will create new usernames longer than 48 characters. I created again username with 50 characters - access denied. I created again new username with 48 characters and connection successful. Only after that, the previous login of 50 characters will work.

**Comment by ansgarbecker** [comment]
I can reproduce that, at least with all users I created with "%" as host. As soon as I specifiy "localhost", these users are able to connect. Are you sure you created the last user with %, or was it localhost perhaps? (or something different)

**Comment by ansgarbecker** [comment]
Perhaps this is helpful: https://serverfault.com/a/122477/386260

**Comment by id333k** [comment]
I create a new username with 80 characters through your program (user manager).
Result:
Connection to remoteip via MySQL (TCP/IP), username TGGE92O38NE7QZZNZBUHZQL3IW1XRID1TCWW1OIGPXLDTW9JQK453YDIVBYM0FVZ20UT702MCXOR1MJP, using password: Yes ... */
Access denied for user 'TGGE92O38NE7QZZNZBUHZQL3IW1XRID1TCWW1OIGPXLDTW9J'@'myip' (using password: YES) */

Pay attention to the first line, the username is 80 characters.
In the second line, the username has changed to 48 characters.
Conclusion: the program cuts the username.

My previous tests were incorrect, because I created the same usernames, only removing the last characters. Your program connected to the username with 48 characters, and I thought that it connects to 50, 70 and 80 characters. It is not true. The program just connected with the last username with 48 characters, instead of 50,70,80, as they were the same (without last characters). It's ipossible to connect to any username with more than 48 characters.
Obviously, there is a bug in "Session manager".

**Comment by ansgarbecker** [comment]
And you are still on MariaDB 10.3.4 + HeidiSQL 9.5.0.5245 ?
I'm asking so I can probably try out on a MariaDB 10.3 - on my 10.2 I cannot reproduce that.

The localhost/% confusion should not be a problem, as your "access denied" message contains "...@myip", not "...@localhost".

**Comment by id333k** [comment]
I removed 10.3.4 to avoid any beta issuses.
Server: CentOS 7.4.1708 + MariaDB 10.2.12 stable 
Client: Microsoft Windows [Version 10.0.16299.125] 64 Bit + HeidiSQL 9.5.0.5245 (64 Bit)
As already mentioned, all other clients connect successfully with usernames more than 48 characters.

I have MariaDB 10.2.7 on my local system (on Windows 10).
So, I created a username with 80 characters with "@localhost".
`/* Connecting to 127.0.0.1 via MySQL (TCP/IP), username 2HYG4PS0BWNUMJTYU3QQ9Y12XC4JGKDJOFV5IRCHEBW2NBZLBAS39DT80TT1C7B38X5ZC0I3Z8YPJDET, using password: Yes ... */
/* Access denied for user '2HYG4PS0BWNUMJTYU3QQ9Y12XC4JGKDJOFV5IRCHEBW2NBZL'@'localhost' (using password: YES) */`

Pay attention to the second line. The username is cutted for 48 characters. Same story.
Conclusion: the reason not in "@%" or "@localhost". The reason is in something else.

**Comment by id333k** [comment]
After I copied the connection status above and clicked on the "User manager" menu, the program crashed.
By the way, your program very often crashed, very often. But I love it, for speed and convenience.
I attached bug report, maybe it will help you.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1716897/bugreport.txt)

**Comment by ansgarbecker** [comment]
Probably you have an old libmysql in your HeidiSQL folder? Unlikely, but possible, and even possible that this older library only supported 48 characters for usernames.

Can you please click (in HeidiSQL) on the bottom status bar panel with the server version on it (e.g. "MariaDB 10.2."), that should bring up a dialog. Copy the contents via <kbd>Ctrl+C</kbd> and post the line with the "client library" here.

![grafik](https://user-images.githubusercontent.com/7986591/36113427-08c326a0-102d-11e8-90a7-0e84b950bcea.png)

**Comment by rentalhost** [comment]
**Could not reproduce here using MariaDB 10.1.14.**

@id333k Could you check the output SQL on log when you create your user on User Manager? And too could you check if when you open the User Manager the user is cutted off or it is represented correctly?

**Comment by id333k** [comment]
HeidiSQL_9.5.0.5196_Setup.exe was installed 14.01.2018, after a while it was updated to Nightly Builds.
MariaDB 10.2.12 on CentOS7 was installed yesterday.

[Window Title]
xxx.xxx.xx.x: Information
[Content]
Host: xxx.xxx.xx.x
Network type: MariaDB (SSH tunnel)
Connected: Yes
Real Hostname: xxxxxxx.com
Server OS: Linux
Server version: 10.2.12-MariaDB - MariaDB Server
Connection port: 3306
Compressed protocol: No
Unicode enabled: Yes
SSL enabled: No
max_allowed_packet: 32,0 MiB
Client version (libmysql.dll): 5.6.6-m9
Uptime: 19:47:37
Threads: 16
Questions: 2 699 839
Slow queries: 0
Opens: 2 170
Flush tables: 1
Open tables: 1 105
Queries per second avg: 37,888
[OK]

**Comment by id333k** [comment]
>Could you check the output SQL on log when you create your user on User Manager?
`CREATE USER 'V8PG8TSZW4SHDL40OMKDCJEIXH5WZKBUIF8NNMJ18W70IQCRODN9QNV8DA9NDBVUCD4MC3WL871IFS31'@'%' IDENTIFIED BY '8L0LQCU44DYM499CTXZ71K6HL41QT48PK0PSWWK31YTQXK6NWPFXFHY891L5CWNKV7397BXUXTZMWCMVSR4LJZGXE37RGK7DKYZV';
GRANT EXECUTE, PROCESS, SELECT, SHOW DATABASES, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TABLESPACE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, CREATE USER, FILE, LOCK TABLES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHUTDOWN, SUPER  ON *.* TO 'V8PG8TSZW4SHDL40OMKDCJEIXH5WZKBUIF8NNMJ18W70IQCRODN9QNV8DA9NDBVUCD4MC3WL871IFS31'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'V8PG8TSZW4SHDL40OMKDCJEIXH5WZKBUIF8NNMJ18W70IQCRODN9QNV8DA9NDBVUCD4MC3WL871IFS31'@'%';
`
>could you check if when you open the User Manager the user is cutted off or it is represented correctly?
`SHOW GRANTS FOR 'V8PG8TSZW4SHDL40OMKDCJEIXH5WZKBUIF8NNMJ18W70IQCRODN9QNV8DA9NDBVUCD4MC3WL871IFS31'@'%';`
it's ok. everything is correctly, expect one thing: if I point mouse to any username, there is a red message: "This user has an empty password". Same message in other clients.

**Comment by id333k** [comment]
C:\Program Files\HeidiSQL\libmysql.dll 4,52 МБ (4 747 776 byte)
Client version (libmysql.dll): 5.6.6-m9
I don't have libmariadb.dll in the folder.

I have downloaded now the portable version:
..\HeidiSQL_9.5_Portable\libmysql.dll 4,25 МБ (4 465 152 байт)
same version: (libmysql.dll): 5.6.6-m9
Same strory, don't have libmariadb.dll in the folder.

Obviously, you need to make a message in the program so that new users like me must download and add the file manually to the folder, if you have a reason not to include it in setup or portable build.
So, where I can download it?
Now it became clear why the program often crashes.

**Comment by id333k** [comment]
I downloaded mariadb-10.2.12-winx64.zip from:
https://downloads.mariadb.org/mariadb/10.2.12/#os_group=windows
and extracted libmariadb.dll from lib folder to HeidiSQl folder.
Now, it's ok:
Client version (libmariadb.dll): 10.2.12
And now I can connect to any usernames with 80 characters.
Thanks for help! This issue can be closed.
If you will add a message in your program about libmariadb.dll it will save your time and helps new users to stay away from bugs and crashes.

**Comment by ansgarbecker** [comment]
The libmariadb.dll was added after the 9.5 release. So, the next release will have the updated one.
Sorry for the confusion, didn't think that this causes such a confusion for user names.

**Comment by ansgarbecker** [comment]
Just to complete my explanation: if there's a new Heidi release, users cannot use the auto-updater for getting a nightly build, unless they install the new release at first. That's intentionally for exactly your mentioned reasons. Otherwise people would be able to sit on their old libraries across releases.
The only remaining question is when I'll release v9.6 . No clue yet.
