### ISSUE TITLE
"Explain analyzer for current query" does not work

### ISSUE THREAD

**Issue by richardeaxon** [HeidiSQL/HeidiSQL#1240]
**Describe the bug**
"Explain analyzer for current query" does not work - results in "EXPLAIN ;" SQL.

**To Reproduce**
1. Open HeidiSQL and open a saved session
2. Press CTRL-T to open new query tab
3. Create a simple query like "SELECT * FROM xxx;"
4. Run the query by pressing F9
5. Select the "Query" menu, then "Explain analyzer for current query"
6. See SQL error message due to invalid query generated

**Expected behavior**
The EXPLAIN should contain the query from the query tab

**Screenshots**
N/A

**Environment:**
 - OS: Windows 10
 - HeidiSQL version: 11.1.0.6116 
 - Database type and version: MariaDB 10.4.14

**Comment by ansgarbecker** [comment]
For me this works as designed.

Did you perhaps have your cursor after the closing query semicolon? The "_current query_" is defined as the "_query where your cursor is currently_"

**Comment by richardeaxon** [comment]
Some more info. If the cursor focus is not in the query tab window (just click on a database in the left nav bar to remove focus) then the menu options is still selectable and results in empty explain. If you move focus out of the query tab then the menu option should probably not be selectable. Also as you mentioned if the cursor focus is after the ; then you get an empty explain and an sql error. Perhaps check for empty explain condition and popup some usage information instead of allowing the database to throw an error. Now that you have shown how it works it makes sense, but it was not intuitive initially.

EXPLAIN ;
/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1 */

**Comment by ansgarbecker** [comment]
Yes, reasonable.

**Comment by ansgarbecker** [comment]
Menu items should both be disabled now when no current query is available.
