### ISSUE TITLE
Crashes and hangs on latest stable HeidiSQL version

### ISSUE THREAD

**Issue by hahyes** [HeidiSQL/HeidiSQL#1241]
**Describe the bug**
Application crash in random situations with error `Access violation`. For example, while ago I just select database and error appeared. Random hangs and freezes happens too. When I tried to open some cell with string value - app froze and crashed without any error.

**To Reproduce**
Sadly I just can't, it's pure random. I can deliver more reports from errors.

**Detailed report**
Error showed by HeidiSQL: https://pastebin.pl/view/016d2de2

**Environment:**
 - OS: Windows 10 20H1 (2004)
 - HeidiSQL version: 11.1.0.6116
 - Database type and version: MariaDB 10.3.25

**Comment by ansgarbecker** [comment]
The callstack definitely says it's something with the theme you likely have selected. Please try the default "Windows" theme instead.

Also, I recently updated the vcl-styles code in 6475b1e098cb88941d8bceff4a9224141965b68b , so you should update to the latest build.

And please report if that already helped.

Appending the relevant part of your crash report here:

```
exception class    : EAccessViolation
exception message  : Access violation at address 0000000000681C9F in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF.
 
main thread ($34bc):
00681c9f heidisql.exe Vcl.Graphics               TCanvas.GetHandle
0078454b heidisql.exe Vcl.ComCtrls               TTabControlStyleHook.Paint
00800656 heidisql.exe Vcl.Themes                 TStyleHook.WMPaint
0040ed32 heidisql.exe System                     TObject.Dispatch
00800e03 heidisql.exe Vcl.Themes                 TStyleHook.WndProc
00801194 heidisql.exe Vcl.Themes                 TMouseTrackControlStyleHook.WndProc
00782bc2 heidisql.exe Vcl.ComCtrls               TTabControlStyleHook.WndProc
00800129 heidisql.exe Vcl.Themes                 TStyleHook.HandleMessage
00cb1aae heidisql.exe Vcl.Styles                 TStyleEngine.HandleMessage
007fbc2c heidisql.exe Vcl.Themes                 TStyleManager.HandleMessage
006d18e4 heidisql.exe Vcl.Controls               TWinControl.DoHandleStyleMessage
006d3964 heidisql.exe Vcl.Controls               TWinControl.WndProc
006d33fa heidisql.exe Vcl.Controls               TWinControl.MainWndProc
00568793 heidisql.exe System.Classes             StdWndProc
7ff916cc ntdll.dll                               KiUserCallbackDispatcher
7ff915c7 USER32.dll                              CallWindowProcW
006d43c2 heidisql.exe Vcl.Controls               TWinControl.DefaultHandler
0040ed40 heidisql.exe System                     TObject.Dispatch
006ccfbd heidisql.exe Vcl.Controls               TControl.WndProc
006d422b heidisql.exe Vcl.Controls               TWinControl.WndProc
006d33fa heidisql.exe Vcl.Controls               TWinControl.MainWndProc
00568793 heidisql.exe System.Classes             StdWndProc
7ff915c7 USER32.dll                              SendMessageW
0042ece4 heidisql.exe Winapi.Messages            SendStructMessage
0074e545 heidisql.exe Vcl.ComCtrls               TTabStrings.Insert
00547fc9 heidisql.exe System.Classes             TStrings.InsertObject
007515ff heidisql.exe Vcl.ComCtrls               TPageControl.InsertTab
007506c5 heidisql.exe Vcl.ComCtrls               TTabSheet.SetTabShowing
007507af heidisql.exe Vcl.ComCtrls               TTabSheet.UpdateTabShowing
00750712 heidisql.exe Vcl.ComCtrls               TTabSheet.SetTabVisible
00ef5db9 heidisql.exe Main             9212 +149 TMainForm.DBtreeFocusChanged
0096b614 heidisql.exe VirtualTrees    19935   +2 TBaseVirtualTree.DoFocusChange
009728ae heidisql.exe VirtualTrees    22698 +281 TBaseVirtualTree.HandleMouseDown
00965525 heidisql.exe VirtualTrees    17341   +6 TBaseVirtualTree.WMLButtonDown
0040ed32 heidisql.exe System                     TObject.Dispatch
00979e02 heidisql.exe VirtualTrees    25633  +19 TBaseVirtualTree.WndProc
006d33fa heidisql.exe Vcl.Controls               TWinControl.MainWndProc
00568793 heidisql.exe System.Classes             StdWndProc
7ff915c7 USER32.dll                              DispatchMessageW
0088b1ee heidisql.exe Vcl.Forms                  TApplication.ProcessMessage
0088b263 heidisql.exe Vcl.Forms                  TApplication.HandleMessage
0088b6b1 heidisql.exe Vcl.Forms                  TApplication.Run
00f18468 heidisql.exe heidisql          103  +41 initialization
7ff91650 KERNEL32.DLL                            BaseThreadInitThunk
7ff916c7 ntdll.dll                               RtlUserThreadStart
```

**Comment by hahyes** [comment]
> The callstack definitely says it's something with the theme you likely have selected. Please try the default "Windows" theme instead.
> 
> Also, I recently updated the vcl-styles code in [6475b1e](https://github.com/HeidiSQL/HeidiSQL/commit/6475b1e098cb88941d8bceff4a9224141965b68b) , so you should update to the latest build.
> 
> And please report if that already helped.
> 
> Appending the relevant part of your crash report here:
> 
> ```
> exception class    : EAccessViolation
> exception message  : Access violation at address 0000000000681C9F in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF.
>  
> main thread ($34bc):
> 00681c9f heidisql.exe Vcl.Graphics               TCanvas.GetHandle
> 0078454b heidisql.exe Vcl.ComCtrls               TTabControlStyleHook.Paint
> 00800656 heidisql.exe Vcl.Themes                 TStyleHook.WMPaint
> 0040ed32 heidisql.exe System                     TObject.Dispatch
> 00800e03 heidisql.exe Vcl.Themes                 TStyleHook.WndProc
> 00801194 heidisql.exe Vcl.Themes                 TMouseTrackControlStyleHook.WndProc
> 00782bc2 heidisql.exe Vcl.ComCtrls               TTabControlStyleHook.WndProc
> 00800129 heidisql.exe Vcl.Themes                 TStyleHook.HandleMessage
> 00cb1aae heidisql.exe Vcl.Styles                 TStyleEngine.HandleMessage
> 007fbc2c heidisql.exe Vcl.Themes                 TStyleManager.HandleMessage
> 006d18e4 heidisql.exe Vcl.Controls               TWinControl.DoHandleStyleMessage
> 006d3964 heidisql.exe Vcl.Controls               TWinControl.WndProc
> 006d33fa heidisql.exe Vcl.Controls               TWinControl.MainWndProc
> 00568793 heidisql.exe System.Classes             StdWndProc
> 7ff916cc ntdll.dll                               KiUserCallbackDispatcher
> 7ff915c7 USER32.dll                              CallWindowProcW
> 006d43c2 heidisql.exe Vcl.Controls               TWinControl.DefaultHandler
> 0040ed40 heidisql.exe System                     TObject.Dispatch
> 006ccfbd heidisql.exe Vcl.Controls               TControl.WndProc
> 006d422b heidisql.exe Vcl.Controls               TWinControl.WndProc
> 006d33fa heidisql.exe Vcl.Controls               TWinControl.MainWndProc
> 00568793 heidisql.exe System.Classes             StdWndProc
> 7ff915c7 USER32.dll                              SendMessageW
> 0042ece4 heidisql.exe Winapi.Messages            SendStructMessage
> 0074e545 heidisql.exe Vcl.ComCtrls               TTabStrings.Insert
> 00547fc9 heidisql.exe System.Classes             TStrings.InsertObject
> 007515ff heidisql.exe Vcl.ComCtrls               TPageControl.InsertTab
> 007506c5 heidisql.exe Vcl.ComCtrls               TTabSheet.SetTabShowing
> 007507af heidisql.exe Vcl.ComCtrls               TTabSheet.UpdateTabShowing
> 00750712 heidisql.exe Vcl.ComCtrls               TTabSheet.SetTabVisible
> 00ef5db9 heidisql.exe Main             9212 +149 TMainForm.DBtreeFocusChanged
> 0096b614 heidisql.exe VirtualTrees    19935   +2 TBaseVirtualTree.DoFocusChange
> 009728ae heidisql.exe VirtualTrees    22698 +281 TBaseVirtualTree.HandleMouseDown
> 00965525 heidisql.exe VirtualTrees    17341   +6 TBaseVirtualTree.WMLButtonDown
> 0040ed32 heidisql.exe System                     TObject.Dispatch
> 00979e02 heidisql.exe VirtualTrees    25633  +19 TBaseVirtualTree.WndProc
> 006d33fa heidisql.exe Vcl.Controls               TWinControl.MainWndProc
> 00568793 heidisql.exe System.Classes             StdWndProc
> 7ff915c7 USER32.dll                              DispatchMessageW
> 0088b1ee heidisql.exe Vcl.Forms                  TApplication.ProcessMessage
> 0088b263 heidisql.exe Vcl.Forms                  TApplication.HandleMessage
> 0088b6b1 heidisql.exe Vcl.Forms                  TApplication.Run
> 00f18468 heidisql.exe heidisql          103  +41 initialization
> 7ff91650 KERNEL32.DLL                            BaseThreadInitThunk
> 7ff916c7 ntdll.dll                               RtlUserThreadStart
> ```

It seems like changing theme to "Windows" fixed regular problem with crashes, thank you. 
I used Material built-in skin earlier.

About fix in newest version, I will wait for next stable cause night build usually seems to "not like me" very much. I believe, it will be fixed then. Thank you very much for help. 👍

**Comment by ansgarbecker** [comment]
I'm afraid I was not really able to fix such bugs in the themes myself. I have to rely on fixes from Embarcadero. Marking this issue as upstream and closing it.
Apart from that, I just removed the theme selector from the installer, as the Material theme is not maintained currently.
