### ISSUE TITLE
'ON UPDATE CURRENT_TIMESTAMP' part missing after create table

### ISSUE THREAD

**Issue by User756675678** [HeidiSQL/HeidiSQL#1243]
**Describe the bug**
I create table manually with field
`ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`
select table in heidi and now part `ON UPDATE CURRENT_TIMESTAMP` disappear.
I try see it on tab with CREATE code, but see this:
`ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,`
I run `SHOW CREATE TABLE` request and here all as I send to server:
`ts timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`
So it is something wrong with heidi.

**To Reproduce**
1. Create table with  `ON UPDATE CURRENT_TIMESTAMP` part.
2. Check table fields info.
3. Check CREATE code.

**Expected behavior**
`ON UPDATE CURRENT_TIMESTAMP` part not disappear.

**Screenshots**

**Environment:**
 - OS: Windows 7
 - HeidiSQL version 11.1.0.6141 64-bit
 - Database type and version MySQL 8.0.20

**Comment by ansgarbecker** [comment]
Probably an issue with MySQL 8, I cannot reproduce that with MariaDB 10.3

**Comment by ansgarbecker** [comment]
Hm, even on MySQL 8.0.19 I cannot reproduce that. The TS column keeps the `ON UPDATE` clause in the table designer:

![grafik](https://user-images.githubusercontent.com/7986591/100903890-b46ad000-34c6-11eb-8fab-7a885602022e.png)

**Comment by ansgarbecker** [comment]
@User756675678 : please test such a query:

```
SELECT * FROM `information_schema`.`COLUMNS`
WHERE TABLE_SCHEMA='your-database' AND TABLE_NAME='your-table'
ORDER BY ORDINAL_POSITION
```

Please replace "your-database" and "your-table" according to your names.
Watch out
* if the query fails (!)
* if not - what does the "EXTRA" column contain? For me here it is `DEFAULT_GENERATED on update CURRENT_TIMESTAMP`

**Comment by User756675678** [comment]
> what does the "EXTRA" column contain?

`DEFAULT_GENERATED on update CURRENT_TIMESTAMP`

Same issue on MySQL 8.0.21 hosted on Linux. And same result of your query.

**Comment by User756675678** [comment]
Reason:
Changes from this commit https://github.com/HeidiSQL/HeidiSQL/commit/849a50c4f396af3ef86ba57e5004c173fa1556ee
not applied for 
`function TMySQLConnection.GetTableColumns(Table: TDBObject): TTableColumnList;`
```
    // MySQL pre-5.0 has no IS.COLUMNS table
    ColQuery := GetResults('SHOW FULL COLUMNS FROM '+QuoteIdent(Table.Database)+'.'+QuoteIdent(Table.Name));
```

**Comment by ansgarbecker** [comment]
`TMySQLConnection.GetTableColumns` is a fallback for MySQL pre-5.0 servers. How can that fix your issue if you run MySQL 8? The fallback applies only if there is no IS.columns table, but your above query shows you have that table.

**Comment by User756675678** [comment]
IDK how. I initially edit places with look similar to your test question but realize it not run. So I find this. And this run. IDK why this selected. I use libmariadb.dll - maybe because of that?
I can check critical places for choose if you say where it is.

**Comment by ansgarbecker** [comment]
You could probably watch out if Heidi fires such a query:

    SHOW FULL COLUMNS FROM ...

... or this one:

    SELECT * FROM information_schema.COLUMNS ...

**Comment by User756675678** [comment]
Yep, it fires `SHOW FULL COLUMNS FROM`. Need figure why. Where choose happen?

**Comment by User756675678** [comment]
`InformationSchemaObjects` is empty.

**Comment by ansgarbecker** [comment]
Maybe due to a hidden `information_schema` database. I guess it's not visible in the database tree?

**Comment by ansgarbecker** [comment]
Next build should retrieve column details through information_schema.columns, even if information_schema is hidden by session settings. That way, the `ON UPDATE` clause should be detected correctly now.
