### ISSUE TITLE
VARCHAR 255 display as VARCHAR without size

### ISSUE THREAD

**Issue by User756675678** [HeidiSQL/HeidiSQL#1245]
**Describe the bug**
tab CREATE:
![img](https://user-images.githubusercontent.com/53032556/100865541-2380fe00-34a0-11eb-9fcd-8964d1ee582c.png)
Grid:
![img](https://user-images.githubusercontent.com/53032556/100865627-3c89af00-34a0-11eb-938d-071fd6308f84.png)
SHOW CREATE TABLE:
![img](https://user-images.githubusercontent.com/53032556/100865700-5925e700-34a0-11eb-97f7-fed3511dcf92.png)

**To Reproduce**
1. Create VARCHAR(255) field in table.
2. Open grid with fields for table or CREATE tab.

**Expected behavior**
Length specifier (255) not missing.

**Screenshots**
See above.

**Environment:**
 - OS: Windows 7
 - HeidiSQL version 11.1.0.6141 64-bit
 - Database type and version MySQL 8.0.20

**Comment by ansgarbecker** [comment]
Perhaps same as issue #1243

**Comment by User756675678** [comment]
Issue happen only if length is 255. if I set 254 or 256 - length appear as must be.

Related part (second row on picture) of 
SELECT * FROM `information_schema`.`COLUMNS`
![img](https://user-images.githubusercontent.com/53032556/100971995-a9ed1c80-3540-11eb-95fb-2a446902ff7f.png)

**Comment by ansgarbecker** [comment]
Should be solved in the next build - please test.
I broke that while extending the data types for csv layout detection (#477): https://github.com/HeidiSQL/HeidiSQL/commit/5df6149db4de3a263ce2e465c379d3ddd7cd3824#diff-5b33e21b27333a526e2a22449b72da5a9eda3042a4e8e76658c61ea2fb150584R881

**Comment by User756675678** [comment]
Solved. Thanks.
