### ISSUE TITLE
Invalid Postgresql query: "drop foreign key"

### ISSUE THREAD

**Issue by TheColorRed** [HeidiSQL/HeidiSQL#1247]
Relates to: https://www.heidisql.com/forum.php?t=37283

When dropping a key in the "Foreign keys" tab, the command that is executed is this:

```
ALTER TABLE "example" DROP FOREIGN KEY "FK_key";
```

This throws an error:

> ERROR:  syntax error at or near "FOREIGN" LINE 2:  DROP FOREIGN KEY "FK_key"

The proper syntax is (at least one that works) uses `DROP CONSTRAINT` instead of `DROP FOREIGN KEY`:

```
ALTER TABLE "example" DROP CONSTRAINT "FK_key";
```

PostgreSQL version:

```
$ SELECT VERSION()
PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit
```

**Comment by narrowizard** [comment]
Same here, waiting for a fix release. is there any release plan for v11.3?

**Comment by ansgarbecker** [comment]
No date set for next releases. I only planned to release more often, probably with less modifications then.

**Comment by TheDude-gh** [comment]
This would be nice to have fixed asap.

**Comment by arecaps** [comment]
Any plan to fix this?
