### ISSUE TITLE
Color for table name is missing

### ISSUE THREAD

**Issue by franky920920** [HeidiSQL/HeidiSQL#1250]
**To Reproduce**
1. Go to Query tab
2. Type the SQL script like
```SQL
SELECT test_data.* LIMIT 100
```

**Expected behavior**
The font color for table name should be red like previous version

**Screenshots**
![image](https://user-images.githubusercontent.com/11349917/101481755-82180300-390a-11eb-96d4-dbb90146f208.png)

**Environment:**
 - OS: Windows 10 20H2 build 19042.630
 - HeidiSQL version: 11.1.0.6145 (64bit)
 - Database type and version: MySQL Enterprise Server 8.0.22

**Comment by franky920920** [comment]
Update: reinstall heidisql to the lastest version on the website (11.1.0.6116) fixed this [Not the lastest version 11.1.0.6145 checked by the "check for update"].

**Comment by ansgarbecker** [comment]
Although I already saw that effect, I am not able to reproduce it. I am also unsure whether my just pushed modification changes anything here. Do you know how to reproduce it?

**Comment by franky920920** [comment]
Steps to reproduce it:
1. Launch Windows Sandox.
2. Grab Heidisql setup (v11.1.0.6116) from heidisql.com
3. Launch setup and complete the installation.
4. It's working fine in this version
![image](https://user-images.githubusercontent.com/11349917/101559711-8a0d8c80-3976-11eb-9974-73d8ea3362c8.png)
5. Click Help -> Check for Updates from the menu.
6. Download and install build 6147.
7. Connect to database and type the SQL script.
![image](https://user-images.githubusercontent.com/11349917/101559689-81b55180-3976-11eb-966d-6dc1fa9793d8.png)

And it's working on build 6147.
So it seems to be a bug on build 6145 and fixed in the build 6147.
I'll go ahead and close this issue. Thanks!
