### ISSUE TITLE
crash connecting to postgresql over forwarded ssh port

### ISSUE THREAD

**Issue by Deracination** [HeidiSQL/HeidiSQL#1251]
**Describe the bug**
Connecting to postgresql via ssh tunnel provided by putty. Heidi exits (crashes?) with no messages. I know the port forwarding is working because initially I was seeing errors in the postgresql log about the pg_hba.conf not permitting the connection. I've allowed the connection and now heidi crashes silently.

**To Reproduce**
1. Run Heidi
2. Click on the configured Postgresql TCP/IP connection to localhost forwarded port
3. Heidi exits after a couple of seconds

**Expected behavior**
Expect to connect or at least see an error/warning message

**Environment:**
 - OS: Windows 10
 - HeidiSQL version 11.1.0.6116
 - Database type and version postgresql 9.6.17

**Comment by ansgarbecker** [comment]
Please provide a way to forward a port through putty.
I have no PostgreSQL server on a remote system. Can I forward the port of my local installation to another local port through putty? Of course assuming I have an SSH server running.
