### ISSUE TITLE
"file does not exist" error after changing a connection network type

### ISSUE THREAD

**Issue by Deracination** [HeidiSQL/HeidiSQL#1252]
**Describe the bug**
Changing a connection network type and then trying to connect results in a warning dialog saying 'file does not exist'

**To Reproduce**
1. Run Heidi
2. Change the 'network type' of a connection (eg change postgresql tcp/ip to postgresql ssh)
3. Try to connect

**Screenshots**

![image](https://user-images.githubusercontent.com/9244595/101552151-6e51c700-3a06-11eb-9ba2-d3bf81ca73d7.png)

**Environment:**
 - OS: Windows 10
 - HeidiSQL version 11.1.0.6116

**Comment by ansgarbecker** [comment]
The library drop-down has no selection after changing the network type.
I will have to pre-select the first available one then.
