### ISSUE TITLE
SQL editor : cursor moving and edittng are not drawn correctlly if you have over 92 characters in a line.

### ISSUE THREAD

**Issue by kitora** [HeidiSQL/HeidiSQL#1254]
**Describe the bug**
In SQL editor, you have trouble if you enter over 92 characters (count as ASCII) in a line.
Cursor is not drawn after editing and enter Enter key or editing by mouse.

**To Reproduce**
1. Open SQL editor
2. Enter 93bytes any character.
3. Press left cursor key.

**Expected behavior**
Cursor is shown on correct place.
Modifications are applied and displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1788973/101667545-cc2bf080-3a92-11eb-8e2c-01b2fa03122d.png)
When I input 93rd "a", small dot appears between 92nd and 93rd "a".
It's the sign of this issue occurs.

**Environment:**
 - OS: [Windows 10]
 - HeidiSQL version [11.1.0.6147 (64 Bit)]
 - Database type and version [PostgreSQL 13.1]

**Comment by ansgarbecker** [comment]
Cannot reproduce that here.
Please retry using the "Windows" theme:
![grafik](https://user-images.githubusercontent.com/7986591/101673708-ccf36100-3a57-11eb-9cfe-05b4d512f4eb.png)

**Comment by kitora** [comment]
![image](https://user-images.githubusercontent.com/1788973/101711271-9c9ed780-3ad6-11eb-9b12-225324db7277.png)
![image](https://user-images.githubusercontent.com/1788973/101711305-ab858a00-3ad6-11eb-9b24-921eda109779.png)

Set Application language to en:English , and StyleTheme to Windows.
Editor's font is Consolas.
Yet reproduced on my environment.

According to your comment, I checked other UI settings.
And I got reproducing condition.

"Override high DPI scaling behavior" in .exe property.
https://blogs.windows.com/windowsdeveloper/2017/05/19/improving-high-dpi-experience-gdi-based-desktop-apps/
 - Configuring a local app to run with enhanced system scaling

If this property is set to "System(enhanced)", this phenomenon occurs.
This may be the problem of Windows?

**Comment by ansgarbecker** [comment]
So I understand right if you leave the DPI setting as is, the issue is gone?
High DPI mode is anyway not supported in HeidiSQL, due to various issues. If you activate that setting through Windows, you will get many other issues as well.

**Comment by kitora** [comment]
Yes, the issue was gone when I change "Override high DPI scaling behavior" to other than "System(enhanced)".
Please close this issue.

I had forgotten to reset this setting when HeidiSQL dropped HighDPI support...
Windows' HighDPI functions are curious for me.
