### ISSUE TITLE
Duplicate last used collations on top of dropdown list

### ISSUE THREAD

**Issue by User756675678** [HeidiSQL/HeidiSQL#1255]
**Is your feature request related to a problem? Please describe.**
When you want select collation list is very huge, so find something on it is problematic. Most values never used at all.

**Describe the solution you'd like**
List of last used collation duplicated at top of list. Next is horizontal line and full list of collations.
It can be near 20 last used collations. So after some use list will be stable and combobox fast in use.

**Describe alternatives you've considered**
Add to settings possibility select items which appears in dropdown. but this need more code, special UI and so on.

**Additional context**
Nope.

**Comment by ansgarbecker** [comment]
Please comment in this forum thread, for which I recently made the collation drop-down editable:
https://www.heidisql.com/forum.php?t=37117

**Comment by User756675678** [comment]
Completely different functionality.

I don't want everyone to practice typing a bunch of characters. I want to solve my problem in two clicks.

Moreover, given that most collates are very similar at the beginning, it generally has little use other than the first few characters.

And you shouldn't have closed the issue - it is absolutely unrelated to your comment and link.

For example, I like AkelPad, where I can leave in the settings only those encodings that I really need, and not every time to search for them in a huge list.

I don't understand why I have to do this here all the time.

Moreover, the task is technically very simple. If it bothers someone, you can simply make it possible to disable statistics collection in the settings and it will work.

**Comment by User756675678** [comment]
Fix dirty and not general. So not recommended to include in main project code.
For real use need more work, but nothing too complicated.

**Comment by ansgarbecker** [comment]
I just asked you to leave a comment there, so we don't have two places with a similar discussion. The request is the same: finding a collation more quickly.
I don't want two solutions for one issue, so either we will go with the current editable drop-downs, or probably with your idea.
