### ISSUE TITLE
[sqlite] Renaming columns not possible using UI 

### ISSUE THREAD

**Issue by jojomatik** [HeidiSQL/HeidiSQL#1256]
**Describe the bug**
It is not possible to rename columns using the UI since HeidiSQL tries to use the *change column syntax* ( `CHANGE COLUMN old_col_name new_col_name column_definition`) unsupported by SQLite. See also [SQLite-Documentation](https://www.sqlite.org/omitted.html).

**To Reproduce**
1. Create table `test` with one column `column 1`
2. Try to rename `column 1` to `column 2`
3. Hit `Save`
```
ALTER TABLE "test"
	CHANGE COLUMN "column 1" "column 2" INTEGER NULL;
/* SQL Error (1): near "CHANGE": syntax error */
```

**Expected behavior**
According to the [SQLite-Documentation](https://www.sqlite.org/omitted.html), the *rename column syntax* (`RENAME COLUMN old_col_name TO new_col_name`) is supported. Therefore this syntax should be used. All other operations like changing column definitions should be disabled in the UI. 

Alternatively the user could be provided with one of the available workarounds such as: renaming the table, creating a new table and copying all data. This should definitely be disclosed before the operation is run and the user should be able to decide whether or not he wants to take the risk of potential damages to foreign key links or similar problems one could imagine.

**Environment:**
 - OS: Windows 10
 - HeidiSQL version 11.1.0.6116
 - SQLite3

**Comment by jojomatik** [comment]
I just had a look into how other GUI-Tools for browsing and editing SQLite databases would handle editing columns.

I don't want to go into too much detail as I'm not at all competent enough to write a fail proof concept nor have I completely scanned all the queries issued by the software, but as far as i can tell [sqlitebrowser](https://github.com/sqlitebrowser/sqlitebrowser) for example is re-creating the table. So apparently the risk of loosing data can be minimized if certain precautions are taken, but I'm sure there are people out here that are way more qualified than me when it comes to SQL and would be keen to comment on this.

As I said in the initial comment of this issue, I'm not really asking for implementing such a procedure, much rather I'd have the relevant input fields disabled or a custom error message explaining the limitations of SQLite and the correct syntax for renaming columns, but it would be a nice addition anyway (maybe this part of the issue should get its own feature request issue).

**Comment by ansgarbecker** [comment]
Next build can now rename columns in SQLite, using the `ALTER TABLE x RENAME COLUMN y TO z` syntax.

Other modifications are not directly supported in SQLite, e.g. changing the data type. This would require a rewrite of the whole table, like described [in the docs](https://www.sqlite.org/lang_altertable.html#making_other_kinds_of_table_schema_changes).

**Comment by jojomatik** [comment]
> Next build can now rename columns in SQLite, using the `ALTER TABLE x RENAME COLUMN y TO z` syntax.
> 
> Other modifications are not directly supported in SQLite, e.g. changing the data type. This would require a rewrite of the whole table, like described [in the docs](https://www.sqlite.org/lang_altertable.html#making_other_kinds_of_table_schema_changes).

Great, Thanks 👍 

Could you make sure that these other modifications are blocked in the first place to indicate that such operations are not possible and to prevent that an error occurs?

**Comment by ansgarbecker** [comment]
Makes sense, otherwise the user is left alone without knowing why his changes did not take affect. 
Next build disables most column changes when editing an existing table. Also, an explanatory message in the log panel says why, once.

**Comment by jojomatik** [comment]
Thanks 👍
