### ISSUE TITLE
LEFT prevents access to data of PSQL<=9.0 tables with text data

### ISSUE THREAD

**Issue by nummacway** [HeidiSQL/HeidiSQL#1259]
**Describe the bug**

**To Reproduce**
1. Connect to a server running PSQL 9.0 or below
2. View data of a table that has a text-typed column
3. HeidiSQL fails because LEFT does not exist

**Expected behavior**
Shows data.

**Workaround**
Manually run "SELECT * FROM table"

**Suggested solution**
Stop using LEFT on PSQL <= 9.0, add an option to turn this off, or use SUBSTRING instead.

**Environment:**
 - HeidiSQL version 11.0.6113
 - Database type and version PostgreSQL 8.4, but according to documentation, HeidiSQL won't with 9.0 either and requires at least 9.1 to run.

**Comment by ansgarbecker** [comment]
Should be easy to fix, as that `LEFT` is already kind of template based in HeidiSQL.

Please be more exact with the versions - HeidiSQL 11.0 or 11.1?

**Comment by nummacway** [comment]
This was in 11.0. I just updated and the error still occurs:

ERROR: function left(text, integer) does not exist.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.

**Comment by ansgarbecker** [comment]
That `SUBSTR()` broke support for Redshift, like reported here: https://www.heidisql.com/forum.php?t=38326
I will replace it with `SUBSTRING()` instead, hoping that does not make problems with normal PG servers.

**Comment by nummacway** [comment]
No issues with SUBSTRING on PSQL.
