### ISSUE TITLE
Autocomplete: search on mid

### ISSUE THREAD

**Issue by rentalhost** [HeidiSQL/HeidiSQL#126]
**Improvement request:** currently the autocomplete is based on first string index to last (eg. in regular-expression `/^searchterm/`), instead of filter it from the mid (eg. `/searchterm/`). For instance: if you have two columns like `user_firstname`, `user_lastname`, you need write `user_l` to access the second column, but is preferable that you just write `l` (from `lastname`) to found it.

**Actually**: I have a table called `sistema_rns`, to found it I should write `sistema_r...`.

![image](https://user-images.githubusercontent.com/421851/36075876-b66bd24a-0f3b-11e8-83ff-647c6310a8c5.png)

**How it could be:** just write `rns`:

![image](https://user-images.githubusercontent.com/421851/36075905-2b4f37dc-0f3c-11e8-9b40-f17e650bffa2.png)

* **HeidiSQL version**: 9.5.0.5245 (from 2018-02-11)

**Comment by fifonik** [comment]
The proposed "improvement" would not be an improvement for everyone. For some people (I'd say for majority) it would make things worse.

I do not have such long prefixes in my database and my columns named firstname, lastname and middlename.
Right now, when I'm pressing 'm' I'm receiving a single line in auto-completion dropdown: middlename. Easy.
If you suggestion implemented, I will receive all 3 items, so I would need to key in 'mi' to get middlename. It would not be possible to use single-letter shortcuts at all.

So the option must be optional if implemented.

**Comment by rentalhost** [comment]
Actually it will not affect you except that will shows 3 suggestions instead of 1. It because the list should be sortered by proximity to first index. Só if you search by "m", then you will have this suggestions in that order:

1. `middlename`: `m` is ar index 0;
2. `lastname`: `m` is at index 7;
3. `firstname`: `m` is at index 8;

**Comment by fifonik** [comment]
No way!
It would be nightmare to find required word in the dropdown list then!
Items in dropdown lost must be ordered alphabetically only!

**Comment by lukinhaspm** [comment]
I agree with @fifonik , alphabetically only... or an parameter to change this

**Comment by rentalhost** [comment]
@fifonik your "na" example will just display elements that have "na" in some part of string, but will keep the "name" (supposing that we have a column like it) above "lastname" (then if you hit enter here, "name" will be selected), for instance. And it will be very useful if you want to list the "name" fields. For instance, if I input "name" I will receive "name", "lastname", "firstname" and "middlename" (in that order). All the terms are related to "name" input and you not need remember exactly all the columns name, just part of it (maybe if you use legacy systems with more than 100 tables and 20~50 columns by table you will understand my point).

@fifonik and @lukinhaspm currently the items of dropdown are sortered by "structural order" from table structure original order (and not alphabetically). So it will not do difference anyway.

**Comment by lukinhaspm** [comment]
@rentalhost good point! I think the better way is alphabetically... @ansgarbecker  it is another request?

**Comment by penCsharpener** [comment]
What about a form of camel case but instead auto-completion also looks for lowercase letters after an underscore.
example: 
typing `na` would find first all entries with `na` at the beginning but then also those that have `_na` in the name. 

I use a lot prefixes and this would really help me but I'm not sure whether I've drifted away from convensions.

**Comment by ansgarbecker** [comment]
I just added a new checkbox option in the preferences dialog for that search-in-the-middle feature:
![grafik](https://user-images.githubusercontent.com/7986591/79069504-132cd080-7ccf-11ea-9d37-97bc65214a62.png)

I stumbled across that `scoLimitToMatchedTextAnywhere` setting during the recent SynEdit update, which referenced https://github.com/SynEdit/SynEdit/issues/136

**Comment by lukinhaspm** [comment]
Great, works really fine!! Thanks a lot!
