### ISSUE TITLE
Auto-reformat messes up string constants and misses ORDER BY.

### ISSUE THREAD

**Issue by mbomb007** [HeidiSQL/HeidiSQL#1260]
**Describe the bug**

Keywords in string constants are modified, which changes and messes with queries.

Also, when formatting, sometimes not the entire query is reformatted.

**To Reproduce**
1. Paste in the following query (so that the key words don't auto-capitalize):

```sql
select 
	f.id

from f

where 
	f.val like '%"test/default%'

order by f.id
```

2. Click the paintbrush "auto-reformat" button.
3. The result is the following:

```sql
SELECT 
	f.id
FROM f
WHERE 
	f.val LIKE '%"test/ DEFAULT%'

order by f.id
```

**Expected behavior**

The string `'%"test/default%'` should not be modified, and the ORDER BY should be formatted. I do not know if these issues occur with other keywords.

**Environment:**
 - OS: Windows 10
 - HeidiSQL version: 11.1.0.6116 (64-bit)
 - Database type and version: MariaDB 10.5

**Comment by ansgarbecker** [comment]
Related to #750

**Comment by ben-inqipit** [comment]
Hi! Thanks for this great application!

I confirm the bug, the auto-reformat changes the syntax and reformated query returns nothing !

Original query:
```sql
select * from `deliveries` where `status` = "done" and json_unquote(json_extract(`config`, '$."purge"."enabled"')) = "true" and json_unquote(json_extract(`config`, '$."purge"."age"')) > 0 and `files_purged` = false order by `eod_date` ASC
```

Reformated query:
```sql
SELECT *
FROM `deliveries`
WHERE `status` = "done" AND JSON_UNQUOTE(JSON_EXTRACT(`config`, '$." PURGE"."enabled"')) = "true" AND JSON_UNQUOTE(JSON_EXTRACT(`config`, '$." PURGE"."age"')) > 0 AND `files_purged` = FALSE
ORDER BY `eod_date` ASC
```

The syntax inside `json_extract()` is transformed:
* added space character,
* changed case.

So, the new query is different and returns a different result!

The auto-reformat should not change syntax inside function.

Environment:
* OS: Windows 10 Pro
* HeidiSQL version: 12.1.0.6537 (64-bit)
* Database type and version: Mysql 5.7.33

Best regards.

**Comment by ansgarbecker** [comment]
Should be fixed in the new online formatter (see https://github.com/HeidiSQL/HeidiSQL/issues/750#issuecomment-1732621991 for details):

```sql
SELECT
   f.id
FROM
   f
WHERE
   f.val LIKE '%"test/default%'
ORDER BY
   f.id
```
