### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by marvel-magellan** [HeidiSQL/HeidiSQL#1263]
I would like to see two enhancements:

1. Sometimes, I run a query script that outputs many tables (> 20). Instead of pressing those little left and right arrow buttons to find the table that I'm looking for, I would like to suggest a shortcut: Right click on the tab headers, and a pop up appears with all the table names in sorted order, and I can click on one of them to immediately scroll to that table and it will appear. 

2. Add a keyboard shortcut for commenting/uncommenting lines in the query script.

3. Allow a way to name the query (instead of using the default table name) so that appears on the tab. Sometimes, I have two or more queries on the same table, and it will thus display the same table name on the tabs.

I'm willing to donate to have these features added.

**Comment by ansgarbecker** [comment]
This is not the way issues must be reported. Instead, please click the "New issue" button, select an issue template and describe _one_ bug or feature request. Prior to that, look into the issues, whether it was already reported.

Notes related to your questions:
* There is a "Un/comment" context menu item in the query area. In the preferences dialog, you can assign a shortcut to it.
* Related to your 3rd question: https://www.heidisql.com/forum.php?t=10493
