### ISSUE TITLE
Add Cardinality with index option page

### ISSUE THREAD

**Issue by liuanxin** [HeidiSQL/HeidiSQL#1264]
Is it possible to display cardinality in the index options page?
![image](https://user-images.githubusercontent.com/2647495/102679307-d31cd680-41e9-11eb-9e8b-a9dc17826d54.png)

Its corresponding sql is `show index from table_name`, just like
![image](https://user-images.githubusercontent.com/2647495/102679254-4114ce00-41e9-11eb-8b10-dd0fcbc14607.png)

then I can understand which indexes are rarely used in index management

**Comment by ansgarbecker** [comment]
The index list is not meant for analyzing, just for creating indexes.

Please use the forum for questions. And use a template when reporting an issue.
