### ISSUE TITLE
Random Guid Value Insert Option in Lower Case

### ISSUE THREAD

**Issue by ab-tools** [HeidiSQL/HeidiSQL#1268]
There is an option already to insert a random guid (with or without brackets) into a database tablet field (via "Insert special value" context menu), but unfortunately till now only in upper case.

As all guids in my database are lower case, I would like to have an option to insert a random one (without brackets in my case) in lower case instead.

Thanks for considering!
Andreas

**Comment by ansgarbecker** [comment]
Done:
![grafik](https://user-images.githubusercontent.com/7986591/104034820-ac8f0180-51d1-11eb-9c23-beb1f2d01c4a.png)

Next time please use the issue template when reporting.

**Comment by ab-tools** [comment]
Thanks, Ansgar, appreciated! :-)
