### ISSUE TITLE
Memory problem with large SQL files

### ISSUE THREAD

**Issue by RobertsMrtn** [HeidiSQL/HeidiSQL#1269]
**Describe the bug**
If tring to run very large SQL files the system goes out of memory. The problem is that the same large SQL file is loaded on startup causing the system to take a very long time to start followed by an out of memory error. The same problem occurs after uninstalling and re-installing.

**To Reproduce**
Try to run a very large SQL file

**Comment by WesleyM77** [comment]
What kind of operations is the file doing? I've had no issues with loading databases from 5+ GB files.

**Comment by ansgarbecker** [comment]
@RobertsMrtn are you sure this was meant to be a report for HeidiSQL?
If yes, please refine your report, be sure you are using the latest version, and be more precise in your description.
I will close this now, but feel free to report back.

**Comment by RobertsMrtn** [comment]
Yes, I know what sotware I am running. HeidiSQL version 11.1.0.6116. I was able to resolve the problem by locating the large backup file and deleting it. The system was taking several minutes to load followed by an 'out of memory' error. I am using Windows 10 with 6GM RAM.

**Comment by RobertsMrtn** [comment]
The backup file size was 313512KB. Can you check the file size before automatic loading on startup?

**Comment by ansgarbecker** [comment]
Could you please describe how you started HeidiSQL then? "loading on startup" means at least two possibilities, both of them are quite unusual with a large file.
