### ISSUE TITLE
It fails to display the default and the comment of some special fields in table definition viewer

### ISSUE THREAD

**Issue by owen1759** [HeidiSQL/HeidiSQL#127]
## Expected behavior

I wish it displays as what it is to be.

## Current behavior

The default and the comment of fields of type DATETIME or INT with default value will disappear in table definition viewer, it just show me the blank.
And the "Create Code" is not correct too.

## Failure information (for bugs)

N/A

### Steps to reproduce

Now, you can create a table in MariaDB like this:
```
CREATE TABLE IF NOT EXISTS `TABLE1` (
  `ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
  `THE_TIME` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'TIME',
  `THE_INTEGER` INT NOT NULL DEFAULT 0 COMMENT 'INTEGER'
);
SHOW CREATE TABLE `TABLE1`;
```

And then, open this table definition in HeidiSQL, you can see this two fields with blank default and blank comment.

And even worse, the 'Create Code' show me the code as below:
```
CREATE TABLE `table1` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
	`THE_TIME` DATETIME NULL DEFAULT '',
	`THE_INTEGER` INT(11) NOT NULL DEFAULT '',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
```
Why it is not the same with the result of `SHOW CREATE TABLE TABLE1;`

P.S.:It also happens when I use HeidiSQL itself to create table or modify field definition.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version:9.4.0.5125
* Database system + version:Server version: 10.2.12-MariaDB
* Operating system:Windows 7 Professional Service Pak 1

### Failure Logs

N/A

**Comment by ansgarbecker** [comment]
Could you please update to the current nightly build of HeidiSQL, and report back if the problem persists. v9.4 is outdated.

**Comment by rentalhost** [comment]
**Could not reproduces with 9.5.5245 (current) or 9.4.5125 (from author).**

@owen1759 Could you test it again with the most recent nightly version? If you get on this issue again I will install the same MariaDB as you (mine is 10.1.14), although I think that it is not the cause.

**Comment by owen1759** [comment]
It works! Thanks a lot, you are really a great help.
refer: [](https://github.com/HeidiSQL/HeidiSQL/issues/68
)
