### ISSUE TITLE
Add a quick filter for related rows

### ISSUE THREAD

**Issue by vakata** [HeidiSQL/HeidiSQL#1278]
**Is your feature request related to a problem? Please describe.**
I would like to be able to quickly view related rows in other tables in their entirety.

**Describe the solution you'd like**
A datagrid contextmenu item (with a hotkey) that lets me select a cell and if it is a column with a foreign key - follow the foreign key by opening a new query tab with the foreign table data filtered accordingly. 

**Example**
Imagine browsing a `news` table which has an `author` column, which is a foreign key to an `authors` table. When a row in the `news` datagrid has a value of `1` in the `author` column I would like to be able to press a key and open a new query tab which will `SELECT * FROM authors WHERE author = 1`

**Comment by vakata** [comment]
@WesleyM77 you are right - sorry, I did not find the original issue. I would much prefer this to be a filter, not a table list with the row selected, but still it is close enough.
Closing as duplicate of #156

**Comment by WesleyM77** [comment]
No worries. I can understand both views. You should add a comment on there to add to the conversation.
