### ISSUE TITLE
Opening Heidi after closing starts super minimized with all query tabs from previously opened instances

### ISSUE THREAD

**Issue by datacubed** [HeidiSQL/HeidiSQL#1279]
**Describe the bug**
If I have multiple instances up of Heidi (connected to different servers) - with many tabs of queries etc.. after a reboot or closing them down, the next time I open heidi and log into 1 of those sessions, all query tabs are loaded into that - where as historically they would be loaded per session.
I don't know if this is the cause, but I've noticed more and more when heidi loads (maybe after a win update reboot) it starts minimized to the point only the windows tool bar 3 buttons are visible, and I have to drag n resize it. It seems to happen when it loads a lot of query tabs.

**To Reproduce**
1. Start different heidi sessions in different servers.
2. Run different queries in different tabs.
3. Close/restart machine forcing a close
4. Open 1 heidi instance and reconnect a session.
5. Witness all tabs from other sessions appearing in this 1 place.

**Expected behavior**
Only the query tabs relative to that session reopening.

**Screenshots**
![heidibug2](https://user-images.githubusercontent.com/34278418/104708378-890a1080-5715-11eb-91be-b283d66ee105.png)

![heidibug](https://user-images.githubusercontent.com/34278418/104707500-60354b80-5714-11eb-8507-47493911c20e.JPG)

**Environment:**
 - OS: Windows 10
 - HeidiSQL version: 11.1.0.6116
 - Database type and version: MySQL

**Comment by datacubed** [comment]
Hey guys, the issue of heidi starting shrunk has gone.

But the openign of a conneciton with ALL tabs from all connections is still happening.

**Comment by ansgarbecker** [comment]
Query tabs were never bound to a particular session in HeidiSQL. Please note you can open multiple sessions in one window. Tabs are shared over all opened sessions. Maybe they could partly not be loaded when accessing them from different windows, but the idea behind tabs was to have them all open, not to bind them to a session.

**Comment by datacubed** [comment]
Ah cheers for the info !

Weird though.. over the many, many, years I'd swear I've never noticed this before. I've had many instances open on differeent connections at a time, close and open - and i'd get the specific connections' tabs back.

If it's not coded to do so then I dont know what to say lol, very strange :S

I feel like binding the tabs to a session/connection profile makes sense though.. if possible?

**Comment by datacubed** [comment]
Also big fan of your product. Been using happily for years : )

**Comment by ansgarbecker** [comment]
Thanks for your appreciation!

I think issue #933 is similar to your expectation, so I'll close this one as a duplicate.
Long discussion there, and I still disagree with the idea of binding query tabs to a session.
