### ISSUE TITLE
HeidiSQL 11.1.0.6116 crashes on startup

### ISSUE THREAD

**Issue by gabahey** [HeidiSQL/HeidiSQL#1286]
Faulting application name: heidisql.exe, version: 11.1.0.6116, time stamp: 0x5fa04291
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000041d
Fault offset: 0x0000000011146190
Faulting process id: 0x4c74
Faulting application start time: 0x01d6ef5d3fe44812
Faulting application path: C:\Program Files\HeidiSQL\heidisql.exe
Faulting module path: unknown
Report Id: 51fc3a19-e425-4fc4-9482-4f0f554c5388
Faulting package full name: 
Faulting package-relative application ID:

**Comment by ansgarbecker** [comment]
Please do not remove the whole issue template. And if you have a crash report like in your case, do not remove the callstack from it. I cannot do anything with these details.
