### ISSUE TITLE
Blank SSH user and/or password need a prompt when connecting, not a message dialog

### ISSUE THREAD

**Issue by b-fett** [HeidiSQL/HeidiSQL#129]
## Expected behavior

Connection to be established successfully.

## Current behavior

Raising error window "Can't connect to MySQL server on 'localhost' (10061)"

### Steps to reproduce

1. Create new connection with next settings:
- Network type: MySQL (SSH tunnel)
- Hostname / IP: localhost
- Prompt for credentials: _checked_

- SSH host + prot: _my_host_IP_
- Username: _blank_
- Password: _blank_

2. Open created connection
3. Type mysql credentials in according fields, hit Login
4. Type SSH user name while focus on authentification dialog
![image](https://user-images.githubusercontent.com/33630339/36093665-f903999a-0ff3-11e8-99c7-a57f14f502d9.png)
and hit OK
5. Error window appears here.

### Context

* HeidiSQL version: 9.5.0.5245
* Database system + version: Ubuntu 16.04.3 LTS, 10.2.12-MariaDB
* Operating system: Windows 7 (6.1.7601)

### Failure Logs
```
Connecting to localhost via MariaDB (SSH tunnel), username root, using password: Yes ...
Attempt to create plink.exe process, waiting 4s for response ...
plink.exe -ssh my_host_IP -N -L 3307:localhost:3306
Can't connect to MySQL server on 'localhost' (10061)
Closing plink.exe process #2932 ...
```

**Comment by b-fett** [comment]
plink version is 0.68

**Comment by ansgarbecker** [comment]
Blank SSH user + passwords are currently not supported by HeidiSQL, as this requires a prompting approach in the upcoming dialog.
