### ISSUE TITLE
Cannot delete row in MSSQL

### ISSUE THREAD

**Issue by endo64** [HeidiSQL/HeidiSQL#1294]
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: MSSQL 2017
* OS: Win10 x64

**Describe the bug**

`DELETE` doesn't work and produces the below output & error:

```
DELETE ;
/* SQL Error (102): Incorrect syntax near 'DELETE'. */
```

**To Reproduce**

Place a row, press CTRL-DELETE to delete the row, see the error.

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/840604/105893728-7ef4e580-6024-11eb-8a97-2fb3da14f133.png)

**Comment by ansgarbecker** [comment]
Embarrassing bug, broken while I fixed #343. Should be fixed in the next build.
