### ISSUE TITLE
vcruntime140.dll missing

### ISSUE THREAD

**Issue by sh-q** [HeidiSQL/HeidiSQL#1296]
**Preconditions**
* HeidiSQL version: 11.2.0.6213
* Database type and version: MariaDB 10.5.8
* OS: Windows Server 2019 Essentials 1809 64-bit

**Describe the bug**
I successfully installed HeidiSQL using HeidiSQL_11.2.0.6213_Setup.exe which installed it 64-bit.
When trying to open a session to MariaDB using libmariadb.dll HeidiSQL issues an error window which complains that it cannot load libmaria.dll. Using a dependency viewer it turned out that libmariadb.dll requires to load vcruntime140.dll which is not present on the target system. After installing the vc_redist package from Microsoft HeidiSQL works fine.

Therefore the installation package should include the vc_redist package.

Note that the HeidiSQL 11.0 32-bit which came with MariaDB 10.5.8 did not have the issue.

**To Reproduce**
1. Go to the session manager and define a connection to an instance of MariaDB using libmariadb.dll.
2. Click on 'Open'
3. See error message: cannot load libmariadb.dll

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Heard that various times now. I should perhaps include that runtime in the installer.

**Comment by ansgarbecker** [comment]
Should be working with the next installers.
