### ISSUE TITLE
Show check constraints on MySQL, MSSQL and PostgreSQL

### ISSUE THREAD

**Issue by Dragonrun1** [HeidiSQL/HeidiSQL#1298]
* HeidiSQL version: 11.2.0.6213
* Database type and version: MYSQL 8.0.22
* OS: WINDOWS 10

** Bug**
Table check constraint tab doesn't show any constraints for tables that have them.

**To Reproduce**
```
CREATE TABLE addresses
(
    id                      CHAR(22)    NOT NULL,                  
    post_office_box  VARCHAR(50)  DEFAULT NULL,
    street                VARCHAR(255) DEFAULT NULL,
    CONSTRAINT chk_addresses_pob_street
        CHECK ((post_office_box IS NULL) <> (street IS NULL)),
    PRIMARY KEY (id)
) DEFAULT CHARACTER SET utf8mb4
  ENGINE = InnoDB;
```
check constraint tab does not show constraint.
Also the CREATE code tab is missing the constraint as well.

When trying to add new check in tab the DB reports duplicate constraint as expect which is shown in screenshot alter line.

**Screenshots or Crash reports**
![heidiSQL_check_constraint](https://user-images.githubusercontent.com/1431541/106365076-f312e000-62e7-11eb-998e-d517f3c63f9c.PNG)

**Comment by ansgarbecker** [comment]
Yes, this is expected. Only MariaDB constraints are yet supported. MySQL (and MSSQL) work differently, and there is no idea yet how to rertrieve them in a stable way, and efficient enough. See the missing `TABLE_NAME` column in IS.`CHECK_CONSTRAINTS`.

**Comment by Dragonrun1** [comment]
MySql has information_schema.{check_constraints, table_constraints} as per the standard so should be the same as  PostgreSql. MSSQL also has the same tables so might not even need to do anything different there as well. Everyone seems to forget  information_schema is your friend when dealing with cross platform stuff. Normally only Oracle messes that up now days ;)

Just to let you know the constraints are showing in the information_schema tables as expected as that the other way I was confirming they were created correctly.

![heidiSQL_check_constraint_info_schema](https://user-images.githubusercontent.com/1431541/106974903-5fd41300-670a-11eb-8397-dc8011b92588.PNG)

**Comment by ansgarbecker** [comment]
Yes, I already tried to query `IS.TABLE_CONSTRAINTS`, joining `IS.CHECK_CONSTRAINTS`. And that query is way to slow on a larger database, takes about 30 seconds on a just started server, 5 seconds after warming up:
```sql
SELECT *
FROM information_schema.TABLE_CONSTRAINTS tc, information_schema.CHECK_CONSTRAINTS cc
WHERE
	tc.CONSTRAINT_SCHEMA='mydb'
	AND tc.TABLE_NAME='mytable'
	AND tc.CONSTRAINT_TYPE='CHECK'
	AND tc.CONSTRAINT_SCHEMA=cc.CONSTRAINT_SCHEMA
	AND tc.CONSTRAINT_NAME=cc.CONSTRAINT_NAME
	AND tc.TABLE_NAME=cc.TABLE_NAME
```

Could you please fire the same query, so we can optimize the approach.

**Comment by Dragonrun1** [comment]
```
SELECT *
FROM information_schema.TABLE_CONSTRAINTS tc, information_schema.CHECK_CONSTRAINTS cc
WHERE
	tc.CONSTRAINT_SCHEMA='slc'
	AND tc.TABLE_NAME='addresses'
	AND tc.CONSTRAINT_TYPE='CHECK'
	AND tc.CONSTRAINT_SCHEMA=cc.CONSTRAINT_SCHEMA
	AND tc.CONSTRAINT_NAME=cc.CONSTRAINT_NAME
```

Had to drop the last `AND` from SQL as cc.TABLE_NAME does not exist.
Result (warm):
`/* Affected rows: 0  Found rows: 3  Warnings: 0  Duration for 1 query: 0.015 sec. */`
After dropping and re-creating tables etc, restarting MySQL service, and HS time was the same.

**Comment by ansgarbecker** [comment]
Due to the non existent cc.TABLE_NAME in MySQL, that query returns rows in `cc` from other tables as well, as long as they have the same `CONSTRAINT_NAME`.
Try yourself, after adding constraints with the same name in two tables:
```sql
CREATE TABLE test1 (col1 int);
CREATE TABLE test2 (col1 int);
ALTER TABLE `test1` ADD CONSTRAINT `constr_a` CHECK (2>1);
ALTER TABLE `test2` ADD CONSTRAINT `constr_a` CHECK (3>1);
SELECT *
FROM information_schema.TABLE_CONSTRAINTS tc, information_schema.CHECK_CONSTRAINTS cc
WHERE
	tc.CONSTRAINT_SCHEMA='test'
	AND tc.TABLE_NAME='test1'
	AND tc.CONSTRAINT_TYPE='CHECK'
	AND tc.CONSTRAINT_SCHEMA=cc.CONSTRAINT_SCHEMA
	AND tc.CONSTRAINT_NAME=cc.CONSTRAINT_NAME;
-- result shows two constraints instead of one
```

**Comment by ansgarbecker** [comment]
According to [this tutorial](https://www.mssqltips.com/sqlservertutorial/180/informationschemacheckconstraints/), one can query `IS.CONSTRAINT_TABLE_USAGE` to get the table for a specific constraint. But that table/view is not available on MySQL nor MariaDB, even not on my MSSQL Express 2017 server.

**Comment by Dragonrun1** [comment]
Constraint names have the same uniqueness requirement as table names so within a single schema they can not have duplicate names.
From Postgresql docs on CONSTRAINT_TABLE_USAGE:
https://www.postgresql.org/docs/current/infoschema-constraint-table-usage.html
In the last sentence it states 'Check constraints and not-null constraints are not included in this view.'

If MS does include them it probably is a non-standard extension of the existing standards which makes them non-compliant in this area.

Here is what I've been using during my testing on this issue so we can make sure we have a common base to work with.

I've created the same database in both MySQL and Postgresql and used the following SQL to create my test tables:
```
--
-- users
--
-- Must by created before other tables that use create_by or updated_by fk.
--
CREATE TABLE users
(
    -- Primary key
    id         CHAR(22)     NOT NULL,
    sign_in    VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    -- Timestamp adding entry.
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Timestamp updating entry.
    updated_at TIMESTAMP             DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX unq_users_sign_in ON users (sign_in);
--
-- addresses
--
CREATE TABLE addresses
(
    -- Primary key
    id               CHAR(22)    NOT NULL,
    -- Country name or abbreviation.
    country          VARCHAR(50)          DEFAULT NULL,
    -- Apartment/suite/room name/number if any.
    extended_address VARCHAR(50)          DEFAULT NULL,
    -- City/town/village.
    locality         VARCHAR(50) NOT NULL,
    -- Post office box description if any.
    post_office_box  VARCHAR(50)          DEFAULT NULL,
    -- Postal code, e.g. US ZIP code.
    postal_code      VARCHAR(30)          DEFAULT NULL,
    -- State/county/province if any.
    region           VARCHAR(50) NOT NULL,
    -- Street number + name.
    street           VARCHAR(255)         DEFAULT NULL,
    -- Timestamp adding entry.
    created_at       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Track who created if known.
    created_by       CHAR(22)             DEFAULT NULL,
    -- Timestamp updating entry.
    updated_at       TIMESTAMP            DEFAULT NULL,
    -- Track who updated.
    updated_by       CHAR(22)             DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX idx_addresses_postal_code ON addresses (postal_code);
CREATE INDEX idx_addresses_region_locality ON addresses (region, locality);
CREATE INDEX idx_addresses_created_by ON addresses (created_by);
CREATE INDEX idx_addresses_updated_by ON addresses (updated_by);
ALTER TABLE addresses
   ADD CONSTRAINT fk_addresses_created_by
        FOREIGN KEY (created_by) REFERENCES users (id)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT;
ALTER TABLE addresses
   ADD CONSTRAINT fk_addresses_updated_by
        FOREIGN KEY (updated_by) REFERENCES users (id)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT;
ALTER TABLE addresses
   ADD CONSTRAINT chk_addresses_pob_street
        CHECK ((post_office_box IS NULL) <> (street IS NULL));
ALTER TABLE addresses
   ADD CONSTRAINT chk_addresses_pob_postal_code
        CHECK ((post_office_box IS NULL) OR
               ((post_office_box IS NOT NULL) AND (postal_code IS NOT NULL)));
ALTER TABLE addresses
   ADD CONSTRAINT chk_addresses_street_extended_address
        CHECK ((street IS NOT NULL) OR
               ((street IS NULL) AND (extended_address IS NULL)));
```

I then used the same query on both with the single change of `constraint_schema`  as in MySQL schema = database vs Postgresql where they are not and it by default puts all tables in schema = 'public'.
MySQL query:
```
SELECT tc.constraint_schema, tc.constraint_name, tc.table_name, tc.constraint_type, tc.enforced, cc.check_clause
FROM information_schema.TABLE_CONSTRAINTS tc
   LEFT JOIN information_schema.CHECK_CONSTRAINTS cc
   ON tc.CONSTRAINT_SCHEMA=cc.CONSTRAINT_SCHEMA
   AND tc.CONSTRAINT_NAME=cc.CONSTRAINT_NAME
WHERE
	tc.CONSTRAINT_SCHEMA='slc'
	AND tc.TABLE_NAME='addresses'
	AND tc.CONSTRAINT_TYPE='CHECK'
```

PostgreSQL query:
```
SELECT tc.constraint_schema, tc.constraint_name, tc.table_name, tc.constraint_type, tc.enforced, cc.check_clause
FROM information_schema.TABLE_CONSTRAINTS tc
   LEFT JOIN information_schema.CHECK_CONSTRAINTS cc
   ON tc.CONSTRAINT_SCHEMA=cc.CONSTRAINT_SCHEMA
   AND tc.CONSTRAINT_NAME=cc.CONSTRAINT_NAME
WHERE
	tc.CONSTRAINT_SCHEMA='public'
	AND tc.TABLE_NAME='addresses'
	AND tc.CONSTRAINT_TYPE='CHECK'
```

MySQL result:
| CONSTRAINT_SCHEMA | CONSTRAINT_NAME | TABLE_NAME | CONSTRAINT_TYPE | ENFORCED | CHECK_CLAUSE | 
| --- | --- | --- | --- | --- | --- | 
| slc | chk_addresses_pob_postal_code | addresses | CHECK | YES | ((`post_office_box` is null) or ((`post_office_box` is not null) and (`postal_code` is not null))) | 
| slc | chk_addresses_pob_street | addresses | CHECK | YES | ((`post_office_box` is null) <> (`street` is null)) | 
| slc | chk_addresses_street_extended_address | addresses | CHECK | YES | ((`street` is not null) or ((`street` is null) and (`extended_address` is null))) | 

PostgreSQL result:
| constraint_schema | constraint_name | table_name | constraint_type | enforced | check_clause | 
| --- | --- | --- | --- | --- | --- | 
| public | chk_addresses_pob_street | addresses | CHECK | YES | (((post_office_box IS NULL) <> (street IS NULL))) | 
| public | chk_addresses_pob_postal_code | addresses | CHECK | YES | (((post_office_box IS NULL) OR ((post_office_box IS NOT NULL) AND (postal_code IS NOT NULL)))) | 
| public | chk_addresses_street_extended_address | addresses | CHECK | YES | (((street IS NOT NULL) OR ((street IS NULL) AND (extended_address IS NULL)))) | 
| public | 2200_18023_1_not_null | addresses | CHECK | YES | id IS NOT NULL | 
| public | 2200_18023_4_not_null | addresses | CHECK | YES | locality IS NOT NULL | 
| public | 2200_18023_7_not_null | addresses | CHECK | YES | region IS NOT NULL | 
| public | 2200_18023_9_not_null | addresses | CHECK | YES | created_at IS NOT NULL | 

PostgreSQL result ends up having the extra internal generated NOT NULL constraints which MySQL doesn't add to this view which falls under an implementation detail beyond any standard. Other than that minor detail both show the result I would expect.

**Comment by ansgarbecker** [comment]
Sorry, I just tested in MariaDB, and I just realize it's the only system where I can create non-unique constraint names. Doing the same in MySQL 8.0.19 results in the expected error:

    SQL Error (3822): Duplicate check constraint name 'constr_a'.

I think in that case it's just MariaDB requiring the current query type, while all others should work with the above one.

**Comment by ansgarbecker** [comment]
I think that's it now.
Please retry with the next build, available in half an hour.

**Comment by Dragonrun1** [comment]
Heading to bed right now but I can see the check constraints now in both MySQL and PostgreSQL with the update. I'll look around at it some more when I'm less blurry eyed to see if anything still needs tweeked but thank you for the afford to make it work.

**Comment by Dragonrun1** [comment]
Good Morning ;) Looks good thanks again for getting this working correctly.

An enhancement would be to include the `enforced` column. It is a non-standard extension that both MySQL and PostgreSQL seem to have which can be very useful during testing etc. MSSQL seems to have a `NO CHECK` that might serve a similar function but not sure if if it has a column for it you can access or if it really has a close enough semantics to offer it in place.

PostgreSQL also has some stuff around deferred vs not etc which seem to also be non-standard extensions that someone might like to have access to.

As far as I'm concerned the issue can be closed but thought I'd leave it open for now just in case someone else finds some edge cases.
