### ISSUE TITLE
osx support

### ISSUE THREAD

**Issue by thecotne** [HeidiSQL/HeidiSQL#13]
RAD Studio supports osx so in theory if we migrate this project to latest version of RAD studio then we can have osx support 

i have tried to build HeidiSQL with RAD studio 10.2 but it does not work ...

**Comment by ansgarbecker** [comment]
Delphi XE5 is the only supported package yet, as stated in the readme. Also, compiling for OSX can only be done with FireMonkey code, or?

**Comment by thecotne** [comment]
i was looking at this https://www.embarcadero.com/products/rad-studio/features/mac-os

so yes it's about  FireMonkey

is it possible to first migrate to latest RAD studio and then try to migrate it to FireMonkey?

i was searching about this and there are some projects like `Mida Converter` that aim to convert windows only Delphi code to FireMonkey

**Comment by ansgarbecker** [comment]
Feel free to check that, make a fork of the current sources here and apply that converter on your sources. The make a pull request here.

**Comment by phoenixg** [comment]
HeidiSQL is so cool except it does not support Mac

**Comment by ansgarbecker** [comment]
HeidiSQL runs on Wine, and MacOS has Wine, doesn't it?

**Comment by thecotne** [comment]
@ansgarbecker wine is not solution to problem it's more like a workaround

and to answer question: yes there is wine builds for mac and it does work pretty well no major issues

in minnor issues you need to use windows/linux style keyboard shortcuts to copy/paste

**Comment by phoenixg** [comment]
@ansgarbecker I know wine, but it is not very "smooth" in usage. ( I think you know what I mean)

**Comment by ansgarbecker** [comment]
macOS release is on the download page, since v12.15
