### ISSUE TITLE
HeidiSQL main site down, no binaries on GitHub releases as redundancy

### ISSUE THREAD

**Issue by kyleboddy** [HeidiSQL/HeidiSQL#130]
## Expected behavior

To be able to access www.heidisql.com

## Current behavior

Website is offline

## Failure information (for bugs)

ERR_CONNECTION_TIMED_OUT

### Steps to reproduce

Go to the website,

### Context

The github releases page does not have binaries and there are no easily-found mirrors of the Windows binaries. When the main site is down, it is very difficult to find precompiled binaries. Strongly recommend that releases are made available on Github as well as the main site.

**Comment by ansgarbecker** [comment]
Neither me nor the monitoring took a notice about that off-time, but who knows...

**Comment by ansgarbecker** [comment]
Oh, Pingdom _did_ notice that - I just found their mails in my spam folder.
The exact time was today 18:40 to 18:55

**Comment by kyleboddy** [comment]
So monitoring might need to be improved :) 

Still, perhaps redundant binaries provided in Github could be a thing in case of failure otherwise. Just a thought.

**Comment by rentalhost** [comment]
@kyleboddy It seems to be a regional failure (you can fix that by setup more DNS servers). 

@ansgarbecker But I think that the Github mirroring should be useful anyway.
