### ISSUE TITLE
Classify objects in database tree by type

### ISSUE THREAD

**Issue by rabrego** [HeidiSQL/HeidiSQL#1301]
**Is your feature request related to a problem? Please describe.**
Not really, but would be easier to find something

**Describe the solution you'd like**
Put every type of object in separate folders (tables, procedures, triggers, functions, views)

**Describe alternatives you've considered**
Currently I am using prefix letter for each type of object (t_ for table, p_ or procedure, f_ for functions)

**Additional context**
![Sin título-1](https://user-images.githubusercontent.com/22224945/106756026-cec34600-65fc-11eb-9c35-752ab21e0db0.png)

**Comment by ansgarbecker** [comment]
This is already implemented. See the context menu in the tree, then click "Tree style options", then "Group objects by type".
