### ISSUE TITLE
MariaDB 10.5:  REPLICATION CLIENT privilege was renamed to BINLOG MONITOR

### ISSUE THREAD

**Issue by tobias-gruenewald** [HeidiSQL/HeidiSQL#1302]
**Preconditions**
* HeidiSQL version: 11.2.0.6213
* Database type and version: 10.5.x
* OS: Windows

**Describe the bug**
MariaDB renamed the REPLICATION CLIENT privilege to BINLOG MONITOR. The old syntax is understood for compatibility.
The HeidiSQL user management interface dows not recognize the "BINLOG MONITOR" when issuing "SHOW GRANTS" and thus does not show the privilege.
It can be set by HeidiSQL as the server still accepts "GRANT REPLICATION CLIENT", but will not be listed.

**To Reproduce**
1. Connect to MariaDB 10.5 server
2. Go to 'role/permission management'
3. select a user account that does have the "BINLOG MONITOR" GRANT (but not via GRANT ALL)
4. observe that the "REPLICATION CLIENT" GRANT is not shown as checked in the UI
5. check "REPLICATION CLIENT" and save
6. return to the same view and observe it is again unchecked

**Screenshots or Crash reports**

https://mariadb.com/kb/en/changes-improvements-in-mariadb-105/

**Comment by ansgarbecker** [comment]
Should be easy to fix.

**Comment by tobias-gruenewald** [comment]
> 
> 
> Should be easy to fix.

yeah, probably. I would create a pull request, but I have no clue how Pascal works unfortunately :)

Thanks for your great work!

**Comment by ansgarbecker** [comment]
Please try the next build.

I also added 7 new privileges, introduced in the same MariaDB version (10.5.2).
I suppose Heidi already misses some privileges from earlier updates.

**Comment by tobias-gruenewald** [comment]
installed build 6221, user management now correctly displays the new roles when connected to a MariaDB 10.5 server.
