### ISSUE TITLE
Left Pane Interferes With Off-Pane Mouse Dragging

### ISSUE THREAD

**Issue by bhsmither** [HeidiSQL/HeidiSQL#1303]
This effect exists with 11.2.0.6220

**Preconditions**

* HeidiSQL version: 11.2.0.6220 (and 11.1.0.6116) only versions tried
* Database type and version: N/A
* OS: Win7 64-bit
* Display: Pair of 4K DisplayPort monitors extended desktop

**Describe the bug**

Have some icons along the very left edge of the left monitor. Open HeidiSQL so that the left edge of its window is about in the middle of the first (left-hand) monitor. The right edge can be anywhere. Whether a second monitor to the right makes a difference, I do not know.

Use the mouse to click on an icon and drag the icon slowly towards the left edge of the HeidiSQL window. At about five icon-column-widths away from the edge, the dragged icon will change appearance (red slash-circle-stop) and a highlight bar will activate in the left pane - as if the icon was about to be dropped onto an item or between two items in the list.

**To Reproduce**

**Screenshots or Crash reports**

**Comment by bhsmither** [comment]
This isn't accepting my screenshot.

**Comment by ansgarbecker** [comment]
Yes I can reproduce that:
![grafik](https://user-images.githubusercontent.com/7986591/106851694-0262a680-66b7-11eb-9988-61634b5f30a9.png)

I suppose this is what you mean?

What exactly is buggy here?

**Comment by bhsmither** [comment]
Not at all. The 'effect' I describe happens when the mouse cursor that is dragging the icon **is still quite a ways to the left of the left edge** of the HeidiSQL window.

In your image above, the mouse cursor has entered into the left pane region. And, I do not recognize the window border styling of your HeidiSQL window. And, is 'readme.md' an icon on the Win7 desktop?

**Comment by ansgarbecker** [comment]
No, that readme.md is a filename shown by an explorer window. You did not mention the desktop, so I thought you meant "from anywhere".
I retried with a desktop icon, then also from one screen to my second one, but the mouse cursor never shows that "drop" effect before it's on the HeidiSQL window. Perhaps the effect does not happen on my Win10 here. I have no Win7 any longer reachable on any system here.
You should run a test on Win 10 as well.
Probably relevant: high-dpi setting - as you mention 4k. Did you perhaps tell HeidiSQL to override your system settings here? And are your both monitors set to the same dpi setting?

**Comment by bhsmither** [comment]
Not sure how to instruct HeidiSQL to override any system settings. Both monitors are identical (model, resolution, background, everything - except the task bar is on the left monitor).
(I wish I could attach an image. Try: https://i.postimg.cc/pXTrBNv3/capture-001.gif)
(Win10 is a non-starter.)

**Comment by ansgarbecker** [comment]
Win7 is not supported by MS any longer. And I do not have Win7 test machine any longer here, so there's no way for me to find a solution. Please shout if there's a reproduction recipe on Win10.

**Comment by bhsmither** [comment]
Reading through past issues regarding high-dpi and the spotty support provided by Delphi as reported in those issues, that is where I will place the blame, and just live with it.
