### ISSUE TITLE
可以加上不同数据库之间数据迁移吗

### ISSUE THREAD

**Issue by fuhx** [HeidiSQL/HeidiSQL#1305]
如题，
假设数据库A为mysql，数据库B为sql server，同时连两个数据库，把A库中数据迁移到B库。
或者，从在两个不同版本的数据库进行数据迁移。

**Comment by WesleyM77** [comment]
**Translated Title**: Can you add data migration between different databases?
**Translated Content**: As the title, Assuming that database A is mysql and database B is sql server, two databases are connected at the same time, and the data in database A is migrated to database B. Or, migrate data from two different versions of the database.

**Comment by xiaozhubenben** [comment]
What you need is ETL tools, like Kettle

**Comment by ansgarbecker** [comment]
Exporting to Excel is already doable. Importing as well - through the CSV import dialog.

There is also the SQL export with support for exporting to other databases and servers.
