### ISSUE TITLE
No mapping for the unicode character exists in the target multi-byte code page

### ISSUE THREAD

**Issue by acqsk** [HeidiSQL/HeidiSQL#1307]
**Preconditions**
* HeidiSQL version: 10.2.0.5599 32bit
* Database type and version: GoogleCloud MySQL8, or localhost Windows10 MySQL8 and also tested on 5.6 and same problem
* OS: Ubuntu/Windows10

**Describe the bug**
560MB sql file - UTF8 => error after few minutes of import

**To Reproduce**
...run SQL file

**Screenshots or Crash reports**
![image](https://user-images.githubusercontent.com/53380201/107206080-e33d7f00-69fe-11eb-9a3f-4156fc4c547e.png)

![image](https://user-images.githubusercontent.com/53380201/107206266-17b13b00-69ff-11eb-9840-80de318d6575.png)

**Comment by acqsk** [comment]
...and same issue in latest version 11.2.0.6213

**Comment by ansgarbecker** [comment]
This is a duplicate to #1048 

Also, that's most likely caused by the file itself, or by the way HeidiSQL reads the file. Or due to a wrong encoding selected when you open that file. However, please comment in the above issue if you have an example file to play with.

**Comment by StanislavHrouzek** [comment]
Still the same problem in HeidiSQL. Console line is solution...
