### ISSUE TITLE
GUI Freeze Issue

### ISSUE THREAD

**Issue by maazu** [HeidiSQL/HeidiSQL#1308]
The GUI freezes while loading a big SQL file.

**Comment by ansgarbecker** [comment]
Please do not remove the issue template. Fill out all fields and provide examples.
Further on there is no exact definition of a "big file". You will need to be more exact.

**Comment by maazu** [comment]
When attempting to import a large file, in my case which 375MB, the GUI freezes and it becomes not un responsive.
 
![freez issue](https://user-images.githubusercontent.com/35654937/107531617-d8414500-6bde-11eb-9714-9e40530d9348.PNG)

**Comment by ansgarbecker** [comment]
Ok, your screenshot tells me your script creates or modifies 4 million rows up to that point. It's very normal that this takes a while. Just wait for it to finish.
I also guess that script holds lots of non-optimized single INSERTs, instead of the much quicker bulk INSERTs.
