### ISSUE TITLE
Hiding panes

### ISSUE THREAD

**Issue by Tezei** [HeidiSQL/HeidiSQL#1311]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
Hiya guys, I think it will be very useful to have opportunity to hide log window at the bottom of results also, database tree on the left especially for smallest laptop screens.

**Additional context**

**Comment by ansgarbecker** [comment]
I disagree here - both of them are intentionally not closable. Once they would be closed, many users would panic, not knowing how to show them again.
