### ISSUE TITLE
Doublicate row

### ISSUE THREAD

**Issue by Tezei** [HeidiSQL/HeidiSQL#1312]
**Is your feature request related to a problem? Please describe.**
Ctrl+D to duplicate row same as in MySQL Workbench. Now I should copy entire row. I am using duplicate row functionality a lot. And not only me. :)

**Describe the solution you'd like**
Guys, it will be very useful to be able for us developers to have Ctrl+D to duplicate row same as in MySQL Workbench. It will speed the development for sure.

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment]
There's already a "duplicate row" context menu item.
