### ISSUE TITLE
Cannot open sqlite database stored inside wsl 1 or 2

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#1314]
**Preconditions**

* HeidiSQL version: 11.1.0.6116
* Database type and version: sqlite
* OS: windows 10 + wsl

**Describe the bug**

I have a project inside wsl (1 or 2) with a sqlite database. I'm trying to open it via \\wsl$\ . After a minute or so, it opens but the database is empty (no tables)

**To Reproduce**

1. Create a sqlite database in wsl and create some tables in it
2. Opens it via \\\wsl$\
3. Get an empty database

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/3911428/107994688-240f3800-6fab-11eb-925d-13656c224357.png)

**Comment by ansgarbecker** [comment]
As far as I know opening files from a WSL network share is full of problems, especially when trying to write. I suppose the WSL filesystem causes that empty database, sqlite3.dll is not able to access the database file.

**Comment by sirber** [comment]
I can't even map the wsl network path to a drive. Looks like a huge hack 😄

**Comment by sirber** [comment]
Even dBeaver can't do it.
