### ISSUE TITLE
JSON field viewer

### ISSUE THREAD

**Issue by WinterSilence** [HeidiSQL/HeidiSQL#1318]
Can you append [JsonViewer](https://wiki.freepascal.org/fcl-json#From_JsonViewer)(or something like this) to display JSON in human readable format? For fields with `JSON`  type and optional for `*TEXT` types add here:
 
![изображение](https://user-images.githubusercontent.com/3521094/108925688-25e19700-764e-11eb-9139-2f2e4ce4538c.png)

**Comment by ansgarbecker** [comment]
I planned to add highlighters for some code types, see #136

This is not a valid feature request, as you deleted the whole template.

**Comment by WinterSilence** [comment]
@ansgarbecker ups.. sorry i'm think it's only  issue pattern
