### ISSUE TITLE
Foreign key add issue

### ISSUE THREAD

**Issue by nfrumer** [HeidiSQL/HeidiSQL#1320]
**Preconditions**

 HeidiSQL version: 11.2.0.6213
 Database type and version: MySql 8.0.15
 OS: Win 10 Pro

**Describe the bug**

when adding Goreign keys (constraints) the ON UPDATE and ON DELETE save as "NO ACTION" in place of what I choose

**To Reproduce**

Example:
1. Go to 'foreign keys'
2. add a Foreign key
3. See the result described

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Interestingly, MySQL 8 and current MariaDB versions have a different default setting for the ON UPDATE/DELETE clauses, which are used when you don't modify it in HeidiSQL.
Means I will make "NO ACTION" as the new default for both, and set it explicitly, to overcome these differences in server flavours.

**Comment by ansgarbecker** [comment]
Fixed for the next build
