### ISSUE TITLE
Cannot update/insert postgres jsonb column from data editor

### ISSUE THREAD

**Issue by neobenedict** [HeidiSQL/HeidiSQL#1321]
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: Postgresql (Debian 13.1-1+b1)
* OS: Windows v10.0

**Describe the bug**

Attempting to update a field type of jsonb fails with error
```
/* ERROR:  syntax error at or near "x5B227465737420746578742031222C20227465737420746578742032225D"
LINE 1: ..."Optional") VALUES 
```
The failed query is 
```INSERT INTO "public"."table" ("UpdateChanges") VALUES (0x5B227465737420746578742031222C20227465737420746578742032225D);```
The correct query is
```INSERT INTO "public"."table" ("UpdateChanges") VALUES ('["test 1", "test 2"]');```

This was working previously on version HeidiSQL_10.2.0.5599 so this is a regression. Probably https://github.com/HeidiSQL/HeidiSQL/commit/0c6b609cf29e64026f8ac994427e641d59cd8cbb broke it. Change https://github.com/HeidiSQL/HeidiSQL/blob/0c6b609cf29e64026f8ac994427e641d59cd8cbb/source/dbstructures.pas#L2134 from dtcBinary to dtcOther or dtcText and it should work again as it was working fine with "unknown".

**To fix,** you need to insert the json data as text, not as binary data, yes the column is "json binary" but that is just how it is stored internally, insert and update statements need text.

https://github.com/HeidiSQL/HeidiSQL/blob/033041c2c5833c2b4a0a4dd810d3fa7fa0c81380/source/exportgrid.pas#L686

**To Reproduce**

Create a jsonb column
Insert data normally `INSERT INTO table ("json_column") VALUES ('[1, 2]');`

Try to edit it in the data editor, or add a new row with the data editor. It appears correctly but editing tries to insert binary data instead of updating it as text.

**Screenshots or Crash reports**

https://i.imgur.com/KuNhlup.png
https://i.imgur.com/WhaJXBT.png

**Comment by ansgarbecker** [comment]
I overtook your idea, but ignored the pull request which has lots of unrelated invisible changes.
I suppose the issue is fixed.

**Comment by neobenedict** [comment]
Yes, it is fixed, thank you.
