### ISSUE TITLE
Nightly build installation failed

### ISSUE THREAD

**Issue by WinterSilence** [HeidiSQL/HeidiSQL#1323]
**Preconditions**

* HeidiSQL version: 11.2.0.6230 (64 Bit)
* Database type and version: MySql 8.0
* OS: Windows 10

**Describe the bug**

Nightly build installation failed because the app was not closed. Need add auto closing current application on start installer.

**To Reproduce**

1. Press "Load and intall build ..."
2. New version load successful
3. Error message "app already open, can't replace"(something like this)
4. Installer self close

**Screenshots or Crash reports**

Can't catch this short moment :)

**Comment by ansgarbecker** [comment]
This should be fixed in the latest builds. I refactored the build updater recently.
Please shout if this still occurs for you.
