### ISSUE TITLE
Group SQL keywords and functions

### ISSUE THREAD

**Issue by WinterSilence** [HeidiSQL/HeidiSQL#1324]
**Is your feature request related to a problem? Please describe.**
Current lists are very long and difficult to select quickly (active on first screen).

**Describe the solution you'd like**
Group SQL keywords and functions as in manual (on second screen).

**Describe alternatives you've considered**
Autocomplete not better - sometimes need discover group to find optimal solution.

**Additional context**
![изображение](https://user-images.githubusercontent.com/3521094/109431283-b9341700-7a16-11eb-8752-e1e5913b6440.png)
![изображение](https://user-images.githubusercontent.com/3521094/109431450-cac9ee80-7a17-11eb-93d7-7734a1a548a2.png)

**Comment by ansgarbecker** [comment]
Keywords are not contained in the help structure, so we would have to group them manually. I have no clue how these could be reasonably grouped to be honest.
Functions are already grouped in the context menu, see the screenshot below. I think the helpers listbox does not need grouping as there is a filter box instead. What do you think?

![grafik](https://user-images.githubusercontent.com/7986591/109468555-080c9b80-7a6d-11eb-9f96-585b2d459e3e.png)

**Comment by WinterSilence** [comment]
@ansgarbecker don't see this, fine
