### ISSUE TITLE
Multifilter no longer case intensitive since few updates

### ISSUE THREAD

**Issue by C0kkie** [HeidiSQL/HeidiSQL#1327]
* HeidiSQL version: 11.2.0.62231
* Database type and version: Mariadb 10.5.8
* OS: Windows 10

**Describe the bug**
Since a few weeks (i was lazy) its not longer possible to use the multifilter without being case sensitive. In the past (novembre ?) or something like that it was possible to also search case intensitive

**Comment by ansgarbecker** [comment]
You mean the multi-filter box in the data tab?
If so, this just generates a filter with or'd `column LIKE '%abc%'`. Case sensitivity is defined in the columns. Maybe you were filtering some binary columns?

**Comment by C0kkie** [comment]
Yes in the data tab. In the past i can remember the filter was also like LOWER(column) LIKE '%abc%'

**Comment by ansgarbecker** [comment]
I just looked at the relevant modifications of the multi filter generation, back to 2010. But I couldn't find some `LOWER()` in these modifications. 

Probably you saw a `CAST(xyz AS CHAR)` instead - that is used for date/time columns in MySQL/MariaDB.
