### ISSUE TITLE
Currency € icon post error.

### ISSUE THREAD

**Issue by turkiye61** [HeidiSQL/HeidiSQL#1335]
Hi, 

* HeidiSQL version: 11.2.0.6213
* Database type and version: MySQL 5.6.20
* OS: Windows 10 Pro 64 Bit 20H2.

and 

* Delphi 10.2.3
* Unidac 7.2.6

As seen in the picture below, the € money symbol gives an error when entered.

```
CREATE TABLE `currencys` 
(
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`currency` VARCHAR(3) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	`**moneyicon**` VARCHAR(1) NULL DEFAULT NULL COLLATE 'latin5_turkish_ci',
	PRIMARY KEY (`ID`) USING BTREE
)
COLLATE='latin5_turkish_ci'
ENGINE=MyISAM;
```

Screenshots or Crash reports :

https://prnt.sc/10kow9c 
![grafik](https://user-images.githubusercontent.com/7986591/111040716-b08b0a00-8434-11eb-8090-9d41b477ddbe.png)

Good work.

**Comment by ansgarbecker** [comment]
As far as I can see latin5 has no character for that € sign. You should convert that column to utf8.
