### ISSUE TITLE
这个sql格式能不能优化下？

### ISSUE THREAD

**Issue by wangning769** [HeidiSQL/HeidiSQL#1337]
感谢作者提供这么方便的软件
Thanks to the author for providing such a convenient software
![微信图片_20210316112817](https://user-images.githubusercontent.com/26643242/111252538-48af0c00-864c-11eb-8c4d-d359bd340d7f.png)

**Comment by WesleyM77** [comment]
Translated Title: Can this sql format be optimized?
Translated Body: Thanks to the author for providing such a convenient software.
@wangning769 You're probably going to be asked to close this ticket and put in another using the issue template. There is one for change requests when you click the "New Issue" button above after you're signed in.

**Comment by ansgarbecker** [comment]
Exactly :)
