### ISSUE TITLE
HeidiSQL on Mac using Winery WineSkin

### ISSUE THREAD

**Issue by paulvi** [HeidiSQL/HeidiSQL#1338]
There is https://github.com/jokorivai/HeidiSQL-For-Mac by @jokorivai
that is said was ported to Mac using Winery WineSkin

The usual problem with external build as they don't when there is new version,  
so ideally the port/build should be aligned with this project

**Is your feature request related to a problem? Please describe.**
HeidiSQL is not crossplatform.

**Describe the solution you'd like**
Build for Mac or periodic ports to Mac.

**Describe alternatives you've considered**
Running with Wine, that may not work always.

**Additional context**

**Comment by ansgarbecker** [comment]
I already made various attempts to make the code cross platform, for example using Lazarus and FreePascal. Believe me, that would require a re-build from the scratch. There are many Windows-API calls in the code, and HeidiSQL is based on the Windows-only VCL components. So, a cross-platform build is not just a port, but an entirely new project. Feel free to dive into it.

**Comment by paulvi** [comment]
I bet if @jokorivai was cooperating, those pure Windows API and libraries would evolve into clearly defined antd possibly extracted into separate classes, so any porting effort would be easier

Otherwise, while it is possible to spend (much) time and make it work on other platform,
it would be impossible to keep up with this main line

**Comment by jokorivai** [comment]
> I already made various attempts to make the code cross platform, for example using Lazarus and FreePascal. Believe me, that would require a re-build from the scratch. There are many Windows-API calls in the code, and HeidiSQL is based on the Windows-only VCL components. So, a cross-platform build is not just a port, but an entirely new project. Feel free to dive into it.

Agreed. 
I,ve tried the code porting using Lazarus as well as Delphi FMX, and indeed a rebuild from scratch is needed.

**Comment by jokorivai** [comment]
> I bet if @jokorivai was cooperating, those pure Windows API and libraries would evolve into clearly defined antd possibly extracted into separate classes, so any porting effort would be easier
> 
> Otherwise, while it is possible to spend (much) time and make it work on other platform,
> it would be impossible to keep up with this main line

I don't think I have time for that. I am sorry.

**Comment by ansgarbecker** [comment]
@jokorivai I just wanted to let you know I ported the current code of HeidiSQL v12.10 successfully to Lazarus. I already released a Linux preview version. A version compiled on a Mac is probably only a matter of some yet missing Apple hardware on my side.
