### ISSUE TITLE
Support for Mac OS

### ISSUE THREAD

**Issue by VarunAnandK** [HeidiSQL/HeidiSQL#1341]
Hi team,
   First appreciate for the work and app.

Please add mac os support for app.

**Comment by ansgarbecker** [comment]
That would be an entirely new application, not just "some" changes. I am not very familiar with MacOS, so this will definitely not be mine. But feel free to found a new project.

**Comment by ansgarbecker** [comment]
Probably this one is a good starting point: https://github.com/jokorivai/HeidiSQL-For-Mac
Outdated, but probably helpful.
