### ISSUE TITLE
different from the one I specifiekd.

### ISSUE THREAD

**Issue by Koichi4567** [HeidiSQL/HeidiSQL#1344]
**Preconditions**

* HeidiSQL version:11.0.0.5919(Windows10(64bit) 20H2)
* Database type and version:Maria Ver15.1 Distrib 10.4.17
* OS:CentOS 8.3.2011

**Describe the bug**

HeidiSQL connect to an address different from the one I specifiekd.

**To Reproduce**

1. I connect connect address '192.168.10.103'
2. But error message indicate '192.168.10.105'

**Screenshots or Crash reports**

![bandicam 2021-03-25 09-48-03-301](https://user-images.githubusercontent.com/81345063/112423999-ffab3600-8d76-11eb-86d4-031a7851ff77.jpg)

**Comment by ansgarbecker** [comment]
Please read the error message more carefully: that 192.168.10.105 is the client IP, not the server IP.

**Comment by Koichi4567** [comment]
Sorry,Server Address .

**Comment by Koichi4567** [comment]
Real server address is '192.168.10.103'.

**Comment by Koichi4567** [comment]
I'm sorry .
Cliant address is 192.168.10.105.
Firewall?

**Comment by Koichi4567** [comment]
I made a mistake in the English messase.
I'm so sorry.

**Comment by ansgarbecker** [comment]
No need to be sorry. It was just a misunderstanding of the error.

The message clearly comes from the MySQL/MariaDB server, so you don't have a firewall issue.
But your user "root" is probably only allowed to connect from the local IP 127.0.0.1. You have to connect to the server via SSH or some other remote access. Then, fix the user in MySQL to allow connections from 192.168.10.105.

**Comment by Koichi4567** [comment]
Thank you very much.
