### ISSUE TITLE
Performing search (with F3 key) produces access violation at address 00007FFAE9EE1CE0 in module 'ntdll.dll'.

### ISSUE THREAD

**Issue by budiony** [HeidiSQL/HeidiSQL#1345]
**Preconditions**
On Windows, with HeidiSQL 11.2.0.6251 and MSSQL v.11.0

* HeidiSQL version: 11.2.2.6251
* Database type and version: MSSQL v.11.0
* OS: Windows

**Describe the bug**

When performing simple search in query tab, Ctrl+F and then F3 to find next match, app crashes with access violation. 
SQL was loaded from file. See attached bug report.

**Screenshots or Crash reports**

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/6204146/bugreport.txt)
![heidi](https://user-images.githubusercontent.com/8297417/112463261-b3f28f80-8d6a-11eb-9910-6e7fe8ced03a.png)

**Comment by ansgarbecker** [comment]
Is that reproducible for you? I just tried that with the same settings as in your screenshot, on MSSQL and with a loaded sql file. No crash here.

**Comment by budiony** [comment]
This is weird, I cannot reproduce it anymore.

**Comment by ansgarbecker** [comment]
I'd say I'll close this then, and you shout if you at some point get the same crash again.
The crash happens without any code issue in HeidiSQL, at least from what I can tell.
