### ISSUE TITLE
Error Blob file update

### ISSUE THREAD

**Issue by serginholapolli** [HeidiSQL/HeidiSQL#1348]
date/time          : 2021-03-26, 08:16:25, 632ms
computer name      : SERGIOLAPOLLI
user name          : Serginho
registered owner   : Sergio
operating system   : Windows 10 x64 build 19042
system language    : Portuguese
system up time     : 11 hours 57 minutes
program up time    : 13 minutes 49 seconds
processors         : 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
physical memory    : 21370/32626 MB (free/total)
free disk space    : (C:) 199,46 GB
display mode       : 1920x1080, 32 bit
process id         : $2fd0
allocated memory   : 181,98 MB
largest free block : 122839,95 GB
executable         : heidisql.exe
exec. date/time    : 2021-03-22 17:55
version            : 11.2.0.6251
compiled with      : Delphi 10.4 Sydney
madExcept version  : 5.1.0
callstack crc      : $586c79bc, $e1bbfa39, $e1bbfa39
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 0000000000D74356 in module 'heidisql.exe'. Write of address 0000000000000080.

thread $48ac:
00d74356 heidisql.exe grideditlinks    276  +2 TBaseGridEditorLink.Destroy
00d74e84 heidisql.exe grideditlinks    478  +1 THexEditorLink.Destroy
0041ad62 heidisql.exe System                   TInterfacedObject._Release
00418f4b heidisql.exe System                   @IntfClear
0096f028 heidisql.exe VirtualTrees   19966 +28 TBaseVirtualTree.DoEdit
0096a4c6 heidisql.exe VirtualTrees   17968  +7 TBaseVirtualTree.WMTimer
0040f072 heidisql.exe System                   TObject.Dispatch
006cd90d heidisql.exe Vcl.Controls             TControl.WndProc
006d4b6b heidisql.exe Vcl.Controls             TWinControl.WndProc
0097dc73 heidisql.exe VirtualTrees   25787 +32 TBaseVirtualTree.WndProc
006d3cea heidisql.exe Vcl.Controls             TWinControl.MainWndProc
00569013 heidisql.exe System.Classes           StdWndProc
7ffc80d4 USER32.dll                            DispatchMessageW
0088c44e heidisql.exe Vcl.Forms                TApplication.ProcessMessage
0088c4c3 heidisql.exe Vcl.Forms                TApplication.HandleMessage
0088c911 heidisql.exe Vcl.Forms                TApplication.Run
01064688 heidisql.exe heidisql         104 +41 initialization
7ffc8024 KERNEL32.DLL                          BaseThreadInitThunk
7ffc80fa ntdll.dll                             RtlUserThreadStart

**Comment by serginholapolli** [comment]
Alguém pode ajudar?

**Comment by ansgarbecker** [comment]
Yes, I can probably help. But you will have to use the issue template.
