### ISSUE TITLE
Column visibility checkbox list issue

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#1350]
**Preconditions**

* HeidiSQL version: 11.2.0.6253
* Database type and version: MariaDB ***
* OS: Windows 10

**Describe the bug**
Assume there are ample columns in the table and we'd like to hide some. When we open the column visibility checkbox list we can't set the last _visible_ checkbox by single left button mouse click.
Instead the list scrolls down and the _next_ checkbox switches, not that you just clicked.
 
**To Reproduce**
Important to reproduce the bug: the bottom edge of the last item should be at least slightly below visible field of the list. When the last item is _entirely_ visible, switching performs as expected.

**Screenshots or Crash reports**
Youtube 16 sec video bug reproduction:
[https://youtu.be/-28CjCL9Rsw](https://youtu.be/-28CjCL9Rsw)

**Comment by ansgarbecker** [comment]
That's intenionally I suppose. I recommend to use the arrow and space key to overcome that. Also you could enlarge the dialog to increase the chance all columns are visible at once.

**Comment by AlexLunyov** [comment]
Ok, thank you for recommendation Ansgar.
