### ISSUE TITLE
Data view editor truncated for TEXT columns when emoji is present

### ISSUE THREAD

**Issue by Supinic** [HeidiSQL/HeidiSQL#1351]
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: 10.3.25-MariaDB-0ubuntu0.20.04.1
* OS: Windows 10

**Describe the bug**
In the `Data view` edit window of a ` TEXT` type column, when an emoji (or any multi-byte character in general, possibly) is at position up to 256 inclusive, the value is truncated to 257 characters. The data itself is unchanged. This issue is possibly related to the report on HeidiSQL forums [here](https://www.heidisql.com/forum.php?t=36137).

**To Reproduce**
Example:
1. Create a table containing a `TEXT`, `MEDIUMTEXT`, or `LONGTEXT` column
2. Insert a string value into the row's column, longer than 256 characters
3. Insert an emoji in the string on any position in the 0..256 range
4. Save the column 
5. Refresh the Data view with F5
6. Edit the column again
7. Observe the value being truncated to 257 characters

**Screenshots or Crash reports**

1. `MEDIUMTEXT` column with 500+ characters, and an emoji character on a position lower than 256
2. After saving and refreshing the Data view, the value in the editor is truncated to 257 characters.
![one](https://user-images.githubusercontent.com/7684273/113435536-4a662700-93e3-11eb-8581-810bb9e8645f.png)
![two](https://user-images.githubusercontent.com/7684273/113435545-4e924480-93e3-11eb-8767-9612ca065a9a.png)

**Comment by ansgarbecker** [comment]
There's also a forum post with a CREATE TABLE script and a data row: https://www.heidisql.com/forum.php?t=39239

Bug should be fixed in the nightly builds through bb608ff52c0e48b6685705e5b95d6df7041c3e4d
