### ISSUE TITLE
User manager doesn't remove all rights with checkbox

### ISSUE THREAD

**Issue by geki007** [HeidiSQL/HeidiSQL#1352]
**Preconditions**

* HeidiSQL version: 11.2.0.6253
* Database type and version: MariaDB 10.3.27
* OS: Windows 10 x64

**Describe the bug**
In the User manager if i remove 'Full Access' to Database with the checkbox it doesn't remove all rights

**To Reproduce**
1. Go to 'User manager'
2. Click on 'A User' or create a user
3. Click on 'Add object' (allow access to)
4. Select a Database
5. Give Full Access to Database (Click 'checkbox')
6. Click on 'Save'
7. Now remove Access to Database (Click 'checkbox' again)
8. Click on 'Save'
9. Now the Issue: Some rights are not removed !!

For me it looks like the **rights which are not removed are the rights i see not in the view** if i don't scroll down
If i scroll down before Last Save (before Step 8) it removes every right

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.

**Comment by geki007** [comment]
Wow, thanks for the fast fix and all your work on heidisql.

Looks really fixed for me.
