### ISSUE TITLE
Status bar overlap (high DPI issue)

### ISSUE THREAD

**Issue by quantumwebco** [HeidiSQL/HeidiSQL#1356]
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: mysql 8
* OS: Windows 10

**Describe the bug**

The items in the task bar overlap

**To Reproduce**

On a 4k 28" monitor with 150% display scaling open heidisql and look at the taskbar

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/12368817/114759089-a3c04580-9d55-11eb-9ff5-ac8a23bcdfe7.png)

**Comment by ansgarbecker** [comment]
HeidiSQL is not DPI-aware, and should normally look a bit blurry. Your screenshot tells me you have overridden HeidiSQL's DPI awareness setting. This is not supported. But anyway, that overlapping is more an issue with the small window width. You can widen the window to widen the status bar panels, which fixes that overlapping. There should be enough space on a 28" screen or?

**Comment by quantumwebco** [comment]
Yeah I have overridden the DPI settings

That image is with the app full screen on a 28" 4k monitor so not to do with window size

![image](https://user-images.githubusercontent.com/12368817/115732225-b3f0aa00-a37f-11eb-9926-baa2230d82b2.png)

Everything else works perfectly overriding the display scaling apart from the status bar but I totally understand it's not supported, I just thought I'd mention it on the off chance

Appreciate all your hard work and amazing software

**Comment by quantumwebco** [comment]
<img width="229" alt="image" src="https://user-images.githubusercontent.com/12368817/161381074-4cee4f74-011c-429a-a79e-299b00dfe404.png">

This didn't actually fix it but no worries, I wonder if it's possible to just add a tooltip or something? Or is there another way I can see number of rows selected?

Thanks!

**Comment by ansgarbecker** [comment]
Use the nightly builds, I made a new attempt to support high DPI settings. See #1503
