### ISSUE TITLE
copy-as >SQL INSERTs generate wrong SQL-Code, if  datacolumns are hidden

### ISSUE THREAD

**Issue by Padina42** [HeidiSQL/HeidiSQL#1357]
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: mysql  Ver 15.1 Distrib 10.2.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2 
* OS: Windows 10 (/ Docker/ddev

**Describe the bug**

The Copy-as > SQL INSERTs-Option use everytime the short form for full-row-insert. 
That syntax will fail, if you copy only a selected subset of columns from a table. 

**To Reproduce**

1. Data-view of a table and hide some colum 
2. Mark rows and do action 'copy as > SQL INSERTs'
3. You get a list of INSERT-SQL in this style 'INSERT INTO `tx_simpledataedittest_domain_model_child` VALUES (1618082987, 3, ...'
    (The hidden values are missing, (good), The list of selected column-names after the table-name is missing too. (bad) )
4. You paste the copy in the query-window and let it run. I got the error-Message: "SQL Fehler 1136:  Column count doesn't match value count at row 1."

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
That is normal behaviour, not a bug. If you want the column names in these copy actions, you need to change the clipboard settings once, using the export dialog. Afterwards, the copy as xyz actions will include the columns:

![grafik](https://user-images.githubusercontent.com/7986591/115139905-dcea0580-a034-11eb-9f81-10fe5f39c79e.png)

**Comment by Padina42** [comment]
Thanks for the hint, to use the 'export' (Ergebnis exportieren). That part works fine. The settings of inclusion is preselected. It wrks fine.
 
Have you tested my description, before you closed the issue?
If I use the the copy-as function instead odf the export-as function in the contenxt-menu. the error occur. I don't think, that this is wished standard-behavior.

![2021-04-18 11_19_57-Window](https://user-images.githubusercontent.com/8037773/115140515-0a847e00-a038-11eb-9b87-600ec48cfd4f.png)

**Comment by ansgarbecker** [comment]
Yes, I tested that recently, and now once again. This works as described. Did you probably forget to click the "Save clipbard settings" button?

**Comment by ansgarbecker** [comment]
Note that the button has a probably unclear caption "Kopieren-Einstellungen" in german. However, that's a different issue.

**Comment by ansgarbecker** [comment]
I think it's a good idea to include column names by default. Just changed that for the next build.
