### ISSUE TITLE
Commenting in query windows raises error

### ISSUE THREAD

**Issue by khorsky** [HeidiSQL/HeidiSQL#1359]
**Preconditions**

* HeidiSQL version: 11.2.0.6262 (64 Bit)
* Database type and version: MySQL 5.7.28
* OS: Windows

**Describe the bug**

When trying to comment anything in query windows, I get an error - regardless the content of the query.

**To Reproduce**
Example:
1. Go to query window or create new query window
2. Use CTRL + SHIFT + C
3. See error message: "An error occurred in the application"
4. Hit "continue", rince and repeat

**Screenshots or Crash reports**

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/6338175/bugreport.txt)

**Comment by ansgarbecker** [comment]
Confirmed. Broken through my recent change for 38e5409dbe9758ccbd89cd858089f0728d3e4ca6
Just fixed for the next build.
