### ISSUE TITLE
View XML with markup in Query tab results

### ISSUE THREAD

**Issue by YetAnotherRussian** [HeidiSQL/HeidiSQL#136]
## Expected behavior

Built-in XML viewer **or** show as a link (for system external viewer) **or** tooltip with textarea style (with margins and line breaks)

## Current behavior

Veeeery long tooltip w/o line breaks. It also has display timeout

### Steps to reproduce (use case)

1. Use SELECT statement to find rows containing XML data in any column(s)
2. Wanna see full content (XML-style markup)

### Context

New session (MS SQL), "▻Query" tab(s)

* HeidiSQL version: 9.5.0.5196 64-bit
* Database system + version: MS SQL Server 2008 R2
* Operating system: Windows 10

Detailed screenshots:
![heidi1](https://user-images.githubusercontent.com/4670472/36151775-aaf2b27c-10d9-11e8-914d-726dc42ac3b0.png)
![heidi2](https://user-images.githubusercontent.com/4670472/36151777-ab11eb9c-10d9-11e8-9752-8ad0c37f4d72.png)

**Comment by rentalhost** [comment]
I think that in this case we should only limit the tooltip max length and display an ellipsis in cases like that. Additionally, provide a way to open the Text Editor in read-only (if we could not update the row at moment) or in write-mode (if is possible).

**Comment by YetAnotherRussian** [comment]
I'm not on Pascal side, sorry. In C# you are able to send any text to e.g. stock notepad through importing user32.dll library and sending your text through SendMessage() to a target process. Then, you can read or save this anywhere you want as text file (not to database, of course, I did not mean direct xml save throgh UPDATE statement).

**Comment by rentalhost** [comment]
Did you mean "open text in an external editor"?

**Comment by YetAnotherRussian** [comment]
Yes. It's the simpliest way (rather than providing a built-in editor like MS SQL Management Studio does).

**Comment by rentalhost** [comment]
@ansgarbecker I think valid this suggestion. So I think that we could make it available on Preferences to be an alternative to the default Text Editor (the `[...]` on text columns).

It could works like the Filezilla do: when you open some file to edit, it creates a temporary file with that content, and if you modify it, the app will ask if you wants to save changes. In this way, we just should take care about two situations:

1. If Data Grid still is opened, so the field will be updated with the red arrow;
2. If Data Grid is not available (eg. you are modifying a lot of files at same time), then it will ask to run an UPDATE query to save the changed content;

**Comment by ansgarbecker** [comment]
@YetAnotherRussian - some things you might not have noticed:
* ony the data grid shows that hard coded ellipsis in the tooltip text `[...]` - and only as long as you did not press Ctrl+C, F2 or right mouse button (anything for which HeidiSQL knows it has to load the full row now). The query grids do not show that `[...]` at all.
* you can rightclick any grid cell, then click "Save to file":
![grafik](https://user-images.githubusercontent.com/7986591/36172930-af77f07c-1107-11e8-8f24-e9e8814e0a28.png)
* pressing F2 on a field normally brings up an internal text editor, unless the result is non-editable.

Two things which would help here most in my eyes:
* allow F2 to show the text editor - read only if the result is non-editable
* extend the internal popup text editor with other highlighters. SynEdit (already part of the HeidiSQL sources) provides support for many different code languages, for example xml, html, json, etc. What I have in mind is providing a dropdown in the text editor's toolbar, where the user can select a fitting highlighter, then Heidi remembers that setting for all other fields in the same row of the same table.

**Comment by rentalhost** [comment]
Hm... I thinks that an external editor seems better in general way. I could just open an image to Photoshop, save and update the binary content, for instance.

It could be done?

**Comment by ansgarbecker** [comment]
I think we're about to lose the point of the initial reporter here, which only asked for
> View XML with markup in Query tab results

Anyway, that external app thing is a nice idea, but should probably have its own ticket.

**Comment by rentalhost** [comment]
Oh, you are right at this point. So based on current ticket, I think that supports specific language markup will give to HeidiSQL one more responsability that goes beyond of to be a database manager. And maybe this feature is very public specific at time.

So I think that the best solution here is close this ticket while I write a new ticket about the external editor support. 😃

**Comment by ansgarbecker** [comment]
This is how it looks like after some hours I spent on it, replacing the standard memo with a mighty TSynMemo:

![grafik](https://user-images.githubusercontent.com/7986591/111082222-70488c00-8507-11eb-8812-668a7ea30f33.png)

There are quite a few other highlighters, e.g. for JSON, HTML, PHP, even for TeX and ZPL.
I left some todos unfinished: 
* search/replace dialog does not work with the new editor
* displayed caret position is now broken, have to find a different approach
* provide highlighter customizations

**Comment by ansgarbecker** [comment]
I think I can safely consider this as done. The only doable thing which might now be missing is the highlighter customizations. I will probably do that in a future commit.

Apart from that, there are some enhancements here I didn't even expect:
* search/replace now uses the more feature-rich dialog which is also used for SQL editors
* modified lines are marked with a color bar in the left gutter
* supports 64 different code languages (if I did not miscount)

![grafik](https://user-images.githubusercontent.com/7986591/111514490-14be0e80-8752-11eb-8e65-bc049d6690d6.png)

**Comment by ansgarbecker** [comment]
One additional thing to note: the language selector is restored for edited columns in the data tab, but not in the query tabs (the query tab columns don't have unique identifiers which could be used to identify them the next time)
