### ISSUE TITLE
[Feature Request] Use AppData for saving settings

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1361]
I recently migrated the settings for all my apps to a new computer except HeidiSQL. That's the only app I use that didn't honour the AppData folder.

A proposal to use %AppData% for storing settings instead of the Windows Registry.
The main reason is because it's pretty industry standard.

**Comment by ansgarbecker** [comment]
It's not true that storing configuration in %AppData% is industry standard. The location for configuration highly depends on the program. Just have a look into your registry folder `HKEY_CURRENT_USER\SOFTWARE\`, and you will see it's quite still popular to use the registry for settings. Windows itself uses it as well for most settings.
Even HeidiSQL makes use of it - for log files and tab restoring.

However, the idea may still be a good thing, but you will need to repost it using the issue template.
