### ISSUE TITLE
Invalid create SQL for foreign key in database that has dots in the name

### ISSUE THREAD

**Issue by exuvo** [HeidiSQL/HeidiSQL#1364]
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: mariadb 10.5.8
* OS: linux 5.9.8 and wine 4.8

**Describe the bug**

While connected to a DB whose name contains a dot . the create code tab has invalid SQL. This used to work in older versions when the DB name was never prepended to the foreign key target. Which is also what i would prefer as i now have to clean the create code up as it should not contain the DB name at all for my use case.

**To Reproduce**

1. Add a foreign key and save it.
2. After the save the view is reloaded and the create code tab now contains the DB name incorrectly in the CONSTRAINT REFERENCES part. 

**Screenshots or Crash reports**

Ex with DB named a.b.c and table test_table:
```CONSTRAINT `FK_test_table_1` FOREIGN KEY (`roundID`) REFERENCES `a`.`b.c.test_table` (`roundID`) ON UPDATE CASCADE ON DELETE CASCADE```

**Comment by exuvo** [comment]
Sorry just realised my heidi version is not up to date. I'll test tomorrow with the lastest one and reopen if the issue persists.

**Comment by exuvo** [comment]
The problem is also in 6265 so i'll reopen this.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.

Note you can still trick the SQL generation when creating a new foreign key, and you type the name of a different database into it:
![grafik](https://user-images.githubusercontent.com/7986591/116826198-1b360780-ab93-11eb-8293-014dda3e6d3f.png)
![grafik](https://user-images.githubusercontent.com/7986591/116826210-30ab3180-ab93-11eb-8f5a-be5446f03b89.png)

But that's an edge case I'd say. However, loading an existing foreign key should not generate a wrong reference now.

**Comment by exuvo** [comment]
Thanks for the quick response but I am sad to say the fix does not seem correct. I tested with 6269.
When opening an existing table with foreign keys my create tab now has an extra invalid dot in front of the table name.
```
CREATE TABLE `test` (
	`aID` INT(10) UNSIGNED NOT NULL,
	`bID` INT(10) UNSIGNED NOT NULL,
	`distance` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (`aID`, `bID`) USING BTREE,
	INDEX `FK_test_2` (`bID`) USING BTREE,
	CONSTRAINT `FK_test_1` FOREIGN KEY (`aID`) REFERENCES `a.domain.se`.`.test_A` (`aID`) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT `FK_test_2` FOREIGN KEY (`bID`) REFERENCES `a.domain.se`.`.test_B` (`bID`) ON UPDATE CASCADE ON DELETE CASCADE
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
```
DB is named `a.domain.se` and tables `test` `test_A` `test_B`.

**Comment by exuvo** [comment]
How do i reopen this?

**Comment by ansgarbecker** [comment]
Next build hopefully fixes the wrong dot position, and some more:
* data tab grid should display foreign key dropdowns for such keys
* foreign key editor for column name(s) should work without this error: "_Reference table "xyz" seems to be missing, broken or non-accessible._"

**Comment by ansgarbecker** [comment]
By the way, to reopen an issue, there's a button below the comment box (probably not available due to missing privileges, not sure):
![grafik](https://user-images.githubusercontent.com/7986591/119258096-8e4a0100-bbc8-11eb-8030-51c18c1443df.png)

**Comment by exuvo** [comment]
No that button was not there for me here, i usually have it in other places on github.

**Comment by exuvo** [comment]
Can confirm the fix works in 6292!
