### ISSUE TITLE
Reported wrong version of PostgreSQL

### ISSUE THREAD

**Issue by Ivan-Perez** [HeidiSQL/HeidiSQL#137]
I'm connecting to a PostgreSQL server, version 10.2. HeidiSQL incorrectly reports it as PostreSQL 4.8.5, although on the ballon I can see the correct version. Maybe this is only a parse problem, so it could be fixed easily.

### Context

* HeidiSQL version: 9.5.0.5245
* Database system + version: PostgreSQL 10.2 on CentOS 7
* Operating system: Windows 7

![sin titulo](https://user-images.githubusercontent.com/3533970/36155869-d009bc6c-10d5-11e8-8a07-8da2462f01b3.png)

**Comment by rentalhost** [comment]
Seems like it is reading the Red Hat version instead of database system.

**Comment by ansgarbecker** [comment]
Should be fixed in the next nightly build.

**Comment by Ivan-Perez** [comment]
Thanks!
