### ISSUE TITLE
HeidiSQL Crashes on Windows XP 32 bit

### ISSUE THREAD

**Issue by algPoS** [HeidiSQL/HeidiSQL#1371]
**Preconditions**
* HeidiSQL version: 11.2.0.6213 (32 Bit)
* Database type and version: MySQL (version 5.6.51)
* OS: Windows XP 32 Bit

**Describe the bug**
When the application is downloaded form the website I am getting a error saying "this is not a valid Win32 application" so I downloaded the Portable 32 bit version and when I start the program I get the Crash screen that allows me to send you a bug report but when I try It fails to send the report so I am sending it on here.

**To Reproduce**
Try to run it on a Windows XP 32 Bit machine 

**Screenshots or Crash reports**
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/6437585/bugreport.txt)

**Comment by ansgarbecker** [comment]
I dropped support for running on WinXP long time ago. Even Win7 is not fully supported with HeidiSQL. You should update to a newer Windows.
