### ISSUE TITLE
show error

### ISSUE THREAD

**Issue by zb503758762** [HeidiSQL/HeidiSQL#1373]
'（			）','（   ）')

![image](https://user-images.githubusercontent.com/16384186/118449061-51dc5800-b725-11eb-9f88-930d1575ccf6.png)
![image](https://user-images.githubusercontent.com/16384186/118449087-586acf80-b725-11eb-8f0a-0dff4691e50d.png)

**Comment by ansgarbecker** [comment]
Please use the issue template.
