### ISSUE TITLE
"Explain Current Query" on right click is gray when current query is selected

### ISSUE THREAD

**Issue by auspiciousflat** [HeidiSQL/HeidiSQL#1375]
**Preconditions**

* HeidiSQL version:11.2.0.06287
* Database type and version:Postgres13
* OS:Windows10

**Describe the bug**

Run Current Query is work, but "Explain Current Query" on right click is gray.

**To Reproduce**

1.Run Current Query (work)
2.In menu, Query -> Explain Current Query  (work)
3.Right Click on SQL, Explain -> "Explain Current Query" is gray. 
  (Run Current Query is still work)
4.after see that, In menu, Query -> Explain Current Query  is also gray.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Didn't know PG and SQLite support `EXPLAIN` queries. However,
* menu items were inconsistently updated, which is now fixed
* menu item for EXPLAIN analyzer is enabled only for MySQL and MariaDB
* MSSQL never gets these items enabled.

**Comment by auspiciousflat** [comment]
#1240 doesn't work

**Comment by ansgarbecker** [comment]
Can't find a reproduction recipe for that - `EXPLAIN` is never fired with an empty sql here. And the code for the error message due to an empty query is still there.
Please describe exactly what you did and which error you got.

**Comment by auspiciousflat** [comment]
sorry I was misunderstanding it.
thank you for incredibly rapid fix
