### ISSUE TITLE
Search and Replace crash in procedures and views

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#1376]
**Preconditions**

* HeidiSQL version: 11.2.0.6290
* Database type and version: 
* OS: Windows 10

**Describe the bug**

Search and Replace form crashes in procedure editor.

**To Reproduce**

**Screenshots or Crash reports**

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/6531993/bugreport.txt)

**Comment by ansgarbecker** [comment]
Confirmed. Broken by my recent changes for #136. Fixed in the next build.

**Comment by AlexLunyov** [comment]
Thanks!
