### ISSUE TITLE
1054 Unknown Column on updating subselectresults

### ISSUE THREAD

**Issue by Dwza** [HeidiSQL/HeidiSQL#1380]
**Preconditions**

* HeidiSQL version: 11.2.0.6213
* Database type and version: MariaDB
* OS: Windows

**Describe the bug**

When selecting across two or more tables, it is not possible anymore to update selected value in resultlist.

**To Reproduce**

lets say you have 2 tables (t1, t2)
Example:
1. select t1.a, t1.b, t2.x from t1 left join t2 on t1.a = t2.a
2. Click on submit and see result list
3. click column t2.x and change value
throws an error (1054) unknown column 'x' in 'field list'

**Screenshots or Crash reports**

No Crashreport available. Error will appear on select rebuild of my example

**Comment by ansgarbecker** [comment]
HeidiSQL just not supports updates on multi-table results, because it is mostly not possible to generate a safe WHERE clause for an update in such cases. I wonder how you managed to trigger an update? Using the current build, a joined result does not let me edit the values.

**Comment by Dwza** [comment]
ok. to trigger the update i just clicked in the result into a field, changed value and removed curser from this field. it triggers some kind of autoupdate.... but with the note i mentioned. :)

**Comment by ansgarbecker** [comment]
Thanks for the update. We should test again with the soon coming next release.
