### ISSUE TITLE
File does not exist: portable_settings.txt

### ISSUE THREAD

**Issue by Morgy93** [HeidiSQL/HeidiSQL#1382]
**Preconditions**

* HeidiSQL version: 11.3.0.6295 (32 Bit)
* Database type and version: - 
* OS: -
* Compiled: 2021-05-30 05:39:24
* Environment: Windows v10.0, Store Package 2691 AnsgarBeckerSoftware

**Describe the bug**

I assume the latest update from today broke my HeidiSQL Microsoft Store version.
Upon start I'm only left with:

![image](https://user-images.githubusercontent.com/7961978/120160486-96242980-c1f6-11eb-9472-b874e4f7f0ba.png)

It starts if I click on OK but all my settings are gone =(

If I reimport the settings, then they're gone with the next start again.

It is unusable in this state, there are way more errors thrown if I try to use the application.

I'd try to reinstall it, but I wanted to report first, since it really might be caused by the update and does not affect just me. *EDIT:* Does not work

**To Reproduce**

1. Use HeidiSQL via MS Store for longer
2. Update via MS Store
3. See Error
4. I really don't know how this happened, I just saw that the app updated today via Microsoft Store

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/7961978/120160802-f31fdf80-c1f6-11eb-9cda-1cad585cd5c0.png)
"Recent activity: changed today"

**Comment by Morgy93** [comment]
Resetting or reinstalling the app via Microsoft Store does NOT solve the issue. 😭

**Comment by ansgarbecker** [comment]
Exit HeidiSQL and delete the portable.lock file from the installation - that should work. I'll go and add another release without that file.
This is the second time I broke this. I think I should drop the MS Store version.

**Comment by Morgy93** [comment]
I tried, but I cannot simply edit files under `C:\Program Files\WindowsApps\` nor delete the `portable.lock`.
It says I need elevated priviliges. I'll just wait for your update.

I'd really love to keep the Microsoft Store version for easy updates. 🙏 

But "at least" you may consider maintaining for the Windows Package Manager yourself: 
https://github.com/microsoft/winget-pkgs#submitting-a-package
https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/HeidiSQL/HeidiSQL (only v11.2)
That would be my second preferred install method.

**Comment by caesarali** [comment]
How to get my previous setting back after update ?
after this bug, my all setting is totally cleared. Did not see anything in session manager, just like fresh installed heidisql.

**Comment by ansgarbecker** [comment]
Update is in progress in the MS store dev center.

If you can, delete the "portable.lock" file from
`C:\Program Files\WindowsApps\2691AnsgarBeckerSoftwareD.19284136982C_11.1.0.0_x86__peg9cky9b9hfj` .
The folder may be named differently on your system. If so, find it in
`C:\Program Files\WindowsApps\`

**Comment by ansgarbecker** [comment]
Dev center says the update is in the store now.

**Comment by ariadevl** [comment]
I tried to delete portable.lock file from 
`C:\Program Files\WindowsApps\2691AnsgarBeckerSoftwareD.19284136982C_11.3.0.0_x86__peg9cky9b9hfj`
with take ownership before deleting and finally my setting restored, thanks @ansgarbecker

**Comment by JinZhuXing** [comment]
I love HeidiSQL at Microsoft Store.
I have a same issue.
Please update ASAP.
Thank you and thanks to HeidiSQL.

**Comment by ansgarbecker** [comment]
The store version should already be updated, and the update contains a fix. Please check if you see that update.

**Comment by JinZhuXing** [comment]
Still can not find update version.
![image](https://user-images.githubusercontent.com/15034343/120483485-baddf400-c3e4-11eb-8877-b3397a481f41.png)

I'll wait more.
I think Store is not ready at our region.

**Comment by ansgarbecker** [comment]
The version 11.3 did not change. I was able to upload the same version again, with an update package.
Probably you have to remove it once and reinstall.

**Comment by Morgy93** [comment]
> The version string "11.3" did not change. I was able to upload the same version again, with an update package.
> Probably you have to remove it once and reinstall.

I sadly cannot confirm. Reinstall doesn't solve it.
But thanks for the hint, I'll just try it every day. 😁

**Comment by JinZhuXing** [comment]
I just tried with reinstalling, but this issue is not solved.
I'll try it tomorrow.
Thank you.

**Comment by ebonato** [comment]
> Exit HeidiSQL and delete the portable.lock file from the installation - that should work. I'll go and add another release without that file.
> This is the second time I broke this. I think I should drop the MS Store version.

Worked. And settings restored like a charm...  
To delete portable.lock, you need first get the ownership of file, then add a security rule allowing total control for your current user.

**Comment by MichaelPagel** [comment]
I can´t see any updates inside the windows store, just the first one from yesterday.
Could it be that the store didn´t recognize the "upload the same version again, with an update package." as a newer version and keeps the old, faulty one?

**Comment by ansgarbecker** [comment]
I guess that's it - the dev center allows to publish a new submission with the same version number but users won't get it.
So I just incremented the build version (11.3.1.0) and uploaded again. Now awaiting certification from MS.

**Comment by JinZhuXing** [comment]
Thank you. It's resolved.
