### ISSUE TITLE
SQLite database created with Delphi and FireDAC cannot be opened with HeidiSQL

### ISSUE THREAD

**Issue by IvBKo** [HeidiSQL/HeidiSQL#1383]
**Preconditions**

* HeidiSQL version: 11.3.0.6295 (64 Bit)
* Database type and version: SQLite3
* OS: Windows 10 Pro

**Describe the bug**

SQLite database created with Delphi 10.4 and FireDAC cannot be opened with HeidiSQL. 

When you open SQLite 3, a database created in Delphi 10.4 and the database is created with parameters
'OpenMode = CreateUTF16' / 'GUIDFormat = Binary' / 'DateTimeFormat = DateTime'

an error occurs

'attached databases must use the same text encoding as main databaseuery'

**To Reproduce**

1. Create a new DELPHI project, add DM, place a button and on execute:

 with SQLiteDM.FDConnection do
            begin
              Close;
              Params.Clear;
              DriverName := 'SQLite';
              LoginPrompt := False;
              Params.Add('OpenMode=CreateUTF16');
              Params.Add('SQLiteAdvanced=page_size=16384;auto_vacuum=1');
              Params.Add('Database=C:\TEMP\SQLiteStore.sdb');
              Params.Add('GUIDFormat=Binary');
              Params.Add('DateTimeFormat=DateTime');

              Connected := True;
            end;
            
     2. Try to open C:\TEMP\SQLiteStore.sdb with HeidiSQL. 

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/85292264/120644335-e235cf00-c47f-11eb-860b-cf5fe8bd1470.png)

**Comment by ansgarbecker** [comment]
Please try to open that database with a new blank session. According to your description, you were attaching it to another one.

**Comment by IvBKo** [comment]
It doesn't matter.
All other connections are closed, the error is the same.
The database is the same, it is easier for me to write C: \ TEMP \ in a public post than to publish the real path.
I have been involved in Delphi and programming since 1992.

**Comment by IvBKo** [comment]
The same DB opened with FireDAC Explorer

![image](https://user-images.githubusercontent.com/85292264/120646156-e82caf80-c481-11eb-8865-f616c9001923.png)

**Comment by ansgarbecker** [comment]
I meant you were using one session with multiple sqlite files.
Your screenshot says there's a "127.0.0.1|" in front of the actual file. Please remove that, so you have only "C:\whatever\xyz.sdb" in the filename input.

**Comment by IvBKo** [comment]
Aha I understand.
Interesting. I did not enter this address.
I only used the application interface.
Perhaps when a file is selected, this address is not deleted.

Thanks!
Everything is fine now!
