### ISSUE TITLE
"Quick Filter" misses quotes if INT value selected in VARCHAR column

### ISSUE THREAD

**Issue by niewouf** [HeidiSQL/HeidiSQL#1386]
**Preconditions**

* HeidiSQL version: 11.3.0.6311
* Database type and version: MariaDB 10.3.16
* OS: windows 10

**Describe the bug**

When pressing right mouse button on a VARCHAR data grid row field and choose "Quick Filter" the selected value or the value of the clipboard is not put into quotes anymore. Looks like it interpretes the value as INT if it only contains digits?!? This behaviour leads to much longer selection times or to complete unsuability of Heidi. Suggestion: maybe better to use the field type instead the value type to decide how to handle the filter string!

**To Reproduce**

MSISDN IN (49123456789) 
instead of 
MSISDN IN ('49123456789')
where column is defined
`MSISDN` VARCHAR(20) NOT NULL DEFAULT '0' COLLATE 'utf8_general_ci',

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Broken in 65cf4a58209f239b641881273bc6ee361ae829c6
