### ISSUE TITLE
File not found Error when Accents are in Filepath

### ISSUE THREAD

**Issue by DoomChryz** [HeidiSQL/HeidiSQL#1387]
**Preconditions**

* HeidiSQL version: 11.3.0.6295 (64bit)
* Database type and version: MariaDB 10.4.12
* OS: Windows 10

**Describe the bug**

When attempting to import csv Files from a Filepath where accents are present, it shows "SQL Error (2): File 'C:\Páth\with\Accent\test.csv' not found (Errcode: 2)

**To Reproduce**

1. Create a Path with an Accent e.g. (C:\Tést)
2. Put valid csv File there
3. Attempt to import said File
4. Fails

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
From https://mariadb.com/kb/en/load-data-infile/ :

> The character_set_filesystem system variable controls the interpretation of the filename.

`SHOW VARIABLES LIKE 'character_set_filesystem';`

| Variable_name | Value | 
| --- | --- | 
| character_set_filesystem | binary | 

Any clue how to convert the filename into MySQL's binary charset?

**Comment by ansgarbecker** [comment]
I found the `LOAD DATA` command accepts the 8.3 format of a filename, which also works in cases the original filename has accented chars. Next build will have that workaround. Please test.

I would be happier if I had a way to convert the real filename into the binary charset.

**Comment by DoomChryz** [comment]
Just do add input - i think converting should be possible using the BINARY charset:

https://dev.mysql.com/doc/refman/8.0/en/charset-binary-set.html

Thanks for fixing Ansgar! 👍
