### ISSUE TITLE
Alternated color in field list

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#139]
## Steps to reproduce this issue

Would be nice if in list of fields we had the option to put alternated colors like the data tables.

## Possible solution
![image](https://user-images.githubusercontent.com/11230133/36282783-71779934-1289-11e8-93d9-603cecd57cc7.png)

**Comment by rentalhost** [comment]
**Internal:** the "grid formatting - alternating row background" will not works here, but I think that we could use the same option to affects this list (_and maybe apply it to tables listing too?_).

**Comment by lukinhaspm** [comment]
@rentalhost agree

**Comment by lukinhaspm** [comment]
In additional, can add a "sort columns"? I think its will help a lot

**Comment by lukinhaspm** [comment]
@ansgarbecker , how should looks? For me keep same

**Comment by yphastos** [comment]
Can you also add the alternating colors to the "Database" view tab? e.g. the one listing all the tables (and views, etc) from a given database?

![image](https://github.com/HeidiSQL/HeidiSQL/assets/13773388/cbf23e16-5796-42a9-a1b3-a98c7cfc0550)

ty in advance

**Comment by ansgarbecker** [comment]
Really? Quite ugly there if you ask me. However, the user has the choice.

**Comment by ansgarbecker** [comment]
Next build supports alternating row colors in even more lists: database tab, and all subtabs of host:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/b84cf92e-9535-41f6-8704-a723fca88374)
