### ISSUE TITLE
Query tabs: new highliting doesn't stick after zooming in/out

### ISSUE THREAD

**Issue by Joey79100** [HeidiSQL/HeidiSQL#1392]
**Preconditions**

* HeidiSQL version: 11.3.0.6326
* Database type and version: any
* OS: Windows 10 12H1 - build 19043.1052

**Describe the bug**

In **Query X** tabs, the left column that displays row numbers is now highlighted with the color choosen for the current session.
When you zoom in/out in these tabs, the color disappears.

**To Reproduce**

1. Make sure you're using a session than has a Background color different than default (Session Manager > select a session > Advanced tab > Background color). Let's say it is yellow.
2. Open a Query tab. You should see the left column in a yellow color.
3. Use Ctrl+Mouswheel to zoom in or out: the color turns back to the default color.
You can then select another session, and come back to this one, and the color will be restored.

**Screenshots or Crash reports**

Before:
![image](https://user-images.githubusercontent.com/12445716/123229615-c2ba2100-d4d6-11eb-892a-0286add7e793.png)

After:
![image](https://user-images.githubusercontent.com/12445716/123229626-c64da800-d4d6-11eb-966c-b526ef938647.png)

**Comment by ansgarbecker** [comment]
Fixed in the latest build.
