### ISSUE TITLE
Unkown Column "passsword" in "field_list" 

### ISSUE THREAD

**Issue by DoomChryz** [HeidiSQL/HeidiSQL#1394]
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: MariaDB 10.4.14
* OS: Windows 10

**Describe the bug**

So i have actually not really an idea whats happening here, but i have some tables where i have a password field in it.
For some, to me unkown Reason, when i try to change Data inside those Tables, i get this Error:

![image](https://user-images.githubusercontent.com/19556660/123417747-6f200400-d5b8-11eb-925b-72210b6c068d.png)

I mean this Error is technically true. There isnt any "Pa**sss**word" column in the field list, where does the third s come from?  I also do not try to change the password but another value. Also: Not sure if really bug.

**To Reproduce**

*Create Table*
*Put a password field in it & name it password*
*Put a Username Field in it*
*Enter Values*
*Try to change any values*

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
And you entered the values through the Data tab, or a query tab?

However, a quick test with the current nightly build did not show me the same result in the data tab. I get a normal update with the correct spelling of the password column.

**Comment by DoomChryz** [comment]
Ive checked it through the Data Tab.

**Comment by DoomChryz** [comment]
Okay, ive found the error - its not related to heidi, i have a trigger here which is wrongly named

**Comment by ansgarbecker** [comment]
Hehe, funny issue. Glad you found the cause.
