### ISSUE TITLE
Crash on exit, in TMainForm.DisplayRowCountStats

### ISSUE THREAD

**Issue by jhansen31** [HeidiSQL/HeidiSQL#14]
## Expected behavior

Crashed on exit

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

click on Windows 10 'X' upper right corner of HeidiSQL app
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1496186/bugreport.txt)

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version:
* Database system + version:
* Operating system:

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by ansgarbecker** [comment]
Should be fixed by 7a9d367ad1c1b3751b8570b0d75d3ca8bb1c38b5

The next time you report something here, please correctly fill out the issue template.

**Comment by jhansen31** [comment]
Yes sir – I thought the crash report would answer any questions.
Sorry about that.

John Hansen
jwhansen@live.com
