### ISSUE TITLE
HeidiSQL desktop disapper on windows 10

### ISSUE THREAD

**Issue by fy-kenny** [HeidiSQL/HeidiSQL#1404]
**Preconditions**

* HeidiSQL version: 10.2.0.5599
* Database type and version: 5.5.5-10.4.7-MariaDB
* OS: Windows 10 Pro

**Describe the bug**

I  occured that the query edit and log viewer is black blocks every line and I guess the cause maybe prefference is modified
but after restored, it is still existing.  so I close the window and try to start it again, after I type user and password, I can not see it  anywhere. but it showes in Window task manager.

**To Reproduce**

sorry, I have no time to shutdown my computer

**Screenshots or Crash reports**

![heidisql_desktop_disapper](https://user-images.githubusercontent.com/1905343/124716727-fa918180-df36-11eb-8946-cacb9ea411ff.png)

**Comment by ansgarbecker** [comment]
v10.2 is two years old. Please install v11.3 and on top update to the latest build. Afterwards please retry.

**Comment by fy-kenny** [comment]
@ansgarbecker Thank you reply, it works now after re sign in my computer, maybe the bug is related to windows explorer, but Im not sure.
Another possible reasons:
1. backgroud color solution of query editor or log viewer is conflict to another application at specified time like '360 desktop assistant‘ 
![image](https://user-images.githubusercontent.com/1905343/124726914-c8851d00-df40-11eb-97a7-c6a593bed078.png)


> v10.2 is two years old. Please install v11.3 and on top update to the latest build. Afterwards please retry.

**Comment by fy-kenny** [comment]
![image](https://user-images.githubusercontent.com/1905343/124727277-26b20000-df41-11eb-9493-22e5d20d965d.png)
This is my backgroud color of windows task manager before HeidiSQL desktop disappear. This is just a guess you can use it as a reference.

Thank you again :D

**Comment by ansgarbecker** [comment]
Will close this issue, as the comments sound as if this is fixed. If it re-appears, please shout.
