### ISSUE TITLE
SQLite Unable to drop a column

### ISSUE THREAD

**Issue by barok1383** [HeidiSQL/HeidiSQL#1408]
**Preconditions**

* HeidiSQL version: 11.3.0.6333
* Database type and version: SQLite
* OS: Windows 10 64 bits

**Describe the bug**
Unable drop a column

**To Reproduce**
This is the SQL statement produced when creating the table with the GUI
CREATE TABLE "statistics" (
	"verdict" CHAR(2) NULL DEFAULT NULL,
	"date" DATETIME NULL DEFAULT NULL
);
ALTER TABLE "statistics" DROP COLUMN "date";
/* Error de SQL (1): near "DROP": syntax error */

**Workaround**
https://www.sqlite.org/faq.html#q11
Regards

**Comment by ansgarbecker** [comment]
Related: issue #1604 and #1605

**Comment by ansgarbecker** [comment]
Note that if you try to drop a column which has an index, SQLite complains with a cryptic message:
> error in index MyIndex after drop column: no such column: "MyColumn" - should this be a string literal in single-quotes?

Solution is to it in two steps: drop the index first, then drop the column.
