### ISSUE TITLE
Exception raise while plink reconnecting

### ISSUE THREAD

**Issue by b-fett** [HeidiSQL/HeidiSQL#141]
## Steps to reproduce this issue

1. configure MySQL connection through SSH tunnel
2. open connection
3. wait plink connection to be terminated
4. use any function that causes SQL commands sending

## Current behavior

Exception message is raising.

## Expected behavior

Connection reestablished successfully.

## Environment
- HeidiSQL version: 9.5.0.5245
- Database system + version: Ubuntu 16.04.3 LTS, 10.2.12-MariaDB
- Operating system: Windows 7 (6.1.7601)

## Logs
There are diffrent versions and time of bugreports.
[bugreport.zip](https://github.com/HeidiSQL/HeidiSQL/files/1731505/bugreport.zip)

**Comment by ansgarbecker** [comment]
I recall I already fixed this, short before releasing v10.0.

Could you please verify that with the latest build?

**Comment by b-fett** [comment]
with latest heidi, plink and  win10 i'm not experiencing such problem anymore.
i've tried to terminate ssh connection and even plink process, it seems like heidisql handles such scenarios.
