### ISSUE TITLE
HeidiSQL does not show Postgres databases, neither with 1.0 nor with 1.2 library...

### ISSUE THREAD

**Issue by jayjupdhig** [HeidiSQL/HeidiSQL#1410]
**Preconditions**

* HeidiSQL version: Most current on 2021-07-21
* Database type and version: Postgres from Debian 10
* OS: Debian 10

**Describe the bug**
Does not show that databases, pls. look at screenshot.

**To Reproduce**
Install Debian 10 and Postgres and Nocommerce - most current versions

**Screenshots or Crash reports**
![1](https://user-images.githubusercontent.com/42765391/125289568-a95f0480-e31f-11eb-8378-803296bc7e5a.png)
![2](https://user-images.githubusercontent.com/42765391/125289569-aa903180-e31f-11eb-8682-4c8848b0937f.png)

Thank you for your feedback.

**Comment by jayjupdhig** [comment]
-> PostgreSQL 11.12

**Comment by ansgarbecker** [comment]
Probably you mix up schemata and databases. HeidiSQL's tree on the left shows the result of such a query:

    SELECT "nspname" FROM "pg_catalog"."pg_namespace" ORDER BY "nspname";

You can select a database in the session settings. Github just does not let me upload a screenshot right now - please look at the "Database" setting in the session manager. Using the drop-down arrow, you should see that "postgres" database (but not the "template"s).

**Comment by jayjupdhig** [comment]
same result when i select "postgres" database...

**Comment by jayjupdhig** [comment]
and same result too when i select nopcommerce db...

why that?

**Comment by ansgarbecker** [comment]
Do you expect to see databases in the schemata list, or..? I'm not sure if this is a misunderstanding.

**Comment by jayjupdhig** [comment]
Oh - now i saw it i need to open the "public" entry (after chosing "nopcommerce" in the connections settings list)... then i see the tables from "nopcommerce".

Thank you very very much!! :-)

**Comment by ansgarbecker** [comment]
Thanks for the feedback!
