### ISSUE TITLE
Efficient navigation through foreign key relations

### ISSUE THREAD

**Issue by AlexandrosMelissas** [HeidiSQL/HeidiSQL#1411]
**Is your feature request related to a problem? Please describe.**
In case there are a lot of tables and rows, it's really difficult to navigate through foreign key associations efficiently.

**Describe the solution you'd like**
A good solution would be that if i were to Ctrl + Click a foreign key, i would be taken to the associated row to the other table.

**Describe alternatives you've considered**
An alternative solution would be a right side panel showing the associations there but that's not ideal because there might be many.

**Additional context**
None.

**Comment by ansgarbecker** [comment]
Duplicate of #156
