### ISSUE TITLE
Cannot connect to PostgresSQL server with apostrophe in the password

### ISSUE THREAD

**Issue by sycdan** [HeidiSQL/HeidiSQL#1417]
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: PostgreSQL
* OS: Windows 10

**Describe the bug**

I am unable to connect to PostgresSQL when there's an apostrophe (`'`) in the password. I get the following error message:

`missing "=" after "TheRestPartOfMyPasswordAfterTheApostrophe'" in connection info string`

**To Reproduce**

Edit any existing PostgreSQL connection, or create a new one, and put an apostrophe somewhere in the password string (the rest of the connection parameters don't need to be correct), save it then click Open.

**Comment by ansgarbecker** [comment]
Backslashes in SSL options are already escaped since 0fe7bb66cba163b3e56a9e6831628569bd305e14, but that's just half baken.

**Comment by ansgarbecker** [comment]
Fixed in the next nightly build.
SIngle quotes and backslashes in all connection string values are now properly escaped with a backslash. See the [docs](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING).

**Comment by sycdan** [comment]
@ansgarbecker Thank you for that lightning-fast fix! :)
