### ISSUE TITLE
Tab "Code CREATE" kepp dbname in foreign key even if both table are in same database

### ISSUE THREAD

**Issue by Cassetete** [HeidiSQL/HeidiSQL#1419]
Tab "Code CREATE" kepp dbname in foreign key even if both table are in same database

**Preconditions**

* HeidiSQL version: Version 11.3.0.6336 (64 Bit)
* Database type and version: MariaDB 10.3.30
* OS: Windows 10 (19043.1110)

**Describe the bug**

Since some version, in "Code CREATE" tab, HeidiSQL add the database name in foreign key definition even 
if the foreign table is in same database. 

**To Reproduce**

1. Create db, like "dbtest"
2. Create tableA in dbtest
2. Create tableB in dbtest with a foreign keys to tableA
3. View the tab "Code CREATE" for tableB.
4. Voilà, in create code, the db name "dbtest" will appear (even if the two tables are in the same db).

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/18293669/127867731-3f9d1888-ca6b-4741-847a-0f2df318d1a6.png)

**Comment by ansgarbecker** [comment]
I suspect my solution for #1364 to be causing that.
Is there a real problem with the database name or is that just cosmetically?

**Comment by Cassetete** [comment]
The problem is the database name is there.
For example, with query "SHOW CREATE TABLE `dbtest`.`tableb`;", the result is ok (no database name in result) but HeidiSQL put the name.
It's very annoying when I copy/paste for an another database (now I must remove the db name for each foreign key, or use "show create table").

**Comment by Cassetete** [comment]
4 month passed, this "bug" (keep dbname in references forgein key) can ruin a database system and nothing change... it's a really quick change in your code. 
I see the "enchencement" tag, it's not good. If someone got used to the code in "create table" tab for not on the EXACTLY the same db (thing will never happen, because the use of this tab it's the fast replication table in another db), own dbs will be produce error or worse, corrupt data organisation.

**Comment by ansgarbecker** [comment]
Next build should have no database name in the reference if it's the same as the database of the underlying table.
Hopefully this does not break #1364 again, with database names containing a dot.
