### ISSUE TITLE
Horizontal scrolling in grids

### ISSUE THREAD

**Issue by penCsharpener** [HeidiSQL/HeidiSQL#142]
## Current behavior

* mouse wheel without function key pressed scrolls up and down a table
* mouse wheel with `shift` pressed moves the selected row/cell
* mouse wheel with `ctrl` pressed zooms the table
* mouse wheel with `alt` is just normal scrolling

## Expected behavior

* horizontally scrolling with mouse wheel is somehow possible
* avoids having to use the scroll bar with the mouse pointer

## Possible solution

* I don't think it's wise to change present/establish functionality but I'd like horizontal scrolling of a table with lots of columns with `shift + mouse wheel`. Since it's already used `alt + mouse wheel` would work as well

## Environment

* **HeidiSQL version:**
    9.5.0.5248
* **Operating system:**
    Windows 10 1709

**Comment by ansgarbecker** [comment]
I'm confused.  Are you sure you did not mix up vertical with horizontal?

**Comment by penCsharpener** [comment]
🤦‍♂️  totally! I will correct it

**Comment by lukinhaspm** [comment]
If you click with the mouse wheel, you can roll to up, down and both sides... your idea to use ctrl or shift will n direction with other mouse wheel functions (like zoon)

**Comment by ansgarbecker** [comment]
<kbd>Alt + MouseWheel</kbd> is indeed unused currently, so I should add that.

Also note, that if a grid has only a few rows fitting to your vertical space, then your mouse wheel already scrolls horizontally. But of course this issue is about scrolling horizontally when there are more rows than the screen has vertical space for.

**Comment by ansgarbecker** [comment]
The next build should work with <kbd>Alt+Mousewheel</kbd> in all grids.

**Comment by penCsharpener** [comment]
wow, that was fast. looking forward to the next nightly.
thanks a lot for this!

**Comment by ansgarbecker** [comment]
> Revision: d60d3f3ea6fd17a43220337da81ae08b87a956c8
> Date: 11.12.2010 08:25:19
> Message: Focus next or previous grid node on Shift+MouseWheel, in all trees. See http://www.heidisql.com/forum.php?t=7269

**Comment by ansgarbecker** [comment]
I'm with you with the "inversing functionality with <kbd>shift</kbd>" argument, as I'm personally also used to that. Probably I should switch the <kbd>Alt</kbd> logic with the <kbd>Shift</kbd> logic. What do you think?

**Comment by penCsharpener** [comment]
Would be my preference as well. But I just read that forum post and if user `AliG` is now pretty used to the way it was that last 7 years then an option in preference would be in order. Default setting would be what it is now since that has a long history and optionally the user can switch around that logic.

**Comment by ansgarbecker** [comment]
To be honest, I don't think many users apart from that forum reporter knows about <kbd>Shift+Mousewheel</kbd>. So I guess switching these is a good idea.
