### ISSUE TITLE
Filtered function list by column type and SQL statement

### ISSUE THREAD

**Issue by WinterSilence** [HeidiSQL/HeidiSQL#1423]
Display functions available for current column(by type) and SQL statement(`CREATE TABLE`).
Also, show brief description for focused function in list.

![изображение](https://user-images.githubusercontent.com/3521094/128629603-07113c75-0fc4-4285-99db-08f1c525fa5a.png)

**Comment by ansgarbecker** [comment]
Please rewrite and use the issue template.
