### ISSUE TITLE
HeidiSQL using wrong SQL statement to rename table in SQLite..

### ISSUE THREAD

**Issue by Glsevans** [HeidiSQL/HeidiSQL#1427]
Currently as of HeidiSQL 11.3.0.6295 when renaming a table within a SQLite Database it issues the SQL Command...
RENAME TABLE existing_table TO new_table; 
Which returns the error... "SQL Error (1) near "RENAME": syntax error"
The correct SQL statement to rename a Table in SQLite is..
ALTER TABLE existing_table RENAME TO new_table;

**Comment by Nononitas** [comment]
I can confirm that

**Comment by ansgarbecker** [comment]
Fixed in the next build.

**Comment by Nononitas** [comment]
Thanks :D
Same is btw for renaming a column
Currently (not working) ALTER TABLE "table" CHANGE COLUMN "current_name " "new_name" <DATATYPE> NOT NULL;

How it should be: ALTER TABLE table_name RENAME COLUMN current_name TO new_name
