### ISSUE TITLE
Add INSERT IGNORE option to export SQL option

### ISSUE THREAD

**Issue by littleearth** [HeidiSQL/HeidiSQL#1429]
**Is your feature request related to a problem? Please describe.**
Insert ignore is brilliant in database exports, would be handy if it was in the  SQL exports dialog

**Describe the solution you'd like**
![HeidiSQL](https://user-images.githubusercontent.com/13463023/129510191-e420e0d8-68f1-4437-bd29-f3b9d9a9055f.png)
Example image attached

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by ansgarbecker** [comment]
I suppose I need to turn these radio buttons into a pulldown menu at some point.

**Comment by Stefano-VLN** [comment]
Speaking of which, what about also an "SQL UPDATE" option?

(If needed, i'll open another issue)

**Comment by Kcko** [comment]
> Done in the next build

excellent!
