### ISSUE TITLE
Missing Zoom functions and indicators

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#143]
## Current behavior

Zoom works very fine on data list, but we haven't this functionality in text/query editor, other problem is we haven't the indicator the zoom in the bottom bar.

## Expected behavior

Zoom in data list and indicator in status bar

## Possible solution

Add capability to zoom in and zoom out in query editor
Add zoom indicator and menu with shortcuts to zoom in/out and back to 100%

**Comment by ansgarbecker** [comment]
Mousewheel function just added. Please update to the latest build and report back if that works as expected.

That zoom indicator is a different issue, you could add a separate ticket for that. Please also with some graphical suggestion for that indicator, and especially where to place it.

**Comment by lukinhaspm** [comment]
Great! Thanks... I will think and try to do some prints what I think its a good idea...

Thanks again!
