### ISSUE TITLE
Decimal separator is not correct when editing cells if using a OS region format with comma separator, causing wrong data to be summited.

### ISSUE THREAD

**Issue by GeeZuZz** [HeidiSQL/HeidiSQL#1433]
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: Percona 5.7.34
* OS: Win 10

**Describe the bug**
When the OS is configured for a region (norwegian e.g) where comma is used as a decimal separator, HeidiSQL will display the numbers using the correct region format. But when editing, if you use a comma, the decimals are ignored when updating. This can cause big problems, since it's very hard to notice that your decimals were ignored during UPDATE. I have multiple times updated the database with incorrect values due to this issue.

It seems to be server dependent. On my Windows MySQL server the UPDATE will fail, with invalid number. On another server (Linux), the value is updated with decimals ignored, as shown in screenshot.

It can be argued, that it does display the . separator when cell is in edit mode and thus shouldn't be a problem if you just edit the selection - but since the text is automatically selected after clicking the cell, the normal behavior is to just start typing the new number, and you won't notice that it expects a dot instead of comma.

**To Reproduce**
1. Use a OS locale/format where decimal separator is used, e.g Norwegian.
2. Click a cell with a decimal number, e.g 176,54
3. Enter new number with a comma, e.g 180,44
4. The number that is submitted to the database is 180,00 - it ignored the decimals.
5. It works as expected if you use dot as separator, but this is not intuitive, since HeidiSQL displays the numbers using comma, according to OS locale setting.

**Screenshots or Crash reports**
Screenshot of behavior:

![comma-bug](https://user-images.githubusercontent.com/6109769/130613776-e8cdd851-141f-4502-a7e3-eb1e0210a453.png)

**Comment by ansgarbecker** [comment]
Editing float/real numbers has to be done in the original format of the value. Formatting the value to the local format and then back to the original for posting the change results in floating point conversion errors, especially when dealing with large numbers, but also randomly on smaller numbers. I'm not able to provide a stable conversion here without changing the value itself, so I'll leave this untouched in order not to break data integrity.
