### ISSUE TITLE
CSV Import Error

### ISSUE THREAD

**Issue by ksorbo** [HeidiSQL/HeidiSQL#1438]
**Preconditions**

* HeidiSQL version: 11.3.6.6295
* Database type and version: Server version: 8.0.25-0ubuntu0.20.04.1 (Ubuntu)
* OS: Ubuntu 20.04

**Describe the bug**

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
No description

**Comment by ksorbo** [comment]
Weird, I typed out all the info, but it didn't save.

Steps:
1. Select import csv
2. Click on the folder icon next to the file name to be imported. Windows folder dialog opens
3. Click on the folder/ directory icon at the top of the dialog
4. Heidi crashes with no message. Just stops

**Comment by ansgarbecker** [comment]
Ok, if the folder dialog crashes I assume it's Wine to blame, or what do you use?

**Comment by ksorbo** [comment]
I am running Heidi on Windows 11, but the mysql server is on linux.
(Connecting through a virtual machine)

**Comment by ansgarbecker** [comment]
Oh your "OS: Ubuntu 20.04" made me think you're using Wine. Anyway.
Could it be that the dialog crashes due to some issue in Win11? Is that a stable version of Win11?

**Comment by jjasoncool** [comment]
Win11 is not stable OS.
And UI have a lots of changes.
I think you can roll-back to win 10.

**Comment by ksorbo** [comment]
Thanks.

So far, I am not having any noticeable problems. I can work around the
issue in HeidiSQL for now.
