### ISSUE TITLE
HeidiSQL is listed as malware by MaxSecure

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1439]
Thought I would share this as MaxSecure lists HeidiSQL as Trojan.Malware.300983.susgen.

![image](https://user-images.githubusercontent.com/359192/132606263-2e86bf0f-97bf-470b-b97f-9c1f17f1fb44.png)

Using the latest Windows App version from Microsoft Store.

**Comment by ansgarbecker** [comment]
Thanks for the info. I just tested heidisql.exe from the v11.3 release, and the current nightly build, both in 64 bit. Both don't show any malware notice. Which build did you test there?

**Comment by timint** [comment]
The build you have on Windows Store is 11.3.0.6295.
It was uploaded by GlassWire to VirusTotal.
![image](https://user-images.githubusercontent.com/359192/132734592-4084de12-8031-42d8-8431-3309b5c5b575.png)

**Comment by ansgarbecker** [comment]
Ok, 32bit, not 64. I just get no such a message there, with the online available build 6295:
https://www.virustotal.com/gui/url/79daf020d44896b0d87589453937cec1fad417662346772244b7d47204d45c8b/detection
I just see MaxSecure is not listed after my upload.

**Comment by timint** [comment]
In your link Quttera marked it as suspicious.
![image](https://user-images.githubusercontent.com/359192/132740893-f7ae0fce-a538-4faf-87d9-debdc236edc7.png)

It's probably nothing nut just annoying.

**Comment by timint** [comment]
Btw, I like it that you published it in Windows App.
I presume it's not possible to get the 64 bit version from there?

**Comment by ansgarbecker** [comment]
I'm sure these are false positives, so I reported that to Quttera: https://quttera.com/quttera-labs

The Microsoft Store version only provides the 32 bit version. Due to much effort for these releases I planned to move to WinGet in the future, which already has some releases: https://github.com/microsoft/winget-pkgs/tree/master/manifests/h/HeidiSQL/HeidiSQL
