### ISSUE TITLE
Missing madExcept.dcu

### ISSUE THREAD

**Issue by G3ph4z** [HeidiSQL/HeidiSQL#145]
## Steps to reproduce this issue

1. Step 1; Clone the source
2. Step 2; Try to compile

## Current behavior
I compiled and installed packages w/o problems.
But when I try to compile the whole project, I get this message:
`[dcc32 Fatal Error] heidisql.dpr(46): F1026 File not found: 'C:\Users\denes\Desktop\HeidiSQL-master\HeidiSQL-master\components\detours\build\Win64\madExcept.dcu'`

The full log:
http://paste.denes.cloud/view/be3dae67#4ZOXWR9C4MRElfSdxOck6NFUNeLJLa6Q

## Environment

* **HeidiSQL:** 
  Latest source code
* **Delphi:** 
  Delphi XE7 Architect
* **Operating system:** 
  Windows 7 x64

**Comment by ansgarbecker** [comment]
You need to install madexcept to get that running. That's it.

**Comment by G3ph4z** [comment]
I realized that and installed just the wrong version, but now its working fine.
