### ISSUE TITLE
Support LATERAL

### ISSUE THREAD

**Issue by InvisibleSmiley** [HeidiSQL/HeidiSQL#1454]
**Is your feature request related to a problem? Please describe.**
HeidiSQL does not recognize the LATERAL keyword

**Describe the solution you'd like**
Understand LATERAL as described here: https://dev.mysql.com/doc/refman/8.0/en/lateral-derived-tables.html

**Comment by ansgarbecker** [comment]
Fixed by f42afad480df36bd5369aac924e2f8b7501144df
See also: #1437
