### ISSUE TITLE
Security warning of insecure use of SQL driver

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1456]
Trying to access Microsoft SQL Server on the local machine results in a security warning.
It appears that SQLOLEDDB is insecure and I am proposed to install Microsoft® OLE DB Driver 18 for SQL Server.

Is it that HeidiSQL is shipped with an old driver? 

![image](https://user-images.githubusercontent.com/359192/136277472-490a8143-5920-46e0-ac1d-762ba258cc7b.png)

Translated:
"Security problem: Using SQLOLEDB ADO provider with unsafe TLS 1.0. You should install Microsoft OLE Driver from https://..."

**Comment by ansgarbecker** [comment]
That security warning is not a bug, it's a warning about insecure TLS version used by that driver. You may use it, HeidiSQL just warns about that.
Please try out the MSOLEDBSQL option in the Library dropdown.
