### ISSUE TITLE
Losing TZ offset from TIMESTAMP values while exporting DB/table from one server to another

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#1457]
**Preconditions**

* HeidiSQL version: 11.3.6337
* Database type and version: MySQL 5.7
* OS: Windows, Linux

**Describe the bug**

When exporting DB/table from one server to another timezone offset in TIMESTAMP values is lost.
For example, if **source** server is in UTC+11 and TIMESTAMP value is '2021-10-07 09:00:00', when the record with the value exported to another server the value will become '2021-10-06 22:00:00'.

IF you export the same data into sql file with HeidiSQL/mysqldump and then import it into another MySQL server using HeidiSQL/mysql CLI, everything will be as it should.

**To Reproduce**

1. 
```
CREATE TABLE `test` (
	`ts` TIMESTAMP NOT NULL,
	`dt` DATETIME NOT NULL
);
INSERT INTO `test` (`ts`, `dt`) VALUES ('2021-10-07 09:00:00', '2021-10-07 09:00:00');
```
2. Check data and notice that values are the same
3. Right click over the `test` table | Export database as SQL | Output: your dest server | Export
4. Check data on the dest server and notice `ts` value lost timezone offset and is different (exact value depend on timezone of your source server, as my source server is in UTC+11, the value become '2021-10-07 09:00:00' - 11 hours = '2021-10-06 22:00:00')
5. Right click over the `test` table | Export database as SQL | Output: 'Single .sql file', key in file name | Export
6. Check the sql file and notice presence of `/*!40103 SET TIME_ZONE='+00:00' */;` line and that `ts` value is stored in UTC (as it should)
7. Import the file into dest server using mysql CLI or HeidiSQL (connect to dest server | drag the file into Query | F9)
8. Check data on dest server and notice that `ts` value is correct. It will be the same if you import into dest server that is in the same timezone or might be a bit different if timezone is different. For example, if I import provided data into server that is in UTC+10, `ts` value will be 1 hour behind: '2021-10-07 08:00:00'.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
If `SET TIME_ZONE...` is fired for reading and writing, shouldn't the times be correct?
See also:
* https://www.heidisql.com/forum.php?t=38078
* 2ea193992c30ab62b0b66a287ba7da88b289dacc
* ee69a049fd909fd25167c4b500e13ed38154dcaf

**Comment by ansgarbecker** [comment]
Fixed in the next build

**Comment by fifonik** [comment]
I do not see anything related to TZ in log (build 11.3.6344), however TIMESTAMP values exported correctly.
Thanks.
