### ISSUE TITLE
MySQL ANY_VALUE() not highlighted and suggested in query editor

### ISSUE THREAD

**Issue by Madjosz** [HeidiSQL/HeidiSQL#1458]
**Preconditions**
* HeidiSQL version: 11.3.0.6343 (64-bit)
* Database type and version: MySQL 8.0.18
* OS: Windows 10 Pro 20H2 build 19042.1237

**Describe the bug**
In the query editor the MySQL aggregation function [`ANY_VALUE()`](https://dev.mysql.com/doc/refman/8.0/en/miscellaneous-functions.html#function_any-value) is not highlighted nor suggested by the content assist.

**To Reproduce**
Enter the query

    SELECT COUNT(1), ANY_VALUE(1)
into the Query editor.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/28844868/136535962-02289541-e42e-41a1-b12b-0ac140ff1c46.png)

**Additional Context**
Pressing `F1` on the function opens the Integrated SQL-help on the correct description page for the `ANY_VALUE` function.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build. I just updated the list of highlighted function names with those from MySQL 8.0.26.
