### ISSUE TITLE
Table filter dropdown with recent searches needs graphical hint

### ISSUE THREAD

**Issue by penCsharpener** [HeidiSQL/HeidiSQL#146]
## Current behavior

text box for database and table filtering doesn't remember search history

## Expected behavior

* the textbox remembers past searches and especially regex filters that potentially took some time to come up with
* restore filter history on application restart

## Possible solution

* turn textbox into a combobox/dropdown that collects recent searches for reuse

If you check out the really great Windows search tool `Everything` (www.voidtools.com) it has this feature (needs turning on first) which adds a search to the history after you leave the filter control. 

## Environment

* **HeidiSQL version:** 
  9.5.0.5253
* **Operating system:** 
  Win10 1709

**Comment by ansgarbecker** [comment]
Perhaps you did not yet click on the left icon in the boxes?

![grafik](https://user-images.githubusercontent.com/7986591/36383955-fb213288-158d-11e8-8e1e-961e2bb6db95.png)

**Comment by penCsharpener** [comment]
no way! How long has that been there? o well, then close the issue and maybe someone else finds it. 

But the icon never invited me to click it. A chevron down would be more obvious but it could just be me.

**Comment by ansgarbecker** [comment]
I'll add some arrow on the left button images. I guess you're not the only one not having seen this.
