### ISSUE TITLE
Export to ZIP file fails when the SQL is > 4GB

### ISSUE THREAD

**Issue by ExactImage** [HeidiSQL/HeidiSQL#1461]
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: MySQL 8
* OS: Windows 10 / Server 2019

**Describe the bug**
Export to compressed ZIP produces a corrupt ZIP file when the SQL file is > 4GB.   If the SQL is exported to the file system then windows used to send to ZIP it works OK.  Could this be a 32 file pointer issue?

**To Reproduce**
Export database as SQL,  Drop & Create checked, Output Zip compressed file.   If the temp SQL is > 4GB the ZIP file is corrupt and too small.    

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
I wasn't aware Delphi's `TZipFile` supports 32bit file sizes only: https://stackoverflow.com/questions/52032211/get-a-decompression-stream-for-a-file-in-a-zip-file
They recommend using https://github.com/ccy/delphi-zip , but that supposedly has other flaws.

**Comment by ansgarbecker** [comment]
I just read the current Delphi compiler has 64bit support in `TZipFile`:
https://www.embarcadero.com/products/rad-studio/whats-new-in-11-alexandria?aldSet=en-GB#tab-whats-new-rtl
![grafik](https://user-images.githubusercontent.com/7986591/152678539-407e2674-4fbc-4237-b721-65ab24a1035d.png)

I'm not yet sure when but I will upgrade to the new compiler at some point, most probably this year.

**Comment by ExactImage** [comment]
Thanks for keeping this on your list.    For now, I'm exporting using the export to folder and using the Windows ZIP tool to zip them.

**Comment by ansgarbecker** [comment]
This is fixed in the latest build, which are compiled with the latest Delphi version with large file support in TZipFile. I just verified that myself, by creating and exporting a 7GB file.

Just be aware the 12.0 release is still broken, you need the very latest build, or wait for v12.1.
