### ISSUE TITLE
Editing aborted when pressing backspace key

### ISSUE THREAD

**Issue by erickcomp** [HeidiSQL/HeidiSQL#1476]
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: MySQL 8.0
* OS: Linux/Wine - wine-5.0.3 (Ubuntu 5.0.3-3+zorin2)

**Describe the bug**

Pressing backspace key when editing anything (table name, column name, column data...) aborts edition and discard all changes.

**To Reproduce**

Try to edit the name of an arbitrary column

**Screenshots or Crash reports**

https://youtu.be/tdWGoPrFTyA

**Comment by xelan** [comment]
Hi! I had the same issue and solved it by upgrading Wine to the latest 6.x staging, currently 6.21.

**Comment by erickcomp** [comment]
Yeah! It really resolved the issue. It's a pitty that my GTK theme did not apply when using wine-staging. But it's a wine's issue. Closing...
Thank you @xelan

**Comment by xelan** [comment]
You're welcome, glad I could help :smiley:
