### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by WHK102** [HeidiSQL/HeidiSQL#1481]
Please, made a linux version for this software. In ubuntu have not a god alternative for database management from ui.

**Comment by ansgarbecker** [comment]
Sorry, but that would be a new project, not a normal task. I have the sources in Delphi and am using Win32 related stuff in wide areas, so it's impossible to convert them in some easy way. One has to do it from the scratch, probably not me.

**Comment by aldenw** [comment]
@WHK102 I too would like a linux native version.  For lack of that, however, you can run it via Wine.  

https://appdb.winehq.org/objectManager.php?sClass=application&iId=3326

I've found that if you follow the version instruction given there, currently that being using version 6.5 of Wine and version 10.x of HeidiSQL that the results are good.  Using the higher versions of HeidiSQL with Wine I did find unstable, so stick with what they recommend.  Or not.  You do you.
