### ISSUE TITLE
Option for disabling instant column search (IncrementalSearch)

### ISSUE THREAD

**Issue by fuxifex** [HeidiSQL/HeidiSQL#1485]
**Is your feature request related to a problem? Please describe.**
When editing, it's very frustrating when the column search will cause the cursor to jump to a different record
(in data view when hitting any key)

**Describe the solution you'd like**
please add the option to the preferences for disabling it

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment]
Duplicate of #1730 - already done for v12.4
