### ISSUE TITLE
Upgrade SQLite3.dll

### ISSUE THREAD

**Issue by magicprinc** [HeidiSQL/HeidiSQL#1486]
**Is your feature request related to a problem? Please describe.**
HeidiSQL uses quite old SQLite3.dll version. The current version is Version 3.36.0 (2021-06-18)

**Describe the solution you'd like**
Simply download and use a new version of SQLite3.dll
https://www.sqlite.org/2021/sqlite-dll-win64-x64-3360000.zip

**Describe alternatives you've considered**
I replaced it locally myself and everything works fine :-)

**Comment by ansgarbecker** [comment]
Already updated in 4900730f2d838d7e57b81f8b70793ef69b356d97
Please either place the newer lib in your HeidiSQL directory, or wait for the next release.

**Comment by magicprinc** [comment]
Just FYI:
1) I have replaced sqlite3.dll with a new one and everything works fine
2) version 3.**37** is already available
PS: Thank You very much for a great tool!
