### ISSUE TITLE
Allow selection of multiple tables in treeview for batch actions

### ISSUE THREAD

**Issue by AntonioCS** [HeidiSQL/HeidiSQL#1488]
**Is your feature request related to a problem? Please describe.**
I need to drop a few tables and there is no way to just multi-select.

**Describe the solution you'd like**
I understand that when the user clicks on a table in the side treeview, HeidiSQL will retrieve some data from that table.
But maybe if the user is pressing the `shift` key (or some other key) then HeidiSQL should just allow to select multiple tables without extracting information and allow for batch actions. In my case it would be Drop selected tables.

**Describe alternatives you've considered**
Creating SQL to drop the tables I want... but then why am I using something like HeidiSQL if I have to type such mundane tasks? 

**Additional context**

**Comment by ansgarbecker** [comment]
This is exactly how it works in the database tab. There are even more things which you can't do in the tree, like sorting e.g.

**Comment by AntonioCS** [comment]
Why can't I do it in the tree view? Why just in the database tab which I barely use... The tree view is always present.
This is bad UX

**Comment by ansgarbecker** [comment]
You cannot do that in many other tools as well. Have a look at the Windows explorer e.g.

**Comment by AntonioCS** [comment]
So you're saying this is a windows limitation?

**Comment by ansgarbecker** [comment]
No, this has nothing to do with Windows, the Explorer was just an example. It's just not practical to have all feature of a list in a tree view. The base construction of the tree is different and the usage is different. The tree is meant for navigating, while the list shows much more details, and has more features.

**Comment by AntonioCS** [comment]
Well... I've been using HeidiSQL for years... and the tree view is the only thing I use to jump around databases/tables and to perform actions on databases/tables, to have to go into another tab to just do something I can partially do in the tree view is extremely disappointing....
I guess I'll just have to remember to go to... wherever.. to do what I want..
