### ISSUE TITLE
HeidiSQL can't export Postgresql database with including option "Create Database"

### ISSUE THREAD

**Issue by jayjupdhig** [HeidiSQL/HeidiSQL#1490]
Hello

I  get a message with "CREATE SHOW DATABASE ... " Error!!

![image](https://user-images.githubusercontent.com/42765391/144083251-645e26a4-f2fd-46aa-9c81-a3688c234517.png)

When i uncheck "Database(s):" -> "Create" [as a workaround], i can reach my goal...

-> "public" is not the database name, it's just the schema. But i think you know that ;-) 

With kind regards,
Jan

**Comment by jayjupdhig** [comment]
-> Selected postgres library .dll is for version 12, but on server (Debian 11) runs version 13

**Comment by jayjupdhig** [comment]
Or Postgresql support is still in beta phase...?

**Comment by jayjupdhig** [comment]
???

**Comment by ansgarbecker** [comment]
Yes, PG support is still unfinished.

**Comment by jayjupdhig** [comment]
Thank you very much for your feedback.

**Comment by mmm8955405** [comment]
A year has passed, and can't you support exporting SQL to PG database?  I still have this problem！

**Comment by electricmessiah** [comment]
So is there any way to export a Postgres database with HeidiSQL yet?
