### ISSUE TITLE
Empty tables with FOREIGN_KEY_CHECKS=0

### ISSUE THREAD

**Issue by AntonioCS** [HeidiSQL/HeidiSQL#1491]
**Is your feature request related to a problem? Please describe.**
I am unable to empty a table that is referenced in another table even though the other table is empty

**Describe the solution you'd like**
Have the possibility to empty tables with: `SET FOREIGN_KEY_CHECKS=0;` and after it's cleared do `SET FOREIGN_KEY_CHECKS=1;`

**Describe alternatives you've considered**
I have to manually run this query:
```
SET FOREIGN_KEY_CHECKS=0;
<TABLE OR TABLES I WANT TO CLEAR>
SET FOREIGN_KEY_CHECKS=1;
```

**Comment by ansgarbecker** [comment]
Related commits: daae16e5834f51ed1370f34ec2e39f757b07d559 and cf6c8e0618a7cf68e64e6574d9bf971890f1daf3

As there are also reasons to keep these foreign key checks, I think I'll add a second menu action "Empty table(s) without foreign key checks", or something like that. This way the user decides, and the prompt can warn the user about orphaned rows in connected tables.

**Comment by AntonioCS** [comment]
@ansgarbecker yes yes apologies if I was not clear.
What would be ideal is if an error pops up, give the user an option to delete with foreign key checks turned off for that `TRUNCATE` and that is it.
Or maybe just something like you are suggesting, where the user explicitly chooses the  "Empty table(s) without foreign key checks"

**Comment by ansgarbecker** [comment]
That empty-table-dialog now has a checkbox for disabling foreign key checks:

![grafik](https://user-images.githubusercontent.com/7986591/155213084-8b35f38e-f7d2-47bd-8590-67e147f03f29.png)

This is only the case in MySQL/MariaDB mode. The queries behind that respect a probably custom value:
```sql
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
TRUNCATE...
SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1)
```

Please update to the next build and verify if that works for you.
