### ISSUE TITLE
Closing Tabs crashes App

### ISSUE THREAD

**Issue by fuxifex** [HeidiSQL/HeidiSQL#1496]
**Preconditions**

* HeidiSQL version: Portable 11.3.0.6370
* Database type and version: 
* OS: Windows 10 home

**Describe the bug**
When having several tabs with queries and closing them by keeping Ctrl-F4 pressed, HeidiSQL will crash - even if the tabs don't contain any query.

**To Reproduce**
open several tabs (no content required), then keep Ctrl-F4 pressed.

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/424315/145072060-0cb2a54f-b299-4c86-8214-1cb417f254e0.png)

**Comment by Kcko** [comment]
I see this error the whole time I use HeidiSQL. I've already learned to live with it, just restart ;-)

**Comment by ansgarbecker** [comment]
Should be fixed in the next build
