### ISSUE TITLE
Show SQL completion proposal no longer suggests functions

### ISSUE THREAD

**Issue by MipamBruiningCalder** [HeidiSQL/HeidiSQL#1498]
**Preconditions**

* HeidiSQL version: 11.3.0.6345
* Database type and version: mariaDB 10.3.16
* OS: windows 10

**Describe the bug**

When writing a query and using SQL completion proposal to find a function name, the list of suggestions remains empty.
Using SQL completion proposal to find column names still works just fine.
This bug was present as of version 11.3.0.6345 and after.
This bug was not present in versions 11.3.0.6344 and before.

**To Reproduce**

1. Place cursor in a "query" tab.
2. type "unix_"
3. press ctrl+space to trigger auto-suggest
4. This is where there used to be 2 function name suggestions but now the suggestions list remains empty
-  "UNIX_TIMESTAMP()" 
- "UNIX_TIMESTAMP(date)

**Screenshots or Crash reports**

![correct_suggestions heidiSQL 11 3 0 6344](https://user-images.githubusercontent.com/46897624/146045756-e66b8925-ef20-4617-8c07-10746d0ace85.png)
![no_suggestions heidiSQL 11 3 0 6345](https://user-images.githubusercontent.com/46897624/146045773-5429d24d-f910-429d-8dd0-2a22b6ca5ee0.png)

**Comment by ansgarbecker** [comment]
I moved these function definitions to separate *.ini files recently. You just need these files to fix that. You can use the latest installer from the [nightly builds section](https://www.heidisql.com/download.php#nightlybuilds) .
