### ISSUE TITLE
Foreign key drop-down support in data grid for MSSQL

### ISSUE THREAD

**Issue by jimtut** [HeidiSQL/HeidiSQL#150]
## Steps to reproduce this issue

1. Step 1; Enable the preference "Show value in foreign key columns"
2. Step 2; Access a SQL Server DB with foreign keys
3. Step N; Open the Data tab and look at a field with a foreign key

## Current behavior

Currently, HeidiSQL shows the original value in the field, not the value that the foreign key points to.

## Expected behavior

HeidiSQL should provide a drop-down list of possible values from the foreign table, similar to how it does for Maria/MySQL.

## Possible solution

The way to query foreign keys is documented by Microsoft, basically:

```
SELECT   
    f.name AS foreign_key_name  
   ,OBJECT_NAME(f.parent_object_id) AS table_name  
   ,COL_NAME(fc.parent_object_id, fc.parent_column_id) AS constraint_column_name  
   ,OBJECT_NAME (f.referenced_object_id) AS referenced_object  
   ,COL_NAME(fc.referenced_object_id, fc.referenced_column_id) AS referenced_column_name  
   ,is_disabled  
   ,delete_referential_action_desc  
   ,update_referential_action_desc  
FROM sys.foreign_keys AS f  
INNER JOIN sys.foreign_key_columns AS fc   
   ON f.object_id = fc.constraint_object_id   
WHERE f.parent_object_id = OBJECT_ID('<tablename>');
```

## Environment

* **HeidiSQL version:** 
  
9.5.0.5253

* **Database system and version:** 
  
MS SQL any version, but tested with SQL Server 2017 Express

**Comment by oegstgeest** [comment]
I just migrated from Windows7/MySQL to Windows10/MSSQL.
It is really disappointing to find the drop-down is missing where it used to be...

**Comment by ansgarbecker** [comment]
Works for me now, please check the next build:

![grafik](https://user-images.githubusercontent.com/7986591/73142047-a409ed80-408a-11ea-9ca1-fd7e78ce9eec.png)

**Comment by oegstgeest** [comment]
Thanks Ansgar,

I just tested it, it looks even better than the previous version!

 

Met vriendelijke groet,

 

Roberto Veldhoven

 

Van: Ansgar Becker <notifications@github.com> 
Verzonden: zondag 26 januari 2020 22:25
Aan: HeidiSQL/HeidiSQL <HeidiSQL@noreply.github.com>
CC: oegstgeest <Roberto.Veldhoven@gmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [HeidiSQL/HeidiSQL] Foreign key drop-down support in data grid for MSSQL (#150)

 

Works for me now, please check the next build:

 <https://user-images.githubusercontent.com/7986591/73142047-a409ed80-408a-11ea-9ca1-fd7e78ce9eec.png>
