### ISSUE TITLE
Query Tabs will close randomly when focusing other tabs

### ISSUE THREAD

**Issue by sommmen** [HeidiSQL/HeidiSQL#1502]
**Preconditions**

* HeidiSQL version: 11.3.0.6376
* Database type and version: 
* OS: Windows 10 (20H2)

**Describe the bug**

Tabs get closed when focusingon other tabs. Tabs also seem to get closed when double clicking.
I'm also not receiving a confirmation for closing tabs which is sad. I Just lost a bunch load of test queries i'm now forced to rewrite.

**To Reproduce**

https://user-images.githubusercontent.com/8641495/147383714-eb1228be-060e-4588-a7a7-ab0e475b1bad.mp4

As a side-note my setup does tend to give double mouse clicks instead of single ones from time to time. I don't think thats related though.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Double on a tab click closes it.
Normally you get a warning when the closing tab has unsaved contents, but you may have disabled that warning in Tools > Preferences:
![grafik](https://user-images.githubusercontent.com/7986591/147386055-b80f6472-441a-4835-a944-ab9e9b09dffb.png)

Is that the case?

**Comment by sommmen** [comment]
> Doubleclick on a tab click closes it. Normally you get a warning when the closing tab has unsaved contents, but you may have disabled that warning in Tools > Preferences: ![grafik](https://user-images.githubusercontent.com/7986591/147386055-b80f6472-441a-4835-a944-ab9e9b09dffb.png)
> 
> Is that the case?

I'll check on that. Regardless that's not the issue; the issue is that the tabs seem to close without me wanting them to close :(

**Comment by ansgarbecker** [comment]
But you said your setup tends to trigger doubleclicks instead of single clicks, which in conjunction with the mentioned setting will close a tab without asking to save.

**Comment by sommmen** [comment]
> But you said your setup tends to trigger doubleclicks instead of single clicks, which in conjunction with the mentioned setting will close a tab without asking to save.

Oh My apologies i read past the first sentence of your earlier message (`Doubleclick on a tab click closes it.`).

You're right the setting was disabled and i've enabled it to be safe.

Is there also a possibility of a setting that could enable/disable this double click to close behaviour?

**Comment by ansgarbecker** [comment]
Yes I was already planning that, see the last comments in #1151

**Comment by sommmen** [comment]
> Yes I was already planning that, see the last comments in #1151

You're a legend! 

I've been loving Heidi so far and will definitely recommend it. Thanks for your efforts!
