### ISSUE TITLE
High DPI support, new attempt to get rid of blurry displaying

### ISSUE THREAD

**Issue by ansgarbecker** [HeidiSQL/HeidiSQL#1503]
**Is your feature request related to a problem? Please describe.**
Running HeidiSQL with scaled screen resolution over 100% is blurry/ugly.

**Describe the solution you'd like**
* add support for high DPI awareness in manifest file
* fix places where storing and restoring component dimensions fails, due to increasing values

**Describe alternatives you've considered**
Keep blurry display - has no store/restore bugs, but looks ugly

This is a duplicate to #213, which I gave up some time ago, now giving it a new try.

**Comment by id0612** [comment]
There was an attempt to support high DPI about 2 years ago, but there were some issues that didn't work out at 4K resolution. In order to ensure normal use, this support was removed. Try again now, and I suggest reviewing the original problem.

[https://github.com/HeidiSQL/HeidiSQL/issues/504](https://github.com/HeidiSQL/HeidiSQL/issues/504)

**Comment by id0612** [comment]
I've probably played with some of the commonly used interfaces, as shown in the picture, where the red arrow points, it would be better to optimize it. I'm sure there are other places like this, but this time it's fine, because of the above problems, after I manually resize it, it will display normally, and when I open the interface again, it will retain the effect after I adjust it. Not much. Thumbs up for you. @ansgarbecker 
![image](https://user-images.githubusercontent.com/2449459/147619783-89a6b41a-df99-4363-9be0-6fd66674e9e7.png)
![image](https://user-images.githubusercontent.com/2449459/147619851-99c8104e-ec65-4753-b9c6-ceff3ef32f05.png)
![image](https://user-images.githubusercontent.com/2449459/147619913-259762b8-41fd-4a83-a143-d2b1f72e78f4.png)
![image](https://user-images.githubusercontent.com/2449459/147619960-c6a4d971-fd7c-4a5d-97d7-5b07827b4298.png)

**Comment by ansgarbecker** [comment]
@id0612 could you please update to the latest build and check what's left now from your point of view? Thanks a lot!

**Comment by id0612** [comment]
> @id0612 could you please update to the latest build and check what's left now from your point of view? Thanks a lot!

I'd be happy to participate. I always use the latest version unless I run into an irresistible problem.

All the known problems have been solved so far. It's perfect. I will keep an eye on it and let you know if I encounter any new problems.

**Comment by id0612** [comment]
@ansgarbecker 
![image](https://user-images.githubusercontent.com/2449459/149309103-ba98e12a-54f6-4980-98ee-4bccd6575d68.png)
In the data table window, the sort options are too small and cannot be adjusted by themselves.

**Comment by ansgarbecker** [comment]
Sorting controls are now scaled in the next build:

![grafik](https://user-images.githubusercontent.com/7986591/149656407-6fdcd07f-9b76-42c3-a02c-626ca1de662e.png)

**Comment by id0612** [comment]
> Sorting controls are now scaled in the next build:
> 
> ![grafik](https://user-images.githubusercontent.com/7986591/149656407-6fdcd07f-9b76-42c3-a02c-626ca1de662e.png)

Yes, it was fixed.
![image](https://user-images.githubusercontent.com/2449459/149687153-1f93baf0-fd5b-46ad-9c47-966cf8888b43.png)

**Comment by id0612** [comment]
@ansgarbecker 
Modify field defaults, dialog box is too small.
![image](https://user-images.githubusercontent.com/2449459/149899515-a875dc66-72cb-431b-83b8-25c5ccf71820.png)

**Comment by id0612** [comment]
![image](https://user-images.githubusercontent.com/2449459/150285190-000aec8c-c4d9-4abf-810c-7fa449589fff.png)

**Comment by ansgarbecker** [comment]
Both the column default editor and the result tabs should be better in the next nightly build.

**Comment by id0612** [comment]
![image](https://user-images.githubusercontent.com/2449459/152628779-89823417-2e32-40c9-a4ee-ab0fcce842c0.png)
![image](https://user-images.githubusercontent.com/2449459/152628800-ab79f6e4-c65c-4171-9b40-5e56e1855df9.png)
There is no expression to choose from, but you can enter it yourself.

**Comment by glen-84** [comment]
It's so nice to see that this is being looked at again. 🙂

Here are a few things that I've noticed:

**Status bar**

![image](https://user-images.githubusercontent.com/261509/152634084-a1e3232b-cdd8-4d48-8826-239cae1d275f.png)

(items are not wide enough)

**Query tabs**

![image](https://user-images.githubusercontent.com/261509/152634128-f50bd7ee-01bb-4ade-9acb-9d7d79f6ef5d.png)

(the editor area is not very tall, and not persisted)

**Open dialogue window**

![image](https://user-images.githubusercontent.com/261509/152634240-02a3094f-9e62-4d17-a455-384c3426cc0c.png)

(tiny icons, encoding field cut off)

**Create database dialogue window**

![image](https://user-images.githubusercontent.com/261509/152634368-e51344cb-9ce2-44bb-a76d-2af0ab7671ac.png)

(might be unrelated, but this window is not being drawn properly)

**Indexes tab**

![image](https://user-images.githubusercontent.com/261509/152634526-806a1d23-c7a0-49ef-8e01-6689e4ae7447.png)

(redraw issue when switching from Options to Indexes tab)

---

Let me know if I should stop sending examples.

**Comment by ansgarbecker** [comment]
@id0612 : the empty drop-down is unrelated. You need some new ini files I recently added for managing function names. Please use the last installer from the nightly build section to get them: https://www.heidisql.com/installers/HeidiSQL_11.3.0.6371_Setup.exe

@glen-84 : 
* I just tried to optimize the status bar panels with real text samples for the next nightly build. Works ok here, please test them with your higher DPI setting.
* the height of the query box is customizable, doesn't HeidiSQL remember the height of it for the next time?
* the small icons in the open-file-dialog are weird - they are drawn by Windows, not by code in HeidiSQL itself. Will have a look at that. At least this is not a Win11 issue, as I have that too here on Win10.
* I suspect the drawing issues in the create-database dialog and the toolbar are related to really high DPI settings. Will check that as well

**Comment by glen-84** [comment]
> I just tried to optimize the status bar panels with real text samples for the next nightly build. Works ok here, please test them with your higher DPI setting.

![image](https://user-images.githubusercontent.com/261509/152653907-ba217b60-fc7d-4c26-aaf9-62361c07228e.png)

Getting better. 😛 I'm surprised that this control doesn't support auto-sizing? Is it custom?

> the height of the query box is customizable, doesn't HeidiSQL remember the height of it for the next time?

Nope. I have two query tabs open (saved). When I restart, the first tab is fine, the second one doesn't even show 3 lines of the query. Is there something that tries to size its height based on the number of lines in the query? (3 in this case)

![image](https://user-images.githubusercontent.com/261509/152654163-cf040b43-4dc6-47aa-9cbf-0bd2abeb1bca.png)

> the small icons in the open-file-dialog are weird - they are drawn by Windows, not by code in HeidiSQL itself. Will have a look at that. At least this is not a Win11 issue, as I have that too here on Win10.

Hmm, are there any options available when opening the dialogue?

> I suspect the drawing issues in the create-database dialog and the toolbar are related to really high DPI settings. Will check that as well

Okay. I'm on 200% scale.

**Comment by ansgarbecker** [comment]
* Status bar now has slightly wider panels
* File-open dialog issues (tiny buttons and cut off encodings) were in Delphi's old implementation of `TOpenTextFileDialog`. Fixed by using a newer `TFileOpenDialog` with a customized encoding selector. Seems to fully support high DPI, and looks exactly like in other apps here:
![grafik](https://user-images.githubusercontent.com/7986591/152681715-9334a38c-2dd0-4a69-bc0d-56b480812fee.png)

**Comment by glen-84** [comment]
> Status bar now has slightly wider panels

![image](https://user-images.githubusercontent.com/261509/152685261-94e62b6d-7fa5-4956-a4aa-54eba8b88ac3.png)

Tight. 🙃

> File-open dialog issues ...

Perfect. 👍

**Comment by ansgarbecker** [comment]
@glen-84 I think I just fixed that issue with too small query tab memos, through 0bbca8e6f7eb629b01bc3c8000e5007d7d932cb1

**Comment by glen-84** [comment]
It does appear to be fixed. 👍Thank you.

**Comment by glen-84** [comment]
I've seen this error twice now, not sure if it's related:

![image](https://user-images.githubusercontent.com/261509/153007195-d4bb4168-e370-4f23-8237-aef86a2f64ed.png)

I have 2 windows open.

**Comment by ansgarbecker** [comment]
> I have 2 windows open.

That's the problem I suppose. I recommend to disable multiple application instances, in Tools > Preferences > General.
Anyway this is not related to high DPI.

**Comment by glen-84** [comment]
The "Search and replace text" dialog has the same issue with drawing the screen:

![image](https://user-images.githubusercontent.com/261509/153626275-5d4bfad4-33ca-4a9e-ab62-ad6b1117f40b.png)

**Comment by ansgarbecker** [comment]
You reported two of these drawing issues, and both happened in a combobox. Both are not reproducible here on Win10.
Do these comboboxes look normal on 100% DPI with Win11? I don't have Win11 here yet for testing.

**Comment by ansgarbecker** [comment]
Just tested that on a Win11 HyperV machine - same bugs with 100% scaling. So this is not DPI related but most likely Win11/compiler related. Will hopefully get fixed with a newer Delphi version.

I'm closing this issue. Further DPI related reports please in separate issues.
