### ISSUE TITLE
Tabs - Size and Rename

### ISSUE THREAD

**Issue by byman64** [HeidiSQL/HeidiSQL#1504]
**Is your feature request related to a problem? Please describe.**
Query Tabs are too size if file name are long and they create confusion.
I also tried to rename a tabs but his size seems not reduced.

**Describe the solution you'd like**
Reducing tabs size cutting file name and showing 3 dots.
On mouse over I would like see the full name.
Renaming a tab I would like see the size reducing and on mouse over see the file name.

**Describe alternatives you've considered**
The above solution would solve my request.

**Additional context**
HIDI SQL INFO
- Version 11.3.0.6358 (64 bit) portable
- Compiled on 2021-10-20 05:55:16
- Enviroment proposed by Heidi is wrong: mine is Windows 11 

![Heidi SQL](https://user-images.githubusercontent.com/2996260/147410433-def1cca6-df22-4720-8dd0-8a6e92055aaa.jpg)

**Comment by ansgarbecker** [comment]
Please post a screenshot, and version details.

**Comment by ansgarbecker** [comment]
This is fixed, already in an older release.
