### ISSUE TITLE
Broken link in confirmation dialog when closing an unsaved query

### ISSUE THREAD

**Issue by Aviat0r93** [HeidiSQL/HeidiSQL#1506]
**Preconditions**
* HeidiSQL version: 11.3.0.6295
* Database type and version: MySQL 8.0.27 (doesn't matter)
* OS: Windows 10 (doesn't matter)

**Describe the bug**
The hyperlink to open the SQL file within the close confirmation dialog message is broken when the path or the filename itself contains a space.

**To Reproduce**
1. Open a new query and save it to a directory containing a space or use a filename which contains a space (e.g. C:\Test Directory\Query.sql)
2. Change the query text and close the tab without saving (either by closing the whole application or only that single tab)
3. The hyperlink is broken and can't be clicked whereas with a directory/filename which doesn't contain a space it's possible.

**Screenshots or Crash reports**

**Broken link**
![heidisql_2021-12-29_22-44-45](https://user-images.githubusercontent.com/35074445/147706026-3fede315-266d-4f2a-9282-e34252af06c0.png)

**Working link**
![heidisql_2021-12-29_22-48-31](https://user-images.githubusercontent.com/35074445/147706036-2d825a13-ace2-426a-b923-0032a108dabd.png)

**Comment by ansgarbecker** [comment]
Fixed by 210f056c472ba8e08d0eabaa7b789511052a0a57
