### ISSUE TITLE
Overflow while converting variant of type (Decimal) into type (Currency)

### ISSUE THREAD

**Issue by VitalySR** [HeidiSQL/HeidiSQL#151]
## Steps to reproduce this issue

1. Open MS SQL Server;
2. Select table;
3. Click to page "Data";

## Environment
Table has columns with type Decimal(18,2) null

* **HeidiSQL version:** 
  9.3.0.4984 Portable
* **Database system and version:** 
  SQL Server 2014 SP2 (12.0.5000)
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1747363/bugreport.txt)

**Comment by rentalhost** [comment]
Please, could you try run that issue on last nightly version?

**Comment by VitalySR** [comment]
I try 9.5.0.5254 - error repeated.

[bugreport_9.5.0.5254.txt](https://github.com/HeidiSQL/HeidiSQL/files/1757597/bugreport_9.5.0.5254.txt)

**Comment by priyank1508** [comment]
I too am facing this issue. Do we have any insight into resolving this?

Alternatively, Is there any additional information that is required to aid resolution?

**Comment by swiffer** [comment]
still facing this issue from the latest nightly

MSSQL DDL
```sql
CREATE TABLE dummy (
	"FIELD" DECIMAL(17,0) NULL DEFAULT NULL
)
```

https://www.heidisql.com/forum.php?t=23698
https://www.heidisql.com/forum.php?t=17218
https://sourceforge.net/p/heidisql/tickets/2570/

**Comment by ansgarbecker** [comment]
Closing this in preference of the newer report #890  with more details
