### ISSUE TITLE
Support for MySQL 8 descending indexes

### ISSUE THREAD

**Issue by dcelasun** [HeidiSQL/HeidiSQL#1512]
**Is your feature request related to a problem? Please describe.**
As of 12.0.0.6468, HeidiSQL does not support creating, viewing, or modifying descending indexes. Modifying an existing descending index is destructive; i.e. the order is removed.

**Describe the solution you'd like**
Descending indexes should be supported.

**Comment by ansgarbecker** [comment]
I just added some basic support for a direction in index parts, which can be edited per dropdown. HeidiSQL won't yet check if the server is capable of using DESC - so the ALTER query will fail on older servers.
Note you probably need to make the new column visible to edit it, via rightclick on the column header.

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/33f8908b-ec1e-43a2-9cbe-30ecc5d441e4)

Please test and give feedback.

**Comment by marcelhaase** [comment]
Hello @ansgarbecker,

Thank you very much  for the quick feedback and the basic support for that feature 👍 
Is it right that I have to wait for a new version to test this?

**Comment by ansgarbecker** [comment]
Yes, forgot to say, the builds are compiled once in a while only. But it's already there now, so you can update per _Help > Check for updates > Download and install build xyz_.

**Comment by tscheifler** [comment]
I'm currently using version 12.10.0.7027 (windows).
I do not see the "Direction" attribute for index fields.

![Image](https://github.com/user-attachments/assets/47b815b4-5dfe-4c66-9469-33b243c1277f)
