### ISSUE TITLE
Warning message through SmartScreen after download on Win8/10

### ISSUE THREAD

**Issue by ansgarbecker** [HeidiSQL/HeidiSQL#152]
## Steps to reproduce this issue

1. download HeidiSQL installer or build using any webbrowser
2. try to execute it

## Current behavior

a fat warning message, saying that the downloaded file has no certificate

## Expected behavior

no warning, but a nice dialog telling who's the certified author

## Possible solution

Buy an AuthentiCode certificate, and sign the exe files with Microsoft's sign tool.
Previously, I bought one from Certum.pl as it was cheap, but now you need some hardware to generate the keys. Probably it's easier to buy a certificate anywhere else. Alternatives should be gathered here so I can compare them.

## Environment

* **HeidiSQL version:** v9.5, any build
  
* **Operating system:** Win10, probably also Win8

**Comment by ansgarbecker** [comment]
Here's the forum thread where I installed the first certificate: https://www.heidisql.com/forum.php?t=19857

**Comment by ansgarbecker** [comment]
Here are some recommendations which I received from various users:
* https://cheapsslsecurity.com/sslproducts/codesigningcertificate.html
* https://ssl.comodo.com/free-ssl-certificate.php?track=8256&s_track=7639
* https://letsencrypt.org/ (won't work, as they don't support AuthentiCode yet)
* https://www.godaddy.com/web-security/code-signing-certificate
* http://www.cacert.org/

**Comment by ElectronicWar** [comment]
https://ssl.comodo.com/free-ssl-certificate.php?track=8256&s_track=7639 is only a SSL cert, not for code signing
http://www.cacert.org/ has their root certificate not in the official Windows root cert list, the user would need to install and trust it first.

**Comment by CodehunterWorks** [comment]
There are some threads about code signing in the DelphiPraxis.net. Finally, it is a question of effort and benefit. A corresponding certificate costs ~ 90 Euro per year. HeidiSQL is a free software, in which the authors already invest their spare time. I think you can live well with the certificate warning in Windows 10. If MS requires certified installers at some point, we need to rethink this. But until then, it can stay the same because of me.

**Comment by ansgarbecker** [comment]
Things I found out so far:
* Win10 and Win11 require an extended validation (EV) certificate, the cheaper OV certificates are not accpted:
![grafik](https://user-images.githubusercontent.com/7986591/158010635-96cc18ce-96f7-4f64-8b69-22dcebf23854.png)

* These EV certificates start around 200€ up per year.
* Most if not all of the EV certificates require a USB token (smart card) which needs to be connected to the physical machine when signing an executable
* Each sign process prompts for a password for the USB token

While the costs are absolutely fine for me, the requirement for that USB token and a password prompt is a no-go for my automatic build process on my remote server.
I wonder how other OpenSource or free applications handle such an effort.

**Comment by CodehunterWorks** [comment]
Code signing is a "cheap" solution for the closed source universe. This was one of the causes why I'm left the Windows ecosystem for my hobby projects some years ago.

The best answer to Microsoft about the EV issue is: Use Linux ^^ Why not migrate to FPC/Lazarus and make HeideSQL platform-independent? I know this does not solve the SmartScreen issue on Windows. But each software project which turns from Windows-only to platform independent is a little needle prick to Microsoft. ;-)

**Comment by ansgarbecker** [comment]
I just stumbled about a [blog post](https://docs.microsoft.com/en-us/archive/blogs/ie/microsoft-smartscreen-extended-validation-ev-code-signing-certificates#-windows-store--windows-8-apps) from Microsoft, which says an app in the MS Store does not need any code signing certificate, basically because it already went through a validation process. Probably that's an alternative. I already have that validation process behind me, I would just need to create a 64bit version of HeidiSQL additionally to the existing 32bit version.

**Comment by ansgarbecker** [comment]
Release 12.0 now has an OV certificate, which needs some reputation before it can remove the SmartScreen warning.

I leaft my idea with moving to the Microsoft Store behind, as the DesktopAppConverter is no longer working. Developers are forced to use the MSIX Packaging Tool, which makes it again unclear how to add certificates. I think I should remove the store version, which is already old now.
