### ISSUE TITLE
Using MariaDB 10.6 HeidiSQL does not show partitions

### ISSUE THREAD

**Issue by tkn777** [HeidiSQL/HeidiSQL#1521]
**Preconditions**
* HeidiSQL version: 11.3.6295
* Database type and version: MariaDB 10.6
* OS: Windows 10 (latest)

**Describe the bug**
Partitions are not shown. Not in the 'Partition' tab, not in the tab 'CREATE code'.

**To Reproduce**
1. Create a table with partitioning with MariaDB 10.6 (see the comments for an example)
2. Goto tabs 'Partitions' and 'CREATE code'
3. Partitions are not shown there

**Screenshots or Crash reports**
n/a

**Comment by tkn777** [comment]
Example table:

CREATE TABLE `foo` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `field1` decimal(10,4) NOT NULL,
  `field2` varchar(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
 PARTITION BY RANGE (`id`)
(PARTITION `p1` VALUES LESS THAN (1000) ENGINE = InnoDB,
 PARTITION `p2` VALUES LESS THAN (2000) ENGINE = InnoDB,
 PARTITION `p3` VALUES LESS THAN (3000) ENGINE = InnoDB)

**Comment by ansgarbecker** [comment]
Related to #187

**Comment by ansgarbecker** [comment]
Next nightly builds have a smarter expression for detecting a partition clause in the `CREATE TABLE` code, which should work both in MySQL and MariaDB.
Note the generated `CREATE CODE` wraps this clause in a version conditional comment, to prevent issues on old servers:

![grafik](https://user-images.githubusercontent.com/7986591/164646850-8acf704a-cf61-430a-9dff-222a5a180b0f.png)

This is still very basic, and the detection may be tricked out by subsequent clauses after the `PARTITION` clause. But there is #187 which should once make partition support more complete.

**Comment by tkn777** [comment]
Thanks. That is very helpful! :)
