### ISSUE TITLE
Update SQLite library

### ISSUE THREAD

**Issue by momt99** [HeidiSQL/HeidiSQL#1526]
**Is your feature request related to a problem? Please describe.**
Some new great features are added to SQLite in recent versions such as support for `DROP COLUMN`. But as HeidiSQL is using version 3.34 of it by default, they are not available and causing problems like #1408. By the time of writing this, version 3.37.2 is released.

**Describe the solution you'd like**
Update the library version included in the package.

**Describe alternatives you've considered**
I downloaded the latest dll from SQLite's official website and it worked just fine.

**Additional context**

**Comment by momt99** [comment]
Duplicate of #1486.

But I wonder why it is not included in the installation package 🤔.

**Comment by ansgarbecker** [comment]
It's been some time ago since I created a new official release, and the update dll is newer than the last one. But the installer from the [nightly builds section](https://www.heidisql.com/download.php#nightlybuilds) have that update.
