### ISSUE TITLE
Grid resuts hidden

### ISSUE THREAD

**Issue by fredericoregateiro** [HeidiSQL/HeidiSQL#1527]
**Preconditions**

* HeidiSQL version: 11.3.0.6407
* Database type and version: mariadb 10.3.27
* OS: win10

**Describe the bug**

The grid results is missing, and i don't know how to make it visible again. 
Maybe there is a way to re enable again, but i couldn't find it.

I use two monitors with different resolutions, and moving to other monitor cause the grid results to disappear, but now it not working on any monitor.

The forum would be a better place for this question, but i didn't want to register to yet another forum, and maybe a discussion tab where on github would be a better place for this questions.

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Try the following:
* exit all heidisql instances
* start regedit.exe
* navigate to `HKEY_CURRENT_USER\SOFTWARE\HeidiSQL`
* delete values `MemoEditorHeight` and `sqloutheight`
* restart HeidiSQL

If that's not helping out, you should post a screenshot so I can see what's wrong.

**Comment by fredericoregateiro** [comment]
I've deleted the `sqloutheight` but i didn't found the `MemoEditorHeight`  the grid results doesn't show yet.

![image](https://user-images.githubusercontent.com/6304701/152877757-7d2b69d8-385c-4d1c-815c-da8cc04d8b5f.png)

**Comment by ansgarbecker** [comment]
I just refactored some code which resets the height of query tabs and log panel in such cases. Please update to the next nightly build, available in a few minutes.

**Comment by fredericoregateiro** [comment]
@ansgarbecker  I've justupdated and it work good now. Thanks
