### ISSUE TITLE
Grid results hidden

### ISSUE THREAD

**Issue by fredericoregateiro** [HeidiSQL/HeidiSQL#1528]
@ansgarbecker  I've deleted the `sqloutheight` but i didn't found the `MemoEditorHeight`  the grid results doesn't show yet.

![image](https://user-images.githubusercontent.com/6304701/152877757-7d2b69d8-385c-4d1c-815c-da8cc04d8b5f.png)

_Originally posted by @fredericoregateiro in https://github.com/HeidiSQL/HeidiSQL/issues/1527#issuecomment-1031967571_

**Comment by ansgarbecker** [comment]
Keep comments in the original issue please. Wildly opening new ones for each comment makes it impossible to understand the issue.

**Comment by fredericoregateiro** [comment]
> Keep comments in the original issue please. Wildly opening new ones for each comment makes it impossible to understand the issue.

Yes, I've opened this one because i could not reopen the other one, and commenting a closed issue just feld stange :D
