### ISSUE TITLE
SSH tunnel using klink.exe broken

### ISSUE THREAD

**Issue by Frank071** [HeidiSQL/HeidiSQL#1529]
The introduced support for OpenSSH has broken support for native use of the Kitty flavour of Putty. Until that commit one could perfectly put the link to the klink.exe executable as 'plink location', but now there is a stringent check whether the word 'plink' is part of that link:

https://github.com/HeidiSQL/HeidiSQL/blob/98c69fa2ed08462b79d856dd28b1bd0111aa729a/source/dbconnection.pas#L1088

If not then (later in the code) the port parameter uses a lower case p, which causes klink (and probably other Putty flavours) to bail out with an error. I, for one, would very much welcome the IsPlink check to include a check for klink as well, or turn the check the other way around and check for the mention of 'ssh' in the string (IsSSH).

**Comment by ansgarbecker** [comment]
I prefer to keep `IsPlink`, just widening the detection to variants like "klink" and "putty". Next build should do that.
