### ISSUE TITLE
Multiple selects don't label correctly several tabs

### ISSUE THREAD

**Issue by CMMoreira** [HeidiSQL/HeidiSQL#1530]
**Preconditions**

* HeidiSQL version:11.3.0.6408
* Database type and version:
* OS: Windwos 10

**Describe the bug**

Multiple selects don't label correctly several tabs below.

**To Reproduce**
Example:
1. select * from item
2. Select * from family
3. Results are placed in 2 tabs, and both are with the same name.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
I suppose you're on MS SQL?
You need to separate queries with a semicolon, then the server responds with different table names.

**Comment by CMMoreira** [comment]
Yes. Ms Sql. Could it be automatically without semicolon? 

Enviado do Yahoo Mail para Android 
 
  Em qua, 9 fev, 2022 às 18:58, Ansgar ***@***.***> escreveu:   


I suppose you're on MS SQL?
You need to separate queries with a semicolon, then the server responds with different table names.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ansgarbecker** [comment]
No, I think the missing semicolon is exactly the issue.
