### ISSUE TITLE
Reformat SQL does not recognize hash char (#) in strings

### ISSUE THREAD

**Issue by bisteris** [HeidiSQL/HeidiSQL#1534]
**Preconditions**

* HeidiSQL version: 11.3.0.6411
* Database type and version: MariaDB 10.4.22
* OS: Windows 10

**Describe the bug**

If the # character is in a string, the following sql is not considered

**To Reproduce**

SELECT '#' FROM config
return
SELECT '#' FROM config
instead of:
SELECT '#' 
FROM config

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Thinking this is outdated, with the new reformatter options for #750 . Result is now:

```
SELECT '#'
FROM config
```
