### ISSUE TITLE
Reformat SQL does not recognize STRAIGHT_JOIN clausole

### ISSUE THREAD

**Issue by bisteris** [HeidiSQL/HeidiSQL#1535]
**Preconditions**

* HeidiSQL version: 10.3.0.6411
* Database type and version: MariaDB 10.4.22
* OS: Windows 10

**Describe the bug**

STRAIGHT_JOIN clausole should be regarded as JOIN clausole

**To Reproduce**

Using the clean JOIN clausole a query like this:
```
SELECT 1.id FROM a JOIN b ON a.id=b.id
```

become:
```
SELECT 1.id
FROM a
JOIN b ON a.id=b.id
```

Using the STRAIGHT_JOIN clausole this is not considered:
```
SELECT 1.id FROM a STRAIGHT_JOIN b ON a.id=b.id
```

become:
```
SELECT 1.id
FROM a STRAIGHT_JOIN b ON a.id=b.id
```

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
I think this is fixed meanwhile. Using the reformatter from sqlformat.org, a straight join looks nice in the output:

```
SELECT 1.id
FROM a
STRAIGHT_JOIN b ON a.id=b.id
```
