### ISSUE TITLE
Make filter textarea resizable

### ISSUE THREAD

**Issue by savissimo** [HeidiSQL/HeidiSQL#1536]
**Is your feature request related to a problem? Please describe.**
I often use the Data tab when inspecting a table, and I use the filter area for quick queries. However, when the filter gets long, I am limited by the size of the input area, that lets me see just a couple of lines when there are recent filters, and I cannot resize it to make it bigger. 

**Describe the solution you'd like**
The Filter area should be resizable. 

**Describe alternatives you've considered**
No real workaround. 

**Additional context**
None

**Comment by ansgarbecker** [comment]
dc408630fc5251a7fe564899ada34df646ca2098 also belongs here.

The filter area now auto-resizes the height to prevent the vertical scrollbar until a maximum of 8 lines are reached. I could imagine making this maximum user configurable.

![data-filter-autosize](https://user-images.githubusercontent.com/7986591/201535481-e81796d8-f30e-4417-82d7-67c69b2d0b3a.gif)

I preferred an automatism over a splitter for several reasons:
* the user does not have to hassle with the mouse here
* a tried to add a horizontal splitter, but that was always appearing at the wrong place. Splitters can be very tricky, as they need alignment.
