### ISSUE TITLE
MySQL v8 fails with SSL; latest connector plugin fixes

### ISSUE THREAD

**Issue by imgrant** [HeidiSQL/HeidiSQL#1539]
### **Preconditions**

* **HeidiSQL version**:  `11.3.0.6413 (64-bit)`
* **Database type and version**: MySQL/MariaDB `8.0.26` (DigitalOcean hosted managed database cluster)
* **OS**: Windows 11 

### **Describe the bug**

Access is denied when using SSL mode in HeidiSQL. Identical connection parameters work from, e.g. mysql CLI.
Disabling SSL in HeidiSQL connects fine.
The connection was configured for basic "one-way" SSL; that is, no private key, certificate, CA certificate was used. The SSL cipher parameter was left empty (default).

### **To Reproduce**

1. Create a **MariaDB or MySQL (TCP/IP)** connection in HeidiSQL (using `libmariadb.dll`)
2. Fill in the connection details (hostname, port, user, etc), in this case using the values supplied from the DigitalOcean dashboard
3. Ensure the IP address you are connecting from is an allowed source in the DigitalOcean settings (i.e. the firewall will allow the connection)
4. Click on the SSL tab, check '**Use SSL**', leave the four parameter fields empty
5. Click 'Open'
6. Observe the error message, "`Access denied for user '<username>'@'<IP address>' (using password: YES)`"
7. Try the connection using the MySQL command line client: `mysql -h <hostname> -P <port> -u <username> -p --ssl`
8.  Enter the password when prompted, observe that the connection is successful
9. Try HeidiSQL without SSL by unchecking '**Use SSL**' on the SSL tab for the connection
10. Observe the connection works (but note that it is *NOT* using SSL (e.g. `SHOW STATUS LIKE 'Ssl_version'` is blank, it should say, e.g. `TLSv1.3`)

### **Screenshots or Crash reports**

I debugged the connection attempt using Wireshark. For HeidiSQL, the login request step (before TLS is negotiated) appears to show the "`Plugin Auth LENENC Client Data`" extended client capabilities is not set (bit is `0`). e.g.:

```
MySQL Protocol
    Packet Length: 32
    Packet Number: 1
    Login Request
        Client Capabilities: 0xae85
            .... .... .... ...1 = Long Password: Set
            .... .... .... ..0. = Found Rows: Not set
            .... .... .... .1.. = Long Column Flags: Set
            .... .... .... 0... = Connect With Database: Not set
            .... .... ...0 .... = Don't Allow database.table.column: Not set
            .... .... ..0. .... = Can use compression protocol: Not set
            .... .... .0.. .... = ODBC Client: Not set
            .... .... 1... .... = Can Use LOAD DATA LOCAL: Set
            .... ...0 .... .... = Ignore Spaces before '(': Not set
            .... ..1. .... .... = Speaks 4.1 protocol (new flag): Set
            .... .1.. .... .... = Interactive Client: Set
            .... 1... .... .... = Switch to SSL after handshake: Set
            ...0 .... .... .... = Ignore sigpipes: Not set
            ..1. .... .... .... = Knows about transactions: Set
            .0.. .... .... .... = Speaks 4.1 protocol (old flag): Not set
            1... .... .... .... = Can do 4.1 authentication: Set
        Extended Client Capabilities: 0x80df
            .... .... .... ...1 = Multiple statements: Set
            .... .... .... ..1. = Multiple results: Set
            .... .... .... .1.. = PS Multiple results: Set
            .... .... .... 1... = Plugin Auth: Set
            .... .... ...1 .... = Connect attrs: Set
            .... .... ..0. .... = Plugin Auth LENENC Client Data: Not set
            .... .... .1.. .... = Client can handle expired passwords: Set
            .... .... 1... .... = Session variable tracking: Set
            .... ...0 .... .... = Deprecate EOF: Not set
            1000 000. .... .... = Unused: 0x40
        MAX Packet: 1073741824
        Charset: latin1 COLLATE latin1_swedish_ci (8)
        Unused: 0000000000000000000000000000000000000000000000
        Username: 
```

For a connection that works from the MySQL CLI, that data _is_ present (bit is set to `1`):

```
MySQL Protocol
    Packet Length: 32
    Packet Number: 1
    Login Request
        Client Capabilities: 0xae85
            .... .... .... ...1 = Long Password: Set
            .... .... .... ..0. = Found Rows: Not set
            .... .... .... .1.. = Long Column Flags: Set
            .... .... .... 0... = Connect With Database: Not set
            .... .... ...0 .... = Don't Allow database.table.column: Not set
            .... .... ..0. .... = Can use compression protocol: Not set
            .... .... .0.. .... = ODBC Client: Not set
            .... .... 1... .... = Can Use LOAD DATA LOCAL: Set
            .... ...0 .... .... = Ignore Spaces before '(': Not set
            .... ..1. .... .... = Speaks 4.1 protocol (new flag): Set
            .... .1.. .... .... = Interactive Client: Set
            .... 1... .... .... = Switch to SSL after handshake: Set
            ...0 .... .... .... = Ignore sigpipes: Not set
            ..1. .... .... .... = Knows about transactions: Set
            .0.. .... .... .... = Speaks 4.1 protocol (old flag): Not set
            1... .... .... .... = Can do 4.1 authentication: Set
        Extended Client Capabilities: 0x60ff
            .... .... .... ...1 = Multiple statements: Set
            .... .... .... ..1. = Multiple results: Set
            .... .... .... .1.. = PS Multiple results: Set
            .... .... .... 1... = Plugin Auth: Set
            .... .... ...1 .... = Connect attrs: Set
            .... .... ..1. .... = Plugin Auth LENENC Client Data: Set
            .... .... .1.. .... = Client can handle expired passwords: Set
            .... .... 1... .... = Session variable tracking: Set
            .... ...0 .... .... = Deprecate EOF: Not set
            0110 000. .... .... = Unused: 0x30
        MAX Packet: 16777216
        Charset: utf8 COLLATE utf8_general_ci (33)
        Unused: 0000000000000000000000000000000000000000000000
        Username: 
```

### **Suggested resolution**

I downloaded the latest MariaDB connector (version `3.2.5-GA`), and copied the `caching_sha2_password.dll` plugin file to the HeidiSQL plugins directory; the SSL-enabled connection then worked fine in HeidiSQL 🥳
Wireshark also then showed that the `Plugin Auth LENENC` bit was being correctly set for the connection.
So maybe Heidi just needs the updated plugin?

**Comment by ansgarbecker** [comment]
First thanks for the very deep look and your hint! Makes it really easier to fix things.

I updated all plugin libraries and libmariadb.dll to the currently available GA release. If you say that the update helps it's definitely worth it. The fresh installer on the download page has these updates: https://www.heidisql.com/installers/HeidiSQL_11.3.0.6414_Setup.exe

Additionally, I activated `CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA` for all MySQL/MariaDB connections. That is one of the newer constants which I did not yet have in HeidiSQL. That way you even don't need the newer plugins, likely, only the new heidisql build.

**Comment by ansgarbecker** [comment]
By the way, that `CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA` is documented [here](https://dev.mysql.com/doc/internals/en/capability-flags.html#flag-CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA):

> Length of auth response data in [Protocol::HandshakeResponse41](https://dev.mysql.com/doc/internals/en/connection-phase-packets.html#packet-Protocol::HandshakeResponse41) is a length-encoded integer.

**Comment by imgrant** [comment]
I can confirm `11.3.0.6414` works as expected! Thanks for the quick fix, & glad I could help.
