### ISSUE TITLE
Binary Garbage in Binary Foreign Key Selection (Rather than HEX)

### ISSUE THREAD

**Issue by broady02** [HeidiSQL/HeidiSQL#1540]
**Preconditions**

* HeidiSQL version: 11.0.0.5919
* Database type and version: MariaDB 10.6
* OS: Windows 10

**Describe the bug**

* Foreign Key dropdown selection box, on column type Binary, has options displayed as text rather than hex.
* Fields in the table display appropriately as per the Text/Hex toggle in the menu.
* Dropdown selection on Binary Foreign Key does not obey this (making selection difficult).

**To Reproduce**
1. Create a table1 with a Binary Primary Key
2. Insert some rows of random binary data
3. Create table2, with Binary Foreign key of table1
4. Insert some rows, making use of dropdown selection
5. Notice that items cannot be shown in hex, and garbage characters are displayed for selection.

**Screenshots or Crash reports**
![image](https://user-images.githubusercontent.com/46899440/153838262-4f3b1b67-92f6-4b5f-a903-1a51f102be4c.png)

**Comment by ansgarbecker** [comment]
Next build works with hex values in that pulldown menu:

![grafik](https://user-images.githubusercontent.com/7986591/156387945-e3a47d0d-e0c1-418b-b4c8-17d88f89e531.png)
