### ISSUE TITLE
DNS lookup/cache error

### ISSUE THREAD

**Issue by Gehrt-IT** [HeidiSQL/HeidiSQL#1544]
**Preconditions**

* HeidiSQL version: 11.1.0.6116
* Database type and version: mysql(galera) version 10.6.7
* OS: 10 64 bit

**Describe the bug**

When trying to connect with hostname the ipv6 adresse gets looked up through DNS. The result however is wrong. Connection therefor fails. nslookup reveals that DNS resolution is working correctly, just heidisql is mixing things up

**To Reproduce**

try connecting to several ipv6 hosts using hostnames. it works for some, doesnt for other.

**Screenshots or Crash reports**

![connection_LI](https://user-images.githubusercontent.com/63617342/155516978-dccd0ad8-eed8-4322-aabd-7cdeadddd6a2.jpg)
![nslookup](https://user-images.githubusercontent.com/63617342/155516999-286ac79a-bb69-443d-93c5-9efd104ca22c.JPG)

**Comment by ansgarbecker** [comment]
This is a misinterpretation of the error message
> Access denied for user 'xyz'@'ip-address'
That ip address is yours, not the one from the server you want to connect to.

The access denied error can be fixed in the user privileges on the server. Either "testuser" is defined with a non-matching host/ip, or the password is just wrong.
