### ISSUE TITLE
MariaDB 10.7 UUID datatype

### ISSUE THREAD

**Issue by surcoufx83** [HeidiSQL/HeidiSQL#1545]
**Is your feature request related to a problem? Please describe.**
Maria DB has introduced the new data type UUID (like PostgreSQL) in version 10.7 (see https://mariadb.com/kb/en/uuid-data-type/). On version 11.3.0.6423 of Heidi SQL I'm not able to select UUID in the column data type when creating or updating a table. Maria DB server is 10.7.3 and connection to the db is established with libmariadb.dll.

**Describe the solution you'd like**
Add the UUID datatype to the create / update table wizard for databases on Maria DB >= 10.7

Thank you

**Comment by cyraid** [comment]
I was hoping I'd find some sort've solution but I guess this is still open.

**Comment by ItsANoBrainer** [comment]
+1

**Comment by ansgarbecker** [comment]
Next nightly build detects such UUID columns correctly.
