### ISSUE TITLE
Query Editor Improvement

### ISSUE THREAD

**Issue by haruncetin** [HeidiSQL/HeidiSQL#1546]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

It doesn't see "execute immediate" statement for mysql in query editor. It can be useful to add.

**Comment by ansgarbecker** [comment]
Please edit your report, and describe that more detailed. I have no clue what that "execute immediate" should do and how that should look like.
