### ISSUE TITLE
From table with foreign keys, open other table with row selected

### ISSUE THREAD

**Issue by Mondane** [HeidiSQL/HeidiSQL#156]
## Steps to reproduce this issue

Not implemented yet.

## Current behavior

Not implemented yet.

## Expected behavior

- Connect to a server
- Select a database
- Select a table and optional apply some filters
- ctrl+click the value in a cell which has a foreign key
- open the foreign table with the associated row selected

This makes it easier to look through the data.

Combined with #155 , the other table could be opened in a new tab (optionally when doing ctrl+shift+click).

## Possible solution

n/a

## Environment

Ubuntu 16.04

* **HeidiSQL version:** 
9.5.0.5196

**Comment by WesleyM77** [comment]
This would speed up my workflow substantially and be insanely useful.

**Comment by markdza** [comment]
Agreed. Let's make it happen please! It was originally requested more than [3 years ago](https://www.heidisql.com/forum.php?t=20427).

**Comment by Ivan-Perez** [comment]
If this is implemented and one table and its data is shown at a time (like it is now), a back button to return to the previous table would be something nice to have.

**Comment by albertotn** [comment]
I like this feature a lot to speed up data navigation, as reference see this: https://github.com/dbeaver/dbeaver/wiki/Navigation#navigate-foreign-keys--referencing-tables

**Comment by ferenczy** [comment]
How does it look with this request, please? It's being opened for 3 years already. Is it being considered? Is it waiting in any queue and is it possible to see such queue?

**Comment by RoDoerIng** [comment]
Heidi is a great tool which I use on a daily basis. The only thing I'm really missing is the Ctrl + Klick - Navigation to the foreign table/entity. Please consider adding this feature.

**Comment by dungsaga** [comment]
I'm working on a new feature that allow the user to follow foreign key to the reference table and filter to show only rows linked from the current row (https://github.com/HeidiSQL/HeidiSQL/pull/1571). Since I'm not familiar with Delphi and Pascal, there is a problem I can't resolve now.

I'm trying to set the filter after switching to the reference table from the foreign key. But the filter text only appears in Recent filters. I guess there's something that load the filter text from filter history whenever I switch to another table.

Here's the code I wrote:
```
SynMemoFilter.UndoList.AddGroupBreak;
SynMemoFilter.SelectAll;
SynMemoFilter.SelText := ForeignColumnName + ' = "' + TextCopy + '"';
// SynMemoFilter.Text := ForeignColumnName + ' = "' + TextCopy + '"';
actApplyFilter.Execute;
// actApplyFilterExecute(nil);
The commented code is the alternative code which also doesn't work.
```
@ansgar Can you give me some tips to handle this?

**Comment by ansgarbecker** [comment]
Let's discuss such internal stuff via mail.

**Comment by dungsaga** [comment]
There are some alternative approach for the UI of this feature:
1. show reference table in tab "Data" and filter to show only rows linked by the foreign key
2. show reference table in tab "Data" and scroll to focus on the first row linked by the foreign key
3. show reference table in new Query tab by executing a query like `SELECT * FROM table WHERE id=xxx`

I'm working on approach 1. But approach 3 seems easier, and it allows opening multiple query tabs.

**Comment by ansgarbecker** [comment]
Next build will have a first attempt for a "Follow foreign key" menu item, mainly done by @dungsaga :

![grafik](https://user-images.githubusercontent.com/7986591/166096817-380d1f03-1433-4b89-98df-335a4b05f935.png)

Just shout if you find issues with it.

**Comment by bytech-ca** [comment]
This is an awesome one - thanks @dungsaga ... one thing I can't find is a "back" option to return to the original table. Also, an option to see the first few fields of data on a mouse hover would be sweet. ;)

**Comment by dungsaga** [comment]
It's a good idea @bytech-ca

Unfortunately, I haven't used Heidi much recently since I found a more
light-weight tool for my daily needs (adminer/adminneo).

But I still like Heidi a lot and will try to improve this when I can.

**Comment by bytech-ca** [comment]
@dungsaga Thank you, excellent human being!
