### ISSUE TITLE
Regular Expression Search & Replace doesn't work

### ISSUE THREAD

**Issue by miles-harrison** [HeidiSQL/HeidiSQL#1562]
**Preconditions**

* HeidiSQL version: 11.3.0.6295 (64 bit)
* Database type and version: MYSQL
* OS: Windows

**Describe the bug**
When you try a regular expression search and replace, the editor says it's replaces X instances but nothing happens. The editor text is unchanged.

**To Reproduce**
1. Go to the SQL pain, place in some text - search, replace text. Try a regular expression replace of $ to '),  
2. Click on "replace".
3. Get a popup saying replaced X times but nothing happens.

**Screenshots or Crash reports**
![image](https://user-images.githubusercontent.com/8243570/161501518-a2190931-f3fc-4d5a-b277-27825353a923.png)

**Comment by miles-harrison** [comment]
Also start of line ^ as well.

**Comment by ansgarbecker** [comment]
Fixed by merging recent updates from https://github.com/andgineer/TRegExpr/
