### ISSUE TITLE
SQLite edits apply to highlighted DB rather than the one in the query

### ISSUE THREAD

**Issue by babudro** [HeidiSQL/HeidiSQL#1563]
SQLite3 database edits follow the DB highlighted on the left-hand side rather than the one in the query.  Steps to reproduce:

1. Open SQLite3 session.
2. Create two databases with the same schema.
3.  In the query pane SELECT * FROM one of your databases.
4.  Highlight on the left side a different DB than the one in your SELECT query
5.  On the right side edit one of the records and apply it.
6. Notice in the console output at the bottom that the UPDATE statement applies to the DB highlighted on the left side rather than the one in the query.  You can also refresh your query to verify that the update was not applied to the DB in the query, but rather (if the two DBs have the same structure) the one that was highlighted on the left side.

HeidiSQL version 11.3.0.6463

**Comment by ansgarbecker** [comment]
I suppose you mean "table" when you say "database". Could it be you're mixing up the two words here?

**Comment by ansgarbecker** [comment]
Closing due to no feedback. Just give feedback to reopen.
