### ISSUE TITLE
Comments in SELECT query are taken as column names in result grid

### ISSUE THREAD

**Issue by golimarrrr** [HeidiSQL/HeidiSQL#1566]
**Preconditions**

* HeidiSQL version: 11.3.0.6295 and 12.0
* Database type and version: MariaDB 10.6.7.0
* OS: Win10

**Describe the bug**
When the SELECT fields contain functions and comments, the wrong column names are shown in the data grid

**To Reproduce**
Run: 
```
SELECT
	MD5(1), -- one
	MD5(2), -- two
	MD5(3)  -- three
;
```
First column name will be `MD5(1)` -- ok
Second column name will be `-- one` -- wrong
Third column name will be `-- two` -- wrong

If no functions like MD5() are used, the content of comments is not shown in the column names

**Comment by ansgarbecker** [comment]
Strange, though that seems to be a MariaDB issue.
MySQL 5.7.37 does it the way one would expect:

![grafik](https://user-images.githubusercontent.com/7986591/163209963-a2f4bd5b-3c4e-48ce-bb9b-ede9de9777fb.png)

While in MariaDB 10.3.12 I see the issue:

![grafik](https://user-images.githubusercontent.com/7986591/163210069-76e4c909-0110-4059-9681-056b9e45eb82.png)

HeidiSQL shows you the `org_name` property from the result of `mysql_fetch_field_direct`: https://mariadb.com/kb/en/mariadb-connectorc-data-structures/#mysql_field . I'll check whether `name` contains something different in that case.

**Comment by golimarrrr** [comment]
Looks like the 2nd and 3rd column contain the comment, then a line break, and then the correct column name in a second line, but that second line can't be seen.
If I copy the results grid as HTML:

![image](https://user-images.githubusercontent.com/3762732/163238423-43e065b6-8a4c-4bc5-a873-d519d7e69512.png)

**Comment by ansgarbecker** [comment]
Oh my god, what a funny issue.

Next build displays multi-line column headers:

![grafik](https://user-images.githubusercontent.com/7986591/163310997-1bc29742-48d4-4922-91bc-57922b9f407a.png)
