### ISSUE TITLE
Many Versions of Firebird

### ISSUE THREAD

**Issue by acgubamg** [HeidiSQL/HeidiSQL#1569]
How to change dll vendor, when i use three versions firebird ? 2.5, 3.0 and 4.0? The combobox is fixed with version 4 only

**Comment by ansgarbecker** [comment]
That is just the client library. I suppose the 4.x versions are backward compatible. Please just try it out, and report back if you get an error.

**Comment by jasonjac2** [comment]
When I try to connect  to a FB 1.5.6 DB 
[Window Title] - V3: Error
[Main Instruction] - Connection failed
[Content] - SQL Error (335544324): [FireDAC][Phys][FB]invalid database handle (no active connection)

See also #1631 for suggestion.

Also, the error title is a bit confusing - V3 is open, but I am trying to open V1.5

![image](https://user-images.githubusercontent.com/68282090/182290531-c7b6fb3b-442f-4ef7-85ba-cd8018cd18dc.png)

**Comment by regs01** [comment]
Copy fbclient.dll with its related libraries (ib_util.dll fbclient.dll icudt30.dll icuin30.dll icuuc30.dll msvcp80.dll msvcr80.dll) into HeidiSQL folder and it will pick it up. Make sure you are using 32-bit Firebird libraries for 32-bit HeidiSQL and 64-bit libraries for 64-bit HeidiSQL.

You can rename fbclient.dll adding postfixes. Like fbclient1.dll for Firebird 1 and fbclient2.dll for Firebird 2.
