### ISSUE TITLE
Clear log window (First line need be 1 after clear log window)?

### ISSUE THREAD

**Issue by SmileYzn** [HeidiSQL/HeidiSQL#157]
## Steps to reproduce this issue

1. Step 1;I worked a bit, soo log window shoud be with some log at this moment;
2. Step 2; When i use CTRL + Q to clear log window, first line still in 245 or any line number that i point
3. Last line number from log window

## Expected behavior

Since i have clear the window, log line need be 1 again

## Environment

* **HeidiSQL version:** 
9.5.0.5253
* **Database system and version:** 
    MySQL 5.6
* **Operating system:** 
  Windows 8.1  x64

[Screenshot here](https://i.imgur.com/v1Lx6rb.png)

**Comment by ansgarbecker** [comment]
Well, that's intentionally... I thought it's a good idea to have at least the line numbers unchanged. Is that even worth to create an issue?

**Comment by rentalhost** [comment]
I too don't understand why it doesn't reset line count. I mean, why line number is important to keep it even after clear?

**Comment by SmileYzn** [comment]
@ansgarbecker 

I do not know why this maintain last line, but i think that is a bug.
Thanks :D

**Comment by WinterSilence** [comment]
why it's issue clossed? not fixed

**Comment by ansgarbecker** [comment]
This is not a bug, but intentionally.
