### ISSUE TITLE
access violation by corrupted table

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [HeidiSQL/HeidiSQL#1570]
**Preconditions**

* HeidiSQL version:12.0.0.6492
* Database type and version:Mariadb 10.7.x
* OS:win 11 64bit

**Describe the bug**
when click the corrupted table name on treeview, it happened.
user click the table name that already corrupted is to use 'DROP' context menu. but any of command of context menu are not working. thats why report to you. Any improvement will be welcome.

**To Reproduce**
To reproduce the symptom under normal condition mysql/mariadb would be..... shutdown db > go to data folder > and go into any of folder that database > find any of file that you want to make corrupt which have '*ibd' extension > edit bytes or truncate contents > restart db

**Screenshots or Crash reports**
SELECT * FROM information_schema.VIEWS WHERE TABLE_SCHEMA='ssssssssss' AND TABLE_NAME='ssssssssssssssssssssssssssssssssssssssssss';
/* Result #1 fetched. */
/* Detected column type for TABLE_CATALOG: VARCHAR */
/* Detected column type for TABLE_SCHEMA: VARCHAR */
/* Detected column type for TABLE_NAME: VARCHAR */
/* Detected column type for VIEW_DEFINITION: TEXT */
/* Detected column type for CHECK_OPTION: VARCHAR */
/* Detected column type for IS_UPDATABLE: VARCHAR */
/* Detected column type for DEFINER: VARCHAR */
/* Detected column type for SECURITY_TYPE: VARCHAR */
/* Detected column type for CHARACTER_SET_CLIENT: VARCHAR */
/* Detected column type for COLLATION_CONNECTION: VARCHAR */
/* Detected column type for ALGORITHM: VARCHAR */
/* Access violation at address 0000000000CF5EA0 in module 'heidisql.exe'. Read of address 0000000000000030 */

**Comment by ansgarbecker** [comment]
Can you please indicate what should happen instead, when clicking any menu on a broken table?

**Comment by Mitchell-kw-Lee** [comment]
Well. that should kinda 'By design' area that your decision I thought.
For now, as is, heidlSQL cannot even recognize the table name is. 
So we can see the context menu that usually see. But that is it. none(especially the DROP menu) of menu working.
so user can do none of any of following action. 
Above report is the meaning.

expect that, at least, allow to DROP the corrupted table and do 'check table' or 'repair table' or 'analyse table' or 'optimize table'. that your decision. since...that corrupted.

**Comment by ansgarbecker** [comment]
Well I thought you had something in mind what should happen then. I was asking because my server generates errors when trying to drop, check, repair or analyze a broken table:
* SQL Error (1347): 'dbx.tabley' is not of type 'VIEW'
* Table 'dbx.tabley' doesn't exist in engine

and so forth. I think HeidiSQL cannot do much in such cases, apart from showing the error.

**Comment by Mitchell-kw-Lee** [comment]
is it? 
hope that possibly do the DROP table at least since I was try to use the menu.
not by typing 'drop table table_name'. you know.. the reason why using heidisql that make life easier...

if...can recognize the table name, then anything would be possible.
eventhough system tells us, how the tree_view got the right table name??
the what we only need isn't the table name? to go next?

**Comment by Mitchell-kw-Lee** [comment]
fyi. the crash report is not part of log when I click the tree view.
but everything I've got when I click the tree view item.

**Comment by Mitchell-kw-Lee** [comment]
Ah. Here you go the full log for you. Found it.
------------------------
/* 2022-04-22 22:02:04 [db_name] */ /* SetDatabase(db_name), FDatabase: db_name */
/* 2022-04-22 22:02:04 [db_name] */ /* Getting fresh columns for `db_name`.`the_table_name` */
/* 2022-04-22 22:02:04 [db_name] */ /* Ping server ... */
/* 2022-04-22 22:02:04 [db_name] */ SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='db_name' AND TABLE_NAME='the_table_name' ORDER BY ORDINAL_POSITION;
/* 2022-04-22 22:02:04 [db_name] */ /* Result #1 fetched. */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for TABLE_CATALOG: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for TABLE_SCHEMA: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for TABLE_NAME: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for COLUMN_NAME: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for ORDINAL_POSITION: BIGINT */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for COLUMN_DEFAULT: TEXT */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for IS_NULLABLE: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for DATA_TYPE: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for CHARACTER_MAXIMUM_LENGTH: BIGINT */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for CHARACTER_OCTET_LENGTH: BIGINT */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for NUMERIC_PRECISION: BIGINT */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for NUMERIC_SCALE: BIGINT */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for DATETIME_PRECISION: BIGINT */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for CHARACTER_SET_NAME: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for COLLATION_NAME: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for COLUMN_TYPE: TEXT */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for COLUMN_KEY: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for EXTRA: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for PRIVILEGES: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for COLUMN_COMMENT: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for IS_GENERATED: VARCHAR */
/* 2022-04-22 22:02:04 [db_name] */ /* Detected column type for GENERATION_EXPRESSION: TEXT */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "bigint(20) unsigned" : bigint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "varchar(10)" : varchar */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "char(1)" : char */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "tinyint(4)" : tinyint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "int(8)" : int */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "mediumint(6)" : mediumint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "double" : double */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "float" : float */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "smallint(6)" : smallint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "tinyint(4)" : tinyint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "tinyint(4)" : tinyint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "smallint(6)" : smallint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "smallint(6)" : smallint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "tinyint(4)" : tinyint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "tinyint(4)" : tinyint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "smallint(6)" : smallint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "smallint(6)" : smallint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "tinyint(4)" : tinyint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "tinyint(4)" : tinyint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "smallint(6)" : smallint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "smallint(6)" : smallint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "smallint(6)" : smallint */
/* 2022-04-22 22:02:04 [db_name] */ /* GetDatatypeByName: "timestamp(6)" : timestamp */
/* 2022-04-22 22:02:04 [db_name] */ /* Ping server ... */
/* 2022-04-22 22:02:04 [db_name] */ SHOW INDEXES FROM `the_table_name` FROM `db_name`;
/* 2022-04-22 22:02:04 [db_name] */ /* SQL Error (1877): Table db_name/the_table_name is corrupted. Please drop the table and recreate. */
/* 2022-04-22 22:02:06 [db_name] */ /* Ping server ... */
/* 2022-04-22 22:02:06 [db_name] */ SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='db_name'   AND TABLE_NAME='the_table_name'   AND REFERENCED_TABLE_NAME IS NOT NULL;
/* 2022-04-22 22:02:06 [db_name] */ /* Result #1 fetched. */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for CONSTRAINT_CATALOG: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for CONSTRAINT_SCHEMA: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for CONSTRAINT_NAME: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for UNIQUE_CONSTRAINT_CATALOG: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for UNIQUE_CONSTRAINT_SCHEMA: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for UNIQUE_CONSTRAINT_NAME: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for MATCH_OPTION: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for UPDATE_RULE: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for DELETE_RULE: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for TABLE_NAME: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for REFERENCED_TABLE_NAME: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Ping server ... */
/* 2022-04-22 22:02:06 [db_name] */ SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='db_name'   AND TABLE_NAME='the_table_name'   AND REFERENCED_TABLE_NAME IS NOT NULL;
/* 2022-04-22 22:02:06 [db_name] */ /* Result #1 fetched. */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for CONSTRAINT_CATALOG: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for CONSTRAINT_SCHEMA: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for CONSTRAINT_NAME: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for TABLE_CATALOG: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for TABLE_SCHEMA: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for TABLE_NAME: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for COLUMN_NAME: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for ORDINAL_POSITION: BIGINT */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for POSITION_IN_UNIQUE_CONSTRAINT: BIGINT */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for REFERENCED_TABLE_SCHEMA: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for REFERENCED_TABLE_NAME: VARCHAR */
/* 2022-04-22 22:02:06 [db_name] */ /* Detected column type for REFERENCED_COLUMN_NAME: VARCHAR */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoQuery" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoQuery2" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoQuery3" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoQuery4" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoQuery5" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoQuery6" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoQuery7" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoFilter" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoProcessView" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoSQLLog" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoBody" */
/* 2022-04-22 22:02:06 [] */ /* Setting up TSynMemo "SynMemoCreateCode" */
/* 2022-04-22 22:02:06 [] */ /* TfrmView.Init, using object "the_table_name" */
/* 2022-04-22 22:02:06 [db_name] */ /* Fetching user@host ... */
/* 2022-04-22 22:02:06 [db_name] */ /* Ping server ... */
/* 2022-04-22 22:02:06 [db_name] */ /* Fetching user@host ... */
/* 2022-04-22 22:02:06 [db_name] */ /* Ping server ... */
/* 2022-04-22 22:02:06 [db_name] */ /* Ping server ... */
/* 2022-04-22 22:02:06 [db_name] */ SHOW CREATE VIEW `db_name`.`the_table_name`;
/* 2022-04-22 22:02:07 [db_name] */ /* SQL Error (1877): Table db_name/the_table_name is corrupted. Please drop the table and recreate. */
/* 2022-04-22 22:02:07 [db_name] */ /* Ping server ... */
/* 2022-04-22 22:02:07 [db_name] */ SELECT * FROM information_schema.VIEWS WHERE TABLE_SCHEMA='db_name' AND TABLE_NAME='the_table_name';
/* 2022-04-22 22:02:07 [db_name] */ /* Result #1 fetched. */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for TABLE_CATALOG: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for TABLE_SCHEMA: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for TABLE_NAME: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for VIEW_DEFINITION: TEXT */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for CHECK_OPTION: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for IS_UPDATABLE: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for DEFINER: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for SECURITY_TYPE: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for CHARACTER_SET_CLIENT: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for COLLATION_CONNECTION: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Detected column type for ALGORITHM: VARCHAR */
/* 2022-04-22 22:02:07 [db_name] */ /* Access violation at address 0000000000CF5EA0 in module 'heidisql.exe'. Read of address 0000000000000030 */
/* 2022-04-22 22:02:07 [db_name] */ /* Ping server ... */

**Comment by ansgarbecker** [comment]
These debug log lines are mostly irrelevant, or?
Didn't you say you get a crash dialog? If so, please attach the bug report textfile here.

**Comment by Mitchell-kw-Lee** [comment]
For this, no crash dialog. 
what you thinking term 'crash' from me should be indicate 'Access violation at address 0000000000CF5EA0'.
that crash inside module.

**Comment by ansgarbecker** [comment]
Ah I see. That log line with "Access violation" is _intentionally_ not crashing with a dialog, but meant for debugging purposes. There is no need to report them, as these are already part of existing reports which are not yet solved.

**Comment by Mitchell-kw-Lee** [comment]
okay. (presumably) we are waiting for your patchs all the time.
cheers up and have a nice weekend.
