### ISSUE TITLE
Need to suspend Find/Replace operation on Error

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#1577]
Say I have a column limited to 10 symbols and I'm going to Find-Replace there some substring to a 15-char replacement string. I have hundreds of substrings. I got an error like "too long string" on each replacement attempt when use Replace All option. This makes me to kill the process, no other way to escape the operation.

Please, add an ability to cancel this operation on error. Thank you!

**Comment by ansgarbecker** [comment]
Can you please attach a screenshot of the error you've got, and a crash report (if it was a crash)

**Comment by ansgarbecker** [comment]
And please a rough estimation how long the edited text was.

**Comment by AlexLunyov** [comment]
Yes, sure. I just would like to amend my table when I got an error. It seems currently we are unable to do this until all entries are done (each with similar error).

So, in short, I'd like to press OK, then go to my table, fix the length of VARCHAR column, and do my replace again.
Instead, currently I have to press OK seven times before I actually get control over the App again.

And please, remove the auto closing of the Find-Replace dialog after user press Find or Replace button. If possible. Thank you very much!

![image](https://user-images.githubusercontent.com/43061117/166558875-48c38713-c35d-4ff0-b918-0911ffc8e1c3.png)

**Comment by ansgarbecker** [comment]
Makes sens now that you mention the grid and the SQL error.
Next build now breaks the "replace all" process when a grid update produces any error.
The auto-close thing was reported in #896 already.

**Comment by ansgarbecker** [comment]
I got an SQL error like in your screen while testing. Not so on your side?

**Comment by AlexLunyov** [comment]
Oh, yes, indeed. That was another server. Thanks a lot for explanation and help!
There were no warnings, but I guess, it is about server too.
