### ISSUE TITLE
Unable to cancel cell editing action in a grid with ESC button after Search-Replace

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#1579]
**Preconditions**

* HeidiSQL version: Version 12.0.0.6500 (64 Bit)
* Database type and version: MariaDb ...
* OS: Win10

**Describe the bug**

Unable to undo cell editing action with ESC button after Search-Replace action.

After replacement with Search-Replace, we get a cell with red corner arrow to be updated.
Then we want to undo action. I expect to press ESC button to do this but I can't. I can do it only by opening text editor and pressing red cross. Or just by clicking to edit that cell and pressing ESC again.

**To Reproduce**

1. Open table grid
2. Run Search-Replace to get at least one replacement
3. Last edited cell has red corner arrow but we unable to prevent commiting by pressing ESC

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/43061117/166813649-9fc12d55-5091-4c33-bff4-8f2972c22d9c.png)

**Comment by ansgarbecker** [comment]
Should be fixed
