### ISSUE TITLE
Hidden query text

### ISSUE THREAD

**Issue by Exlipse7** [HeidiSQL/HeidiSQL#1582]
**Preconditions**

* HeidiSQL version: 12.0.0.6468 64bit
* Database type and version: mysql
* OS: windows 10

**Describe the bug**

When typing in a query, after row 4 the text does not show on the screen until you move the cursor to somewhere in the first 4 rows.   This also seems to happen in the first 4 rows after 99 characters in.  I noticed this several versions ago, I don't remember exactly after which update.  To be clear, the characters are there, you just can't see them or the cursor until you click further up the window.  It is also not exactly rows 1-4 that work, but the top 4 rows displayed in the query window.  For example if I have the window scrolled down so that row 8 is at the top, then the text will be hidden starting on row 12.

**To Reproduce**

1. Open a query tab
2. Type in 5 lines of text
3. Notice that text on line 5 is not displayed

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
I checked this several times, but that hidden text was never reproducible up to the latest release. Can you reproduce this with the current release?
