### ISSUE TITLE
Duplicate SQL delimiter (`;`) in log

### ISSUE THREAD

**Issue by WinterSilence** [HeidiSQL/HeidiSQL#1583]
**Preconditions**

* HeidiSQL version: 12.0.0.6503 (64 Bit)
* Database type and version: Mysql 8
* OS: Win 10

**Describe the bug**

Duplicate SQL delimiter (`;`) in log.

**To Reproduce**
1. Execute any SQL
2. Loot log

**Screenshots or Crash reports**

![изображение](https://user-images.githubusercontent.com/3521094/167265502-c06ff5f1-7d36-4751-92e8-9d5a749a6217.png)

**Comment by ansgarbecker** [comment]
Confirmed, but only if "Send batch in one go" is enabled:

![grafik](https://user-images.githubusercontent.com/7986591/167344646-1c639f46-e9e6-4600-baa1-190310f07866.png)
