### ISSUE TITLE
Change table collation + convert data checkbox does not work

### ISSUE THREAD

**Issue by RickKukiela** [HeidiSQL/HeidiSQL#1586]
**Preconditions**

* HeidiSQL version: 12.0.0.6468
* Database type and version: MariaDB 10.6.5
* OS: Win11 x64

**Describe the bug**

Changes to table collation with convert data checked do not appear to save. I'm not sure if this is a bug where the view is not refreshing after the change and showing old structure cache, or if the new collation settings are not saving.

**To Reproduce**

Edit a table structure
Choose a new default collation.
Check the convert data checkbox (observe all string fields have new collation set).
Click save (action appears to be successful).
Navigate away from the table.
Return to the table.
Observe the old collation on the table and columns.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Confirmed. And fixed in the next build.

The `ALTER TABLE .. CONVERT TO ..` code was missing a `COLLATE xyz` clause at the end, so the columns were converted to the _default_ collation of the new character set.
