### ISSUE TITLE
Snippet Folder

### ISSUE THREAD

**Issue by Dwza** [HeidiSQL/HeidiSQL#1588]
**Is your feature request related to a problem? Please describe.**
Currently there is a folder where you can save snippets. I am using HeidiSQL quite a while and it is a awesome tool. Now since there are many snippets i've saved it's getting kind of confusing.

**Describe the solution you'd like**
I would love to see that heidi could handle different subfolders to cleanup the amount of snippets and sort them into folders :)

## EXTRA (Github related):
There is a cool way to improve these issue templates (error, feature... etc) by adding yaml files. Checkout issue configs: 
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by Dwza** [comment]
Is "no reply" kind of like a "no, will not be implemented" ?

**Comment by ansgarbecker** [comment]
Certainly not.

But this is a duplicate to #1399 , so I'm closing this.
