### ISSUE TITLE
Invalid dump of database using foreign keys

### ISSUE THREAD

**Issue by WinterSilence** [HeidiSQL/HeidiSQL#1593]
**Preconditions**

* HeidiSQL version: Версия 12.0.0.6507 (64 Bit)
* Database type and version: Any supported foreign keys
* OS: Any

**Describe the bug**

DP tables dumped in alphabet order. This SQL dumps can't be imports when tables with FK creates before attached tables.
Easy solution: export tables without FKs at begin.

**To Reproduce**

**Screenshots or Crash reports**

```sql
CREATE TABLE `a` (
  `id` INT(10) UNSIGNED NOT NULL,
  `a_id` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  CONSTRAINT `fk_b` FOREIGN KEY (`a_id`) REFERENCES `b` (`id`) 
  ON DELETE CASCADE
) ENGINE=InnoDB;
CREATE TABLE `b` (
  `id` SMALLINT(5) UNSIGNED NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB;
```

**Comment by ansgarbecker** [comment]
Isn't that what disabling the `FOREIGN_KEY_CHECKS` variable is for?

```
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
```

**Comment by WinterSilence** [comment]
@ansgarbecker sorry, my mistake
