### ISSUE TITLE
Autosizing the autocomplete window based on the content of the list

### ISSUE THREAD

**Issue by scooi** [HeidiSQL/HeidiSQL#1596]
**Is your feature request related to a problem? Please describe.**
Autocomplete dialog is unable to show complete table name when table name is slightly longer

**Describe the solution you'd like**
Auto-sizing the autocomplete window based on the content

**Describe alternatives you've considered**
1. Let us resize the autocomplete window
2. Have a bigger default width for autocomplete window

**Additional context**
***Version/Device info***
* Resolution: 1920/1080
* OS: WIndows 11
* HeidiSQL version: 12.0.0.6468

***Screenshots***
<img width="407" alt="image" src="https://user-images.githubusercontent.com/2107336/170609333-8e0d5b8e-dcb0-427e-bda2-a237cba4cdee.png">

**Comment by ansgarbecker** [comment]
Isn't the proposal window resizable for you? It should be, definitely, and it is here as you can see the arrow mouse cursor:
![grafik](https://user-images.githubusercontent.com/7986591/197743751-b0950f8e-9a23-4635-af2b-e85c9b42b22c.png)

**Comment by scooi** [comment]
Yeah it is resizable now. It wasn't before.
