### ISSUE TITLE
Out of memory connecting to any SQLite3 database

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1602]
**Preconditions**
HeidiSQL 12.0.0.6468
Windows 11 64-bit

**Describe the bug**
 I am trying to open SQLite3 file databases but I receive the error "SQL-error(7): Out of memory".
The database file opens fine in other db managers.

**To Reproduce**
Use the attached sample database

**Screenshots or Crash reports**
![image](https://user-images.githubusercontent.com/359192/171970126-c8bcf141-31b5-46fa-be82-f680f96ed8a6.png)

Sample Database:
[foo.zip](https://github.com/HeidiSQL/HeidiSQL/files/8836490/foo.zip)

**Comment by timint** [comment]
And I think I just found the problem. The path is added to a predefined location 127.0.0.1 like this:
Database filename: 127.0.0.1|X:\path\to\foo.sqlite

Removing the default value 127.0.0.1 solves the problem.
I propose a fix not setting the default value of 127.0.0.1 for sqlite connections.

**Comment by ansgarbecker** [comment]
Funny: it's "connecting" to the IP address as if it's a file here:

![grafik](https://user-images.githubusercontent.com/7986591/172050403-b6c235f0-3479-4218-8837-ec704a33b53e.png)

But yes, any IP address should be removed when the session gets modified as SQLite.
