### ISSUE TITLE
Can't create indexes for SQLite tables

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1604]
**Preconditions**
HeidiSQL 12.0.0.6468
Windows 11 64-bit

**Describe the bug**
Adding an index key causes a malfunction.

**To Reproduce**
Create an index, click Save.
This produces the following query:
`ALTER TABLE "dummy" ADD INDEX "foo" ("foo");`

**Screenshots or Crash reports**
![image](https://user-images.githubusercontent.com/359192/171970694-3c4e06db-458e-4fc7-947d-45239c76c346.png)

Documentation:
https://www.sqlitetutorial.net/sqlite-index/

**Comment by ansgarbecker** [comment]
Should be doable in the upcoming builds. CREATE code shows code like this:

```sql
CREATE TABLE "table5" (
    "Column 1" INTEGER NULL,
    "Column 2" INTEGER NULL
)
;
CREATE UNIQUE INDEX "Index 2" ON "table5" ("Column 1", "Column 2");
CREATE INDEX "Index 1" ON "table5" ("Column 1");
```

@timint do you have the chance to test the new build?

**Comment by timint** [comment]
I have a lot this week, but I will write down a memo to do it when I get the chance.

**Comment by ansgarbecker** [comment]
Adding primary key to new tables now supported. I'll close the issue.
