### ISSUE TITLE
Can't drop indexes from SQLite tables

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1605]
**Preconditions**
HeidiSQL 12.0.0.6468
Windows 11 64-bit

**Describe the bug**
Removing  an index key causes a malfunction.

**To Reproduce**
Remove an index, click Save.
This produces the following query:
`ALTER TABLE "dummy" DROP .......;`

**Screenshots or Crash reports**
![image](https://user-images.githubusercontent.com/359192/171970795-10dd7068-08cd-4856-8d11-f4ea0ad4a868.png)

Documentation:
https://www.sqlitetutorial.net/sqlite-index/

**Comment by ansgarbecker** [comment]
Just tested successfully.

If you get the chance, please also give it a test.

**Comment by timint** [comment]
Is it 12.7.0.6898 (Jun 23)? I am stuck at creating a table.

```
CREATE TABLE "testtbl" (
	"id" INTEGER NOT NULL
)
;
CREATE PRIMARY INDEX "id" ON "testtbl" ("id");
/* SQL-error (1): near "PRIMARY": syntax error */
```

**Comment by ansgarbecker** [comment]
According to the tutorial, shouldn't it be without the `CONSTRAINT id` clause?
```sql
CREATE TABLE "testtbl" (
   "id" INTEGER NOT NULL,
   PRIMARY KEY ("id")
);
```

Also - as we're here in the "drop index" issue - SQLite does not support dropping a primary  key. The user will need to recreate the whole table instead. What a mess...

**Comment by timint** [comment]
My bad I can create a new issue ticket for primary key If you like. I created a table with a regular index that was both addable and dropable. So this issue can be closed. And open a new one for primary key.

Constraint keyword or not depends on the guides you find. Some use the shorthand. I am told there are differences. Using the constraint keyword allows for some extended use like naming the key alias and span over more than one column.

**Comment by ansgarbecker** [comment]
Ah thanks, but no, let's do the add-primary-key here. I just need a technical idea how to create these inline, while indexes are created per separate query.

**Comment by ansgarbecker** [comment]
Basically one can now add a primary key to a table. But only for newly created tables, and you cannot drop it. I have no recreate logic yet. That's definitely its own topic, and needs a new ticket.
