### ISSUE TITLE
Creating an SQLite view crashes the application

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1608]
**Preconditions**
HeidiSQL 12.0.0.6468
Windows 11 64-bit

**Describe the bug**
Application crash while creating table view.

**To Reproduce**
Open the context menu. Select Create New -> View

![image](https://user-images.githubusercontent.com/359192/171971243-0b31f3a9-33aa-4230-9a09-8c9fc8c30134.png)

Documentation:
https://www.sqlitetutorial.net/sqlite-create-view/

**Comment by timint** [comment]
The same goes for SET

![image](https://user-images.githubusercontent.com/359192/171971457-e0b27e9e-4ccd-48c9-b519-5b701b923e4a.png)

**Comment by ansgarbecker** [comment]
I think the next build fixes this crash. Only the editor yet uses MySQL syntax for creating a view, when you try to save it.
