### ISSUE TITLE
Optionally delete existing sessions before import settings file

### ISSUE THREAD

**Issue by baukezwaan** [HeidiSQL/HeidiSQL#161]
## Steps to reproduce this issue

Would be nice to be able to clear all existing session bookmarks, before importing a settings file.

## Current behavior

When I share a settings files with a co-worker, duplicate entries may appear if some of the names are changed.

## Possible solution

Make a checkbox on the import screen (after selecting the settings file), where you can choose to clear all existing entries. Perhaps: 'You are about to import 16 bookmarks, would you like to keep your existing bookmarks?'

## Environment

* **HeidiSQL version:** 
9.5.0.5254 Windows 10

**Comment by G3ph4z** [comment]
Do you mean something like this?
http://prtsc.denes.cloud/vmware_2018-02-26_23-48-44.png

**Comment by baukezwaan** [comment]
Exactly!

Maybe even nicer if this question was part of the 'Select file' box, but as this is different for every platform, a question afterwards seems most realistic.

**Comment by G3ph4z** [comment]
It will be displayed after you selected the settings file. But I will try the other version.

**Comment by ansgarbecker** [comment]
To be clear here, we are talking about deleting sessions, not "bookmarks". That's a quite critical thing, especially when doing that in an automated way.

A better way of sharing session parameters between people is to run HeidiSQL in portable mode. The existing portable_settings.txt file with all sessions can be synchronized with some external rsync or backup command after leaving HeidiSQL.

**Comment by G3ph4z** [comment]
@ansgarbecker Then what is ur opinion? Would it be worth to develop or not?

**Comment by ansgarbecker** [comment]
I'm against such an automatism. This is too critical. I can already hear others shouting "I accidentally deleted all my session data, including passwords, and now I cannot recreate them".

**Comment by G3ph4z** [comment]
Ah okey, I got it. :) then I will remove my changes.

**Comment by baukezwaan** [comment]
Understandable!

**Comment by ansgarbecker** [comment]
However, a simple way to delete all your sessions is as follows:
* exit all HeidiSQL instances
* run regedit.exe
* navigate to `HKEY_CURRENT_USER\Software\HeidiSQL\Servers`
* delete all keys below the "Servers" key
