### ISSUE TITLE
Spatial indexes not recognized

### ISSUE THREAD

**Issue by FluentIMS-ShaneCurless** [HeidiSQL/HeidiSQL#1613]
Hello,

When creating a table with a `SPATIAL` index, viewing the table later shows the index as a regular index (green key).

This can be replicated by creating a table with any SPATIAL key for example:
```
CREATE TABLE `test` (
	`the_point` POINT NOT NULL,
	SPATIAL INDEX `the_point` (`the_point`)
)
COLLATE='utf8_general_ci'
;;
```

This is then immediately shown as a green key, and listed under the index "Indexes" tab as "Type / Lenth" of `KEY`.
The "CREATE code" tab shows:

```
CREATE TABLE `test` (
	`the_point` POINT NOT NULL,
	INDEX `the_point` (`the_point`(32))
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;;
```

However, the raw output of running `SHOW CREATE TABLE test.test` in a Query tab shows:

 ```
 CREATE TABLE `test` (
  `the_point` point NOT NULL,
  SPATIAL KEY `the_point` (`the_point`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

So it appears that HeidiSQL is incorrectly interpreting the `SPATIAL KEY` part

**Comment by ansgarbecker** [comment]
Next build should show spatial keys as they should, and the CREATE code tab should contain valid SQL for it.

![grafik](https://user-images.githubusercontent.com/7986591/172446376-e464015b-e396-4a08-b5ff-4fff93331871.png)

Please update and report back if that works.
