### ISSUE TITLE
Add Shortcut (Save Button)

### ISSUE THREAD

**Issue by paulocotta** [HeidiSQL/HeidiSQL#1619]
**Is your feature request related to a problem? Please describe.**
Not

**Describe the solution you'd like**
Add Shortcut (Save Button)

**Describe alternatives you've considered**
Add Shortcut (Save Button)

**Additional context**
N/A
![Captura de tela 2022-06-17 161814](https://user-images.githubusercontent.com/405220/174388723-ed833fc1-c59a-41d1-b541-f0358f85e024.png)

**Comment by rentalhost** [comment]
@paulocotta O que você quis dizer com isso? O botão já está aí. Você diz algum tipo de "atalho de teclado", como um CTRL+S?

---

EN: What did you mean by that? The button is already there. You say some kind of "keyboard shortcut", like a CTRL+S?

**Comment by paulocotta** [comment]
Sim exatamente. Estou me referindo a um atalho.

EN: Yes, exactly. I'm referring to a shortcut.

**Comment by ansgarbecker** [comment]
In fact that button already has one: <kbd>Enter</kbd>, and that's why the button is drawn with a thick border. But of course other controls like the editor "eats" any <kbd>Enter</kbd> key, so it makes sense to add another keyboard shortcut.

**Comment by paulocotta** [comment]
Top Top thank you very much

**Comment by paulocotta** [comment]
Hello how are you?
Do you have any predictions?

**Comment by paulocotta** [comment]
Hello!
The Ctrl+S shortcut is saving the content to a text file and not committing the command to the database

**Comment by leoborlot** [comment]
@ansgarbecker 
I think so, theres any hierarchycal problem, when press ctrl+s, the aplication execut the mais save (File/Save). 

Theres any class above these PR commited, covering the rules about the ctrl +s when Procedure window was active. 

<img width="738" alt="heidisql_Q4jqfXD75p" src="https://github.com/HeidiSQL/HeidiSQL/assets/20361821/5be23d61-4351-41c2-a992-8b3811bcefd0">
