### ISSUE TITLE
[Enhancement] Add indentation to pretty printed SQL

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1622]
When reformatting/pretty printing the SQL, I think indentation is critical.

This:
![image](https://user-images.githubusercontent.com/359192/175750730-6927b408-e86d-40b0-8a8e-9737d5586691.png)

Is more useful like this:
![image](https://user-images.githubusercontent.com/359192/175750883-57af3a4e-8449-4c38-9b8b-88bbb420eec4.png)

Instead of HeidiSQL 12.0.0.6468:
![image](https://user-images.githubusercontent.com/359192/175750909-03fd760b-b144-4c2e-bc56-da72925937f9.png)

I understand it can be tricky to determine when it's suitable to use indentation and not. But perhaps somone already invented the wheel for this?

**Comment by ansgarbecker** [comment]
See also issue #750

**Comment by timint** [comment]
I see there is an old discussion about this.

I was thinking about this. Thinking how hard can it be? So I attempted to invent the wheel myself in PHP. I came up with ~100 lines of code which is pretty straight forward with a cursor stepping through the character sequence:

https://gist.github.com/timint/ff8cbdba8801f4d3f7ec79ff284f1a50

A query like the following:
`select t1.column1, t1.column2, t1.column3, t2.column4, t2.column5, t2.column6, t1.date_created from Table1 t1 left join ( select column4, column5, column6 from Table2 group by column4 order by date_created desc ) t2 on (t2.row_id = t1.id) where t1.column1 = 'this' and t1.column2 like '%query%' order by t1.date_created desc;`

Will turn out like this:
```
SELECT t1.column1, t1.column2, t1.column3, t2.column4, t2.column5, t2.column6, t1.date_created
FROM Table1 t1
LEFT JOIN (
  SELECT column4, column5, column6
  FROM Table2
  GROUP BY column4
  ORDER BY date_created DESC
) t2 on (t2.row_id = t1.id)
WHERE t1.column1 = 'this'
AND t1.column2 like '%query%'
ORDER BY t1.date_created desc;
```

Maybe it can inspire you or something? I'm unfortunately no Delphi programmer.

**Comment by timint** [comment]
@ansgarbecker I see you use a similar approach.
https://github.com/HeidiSQL/HeidiSQL/blob/07427f4c939a61f53b56b31eda62b1c58617375c/source/apphelpers.pas#L1691-L1798

In my code, I implemented some conditions to look around the cursor which was very useful to when determining the surrounding characters. The subquery is just passed to the function separately like an iterator.

**Comment by ansgarbecker** [comment]
Should be much better with the new online formatter. See https://github.com/HeidiSQL/HeidiSQL/issues/750#issuecomment-1732621991 for some more details.

@timint here's how your example from above looks like formatted:

```sql
SELECT
   t1.column1,
   t1.column2,
   t1.column3,
   t2.column4,
   t2.column5,
   t2.column6,
   t1.date_created
FROM
   Table1 t1
   LEFT JOIN (
      SELECT
         column4,
         column5,
         column6
      FROM
         Table2
      GROUP BY
         column4
      ORDER BY
         date_created DESC
   ) t2 ON (t2.row_id = t1.id)
WHERE
   t1.column1 = 'this'
   AND t1.column2 LIKE '%query%'
ORDER BY
   t1.date_created DESC
```
