### ISSUE TITLE
it can't find the dll library,can fix it next version?

### ISSUE THREAD

**Issue by rhettli** [HeidiSQL/HeidiSQL#1624]
**Preconditions**

* HeidiSQL version:
* Database type and version:
* OS:windows10

**Describe the bug**

move the dir of hidisql to D:/ from desktop

it can't find the dll library

![屏幕截图 2022-07-01 184611](https://user-images.githubusercontent.com/26317003/176880267-2d8606cc-688d-40ea-9261-db9e6078d7ec.png)

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
What did you do exactly? Move the directory? Or was it probably only the executable heidisql.exe?
Please don't mess with the directory. Just install HeidiSQL and keep the files where they are.
