### ISSUE TITLE
Refresh button does not reload table structure

### ISSUE THREAD

**Issue by Eddcapone** [HeidiSQL/HeidiSQL#1628]
**Preconditions**

* HeidiSQL version: 12.0.0.6468
* Database type and version: MySQL, InnoDB
* OS: Ubuntu 20.04.2 LTS

**Describe the bug**

Refresh fails if data is changed externaly.

**To Reproduce**

Example:
1. Open a database table in HeidiSQL and press on the foreign keys tab
2. Write code e.g. PHP to add a foreign key constraint to that database table.
3. Refresh the HeidiSQL view.

Result:
No change is visible.

4. Restart HeidiSQL
5. Open the database table from before and look on the foreign keys tab

Result:
Change is now visible

### Another example:

First I opened HeidiSQL and opened the table "sales_order_grid" from my magento 2 database.

Then I ran a routine from my magento 2 onlineshop to add two columns to the table "sales_order_grid" .

Then I refreshed HeidiSQL with F5 and by pressing the refresh button, to see if the script worked, but the two columns were not there.

So I thought I did something wrong and wasted alot of hours of debugging until I figured out that HeidiSQL Refresh is just broken.

After I closed HeidiSQL and opened it again, it suddenly showed the new columns.

**Comment by ansgarbecker** [comment]
HeidiSQL caches the table structure, and it's not really refreshed if you use the refresh button.

**Comment by ansgarbecker** [comment]
Next build just reinitializes the table editor when the refresh button was pressed. (same with views, procedures etc.)
