### ISSUE TITLE
Frequent Unresponsiveness When Resuming From Idle Using SSH Tunnel

### ISSUE THREAD

**Issue by CanIGetaPR** [HeidiSQL/HeidiSQL#1629]
Version 12.0.0.6468 (64 Bit)
Environment: Windows v10.0

![image](https://user-images.githubusercontent.com/45294513/181829528-200a172c-43b4-4857-b767-d6275a011c2f.png)

Whenever I leave HeidiSQL in the background for a while then come back and try to do anything such as double click a table, instead of re-connecting to the database the program just goes unresponsive. This happens very often. 

Rarely it does it ever reconnect though instead of hanging.

**Comment by CanIGetaPR** [comment]
I clicked on a different database in the same server and it got stuck on reading objects... unresponsive for 1 minute instead of just reconnecting after 3 seconds. At least this time it came back to life in 1 minute.  
![image](https://user-images.githubusercontent.com/45294513/181920648-40f8f86c-c970-4653-844b-f94c9c4154ad.png)

**Comment by ansgarbecker** [comment]
What are the last 2 or 3 queries shown in the log panel at the bottom?

Please also check the state of your session option "Full table status":

![grafik](https://user-images.githubusercontent.com/7986591/181933648-b93eb869-aeb8-45da-9bf4-a181c0118cbf.png)

**Comment by CanIGetaPR** [comment]
> What are the last 2 or 3 queries shown in the log panel at the bottom? 

What moment in time do you want those? Before it freezes or after the point of recovery?

![image](https://user-images.githubusercontent.com/45294513/181933732-d0825aae-23d3-4988-a342-550e91c3b38d.png)

**Comment by ansgarbecker** [comment]
At the time where it seems to freeze. I suspect the last query to take longer than normal/expected.

**Comment by CanIGetaPR** [comment]
maybe heidisql isn't optimized for connecting through an ssh tunnel and there's additional waiting somewhere

**Comment by ansgarbecker** [comment]
If it's an SSH tunnel, then also check the SSH timeout in the tunnel settings.
Apart from that, just the 3 last queries at the freezing point. (make a screenshot while the freeze happens)

**Comment by CanIGetaPR** [comment]
So, I copied what you have, and inserted a value into **Ping every X seconds** except I set mine to 5. I haven't had any issues yet knock on wood. 

![image](https://user-images.githubusercontent.com/45294513/182047789-046962cf-88d2-45db-a5d7-66e403ff7a0c.png)

**Comment by ansgarbecker** [comment]
That ping value is 20 by default. Must have been modified accidentally, or probably through an older resolved issue.
