### ISSUE TITLE
Export settings feature copies tab results

### ISSUE THREAD

**Issue by hahyes** [HeidiSQL/HeidiSQL#1630]
**Preconditions**

* HeidiSQL version: 12.0.0.6468
* Database type and version: any
* OS: Windows 11

**Describe the bug**

Hello there,
I'm not sure if it is bug or not well thought feature but export settings file contains result of queries from tabs. For someone unconscious it would be security breach even. You think this file contains settings, but there are queries and results containing possibly important data. Who thought this is good idea at all?

Possibly solutions I see: 
- let user choose, what data should be added to export
- don't put results of queries in export of SETTINGS

**To Reproduce**
1. Export settings file anywhere
2. Look into content

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Can you please say where exactly you found a query result? I'm aware that HeidiSQL stores some filters from the data tab, and query code for showing them in the history. But both of these can be disabled, and results are not stored anywhere as far as I recall.

**Comment by hahyes** [comment]
@ansgarbecker I panicked little too much about it, now analysing export with cool head. I found some data in `FindDialogSearchHistory`. Weird thing is, I do not recall any of these being searched, there are full records from some queries I surely didn't search in any way. This data seems very random to me.

**Comment by ansgarbecker** [comment]
I suppose the data was in the find dialog due to the "Find word under cursor" feature.
