### ISSUE TITLE
Improve execution logging window: Prepend datetime of when query was executed

### ISSUE THREAD

**Issue by pribeirojtm** [HeidiSQL/HeidiSQL#1635]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add somehow a datetime right after line number and right before the query that was executed so the user can see when specific query was executed. I think it as a useful feature.

**Describe alternatives you've considered**
None

**Additional context**
Printscreen: something like this:

![datetime_in_logging_window](https://user-images.githubusercontent.com/18724236/182877970-4921415d-bff2-4fd6-97fd-10f25a5a3534.png)

**Comment by ansgarbecker** [comment]
At least for the session log files there is already a date/time in an SQL comment:

![grafik](https://user-images.githubusercontent.com/7986591/183030406-2c4b534f-75d8-4aee-aa5e-710d08cfa9e1.png)


```
/* 2022-08-05 09:54:14 [] */ /* Writing to session log file now: C:\Users\anse\AppData\Roaming\HeidiSQL\Sessionlogs\000001.log */
/* 2022-08-05 09:54:23 [localhost] */ USE `test8`;
/* 2022-08-05 09:54:24 [localhost] */ USE `test7`;
```
Displaying it in the log panel produces quite a bit clutter doesn't it?

**Comment by pribeirojtm** [comment]
Hi @ansgarbecker 

`At least for the session log files there is already a date/time in an SQL comment:`
 The thing is that having to consult another file is not practical, even if it is better than nothing.

`Displaying it in the log panel produces quite a bit clutter doesn't it?`
I think it will depend on the way the date will be presented graphically. You could create a column with a background like grey, to better separate that info from the query itself to avoid producing clutter.

What do you think?

**Comment by ansgarbecker** [comment]
The idea with the column sounds nice. Just the underlying SynMemo does not support columns, as it's just a memo with syntax highlighting. The [SynEdit](https://github.com/SynEdit/SynEdit) project does not have a similar component which can do that I'm afraid. Perhaps I'll find a different component in the VCL somewhere which supports columns.

**Comment by pribeirojtm** [comment]
Hi @ansgarbecker 
I'm closing this issue since you already developed that:

![Screenshot from 2023-02-06 10-55-31](https://user-images.githubusercontent.com/18724236/216954298-84ab0ace-83cd-4f08-be4c-8a9cd9af43d3.png)

![Screenshot from 2023-02-06 10-55-00](https://user-images.githubusercontent.com/18724236/216954326-1dcf57dd-c9b4-44f0-b388-498b1953ead5.png)

Thanks for the improvement!
