### ISSUE TITLE
Slow open and freezes with 120.000 rows

### ISSUE THREAD

**Issue by samyan** [HeidiSQL/HeidiSQL#1638]
**Preconditions**

* HeidiSQL version: 12.0.0.6536
* Database type and version: 10.6.8
* OS: Windows 11

**Describe the bug**

I have a table with 120000 records. Since then, when I try to open heidi, it takes several minutes. After the window appears, it freezes on every click.

**Comment by ansgarbecker** [comment]
Could you please describe more exact, probably with a screenshot.

**Comment by samyan** [comment]
> Could you please describe more exact, probably with a screenshot.

I was trying to get the execution time of a complex query and for this I had to fill a table with 10 columns with information. All the rows were approximately 120 thousand, maybe a little more. As there were many rows, I had to upload in a ZIP through phpmyadmin. When I went back to Heidi and hit the refresh button. The program froze and I had to kill the process through process manager. Later I tried to open Heidi and saw that the window did not appear, however looking at the processes, I saw the application executed. I decided to let it see what happened and in a matter of 2-3 minutes the window appeared. After selecting the connection and hitting connect, the typical window appeared where the list of tables appears, etc... When I selected a table, I had short-term freezes. After emptying the table, Heidi started working correctly. I can pass a screenshot in a frozen state but I don't think it will help you. Rather I would have to make a 2 minute video for you to see the problem. But it will be faster if you try yourself to fill a table with more than 100 thousand rows and see what happens.

**Comment by ansgarbecker** [comment]
That sounds as if that large table is causing the slowness of some internal HeidiSQL queries. For example the list of table is retrieved with a `SHOW TABLE STATUS`, which can be slow when the current database contains very large tables. You could check the session settings, and disable "Get full table status" in the Advanced tab.

**Comment by samyan** [comment]
> That sounds as if that large table is causing the slowness of some internal HeidiSQL queries. For example the list of table is retrieved with a `SHOW TABLE STATUS`, which can be slow when the current database contains very large tables. You could check the session settings, and disable "Get full table status" in the Advanced tab.

You are right! After uncheck, the slowness and the freezes gone! Thank you very much!
