### ISSUE TITLE
Can not create new table

### ISSUE THREAD

**Issue by vejrous** [HeidiSQL/HeidiSQL#1642]
**Preconditions**

* HeidiSQL version: 12.1.0.6537
* Database type and version: Firebird 4.0.2
* OS: Windows 7 64bit

**Describe the bug**

Creating new table with gui in local Firebird database does not work.
Below is code and error HeidiSQL generates.

CREATE TABLE "Table1" (
	"Collumn1" INTEGER NULL
)
;
/* SQL chyba (335544569): [FireDAC][Phys][FB]Dynamic SQL Error
SQL error code = -104
Token unknown - line 2, column 21
NULL :: [FireDAC][Phys][FB]Dynamic SQL Error
SQL error code = -104
Token unknown - line 2, column 21
NULL */

**To Reproduce**

See attached image.

**Screenshots or Crash reports**

![heidi_firebird_table_error](https://user-images.githubusercontent.com/17109133/184899302-4f26a20c-fed8-4e42-9478-926d0bd146a4.PNG)

**Comment by vejrous** [comment]
I tested SQL staments and Firebird acceps:

_CREATE TABLE "Table1" (
	"Collumn1" integer 
);_

or

_CREATE TABLE "Table1" (
	"Collumn1" integer NOT NULL
);_

**Comment by ansgarbecker** [comment]
"NOT NULL" is allowed, but not so the opposite "NULL". Next build fixes this.
