### ISSUE TITLE
Create table statement does not create proper value for varchar fields 

### ISSUE THREAD

**Issue by YogeshMKumbhar** [HeidiSQL/HeidiSQL#1649]
**Preconditions**

* HeidiSQL version: 12.1.0.6537 (64Bit)
* Database type and version: Mariadb10.2.6
* OS: Windows 10

**Describe the bug**

Crreate statement in CREATE Code tab does not create it properly.
```
CREATE TABLE `BonafidePrint` (
	`SchoolId` TINYINT(4) UNSIGNED NOT NULL DEFAULT '0',
	`JFileName` VARCHAR(100) NOT NULL DEFAULT - COMMENT 'Jasper File Name With 8.3 Format' COLLATE 'utf8_unicode_ci',
	PRIMARY KEY (`SchoolId`) USING BTREE,
	INDEX `FK_BonafidePrint_School` (`SchoolId`) USING BTREE,
	CONSTRAINT `FK_BonafidePrint_School` FOREIGN KEY (`SchoolId`) REFERENCES `School_Endow`.`School` (`SchoolId`) ON UPDATE CASCADE ON DELETE RESTRICT
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
```

in abobe statement the default column for `JFileName` must contain within single quote. It should show something like below
`JFileName` VARCHAR(100) NOT NULL DEFAULT '-' COMMENT 'Jasper File Name With 8.3 Format' COLLATE 'utf8_unicode_ci',

**To Reproduce**

Example:
1. Go to 'CREATE Code tab'
2. Click on 'CREATE Code tab'

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
The only way how I can reproduce the dash without quotes is when I enter the dash in the "Expression" box. Was that the case for you?

Please note such static text has to be entered in the "Custom text" box. The "Expression" box is used without quotes, and can contain functions:

![grafik](https://user-images.githubusercontent.com/7986591/186483778-ddeb091f-ee0f-42a2-95ea-063055d8daee.png)

**Comment by YogeshMKumbhar** [comment]
Yes Thanks its working. But I don't know how - got converted into Expression from Custom Text. I don't remember I've added anyhow it in expression field I always put it in custom text. If any possible explation on this.

**Comment by ansgarbecker** [comment]
Can't explain that, and also cannot reproduce it here on MariaDB 10.2.12 with Heidi 12.1
