### ISSUE TITLE
Saving BLOB to file creates corrupted files

### ISSUE THREAD

**Issue by mnettling** [HeidiSQL/HeidiSQL#1658]
**Preconditions**

* HeidiSQL version: 12.1.0.6541
* Database type and version: MySQL 5.7.30
* OS: Windows v10.0 64 Bit

**Describe the bug**

When I save the content of a BLOB field (in my case Mediumblob) the file is saved to disk. But it has always just a filesize of 256 Bytes and cannot be opened accordingly.

**To Reproduce**

Save the content of a BLOB field to disk.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Next build should fix that.
