### ISSUE TITLE
Text Editor: json text not readable on dark theme

### ISSUE THREAD

**Issue by ahmedNY** [HeidiSQL/HeidiSQL#1659]
Text Editor: json text not readable on dark theme
![image](https://user-images.githubusercontent.com/14958972/189478763-ce3af699-3b02-432a-8a09-e3d7f18f7f29.png)

**Comment by ansgarbecker** [comment]
I recommend to use a light theme when using highlighters in the text editor. Same as here: https://www.heidisql.com/forum.php?t=39559

The only highlighter which is customizable is the one for SQL, used in the various query editors. There should be a button besides the highlighter dropdown, showing a dialog for customizing the colors.

**Comment by ansgarbecker** [comment]
Next build offers a button/dialog for customizing the used highlighter:

![grafik](https://user-images.githubusercontent.com/7986591/189526172-ea4557db-8e62-4673-82ff-bf1ff9fcdcf8.png)

Note that this is work in progress! Closing the dialog crashes, and transparent colors are treated as white currently.

**Comment by ansgarbecker** [comment]
Next build fixes the mentioned crash, and can handle transparent colors now.
Translation is also activated. And I removed the example text box, which was missing the correct colors for some reason.

**Comment by vince-opencity** [comment]
Use the gear dropdown to "Customize highlighter"

![image](https://github.com/HeidiSQL/HeidiSQL/assets/99843706/8ca0411a-5a8b-4987-b308-ce5e31d2922b)
