### ISSUE TITLE
"SQL error(1067); Invalid default value" when renaming BIT(1) columns with default value

### ISSUE THREAD

**Issue by pediRAM** [HeidiSQL/HeidiSQL#1663]
**Preconditions**

* HeidiSQL version: 12.1.0.6537 (64 Bit)
* Database type and version: mysql  Ver 8.0.29 for Win64 on x86_64 (MySQL Community Server - GPL)
* OS: Windows 10 Pro 21H2 (Sys. Build: 19044.1826)

**Describe the bug**
While renaming a boolean column (which is defined as `BIT(1) NOT NULL DEFAULT '\'0\''` ) in the table-design-view of HeidiSQL, I clicked on the save button, which resulted in an error-dialog with the message "SQL error(1067); Invalid default value for 'has_confirmed_registration' "

Just for so some testing, I tried to rename another column with the same definition (only different name), and the result was the same.

**To Reproduce**

**Screenshots or Crash reports**

```sql
SELECT * FROM `radio_stations`.`users` LIMIT 1000;
/* #1634496361: Access violation at address 00000000005DE1FB in module 'heidisql.exe'. Read of address 0000000000000000 Message CharCode:13 Msg:256 */
ALTER TABLE `users`
	CHANGE COLUMN `has_confirmed_registration` `has_con_reg` BIT(1) NOT NULL DEFAULT 'b\'0\'' AFTER `pin`;
/* SQL Fehler (1067): Invalid default value for 'has_con_reg' */
/* #1634496361: Access violation at address 00000056C1800000 in module 'heidisql.exe'. Execution of address 00000056C1800000 Message CharCode:13 Msg:256 */
ALTER TABLE `users`
	CHANGE COLUMN `has_confirmed_registration` `has_conf_reg` BIT(1) NOT NULL DEFAULT 'b\'0\'' AFTER `pin`;
/* SQL Fehler (1067): Invalid default value for 'has_conf_reg' */
/* #1634496361: Access violation at address 00000056C1800000 in module 'heidisql.exe'. Execution of address 00000056C1800000 Message CharCode:13 Msg:256 */
ALTER TABLE `users`
	CHANGE COLUMN `has_confirmed_registration` `has_confirmed_regiration` BIT(1) NOT NULL DEFAULT 'b\'0\'' AFTER `pin`;
/* SQL Fehler (1067): Invalid default value for 'has_confirmed_regiration' */```
```

![1](https://user-images.githubusercontent.com/11803923/190848724-74158f86-93f6-47ce-9985-90fe9deff9e6.png)
![2](https://user-images.githubusercontent.com/11803923/190848738-150d2d23-6541-4e6b-99d2-5f5557da6711.png)

**Comment by pediRAM** [comment]
> Hola, tuve el mismo error, y lo solucioné colocando el valor predeterminado como expresión, en vez de como custom text. El error solo se produce al crear o modificar la tabla (en ese caso se usa expresión). Pero luego, para administrar los valores del campo, funciona perfectamente.
¡Hola!
¡Gracias por la pista!
¿Puedes publicar algún código de ejemplo?

**Comment by ansgarbecker** [comment]
Sorry for the long delay.

Another related thread, in the forum: https://www.heidisql.com/forum.php?t=38149

Issue should be fixed through e028e3f9989b3ca3da214b5d6e785aabfb58e863
Please update and verify the new build 6895 works.
