### ISSUE TITLE
Floating point overflow with SQLite database when row contains Number.MAX in column with REAL data type

### ISSUE THREAD

**Issue by Glodoc** [HeidiSQL/HeidiSQL#1664]
**Preconditions**

* HeidiSQL version: 12.1.0.6537 (but happens also with older versions)
* Database type and version: SQLite 3
* OS: Windows 10

**Describe the bug**

HeidiSQL crashes when data grid view (or result of the select query) contains a row which has Number.MAX (1.7976931348623157e+308) value in a column. Same happens also with negative Number.MAX (-1.7976931348623157e+308). Other database tools doesn't seem to have a problem with this value.

**To Reproduce**
1. Open SQLite database with above mentioned value in some table/row/column
2. Navigate to the table, click on Data tab
3. Crash happens
4. Alternatively paste 1.7976931348623157e+308 into a cell in the data grid for some REAL column
5. Press Post button (ctrl-enter)
6. Crash happens

**Screenshots or Crash reports**

Attached bug report.

[heidi_sql_max_int_bug.txt](https://github.com/HeidiSQL/HeidiSQL/files/9607794/heidi_sql_max_int_bug.txt)

**Comment by ansgarbecker** [comment]
Can confirm that. Happens here also when trying to insert a new value via query:

    INSERT INTO mytable ("myreal") values (1.7976931348623157e+308);

The callstack and the debugger here both say that happens in sqlite3.dll, not in the HeidiSQL code itself. Not sure if that's worth an issue report on sqlite.org?

I also updated the libaries (32 + 64bit) to v3.39.3, without luck - same crash.
