### ISSUE TITLE
Thai language showing incorrect encoding.

### ISSUE THREAD

**Issue by kimdeakung** [HeidiSQL/HeidiSQL#1667]
Preconditions
HeidiSQL version: 12.1.0.6546 (64bit)
Database type and version: MySQL 5.0.51 (MyISAM engine, utf8_unicode_ci)
OS: Windows 11, Windows 10
Describe the bug
HeidiSql showing Thai language encoding not correctly, effected in old version of mysql database like 5.0.51,
 
Screenshots or Crash reports
![Screenshot 2022-09-22 091520](https://user-images.githubusercontent.com/2996623/191643573-b6abc672-48de-44d2-996e-512b9884a452.png)
connect to mysql database v5.0.51, incorrect thai encoding.

![Screenshot 2022-09-22 092107](https://user-images.githubusercontent.com/2996623/191644326-69bc09a3-e4c0-47fe-83fc-6d08161c374c.png)
same version of HeidiSql - connect to MariaDB 10.1.48  thai encoding showing correctly.

**Comment by ansgarbecker** [comment]
Can you create a dump file of that table with mysqldump, so I can check that? Just please remove sensitive information if any.

Also, please post the used dll library for both sessions. (see the session manager) I would recommend to use libmariadb.dll even on older MySQL servers.

**Comment by kimdeakung** [comment]
after i changed the Library

the result:
![Screenshot 2022-09-22 165036](https://user-images.githubusercontent.com/2996623/191716487-aa7123f8-ffc5-49e0-b395-8490d05186e6.png)
a default of library i am use in any MySQL version.  **libmariadb.dll** library is showing result incorrect encode.

![Screenshot 2022-09-22 165110](https://user-images.githubusercontent.com/2996623/191716527-1977e0a6-68c5-4c9c-9095-23d950db84f2.png)
But after i try to use  **libmysql-6.1.dll** or **libmysql.dll** connect to any MySQL version, 
Thai encoding are now showing correctly. (MySQL 5.0.51)

So i think this is about library that i am use when connect.

**Comment by ansgarbecker** [comment]
Thanks for your feedback!

I'd recommend to update the server version. MySQL 5.0.51 is from January 2008 - almost 15 years old.
