### ISSUE TITLE
"Prettify JSON fields"

### ISSUE THREAD

**Issue by aschoijett** [HeidiSQL/HeidiSQL#1669]
**Is your feature request related to a problem? Please describe.**
The content of a JSON field is shown as a long string in the editor.  Making manual changes to it is error prone.
 
**Describe the solution you'd like**
It would be great to have Heidi format the JSON field for readability, with proper indents and new lines. 

**Describe alternatives you've considered**
I prettified the contents of a JSON field manually, but after I save and re-open it, it shows again as a long string.  I assume that this is because how MySQL saves it, but I don't know enough to say. 

**Additional context**

Many thanks!

**Comment by ansgarbecker** [comment]
Delphi's Json support has a reformat feature, so that should be possible, and really makes sense. I'm also reading a lot of Json values each day. Only that needs some button to trigger the reformatting - Heidi should not change anything in the value silently. And that button should be placed left to the new "customize highlighter" button:

![grafik](https://user-images.githubusercontent.com/7986591/192208949-492aea2f-e32f-44f5-be49-c0107ccf8c4e.png)

Does that make sense?

**Comment by ansgarbecker** [comment]
Next build has two new drop-down items on that button:

![grafik](https://user-images.githubusercontent.com/7986591/192485700-cb4003cb-2546-4f6e-8eaa-ea14df1809ae.png)

The "Always" item tells the editor to format JSON or SQL automatically on each start. Note that HeidiSQL in that case modifies the data in the underlying field. If you save modifications, the formatted code will be saved.

**Comment by ansgarbecker** [comment]
Feel free to leave some feedback.

**Comment by ansgarbecker** [comment]
Next build adds a reformatter for XML.

**Comment by aschoijett** [comment]
Hi Angskar,

I noticed that the "prettifier" for JSON reorganizes the content and saves
it differently from what I typed or pasted.  What is the rationale for
this?  I know that the order or the objects should not matter, but since
I'm creating the content outside of Heidi and it appears differently from
what it was when I put it, I thought I should ask.
Many thanks !

PS: I did not check what happens with items in an array, where the order
may matter.

*Alex Schoijett*
Libra Enterprise Consulting <http://www.libragroup.ca>
647-924-7253

**Comment by aschoijett** [comment]
To provide more context:
This is what I create in Notepad++
{

    "ARM": {
        "Name": "Application Reference Model",
        "Value": "Trip To Cash",

        "FieldTypeDataType": "Category Tree",
        "FieldTypeID": 22,
        "ItemTypeID": 87,
        "ItemLineage": "-002J-002N" ,

        "BkgColor": "grey",
        "BarHeight": 15,
        "LineColor": "black",
        "LinePixels": 1
    } ,

    "CurrencyRisk": {
        "Name": "Currency Risk",
        "Value": "Low Risk",

        "FieldTypeDataType": "Item List",
        "FieldTypeID": 2,
        "ItemTypeID": 2,
        "ItemLineage": "-0002" ,

        "BkgColor": "green",
        "BarHeight": 15,
        "LineColor": "black",
        "LinePixels": 1
    } ,

    "Range_Beta": {
        "Name": "Beta",
        "Value": {
            "Start": "2016-10-01",
            "End": "2017-02-29"
        },

        "FieldTypeDataType": "Date Range",
        "FieldTypeID": 29,

        "BkgColor": "grey",
        "BarHeight": 15,
        "LineColor": "black",
        "LinePixels": 1
    },

    "Range_GA": {
        "Name": "General Availability",
        "Value": {
            "Start": "2017-03-01",
            "End": "2023-11-30"
        },

        "FieldTypeDataType": "Date Range",
        "FieldTypeID": 30,

        "BkgColor": "blue",
        "BarHeight": 15,
        "LineColor": "black",
        "LinePixels": 1

    },

    "Range_ExtSupp": {
        "Name": "Extended Support",
        "Value": {
            "Start": "2023-12-01",
            "End": "2028-12-31"
        },

        "FieldTypeDataType": "Date Range",
        "FieldTypeID": 31,

        "BkgColor": "yellow",
        "BarHeight": 15,
        "LineColor": "black",
        "LinePixels": 1
    } ,

    "Date_ExtSuppEnds": {

        "FieldTypeName": "End of Extended Support",
        "Value": "2028-12-31",

        "FieldTypeDataType": "Date",
        "FieldTypeID": 32,

        "icon": "fa-solid fa-rhombus",
        "BkgColor": "red",
        "LineColor": "red",
        "LinePixels": 1
    }
}

I paste this into a JSON field in the database using Heidi, save the field,
and when I reopen it, this is what appears:

[image: image.png]




*Alex Schoijett*
Libra Enterprise Consulting <http://www.libragroup.ca>
647-924-7253
