### ISSUE TITLE
Cannot proceed because system tables used by Event Scheduler were found damaged at server start

### ISSUE THREAD

**Issue by knoxcard** [HeidiSQL/HeidiSQL#167]
## **Error: Cannot proceed because system tables used by Event Scheduler were found damaged at server start**

Any way to just run these commands whenever this error arises?
This fixes it beautifully every time!

**mysqlcheck -u [username] -p --all-databases --check-upgrade --auto-repair
mysql_upgrade -u [username] -p**

https://serverfault.com/questions/100685/cannot-proceed-because-system-tables-used-by-event-scheduler-were-found-damaged/224487#224487

**Comment by ansgarbecker** [comment]
That would only be possible if 
1. the server is installed on the same machine where HeidiSQL runs
2. and HeidiSQL knows where to find mysqlcheck.exe (which is probabably configured in preferences > general)

**Comment by ansgarbecker** [comment]
These commands are nothing HeidiSQL should run automatically.

**Comment by knoxcard** [comment]
Ok, thanks for the wonderful software!!
