### ISSUE TITLE
No longer able to edit or copy more than 256 characters of text

### ISSUE THREAD

**Issue by pauljura** [HeidiSQL/HeidiSQL#1670]
**Preconditions**

* HeidiSQL version: r6547
* Database type and version: MS SQL 13.0
* OS: Windows

**Describe the bug**

I have a table with a TEXT column and the Data grid will truncate to show the first 256 characters (this part is fine). But in version 12.1 and prior, the FULL text was selected whenever I press CTRL-C, and the full text was shown when I press ALT-ENTER to edit. In the nightly, r6547, this is no longer the case and I can only ever copy or edit the first 256 characters as shown in the data grid (I don't know exactly in which version this broke, I just checked the latest nightly and noticed the issue there).

In version 12.1 and prior, there would be a query appear in the logs that shows the application fetching the full text, but in the nightly this is no longer happening.

**To Reproduce**

Pretty easy to reproduce:
1. Make a table with a column with long text
2. Enter more than 256 characters of text
3. Try to copy the cell to clipboard, or edit the text
4. Only the first 256 characters are shown

**Screenshots or Crash reports**

Example table which records HTML emails, in 12.1, you can see the extra query at the bottom of the log that fetches the full data:
![image](https://user-images.githubusercontent.com/42629973/192396422-41dedacc-55b2-4c5d-8d0e-80d25e803def.png)

The same table using the nightly version, you can see the query to fetch full text is missing, and the text editor is showing truncated data:
![image](https://user-images.githubusercontent.com/42629973/192396494-015902d0-3c24-44dc-aea4-7a6e56df27f2.png)

**Comment by ansgarbecker** [comment]
Broken by 47f5058ae30ca27fd63b16e8dafa35121eab36ab

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.
