### ISSUE TITLE
Text Editor truncates text

### ISSUE THREAD

**Issue by stahl-riesa** [HeidiSQL/HeidiSQL#1673]
**Preconditions**

* HeidiSQL version: 12.1.0.6552
* Database type and version: PostgreSQL 13.8.0
* OS: Windows 10

**Describe the bug**

When I double click on a text field to open the text editor for chaning the content, like I always do, I see the shorted table preview version of the text in the editor.

Some days ago, I still works.

I added a picture showing the same field content in HeidiSQL and pgadmin4 to show you the problem.

**To Reproduce**

Select a table, double click on a text field to open the text editor. The visible text is truncated.

**Screenshots or Crash reports**

![heidisql-cutted-text](https://user-images.githubusercontent.com/6726821/193036621-956cccbb-2626-40f0-843a-6824d98a761d.png)

**Comment by stahl-riesa** [comment]
Maybe this is related to that:
https://github.com/HeidiSQL/HeidiSQL/commit/0148564047b616a1e818f80802751d04f6d38b53

**Comment by ansgarbecker** [comment]
Yes my previous attempts to fix a 256-char-bug for MySQL may have broken it for Postgres.
Only I cannot reproduce it here, in a PG table with a TEXT column:

![grafik](https://user-images.githubusercontent.com/7986591/193985927-ad3a069b-19a3-461a-be93-f06d41c7c0b9.png)

Could you post the CREATE code and at least one row (INSERT) for the table in your screenshot?

**Comment by stahl-riesa** [comment]
This is the type defintion of the column: TEXT NULL DEFAULT NULL,

I will try to send you some demo code in the late evening.

**Comment by stahl-riesa** [comment]
```
CREATE TABLE "t_shop_vorlagen" (
	"vorlage_id" SMALLINT NOT NULL,
	"text" TEXT NULL DEFAULT NULL,
	"type_id" SMALLINT NULL DEFAULT NULL,
	"subject" VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY ("vorlage_id")
);

INSERT INTO "t_shop_vorlagen" ("vorlage_id", "text", "type_id", "subject") VALUES
(-13, '##shopname##: Artikel leider ausverkauft
--------------------------------------------------
Ihre Kundendaten:
------------------------------
Ihre Kundennummer: ##kundennummer##
Ihre Bestellnummer: ##bestellnummer##

##anrede##,

wir müssen Sie mit dieser eMail leider über den
Ausverkauf folgender Artikel informieren:

##artikeltabelle##

Es tut uns leid, dass wir die Bestellung nicht zu Ihrer
Zufriedenheit bearbeiten können.

Leider erhalten wir nicht immer die aktuellen Informationen
von den Herstellern zeitnah, so dass wir erst verspätet oder nur nach
Anfrage über Ausverkäufe informiert werden.

Wir entschuldigen uns für die Unannehmlichkeiten und danken
für Ihr Verständnis.


Mit freundlichen Grüßen
Ihr ##shopname##-Team
##shopemail##', 2, NULL),
(-21, 'Willkommen bei ##shopname##!

Vielen Dank, dass Sie sich für unseren Newsletter angemeldet haben.
Ab sofort werden Sie immer als Erstes über Trends, Neuheiten und
exklusive Angebote informiert.

Als Willkommensgeschenk erhalten Sie einen Vorteilscode für Ihren
nächsten Einkauf bei ##shopname##*:

##vorteilscode_hinweis##
Vorteilscode: ##vcode##

*Geben Sie den Vorteilscode im Warenkorb ein. Dieser gilt ab der
Anmeldung 4 Wochen. Der Code ist nicht mit anderen Aktionen kombinierbar.
Keine Barauszahlung möglich.

Mit freundlichen Grüßen
Ihr ##shopname##-Team
##email##', 2, NULL)
```

**Comment by stahl-riesa** [comment]
Thanks. Your fix seems to work. No problems any more by editing long text fields.
