### ISSUE TITLE
Format decimals are not working in Data list / SQL Select

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#1677]
**Preconditions**

* HeidiSQL version: 12.1.0.6555
* Database type and version: Mariadb 10.5.x
* OS: Windows 10 64bits

**Describe the bug**

Format decimals are not working in SQL list / SQL Select

**To Reproduce**

CREATE TABLE IF NOT EXISTS `decimal` (
  `Decimal0` decimal(20,0) DEFAULT NULL,
  `Decimal1` decimal(20,1) DEFAULT NULL,
  `Decimal2` decimal(20,2) DEFAULT NULL,
  `Decimal3` decimal(20,3) DEFAULT NULL,
  `Decimal4` decimal(20,4) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `decimal` (`Decimal0`, `Decimal1`, `Decimal2`, `Decimal3`, `Decimal4`) VALUES
	(1, 1.1, 1.11, 1.111, 1.1111),
	(1, 1.0, 1.00, 1.000, 1.0000),
	(1, 1.0, 1.10, 1.100, 1.1000);

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/11230133/193913699-aa045512-5ce3-4765-8926-b5eed6bd3853.png)
![image](https://user-images.githubusercontent.com/11230133/193913769-4c527621-2292-42a9-b2a8-5936c37e42db.png)

**Comment by ansgarbecker** [comment]
I guess you have the "Max decimal zeros for floats" setting at "1", or?

![grafik](https://user-images.githubusercontent.com/7986591/193985026-7aa29e5f-c251-4e95-b14f-3b6ddbab60b7.png)

See also https://www.heidisql.com/forum.php?t=38775

**Comment by lukinhaspm** [comment]
yes correct, I never changed this.
Thanks and sorry :D
