### ISSUE TITLE
When I type multibyte characters in Windows 11, it crashes after a while

### ISSUE THREAD

**Issue by ryotsukuda333** [HeidiSQL/HeidiSQL#1683]
**Preconditions**

* HeidiSQL version: 12.1.0.6537(64bit) or 11.3.0.6295(32bit)
* Database type and version: MySQL: 5.7.38-google-log or 8.0.26-google
* OS: Windows11

**Describe the bug**

If you describe multibyte characters, such as Japanese, in the place where you describe the query. The operation will stop after some seconds and the application will terminate by itself. You will not be able to enter Japanese or other languages.

Copy and paste works.

**To Reproduce**

1: Connect to DB
2: Enter multibyte characters in the query tab
3: Type in another character, and suddenly the app shuts down.

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/80437495/195543403-4dadd952-7e59-4024-a164-302ccd934f20.png)

**Comment by ryotsukuda333** [comment]
Please confirm T_T

**Comment by ansgarbecker** [comment]
Please try with the default "Windows" style, not a dark style. These styles are prone to many kinds of errors.

**Comment by ryotsukuda333** [comment]
Thanks for the solution!
Sorry for the late reply!

I've changed the style to "windows" as you advised.
but when I type in Japanese
The app is force-closing again (┬﹏┬┬)

Copy and paste can be done in another style.
It works fine!

▽ Modified Style
![image](https://user-images.githubusercontent.com/80437495/196021732-dd51b863-ef9b-4c4b-b367-1c980feaa589.png)

▽queriedita
![image](https://user-images.githubusercontent.com/80437495/196021893-f1f3bd48-0fa9-48f5-8c5c-74df0d1fb551.png)

**Comment by ryotsukuda333** [comment]
I didn't have a problem with windows 10 either!
It's happening since I upgraded to windows 11.

**Comment by ryotsukuda333** [comment]
Fixed!
After a new BIOS update on this PC, I was able to type multibyte characters without any problems.
I am happy to report that.

Current PC information
```
processor: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz
edition: indows 11 Pro
version: 22H2
OS build: 22621.819
```

**Comment by ansgarbecker** [comment]
Oh, did not expect that it was the BIOS. Good find!
Thanks for the update.
