### ISSUE TITLE
Features request

### ISSUE THREAD

**Issue by miteshkothari3319** [HeidiSQL/HeidiSQL#1684]
**Is your feature request related to a problem? Please describe.**
I face a major problem is to see multiple tables in the same window.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/72382861/195550225-c3c8d2e0-9600-41dc-b7d5-5835e3a4151c.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment]
This is just the user inteface how it is in HeidiSQL. Removing the database tab is not something I will consider, as well as the data tab.

By the way, there is a "search table" feature, and a separate "search database" feature:

![grafik](https://user-images.githubusercontent.com/7986591/195564368-7cb5a5bf-f828-4f74-bfdf-a91588ab814d.png)

**Comment by miteshkothari3319** [comment]
Great!
