### ISSUE TITLE
Running on MacOS

### ISSUE THREAD

**Issue by raselldev** [HeidiSQL/HeidiSQL#1687]
Dear Developer,

Hello i using HeidiSQL since 2016 on my personal potato PC. Now i use MacOS as daily driver for development.

For now, can HeidiSQL support on MacOS?

**Comment by sja81** [comment]
I'm joining with this wish too. Would be good to have HeidiSQL under MacOS.

**Comment by ansgarbecker** [comment]
See #13 for reasons why a Mac port of HeidiSQL would be a rewrite from the scratch.
I don't have the time to do that.
