### ISSUE TITLE
Scaling of text areas is wrong in certain situations with multi-monitor setup and different scaling factors

### ISSUE THREAD

**Issue by ilpssun** [HeidiSQL/HeidiSQL#1692]
**Preconditions**

* HeidiSQL version: 12.1.0.6537
* Database type and version: various, irrelevant
* OS: Windows 11 (22H2, Build 22621.674)

**Describe the bug**
Scaling of text areas is wrong in certain situations with multi-monitor setup and different scaling factors.

**To Reproduce**
Create wrong display issue:
1. Go to built-in display with scaling = 125% and launch Heidi.
2. Notice that log says “scaling components to 125%” (`/* Skaliere Komponenten auf Bildschirm DPI: 125% */`); everything looks ok.
3. Move window to second display with scaling = 100%
4. Notice that log says “scaling components to 80%” (`/* Skaliere Komponenten auf Bildschirm DPI: 80% */`), which is incorrect.  Toolbars and application itself look good, but all text areas (sql editor, log view, results table) are too small.

Similar steps that *do not* reproduce issue:
1. Launch Heidi on the second screen with scaling = 100%
2. Scaling is correctly detected as 100%; everything renders fine.
3. Move Heidi to built-in screen with scaling = 125%.
4. Notice that log says “scaling components to 125%” (`/* Skaliere Komponenten auf Bildschirm DPI: 125% */`); *everything still looks ok.*
5. Move window to second display with scaling = 100%
6. Notice that log says “scaling components to 80%” (`/* Skaliere Komponenten auf Bildschirm DPI: 80% */`), which is incorrect.
7. Notice that even so, the textareas are scaled correctly.

**Screenshots or Crash reports**
![image](https://user-images.githubusercontent.com/835280/198206104-8939f832-4af6-48ca-818a-5f61251183e6.png)
![image](https://user-images.githubusercontent.com/835280/198206131-dfbf0405-057e-420c-ad7b-4b479d7066cf.png)

**Comment by ansgarbecker** [comment]
Please note that the SQL editors and grids have their own font size, which can easily be zoomed using <kbd>Ctrl+Mousewheel</kbd>.
Also, please test whether the issue persists after restarting HeidiSQL. There are some known issues when you move between monitors with different DPI settings.

**Comment by ilpssun** [comment]
Today, I cannot reproduce the issue.  Maybe my graphics driver was updated or some other windows update has resolved it.  As it is no big deal to begin with, I'll close the issue.
