### ISSUE TITLE
Can't see the total number of interogation lines when importing sql if window is minimized (a white square appears over)

### ISSUE THREAD

**Issue by CraftedRO** [HeidiSQL/HeidiSQL#1693]
**Preconditions**

* HeidiSQL version: 12.1.0.6564
* Database type and version: MariaDB-10.4.10
* OS: Windows 10x64
* Windows 10 SlateGray theme
* ro_RO language

**Describe the bug**

When you run a query you can't see the total number of it in right downside corner if the window is minimized , it appear a white square over.

**To Reproduce**

Connect to a database
Minimize the heidisql
Run a long query
Try to ajust window size to see the bug while the query running

**Screenshots or Crash reports**

![heidisql](https://user-images.githubusercontent.com/24683355/199216772-9c9b7f4b-b311-4715-a3bb-58ce12bc823e.PNG)

**Comment by CraftedRO** [comment]
Seems like same white square does appear on the right scrolling editor thing too if resized too much:

![sqsq](https://user-images.githubusercontent.com/24683355/199308489-a73c8b95-b14e-4fc0-a82f-05b30d16e407.PNG)

**Comment by ansgarbecker** [comment]
Yes, these styles have quite a few cosmetic issues. I can't do much here I'm afraid.
