### ISSUE TITLE
Crash when importing .sql exported data

### ISSUE THREAD

**Issue by CraftedRO** [HeidiSQL/HeidiSQL#1695]
**Preconditions**

* HeidiSQL version: 12.1.0.6564
* Database type and version: MySQL 8.0.28
* OS: Windows 10x64

**Describe the bug**
It does crash everytime when I try to import specific exported.sql file with heidisql from mariadb to mysql.

**To Reproduce**
I can upload sql file if needed.

**Screenshots or Crash reports**
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/9911590/bugreport.txt)

**Comment by ansgarbecker** [comment]
Please describe more exactly:
* did you import that file by loading it into an editor, or did you use File > Run SQL file?
* are you using a theme other than the default "Windows" theme? (e.g. a dark theme)

**Comment by CraftedRO** [comment]
I drag and droped the file then press execute button.
Yes I use Windows 10 SlateGray theme.

**Comment by ansgarbecker** [comment]
Then please retry with the default Windows theme in Preferences > General > Style/Theme. Don't mix it up with "Windows 10" by the way.
If the crash does not appear with that Windows theme, the crash is theme related.

**Comment by CraftedRO** [comment]
With default theme seems ok from my latest tests.

**Comment by CraftedRO** [comment]
Today it crashed with default theme , with clean portable version and default settings:

![sqsq](https://user-images.githubusercontent.com/24683355/199964653-321d6e63-b7bd-4cc1-b635-87bbe6cbdfd5.PNG)
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/9937860/bugreport.txt)

I have to mention that database was also opened in other application too.

**Comment by ansgarbecker** [comment]
I see the callstack but I cannot reproduce that crash here. I also see there was a automatic reconnect on your side when you made the screenshot.
Can you post the imported sql file here? Only if it does not contain sensitive information.

**Comment by CraftedRO** [comment]
its actually public as gist atm here : https://gist.github.com/CraftedRO/c3dd3b3d43d59e732635ca6fe0666a7a

**Comment by ansgarbecker** [comment]
Thanks, I see there is nothing special in it, just UPDATEs.
I still could not reproduce the issue, so I am blindly trying things now.
I just made the check before the crash happens more robust. Please update to build 6566 and retry.

**Comment by CraftedRO** [comment]
still crash most likely is related to that other issue when you have multiple apps connected to same database

![sqsq](https://user-images.githubusercontent.com/24683355/200054411-b0a58adc-1655-4886-a5a1-cf13d425280b.PNG)

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/9941310/bugreport.txt)

I can also let you on my computer with remote or smth if you think that it helps.

**Comment by CraftedRO** [comment]
Today it crashed even without other apps be connected to database , only heidi.

Is there a chance to be related with innodb_buffer_pool_size = 1024M

**Comment by CraftedRO** [comment]
Today it crashed even without other apps be connected to database , only heidi.

Is there a chance to be related with innodb_buffer_pool_size = 1024M ?
