### ISSUE TITLE
Crash when launch the HeidiSQL main application

### ISSUE THREAD

**Issue by madafoo** [HeidiSQL/HeidiSQL#1696]
**Preconditions**

* HeidiSQL version: 12.1.0.6565
* Database type and version: N/A
* OS: Win11 21H2 22000.1098

**Describe the bug**

Latest heidiSQL will not launch on the win11.

**To Reproduce**

1. Click on the heidisql icon to launch the application, nothing happen and after a while, a new application crash log appear in the windows event log.

**Screenshots or Crash reports**

This is what I found in the windows 11 event log.

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-11-03T03:17:50.9161537Z" /> 
  <EventRecordID>202860</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="15816" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>MSI</Computer> 
  <Security /> 
  </System>
  <EventData>
  <Data>heidisql.exe</Data> 
  <Data>12.1.0.6565</Data> 
  <Data>6362b638</Data> 
  <Data>unknown</Data> 
  <Data>0.0.0.0</Data> 
  <Data>00000000</Data> 
  <Data>c0000005</Data> 
  <Data>0000000005430987</Data> 
  <Data>26c0</Data> 
  <Data>01d8ef32dab185a9</Data> 
  <Data>D:\Tools\HeidiSQL\heidisql.exe</Data> 
  <Data>unknown</Data> 
  <Data>7ea5e44b-8ac8-408b-aba7-6510e05bf2a6</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>
```

**Comment by ansgarbecker** [comment]
No problem in Windows 10 here. I'll test on Win 11 as well.

**Comment by madafoo** [comment]
Some update might help for this issue. I have download the 12.0 heidisql from the official website. This old version works on the same win11 system.
Again use the 12.1 downloaded from the website, it crashed again.

**Comment by ansgarbecker** [comment]
v12.2 runs as well here, on the same Win11 version, although in a HyperV box:

![grafik](https://user-images.githubusercontent.com/7986591/204365099-829da187-b063-40de-9a13-4a8900a5286d.png)

**Comment by ansgarbecker** [comment]
Was it probably only the portable version which crashed?

**Comment by ansgarbecker** [comment]
Meanwhile I upgraded my system to Win11, and still can run HeidiSQL normally.
Please re-test with v12.3, and if possible also test the installer, to compare it to the portable version.

**Comment by madafoo** [comment]
Because the latest v12.4.0 has already fix the problem, so close this issue.
