### ISSUE TITLE
CSV Import Crash on detecting CSV Format

### ISSUE THREAD

**Issue by MyIDisMine** [HeidiSQL/HeidiSQL#1698]
**Preconditions**

* HeidiSQL version: 12.1.0.6537 (64 bits)
* Database type and version: MySQL 10.3.34-MariaDB-0+deb10u1 - Raspbian 10 
* OS: Windows 10

**Describe the bug**

When you try to import a CSV file with the dedicated tool, you then choose table and "create a new table", it should scan the file and provide a suggestion of the fields to create the table. Instead the application crashes.
Does for some CSV files not all of them.

**To Reproduce**

Tools > Import CSV File > choose the CSV File to import and propoer settings (coma fields separation) > choose the database > and then table and "Create a new table", see it crash...
**Screenshots or Crash reports**

Here is the bugreport of the crash :
date/time          : 2022-11-06, 20:54:43, 362ms
computer name      : TOSHIBA
user name          : Toshiba
registered owner   : Toshiba
operating system   : Windows 10 x64 build 19044
system language    : French
system up time     : 18 days 22 hours
program up time    : 1 minute 40 seconds
processors         : 4x Intel(R) Core(TM) m5-6Y54 CPU @ 1.10GHz
physical memory    : 3564/8114 MB (free/total)
free disk space    : (C:) 75,73 GB
display mode       : 1536x864, 32 bit
process id         : $3b00
allocated memory   : 105,05 MB
largest free block : 131025,95 GB
executable         : heidisql.exe
exec. date/time    : 2022-08-13 08:06
version            : 12.1.0.6537
compiled with      : Delphi 11
madExcept version  : 5.1.2
callstack crc      : $e5c2ca09, $5473dd9a, $5473dd9a
exception number   : 1
exception class    : EArgumentOutOfRangeException
exception message  : Argument out of range.

main thread ($e9c):
00f54275 heidisql.exe csv_detector   244 +25 TfrmCsvDetector.DetectColumnAttributes
00f53bbf heidisql.exe csv_detector   194 +73 TfrmCsvDetector.btnScanClick
007a8e30 heidisql.exe Vcl.ExtCtrls           TTimer.Timer
007a8c58 heidisql.exe Vcl.ExtCtrls           TTimer.WndProc
005d2033 heidisql.exe System.Classes         StdWndProc
7fff496e USER32.dll                          DispatchMessageW
0084a18e heidisql.exe Vcl.Forms              TApplication.ProcessMessage
0084a203 heidisql.exe Vcl.Forms              TApplication.HandleMessage
0084314f heidisql.exe Vcl.Forms              TCustomForm.ShowModal
00f57d28 heidisql.exe loaddata       263  +5 Tloaddataform.comboTableChange
006e7c99 heidisql.exe Vcl.StdCtrls           TCustomCombo.Change
006e6d3f heidisql.exe Vcl.StdCtrls           TCustomComboBox.Change
006e8097 heidisql.exe Vcl.StdCtrls           TCustomCombo.Select
006e7bc3 heidisql.exe Vcl.StdCtrls           TCustomCombo.CNCommand
0040f2a2 heidisql.exe System                 TObject.Dispatch
006b041d heidisql.exe Vcl.Controls           TControl.WndProc
006b788b heidisql.exe Vcl.Controls           TWinControl.WndProc
006e79fd heidisql.exe Vcl.StdCtrls           TCustomCombo.WndProc
006ea660 heidisql.exe Vcl.StdCtrls           TCustomComboBox.WndProc
006aff10 heidisql.exe Vcl.Controls           TControl.Perform
006b7a69 heidisql.exe Vcl.Controls           DoControlMsg
006b8c43 heidisql.exe Vcl.Controls           TWinControl.WMCommand
0040f2a2 heidisql.exe System                 TObject.Dispatch
006b041d heidisql.exe Vcl.Controls           TControl.WndProc
006b788b heidisql.exe Vcl.Controls           TWinControl.WndProc
006b6a2a heidisql.exe Vcl.Controls           TWinControl.MainWndProc
005d2033 heidisql.exe System.Classes         StdWndProc

Here is the content of the CSV File that causes the crash
System,Mass Code,System Stars,Primary Star Type,Primary Star Spectral Class,Primary Star Luminosity,Primary Star Age,Parent Star,Parent Star Type,Parent Star Spectral Class,Parent Star Luminosity,Parent Star Age,Parent Body,Parent Body Type,Parent Landable,Parent Terraformable,Planet Name,Landable,Orbit Type,Type,Rings,RingTypes,Arrival Distance,Terraforming State,Radius,Earth Masses,Surface Gravity,Surface Temperature,Surface Pressure,Volcanism,Atmosphere,Axial Tilt,Rotational Period,Tidally Locked,Orbital Period,Semi-major Axis,Orbital Eccentricity,Orbital Inclination,Arg. of Periapsis,Mean Anomaly,Longitude of Ascending Node,Coord X,Coord Y,Coord Z,Timestamp
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 1,no,planetary,Helium gas giant,2,"Metal Rich (1), Rocky (1)",159.1263427734,Not terraformable,34909.228,3194.1672363281,106.528503418,1701,0,No volcanism,,-0.426678,50.491792564063,yes,49.253645594468,0.318807371075,0.000264,5.1e-05,197.531745,161.633127,,-131.469,115.094,44,2020-03-15 11:05:01
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 10,no,planetary,Helium gas giant,0,"",4319.4770507813,Not terraformable,33473.582,2124.8806152344,77.075958252,630,0,No volcanism,,0.366044,0.661159205104,no,757.119114752164,0.198237339673,0.127965,-8.117439,222.006778,1.102921,,-131.469,115.094,44,2020-03-15 11:04:45
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 11,no,planetary,Helium gas giant,1,"Metal Rich (1)",5541.982421875,Not terraformable,21340.11,5781.1010742188,515.948059082,1690,0,No volcanism,,-0.255994,1.727142833727,no,10178.4751922996,11.143576051007,0.005175,13.653927,311.236803,310.797828,,-131.469,115.094,44,2020-03-15 11:05:42
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 3,no,planetary,Helium gas giant,2,"Metal Rich (2)",836.2499389648,Not terraformable,34588.424,2686.9555664063,91.2825164795,1024,0,No volcanism,,-0.20475,55.774730905868,yes,33.463136189514,0.017026523079,0.003481,-2.064356,124.352002,138.155995,,-131.469,115.094,44,2020-03-15 11:05:35
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 4,no,planetary,Helium gas giant,2,"Metal Rich (1), Rocky (1)",812.9218139648,Not terraformable,38216.892,1511.1413574219,42.051651001,737,0,No volcanism,,-0.09793,41.827719174641,yes,33.463136189514,0.030274184991,0.003481,-2.064356,304.351997,138.101939,,-131.469,115.094,44,2020-03-15 11:05:32
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 5,no,planetary,Helium gas giant,0,"",1157.28125,Not terraformable,36828.14,2137.3110351563,64.0467224121,799,0,No volcanism,,0.052728,1.766553131678,no,966.258050390972,2.318986335075,0.000102,-1.035645,24.643722,144.256541,,-131.469,115.094,44,2020-03-15 11:04:23
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 6,no,planetary,Helium gas giant,2,"Metal Rich (1), Rocky (1)",1503.6811523438,Not terraformable,37295.756,2121.1420898438,61.978302002,751,0,No volcanism,,-0.429068,1.65950137706,no,1431.47597986238,3.01364540681,0.000416,0.078868,273.835289,76.822566,,-131.469,115.094,44,2020-03-15 11:05:22
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 7,no,planetary,Helium gas giant,2,"Metal Rich (1), Rocky (1)",2118.6384277344,Not terraformable,25308.634,3749.5632324219,237.9205627441,1153,0,No volcanism,,-0.18771,0.755032978171,no,2393.30350800796,4.24523127887,0.001646,-0.075045,112.656495,266.022234,,-131.469,115.094,44,2020-03-15 11:04:54
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis 7,Helium gas giant,no,no,52 Herculis 7 a,no,moon,Helium gas giant,1,"Rocky (1)",2123.0717773438,Not terraformable,65354.62,284.4737854004,2.7069387436,325,0,No volcanism,,-0.244306,105.243145496817,yes,101.460951069988,0.097782114268,0,85.344067,355.791435,285.915626,,-131.469,115.094,44,2020-03-15 11:04:57
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 8,no,planetary,Helium gas giant,0,"",3266.333984375,Not terraformable,35226.84,2291.6435546875,75.0565338135,693,0,No volcanism,,0.335449,1.116243651227,no,4582.98927104031,6.546392184815,0.000165,4.659913,136.389449,50.022951,,-131.469,115.094,44,2020-03-15 11:05:10
52 Herculis,D,single,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,A5,V,1730,52 Herculis,A (Blue-White) Star,,,52 Herculis 9,no,planetary,Helium gas giant,0,"",4189.7387695313,Not terraformable,32216.646,2266.3415527344,88.746963501,666,0,No volcanism,,-0.461671,1.061593173194,no,757.119114752164,0.185866721593,0.127965,-8.117439,42.006801,1.102879,,-131.469,115.094,44,2020-03-15 11:04:37
Boeths MM-S b22-31,B,multiple,M (Red dwarf) Star,M2,Va,6860,Boeths MM-S b22-31 A,M (Red dwarf) Star,M2,Va,6860,Boeths MM-S b22-31 A,M (Red dwarf) Star,,,Boeths MM-S b22-31 A 6,no,planetary,Helium gas giant,2,"Icy (1), Metal Rich (1)",2102.3483886719,Not terraformable,16762.012,9.0039339066,1.3024730682,53,0.788738742906,No volcanism,,-0.381479,0.959398982813,no,5015.50195945634,4.212359287669,0.000195,0.131229,263.881705,151.983816,,-2698.03,-370.219,16060.6,2022-04-12 12:40:52
HR 6870,F,single,B (Blue-White super giant) Star,B8,II,2,HR 6870 11,T Tauri Star,TTS3,VI,2,HR 6870 11,T Tauri Star,,,HR 6870 11 a,no,moon of star,Helium gas giant,0,"",3844.3273925781,Not terraformable,73540.656,1723.8790283203,12.9550943375,691,0,No volcanism,,0.424777001143,0.517331237708,no,192.820756799641,0.320437461783,0,-47.857448,90.885694,83.113931,,25.5,-107.906,545.438,2016-12-12 23:00:40
HR 6870,F,single,B (Blue-White super giant) Star,B8,II,2,HR 6870 12,T Tauri Star,TTS7,VI,2,HR 6870 12,T Tauri Star,,,HR 6870 12 a,no,moon of star,Helium gas giant,0,"",5372.0366210938,Not terraformable,69939.064,2457.232421875,20.4171619415,854,0,No volcanism,,-0.083185002208,0.972253159514,no,178.927810931644,0.337976262599,0,-19.641353,304.501192,109.351322,,25.5,-107.906,545.438,2016-12-12 23:05:02
HR 6870,F,single,B (Blue-White super giant) Star,B8,II,2,HR 6870 8,T Tauri Star,TTS0,VI,2,HR 6870 8,T Tauri Star,,,HR 6870 8 a,no,moon of star,Helium gas giant,0,"",1436.1711425781,Not terraformable,75900.72,655.8972167969,4.6273541451,667,0,No volcanism,,0.429960012436,30.696828754919,yes,30.12353209434,0.071275340292,0,57.701056,85.930518,5.281206,,25.5,-107.906,545.438,2016-12-12 22:57:54
Ooch Chrea US-U d2-21,D,single,G (White-Yellow) Star,G1,Vab,1392,Ooch Chrea US-U d2-21,G (White-Yellow) Star,G1,Vab,1392,Ooch Chrea US-U d2-21,G (White-Yellow) Star,,,Ooch Chrea US-U d2-21 2,no,planetary,Helium gas giant,1,"Icy (1)",3683.5478515625,Not terraformable,18022.848,11.9483070374,1.4950243235,93,731.200394769307,No volcanism,,-0.401956,1.331895442951,no,6659.27871509834,7.288305503412,0.013019,-0.307019,271.148599,190.005609,,589.812,2541.38,27353.3,2020-03-12 04:38:33
Swuemuia EJ-L c10-0,C,single,K (Yellow-Orange) Star,K0,Vab,10142,Swuemuia EJ-L c10-0,K (Yellow-Orange) Star,K0,Vab,10142,Swuemuia EJ-L c10-0,K (Yellow-Orange) Star,,,Swuemuia EJ-L c10-0 4,no,planetary,Helium gas giant,0,"",2132.9194335938,Not terraformable,19159.362,15.3061408997,1.6946982145,113,30887.2179620035,No volcanism,,0.047881,1.983128039387,no,3754.39164539178,4.279900519125,0.001394,0.005823,70.742885,338.618404,,-11145.5,-296.25,49322.3,2022-04-25 21:22:09

**Comment by MyIDisMine** [comment]
[Helium-gas-giants.csv](https://github.com/HeidiSQL/HeidiSQL/files/9954586/Helium-gas-giants.csv)


CSV file that goes wrong...

**Comment by MyIDisMine** [comment]
Got the same result with a 7 system...

date/time          : 2022-11-07, 19:59:06, 565ms
computer name      : ALEK-PC
user name          : ALEK
registered owner   : ALEK
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : French
system up time     : 1 day 11 hours
program up time    : 56 seconds
processors         : 6x AMD Phenom(tm) II X6 1090T Processor
physical memory    : 11224/16375 MB (free/total)
free disk space    : (C:) 43,50 GB
display mode       : 1920x1080, 32 bit
process id         : $1d00
allocated memory   : 120,71 MB
largest free block : 8181,15 GB
executable         : heidisql.exe
exec. date/time    : 2022-08-13 08:06
version            : 12.1.0.6537
compiled with      : Delphi 11
madExcept version  : 5.1.2
callstack crc      : $e5c2ca09, $1f65b2e6, $1f65b2e6
exception number   : 1
exception class    : EArgumentOutOfRangeException
exception message  : Argument out of range.

main thread ($2fd4):
00f54275 heidisql.exe csv_detector   244 +25 TfrmCsvDetector.DetectColumnAttributes
00f53bbf heidisql.exe csv_detector   194 +73 TfrmCsvDetector.btnScanClick
007a8e30 heidisql.exe Vcl.ExtCtrls           TTimer.Timer
007a8c58 heidisql.exe Vcl.ExtCtrls           TTimer.WndProc
005d2033 heidisql.exe System.Classes         StdWndProc
77319935 USER32.dll                          DispatchMessageW
0084a18e heidisql.exe Vcl.Forms              TApplication.ProcessMessage
0084a203 heidisql.exe Vcl.Forms              TApplication.HandleMessage
0084314f heidisql.exe Vcl.Forms              TCustomForm.ShowModal
00f57d28 heidisql.exe loaddata       263  +5 Tloaddataform.comboTableChange
006e7c99 heidisql.exe Vcl.StdCtrls           TCustomCombo.Change
006e6d3f heidisql.exe Vcl.StdCtrls           TCustomComboBox.Change
006e8097 heidisql.exe Vcl.StdCtrls           TCustomCombo.Select
006e7bc3 heidisql.exe Vcl.StdCtrls           TCustomCombo.CNCommand
0040f2a2 heidisql.exe System                 TObject.Dispatch
006b041d heidisql.exe Vcl.Controls           TControl.WndProc
006b788b heidisql.exe Vcl.Controls           TWinControl.WndProc
006e79fd heidisql.exe Vcl.StdCtrls           TCustomCombo.WndProc
006ea660 heidisql.exe Vcl.StdCtrls           TCustomComboBox.WndProc
006aff10 heidisql.exe Vcl.Controls           TControl.Perform
006b7a69 heidisql.exe Vcl.Controls           DoControlMsg
006b8c43 heidisql.exe Vcl.Controls           TWinControl.WMCommand
0040f2a2 heidisql.exe System                 TObject.Dispatch
006b041d heidisql.exe Vcl.Controls           TControl.WndProc
006b788b heidisql.exe Vcl.Controls           TWinControl.WndProc
006b6a2a heidisql.exe Vcl.Controls           TWinControl.MainWndProc
005d2033 heidisql.exe System.Classes         StdWndProc
7744bc61 ntdll.dll                           KiUserCallbackDispatcher

**Comment by ansgarbecker** [comment]
Fixed in the next build
