### ISSUE TITLE
make window interactive while opening a db with long list of table

### ISSUE THREAD

**Issue by CephalidOne** [HeidiSQL/HeidiSQL#1699]
**Is your feature request related to a problem? Please describe.**

just started working at a new organization and they have a db with 4000 (not an error four thousand) tables, heidi freezes up while filling the db treeview.

**Describe the solution you'd like**

i would like to continue working while the treeview populate

**Describe alternatives you've considered**

start opening only starred tables if active and fill the rest in background

**Additional context**

the db is remote so slow connection might be an additional problem, same db in MS SQL Server open in a snap

**Comment by Bens-ct** [comment]
On the session manager > advanced tab, you can disable get full table status which will speed things up a bit for you.

**Comment by CephalidOne** [comment]
thanks for your response, it works like a charm
