### ISSUE TITLE
Clear query history on "query" node runs exception

### ISSUE THREAD

**Issue by rentalhost** [HeidiSQL/HeidiSQL#170]
## Steps to reproduce this issue

1. Step 1; go to Query tab;
2. Step 2; on right side of screen, open the "Query history" node, then some date node;
3. Step 3; right-click on some query node and select "clear query history" option.

## Current behavior

Exception (attached).

## Expected behavior

1. Clear all history;
2. Clear only selected query node (as #171);

## Environment

* **HeidiSQL version:** 9.5.5254
* **Database system and version:** -
* **Operating system:** Win10 x64
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1767986/bugreport.txt)

**Comment by ansgarbecker** [comment]
See #168
