### ISSUE TITLE
Shift+delete not working for cut

### ISSUE THREAD

**Issue by Nils-Berghs** [HeidiSQL/HeidiSQL#1702]
**Preconditions**

* HeidiSQL version: 12.1.0.6537
* Database type and version: All types and versions
* OS: Windows 10

**Describe the bug**

Short version: In the Query editor, Shift+Delete does not cut the selected text as it should. In preferences it is not possible to assign shift+delete to any action so that isn't a help. The copy and paste shortcuts (ctrl+insert and shift+insert) are working.

Long version: Shift+Delete is THE cut shortcut, it is largely replaced by ctrl+x, for right handed mouse users, but there are also left handed people out there, so Shift+Delete should always be CUT (so yes Windows does this wrong for many years). 
If you think this is low prio, build a version where ctrl+x does not work for cut and see how long you manage... As a reminder:  software that isn't tested by left handed mouse users is not tested at all!

**To Reproduce**

1. Open table
2. Go to 'Query' tab
3. Select part of the query
4. Press shift+delete
5. Nothing happens

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
I recently fixed the shortcut customizer in the preferences dialog, so you should now be able to assign some hotkey with the <kbd>Del</kbd> key. Please update to the latest build and try that.

**Comment by Nils-Berghs** [comment]
I somehow forgot about this, until I had to work on a machine where an old version was installed. After updating to the latest version, it works perfectly.
