### ISSUE TITLE
Unable to export data from PostgreSQL

### ISSUE THREAD

**Issue by AntoineBW** [HeidiSQL/HeidiSQL#1704]
**Preconditions**

* HeidiSQL version: 12.2.0.6576
* Database type and version: Postgres 14.5-alpine
* OS: Windows 11

**Describe the bug**

I can't export data from my Postgres database (official docker image) with HeidiSQL.

**To Reproduce**

1. Right click on "public" table 
2. Export in SQL
3. .sql unique file
4. Button Export

**Screenshots or Crash reports**

<img width="606" alt="image" src="https://user-images.githubusercontent.com/111440413/202436816-b054c2ad-c19f-4a79-b21c-bead678d5e44.png">

**Comment by ansgarbecker** [comment]
Yes, the SQL export is mostly incompatible with other modes than MySQL/MariaDB. Though a data-only export should work at least.
