### ISSUE TITLE
RDS kill query

### ISSUE THREAD

**Issue by Bens-ct** [HeidiSQL/HeidiSQL#1705]
**Is your feature request related to a problem? Please describe.**
RDS databases don't use the standard MySQL kill query, instead you have to call an rds specific proceedure with the process id, e.g., CALL mysql.rds_kill( 640);

**Describe the solution you'd like**
I tend to kill quite a few queries in Heidi and love how easy it is to quickly sort, select & kill is really useful, although obviously it doesn't work on RDS. It would be really helpful if Heidi identified when it's connected to an RDS database and used the rds.kill logic instead.

**Describe alternatives you've considered**
The only alternative at the moment is to construct the required queries and run them which takes times.

**Additional context**
I'm not the only one, I've seen a few requests for this on the forum over the years, but can't see anything on the tracker thus far.

Thanks in advance :)

**Comment by Bens-ct** [comment]
Unfortunately the version just shows as 8.0.29
There are these which give it away,

session_variables
---
| Variable_name | Value | 
| --- | --- | 
| basedir | /rdsdbbin/mysql-8.0.29.R7/ | 
| character_sets_dir | /rdsdbbin/mysql-8.0.29.R7/share/charsets/ | 
| datadir | /rdsdbdata/db/ | 
| general_log_file | /rdsdbdata/log/general/mysql-general.log | 
| innodb_data_home_dir | /rdsdbdata/db/innodb | 
| innodb_log_group_home_dir | /rdsdbdata/log/innodb | 
| lc_messages_dir | /rdsdbbin/mysql-8.0.29.R7/share/ | 
| log_bin_basename | /rdsdbdata/log/binlog/mysql-bin-changelog | 
| log_bin_index | /rdsdbdata/log/binlog/mysql-bin-changelog.index | 
| log_error | /rdsdbdata/log/error/mysql-error.log | 
| pid_file | /rdsdbdata/log/mysql-3306.pid | 
| plugin_dir | /rdsdbbin/mysql-8.0.29.R7/lib/plugin/ | 
| relay_log | /rdsdbdata/log/relaylog/relaylog | 
| relay_log_basename | /rdsdbdata/log/relaylog/relaylog | 
| relay_log_index | /rdsdbdata/log/relaylog/relaylog.index | 
| slow_query_log_file | /rdsdbdata/log/slowquery/mysql-slowquery.log | 
| ssl_ca | /rdsdbdata/rds-metadata/ca-cert.pem | 
| ssl_cert | /rdsdbdata/rds-metadata/server-cert.pem | 
| ssl_key | /rdsdbdata/rds-metadata/server-key.pem | 
| tmpdir | /rdsdbdata/tmp | 

I am not sure if they are useful or subject to change though, will do some further digging to see if there is an "official" way to identify when you are connected to an RDS instance.

**Comment by Bens-ct** [comment]
Doesn't look like there is any other way to detect that it is RDS but those paths appear to have been consitent for 10+ years.

**Comment by ansgarbecker** [comment]
What I could do is provide a new network type "MySQL RDS" or something, let it inherit evertyhing from MySQL, except for that one kill query. That way, the user just has to select the right network type to use that.
But I will need some unique 100x100px icon for RDS + MySQL

**Comment by Bens-ct** [comment]
Sounds like a good way to do it to me.  Our designed knocked up this icon that combines the RDS icon with the MySQL logo, hopefully this will suffice.
![rds_sql_icon](https://user-images.githubusercontent.com/100347181/203295308-644fbff4-7cf5-4356-a8d4-f56b22cbf756.png)

**Comment by ansgarbecker** [comment]
I suppose in most cases RDS MySQL needs to have a SSH tunnel, right?
At least from what I read here: https://stackoverflow.com/questions/37095433/heidisql-cant-connect-to-my-rds-database

**Comment by ansgarbecker** [comment]
Thanks for your icon!

Next build provides the new network type with your icon, and uses the above mentioned procedure to kill a process:
![grafik](https://user-images.githubusercontent.com/7986591/203627794-7361a622-7ce7-42be-a768-feb37e4b6101.png)

I wonder whether the syntax for `KILL QUERY x` is the same as for killing a process, or does that still work?
Unfortunately I have no RDS server to test this out. Would be good to get some feedback.

(Note that the current build updater may still be broken, so in case "Help > Check for updates" does not update, download the new build from the [website](https://www.heidisql.com/download.php))

**Comment by Bens-ct** [comment]
Downloaded and tested, works well thank you so much, this will make life much easier :).

Checking the docs rds_kill appears to be the same as kill xxx, i.e. it kills the thread.  rds_kill_query is the equivelent of kill query xxx.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql_rds_kill.html
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql_rds_kill_query.html

**Comment by ansgarbecker** [comment]
Done in the next build.

**Comment by KENNYSOFT** [comment]
> I suppose in most cases RDS MySQL needs to have a SSH tunnel, right? At least from what I read here: https://stackoverflow.com/questions/37095433/heidisql-cant-connect-to-my-rds-database

Well, no, if someone is using a VPN like me, he/she can directly access via TCP/IP. Adding an SSH tunnel even if attached to the VPN adds more hops and makes performance degraded.
