### ISSUE TITLE
BIT data type

### ISSUE THREAD

**Issue by YitzchakK** [HeidiSQL/HeidiSQL#1708]
**Preconditions**

* HeidiSQL version:12.2.0.6576
* Database type and version: mySQL
* OS: Win10 64-bit

**Describe the bug**

**To Reproduce**

**Screenshots or Crash reports**

**Comment by YitzchakK** [comment]
I cannot update any BIT data type field. 0 to 1 or 1 to 0 does not work. Error: 1054

**Comment by ansgarbecker** [comment]
Duplicate of #1709

Fixed in coming build.
