### ISSUE TITLE
Missing quotes blocking edit of BIT(1) field following recent update in "Data" tab.

### ISSUE THREAD

**Issue by tobestool** [HeidiSQL/HeidiSQL#1709]
**Preconditions**

* HeidiSQL version: 12.2.0.6579 (64 Bit)
* Database type and version: MariaDB 10.3.35
* OS: Windows 10 Pro - 64 bit - 21H2

**Describe the bug**

A recent update has changed the query run when changing the value of a BIT(1) field by double clicking a cell in the grid view of the data tab. The generated query now is along the lines of `UPDATE table_name SET column_name=b1 WHERE  column_id=1;` (note the value `b1` rather than the (previously used) `b'1'`. This results in an error of `SQL Error (1054): Unknown column 'b1' in 'field list'`

Prior to a recent update, it was possible to edit these cells via this method.

**To Reproduce**

1. View the data on a table containing a BIT(1) field
2. Double click a cell of the column representing that BIT(1) field
3. Change the 0 to 1 (or vice versa) in the grid view
4. Click another row to save the change

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/15816699/203522336-b4a75a66-0329-4ed7-ae01-8309b07c29f9.png)

**Comment by ansgarbecker** [comment]
Related and likely broken through #1386

**Comment by ansgarbecker** [comment]
Next build should fix that.

Note that the recent versions have bugs in the build updater, so you might need to download the new build from heidisql.com

**Comment by tobestool** [comment]
Thanks for the fix / update!
