### ISSUE TITLE
复制格式Copy Format

### ISSUE THREAD

**Issue by aliger** [HeidiSQL/HeidiSQL#1711]
**Is your feature request related to a problem? Please describe.**
复制格式希望提供这样的功能 The copy format should provide such a function
现有复制格式问题 copy format 
|| ID || operator_id || operator_name || merchant_nature ||
| 1 | 3495 | XX科技控股股份有限公司 | 2 |
| 3045 | 3494 | 测试运营商限制 | 1 |
| 3 | 3499 | 测试XXX限制 | 3 |
| 3047 | 3500 | 个体XXXX | 1 |

希望复制格式copy format Columns are consistent
|| ID     || operator_id 		 || operator_name                 || merchant_nature ||
| 1        | 3495 				  | XX科技控股股份有限公司 | 2 			     |
| 3045  | 3494                            | 测试XXX限制 		      | 1 			     |
| 3        | 3499                            | 个体XXXX			      | 3 			     |

**Describe the solution you'd like**
希望格式copy format  Columns are consistent
|| ID     || operator_id 		 || operator_name                 || merchant_nature ||
| 1        | 3495 				  | XX科技控股股份有限公司 | 2 			     |
| 3045  | 3494                            | 测试XXX限制 		      | 1 			     |
| 3        | 3499                            | 个体XXXX			      | 3 			     |

**Describe alternatives you've considered**
格式直观明了，列对应，方便查看The format is intuitive and clear, with corresponding columns for easy viewing

**Additional context**

**Comment by ansgarbecker** [comment]
Please use the "Jira Textile" format - this is exactly what you describe here.

**Comment by aliger** [comment]
https://glmje.com/i/2022/12/12/h4xv4b.png
