### ISSUE TITLE
individual windows

### ISSUE THREAD

**Issue by misu34** [HeidiSQL/HeidiSQL#1716]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [i cant take an open query tab and drag it to another screen]

**Describe the solution you'd like**
the ability to drag query windows out like how visual studio works. or duplicate my screen so i can work on more than one table update

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment]
If working on multiple queries, I must say this is already possible through multiple query tabs.
Dragging query tabs somewhere to create a new one is not planned.
