### ISSUE TITLE
Cannot find a usable libpq.dll

### ISSUE THREAD

**Issue by cookieguru** [HeidiSQL/HeidiSQL#172]
## Steps to reproduce this issue

1. Step 1; Install HeidiSQL 64 bit from installer on a 64 bit machine accepting all defaults
2. Step 2; Launch HeidiSQL and attempt to connect to a Postgres server
3. Then I get... `Cannot find a usable libpq.dll.  Please launch heidisql.exe from the directory where you have installed it.`

[Video showing reproduction of the above](http://www.mediafire.com/file/zjjanh0au16j4rj/2018-02-28_09-42-58.mp4)

## Current behavior

Error: Cannot find a usable libpq.dll.  Please launch heidisql.exe from the directory where you have installed it.

## Expected behavior

Connects to server

## Possible solution

I have tried all the suggestions in [this post](https://www.heidisql.com/forum.php?t=21039#msg21074) however the error reappeared with each possible workaround.

## Environment

* **HeidiSQL version:** 
  9.5.0.5255
* **Operating system:** 
  Windows 10 64 bit.  Repros on every Win10 machine I have tested including a virtual machine; the video is a free VM provided from Microsoft available [here](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)

**Comment by ansgarbecker** [comment]
The forum thread is old and irrelevant for the current release.

Could you please use the v9.5 installer and retry ?

**Comment by ansgarbecker** [comment]
Or at least tell me the installer link you downloaded.

**Comment by cookieguru** [comment]
@ansgarbecker As shown in the video and noted in the Environment section it was 9.5.0.5255

**Comment by ansgarbecker** [comment]
Well, there is more than one way to get heidisql.exe v9.5.0.5255 - I wanted to ensure you were installing from https://www.heidisql.com/installers/HeidiSQL_9.5.0.5255_Setup.exe - was that the case?

**Comment by cookieguru** [comment]
I had pre-downloaded https://www.heidisql.com/installers/HeidiSQL_9.5.0.5255_Setup.exe (didn't want to waste 3 minutes of video showing the downloading it)

**Comment by ansgarbecker** [comment]
Ok, and you have a libpq.dll in your HeidiSQL folder?
Here's what it looks like for me:

![grafik](https://user-images.githubusercontent.com/7986591/36807753-f82bf88c-1cc3-11e8-9cc1-3386aaa5779b.png)

**Comment by G3ph4z** [comment]
I had same issue 2-3 days ago on one of my VM, and I installed (I cant remember correctly, sorry) VC++ redistributable 2013 (or 2015) x64, and its solved my problem

**Comment by cookieguru** [comment]
[Visual C++ 2013 Redistributable Package](https://support.microsoft.com/en-us/help/3179560/update-for-visual-c-2013-and-visual-c-redistributable-package) did the trick, thank you @G3ph4z!

@ansgarbecker Probably the same DLL: 
![untitled](https://user-images.githubusercontent.com/1888809/36810571-ecd0b908-1c7f-11e8-8c2e-4e6f5cb3bed4.png)
But the package above did the trick; is it possible to detect that dependency at runtime?

**Comment by G3ph4z** [comment]
@cookieguru You’re welcome. :)

**Comment by e14mattc** [comment]
Same thing happening to me on Win7 with the latest Heidi installer (upgrading existing installation).. installing the V C++ 2013 Redist package fixed it for me too!

**Comment by podojoos** [comment]
Exactly """"x64!!!!""" Visual C++ 2013 Redistributable Package, not x86, even if you use x86.
Thank you!!

**Comment by ansgarbecker** [comment]
I added a note and a link for the VC Redistributable on HeidiSQL's download page, as a prerequisite for connecting to PostgreSQL.

**Comment by Sleepful** [comment]
Visual C++ (vc_redist.x64.exe) 2015 version did it for me, apparently my computer already had 2013
