### ISSUE TITLE
MySQL on RDS, option to NOT use SSH tunnel

### ISSUE THREAD

**Issue by pauljura** [HeidiSQL/HeidiSQL#1721]
**Is your feature request related to a problem? Please describe.**
All my current MySQL connections are on RDS and work just fine without an SSH tunnel.

With your latest version, I switched my existing connections to use the new MySQL on RDS Network type to take advantage of the kill query command, and now I can't connect.

**Describe the solution you'd like**
I would like an option to not use an SSH tunnel with MySQL on RDS.

**Describe alternatives you've considered**
I've tried following the instructions to use an SSH tunnel, but it doesn't seem to work for me.

**Additional context**
My employer uses AWS Direct Connect so probably that's why I don't need an SSH tunnel. I'm not sure how common that is. I'm just a developer, not a network engineer :)

Thanks!

**Comment by ansgarbecker** [comment]
I decided to add a checkbox for disabling/enabling the SSH tunnel configuration. That way I can easier add SSH tunneling support in other network types like MS SQL in the future:

![grafik](https://user-images.githubusercontent.com/7986591/210273382-d15b937c-23b7-427c-8ebd-64e4ccf78ed3.png)

Please update to the next build and test if that works now as it should.

**Comment by pauljura** [comment]
Thanks, this works for me now, including the RDS kill command, thank you!

**Comment by ansgarbecker** [comment]
Thanks for the feedback!
