### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by tmtisfree** [HeidiSQL/HeidiSQL#1722]
**Preconditions**

* HeidiSQL version: 12.3.x
* Database type and version:
* OS:

**Describe the bug**

Required strings not found in the English default.po master file.

In session manager:
"Library"
"Filter ..."

In menu:
"Undo"

In Prefs > Shortcuts tab:
"New query tab in background"
"Follow foreign key"
"Copy with tabs to spaces"
"Connection properties"
"Delimited text"
"Move line up"
"Move line down"

Misc:
"Count hits when grouping by distinct values in some column"
"Find records only present in 1 of 2 tables"

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Fixed. Transifex now shows these strings after updating the master po file.

**Comment by tmtisfree** [comment]
Thank you.
