### ISSUE TITLE
Improve usability of filter option for table column listing

### ISSUE THREAD

**Issue by stahl-riesa** [HeidiSQL/HeidiSQL#1725]
**Is your feature request related to a problem? Please describe.**
Sometimes tables consist of many columns. So it is hard to find the right column.

**Describe the solution you'd like**
Add a filter option on the right side to the column setup (new, delete, up, down). See      #####screenshot.

**Describe alternatives you've considered**
I dont know what else could be better.

**Additional context**
![columnfilterheidisql](https://user-images.githubusercontent.com/6726821/206675062-de955e79-778d-4af8-b4e0-aa24a1a6a4d1.png)

**Comment by stahl-riesa** [comment]
Same like:
https://github.com/HeidiSQL/HeidiSQL/issues/1715

**Comment by ansgarbecker** [comment]
That is already there, you only need to activate it through Edit > "Filter panel":

![grafik](https://user-images.githubusercontent.com/7986591/206680234-c0d9323b-2702-400a-a7ac-7cb3e8eb6838.png)

**Comment by stahl-riesa** [comment]
Okay. Thats great. Unfortunately, this is not very intuitive and conducive to the workflow.

**Comment by ansgarbecker** [comment]
Well, that's the way it is. Should not be too hard to use, especially as the filter panel stays there once activated, even after restarting HeidiSQL.

**Comment by ansgarbecker** [comment]
I can probably add a history-dropdown there, similar to the table filter and like in your screenshot.

**Comment by stahl-riesa** [comment]
That's a good idea. Let's try it.

Please don't get me wrong, I also create graphical user interfaces and therefore I know how blind users can be. Take the people by the hand.

**Comment by ansgarbecker** [comment]
Next build has a history menu on the now visible left button there.

Any more ideas to make that filter more visible to the user? I already made it visible by default, for users with a blank installation. I could add that "Filter panel" menu item somewhere else (additionally to the Edit main menu), but I wouldn't say that makes sense.
