### ISSUE TITLE
Missing foreign key for MySQL 4 innodb

### ISSUE THREAD

**Issue by ethersweeper** [HeidiSQL/HeidiSQL#1729]
**Preconditions**

* HeidiSQL version: any version Later than 10.3.0.5771
* Database type and version: MySQL 4, innodb engine
* OS: Windows 7, 10, Server 2019 Datacenter

**Describe the bug**

Missing foreign keys for all Tables. 
The last working HeidiSQL that shows foreign key is 10.3.0.5771, any version Later than that has this issue.

**To Reproduce**

Create a Table with foreign key, it will not show in Foreign Key tab.

**Screenshots or Crash reports**

The below screenshot shows a working version on the Left, and on the Right having said issue. I have notice the `CONSTRAINT `FK__tbl1` FOREIGN KEY (`id`) REFERENCES `tbl1` (`id`)` is missing in the **Create Code** tab.

![Untitled](https://user-images.githubusercontent.com/27274867/207110570-4743ca51-9c45-4b23-85b3-991d808d6537.png)

**Comment by ansgarbecker** [comment]
Current HeidiSQL version use such a query to detect foreign keys:

    SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='mydatabase'   AND TABLE_NAME='mytable' AND REFERENCED_TABLE_NAME IS NOT NULL;

MySQL 4 does not have that `REFERENTIAL_CONSTRAINTS` system view, so the query fails (silently) and HeidiSQL does not foreign keys.

MySQL 4 is 20 years old. Please use an old version of HeidiSQL if you still need compatibility to such old server versions.
