### ISSUE TITLE
Add option to disable incremental search in grids

### ISSUE THREAD

**Issue by andrewbaranov** [HeidiSQL/HeidiSQL#1730]
**Is your feature request related to a problem? Please describe.**
When editing quickly, it's easy to not press the key to enter the edit mode of the record, and instead of editing, a search will be performed.

**Describe the solution you'd like**
Add "Disable Quick Search" to Settings

**Additional context**
No needs in screenshots

**Comment by ansgarbecker** [comment]
New checkbox in preferences > Data editors:

![grafik](https://user-images.githubusercontent.com/7986591/210133819-53c731ed-c446-4393-b893-1bbc60cd720f.png)

**Comment by ansgarbecker** [comment]
New issues:
* grid font size gets reset each time a query runs
* wrong vertical position / anchor of linebreak option in data editors tab
