### ISSUE TITLE
A Crash occurs in User Management in Postgres Database

### ISSUE THREAD

**Issue by Zwixx** [HeidiSQL/HeidiSQL#1731]
**Preconditions**

* HeidiSQL version: 12.3.0.6589 - 64bit
* Database type and version: postgres 11.18
* OS: Windows 10

**Describe the bug**

I get a error (pqsql: Fehler - ERROR:  syntax error at or near "FLUSH"
LINE 1: FLUSH PRIVILEGES
        ^
if I try to use the USer Management.

**Screenshots or Crash reports**

![grafik](https://user-images.githubusercontent.com/4589892/208185489-454572b8-c59f-44ba-8203-cd00f2468a3b.png)

**Comment by ansgarbecker** [comment]
Duplicate of #80
