### ISSUE TITLE
6603 crash on windows 11 HomeEdition(22H2)

### ISSUE THREAD

**Issue by phiree** [HeidiSQL/HeidiSQL#1734]
**Preconditions**

* HeidiSQL version:12.3.0.6603
* Database type and version:mysql
* OS:Windows 11 HomeEdition(22H2)

**Describe the bug**

crash when start it.

**To Reproduce**

1. install 12.3.0.6603
2. check "Lauch HeidiSQL" on the last step of installing
3. click ok
4. nothing happens.
5. system error log: 

`  + System 
  - Provider
   [ Name]  Application Error 
   [ Guid]  {a0e9b465-b939-57d7-b27d-95d8e925ff57} 
   EventID 1000 
   Version 0 
   Level 2 
   Task 100 
   Opcode 0 
   Keywords 0x8000000000000000 
  - TimeCreated
   [ SystemTime]  2022-12-22T07:24:44.7659925Z 
   EventRecordID 10805 
   Correlation 
  - Execution 
   [ ProcessID]  2836 
   [ ThreadID]  22928 
   Channel Application 
   Computer *****
  - Security 
   [ UserID]  S-1-5-21-1916634152-1665802421-608695537-1002 
- EventData 
  AppName heidisql.exe 
  AppVersion 12.3.0.6603 
  AppTimeStamp 63a20851 
  ModuleName unknown 
  ModuleVersion 0.0.0.0 
  ModuleTimeStamp 00000000 
  ExceptionCode c000041d 
  FaultingOffset ffffffff81b00987 
  ProcessId 0x4ff0 
  ProcessCreationTime 0x1d915d674c9bb69 
  AppPath C:\Program Files\HeidiSQL\heidisql.exe 
  ModulePath unknown 
  IntegratorReportId 9bb894b9-019a-47e1-b769-89db09cd2566 
  PackageFullName  
  PackageRelativeAppId  
`

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Please download build 6603 again. The 64bit build had such a crash, not only in the Win11 Home edition. I recompiled it with disabled memory address layout randomization (HighEntropyVa) to fix that. A few users already downloaded the crashing build, so I suppose you were one of them. Just downlod it again, manually, from https://www.heidisql.com/download.php#nightlybuilds

**Comment by ansgarbecker** [comment]
Closing. Guess that was it.
