### ISSUE TITLE
Give a choice to install in user space, avoid UAC prompt

### ISSUE THREAD

**Issue by hj-collab** [HeidiSQL/HeidiSQL#1735]
Hi @ansgarbecker,

Thanks for telling me about the installer used for the HeidiSQL. I was reading a post from WinSCP developer and I think it's possible to give a choice where to install the app. Please take a look. https://stackoverflow.com/questions/21556853/make-inno-setup-installer-request-privileges-elevation-only-when-needed/35435534#35435534

Thank you!

**Comment by ansgarbecker** [comment]
Please don't delete the issue template. It's important to have a use case and versions for a request.

**Comment by ansgarbecker** [comment]
Latest nightly installer v12.3.0.6652 asks whether to install for all users or just for the current one, where the latter one does not request admin privileges.

![grafik](https://user-images.githubusercontent.com/7986591/214652308-82852006-0104-4c1f-b4d8-d79693c6147b.png)

Note that if you previously installed HeidiSQL in `C:\Program Files\`, the installer runs in update-mode, requesting admin privileges without showing that dialog. To test that, you can safely uninstall HeidiSQL and reinstall the nightly installer from https://www.heidisql.com/download.php#nightlybuilds . Uninstalling will just remove the app itself and a registry entry for the .sql file extension. It will not remove your sessions. If in doubt, make a backup of `HKEY_CURRENT_USER\Software\HeidiSQL`

**Comment by ansgarbecker** [comment]
Also note this is experimental. I need some feedback here before that will make it into the next official release.

**Comment by ansgarbecker** [comment]
Yes, the build updater is a different thing, and was always requesting admin privileges. I don't see yet a way to remove that, depending on the installer mode, and it's anyway just for the nightly builds.
