### ISSUE TITLE
Heidisql not responsing on mysql create new function

### ISSUE THREAD

**Issue by mailparikshit** [HeidiSQL/HeidiSQL#1737]
**Preconditions**

* HeidiSQL version: 12.3.0.6609
* Database type and version: MariaDB 10.4.22
* OS: windows 10 pro x64

**Describe the bug**

heidisql goes not responding no error shown 
**To Reproduce**

1. connect to you localhost database 
2. right click on database and create new function
3. write new function name
4. under a code section write a statement `declare Tinyint` and enter a space and wait few seconds
5. Heidisql becomes not responding
**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/5322914/209922662-106ef991-8c66-4d3f-bece-4d48c4bebb73.png)

**Comment by ansgarbecker** [comment]
Sounds quite similar to #1568 . Could you please update to the latest nightly build and retry? I pushed a potential bugfix for it, but I am unsure if that was it, as the freeze was only sporadically reproducible for me.

**Comment by ansgarbecker** [comment]
@mailparikshit any feedback would be appreciated.

**Comment by ansgarbecker** [comment]
I assume this is fixed.

**Comment by mailparikshit** [comment]
@ansgarbecker Thanks for the fix, it was really urgent, as i was not able to create procedures.

**Comment by mailparikshit** [comment]
> I assume this is fixed.

yes. it is fixed, thanks again
