### ISSUE TITLE
Heidisql crash when do simple query

### ISSUE THREAD

**Issue by jjasoncool** [HeidiSQL/HeidiSQL#1738]
**Preconditions**

* HeidiSQL version:12.3.0.6616
* Database type and version:MSSQL 11.0
* OS:Windows 10 X64 build19042

**Describe the bug**

Prompt error, can't do anything.
![圖片](https://user-images.githubusercontent.com/24731867/210050120-a717d79a-00bf-4c60-8dde-1e27877b08fe.png)

And status show continuing query, can't close tab when query is processing.
Previous version 6612 is normal.
After 6612, when do query will crash.
![圖片](https://user-images.githubusercontent.com/24731867/210050598-0c504c40-d676-4ee1-a140-f63c2ebacc67.png)

**To Reproduce**

Just do a simple query using selected script.

**Screenshots or Crash reports**

![圖片](https://user-images.githubusercontent.com/24731867/210049905-ab2d981b-3c79-4cdd-be58-f24a489b1f6c.png)
![圖片](https://user-images.githubusercontent.com/24731867/210049921-82861172-1e1d-491e-bf47-9966db2f7c82.png)

**Comment by ansgarbecker** [comment]
Yes, that is apparently broken after the recent updates to the VirtualTree component. Already at it.

**Comment by ansgarbecker** [comment]
Should be working again now in 64 bit mode. The 32 bit mode was somehow unaffected.
However, I reverted the component update, so I will have to redo it at some point.
