### ISSUE TITLE
HeidiSQL version 12 does not handle special characters correctly

### ISSUE THREAD

**Issue by Rippleblue72** [HeidiSQL/HeidiSQL#1739]
**Preconditions**

* HeidiSQL version: 12.3.0.6589
* Database type and version: MySQL 5.1.73
* OS: Windows 10

**Describe the bug**

Upgraded from ver 11 to 12. The tables with special characters (not a-z or 0-9) the display is incorrect and when importing data with these characters the import fail with duplication a duplication error and the imported data in the table is not correct. HeidiSQL  11.3.0.6295 works correct with correct display and the old version of MySQL workbench (6.2 CE newer does not support ver 5 of MySQL)
**To Reproduce**

1. Go to 'Load SQL file'
2. Encoding is set to UTF-8
3. See error message: SQL Error (1062): Duplicate entry '' for key 'Text'
4. The import works correctly in version HeisiSQL 11.3.0.6295 and the data displayed is correct. 
5. 
**Screenshots or Crash reports**

Version 11 display of data:
![image](https://user-images.githubusercontent.com/121666365/210056902-dcee1e8d-e78b-469d-a22f-00be0b398609.png)

Version 12 display of data:
![image](https://user-images.githubusercontent.com/121666365/210057307-e5aaa1ff-612a-419f-aac8-1124f8985e91.png)

When importing in version 12, import stops at record 80 as record 81 is a duplicate with a record that is only a capital C (record 16), version 11 imports correctly.
![image](https://user-images.githubusercontent.com/121666365/210057815-5dc2b7ab-192f-4400-9d7f-62b62e0a0525.png)

[test.zip](https://github.com/HeidiSQL/HeidiSQL/files/10324048/test.zip)
SQL file with data

**Comment by ansgarbecker** [comment]
Exactly what I found in [#287](https://github.com/HeidiSQL/HeidiSQL/issues/287#issuecomment-1151955030)
Please select the older libmysql.dll in the sessions "Library" setting for Unicode support on such old servers. With libmariadb on MySQL 5.1, HeidiSQL is not in Unicode mode:
![grafik](https://user-images.githubusercontent.com/7986591/210067566-b0f2c4c9-7d65-4643-8f7a-15ab75b636f3.png)

Caution: this is just meant for old servers. Using the old libmysql on newer servers has other issues.
