### ISSUE TITLE
SSH tunnel passphrase dialog shown although passphrase saved in connection template

### ISSUE THREAD

**Issue by schengawegga** [HeidiSQL/HeidiSQL#1741]
**Preconditions**

* HeidiSQL version: 12.3.0.6629
* Database type and version: MariaDB 10.1.48
* OS: Windows 10

**Describe the bug**

SSH tunnel passphrase dialog shown although passphrase saved in connection template.
The passphrase must be inserted again.

**To Reproduce**

Connect to a database via ssh-tunnel (plink.exe) with preconfigured passphrase stored in the connection-template.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
You cannot store the passphrase for a private key file in a HeidiSQL session. That must be entered each time you get prompted. What is stored in the session is the password you are normally using to authenticate on the database server.

I guess this solves it? If not please shout.
