### ISSUE TITLE
Nightly build update failes: does not restart new .exe

### ISSUE THREAD

**Issue by andipfaff** [HeidiSQL/HeidiSQL#1742]
**Preconditions**

* HeidiSQL version: 12.3.0.6229 or eveyre newer version
* Database type and version: n/a
* OS: Windows 10

**Describe the bug**

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Likely what I experienced myself, and fixed in build 6229, which is 4fd9b87767931b8e2491fadedf09366d78b07f98
Happened when the path to HeidiSQL has spaces, e.g. "C:\Program Files\HeidiSQL\..."
Please watch out if the next build update _from 6229_ to a later one works.

**Comment by ansgarbecker** [comment]
@andipfaff could you check if the further updates are now starting the new exe ?

**Comment by andipfaff** [comment]
Hi Ansgar,

I've tested it. The behaviour ist different from before. Ich get ths attached messages and after 10s or so the cmd-Window closes.
![grafik](https://user-images.githubusercontent.com/4201912/212294075-614d3a9e-7669-4b49-81bd-a0ff391644e3.png)

Best regards
Andi

**Comment by ansgarbecker** [comment]
That looks like it should!
I suppose the HeidiSQL window in front is the updated exe.
