### ISSUE TITLE
Connection open causes file corruption in files containing degrees sign and file size is around 10k.

### ISSUE THREAD

**Issue by ControlDesign** [HeidiSQL/HeidiSQL#1744]
**Preconditions**

* HeidiSQL version: 12.0.0.6468 (64 Bit)
* Database type and version: HeidiSQL 10
* OS: Windows 10 19045.2364

**Describe the bug**

Extra text is inserted into the middle of source files.  Starts small, but each time opening, doubles the jumble of text.  The seed is a degrees symbol below about line 400.  Can delete the extra text without data loss but it comes back on connection open.  

**To Reproduce**

Open a connection to mysql.  Create a sql file.  Make first 451 lines this line:
# *************************************************************************************
Make line 452:
°C_abs
Close HeidiSQL and save.
Open HeidiSQL.  Open connection, which opens the file that was left open, but with corruption before degrees sign:
Â°C_abs
Make a trivial change and save.  Close HeidiSQL.  Open HeidiSQL.  Open connection.  File loads with more corruption:
Ã‚Â°C_abs
Make a trivial change and save.  Close HeidiSQL.  Open HeidiSQL.  Open connection.  File loads with more corruption:
Ãƒâ€šÃ‚Â°C_abs
Make a trivial change and save.  Close HeidiSQL.  Open HeidiSQL.  Open connection.  File loads with more corruption:
ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â°C_abs

This can repeat until the corruption is larger than 10k and cannot escape notice.

Does not occur without first 451 lines at the beginning making it hard to find the minimal file that causes it.

I am creating test reports that have °C_abs as a unit of measure.  I am noticing file corruption in my repo due to opening files in HeidiSQL.

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/62630751/211090025-bed02012-8d6a-4637-8238-b346e51d4f52.png)

**Comment by ansgarbecker** [comment]
Confirmed.
Only broken when you save it to a custom file name. Not broken when you chose not to save the file, and let it be restored automatically. Will look at that.

Please use the latest build next time you report an issue. v12.3 is the current release.

**Comment by ansgarbecker** [comment]
Fixed in the next build.

Note that now such files are loaded in UTF-8 encoding, even when the file has UTF-16 or something else.
Previously, the first kilobytes of the file were scanned for the correct encoding, which is why you needed to insert ASCII characters in the first place.
