### ISSUE TITLE
Save As Fragment : When a long filename is used, the end of the filename is cropped and replaced by many points.

### ISSUE THREAD

**Issue by philibe** [HeidiSQL/HeidiSQL#1747]
**Preconditions**

* HeidiSQL version: 12.3.0.6589
* Database type and version: SQL Server 2005 9.00.3042.00
* OS: Windows 7 SP1

**Describe the bug**

In Save as fragment : When a long filename is used, the end of the filename is cropped and replaced by many points.

I use HeidiSQL for many years, thank you, this little bug seems to be old only for less than one month.

**To Reproduce**

- Go to File
- `Save` initial query and replace "Requête#3.sql" with 
  +`MyFilekljdfjgdjfgdfjlgdkfjgkldjflgkjdflkgjdlfkjdlfkjdlkjdlkjldjldjfdflj.sql`
- Save as fragment and see the proposition
  +`MyFilekljdfjgdjfgdfjlgdkfjgkldjflgkjdflkgjdlfkjdlfkjdlkjdlkjldjldjfdf….sql`

 instead of  the end "flj.sql"  the end of filename proposition is replaced by "f….sql"

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Fixed in the next build
