### ISSUE TITLE
HeidiSQL Freeze when clicking on a table to get more details during "SHOW ENGINES" through a VPN the response gets blocked by firewall and HeidiSQL hangs entirely

### ISSUE THREAD

**Issue by Zeg0** [HeidiSQL/HeidiSQL#1748]
**Preconditions**

* HeidiSQL version: 12.3.0.6589
* Database type and version: MySQL 5.7.3 and MySQL 5.7.4 and MySQL 5.7.17 and several more ... 
* OS: Windows 10 V 21H2 - lates update as of 11.01.2023 - KB5022282, KB2267602

**Describe the bug**

First i connect my windows PC through a VPN with my company network. The databases are hosted at amazon AWS. Without the VPN a firewall at amazon would block connection attempts to AWS. Through the company network another firewal layer is added.
All in all most SQL Queries (like simple select statements) get through. However "SHOW ENGINES" for example gets blocked and gets no response back. 

In HeidiSQL this query is used when clicking on a table to expand details about it. Since no result is returned this causes the bug. It should lead to a timeout and work with less data than expected or a failure message in my opinion (SHOW TABLES e.t.c. works). Instead HeidiSQL performs an endless loop and freezes entirely till it gets shutdown by windows hanging process or taskmanager.

Bug is reproducable with MySQL 5.7.3 and MySQL 5.7.4 and MySQL 5.7.17 and several more.
However MariaDB 10.1.48 and MariaDB 10.5.18 don't cause the firewall to block. Potentially the firewall doesn't filter for specific content, but some other reason why the response to the request is missing to the HeidiSQL Client... I saw a TCP Package loss with RST-Package in Wireshark after the SHOW ENGINES command which is reproducable with my setup and said old MySQL Databases. While HeidiSQL can definetly not undo the firewall behaviour it shouldn't freeze the and hang the HeidiSQL process.

**To Reproduce**

You need a firewall that don't respond at all and blocks the result of the SHOW ENGINES command between you and the database. Once that is set up just expand the database and click on any table to view its details.

**Screenshots or Crash reports**

*HeidiSQL process freezed. last few lines in logfile once i clicked on my table mydatabase.mytable:*
```
...
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ [09:44:33.849] SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='mydatabase'   AND TABLE_NAME='mytable'   AND REFERENCED_TABLE_NAME IS NOT NULL;
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.903] Result #1 fetched. */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.905] Detected column type for CONSTRAINT_CATALOG (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.907] Detected column type for CONSTRAINT_SCHEMA (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.909] Detected column type for CONSTRAINT_NAME (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.910] Detected column type for UNIQUE_CONSTRAINT_CATALOG (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.912] Detected column type for UNIQUE_CONSTRAINT_SCHEMA (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.915] Detected column type for UNIQUE_CONSTRAINT_NAME (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.917] Detected column type for MATCH_OPTION (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.920] Detected column type for UPDATE_RULE (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.922] Detected column type for DELETE_RULE (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.923] Detected column type for TABLE_NAME (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.924] Detected column type for REFERENCED_TABLE_NAME (253): VARCHAR */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ /* [09:44:33.926] Ping server ... */
/* 2023-01-11 09:44:33 [xxxxxxxxx] */ [09:44:33.974] SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='mydatabase'   AND TABLE_NAME='mytable'   AND REFERENCED_TABLE_NAME IS NOT NULL;
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.036] Result #1 fetched. */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.038] Detected column type for CONSTRAINT_CATALOG (253): VARCHAR */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.040] Detected column type for CONSTRAINT_SCHEMA (253): VARCHAR */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.042] Detected column type for CONSTRAINT_NAME (253): VARCHAR */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.043] Detected column type for TABLE_CATALOG (253): VARCHAR */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.044] Detected column type for TABLE_SCHEMA (253): VARCHAR */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.046] Detected column type for TABLE_NAME (253): VARCHAR */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.048] Detected column type for COLUMN_NAME (253): VARCHAR */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.050] Detected column type for ORDINAL_POSITION (8): BIGINT */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.054] Detected column type for POSITION_IN_UNIQUE_CONSTRAINT (8): BIGINT */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.055] Detected column type for REFERENCED_TABLE_SCHEMA (253): VARCHAR */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.057] Detected column type for REFERENCED_TABLE_NAME (253): VARCHAR */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.058] Detected column type for REFERENCED_COLUMN_NAME (253): VARCHAR */
/* 2023-01-11 09:44:34 [] */ /* [09:44:34.196] Setting up TSynMemo "SynMemoPartitions" */
/* 2023-01-11 09:44:34 [] */ /* [09:44:34.200] Setting up TSynMemo "SynMemoCREATEcode" */
/* 2023-01-11 09:44:34 [] */ /* [09:44:34.203] Setting up TSynMemo "SynMemoALTERcode" */
/* 2023-01-11 09:44:34 [] */ /* [09:44:34.205] TfrmTableEditor.Init, using object "realtimetest" */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.208] Fetching list of table engines ... */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.211] Ping server ... */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ /* [09:44:34.267] Ping server ... */
/* 2023-01-11 09:44:34 [xxxxxxxxx] */ [09:44:34.318] SHOW ENGINES;
```

**Comment by Zeg0** [comment]
Maybe related to old freezing bug in MySQL? https://bugs.mysql.com/bug.php?id=79815

**Comment by Zeg0** [comment]
Potentially a combined bug with packageloss / packagesize and old MySQL Server Response size? However HeidiSQL shouldn't freeze over that so it would be cool to catch the missing response without causeing Heidi to freeze

**Comment by Zeg0** [comment]
Update:

It was NOT a firewall issue, but happens only through vpn.
- the Bug is reproducable with said configuration and **libmariadb.dll** and **libmysql.dll** and said old MySQL Servers

The Bug is resolved when using **libmysql-6.1.dll** 👍👍👍🎉

**Comment by Zeg0** [comment]
Could be a MTU package size missmatch between my provider and vpn and/or firewalls to aws somewhere in said .dlls? Just a guess.

**Comment by Zeg0** [comment]
Feel free to close this or use it to update non-freezing but not that much you can do here

**Comment by ansgarbecker** [comment]
Thanks for your comprehensive feedback!
