### ISSUE TITLE
Don't autocreate Documents\HeidiSQL

### ISSUE THREAD

**Issue by jifb** [HeidiSQL/HeidiSQL#1751]
**Preconditions**

* HeidiSQL version: 11.1.0.6116
* Database type and version: any (bug appears before any connection)
* OS: Windows 10

**Describe the bug**

The directory C:\Users\xx\Documents\HeidiSQL gets created although not needed

**To Reproduce**

1. Open HeidiSQL
2. Open Options 
3. Set Snippet Directory to somewhere outside Documents
4. Close HeidiSQL
5. Remove C:\Users\xx\Documents\HeidiSQL
6. Open HeidiSQL
7. Close HeidiSQL
8. C:\Users\xx\Documents\HeidiSQL is there!

**Screenshots or Crash reports**

not applicable

**Possible solution**

In source/apphelpers.pas remove lines 4463-4465 (DirectoryExists()/ForceDirectories() of `function TAppSettings.DirnameUserDocuments`)
If it is wished to use "HeidiSQL" folder for open dialoge (`procedure Tconnform.PickFile` in connections.pas), one could add the DirectoryExists()/ForceDirectories() there, so it happens not so frequent on "normal use".

**Comment by ansgarbecker** [comment]
Next build doesn't do that any longer.
Note the installer still auto-creates that folder: https://github.com/HeidiSQL/HeidiSQL/blob/4ccf6e07f8275fb7cc51c437a0a3c5f040235b1b/out/heidisql.iss#L95
