### ISSUE TITLE
Translation (Dutch) not fully visible in button in session manager

### ISSUE THREAD

**Issue by KjartanBourgeois** [HeidiSQL/HeidiSQL#1752]
**Preconditions**

* HeidiSQL version: 12.3.0.6589
* * Database type and version: /
* OS: Windows 11

**Describe the bug**
Translation (Dutch) not fully visible in button in session manager

**To Reproduce**
1. Start HeidiSQL
2. In the sessionmanager button import settings, the width of the button is not wide enough

**Screenshots or Crash reports**
![image](https://user-images.githubusercontent.com/59248305/214234502-c852380e-9bf5-462f-b50a-5ea961f33587.png)

**Comment by ansgarbecker** [comment]
Yes, that button definitely needs more width. I already forgot about that several times, so good there is an issue now.
Last modification of the width was in 2012: bf3ff4eecb155987c430599ad1e2fad6ba6719d7
