### ISSUE TITLE
Error if SSL CA certificate path is within virtualbox shared folder

### ISSUE THREAD

**Issue by floh96** [HeidiSQL/HeidiSQL#1757]
**Preconditions**

* HeidiSQL version: 12.3.0.6589
* Database type and version: MYSQL 5.7.38
* OS: Microsoft Windows [Version 10.0.19044.2486]

**Describe the bug**

I tried to connect to the mysql db with the use SSL option enabled.
I provided the path to the SSL CA certificate which is within a virtualbox shared folder see screenshot.
Heidi SQL does not recognize the path see error message.

**To Reproduce**
Try to use a file path within a virtualbox shared folder.

**Screenshots or Crash reports**

![Unbenannt](https://user-images.githubusercontent.com/49693964/215484841-61c62d53-7eba-44a5-9b29-75a16e6f1776.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/49693964/215484861-af160b67-d792-45e2-91af-355c6663a388.PNG)

**Comment by floh96** [comment]
fyi @ansgarbecker i browsed the path and saved it again and the error is gone...

**Comment by ansgarbecker** [comment]
Thanks a lot for the update!
