### ISSUE TITLE
Please add libpq-15.dll 

### ISSUE THREAD

**Issue by kingofnull** [HeidiSQL/HeidiSQL#1758]
**Is your feature request related to a problem? Please describe.**
Add support for Postgresql 15 

**Describe the solution you'd like**
Add libpq-15.dll to build.

[libpq-15.zip](https://github.com/HeidiSQL/HeidiSQL/files/10579111/libpq-15.zip)

**Comment by ansgarbecker** [comment]
No problem. But I'll take the official one from postgresql.org, not one from an attached zip here.

**Comment by ansgarbecker** [comment]
That new libpq.dll has dependencies from other dlls which are not yet shipped with HeidiSQL. I will need to
* find out which ones
* copy them from the Win64 PG server package
* sign them with my Authenticode certificate (see #1734)
* and finally add all of them to the installer.

**Comment by ansgarbecker** [comment]
Done.

Latest built installer ships libpq-15.dll and 4 additional dependent libraries. All files are signed with my Authenticode certificate, as the original files from PostgreSQL were not signed at all.

**Comment by ansgarbecker** [comment]
@kingofnull I forgot to ask: did you ask for v15 libpq due to some issue with a connection you got? I suppose the v12 libpq generelly works a v15 server, right?

**Comment by zilzila** [comment]
> Done.
> 
> Latest built installer ships libpq-15.dll and 4 additional dependent libraries. All files are signed with my Authenticode certificate, as the original files from PostgreSQL were not signed at all.

...and portable versions?
