### ISSUE TITLE
Bad UX feature (bug)

### ISSUE THREAD

**Issue by dm6790** [HeidiSQL/HeidiSQL#1764]
**Preconditions**

* HeidiSQL version: * > 12.2.0.6576
* Database type and version: MySQL connected over SSH
* OS: W11

**Describe the bug**
When opening a new database session, a window constantly appears for entering the passphrase for the SSH key. This has not been observed before. It is very uncomfortable. This feature (bug) seems to degrade the UX of a great app!

Thanks!

**To Reproduce**

1. Try to open any session with MySQL  over SSH with passphrase by plink.exe

**Screenshots or Crash reports**

![image](https://user-images.githubusercontent.com/34000999/218477198-09f6c8b9-3e1b-4f93-9285-8f0efed9b990.png)

**Comment by ansgarbecker** [comment]
I suspect this has something to do with the key you are using. Does it have a passphrase? And did you enter the right one, or what did you do in that dialog?
