### ISSUE TITLE
Suggestion List

### ISSUE THREAD

**Issue by theRavindraS** [HeidiSQL/HeidiSQL#1767]
**Suggestion List**
There should open a option list in SQL edit tab.
Like phpmyadmin when you edit query.  it gives you a list of table name, field name, keywords and functions.
in HeidiSQL it opens but when we press Ctrl+space.

**Additional context**
This is my first request on github. so if any error in writing or else, please inform me.
Thanks

**Comment by theRavindraS** [comment]
Thanks for replay,

If you remove Ctrl+space option it will also be not wrong. 

I just suggest you for more simplicity for the developer. Because i worked on phpmyadmin from long time. this option is so handy you don't have to type. Many times it is easy to type complete word than pressing Ctrl+space.


If there is problem to make it, leave it. 

I am using HeidiSql from last 4months. It is great tool. So I suggest you this option, it will give developer more comfort to write long query where many function and keywords used.

**Comment by ansgarbecker** [comment]
I don't get what you mean I'm afraid. Please explain more precise.

**Comment by theRavindraS** [comment]
![Screenshot 2023-02-20 200936](https://user-images.githubusercontent.com/104681807/220195385-b46ae6d0-214f-480e-aed5-398bf301932a.png)


I just only suggest you to add a feature in which user don't need to press Ctrl+space. When he type it's suggest all available options. 

If it is possible, incorporate it. 

It will give value to the HeidiSQL.

I am attaching screenshot, so that you can understand better what i want to tell you.



**And don't afraid. I just want your product more valuable.**

**Comment by ansgarbecker** [comment]
Ah, got it. You just want the proposal to open without pressing some hotkey.
Then this is just a duplicate issue. See #1003
