### ISSUE TITLE
HeidiSQL unable to connect to SSL using client certificates

### ISSUE THREAD

**Issue by gnd** [HeidiSQL/HeidiSQL#1768]
**Preconditions**

* HeidiSQL version:  12.3.0.6589
* Database type and version: MariaDB 10.5 (1:10.5.18-0+deb11u1)
* OS: Windows 11

**Describe the bug**

HeidiSQL under Windows 11 is unable to use client certificates to connect to a MariaDb instance running on Debian 11. When trying to connect i get an error from HeidiSQL: 

`SSL connection error: no cipher match. Error 0x80090331 (SEC_E_ALGORITHM_MISMATCH)`

On the server side i see that Mariadb sees the client disconnecting: 

`Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: 'XXX.XXX.XXX.XXX' (This connection closed normally without authentication)`

I have tested the connection from another machine, using mariadb-client under Linux and it works well. Following the issue: https://jira.mariadb.org/browse/CONC-527 i have configured the Mariadb server with 

`ssl-cipher=DEFAULT:@SECLEVEL=1`

This results in HeidSQL logging in and the connection working. However, this is not an acceptable solution as SECLEVEL=1 permits also broken SHA1 cryptographich  primites. 

In order to better understand the issue, i used Wireshark to sniff the connection. It seems like HeidiSQL advertizes a lot of  Signature Hash Algorithms during the CLIENT HELLO phase, which are matching with many Signature Hash Algorithms advertised by the SERVER HELLO, however unless the Mariadb server isnt setup with SECLEVEL=1 it closes the connection. 

Under `SECLEVEL=1` the server advertizes additional Signature Hash Algorithms, from which HeidiSQL chooses the `rsa_pkcs1_sha1`. In such a case the connection works, however its using a weak signature hash algo and the server allows crypto primitives using SHA1. 

Could you please verify why from all possible hashes the `rsa_pkcs1_sha1` is chosen ? 

**To Reproduce**

1. Configure MariaDB server 10.5 on Debian 11 to use SSL, Generate a client certificate and private key and make the connection work from a Linux command line client. Once its working, use the client cert + key for a SSL connection in Windows 11 using HeidiSQL. 

One note: if we use just SSL without client certificates, we dont have to lower the SECLEVEL. I think the issue is just in how Heidi chooses the certificate signature algorithm.

**Screenshots or Crash reports**

HeidiSQl Client Hello:

![heidi_hello](https://user-images.githubusercontent.com/24922284/220327672-2e5e8e5a-32e3-41b7-866d-0254bc397eb0.png)

Server Hello without SECLEVEL=1:

![server_hello_secure](https://user-images.githubusercontent.com/24922284/220328328-0ffd3227-a4d4-400a-8c96-3ec0b7acb449.png)

Server Hello with SECLEVEL-1:

![server_hello_insecure](https://user-images.githubusercontent.com/24922284/220328794-c4244d91-3a44-4484-9348-7d5066e45d41.png)

As you can see here, HeidiSQL completes the handshake using the `rsa_pkcs1_sha1`:

![cert_exchange_complete](https://user-images.githubusercontent.com/24922284/220329510-c53fda63-31a5-42e3-bef2-0f1548d44849.png)

**Comment by ansgarbecker** [comment]
Related: https://github.com/HeidiSQL/HeidiSQL/issues/1426#issuecomment-1399570426

**Comment by ansgarbecker** [comment]
In the MariaDB docs I found:
> [mysql_ssl_set()](https://mariadb.com/kb/en/mysql_ssl_set/) must be called before attempting to use [mysql_real_connect()](https://mariadb.com/kb/en/mysql_real_connect/). TLS support must be enabled in the client library in order for the function to have any effect.
And HeidiSQL did this yet in the wrong order, so that may be the crux here.
Next build (6856) sets the TLS versions before calling preparing the SSL connection parameters.

**Comment by ansgarbecker** [comment]
Parallel discussion taking place in the [forum](https://www.heidisql.com/forum.php?t=42177#p42188)

**Comment by ansgarbecker** [comment]
I think I got it now. There were two issues, one of them is that older libmysql and all libmariadb are not able to connect to newer SSL-enabled servers. This issue is not in HeidiSQL itself. That's why I just added libmysql from the brandnew MySQL 8.4.0 to the the nightly built installer.

The other issue was in HeidiSQL, and caused it not to work even with that newer libmysql. This was due to some wrong offsets in the `mysql_options()` constants, like `MYSQL_OPT_USE_REMOTE_CONNECTION`. Some of these [were removed in MySQL 8](https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html), and HeidiSQL still worked with the old offsets.

You can [download the nightly built installer](https://www.heidisql.com/download.php#nightlybuilds) to get the newer libmysql.

Please report back if that now works.
