### ISSUE TITLE
Incorporate `~/.ssh/config` file so that Hostname aliases can be used.

### ISSUE THREAD

**Issue by cyclr-adrian** [HeidiSQL/HeidiSQL#1775]
The SSH config file stored in `c:\users\{username}\.ssh\config` (on Windows) can store SSH HostName aliases, for example:
```
Host MyFirstFriendlyHostName
    HostName 123.123.123.1

Host MySecondFriendlyHostName
    HostName 123.123.123.2
```

It gives the flexibility that if one of my host IP address changes, I only have to change it in one place, in the `~/.ssh/config` file.

**N.B.** The aliases in this file can also be used by `c:\users\{username}\.ssh\known_hosts` (on Windows) which makes that easier to keep up to date.

In MySQL Workbench, you have the option to reference these files in the application's preferences:
![image](https://user-images.githubusercontent.com/95350065/223194926-fff1fc79-9c82-433c-bdef-514b8099579f.png)

With these preferences set in MySQL Workbench you can then use the configured alias `MyFirstFriendlyHostName` instead of the IP address `123.123.123.1` when creating a new connection:
![image](https://user-images.githubusercontent.com/95350065/223194713-846d3ada-99c6-400f-ac83-645f2e5e1b16.png)

It would be good if we could use the same aliasing technique in HeidiSQL.

**Comment by ansgarbecker** [comment]
The SSH tunnel gets created through plink.exe or the Windows own OpenSSH client (`ssh.exe`). Support for using the `.ssh` folder files should be part of these tools, not of HeidiSQL directly. This is different from the SSH tunnels in MySQL Workbench which seems to have an own/internal SSH implementation. Further on, I'm nearly sure that the Windows OpenSSH executable already supports a known_hosts file, and also a config file. Not sure if plink looks at the same files, but ssh.exe does:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/5059fc59-7195-4402-a48a-c27d55205254)

**Comment by ansgarbecker** [comment]
If this is still an issue please provide feedback.
