### ISSUE TITLE
PlanetScale support

### ISSUE THREAD

**Issue by dan-willett** [HeidiSQL/HeidiSQL#1776]
**Is your feature request related to a problem? Please describe.**
I would like to use HeidiSQL to access my PlanetScale database, however, PlanetScale requires an SSL connection.

**Describe the solution you'd like**
Add a network type for PlanetScale that uses the Windows CA certificate for verifying the PlanetScale SSL certificate.

**Describe alternatives you've considered**

**Additional context**
https://planetscale.com/blog/connect-any-mysql-client-to-planetscale-using-connection-strings
https://planetscale.com/docs/concepts/secure-connections
https://planetscale.com/docs/tutorials/connect-mysql-gui

**Comment by dudagervasio** [comment]
I have this issue too!

**Comment by alexop1000** [comment]
Just download the latest file from [here](https://curl.se/docs/caextract.html)
And then set "SSL CA certificate" to that file under SSL in HeidiSQL.

**Comment by hxer520** [comment]
已解决！
