### ISSUE TITLE
Run part of script by select it

### ISSUE THREAD

**Issue by sadeq-n-yazdi** [HeidiSQL/HeidiSQL#1778]
**Is your feature request related to a problem? Please describe.**
In many times, I use the SQL Editor to write multiple queries to run and check the result. If I run it, all the queries will run and the results comes into separate tabs, that is great. But in many cases, I just need to run one of my queries and I prefer to not run all the queries at once. So I think it is good to be able to run a selected query. A shortcut like `Shift-Enter`, `Ctrl-Enter`, `Shift-F9` or `Ctrl-F9` make it more great.
This is specially useful when you have several queries with long runtime or make high amount of load on server.

**Describe the solution you'd like**
User write several queries, then select one of them, then run partial query/queries and just the selected query/queries run and result(s) appears in tab(s).

**Describe alternatives you've considered**
Add shortcut that toggle comment prefix of line/selected lines of query can resolve this requirement too. So when user press `Ctrl-/` the line or the selected lines of the query will be marked as comment and if it is already commented it remove the comments. This make user able to select which part of query run.

**Additional context**
sample multiple query that one of them is commented to not run can be similar to this:

```sql
SELECT 
    field1, field2, field2
FROM 
    aTable
JOIN
    anotherTable ON 
WHERE 
   ....

-- this query is not going to run
-- SELECT 
--     field1, field2, field2
-- FROM 
--    aTable
-- JOIN
--     anotherTable ON 
-- WHERE 
--   ....

SELECT 
    field1, field2, field2
FROM 
    aTable
JOIN
    anotherTable ON 
WHERE 
   ....
      
```

**Comment by ansgarbecker** [comment]
HeidiSQL already supports all of your ideas, if I get them right:
* <kbd>Ctrl+F9</kbd> executes the query in the text selection (only available if any text is selected)
* <kbd>Shift+Ctrl+F9</kbd> executes the query under the cursor

![grafik](https://user-images.githubusercontent.com/7986591/224311773-33fa0617-9324-49ca-9cf1-4e2a34cf9eef.png)

* in the same context menu you find a "Un/comment" item, which toggles a double-dash comment for the selected line(s).

For all of these items, you can change a keyboard shortcut, in Tools > Preferences > Shortcuts.

**Comment by ansgarbecker** [comment]
Note the "Run current query" requires single queries to be separated by semicolon, like in my screenshot.

**Comment by BlueMatthew** [comment]
If there is selected sql, make "Run" to just run selected sql, it is better
