### ISSUE TITLE
Unable to set default value for BIT field datatype.

### ISSUE THREAD

**Issue by gecko9** [HeidiSQL/HeidiSQL#1779]
Preconditions

    HeidiSQL Portable version: 12.3.0.6657 (64 Bit)
    Database type and version: mysql Ver 10.4.13-MariaDB
    OS: Windows 10 Pro

**Describe the bug**
Cannot set default value for BIT(1) field. This is a game-over bug for users of HeidiSQL. The BIT field is a legit field but cannot be used with HeidiSQL. It would seem trivial yet essential to fix this bug.

I always get this error when saving:
LocalMySQL: Error
SQL Error (1067): Invalid default value for 'cached'._

A field defined as BIT(1) NOT NULL DEFAULT '\'0\'  in the table-design-view, click save button results in an error-dialog with the message "SQL Error (1067): Invalid default value for 'cached'".

**To Reproduce**

1. Add a BIT(1) column to any MySQL table. Or create new table then add.
2. Set the default value to b'0'.
3. Click Save button to see the error.

**Comment by ansgarbecker** [comment]
Did you try to set `b'0'` in the expression box? Should work as it does for me here:

![grafik](https://user-images.githubusercontent.com/7986591/224536461-8922f1a7-fa75-475b-92d4-eadd372b15b8.png)

**Comment by gecko9** [comment]
Thank you Ansgar, it works and that is what I should have done! Somehow my attention got locked into the Custom Text entry box. Plus having read a few past entries that seemed to indicate this is an outstanding issue.

Also I would like to take this opportunity to thank you very much for producing HeidiSQL.

**Comment by ansgarbecker** [comment]
Thanks a lot for your appreciation!

Indeed HeidiSQL's support for BIT values in the grid cells is quite lousy. But this is another topic.
