### ISSUE TITLE
Allow sorting and filtering in tree on "Table Tools" dialog

### ISSUE THREAD

**Issue by Mondane** [HeidiSQL/HeidiSQL#178]
## Steps to reproduce this issue

1. Make a db connection
2. Right click a database
3. Select 'Export database as SQL'
4. Select the tables to export.

## Current behavior
In this view, it's not possible to order te tables on, for instance number of rows or size.

## Expected behavior
To make it easy to skip specific tables, sorting and filtering should be available. This would behave the same as in the database tab.

## Possible solution
![image](https://user-images.githubusercontent.com/1150272/36979132-d6cece46-2086-11e8-8faf-5dca604e159f.png)

## Environment

* **HeidiSQL version:**  9.5.0.5196

**Comment by ansgarbecker** [comment]
Well you cannot compare the tree structure with the list on the Database tab. But I can probably apply the same features from the database tree on the main form to the tree on the table tools dialog. These are:
* database filter box
* table filter box
* favorites with yellow stars (does that make sense there?)

**Comment by Mondane** [comment]
That would be great!

About those stars, they could be usefull if you limit those only to this filter. I have several database for which I most of the times export a specific set of tables. A star preset would be usefull.

**Comment by jpurpleman** [comment]
Wondering where this stacks up against other features?  Will we see this implemented down the road?  Thank you.

**Comment by Kcko** [comment]
> Well you cannot compare the tree structure with the list on the Database tab. But I can probably apply the same features from the database tree on the main form to the tree on the table tools dialog. These are:
> 
> * database filter box
> * table filter box
> * favorites with yellow stars (does that make sense there?)

table filter box  with regexp functionality same as main window + type of object (table / view / procedure / trigger ..) would be fantastic  (its important too , is it possible)?

**Comment by Kcko** [comment]
What is the status? :)

**Comment by ansgarbecker** [comment]
@Kcko I'm planning this for the next release. Please be a bit more patient. I'm still doing this all in my few hours after normal work.

**Comment by Kcko** [comment]
> @Kcko I'm planning this for the next release. Please be a bit more patient. I'm still doing this all in my few hours after normal work.

I know that, Im sorry, I feel the same way but I don't own top OpenSource like you do :-)

When I keep asking, I don't mean it in a bad way, I just want it to be remembered :-), I'm really looking forward to it, I'll tone it down (myself), thanks!

**Comment by ansgarbecker** [comment]
No problem, thanks for being patient. I just tagged this issue with the next release milestone 12.7, which means I cannot forget it ;)

**Comment by ansgarbecker** [comment]
New builds now have the two filter boxes on top of the objects tree:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/24727228-0696-4ab9-8aae-6bf7da0b4f62)

What I would like to leave away is the dropdown with the recently used filters, as these would make them complicated to use on the main window.

Note the find/export/etc. actions only process a table if it's checked _and_ visible now. I think this is what the user expects here. Invisible nodes are _not_ processed.

**Comment by Kcko** [comment]
Finally! :-) Awesome!

**Comment by jpurpleman** [comment]
Great!  Thank you for the feature addition!  I love it.

I do have some feedback.  When filtering the tables I mis-typed a 0 and put in a ).  The regex didn't like it.

Please see the screenshot of the log and what it did.  I expected there to be no tables listed.

![2024-02-12_14:47:04](https://github.com/HeidiSQL/HeidiSQL/assets/8206604/7f2b8119-15d0-4d52-a1c7-2c38215e7a28)

**Comment by ansgarbecker** [comment]
@jpurpleman I think hiding the tables with an invalid regex would make the user think the expression is correct and not just matching. Please watch out for the regular expression errors in the lower log panel. Functionality is the same on the main window.

I will close this for now. If you find bugs, please report in a separate ticket.
