### ISSUE TITLE
No 'open a blank query tab' present when many tabs are opened (2lines)

### ISSUE THREAD

**Issue by SamKur** [HeidiSQL/HeidiSQL#1781]
**Preconditions**

* HeidiSQL version: 12.4.0.6665
* Database type and version: MySQL 8.0.32
* OS: Windows 10

**Describe the bug**

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
You can rightclick the tabs, or just use the main menu "Query" > "New query tab"
