### ISSUE TITLE
HeidiSQL doesn't support TLS 1.2 with MYSQL ?

### ISSUE THREAD

**Issue by kemecs** [HeidiSQL/HeidiSQL#1785]
**Preconditions**

* HeidiSQL version: 12.4.0.6665
* Database type and version: MySQL 8.0.28  mysql-*******.mysql.database.azure.com
* OS: Windows10

![image](https://user-images.githubusercontent.com/8629116/226581710-4ce64570-1fca-4e13-8702-f7bc9408e52a.png)

I get the connection error shown in the picture when using TLSv1.2. 

(Microsoft will also stop supporting connection over TLSv1 and TLSv1.1 to Azure Database for MySQL - Single server before 3 April 2023, to comply with security standards.)

**Comment by ansgarbecker** [comment]
What's the filename and the version number of the used library in your session?

**Comment by ansgarbecker** [comment]
No problem.
