### ISSUE TITLE
Unable to load libpq-15.dll on HeidiSQL (module not found)

### ISSUE THREAD

**Issue by OSPanel** [HeidiSQL/HeidiSQL#1790]
**Preconditions**

* HeidiSQL version: 12.4.0.6659
* Database type and version: PostgreSQL 15.0.2
* OS: Windows 10 (Version 22H2, OS Build 19045.2486, 64-bit Edition)

**Describe the bug**

Unable to load libpq-15.dll (module not found)
MS VC++ 2005-2022 (x86 & x64) installed 27.03.2023 from https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
Everything that was needed was installed. The computer has rebooted.

All other dll is ok (libpq-10.dll & libpq-12.dll)

**To Reproduce**

Create a new connection using the libpq-15.dll library and try to activate it.

**Screenshots or Crash reports**

![Error](https://ospanel.io/files/err/hsql.png)

**Comment by ansgarbecker** [comment]
For me on Windows 11 64bit that libpq-15.dll works normally. You need to find out which module cannot be found. Not a big task if you use ProcessExplorer: https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer 
When ProcessExplorer runs,
* set the filter like in the following screenshot
* run HeidiSQL
* watch out for DLLs with a failure:

![grafik](https://user-images.githubusercontent.com/7986591/230576041-ae4f911b-1c9f-4378-a692-3c25b901f3f3.png)

**Comment by OSPanel** [comment]
ok, I did this and determined which files were missing.
To make it work, I had to download the PostgreSQL 15 distribution and take the following files from there:

- bin\libcrypto-3-x64.dll
- bin\libintl-9.dll
- bin\libssl-3-x64.dll
- bin\libwinpthread-1.dll

I put these files in a folder with Heidisql, and only after that the error disappeared.

**Comment by ansgarbecker** [comment]
I am just realizing these 4 files are just missing from the portable package, while the installer executable contains them. I will include these in the v12.5 portable, soon.

**Comment by britisharmy** [comment]
why was this closed, no pr was created. Is there a license that would allow the dll to be embedded within heidisql?

**Comment by ansgarbecker** [comment]
... because I already released the v12.5 installer and portable package, and this time I was sure to include the missing files mentioned above. You just need to update to v12.5.
