### ISSUE TITLE
Explain Analyzer on MariaDB.org unavailable

### ISSUE THREAD

**Issue by Rytiss** [HeidiSQL/HeidiSQL#1795]
**Preconditions**

* HeidiSQL version: 12.4.0.6670
* Database type and version: MariaDB
* OS: Windows 11

**Describe the bug**

Right clicking a query in the processlist has two explain options: normal EXPLAIN query, and EXPLAIN analyzer on mariadb.org. The latter does not work - the explain analyzer seems to have been removed from mariadb.org

**To Reproduce**

1. Go to Host -> Processes
2. Right click a query
3. Choose Explain analyzer on mariadb.org
4. HTTP 404 error

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Removed menu items and code for the next nightly builds.
