### ISSUE TITLE
SQL export show improper % values

### ISSUE THREAD

**Issue by honzak-lib** [HeidiSQL/HeidiSQL#180]
## Steps to reproduce this issue

1. Step 1; Open SQL export (Export database as SQL)
2. Step 2; Choose some bigger table in some database and let it export to some file. Watch progress and check percentage values. They get weird and in my table > 3mil rows I got to 135%....

## Expected behavior

It should show proper percentage value going to 100%.

## Environment

* **HeidiSQL version:** 
9.5.0.5261
  
* **Database system and version:** 
MySQL 8.03
  
* **Operating system:** 
Windows 10 64bit Czech
  

![2018-03-06_06](https://user-images.githubusercontent.com/37121107/37054854-5f30d5a0-2180-11e8-8739-dae1c7da1fdb.png)

**Comment by rentalhost** [comment]
I think that it is related to the imprecision of `SHOW TABLE STATUS LIKE` vs `SELECT COUNT(*)`. Then I think that we have two solutions here: use the `COUNT(*)` (it will requires a new query before export) or then just display `100%` when it have more than `100%` (because of the imprecision).

**Comment by honzak-lib** [comment]
Thanks for reply. Not a big issue, thought it is in code rather than in Mysql. Yeah, my tables are in Innodb.

**Comment by sirber** [comment]
Same issue with TokuDB tables.
