### ISSUE TITLE
Help window is incomplete

### ISSUE THREAD

**Issue by manuelmsni** [HeidiSQL/HeidiSQL#1805]
**Preconditions**

* HeidiSQL version: 12.3.0.6589
* Database type and version:  
* OS: Windows 10 pro

**Describe the bug**

**To Reproduce**

I dont know how it happened but I can not fix it by closing Heidi and opening it back.

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/5380991/230c83d9-6fd3-4853-8ec5-dc21d3a68f86)

**Comment by ansgarbecker** [comment]
That can happen if you resize the panels down to a minimum. Even you cannot reset the size yourself, at least not for the left side. The bottom panel can be revealed if you make the whole form higher. However, the next nightly build restricts the 3 panels from being resized to a 0 value.

**Comment by manuelmsni** [comment]
Oh, thanks. Good to know. :)
 Anyway, I updated Heidi to the latest version, but it still doesn't show the left panel.
 How can I fix it?
 Thank you in advance.
