### ISSUE TITLE
Truncating tables doesn't reset row count

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1807]
When right clicking tables in the list of database contents and selecting "Empty table(s)", the Rows count is not reset.
Force refresh F5 does not reset the count either.

Version 12.5.0.6677

![image](https://github.com/HeidiSQL/HeidiSQL/assets/359192/0000e650-0023-4d8b-b6f7-6ceef13e147c)

**Comment by ansgarbecker** [comment]
As you may know, the row count on InnoDB tables takes some time to validate after deleting rows. Or wasn't that an InnoDB table?

**Comment by timint** [comment]
Yes those are InnoDB. And you could be right about the delay. When there are just a few rows it works like expected.
