### ISSUE TITLE
TLS1.3 support

### ISSUE THREAD

**Issue by tqre-mc** [HeidiSQL/HeidiSQL#1811]
**Is your feature request related to a problem? Please describe.**
TLSv1.3 only connections are not supported.

**Describe the solution you'd like**
TLSv1.3 support

**Describe alternatives you've considered**
TLSv1.2 works, but the newer protocol would be preferred as the only option.

**Additional context**
We have a MariaDB cluster with HAProxy load balancer.
When I configured the server cluster and HAProxy to accept only TLSv1.3 connections, I get the following error on HeidiSQL:

`SSL connection error: The function requested is not supported. Error 0x80090302(SEC_E_UNSUPPORTED_FUNCTION)`

Testing with other clients (Beekeeper Studio), TLSv1.3 only works fine.

**Comment by ansgarbecker** [comment]
In 51da7c8efc890ebdb394dfa53f911b64223a53e8 I already told libmariadb/libmysql to support TLS versions up to 1.3. Did you already try the different libraries for it? I recommend libmariadb.dll, but please also try the others.

**Comment by Lotendan** [comment]
Here a reference for TLS v1.3 in SChannel: https://jira.mariadb.org/browse/CONC-653

**Comment by ansgarbecker** [comment]
@tqre-mc please retry with the next (soon coming) release v12.7 with updated libmariadb.dll. I just updated it for #1946 .
