### ISSUE TITLE
Why client_ed25519.dll isn't inluded by default?

### ISSUE THREAD

**Issue by luceat-lux-vestra** [HeidiSQL/HeidiSQL#1814]
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: MariaDB 10.11.2
* OS: Windows 10

**Describe the bug**

I need to put client_ed25519.dll from mariadb plugin folder to heidisql plugins folder.

`D:\path\to\MariaDB\lib\plugin`
`C:\Program Files (x86)\Common Files\MariaDBShared\HeidiSQL\plugins`

**To Reproduce**

1. Install MariaDB
2. Check client_ed25519.dll in `C:\Program Files (x86)\Common Files\MariaDBShared\HeidiSQL\plugins`
3. not available...

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Same here, duplicate to #754 - `client_ed25519.dll` integrated since v10.3. Please try the official installer from heidisql.com
