### ISSUE TITLE
The default value of the timestamp data is incorrect and cannot be run after being exported

### ISSUE THREAD

**Issue by Ronass** [HeidiSQL/HeidiSQL#1817]
**Preconditions**

* HeidiSQL version: v12.5.0.6677
* Database type and version: mysql 8.0.25
* OS: Windows 10 Home Edition

**Describe the bug**

When I exported the sql, I found that the default value of the timestamp type in the sql statement was treated as a string. I set the value to CURRENT_TIMESTAMP, but the exported value is a string
`create_time TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP' COMMENT '创建时间',`

When I delete the string concatenation, the SQL executes normally

**To Reproduce**

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/13976637/500f840b-eb5d-4c25-858e-e612843766c5)

![image](https://github.com/HeidiSQL/HeidiSQL/assets/13976637/201b1122-8f10-4557-9215-29bbdc406cb1)
When executed properly
![image](https://github.com/HeidiSQL/HeidiSQL/assets/13976637/64c64b30-31f4-4420-ad9a-215e147b3e79)

**Comment by ansgarbecker** [comment]
Strange, on MySQL 8.0.33 my column default gets converted to `now()` after creating it with `CURRENT_TIMESTAMP`. So I'm not able to create a column with a `CURRENT_TIMESTAMP` default here. Perhaps this was different in MySQL 8.0.25?

**Comment by Ronass** [comment]
First of all, thank you for your reply


The screenshot below shows the default Settings when I created the table

![image](https://github.com/HeidiSQL/HeidiSQL/assets/13976637/d1ea8261-1176-4b79-b8e8-94b285eadf1b)

I installed Mysql 8.0.33 and created a new table that changed to `now()` when setting the default value of the column to `CURRENT_TIMESTAMP`, so I'm not sure if this is a BUG, but I'm sure it happened after I updated hiediSQL

For now, I can only manually fix this default value problem and then execute my SQL

This tool works very well. I like it
