### ISSUE TITLE
Error in adding auto initialized timestamps in table designer

### ISSUE THREAD

**Issue by abhishek--ranjan** [HeidiSQL/HeidiSQL#1826]
**Preconditions**

* HeidiSQL version:   12.5.0.6680
* Database type and version:  MySQL 8.0.32  & above 
* OS:  windows

**Describe the bug**

While table creation or alteration on Heidi, to add datetime or timestamp columns with auto initialized value it throws an error as below.

SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') ON UPDATE (CURRENT_TIMESTAMP) AFTER `linkDate`'

The designer generates the below query while in create or alter 

```sql
ALTER TABLE `tester`
	ADD COLUMN `linkDate` DATETIME NULL DEFAULT (CURRENT_TIMESTAMP()) ON UPDATE (CURRENT_TIMESTAMP()) AFTER `name`;
```

correct query that works  is as below
```sql
ALTER TABLE `tester`
	ADD COLUMN `linkDate` DATETIME NULL DEFAULT  CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `name`;
```

**To Reproduce**

To reproduce 
1.  run the below query replacing table & field name
```sql
ALTER TABLE `tester`
	ADD COLUMN `linkDate` DATETIME NULL DEFAULT (CURRENT_TIMESTAMP()) ON UPDATE (CURRENT_TIMESTAMP()) AFTER `name`;
```

**Comment by ansgarbecker** [comment]
I thought I already fixed that in #1800 but there seem to be some exceptions to the rule again. Please also try out `curdate()` instead of `CURRENT_TIMESTAMP`.

**Comment by abhishek--ranjan** [comment]
If you use  CURRENT_TIMESTAMP() it gets converted to NOW(), but if you use now() it does not work again. while it should work, this is a mysql issue it seems.
Heidi generates the below query, the single quotes should be removed.

ALTER TABLE `tester`
	ADD COLUMN `linkDate` DATETIME NULL DEFAULT  'CURRENT_TIMESTAMP' ON UPDATE 'CURRENT_TIMESTAMP' AFTER `name`;

**Comment by ansgarbecker** [comment]
The `ON UPDATE (...)` clause now does not use parentheses in the next build: `ON UPDATE CURRENT_TIMESTAMP()`.
Also reported on https://www.heidisql.com/forum.php?t=41405

**Comment by aarontravass** [comment]
This happens with PostgreSQL as well. I selected `CURRENT_TIMESTAMP` in the expression for default value.

```sql
ALTER TABLE "Ticket"
	ALTER COLUMN "updatedAt" TYPE TIMESTAMP,
	ALTER COLUMN "updatedAt" SET NOT NULL,
	ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP(precision);
/* ERROR:  syntax error at or near "precision"
LINE 4: ... COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP(precision)
      
```
