### ISSUE TITLE
Remove double quotes from description command line switch

### ISSUE THREAD

**Issue by andreashager** [HeidiSQL/HeidiSQL#1827]
**Preconditions**

* HeidiSQL version: 12.5.0.6680
* Database type and version: not necessary 🙂
* OS: Windows 11 Version 22H2 (Build 22621.1928)

**Describe the bug**

If I use the Command line switches and launch HeidiSQL from WSL2 and quote the description argument and add spaces (--description="Test Test"), the quotes and spaces are not correctly stripped and spaces are removed from the argument and shown in the connection manager.

I would expect that the quotes are completely stripped from the description argument and spaces are added.

**To Reproduce**

1. Open the WSL 2 Terminal
2. Open HeidiSQL with Command Line Switches: "/mnt/c/Program Files/HeidiSQL/heidisql.exe" "--host=127.0.0.1 --port=52573 --user=root --password=root --description="Test1 Test1""

**Screenshots or Crash reports**

![Connection-Manager](https://github.com/HeidiSQL/HeidiSQL/assets/3351175/900f9b74-9ce6-429f-b7f3-05a85b44cb98)

**Comment by ansgarbecker** [comment]
Did you notice you have a duplicate doublequote at the end: `--description="Test1 Test1""`?

**Comment by andreashager** [comment]
Yap I noticed the double quotes at the end - the code part comes from DDEV where HeidiSQL is used to launch a local database connection. There this command is done like this, maybe there I need a different quoting 🤔 

https://github.com/ddev/ddev/blob/master/pkg/ddevapp/global_dotddev_assets/commands/host/heidisql

**Comment by andreashager** [comment]
@ansgarbecker 

That was a problem with double quoting the arguments from DDEV. I did a PR there that should fix the problem with double quoutes in the connection manager: https://github.com/ddev/ddev/pull/5084

Thanks for pointing out and your time 😊

**Comment by ansgarbecker** [comment]
Thanks a lot for consistent feedback and leaving a reference to the ddev ticket!
