### ISSUE TITLE
Application hang/crash when refreshing the table grid after the connection got closed

### ISSUE THREAD

**Issue by Geolim4** [HeidiSQL/HeidiSQL#183]
## Steps to reproduce this issue

When working on a database with short timeout, if you attempt to refresh the table grid more than one time the application hang then crash after the exception handler popup came.

## Current behavior

Crash

## Expected behavior
No crash

## Possible solution

See bug report:
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1793875/bugreport.txt)

## Environment
Windows10x64

* **HeidiSQL version:** 
![image](https://user-images.githubusercontent.com/1332071/37162093-a98e850a-22f4-11e8-9e2f-409569e556f6.png)

* **Database system and version:** 
Mariadb/MySQL
* **Operating system:** 
Windows10x64

**Comment by mariusz-buk** [comment]
I noticed the same. Here is screenshot with query and connection closed by server: https://1drv.ms/u/s!AlRmUk4xSO1ih5hLP8JwKDQmA373ow

**Comment by Geolim4** [comment]
HeidiSQl is getting too many exception when working with a remote SQL (SSH tunnel) that enforces timeout.
I get plenty of exception in the log area:
`/* Access violation at address 0000000000AB8BDC in module 'heidisql.exe'. Read of address 00000027000000FB */` 
`/* Access violation at address 00007FF95C080DC2 in module 'libmysql.dll'. Read of address 0000000000000008 */`
Win10x64

**Comment by ansgarbecker** [comment]
You should probably tell HeidiSQL to keep the connection alive, by setting a ping interval:

![grafik](https://user-images.githubusercontent.com/7986591/40196857-037d408e-5a12-11e8-9f6d-bde003abd59e.png)

**Comment by Geolim4** [comment]
Nope still getting a lot of error in SSH mode, even with settings up ping every x seconds:
> /* Access violation at address 00007FFB67940DC2 in module 'libmysql.dll'. Read of address 0000000000000008 */

It occurs at the first connection and in every re-connection after a timeout.
