### ISSUE TITLE
Unable to connect to database in debian 12 server with Postgresql 15 

### ISSUE THREAD

**Issue by r0cketfuel** [HeidiSQL/HeidiSQL#1839]
**Preconditions**

* HeidiSQL version: 12.5.0.6677
* Database type and version: Postgresql 15.3
* OS: Debian 12

**Describe the bug**

Im trying to connect to my postgresql server remotely (from the same network) using username and password method. Tried several configs in pg_hba.conf. The only way i can connect i get "access denied" in console and my database is not shown. I can however connect normally through pgAdmin 4.

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
"Access denied" normally points to a wrong user and/or password.

If you have non-ASCII characters in your password, these may be broken when HeidiSQL stored it and reads it afterwards. You can work around that by resetting the password to something with ASCII chars only, or by checking the "Prompt for credentials" checkbox.

**Comment by r0cketfuel** [comment]
Thank you for your reply. My password is the same that I used to connect with MySQL before fresh Debian install. It involves some non-ascii characters but no problems connecting to MySQL. I tried asking for credentials but I get the same error
![1](https://github.com/HeidiSQL/HeidiSQL/assets/114667259/7b8f04aa-e985-4110-a81b-e218f4d3ce2d)

**Comment by ansgarbecker** [comment]
Probably the password contains a backslash and/or a single quote?
Both of these are the only characters getting escaped with a backslash. So, for instance, a password of `foo'b\ar` is escaped by HeidiSQL to `foo\'b\\ar`. According to the [docs](https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.5) this is the right way, but who knows.

Did you select the `libpq-15.dll` library?

Can you test with a different password without these chars?

**Comment by ansgarbecker** [comment]
Your log content says you are connected, and the "access denied" message is related to something else. You should turn on debug logging, so it probably gets clearer what's happening right before that "access denied".

**Comment by r0cketfuel** [comment]
Thank you for your time. I had to roll back to mysql database so I wont be using postgres again. Sorry for the inconvenience. Delete this thread if needed. Thank you again.
