### ISSUE TITLE
SQL export option 'Copy mysqldump command' not working

### ISSUE THREAD

**Issue by r3ganbr0wn** [HeidiSQL/HeidiSQL#1845]
**Preconditions**

* HeidiSQL version: 12.5.0.6677
* Database type and version: MySQL 8.0.34
* OS: Ubuntu 20.04

**Describe the bug**

The SQL export option 'Copy mysqldump command' does not work.  When clicking the option, it does not check on or check off and no mysqldump command is included in the export.

**Screenshots or Crash reports**

![CAPTURE](https://github.com/HeidiSQL/HeidiSQL/assets/31259692/1582fba4-992c-4d76-ae6f-4af5a66c64dd)

**Comment by ansgarbecker** [comment]
This is a misunderstanding, probably because the menu item is not clear about that. You click the "Copy..." menu item to copy the mysql command to your clipboard. So this is not some option for the export stream.

**Comment by r3ganbr0wn** [comment]
Thank you for clarifying.
