### ISSUE TITLE
Allow to not insert DELIMITER when exporting database

### ISSUE THREAD

**Issue by yanis60** [HeidiSQL/HeidiSQL#1847]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to not add DELIMITER when exporting to sql file

**Comment by ansgarbecker** [comment]
If the current delimiter command is not a problem for you, then why are requesting this?

**Comment by yanis60** [comment]
sometimes i need to remove delimiters ( i do it using notepad++)

**Comment by ansgarbecker** [comment]
Then why do you need to remove them? It makes no sense to me, as that makes the query invalid.

**Comment by yanis60** [comment]
i have a software that runs an sql file, and a delimiter is invalid for him.
that why i remove delimiters manually.

**Comment by ansgarbecker** [comment]
Ah ok, but how do you tell that software to use `//` as a delmiter, if not per `DELIMITER //` ? Sounds like a quirky software to me.

**Comment by yanis60** [comment]
i completly remove delimiter // and delimiter; using notepad++ in order to run sql file successfully

**Comment by ansgarbecker** [comment]
Removing the DELIMITER command would make the SQL export inconsistent, and it would not run through on servers. Adding such exotic options can also overcrowd the UI with moreorless useless options. Unless not some others have similar use cases, I will close this.
