### ISSUE TITLE
Collation error - uft8mb4

### ISSUE THREAD

**Issue by JonathanVillenaES** [HeidiSQL/HeidiSQL#1850]
**Preconditions**

* HeidiSQL version: 12.5.0.6677
* Database type and version: MySQL 8.0.30
* OS: Windows 10

**Describe the bug**
When I use HeidiSQL to edit a cell containing text with emojis, the text content is cut off. This problem does not occur when I use other tools such as DBeaver, where the text is displayed in its entirety without being cut off.
The emojis that I have tried and I get this problem are these: 📣 and 🔥 .
Important, the collation used is 'utf8mb4_0900_ai_ci'.

**To Reproduce**
1. Open HeidiSQL and connect it to the database in question.
2. Locate a Cell with Emojis: Search for a cell containing text with emojis.
3. Disconnect from database and connect again.
4. Edit the Cell: Try to edit the cell containing the text with emojis.
5. Observe the Error: You will notice that the text is cut, not showing the complete text containing emojis.
6. Compare with DBeaver: Open the same database with DBeaver and verify that the text is completely displayed in this tool, confirming that it is a HeidiSQL specific problem.

IMPORTANT, the collation used is 'utf8mb4_0900_ai_ci'.
The text used for the example is this one, ***REPEATING IT 15 LINES***:
📣 {URL_Short_STRING} 🔥 

**Screenshots or Crash reports**

![0](https://github.com/HeidiSQL/HeidiSQL/assets/121164789/0b6dfa1d-ffdf-4e45-9e95-7cb9b0f3c61e)
![1](https://github.com/HeidiSQL/HeidiSQL/assets/121164789/f93a4325-b3b9-4d57-983e-7731350d7f46)
![2](https://github.com/HeidiSQL/HeidiSQL/assets/121164789/fecbece1-aa6a-43f6-9df2-179df2e2fa48)
![3](https://github.com/HeidiSQL/HeidiSQL/assets/121164789/7777f37a-8e20-4f5d-b2f8-9ca92193fdef)

**Comment by ansgarbecker** [comment]
Next build fixes that issue. This is similar to #1351. HeidiSQL selects larger text values using `LEFT(col, 256)`, and the later loading of the full value for editing sometimes detects a wrong number of characters, so the row does not get fully loaded. I just added an additional check for `LEFT` or `SUBSTR` in the original column name, making it safe at least in MySQL.
