### ISSUE TITLE
Converting data

### ISSUE THREAD

**Issue by wvankastel** [HeidiSQL/HeidiSQL#1851]
**Preconditions**

* HeidiSQL version: 12.5.0.6691
* Database type and version: MariaDB 11.1.2 (MySQL)
* OS: Windows 10 and Windows Server 2016

**Describe the bug**

When I want to convert all text fields from, for example, "latin1_swedish_ci" to "utf8mb4_general_ci" a text field with Datatype TINYTEXT is converted to TEXT and Datatype TEXT is converted to MEDIUMTEXT. 

**To Reproduce**

1: table
2: Tab Tabel: [table name]
3: Sub tab: Options
4: default collation: choose other then is selected and click on the checkbox to convert
5. click save

**Screenshots or Crash reports**

1: ![image](https://github.com/HeidiSQL/HeidiSQL/assets/101640730/80dcbaa7-c799-499d-a5a5-6adb0cd6b827)
2: ![image](https://github.com/HeidiSQL/HeidiSQL/assets/101640730/958ef4c3-3a88-498f-b2d0-53823f987cac)
3: ![image](https://github.com/HeidiSQL/HeidiSQL/assets/101640730/220c81c0-b012-498d-b4ef-a5d3b029131d)

**Comment by ansgarbecker** [comment]
`utf8mb4` uses up to 4 bytes per character, while `latin1` uses 1 byte. I suppose MariaDB did that silent datatype change for you, so you don't lose text data which is too long for TINYTEXT/`utf8mb4`.
However, HeidiSQL itself does not do such a type conversion, so that must have happened through the server.
Can you confirm that?

**Comment by wvankastel** [comment]
No idea if MariaDB does that. If I change the collation per field then the dataType of a field is not converted. This only happens when converting. The fields have enough space for data.

**Comment by ansgarbecker** [comment]
Reading the documentation, it turns out to be true: https://mariadb.com/kb/en/setting-character-sets-and-collations/#table-level
> For example, an ascii TEXT column requires a single byte per character, so the column can hold up to 65,535 characters. If the column is converted to utf8, 3 bytes can be required for each character, so the column will be converted to [MEDIUMTEXT](https://mariadb.com/kb/en/mediumtext/) to be able to hold the same number of characters.

You can avoid such data type changes by setting the collation on each individual column, instead of using the "Convert data" checkbox.

**Comment by wvankastel** [comment]
Okay, so thats the reason. Thanks for helping me out!
