### ISSUE TITLE
Incorrect table name used

### ISSUE THREAD

**Issue by alexcesygroupcom** [HeidiSQL/HeidiSQL#1854]
**Preconditions**

* HeidiSQL version:  12.5.0.6687 
* Database type and version: MySQL 8.0.34
* OS: WIndows 7

**Describe the bug**

**To Reproduce**
Type the following.
First, type a select query with any table and put SQL comment dashes at the front so the query is commented.
Then, type another select query underneath without commenting it and run the query.
In the window below you will see query results from **table2** table.
Right click on any row and select "Duplicate row without keys" or press "Ctrl" + "Insert". Then click anywhere outside the rows for the row to be actually be inserted. The HeidiSQL will try to create another row in the **table2**  by using the field names from table1 which will usually cause an error if the column names in either tables are different.

--  SELECT * FROM table1
SELECT * FROM **table2**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Related: #1818

**Comment by ansgarbecker** [comment]
Should be fixed in the next nightly build.
