### ISSUE TITLE
Please add PostgreSQL 16 support

### ISSUE THREAD

**Issue by PrinceJunkie** [HeidiSQL/HeidiSQL#1855]
Please add PostgreSQL 16 support

//Edit: My fault, seems to work with libpq-15.dll

**Comment by ansgarbecker** [comment]
Is the `libpq-15.dll` not working on PG 16 as well?
Coming from the MySQL/MariaDB world, I hardly experienced breaking changes in the server versions with older libraries.

**Comment by PrinceJunkie** [comment]
Doesn't seem like that. That's the error message I'm getting:
![image](https://github.com/HeidiSQL/HeidiSQL/assets/76892599/d1849217-0398-409a-986f-dafe40740e0c)

**Comment by rhenanpaixao** [comment]
testei com o postgres 16.8 não funciona com a libpq-15.dll 
funcinou com a libpq-17.dll
