### ISSUE TITLE
Unable to import large CSV files

### ISSUE THREAD

**Issue by Glorou** [HeidiSQL/HeidiSQL#1857]
**Preconditions**

* HeidiSQL version: 12.5.0.6677
* Database type and version: MariaDB 10.11.2
* OS: Client OS Win 10, Server OS Debian

**Describe the bug**

HeidiSQL fails to process large CSV files for import in to a database
**To Reproduce**

Go to tools
Import CSV/Text File
Select a CSV over 1GB in size
Get Error: Stream read error

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/93338547/41524563-2328-4e1c-927d-daa0af4890e1)
I have a 800mb and a 1GB+ file, the application is unresponsive for the smaller file but still works, however it cannot process the larger file.

**Comment by ansgarbecker** [comment]
Probably happening due to a wrong file encoding, selected in the file-open-dialog. Please provide a screenshot of the import dialog.

**Comment by Glorou** [comment]
Switched to ANSI encoding, got this instead
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/12859011/bugreport.txt)

**Comment by ansgarbecker** [comment]
Please also try the "server parses" method. And a screenshot would still be useful.

**Comment by Glorou** [comment]
![image](https://github.com/HeidiSQL/HeidiSQL/assets/93338547/eb8188f5-9529-499d-9b78-c3b08f550fb9)
Server parses doesnt support ANSI encoding, only ASCII so it refuses to upload, I've also tried UTF-8 which notepad++ suggests is the file encoding

**Comment by ansgarbecker** [comment]
Using the last field encloser in the line terminator is clearly wrong. You need to use `\n` only as the line terminator, to get the server method working. Please test that. It doesn't matter if a field has multiple lines, as long as it's enclosed with the "field encloser".

**Comment by ansgarbecker** [comment]
@Glorou did you test the `\n` line terminator as suggested? I also recommend to update to the latest build first and test again.
If you still think there is a todo for HeidiSQL, please shout.
