### ISSUE TITLE
Search text on server - not showing all result tables

### ISSUE THREAD

**Issue by Eddcapone** [HeidiSQL/HeidiSQL#1859]
If there are results in many tables then not all result tables are showing. Only 10 tables are showing.

**Comment by ansgarbecker** [comment]
You can increase the maximum number of result sets in Preferences > SQL . This is also noted in the log panel:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/378d26ca-09d1-4cac-ae04-717cbcd51e06)

**Comment by Eddcapone** [comment]
Thx, it was not obvious enough and so I missed it.
