### ISSUE TITLE
Incomplete progress status when running query batch

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#186]
## Steps to reproduce this issue

Execute a large amount off statments - expected sse how much remains...

With current Heidi Version
![image](https://user-images.githubusercontent.com/11230133/37248784-d9693516-24b8-11e8-9193-c9f260fc1328.png)

With previous Heidi
![image](https://user-images.githubusercontent.com/11230133/37248806-2ba1b5c4-24b9-11e8-9306-6b189affc6d6.png)

## Current behavior

In this new versions off Heidi we havent how many statments Heid will execute/was executed and I can find time elapsed/time estart

## Expected behavior

Back again with this informations

## Environment

* **HeidiSQL version:** 9.5.0.5261 and to compare 9.5.0.5196
* **Database system and version:** MariaDB
* **Operating system:**  Win 10 64 (FullHD)

**Comment by G3ph4z** [comment]
I can't reproduce this issue with Heidi 9.5.0.5261 and MariaDB 10.2.13

**Comment by ansgarbecker** [comment]
Me too - works nice here with a sleep(10) query.

**Comment by lukinhaspm** [comment]
I try again in another pc....

Try this:

**Comment by lukinhaspm** [comment]
select sleep(5);
select sleep(5);
select sleep(5);

When you run in the old version, Heidi show step by step (Run 1, 2,3), if you run in the newest version, show only "Running 1 of 3", when starts second, they not show anything...

**Comment by ansgarbecker** [comment]
Well, I cannot reprodue an issue in the elapsed time. But that "Execute queries x to y of z" is buggy - x is always 1.

**Comment by lukinhaspm** [comment]
OK, agree

**Comment by ansgarbecker** [comment]
Forget my previous comment - that was the only thing working. I had the option "Send batch in one go" activated. Normal queries did not show up in the status bar. Should be fixed in the coming built.

**Comment by lukinhaspm** [comment]
Thanks a lot @ansgarbecker , works very fine!
