### ISSUE TITLE
"Duplicate row with keys" lead to error message

### ISSUE THREAD

**Issue by simonzhang98** [HeidiSQL/HeidiSQL#1861]
**Preconditions**

* HeidiSQL version:  12.5.0.6716
* Database type and version: MySQL 5.x or 8.x
* OS: Windows any

**Describe the bug**

After upgrade to the newest HeidiSQL version,   the command "Duplicate row with keys" and "Duplicate row without keys" will lead to an error message dialog

**To Reproduce**

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/73210279/159c3a41-3407-49fd-9632-271212bb207b)
![image](https://github.com/HeidiSQL/HeidiSQL/assets/73210279/62f03181-0a3e-4428-9f41-63f11722cf87)

**Comment by ansgarbecker** [comment]
Broken since #861

**Comment by ansgarbecker** [comment]
Fixed in the next build. Thanks for the report!
