### ISSUE TITLE
add a  name filter when export Database talbes to sql

### ISSUE THREAD

**Issue by techyang** [HeidiSQL/HeidiSQL#1871]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
add a  name filter when export Database talbes to sql, for example , if there are 10 tables in the database, some tables's name begin with 'user_', when  tabed  'user_' in th filter , only the tables with names  begin with 'user_' show in the view. 

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment]
Duplicate of #178
