### ISSUE TITLE
bit field default value bug 

### ISSUE THREAD

**Issue by star008** [HeidiSQL/HeidiSQL#1873]
ALTER TABLE `sys_dept`
	CHANGE COLUMN `deleted` `deleted` BIT(1) NULL DEFAULT 'b\'0\'' COMMENT '是否删除(1未删除；0已删除)' AFTER `update_time`;
	
	
	/* SQL错误（1067）：Invalid default value for 'deleted' */

**Comment by ansgarbecker** [comment]
Related forum thread: https://www.heidisql.com/forum.php?t=38149

Issue should be fixed through e028e3f9989b3ca3da214b5d6e785aabfb58e863

Please update and verify the new build 6895 works.

**Comment by ansgarbecker** [comment]
Duplicate of #1663
