### ISSUE TITLE
Support for password-protected key files for SSH tunnel

### ISSUE THREAD

**Issue by stefano-xy** [HeidiSQL/HeidiSQL#1876]
**Is your feature request related to a problem? Please describe.**
I have to connect to a database via a SSH tunnel. The authentication system requires certificates. The certificate file (private key) I have on my machine is password protected. It seems there's no way to make it work, if I specify a certificate file that is not password protected it works fine. It seems there's no way to specify the certificate file password.

**Describe the solution you'd like**
A small dialog window should show up and allow me to enter the password to unlock the certificate file.

**Describe alternatives you've considered**
None

**Additional context**
Tested with 12.5 and 12.6.

**Comment by ansgarbecker** [comment]
You mean key files with a passphrase, right? That should normally create a prompt dialog where you can enter the passphrase, like you can see [here](https://github.com/HeidiSQL/HeidiSQL/issues/284#issuecomment-559996831).

**Comment by ansgarbecker** [comment]
Closing due to missing feedback.
