### ISSUE TITLE
"Save As..."

### ISSUE THREAD

**Issue by rdeardorff** [HeidiSQL/HeidiSQL#1878]
**Is your feature request related to a problem? Please describe.**
Yes, insofar as it's an expected feature of any kind of text editor.

**Describe the solution you'd like**
"Save As..." for queries

**Describe alternatives you've considered**
I don't know what "Snippets" are or why they are the only option for "Save as"--it doesn't point me to the same folder as all my other saved queries.

**Comment by ansgarbecker** [comment]
There is a "Save" item in the "File" main menu, and in the context menu of each editor there is a "Save as" item:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/6fe21aa1-5fba-4b70-9797-3aa24eca8250)
