### ISSUE TITLE
In data view, an entry in the multi-column filter box, after switching tables, will not apply until edited

### ISSUE THREAD

**Issue by FirstMnM** [HeidiSQL/HeidiSQL#1879]
**Preconditions**
* HeidiSQL version: 12.6.0.6778
* Database type and version: MariaDB
* OS: Windows

**Describe the bug**
When data is open in a table, and a search is conducted using the multi-column filter, switching to a new table and trying to run the same filter will not apply via either <enter> in the box or via the "Apply Filter" button until the filter is edited in some way (such as deleting a letter).

**To Reproduce**
Open the data view in a table.
Select Filter
Enter a search term with results in the "Create multi column filter" box
Hit enter or click "Apply Filter" to yield results
Switch to another table in the same database
In the multi-column filter box, either hit enter or click "Apply Filter" to try to filter results once again
Observe it does not run/yield results
You can edit it in some small way, such as deleting & re-typing a letter, and it will work

**Screenshots or Crash reports**
<img width="127" alt="image" src="https://github.com/HeidiSQL/HeidiSQL/assets/128605932/9d97ea17-2d5b-4e79-bbce-badf1b6014cb">

**Expected Behavior**
Filtering a new table in the DB with an existing term should be able to be done via an already typed filter term by either hitting "Apply Filter" or hitting enter in the search box without editing the already typed search term.

**Comment by ansgarbecker** [comment]
That should work out of the box - I just tested and recorded it:

![apply-filter](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/299f86fc-e5fb-40f5-9012-5396bfa82c36)

Please retry and report back.

**Comment by FirstMnM** [comment]
Thanks for the quick response.  Here is my recording showing it in action - 


https://github.com/HeidiSQL/HeidiSQL/assets/128605932/d0250b3a-6ecb-49b3-a7d6-0f26e9029993

**Comment by ansgarbecker** [comment]
I see what you mean now. The difference to my screen is that you already have an active filter clause when you pressed "Apply filter". In my case the active filter was empty, and that's exactly how it is supposed to work. I recall this was discussed before after I temporarily changed the behaviour like you are asking for. I had to revert that as quite a few people were used to the old behaviour. I can probably add a dropdown arrow to that button with a single "Always overwrite" in it, which you can activate.

**Comment by ansgarbecker** [comment]
Next build has such a dropdown, and it stores the user preference permanently.

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/700dbb34-2939-48e3-94ec-e5551a58be57)

**Comment by FirstMnM** [comment]
Just wanted to say thank you!  Helps a ton with my workflow.
