### ISSUE TITLE
horizontal scrolling is reset when sorting columns or paging down to the next page limit (worked fine before v12.6)

### ISSUE THREAD

**Issue by lukemim** [HeidiSQL/HeidiSQL#1887]
**Preconditions**

* HeidiSQL version: 12.6.0.6765
* Database type and version: MySQL 8
* OS: Windows 10 Pro

**Describe the bug**

When viewing the data of a table with a lot of columns I sometimes want to see the values that are in the columns not in view, so I have to scroll horizontally to see them. When I click a column to be sorted or when I page down to the next thousand records the horizontal scroll is reset and it shows me the first couple of columns again. Before version 12.6. this worked fine and the horizontal scroll wasn't reset when sorting or paging.

However curiously this doesn't happen if the cell cursor is left on the first column and only the mouse is used to scroll the horizontal scrollbar to the right column.

**To Reproduce**

1. Open the data view on a table with a lot of columns, move the data edit cell cursor to the rightmost colum, sort by the last column by clicking on its name
2. view is reset to the first column instead of remaining on the last column (the cell cursor remains on the last column)

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Issue is only half fixed now. Header clicks for sorting now do not move the focus to the leftmost column. But paging to the next bunch of rows still does so.

**Comment by datadiode** [comment]
I suspect that this is a regression from [https://github.com/HeidiSQL/HeidiSQL/commit/2d648c6](https://github.com/HeidiSQL/HeidiSQL/commit/2d648c6).
The proper fix isn't obvious to me. I think SelectNode should try to avoid changing VT.FocusedColumn.

**Comment by ansgarbecker** [comment]
Should now be the same as in earlier versions, with the next build.
