### ISSUE TITLE
Save selected encoding in export

### ISSUE THREAD

**Issue by Mondane** [HeidiSQL/HeidiSQL#189]
## Steps to reproduce this issue

1. In de query tab, perform a select query.
2. Right click on the results and choose export.
3. Select a different encoding, e.g. UTF-8
4. Change some other settings too.
5. Export, close the export window and open it again.

## Current behavior

All changes options, except the encoding will be saved and show upon opening the export window again.

## Expected behavior

The chosen encoding must also be saved.

## Possible solution

As an extra, set the encoding to UTF-8 by default throughout the application..

## Environment

* **HeidiSQL version:** 9.5.0.5196
* **Operating system:** Ubuntu 16.04

**Comment by ansgarbecker** [comment]
The encoding is stored and restored for all export formats, but not for "Excel CSV". Excel always expects ANSI, and it would break your Excel file if Heidi would use the restored UTF-8 for example.
