### ISSUE TITLE
Make safe/valid CSV export format the default for CSV (x_x)

### ISSUE THREAD

**Issue by tanzanite777** [HeidiSQL/HeidiSQL#1892]
**Is your feature request related to a problem? Please describe.**
Heidi, by default, exports broken CSV files. "Broken" here meaning that other people cannot reliably open them due to Heidi CSV export enforcing incorrect assumptions about windows list separator settings into the file.

**Describe the solution you'd like**
Output encoding for CSV files should be forced to UTF-16LE (or UTF-16BE as an highly unusual alternative) with required BOM and tab as separator. Leaving only "Delimited text" as configurable (this is currently the only way to produce, pseudo-reliably, correct CSV files assuming the user knows how to do it).

It is a quite painful discovery when people realize that their CSV exports, they saw as fine, are actually junk - they needed to use "Delimited text" with special non-default settings to get a safe/valid CSV file.

**Describe alternatives you've considered**
There are none. "Delimited text" fiddle-heavy workaround is not a sane, IT-support, option.

Note: must be utf-18, must use BOM and must use tab as separator. For example, cannot use 'sep' keyword as that forces ASCII / unspecified code page (ie. utf-8 not allowed) - which, essentially, no-one can ever use. Similarly, must use tab as that is the only one recognized reliably regardless of list separator settings. BOM - there is no valid reasons to omit it ("Delimited text" probably needs an option "... Force BOM" - as currently none is written for UTF-16BE and there can be, external format requirement, cases where one is required or, conversely, not allowed).

**Additional context**
Since many do not work in environments where list separator settings differ then one can alternatively simulate the situation by fiddling with the list separator settings while wrangling Heidi "CSV" export files (the config path might differ depending on windows version - adapt as needed):

setings -> time & language -> date, time & regional formatting -> additional date, time & regional settings
[or alternatively: control panel -> clock and region] -> region -> additional settings -> list separator.

**Comment by ansgarbecker** [comment]
The output is named "Delimited text", not "CSV" - that's intentionally. The user can specifiy different control characters, which was highly demanded by many users years ago. Forcing usage of system regional settings for exporting text files is not what I see as user-friendly.

**Comment by tanzanite777** [comment]
> The output is named "Delimited text", not "CSV" - that's intentionally. The user can specifiy different control characters, which was highly demanded by many users years ago. Forcing usage of system regional settings for exporting text files is not what I see as user-friendly.

I am not talking about "Delimited text" - therefore how is any of this relevant? Did you read OP? Please do so before replying.

**Comment by ansgarbecker** [comment]
Well you were talking about "CSV" in general, not "Excel CSV", so I thought you meant the delimited text option.

In case of Excel CSV - where and how exactly did you encounter an issue here? This is posted as a feature request, and I cannot see any problem when opening such files in (modern versions of) Excel. If you encounter a problem, then please post a valid reproduction recipe, and Excel version, plus probably screenshots.

**Comment by tanzanite777** [comment]
Considered reporting this as a bug - but decided against it on technicality. CSV is broken by design except under specific settings - therefore blindly following and using the broken variant is not technically a bug. In any sane world - it is a bug. Question is whether/how one is willing to fix it.

I assume you are not familiar with CSV format - one random link talking about the relevant problem and the workarounds that might be helpful: https://stackoverflow.com/questions/20395699/sep-statement-breaks-utf8-bom-in-csv-file-which-is-generated-by-xsl#23513342

To see it happen yourself then do (consult OP for details):
* set list delimiter in windows to ','.
* export "Excel CSV".
* open it (ex: latest Excel in MS 365 suite) - works fine.
* set list delimiter in windows to ';'
* open the previously made export again - you get garbage. Excel won't understand the file.

PS. a word of warning, due to the "broken by design" caveat - "works in latest Excel" is not a terribly useful metric (ie. the implicit "latest is the most conforming / bugfree" is misleading).

**Comment by ansgarbecker** [comment]
Excel is maybe broken by design, which is just my personal 2 cents.

I'm not going to "fix" things which were forced up due to modified regional settings. HeidiSQL always offers the way to use the "Delimited text" option to circumvent most limitations of the "Excel CSV" option.

**Comment by tanzanite777** [comment]
Odd reasoning for the decision, to put it extremely mildly. "Don't care to fix it" / "Don't have time to fix it" would be more understandable reasons - current reason, as given, sounds like the issue was not even understood (?).

Nothing was "forced" (what !?) - this is a real word issue (hence this issue posting). Simplified and succinct summary: **HeidiSQL "Excel CSV" export IS BROKEN!** Why, given that you CAN fix it, you choose to keep it broken?

Due to the, bizarre, mentioning of "forced" i remind that "," **IS NOT THE DEFAULT** list delimiter for **MANY** regions/countries! This issue **IS NOT** due to someone fiddling with the settings! Fiddling instructions were given to simplify reproduction (since many do not work in multicultural settings and would not know how to affect the relevant regional defaults).

Current user experience (how it was kicked up the IT-support chain) - paraphrased, but completely accurate:
* Client: got a bunch of HeidiSQL "Excel CSV" export for another worker and cannot get any of them to open - source claims that it works fine for him.
* IT resolution: aah, sorry, turns out that HeidiSQL "Excel CSV" output format does not produce a valid Excel CSV for everyone - the original exporter should have used "delimited text" with this-n-that specific settings to get a working Excel CSV file (well, way too late for that to be possible, so recommended the original exporter convert the problematic CSV's on his PC into xslt and send the resulting files).
* Client: so, "Excel CSV" option is unuseable for Excel CSV?
* IT: Yes.
* Client: This it nuts!
* IT: yeah, it is, i'll contact Heidi - will see what comes of it.

... sure you are strictly against fixing it?

Would highly prefer that "Excel CSV" export would actually produce files that work for everyone using Excel - especially as it can be done (if heidi would follow the established, and reiterated in OP, CSV format recommendations) and does not limit existing functionality (still can do any specific variant of CSV via "Delimited text" option).

**Comment by ansgarbecker** [comment]
To be honest, the rude tone here is one of the reasons why I was closing it. Please respect that HeidiSQL is free, OpenSource, maintained in my rare free time. I don't earn much money with it. If you have hard requirements, you should probably use some commercial software.

**Comment by tanzanite777** [comment]
Apologies if i felt rude - i can only ensure that it was not intentional at any point. English is not my native language and directness is deep in my nature (IT tends to draw people like me). There is nothing more behind that - think nothing of it.

I hope that my willingness to write long issue OP and replies signal somewhat that i surely am not here to bash and am just trying to help (just unsure if my issue was understood).

Unfortunately, i do see my directness been seen as rude sometimes - seems it bites gain (actually, funnily, speaking of multicultural - harsh directness it is often mentioned as a stereotypical national trait for us - we really do not like beating around the bush or however the expression was).
