### ISSUE TITLE
Exporting stored function has double quotes in name which is invalid for MySQL

### ISSUE THREAD

**Issue by arikanorh** [HeidiSQL/HeidiSQL#1894]
**Preconditions**

* HeidiSQL version: 12.6.0.6765
* Database type and version: MySQL 5.7.16
* OS: Windows 11

**Describe the bug**

When I export a stored function the drop sql is correct but the create sql is incorrect. It has double quotes in the name and mysl doesnt like it

```
DROP PROCEDURE IF EXISTS `exportSummaryData`;
DELIMITER //
CREATE PROCEDURE "exportSummaryData"(
```
![image](https://github.com/HeidiSQL/HeidiSQL/assets/17791032/c5abb9fd-4c31-4b33-8590-4cf28f7d6f9c)

**To Reproduce**

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Strange, and not reproducible here, on MySQL 5.7.41:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/cd2ddbe1-2879-4027-b83a-58ec6434151e)

Do you have a chance to test the export with a newer MySQL version as yours?

**Comment by arikanorh** [comment]
I tried on 5.7.35 and it didnt happen. Might be sql version related

**Comment by ansgarbecker** [comment]
I also tested on MySQL 5.7.9 - an older version of the one you were initially testing. But I get the correct backticks there as well:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/9fc0036f-ee69-4547-8225-cab73870e194)

Please shout if you once find out how the double quotes are reproducible.
