### ISSUE TITLE
Weird Vertical Bar in SQL Editor (Multiple Query Bug)

### ISSUE THREAD

**Issue by WRSP** [HeidiSQL/HeidiSQL#1897]
**Preconditions**

* HeidiSQL version: 12.6.0.6785
* Database type and version: MySQL Community Server v5.6.43
* OS: Windows 11 Pro

**Describe the bug**

After you've executed 3 or more queries at the same time, the weird vertical bar will appear in the SQL Editor, it will always appear like that and can't be removed until you click the third tab of the execution result.

**To Reproduce**

1. Execute 3 or more queries at the same time.
2. The weird vertical bar will appear in the SQL Editor.

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/43071880/49852839-dd13-4dcd-8cf2-7bcdb4c167d4)

**Comment by ansgarbecker** [comment]
I'm not getting that here, also on Windows 11. Is that reproducible for you even after restarting Heidi, and/or the computer?
Looks a bit like a graphics driver issue.

**Comment by jemmel** [comment]
I'm experiencing a similar issue when executing queries.

When running the query, a rectangle appears:

![display_bug_1](https://github.com/HeidiSQL/HeidiSQL/assets/153074/46154b67-7d45-4149-ad59-b46da452dcf9)


After executing long queries:

![display_bug_2](https://github.com/HeidiSQL/HeidiSQL/assets/153074/06ace0f0-1470-4d5b-97f0-1037212cf31f)

Version: 12.6.0.6765, Windows 11 Pro, Nvidia 3080ti (driver version 551.23).

**Comment by ansgarbecker** [comment]
For me this issue looks fixed with my just pushed modification.
@jemmel or @WRSP please test with build 6851.

**Comment by digitalmonk2024** [comment]
A <a href="https://digitalmonkseo.ca/vancouver-seo/">technical SEO agency in Vancouver</a> can help address a "frozen window" issue when running queries by implementing several key strategies:

1. **Server Optimization**: Enhancing server response times to prevent delays and timeouts during queries.

2. **Database Optimization**: Streamlining database queries to ensure they execute efficiently, reducing load times and minimizing bottlenecks.

3. **Caching Solutions**: Implementing caching mechanisms to store frequently accessed data, which speeds up response times and reduces server load.

4. **Monitoring Tools**: Utilizing performance monitoring tools to identify and troubleshoot query issues in real-time, allowing for immediate adjustments.

5. **Code Review**: Conducting thorough reviews of the website's code to identify any inefficient scripts or plugins that may be causing slowdowns.

By addressing these technical aspects, a Vancouver SEO agency can help ensure smooth query performance, enhancing overall user experience and site functionality.
