### ISSUE TITLE
Events Not showing in Tree

### ISSUE THREAD

**Issue by HenryLogan1465** [HeidiSQL/HeidiSQL#1898]
**Preconditions**

* HeidiSQL version: 12..3.0.6.6589 (32 bit)
* Database type and version: MariaDB 11.1 (x64)
* OS: MS windows 11

**Describe the bug**

**To Reproduce**

**Screenshots or Crash reports**

**Comment by HenryLogan1465** [comment]
I messed up, the problem report I submitted does not show details.
Basiically, the event list in the database tree does not show events that can be seen using the SQL command Select * frem mysql,event;

**Comment by ansgarbecker** [comment]
By chance, someone posted the same issue in the forum: https://www.heidisql.com/forum.php?t=41682
I already tried to fix it in 79ce5edcf3124202ef6ff882c9fc2e2deab338b9, so I would like to ask you to verify the newest build now works or not.
Just update through _Help > Check for updates > Download build xyz_

**Comment by HenryLogan1465** [comment]
I was able to fix the error. After showing the event in the MySQL.event query, I modified the database name to match case with my "tree" name. A refresh returned the event in the tree.

**Comment by ansgarbecker** [comment]
Would be good if you revert to the "wrong" case and check if the latest HeidiSQL build works correctly now. Otherwise I cannot close this ticket and there may be some issue left.
