### ISSUE TITLE
Columns indicator on "Data" tab displaying incorrect column count

### ISSUE THREAD

**Issue by r3ganbr0wn** [HeidiSQL/HeidiSQL#1899]
**Preconditions**

* HeidiSQL version: 12.6.0.6786
* Database type and version: MySQL 8.0
* OS: Windows 10

**Describe the bug**

When viewing table Data, the Columns indicator is showing an incorrect number of selected columns.  See attached screenshot; I have selected to show all 3 columns in the table, but the indicator text says only 2/3 columns have been selected or shown.

**To Reproduce**

1. Click the Data tab to see results data for any table.
2. Look at the Columns indicator text

**Screenshots or Crash reports**

![screen-capture-1](https://github.com/HeidiSQL/HeidiSQL/assets/31259692/a40700fc-51ae-4507-8d30-bc1ca5f588f0)

**Comment by ansgarbecker** [comment]
Fixed in the next build.
