### ISSUE TITLE
Untranslatable words

### ISSUE THREAD

**Issue by wwycheuk** [HeidiSQL/HeidiSQL#19]
## Expected behavior

Some words/strings are still in English after completing translation. Also some minor problems with UI.

## Current behavior

All words/strings should be translated.

## Failure information (for bugs)

![image](https://user-images.githubusercontent.com/9688953/33248645-faf0ea48-d360-11e7-89b6-de6c662d4674.png)
![image](https://user-images.githubusercontent.com/9688953/33249162-f67ffd3e-d363-11e7-89c9-3d530d6d5f87.png)
![image](https://user-images.githubusercontent.com/9688953/33249439-76a4294e-d365-11e7-978d-f31f3edc23ac.png)
![image](https://user-images.githubusercontent.com/9688953/33250947-ad372750-d36e-11e7-9845-a0e337a3ee81.png)
![image](https://user-images.githubusercontent.com/9688953/33251154-2eb3c1de-d370-11e7-8871-f2ff19867374.png)

BTW, there are many words begin with "SEL" near the end of the translation file, what are they for?

**Comment by wwycheuk** [comment]
Thanks!

**Comment by ansgarbecker** [comment]
Sel Page Top, Sel Page Top and some others are for SynEdit keystrokes. In HeidiSQL displayed in Preferences > Shortcuts > SQL editing

**Comment by ansgarbecker** [comment]
Most of these should be fixed now.
The "Custom" color in the drop down is not translatable I suppose.
Size of the dialogs could be enhanced I guess.
