### ISSUE TITLE
Can't change session background color on Ubuntu

### ISSUE THREAD

**Issue by Mondane** [HeidiSQL/HeidiSQL#190]
## Steps to reproduce this issue

1. Make a server connection.
2. Right click the connection in the sidebar.
3. Go to 'Tree style options'.
4. Click on 'Select session background color'.

## Current behavior

After clicking on 'Select session background color', nothing happens.

## Expected behavior

A color picker or something should be shown allowing me to change the session background color.

## Environment

* **HeidiSQL version:** 9.5.0.5196
* **Operating system:** Ubuntu 16.04
* **Wine version:** 1.6.2

**Comment by ansgarbecker** [comment]
Sorry for the long delay. Is that issue still there? The background color setting has moved to the session manager's advanced tab, which works different, and I highly guess that fixed it, or?
