### ISSUE TITLE
Wrong Hungarian transaltions

### ISSUE THREAD

**Issue by Meister1977** [HeidiSQL/HeidiSQL#1901]
**Preconditions**

* HeidiSQL version: 12.6.0.6786 (64 Bit)
* Database type and version: Irrelevant
* OS: Windows 11

**Describe the bug**

If you check the running processes, the State (I don't see the English version, so maybe Status) is translated to "Állam" which is incorrect. "Állam" means like a state of the United States. The proper Hungarian word would be "Státusz".

**To Reproduce**

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/10465690/e198c5cf-6724-4cd6-9cad-92a83e32e328)

**Comment by ansgarbecker** [comment]
Here's the english original - it says "State", not "Status". So we have both, "Status" in the second level tabs under "Host", and "State" in the columns of the process list.

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/b414c25a-f182-4970-be91-7c8bb8c20873)

What is then the right word for "State" here? It's meaning is similar to "status", but slightly different. Deepl also says "Állam", but if there is no such a word in Hungarian we should probably use "Státusz".

**Comment by Meister1977** [comment]
Státusz is ok for me. I know status and state slightly different in English, but both can be Státusz in Hungarian.

**Comment by Meister1977** [comment]
Anyway, where is the Hungarian localization? If I find more wrong translation, I may fix that, and create a pull request. Easier than open an issue. 😃

**Comment by ansgarbecker** [comment]
Fixed in the latest builds, using _Állapot_ from the last translator razielanarki.
