### ISSUE TITLE
It would be desirable to have an improved capability for viewing and editing multiple lines of text

### ISSUE THREAD

**Issue by prodcd** [HeidiSQL/HeidiSQL#1903]
**Is your feature request related to a problem? Please describe.**

It is inconvenient to use the current pop-up window when viewing and editing multi line text boxes, especially when switching between multiple lines of data.
And now I am using version 12.6.0.6786, which often causes software crashes when using pop-up windows to edit multiple lines of text.

**Describe the solution you'd like**

Add a dedicated window below the grid and use multiple formats to display multiple lines of text. For example, JSON, hexadecimal, binary, image, HTML, and even support for audio formats can be considered.

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment]
Please note the popup text editor already has highlighters for numerous languages, like JSON, XML and so on.

For the other part of your request, I think the current modal window has more advantages than an inplace area with the editor. For example the dialog does not waste space if it's inactive, and it focuses the text memo as soon as it opens.
