### ISSUE TITLE
Tab Icons: Non-selected tab icons appear greyed-out / all the same colour - request for them to always remain in colour.

### ISSUE THREAD

**Issue by peterfox1** [HeidiSQL/HeidiSQL#1906]
**Is your feature request related to a problem? Please describe.**

I have finally just updated from v10 but had been a little diorentated at first - even though everything is in the same place I wasn't immediately seeing where I wanted to go, realised it's becuase all the tab icons are the same colour and I must have relied on that more than I expected. It would be helpful for quick identification for the tab icons to remain in colour to help differencaite them (also applies to the tab bar in settings etc)

![image](https://github.com/HeidiSQL/HeidiSQL/assets/2419942/71cc1d3e-f5e1-4d38-838d-c7467cc67552)

**Describe the solution you'd like**
Keep the icons in full colour even when the tab is not selected - increases the distiction between the options / faster to skim & locate tabs by their icon.

**Describe alternatives you've considered**
Tempted to use an older version of heidiSql for now :D
Chaning the theme seemed to work initially, but as soon as you choose a tab it greys out the others 😢

**Additional context**

**Comment by ansgarbecker** [comment]
The inactive tabs are intentionally grayscaled, to make it easier to find the active tab. See https://www.heidisql.com/forum.php?t=41323

**Comment by peterfox1** [comment]
Thank you for the clarification, it seemed intentional and I can appreciate the benefit for the query tabs - wonder if it would be possible for it to only apply to those?. The current tab is also shown by not having a line below it so I suppose it depends what you're tuned into looking out for but I understand the issue. I was mostly surprised at myself how much I used the icons & colour for locating the tabs.

Noticed it was recent so I've started using 12.5 / more than happy to do that if I'm an outlier

**Comment by ansgarbecker** [comment]
The initial idea was to enhance the _query_ tabs. My idea was then "why not do the same for all tabs", to have a unique look and feel. But I guess you have a point here, and I can confirm the grayscale icons are looking quite all the same now.
I think I will create a new preference option on the "Files and tabs" panel: "Grayscale inactive tabs", with 3 radio buttons:
* use color icons on all tabs
* use grayscale icons on inactive query tabs
* use grayscale icons on every inactive tab

**Comment by ansgarbecker** [comment]
That new option is available in the next builds. After updating you will see this in Tools > Preferences > Files and tabs:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/14f726a7-f51e-4b45-8382-6a123144208e)

**Comment by peterfox1** [comment]
Ooh very nice @ansgarbecker ! 🤩
