### ISSUE TITLE
Invalid default value CURRENT_TIMESTAMP on HeidiSQL 12.6.0.6799 with mySQL 8.0.36

### ISSUE THREAD

**Issue by jprinzler** [HeidiSQL/HeidiSQL#1910]
**Preconditions**
* HeidiSQL version: HeidiSQL 12.6.0.6799
* Database type and version: mySQL 8.0.36-0ubuntu0.20.04.1 (bug)
mySQL 10.4.10-MariaDB (success)
* OS: Ubuntu or Windows

**Describe the bug**
Hello Ansgar.
There still seems to be a problem with CREATE TABLE and the default values like CURRENT_TIMESTAMP. These are still interpreted as a string. It seems to depend on the database version. It works under version 5.x, but not under 8.0? Sorry, I no longer have the 5.x DB version on Linux.

**To Reproduce**
Create Table:
```
CREATE TABLE fuckingdates ( 
  col1 DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  col2 TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
) COLLATE='utf8mb4_unicode_ci' ENGINE=InnoDB;
```

... then show create code on HeidiSQL:

```
CREATE TABLE `fuckingdates` (
   `col1` DATETIME NULL DEFAULT 'CURRENT_TIMESTAMP' ON UPDATE CURRENT_TIMESTAMP,
   `col2` TIMESTAMP NULL DEFAULT 'CURRENT_TIMESTAMP' ON UPDATE CURRENT_TIMESTAMP
)
COLLATE='utf8mb4_unicode_ci' ENGINE=InnoDB;
```

Unfortunately, this is wrong and doesn't work.

**Screenshots or Crash reports**
![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/118431619/6e0bdcfc-9323-4e2f-b4a2-48ee667b5e3f)

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/118431619/d3731fb3-4e46-40e0-b218-079bf91d8e09)

Can you help?

**Comment by ansgarbecker** [comment]
Confirmed, for MySQL 8.0.14 and newer versions.
Should be fixed in the next build available in one hour. Please update and retest.

**Comment by jprinzler** [comment]
Thank you. It works.
