### ISSUE TITLE
Label too long in french version

### ISSUE THREAD

**Issue by Delphichem** [HeidiSQL/HeidiSQL#1915]
HeidiSQL 12.6.0.6804 (French)
Windows 11

In preference dialog on the last tab
The label in french is too long and the combobox appears above it

![image](https://github.com/HeidiSQL/HeidiSQL/assets/12384176/75a28150-df0e-4c9c-b680-4987520f0a0d)

**Comment by Delphichem** [comment]
Fixed by the new translation smaller then older

**Comment by ansgarbecker** [comment]
Did you fix that on Transifex? Thank you in that case :)

**Comment by Delphichem** [comment]
It is fixed in Transifex by FeverBeaver, who provide a better and smaller translations than mine, thanks to him.
