### ISSUE TITLE
scroll bar style issue

### ISSUE THREAD

**Issue by aibdpgj** [HeidiSQL/HeidiSQL#1916]
![企业微信截图_20240227102600](https://github.com/HeidiSQL/HeidiSQL/assets/20835643/37e2cbbf-f126-40c2-aef5-8c56a0f64962)
Scrollbar style exception when using theme "material"

**Comment by ansgarbecker** [comment]
Right place to report that would be the SynEdit project. I recommend to contact the reporter of this one: https://github.com/SynEdit/SynEdit/issues/169 Probably he is able to find back its pull request.
