### ISSUE TITLE
Exception when execute query on remote connection

### ISSUE THREAD

**Issue by EliuTimana** [HeidiSQL/HeidiSQL#192]
## Steps to reproduce this issue

1. Execute a select query on a remote or even a local MySql(MariaDB) connection
2. HeidiSql gets freeze
3. Then an error dialog appears and lets me three options: continue, restart and close the application.

## Current behavior

Sometimes selecting "continue application" solves the problem and I come back to work, but sometimes the continue button is disabled I have to restart the application.

## Possible solution
I think the problem is that I select large sets of data.

## Environment

* **HeidiSQL version:** 9.5.0.5261
  
* **Database system and version:** mysqld 10.2.6-MariaDB
  
* **Operating system:** Windows 10 Home Single Language version 1709 build 16299.248
  

### Bugreport.txt

````
date/time          : 2018-03-13, 15:18:51, 653ms
computer name      : ELIU-PC
user name          : Eliu
registered owner   : Windows User
operating system   : Windows 10 x64 build 16299
system language    : English
system up time     : 20 days 4 hours
program up time    : 31 minutes 34 seconds
processors         : 8x Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
physical memory    : 9527/16331 MB (free/total)
free disk space    : (C:) 95.58 GB
display mode       : 1366x768, 32 bit
process id         : $3130
allocated memory   : 104.81 MB
largest free block : 131029.99 GB
executable         : heidisql.exe
exec. date/time    : 2018-03-05 19:07
version            : 9.5.0.5261
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $ff7e540c, $95bd0b6e, $95bd0b6e
exception number   : 7
exception class    : Exception
exception message  : Runtime error 216 at 000000000040F8BA.

thread $4144:
0040f8b5 heidisql.exe System         @DoneExcept
005d6c49 heidisql.exe System.Classes ThreadProc
00410468 heidisql.exe System         ThreadWrapper
7ff9c2a2 KERNEL32.DLL                BaseThreadInitThunk
7ff9c33d ntdll.dll                   RtlUserThreadStart

main thread ($1a5c):
00000000 heidisql.exe madStackTrace +0 StackAddrToStr
>> stack will be calculated soon
````

**Comment by G3ph4z** [comment]
I had issue few years ago with other software. 
Please try to run `Kaspersky TDSSKiller`
You can download from here:
https://usa.kaspersky.com/downloads/tdsskiller

I think ur PC has infected by trojan.

**Comment by ansgarbecker** [comment]
That dialog with continue, restart and close buttons is the exception handler, packed into heidisql.exe - nothing infectuous.

How's the query looking you are trying to execute? I highly guess it has some error in it.
