### ISSUE TITLE
Autocomplete on aliases doesn't trigger if the table name contains the word "join"

### ISSUE THREAD

**Issue by marcel-aguiar-frequence** [HeidiSQL/HeidiSQL#1923]
**Preconditions**

* HeidiSQL version: 12.6.0.6765
* Database type and version: MySQL 5.7.12 and Postgres 12.0
* OS: Windows 11 Pro 22H2

**Describe the bug**

There are a handful of tables in our Mysql db where when a table alias is used, autocomplete doesn't work. I noticed this seems to only happen with tables that have the word "join" them, such as "shelf_join_books" or "users_join_admins". However autocomplete does work if I reference the table name directly. I tested this on different SQL types, different machines, and different HeidiSQL versions, and the issue exists across all of them.

Example:
```
SELECT uja. <-- after typing ".", autocomplete doesnt trigger.
FROM users_join_admins uja;
```

```
SELECT users_join_admins . <-- This DOES work
FROM users_join_admins uja;
```

**To Reproduce**

1. Find a table with "join" in the name, or create one.
2. In a query tab, reference the above table in a query and give it an alias
3. Reference the alias and type dot (.)
4. Autocomplete won't appear

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Issue introduced in 28634e67b3bd40e12893946717d4ce2d0c1bac3e from March 2008 :)

**Comment by ansgarbecker** [comment]
Fix 16 years later. Please update to the next build.

**Comment by marcel-aguiar-frequence** [comment]
Thank you! Is this a record?

**Comment by ansgarbecker** [comment]
No I don't think it's a record, but definitely worth a joke :) HeidiSQL's oldest code passages are even older than 20 years, and I believe there are still issues from that time.
