### ISSUE TITLE
HeidiSQL crashes/hangs when running SHOW PROCESSLIST during query execution.

### ISSUE THREAD

**Issue by mbomb007** [HeidiSQL/HeidiSQL#1926]
**Preconditions**

* HeidiSQL version: 12.6.0.6765 (64 bit) - *As a side note, you really should make the version string copyable in the About dialog. You can't currently select it with the mouse to copy it.*
* Database type and version: 10.11.6-MariaDB-1:10.11.6+maria~ubu2204-log
* OS: Ubuntu 22.04 in Docker on WSL for Windows 11

**Describe the bug**

When I run a SELECT query, and run `SHOW PROCESSLIST;` or `SHOW EXPLAIN FOR <id>;` while the query is still running, HeidiSQL closes/crashes or hangs.

**To Reproduce**

I don't see any error message to include. Is there a way to see why it hangs or closes (e.g. a log/dump file)

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
The about dialog already has a context menu on the text lables, with a "Copy" item in it:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/0d25d0d6-291f-4c48-abad-34265dcbdb62)

Regarding the blocked query: you cannot execute queries simultaneously _in one session_. The server would return an error saying "commands out of sync" or something similar.
You need to open two sessions, one for the long running `SELECT` query, and one for the `SHOW PROCESSLIST` query.
