### ISSUE TITLE
field comment can be prompted in the query box

### ISSUE THREAD

**Issue by linauror** [HeidiSQL/HeidiSQL#1927]
**Is your feature request related to a problem? Please describe.**
When writing SQL, I always forget the field comment and need to switch frequently  between the **table tabs** to check them.

**Describe the solution you'd like**
Eample: `gender` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '1: male, 2: female',
When the mouse is placed over the field，display the image below.
![20240325094359](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/09edb915-915c-4815-a8f2-976713f136c6)

Or autocomeplete box show the comment 
![20240325095447](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/4413fbf2-e697-4e63-be7e-8987157e47ec)

**Describe alternatives you've considered**
switch tab to view the field comment

**Additional context**
Writing SQL statements has become faster

**Comment by ansgarbecker** [comment]
SynEdit has a wonderful formatting feature in that completion proposal, so this was easy. Next build shows column comments in the dimmed right column of the list:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/fc3341b1-06eb-46ff-9e35-2c75bee2c9a2)

**Comment by linauror** [comment]
wonderful!!!
