### ISSUE TITLE
having a lot of tabs take a serious toll on performance

### ISSUE THREAD

**Issue by raresn** [HeidiSQL/HeidiSQL#1928]
**Preconditions**
* HeidiSQL version: 12.3.0.6589
* Database type and version: Doesn't matter
* OS: Windows 10

**Describe the bug**
My colleague uses Heidi in an .. unique way and has a lot of tabs opened.
This takes a serious toll on peformance, and we were wondering if there is anything that can be done.
Right now, he can barely type inside a new tab :)

**To Reproduce**
open a lot of tabs with querries inside.

**Screenshots or Crash reports**
![image](https://github.com/HeidiSQL/HeidiSQL/assets/1768694/f79bf7db-953b-47fe-bf2f-4bc158a0ed6b)

**Comment by ansgarbecker** [comment]
12.3 is outdated. Please try with the latest build.

I already fixed a slowness with many tabs in 2b29b51aafeef8a48d70a60b6fdbaf3542dd2a1d, reported in a [forum thread](https://www.heidisql.com/forum.php?t=37961). But you're talking about an absurd high number of tabs (> 300). I will likely close this without a code change.

**Comment by raresn** [comment]
Thx for the fast response. Will update the app now.

**Comment by raresn** [comment]
No luck. I guess we need to find a different way to use the app if no plans to improve in this direction are in place.

**Comment by ansgarbecker** [comment]
As already said, having 300 tabs open is absurd. Will close the issue.
