### ISSUE TITLE
JSONL export options

### ISSUE THREAD

**Issue by prsyahmi** [HeidiSQL/HeidiSQL#1930]
**Is your feature request related to a problem? Please describe.**
Hi, I'd like to export the query result directly to jsonl format (json lines). For now, I'm always fire up converter to do so adding some frictions to workflow.

**Describe the solution you'd like**
I'd like to have jsonl export options as one of the "output format" on the screenshot below.

The 3 requirements of jsonl is:
1. UTF8 encoding, same as json
2. Each line is a valid json value (in this case, it should be always a json object)
3. Line separator is `\n`, for consumer any whitespace is ignored including `\r`. Last entry may or may not contain newline. (I think giving user choices LF / CRLF is ok)

https://jsonlines.org/

**Describe alternatives you've considered**
NA

**Additional context**
![image](https://github.com/HeidiSQL/HeidiSQL/assets/1040494/9d0c5197-ed27-4868-9b15-b7a21784fc23)

**Comment by ansgarbecker** [comment]
Implemented in the next build, along with some other UI related changes:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/38460d62-417e-4293-bcbe-09f5cde64e4e)

Sample output:
```jsonl
{"pdate": "2023-09-23", "pdate2": "1", "pdate3": "1"}
{"pdate": "2023-09-23", "pdate2": "1", "pdate3": "2"}

```

Note the output ends with a linefeed `\n/chr10`, just like the line ending.

**Comment by ansgarbecker** [comment]
Ah, please test that (Help > Check for updates), and report back if everything's fine.

**Comment by prsyahmi** [comment]
Thank you @ansgarbecker! The new jsonl export works beautifully.
