### ISSUE TITLE
An error in field prompt is found when the field in the query box contain symbols.

### ISSUE THREAD

**Issue by linauror** [HeidiSQL/HeidiSQL#1934]
**Preconditions**

* HeidiSQL version: 12.6.0.6819
* Database type and version: MySQL 5.6.21
* OS: Window 10

**Describe the bug**

 show create table **user** like this

    CREATE TABLE user (
	    uid INT(10) NOT NULL AUTO_INCREMENT,
	    gender INT(10) NOT NULL DEFAULT '0' COMMENT '1, male 2, female',
	    PRIMARY KEY (uid) USING BTREE
    )
    COLLATE='utf8_general_ci'
    ENGINE=InnoDB

SQL like this:

    SQL1: SELECT * FROM user WHERE gender = 1;
    SQL2: SELECT * FROM user WHERE `gender` = 1;

When i selected **gender** field  AND Run command **Show SQL completion proposal**, the SQL1 can be displayed correctly , but SQL2 cann't.

**To Reproduce**

1, wirte sql with symbols **`**
2, selected field
3, Run command **Show SQL completion proposal**

**Screenshots or Crash reports**

![20240407173759](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/9748a1eb-205a-404b-ac1c-1ac0d8ef82bf)
![20240407173820](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/a325ef82-61f0-4809-934d-4f1cff26e828)

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.
