### ISSUE TITLE
Warn to overwrite file on Export grid rows

### ISSUE THREAD

**Issue by endo64** [HeidiSQL/HeidiSQL#1937]
**Is your feature request related to a problem? Please describe.**
A few times I accidentally overwrite an old file while exporting grid rows to a file. I thought I selected Clipboard, but file option was selected as Output target, and the old file overwritten without a warning.

**Describe the solution you'd like**
Check if file already exists and show a warning popup with overwrite option:

```
File already exists, overwrite?

+----+  +----+
|Yes |  | No |
+----+  +----+
```

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by ansgarbecker** [comment]
I get a confirmation dialog when I click ok and the file exists:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/40e2d62a-a186-4ea0-b8e1-30646a08fc35)

**Comment by ansgarbecker** [comment]
Please shout if there is still an issue with it.

**Comment by endo64** [comment]
I confirm it works; I got confirmation popup. Probably my version was older, I updated to the daily build.
