### ISSUE TITLE
comments are not recognized as such when there is no space after '--' e.g. '--bug' is not recognized as a comment

### ISSUE THREAD

**Issue by Whoeza** [HeidiSQL/HeidiSQL#1938]
**Preconditions**

* HeidiSQL version: 11.3.0.6295
* Database type and version: MariaDB 10.3.27
* OS: Win10

**Describe the bug**

comments are not recognized as such when there is no space after '--' e.g. '--bug' is not recognized as a comment

**To Reproduce**

1. Open the query tab
2. Type '--bug' on line 1 and run it
3. See error message at line 1

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
A double-dash comment _requires_ a space after the double dash. Without the space, it's not a comment. See the [MariaDB documentation](https://mariadb.com/kb/en/comment-syntax/).
