### ISSUE TITLE
Crash on 'explain anayzer on mariadb'

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#194]
## Steps to reproduce this issue

1. Step 1; Connect DB, go to processes
2. Step 2; Select a running query
3. Step 3; Hit 'explain anayzer on mariadb'
4. Then I get... a crash

## Current behavior

![image](https://user-images.githubusercontent.com/3911428/37462569-d74dad20-2828-11e8-923e-9fa40da173a8.png)

## Expected behavior

I popup to the web I guess?

## Possible solution

Add a warning to "do not click"? :)

## Environment

* **HeidiSQL version:** 
last available Nightly
* **Database system and version:** 
mariadb 10.1 on debian 8
* **Operating system:** 
windows 10

**Comment by ansgarbecker** [comment]
Not all kinds of queries can be EXPLAINE'd, and that's where Heidi is currently missing some exception catching.
