### ISSUE TITLE
No Passphrase Popup, when using ssh tunnel.

### ISSUE THREAD

**Issue by Bastika07** [HeidiSQL/HeidiSQL#1940]
**Preconditions**

* HeidiSQL version: 12.6.0.6765
* Database type and version: MariaDB 10.5.23
* OS: Win11 23H2

**Describe the bug**

If i am using a ssh key with a passphrase, and usind ssh.exe for the tunnel, i just get can´t connect. With plink.exe i get a popup for the ssh password, but not the passphrase.
Using it with the same ssh key, without a passphrase, it is working without any problems.
**To Reproduce**

**Screenshots or Crash reports**

![Screenshot 2024-04-16 145606](https://github.com/HeidiSQL/HeidiSQL/assets/10380453/dcbcf855-9170-4a5c-a560-781dfd92d772)
![Screenshot 2024-04-16 145816](https://github.com/HeidiSQL/HeidiSQL/assets/10380453/f7c6ac9a-d10a-4751-a08a-1c3e0db95146)
plink.exe -ssh root@x.x.x.x -P 22 -i "C:\Users\xxx\.ssh\id_rsa" -N -L 3307:127.0.0.1:3306

**Comment by ansgarbecker** [comment]
I was just trying to reproduce on poweshell terminal, and `ssh.exe` prompts for my passphrase - so far so correct. After I entered the correct passphrase, I get a waiting cursor, and nothing happens for at least 20 seconds:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/77f36557-c398-402a-9dca-013e7741efc9)

What's happening there?

**Comment by ansgarbecker** [comment]
Problem seems to lie somewhere in my `TProcessPipe` and `TSecureShellCmd` implementation. The output saying "Enter passphrase for key ...:" is not visible in the out pipe, for some reason.

**Comment by ansgarbecker** [comment]
Related: #1838

**Comment by ansgarbecker** [comment]
I just tried with plink.exe and I was asked for the passphrase:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/1f04c931-d3fc-4dd7-8bf6-d29ff80c3266)

Note that plink/putty uses a different key format, so I had to convert my OpenSSH key with puttygen.exe to the format which plink accepts. Withouth that, plink is returning a "Unable to use key file" error (invisible in HeidiSQL), and asks for the users password.

**Comment by ansgarbecker** [comment]
Solution is to use plink witha putty key if you want to use keys with a passphrase. HeidiSQL then prompts you for the passphrase.

Using ssh.exe, it seems impossible to catch the "Enter passphrase" prompt from the internal process.

**Comment by MVS** [comment]
Just wanted to note that if you enable the SSH Agent, you can use `ssh.exe` as your SSH executable with a key that has a passphrase.

1. Enable the "OpenSSH Authentication Agent" service in Windows (set it to Manual instead of Disabled)
2. Add your key to the agent: `ssh-add keyfile`
3. Enter your passphrase

Now the SSH tunnel should work.
