### ISSUE TITLE
Sorting of JSON keys

### ISSUE THREAD

**Issue by aschoijett** [HeidiSQL/HeidiSQL#1941]
**Is your feature request related to a problem? Please describe.**
Using Heidi SQL 12.6.0.6814 on Windows 10

It looks to me that the JSON display of a column sorts the keys based on length of the key's name and then alphabetically.   
![image](https://github.com/HeidiSQL/HeidiSQL/assets/76222555/4699063c-8e3f-4a28-88b5-559276aaf7a0)

**Describe the solution you'd like**
Would it be better to sort them alphabetically or if it were possible, in the order that the json doc was created? 

**Describe alternatives you've considered**

**Additional context**

**Comment by ansgarbecker** [comment]
The order is not touched at all, at least should not. I made a quick test and the order of items of the original source is untouched, only indentation is done:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/c1be64f4-6121-4288-8e00-452d616a8734)

Please test this on your side: disable the menu item "Always format code" and watch out if the order of items is identical.

**Comment by aschoijett** [comment]
Hi Ansgar,
After disabling the "Always format Coe" option, I saw no difference in what
is shown by Heidi.

BTW, every time I close the Details - Text Editor, the application shows
the following.
I already reported this one but I thought it was because of the JSON.  It
happens with other field types as well.

[image: image.png]


*Alex Schoijett  |   *+1 647-924-7253

* <http://www.libraworks.ca>*
