### ISSUE TITLE
Sequal integration does not work

### ISSUE THREAD

**Issue by Jackymancs4** [HeidiSQL/HeidiSQL#1948]
**Preconditions**

* HeidiSQL version: 12.7.0.6850
* Database type and version: Irrelevant
* OS: Windows

**Describe the bug**

https://sequal.dev/ seems dead and I think it would be better to remove any reference to it.

**To Reproduce**

1. Go to a new query tab
2. Click Sequal Suggest
3. Click Generate SQL

**Screenshots or Crash reports**

![heidisql_3p73HQ5KFA](https://github.com/HeidiSQL/HeidiSQL/assets/6209647/bf4c5017-c07a-4c39-acca-4127b780af34)

**Comment by ansgarbecker** [comment]
Thanks for the hint! Didn't expect they take their page down. They also did not reply to my recent 3 emails, so I'll remove the dialog for now.

**Comment by ezekel** [comment]
Yes confirmed, I tried also and it didn't work the page of sequal is down.

**Comment by ansgarbecker** [comment]
Menu item is now hidden in the next builds.
