### ISSUE TITLE
Shortcut overwrite

### ISSUE THREAD

**Issue by anselal** [HeidiSQL/HeidiSQL#195]
1. Step 1: Go to Tools -> Preferences -> Shortcuts -> Export/Import and add a shortcut for exporting the grid data eg. Ctrl-E
2. Step 2: Ctrl-E works great, thus it displays the export popup
3. Step 3: The new shortcut is appears in the context menu as it should !!!

![2018-03-16_10h56_06](https://user-images.githubusercontent.com/8732668/37511797-cdc4c6ea-2908-11e8-84d6-01c4f0f2d3ca.png)

4 Step 4: Ctrl-E was default for "Table Filter" and it is still displayed as a shortcut although it got overwritten

![2018-03-16_10h42_02](https://user-images.githubusercontent.com/8732668/37511273-e5add3e8-2906-11e8-8c84-de2ee1dcff56.png)

## Current behaviour

The new shortcut (Ctrl-E) works and the shortcut is displayed in the context menu but it overwrites an existing shortcut that I don't was aware of.. at least I forgot that it existed.

## Expected behaviour

Prompt what to do ??? Don't overwrite existing shortcuts unless I tell you so. Actually it should replace and not overwrite.

## Possible solution

Display a warning/popup letting me know that the shortcut I am trying to apply already exists and also inform me what it currently does.
Or It could display a prompt asking me to *replace* it and if I agree it should delete the previous shortcut and apply the new one. With the update is should normally update the menu too I guess.
As you can see in the above image the shortcut is displayed in the menu because it is a default shortcut which was overwritten.

## Environment

* **HeidiSQL version:** 
  9.5.0.5261

**Comment by lubomihailov** [comment]
it's reproducible we can override shortcuts with no warning

**Comment by ansgarbecker** [comment]
I think this is a duplicate to #744 which I solved for the last v11.2 release.
