### ISSUE TITLE
CURRENT_TIMESTAMP not available for selection as default on DATETIME

### ISSUE THREAD

**Issue by WeviMark** [HeidiSQL/HeidiSQL#1951]
**Preconditions**

* HeidiSQL version: 12.7.0.6852
* Database type and version: MySQL 
* OS: Windows 11

**Describe the bug**

When selecting a default for a DATETIME field, i used to be able to select CURRENT_TIMESTAMP, but its not available in the Expression dropdown anymore. When i type it in the Expression field, i can set it as default.

**To Reproduce**

**Screenshots or Crash reports**

![image](https://github.com/HeidiSQL/HeidiSQL/assets/120108311/65ca56d8-37b1-43a7-99ec-5387b8680672)

**Comment by ansgarbecker** [comment]
Confirmed. Just like #1666

**Comment by ansgarbecker** [comment]
Fixed in the underlying .ini file. Will be installed with the installer, either the nightlies or the next official release.
If you want to have it fixed immediately, you can download this file and place in your HeidiSQL directory:
https://github.com/HeidiSQL/HeidiSQL/blob/master/out/functions-mysql8.ini

**Comment by WeviMark** [comment]
@ansgarbecker Thank you and sorry I missed the other ticket.

**Comment by ansgarbecker** [comment]
No need to be sorry - that was in a different file, but with the same effect.
Background: these ini files were generated by a custom PHP script I wrote, which retrieves the functions from the `mysql.help_*` tables. I guess my regular expression for filtering out unwanted items is not working for the particular `CURRENT_TIMESTAMP` description.
