### ISSUE TITLE
Allow editing values of SELECT query Result

### ISSUE THREAD

**Issue by Eddcapone** [HeidiSQL/HeidiSQL#1952]
It should be possible to edit values of a SELECT query result.
This would save alot of time.

In other software like DBeaver it works.

**Comment by ansgarbecker** [comment]
This is already possible. The only requirement is that HeidiSQL is able to determine the table name of the result, and that all columns derive from a single table.

**Comment by Eddcapone** [comment]
@ansgarbecker I can't confirm it. It knows the name but I still can't change data:

![image](https://github.com/HeidiSQL/HeidiSQL/assets/16349349/20154a51-81ff-414a-8fa9-5741c45c1f72)

**Comment by ansgarbecker** [comment]
Ok, then please select the primary key column(s) as well.

**Comment by Eddcapone** [comment]
Yes, that workaround works. But it would consume less time, if I could just change it without having to figure out the primary key column(s) first and changing my query accordingly. Another problem is, that people need to have that knowledge, otherwise they will think it is a bug / missing feature...

**Comment by ansgarbecker** [comment]
You say in DBeaver it works. How does it work there in such a situation? How does an UPDATE look like when you edit a value there?

**Comment by Eddcapone** [comment]
Well, I just execute my SELECT e.g.

```
SELECT path, value FROM
core_config_data 
```

Then I can simply edit the entries and click on save at the end.

**Comment by Eddcapone** [comment]
I see. Initially this window popped up:

![image](https://github.com/HeidiSQL/HeidiSQL/assets/16349349/cfd40fd4-32e4-404f-8794-b23054b5f98d)

I clicked on Use All Columns. Then after saving it executed these queries:

    UPDATE blizz_2024.core_config_data
        SET value='http://company.vm/xy'
	WHERE `path`='web/secure/base_url' AND value='http://company.vm/x'
	
And then a SELECT afterwards:

    SELECT path, value FROM core_config_data WHERE (`path` = 'web/secure/base_url') AND (value = 'http://company.vm/xy')

**Comment by Eddcapone** [comment]
I see. Initially this window popped up:

![image](https://github.com/HeidiSQL/HeidiSQL/assets/16349349/cfd40fd4-32e4-404f-8794-b23054b5f98d)

I clicked on Use All Columns. Then after saving it executed these queries:

    UPDATE company_2024.core_config_data
        SET value='http://company.vm/xy'
	WHERE `path`='web/secure/base_url' AND value='http://company.vm/x'
	
And then a SELECT afterwards:

    SELECT path, value FROM core_config_data WHERE (`path` = 'web/secure/base_url') AND (value = 'http://company.vm/xy')

**Comment by ansgarbecker** [comment]
Quite dangerous, this "Use All (selected) columns" button. You probably update more than one row then. Worst case would be you overwrite an important setting with that, and you even don't know you did it.

Is that "Use All columns" really something HeidiSQL should provide?

**Comment by Eddcapone** [comment]
Im not sure about that. Maybe you could name the button "Use All Colums (use at your own risk)"

**Comment by ansgarbecker** [comment]
I'm against such an addition. It leads to data loss. In my experience, even if a dialog says "use at your own risk", it's something many users don't understand and/or don't read.

But I just made the warning message visible in the log in such cases:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/9ac6f35f-5c37-451f-a08d-2f5e1712518c)
