### ISSUE TITLE
small display error in query panel

### ISSUE THREAD

**Issue by SethosOne** [HeidiSQL/HeidiSQL#1955]
**Preconditions**

* HeidiSQL version: 12.7.0.6850
* Database type and version: MariaDB 10.3.38
* OS: Windows 11

**Describe the bug**

In a query window with multiple queries, a small canvas appears briefly in the upper left corner of the query box during execution. If this query is executed multiple times and scrolled in the query window, a portion of the canvas will occasionally freeze and cover the contents of the query. This ghost field becomes larger and more disturbing throughout the day. The error occurs regardless of the connected database version or architecture.

**To Reproduce**

1.) connect to a database
2.) create any query in the query window. There must be more than 3 queries executed at a time.
3.) Click on execute
4.) observe the top left corner of the query window
5.) the small canvas appears short (bottom and right frame lines are drawn)
6.) At this point Windows gets confused with the refresh

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
This is a known issue, and was already reported in #1897.

I also made an attempt to fix that, after the v12.7 release. Please update to the latest build and retry. (Help > Check for updates > Download and install build xyz)
