### ISSUE TITLE
MySQL error 2006: mysql server has gone away

### ISSUE THREAD

**Issue by CraftedRO** [HeidiSQL/HeidiSQL#1960]
**Preconditions**

* HeidiSQL version: 12.7.0.6867
* Database type and version: MariaDB 10.4.32
* OS: Windows 11 x64

**Describe the bug**

For some reason everytime I'm trying to import a specific database I get this error even if server isn't stopped actually.
but max_allowed_packet = 512M is high enough as allways.

Same sql-s with few heidisql version ago worked well.

**To Reproduce**

1. Go to 'this link: https://github.com/CraftedRO/WowPacketParser/tree/master/SQL
2. Try to import https://github.com/CraftedRO/WowPacketParser/blob/master/SQL/create_wpp.sql then https://github.com/CraftedRO/WowPacketParser/blob/master/SQL/wpp_data_objectnames.sql
3. See error message:

**Screenshots or Crash reports**

![Captură de ecran 2024-06-02 165455](https://github.com/HeidiSQL/HeidiSQL/assets/24683355/2fabbb3b-5154-4d0a-9327-02048ef84624)

**Comment by CraftedRO** [comment]
Interesting, seems this happen only when I run mariadb as service, as process it is imported succesfully with same settings.

**Comment by ansgarbecker** [comment]
Likely something with your server settings, or with the file itself.

For debugging purposes please ensure you have import logging activated:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/b2bdce1e-ebca-45af-8774-b125d9c6a0e4)

Afterwards retry and watch out for the very last logged query in the bottom log panel before you get the error message.

**Comment by ansgarbecker** [comment]
You should in any case check if the max_allowed_packet variable is really set to the value you wanted. Probably the my.ini file is in the wrong folder:
```sql
SELECT @@max_allowed_packet;
```

**Comment by CraftedRO** [comment]
> Afterwards retry and watch out for the very last logged query in the bottom log panel before you get the error message.

I did this and that's the INSERT query before I get the message.

> You should in any case check if the max_allowed_packet variable is really set to the value you wanted.

seems like I got two different values here, and indeed as service the value is lower (16777216) probably default one.

**Comment by ansgarbecker** [comment]
Thank your for the update! Hope you find a fix for your server settings.
