### ISSUE TITLE
MySQL connection with SSL without Certificate and key not working

### ISSUE THREAD

**Issue by DaniDefago** [HeidiSQL/HeidiSQL#1961]
**Preconditions**

* HeidiSQL version: 12.7.0.6869
* Database type and version: MySQL 8.4
* OS: Windows 11

**Describe the bug**
I setup to connect to the server with SSL, but without any certificate and key, it's work with other software like MySQL Workbench and also using the command line. With Heidi SQL, I get an error "Lost connection to server during query ". I use the libmariadb.dll library.

**To Reproduce**

**Screenshots or Crash reports**
![image](https://github.com/HeidiSQL/HeidiSQL/assets/151941533/46eb0e04-105b-4efa-80b7-e7e26333609c)

**Comment by ansgarbecker** [comment]
I think this is related to what I found recently, and which also caused issue #1426 . If you update HeidiSQL with the latest build installer from the nightly builds page, I highly guess you can connect then.
Note you need to use the ["_32+64bit installer_" link from Revision 12.7.0.6868](https://www.heidisql.com/download.php#nightlybuilds).
After updating, change the library in your session to "libmysql-8.4.0.dll" and try to connect.

**Comment by DaniDefago** [comment]
The nightly build fixed the problem, thank you very much for your very quick answer.

**Comment by ansgarbecker** [comment]
Merci beaucoup, for your update!

**Comment by DaniDefago** [comment]
Hi,
Is this bug fixed in the last version 12.8.0 versions? Because I sill get the same error with the last version 12.8.0.6924

**Comment by ansgarbecker** [comment]
@DaniDefago please look at your comment from Jun 6.

**Comment by DaniDefago** [comment]
Hi,
I installed using the installer https://www.heidisql.com/installers/HeidiSQL_12.8.0.6922_Setup.exe I tried to connect using the library libmysql-8.4.0.dll and I get the following error:

![image](https://github.com/user-attachments/assets/3188d7ca-d9d0-418d-a3aa-a326f3c972e2)

**Comment by DaniDefago** [comment]
Hi,
I tried again with libmysql-8.4.0.dll and I had to change the option in the SSL certificate part to not verify the certificate.
Kindest regards,

**Comment by ansgarbecker** [comment]
Thank you for your quick feedback!
