### ISSUE TITLE
Suggestion window bug

### ISSUE THREAD

**Issue by Mbosso** [HeidiSQL/HeidiSQL#1962]
**Preconditions**

* HeidiSQL version: 12.6.0.6804
* Database type and version: SQL Server
* OS: Windows

**Describe the bug**
When using the column suggestion, the window opens incorrectly, with a height and width that make it impossible to view.

**To Reproduce**
Example:
Press CTRL + Space

**Screenshots or Crash reports**
![image](https://github.com/HeidiSQL/HeidiSQL/assets/32332557/02115f35-f681-400a-9297-a323f1ab1231)

**Comment by ansgarbecker** [comment]
Please install v12.7, and afterwards update to the latest build.
The next builds reset the width and height of that completion proposal, when you click _Tools > Reset panel dimensions_.

**Comment by Mbosso** [comment]
@ansgarbecker it's worked for me, thanks!
