### ISSUE TITLE
[BUG] Autocomplete size is broken

### ISSUE THREAD

**Issue by OxCom** [HeidiSQL/HeidiSQL#1963]
**Preconditions**
* HeidiSQL version: 12.7.0.6872
* OS: Windows 10 Build 19045
* 3 Monitors: with different scale factor (250%, 150% and 150%)

**Describe the bug**
The autocomplete suggestion box become smaller each launch of HeidiSQL.

**To Reproduce**
1. Run HeidiSQL
2. Write query and trigger autocomplete box (shift+space)
3. Restart HeidiSQL
4. Repeat from point 1.

Each restart the autocomplete box become smaller and smaller.
![image](https://github.com/HeidiSQL/HeidiSQL/assets/4608564/ba19cf06-8e5a-48d3-b672-dec88299c96b)

What I tried:
- Reset all settings to defaults
- Edit ```HKEY_CURRENT_USER\Software\HeidiSQL``` **CompletionProposalWidth**  and  **CompletionProposalNbLinesInWindow**
- Uninstall and install latest builds

**Comment by ansgarbecker** [comment]
I cannot reproduce this here. Do you probably move HeidiSQL back and forth between the monitors?

Related: #1962

**Comment by OxCom** [comment]
@ansgarbecker Just played with moving from one screen to another. Before test I used main monitor with scale factor (250%) and set CompletionProposalNbLinesInWindow = 10 and CompletionProposalWidth = 1024. Then:

- restart on first monitor with scale factor 250% - no changes, all good
- move from monitor 250% to next monitor 150% - changes the CompletionProposalNbLinesInWindow to lower value, CompletionProposalWidth  - same
- restart on 150% monitor (even if the session manager has been started on the same screen) - changes CompletionProposalNbLinesInWindow and CompletionProposalWidth to lower value then it was before

**Comment by ansgarbecker** [comment]
I think the next build fixes the issue.

Problem was the proposal form has its own DPI scaling, on top of the DPI aware stored/restored dimensions through the app. The (second) scaling is now disabled.

**Comment by gismofx** [comment]
@ansgarbecker @OxCom I am running 12.7.0.6874(Latest build as of today)

I still see autocomplete size issues. 
![image](https://github.com/HeidiSQL/HeidiSQL/assets/6783791/3e4884f6-82f8-419a-ae91-b559d64ac4e8)

I'm using windows 11 and have scaling enabled:
![image](https://github.com/HeidiSQL/HeidiSQL/assets/6783791/60383a9e-bfc9-4c0e-8442-7d98eca120f1)

**Comment by OxCom** [comment]
@ansgarbecker now it's become better: the autocomplete box keeps it's dimensions. thanks

**Comment by gismofx** [comment]
> @gismofx please resize the proposal window once to a good size. Then restart HeidiSQL to see if it still has the same size. The new build should fix a wrong resize after you restart HeidiSQL.

How do I do that? There is no resizer for the proposal window. (Also, I have switched to a 4k external monitor and have the same issue as above)

**Comment by ansgarbecker** [comment]
@gismofx yes, that's a known issue with the proposal, but only when having a (dark) style active. See the [upstream ticket](https://github.com/SynEdit/SynEdit/issues/123).
You can, however, click Tools > "Reset panel dimensions" to reset some controls inclusing the proposal to their default width and height.
