### ISSUE TITLE
MariaDB INET6 datatype support

### ISSUE THREAD

**Issue by NormanRice** [HeidiSQL/HeidiSQL#1964]
**Preconditions**

* HeidiSQL version: 12.7.0.6850
* Database type and version: MariaDB 10.6.8
* OS: Windows 11

**Describe the bug**

[MariaDB INET6 datatype](https://jira.mariadb.org/browse/MDEV-274) is not supported by the client. Columns with this datatype will register as UNKNOWN datatype, table modifications will fail because of unsupported datatype.

**To Reproduce**

1. CREATE TABLE t1 (a INET6); -- create test table
2. DESCRIBE prj_ip_location; -- shows table column a has datatype inet6
3. see HeidiSQL Table Structure tab of table t1: datatype is UNKNOWN. 

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Interesting to see MySQL does _not_ have these INET4 and INET6 types.
MariaDB has them documented [here](https://mariadb.com/kb/en/data-types/).

**Comment by ansgarbecker** [comment]
I'm thinking about outsourcing the data type definitions out of the [dbstructure units](https://github.com/HeidiSQL/HeidiSQL/blob/77f3407738e945d6ee492509e6ba8303904f81f7/source/dbstructures.mysql.pas#L314) into separate .ini files. Similar to the [functions *.ini files](https://github.com/HeidiSQL/HeidiSQL/blob/master/out/functions-mariadb.ini). This would introduce some advantages:
* separate MariaDB types from MySQL (which we would need for these INET6/INET4 types)
* possible customization done by the user

.. but as always some disadvantages:
* .ini files not updated through nigtly build updater
* more internal parsing for certain types and categories

**Comment by NormanRice** [comment]
If customization by the user is a requirement, maybe you could split the ini files into 2 files? Like have a _dbstructure-mariadb.ini_ and an optional _dbstructure-mariadb.user.ini_ - with only the first one being part of the build and subject to updates?

**Comment by ansgarbecker** [comment]
Customization is not a requirement, it was just an idea as I was weighing the pros and cons. In fact, having data types in a separate file could introduce new issues, for instance with file privileges. I think I will leave this internally for now. I will find a way to hide these types away on MySQL sessions which do not have INET4/INET6.

**Comment by ansgarbecker** [comment]
Next build has these both types:
![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/478c607e-b684-44e5-9475-88238e486fc1)
