### ISSUE TITLE
Empty warnings when importing mariadb into mysql

### ISSUE THREAD

**Issue by CraftedRO** [HeidiSQL/HeidiSQL#1965]
**Preconditions**

* HeidiSQL version: 12.7.0.6876
* Database type and version:MariaDB 10.4.32 and MySQL 8.4
* OS:Windows 11

**Describe the bug**

When I try to import some mariadb db file into mysql 8.4 it is imported but with some "empty" warnings, I understand that might be some incompatibilities between the two database servers but interesting fact is that in navicat no error occurs doing same operation.

**To Reproduce**

Example:
1. Go to Heidisql login to MariaDB 10.4.32 server then export some database
2. Go to Heidisql login to empty MySQL 8.4 server then import previous database
3. See Warnings: 69 message: xyz

**Screenshots or Crash reports**
![Captură de ecran 2024-06-14 183650](https://github.com/HeidiSQL/HeidiSQL/assets/24683355/872dbe70-1916-46b0-abc8-70c97a7fdb3f)

![Captură de ecran 2024-06-14 183709](https://github.com/HeidiSQL/HeidiSQL/assets/24683355/7e3799d0-fbcd-45a4-8434-3cf5fbc69b6c)

**Comment by CraftedRO** [comment]
Also I have another somehow related issue when I --initialize-insecure mysql 8.4 I can connect with heidisql libmysql.dll but once I enter a password or I just --initialize simple I won't be able to connect with libmysql.dll but only with libmariadb.dll and idk what's the issue here.

**Comment by ansgarbecker** [comment]
I cannot reproduce that here, with an import on MySQL 8.3 from a MariaDB 10.3 server.

Please provide the SQL export here, if it does not contain sensitive details.
Alternatively, run the import queries one by one, so the warning message(s) can be seen.

**Comment by CraftedRO** [comment]
well unfortunately this time the sql contain sensitive details, maybe I can reach you on discord ?

**Comment by ansgarbecker** [comment]
I am not using Discord. You could send me an email, to the address mentioned on the [imprint page](https://www.heidisql.com/imprint.php).

**Comment by CraftedRO** [comment]
ok, mail has been sent.

**Comment by ansgarbecker** [comment]
Thanks for your email. I could import your data into my local MySQL 8.3 server, and got the same warning number like you.

If you execute the first query only, you already see the warning details:
![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/36b229b8-bd32-4dbd-a442-be64afc4b427)

The repeated message is just a deprecation warning:
```
Integer display width is deprecated and will be removed in a future release.
```
It basically says your code contains column types like `INT(11)` which will no longer be supported in some future release of MySQL.

**Comment by CraftedRO** [comment]
ok I got it, even if I think all errors shoud still be displayed instead empty tab when inserting the whole db as bulk.

some thoughts about second issue, when I set a password on mysql it won't allow me to connect with libmysql.dll but only with libmariadb.dll , is this expected behaviour ?

> Also I have another somehow related issue when I --initialize-insecure mysql 8.4 I can connect with heidisql libmysql.dll but once I enter a password or I just --initialize simple I won't be able to connect with libmysql.dll but only with libmariadb.dll and idk what's the issue here.

**Comment by ansgarbecker** [comment]
libmysql.dll is old, and only provided for compatibility to old 4.x/3.x servers. Don't use it on modern servers. The different libraries have all their reason, but libmariadb.dll is the default one.

**Comment by ansgarbecker** [comment]
Warnings will be shown in the log panel in the next builds. I was not aware the warnings pool gets emptied on the next query. Firing `SHOW WARNINGS` only once at the end does not show anything, or only those from the very last query.

The messages can either be warnings or notes, and both of them get a background color in the log, so the user can distinct them easily:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/a58a234f-4a6d-4393-bd33-462aa1ca24c6)

**Comment by ansgarbecker** [comment]
Related earlier post: https://www.heidisql.com/forum.php?t=41753

**Comment by CraftedRO** [comment]
interesting is that navicat for example doesn't export integer width value, maybe an option to disable that

**Comment by ansgarbecker** [comment]
Note that the CREATE code is retrieved from the server, via `SHOW CREATE TABLE`. On MySQL 8.0+, this already does not contain integer display widths.

Also, HeidiSQL now does not show the integer display width on MySQL 8.0.17+. The user may still apply a display length, but the server will return a warning which is now displayed in the log panel, with a warning color.

**Comment by ansgarbecker** [comment]
Related: issue #1088
