### ISSUE TITLE
Delta parquet support

### ISSUE THREAD

**Issue by benito2313** [HeidiSQL/HeidiSQL#1966]
**Is your feature request related to a problem? Please describe.**
I cant read delta files.

**Describe the solution you'd like**
I would like to use heidi to read/write to a Delta Lake House. Delta parquet.

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by ansgarbecker** [comment]
This was already discussed in the a [forum thread](https://www.heidisql.com/forum.php?t=41420).

Reading and writing parquet files is beyond what HeidiSQL will support.
