### ISSUE TITLE
The donation button occupies two rows of space

### ISSUE THREAD

**Issue by linauror** [HeidiSQL/HeidiSQL#1967]
**Preconditions**

* HeidiSQL version: 12.7.0.6877
* Database type and version: mysql 5.7
* OS: windows 10

**Describe the bug**

When I upgraded to the latest version, when I opened it, I saw that the donation button in the toolbar occupied two rows and could not be adjusted to one row

**To Reproduce**

**Screenshots or Crash reports**

![20240617162306](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/aa28f57b-6099-49a0-8b22-c4f7e28e2cad)

**Comment by ansgarbecker** [comment]
Is that really still the case in the latest build? I thought I fixed that in 0e389da429feb138f0320a584ca245c6e32e6f12 (build 6852) . 🤔

**Comment by linauror** [comment]
Yes, it's the latest version
![image](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/b50b811b-6595-4db1-a51b-256be8c275a4)

**Comment by ansgarbecker** [comment]
Ok, then is there a screen with a non-default DPI setting active?

**Comment by linauror** [comment]
it's default DPI setting 100%

**Comment by ansgarbecker** [comment]
Strange.. and I cannot reproduce that here on 3 different systems, one of them running Windows 10 without DPI scaling, just like yours.
Could you perhaps make a screenshot of the "General" settings page, in Tools > Preferences? Hoping to find some cause there, exotic setting or something.

**Comment by linauror** [comment]
There is "General" settings page

![image](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/6a12f060-66ea-4713-aefd-e232b415cdfc)

**Comment by ansgarbecker** [comment]
Ok, looks very normal so far. Only one thing: Is it my old eyes or could it be the font is different from the default? Although I see GUI font is set to default.

**Comment by linauror** [comment]
I think it‘s bacause the deault font is "微软雅黑" and "9 pt".     But "8 pt" is ok, and other font is also ok.
![image](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/ad9787ec-832e-4a62-9c36-62ad4846a124)

**Comment by linauror** [comment]
And font is "Microsoft YaHei UI" with "9 pt" is not ok.
![image](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/918857ac-a2fe-4e74-9a42-099d384519f0)

**Comment by ansgarbecker** [comment]
Can you please post another screen where I can see the height of the button, when you hold the mouse over the button?
![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/6e61ce03-15b4-4af7-a0d1-0028f2369c81)

**Comment by linauror** [comment]
when the mouse over the buttom
![image](https://github.com/HeidiSQL/HeidiSQL/assets/3039051/86a35f8c-9c0f-4a49-b531-0f2f8dd262a9)

**Comment by ansgarbecker** [comment]
This is definitely a font issue. No problem with my default font, which is "Segoe UI" I believe. I will try to work around that, now that I can reproduce with "Microsoft YaHei UI".

**Comment by linauror** [comment]
good job
