### ISSUE TITLE
Recently imported tables will export empty value if not refresh

### ISSUE THREAD

**Issue by CraftedRO** [HeidiSQL/HeidiSQL#1969]
**Preconditions**

* HeidiSQL version: 12.7.0.6897
* Database type and version: MySQL 8.4
* OS: Windows 11 x64

**Describe the bug**

Recently imported tables will export empty value if not using refresh first, maybe adding some autorefresh before exporting ?

**To Reproduce**

Example:
1. Go to 'heidisql then login to session'
2. Click on 'create a database with any name you want then import somthing there'
3. Now click to export that database
4. See that you exported empty database unless you use refresh after importing

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
I'm not sure I get the issue. You were doing an SQL export and did not watch out for the tables inside the database tree node, or how did you produce an empty sql file? Please post a screen of the problematic area.

**Comment by CraftedRO** [comment]
seems cannot longer reproduce on latest build but maybe woud be a good thing to not be able to export database while importing process is in progress (at the same database :D)
