### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by marcelomelofreitas** [HeidiSQL/HeidiSQL#197]
How do I compile the HeidiSQL compiled by me to stay in Brazilian Portuguese? How to apply the translation?

**Comment by ansgarbecker** [comment]
This is a question, please post such things to the forum, not in the issue tracker.

If you have a .po file compiled to some .mo file, in out/locale/..., and you have a compiled heidisql.exe, you can put both together with such a command line:
`c:\heidisql\master\> extra\internationalization\assemble.exe out\heidisql.exe --dxgettext`
