### ISSUE TITLE
Database export - View's being export Creating temporary table to overcome VIEW dependency errors. Will result in Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535.

### ISSUE THREAD

**Issue by littleearth** [HeidiSQL/HeidiSQL#1971]
**Preconditions**

* HeidiSQL version: 12.7.0.6851
* Database type and version: MySQL 8.0.36
* OS: Windows

**Describe the bug**

When a temporary tables is being created for a view that contains alot of large VARCHAR. The temporary table cannot be created. Possible limitation in MyISAM.

**To Reproduce**
Create a view that contains many VARCHAR(2000) and use the export routine. 

Solution as these are just temporary any VARCHAR over 45 becomes VARCHAR(45)

```
function StripNonNumeric(
  const AValue: string;
  AAllowDecimal: Boolean = False;
  AAllowNegative: Boolean = False): string;
var
  i: Integer;
begin
  Result := '';
  if Trim(AValue) <> '' then
  begin

    for i := 1 to length(AValue) do
    begin
      if (CharInSet(AValue[i], ['0' .. '9'])) or
        ((AAllowDecimal) and (AValue[i] = '.')) or
        ((AAllowNegative) and (AValue[i] = '-')) then
      begin
        Result := Result + AValue[i];
      end;
    end;
  end;
  Result := Trim(Result);
end;

// try to avoid error  Row size too large. The maximum row size for the used
// table type, not counting BLOBs, is 65535.
if StrToIntDef(StripNonNumeric(LColumnType, false, false), 0) > 45
then
begin
 LColumnType := 'varchar(45)';
end;
```

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Can confirm the issue.

But why exactly `varchar(45)`, not `varchar(1)`?

**Comment by littleearth** [comment]
Valid point no reason for 45 that I can think of.

**Comment by ansgarbecker** [comment]
Fixed in the next build.
