### ISSUE TITLE
Verify SSL identity and CA as the default behavior

### ISSUE THREAD

**Issue by gnd** [HeidiSQL/HeidiSQL#1972]
**Is your feature request related to a problem? Please describe.**
HeidiSQL does not verify SSL certificate against hostname by default when using SSL. This is wrong as it opens the possibility of a MITM attack, and makes the usage of SSL to encrypt the connection a moot point. 

**Describe the solution you'd like**
HeidiSQL shall by default verify the certificate. This should be possible to turn off, but the default behaviour should be secure. 

**Describe alternatives you've considered**
Installing DBeaver which does this properly.

**Additional context**
The motivation to use SSL is to prevent eavesdropping along the way. However if the attacker already controls a device or network along the route, it is easy for them to intercept the connection and do a MITM attack. This can be prevented by the client properly verifying the server's SSL certificates. Without verification SSL is mostly useless.

**Comment by ansgarbecker** [comment]
Confirmed. I had no clue that by default no check is done. According to the [docs](https://dev.mysql.com/doc/c-api/8.4/en/c-api-encrypted-connections.html), there are 3 options/levels, not just one: no check, verify ca, and verifiy hostname identity.

> To specify the CA certificate, call [mysql_options()](https://dev.mysql.com/doc/c-api/8.4/en/mysql-options.html) to pass the MYSQL_OPT_SSL_CA (or MYSQL_OPT_SSL_CAPATH) option, and call [mysql_options()](https://dev.mysql.com/doc/c-api/8.4/en/mysql-options.html) to pass the MYSQL_OPT_SSL_MODE option with a value of SSL_MODE_VERIFY_CA.
> 
>    To enable host name identity verification as well, call [mysql_options()](https://dev.mysql.com/doc/c-api/8.4/en/mysql-options.html) to pass the MYSQL_OPT_SSL_MODE option with a value of SSL_MODE_VERIFY_IDENTITY rather than SSL_MODE_VERIFY_CA.

I think I will place a dropdown on the SSL tab with these 3 values.

**Comment by gnd** [comment]
Thanks for looking into this. I think at least `SSL_MODE_VERIFY_IDENTITY` should be a default.

**Comment by ansgarbecker** [comment]
Seems MariaDB and MySQL have a different and incompatible implementation:
* MariaDB uses the on/off option `MYSQL_OPT_SSL_VERIFY_SERVER_CERT`
* MySQL uses the 3 state option `MYSQL_OPT_SSL_MODE`

HeidiSQL offers both libraries, so I should take care of that. What a mess.

**Comment by ansgarbecker** [comment]
Plus there is the [client capability flag](https://mariadb.com/kb/en/connection/#capabilities) `CLIENT_SSL_VERIFY_SERVER_CERT`. But that is for my peace of mind deprecated in favour of the above `MYSQL_OPT*` options.

**Comment by adopauco** [comment]
The "Verify CA" option without host name identity verification should be also labeled as insecure in the GUI imho.
If there is no SSL CA Certificate specified in the SSL settings tab then the system certificates will be used. In this case any publicly trusted certificate from an attacker owned domain could be used to perform MITM for any database host.

**Comment by ansgarbecker** [comment]
Done. Would be good to hear from someone giving the new options a test.

**Comment by gnd** [comment]
Thank you so much, legendary !

**Comment by ansgarbecker** [comment]
Thank you, for your quick feedback!

**Comment by ansgarbecker** [comment]
@nwcm Yes, understood. I was hoping the text in the footer of the error dialog makes it clear:
    You might need to lower the certificate verification in the SSL settings.
Please also note this verification is security related, and should be used by default. That indeed changed the session logic silently. I was also thinking most of the certificates used by SSL users are valid.
