### ISSUE TITLE
Minor: Very low contrast for User Management window on third group of permissions

### ISSUE THREAD

**Issue by jabcreations** [HeidiSQL/HeidiSQL#1981]
**Preconditions**

* HeidiSQL version: 12.8.0.6908
* Database type and version: MariaDB 10.11
* OS: Windows 10 x64 22H2

**Describe the bug**

Using the "Windows10 Dark" theme the User Management window has very low contrast text for the third group of permissions. Please see the image below.

**To Reproduce**

Example:
1. Open HeidiSQL
2. Connect to any server.
3. Click on the Tools menu.
4. Click on User Management.
5. Click on any user on the left column.
6. Expand the permissions and note the very dark blue text for the bottom third of the commands.

![heidisql-theme-users-low-contrast](https://github.com/user-attachments/assets/90888da6-a1d1-4724-82f9-030954fc9795)

**Comment by ansgarbecker** [comment]
Fixed in the next build:

![grafik](https://github.com/user-attachments/assets/57f6aeae-c6a9-4d2d-93f4-0f2bb16cb92b)

**Comment by jabcreations** [comment]
ROCK! Thank you Ansgar!  🎈🎉🎊

**Comment by jabcreations** [comment]
Also, if it's not a bother, any general ETA on the next release? 🙂︀

**Comment by ansgarbecker** [comment]
I think before christimas.
