### ISSUE TITLE
Wrong Result Tab Labels

### ISSUE THREAD

**Issue by andi3** [HeidiSQL/HeidiSQL#1984]
**Preconditions**

* HeidiSQL version: 12.8.0.6908 (64 Bit)
* Database type and version: MariaDB 10.4.17
* OS: Windows 11

**Describe the bug**

When running multiple queries at once, the labels of the result tabs are wrong if an alias is used in the query.

First example (no alias in the order table query)
![Screenshot 2024-07-18 134232](https://github.com/user-attachments/assets/72051482-d133-4563-90bd-ccefb3d21c00)
Everything works as expected! The result tab name is "order"

If an alias is used in the second query (line 4), then the result tab label is the name of the first commented line even if there are multiple comment lines:
![Screenshot 2024-07-18 134444](https://github.com/user-attachments/assets/de7ba216-b1fa-43c5-a600-f3bccf1f2967)

The content of the second tab is correct and contains the data from the query of line 4, but the label should be "order" instead of "order_item".

**To Reproduce**

1. Write multiple queries in a new query tab and use aliases for the tables in the FROM part.
2. Add commented out queries among those active queries.
3. By running the queries, the result tabs will have the title of the commented out queries.

**Screenshots or Crash reports**

**Comment by ansgarbecker** [comment]
Fixed in the next build.
