### ISSUE TITLE
List of selectable columns for foreign keys only shows 3-4 characters.

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1990]
When setting up foreign keys; the list of selectable columns only shows the first 3-4 characters.

![image](https://github.com/user-attachments/assets/49ef8245-e042-4afd-bc23-bb2d78111e1f)

**Comment by ansgarbecker** [comment]
The width of that checkbox list is synced with the "Foreign columns" column. Widening the column also widens the list.

![foreign-columns-checkboxes-width](https://github.com/user-attachments/assets/09a0d118-d194-44d0-a05e-65957fa849d2)

**Comment by timint** [comment]
Very good. Thank you
