### ISSUE TITLE
Selected referenced table throws an error

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#1991]
When constructing a foreign key. When selecting a table in the referenced list of tables. An error is shown saying the table does not exist or is damaged. It is possible this could be caused by a dot in the table name? If preceeded by database name it works e.g. "dbname.tbl.name".
![image](https://github.com/user-attachments/assets/6df5e413-6a3f-4497-adf7-58f358b63a6e)
![image](https://github.com/user-attachments/assets/b08a4c0f-655b-4f23-a9ba-4289fe484005)

**Comment by ansgarbecker** [comment]
Please post more technical details like server version, and please don't delete the issue template.

**Comment by timint** [comment]
HeidiSQL 12.8.0.6908
MariaDB 11.3.2
The error translates to: Reference table "clients.invoices" seems to be missing, is broken or not accessible.

**Comment by ansgarbecker** [comment]
Ah, understand. Yes, this is caused by the dot in a tablename. That referenced table may already have the database name in it, so HeidiSQL currently has difficulties with table names containing a dot. Next build does a quick check if the left part was already seen in the list of databases.

**Comment by timint** [comment]
These errors can occur if not encapsulating table names in the queries with ``` ` ```.

Examples:
``` `table.name` ```
``` `database.name`.`table.name` ```

I don't know what other characters except dot that can cause conflicts. But encapsulating should be safe for any conflicting character.
