### ISSUE TITLE
CREATE TABLE ... CHECK() . support

### ISSUE THREAD

**Issue by igorky** [HeidiSQL/HeidiSQL#2]
## Expected behavior

Please add support of CHECK section in create table statement.

## Current behavior

No information on UI. 
No information about CHECK section in the "CREATE code" tab.

### Steps to reproduce

CREATE TABLE `test_json` (
	`test_col` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin'
)
ENGINE=InnoDB;

ALTER TABLE `test_json`
	ADD CHECK(JSON_VALID(test_col));

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: r5184
* Database system + version: MariaDB 10.2.10
* Operating system: Win10

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by ansgarbecker** [comment]
Sorry, wrong ticket id in the commit, should have been #3, not #2.

**Comment by ansgarbecker** [comment]
Some documentation about `CHECKS` can be found on the [MariaDB pages](https://mariadb.com/kb/en/library/constraint/#check-constraints).

But I have problems in finding a documentation for getting existing CHECK clauses on a table. Can you provide some details or an online documentation?

**Comment by vaintroub** [comment]
@ansgarbecker , "SHOW CREATE TABLE"  gives existing check clauses.

**Comment by rentalhost** [comment]
**Closing:** as is same as #75 we will keep talking in this new ticket.

**Comment by lukinhaspm** [comment]
You can fetch some information from CHECK_CONSTRAINTS in information_schema.

I think you can add this option to create "check" in the collumns options
