### ISSUE TITLE
Inconsistent Conversion of CURRENT_TIMESTAMP to now() for Default Column Values

### ISSUE THREAD

**Issue by harusakura924** [HeidiSQL/HeidiSQL#2001]
### Description

**What were you trying to do?**

Set the default value of a column to `CURRENT_TIMESTAMP`.

**What actually happened?**

When setting the default value of a column to `CURRENT_TIMESTAMP`, it was automatically converted to `now()` upon saving the table.

**What did you expect to happen?**

The column's default value should remain as `CURRENT_TIMESTAMP`.

> Even though the official documentation for the [MySQL CURRENT_TIMESTAMP() function](https://www.w3resource.com/mysql/date-and-time-functions/mysql-current_timestamp-function.php) states that the two are functionally equivalent, this leads to inconsistency in table schema definitions. This is particularly problematic for projects where table definitions need to remain consistent across different environments.
>
> The reason for setting the column's default value to `CURRENT_TIMESTAMP` is because phpMyAdmin offers the `CURRENT_TIMESTAMP` option for setting default values in table columns.
> 
![image](https://github.com/user-attachments/assets/e20380e6-1378-45cf-b92a-02ad06d123aa)

### HeidiSQL version

12.8.0.6908

### Database server version

MySQL 8.0.36

### Error/Backtrace

```shell
No
```

### Reproduction recipe

1. Create a new table.
2. Create a field (name can be arbitrary).
3. Set the type to DATETIME.
4. Set the default value by selecting CURRENT_TIMESTAMP in the "Expression" field.
5. Click "Save".
6. The field's default value will be converted to now().

**Comment by ansgarbecker** [comment]
That silent conversion to "now()" is done by the server, not by HeidiSQL. Some more silent conversions are documented on [mysql.com](https://dev.mysql.com/doc/refman/8.4/en/silent-column-changes.html).
What do you expect from HeidiSQL here?

**Comment by ansgarbecker** [comment]
Yes, HeidiSQL wraps a column `DEFAULT` expression in parentheses, but only for [MySQL 8.0.13+](https://dev.mysql.com/doc/refman/8.0/en/data-type-defaults.html#data-type-defaults-explicit). This is a requirement from MySQL, for all expressions except `CURRENT_TIMESTAMP`. And yes, using `CURRENT_TIMESTAMP` without parentheses around it, the `DEFAULT` value indeed is not silently converted to `now()`.

This is a mess... it just leads to complicated code here and there. I wonder why MySQL still supports that, while on the other hand they require the parentheses for all other expressions. On top of that, it doesn't matter if you specify `DEFAULT CURRENT_TIMESTAMP` or `DEFAULT CURRENT_TIMESTAMP()` - the latter one gets converted to `DEFAULT CURRENT_TIMESTAMP` silently.

I like to keep things simple and consistent, so I tend to say MySQL 8.0.13 DEFAULT values always get parentheses.
