### ISSUE TITLE
Enhance auto-sized column in foreign key list of table editor

### ISSUE THREAD

**Issue by ZeoNish** [HeidiSQL/HeidiSQL#2003]
### Description

[ice_video_20240813-100524.webm](https://github.com/user-attachments/assets/75dcc8b3-d280-4fc0-a74a-a9bc501e99a5)

### HeidiSQL version

12.8.0.6919

### Database server version

-

### Reproduction recipe

In video progress

**Comment by webdbase** [comment]
I confirm the same behaviour.

Microsoft Windows [Version 10.0.19045.4651]
Preferences > General > Style theme is Windows

https://github.com/user-attachments/assets/0c54bcdd-b593-4a79-ba46-ca1e5819fe94

**Comment by ZeoNish** [comment]
> This is very normal behaviour. The first column is set as the "main column", for which reason the others are aligned to the right. I don't see any problem in the video, and there is no description on what you think is a bug here.

Exactly what cannot be moved normally. Is the first column "Key name" supposed to be fixed like this?... It's just that when trying to output the rest of the columns normally, the columns change their width in the opposite direction.  Similar behavior in "Indexes" and "Foreign Keys"

**Comment by ZeoNish** [comment]
I do not understand why the first column is set as the "main" one, why such a priority that prevents the use of other columns.

**Comment by ansgarbecker** [comment]
Next build removes the "AutoSize" thing in the first column of the foreign key list. Please update and see if that really makes it better.

![foreign-keys-no-autosize](https://github.com/user-attachments/assets/34609829-c39e-43e8-915d-3d1964adf6a6)
