### ISSUE TITLE
SQLite Triggers neither displayed nor editable

### ISSUE THREAD

**Issue by igpf** [HeidiSQL/HeidiSQL#2004]
**Is your feature request related to a problem? Please describe.**
When using the sqlite database, I'm able to create a trigger on a table, however I'm not able to view it after its been created.
I'm also not able to delete it using the treeview.

Since you're able to create the triggers, I figured you should be able to view/edit them accordingly.

Amazing application. I love it, great work!

kind regards,
-ivan

**Comment by ansgarbecker** [comment]
Do you get some error when opening a trigger? Can you describe what's happening when you do that?

**Comment by ansgarbecker** [comment]
Triggers are now loaded in the tree/tab, but trying to edit them causes SQL errors, as the trigger editor is still only usable for MySQL.
