### ISSUE TITLE
Feature request: A data generation tool

### ISSUE THREAD

**Issue by robsch** [HeidiSQL/HeidiSQL#2009]
**Is your feature request related to a problem? Please describe.**
I need some dummy data in a table. How can I create, let's say, 100.000 rows? Might be with a stored procedure or creating an appropriate list of Insert statements, with copy and paste, maybe with the help of Excel or so. For me, it is not so obvious, how to do it easily.

But since HeidiSQL already knows the structure of my table/database, I thought it might be adequate to have a generation option in HeidiSQL. I could imagine that it would be helpful to many users, if there is a nice way to create data easily.

**Describe the solution you'd like**
Not sure. It's up to you. I thought about an separate dialog, where the user can configure how the data should be generated. Of course, there would be a lot of options. But some basic logic could be there, like incrementing a number or date with a certain interval for each row, starting from a certain point. Or alternating between certain values. Or creating random values. Providing constants would be simple.

From a development perspective I'd say, start basic and add more sophisticated things later.

**Describe alternatives you've considered**
As described above, I do not know how to create data. Possible that other tools exist, but having it within HeidiSQL would be great!

Of course, this is not implemented in a weekend or so. You can think about it and if so, design it as you like. It is just an idea - whatever you'll do with it.

**Love HeidiSQL for long time! Great piece of work!**

**Comment by ansgarbecker** [comment]
The "table tools" dialog with the SQL export and other things could get a new tab "Generate data". That way we already have a table selection tree, and a dialog already known by the user.

**Comment by robsch** [comment]
Wow, you are fast! That's cool. Really great that you started to implement it straight away. But I can imagine, this feature will embraced by many users.

With what does the columns get filled? I guess static values as a first approach, right? Question is, what other fill options could be offered. It is probably not so trivial, as there are different needs (random, increasing, alternating, ...) for different types. And this has to be realized in the UI somehow. But the good thing is, that it can added step by step.

Looking forward about that feature!

**Comment by lukinhaspm** [comment]
@ansgarbecker great tool!!
I tried but not worked for me because broke in CONSTRAINT, can you add one option to ignore CONSTRAINT? Also ignore FK?
I think you will need handle to get random values from connected tables to works better.

**Comment by ansgarbecker** [comment]
> With what does the columns get filled?

Random values. Random integer and float numbers, text with non-critical ASCII chars in random length up to the max length. Date/time values from 1971 to 2035, and so on.

**Comment by webdbase** [comment]
The line "Generate data" in the "Тools" menu, as well as the button "Generate" are not translatable in Transifex.
![image](https://github.com/user-attachments/assets/1423ac79-1c90-41d3-9b5e-8795828b6f8c)

**Comment by ansgarbecker** [comment]
Next build adds:
* missing translation strings
* random binary data generation
* disabling foreign key checks during generation

**Comment by ansgarbecker** [comment]
I'm closing this ticket for now, as the basics are working good from my perspective.
