### ISSUE TITLE
Set default database collation in dropdown list to server default if available

### ISSUE THREAD

**Issue by TonyGravagno** [HeidiSQL/HeidiSQL#2011]
**Is your feature request related to a problem? Please describe.**
I installed MariaDB v11.5 today, which is bundled with HeidiSQL. The collation "Servers default: utf8mb4_uca1400_ai_ci" is displayed but the default collation in the dropdown list is the first in the list, which is "armscii8_bin" (binary Armenian). That does not at all suit most countries. Prior to HeidiSQL v12.7 we couldn't get that specific collation. Thanks to a v12.7 enhancement from #1917 we can. Perhaps the default selection already should select that value, and it's a bug now that it does not.

The issue/challenge is that a new database will be created with this Armenian binary collation sequence in the current MariaDB unless the DBA knows about this nuance. 

**Describe the solution you'd like**
The feature request is to detect the system default and try to match it, perhaps to advise the user that the default is not available if it cannot be found, and perhaps to default to something more regionally acceptable than the array element zero of the full list.

**Describe alternatives you've considered**
No alternatives available for this challenge other than being intensely curious about what armscii8_bin is and then following the path to setting the correct value.

**Additional context**

![image](https://github.com/user-attachments/assets/4439e571-971e-4995-a456-3e0ebef172e6)

![image](https://github.com/user-attachments/assets/02a48189-70a7-4321-8e91-b79cbf3182b3)

**Comment by ansgarbecker** [comment]
The create-database dialog auto-selects the collation you have previously used. If you never used the dialog before (to be exact, if you never clicked the OK button there), it auto-selects the servers' `collation_server` variable. If that default one is not in the list (as in older HeidiSQL versions), the very first collation in the list is selected (which happened in your case).

Could it be you have previously used that dialog in an older HeidiSQL version, without UCA collation support? That would explain the issue.

**Comment by TonyGravagno** [comment]
I'm sure that is what happened. I would need to uninstall/reinstall MariaDB and HeidiSQL to test, and I'd prefer not right now. If someone loads Heidi for the first time and sees the correct collation in the dropdown then this ticket is certainly invalid. So, the decision is to you about whether to leave open for a while for verification or close now.

Thanks!

**Comment by ansgarbecker** [comment]
I just optimized the code slightly, so that the drop-down selects 'utf8mb4_unicode_ci' in cases where the servers default collation is not set, or not yet supported by HeidiSQL.
