### ISSUE TITLE
MySQL 8 user not showing SSL required

### ISSUE THREAD

**Issue by NigelGomm** [HeidiSQL/HeidiSQL#2014]
### Description

did a create user with REQUIRE SSL and it appears to have worked. but when i use Heidi to check it doesn't show the SSL requirement.
![image](https://github.com/user-attachments/assets/e4cf04fd-2a56-40b7-9649-5a90c8ab04f0)

### HeidiSQL version

12.8.0.6908

### Database server version

MySQL 8.0.37-azure

### Reproduction recipe

create user 'xyz' indentified by 'abc' REQUIRE SSL;
SELECT HOST,USER,ssl_type FROM mysql.user;
/ shows 'ANY' which i believe means SSL
now click users icon in Heidi and look at the SSL tab.... no requirements showing.

**Comment by ansgarbecker** [comment]
Confirmed. MySQL 8 seems to have the `REQUIRE SSL` clause in the `CREATE USER` statement, while earlier versions show it in the `SHOW GRANTS FOR user...`. HeidiSQL expects the latter one, and I don't know how to obtain that SSL settings for MySQL v8 users.
