### ISSUE TITLE
https://www.heidisql.com/forum.php?c=4#google_vignette

### ISSUE THREAD

**Issue by chotu121kim** [HeidiSQL/HeidiSQL#2016]
### HeidiSQL version

sass

### Database server version

sasasas

### Error/Backtrace

```shell
https://www.heidisql.com/forum.php?c=4#google_vignette id not login or activation code not received in email id
```

### Reproduction recipe

Go to ...
Click on ....
See error message: ...

**Comment by ansgarbecker** [comment]
This is not a valid bug report.

If you expect something useful, please describe the problem.
