### ISSUE TITLE
HeidiSQL freezes (hangs) completely when displaying large cells in results table

### ISSUE THREAD

**Issue by ilpssun** [HeidiSQL/HeidiSQL#2020]
### What where you trying to do?
Connected to an MS SQL server (although I'm not sure whether that is relevant), I do a simple select that returns a small number of rows (e. g. `select top 50 …`).  One of the columns contains a large text field with character data that is several KiB in size, e. g. an XML document with >100.000 characters.  I would then like to copy the cell value and paste it into my text editor.

### What actually happened?
When that cell scrolls into view, the entire application freezes.  Sometimes, if I wait long enough (> 45s), the application starts reacting again for a short while before freezing up again.

Observations:

* The application hangs as soon as the large cells scroll into view (e. g. scrolling horizontally to the right).
* The application does not hang as long as the cells are not displayed.
* The application does not hang for small amounts of data, it only starts after a certain amount of total data.  For example, displaying three rows might work well, displaying five rows is a little sluggish, displaying seven rows has HeidiSQL freeze for 20s, …

### What did you expect to happen?
No freezes/hangs when copying the data from the cell. 

### HeidiSQL version

12.8.0.6908 (and earlier)

### Database server version

Microsoft SQL Server 2017 (RTM-CU19) (KB4535007) - 14.0.3281.6 (X64)  	Jan 23 2020 21:00:04  	Copyright (C) 2017 Microsoft Corporation 	Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

### Reproduction recipe

Needs specific database to reproduce (large values in columns).

1. `select top 50 id, MailSubject, len(MailDetails)` works well: results display, HeidiSQL not freezing
2. `select top 50 id, MailSubject, MailDetails` produces a result, but makes HeidiSQL hang

**Comment by ilpssun** [comment]
Note that the Microsoft SQL Server Management Studio handles this in a different way: They select only the leftmost *x* bytes from the large cells.  But that also means, I cannot get the entire value into the clipboard.  I don't need to have the value displayed, I just need a way to access the value for transferring it into my editor for further analysis.

**Comment by kudlav** [comment]
Same with `libpq-12.dll`.

When there is visible column with large data (even the data is shortened with elipsis ...) the app became totally unresponsive and is rendered slowly one line per 3 seconds. After rendering all lines, other part of GUI (like logs and toolbars) are re-rendered.
After rendering I can use the GUI except the context menu (right-click) on a row. Right-click on the row freezes the app again and takes a few seconds to display the menu.

The app became unresponsive with each resizing of the window or scrolling the results.

This bug was introduced with some recent update.

**Comment by ansgarbecker** [comment]
Related, if not the same: #2000

**Comment by kudlav** [comment]
The Query tab is affected the same.

**Comment by webloft** [comment]
@ansgarbecker not the same or still have issues with build 6945

**Comment by ansgarbecker** [comment]
@ilpssun can you please take a look with the current nightly build (Help > Check for updates). Perhaps your reported issue was fixed, but I'm unsure.

**Comment by ilpssun** [comment]
@ansgarbecker In build 6945 the situation has definitely improved a lot: Heidi does not freeze/hang completely and it’s definitely a situation that I would call “tolerable”.  It is far from smooth scrolling, however: I can scroll freely without hanging (but the grid does not update after a few lines scroll through), then I have to wait 5–10 seconds for the grid view to update.  But, as I said, it is much better than before.

**Comment by ansgarbecker** [comment]
Thanks for feedback.
