### ISSUE TITLE
Forum registration not working

### ISSUE THREAD

**Issue by raelb** [HeidiSQL/HeidiSQL#2021]
### What where you trying to do?
Register on the forum

### What actually happened?
Looks like the process hung at some point. No email received.

Website shows partial information:
![image](https://github.com/user-attachments/assets/6591d1b9-2797-49b8-9482-84ebe02c01d9)

### What did you expect to happen?
Acknowledge new user registration/provide more information

### HeidiSQL version

12.8

### Database server version

10.6

### Reproduction recipe

I tried in chrome and firefox, same result

**Comment by ansgarbecker** [comment]
Thanks for the hint. Just solved that.

SQL error in the background, since I recently strengthened the anti-spam mechanisms.
