### ISSUE TITLE
Improve performance on export CSV

### ISSUE THREAD

**Issue by guidd** [HeidiSQL/HeidiSQL#2024]
**Is your feature request related to a problem? Please describe.**
When exporting to CSV results from a moderately large query (10k or more records), the time increases exponentially.
I believe some memory management or some type of issue is happening.
First the UI gets very slow to trigger the right popup menu and the export can be very long. It should be more linear
This happens both on mysql and sqlserver (I'm pretty sure it would be the same for all DBs)

**Describe the solution you'd like**
Re-check the export function

**Describe alternatives you've considered**
not tried anything else.

**Additional context**
I'm a developer myself but I don't have any delphi environment anymore. Wish you good luck there, I'll try to check the code just out of curiosity if I find something but I can't make any Merge request with out testing. In any case I'm sure this can be greatly improved. 
I would understand slowness but for much larger records.

**Comment by ansgarbecker** [comment]
Please use the "bug" template next time, not the one for "feature request".

Can you please post the structure of the table you were exporting?

**Comment by evs-xsarus** [comment]
@ansgarbecker I can back this; trying to export some larger tables from Magento 2 like 'sales_order'. Before (like v11, the export was doable, but with 6908, even a 4MB set takes like 5 minutes. This is not workable when I have a ~200MB set.

![image](https://github.com/user-attachments/assets/2403cc2b-9e99-441a-948a-c10bf12316fd)


```sql
SELECT *
FROM
sales_creditmemo sc
WHERE 
sc.created_at >= '2023-09-30 23:00:00' 
AND sc.created_at < '2024-09-30 23:00:00'
```

NB Doesn't seem limited to csv, I tried SQL INSERTs and that takes a long time too.

PS I connect to the database server using a SSH tunnel.

Also tested with https://www.heidisql.com/installers/HeidiSQL_12.8.0.6944_Setup.exe combined with https://www.heidisql.com/builds/heidisql64.r6951.exe . No improvements.

PPS In v11, I saw a counter for downloading the rows, not showing anymore.

**Comment by ansgarbecker** [comment]
I just created that `xsarus_seo_href_lang` table and filled it with 70,000 random rows. Selecting them per query, then exporting with the settings from your screenshot above to a file with placeholders `%host`, `%date` and `%db`. Finished in 2 seconds.
A `sales_flat_order` table from Magento 1.9 (limited to 50,000 rows) takes 1 minute. Quite normal with a 186-columns table.

![gridexport-large-tables](https://github.com/user-attachments/assets/2853a442-3b4b-4028-a5d3-aa4314a8d8f0)

Well, there may be issues with Wine again. Is it Wine on your side?
And I am connecting to a local server, no tunnel.

**Comment by evs-xsarus** [comment]
I'm using Wine indeed.  Not sure if I can test this without Wine.

**Comment by guidd** [comment]
I use the standard client on Windows on my side. (so not Wine related in my
opinion)

**Comment by ansgarbecker** [comment]
On Wine, I would suggest a quick test with clipboard as the target, so HeidiSQL does not write to a file stream. Maybe that file stream is slow.

**Comment by evs-xsarus** [comment]
@ansgarbecker a test with clipboard has the same results. 

* No progress counter is shown.
* CPU usage goes through the roof.
* Finishing the exports takes way too long.

**Comment by ansgarbecker** [comment]
@evs-xsarus ok thanks for your quick testings. Then this is definitely not a filesystem issue.
Could you perhaps make some more tests with smaller results? Let's say you take the above `xsarus_seo_href_lang` table, but with a `LIMIT 20000`, then with 10000 and finally 1000.
Do you have access to a Windows system where you could do the same tests?

**Comment by evs-xsarus** [comment]
Tested on local docker db server

* 235.000 records (~15.5MB) took 28 seconds
* 150.000 records (~7.9MB) took 21 seconds
* 100.000 records (~5.3MB) took 14 seconds
* 50.000 records (~2.6MB) took 7 seconds
* 25.000 records (~1.3MB) took 4 seconds
* 10.000 records (~0.5MB) took 1 seconds
* 1000 records (~0.05MB) took 0 seconds

I do not have access to a Windows system at the moment.

**Comment by evs-xsarus** [comment]
@ansgarbecker I've tested the previous portable 64bit versions with the 235.000 records export:

v12.7 (revision 6850) from 05 May 2024: same results as above
v12.6 (revision 6765) from 05 Nov 2023: export took at most 1 second
v12.5 (revision 6677) from 08 May 2023: export took at most 1 second
v12.3 (revision 6589) from 05 Dec 2022: export took at most 1 second

Seems like the export overhaul introduces these problems.

**Comment by ansgarbecker** [comment]
Ok I see similar results on my Windows system, so performance does _not_ seem to be Wine-related. While the breakdown is not so significant as I thought. 7 seconds for 50.000 rows is not so bad.
I just had a quick look at the changes made to the grid exporter. The only one relevant for CSV was the new checkbox "Remove linebreaks from contents". This of course takes some performance, but in my tests I did not activated it.
So the only remaining possibly relevant change was the VirtualTree update.
Can you please once again update your HeidiSQL build to the current revision 6955, and retest.
That should reveal if bc9693c622406f3338acec4b69a18c7a2939e317 did something relevant here.

**Comment by evs-xsarus** [comment]
Nah, I have the same results when exporting to another format.

I've exported 50.000 rows with build 6955 to both 'Delimited text' and 'HTML table'. Took 7 seconds in both cases.

In build 6765, the export is instant.

Do you have portable editions to test ? The last one using this export interface:

![image](https://github.com/user-attachments/assets/bd1e1f60-4a01-4418-aff1-b6c8cefa7af7)

and the next build so I can compare?

**Comment by ansgarbecker** [comment]
I created portable packages for each release version. Old versions are linked within the "Previous releases" link.

Although you may have found something here, I have to say exporting 235.000 rows in 28 seconds is not the baddest.

I'm not sure if I will find the relevant change - thanks to your tests we know it should be located in the changes between v12.6 and v12.7. But even when I find it, it may be an important thing which otherwise would reintroduce old bugs.

**Comment by evs-xsarus** [comment]
I agree that 28 seconds is ok . Sadly, I have other tables with more records that exported properly before but now take way too  long. Hopefully we'll be able to pinpoint the changes.

Some more testing using the daily build for 235.000 rows:

6832 - 1-2 seconds
6833 - 1-2 seconds
6834 - 3-4 seconds
6835  - not downloadable
6836 - 23 seconds

Hope this helps pinpointing the leak. I find it notable that 6834 already introduced some decreased performance.

**Comment by ansgarbecker** [comment]
Good find! Out of curiosity: how many builds did you download and test? Quite a nasty job ;)

With your hint, I think I got it fixed now. From my tests, I found that reading the earlier used `TGroupBox.ItemIndex` was much faster than the newer `TComboboxEx.ItemIndex` (after the dialog revamp). A simple local variable is now used instead, and speeds it up quite a lot.
Please test with the new build (6956).

**Comment by evs-xsarus** [comment]
Not that many.. binary approach rocks.

With build 6956, the export is instant again. I've tested another query which takes ~15 seconds on build 6833. Seems to be the same with 6956.

Thank you for the fix.

Another thing, is it possible to add a progress counter in the export view? The same as is shown when exporting from the data tab?

**Comment by ansgarbecker** [comment]
Thanks for re-testing.

I see a progress counter while the export dialog is busy, anyway if started from a query result or the data tab grid. Is that the case for you? Probably this is a Wine issue in the end.

**Comment by evs-xsarus** [comment]
I'll do some more testing concerning the progress counter. When needed, I'll create a new ticket. Tnx
