### ISSUE TITLE
Add a window .

### ISSUE THREAD

**Issue by BilalDDD** [HeidiSQL/HeidiSQL#2027]
Hello, I'd like you to be able to add two windows for both queries and data without having to go to another page. 
![feature](https://github.com/user-attachments/assets/85afdc14-b39f-421e-8051-393d53048841)

**Comment by ansgarbecker** [comment]
That's not possible I'm afraid, and not on the todo list.

**Comment by BilalDDD** [comment]
Okay, but what about this? Are you going to add this option?

**Comment by ansgarbecker** [comment]
Sorry I was a bit short tempered.

I wanted to say the window layout is quite fixed, and the idea of adding query editor/result below another one would require too much effort for a nice-to-have feature. Also please note the "Data" tab is a special tab, not comparable to a query tab.
What would come close to your idea, and what probably is doable is to have multiple results of a query tab besides each other, like so:

![grafik](https://github.com/user-attachments/assets/73a22635-daff-475a-bbd9-0e2f19a4ecfa)

**Comment by BilalDDD** [comment]
Ok, nevermind, thank you ;)
