### ISSUE TITLE
 The tree view closes all open branches after deleting an entry

### ISSUE THREAD

**Issue by patrick-fischer-hirschstein** [HeidiSQL/HeidiSQL#2028]
**Is your feature request related to a problem? Please describe.**
The tree view closes all open branches after deleting an entry. I use the grouped view. So removing a view, Removing a view closes everything and I lose focus.

**Describe the solution you'd like**
The tree view retains the open branches and the scroll position does not change.

**Comment by ansgarbecker** [comment]
Duplicate of #16
