### ISSUE TITLE
Deleting several entries (tables, views, ...) at once

### ISSUE THREAD

**Issue by patrick-fischer-hirschstein** [HeidiSQL/HeidiSQL#2029]
**Is your feature request related to a problem? Please describe.**
It's annoying to delete multiple views or tables at once. Each entry must be selected and deleted individually.

**Describe the solution you'd like**
It would be helpful if you could select and delete several entries (tables, views, ...) at once.

**Comment by ansgarbecker** [comment]
Multiple table actions can be used in the "Database" tab, after selecting the tables you want. You may drop, empty or export selected items:

![grafik](https://github.com/user-attachments/assets/58733e11-2b55-4026-a4e7-dfe3b0113fe7)
