### ISSUE TITLE
dialog plugin not working with libmariadb.dll

### ISSUE THREAD

**Issue by charles-001** [HeidiSQL/HeidiSQL#203]
Hello,

I'm using the latest nightly build (9.5.0.5263) and noticed that the dialog plugin isn't working with libmariadb.dll. It works fine when libmysql.dll is used though.

The error I get is: Plugin dialog could not be loaded. The specified module could not be found.

The dialog plugin is in C:\Program Files\HeidiSQL\plugins.

I had to put the dialog plugin before into C:\Program Files\MySQL\MySQL Server 5.6\lib\plugin for it to work with libmysql.dll

Do I need to put the dialog plugin somewhere else new now?

Thanks!

**Comment by vuther** [comment]
Nevermind, I did a trace and found that the plugin needed to be in: C:\Program Files\MariaDB 10.2\lib\plugin
