### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by DavidMrLane** [HeidiSQL/HeidiSQL#2030]
### Description

The installation on Windows fails due to:

                          An error occurred while trying to create a file in the destination directory:
                          **Setup was unable to create the directory "C:\Users\Public\Documents\HeidiSQL".**

It is being blocked by Defender Ransomware protection, I can't disable or add an exception to Protected Folders for that location due to GPO. I can add an exception for an exe after it is blocked, but every time I rerun the installer is extracts the exe to a different tmp file and you go around in circles.
![image](https://github.com/user-attachments/assets/2ffc8498-20d6-44a4-95b7-74e9d3601512)

Is creating a folder in public documents really necessary for the installation?

### HeidiSQL version

12.8.0.6908

### Database server version

-

### Reproduction recipe

Try to install with Windows Defender Ransomware protection turned on

**Comment by ansgarbecker** [comment]
I'm also wondering where this has its cause.
Can you please rerun the installer and watch out which folder is mentioned with the "sample snippets" option?

![grafik](https://github.com/user-attachments/assets/7f58c5cd-ad87-41a1-a36c-bc7d6c727258)

**Comment by ansgarbecker** [comment]
And please post the Windows version here.

**Comment by DavidMrLane** [comment]
That worked, thanks for the tip. When installing via winget (silently) you don't get those options.
