### ISSUE TITLE
Could not load full row data error 

### ISSUE THREAD

**Issue by abanchev** [HeidiSQL/HeidiSQL#2031]
### Description

In some views i cannot doubleclick to see the contents of some rows, i get the "Could not load full row data" error pop up, 
it appears to be random, and i can click on some other rows no problem.

### HeidiSQL version

12.8.0.9638

### Database server version

-

### Reproduction recipe

Just opened a view, and doubleclick on a row to make it editable (to copy data for example)
the data is in the row visible at all times

**Comment by ansgarbecker** [comment]
Can you please watch out at the bottom log panel for the SQL query which triggers that error. There should be some `SELECT ... FROM mytable...`, possibly followed by an SQL error. Screenshots welcome.

**Comment by abanchev** [comment]
Here is an example, i see that the select query is trying to pull the exact row by trying to match all fields, but running the query returns 0 results, so maybe there is an precision issue or something else
![image](https://github.com/user-attachments/assets/d341bc7b-2da4-4cec-8434-76ee1845ff86)
```
SELECT `uid`, `disabled`, `credentials`, `userConfig`, `username`, `platform`, `baseCurrency`, `contractSize`, `leverage`, `drawdown`, `profit_percentage`, `absolute_profit`, `trades`, `openTrades`, `balance`, `equity`, `stopLoss`, `timestamp`, `status` FROM `secure_staging`.`config_strategy` WHERE  `uid`='e4b0b978-836f-44ee-beed-cdaf7a515319' AND `disabled`=0 AND `credentials`='Anton - Medium' AND `userConfig`='{"risk": "medium", "assets": ["EURUSD", "GBPUSD"], "customRisk": 0.39, "advancedStopLoss": {"customStopLoss": 0.85, "stopLossEnabled": false, "useCustomStopLoss": false}, "sailingModeThreshold": 40}' AND `username`='84701960' AND `platform`='METATRADER' AND `baseCurrency`='USD' AND `contractSize`='1000' AND `leverage`='1000' AND `drawdown`=3.29 AND `profit_percentage`=65.22 AND `absolute_profit`=10838.46 AND `trades`=8645 AND `openTrades`=42 AND `balance`='29144.25' AND `equity`=28185.41 AND `stopLoss`='0' AND `timestamp`='2024-10-09 14:50:00.000' AND `status`='OK' LIMIT 1;
```

**Comment by abanchev** [comment]
I did make sure to refresh the results before clicking, so it is not trying to pull stale data, and some rows work well

**Comment by ansgarbecker** [comment]
Doesn't the table have a primary key perhaps?

**Comment by ansgarbecker** [comment]
If that `SELECT` returns 0 rows, HeidiSQL shows that error. Probably like you said due to a precision error in your float fields. The code for that is quite old, so it's definitely not a new issue.
Should only be problematic when entering edit mode, not when just scrolling through the grid.

I see the column value has bold font style, so there _is_ a primary key available. Also, you are filtering by the same uid column. Probably that's a point where I can fix something. But I will need the structure of that view and underlying tables, at least relevant ones.

**Comment by ansgarbecker** [comment]
Thank you. Looks like the `workers` table is missing, probably more. workers is referenced by configs.

**Comment by abanchev** [comment]
I thought it can be ignored but here it is 
```
CREATE TABLE `workers` (
	`uid` VARCHAR(191) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`startedAt` DATETIME(3) NOT NULL DEFAULT (CURRENT_TIMESTAMP(3)),
	PRIMARY KEY (`uid`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
;
INSERT INTO `workers` (`uid`, `startedAt`) VALUES ('50c9acbd-4ca2-4c8c-aa57-5777ee06ccb5', '2024-10-10 14:55:12.900');
```

**Comment by ansgarbecker** [comment]
Thanks, I can now reproduce the error popup.

I played with the view code and found these columns are from `JSON_EXTRACT()` and should be casted to `UNSINED` or `FLOAT`: contractSize, leverage, balance, stopLoss. Example:
```
CAST(json_extract(`c`.`strategyState`, '$.contractSize') AS FLOAT) AS `contractSize`
```
This way, MySQL will match the values, which it does not if they are quoted strings in the `SELECT`.

But there is another issue with the whole JSON string in `userConfig`. Not yet sure why this does not match.

**Comment by ansgarbecker** [comment]
Oh, I should probably modify the WHERE filter with a CAST to JSON:
```
SELECT FROM `config_strategy`
WHERE
    `uid` = 'e4b0b978-836f-44ee-beed-cdaf7a515319'
    ...
    AND `userConfig` = CAST('{"risk": "medium", "assets": ["EURUSD", "GBPUSD"], "customRisk": 0.39, "advancedStopLoss": {"customStopLoss": 0.85, "stopLossEnabled": false, "useCustomStopLoss": false}, "sailingModeThreshold": 40}' AS JSON)
    ....
```
Please do not yet modify your view. Let me test that.

**Comment by ansgarbecker** [comment]
Interestingly, MySQL returns data type JSON from JSON_EXTRACT, although it looks like a normal string. Here's a simple test: first one fails, second one matches:

```
SELECT
    JSON_EXTRACT('{"abc":123}', '$.abc') = '123',
    JSON_UNQUOTE(JSON_EXTRACT('{"abc":123}', '$.abc')) = '123'
    ;
```

**Comment by ansgarbecker** [comment]
Next build should fix it: Grid SELECTs now cast JSON columns to text in its WHERE clause, using `CAST(jsoncol AS CHAR)`. This is also done when you update a row in such views or tables. (Although in this particular case the view tells me _target table is not updatable_, but that's an issue in the view definition). This way, the WHERE clause finds a row and the error popup "could not load full row" should not show up.

**Comment by abanchev** [comment]
good to know, and good job figuring it out
probably it was not something people encounter very often
