### ISSUE TITLE
Add option to export definer on suppoted database objects

### ISSUE THREAD

**Issue by jferrer-xcl** [HeidiSQL/HeidiSQL#2032]
**Is your feature request related to a problem? Please describe.**
When exporting a database object (eg. a trigger or procedure), the output (be it a file, or another database) gets the definer of the connected user. They do not preserve their definers at all, and sometimes it causes problems with database permissions.

**Describe the solution you'd like**
1.- Add a checkbox to the exporting window, so HeidiSQL adds the "DEFINER" clause with the actual value of the migrated object (avoiding creating the objects with a default user without permissions).
2.- Add as a "advanced" feature to set the definer for all supported database objects, so they can be set before being migrated (to a file or another database).

**Describe alternatives you've considered**
1.- Detect the actual definer, check if it exists in the destination database, if so, create the object as-is (most possibly, keeping the definer of the object is what the user wants), else, create the object using the actual user as definer (actual behavior). Control this with a "Preserve definer if possible" checkbox. If unchecked, copy the objects with the connected user as definer, else, try to preserve the definer.

**Additional context**

**Comment by ansgarbecker** [comment]
Isn't that "Remove definer" option the way to go here?

![grafik](https://github.com/user-attachments/assets/0a7247ef-ca46-4fa6-8e50-466e49d4be99)
