### ISSUE TITLE
MariaDB 10.5.9+: REPLICA MONITOR privilege not recognised

### ISSUE THREAD

**Issue by Andrew-Staves-Activ** [HeidiSQL/HeidiSQL#2035]
### Description

MariaDB added the `REPLICA MONITOR` privilege in 10.5.9 (based on [https://mariadb.com/kb/en/grant/#replica-monitor](https://mariadb.com/kb/en/grant/#replica-monitor)). This privilege is not shown in HeidiSQL's "User manager" interface.

It can be applied to a user in HeidiSQL using by executing a `GRANT REPLICA MONITOR [...]` statement in a query tab.

It may be worth mentioning that `SHOW GRANTS FOR [...]` returns the privilege as `SLAVE MONITOR` - which is stated to be an alias for `REPLICA MONITOR` in [https://mariadb.org/wp-content/uploads/2024/10/MariaDBServerKnowledgeBase.pdf](https://mariadb.org/wp-content/uploads/2024/10/MariaDBServerKnowledgeBase.pdf) (though does not appear to be mentioned on [https://mariadb.com/kb/en/grant/#replica-monitor](https://mariadb.com/kb/en/grant/#replica-monitor)).

### HeidiSQL version

12.8.0.6941

### Database server version

MariaDB 10.11.4

### Reproduction recipe

1. In HeidiSQL, connect to a server running MariaDB 10.5.9+
2. Open the "User manager" interface
3. Select a user (on the left)
4. Expand "Global privileges" (under "Allow access to:" on the right)
5. Observe that `REPLICA MONITOR` is not shown as an item in the list

**Comment by ansgarbecker** [comment]
Next build adds the new `REPLICA MONITOR` privilege on MariaDB 10.5.9+.

**Comment by ansgarbecker** [comment]
Yes I just saw the same here.
Next build prefers the `SLAVE MONITOR` phrasing over `REPLICA MONITOR`, which then stays checked after saving:

![grafik](https://github.com/user-attachments/assets/537cd4ee-e268-40d7-9b53-cadaed279077)

**Comment by Andrew-Staves-Activ** [comment]
Sounds good! Thanks again :beers:
