### ISSUE TITLE
Unreadable text on error boxes with dark themes

### ISSUE THREAD

**Issue by NorseJedi** [HeidiSQL/HeidiSQL#2036]
### Description

When using a dark theme (I've tried most of them), several errors and warnings that pop up are almost or completely unreadable (depending on the theme) due to the text being black and the background being black or dark. The text can't be highlighted to make it readable either.

The issue is present regardless of the Windows theme in use (Light or Dark). I've tried both Windows 11 Pro and Windows Server 2022 Standard.

Example with `Carbon` theme:
![Carbon](https://github.com/user-attachments/assets/a6aa718e-b8d8-4cc0-be92-d5b10129d137)

Example with `Windows10 Dark` theme:
![Windows 10 Dark](https://github.com/user-attachments/assets/6c3e49ae-8bb7-4159-b212-13d168d85bec)

### HeidiSQL version

12.8.0.6908

### Database server version

-

### Reproduction recipe

The warning in the screenshots was produced like this:

Add a new connection
Select Network Type: `Microsoft SQL Server (TCP/IP)`
Select Library: `SQLOLEDB`
Click the arrow-down in the `Databases` select-box

**Comment by ansgarbecker** [comment]
Confirmed, for the warning dialog you show above. Other warnings don't seem to have that issue:

![grafik](https://github.com/user-attachments/assets/0600e799-3a1f-4988-a635-1d31b71c29f6)

Probably this has to do with parsing the text for HTML anchors, due to `tfEnableHyperlinks`. Will check that.

**Comment by ansgarbecker** [comment]
Indeed, if the text does not contain HTML markup, it has correct font color:

![grafik](https://github.com/user-attachments/assets/18983483-3044-4167-ad0f-234e5c28ea5a)

Probably it's ok to disable clickable anchors if the selected theme is a dark one. I don't know how to fix that otherwise.

**Comment by ansgarbecker** [comment]
Next build has the mentioned workaround.

Additionally, I posted an update in the vcl-styles-utils project, see above mention.
