### ISSUE TITLE
Image preview needs two clicks on BLOB instead of one

### ISSUE THREAD

**Issue by start780** [HeidiSQL/HeidiSQL#2038]
### Description

Do the image preview of a blob column AFTER the reload of the select row for editing, when a table has a primary key.

### HeidiSQL version

10

### Database server version

-

### Reproduction recipe

Select an image blob column in a table with a primary key.
Preview is not displayed at first click.
(But preview is displayed at second click.)

**Comment by ansgarbecker** [comment]
Next build fixes this issue, caused by a wrong field length after loading a full row.
