### ISSUE TITLE
Crash when closing query tab while grid cell editor is active

### ISSUE THREAD

**Issue by CraftedRO** [HeidiSQL/HeidiSQL#2040]
### Description

Heidi crashed ugly while closing a temporary query tab.

![Captură de ecran 2024-10-23 181228](https://github.com/user-attachments/assets/9df58891-5bbd-4b11-9815-fa2fe4820dce)

### HeidiSQL version

12.8.0.6945 (.zip one)

### Database server version

MariaDB 10.4.32

### Reproduction recipe

not able to reproduce it again but I multiple (9) temporary query tabs opened and I just closed the last one # 9
containing smth like:
```sql
--
SELECT * FROM `creature_addon` WHERE `guid` IN (SELECT `guid` FROM `creature` WHERE `id` IN (7107,7108));
```

### Error/Backtrace

```shell
https://gist.github.com/CraftedRO/882b440ef69c7fa9bae8b37e4802ec54
```

**Comment by CraftedRO** [comment]
yes it is correct

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.

**Comment by CraftedRO** [comment]
hmm now after update I got other strange crash while closing a query tab after I executed it

[bugreport.txt](https://github.com/user-attachments/files/17598156/bugreport.txt)

**Comment by CraftedRO** [comment]
looks like while closing any tab now it crash.

**Comment by ansgarbecker** [comment]
Yes, my fault. Crash happens when closing tab with no result grid. Next build also fixes that new crash.
