### ISSUE TITLE
Exporting grid rows as a SQL statement should not include currency symbol for money datatype

### ISSUE THREAD

**Issue by foxip** [HeidiSQL/HeidiSQL#2041]
### Description

If I export a record as a INSERT statement, it will include the currency symbol in the SQL statement as follows:

`INSERT INTO "MyTable" VALUES (580280, € 0,00);`

It should be:

`INSERT INTO "MyTable" VALUES (580280, 0.00);`

### HeidiSQL version

12.8.0.6945

### Database server version

Postgresql 16

### Reproduction recipe

CREATE TABLE "MyTable" (
	"Id" INTEGER NOT NULL,
	"Credits" MONEY NOT NULL DEFAULT (0.0)::money
)
INSERT INTO "MyTable" VALUES (580280, 0.00);

**Comment by ansgarbecker** [comment]
Strange thing, libpq.dll includes the currency symbol in the value returned by [PQgetvalue](https://www.postgresql.org/docs/current/libpq-exec.html#LIBPQ-PQGETVALUE).

**Comment by ansgarbecker** [comment]
[PG's documentation](https://www.postgresql.org/docs/8.4/datatype-money.html) suggests to replace locale currency symbol and decimal separator to convert values to numbers:

    SELECT regexp_replace(mycolumn::money::text, '[$,]', '', 'g')::numeric FROM mytable;

But this depends on the client's (or the server's?) system locale. On my German server + client I would have to remove a different currency symbol and a different thousands separator, plus even replace the decimal separator (comma in Germany):

    SELECT REPLACE(regexp_replace(credits::TEXT, '[€.]', '', 'g'), ',', '.')::numeric FROM mytable;

I can't believe this is the only way. There must be a simpler way to do that, without checking the system locale.

**Comment by ansgarbecker** [comment]
Btw, the PostgreSQL's Wiki and mailing lists recommends not to use the money types:
* https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_money
* https://www.postgresql.org/message-id/flat/20130328092819.237c0106@imp#20130328092819.237c0106@imp

**Comment by ansgarbecker** [comment]
That money type is really full of shit. I was just able to convert it locally in HeidiSQL to a numeric float value. But when using such values in a WHERE clause, the server throws such an error:
> Operator does not exist: money = numeric

I think it would be an idea to quote MONEY columns like TEXT columns. That way, this issue you reported was solved through having quotes around a value (e.g. `'€ 0,00'`). Also, WHERE clauses would not throw the mentioned _Operator does not exist_ error:

    SELECT * FROM mytable WHERE credits = '0,00 €';

Other or even better ideas?

**Comment by foxip** [comment]
Yes, having quotes around the value would solve it.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.
