### ISSUE TITLE
FATAL:  password authentication failed for user [Docker postgres]

### ISSUE THREAD

**Issue by chrisonoo** [HeidiSQL/HeidiSQL#2043]
### Description

Failure to properly connect to the PostgreSQL database running on Docker.

### HeidiSQL version

12.8.0.6908

### Database server version

Docker Postgres 16.4

### Reproduction recipe

Docker started with the command:

```bash
docker run --name 'postgres-database' \
  -e POSTGRES_USER='dev' \
  -e POSTGRES_PASSWORD='Dev12' \
  -e POSTGRES_DB='postgres' \
  -p 5432:5432 \
  -v postgres-data:/var/lib/postgresql/data \
  --restart always \
  -d postgres:16.4
```

Authentication error, trying all libraries, missing the one suggested in the message `libpq.dll`.

![image](https://github.com/user-attachments/assets/9d267520-50b9-4e78-9215-a71333ca9e3c)

The `MariaDB` and `sqlite` databases works properly. Tested on localhost and 127.0.0.1

### Error/Backtrace

```shell
2024-10-26 17:41:25 2024-10-26 15:41:25.077 UTC [118] FATAL:  password authentication failed for user "dev"
2024-10-26 17:41:25 2024-10-26 15:41:25.077 UTC [118] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"

Changing to md5 doesn't help

2024-10-26 18:10:12 2024-10-26 16:10:12.172 UTC [39] FATAL:  password authentication failed for user "dev"
2024-10-26 18:10:12 2024-10-26 16:10:12.172 UTC [39] DETAIL:  Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all md5"
```

**Comment by ansgarbecker** [comment]
Do you really think this is an issue in HeidiSQL itself?
You could try other clients to track down the error.

**Comment by chrisonoo** [comment]
> Do you really think this is an issue in HeidiSQL itself? You could try other clients to track down the error.

Thank you for your reply @ansgarbecker  I also use DataGrip and the connection to the container was correct there. However, it turned out that the problem was with the container, or rather with the volume. Deleting the container does not delete the volume and I kept connecting to the same one. Only after deleting the volume and the container and restarting everything started working.

**Comment by ansgarbecker** [comment]
Thank you for having a deeper look and for your feedback!
