### ISSUE TITLE
Using the STATUS command fails in HeidiSql

### ISSUE THREAD

**Issue by digdilem-work** [HeidiSQL/HeidiSQL#2045]
### Description

MariaDb 10.11+ (at least) has the command; "STATUS" which works with and without a trailing ';' 

If I run this command on a MariaDb server locally or remotely using the CLI mysql client it responds with some useful info:

```
MariaDB [(none)]> status
--------------
mysql  Ver 15.1 Distrib 10.11.9-MariaDB, for Linux (x86_64) using  EditLine wrapper

Connection id:          6
Current database:
Current user:           redacted_username@redacted_hostname 
SSL:                    Not in use
Current pager:          stdout
Using outfile:          ''
Using delimiter:        ;
Server:                 MariaDB
Server version:         10.11.9-MariaDB-log MariaDB Server
Protocol version:       10
Connection:             redacted_hostname via TCP/IP
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8mb3
Conn.  characterset:    utf8mb3
TCP port:               3306
Uptime:                 41 min 14 sec

Threads: 2  Questions: 158  Slow queries: 0  Opens: 548  Open tables: 541  Queries per second avg: 0.063
```

However, if I run STATUS as a standard query in HeidiSql using the same user, with or without the trailing ;, it errors with

![image](https://github.com/user-attachments/assets/53c34084-cdf8-41a8-b8d9-52b7c3b77c55)

Conjecture:
That error looks to be coming from the server rather than internally from Heidi. Is Heidi doing something odd to the query before it sends it that's confusing the server?

The Heidi log shows it's appending a semicolon, which should still be fine, but still fails.

![image](https://github.com/user-attachments/assets/f9317169-4a1f-4bca-ae99-be41324deada)

### HeidiSQL version

12.8.0.6908

### Database server version

MariaDb 10.11

### Reproduction recipe

As above

**Comment by ansgarbecker** [comment]
No, `STATUS` is not a valid query. It's a command which the MariaDB/MySQL CLI understands, but not as an SQL query.

Probably comparable to what HeidiSQL shows when you hover over the server version in the status bar:

![grafik](https://github.com/user-attachments/assets/a310c250-4aa6-49b7-a5a6-1bdedac0314e)

**Comment by ansgarbecker** [comment]
Note there are some more CLI-only commands documented: https://mariadb.com/kb/en/mariadb-command-line-client/#mariadb-commands

**Comment by digdilem-work** [comment]
@ansgarbecker - thank you for the clear explanation - TIL!  Also useful to note the hover pane, I hadn't noticed that before.

Obviously not a Heidi issue as I had assumed, so closing ticket. 

Regards
