### ISSUE TITLE
Postgresql SSLmode 

### ISSUE THREAD

**Issue by xsakim** [HeidiSQL/HeidiSQL#2046]
I am currently working in an environment where the SSL mode of a PostgreSQL DBMS is enabled. Since this is a DBaaS product hosted in a cloud environment, it is not possible to disable SSL communication settings.

Although HeidiSQL provides an "ssluse" checkbox for SSL functionality, I have noticed that even when this checkbox is not selected, the actual protocol still uses TLS v1.3. Upon capturing network traffic, I confirmed that packets are being transmitted using TLS v1.3.

In my current environment, I need to use the TCP/IP protocol without SSL, but HeidiSQL does not appear to support this functionality. Other database tools offer an option to disable SSL mode, which makes them usable in my scenario.

Could you please consider supporting this feature in HeidiSQL, allowing users to disable SSL mode and use the TCP/IP protocol? Your support on this matter would be greatly appreciated.

**Comment by ansgarbecker** [comment]
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLMODE

**Comment by ansgarbecker** [comment]
As pointed out in the forum, HeidiSQL currently does not set `sslmode` if the "Use SSL" checkbox is not checked. In that case libpq uses the default: `sslmode=prefer`, which is documented as "_first try an SSL connection; if that fails, try a non-SSL connection_".
In terms of security, this is a good thing. But yes, disabling the SSL checkbox could also tell HeidiSQL to set `sslmode=disable`. But...

> In my current environment, I need to use the TCP/IP protocol without SSL ...

For what reason?

**Comment by xsakim** [comment]
When using SSL mode, there is a phenomenon in which packets cannot be controlled in certain DB security solutions, so the function requires SSL disable.

**Comment by ansgarbecker** [comment]
Next build now supports 4 different SSL verification levels on the "SSL" tab:

![grafik](https://github.com/user-attachments/assets/9494a6e1-f5de-4044-9e55-6f68e1873e2f)

So we have a way now to disable SSL.

By the way, that verification drop-down was recently introduced for MySQL/MariaDB connections in #1972 . Up to now, the setting did not affect a PostgreSQL connection. Next builds will. Would be nice if you could test and report back if that works for you. I don't have an SSL setup in my local PostgreSQL server.

**Comment by xsakim** [comment]
thanks
once version 12.9 is downloaded, we’ll go ahead and test it

**Comment by ansgarbecker** [comment]
Anyone has a tipp for me how to easily set up SSL in a local PostgreSQL server on Windows? I have both v15 and v17 installed, and would like to test whether the latest library cleanup still allows SSL based connections.

**Comment by piggybox** [comment]
As someone new to HeidiSQL, this menu looks very confusing

<img width="1466" height="368" alt="Image" src="https://github.com/user-attachments/assets/991deca5-347e-4883-8bd2-ece77e4396c6" />

**Comment by ansgarbecker** [comment]
@piggybox yes the "No verification" item should only display once, probably a bug. Please make sure you have the latest HeidiSQL release. If the issue persists please file a new bug report here.
