### ISSUE TITLE
Stop ordering by text

### ISSUE THREAD

**Issue by Simone-98** [HeidiSQL/HeidiSQL#2048]
**Is your feature request related to a problem? Please describe.**
i'm using HeidiSql to view custom table of logs with a column of big json arrays saved, sometimes i need to see what is in the latest row (the upper), but if i accidentally click on the column name Heeidisql start sorting by it, and in a big table (270MiB) it is too heavy and i need to close heidi (if i don't close it took 2-3 minutes).
But when i restart heidi and i try to reopen the table it keep my sorting filter and restart sorting.

**Describe the solution you'd like**
I think there are many way to resolve:

1. you can just stop sorting by text column and users can active by settings 
2. before start sorting, if text ask with alert to confirm action
3. possibility to check a column as Not Sortable (with right click on column)

**Describe alternatives you've considered**
You can check if table too big (like over 100Mib), and if column is text (not varchar, only big text) before ask user to acceprt sorting

**Additional context**
![Screenshot (445)](https://github.com/user-attachments/assets/0be7f69a-b67e-4140-b584-a8e35478c24d)
feature request here.

**Comment by ansgarbecker** [comment]
There are already two helpful things you might not have noticed:
1. disable auto-applied filters across sessions, in Tools > Preferences > Data editors > "_Remember filters, sorting and column selection across sessions_"
2. To delete the previous filter for one table, you can right-click the table while the "Table" tab is active (note, don't click the "Data" tab). Then click "_Clear data tab filter and sort order_":

![grafik](https://github.com/user-attachments/assets/3ee53d04-0ceb-4435-94ad-0e57902200a6)

**Comment by Simone-98** [comment]
ah perfect,
this help me finally reopen the table,
i close the issue as no planned because i think there is nothings to fix
thanks
