### ISSUE TITLE
SSH section suddenly disabled

### ISSUE THREAD

**Issue by kosuodhmwa** [HeidiSQL/HeidiSQL#2049]
### Description

I don't know since which version? (I've noticed it today after updating on must current version)

![image](https://github.com/user-attachments/assets/e9187b67-276f-412c-b1b1-5cf4aabb32a1)

### HeidiSQL version

12.8.0.6956

### Database server version

Not relevant

### Reproduction recipe

I don't know since which version? (I've noticed it today after updating on must current version)

### Error/Backtrace

```shell
I don't know since which version? (I've noticed it today after updating on must current version)
```

**Comment by ansgarbecker** [comment]
I guess you have selected the wrong network type. Select the SSH-enabled network type, which enables the SSH checkbox:

![grafik](https://github.com/user-attachments/assets/d9ea95da-53d3-433d-9e16-319a9f7e9731)

**Comment by kosuodhmwa** [comment]
thank you very much
