### ISSUE TITLE
sync database “apply” button cannot be clicked

### ISSUE THREAD

**Issue by caozk929** [HeidiSQL/HeidiSQL#2057]
### Description

sync database “apply” button cannot be clicked

### HeidiSQL version

12.8.0.6958 (64 Bit)

### Database server version

MySQL 8.0.22

### Reproduction recipe

sync database

**Comment by caozk929** [comment]
![image](https://github.com/user-attachments/assets/7ad769d2-d9f2-4b79-aea6-5473f2d6f622)

**Comment by ansgarbecker** [comment]
How did you manage to show that dialog? It's a never finished feature. Using that is like using a pre-alpha version of something. I will remove that from the shortcuts list so it's gone.

**Comment by ansgarbecker** [comment]
Again, please don't use that dialog. It's a never finished feature.

See the original old ticket on Sourceforge: https://sourceforge.net/p/heidisql/tickets/1289/
