### ISSUE TITLE
PostgreSQL CONCAT not highlighting

### ISSUE THREAD

**Issue by RichardKanshen** [HeidiSQL/HeidiSQL#2058]
### Description

In PostgreSQL, 'CONCAT' is not being properly highlighted. 'C' is being highlighted for seemingly no reason, possibly related.
![image](https://github.com/user-attachments/assets/fdc18ff9-17c6-43b9-9187-efd82208341c)

### HeidiSQL version

12.8.0.6908

### Database server version

PostgreSQL 12.4

### Reproduction recipe

1. Start up a PostgreSQL server, and connect to it via HeidiSQL.
2. Create a new prompt, containing the keywords CONCAT, and just the letter c.
![image](https://github.com/user-attachments/assets/f62f3d82-6343-4b43-b438-6a0f2f554b24)

**Comment by ansgarbecker** [comment]
Yes, the `functions-postgresql.ini` is very incomplete as it seems. I'm just trying to find a somehow complete listing of internal PG functions, including a short description of what they do. I should probably parse the [official documentation](https://www.postgresql.org/docs/13/functions-string.html) to be most reliable here.
Feel free to help out here :)

**Comment by ansgarbecker** [comment]
<ins>Many more</ins> PG functions coming up in the next installer respectively `functions-postgresql.ini`.

![grafik](https://github.com/user-attachments/assets/b948b089-c221-4cea-bc9a-91951e476bc0)

Please note this now also provides some overloaded function names with the same name but different parameter declaration, of which exist some in PG:

![grafik](https://github.com/user-attachments/assets/a14f30ac-3c3c-472e-8a6c-16bb1abf970f)

Also please note, the new .ini file gets compiled into the next installer, available on the HeidiSQL download page in the nightly builds section. Updating HeidiSQL to the new build per auto-updater does not get you the update in this case.
