### ISSUE TITLE
cant see postgres db after create

### ISSUE THREAD

**Issue by kosuodhmwa** [HeidiSQL/HeidiSQL#2059]
### Description

cant see postgres db after create, but when try re-create i see already exists 

### HeidiSQL version

current version

### Database server version

current version

### Reproduction recipe

see postgres db after create

**Comment by kosuodhmwa** [comment]
db name should be 'nbxplorer' 

![image](https://github.com/user-attachments/assets/9a1c0f23-af2f-4a9c-82bd-ad41a18fe2e2)

thx for feedback :-)

**Comment by kosuodhmwa** [comment]
hmmm... but i see it in connection explorer and when i chose it i can connect with

**Comment by kosuodhmwa** [comment]
![image](https://github.com/user-attachments/assets/375da570-7c97-4bd3-8792-f6f8019ad9a2)

**Comment by kosuodhmwa** [comment]
but same result at the end: can see any dbs called 'nbxplorer' here 
![image](https://github.com/user-attachments/assets/147049cf-0c34-4914-914a-48480c89121d)

**Comment by kosuodhmwa** [comment]
hmmm... seems to be a lil bit different approach then MySQL - now i saw it. so problem solved

**Comment by NotWorkingCode** [comment]
@kosuodhmwa Could you share the solution? I ran into the same thing.

**Comment by kosuodhmwa** [comment]
It's by HeidiSQL design i.m.o., so you will not see them* AFTER you logged in into a (1) database provided by HeidiSQL Postgres db connection profil...

<img width="1429" height="1033" alt="Image" src="https://github.com/user-attachments/assets/3f0c12da-a794-45ff-85c2-28eb4bd9acfd" />

...different to MySQL/MariaDB. 

So you will need to define each Postgres Connection profile for each Postgres DB (1 profile for every DB - separately). Then you will see it's tables, views, SPs, triggers - etc. But not the database "top level" entry. 

**PS:** Please correct me if i'm wrong, **@ansgarbecker...**

**Comment by kosuodhmwa** [comment]
So: On MySQL/MariaDB, if you have same user login / permissions for MANY databases, you can switch between them after you logged in. But not on Postgres.
