### ISSUE TITLE
fast copy excel data to Heidisql

### ISSUE THREAD

**Issue by MrHuang2024** [HeidiSQL/HeidiSQL#2060]
Hello, there is a very practical feature, which is to select data in Excel, copy it, and then paste it in Heidisql to insert the data into the database. Because Excel to CSV file data is sometimes lost, and the import function is not very convenient. Do you have a plan for this feature?

**Comment by ansgarbecker** [comment]
There are too many pitfalls in such a process, for instance the number of columns must match to those in the database, and the data types need to accept the Excel values.
In the end this would be a Microsoft-only feature, and I'm not paid by them. Other spread sheet calculations like Libre Office Calc and Google Docs are likely using a different clipboard format than Excel.
Please use the CSV import feature where you set up the control characters and columns.
