### ISSUE TITLE
Optimized object order on database export

### ISSUE THREAD

**Issue by HA1024** [HeidiSQL/HeidiSQL#2061]
_Feature:_ 
> Allow optimized export order of MySQL database objects (priorize tables).

_Problem:_
> Export of multiple databases **with recreation** i.e. from one server to another one fails if there exists a procedure, view or trigger that depends on a database object that does not exists (forward reference). This, for example, may happen if a view references tables of multiple database.

_Solution:_ 
1. Delete and create all target databases if requested.
2. Create/export the content of all **tables** to all target databases as next step
3. Continue with **functions** and other object types (except of triggers, events).
4. Export **triggers** of all databases.
5. Export **events** of all databases always as last the step.

_Alternatives:_
A) Export the objects in the order of their checkbox selection.

B) Do the export manually in multiple steps:
1. Export all tables of all databases and **select** the option to delete the target databases
2. Select all databases and uncheck already exported tables **and** disale the option that deletes the target databses,

**Comment by ansgarbecker** [comment]
Please retest that all on your server, that should already work since several years now. If it does not work please post more details about server versions.

For view dependencies there's already a logic in the exporter, which creates dummy/replacement tables first, then create all tables, then drop the dummy tables and create the final views. (orange background in the screenshot below). 

For procedures there's no such replacement logic, but I don't see any error when a procedure is exported before a dependent table. See the yellow lines in the screenshot.

![grafik](https://github.com/user-attachments/assets/70b39fa5-b584-430d-bec4-f9771541e22d)

**Comment by HA1024** [comment]
Dear Ansgar Becker,

 

Here you get more details to reproduce the issue:

1.	created two sample databases and cross referencing views manually.
2.	Try to copy the two databases from localhost to a second physical server (192.168.100.250 in my case)

 

Database and table definition:

-- --------------------------------------------------------

-- Host:                         127.0.0.1

-- Server-Version:               8.0.26-commercial - MySQL Enterprise Server - Commercial

-- Server-Betriebssystem:        Win64

-- HeidiSQL Version:             12.8.0.6975

-- --------------------------------------------------------

 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;

/*!40101 SET NAMES utf8 */;

/*!50503 SET NAMES utf8mb4 */;

/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;

/*!40103 SET TIME_ZONE='+00:00' */;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

 

 

-- Exportiere Datenbank-Struktur für testdb1

CREATE DATABASE IF NOT EXISTS `testdb1` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `testdb1`;

 

-- Exportiere Struktur von Tabelle testdb1.t1

CREATE TABLE IF NOT EXISTS `t1` (

  `id` int DEFAULT NULL,

  `value1` int DEFAULT NULL,

  `Value2` int DEFAULT NULL

) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

 

-- Exportiere Daten aus Tabelle testdb1.t1: ~3 rows (ungefähr)

REPLACE INTO `t1` (`id`, `value1`, `Value2`) VALUES

   (1, 2, 3),

   (2, 3, 4),

   (3, 4, 5);

 

 

-- Exportiere Datenbank-Struktur für testdb2

CREATE DATABASE IF NOT EXISTS `testdb2` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `testdb2`;

 

-- Exportiere Struktur von Tabelle testdb2.t1

CREATE TABLE IF NOT EXISTS `t1` (

  `id` int DEFAULT NULL,

  `value1` int DEFAULT NULL,

  `Value2` int DEFAULT NULL

) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

 

-- Exportiere Daten aus Tabelle testdb2.t1: ~3 rows (ungefähr)

REPLACE INTO `t1` (`id`, `value1`, `Value2`) VALUES

   (1, 2, 3),

   (2, 3, 4),

   (3, 4, 5);

 

/*!40103 SET ***@***.***_TIME_ZONE, 'system') */;

/*!40101 SET ***@***.***_SQL_MODE, '') */;

/*!40014 SET ***@***.***_FOREIGN_KEY_CHECKS, 1) */;

/*!40101 SET ***@***.***_CHARACTER_SET_CLIENT */;

/*!40111 SET ***@***.***_SQL_NOTES, 1) */;  

 

View definition:

-- --------------------------------------------------------

-- Host:                         127.0.0.1

-- Server-Version:               8.0.26-commercial - MySQL Enterprise Server - Commercial

-- Server-Betriebssystem:        Win64

-- HeidiSQL Version:             12.8.0.6975

-- --------------------------------------------------------

 

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;

/*!40101 SET NAMES utf8 */;

/*!50503 SET NAMES utf8mb4 */;

/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;

/*!40103 SET TIME_ZONE='+00:00' */;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

 

 

-- Exportiere Datenbank-Struktur für testdb1

CREATE DATABASE IF NOT EXISTS `testdb1` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `testdb1`;

 

-- Exportiere Struktur von View testdb1.v1

-- Erstelle temporäre Tabelle, um View-Abhängigkeiten zuvorzukommen

CREATE TABLE `v1` (

   `id` INT NULL,

   `sum` BIGINT NULL

) ENGINE=MyISAM;

 

-- Entferne temporäre Tabelle und erstelle die eigentliche View

DROP TABLE IF EXISTS `v1`;

CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v1` AS select `a`.`id` AS `id`,(((`a`.`value1` + `a`.`Value2`) + `b`.`value1`) + `b`.`Value2`) AS `sum` from (`t1` `a` join `testdb2`.`t1` `b` on((`a`.`id` = `b`.`id`)))

;

 

 

-- Exportiere Datenbank-Struktur für testdb2

CREATE DATABASE IF NOT EXISTS `testdb2` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `testdb2`;

 

-- Exportiere Struktur von View testdb2.v2

-- Erstelle temporäre Tabelle, um View-Abhängigkeiten zuvorzukommen

CREATE TABLE `v2` (

   `id` INT NULL,

   `sum` BIGINT NULL

) ENGINE=MyISAM;

 

-- Entferne temporäre Tabelle und erstelle die eigentliche View

DROP TABLE IF EXISTS `v2`;

CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `testdb2`.`v2` AS select `a`.`id` AS `id`,(((`a`.`value1` + `a`.`Value2`) + `b`.`value1`) + `b`.`Value2`) AS `sum` from (`testdb2`.`t1` `a` join `testdb2`.`t1` `b` on((`a`.`id` = `b`.`id`)))

;

 

/*!40103 SET ***@***.***_TIME_ZONE, 'system') */;

/*!40101 SET ***@***.***_SQL_MODE, '') */;

/*!40014 SET ***@***.***_FOREIGN_KEY_CHECKS, 1) */;

/*!40101 SET ***@***.***_CHARACTER_SET_CLIENT */;

/*!40111 SET ***@***.***_SQL_NOTES, 1) */;

 

Copy the both databases from localhost to a second server:



 



 

*	I split the creation scripts into two steps – the same way as my suggested solution: 
- Tables first
- depending objects later…

 

Thank you very much for the very fast response – I hope this helps you.

 

Best Regards & Frohe Weihnachten 😉

Heiko Auerswald

 

 

IBA Software (Ing.-Büro)

Dipl.-Inf. (TU) Heiko Auerswald

Huttenstraße 3

01309 Dresden

 

Tel +49 351 2633.173

Fax +49 351 2633.175

E-Mail  ***@***.***> ***@***.***

 

 

Von: Ansgar Becker ***@***.***> 
Gesendet: Freitag, 20. Dezember 2024 17:05
An: HeidiSQL/HeidiSQL ***@***.***>
Cc: HA1024 ***@***.***>; Author ***@***.***>
Betreff: Re: [HeidiSQL/HeidiSQL] Optimized object order on database export (Issue #2061)

 

Please retest that all on your server, that should already work since several years now. If it does not work please post more details about server versions.

For view dependencies there's already a logic in the exporter, which creates dummy/replacement tables first, then create all tables, then drop the dummy tables and create the final views. (orange background in the screenshot below).

For procedures there's no such replacement logic, but I don't see any error when a procedure is exported before a dependent table. See the yellow lines in the screenshot.

 <https://github.com/user-attachments/assets/70b39fa5-b584-430d-bec4-f9771541e22d> grafik.png (view on web)

**Comment by ansgarbecker** [comment]
@HA1024 please attach the SQL export in one or two files here again, don't send them per mail as a reply. The code is lost somewhere behind a link. Thank you.

**Comment by HA1024** [comment]
Dear Ansgar Becker,

Here you get more details to reproduce the issue:
1)	created two sample databases and cross referencing views manually.
2)	Try to copy the two databases from localhost to a second physical server (192.168.100.250 in my case)

**Database and table definition:**
-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server-Version:               8.0.26-commercial - MySQL Enterprise Server - Commercial
-- Server-Betriebssystem:        Win64
-- HeidiSQL Version:             12.8.0.6975
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Exportiere Datenbank-Struktur für testdb1
CREATE DATABASE IF NOT EXISTS `testdb1` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `testdb1`;

-- Exportiere Struktur von Tabelle testdb1.t1
CREATE TABLE IF NOT EXISTS `t1` (
  `id` int DEFAULT NULL,
  `value1` int DEFAULT NULL,
  `Value2` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

-- Exportiere Daten aus Tabelle testdb1.t1: ~3 rows (ungefähr)
REPLACE INTO `t1` (`id`, `value1`, `Value2`) VALUES
   (1, 2, 3),
   (2, 3, 4),
   (3, 4, 5);


-- Exportiere Datenbank-Struktur für testdb2
CREATE DATABASE IF NOT EXISTS `testdb2` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `testdb2`;

-- Exportiere Struktur von Tabelle testdb2.t1
CREATE TABLE IF NOT EXISTS `t1` (
  `id` int DEFAULT NULL,
  `value1` int DEFAULT NULL,
  `Value2` int DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;

-- Exportiere Daten aus Tabelle testdb2.t1: ~3 rows (ungefähr)
REPLACE INTO `t1` (`id`, `value1`, `Value2`) VALUES
   (1, 2, 3),
   (2, 3, 4),
   (3, 4, 5);

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;  

View definition:
-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server-Version:               8.0.26-commercial - MySQL Enterprise Server - Commercial
-- Server-Betriebssystem:        Win64
-- HeidiSQL Version:             12.8.0.6975
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Exportiere Datenbank-Struktur für testdb1
CREATE DATABASE IF NOT EXISTS `testdb1` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `testdb1`;

-- Exportiere Struktur von View testdb1.v1
-- Erstelle temporäre Tabelle, um View-Abhängigkeiten zuvorzukommen
CREATE TABLE `v1` (
   `id` INT NULL,
   `sum` BIGINT NULL
) ENGINE=MyISAM;

-- Entferne temporäre Tabelle und erstelle die eigentliche View
DROP TABLE IF EXISTS `v1`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `v1` AS select `a`.`id` AS `id`,(((`a`.`value1` + `a`.`Value2`) + `b`.`value1`) + `b`.`Value2`) AS `sum` from (`t1` `a` join `testdb2`.`t1` `b` on((`a`.`id` = `b`.`id`)))
;


-- Exportiere Datenbank-Struktur für testdb2
CREATE DATABASE IF NOT EXISTS `testdb2` /*!40100 DEFAULT CHARACTER SET latin1 COLLATE latin1_general_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `testdb2`;

-- Exportiere Struktur von View testdb2.v2
-- Erstelle temporäre Tabelle, um View-Abhängigkeiten zuvorzukommen
CREATE TABLE `v2` (
   `id` INT NULL,
   `sum` BIGINT NULL
) ENGINE=MyISAM;

-- Entferne temporäre Tabelle und erstelle die eigentliche View
DROP TABLE IF EXISTS `v2`;
CREATE ALGORITHM=UNDEFINED SQL SECURITY DEFINER VIEW `testdb2`.`v2` AS select `a`.`id` AS `id`,(((`a`.`value1` + `a`.`Value2`) + `b`.`value1`) + `b`.`Value2`) AS `sum` from (`testdb2`.`t1` `a` join `testdb2`.`t1` `b` on((`a`.`id` = `b`.`id`)))
;

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;

**Copy the both databases from localhost to a second server:**
![screenshot](https://github.com/user-attachments/assets/961d4616-a0a4-4629-9ff9-8c5aa1aae169)
![Log](https://github.com/user-attachments/assets/ef76339f-903c-4f00-a203-9fc05f0bb4ef)

-->	I split the creation scripts into two steps – the same way as my suggested solution: 
- Tables first
- depending objects later…

Thank you very much for the very fast response – I hope this helps you.

Best Regards & Frohe Weihnachten 😉
Heiko

**Comment by ansgarbecker** [comment]
Ok I think now I got what you mean. You have a view in database "x" referring a table in database "y". Yes, that's unsupported by HeidiSQL. I think the user is responsible for importing things in the right order in such cases. HeidiSQL does not support such cross dependencies in the SQL export.

Is there any other client which exports data in the way you are describing?

I'm closing this issue, as I don't plan to add such complexity. But feel free to keep it updated.
