### ISSUE TITLE
Crash when closing database connection when query histories are visible

### ISSUE THREAD

**Issue by scottcopus** [HeidiSQL/HeidiSQL#207]
## Steps to reproduce this issue

1. Open any database connection
2. Open Query history tree
3. Open any trees under it... like 2018-03-18
4. Keep any of those past queries VISIBLE in that window
5. Close the database connection (via the 2nd icon on the toolbar)
6. EXCEPTION: An error occurred in the application.
EAccessViolation
Top call stack function:
addr 00CB0484, Main, line 11510, rel. +14, function TMainForm.treeQueryHelpersPaintText

## Possible solution

Note that this only happens when the *last* database connection is closed.  If multiple database connections are open, closing others first does not cause an exception.  If the past queries are NOT visible (such as opening 'SQL keywords' tree pushes them down off-screen), then it will not crash.

## Environment

* **HeidiSQL version:** 9.5.0.5263

**Comment by G3ph4z** [comment]
![image](https://user-images.githubusercontent.com/26697727/37792221-79cdfe50-2e0b-11e8-953e-b896512fcee6.png)

Confirmed, but I got different exception message.

**Comment by scottcopus** [comment]
Yours is the same exception... EAccessViolation.  My other information came from the "call stack" tab which isn't visible in your screenshot.  Following the example in https://github.com/HeidiSQL/HeidiSQL/issues/208 , it might be best to attach the bug report file.  I've attached mine.
[bugreport-207-scottcopus-1.txt](https://github.com/HeidiSQL/HeidiSQL/files/1838907/bugreport-207-scottcopus-1.txt)

**Comment by G3ph4z** [comment]
@scottcopus Ehw, I forgot, thank you for reminding me.

**Comment by ansgarbecker** [comment]
Should be fixed by 51fcf379bbc6d26659021c8c29f5685f434288d4
