### ISSUE TITLE
frame with functions, keywords, snippets etc is narrow and unsizable

### ISSUE THREAD

**Issue by genfail** [HeidiSQL/HeidiSQL#209]
## Steps to reproduce this issue
1. Open Heidi
2. try to open an sql snippet via the pane on the top-right side
3. the pane is so narrow that i cannot read the texts
4. Then I cannot select the snippet
See screenshot:
![heidisql 9 5 0 5263](https://user-images.githubusercontent.com/11422227/37758181-8cd31078-2daf-11e8-826c-0cad9454c34d.jpg)

## Expected behavior
should be wide enough, or resizable

## Possible solution
make wide enough, or resizable

## Workaround
Snippets are saved in c:\Users\<Your Name>\Documents\HeidiSQL\Snippets\

## Environment

* **HeidiSQL version:** 
Heidi 9.5.0.5263
* **Database system and version:** 
MariaDB (not relevant here)
* **Operating system:** 
Win7-64
Tried on multiple PC's

**Comment by WesleyM77** [comment]
Not sure when this was fixed, but that pane can now be resized.

**Comment by ansgarbecker** [comment]
Thanks for checking that. Yes, this was buggy for some time only, until I pushed a fix.
