### ISSUE TITLE
Predefined selection in table tools dialog

### ISSUE THREAD

**Issue by ansgarbecker** [HeidiSQL/HeidiSQL#21]
## Expected behavior

Rightclick in database tree of table tools, showing "Select preset" and "Save preset", based on the database node level. (Having it on the server level would prevent this from selecting presets for different database names.)

## Current behavior

Selection has to be done manually each time the dialog is shown.

See attached screeny for idea.
![table-tools-preselection](https://user-images.githubusercontent.com/7986591/33276235-42512f7c-d395-11e7-8e2d-f997992229c5.png)

**Comment by ansgarbecker** [comment]
Deleting a preset could be done in combination with <kbd>Ctrl</kbd> key, perhaps with an additional disabled menu item containing a hint for this delete feature.

**Comment by rentalhost** [comment]
My suggestion is create a single node on main context menu, and inside it we should see all saved presets, the "save as" option and a preset manager option to dialog.

* Presets:
  * Saved name 1
  * Saved name 2
  * Saved name N
  * --
  * Save as...
  * Manager...

The Manager dialog should allow rename and remove presets (features like edit could be implemented on future), with an initial filter based on current selected table (_regular expression?_).

**Comment by ansgarbecker** [comment]
Closing, in favor to #178.
