### ISSUE TITLE
HeidiSQL crashes when using google authentication

### ISSUE THREAD

**Issue by charles-001** [HeidiSQL/HeidiSQL#211]
Hello,

I'm using 9.5.0.5263 on Windows 10 w/ MySQL 5.7.21 and whenever authenticating via Google Authentication + PAM LDAP, Heidi freezes with no information as to why.

**Here's log file for the authentication**:
Mar 26 16:36:17 xxx mysqld(pam_google_authenticator)[16915]: debug: start of google_authenticator for "cthompson"
Mar 26 16:36:17 xxx mysqld(pam_google_authenticator)[16915]: debug: Secret file permissions are 0400. Allowed permissions are 0770
Mar 26 16:36:17 xxx mysqld(pam_google_authenticator)[16915]: debug: "/home/cthompson/.google/.google_authenticator" read
Mar 26 16:36:17 xxx mysqld(pam_google_authenticator)[16915]: debug: shared secret in "/home/cthompson/.google/.google_authenticator" processed
Mar 26 16:36:24 xxx mysqld(pam_google_authenticator)[16915]: debug: no scratch code used from "/home/cthompson/.google/.google_authenticator"
Mar 26 16:36:24 xxx mysqld(pam_google_authenticator)[16915]: Accepted google_authenticator for cthompson

**Comment by ansgarbecker** [comment]
Hi, and sorry for the long delay here. Is that still reproducible for you with the current nightly build?
