### ISSUE TITLE
Blured fonts on Windows with scale setting

### ISSUE THREAD

**Issue by vatavale** [HeidiSQL/HeidiSQL#213]
## Current behavior
Fonts are blured on Windows systems (with high resolustion screens) with font scale settings.

## Expected behavior
Sharp fonts with any scale factor in Windows settings.

## Possible solution
With scale 100% fonts are too small on hires displays.

* **HeidiSQL version:** 
  9.5.0.5264
* **Operating system:** 
  Windows 10

**Comment by ansgarbecker** [comment]
HeidiSQL has to be DPI aware to avoid this scaling done by Windows. This is not possible with Delphi XE5. I already tried to pretend HS _were_ DPI aware, in build 5078, but that only revealed a lot of problems HeidiSQL has. See also this forum thread: https://www.heidisql.com/forum.php?t=21287

**Comment by ansgarbecker** [comment]
This screenshot is a good overall review of the issues introduced when scaling with pretending DPI awareness:
![grafik](https://user-images.githubusercontent.com/7986591/38176726-712bb814-35f4-11e8-809f-a96bf12c77e2.png)

**Comment by crewone** [comment]
This gets my vote. With high dpi laptops and monitors being more common and almost common these days, it would be important to be high-dpi aware. I for one have stopped using HeidiSQL after I got 4K screens because of this. 

The fact that this has been an issue for over 2 years now makes this even more important.

**Comment by ansgarbecker** [comment]
Well it's still not fixable yet, due to the above mentioned scaling problems of the underlying Delphi XE5 library. Look at the above screenshot. I have no clue how to fix that.

**Comment by Andrzej-W** [comment]
According to this page:
https://www.embarcadero.com/products/rad-studio/whats-new-in-10-2-tokyo
you have to buy new Delphi to have support for HighDPI screens in VCL library.

**Comment by energizer77** [comment]
For me this helped:
Go to the heidisql.exe file => Properties => Compatibility => Check "Override high DPI scaling behaviour" and selecting "System (Enhanced)"

**Comment by ansgarbecker** [comment]
@energizer77 could you please post a screenshot of HeidiSQL, how that looks like with that "enhanced" setting?

**Comment by energizer77** [comment]
3200 x 1800 with 175% zoom
![heididpicomp](https://user-images.githubusercontent.com/16227191/38544394-9b449e22-3ca7-11e8-8ff3-110288fad009.PNG)

Left is with DPI system enhancement, right is without.
For me it looks a bit more sharp.

**Comment by ansgarbecker** [comment]
Nice finding!

I also just see that the free [Lazarus IDE](http://www.lazarus-ide.org/) has a "Hi-DPI" project setting. So, buying a new expensive Delphi license does not seem to be the only alternative.
![grafik](https://user-images.githubusercontent.com/7986591/38581664-c91e7816-3d0d-11e8-9565-b3a15ce21b4a.png)

**Comment by energizer77** [comment]
Just to come back to this, I actually switched to "Application" in the Override high DPI scaling behaviour, seems the best quality, and also my query editor seemed to become unresponsive/not updating with the "System (Enhanced)" setting.
Was working fine before so I checked with previous versions of HeidiSQL but same problem, so I suspect there was a recent change in Windows' override behaviour.

**Comment by glen-84** [comment]
@ansgarbecker,

Are you able to build HeidiSQL on a trial of the latest version of Delphi, to see if there are any improvements?

The quality is perfect when the application takes care of scaling, but I suppose it has to be updated to use scalable fonts, high-resolution icons, updated GUI components that understand pixel ratios, etc.

**Comment by v7a** [comment]
If you really plan to re-write the code for HeidiSQL, I would recommend switching to C++ and Qt. I suppose Qt even supports all drivers HeidiSQL supports now and can easily be extended by registering custom ones. I'd be willing to help!

**Comment by danieldjewell** [comment]
@v7a If you (collectively) do decide to rewrite like that, we'll need to setup a beer savings account or something. Given the complexity already, that would be a massive undertaking. 

I just looked up a new Delphi/RAD Studio 10.2 License from Embarcadero... I was shocked. $2000 - 5000 USD. As @Andrzej-W pointed out - the newer version have HiDPI support. It's a real shame but that's the way it is. 

Maybe we (users of HeidiSQL) can get together and get the money to buy @ansgarbecker the new version? I mean, yeah, it's a lot of money ... but this is not going to be a problem that (a) solves itself or (b) is going away any time soon - high resolution and high DPI displays are just going to become more common.

**Comment by jamesvl** [comment]
Seems like the free Lazarus IDE 1.8.x has gotten better support for compiling High DPI aware applications: http://wiki.lazarus.freepascal.org/High_DPI#High_DPI_in_Lazarus_1.8_and_above

Any chance we could get some builds with those settings enabled? I'm sure we'd love to test it out.

**Comment by ansgarbecker** [comment]
Heidi is written in Delphi XE5, not Lazarus. Probably I should migrate to Lazarus at some point. But I fear all the effort and new bugs this involves.

**Comment by ansgarbecker** [comment]
I just installed a trial of Embarcadero Rad Studio 10 on a virtual machine, to check whether it has some solutions to the above mentioned issues. And it indeed has some!
See the screenshot for some critical components which draw wrong in the current HeidiSQL, in high-dpi mode.
![rx10-sample-program](https://user-images.githubusercontent.com/7986591/47177545-f9e4d700-d318-11e8-99d9-89dd3c068d3e.png)

We have
* high dpi: fixed height of menu items with 16x16px icons
* high dpi: fixed size of toolbar buttons with the same icons
* even various themes are available (screen shows the "carbon" theme). See #8 

Probably I should really buy a license.

By the way, I also gave Lazarus another chance, yesterday, while trying to convert the basic components to Lazarus packages, and/or by finding replacements. This is all a mess - outdated packages, no clear documentation on them, and many VCL units without usable LCL replacement. Means a lot of conversion work, which I am not willing to spend to much time on.

**Comment by ansgarbecker** [comment]
Next step for me is to load Heidi sources into that trial version of RAD Studio 10, and to compile the project.

**Comment by ansgarbecker** [comment]
Here we go - HeidiSQL compiled with Rad Studio 10.2, Carbon Style selected, and Windows set to 150% (high dpi):

Fixed:
* toolbar buttons and icons
* database and table filter boxes

New issues:
* style related: lightgrey column background (custom code, easy to fix)
* dpi related: many non-scaled controls, like the search box at the bottom. Probably missing "Scaled" properties to be set, not sure.
* style related: Broken main menu items (not in the screen). Items are invisible but preserve space.

![tokyo-carbon-database-highdpi](https://user-images.githubusercontent.com/7986591/47235226-b5207500-d3d8-11e8-8206-a49e01ee087f.png)

**Comment by ansgarbecker** [comment]
Quite useful article and comments here: http://zarko-gajic.iz.hr/delphi-high-dpi-road-ensuring-your-ui-looks-correctly/

Also, I see that `Screen.PixelsPerInch` is always 96 for me, while `Monitor.PixelsPerInch` reflects the scale factor set by the user (e.g. 100%, 125%, ...)

**Comment by ansgarbecker** [comment]
I spent some time on dpi scaling and committed relevant fixes for HeidiSQL. Don't expect wonders for now, there are still quite a few things to fix in the nightly builds. But I think I am on the right way this time.

**Comment by ansgarbecker** [comment]
Fixed today:
* dimensions of status bar panels
* size of various blue link-labels
* upscale icons (ugly but hey)

Still broken in high dpi mode:
* various controls on the right side of the session manager are scaled right out off the form
* row height in table editor / columns list
* more?

**Comment by ansgarbecker** [comment]
Also broken:
* rows in right-sided helpers panel on any query tab are too small
* table designer has very huge and misaligned controls, probably 2x scaled?

**Comment by ansgarbecker** [comment]
Any more issues in high DPI mode with HeidiSQL? Apart from unsupported different DPI settings on multiple monitors (#378).

**Comment by energizer77** [comment]
Wanted to try, but for me it hangs right after startup, tested previous versions and last I can run is 5321

Bug report:
```
date/time          : 2018-11-04, 22:51:44, 816ms
registered owner   : Windows User
operating system   : Windows 10 Tablet PC x64 build 17134
system language    : English
system up time     : 21 days
program up time    : 917 milliseconds
processors         : 8x Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
physical memory    : 6241/16112 MB (free/total)
free disk space    : (C:) 253.57 GB
display mode       : 1829x1029, 32 bit
process id         : $8430
allocated memory   : 77.96 MB
largest free block : 131025.96 GB
executable         : heidisql.exe
exec. date/time    : 2018-11-04 22:43
version            : 9.5.0.5325
compiled with      : Delphi 10.2 Tokyo
madExcept version  : 4.0.20
callstack crc      : $b251e01a, $96cc2c21, $96cc2c21
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 00000000009B6674 in module 'heidisql.exe'. Read of address 0000000004FBFFD2.

main thread ($11414):
009b6674 heidisql.exe apphelpers 3089 +34 ResizePngImage
009b6059 heidisql.exe apphelpers 2967 +18 ScaleImageList
00d70c24 heidisql.exe Main       1600 +11 TMainForm.FormCreate
0080e9f3 heidisql.exe Vcl.Forms           TCustomForm.DoCreate
0080e249 heidisql.exe Vcl.Forms           TCustomForm.Create
0081ec36 heidisql.exe Vcl.Forms           TApplication.CreateForm
00db8409 heidisql.exe heidisql     80 +21 initialization
7ffec1c3 KERNEL32.DLL                     BaseThreadInitThunk
7ffec255 ntdll.dll                        RtlUserThreadStart
```

**Comment by fifonik** [comment]
> Any more issues in high DPI mode with HeidiSQL?

Yup. Crash popup is still have blured font :)

**Comment by ansgarbecker** [comment]
Ok, that crash should be fixed with the latest build now. But now the icons are slightly cut at the right and bottom edges.

**Comment by ansgarbecker** [comment]
I am closing this issue now, as I think most of the DPI stuff is done, and my own todo list is (nearly) finished.

If you find more issues, then please report that to a new issue. Thanks!
