### ISSUE TITLE
SSL protocol version mismatch

### ISSUE THREAD

**Issue by G3ph4z** [HeidiSQL/HeidiSQL#215]
## Current behavior

Can't connect to MySQL with SSL.

## Expected behavior

Successful connection. Its working fine with DBEaver or MySQL Workbench

## Possible solution

Update mysql lib.

## Environment
* **HeidiSQL version:** 
  9.5.0.5264
* **Database system and version:** 
  mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64)
* **Operating system:** 
  Windows 10 x64

**Comment by ansgarbecker** [comment]
10.1 has updated libraries, which potentially fixes this issue. Could you please verify that and report back?

**Comment by naknak987** [comment]
This could be the same issue I've been experiencing. The error message I get is `SSL connection error: The message received was unexpected or badly formatted` and started at version `9.5.0.5295`. I've tried out version `10.1` and `10.1.0.5470`, but that didn't resolve the issue. I was able to connect with SSL using `Database Workbench v5.4.6 Lite`, and with `MySQL Workbench 8.0.14 build 14121199 CE`.  
  
Reinstalling version `9.5.0.5196` allows me to connect with SSL again.  
  
Let me know if I can provide you any other information that would be useful.

**Comment by Eldair** [comment]
Hi, is this fixed?

**Comment by ansgarbecker** [comment]
I'm not sure, as I never not myself reproduce this, and I thought the updated libraries in v10.1 healed at least some of the SSL errors reported here. But obviously it is not fixed as you already tried out with the latest build?

**Comment by G3ph4z** [comment]
@ansgarbecker Sorry for long delay. So I quit use to use windows at last year, so sorry, I can't test it. :(

**Comment by Eldair** [comment]
Hi @ansgarbecker I've tried the latest nightly build (running it from the same dir where v9 is installed if that's the correct way) and it still doesn't work

**Comment by ansgarbecker** [comment]
> running it from the same dir where v9 is installed

v9 ? Please install v10.1 and report back if the problem persists.

**Comment by Eldair** [comment]
@ansgarbecker clean install of heidi 10 latest nightly build has the same issue

**Comment by ansgarbecker** [comment]
And the exact error message you get is what the reporter wrote above, or?

**Comment by Eldair** [comment]
The one from this issue
https://github.com/HeidiSQL/HeidiSQL/issues/529

**Comment by ansgarbecker** [comment]
I am confused. If you got the message from #529 - why did you post in this issue, which reports a different (probably related) error?

**Comment by Eldair** [comment]
It seemed/seems to be the same (or closely related) issue and also the
first comment is about the same thing

**Comment by si3le11** [comment]
Hi, same issue here with HeidiSQL 10.1.0.5464 and MySQL 8.0.15: 
"SSL connection error: The message received was unexpected or badly formatted"

**Comment by RalfRoemling** [comment]
Same here

**Comment by KolesnikovDV** [comment]
Same problem

**Comment by ansgarbecker** [comment]
I pushed 51da7c8efc890ebdb394dfa53f911b64223a53e8 yesterday, which now allows all TLS versions up to v1.3. Probably that helps here.

**Comment by RalfRoemling** [comment]
May you please build a new release for testing since not everybody owns Delphi 10? Thx :-)

**Comment by RalfRoemling** [comment]
Works like a charm. Thx :-)

**Comment by naknak987** [comment]
Does that mean all of our serivers were configured to use an old, outdated version of SSL/TLS? 

I feel like I need to upgrade my MariaDB server now.

**Comment by ansgarbecker** [comment]
I'm not sure but it reads like unless you don't configure your server with `tls_version=TLSv1.2`, it runs on TLS 1.0 - but that's speculative.

**Comment by KolesnikovDV** [comment]
in mariadb cnf: ssl-cipher=TLSv1.2,DHE-RSA-AES256-SHA
New build Result: [http://imgdisk.ru/images/2019/05/23/BEZYMYNNYI.png](url)

**Comment by ansgarbecker** [comment]
Please try out the latest HeidiSQL build.

**Comment by ansgarbecker** [comment]
Shout if still reproducible with v12.0
