### ISSUE TITLE
HeidiSQL crashes for... no reason in particular, maybe it thought I was being too productive.

### ISSUE THREAD

**Issue by progmanpaul** [HeidiSQL/HeidiSQL#217]
Why does running a simple SELECT query with no errors still error anyway and crash? Have you ever heard of error handling via a try/catch block?

I think I'm going back to phpMyAdmin, it doesn't cause my browser to crash!

**Comment by jens1o** [comment]
> Have you ever heard of error handling via a try/catch block?

have you ever heard of politeness?

Which `SELECT` query are you executing in detail, with which server-version and SQL flavour...

**Comment by kko123** [comment]
i have this issue with running custom query

**Comment by ansgarbecker** [comment]
If you like to have this analyzed, you should post all the details asked for in the issue template.
This details you posted here are just shit.

**Comment by endo64** [comment]
@progmanpaul what simple SELECT query on what table structure? If the crash happens always, that is good, it shouldn't be difficult for @ansgarbecker to find then, if you share the details.

Raising an issue just to say you are going to use phpMyAdmin is meaningless.
