### ISSUE TITLE
Crash when hit enter key while changing column name of a table

### ISSUE THREAD

**Issue by wangyi6854** [HeidiSQL/HeidiSQL#218]
## Steps to reproduce this issue

1. Step 1; Make some changes to a column name in a table.
2. Step 2; Do not press save button.
3. Step 3; Press enter key.
4. Then I get... Crash.

## Current behavior

Crash when pressing enter key while changing column name.
## Expected behavior

Just confirm changes to the column name.
## Environment

* **HeidiSQL version:** 
  
9.5.0.5264 32 bit
* **Database system and version:** 
  
mysql 5.6.21
* **Operating system:** 
  
windows 7 6.1 7601

**Comment by fifonik** [comment]
HeidiSQL does not crash in my case (9.5.0.5280 & MySQL 5.7.19)

**Comment by ansgarbecker** [comment]
@wangyi6854 can you please verify whether the issue persists with the latest release 10.1

**Comment by ansgarbecker** [comment]
Does not crash here, so I'm closing it now. If it still does for you, @wangyi6854, please give feedback.

**Comment by nssmart** [comment]
Heidi 10.1.0.5464 - error exists just as desribed. Enter press makes it hangs for a second, then it just silently exits.

**Comment by ansgarbecker** [comment]
@nssmart you should update to the latest HeidiSQL and retry.
