### ISSUE TITLE
Can't view table info and data for SQL Server 2000

### ISSUE THREAD

**Issue by phiter** [HeidiSQL/HeidiSQL#221]
## Steps to reproduce this issue

1. Connect to a SQL Server 2000 server
2. Select a table on the left panel
3. You can't see the table columns on the edit panel, nor in the Data tab.

## Current behavior

It seems like the application isn't being able to retrieve the table info.

## Expected behavior

I should be able to edit the table structure and see its data.

* **HeidiSQL version:** 
9.5.0.5196
* **Database system and version:** 
SQL Server 2000
* **Operating system:** 
Microsoft Windows 7

## Additional info:

This is the error I'm seeing:

```
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG='mydb' AND TABLE_NAME='mytable';
```
```
SELECT c.name AS "column", prop.value AS "comment" FROM sys.extended_properties AS prop INNER JOIN sys.all_objects o ON prop.major_id = o.object_id INNER JOIN sys.schemas s ON o.schema_id = s.schema_id INNER JOIN sys.columns AS c ON prop.major_id = c.object_id AND prop.minor_id = c.column_id WHERE prop.name='MS_Description' AND s.name='' AND o.name='mytable';
```
```
/* SQL Error (208): Invalid object name 'sys.extended_properties'
Invalid object name 'sys.columns'. */
```

**Comment by ansgarbecker** [comment]
I think I already solved this in f4d2488998ba585c971e672545b8a2843378572b
