### ISSUE TITLE
Version 9.5: output when combining functions

### ISSUE THREAD

**Issue by ckeschnat** [HeidiSQL/HeidiSQL#227]
## Steps to reproduce this issue

1. Update to latest HeidiSQL
2. run `SELECT SUBSTRING(AVG(SUBSTRING("duration: 0.157773971558", 11, 5)), 1, 5)`

## Current behavior

Output is displayed as `0x302E313537`

## Expected behavior

Output should display `0.157`.
This is true in HeidiSQL 9.3 and 9.4

## Possible solution

Not combining all functions works:
`SELECT AVG(SUBSTRING("duration: 0.157773971558", 11, 5))`
=> `0.157`

`SELECT SUBSTRING("0.157", 1, 5) `
or
`SELECT SUBSTRING(0.157, 1, 5)`
=> `0.157`

## Environment

* **HeidiSQL version:** 9.5.0.5269 on Windows 10
* **HeidiSQL version:** 9.5.0.5196 on Windows Server 2012 R2 Standard
  
* **Database system and version:** MySQL 5.6.39-83.1-log
  
* **Operating system:** Ubuntu 14.04

**Comment by ansgarbecker** [comment]
This is not a bug. The server sends a binary collation along with the resulting field.
But you can press the "View binary data as text" button:
![grafik](https://user-images.githubusercontent.com/7986591/38692752-162bf3fe-3e85-11e8-874f-a24cb4bc6b11.png)
