### ISSUE TITLE
Font Size with Mouse

### ISSUE THREAD

**Issue by maxsnts** [HeidiSQL/HeidiSQL#229]
## Steps to reproduce this issue

Change font when using Windows (virtual) on a MAC with a MagicMouse

## Current behavior

When inadvertently we change the font size using the scroll, its very difficult to restore the font size.
This is NOT a problem with HeidiSQL

## Possible solution

- Provide a preference to disable this feature.

## Environment

Windows (virtual) on a MAC with a MagicMouse

* **HeidiSQL version:** 
9.5

Thank you.

**Comment by ansgarbecker** [comment]
If this is not a problem with HeidiSQL, then what should be done in HeidiSQL?

**Comment by ansgarbecker** [comment]
There is already an option to set the font size, in preferences > SQL. But I guess you want a setting to disable that <kbd>Ctrl+Mousewheel</kbd> shortcut. I can't find that useful, and also I can't see any other software providing a customization of such a simple zoom feature.
All major web browsers do the same thing with the same shortcut, so how do you avoid an inadvertently zoom there?

**Comment by maxsnts** [comment]
Yes, you are right that its a "niche" problem that affects very few people.
It manifests it self only inside the Windows machine that is on top of OSX When using a Magic Mouse.
I manly use to applications on Windows:
- Visual Studio (in there i use an Extension to disable Zoom) and it has a menu option to reset zoom, and shortcut
- HeidiSQL, that i have no way of disable zoom. (That why i asked)
- Browsers i use in OSX (where the problem does not manifest it self) and they have a way to reset Zoom on menu

In Fairnesses, i did state that it was not a direct problem of Heidi.

**Comment by maxsnts** [comment]
Hehe, Close but no. Magic Mouse is hardware, its the Apple Mouse that has no wheel.
You Scroll using Touch, and that's what creates the problem.
In a regular mouse the wheel have clear "ckicks" when you scroll it.
In the touch scroll, there is no way to control how much you scrolled. 
Its not a problem when scrolling documents, but it always  creates a problem when a "small scroll" creates a big difference, like going from one font size to the next.

**Comment by ansgarbecker** [comment]
Ok, understand. But that zooming in HeidiSQL also requires the <kbd>Ctrl</kbd> key to be pressed, so how can that be done inadvertantly?

**Comment by ansgarbecker** [comment]
Btw, please update to the latest build and use the new checkbox I just added to disable zooming per mousewheel. See preferences dialog, then in tab "General".

**Comment by maxsnts** [comment]
Because Windows is a Virtual machine, some key presses (modifiers) seem to get a little delayed.
Sometimes when coding we use Ctrl alot (copy, paste, etc). When we paste, and scroll right after, the delay kicks in and we get a big Zoom.

**Comment by maxsnts** [comment]
Oh man, Thank you.
I know its a very narrow problem (if you can call it that), but its very annoying for the very few that has to deal with it. 
Thanks again, and sorry for the trouble.

**Comment by maxsnts** [comment]
By the way, I know you don't remember be because i was using a different mail/nick at the time.
I gave you the ideia of "testing" de Stored Procedure syntax by creating a Temporary Stored procedure before Droping the real one, and only when the Syntax was ok, change the real Stored Procedure.
Thank you for implementing that too (if that's is how it still works).
That has been a blessing. 
Thanks.
