### ISSUE TITLE
EOutOfMemory crash when exporting grid with huge result

### ISSUE THREAD

**Issue by SergeiShir** [HeidiSQL/HeidiSQL#23]
Just wanted to send you a Bug Report that was shown to me by the application.

## Background

Ran a SELECT query on the table.
Received the expected results.
Tried to export the grid.
The application showed the bug report.
exception class    : EOutOfMemory
exception message  : Out of memory.

## Failure information (for bugs)

date/time          : 2017-11-30, 10:56:25, 572ms
computer name      : XXXX
user name          : XXXX <admin>
registered owner   : XXXX
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : English
system up time     : 1 day 19 hours
program up time    : 1 hour 13 minutes
processors         : 4x Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
physical memory    : 7923/16080 MB (free/total)
free disk space    : (C:) 4.37 GB
display mode       : 1600x900, 32 bit
process id         : $3e4c
allocated memory   : 768.39 MB
largest free block : 210.25 MB
executable         : heidisql.exe
exec. date/time    : 2016-10-21 13:41
version            : 9.4.0.5125
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $d522dc1c, $fb3dc0d6, $fb3dc0d6
exception number   : 1
exception class    : EOutOfMemory
exception message  : Out of memory.

main thread ($1da0):
0040c8ed heidisql.exe System          196   +0 DynArraySetLength
0040ca19 heidisql.exe System          196   +0 @DynArraySetLength
0052b247 heidisql.exe System.Classes           TBytesStream.Realloc
0052b025 heidisql.exe System.Classes           TMemoryStream.SetCapacity
0052b171 heidisql.exe System.Classes           TMemoryStream.Write
0052b628 heidisql.exe System.Classes           TStringStream.WriteString
0090e3c5 heidisql.exe exportgrid      882 +409 TfrmExportGrid.btnOKClick
005b1563 heidisql.exe Vcl.Controls             TControl.Click
005d3f42 heidisql.exe Vcl.StdCtrls             TCustomButton.Click
005d4abc heidisql.exe Vcl.StdCtrls             TCustomButton.CNCommand
005b100d heidisql.exe Vcl.Controls             TControl.WndProc
005b5b2d heidisql.exe Vcl.Controls             TWinControl.WndProc
005d3bec heidisql.exe Vcl.StdCtrls             TButtonControl.WndProc
005b0c48 heidisql.exe Vcl.Controls             TControl.Perform
005b5c93 heidisql.exe Vcl.Controls             DoControlMsg
005b6723 heidisql.exe Vcl.Controls             TWinControl.WMCommand
0067fc8c heidisql.exe Vcl.Forms                TCustomForm.WMCommand
005b100d heidisql.exe Vcl.Controls             TControl.WndProc
005b5b2d heidisql.exe Vcl.Controls             TWinControl.WndProc
0067ca99 heidisql.exe Vcl.Forms                TCustomForm.WndProc
005b5170 heidisql.exe Vcl.Controls             TWinControl.MainWndProc
0053c65c heidisql.exe System.Classes           StdWndProc
77dd0117 ntdll.dll                             KiUserCallbackDispatcher
76a696c0 USER32.dll                            SendMessageW
76a70d60 USER32.dll                            CallWindowProcW
005b5c3e heidisql.exe Vcl.Controls             TWinControl.DefaultHandler
005b19b8 heidisql.exe Vcl.Controls             TControl.WMLButtonUp
005b100d heidisql.exe Vcl.Controls             TControl.WndProc
005b5b2d heidisql.exe Vcl.Controls             TWinControl.WndProc
005d3bec heidisql.exe Vcl.StdCtrls             TButtonControl.WndProc
005b5170 heidisql.exe Vcl.Controls             TWinControl.MainWndProc
0053c65c heidisql.exe System.Classes           StdWndProc
76a67885 USER32.dll                            DispatchMessageW
00686167 heidisql.exe Vcl.Forms                TApplication.ProcessMessage
006861aa heidisql.exe Vcl.Forms                TApplication.HandleMessage
00681516 heidisql.exe Vcl.Forms                TCustomForm.ShowModal
0095a29d heidisql.exe Main           2966   +4 TMainForm.actExportDataExecute
0053b94b heidisql.exe System.Classes           TBasicAction.Execute
00595523 heidisql.exe Vcl.ActnList             TCustomAction.Execute
0053b7eb heidisql.exe System.Classes           TBasicActionLink.Execute
0066c19b heidisql.exe Vcl.Menus                TMenuItem.Click
0066d807 heidisql.exe Vcl.Menus                TMenu.DispatchCommand
0066ea76 heidisql.exe Vcl.Menus                TPopupList.WndProc
005b5170 heidisql.exe Vcl.Controls             TWinControl.MainWndProc
0066e9c5 heidisql.exe Vcl.Menus                TPopupList.MainWndProc
0053c65c heidisql.exe System.Classes           StdWndProc
76a67885 USER32.dll                            DispatchMessageW
00686167 heidisql.exe Vcl.Forms                TApplication.ProcessMessage
006861aa heidisql.exe Vcl.Forms                TApplication.HandleMessage
006864e5 heidisql.exe Vcl.Forms                TApplication.Run
76b63368 kernel32.dll                          BaseThreadInitThunk

**Comment by ansgarbecker** [comment]
Current nightly build is version 5188, while you tested with 5125. Please update and retest. Thanks!

**Comment by rentalhost** [comment]
@SergeiShir could you update to last available version and run your test again? How much memory is installed on your PC currently? Which target mode you have selected (to clipboard or file)?

@ansgarbecker I think that if the option "copy to clipboard" is enabled, it will depends of available client memory. So errors like that is ineviable. The unique solution is show an exception error like "Out memory to copy to clipboard" instead of a hard exception like the provide. If the selected output option is "file", so I think that it should be flush time by time to avoid memory error independent of amount of available memory.

**Comment by SergeiShir** [comment]
I could not reproduce this issue anymore on v9.5.0.5196 (official version dated 19 Dec 2017).
Thank you for the help.
