### ISSUE TITLE
Query result header name showing wrong

### ISSUE THREAD

**Issue by naveen12** [HeidiSQL/HeidiSQL#232]
Am newbie to this HeidiSQL, i have executed queries at time like 
select * from employee
select * from department
select * from salary

then in 3 results it showing header as first table name where it should show three different name as table names

let me know the exact reason, if the issue already reported then give the ticket number

**Comment by ansgarbecker** [comment]
Don't delete the issue template, it's there to help understand your issue!

I have to assume now you're on MSSQL, and I see you are not using semicolon at the end of each query. Insert a semicolon at the end of each query to fix that.
