### ISSUE TITLE
Feature request to suppress dialogs about MySQL warnings

### ISSUE THREAD

**Issue by supropio** [HeidiSQL/HeidiSQL#234]
## Steps to reproduce this issue

Execute any SQL query that throws a MySQL warning. Examples depend on server config as to what triggers a warning.

## Current behavior

Warning is repeated or summarized in a modal dialog box that prevents further action until I click OK.
![image](https://user-images.githubusercontent.com/38508263/38953625-5e14053e-431d-11e8-91bf-0c244b3a29fd.png)

## Expected behavior

I would like to choose which warnings merit my attention by watching the query log at the bottom of the HeidiSQL window.  I don't expect to have to click OK as often as HeidiSQL wants me to with respect to these warnings.

I am aware that I could reconfigure my MySQL servers to suppress my most common warnings but that's a lot of work with more than 100 servers.

## Possible solution

Add a user preference to disable dialog-box presentation of MySQL warnings.

## Environment

Windows 10.

* **HeidiSQL version:** 
  9.5.0.5196 (64 bit)

* **Database system and version:** 
  MySQL 5.5, 5.6

* **Operating system:** 
  Ubuntu Linux 14.04 LTS

THANK YOU AGAIN!!!

**Comment by ansgarbecker** [comment]
The dialog should have a checkbox "Keep showing this dialog", which can be unchecked to disable it for the future. Also, the preferences dialog has a checkbox to reactivate it again.

**Comment by supropio** [comment]
That's a shrewd way to do it, so the suppression option is exposed without requiring that the user know about the toggle in the prefs panels.

Many many thanks!

**Comment by ansgarbecker** [comment]
Just had to look up the word "shrewd". Nice to get some new words from time to time.
However, thanks for your feedback!
