### ISSUE TITLE
Find Text on Server fails when Postgres table contains Integer column

### ISSUE THREAD

**Issue by cookieguru** [HeidiSQL/HeidiSQL#235]
## Steps to reproduce this issue

1. Connect to a Postgres server
2. Launch "Find text on server"
3. Select a table that contains `integer` column(s)
4. Then I get... `ERROR:  function lower(integer) does not exist` 

## Current behavior

`ERROR:  function lower(integer) does not exist` 

## Expected behavior

Feature works as it does for MySQL

## Environment

Example table structure:
```sql
CREATE TABLE myschema.sources
(
  source_id integer,
  source_description character varying(255) COLLATE pg_catalog."default"
)
TABLESPACE pg_default;
```

* **HeidiSQL version:** 
  9.5.0.5256 (64 Bit)
* **Database system and version:** 
  PostgreSQL 10.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit

**Comment by ansgarbecker** [comment]
Fix was to apply `LOWER()` after `CAST(... AS TEXT)`. Should work with the latest build now.
