### ISSUE TITLE
Cannot clear the first query tab with two mouse clicks

### ISSUE THREAD

**Issue by albertdick** [HeidiSQL/HeidiSQL#238]
## Steps to reproduce this issue

Write something to first query tab. The table title will show an asterisk after title, so you know it has been modified.
But when you click twice over tab, it doesn't clean, and doesn't returns to be like a new tab.

## Current behavior

Nothing happens when you click twice or more on a modified first query tab,

## Expected behavior

When you click in the first query tab twice after modifying it, it clears its contents, and returns to be like a new tab, without the "asterisk".

## Possible solution

Don't know.
The last build I checked that this worked is 9.5.0.5225, installed on a friend's computer. But I believe this functionality has been broken most recently than this build.

## Environment

* **HeidiSQL version:** 
9.5.0.5277
* **Operating system:** 
Windows 8.1 Single Language (64-bit)

**Comment by ansgarbecker** [comment]
This is intentionally, see #231 for a discussion on that topic

**Comment by albertdick** [comment]
Well, it's bad. I think that first tab should be "closed" in some way.

After reading issue #231 the impression I have is that it's author accidentally clicked twice on the first tab.

I've used HeidiSQL for almost two years, almost every day, and I've never accidently closed the first tab.

Now, even if I close all used tabs, I'll see a warning (that I don't want to disable) because I can't "close" the first tab anymore.

**Comment by ansgarbecker** [comment]
You can always clear the editor using <kbd>Ctrl+W</kbd> or rightclick => Clear.

**Comment by albertdick** [comment]
I didn't know there were keyboard shortcut to that.
That helps.
Thanks for your reply.
