### ISSUE TITLE
Problem with Dark theme - UI and syntax colors

### ISSUE THREAD

**Issue by Yousha** [HeidiSQL/HeidiSQL#24]
## Expected behavior

Syntax highlight coloring must affect on results window also

## Current behavior

Syntax highlight coloring does NOT affect on results, so readability of results data is reduced!
(when using dark themes in Windows)

Check the Screenshot
http://s2.zipupload.ir/direct/uid_1_fid3003_1396-09-11_13_22_48_351542258.png

## Failure information (for bugs)

None.

### Steps to reproduce

1. Change your Windows theme to Dark
2. Open HeidiSQL
3. `SELECT` some records and look at Result window

### Context

* HeidiSQL version: 9.4 (or ANY OTHER VERSION)
* Database system + version: MySQL 5.6
* Operating system: Windows 7 Pro 64-bit

### Failure Logs

Results window + Syntax coloring preferences
http://s2.zipupload.ir/direct/uid_1_fid3003_1396-09-11_13_22_48_351542258.png

**Comment by ansgarbecker** [comment]
SQL and result grids have different settings. For setting grid colors in the preferences, go to "Grid formatting", and use the dropdown besides "Grid text colors" to define custom colors.

![grid-colors-preferences](https://user-images.githubusercontent.com/7986591/33514521-cb21a598-d755-11e7-9036-57da4a1cbc6f.png)

**Comment by ansgarbecker** [comment]
You probably may benefit from the new SQL color presets in HeidiSQL, added for dark themes. See the "SQL" tab in the nightly build.
