### ISSUE TITLE
Toolbar cannot be docked near the "Help" menu item

### ISSUE THREAD

**Issue by mdcclxv** [HeidiSQL/HeidiSQL#240]
## Steps to reproduce this issue

1. Step 1;
Drag the toolbar on the same row with the menu and try to dock it near the "Help" menu item. 

## Current behavior
Something prevents the toolbar from being docked nearby the "Help" menu item. See screenshot, yellow section.

## Expected behavior
Toolbar should be dockable right next to "Help" menu item.

## Possible solution
Remove the hidden element or reduce the minimum width of the menu toolbar, whatever the case.

## Environment

![screenshot](https://user-images.githubusercontent.com/33668915/39042521-ad57dec8-4493-11e8-9ce2-1fbed5711d6b.png)

* **HeidiSQL version:** 
9.5.0.5277

**Comment by ansgarbecker** [comment]
The main menu is no longer part of the same container as the toolbar. Therefor it will not be possible to even drag the button toolbar into the same row as the main menu. Having the main menu seperately fixed several bugs, so I won't revert this.
