### ISSUE TITLE
Toolbar gradually moves to the right when resizing or maximizing/restoring the window

### ISSUE THREAD

**Issue by mdcclxv** [HeidiSQL/HeidiSQL#241]
## Steps to reproduce this issue

1. Step 1;
Drag & dock the toolbar on the same row with the menu.
2. Step 2;
Repeatedly maximize/restore or resize the window.
3. Then I get...
Toolbar moves to the right until is completely out of sight.

## Expected behavior
Toolbar should stay docked to the right of the menu toolbar.

## Environment

* **HeidiSQL version:** 
9.5.0.5277

**Comment by ansgarbecker** [comment]
The toolbar is no longer draggable into one row with the main menu. So I suppose this is no longer an issue. If it is, please shout.
