### ISSUE TITLE
HeidiSQL \ MySQL : bug Import CSV File

### ISSUE THREAD

**Issue by Sebi45** [HeidiSQL/HeidiSQL#242]
## Steps to reproduce this issue

1- Go to Options\Import CSV File
2- Select options like that :

![image](https://user-images.githubusercontent.com/38557126/39044846-9e72a458-4491-11e8-817a-3d561d69b064.png)

Use a CSV file like that 
![image](https://user-images.githubusercontent.com/38557126/39045024-1488caaa-4492-11e8-83e4-820e6ffe9690.png)

## Current behavior
all data with a 99.99 format are not automatically encapsulated by '...' (and are troncated)

![image](https://user-images.githubusercontent.com/38557126/39045195-7fd303f2-4492-11e8-953f-f9328ac6f3d1.png)
 
## Expected behavior
We should have :

![image](https://user-images.githubusercontent.com/38557126/39045623-a6c9fa3c-4493-11e8-92ce-6b13b5e6ccc9.png)

## Environment

* **HeidiSQL version:** 
v9.5.0.5196 64bits
* **Database system and version:** 
MySQL v5.6.39

**Comment by ansgarbecker** [comment]
What do the "High" and "Low" columns have as data type?

**Comment by ansgarbecker** [comment]
And did you try to uncheck that "Input file contains local formatted numbers" checkbox?

**Comment by nummacway** [comment]
Should be fixed in dc054cc.
