### ISSUE TITLE
Duplicate hidden column after last viewed column in Basic tab when Remove some columns

### ISSUE THREAD

**Issue by panyachu** [HeidiSQL/HeidiSQL#245]
## Steps to reproduce this issue

1. Select database;
2. Select table;
3. Switch on _Basic_ tab;
4. Resize _Columns:_ list work space till more than two columns will make hidden;
5. _Remove_ some column one or more time;
6. Click _Discard_ button;
7. Repeat _Remove_ columns;

## Current behavior

Hidden column after last viewed column in work space duplicate when Removing other higher column.

## Expected behavior

Next columns after last viewed column in work space.

## Possible solution

No idea.

## Environment

* **HeidiSQL version: 9.5.0.5277 (64 bit)** 
  
* **Database system and version: MySQL 5.1.73** 
  
* **Operating system: Windows v10.0** 
  

![screenshot1_2](https://user-images.githubusercontent.com/3668893/39191634-ceac7af6-47f0-11e8-8715-9ae4a2b586f2.jpg)
![screenshot2_2](https://user-images.githubusercontent.com/3668893/39191982-8e470e4e-47f1-11e8-99ba-71f050b38d8e.jpg)

**Comment by ansgarbecker** [comment]
Hi, and sorry for the long delay here. Using the current nightly build, I am not able to reproduce this issue. Could you please check if you are able to reproduce? Probably I am doing something different than you, but I'm nearly sure I understood the reproduction recipe.

**Comment by panyachu** [comment]
I can reproduce this on latest nightly build.
Explaination step by step:
1. Select some table with much columns.
2. Select **Basic** tab under **Table** tab.
3. If you can view all of column list, need to move border above log space higher. It help hide some columns.
4. Select one column in top of list, then press **Remove** 5 times.
5. Press **Discard** button.
6. Then try to **Remove** columns again.


Sorry for my English.

**Comment by ansgarbecker** [comment]
Yes, confirmed now.

**Comment by ansgarbecker** [comment]
Bugfix coming with next build.
