### ISSUE TITLE
[PG] TPGQuery.TableName optimization

### ISSUE THREAD

**Issue by arturm11** [HeidiSQL/HeidiSQL#249]
## Steps to reproduce this issue

1. Connect to PostgreSQL database.
2. Open Query window.
3. SELECT * FROM anytable
4. Click any "id" cell.

## Current behavior

select * from person limit 5
;
SELECT 91039::regclass;
SELECT 91039::regclass;
/* Affected rows: 0  Found rows: 5  Warnings: 0  Duration for 1 query: 0,000 sec. (+ 0,093 sec. network) */
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;
SELECT 91039::regclass;

## Expected behavior

Cache existing object names.

select * from person limit 5
;
SELECT 91039::regclass;
/* Affected rows: 0  Found rows: 5  Warnings: 0  Duration for 1 query: 0,000 sec. (+ 0,093 sec. network) */

## Possible solution

Probably optimize TPGQuery.TableName function (not sure, there are 2 places, where regclass name is used in source code).

## Environment

Windows 10

* **HeidiSQL version:** 

9.5.0.5264

* **Database system and version:** 

PostgreSQL 9.4.13

**Comment by ansgarbecker** [comment]
I am now caching these `SELECT 123::regclass` query results in a hash table, so they're fired only once in the lifetime of a connection. This also fixed issue #538 for some reason.
