### ISSUE TITLE
Add shortcut to clear the log

### ISSUE THREAD

**Issue by jcfaria** [HeidiSQL/HeidiSQL#25]
Hello,

A couple of suggestions:

- make available a shortcut (also user customized in Preferences/Shortcuts)  to clear the LOG. Suggestion: CTRL + L;

- increase the gutter width of the editor. With the current width the bookmark number and line number are confusing;

- remove from the default shortcuts those that are related to the bookmarks of the SynEdit component: CTRL + NUMBER (to mark) and SHIFT + CTRL + NUMBER (to go). By default 1..5 are related main TabSheet focus.

Best,
J.C.Faria

**Comment by ansgarbecker** [comment]
Please one change request per ticket. Maybe except for cases in which they directly related to each other.

**Comment by ansgarbecker** [comment]
Please update to the latest nightly build, the new "Clear" action now has the hotkey Ctrl+Q (Ctrl+L is in use for lowercasing SQL code). Also, the new hotkey is customizable in Tools > Preferences > Shortcuts now.
