### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by gandriyko** [HeidiSQL/HeidiSQL#250]
## Steps to reproduce this issue

1. Download portable version  9.5.64 64 bit
2. Unpack
3. Run program. Everything is OK.
3. Download Nightly Builds of heidisql.exe 9.5.0.5277 and place into that folder
4. Run.
5. Crash 
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1948837/bugreport.txt)

## Current behavior
Crash on startup

## Expected behavior
Run as usual.

## Environment

* **HeidiSQL version:** 9.5.0.5277
  
* **Database system and version:** MariaDB 10.1
  
* **Operating system:** Wine 3.6.1 / ArchLinux

**Comment by ansgarbecker** [comment]
Another user reported that the later build  5380 runs fine on Wine, while build 5382 is again broken. I'll close this one, unless you have some more information? Probably you can then post these in #445.
