### ISSUE TITLE
🐛 Pressing tab while focusing on column type dropdown crashes heidi

### ISSUE THREAD

**Issue by bigopon** [HeidiSQL/HeidiSQL#255]
## Steps to reproduce this issue

1. Step 1; Open any table
2. Step 2; Expand column type to focus
3. Step 3; press Tab
4. Then I get... crash

## Current behavior

It crashes every time.

----

date/time          : 2018-04-28, 08:03:24, 53ms
operating system   : Windows 10 Tablet PC x64 build 16299
system language    : English
program up time    : 22 seconds
allocated memory   : 63.59 MB
executable         : heidisql.exe
exec. date/time    : 2017-12-19 15:46
version            : 9.5.0.5196
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $fbba1a69, $b1006d98, $b1006d98
exception number   : 1
exception class    : EExternalException
exception message  : External exception C000001D.

main thread ($33c4):
00d48668 heidisql.exe
008dde0b heidisql.exe VirtualTrees 18088 +53 TBaseVirtualTree.Animate
008bfe96 heidisql.exe VirtualTrees  5741 +56 TVirtualTreeHintWindow.ActivateHint
006a4f13 heidisql.exe Vcl.Controls           THintWindow.ActivateHintData
00816daf heidisql.exe Vcl.Forms              TApplication.ActivateHint
008163a2 heidisql.exe Vcl.Forms              TApplication.HintTimerExpired
00810ebd heidisql.exe Vcl.Forms              HintTimerProc
7ffa0682 USER32.dll                          DispatchMessageW
0081469f heidisql.exe Vcl.Forms              TApplication.ProcessMessage
00814713 heidisql.exe Vcl.Forms              TApplication.HandleMessage
00814bff heidisql.exe Vcl.Forms              TApplication.Run
00ca0637 heidisql.exe heidisql        80 +24 initialization
7ffa0858 KERNEL32.DLL                        BaseThreadInitThunk
7ffa086c ntdll.dll                           RtlUserThreadStart

**Comment by fifonik** [comment]
I do not have such issue with HeidiSQL 9.5.0.5280 & MySQL 5.7.19

**Comment by ansgarbecker** [comment]
No longer reproducible.

Related: #937
