### ISSUE TITLE
MariaDB UUID bug

### ISSUE THREAD

**Issue by kagasu** [HeidiSQL/HeidiSQL#259]
## Steps to reproduce this issue
1. create table
```sql
CREATE TABLE `users` (
  `uuid` VARCHAR(32) NULL DEFAULT NULL
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
```
2. insert & update data
```sql
INSERT INTO `users` (`id`) VALUES (1), (2), (3);

update users u set u.`uuid` = REPLACE(UUID(), '-', '');
```
3. Then I get same UUID
![image](https://user-images.githubusercontent.com/25629617/39672603-5f81701a-5168-11e8-8150-2141072c2eb7.png)

- Linux mysql command and Mysql Workbench is not same UUID value.
- The event created by HeidiSQL also same UUID.

## Possible solution
No idea.

## Environment
* **HeidiSQL version:** 
9.5.0.5278
* **Database system and version:** 
10.2.12-MariaDB

* **Operating system:** 
Windows 10 1709 64bit

**Comment by knoxcard** [comment]
This is not a bug with HeidiSQL but with SQL.  It doesn't work the way we think it's supposed to work...

select md5(UUID())

Look here and God Bless StackOverFlow...
https://stackoverflow.com/questions/6280789/generate-guid-in-mysql-for-existing-data
