### ISSUE TITLE
Editor: increase gutter width

### ISSUE THREAD

**Issue by jcfaria** [HeidiSQL/HeidiSQL#26]
Please, increase the gutter width of the editor. With the current width the bookmark number and line number are confusing.

**Comment by jcfaria** [comment]
See an example in the picture:

![sshot-1](https://user-images.githubusercontent.com/878690/33524145-f0cb6d6a-d7f5-11e7-85fe-86ef06cd7fed.png)

**Comment by ansgarbecker** [comment]
Ok, I was confused - that screenshot is not from HeidiSQL, but how you would like to have it. So I'll attach a screeny of the (admittedly bad) editor layout in Heidi.
![query-editor-gutter](https://user-images.githubusercontent.com/7986591/33545983-0f75d77e-d8e0-11e7-9a16-212ef7e76696.PNG)

**Comment by jcfaria** [comment]
Yes, gutter the layout in Heidi is bad and the soluction will be to increse gutter width.
The picture was obtained from a external editor to R Language.

A tip: the file SynEdit.res (..\SynEdit\Source\SynEdit.res) has the icons of the numbers and also the wordwrap icon used in the gutter to bookmarks. You can customize it (ResEdit - freweere software: http://www.resedit.net) can help with the task.

**Comment by ansgarbecker** [comment]
I doubled the space in the gutter for the next build, and made the line numbers gray instead of black.
