### ISSUE TITLE
I can't  download software from site, 404 NOT FOUND

### ISSUE THREAD

**Issue by matthijshouwaart** [HeidiSQL/HeidiSQL#260]
## Steps to reproduce this issue

1. Step 1; I try to download heidisql from official site
2. Step 2; I get the 404 NOT FOUND ERROR
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by mikiqex** [comment]
Looks like an issue with the website, maybe DB down?

Symptoms: date in Downloads is 01 Jan 1970, Forum is empty, "I have donated..." doesn't work, there's no lists of donors, on Home page there are several "Data column(s) for axis #0 cannot be of type string" errors on the right.

**Comment by ansgarbecker** [comment]
Not sure what happened, but I guess the provider seemed to make a reboot of the machine. Seems to work again now.
