### ISSUE TITLE
SSH Connection fails with upper quotation mark in passwords

### ISSUE THREAD

**Issue by EvilKarter** [HeidiSQL/HeidiSQL#261]
## Steps to reproduce this issue

1. Create a new Connection with type: MySQL (SSH tunnel)
2. On Tab SSH Tunnel enter your data. Important is that there has to be an upper quotation mark (") in the password
3.  Save Settings and try to connect
4. Then I get an Failure

## Current behavior
If I want to use an upper quotation mark (") in the SSH Tunnel Settings I can't connect to the Server. 

## Expected behavior
It should be possible to use upper quotation mark (") in the pasword of the SSH tunnel Settings.
If I use the same credentials in putty it works. 

## Possible solution

correct escaping of  passwords with upper quotation mark (")

## Environment

* **HeidiSQL version:** 
9.5.0.5278 (64 Bit)
* **Database system and version:** 
  MySQL 5.7.21
* **Operating system:** 
  Win 10 64 Bit

**Comment by ansgarbecker** [comment]
Could you please give a hint on how I should escape double quotes? I find quite some references on the net, but highly insonsistent. Some say it has to be a duplicated double quote, some say it needs to be escaped by several (up to 3) backslashes, plus an additional double quote. I'm confused.

**Comment by ansgarbecker** [comment]
@danitxo or @EvilKarter could someone please update to the latest build and check if double quotes in passwords are now working?
