### ISSUE TITLE
First tab does not clear on double click

### ISSUE THREAD

**Issue by anselal** [HeidiSQL/HeidiSQL#263]
## Short Description

Double clicking on the first tab does not clear the tab

## Steps to reproduce this issue

1. Double click on the first tab

## Current behavior

Nothing happens

## Expected behavior

Clear the tab. This worked in previous versions

## Possible solution

Check previous code

## Environment

* **HeidiSQL version:** 
      9.5.0.5278
* **Database system and version:** 
      MySQL 5.5.60-0
* **Operating system:** 
      Ubuntu 14.04.1

**Comment by alexdb88** [comment]
I think this feature was removed on purpose..
https://github.com/HeidiSQL/HeidiSQL/commit/e84e894164f3e2d11c526635fb7a329e9e6af6d2

Now, if you open a file in the first tab, there's no way to close that file..

**Comment by anselal** [comment]
Thank you @alexdb88, I left some comments there. I hope someone will fix this soon..

**Comment by ansgarbecker** [comment]
> Now, if you open a file in the first tab, there's no way to close that file..

Well, there is: just use rightclick > Clear in the editor, or press the shortcut <kbd>Ctrl+W</kbd>.

**Comment by ansgarbecker** [comment]
See #231
