### ISSUE TITLE
wine: access violation on start on latest nightly

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#265]
## Steps to reproduce this issue

1. wine HeidiSQL_9.5.0.5278_Setup.exe
2. install
3. start heidisql
4. Then I get...

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2008884/bugreport.txt)

## Current behavior

![screenshot from 2018-05-16 07-30-08](https://user-images.githubusercontent.com/3911428/40114457-fe7f44fc-58da-11e8-9776-ec8d54263ac6.png)

## Environment

ubuntu 17.10 with wine 3.0

* **HeidiSQL version:** 
  
HeidiSQL_9.5.0.5278_Setup
* **Database system and version:** 
  
* **Operating system:** 
  
Ubuntu 17.10 with wine 3.0

**Comment by ansgarbecker** [comment]
Did you overwrite Direct2D as stated on the [download page](https://www.heidisql.com/download.php)?

**Comment by sirber** [comment]
Oops... no sorry. The fix worked. Thank you!

**Comment by rentalhost** [comment]
Is not possible check this option in some moment, set and reopen HeidiSQL automatically? Other option is a bit hackish, that is rename real "heidisql.exe" to another name, and create a very simple new one "heidisql.exe" to just check things like that and open the real HeidiSQL.
