### ISSUE TITLE
Replace default shortcuts CTRL + 1..5

### ISSUE THREAD

**Issue by jcfaria** [HeidiSQL/HeidiSQL#27]
Please, remove from the default shortcuts those related to go to bookmarks of the SynEdit component. By default CTRL + 1..5 are set to change the main TabSheet focus, forcing the user to use only the restricted set of CTRL + 6..9.

**Comment by rentalhost** [comment]
Did you have some better solution for this case? 

I think that CTRL + 1..5 is reasonable here for common users, once that you could replace it on Preferences dialog (Shortcuts > Various > Tab 1..5).

**Comment by ansgarbecker** [comment]
Closing due to no feedback.
