### ISSUE TITLE
User management having problems with underscores in schemas name

### ISSUE THREAD

**Issue by antoniopaisfernandes** [HeidiSQL/HeidiSQL#271]
## Steps to reproduce this issue

1. Create a schema with an underscore in it's name (EXAMPLE_TEMP)
2. In the 'User management' section, try to add a permission to it
4. Then HeidiSQL backslashes the underscore in the schema name

![image](https://user-images.githubusercontent.com/6171197/40321116-ef4e8caa-5d25-11e8-9397-26c6a3723b4b.png)

## Current behavior

HeidiSQL backslashes the underscore in the SQL executed

## Expected behavior

The underscore is a valid character and it should not be backslashed.

## Environment

* **HeidiSQL version:** 
Version 9.5.0.5278 (64 Bit)
* **Database system and version:** 
MariaDB 10.2.15
* **Operating system:** 
Windows 10 for client and CentOS 7 for server

**Comment by ansgarbecker** [comment]
Yes, underscore is valid, but it's also a wildcard. See here for documentation: https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html
So, HeidiSQL escapes the underscore to ensure `MYCPC\_SI` only matches "MYCPC_SI" but not `MYCPXSI` or whatever.
