### ISSUE TITLE
🍀 Some tables have blob column are weird.

### ISSUE THREAD

**Issue by BrianMSon** [HeidiSQL/HeidiSQL#273]
## Steps to reproduce this issue

1. Create a table on query tab.
CREATE TABLE `x_blobtest` (
	`number` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`name` VARCHAR(1000) NOT NULL DEFAULT '',
	`image` BLOB NULL,
	PRIMARY KEY (`number`)
)
COLLATE='latin1_general_ci'
ENGINE=InnoDB;

2. Insert data.
insert x_blobtest values(1, 'abcdefg', 0x58CB8ADC3010FC179D7D50B7FA61FB6F02D9432E61992C24B0ECBF67);
insert x_blobtest values(2, '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 0x58CB8ADC3010FC179D7D50B7FA61FB6F02D9432E61992C24B0ECBF67);

3. Select table.
select * from x_blobtest;

4. Edit `name` column on Result Grid Tab and apply.
Or Just copy `image` blob value which `name` column is over 256 letters on Data Tab.

5. Then the `image` blob column value is changed.
Or the copied value is changed.

## Current behavior

Changed From
0x58CB8ADC3010FC179D7D50B7FA61FB6F02D9432E61992C24B0ECBF67
To
0x583F3F103F3F50B7FA613F023F2E613F24B0ECBF67

Before
![image](https://user-images.githubusercontent.com/8359891/45746017-297ec180-bc3d-11e8-8841-a6143c5fa9d4.png)

After (Edit the second row NAME column with F2)
![image](https://user-images.githubusercontent.com/8359891/45746023-2edc0c00-bc3d-11e8-8f0e-963e60aa6cbe.png)

## Expected behavior

Blob column value must not change.

## Possible solution

The real value is not changed.
But the Result Grid or Data Tab view data is shown like changed.
Data Tab column length may be 256 limit.
It's overflow and affect to next column.

## Environment

* **HeidiSQL version:** 9.5.0.5278

**Comment by BrianMSon** [comment]
This bug partially fixed on version 9.5.0.5293. (Fixed only on the Result Grid)
But, Remained on the Data tab view.

**Comment by ansgarbecker** [comment]
Please retry with v12.0 - should be fixed.
