### ISSUE TITLE
Flicker in the editor window when executing SQL

### ISSUE THREAD

**Issue by jcfaria** [HeidiSQL/HeidiSQL#28]
* HeidiSQL version: 9.4.0.5190
* Database system + version: MariaDB
* Operating system: Windows

A flicker in the editor window is visible whenever an SQL statement is executed. I believe this is related to the definition of the parent of TDBGrid created in runtime to display the query result. So, creating an invisible parent on the main screen can be one of the ways to workaround this

**Comment by rentalhost** [comment]
Maybe you mean that flicker?

![image](https://user-images.githubusercontent.com/421851/36103325-346758f8-0ff6-11e8-9057-713222957c8b.png)

**Comment by ansgarbecker** [comment]
Closing due to no feedback.

Also, the same was already reported in #410
