### ISSUE TITLE
Popup for enter passphrase without input-element

### ISSUE THREAD

**Issue by andreybatalof** [HeidiSQL/HeidiSQL#284]
## Steps to reproduce this issue

1. Create new session
1. Choose network type "MySQL SSH-tunnel"
1. Go to SSH-tunnel settings, set host, port, username, choose private key file (which contain passphrase)
1. Go to Settings, set hostname, username, password, port
1. Click "open"

## Current behavior

Popup without input-element, only "ok" button.
![2018-06-09_11h36_41](https://user-images.githubusercontent.com/32363367/41187685-6677df4a-6bd9-11e8-950f-3fb686bbd9db.png)

[Window Title]
Information
[Main Instruction]
PLink:
[Content]
Passphrase for key "rsa-key-20170807": 
[OK]

## Expected behavior
Similar popup, but with input-element for passphrase write.

## Possible solution

add input-element

## Environment
OS Windows 10 professional 64 bit 

* **HeidiSQL version:** 
versions 9.5.0.5196, 9.4.0.5125

* **Operating system:** 
OS Windows 10 professional 64 bit

**Comment by baranelitez** [comment]
I'm suffering from the same issue. This is a needed feature.

**Comment by marcuslsouza** [comment]
> I'm suffering from the same issue. This is a needed feature.

Me too!

**Comment by AskAlice** [comment]
;-;

**Comment by ansgarbecker** [comment]
Should work now, at least if the message does not change in newer plink versions:

![grafik](https://user-images.githubusercontent.com/7986591/69903628-49ab2400-139c-11ea-8c63-c226e6115ef5.png)
