### ISSUE TITLE
Issue/Enhancement: can't connect to DB in a Vagrant VM via SSH, plink.exe needs different parameters

### ISSUE THREAD

**Issue by Yuuseki** [HeidiSQL/HeidiSQL#286]
## Steps to reproduce this issue
Not so much of an issue with Heidi itself, this is more of an enhancement or feature suggestion/wish:

I'm developing on Windows 10 for the OXID eCommerce platform via their official VM: https://github.com/OXID-eSales/oxvm_eshop
I followed the instructions to the point "Quick Start -> Start the VM". Try to establish a DB connection via SSH in HeidiSQL like this: 
https://imgur.com/3Y5Kvci.png
https://imgur.com/tKPwPU2.png

## Current behavior
It timeouts after a while. It worked one time, so it's not a general problem. I found out that executing plink.exe with just user@host -pw "*****" works much more reliable.

## Expected behavior
successful connection

## Possible solution
I think a nice solution would be to give us a "custom parameters" input field, like this: https://imgur.com/TjtdToi
when this input field is used, Heidi should call plink.exe only with `-ssh user@host -pw "pw"` and the content of the input field, nothing else. More control in the hands of the user would be nice :)

## Environment
Windows 10 v1803
oxvm_eshop
OXID VirtualBox VM
https://github.com/OXID-eSales/oxvm_eshop
https://docs.oxid-esales.com/developer/en/6.0/getting_started/installation/environment_preparation.html

* **HeidiSQL version:** 
9.5.0.5196 x64

Thanks for your time, would like to see that in a future build.

**Comment by ansgarbecker** [comment]
If the user had to write half of the command line then there is no need for a GUI like Heidi's session manager.

Which parameter are you missing?

**Comment by codexp** [comment]
please consider this:
https://bjornjohansen.no/ssh-timeout

it should be possible to setup ssh in it's config to have less timeouts.

**Comment by ansgarbecker** [comment]
@Yuuseki without that `-L` parameter, there would be no tunnel, and that `-N` just means: "don't start a shell/command". So I'm not understanding what you are trying to achieve with a user written plink command. You can of course do that already, by using a separate process, but I suppose that's also not what you want. Anyway, I think removing these both parameters is not a reasonable idea.
