### ISSUE TITLE
Collations from mysql/mariadb Server not respected

### ISSUE THREAD

**Issue by wrufeger** [HeidiSQL/HeidiSQL#287]
## Current behavior

character_set_client, character_set_connection, character_set_results and collation_connection are set to defaults on every start of the program. It neither accepts defaults set on server nor it is possible to set individual defaults in heidisql.

With this, edited tables are sometimes set to the wrong collation

* **HeidiSQL version:** 
  9.5.0.5278
* **Database system and version:** 
  5.5.60-0+deb7u1
* **Operating system:** 
 Windows 10 64bit

**Comment by ansgarbecker** [comment]
I was just examining that and tried to provide a collation selector in the session manager.
However, I'm confused as setting `collation_connection` seems to only have an effect on `character_set_connection`, and I don't see why the other two `character_set_client` and `character_set_results` should still be different.
Also, MySQL 4.x does not seem to support these variables/settings - the only way here seems to call `mysql_set_character_set()`.

**Comment by ansgarbecker** [comment]
The reason for HeidiSQL not using the default from the server is that many servers run with latin1_swedish_ci, while HeidiSQL supports (and expects) UTF-8. This was even worse at the time I implemented UTF-8 support many years ago. That hardcoded call to `mysql_set_character_set(handle, 'utf8')` made me safe against user mistakes and data loss.

**Comment by ansgarbecker** [comment]
https://www.heidisql.com/forum.php?t=39162

**Comment by ansgarbecker** [comment]
Next build only changes the character set on startup if the current one does not start with "utf". If that's the case, the user gets a clear message in the log about previous and new charset:
```
/* Changing character set from latin1 to utf8mb4 */
/* Characterset: utf8mb4 */
```
Note that the character set seems also be affected by the used library. While the newer `libmariadb.dll` seems to set utf8mb4 by default, the older `libmysql.dll` v6.1 seems to force latin1, even if the server has a different setting. No clue why the libraries themselve change the charset at all. Good that HeidiSQL now verifies the charset before changing it.

**Comment by ansgarbecker** [comment]
Well, we have a new issue, reported in the forum: https://www.heidisql.com/forum.php?t=39278
Some servers seem to report `utf8mb4` via `mysql_character_set_name()`, so HeidiSQL does not set it on startup. But `character_set_client` then has a latin1 charset, and I can't find out why.
