### ISSUE TITLE
Can not update JSON field

### ISSUE THREAD

**Issue by ghost** [HeidiSQL/HeidiSQL#289]
## Steps to reproduce this issue

1. Create a table with a JSON field
2. try to update it with Heidi

## Current behavior
error  "o Rows updated when there should be 1"

## Expected behavior
to update the field

**Comment by knoxcard** [comment]
What if you make the field LONGTEXT instead of JSON?  I use an ORM called Sequelize.  Sequelize saves the JSON data in LONGTEXT fields. 

The JSON data type provides these advantages over storing JSON-format strings in a string column:
```

Automatic validation of JSON documents stored in JSON columns. Invalid documents produce an error.
Optimized storage format. 

JSON documents stored in JSON columns are converted to an internal format that permits quick read access to document elements. When the server later must read a JSON value stored in this binary format, the value need not be parsed from a text representation. 

The binary format is structured to enable the server to look up subobjects or nested values directly by key or array index without reading all values before or after them in the document.
```

https://stackoverflow.com/questions/10201957/should-i-use-blob-or-text-for-json-in-mysql

**Comment by ecxod** [comment]
OKAY with LONGTEXT its working, but then why is that JSON field there ?

**Comment by rbraband** [comment]
Did u use a ID column? I tried to replicate the bug and noticed that the error occurs when the table does not have a primary key. This is because the JSON field type validates the data and addresses it internally via PRIMARY_KEY.

**Comment by ecxod** [comment]
I switched to LONGTEXT.
I never tried again as I use LONGTEXT now, and with LONGTEXT there are
no issues

Mit freundlichem Gruss
Christian Eichert

+++ sent from a old slow computer +++

Am 06.02.2019 um 20:07 schrieb Roland Braband:
