### ISSUE TITLE
Multi-Column Filter Faulty Behavior

### ISSUE THREAD

**Issue by H4NNE5** [HeidiSQL/HeidiSQL#292]
## Steps to reproduce this issue

1. In Table A I enter a phrase into the Multi Column Filter and click on Apply and the desired search results are displayed

2. I go to Table B in which the same search string is also present. At the multi-colum filter, where the previous phrase is still present, I click on Apply again and the desired results are NOT displayed. In the command window the command from the last search is executed again though a different string is present in the search form.

## Current behavior

Described above

## Expected behavior

The software should always use the search string that is present in the search form.

* **HeidiSQL version:** 
9.5.0.5278 (64 Bit)

**Comment by ansgarbecker** [comment]
I think this is a misunderstanding. I just did the same as you, and both times I click on the Apply button an OR-filter for the current table. Nothing wrong in my eyes. You should probably post a screenshot of Heidi on table A and on table B.

**Comment by H4NNE5** [comment]
Hi,
Please check the screenshots.
Its about the column "CntxPN".
In Table B you can see that it only shows an entry from the previous
filtering.
Only if I paste or alter the phrase in the Multi-Colum search form, then a
command with the new phrase is executed. But before that the software
filters for "%cfy%"


2018-06-20 18:58 GMT+02:00 Ansgar Becker <notifications@github.com>:

**Comment by ansgarbecker** [comment]
Forgot the screenshots?
Btw, you need to go into this issue on Github to be able to post screenshots. If you just send a reply per mail, only the text gets stored.

**Comment by H4NNE5** [comment]
Oh I didn't know that.
Here they are:
![heidi_tableb_afterapply](https://user-images.githubusercontent.com/13788309/41674038-108bc3f0-74bf-11e8-8459-9eb7f1fde417.png)
![heidi_tablea_afterapply](https://user-images.githubusercontent.com/13788309/41674039-10a5d70e-74bf-11e8-946a-bdc531442e7e.png)

**Comment by ansgarbecker** [comment]
Ok, but that's already the case, isn't it? When I change the previous search word to something else, a new filter is generated.

**Comment by H4NNE5** [comment]
Yes, but if you don't enter a new word and just click Apply with the filter
phrase from table A still present, that's what my complaint is about.
I have to alter data in different tables related to the same phrase and
it's annoying to paste the same phrase again several times .


Ansgar Becker <notifications@github.com> schrieb am Mi., 20. Juni 2018,
19:41:

**Comment by ansgarbecker** [comment]
> Yes, but if you don't enter a new word and just click Apply with the filter phrase from table A still present

But that's not true. At least not here. The filter text is never from a different table. Either it's empty, or it is restored from a previous click on table B.

**Comment by H4NNE5** [comment]
Hi, please check out the video that I made: 
https://youtu.be/fjOYNc1KUIg

**Comment by H4NNE5** [comment]
We both figured that out already, but how do you think about that? I think this is a wrong behavior as the software does not do what the user (is it just me?) expects.

**Comment by H4NNE5** [comment]
So could you please change that in upcoming versions?

**Comment by ansgarbecker** [comment]
I am against that change. Current behaviour might seem unfomfortable to you, but it has its sense.
Also, please note how typing into the form already generates the filter text, not the button.
