### ISSUE TITLE
Sorting large result on query tab takes veeery long

### ISSUE THREAD

**Issue by ilopez** [HeidiSQL/HeidiSQL#293]
## Steps to reproduce this issue

1. Execute query with any number of columns, but a large number of rows. 
2. Click on table output heading to sort
3. Observe UI Lockup while the table is sorting

## Current behavior

The application on windows will gray out as no user input is being processed.

## Expected behavior

Expected to sort quickly, or not block the UI.

## Possible solution

Allow for the user interface to continue, and not block the UI.
or
Allow for the user to cancel the sort operation.
or
Offer a warning to users to indicate the sorting "X" number of rows can cause the UI to lockup; possibly set the warning level to 1k rows, and allow the warning to be turned off and on through application settings.

## Environment

* **HeidiSQL version:** 
9.5.0.5196

**Comment by ilopez** [comment]
https://github.com/HeidiSQL/HeidiSQL/issues/107 - Seems like a similar issue.
However, I did check the mysql process list and do not see my query executing there.

**Comment by mfaustusi** [comment]
This happens still on 10.1.0.5464. Sort a modest amount of rows in the grid (30000) it will freeze for roughly a minute. It does not modify the original query but appears to be doing it in ram using a very slow algorithm (hopefully not bubble sort). Perhaps switching to a better algorithm could get those times down to well under a second?  As comparison, PHP (not the fastest of languages) can readily sort 250k rows in ram in roughly 200ms on the same hardware, and 2.5 million rows in 2.5 seconds, so there is something definitely not right with grid sorting in HeidiSQL.

**Comment by ilopez** [comment]
That is how I am surprised by it, I bet its an underlying issue with the grid that is used to display data. 

I'm also wondering if there is an interim solution to disable sorting if the row size is greater than 1000 items. Annoying sure, but what is super disappointing is to get a 100K row result set, accidentally sort it, and lose the SQL query you were developing.  Sometimes I'll wait the 30 or so minutes because I need that SQL.  

Good excuse for a tea break, but nonetheless.

**Comment by ansgarbecker** [comment]
I just played a bit with VirtualTree's `OnCompareNodes` event and the underlying call to `OnGetText` for each single node. Even if I simplify these to the absolute minimum, sorting is still very slow, for a result with more than ~5000 rows. So I guess I need a different approach, as you said, with more than 1000 rows, refire the query or something like that.

**Comment by sergiuhlihor** [comment]
It this going to ever be fixed? From usage point of view, it's very easy to ignore how many rows are loaded and attempt to sort on it and then have to kill the tool completely. Based on execution time, it looks like some kind of O(N^2) operation in background as execution time seems to be increasing quadratically. A good sorting is always O(NlogN) maximum.

**Comment by bradjorgensen** [comment]
bump, this is still relevant

**Comment by sergiuhlihor** [comment]
If fixing this is technically difficult, could there be a workaround implemented? Like a GUI freeze timeout where view would be reset to default after X seconds? Pressing instinctively on column for sorting makes the HeidiSQL fully unusable if having more than 50000 entries. After spending half hour to write a very complex query that lead to 240K entries, I am now waiting for half hour for a simple sorting to finish. Sorting 240K entries in N log N = 240 000 * 18 = 4 320 000 cycles. Assuming a cycle of 100 CPU clock cycles, this would take 432 000 000 clock cycles = ~0.1 seconds on a modern CPU. Hate to say, but sorting is the biggest shame of this tool, would greatly appreciate if anything could be done.

**Comment by sergiuhlihor** [comment]
Could this also be considered a **Bug** instead of an **Enhancement**? It leads to UI freezing for minutes/hours or apparently indefinitely.

**Comment by ansgarbecker** [comment]
Well you can always write some `ORDER BY` clause instead, or?
A fix for that slow logic would anyway just refire the query with an additional clause. But I'm hesitating to touch the user's SQL code automatically. Feels invasive somehow.

**Comment by sergiuhlihor** [comment]
Cannot speak for others but I use column order on a regular basis when quickly inspecting some data and then fallback on ORDER BY only when I am writing some final report. And many times instinctively I press on column before seeing the number of results. 
There is no need to touch the SQL. You can just load whole data in memory and just sort & refresh the view. Since tool is usable up to 500 000 - 1 000 000 entries, the point where running out of memory because you cannot keep the data is usually way ahead of the usability point. Right now, the sorting usability stops around 3000-5000 entries, way below the GUI limits.

**Comment by ansgarbecker** [comment]
So, this is my workaround here, taken from your proposal in your first comment:
* click on column header asks for confirmation if grid contains more than 10000 rows
* that number is customizable, in Tools > Preferences > Grid formatting

![grafik](https://user-images.githubusercontent.com/7986591/83322176-c5a3fd00-a255-11ea-90fb-971ab1344e38.png)

![grafik](https://user-images.githubusercontent.com/7986591/83322184-d3598280-a255-11ea-92f7-bcad7ef53698.png)

Please update to the next upcoming build and test.

**Comment by sergiuhlihor** [comment]
Thank you! The workaround will be greatly appreciated!
