### ISSUE TITLE
Export does not stop if destination db does not exists

### ISSUE THREAD

**Issue by endo64** [HeidiSQL/HeidiSQL#299]
## Steps to reproduce this issue

1. use table tools / SQL Export
2. output a large schema to another server
2.1. don't select Create database
2.2. select "Same as on source server"
2.3. be sure that the db doesn't exists on destination server
3. start exporting

## Current behavior

I get `Unknown Database` for each table for the source database.

## Expected behavior

If `Unknown Database` error happens whole process should stop

## Possible solution

Could be related to #285 

## Environment

* **HeidiSQL version:** 

Version 9.5.0.5278 (64 Bit)

* **Database system and version:** 

MySQL / MariaDB

**Comment by ansgarbecker** [comment]
Confirmed. I get the repeated error for each table:

![grafik](https://user-images.githubusercontent.com/7986591/47155311-b5d7df00-d2e4-11e8-96fc-fb02d5019031.png)

**Comment by ansgarbecker** [comment]
Especially for error code 1049, Heidi now cancels processing in the export dialog.

I wonder whether it makes sense to cancel on _all_ errors during the export. For example on error code 1044 ("access denied for user x to database y"), it makes little sense only to proceed with remaining tables, does it?

**Comment by endo64** [comment]
I agree better to cancel the operation on most errors, but may be not all. If possible, showing a popup to user, asking to continue (and a checkbox to continue on all errors in the current operation) would be the best solution. 
Or we can choose "some" error to cancel and others continue.

**Comment by fifonik** [comment]
Are you sure that you really want to stop it?
It might be commands later in the dump related to other database(s)...
