### ISSUE TITLE
Access violation when opening table with huge ENUM definition

### ISSUE THREAD

**Issue by maurolog** [HeidiSQL/HeidiSQL#3]
First of all, sorry for my bad English...

## Expected behavior

normal display of selected table (data / structure) in HeidiSQL

## Current behavior

HeidiSQL crashes (only with some tables)

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. Run attached table creation script
2. try opening the table just created (tbl_tipoprestazione_test), structure or data, no matter
3. HeidiSQL crashes...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.4.0.5184 (last working version 8.3.0.4784)
* Database system + version: MySQL 5.6.35 (but not relevant)
* Operating system: Windows 7 Enterprise 32bit

### Failure Logs

Heidy does not allow to save the error log (it hangs before), you can only print the attached image.
Thanks for what you can do,
Mauro

[CreateTestTable.txt](https://github.com/HeidiSQL/HeidiSQL/files/1447285/CreateTestTable.txt)
![errorcapture](https://user-images.githubusercontent.com/33426464/32456180-fa19249c-c324-11e7-989d-703442c1e9d4.PNG)

**Comment by ansgarbecker** [comment]
This crash happens in SynEdit's regular expression logic, due to a 10KB string with 433 enum items (!) on the fourth table column "TriCausaleContatto". Probably fixable only in SynEdit. I'm checking that.

**Comment by ansgarbecker** [comment]
I have just simplified the parsing logic a bit in 88bb7eb376d671691954601ab19b049f4e8595c7 , so such huge length/set definitions don't break SynEdit.

Please download the latest build and give feedback.

**Comment by maurolog** [comment]
Hi Hansgar, I updated to the latest version and tried to open various critical tables ... everything Ok now! thanks so much for the quick fix of the problem! Mauro

**Comment by ansgarbecker** [comment]
Thanks for your quick feedback!
