### ISSUE TITLE
Searching numbers is functionally broken

### ISSUE THREAD

**Issue by Beep6581** [HeidiSQL/HeidiSQL#30]
Last reproduced in 9.4.0.5188 though it's been like this since I started using HeidiSQL two years ago.

A bigint column is formatted for example like this:
`99 015 124 722 666`
which is fine when viewing data, is makes reading it much easier.

If you edit the field, it changes to
`99015124722666`
No spaces. Fine again.
![imgur-2017_12_05-12 13 55](https://user-images.githubusercontent.com/5844619/33604320-d01bd462-d9b5-11e7-9c3a-4a270962e346.png)

However, if you want to search for "22666", 0 matches.
Why? Because you actually have to search for "22 666", notice the whitespace.

The digit grouping symbol - whitespace - should be only used for presentation, not when searching!

![imgur-2017_12_05-12 12 15](https://user-images.githubusercontent.com/5844619/33604274-9583150e-d9b5-11e7-83d9-d8e9c4359ad3.png)

**Comment by ansgarbecker** [comment]
I guess I could temporarily disable local number formatting while the search dialog is open.

**Comment by ansgarbecker** [comment]
Should work as expected in latest nightly build, which is on the way to be compiled.

**Comment by Beep6581** [comment]
@ansgarbecker fix confirmed, thank you!
