### ISSUE TITLE
Get rid of build artifacts in the repository

### ISSUE THREAD

**Issue by v7a** [HeidiSQL/HeidiSQL#300]
You should alter your .gitignore file to ignore out/\*\*, .tx/\*\* and other directories that contain build artifacts.

**Comment by ansgarbecker** [comment]
out/** would be wrong as there are versioned files in it.
What's wrong with the file suffixes in .gitignore?

**Comment by v7a** [comment]
Hi,

files that are necessary for the build should not be placed in build artifact directories e.g. out, build or bin. If that is for some reason not possible, the following .gitignore additions may be a solution:

* `out/*.dll`
* `out/plugins*/*.dll`

I've never worked with Delphi before, but I am pretty sure that it consists of a neat dependency system that can be used instead of uploading binary files to the repo :)

Best regards
