### ISSUE TITLE
Feature request: filter in database tab

### ISSUE THREAD

**Issue by pksr** [HeidiSQL/HeidiSQL#301]
It would help me a lot, if you'd add a filter to the database tab. Or did I miss this feature?
Thanks.

![example](https://user-images.githubusercontent.com/2913078/42438560-a10f5aa4-8360-11e8-9f4a-af39862ed8f9.jpg)

**Comment by ansgarbecker** [comment]
You can activate the filter panel using <kbd>Ctrl+Alt+F</kbd> or click Edit > Filter panel. It's then at the very bottom. And it works not only on the Database tab but on nearly all main tabs.

**Comment by rentalhost** [comment]
Wow! It is a very cool feature that I don't know until now. 

I think that you can do something new with this tool:
1. Make it enabled by default;
  a. If user closes it first time, remember that it could be reenabled via Edit / Filter option;
2. Give a touch of style (it's very simple currently);
3. (Bug?) When you open it and closes via 'x', the Edit / Filter options keep enabled;
4. Move the Table/Database filter to bottom, to stay on same position than Filter bar;

**Comment by penCsharpener** [comment]
👍  to "Make it enabled by default" but would vote for bring the regex filter up under the other filters
also make the field wider to show longer, more complex regex
