### ISSUE TITLE
Full blobs loaded in grid

### ISSUE THREAD

**Issue by jelmerjellema** [HeidiSQL/HeidiSQL#302]
## Steps to reproduce this issue

1. Create a table with a longblob
2. Fill the table with a lot of records, each containing a large longblob
3. Open the table in the datagrid

## Current behavior
Loading takes a long time because all the blobs are loaded in the select statement

## Expected behavior
Blobs are not loaded during the select, but only after explicitly "opening" a record by changing something or opening the blob editor. This should at least be a preference.

## Environment

* **HeidiSQL version:** 
9.5.0.5280
  
* **Database system and version:** 
MariaDB 10.2.16

**Comment by ansgarbecker** [comment]
This is the case normally... I wonder what you exactly did to get the full columns in the SELECT query?

**Comment by jelmerjellema** [comment]
I thought so too! I don't think I did anything to provoke this behaviour. Sure would like to know how to get rid of it though ;-)

**Comment by ansgarbecker** [comment]
Oh I forgot there is exactly one situation in which that happens: when the table has no primary key, and no non-null unique key. In that case Heidi needs all data immediately, to make UPDATEs and DELETEs most stable.

Is that the case for that table?
Could you please post the `CREATE TABLE` code of it here?

**Comment by jelmerjellema** [comment]
Yeah, i read about that, makes sense. But I do have primary keys:

``
CREATE TABLE `ondertekening` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`naam` VARCHAR(200) NOT NULL COMMENT 'Naam ondertekenaar' COLLATE 'utf8_unicode_ci',
	`datum` CHAR(10) NOT NULL COMMENT 'YYYY-MM-DD' COLLATE 'utf8_unicode_ci',
	`doc` LONGBLOB NOT NULL COMMENT 'pdf - document met handtekening',
	`docnr` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Intern documentnummer' COLLATE 'utf8_unicode_ci',
	`createdAt` DATETIME NULL DEFAULT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COMMENT='Een ondertekening door opdrachtgever van een verantwoording of opdracht'
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
AUTO_INCREMENT=53
;
``

**Comment by jelmerjellema** [comment]
Hi Ansgar,

Thanks for checking in on this. I just tried it out and it behaves normally now, with left(..). I guess it was just something in some nightly build back then.

Thanks & best regards, Jelmer

**Comment by ansgarbecker** [comment]
Thanks a lot for your quick feedback!
