### ISSUE TITLE
Crashes very often

### ISSUE THREAD

**Issue by stahl-riesa** [HeidiSQL/HeidiSQL#303]
Only open a connection, then click after clicking the cross icon to close the window HeidiSQL crashed.

bugreport:
date/time          : 2018-07-10, 16:01:24, 842ms
computer name      : xx
user name          : pfischer
registered owner   : user
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : German
system up time     : 6 hours 8 minutes
program up time    : 6 seconds
processors         : 2x Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz
physical memory    : 1074/3806 MB (free/total)
free disk space    : (C:) 68,36 GB
display mode       : 1920x1080, 32 bit
process id         : $e74
allocated memory   : 73,70 MB
largest free block : 1,27 GB
executable         : heidisql.exe
exec. date/time    : 2018-07-10 13:39
version            : 9.5.0.5280
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $100073b1, $17e0cabf, $17e0cabf
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 100073B1 in module 'libpq.dll'. Write of address 00190018.

main thread ($1b58):
100073b1 libpq.dll
100052fc libpq.dll                             PQfinish
00866ed6 heidisql.exe dbconnection    2011 +47 TPgConnection.SetActive
00988f34 heidisql.exe Main            2205 +52 TMainForm.ConnectionsNotify
0040c9a4 heidisql.exe System           196  +0 DynArraySetLength
0088d4a2 heidisql.exe dbconnection      38  +0 {System.Generics.Collections}TList<dbconnection.TDBConnection>.Notify
0088e117 heidisql.exe dbconnection     728  +0 {System.Generics.Collections}TObjectList<dbconnection.TDBConnection>.Notify
0088dcb0 heidisql.exe dbconnection     728  +0 {System.Generics.Collections}TList<dbconnection.TDBConnection>.DeleteRange
0088d308 heidisql.exe dbconnection      38  +0 {System.Generics.Collections}TList<dbconnection.TDBConnection>.SetCount
0067ba89 heidisql.exe Vcl.Forms                TCustomForm.DoDestroy
0067b8da heidisql.exe Vcl.Forms                TCustomForm.Destroy
004a6b05 heidisql.exe madExcept                InterceptClassDestroy
004084c4 heidisql.exe System           196  +0 TObject.Free
0053a5f3 heidisql.exe System.Classes           TComponent.DestroyComponents
00679669 heidisql.exe Vcl.Forms                DoneApplication
0044c415 heidisql.exe System.SysUtils          DoExitProc
0040a019 heidisql.exe System           196  +0 @Halt0
009c5c2d heidisql.exe heidisql          82 +26 initialization
758a343b kernel32.dll                          BaseThreadInitThunk

**Comment by mimmi20** [comment]
I got this bugreport today:

date/time          : 2018-08-10, 09:42:57, 203ms
computer name      : DESKTOP-3HAUV19
user name          : Nutzer <admin>
operating system   : Windows 10 x64 build 17134
system language    : German
system up time     : 57 minutes 32 seconds
program up time    : 41 minutes 3 seconds
processors         : 16x AMD Ryzen 7 PRO 1700X Eight-Core Processor
physical memory    : 10231/16338 MB (free/total)
free disk space    : (C:) 134,50 GB
display mode       : 1920x1080, 32 bit
process id         : $109c
allocated memory   : 87,03 MB
largest free block : 131025,96 GB
executable         : heidisql.exe
exec. date/time    : 2018-08-10 09:01
version            : 9.5.0.5284
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $987653d3, $62ab3886, $62ab3886
exception number   : 6
exception class    : EInvalidOp
exception message  : Invalid floating point operation.

main thread ($2558):
0040b3e0 heidisql.exe System                  @Trunc
009a64a4 heidisql.exe apphelpers     1085  +1 FormatTimeNumber
00adcdd0 heidisql.exe dbconnection   4897 +29 TDBConnection.ConnectionInfo
00c748be heidisql.exe Main           1322 +18 TMainForm.StatusBarMouseMove
00696a29 heidisql.exe Vcl.Controls            TControl.MouseMove
00696b04 heidisql.exe Vcl.Controls            TControl.WMMouseMove
0040d90e heidisql.exe System                  TObject.Dispatch
00695ca3 heidisql.exe Vcl.Controls            TControl.WndProc
0069d36e heidisql.exe Vcl.Controls            TWinControl.WndProc
0069c5aa heidisql.exe Vcl.Controls            TWinControl.MainWndProc
005dce43 heidisql.exe System.Classes          StdWndProc
7ff9ed1a USER32.dll                           DispatchMessageW
008157bf heidisql.exe Vcl.Forms               TApplication.ProcessMessage
00815833 heidisql.exe Vcl.Forms               TApplication.HandleMessage
00815d1f heidisql.exe Vcl.Forms               TApplication.Run
00cd4b77 heidisql.exe heidisql         80 +24 initialization
7ff9eb8f KERNEL32.DLL                         BaseThreadInitThunk
7ff9ed87 ntdll.dll                            RtlUserThreadStart

**Comment by ansgarbecker** [comment]
@mimmi20 that's a totally different crash - please try again with the latest build and report in a new issue if that persists.

@stahl-riesa that crash was reported in #37 , according to your callstack. So this is a duplicate.
