### ISSUE TITLE
Drop Down Menu: faulty behavior

### ISSUE THREAD

**Issue by H4NNE5** [HeidiSQL/HeidiSQL#304]
## Steps to reproduce this issue

1. Step 1: Please check this forum [post](https://www.heidisql.com/forum.php?t=25398#p25492).
2. Step 2: So when selecting a drop down menu then after pressing single digit numbers(1,2,3) in some drop down menus the respective entry is not selected though it exists or only after pressing the same key for several times. It seems to work correctly for 4 and above also if there are several entries starting with this number (not the case for 1-3).

## Expected behavior

If the user presses '1' then the related entry should be selected from the drop down menu

## Environment

* **HeidiSQL version:** 
9.5.0.5280

**Comment by ansgarbecker** [comment]
This works for me, at least in the current nightly build. I have some "2: xyz" and a "23: abc" toggling each time I press "2", so I guess this is fixed?
