### ISSUE TITLE
Connection limits are not shown

### ISSUE THREAD

**Issue by matmai** [HeidiSQL/HeidiSQL#305]
## Steps to reproduce this issue

1. Open User Manager
2. Edit Limitations
3. Save
4. Limitations are not shown, even after reload/reconnect

## Current behavior
Limitations are not shown (always 0) in HeidiSQL but can be read via SQL:
![image](https://user-images.githubusercontent.com/8249305/42755764-c7982a04-88f9-11e8-9d71-21d09a2798c6.png)

Changing limits via SQL even does not affect values displayed by HeidiSQL.
```sql
GRANT USAGE ON *.* TO 'test'@'%' WITH MAX_QUERIES_PER_HOUR 5 MAX_UPDATES_PER_HOUR 4 MAX_CONNECTIONS_PER_HOUR 3 MAX_USER_CONNECTIONS 2;
```

## Expected behavior
Show current limit settings in HeidiSQL.

## Possible solution
Use SQL statements instead of HeidiSQL to show and alter limits.

## Environment
Windows 7 64bit

* **HeidiSQL version:** 
  9.5.0.5280
* **Database system and version:** 
  MySQL 5.7.22
* **Operating system:** 
  Windows 7 64bit

**Comment by ansgarbecker** [comment]
Can confirm that, even on a different server version (MariaDB 10.3.9).

The missing limitation values are likely caused by reading them from the wrong `GRANT`. For example when there are two of them:
```sql
GRANT USAGE ON *.* TO 'testuser'@'localhost'
   WITH MAX_QUERIES_PER_HOUR 10000
   MAX_UPDATES_PER_HOUR 20000
   MAX_CONNECTIONS_PER_HOUR 30000
   MAX_USER_CONNECTIONS 40000;
GRANT SELECT ON `testdb`.* TO 'testuser'@'localhost'
   WITH GRANT OPTION;
```
