### ISSUE TITLE
Count of Records in Main Screen not correct in some tables

### ISSUE THREAD

**Issue by baltazaroliveira** [HeidiSQL/HeidiSQL#309]
## Steps to reproduce this issue

1. Step 1;

Open DB and see number of records

![image](https://user-images.githubusercontent.com/953742/42931932-e2bcbb92-8b38-11e8-9188-096bff297c9e.png)

2. Step 2;

Enter in detail and get correct number of records

![image](https://user-images.githubusercontent.com/953742/42931971-f7e926c2-8b38-11e8-9a70-b8469cc5db34.png)

## Current behavior

Incorrect Number of Rows

## Expected behavior

Correct Number of Rows

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
MySql
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
Welcome to the [estimated row count in InnoDB tables](http://stackoverflow.com/questions/11926259/why-is-the-estimated-rows-count-very-different-in-phpmyadmin-results).
