### ISSUE TITLE
Selects the wrong data

### ISSUE THREAD

**Issue by Dmitrytyt** [HeidiSQL/HeidiSQL#31]
## Expected behavior
Hi!
I have the latest version of the program selects the wrong data. (9.4.05191) MySql
The older version displays a normal result.
![82](https://user-images.githubusercontent.com/14854119/33647305-85a27caa-da65-11e7-833d-6e6403988c64.png)
![84](https://user-images.githubusercontent.com/14854119/33647306-85c4ab22-da65-11e7-9e32-b7e901ce8141.png)

**Comment by ansgarbecker** [comment]
You deleted most of the issue template. Please don't do that. The template asks for things you didn't provide now, so it's unlikely to get good feedback or a fix here.

Especially it's quite impossible to say what you mean by "wrong data". Perhaps you mean the rows in one view are sorted and in the other they are not sorted? If so, watch out what's behind the blue arrow button labelled "Sort".
