### ISSUE TITLE
Query Tab Hightlight doesn't consider repeating backslach(escape char, escaped backslash)

### ISSUE THREAD

**Issue by papinianus** [HeidiSQL/HeidiSQL#310]
## Steps to reproduce this issue

1. Open Query Tab;
2. Type Some Query using escaped backslash. Like this: 
```SQL
SELECT * FROM `table` WHERE `string` LIKE '%\\' AND `int` = 1;
```
3. Then you find that "AND `int` = 1;" is displayed in green letters (which means they are string literal)

## Current behavior

All Query after "\\" are displayed in green letters.

## Expected behavior

Parse them correctly as escaped backslashed, like escaped quote("\'")

## Environment

* **HeidiSQL version:** 
9.5.0.5278
  
* **Database system and version:** 
MariaDB 10.1.25
  
* **Operating system:** 
Windows 10, 1803

**Comment by mbomb007** [comment]
I created a pull request to fix this in SynEdit: https://github.com/SynEdit/SynEdit/pull/125

**Comment by ansgarbecker** [comment]
That fix came from me, so isn't that already fixed in the current HeidiSQL version? Or did I overwrite my own fix with the official sources when updating?

**Comment by mbomb007** [comment]
It was overwritten.

**Comment by ansgarbecker** [comment]
Oh shit. Good idea to make a pull request in the original sources.

**Comment by mbomb007** [comment]
Are there other patches that may have been overwritten in the same way?

**Comment by ansgarbecker** [comment]
Yes, I suppose so. Though I recall there were some which I reverted later on, and one or two even were redone by the SynEdit guys. Anyway, I will have to go through them.

**Comment by ansgarbecker** [comment]
That above pull request was overtaken, and I updated the SynEdit sources in b97629b1e106a99b108be43e73d502114e7d09a4 . Later two commits fixed overwritten changes.
