### ISSUE TITLE
Fix typo in readme

### ISSUE THREAD

**Issue by codexp** [HeidiSQL/HeidiSQL#313]
## Steps to reproduce this issue

1. see readme

## Current behavior

typo in word "Larazus"

## Expected behavior

should be "Lazarus"

## Possible solution

type again

## Environment

n/a

* **HeidiSQL version:** 
  n/a
* **Database system and version:** 
  n/a
* **Operating system:** 
  n/a

**Comment by oliveru** [comment]
Pull Request?

**Comment by igitur** [comment]
Filling out the issue template was probably more effort than doing a pull request would have been.
