### ISSUE TITLE
Filter on Data View Doesn't work as expected

### ISSUE THREAD

**Issue by jan-obtam** [HeidiSQL/HeidiSQL#315]
## Steps to reproduce this issue

1. Connect to database
2. Click database to display tables
3. On table list view, apply filter `\b[^\d\W]+\b` (This is for filtering table names without numbers)
4. Apply filter also on database pane (left side pane) for comparison
## Current behavior
Does not filter properly on table list view but works on database pane
![image](https://user-images.githubusercontent.com/32849655/43185079-6c760e72-901d-11e8-9d68-878aab934bb6.png)

## Expected behavior
Should work on both panes.

## Environment

* **HeidiSQL version:** 
9.5.0.5255
* **Database system and version:** 
Server version: 10.0.34-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04
* **Operating system:** 
Ubuntu 16.04 (VM using Vagrant)

**Comment by jan-obtam** [comment]
@ansgarbecker Basically, it should filter out tables with numbers in the name, so tables like:
test123
table40002
etc. should be removed while tables like
table_name
test_tableName
etc. should be displayed.

**Comment by jan-obtam** [comment]
But on the right side, it doesn't filter anything. It still shows all the tables as listed.

**Comment by ansgarbecker** [comment]
Ah ok, I see now. That expression is a bit overloaded for excluding names with number. However, there seems to be some difference between the two filters.

**Comment by ansgarbecker** [comment]
Oh, I just realize this is not a bug, but indeed a feature, really. :)
On the right database panel, the filter box is not only meant to filter stuff in the _first_ column, but in all columns. So, the table names with numbers may not match, but probably the table engine, saying "InnoDB" or similar stuff without a number.

**Comment by jan-obtam** [comment]
Aha. That makes a lot of sense. But is there a way to specify which column the filter is for? My target here is to filter the tables names ONLY and export them. Our current implementation has a multi-tenant table structure, which means we have thousands of tables. In this case, I want to filter out the "non-multi-tenant" tables (i.e. tables without the numbers) so I can export them.

**Comment by ansgarbecker** [comment]
Well, not yet. It's just a basic filter.

**Comment by jan-obtam** [comment]
Alright. Thanks @ansgarbecker !
