### ISSUE TITLE
Refreshing table does not refresh the table schema on the table tab

### ISSUE THREAD

**Issue by WesDowney** [HeidiSQL/HeidiSQL#319]
## Steps to reproduce this issue

1. Step 1: Click on a table and select the table tab so you can view the columns and schema
2. Step 2: Run a command outside of HeidiSQL that changes a column for that table
3. Step 3: Right click on the table and select refresh
4. Step 4: The changes to the table columns aren't shown on the `Table` tab. If you click the `Data` tab, you should see the updated columns there.

## Expected behavior

When refreshing a table, the Data and the Table tab with the schema should both update.

## Environment

* **HeidiSQL version:** 9.5.0.5196
  
* **Database system and version:** mysql 5.7.20

**Comment by routinet** [comment]
Can confirm this issue.  Clicking refresh from the icon bar also does not refresh the table, though I do see the queries to fetch the schema.  Selecting `Tables` from the tree, clicking (or right-click selecting) refresh, and re-selecting the table yields the expected results.

![image](https://user-images.githubusercontent.com/5899388/77956588-1f149d80-72a0-11ea-91ff-cc17cdbc8424.png)

**Comment by exuvo** [comment]
The current behaviour is very confusing. The log says it has refreshed table state but the UI is still showing old table structure after a refresh. Manually running the same refresh query shows the response contains the new table structure.

**Comment by ansgarbecker** [comment]
I suppose this is fixed with my just pushed modifications. If not please shout.
