### ISSUE TITLE
Using PROCEDURE ANALYSE() will show encoded result

### ISSUE THREAD

**Issue by standus** [HeidiSQL/HeidiSQL#32]
This query 
SELECT * FROM table PROCEDURE ANALYSE();

will generate wrong result. Expected result is text, but I got encoded in hexa.

**Comment by ansgarbecker** [comment]
If the server says a column has some binary collation, then HeidiSQL displays it as such.

You can press the button "Show binary data as text" on the main toolbar, to get it readable.

Please don't just delete the issue template when reporting issues, it's there to make reports more readable and more valid.
