### ISSUE TITLE
When I use it to create a procedure, it still executes with a semicolon.

### ISSUE THREAD

**Issue by jay763190097** [HeidiSQL/HeidiSQL#322]
## Steps to reproduce this issue

1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:**  9.5.0.5282
  
* **Database system and version:** mysql 5.7 
  
* **Operating system:**  win10

**Comment by ansgarbecker** [comment]
Closed because the issue template was ignored and left empty.
