### ISSUE TITLE
PASSWORD() function (deprecated as of MySQL 5.7.6) 

### ISSUE THREAD

**Issue by phena109** [HeidiSQL/HeidiSQL#325]
## Steps to reproduce this issue

1. Run SQL server 8.0 (maybe 5.7.6) or plus 
1. Login as someone who have the privilege to change users' password;
1. Update any user's password;
1. Then I get... /* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PASSWORD('blah')' at line 1 */

## Current behavior

Unable to change user password because there is a syntax error.

/* SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PASSWORD('blah')' at line 1 */

## Expected behavior

Able to change the user password

## Possible solution

Update the hooked up sql statement with the new password update syntax (or detect which version of server a user is using and give corresponding statement)

## Environment

* **HeidiSQL version:** 
9.5.0.5249 (32 bit), downloaded from Windows Store
* **Database system and version:** 
MySqlServer 8.0.12
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
According to the [docs](https://dev.mysql.com/doc/refman/8.0/en/set-password.html), MySQL wants an unencrypted password in `SET PASSWORD`.
Should not be too complicated to do that within a version conditional.
