### ISSUE TITLE
Split CSV import INSERT every 1000 rows to avoid MSSQL error 10738

### ISSUE THREAD

**Issue by nummacway** [HeidiSQL/HeidiSQL#326]
## Steps to reproduce this issue
1. Step 1: Import a 1001+ row CSV to MSSQL.
2. Then I get MSSQL error 10738.

## Current behavior
Tries to import all rows at once.

## Expected behavior
Avoids error 10738.

## Possible solution
Split command into multiple commands of up to 1000 rows each.

## Environment
* **HeidiSQL version:** 9.5.0.5280
* **Database system and version:** MSSQL 10.0 Express named pipe

## See also
https://www.heidisql.com/forum.php?t=18227

**Comment by GPHemsley** [comment]
This is still a problem with HeidiSQL Version 11.0.0.6049 (64 Bit) and MSSQL 13.0 (SQL Server 2016).

**Comment by ansgarbecker** [comment]
Next build has a harcoded limit of 1000 rows per extended INSERT command. Reasonable not only for MSSQL, which is why I made it hardcoded.
