### ISSUE TITLE
Invalid types in INSERT if not all columns are imported from CSV

### ISSUE THREAD

**Issue by nummacway** [HeidiSQL/HeidiSQL#327]
The CSV import feature is mostly useless. If the file is missing columns, they must be the last few columns (not in-between or at the start) or the table must be of only one type.

## Steps to reproduce this issue
(Minimal example.)
1. Create a table with two columns. They must have different types and the first column must either be nullable or auto-increment.
2. Create a CSV file with values for the second column. So basically the file is a list of one value per line, not actually comma-separated.
3. Import CSV. Make sure to uncheck the first column, as it's not in the file.

## Current behavior
Heidi tries to use the first column's type to insert the second column's values as it doesn't care what you checked or not when it determines the column types.

## Expected behavior
Heidi must consider unchecked columns when determining what type to import a value as.

## Environment
each and any

## See also
#242

**Comment by fifonik** [comment]
I'm unable to re-produce the issue (HeidiSQL 9.5.0.5280 + MySQL 5.7.19).

Here are my steps:
1. Created tables and with data using the script:

```
DROP TABLE IF EXISTS src;

DROP TABLE IF EXISTS dest;

CREATE TABLE `src` (
	  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	, `val` VARCHAR(15) NOT NULL
);

CREATE TABLE `dest` (
	  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	, `val` VARCHAR(15) NOT NULL
);

INSERT INTO src (val) VALUES ('a1'), ('a2'), ('a3'), ('a4'), ('a5');

```

2. Refreshed DB

3. Clicked on 'src' table and selected Data tab

4. Right mouse button over grid | 'Export grid rows' | Excel CSV, Complete, Include column names. After this step in the z.txt file I got a single val column with values

5. Clicked on 'dest' table and then Tools | Import CSV file. Selected z.txt, changed fields terminated by fields as \t (not needed as only one column in the file), unticked id column and pressed Import! button.

6. Pressed F5 to refresh 'dest' table and checked that everything as expected.

P.S. I do not have INSERTs in log while doing import. LOAD DATA INFILE there in my case.

**Comment by nummacway** [comment]
This issue is about Heidi parsing the file (_client parses file contents_), which is your only option on MSSQL. With your settings (LOAD DATA INFILE, or _server parses file contents_), Heidi does not even convert any types, so no conversion can fail.

**Comment by fifonik** [comment]
I see.
Sorry, MS SQL was not mentioned in original post as any other settings/screenshots that could point in the right direction.

**Comment by fifonik** [comment]
I have tested again with MySQL and "Client parses file content" option selected (everything else as in my previous reply). 

HeidiSQL issued the following query on import:
`INSERT INTO `test`.`dest` (`val`) VALUES ('a1'), ('a2'), ('a3'), ('a4'), ('a5"\r');`

So there is no issue with first auto increment column, however there is an issue with last row's value (notice quote with \r added).

**Comment by nummacway** [comment]
Because I'm running into this bug again, I'm gonna post a minimal example:

1. I run this on my MSSQL server to create a table:
```
CREATE TABLE [dbo].[Test_HeidiTicket327](
	[Column1] [int] NULL,
	[Column2] [varchar](20) NULL
)
```

2. Then I import the following CSV file, but **uncheck Column1**, because the file contains only string values for Column2:
```
lorem
ipsum
dolor
sit
amet
```

3. Then I get 5 rows with Column1=NULL (which is what I expected) and Column2=0 each. Heidi seems to think that the column I want to import was of type int, because the first column of the table _as a whole_ is int. But the first column I want to import is varchar(20).

**Comment by ansgarbecker** [comment]
Are you sure that fixes the issue?

**Comment by nummacway** [comment]
Somewhat. Before committing the fix, I built the project and successfully imported a previously unimportable TSV file (which turned some string columns into '0') that contains the columns highlighted in blue in the following design:
![grafik](https://user-images.githubusercontent.com/24881711/79384579-7173e080-7f67-11ea-9cdf-f4c11efae1a4.png)

**Comment by ansgarbecker** [comment]
Ok, so I guess I can close this.

**Comment by nummacway** [comment]
@ansgarbecker Please close #242, seems to be a duplicate.
