### ISSUE TITLE
"Import CSV file" dialog UI glitch

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#328]
## Steps to reproduce this issue

1. Change system DPI to more than 100%;
2. Run HeidiSQL and open Tools | "Import CSV file";

## Current behavior

Columns navigation arrows & checkbox for ticking/unticking all columns are positioned incorrectly in non default DPI (see screenshot)
![import](https://user-images.githubusercontent.com/7234987/44068765-514e3374-9f6b-11e8-90a8-add03e07ef45.png)

## Expected behavior

Correct positioning of these elements

## Possible solution

Tiny UI change in a way the similar UI is used in HeidiSQL would do the trick (see a couple of options below, I prefer the last one)
![columns selector](https://user-images.githubusercontent.com/7234987/44068796-6f914c40-9f6b-11e8-8e5e-f6e65d215738.png)
![import_updated](https://user-images.githubusercontent.com/7234987/44068801-731872e4-9f6b-11e8-876f-0bf6075c01a7.png)
![import_updated2](https://user-images.githubusercontent.com/7234987/44068935-1045640a-9f6c-11e8-9b40-72b9652998db.png)

## Environment

* **HeidiSQL version:** 9.5.0.5280
  
* **Operating system:** Windows 10 64-bit

**Comment by ansgarbecker** [comment]
I just moved these 3 buttons from right to below the column box.
Please verify that works for you, after updating to the latest build.

**Comment by fifonik** [comment]
Unfortunately, it is still not fixed:
![import](https://user-images.githubusercontent.com/7234987/44312838-d2b97880-a441-11e8-9e16-451a447589de.png)

**Comment by fifonik** [comment]
> I found your single checkbox quite nice, only that misses the two up/down arrow buttons

I do not know what is the reason for these arrows, actually.
If I use keyboard, I can navigate columns using up/down arrow keys
If I use mouse, I can simply click at column's checkbox.
This is the reason I left the single "all" checkbox only.

**Comment by ansgarbecker** [comment]
I just moved the buttons again to the left, where positioning should not be the problem in higher DPI modes. Please again verify by using the new nightly build.

I suspect the problem is that Windows scales the form in high DPI modes without scaling the margin of that toolbar.

**Comment by fifonik** [comment]
The position is is fixed now.

However, the 'All' checkbox meaning is a bit strange (opposed to expected).
When all columns checked (default) the 'All' checkbox is not checked. Usually, such checkbox is checked when all dependent checkboxes checked.
You can have a look at 'Columns' filter on Data tab or at Maintenance and see. The behaviours or 'All' checkbox there and 'All' checkbox on the Import CSV tool are different that is confusing.
