### ISSUE TITLE
"Import CSV file" with "Client parses file content" adds incorrect value into the last row

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#329]
## Steps to reproduce this issue

1. Create tables for testing using the script:
```
DROP TABLE IF EXISTS src;

DROP TABLE IF EXISTS dest;

CREATE TABLE `src` (
	  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	, `val` VARCHAR(15) NOT NULL
);

CREATE TABLE `dest` (
	  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
	, `val` VARCHAR(15) NOT NULL
);

INSERT INTO src (val) VALUES ('a1'), ('a2'), ('a3'), ('a4'), ('a5');
```
2. Select 'src' table, go to Data tab, Right Mouse Button | Export grid rows to file | OK
![export_2](https://user-images.githubusercontent.com/7234987/44175659-67387980-a0d6-11e8-9cdd-3cdc0a290624.png)

3. Check the file's content
![file_2](https://user-images.githubusercontent.com/7234987/44175637-5a1b8a80-a0d6-11e8-9628-e769201a2268.png)

3. Select 'dest' table, Tools | Import CSV file | Client parses file content, untick 'id' column | Import
![import_2](https://user-images.githubusercontent.com/7234987/44175669-6e5f8780-a0d6-11e8-9523-bc9b8519f58e.png)

4. Notice HeidiSQL issued query with incorrect value for the last row (quote char and \r must not be there), press F5 to refresh 'dest' table Data and have a look at the content:
`INSERT INTO `test`.`dest` (`val`) VALUES ('a1'), ('a2'), ('a3'), ('a4'), ('a5"\r');`
![result_2](https://user-images.githubusercontent.com/7234987/44175698-8a632900-a0d6-11e8-9ab2-f7630bac199e.png)

## Current behavior
Quote char with \r added at the last row's last value

## Expected behavior
Quote char and \r should not be added

## Environment

* **HeidiSQL version:** 9.5.0.5280
  
* **Database system and version:** MySQL 5.7.19
  
* **Operating system:** Windows 10 64-bit

**Comment by ansgarbecker** [comment]
I just reproduced that, and can confirm the issue exactly as you described it.

**Comment by ansgarbecker** [comment]
The client parser is quite sensitive to line feeds at the end of the file. Previously, there mustn't be any linefeeds at the end to work correctly, now with my modification, there can be one, without confusing the import.

Please verify after updating to the latest build. Thanks!

**Comment by fifonik** [comment]
Thanks for prompt fix.
Works as expected now.
