### ISSUE TITLE
SSH tunnel is reused even when mysql host is different causing a connection to the "wrong" database

### ISSUE THREAD

**Issue by ppamment** [HeidiSQL/HeidiSQL#335]
## Steps to reproduce this issue

Create a SSH tunnel connection, leave the default local port as 3307, use mysql host prod.foo.com
Create a SSH tunnel connection, leave the default local port as 3307, use mysql host staging.foo.com

## Current behavior

If I open the first connection to prod.foo.com, then open the second connection to staging.foo.com, Heidi reuses the SSH tunnel on localhost:3307 that's already open but is pointing to prod.foo.com
As far as I can tell it appears I have successfully connected to staging.foo.com, but in fact I am really connected to prod.foo.com. This is scary dangerous.

## Expected behavior

If there is already an open SSH tunnel on a local port an error should be thrown if another connection is using that same local port (certainly in the case that the mysql host is different).

## Possible solution

Either throw an error as described above, or perhaps Heidi can pick the local ports automatically and avoid such conflicts.

**Comment by ansgarbecker** [comment]
HeidiSQL already auto-detects whether the wanted port is being used, when you connect to a tunnel. I just tested that and the log tells it:

> /* Connecting to 127.0.0.1 via MariaDB (SSH tunnel), username XYZ, using password: Yes ... */
> /* Port #3307 in use. Checking if #3308 is available... */
> /* Attempt to create plink.exe process, waiting 4s for response ... */

Please check if that isn't the case for you.

**Comment by ppamment** [comment]
This is not the case for me. Opening 2 connections on the same SSH port succeeds both times. Image attached.

![image](https://user-images.githubusercontent.com/2122919/44997228-bd496000-afa4-11e8-8774-779f7eaa164c.png)

**Comment by ansgarbecker** [comment]
Please verify you're using the latest HeidiSQL build (not release, but build)

**Comment by ppamment** [comment]
Thanks. I use this for connecting to production databases so I'm quite wary of using a latest build given the warning: "Be aware that these builds are not official releases and therefore probably have more bugs, possibly serious ones"

I simply can't risk using something that has possibly serious bugs to connect to a production database.

Thanks

**Comment by ansgarbecker** [comment]
This should have already been fixed by 8292e41518f822872cd1db2b7452dbbe497698ac , and was discussed [in the forum](https://www.heidisql.com/forum.php?t=18601) as well.
