### ISSUE TITLE
Reuse the dialog during multi file import.

### ISSUE THREAD

**Issue by Icoss** [HeidiSQL/HeidiSQL#338]
This is a follow up of the issue described here:
https://www.heidisql.com/forum.php?t=25651#p25674

## Steps to reproduce this issue
Import a lot of sql files at once.

## Current behavior
When the Heidi is running in the background during the multi file import, file import dialog pops on top bringing the Heidi on top as well.

## Expected behavior
Heidi should stay in the background no matter how many files are imported.

## Possible solution

Reuse the file import dialog, when importing multiple files.

**Comment by ansgarbecker** [comment]
So, the next build uses a single progress animation dialog for multiple files. Also:
* The progress dialog is no longer modal, which in my experience caused a focus stealing to some other application
* This in turn made it more dangerous for clicks outside the dialog (as you mentioned when you click a) another database, or even b) another connection)
** Solution for a): processing application messages is no longer done now during the progress dialog is shown. This again will probably cause the progress dialog to be non-responsive at some point, but this did not happen during my tests.
** Solution for b): even if the user manages to click some other connection (which should not be possible now), HeidiSQL now ensures to run all files on the connection selected before the dialog showed up

Please update in a few minutes, and give it some tests.
