### ISSUE TITLE
BLOB data over 0x81 is wrong in result grid view.

### ISSUE THREAD

**Issue by BrianMSon** [HeidiSQL/HeidiSQL#34]
## Expected behavior

**Result of select BLOB data must be same with hex(data) when the query executed.**
`select data, hex(data) from x_test;`

## Current behavior

**Select result of BLOB data is now different from hex(data).**
data : **0x3F** -> **WRONG!!**
hex(data) : 0x81

![image](https://user-images.githubusercontent.com/8359891/33811980-330955fe-de5c-11e7-83c8-dd94b48fc3e3.png)

## Failure information (for bugs)

**Data 0x80 is ok. not bug.**
data : 0x80
hex(data) : 0x80

**But 0x81~0xFE data is not ok. it's bug.**
data : 0x3F
hex(data) : 0x81

data : 0x3F
hex(data) : 0x82

### Steps to reproduce

**1. There is a table like below. Create if not exist.**

CREATE TABLE  `x_test` (
    `player_id` INT(11) NOT NULL, 
    `data` BLOB NOT NULL, 
    PRIMARY KEY (`player_id`)
)
COLLATE='utf8_general_ci' ENGINE=InnoDB;

**2. Insert HEX data.**

`INSERT x_test VALUES(1, 0x81);`

**3. Select data.**

`SELECT data, HEX(data) FROM x_test;`

**4. Check the result.**

### Context

`INSERT x_test VALUES(1, 0x81);`
`INSERT x_test VALUES(2, 0x82);`
`INSERT x_test VALUES(3, 0x99);`
`INSERT x_test VALUES(4, 0x8181);`
`INSERT x_test VALUES(5, 0x818181);`
`INSERT x_test VALUES(6, 0x81818181);`
`INSERT x_test VALUES(7, 0x8181818181);`
`INSERT x_test VALUES(8, 0x818181818181);`

![image](https://user-images.githubusercontent.com/8359891/34351982-39cb378c-ea63-11e7-9b7f-76951dd87fa3.png)

* HeidiSQL version: 9.4.0.5191
* Database system + version: 10.0.11-MariaDB
* Operating system: CentOS 6.5

**Comment by BrianMSon** [comment]
Is this not a bug?

**Comment by BrianMSon** [comment]
It's maybe fixed at Revision 9.5.0.5264 or previous rev.
Thank you so much!!

**Comment by ansgarbecker** [comment]
Thanks for your feedback!
