### ISSUE TITLE
postgresql open connection crash

### ISSUE THREAD

**Issue by zhcy** [HeidiSQL/HeidiSQL#342]
date/time          : 2018-09-05, 17:28:37, 65ms
computer name      : xxxxx
user name          : xxxxx
registered owner   : admin
operating system   : Windows 10 x64 build 15063
system language    : Japanese
system up time     : 5 days 22 hours
program up time    : 13 seconds
processors         : 4x Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
physical memory    : 8229/16265 MB (free/total)
free disk space    : (C:) 43.96 GB (D:) 25.04 GB
display mode       : 1440x900, 32 bit
process id         : $23f4
allocated memory   : 58.98 MB
largest free block : 131025.99 GB
executable         : heidisql.exe
exec. date/time    : 2017-12-19 16:46
version            : 9.5.0.5196
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $1a5a691c, $ab8ba400, $ab8ba400
exception number   : 1
exception class    : EConvertError
exception message  : Format '"%s" の不明なデータ型 oid #%d です。%s にフォ' invalid or incompatible with argument.

main thread ($2008):
0047305d heidisql.exe System.SysUtils            ConvertErrorFmt
0047701c heidisql.exe System.SysUtils            FormatError
00478015 heidisql.exe System.SysUtils            WideFormatBuf
00477080 heidisql.exe System.SysUtils            FormatBuf
004772cd heidisql.exe System.SysUtils            FmtStr
00477205 heidisql.exe System.SysUtils            Format
004771d7 heidisql.exe System.SysUtils            Format
0097e0ee heidisql.exe helpers          2638   +2 f_
00a8c95b heidisql.exe dbconnection     1545  +17 TDBConnection.GetDatatypeByNativeType
00ab274a heidisql.exe dbconnection     5663  +42 TPGQuery.Execute
00aa027b heidisql.exe dbconnection     3463  +20 TDBConnection.GetResults
00aaa028 heidisql.exe dbconnection     4615  +14 TPgConnection.FetchDbObjects
00aa61b7 heidisql.exe dbconnection     4331  +22 TDBConnection.GetDBObjects
00c6b30b heidisql.exe Main             7891  +24 TMainForm.DBtreeInitChildren
008e261f heidisql.exe VirtualTrees    20178   +3 TBaseVirtualTree.DoInitChildren
008e89ad heidisql.exe VirtualTrees    22620   +4 TBaseVirtualTree.InitChildren
008fed89 heidisql.exe VirtualTrees    31903 +128 TBaseVirtualTree.ToggleNode
008d5687 heidisql.exe VirtualTrees    14588   +2 TBaseVirtualTree.SetExpanded
00c52c08 heidisql.exe Main             3700  +30 TMainForm.InitConnection
00b6e0e7 heidisql.exe connections       330   +5 Tconnform.btnOpenClick
00695444 heidisql.exe Vcl.Controls               TControl.Click
006ccd66 heidisql.exe Vcl.StdCtrls               TCustomButton.Click
006cdd82 heidisql.exe Vcl.StdCtrls               TCustomButton.CNCommand
0040cb1e heidisql.exe System                     TObject.Dispatch
00694b83 heidisql.exe Vcl.Controls               TControl.WndProc
0069c24e heidisql.exe Vcl.Controls               TWinControl.WndProc
006cc7b0 heidisql.exe Vcl.StdCtrls               TButtonControl.WndProc
00694660 heidisql.exe Vcl.Controls               TControl.Perform
0069c449 heidisql.exe Vcl.Controls               DoControlMsg
0069d7c3 heidisql.exe Vcl.Controls               TWinControl.WMCommand
0080ab28 heidisql.exe Vcl.Forms                  TCustomForm.WMCommand
0040cb1e heidisql.exe System                     TObject.Dispatch
00694b83 heidisql.exe Vcl.Controls               TControl.WndProc
0069c24e heidisql.exe Vcl.Controls               TWinControl.WndProc
00805f1b heidisql.exe Vcl.Forms                  TCustomForm.WndProc
0069b48a heidisql.exe Vcl.Controls               TWinControl.MainWndProc
005dbdc3 heidisql.exe System.Classes             StdWndProc
7ffa1159 USER32.dll                              SendMessageW
7ffa1159 USER32.dll                              CallWindowProcW
0069c3e9 heidisql.exe Vcl.Controls               TWinControl.DefaultHandler
00695aec heidisql.exe Vcl.Controls               TControl.WMLButtonUp
0040cb1e heidisql.exe System                     TObject.Dispatch
00694b83 heidisql.exe Vcl.Controls               TControl.WndProc
0069c24e heidisql.exe Vcl.Controls               TWinControl.WndProc
006cc7b0 heidisql.exe Vcl.StdCtrls               TButtonControl.WndProc
0069b48a heidisql.exe Vcl.Controls               TWinControl.MainWndProc
005dbdc3 heidisql.exe System.Classes             StdWndProc
7ffa1159 USER32.dll                              DispatchMessageW
0081469f heidisql.exe Vcl.Forms                  TApplication.ProcessMessage
00814713 heidisql.exe Vcl.Forms                  TApplication.HandleMessage
0080d058 heidisql.exe Vcl.Forms                  TCustomForm.ShowModal
00c46b7d heidisql.exe Main             2057 +101 TMainForm.AfterFormCreate
00ca05c5 heidisql.exe heidisql           76  +20 initialization
7ffa12f7 KERNEL32.DLL                            BaseThreadInitThunk
7ffa137c ntdll.dll                               RtlUserThreadStart

**Comment by ansgarbecker** [comment]
This is an error in the translation of HeidiSQL.
As the revision is not the latest build, please update to the latest build so we see if that was already fixed.
