### ISSUE TITLE
Double-click selecting issue of non-number-or-latin text

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#346]
## Steps to reproduce this issue

1. I have a table MyTable in my DB with non-latin named columns.
2. I opened a new tab to make some query to this table.
3. I wrote something like `SELECT MyTable.Имя FROM MyTable` where you can see non-latin name.
4. The query worked excellent. But I can't select the non-latin part of the text with double-click (using mouse).

## Current behavior

This issue takes place only in Editor, nowhere else.

## Expected behavior

I'd like to be able to select any text (not only number or latin or other text of ordinary encoding ) using mouse double-click.

## Environment

* **HeidiSQL version:** 
last nightly HeidiSQL rev. 5293 
  
* **Database system and version:** 
  
* **Operating system:**
Windows 10

**Comment by ansgarbecker** [comment]
This is an issue in the underlying SynEdit component, the editor with SQL highlighting. SynEdit is also on Github. Please post this issue in their tracker: https://github.com/SynEdit/SynEdit

**Comment by AlexLunyov** [comment]
OK, thank you for the explanation.
