### ISSUE TITLE
Does not display correctly special chars like é, à etc

### ISSUE THREAD

**Issue by serhioV** [HeidiSQL/HeidiSQL#356]
HeidiSQL does not display correctly special chars like é, à etc.
And I don't see any way to change the displaed encoding

## Steps to reproduce this issue

1. Step 1;
Create a WebAPI application and add via the interface a string like "salut, été à Québec !", that should be saved in a MySQL database (5.1.73-community).
2. Step 2;
Open the HeidiSQL and have a look on the results.
3. Step N;
You can also export the results in text file, the "é" would be represented as "Ã©".
Now, if you modify in the text file the "Ã©" with "é" and imports into the DB(or just simply modifies the text in the HeidiSQL data table view), the HeidiSQL will correctly display the string. **BUT** it will be broken in the Web interface

![image](https://user-images.githubusercontent.com/6714786/46072594-0c894780-c183-11e8-82ec-3eb9be759bb3.png)

![image](https://user-images.githubusercontent.com/6714786/46072635-26c32580-c183-11e8-8c0a-90593c15512a.png)

## Current behavior
"salut, Ã©tÃ© Ã  QuÃ©bec !"

![image](https://user-images.githubusercontent.com/6714786/46072032-a3550480-c181-11e8-899f-9097c53429c7.png)

## Expected behavior
"salut, été à Québec !"

## Possible solution
Provide a way to change display encoding.

## Environment
![image](https://user-images.githubusercontent.com/6714786/46072804-8cafad00-c183-11e8-8c90-14fe486f7994.png)

* **HeidiSQL version:** 9.5.0.5293
  
* **Database system and version:** MySQL 5.1.73-community
  
* **Operating system:** Windows

**Comment by ansgarbecker** [comment]
This is not an error in HeidiSQL, but a wrong usage of charsets. You should check what charset your webpage uses to communicate with MySQL. Often you will find some `SET NAMES utf8` query in your application, or a call to [`mysqli_set_charset()`](http://php.net/manual/de/mysqli.set-charset.php). If you cannot find such a call or query, your communication falls back to the server variable `character_set_server`. Please check with `SHOW VARIABLES LIKE 'character_set%'` and post the results here.

Also, the columns/table charset is relevant here. Please post the result of `SHOW CREATE TABLE mytable` here.

**Comment by serhioV** [comment]
> This is not an error in HeidiSQL, but a wrong usage of charsets. You should check what charset your webpage uses to communicate with MySQL. Often you will find some `SET NAMES utf8` query in your application, or a call to [`mysqli_set_charset()`](http://php.net/manual/de/mysqli.set-charset.php). If you cannot find such a call or query, your communication falls back to the server variable `character_set_server`. Please check with `SHOW VARIABLES LIKE 'character_set%'` and post the results here.
> 
> Also, the columns/table charset is relevant here. Please post the result of `SHOW CREATE TABLE mytable` here.

![image](https://user-images.githubusercontent.com/6714786/46149917-a7f5e780-c26b-11e8-9f3b-6c85a10aa631.png)

**Comment by ansgarbecker** [comment]
Your `character_set_server` is latin1. So, unless you fire `SET NAMES utf8` in your web application, or call `mysqli_set_charset()` at some point, you store latin1 text in your table. You also _read_ the `latin1` encoded text, so everything seems right (in your web application!). When you access the table with any utf8-capable client (like HeidiSQL, but also Workbench and others), you see garbled text.

Solution is to fire `SET NAMES utf8` or to call `mysqli_set_charset()` in your web application. Unfortunately, this will show you the same garbled text as you now see in HeidiSQL. So you need to convert the contents in your tables from latin1 to utf8 first.

**Comment by serhioV** [comment]
how do you comment the `DEFAULT CHARSET=utf8` on the create table script?

**Comment by serhioV** [comment]
anyway, what is the problem to HeidiSQL to be able to display its table data in "latin1" encoding, if someone use it?

**Comment by ansgarbecker** [comment]
The table structure is very ok, only you store latin1 in it instead of utf8 text. And this is what is broken here.

HeidiSQL cannot know that your table contains latin1 chars. Also any other client won't be able to know that. Please test any other sql client on your table.

**Comment by serhioV** [comment]
> The table structure is very ok, only you store latin1 in it instead of utf8 text. And this is what is broken here.
> 
> HeidiSQL cannot know that your table contains latin1 chars. As the table and columns are defined as utf8, HeidiSQL reads them as such. Also any other client won't be able to know that. Please test any other sql client on your table.

How do I store latin1 if the create table script says 
`DEFAULT CHARSET=utf8 |`

**Comment by ansgarbecker** [comment]
Please use `mysqli_set_charset()` or `SET NAMES utf8` in your web application, or set utf8 encoding for the connection in the way your application needs it. I'll close this issue for now, until we see if there really is an issue in HeidiSQL.

**Comment by oliveru** [comment]
How to handle "shit":
https://heiglandreas.github.io/slidedeck/HowToHandlePILE_OF_POO/20180922-phpdd/index_online.html#/52

MySQL is a charset mess.

**Comment by lukinhaspm** [comment]
The problem of collations and charsets is chronic, its not happens only in
MySQL (because we have other factors to interfer). The explanation is very
good (really), but it did "shit" when it wrote ~ "or use a (real) database
like PostgreSQL" ~
:/

Lucas Augusto Milanes
Skype: Lucas Augusto Milanes
Cel:     +55 (11) 98160-3130


Em qui, 4 de out de 2018 às 10:43, Oliver Ulpts <notifications@github.com>
escreveu:

**Comment by serhioV** [comment]
> How to handle "shit":
> https://heiglandreas.github.io/slidedeck/HowToHandlePILE_OF_POO/20180922-phpdd/index_online.html#/52
> 
> MySQL is a charset mess.

Really helpful, I just didn't understand what @ansgarbecker tried to explain to me, now I see, I chan change the connection charset, that, it seems, is not UTF8 by default ! (
