### ISSUE TITLE
Move background color setting to session manager

### ISSUE THREAD

**Issue by rkmaier** [HeidiSQL/HeidiSQL#360]
## Use case
When working with multiple databases across different servers and environments it's easy to make mistakes, so i would like to have an option to show warnings  when working with a production server and also highlighting in some way that I am  currently connected to a production server. Some similar feature is present in almost all of the standalone tools which manage mysql databases. 

## Possible solutions
1. An option in the session manager to mark it as production server.
2. An option to enable/disable warning message when executing modifications that permanently alter 
  the data on the current production server
3. A color to highlight production servers

**Comment by penCsharpener** [comment]
Isn't this already there?
![Set server background color](https://user-images.githubusercontent.com/26190934/46371507-d9feb380-c688-11e8-9522-b4c96fec2b6f.png)

**Comment by rkmaier** [comment]
@penCsharpener Thanks for the tip, i was looking for something like this.  I would include this option inside  the Session Manager > Settings also.

**Comment by ansgarbecker** [comment]
Yes, this is definitely reasonable.

**Comment by ansgarbecker** [comment]
I just moved the color setting to the Advanced tab:

![grafik](https://user-images.githubusercontent.com/7986591/55273899-bb911200-52d1-11e9-9e60-244bc050b324.png)

**Comment by ansgarbecker** [comment]
That background color selector now additionally shows all colors you defined for any of your sessions:

![grafik](https://user-images.githubusercontent.com/7986591/61187495-280e0200-a672-11e9-982e-8e84b5ae2bf1.png)
