### ISSUE TITLE
Heidi crashing in Ubuntu 18-04

### ISSUE THREAD

**Issue by mkburdette** [HeidiSQL/HeidiSQL#363]
date/time          : 2018-10-07, 22:59:44, 879ms
computer name      : *********-XPS-8500
user name          : ***********
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : English
system up time     : 2 days 3 hours
program up time    : 618 milliseconds
processors         : 8x Intel(R) Pentium(R) 4 CPU 2.40GHz
physical memory    : 3455/11969 MB (free/total)
free disk space    : (C:) 41.35 GB
display mode       : 1920x1200, 32 bit
process id         : $2e
allocated memory   : 22.44 MB
largest free block : 130168.64 GB
executable         : heidisql.exe
exec. date/time    : 2018-04-09 22:22
version            : 9.5.0.5268
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $6db0822a, $76e0c7ab, $76e0c7ab
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 00007F1EADB958F2 in module 'd2d1.dll'. Read of address 0000000000000000.

main thread ($2f):
7f1eadb9 d2d1.dll
00898b4b heidisql.exe SynEdit        7417  +4 TCustomSynEdit.WMSize
0040d90e heidisql.exe System                  TObject.Dispatch
00695ca3 heidisql.exe Vcl.Controls            TControl.WndProc
0069d36e heidisql.exe Vcl.Controls            TWinControl.WndProc
0089c5a6 heidisql.exe SynEdit        8581 +22 TCustomSynEdit.WndProc
0069c5aa heidisql.exe Vcl.Controls            TWinControl.MainWndProc
005dce43 heidisql.exe System.Classes          StdWndProc
7f1eb7fb user32.dll                           TranslateAccelerator
7f1eb7fb user32.dll                           SendMessageW
7f1eb7f7 user32.dll                           DefWindowProcW
7f1eb7ff user32.dll                           CallWindowProcW
0069d509 heidisql.exe Vcl.Controls            TWinControl.DefaultHandler
00696e16 heidisql.exe Vcl.Controls            TControl.WMWindowPosChanged
0069ed48 heidisql.exe Vcl.Controls            TWinControl.WMWindowPosChanged
0040d90e heidisql.exe System                  TObject.Dispatch
00695ca3 heidisql.exe Vcl.Controls            TControl.WndProc
0069d36e heidisql.exe Vcl.Controls            TWinControl.WndProc
0089c5a6 heidisql.exe SynEdit        8581 +22 TCustomSynEdit.WndProc
0069c5aa heidisql.exe Vcl.Controls            TWinControl.MainWndProc
005dce43 heidisql.exe System.Classes          StdWndProc
7f1eb7fb user32.dll                           TranslateAccelerator
7f1eb7fb user32.dll                           SendMessageW
7f1eb7ff user32.dll                           SetInternalWindowPos
7f1eb7ff user32.dll                           SetWindowPos
006a11a6 heidisql.exe Vcl.Controls            TWinControl.SetBounds
006ac782 heidisql.exe Vcl.Controls            TMargins.SetControlBounds
00699375 heidisql.exe Vcl.Controls            TWinControl.ArrangeControl
0069985a heidisql.exe Vcl.Controls            DoPosition
00699b32 heidisql.exe Vcl.Controls            DoAlign
0069a45c heidisql.exe Vcl.Controls            TWinControl.AlignControls
0069a6a2 heidisql.exe Vcl.Controls            TWinControl.AlignControl
0069a767 heidisql.exe Vcl.Controls            TWinControl.Realign
00699cf7 heidisql.exe Vcl.Controls            AlignNestedControls
0069a4bf heidisql.exe Vcl.Controls            TWinControl.AlignControls
0069a6a2 heidisql.exe Vcl.Controls            TWinControl.AlignControl
0069a767 heidisql.exe Vcl.Controls            TWinControl.Realign
0069a747 heidisql.exe Vcl.Controls            TWinControl.EnableAlign
00698dc0 heidisql.exe Vcl.Controls            TWinControl.ReadState
005c85a3 heidisql.exe System.Classes          TReader.ReadComponent
005c88fc heidisql.exe System.Classes          TReader.ReadDataInner
005c8810 heidisql.exe System.Classes          TReader.ReadData
005d9b1d heidisql.exe System.Classes          TComponent.ReadState
00691ee1 heidisql.exe Vcl.Controls            TControl.ReadState
00698db6 heidisql.exe Vcl.Controls            TWinControl.ReadState
00715ab2 heidisql.exe Vcl.ComCtrls            TTabSheet.ReadState
005c85a3 heidisql.exe System.Classes          TReader.ReadComponent
005c88fc heidisql.exe System.Classes          TReader.ReadDataInner
005c8810 heidisql.exe System.Classes          TReader.ReadData
005d9b1d heidisql.exe System.Classes          TComponent.ReadState
00691ee1 heidisql.exe Vcl.Controls            TControl.ReadState
00698db6 heidisql.exe Vcl.Controls            TWinControl.ReadState
005c85a3 heidisql.exe System.Classes          TReader.ReadComponent
005c88fc heidisql.exe System.Classes          TReader.ReadDataInner
005c87ee heidisql.exe System.Classes          TReader.ReadData
005d9b1d heidisql.exe System.Classes          TComponent.ReadState
00691ee1 heidisql.exe Vcl.Controls            TControl.ReadState
00698db6 heidisql.exe Vcl.Controls            TWinControl.ReadState
008059bd heidisql.exe Vcl.Forms               TCustomForm.ReadState
005ca033 heidisql.exe System.Classes          TReader.ReadRootComponent
005c0c4a heidisql.exe System.Classes          TStream.ReadComponent
005b15e0 heidisql.exe System.Classes          InternalReadComponentRes
005b37f1 heidisql.exe System.Classes          InitComponent
005b38c5 heidisql.exe System.Classes          InitInheritedComponent
00804dad heidisql.exe Vcl.Forms               TCustomForm.Create
00815a5e heidisql.exe Vcl.Forms               TApplication.CreateForm
00cd3d36 heidisql.exe heidisql         75 +19 initialization

## Steps to reproduce this issue

1. Step 1; open heidi
2. Then I get the crash page

## Current behavior

See above

## Expected behavior

Heidi would open

## Possible solution
I have had Heidi running before on this computer. I removed it trying to install a specific version required for our business. When I tried to install 9.5.0.5268, this happened and now I can't run Heidi.

## Environment

* **HeidiSQL version:**  9.5.0.5268
  
* **Database system and version:** mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper
  
* **Operating system:** Ubuntu 18.04

**Comment by ansgarbecker** [comment]
As stated on the download page, on Wine, you need to disable the builtin Direct2D interface, and configure the native one. This is documented in another issue report: https://github.com/HeidiSQL/HeidiSQL/issues/83#issuecomment-375969129
