### ISSUE TITLE
Can't create a table

### ISSUE THREAD

**Issue by igorky** [HeidiSQL/HeidiSQL#366]
## Steps to reproduce this issue

1. Call a new table form;
2. Add one field and try to change type;

## Current behavior

Crash

## Expected behavior

Dropdown with types

## Environment

[bugreport2.txt](https://github.com/HeidiSQL/HeidiSQL/files/2465995/bugreport2.txt)

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
Did you do something special before the crash happened? Could you please be more detailed where you clicked and/or which keyboard key you pressed?
I am not able to reproduce that crash, so we definitely need more input.
