### ISSUE TITLE
Export Selected Rows fails to copy last instance of INT coloum

### ISSUE THREAD

**Issue by rabievdm** [HeidiSQL/HeidiSQL#368]
## Steps to reproduce this issue

1. Step 1; SELECT * FROM mydb.mytable;
2. Step 2; Right click on the data and say 'export grid rows'
3. Step 3: Specify pretty much any format, but we pick Delimited Text, Complete rows, Include Colum names, then ok to copy to clipboard. 
4. Step 4: Paste the output.

## Current behavior

You will get the contents of the output minus the last coloum that seems to be of type INT
eg:
Name     DataType
actid       MEDIUMINT
name      VARCHAR

Output of paste:
name
MyFirstEntry

## Expected behavior

All coloums should be pasted, expected output:
actid        name
1             MyFirstEntry

## Possible solution
I can get the last coloum to display by selcting it twice eg:
SELECT actid as actid2, actid, name FROM mydb.mytable;
It will then still drop one request for the INT coloum but display the other attempt, it doesn't matter where the colums is located in the request it will still drop it. If I revert to an older version of HeidiSQL it will work.

## Environment

* **HeidiSQL version:** 
On the lastest nightly version 9.5.0.5295
Last version known to work was 9.5.0.5284, suspect it may have broken with some of the bug fixes in 5293?  

* **Database system and version:** 
N/A
* **Operating system:** 
N/A

**Comment by ansgarbecker** [comment]
I highly suspect the reporter had disabled the "_Include auto increment column_" checkbox.
