### ISSUE TITLE
Feature request: text view for headlines and data rows for more easy copy/pasting

### ISSUE THREAD

**Issue by plessmann** [HeidiSQL/HeidiSQL#369]
## Steps to reproduce this issue

1. Connect to a database
2. Select a table
3. Request the data view 
4. Then I get a grid based layout view which is not friendly enough for daily operating and which cannot be changed.

## Current behavior

In current behaviour I get only a grid cell based layout view.

## Expected behavior

The grid cell based layout should be switchable to a simple ASCII table output (read-only mode). The headlines and the row data (taking respect of the current filter criteria) shoud be displayed in this text view.
As user you can much easier extract and copy/paste desired data via clipboard to any other application. In addition to that, searching over the whole resultset by using Ctrl+F is much easier in daily business.
This is a feature of dbeaver which is missing in HeidiSQL next to the record based view (show full records in lines in "Headline: Value" format (handy for tables with lots of columns)

## Possible solution

As in "dbeaver" there is a read-only text based layout next to the grid based layout. In a ddition to that there is an view for record based layout (not horizontal but vertical for the current selected record).
You can switch at any time between these views.
Editing in text based layout view is not needed because it should support the user in analyzing data records, copying and searching values in the result set and not more.
Important: Headlines should be also be displayed in ASCII mode to find a column more fast. 
Separating the grid cells with pipe characters and headline is required.
For double click: select word, For triple click: select full cell content.
Too long or binary content sould be truncated (TEXT, BLOB fields etc).

E.g. of the output in ASCII format should be like this:

```
id                                   |name                       |date_entered        |date_modified       |modified_user_id |created_by |description |deleted |
-------------------------------------|---------------------------|--------------------|--------------------|-----------------|-----------|------------|--------|
1250e22d-2225-7171-13f8-55ea02bf6e42 |Sandeon Corp               |2015-09-04 20:45:06 |2015-09-04 20:45:06 |1                |1          |            |0       |
12b9389b-8882-a081-0e0a-55ea0286bba2 |Overhead & Underfoot Ltd.  |2015-09-04 20:45:06 |2015-09-04 20:45:06 |1                |1          |            |0       |
14208c9c-d6d4-b17f-b2f9-55ea025528d4 |Jungle Systems Inc         |2015-09-04 20:45:06 |2015-09-04 20:45:06 |1                |1          |            |0       |
14771bc3-a796-b6f9-b29d-55ea02af2ffa |SE Capital Corp            |2015-09-04 20:45:06 |2015-09-04 20:45:06 |1                |1          |            |0       |
```
As record view is displayed like this:

```
Name                       |Value                               |
---------------------------|------------------------------------|
id                         |220dbc20-9444-f56c-03d8-55ea02f0878e|
name                       |MIT Talker Co                       |
date_entered               |2015-09-04 20:45:06                 |
date_modified              |2015-09-04 20:45:06                 |
modified_user_id           |1                                   |
created_by                 |1                                   |
description                |                                    |
deleted                    |0                                   |
```

## Environment
* **HeidiSQL version:**  9.5.0.5196
* **Database system and version:** mysql 5.6.39-83.1, Percona Server (GPL), Release 83.1, Revision da5a1c2923f
* **Operating system:** debian-linux-gnu Linux devel 4.9.0-7-amd64 (as server os), Windows 10 as client where HeidiSQL is running

**Comment by fifonik** [comment]
> As user you can much easier extract and copy/paste desired data via clipboard to any other application.

RMB | Copy selected rows & RMB | Export Grid Rows are quite flexible for these purposes.


> searching over the whole resultset by using Ctrl+F is much easier in daily business.

What stopped you to press Ctrl+F in the data grid for the same purpose?


> For double click: select word, For triple click: select full cell content.

Must never be implemented imho as it is OS specific.


> Too long or binary content sould be truncated (TEXT, BLOB fields etc).

How would it make possible to use Ctrl+F to find something?

**Comment by ansgarbecker** [comment]
Reading @fifonik 's comment twice, I don't see any reason to implement such a text view. Find text copying data is already possible with the current grid.
