### ISSUE TITLE
Upgrade project files to Delphi 10

### ISSUE THREAD

**Issue by ansgarbecker** [HeidiSQL/HeidiSQL#372]
Currently HeidiSQL sources need to be compiled with a licensed Delphi XE5 Pro version.

Embarcadero provides a free Community Edition of Delphi 10.2 Pro for non-commercial projects. That potentially fixes various issues, including the broken DPI scaling. Also, we would get cool VCL themes along with that update.

**Comment by ansgarbecker** [comment]
Related issues: #213 and #8

**Comment by ansgarbecker** [comment]
Done and works :)

**Comment by alesvaupotic** [comment]
Ansgar, this is the best news in years! I'm installing it right now and as I have been out of Delphi since D7, will you please guide me to a solution about ```[dcc32 Error] E1026 File not found: '..\..\res\icon.RES'``` error? I've got components installed, this .RES thing is popping out for like 15 files ...

**Comment by alesvaupotic** [comment]
Just ignore it, I figured it all out. Used brcc32 on those .rc files, split updater to updater32 and updater64 and now it compiles. Sweet!

**Comment by ansgarbecker** [comment]
You can also use the build-res.bat from the root directory to compile all required .rc files to .res files. Now as I write this, I see I forgot to add a line for the new styles.rc.

**Comment by alesvaupotic** [comment]
Oh, my bad. Missed that file. Sure, will use that. Anyway, kudos for upgrading to 10.2. I can finally add some of the features we talked about years ago but they never made it to the repo. I'll just maintain my fork from now on. And possibly PR them, if you find them useful. Like this reformating for the view:
