### ISSUE TITLE
Stop work in Ubuntu elementary OS 0.4.1 Loki

### ISSUE THREAD

**Issue by alejosv** [HeidiSQL/HeidiSQL#376]
date/time          : 2018-10-26, 17:38:41, 390ms
    computer name      : laptop
    user name          : ale <admin>
    operating system   : Windows 7 x64 Service Pack 1 build 7601
    system language    : Spanish
    system up time     : 42 minutes 17 seconds
    program up time    : 857 milliseconds
    processors         : 4x Intel(R) Pentium(R) 4 CPU 2.40GHz
    physical memory    : 1106/3855 MB (free/total)
    free disk space    : (C:) 632.80 GB
    display mode       : 1366x768, 32 bit
    process id         : $32
    allocated memory   : 32.51 MB
    largest free block : 130844.94 GB
    executable         : heidisql.exe
    exec. date/time    : 2018-10-26 17:37
    version            : 9.5.0.5305
    compiled with      : Delphi 10.2 Tokyo 
    madExcept version  : 4.0.20
    callstack crc      : $3d21de03, $58caecc6, $58caecc6
    exception number   : 1
    exception class    : Exception
    exception message  : Tipo de conexión no controlado (83).
    
    main thread ($33):
    00ab9b2a heidisql.exe dbconnection 1304 +9 TConnectionParameters.GetNetTypeGroup
    7b44feb2 KERNEL32.dll                      RaiseException

Wine version:
    
    wine-2.4 (Staging)

## Steps to reproduce this issue

1. Step 1;
Update heidisql to the latest version.

## Current behavior
It does not allow to start the application and shows the error.

## Expected behavior
Work well.

## Possible solution
Version 9.5.0.5295 works perfectly, but version 9.5.0.5296 or higher does not work.

## Environment

* **HeidiSQL version:** 
9.5.0.5305
  
* **Database system and version:** 
Server version: 10.2.18-MariaDB-1:10.2.18+maria~bionic-log mariadb.org binary distribution
  
* **Operating system:** 
Ubuntu elementary OS 0.4.1 Loki

**Comment by ansgarbecker** [comment]
Could you please recreate that session in the session manager, and try again?

The place where that crash happens should never be reached - it means that the network type in the session is none of the available ones. I have no clue how you accomplished that, apart from having modified some registry value. Or maybe after updating from a superold Heidi version.

**Comment by alejosv** [comment]
Hi @ansgarbecker, this is my session manager:

![image](https://user-images.githubusercontent.com/14202497/47732782-869e6780-dc2c-11e8-968b-131c51ed7641.png)

Heidi start and work in version 9.5.0.5295, but when updating to the next version the session manager does not start and shows the error. I have not modified anything, neither in Wine or HeidiSql, the only thing I did was to update the version.

I eliminated all the connections I had 
![image](https://user-images.githubusercontent.com/14202497/47733748-899a5780-dc2e-11e8-9ae5-10af3c34aca0.png)


I installed the latest version of HeidiSql and when I try to run HeidiSql I get the error.
![image](https://user-images.githubusercontent.com/14202497/47733952-fa417400-dc2e-11e8-8910-2b94eda00dc5.png)

![image](https://user-images.githubusercontent.com/14202497/47733969-03cadc00-dc2f-11e8-87bf-8b6f8f6f893d.png)

**Comment by ansgarbecker** [comment]
I see also the buttons with a dropdown menu are all black? I have an older working fix for that in the code, which obviously does not work any more. This could be due to the different Wine version or due to the new compiler (Delphi 10.2)

You said that build 5296 introduced this crash. That build corresponds to 5d9dbe20a96533bf1fd9455aacf96b97f11d654e , where I switched to the new compiler, and also changed the manifest xml file with this addition, pretending HeidiSQL is DPI aware:

```xml
  <asmv3:application>
    <asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware>True/PM</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
```

But I suppose this manifest file is not or just partially read by Wine, especially this setting is most likely quite irrelevant on any Linux.

Do you have the chance to test the newer builds on another Linux/Wine version? Just to see whether this is a general issue or probably one with Ubuntu/Loki.

**Comment by alejosv** [comment]
@ansgarbecker I updated my version of Wine from 2.4 to 3.19 and the error disappeared. In this case it was the Wine version.
