### ISSUE TITLE
DPI Scaling not respected on multiple monitors with different DPI settings

### ISSUE THREAD

**Issue by mwidmann** [HeidiSQL/HeidiSQL#378]
## Steps to reproduce this issue

My Setup ist the following: Surface Book 2, 3000x2000 (200% scaling, main display) conntected to a Dell U2711, 2560x1440 (100% scaling, secondary display)

1. Open HeidiSQL
2. move window from main display to secondary display.
3. everything, besides the title and menu bar is displayed at the scaling of the main display. 
![heidisql_2018-10-30_11-30-45](https://user-images.githubusercontent.com/251322/47712149-455f8500-dc37-11e8-8368-b9a8eeace372.png)
 
## Current behavior

The contents of the application are scaled using the dpi scaling of the main display.

## Expected behavior

The contents of the application are scaled according to the dpi scaling of the display, the window is displayed on.

## Possible solution

It must be a bug introduced in either the last version or the version before that. It worked with no problems until I updated yesterday.

## Environment

* **HeidiSQL version:**  Revision 5315 (yours: 5315)
Compiled: 2018-10-29 (yours: 2018-10-30)

* **Operating system:** Windows 10, Version 1809 (OS Build 17763.55)

**Comment by mwidmann** [comment]
I have to correct myself. The issue with the incorrect scaling is present even on the main display. While Titlebar and Toolbar are scaled correctly on the secondary display they are way to small on the primaray display at 200%.

![heidisql_2018-10-31_08-15-19](https://user-images.githubusercontent.com/251322/47771897-49e27700-dce5-11e8-8d9d-b556a934117c.png)

I updated HeidiSQL to 9.5.0.5317 this morning.

**Comment by ansgarbecker** [comment]
I am currently working on high-dpi awareness, which is not yet fully supported. So it's quite explainable that switching from one monitor to the other has issues. For the moment I would be happy to have it all correctly zoomed on one monitor with one scale percentage. As this is all quite complex stuff and partly not supported by Delphi, I am not sure if I can fix this monitor switch issue at all. But we'll see.

**Comment by ansgarbecker** [comment]
The buttons are cut because their width is auto-calculated by the (too small) width of the session tree. Make it wider and the buttons are ok.

The title bar should be higher, yes. But that should go in ticket #213 .

Before I committed these changes, Windows just zoomed HeidiSQL up to your wanted scaling, which made it look very blurry. That's what #213 is all about.

**Comment by mwidmann** [comment]
Thanks for the explanation. In this case let's close this one and continue in #213

**Comment by ansgarbecker** [comment]
Let's keep this one open, as it's a more special issue which I want to solve separately from the other high-dpi glitches.

**Comment by SlyDave** [comment]
I'm also experiencing this issue, so here is an other data point:

OS: Windows 64bit Pro

**Primary Monitor: 3840 x 2160 (4k) with scaling set to 250%**
![image](https://user-images.githubusercontent.com/1842611/50769140-e9d6f680-127a-11e9-8181-3d59cde3f3ed.png)



**Secondary: 2560 x 1440 (WQHD) with scaling set to 100%** 
![image](https://user-images.githubusercontent.com/1842611/50769153-f3605e80-127a-11e9-8257-351994af9d51.png)

**Comment by Saibamen** [comment]
Similar: https://github.com/HeidiSQL/HeidiSQL/issues/479

**Comment by JGJP** [comment]
The weird thing about this is that on the official version 9.5.0.5196 it looks fine. It's only after upgrading to the latest build that I get this scaling issue

**Comment by JGJP** [comment]
Maybe there can be a setting in Preferences to make it DPI-aware or not? Because I mainly use HeidiSQL on my lower DPI monitors and it looks perfectly fine

**Comment by ansgarbecker** [comment]
If you mainly look at a low-dpi monitor then this scaling should not happen, and the issue should not affect you, does it?

**Comment by JGJP** [comment]
It affects me because I am running the low DPI monitors from my surface, which is high DPI. Anyway I noticed that you just published a new version, and this one looks fine on my low DPI monitors. Thanks!

**Comment by mwidmann** [comment]
Which version have you tried @JGJP ? I checked out v10 released yesterday and it looks like this on my external display. 
![heidisql_9gh0u0cluc](https://user-images.githubusercontent.com/251322/51686906-9f32d980-1ff1-11e9-9eae-95b5b5c514cf.png)

**Comment by slaFFik** [comment]
I've downgraded to v9.5. 
v10.1 looked awful on my 4K (main but additional external monitor) and QHD+ (on Dell XPS, 13"). Not preserving correctly columns width, squashing everything. Too small text in tables/table view.

**Comment by ansgarbecker** [comment]
v9.5 looks blurry with high DPI settings - this was discussed in #213. It may look ok enough for some people, but this is just a backward compatibility logic from Microsoft. The right way to go is the complex one - scale every component separately, to make them look sharp. Though that's really hard work, and v10.1 is the first version with support for that, so please have a bit of patience here.

**Comment by JGJP** [comment]
@mwidmann yes it was that version.
I figured out though that if one of my low-DPI monitors is set as the main monitor then it looks fine on the low-DPI monitors. It gets messed up when my high-DPI monitor is set as main

**Comment by mwidmann** [comment]
@JGJP yes, this is a situation that makes me furious. It's been years (an two major Windows versions) that Hi-DPI Laptops have been attached to lower DPI external monitors and Microsoft still hasn't found a way to handle this. Because it's not just the work of the app developers that needs to address this. I have windows opening outside of the screen bounds, I have system dialogs show in 200% on the 100% display, I have window snapping spanning the App over both screens and so on. This used to be so painless when I still was using MacOS. And they figured out how to make this stuff work years ago. 😤

**Comment by JGJP** [comment]
@mwidmann I agree, it's a total pain, getting off-topic though :^)

**Comment by tothandor** [comment]
Same for me. If I move the main window between primary (DPI 125%) and secondary (DPI 100%) screens, then toolbar icons are getting larger, and larger until it becomes useless.

**Comment by ansgarbecker** [comment]
@tothandor that is issue #446 , for which I still don't have a solution. Also I suppose the Delphi library needs more fixes for these dpi issues.

**Comment by ansgarbecker** [comment]
c31cae206042ae00b97e41f43baf7421693d2e46 now removes all tweaks for high DPI monitors. I'm giving up here, this does all not work good enough, even different computers and Windows versions behave differently. It's a mess. So, now HeidiSQL is zoomed by Windows again, like it was in earlier v9.5. This does at least display all controls and fonts in the right dimensions.

**Comment by JGJP** [comment]
@ansgarbecker thanks for looking into this, appreciate that it's kind of an edge case and very difficult to deal with. FWIW it also seems that it's affected by whether external displays were connected or not when the computer is booted up. Anyway, even the version I'm running now is workable, so not an issue.
