### ISSUE TITLE
Table edit tab over screen in high DPI mode

### ISSUE THREAD

**Issue by Jerry-Shaw** [HeidiSQL/HeidiSQL#380]
## Steps to reproduce this issue

1. Open HeidiSQL and connect to a database ;
2. Select a table, open edit tab;
3. Some modification to a table;
4. Cannot find "save" or "cancel" buttons in the bottom like before. Maximize or normalize the window does not help. The button area is over screen.

## Current behavior

Button area contains "save", "apply", "cancel" and others are missing from screen, and not show anyway.

## Expected behavior

There should be a action area in the bottom, like save or cancel.

## Possible solution

Window re-sizable, or a height fix? 
Up to the latest nightly version, the height is fixed both on maximize and normalized window. It can't be changed when opening edit table tab.

## Environment

* **HeidiSQL version:** 
  the latest nightly version and three or four versions before the latest, they all have the same issue.

* **Operating system:** 
  Windows 10 Pro 1803, screen resolution is 1920 * 1080, with 125% scale.

Some screenshots
![screenshot 1](https://user-images.githubusercontent.com/13212198/47758892-0b01f080-dce8-11e8-92c5-dcc0fd30f615.png)
![screenshot 2](https://user-images.githubusercontent.com/13212198/47758893-0b9a8700-dce8-11e8-943d-4ef18b1abb2e.png)

**Comment by ansgarbecker** [comment]
I am on the way to search fixes for high-dpi issues, in #213 .
This is another one, probably the most critical one on this topic.

**Comment by atmanegara** [comment]
i'm using heidisql 9.5.0.5321
![image](https://user-images.githubusercontent.com/9096711/47886588-eb98ce00-de75-11e8-9017-5217f3df09cc.png)

**Comment by atmanegara** [comment]
downgrade version 5.0.5196, is fine 
![image](https://user-images.githubusercontent.com/9096711/47888967-58b26080-de82-11e8-9d91-0d9796aff90c.png)

**Comment by Jerry-Shaw** [comment]
@atmanegara ,Yep, only the latest 5 or 6 nightly versions affected.

**Comment by ansgarbecker** [comment]
Hopefully fixed now, with the latest build.

Please also check.

**Comment by ansgarbecker** [comment]
Great news.

Any more glitches in high dpi mode?

**Comment by Jerry-Shaw** [comment]
Not found till now. So far so good. ^_^
