### ISSUE TITLE
When using ssh tunnel to connect mysql, prompt "can't connect to mysql server on localhost"

### ISSUE THREAD

**Issue by ajisheng** [HeidiSQL/HeidiSQL#381]
## Steps to reproduce this issue
1. Step 1;
![1](https://user-images.githubusercontent.com/25262830/47758786-8dd67b80-dce7-11e8-8518-c59b3ed8778d.jpg)

2. Step 2;
![2](https://user-images.githubusercontent.com/25262830/47758799-9e86f180-dce7-11e8-8a33-220bf3ab78ae.jpg)

4. Then I get...
![3](https://user-images.githubusercontent.com/25262830/47758871-ef96e580-dce7-11e8-8a2d-cc5c4a53c675.jpg)

## Possible solution
I guess you made a judgment in the program. If the IP is local, it will link to localhost directly, but some Linux systems do not have the localhost dns, which leads to such a result.
I think we can change localhost to 127.0.0.1 address.

## Environment
My server only has ssh port and 80 port open, so I need to link mysql through ssh tunnel.

HeidiSql: 9.5.0.5295
Mysql: 5.6.29
System: centos 6.5

I like HeidiSql very much, although it often exits abnormally or is unresponsive for a long time, but it has a great user interface that brings convenience to our work. It is like a child who is growing up. Although there are some bugs, its future is very bright. I am very happy to contribute to the growth of the child, although it is limited to testing and submitting bugs.

**Comment by ansgarbecker** [comment]
> I guess you made a judgment in the program. If the IP is local, it will link to localhost directly, but some Linux systems do not have the localhost dns, which leads to such a result.

Can confirm that! Although I am very aware of the fact that various systems cannot resolve "localhost", I seem to have decided to use "localhost" to connect to an established SSH tunnel. I just changed that to "127.0.0.1" for the next build. Please check out.
