### ISSUE TITLE
Microsoft Store Version: Dropping database leads to exception

### ISSUE THREAD

**Issue by morris-t** [HeidiSQL/HeidiSQL#382]
## Steps to reproduce this issue

1. Open windows store version of HeidiSQL
2. Connect to DB server
3. Right-click on DB and select drop
4. Exception triggered

## Current behavior

Microsoft store version of HeidiSQL triggers exception when attempting to drop database.

## Expected behavior

I was expecting the DB to be dropped. 

## Possible solution

Not Sure.

## Environment

* **HeidiSQL version:** 
9.5.0.5249
* **Database system and version:** 
MySQL 5.7 (Google CloudSQL)
* **Operating system:** 
Windows 10 64 bit

**Bug Report:** [bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2533842/bugreport.txt)

**Comment by ansgarbecker** [comment]
I cannot reproduce this issue with the current release. Can you retry please?

**Comment by slaFFik** [comment]
I'm using the latest (v10.3.0.5771) version of the MS Store HeidiSQL.
I can't replicate this issue when dropping _local_ MySQL databases.

**Comment by ansgarbecker** [comment]
The MS Store version is deprecated. Please retry with the official v12.0 and reopen if issue is still present.
