### ISSUE TITLE
Table options change engine doesn't appears

### ISSUE THREAD

**Issue by neto737** [HeidiSQL/HeidiSQL#383]
## Steps to reproduce this issue

1. Open database on HeidiSQL
2. Open "options" tab in any table 
3. Cannot change the engine or something else

## Current behavior

Screenshot: http://prntscr.com/lctz6x

## Environment

* **HeidiSQL version:** HeidiSQL 9.5.0.5320
  
* **Database system and version:** MariaDB 
  
* **Operating system:** Microsoft Windows 10 Pro 1809 Build 17763.55

**Comment by ansgarbecker** [comment]
Thanks for updating this.

And yes, this is related to the high DPI support I am currently working on. See #213 for more details and a checkbox / task list.
