### ISSUE TITLE
Split database object listing into subfolder

### ISSUE THREAD

**Issue by stahl-riesa** [HeidiSQL/HeidiSQL#386]
My issue is a feature request.

It would be more comfortable to split the database object listing into subfolders:

- tables
- views
- functions
- sequences
- trigger

**Comment by ansgarbecker** [comment]
This is already done in HeidiSQL: rightclick the tree, then point to "Tree style options", then click "Group objects by type.

**Comment by stahl-riesa** [comment]
Oh, thanks! I didnt know! Great!
