### ISSUE TITLE
PostgreSQL: Hide pg_temp tables

### ISSUE THREAD

**Issue by stahl-riesa** [HeidiSQL/HeidiSQL#387]
PostgreSQL uses pg_temp_[1-9][0-9]* pg_toast_temp__[1-9][0-9]* tables for internal stuff.

They should not be visible by default.

**Comment by SmallhillCZ** [comment]
I believe there should also be an option to hide all the `pg_*` tables. Or put them in a separate tree branch.

**Comment by ansgarbecker** [comment]
@SmallhillCZ you mean `pg_*` tables or databases?

Would it make sense to add a checkbox in the Advanced session settings, labelled "Hide temporary and internal databases", and also hide `information_schema` on MySQL, as well as `performance_schema` and `mysql` ?

**Comment by SmallhillCZ** [comment]
**Temporary tables:**
After giving it a little thought must say the temporary tables should be visible somewhere (unlike in pgAdmin where they are hidden in the UI), its just that Postgre pollutes the list with these schemas pg_temp_1, pg_temp_2, etc. and aliases pg_temp to the currently used temp schema. It would be nice if HeidiSQL would hide the numbered pg_temp tables and show just the currently used aliased pg_temp.

**Technical tables:**
With the technical tables like pg_catalog, information_schema, etc. I would like the best if they could be somehow separated from the data tables - either in their own branch, sorted at the bottom of the list or hideable with some button). For example pgAdmin separates two branches: Schemas, where your data lies and Catalogues where pg_catalog and information_schema lies.

**Comment by lovikraba** [comment]
Hi. How can we accelerate this improvement? :)

**Comment by ansgarbecker** [comment]
I think I'll add a new input box in the "Advanced" session settings, labelled "Hide databases", allowing a regular expression, with a default of "^pg_temp_\d". Users who want to see these can remove that filter, and a regular expression makes this highly flexible.

**Comment by ansgarbecker** [comment]
I just added that new input box on the session manager's advanced tab. Please not that for existing sessions the user has to specify a pattern there. For newly created connections, HeidiSQL adds that pg_temp pattern mentioned above.
