### ISSUE TITLE
Table column default window close time exception.

### ISSUE THREAD

**Issue by elky84** [HeidiSQL/HeidiSQL#389]
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2560996/bugreport.txt)

## Steps to reproduce this issue

table default column close time.

## Current behavior

show exception window.

## Expected behavior

don't show exception window.

## Environment

Windows 10 64bit Enterprise
version 1803
OS Build 17134.345

* **HeidiSQL version:** 
9.5.0.5327
* **Database system and version:** 
mysql8
* **Operating system:** 
Windows 10 64bit build

**Comment by ansgarbecker** [comment]
Confirmed

**Comment by ansgarbecker** [comment]
This crash only happens when a theme is currently active. It doesn't happen with the default "Windows" theme.

**Comment by elky84** [comment]
@ansgarbecker 

wow, really not happen crash after follow your guide。

but i want dark theme。so i fix please。

thank regard。

**Comment by ansgarbecker** [comment]
Should be fixed for themes in the latest build now.
