### ISSUE TITLE
Cannot create VIEW on MSSQL

### ISSUE THREAD

**Issue by ionred** [HeidiSQL/HeidiSQL#39]
## Current behavior

When creating a view on MS SQL 11.0 DB, algorithm is set to undefined, but instead of ignoring algorithm in the create statement, it still leaves "ALGORITHM = UNDEFINED"  at the beginning of the create. The entire Alg section should be unavailable/grayed out as well for a MSSQL connection.

## Failure information (for bugs)

/* SQL Error (343): Unknown object type 'ALGORITHM' used in a CREATE, DROP, or ALTER statement. */
### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. CREATE ALGORITHM = UNDEFINED VIEW "V_ZCUSTOM_AGTDATA" AS .......
2. /* SQL Error (343): Unknown object type 'ALGORITHM' used in a CREATE, DROP, or ALTER statement.*/

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.4
* Database system + version:  MS SQL 11

**Comment by ansgarbecker** [comment]
The view editor in HeidiSQL does currently not care for other systems but MySQL/MariaDB. I guess the controls (definer, sql security, algorithm and check option) are not applicable to a view in MSSQL, or? Is there some good documentation on how to read and write views in MSSQL?

**Comment by ionred** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-view-transact-sql
is the most specific information I can find on create view. 
There are "view attributes" that I can't speak for their necessity; but they sound like limited need items for implementation. The rest of the options in the create view screen can likely be dithered/disabled on MSSQL connections.

**Comment by Mihair** [comment]
@ansgarbecker Similar issue with editing an existing view:

Hit "Save" and receive an error:

`ALTER SQL SECURITY DEFINER VIEW "ExampleView" AS SELECT ...`
`/* SQL Error (343): Unknown object type 'SQL' used in a CREATE, DROP, or ALTER statement. */`

Literally all we need for MS SQL is to ignore the header options so the command sent is simply ALTER VIEW ...
Like @ionred mentioned, the other MS SQL specific options are of limited need.

**Comment by ionred** [comment]
Hi @ansgarbecker , is there an update on this bug?

**Comment by ansgarbecker** [comment]
Not yet, but if it's really just that I have to remove the mentioned clauses, I can try to get this done for the next release.

**Comment by ionred** [comment]
I would say removing the extra clauses would resolve the bug. If anybody
needs any extra functionality related to the MS SQL specific  CREATE VIEW
statement. Then they can open that up as a feature request or enhancement

**Comment by ansgarbecker** [comment]
Long story short: should work with the next build :)

![grafik](https://user-images.githubusercontent.com/7986591/70084474-96963100-160e-11ea-9971-e43ded05b1a7.png)
