### ISSUE TITLE
excessive right padding in query right panel

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#390]
this appeared fairly recently, don't know exact build when it regressed (maybe something to do with themes?)

![heidisql_padding](https://user-images.githubusercontent.com/43234/48215854-c958f180-e348-11e8-9744-6ad20632fec4.png)

Windows 10, HeidiSQL 9.5.0.5327

thanks!

**Comment by ansgarbecker** [comment]
When you expand the "Columns in..." tree node, you see something like this:

![grafik](https://user-images.githubusercontent.com/7986591/48217317-56bb3680-e387-11e8-97c6-9ad5cff1a370.png)

So the space is needed for the second column in that tree. I suppose this was the case for years now?

**Comment by leeoniya** [comment]
> I suppose this was the case for years now?

no, something has changed recently.

here's a comparison between current build (5327) and stable build (5196). (i loaded the same `portable_settings.txt` and `snippets` into both builds).

![heidisql_padding2](https://user-images.githubusercontent.com/43234/48224429-4ee79c00-e35f-11e8-841f-b778681268f8.png)

![heidisql_padding3](https://user-images.githubusercontent.com/43234/48224648-13999d00-e360-11e8-93e9-e924597253f9.png)

**Comment by ansgarbecker** [comment]
Ups... in that case - thanks for the update :)

**Comment by Arffeh** [comment]
![image](https://user-images.githubusercontent.com/2135196/48592498-cab79900-e99c-11e8-954b-2a95a8c8dfe2.png)

Yeah its not great. That's made my current workflows severely hampered.

If we could resize that section horizontally it would be workable.
Actually resizing that has been something I've wanted for years. ;)

**Comment by ansgarbecker** [comment]
Resizing column would require the column headers to be shown. Do you have suggestions how to label these?

**Comment by ansgarbecker** [comment]
These shortened tree nodes were caused by 1e92d36ceac7332853f09744613dcdc52801a762, where I disabled `toAutoSpanColumn` in that VirtualTree, while thinking this wiould fix an high dpi issue (#213). I just reverted that, so we have the old length again.

If you'd still propose manual resizing and showing column headers then please another ticket.

**Comment by leeoniya** [comment]
thank you!
