### ISSUE TITLE
Multi Column Filter With NonLatin Character Cause Mysql Error

### ISSUE THREAD

**Issue by sysulincn** [HeidiSQL/HeidiSQL#392]
## Steps to reproduce this issue

1. create a table with columns in type  Date/DateTime/Time/Timestamp like below:
`CREATE TABLE `ActDataDefine_DB` (
	`ActName` VARCHAR(100) NOT NULL,
	`DataName` VARCHAR(100) NOT NULL,
	`TableId` TINYINT(3) UNSIGNED NOT NULL,
	`DataId` SMALLINT(5) UNSIGNED NOT NULL,
	`WeeklyClear` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
	`LastReadDate` DATE NULL DEFAULT NULL,
	`LastWriteDate` DATE NULL DEFAULT NULL,
	`CreateTime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`TableId`, `DataId`),
	UNIQUE INDEX `ActName` (`ActName`, `DataName`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;`

2. open mysql table in heidisql, open the tab 'Data' of the table, fill in some non-latin character, and Click 'Apply Filter'

## Current behavior
It create 'ColName like '%filter%' for every column, and mysql server will throw an error with the 'like' operation with the Date/DateTime/Time/Timestamp column like the pic below ：
SQL Error(1271): Illegal mix of collations for operation 'like', 
then I have to delete the "ColName like '%filter%'" for every  Date/DateTime/Time/Timestamp columns
![image](https://user-images.githubusercontent.com/11144099/48330091-591ed880-e686-11e8-8a49-929a532bd731.png)

## Expected behavior
for Date/DateTime/Time/Timestamp Columns, change the filter string 
"`ColName` LIKE '%filter%'"
TO
"`ColName` LIKE BINARY '%filter%'"
when generate the filter string with the apply filter button.

## Environment

* **HeidiSQL version:** 
HeidiSQL 9.5.0.5332
* **Database system and version:** 
mysql server 5.5 or later
* **Operating system:** 
windows

**Comment by ansgarbecker** [comment]
Should be fixed now in the latest build. But I am generating a `CAST(mycol AS CHAR)` instead of your proposed `mycol LIKE BINARY ...`. Please test if that works for you.
