### ISSUE TITLE
Version portable not updated

### ISSUE THREAD

**Issue by lucashtc** [HeidiSQL/HeidiSQL#393]
## Steps to reproduce this issue
1. Download version Portable version (zipped): 32 bit , 64 bit [Link](https://www.heidisql.com/download.php)
## Expected behavior
Download updated portable version

## Possible solution
Update

## Environment
Windows 10

* **HeidiSQL version:** 
 9.5.0.5196
* **Database system and version:** 
 MySQL 5.6 or later
* **Operating system:** 
Windows 10

**Comment by lucashtc** [comment]
I know I can use the update in the application itself, but without my case the machine is limited to the user

**Comment by ansgarbecker** [comment]
I don't get it. What's exactly the issue in HeidiSQL here?

**Comment by lucashtc** [comment]
The HeidiSQL portable download link is not an updated version.

**Comment by ansgarbecker** [comment]
That link is the official recent release, not a nightly build. Nightly builds can be manually updated for the portable version, by just downloading the right heidisql.exe from the builds section.

**Comment by lucashtc** [comment]
Thank you very much.
