### ISSUE TITLE
"Duplicate row" doesnt duplicate primary or unique fields

### ISSUE THREAD

**Issue by arikanorh** [HeidiSQL/HeidiSQL#396]
## Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/17791032/48468550-3e22a480-e7fd-11e8-8b20-ca40d7c5dcc0.png)

1. Step 1; Create table with multi-column primary key and other fields
2. Step 2;Insert some data
3. Step N; Then duplicate row
4. Then I get empty fields on primary key fields

## Current behavior
The fields are empty

## Expected behavior
I expect those fields are duplicated as above row

## Possible solution
just duplicate those columns and let user change them

## Environment

* **HeidiSQL version:** 
9.5.0.5337 (64 Bit)
  
* **Database system and version:** 
MySQL
  
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
HeidiSQL lets these out intentionally, as you would get some "duplicate entry" error when posting such values. The user would be _forced_ to change unique values otherwise. That's a solution to a problem, not a bug. What do you propose to solve that issue?

**Comment by arikanorh** [comment]
Leaving empty throws another error. This just change the problem not solve them. This also makes the problem worse. What i mean that, when you duplicate a row a and leave primary fields empty, user have to type all the fields, that nullifies convinience of duplicating row.

But after duplicating all fields no matter what, user have to change only one primary key field to make it not duplicate.

In my case, there are 3 primary fields which two of them are timestamps. When those are left empty, I have to manually type those 3 fields. Bu all i need the change the just hour value of the one timestamp column.

You force the user fill 3 column instead of just change a part of 1 column.

I believe that my solution is more convinient for duplicating the row.

**Comment by ansgarbecker** [comment]
As there were users complaining about exactly these unwanted unique key values in a duplicated row, I propose a second "Duplicate row" menu item, perhaps labelled "Duplicate row with keys". The other one should probably renamed to "Duplicate row without keys". Hoping that "keys" is clear for the user that it means "primary or unique key values", as that would be too long for the context menu.

**Comment by ansgarbecker** [comment]
Just implemented that new item to the context menu. Please test and report back.

**Comment by arikanorh** [comment]
Hey, just tested and working as expected. Thanks
