### ISSUE TITLE
feature: log all schema changes in table of that db server

### ISSUE THREAD

**Issue by penCsharpener** [HeidiSQL/HeidiSQL#397]
## Current behavior

Heidi can log all executed queries to log files. 

## Expected behavior

new option in Heidi to allow logging schema changes like CREATE TABLE, ALTER TABLE, DROP Table/Column etc. to a specified table on that db server. 
Some frameworks like php-laravel ship with migrations but if you develop without a framework and in a team it would be great to have Heidi logging away any schema change. The current query logging is too cluttered for that.
Storing schema changes as SQL statements in the database itself is helpful in a team as the current .log files Heidi creates are only available locally on that PC.

## Possible solution

This probably needs to be a setting per connection.
Heidi would require a user privileged enough to create at least a table in a specified database. 
The table should have a primary key, a column with the database name and then the query in a text or mediumtext column. An addition column 'comment' as TEXT could be used to make some notes for others in a team. 

## Environment

* **HeidiSQL version:** 
  9.5.0.5332
* **Database system and version:** 
  MariaDB 10.3 and MySQL 5.7.23
* **Operating system:** 
 Win 10 1803

**Comment by timint** [comment]
👍 @penCsharpener Have a look at my post https://github.com/HeidiSQL/HeidiSQL/issues/985

**Comment by penCsharpener** [comment]
yes, I'd still like to see that feature. 
Especially when working within a team on a shared dev server without a framework at hand that supports migrations this could be a really powerful feature. 
In the end it only needs to filter out the schema changes and dump it in a table on that server.

**Comment by timint** [comment]
So a way to log just the queries that performs all the writes (create/alter/update/insert/delete/truncate).

@penCsharpener What would you prefer?
A) Having that setting inside the session profile
B) Using a record button sort of like a macro
C) Or have them both, cake and cookies? ;)

What did you think of the idea of being able to use date parameters for the file? E.g. C:\Folder\Project\migration-%Y%m%d.sql.

**Comment by penCsharpener** [comment]
I like the data parameters. 

There is value is both options. The migration file I see useful if you have multiple databases (lokal, dev, prod) and need to apply the same change to all. However if you work in a team on a shared db then being able to log them straight to a table is more convenient. But having just the file for now would enable the devs to copy the sql migrations to their table manually. 

The migrations file can be a global setting, The migraitons to a table however makes sense only per connection.

**Comment by ansgarbecker** [comment]
What would you do with these logged queries - either in a file or in a server-side table. Would you copy them and run them on your local server, or what's the exact use case here? You have no version specific attribute, so you would have to guess which queries you did not yet run, or?

**Comment by penCsharpener** [comment]
I haven't thought about those details yet. A timestamp in that table would help. 
But basically yes; just record them and then run them on a different server manually. The user needs to find their own way of marking already applied migrations.

However if you record sql querys directly on the server then a hash of the applied sql along with a timestamp could serve as a migration history, to see what has already been applied and what hasn't. 
I'm just flying a kit here... maybe you have better ideas.

**Comment by timint** [comment]
I can only speak for myself. I have a dev and production environment. Planning to upscale to multiple production environments for one project.

I store sql changes in a folder of migrations e.g. .migrations/20200414.sql.

When deployed the receiving platforms discovers a new migration patch that is not processed. It will then process it immediately and store the filename in .migrations/.migrated. The .migrated file is what keeps track of what's migrated.

**Comment by timint** [comment]
Any chance this is happening?

**Comment by ansgarbecker** [comment]
Well, why not. But I'd like to keep it simple:
* Logging should not be done to the server itself, but to files, so the server is not affected with these things
* I like your file path suggestion. HeidiSQL already creates some other files, so these could go to
  `C:\Users\<user>\AppData\Roaming\HeidiSQL\Migrations\<session-name>\YYYYMMDD-<incremented-number-per-day>.sql`
* this still would not separate queries you ran in different databases, which is something I don't read in the above comments, so this may be ok
* I suppose you want these in your project folder instead, so the migration folder should be customizable per session, in the "Advanced" tab
* migration files should be disabled by default, so we need a checkbox on the same tab as well: "Store migration to files"
* finally, I see a challenge in distinguishing relevant queries from irrelevant ones - probably a quick look for "CREATE" or "ALTER" at the beginning of a query is sufficient

More things to consider, or any other feedback?

**Comment by timint** [comment]
We are pretty much on the same page. :)

Perhaps <database-name> could be added to your path variables?

Looking for CREATE and ALTER is good for the structure. Maybe INSERT, UPDATE and DELETE can be optional? One way could be two checkboxes [ ] Structure (CREATE, ALTER), [ ] Data (INSERT, UPDATE and DELETE).

**Comment by ansgarbecker** [comment]
So the next build has the following checkbox and directory input box:
![grafik](https://user-images.githubusercontent.com/7986591/106104654-06387b00-6143-11eb-8c83-bf5dd03c92b9.png)

I decided to make the base path customizable only. HeidiSQL appends `<session-name>\<database>\YYYYMMDD-<session-counter>.sql` to this path. The user may change the folder to some other folder.
Logging of DML queries like INSERT, UPDATE, etc. makes no sense, as there is already the "normal" log-to-file feature doing the same.
Please note that enabling the checkbox may slow down HeidiSQL slightly, as each fired query has to be checked, and in CREATE/ALTER/DROP cases it opens the log file and closes it immediately. This way it's also possible to write to the file from outside between queries, without getting an error.
If the log file or folder cannot be created or written, an error is shown in the log panel, and logging is automatically disabled for the current session.

**Comment by timint** [comment]
> I decided to make the base path customizable only. 

Not being able to customize the filename is a downside. I personally gather all changes by date and how many sessions I used is irrelevant. So I would be interested in appending to an existing .sql with today's date rather than sessions. But people might do things different? It shouldn't be too much trouble allowing the user to set filename. I feel this is just introducing new limitations rather than unlocking potential.

There are 3 major date formats in the world (Big, mid and small endian). Not everyone uses YMD.

When would one want to use %h %i %s for the folder name? It serves good sense in a filename but not a folder name.

Will all strftime formats be supported or are you handpicking them? The english fellows might want am pm also.

> Logging of DML queries like INSERT, UPDATE, etc. makes no sense, as there is already the "normal" log-to-file feature doing the same.
Sorry what feature are you referring to? Settings -> Logging? That feature is just dumping the last 300 lines of window log to a file, yes? I like it that I see my selects etc in the log buffer window. But I wouldn't want to store my selects to a log file. What do you propose? :(

> Please note that enabling the checkbox may slow down HeidiSQL slightly, as each fired query has to be checked, and in CREATE/ALTER/DROP cases it opens the log file and closes it immediately. 
Yes, thanks. This is an expected behavior.

Don't forget RENAME TABLE :)

**Comment by ansgarbecker** [comment]
> Is there a technical limitation that lead to your solution?

yes, I am thinking the user does not want to write to a file from an earlier session, so I had to append that session counter to the end of the filename, whereas this counter is not available through a placeholder yet. By the way, there are some supported placeholders, shown in my screen above. But mostly useless, as the filename itself is not part of the customizable path, as said. It's just that these placeholders are available in some other places in HeidiSQL, for example in the SQL export filename box. So that's why I'd like to stick with these.

So your suggestion is to make the file path fully customizable, and probably add some useful placeholders? As I don't want to imitate strftime, could you pick most important ones missing yet?

> Sorry what feature are you referring to? Settings -> Logging?

Yes, that's what I meant. That's not limited to 300 lines. But yes, it records boring SELECTs as well.

You suggest to create that second checkbox for DML queries as well? I'm unsure, would that be used by many?

**Comment by timint** [comment]
> So your suggestion is to make the file path fully customizable, and probably add some useful placeholders?

Yes, I see a lot of good potential in being able to set the filename. I'm a web developer and have zero knowledge of the framework or environment you use. I would have thought just passing the parameters to strftime and not reinvent the wheel would be the fastest way. But maybe strftime is not available in your environment? I think the most critical are already covered in your list.

How many extra hours of work is it to produce the filename in the log path?

> You suggest to create that second checkbox for DML queries as well? I'm unsure, would that be used by many?

No I don't think many would use it.

**Comment by ansgarbecker** [comment]
So, next build has two checkboxes, and lets the user customize the whole file path. Supported placeholders for the file are still the same:

![grafik](https://user-images.githubusercontent.com/7986591/106244779-bd98c480-620b-11eb-9d1a-9182ae75a676.png)

**Comment by ansgarbecker** [comment]
I suppose I can consider this feature as done.
