### ISSUE TITLE
Select type - description cutted

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#398]
## Steps to reproduce this issue

1. Step 1; Select new/edit table
2. Step 2; select one colunm type int / smallint
3. Step 3; put the mouse over the type
4. Then you see the desription cutted

## Current behavior
![image](https://user-images.githubusercontent.com/11230133/48631855-9f39ac00-e9a6-11e8-8cc7-5172c287a6ce.png)

i think its missed tranlation too (i'm using Portuguese - Brazil)

## Environment

* **HeidiSQL version:** 9.5.0.5338
* **Database system and version:** MARIA DB 10.2.19
* **Operating system:** Windows 10 64

**Comment by fifonik** [comment]
I'm also see the issue.
