### ISSUE TITLE
VARCHAR Custom default value as empty string is escaped

### ISSUE THREAD

**Issue by Mesolo** [HeidiSQL/HeidiSQL#399]
## Steps to reproduce this issue

1 - Add or edit a field in a table as varchar
2 - Set the default value as Custom with empty string ''
3 - Hit save
4 - Open tab CREATE code

## Current behavior

When I set the default value for a varchar filed as Custom with value of `''` (empty string), the code generated for create the table is escaped ( I suppose) like this: 

`CREATE TABLE test3 (
    Colonna 1 VARCHAR(50) NULL DEFAULT '\'\''
)`

The result is that the defult value is not an empty string, but a double single quotes.

## Expected behavior

I expect the generated code for create looks like this:

`CREATE TABLE test3 (
    Colonna 1 VARCHAR(50) NULL DEFAULT ''
)`

## Possible solution

Maybe remove the escaping for the default value

## Environment

Using italian version of the program ( i switched to English, with the same behavior)
Tried the table collation as utf8_general_ci and utf8_latin_ci

* **HeidiSQL version:** 
  v. 9.5.0.5338 (64 Bit)
* **Database system and version:** 
  MariaDB 10.1.33
* **Operating system:** 
  Windows 10 pro 64bit

**Comment by fifonik** [comment]
Not sure why you adding two apos as default.
You should select 'Custom' in Default and type nothing.
Otherwise you telling SQL server that you'd like your default should be two these apostrophes.

I believe that Heidi's behaviour is correct.

**Comment by Mesolo** [comment]
Ok I understand now, doing like you said is creating the correct default value.
I add two apos because in ohter software it's needed if you want an empty string as default (like the pure SQL statement for create or alter), so i was so used to this behaviour that i though was a bug.
Thank you for your reply, i'm closing the issue.
