### ISSUE TITLE
Azure Database for MySQL connection throws error - "SSL connection error: ASN: bad other signature confirmation"

### ISSUE THREAD

**Issue by philcarbone** [HeidiSQL/HeidiSQL#4]
## Expected behavior
Connection to the SQL server with no errors

## Current behavior
Getting error "SSL connection error: ASN: bad other signature confirmation"

## Failure information (for bugs)
This is when adding a **SSL CA certificate** only (Under the **Advanced** connection settings)

Microsoft provides SSL connection documentation here:
https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl#applications-that-require-a-local-certificate-for-ssl-connectivity 

Also, there are already instructions on how to do this with **MySQL Workbench**: 
https://docs.microsoft.com/en-us/azure/mysql/connect-workbench

### Steps to reproduce

1. Create a new **Azure Database for MySQL** database 
(fully hosted/clustered db by Microsoft Azure - https://azure.microsoft.com/en-us/services/mysql/)
2. Download the SSL CA that Microsoft provides, here: 
https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl 
3. Next, in **HeidiSql**, create a new connection and point to the new Azure database (created in step 1)
4. While still creating your connection, switch to the **Advanced** tab to setup the SSL
5. In the **Advanced** tab, add the **SSL CA certificate** that was just downloaded (only this file-field should be filled in).
6. **Save** and **Open** the connection 
7. Get error

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.4.0.5125 (64-bit)
* Database system + version: Azure Database for MySQL
* Operating system: Windows 10 Pro 64-bit (Fall Creators Update)

### Failure Logs

SSL connection error: ASN: bad other signature confirmation

**Comment by MystK** [comment]
I also ran into this.

HeidiSQL version: 9.5.0.5238 (64-bit)

I was able to verify that it works fine in MySQL Workbench.

**Comment by qnaalx** [comment]
Same Problem here.
HeidiSQL 9.5.0.5196 64Bit
Also on 
HeidiSQL 9.5.0.5278
OS: Windows 10 1709 64bit
![2018-05-25 10_51_40-verbindungsmanager](https://user-images.githubusercontent.com/7326959/40535569-be6d07c4-6009-11e8-9257-4ff3e88b314d.png)

**Comment by amitghosh-inwt** [comment]
Same problem here:

* HeidiSQL 9.5.0.5196 (64 Bit)
* Client OS: Windows 10 1703 Pro 64 Bit
* connecting to MariaDB 10.1 (Ubuntu 16.04)
* no problems connecting using MySQL Workbench

**Comment by philcarbone** [comment]
Once this works I can get the new connection instructions posted next to this document on Microsoft's site: 
https://docs.microsoft.com/en-us/azure/mysql/connect-workbench

**Comment by nzkozar** [comment]
Any solutions for this? I can't connect to my azure db because of this bug.

**Comment by MystK** [comment]
Turn off SSL

Antoine Pham

On Feb 12, 2019, at 2:33 AM, Anže Kožar <notifications@github.com<mailto:notifications@github.com>> wrote:


Any solutions for this? I can't connect to my azure db because of this bug.

**Comment by nzkozar** [comment]
@MystK Turning off SSL is sadly not an option, due to project requirements.

**Comment by Irwandi1987** [comment]
hi, is the issue solved ? because i have the same issue here.

**Comment by ansgarbecker** [comment]
I am not sure. The report is related to v9.5. Probably this was fixed along with my update for all libraries in HeidiSQL 10.0/10.1. Could someone please verify whether this is still an issue with the latest version?

**Comment by amitghosh-inwt** [comment]
We had the same problem over the last years. I just tried with 10.1.0.5464 (x64) and indeed, the problem fixed. Thank you so much!

**Comment by Irwandi1987** [comment]
@amitghosh-inwt thanks for the information. Do you try to using ssl ca certificate only ?

**Comment by amitghosh-inwt** [comment]
> Do you try to using ssl ca certificate only ?

We are using a server with a certificate issued from a private (Windows) CA and require the clients to authenticate with client certificates from the same CA.
