### ISSUE TITLE
I can't start heidisql in windows 7

### ISSUE THREAD

**Issue by BigWolf286** [HeidiSQL/HeidiSQL#401]
## Steps to reproduce this issue

1. Step 1;   when i click  heidisql.exe  in windows 7  .Unable to display interface
2. Step 2;  But when I used it before, it was okay,  I uninstall and reinstall, but I can't display the interface
3. Step 3; when i Click twice ， I'm looking at the task manager，It is show as follows
![image](https://user-images.githubusercontent.com/26453138/48753987-04eda700-eccb-11e8-90ed-b627020bc24b.png)
4. Then I can’t see the interface.

## Current behavior

4. Then I can’t see the interface
## Expected behavior

5. after  click  heidisql.exe   show Display interface
## Environment

 windows 7 , connect mysql 
* **HeidiSQL version:** 
  
heidisql  9.5.0.5196 64 bit

![48753987-04eda700-eccb-11e8-90ed-b627020bc24b](https://user-images.githubusercontent.com/26453138/48754740-c1486c80-eccd-11e8-8fb2-913601d8986b.png)

**Comment by ansgarbecker** [comment]
Please update to the latest build and check if the problem persists.

**Comment by BigWolf286** [comment]
![image](https://user-images.githubusercontent.com/26453138/49200597-81257000-f3d8-11e8-80d5-ae8a4f8fd6fe.png)
sorry ，the problem persists.

**Comment by ansgarbecker** [comment]
Ok, in that case...
Could you please test the following:
* exit all open heidisql instances
* start regedit.exe
* navigate to the key `\\HKEY_CURRENT_USER\Software\HeidiSQL`
* delete the values beginning with `MainWin...`, as shown in the screenshot
* restart heidisql and see if Heidi is now visible somewhere

![grafik](https://user-images.githubusercontent.com/7986591/49205127-545c6300-f3ae-11e8-96ba-2c3d8f44570f.png)

**Comment by BigWolf286** [comment]
![image](https://user-images.githubusercontent.com/26453138/49262241-9eae1480-f480-11e8-9934-82a5f2323b31.png)
thanks  bigGod, it is ok now

**Comment by BigWolf286** [comment]
![image](https://user-images.githubusercontent.com/26453138/49262926-7d9af300-f483-11e8-92a4-812f729ad85e.png)
thanks , new problem

**Comment by ansgarbecker** [comment]
[Here's](https://www.heidisql.com/forum.php?t=10835) a forum thread which may contain some help.

**Comment by ansgarbecker** [comment]
And [another one](https://stackoverflow.com/questions/12432260/heidisql-connecting-to-mysql-server-lost-connection-server-at-reading-initia)

**Comment by ansgarbecker** [comment]
Initial problem was solved. For different issues create a new report please, if it's a HeidiSQL issue at all.
