### ISSUE TITLE
Upper area of table editor gets higher on each table click

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#405]
## Steps to reproduce this issue

1. Create table and view for testing:
```
DROP TABLE IF EXISTS t;
CREATE TABLE `t` ( `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, `val` VARCHAR(15) NOT NULL, PRIMARY KEY (`id`));

DROP VIEW IF EXISTS v;
CREATE VIEW v AS SELECT * FROM t;
```
2. Refresh tree (F5)
3. Click at the table in the tree and select 'Basic' tab. Notice the height of Comment and the height of columns area (marked in red on the first imags below)
4. Click at the view in the tree
5. Click at the table in the tree again. Notice that the height of column is much bigger now (marked in red on images below)

If you continue to switch between view and table you may have troubles with resizing the columns area back to normal as with every step the top arear becoming higher so columns area is becoming smaller and then going off screen.

Screenshots (I just clicked the table and view in tree, have not done anything else):
![table1](https://user-images.githubusercontent.com/7234987/48807974-fce54400-ed6a-11e8-9741-c0561cdefac2.png)

...Here I switched to the view, nothing really interesting there...

![table2](https://user-images.githubusercontent.com/7234987/48807985-0373bb80-ed6b-11e8-85b5-e4b4f492d3b9.png)

...Here I switched back to the view...

![table3](https://user-images.githubusercontent.com/7234987/48807996-08d10600-ed6b-11e8-8c6d-4232696c2728.png)

## Current behavior

Name + Comment area becoming bigger every time you are switching from View to Table in tree

## Expected behavior

The Name + Comment area should not be changed

## Environment

* **HeidiSQL version:** HeidiSQL 9.5.0.5338 64 bit
* **Operating system:** Windows 10 1803 64-bit

**Comment by ansgarbecker** [comment]
This is an issue with the new support for high DPI resolutions. See also issue #213 .
I already added a workaround for that area so it does not become invisible at some point, but somehow this was useless when I see your screenshots.
