### ISSUE TITLE
[BUG] [MYSQL] Export table with computed field to another database causes error

### ISSUE THREAD

**Issue by rv-rsouza** [HeidiSQL/HeidiSQL#407]
## Steps to reproduce this issue

1. Create a simple table with one generated/computed field and insert some data in it
2. Rightclick the table and select "Export database as SQL"
3. Choose any option but "No data" in "Data" field
4. Choose another server or database for "Output"
5. Choose the destination "Database"
6. Click "Export"
7. When the export operation reaches a computed column, an error is returned

## Current behavior

When trying to export a table data from one server to another, if the table has a computed field, the export fails for that table:

>SQL Error (3105): The value specified for generated column 'computed_column_name' in table 'table_name' is not allowed.

The table in question has a column with a simple formula: `AS (columnA + columnB * + columnC)`

## Expected behavior

Only non computed columns should be copied.

## Environment

* **HeidiSQL version:** 
  9.4.0.5125 (32 Bit)
* **Database system and version:** 
  MySQL Community Server (GPL) 5.7.11-log linux x86_64
* **Operating system:** 
  macOS High Sierra (10.13.6) running Wineskin Winery 2.6.2 with engine WS9Wine2.22

---
Issue from forum: https://www.heidisql.com/forum.php?t=23866#p24454

**Comment by ansgarbecker** [comment]
Please update HeidiSQL to the latest build and recheck if the problem persists. I recall I already worked on that issue.

**Comment by ansgarbecker** [comment]
See #5 - should already be solved in v9.5 from December 2017
