### ISSUE TITLE
Configurable web search engine for "Find help" links on dialogs

### ISSUE THREAD

**Issue by paulvi** [HeidiSQL/HeidiSQL#411]
When SQL error pops up, it has nice link to search online.

However it uses google.com, and there is no preferences to configure what search engine to use.

Please add option for search engine, with google.com being default.

**Comment by ansgarbecker** [comment]
I should do it similar to how Notepad++ offers to customize the search engine:

![grafik](https://user-images.githubusercontent.com/7986591/54081557-d261cb80-4306-11e9-9ef1-255c233aeaf4.png)

**Comment by paulvi** [comment]
yes, indeed. FOSS software should not promote specific vendor services.

Please add China baidu option as well.

See http://gs.statcounter.com/search-engine-market-share/all/china

P.S. or manual config can do as well.

**Comment by ansgarbecker** [comment]
I just added a combo box with several predefined search engines. Also allows custom urls:

![grafik](https://user-images.githubusercontent.com/7986591/56315499-1e9af980-6158-11e9-8ea3-f12ee8968a51.png)

I will get space problems when having to add even more preference options on that page - the "General" tab is now officially overcrowded.
