### ISSUE TITLE
Auto uppercase can be inconvenient

### ISSUE THREAD

**Issue by muzza4** [HeidiSQL/HeidiSQL#412]
## Steps to reproduce this issue
type select * from transaction and you get SELECT * FROM TRANSACTION

1. create a table named 'transaction'
2. refresh tree
3. open Query
4. type select from transaction...

You get SELECT * FROM TRANSACTION

## Current behavior

You get SELECT * FROM TRANSACTION

## Expected behavior

You should get SELECT * FROM transaction (since transaction is a table name)

## Possible solution

If it's a table name don't auto-uppercase it

## Environment

Win 10
HSQL 9.5.0.5349
10.2.19-MariaDB

**Comment by ansgarbecker** [comment]
Should be fixed, for tables in the current database.

The original issue by the way was #337
