### ISSUE TITLE
Missing translated words

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#415]
## Steps to reproduce this issue

Some missing translatade words to Portuguese (Brazil)

1. Step 1; do a filter in some table/form with new filter field
2. Step 2; see the message in right side
![image](https://user-images.githubusercontent.com/11230133/49217051-b4093d00-f3b3-11e8-9b97-b5ac9cae44b9.png)

One more
tools->Preferences
![image](https://user-images.githubusercontent.com/11230133/49217095-d4d19280-f3b3-11e8-8825-4a7881a7c358.png)

## Environment

* **HeidiSQL version:** 
  
9.5.0.53.56

**Comment by ansgarbecker** [comment]
Ok, these two strings are not yet in the translation file, so I'll add these first. For the actual translation, the translators have to do that, and the next nightly build gets them then.

**Comment by lukinhaspm** [comment]
OK, I create my profile in Transifex, in the next times I will be glad to help.
thanks @ansgarbecker

**Comment by lukinhaspm** [comment]
Sorry my dummy question, but I need to do something to change?
because its the same for me
thanks

**Comment by lukinhaspm** [comment]
Hahaha, great, thanks a lot @ansgarbecker!
