### ISSUE TITLE
Sorting options squashed together

### ISSUE THREAD

**Issue by TonyMarston** [HeidiSQL/HeidiSQL#416]
## Steps to reproduce this issue

In the "Data" tab when I want to change the sorting options this is made difficult because they are all squashed together, as you can see in the attached screen shot.

<img width="739" alt="heidisql" src="https://user-images.githubusercontent.com/14911160/49219175-6f3cd080-f3ca-11e8-8f91-dc1cf75ee3e1.png">

## Environment
I am running Windows 10 with a screen resolution of 1920 x 1080 with resolution set to 150%

* **HeidiSQL version:** 
9.5.0.5356
  

* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
Should be fixed now, in the next build.

**Comment by TonyMarston** [comment]
Unfortunately a new problems has arisen. I try to add columns to be sorted and they disappear from the list. All I see is a dimmed out area with a button labelled "Reset Sorting" which is unusable. I tried closing and reopening the software and the sorting dialog is still unusable.

<img width="741" alt="heidisql" src="https://user-images.githubusercontent.com/14911160/49338841-86283080-f61f-11e8-88a7-c25e063be9b0.png">

**Comment by ansgarbecker** [comment]
OK, just fixed that for the next build. Crossing fingers that all is fine now.
