### ISSUE TITLE
After automatic update, run heidisql.exe with normal privileges, not as admin

### ISSUE THREAD

**Issue by dejury** [HeidiSQL/HeidiSQL#418]
## Steps to reproduce this issue
Connect using plink.exe to a database. After that, check if there are updates for HeidiSQL. If there are available, install them. HeidiSQL closes and installs the update. Afterwards, HeidiSQL bootes up again. Then it is not possible to connect via SSH again...

Only after a reboot of HeidiSQL it is possible again.

## Current behavior

The SSH connection is not closed correctly, which makes it unavailable after reboot of the application.

## Expected behavior

It should be reset.

## Possible solution

To make it close or reset the connection on update

* **HeidiSQL version:** 
9.5.0.5357
* **Database system and version:** 
MariaDB 10.1.35
* **Operating system:** 
Windows 10, October Update 2018

**Comment by ansgarbecker** [comment]
> The SSH connection is not closed correctly, which makes it unavailable after reboot of the application.

If the plink.exe process is still running, HeidiSQL just creates another process using the next higher port for connecting.

Maybe there are other reasons why Heidi does not connect. What error message do you get in such cases? Is there something in the log?

**Comment by dejury** [comment]
It looks like the plink.exe process is closed during the update. I looked that up into the processlist.
But it seems that somehow, after update, the first time it boots. It doesn't fire the plink.exe process, which gives an error. See attached.

When I close HeidiSQL again, and then start again. It works without a problem.

![after-update-error](https://user-images.githubusercontent.com/16034333/49362852-470de400-f6e0-11e8-9b9b-bae0d3952e69.png)

**Comment by dejury** [comment]
I looked the #10061 error up on the internet. It is that the target computer actively refused the connection.

Good to know, which maybe has something to do with the bug. The SSH server is running on an other port then 22.

**Comment by ansgarbecker** [comment]
You should have a look at the log panel - is there something when that error occurs?
Does a new attempt to connect work? Or do you need to restart HeidiSQL to get it working?

**Comment by dejury** [comment]
> You should have a look at the log panel - is there something when that error occurs?

In the Windows logs there is nothing. I enabled HeidiSQL logging into file with debugging on, but there are no new nightly builds, so I cannot try yet. Will do that after an update is available ;)

> Does a new attempt to connect work? Or do you need to restart HeidiSQL to get it working?

A new attempt does not work, you need to restart HeidiSQL to get it to work again.

**Comment by ansgarbecker** [comment]
If after a nightly build update something does not work, that may have to do with the new heidisql.exe process being started with administrator privileges. That is due to the external updater, which gets started elevated, and the updater then starts heidisql.exe with the same privileges. That is probably fixable if the updater is able to run heidisql with normal privileges again.

For testing purposes, you could download an older build from heidisql.com, then start an update to the current build.

I am myself also experiencing an issue with connecting after an update, but in a different way than you did: on the first run with admin privs, I see a blank list of sessions, where there are ~20 sessions when I run it with normal privs.

**Comment by dejury** [comment]
> If after a nightly build update something does not work, that may have to do with the new heidisql.exe process being started with administrator privileges. That is due to the external updater, which gets started elevated, and the updater then starts heidisql.exe with the same privileges. That is probably fixable if the updater is able to run heidisql with normal privileges again.
> 
> For testing purposes, you could download an older build from heidisql.com, then start an update to the current build.
> 
> I am myself also experiencing an issue with connecting after an update, but in a different way than you did: on the first run with admin privs, I see a blank list of sessions, where there are ~20 sessions when I run it with normal privs.
> 
> [Here](https://stackoverflow.com/a/41770447/4110077)'s a probably helpful post.

Will give this a try tomorrow. I don't think it is only a problem for nightly builds, I think it is also for the "normal" updates. 

Will update you with a status tomorrow.

**Comment by dejury** [comment]
I did an update and attached the logs below.

000001.log is the session which started the update
000002.log is the session which started right after the update, and can't connect via SSH
000003.log is the session after a restart of HeidiSQL, which succesfully connects

I replaced senstive data with
`<username@server>` & `<portnumber>`

[000001.log](https://github.com/HeidiSQL/HeidiSQL/files/2647889/000001.log)
[000002.log](https://github.com/HeidiSQL/HeidiSQL/files/2647890/000002.log)
[000003.log](https://github.com/HeidiSQL/HeidiSQL/files/2647891/000003.log)

**Comment by ansgarbecker** [comment]
Activating that logging to file with debug messages was a really good idea. Reveals a lot of useful details. Of course that could be a bit less verbose when logging usernames, hostnames and such things.

The logs say you have set a timeout of 0 seconds for plink.exe, on the session manager's "Advanced" tab. Could you please raise this to the default value of 4 seconds and try again?

**Comment by ansgarbecker** [comment]
You probably noticed the new "Toegang geweigerd" (access denied) message in your log file? I'm wondering from which command that's caused.

**Comment by dejury** [comment]
Yeah noticed it. I'm not sure what it could be... It is really strange.

**Comment by dejury** [comment]
I think I've found what causes the problem. 

I connect to SSH via a private key. That private key is stored on a network share. This might be the issue. I tested running the updates with the private key on my local desktop, then I can connect after an update.

Maybe the network share can somehow not be accessed after update?

**Comment by ansgarbecker** [comment]
Ah that makes sense. That network share is probably not accessible with elevated (admin) privileges, which are used the first time after the update. I think I'll rename this issue so it's more clear.

**Comment by dejury** [comment]
Yeah, better. Thanks for the help until now :)

**Comment by ilpssun** [comment]
I, too, think this is worth fixing.  In my work environment, we have the Windows UAC muted so I don’t really get informed that Heidi is running with elevated privileges.  It is only apparent when drag-and-drop and password completion don’t work because the operating system restricts my programs running with normal privileges from interacting with the Heidi process running with elevated privileges.  That’s a bit annoying – also, it’s good practice to launch without elevated privileges after install to prevent security issues.

**Comment by ViliusS** [comment]
This is also the culprit for portable versions, for example in enterprise environments where administrator rights are not available. Steps to reproduce:
1. Download the portable version of HeidiSQL, unzip on the Desktop.
2. Run Heidi and try to update through About dialog.
3. UAC will pop-up blocking the update.

I think HeidiSQL should detect if it is running from portable directory and update without administrator rights in that case.

**Comment by ansgarbecker** [comment]
Fixed from the next build on.
The session manager should show sessions from the normal user after the build update, not those from the admin.
