### ISSUE TITLE
No tables list in left menu on MariaDB 10.3.x

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#419]
## Steps to reproduce this issue

1. Connect to mariadb 0.3
2. Expand a database in the tree menu
3. Then I get no tables

## Current behavior

![image](https://user-images.githubusercontent.com/3911428/49331755-49513080-f570-11e8-803a-f79aa8e55028.png)

## Expected behavior

See tables, views, etc

## Environment

* **HeidiSQL version:** 
  
nightly
* **Database system and version:** 
  
MariaDB 10.3, latest
* **Operating system:** 
  
Windows 10 x64

**Comment by ansgarbecker** [comment]
Are you sure you have no filter in the top "Table filter" box?

**Comment by sirber** [comment]
I might have the favorite tables on... lol let me check :)

**Comment by sirber** [comment]
yeah, was the 'favorite table' option lol. sorry.
