### ISSUE TITLE
Incorrect trigger statement's field size

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#420]
## Steps to reproduce this issue

1. Create table and trigger in your database (trigger's body could be empty):
```
DROP TABLE IF EXISTS `tbl`;
CREATE TABLE `tbl` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`val` VARCHAR(15) NOT NULL,
	PRIMARY KEY (`id`)
);

DROP TRIGGER IF EXISTS `trg`;
CREATE TRIGGER `trg` BEFORE INSERT ON `tbl` FOR EACH ROW BEGIN
END;
```
2. Press F5 to refresh database;

3. Click at table 'tbl' in the tree, then select 'Table' tab and press F5;
4. Click at the database in the tree and press F5 again;
5. Click at trigger 'trg' and you'll see trigger page. However field for the trigger statement will be small:
![heidi_smalltriggerstatementtextarea](https://user-images.githubusercontent.com/7234987/49350535-125b5600-f6fb-11e8-9b8a-86bf938e55b1.png)

6. Click at table 'tbl' & then on trigger 'trg'. Now you'll see the trigger page with normal field size for trigger statement.

To see the issue again -- repeat steps 3 to 5.

## Current behavior
Textarea for trigger statement is too small.

## Expected behavior
I'm expecting to see proper size of textarea for trigger statement.

## Environment

* **HeidiSQL version:** 9.5.0.5362 64bit
* **Operating system:** Windows 10 64 bit 1803

**Comment by ansgarbecker** [comment]
Using the latest build 5382 on Windows 7 with 125% scaling, I cannot reproduce this issue. Can you?

**Comment by ansgarbecker** [comment]
I was just able to reproduce this. Another reproduction recipe:
* click any table so the "table" tab shows the table editor
* click away from the "table" tab, e.g. to the "database" tab (or "query"...)
* click any trigger in the tree to show up the trigger editor

Logically, at least one problem is that the "table" tab was used before but is not the active tab while initializing the trigger editor.

**Comment by ansgarbecker** [comment]
The exact problem was/is, that the trigger editor frame is placed on a non-active tab of the underlying page control. If I activate the tab first, then place the editor there, the problem was fixed. However, that introduced other problems, so the solution is now to align the trigger editor with `alClient`, activate `AlignWithMargins`, plus some programmatical code to move the bottom buttons to their correct place.
