### ISSUE TITLE
Cannot delete DB that starts with a space

### ISSUE THREAD

**Issue by ChielTimmermans** [HeidiSQL/HeidiSQL#427]
## Steps to reproduce this issue

1. Add a database starting the name with a space example: " helloworld"
2. Try to delete the DB " helloworld" by right clicking on the db and click on drop
3. Press OK
4. Then I get the error SQL Error (1008): Can't drop database 'helloworld';

## Possible solution

I think that something is deleting the first space.
Because the space is removed in the error where it says: 
Can't drop database 'helloworld'

## Environment

* **HeidiSQL version:** 
9.4.0.5125
* **Database system and version:** 
Server version: 5.7.19 MySQL Community Server (GPL)

![knipsel](https://user-images.githubusercontent.com/22589095/49466593-c4c91100-f800-11e8-954f-f6607738041c.PNG)

**Comment by ansgarbecker** [comment]
Should be fixed in the latest build
