### ISSUE TITLE
[feature request] Show BLOB size in "image preview" view

### ISSUE THREAD

**Issue by paulvi** [HeidiSQL/HeidiSQL#429]
Please show BLOB size in "image preview" view, even if it is not an (known, supported) image.

That is instead of just "No image detected",  

Show "MEDIUMBLOB, 41,767 bytes, No image detected."

**Comment by ansgarbecker** [comment]
Blob size is now displayed in the preview panel, along with that "No image detected" label.

But I guess that does not help in analyzing very much here, as this size is most likely correct, while the size in the grid is not by guarantee correct. But that's the topic of #428
