### ISSUE TITLE
Error on disconecting from database with unsaved invalid data

### ISSUE THREAD

**Issue by Alexsey** [HeidiSQL/HeidiSQL#43]
## Expected behavior

No error should occur

## Current behavior

Error is rising

## Failure information (for bugs)

I was having some unsaved raw in a table that was unable to be saved due to some error (I don't remember what it was). Than I have tried to switch to a different db connection and open some table and the error occurred

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.4.0.5192 (64 Bit)
* Database system + version: MSSQL
* Operating system: Windows 10 Pro v1709 build 16299.64

### Failure Logs

In attachments
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1556640/bugreport.txt)

**Comment by rentalhost** [comment]
Steps:
* Open data grid;
* Set some PK column to an invalid value like `!`;
* Click on disconnect button;

Now, everything you do you will see an error happening (_very annoying, btw_). The workaround is open the data grid again, then the error is gone.

I think that the solution is unload the data grid when you disconnect.
