### ISSUE TITLE
problems with app window after an error/exception popup window

### ISSUE THREAD

**Issue by weinerk** [HeidiSQL/HeidiSQL#431]
## Steps to reproduce this issue

trying to edit a cell in a result set 
which results in an error/exception popup window
 
## Current behavior

when an error pops up 
if i click "continue app"
then the error message window disappears
but the main window becomes inaccessible

when you click on it - it disapears and the click goes to the window behind it

## Expected behavior

dont have that issue with old ver 9.4 or 9.5 

## Possible solution

a workaround - 
ALT + space - to get a window menu - and if maximized - restore, if restored - maximize
then window starts to act normally

## Environment

windows 

* **HeidiSQL version:** 
recent nightly build (ver 9 5 0 5362 64 bit on windows)

* **Database system and version:** 
pg
* **Operating system:** 
windows 10

**Comment by ansgarbecker** [comment]
Please update to the latest build. I guess this is the same crash as in #426 which I already fixed.

Getting unexpected behaviour after clicking "Continue" in the crash reporter is quite normal.
