### ISSUE TITLE
Possible data loss in source database while exporting FEDERATED table data

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#433]
## Steps to reproduce this issue

1. Create databases, user & tables using the following code:
```
DROP USER IF EXISTS '_user'@'%';
CREATE USER '_user'@'%' IDENTIFIED BY '_password';
GRANT USAGE, SELECT, INSERT, UPDATE, DELETE ON *.* TO '_user'@'%';
FLUSH PRIVILEGES;


DROP DATABASE IF EXISTS `_data`;
CREATE DATABASE `_data`;

USE `_data`;
CREATE TABLE `a` (`id` INT UNSIGNED NOT NULL);
INSERT INTO `a` (`id`) VALUES (1), (2), (3), (4), (5);


DROP DATABASE IF EXISTS `_source`;
CREATE DATABASE `_source`;
USE `_source`;
CREATE TABLE `a` (`id` INT UNSIGNED NOT NULL) ENGINE=FEDERATED CONNECTION='mysql://_user:_password@127.0.0.1/_data/a';

CREATE TABLE `b` (`id` INT UNSIGNED NOT NULL);
INSERT INTO `b` (`id`) VALUES (6), (7), (8), (9), (10);


DROP DATABASE IF EXISTS `_target`;
CREATE DATABASE `_target`;

```

2. Check content of tables `_data`.`a`, `_source`.`a`, `_source`.`b`;
2. Right click over database "_source" | "Export database as SQL"
3. Specify the following options: Tables: "Create", Data: "Delete + insert", Output:  "Database", Database: "_target";
3. Export;
4. Check content of tables `_data`.`a`, `_source`.`a`, `_source`.`b`, `_target`.`a`, `_target`.`b` => data in table `_data`.`a` is lost;

## Current behavior

Federated table `_target`.`a` created correctly.
However, then DELETE FROM `_target`.`b` is issued and this deletes all data in `_data`.`a`.

## Expected behavior

HeidiSQL **must not** touch data while exporting federated tables (mysqldump did not try do dump data). 
Federated table is just a "link" so creating federated table in target database will automatically make data in that table available.

## Environment

* **HeidiSQL version:** 9.5.0.5372 64 bit
* **Database system and version:** MySQL, MariaDB (with federated tables supported and enabled)

**Comment by fifonik** [comment]
Is it possible to get it fixed as:
- I believe it is critical as data loss possible during operation that should be safe
- The fix is straightforward, something like this:
tabletools.pas
```
        Output('-- '+_('Data exporting was unselected.')+CRLF, False, True, True, False, False);
+   end else if DBObj.Engine = 'FEDERATED' then begin
+       // Do not copy data for federated tables as per mysqldump & simple logic
    end else if DBObj.Engine = 'MRG_MYISAM' then begin
```

Thanks.

**Comment by ansgarbecker** [comment]
Thanks for your code suggestion.

Should be fixed in the next build.

Also, `MRG_MyISAM` tables were affected, caused by a case sensitive comparison with "MRG_MYISAM" (capitalized "Y").

**Comment by fifonik** [comment]
Thanks!
I have not checked the code and though that the engine's name is normalized (==uppercased).

**Comment by fifonik** [comment]
Downloaded. Checked -- no data dumped. 
Many thanks.

The only tiny suggestion -- add newline after the "-- Table data not exported because this is ..." comment to separate it visually from the following command.

**Comment by ansgarbecker** [comment]
Just added that line break to both "skip-comments".

Thanks for your quick feedback!
