### ISSUE TITLE
Cosmetic: Session Manager button layout out of alignment on classic themes

### ISSUE THREAD

**Issue by sombraguerrero** [HeidiSQL/HeidiSQL#435]
## Steps to reproduce this issue

Pre-condition: Windows is set to a non-Aero, classic theme.

## Current behavior

The session manager buttons are either overlayed or underlayed with the tabs and panels above them.

## Expected behavior

The buttons should be clear of other UI elements within the session manager.

## Environment

* **HeidiSQL version:** 
  9.5.0.5382 (and several revisions prior)

* **Operating system:** 
  Windows 7 32-bit or 64-bit and above with either Aero disabled or non-Aero classic themes being used.
![non_aero_buttons](https://user-images.githubusercontent.com/24618934/49739539-fb5ebb80-fc46-11e8-99c2-62f769bb6d7c.png)

**Comment by ansgarbecker** [comment]
The user manager has the same problem:

![grafik](https://user-images.githubusercontent.com/7986591/50040720-5e868e80-0049-11e9-9062-3a7e54ed4999.png)

While all other dialogs don't seem to have it: the SQL export dialog, CSV import, SQL help, settings, program update, grid export.

**Comment by ansgarbecker** [comment]
This issue occurred after I upgraded the compiler from XE5 to Delphi 10.2. Also, it depends on Aero being disabled. The buttons are at the right place if Aero is enabled, but not so when disabled.

**Comment by ansgarbecker** [comment]
Think I got it now - took me some hours.

Apparently, bad values of the minimum width and height moved those buttons in the bottom right corner of a dialog. To be more precise, `MyForm.Constraints.MinHeight` had the same value as `MyForm.Height` (same for width). Now, I _decreased_ those `Min*` values by about 50 pixels, which made the buttons suddenly stay where they should be, also with disabled Aero.
