### ISSUE TITLE
Run time error 216

### ISSUE THREAD

**Issue by lbraz** [HeidiSQL/HeidiSQL#436]
## Steps to reproduce this issue

Executing sql (insert ignore into) script.

## Current behavior

An error occurred in the application.
Runtime error 216
(bug file attached)

## Expected behavior

Finish the script executing with no errors and no restart application.
:-)

## Environment

HeidiSQL version: 9.5.0.5382 (64 bit)

* **Database system and version: 
MySQL Server 5.5
Version: 5.5.41-0+wheezy1
Compiled for: debian-linux-gnu (i686)

* **Operating system:** 
Windows 10

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2664455/bugreport.txt)
[bugreport2.txt](https://github.com/HeidiSQL/HeidiSQL/files/2664456/bugreport2.txt)
[bugreport3.txt](https://github.com/HeidiSQL/HeidiSQL/files/2664457/bugreport3.txt)
[bugreport4.txt](https://github.com/HeidiSQL/HeidiSQL/files/2664458/bugreport4.txt)

**Comment by ansgarbecker** [comment]
The attached reports show different HeidiSQL versions and different situations / clicks.

Please update to the latest nightly build, describe your clicks more precisely and attach one bug report textfile.
