### ISSUE TITLE
HeidiSQL website source missing

### ISSUE THREAD

**Issue by le717** [HeidiSQL/HeidiSQL#438]
## Current behavior

1. Go to GitHub
2. Can't find website source

## Expected behavior

1. Go to GitHub
2. Find website source
3. Contribute 

## Possible solution

1. Post website source on GitHub

## Additional info

Hello! I have been using HeidiSQL on and off since 2015 and a lot lately from personal projects. I am unable to donate any money to what I consider to be an excellent project or I would. So, to show some of my appreciation for this project, I wanted to help refine the website design just a bit, but the source code does not seem to be visible. So I'm filing this "issue" to ask if you would consider releasing the site source on GitHub so people could help improve it. My GitHub/website houses almost all of my work if you'd like to see what I've done.

Have a good day!

**Comment by ansgarbecker** [comment]
Hm, I'm sorry, but the website is not on Github because I don't want to publish it. I also want to keep the effort very small with it.

**Comment by le717** [comment]
I totally understand. Just thought I'd ask. :)
