### ISSUE TITLE
Bug resizing height of query editor

### ISSUE THREAD

**Issue by chrysler5798** [HeidiSQL/HeidiSQL#439]
Hello !

## Steps to reproduce this issue
1. Go to query tab
2. Open a new query tab
3. Try to resize the height of the query editor
4. You can't on the new tab but you can on the default tab
![2018-12-12_11-22-38](https://user-images.githubusercontent.com/7657777/49863514-bda59280-fe00-11e8-88b9-528384eb2ba3.gif)

## Current behavior
You can't resize the height of the query editor on a new tab.

## Expected behavior
You can resize the height of the query editor on a new tab.

## Environment

* **HeidiSQL version:** 9.5.0.5391
* **Operating system:** v10.0

**Comment by ansgarbecker** [comment]
Confirmed... The splitter for dragging with the mouse should be below the editor, but it is on top of it. Watch out for the slightly increased border above the editor.

**Comment by Arekusei** [comment]
this is a critical bug. Editor is broken in current build =\
`11 hours ago`
`4 hours ago`

**Comment by fifonik** [comment]
Is it something new? I do not have the issue on build 5385

**Comment by doroshenkoiy** [comment]
I have this bug in b5405 and no issue in b5382.

**Comment by tympapost** [comment]
I also have this bug in b5405, no issue before this build...
