### ISSUE TITLE
unexpected Error with CASE function

### ISSUE THREAD

**Issue by margaretandpellman** [HeidiSQL/HeidiSQL#442]
unexpected Error with CASE function

The above error is thrown when the YEAR(datecolumn) function is contained within a CASE function. It forces the user to add the YEAR(datecolumn) to the GROUP BY clause  thereby separating year over year data into separate rows per year instead of just filling the columns.

## Steps to reproduce this issue

1. Step 1-set up table with a date column and some other information that can be counted.
something like

Fruit | Date Picked

Apple | 9/30/2018
Apple | 10/1/2018
Apple | 10/2/2018
Apple | 9/4/2017
Apple | 9/5/2017
Orange | 9/30/2018
Orange | 10/1/2018
Orange | 10/2/2018
Orange | 9/4/2017
Orange | 9/5/2017
Orange | 9/30/2018
Orange | 10/1/2018
Pineapple | 10/2/2018
Pineapple | 9/4/2017
Pineapple | 9/5/2017
Pineapple | 9/30/2018
Pineapple | 10/1/2018
Pineapple | 10/2/2018
Pineapple | 9/4/2017
Pineapple | 9/5/2017
Pineapple | 9/30/2018
Pineapple | 10/1/2018
Pineapple | 10/2/2018
Pineapple | 9/4/2017
Pineapple | 9/5/2017
Cherry | 9/30/2018
Cherry | 10/1/2018
Cherry | 10/2/2018
Gooseberry | 9/4/2017
Gooseberry | 9/5/2017
Gooseberry | 9/30/2018
Gooseberry | 10/1/2018
Gooseberry | 10/2/2018
Peach | 9/4/2017
Peach | 9/5/2017
Peach | 9/30/2018

2. Step 2- run the following Query.
SELECT Fruit, 
CASE WHEN YEAR(Date_Picked)=2017 THEN count(Fruit) ELSE 0 END AS 'Count_2017', 
CASE WHEN YEAR (Date_Picked)=2018 THEN Count(Fruit) ELSE 0 END AS 'Count_2018'
FROM fruit_picking_datatable 
WHERE  YEAR (Date_Picked) IN (2017,2018)
GROUP BY Fruit
ORDER BY Fruit desc;

3. Then I get... See Error Below.

## Current behavior

SQL ERROR 8120: Column 'fruit_picking_table.Date_Picked' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.

The above error is thrown when the YEAR(Date_Picked) function is contained within a CASE function. Upon placing the Year(Date_Picked) in the GROUP BY clause, you end up with 2 rows per named Fruit, one containing the data for 2017 (and 0 for 2018), the other containing the data for 2018(and 0 for 2017).

## Expected behavior

you should be able to run the query without error. It should produce 3 columns of data , one with the Fruit, the second with the data for 2017 and the third with the data for 2018. There should be 1 row of data for each named Fruit.

## Possible solution

Add an exception to rules pertaining to the select list that excludes items contained within the CASE function.

## Environment

* **HeidiSQL version:** 
  9.5.0.5397 (64 bit)

* **Operating system:** 
Windows V 10.0

**Comment by ansgarbecker** [comment]
Ok, I just gave it a try. Here's the table I created:

![grafik](https://user-images.githubusercontent.com/7986591/50012422-e1163c00-ffbe-11e8-948c-1660a50d252f.png)

And here's the results of your SELECT query:

![grafik](https://user-images.githubusercontent.com/7986591/50012443-f3907580-ffbe-11e8-9c4e-2ec37f1f32b8.png)

I highly guess the error you got is returned because the server version does not allow such grouping, while my local MariaDB 10.0.34 does it without error.

You may want to work around that error using such a query instead:

```sql
SELECT Fruit, YEAR(Date_Picked) yr, COUNT(*)
FROM fruit_picking_datatable
WHERE YEAR (Date_Picked) IN (2017,2018)
GROUP BY Fruit, yr
ORDER BY Fruit desc;
```

**Comment by ansgarbecker** [comment]
Not a bug in HeidiSQL obviously.
