### ISSUE TITLE
Crash when close heidisql

### ISSUE THREAD

**Issue by eliateguh** [HeidiSQL/HeidiSQL#443]
## Steps to reproduce this issue

1. When I close the heidisql
2. Then I get crash and the bug report textfile is

date/time          : 2018-12-15, 16:24:58, 830ms
computer name      : TEGUH-PC
user name          : Teguh <admin>
registered owner   : Teguh
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : Indonesian
system up time     : 13 hours 22 minutes
program up time    : 5 seconds
processors         : 4x AMD A6-7310 APU with AMD Radeon R4 Graphics
physical memory    : 6855/11171 MB (free/total)
free disk space    : (C:) 21,60 GB
display mode       : 1366x768, 32 bit
process id         : $1fd4
allocated memory   : 63,02 MB
largest free block : 8185,62 GB
executable         : heidisql.exe
exec. date/time    : 2018-12-15 05:59
version            : 9.5.0.5400
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $822e4ce3, $dcd97735, $dcd97735
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 000007FEF6208E19 in module 'atidxx64.dll'. Read of address FFFFFFFFFFFFFFFF.

main thread ($2314):
7fef6208 atidxx64.dll
004186cb heidisql.exe System              @IntfClear
008deeb0 heidisql.exe SynEdit   14089  +0 Finalization
00410b62 heidisql.exe System              FinalizeUnits
004fbbed heidisql.exe madExcept           InterceptFinalizeUnits
004fbc64 heidisql.exe madExcept           InterceptHalt0FinalizeUnits
00411368 heidisql.exe System              @Halt0
00de723e heidisql.exe heidisql     87 +28 initialization
772b59cb kernel32.dll                     BaseThreadInitThunk
7741385b ntdll.dll                        RtlUserThreadStart

## Current behavior

Crash Window when I close the heidisql

## Expected behavior

I need normally close heidisql without crash

## Possible solution

I don't know

## Environment

Win 7 64 bit

* **HeidiSQL version:** 
  9.5.0.5400
* **Database system and version:** 
  10.1.16-MariaDB
* **Operating system:** 
  Win 7 64 bit

**Comment by ansgarbecker** [comment]
Your crash report is located in some of your ATI graphics card driver. I suppose this is related to #445 which reports a Direct2D related crash.

**Comment by ansgarbecker** [comment]
I have to guess this is fixed.

Would be good to get feedback from you, @eliateguh
