### ISSUE TITLE
Keyboard shortcut for Quick Filter menu

### ISSUE THREAD

**Issue by tomasberdych** [HeidiSQL/HeidiSQL#444]
Hello. I use very often Quick filter menu. Exist any keyboard shortcut for show this menu? It would be very useful to be able to set the shortcut to the every item in this menu. Thank you.

**Comment by ansgarbecker** [comment]
Next time please follow the guide in the issue template, which you have just deleted.

It would be helpful if you make suggestions for these keyboard shortcuts, while watching out if there are other actions having the same one.

**Comment by tomasberdych** [comment]
Sorry. I have not shortcuts suggestions, I am Heidi beginner and I do not know all the shortcuts. I will leave it to you. Thank you very much.

**Comment by ansgarbecker** [comment]
All of these quick filter actions can now get a shortcut, in Tools > Preferences > Shortcuts > Data:

![grafik](https://user-images.githubusercontent.com/7986591/79890208-73beba80-83ff-11ea-9530-f4b8a3062fb0.png)

Only the first two, most important ones, have a default shortcut:
![grafik](https://user-images.githubusercontent.com/7986591/79890282-8fc25c00-83ff-11ea-9bf0-d38919412e49.png)
