### ISSUE TITLE
Builds after 5382 crash on startup, due to unsupported D2DFactory

### ISSUE THREAD

**Issue by lourdas** [HeidiSQL/HeidiSQL#445]
## Steps to reproduce this issue

1. Download the 64-bit build 5382.
2. Run it under Wine in Linux.
3. It crashes on startup.
4. Builds up to 5380 start fine.

## Current behavior
It crashes on startup. Attached screenshot:
![screenshot_20181216_194922](https://user-images.githubusercontent.com/397916/50056898-be755600-016b-11e9-9b4c-ab9e9e1b1e0b.png)
## Expected behavior

It should start normally.

## Possible solution

None.

## Environment

64-bit Linux, kernel 4.19.9, KDE, Wine is 3.21.

* **HeidiSQL version:** 
5382

**Comment by lourdas** [comment]
I'm attaching the bug report. Tried from the build 5382.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2683899/bugreport.txt)

**Comment by ansgarbecker** [comment]
Related: https://github.com/SynEdit/SynEdit/issues/91

Crash is the same as under Windows XP and Windows Server 2003.

Workaround for Wine could be to emulate Windows 7, not XP? No clue if Wine can do that.

**Comment by lourdas** [comment]
> Workaround for Wine could be to emulate Windows 7, not XP? No clue if Wine can do that.
My Wine configuration is supposed to emulate Windows 8:
![screenshot_20181217_164656](https://user-images.githubusercontent.com/397916/50094284-87f71400-021b-11e9-95b6-435a789eb13d.png)

**Comment by ansgarbecker** [comment]
Probably closed a bit in hope this is fixed now. I just found a switch for disabling the use of DirectWrite in SynEdit, and pushed that change. So please check if Heidi runs again on Wine.

**Comment by lourdas** [comment]
Just upgraded to build 5418 and it works! No crash! Thank you Ansgar!

**Comment by lourdas** [comment]
I also noticed some graphical glitches fixed. Check the following screenshots:
Build 5380:
![build5380](https://user-images.githubusercontent.com/397916/50385375-554a9100-06dd-11e9-8441-d84140289d75.png)
Build 5418:
![build5418](https://user-images.githubusercontent.com/397916/50385380-61cee980-06dd-11e9-8f5c-e13051b674d7.png)
