### ISSUE TITLE
Errors to create postgresql function with $$ as body delimiter

### ISSUE THREAD

**Issue by cirix81** [HeidiSQL/HeidiSQL#447]
## Steps to reproduce this issue

When you create a plpgsql function in postgresql, heidisql always complain about $$ as body terminal.
It's terminal it's very helpful when you write function in plpgsql. 

Simple function to try:

`create or replace function test() returns int as 
$$
BEGIN
	return 1;
END;
$$
language plpgsql;`

## Current behavior
Give an error when tou try to launchrun the SQL to create the function

## Expected behavior
Create the function without errors

## Possible solution
It's seems heidisql only send to the server until the ; inside the $$ body but it need to send until the last ";". All between the two $$ it's to be considerate string.
We can use also a identifier inside the $$, like $BODY$

## Environment

* **HeidiSQL version:** 
  
Version 9.5.0.5196
* **Database system and version:** 
  
postgresql 10.5
* **Operating system:** 
Windows 7

**Comment by cirix81** [comment]
This a pretty bad bug for postgresql dba

**Comment by ansgarbecker** [comment]
HeidiSQL currently supports custom delimiters, which is just by default a semicolon. You can either press the button with the red ; on it to change it, or place such a client command above your SQL code:
```sql
DELIMITER //
CREATE ...
DELIMITER ;
```

Using that $$ notation seems like a feature of pgAdmin to me, or?

**Comment by cirix81** [comment]
No, it's not a feature of pgadmin, it's server side. 
The delimiter option is working, thanks for your response .

**Comment by ansgarbecker** [comment]
Thanks for feedback
