### ISSUE TITLE
High resolution icons

### ISSUE THREAD

**Issue by ansgarbecker** [HeidiSQL/HeidiSQL#448]
## Current behavior

Running HeidiSQL on high DPI scaled resolutions makes the icons look blurry.

## Expected behavior

Icons shouls look sharp and clear.

## Possible solution

* use a `TImageCollection` plus a connected `TVirtualImageList`
* remove the old `TImageList` with all the [Silk icons](http://www.famfamfam.com/lab/icons/silk/)
* replace them with bigger ones, e.g. from [Icons8](https://icons8.com/), which are [nice for OpenSource projects](https://icons8.com/articles/weve-contributed-an-icon-to-imageoptim/)

## Environment

* **HeidiSQL version:** 
  9.5.0.5408

**Comment by webdbase** [comment]
Please make the text "Icon pack:" from the preferences translatable.

**Comment by ansgarbecker** [comment]
> Please make the text "Icon pack:" from the preferences translatable.

done ! :)

**Comment by ansgarbecker** [comment]
Everything's done here so far.
