### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by webdbase** [HeidiSQL/HeidiSQL#449]
I've finished Bulgarian localisation. The following is a list of hardcoded strings I've found. There may be others, but I won't know that until next nightly build:

GUI font: *
Style Theme: *
Application language: * - there is a translatable string "Application language (requires restart):", which doesn't show up in the app
Size: - there is a translatable string but doesn't show up in the app
SSH tunnel: - there is a translatable string but doesn't show up in the app
Colors preset

**Comment by webdbase** [comment]
After downlowding the latest nightly build 5409 I found these:
The error window pops up when trying to select "Explain analyzer for current query" on an empty query tab. Is it possible the strings in this window to be translateble too?
![error-explain analyzer for current query](https://user-images.githubusercontent.com/11588031/50206092-ff8b8700-0372-11e9-9347-6c06cf895d3f.png)
![info](https://user-images.githubusercontent.com/11588031/50206094-00241d80-0373-11e9-8718-aad0a0c29163.png)
![about](https://user-images.githubusercontent.com/11588031/50206095-00241d80-0373-11e9-8e32-6b0dade1f661.png)
![pref](https://user-images.githubusercontent.com/11588031/50206096-00241d80-0373-11e9-93de-73439c7daf9c.png)
![snip-dir](https://user-images.githubusercontent.com/11588031/50206097-00bcb400-0373-11e9-8df5-47d4bdba2f09.png)

The following pops up when doing a right click and selecting "Quick Filter" outside of the columns in the data grid
![filter](https://user-images.githubusercontent.com/11588031/50206098-00bcb400-0373-11e9-8313-f5dbc4f28e59.png)
![insert-func](https://user-images.githubusercontent.com/11588031/50206099-00bcb400-0373-11e9-9eed-fc363656c261.png)

**Comment by webdbase** [comment]
and one more
Duration for ...
![of](https://user-images.githubusercontent.com/11588031/50220597-70469980-039b-11e9-8103-cd4603574549.png)

**Comment by webdbase** [comment]
and one more
![stat](https://user-images.githubusercontent.com/11588031/50272376-409d9d00-0440-11e9-817e-668b1a61cbad.png)

**Comment by ansgarbecker** [comment]
I just added nearly all of the above to the translation file.

Just some notes:
* "SSH tunnel" should already be there, probably same as in English
* "The specified path was not found" is a Windows system message, not part of the HeidiSQL source
* SQL function categories like "Bit functions" are retrieved from the server, and should be translated there if at all
* the two first quick filter items are empty due to a bug you detected :) not a translation issue, however

**Comment by webdbase** [comment]
Some more:
Undo|Undo (Alt+BkSp)
