### ISSUE TITLE
Regular Expression on Table List Filter

### ISSUE THREAD

**Issue by jan-obtam** [HeidiSQL/HeidiSQL#45]
## Expected behavior

Using regular expressions on database table list view (Check screenshot)

## Current behavior

Feature does not exists yet.

## Failure information (for bugs)

Trying to run a regular expression filter on the database filter doesn't work. Trying to filter a certain pattern for the table names (table without numbers) but it doesn't work.

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. Run HeidiSQL
2. Select any database
3. Once loaded, go to the Database tab 
4. Assuming table filter is enabled, add any regular expression to the filter textbox.
5. Regular expression should not run.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version:
* Database system + version:
* Operating system:

### Failure Logs

Screenshot:

<img src='https://i.imgur.com/iQ3tkFH.png'></img>

**Comment by ansgarbecker** [comment]
Nice addition. Just did that. Regular expressions work now in that filter box. Please update to the latest build and report back for any issue here.

Also changed: while processing a search on bigger data sets (in a data or query grid for example), the right X icon in that box now shows an hour glass instead, so the user knows that Heidi is just busy.

By the way: searching was and is case insensitive, as I think this is what the user normally expects, also that makes it easier to type a filter.
