### ISSUE TITLE
Column sorting scrolls horizontally

### ISSUE THREAD

**Issue by WesleyM77** [HeidiSQL/HeidiSQL#451]
## Steps to reproduce this issue

1. Step 1: Sort a column
4. Then I (sometimes) get unintended horizontal scrolling.

## Current behavior

This doesn't happen for every column, but when I find a column that does it, it's reproducible. On a column that presents the issue, when I sort the column, the view will scroll horizontally by a particular amount every time.  

## Expected behavior

I would expect horizontal scrolling to never occur when I sort a column. 

## Possible solution

To not scroll horizontally when a column is sorted. 

## Environment

* **HeidiSQL version:**  9.5.0.5332
  
* **Database system and version:** MySQL 5.7.21
  
* **Operating system:** Windows 10 1803 OS build 17134.441

**Comment by ansgarbecker** [comment]
You mean you want to have all columns at the same default width, and want to manually set their width? No, that's not doable, as that sounds uncomfortable.

**Comment by WesleyM77** [comment]
Yeah, I don't see a good way of getting rid of the weird behavior.

**Comment by WesleyM77** [comment]
Would it be possible to have a setting that, when opening a table, the columns width is set to not change until that table is reopened or a column is adjusted manually?

**Comment by ansgarbecker** [comment]
You mean Heidi shall remember manually changed column widths, but should not set them automatically according to their content?

Possible - of course. But that makes little sense to me.

Please describe the problem you have with automatic column widths.

**Comment by WesleyM77** [comment]
I've attached an example where it almost disappears off the screen. 
![2018-12-19_15-47-43](https://user-images.githubusercontent.com/22208037/50247294-7e99b300-03a5-11e9-8253-f16a8231af7c.gif)
So in this example, the columns to the left are all becoming wider and push the column I'm trying to look at off the screen. In a table with many columns, if they all suddenly become wider as a result of sorting, the column isn't in the same place as it was. Maybe the solution is not as I suggested above and would be to try to keep the column in the same location on screen based on it's left-side position.

**Comment by ansgarbecker** [comment]
Well in that case I suggest Heidi should just remember which column you clicked, then set the x-scroll offset so the clicked column is at the same position as before.

**Comment by WesleyM77** [comment]
That sounds like the best solution.

**Comment by ansgarbecker** [comment]
Next build should restore the just clicked column header so it stays at exactly the same position as before the refresh. Please update and report back if that works for you.

**Comment by WesleyM77** [comment]
Yes! Thank you so much! That works perfectly!
