### ISSUE TITLE
bug : missing the right remote IP address

### ISSUE THREAD

**Issue by TatwiraT** [HeidiSQL/HeidiSQL#454]
1. typing remote server ip
2. connect
3. cannot connect

![heid_bug](https://user-images.githubusercontent.com/3307638/50406532-746d1f80-07be-11e9-8326-f0f0568e8d24.png)

## Current behavior
miss selecting the right IP, when I try to connect to my remote server it connect to my public IP adress 

## Expected behavior
it must connect as usual to the given IP address not my machine public address

## Possible solution
fix the miss selection of the remote ip address

## Environment
win7

* **HeidiSQL version:** 

![heid_version](https://user-images.githubusercontent.com/3307638/50406530-67e8c700-07be-11e9-9b1d-54a56aa93c05.png)

**Comment by BadeelProject** [comment]
it's been fixed on today's nightly build ^^
thanks

**Comment by ansgarbecker** [comment]
No clue what went wrong here.

**Comment by BadeelProject** [comment]
no it is at the first screenshot, but it's been fixed later ^^
thank you

**Comment by ansgarbecker** [comment]
There was no fix for this issue in HeidiSQL. So I guess you fixed the user definition on the MySQL server.

**Comment by TatwiraT** [comment]
thanks ^^
