### ISSUE TITLE
Printing Table-Data, Table-Colums maybe also with multiselect tables

### ISSUE THREAD

**Issue by thE-iNviNciblE** [HeidiSQL/HeidiSQL#460]
Feature Request.

**Comment by ansgarbecker** [comment]
This is not a valid feature request.

Please follow the guide in the issue template, and probably describe the request with mockups.

**Comment by thE-iNviNciblE** [comment]
Sorry that i hadn't filled out  the issue template.

But Printing is missing for documentation purpose.

**Comment by ansgarbecker** [comment]
> But Printing is missing for documentation purpose.

Well, I don't doubt. But I'm afraid you have to file a full feature request for that, including a proper description and probably a mockup.
