### ISSUE TITLE
Renaming sessions causes crashes

### ISSUE THREAD

**Issue by Zbee** [HeidiSQL/HeidiSQL#464]
## Steps to reproduce this issue

| Always | Sometimes |
| :--- | :--- |
| 1. Have more than 1 session in the session manager<br>2. Rename a session (right click, or <kbd>f2</kbd>)<br>3. Press <kbd>enter</kbd><br>4. Rename the same session again<br>5. Crash | 1. Have more than 1 session in the session manager<br>2. Rename a session (right click -> rename, or <kbd>f2</kbd><br>3. Click outside of the text box to save the new name<br>4. Open a different session, or rename the same/other session<br>5. Probable crash |

## Current behavior

Renaming works, but frequently causes crashes on <kbd>enter</kbd> saving, and sometimes just on opening a session after renaming another

## Expected behavior

Sessions can be renamed, and opened, without Heidi crashing

## Possible solution

The identifier of a session (in memory, windows "dom", whatever) maybe isn't being updated after the session's name is changed - that would definitely be the reason in a web app at least, maybe start there

## Environment

Logs:
[heidi_bug_report_always.txt](https://github.com/HeidiSQL/HeidiSQL/files/2724593/heidi_bug_report.txt)
[heidi_bug_report_sometimes.txt](https://github.com/HeidiSQL/HeidiSQL/files/2724594/heidi_bug_report_longer.txt)

* **HeidiSQL version:** 
   9.5.0.5249
* **Database system and version:** 
  MySQL 5.6 (x2 servers) and MSSQL 2000 (x2 servers)
* **Operating system:** 
   Windows 10 Pro 1809

**Comment by ansgarbecker** [comment]
Thanks for your good report.
I just tried but could not reproduce either of these two crashes.
As there were lots of changes recently, I would recommend to update HeidiSQL to the latest build, and try to re-check if the problem persists.

**Comment by Zbee** [comment]
My apologies, I have neglected to include important environment information.

HeidiSQL is installed on my system from the Microsoft Store, and is the latest provided there - there are no updates available in the store and I can't check for updates in the app.

**Comment by ansgarbecker** [comment]
Thanks for consistent updates. Rarely seen such quick and good feedback.

As soon as I have v10.0 released, I planned to also update the MS-Store version as well.

**Comment by Zbee** [comment]
Absolutely - I'm working as a developer and I despise vague support tickets, so I try to put out what I hope to receive haha.
I hope the MS store version can become part of the builder and always be up to date (never thought I would say that), as my work's policies/firewall/antivirus config disable the native application's ability to update itself and IT can't figure it out

Cheers!
