### ISSUE TITLE
Row padding greatly reduced

### ISSUE THREAD

**Issue by szheng95** [HeidiSQL/HeidiSQL#468]
## Steps to reproduce this issue

Run a query result, or open the Data tab on a table.

## Behavior

Effective with the 5408 update, there is noticeably reduced default padding on each row in the Data tab and in query results. The left hand side is 5407, the right hand side is 5437. Not sure if this is intentional, but it was definitely unexpected.

![padding example](https://user-images.githubusercontent.com/9489246/50699560-38378b80-1016-11e9-9961-150a1cd8f81b.png)

**Comment by ansgarbecker** [comment]
This is not a bug. I already noticed that, and this most probably happened after my recent update to the VirtualTree component. I found this a good thing, as I get more data on the screen, while probably readability is a bit reduced, but not significantly.

That may have been unexpected, but what's your opinion about that?

**Comment by szheng95** [comment]
As someone who uses the grid-edit functionality in the query results as often as I just use it as a viewer, I definitely preferred the old layout.
