### ISSUE TITLE
Some elements styles are not based on theme colors

### ISSUE THREAD

**Issue by CharlieEtienne** [HeidiSQL/HeidiSQL#471]
## 1. "Session background color" (left sidebar with databases treeview)
This background could be on the same color as one of the darker colors like panels background by default.

## 2. Left sidebar items and "Table" table rows hover and focus background
It looks like these colors are not part of theme.
![hoverandfocused2](https://user-images.githubusercontent.com/9772943/50734716-85953380-11a3-11e9-91fa-e454479d17bb.png)
![hoverandfocused1](https://user-images.githubusercontent.com/9772943/50734688-fdaf2980-11a2-11e9-9747-b71c8d2a477a.png)

## 3. Default "grid text colors" (?) are not exactly the same as current text color theme

![notthesame](https://user-images.githubusercontent.com/9772943/50734817-30f2b800-11a5-11e9-8fc2-7ce81af7c83e.png)

**Possible solution** : apply colors from text theme by default, for example:
```
INTEGER  => DataTypeAttri.Foreground,
FLOAT    => DataTypeAttri.Foreground,
STRING   => StringAttri.Foreground,
BINARY   => NumberAttri.Foreground,
DATETIME => TableNameAttri.Foreground,
SPATIAL  => SymbolAttri.Foreground,
OTHER    => VariableAttri.Foreground
```

Of course you can customize these colors yourself, but if you switch the theme to another one, you will loose all this personnalisation.

## 4. Is it possible to add a shadow behind Forms like basic Windows windows ?
It would improve visibilty and general look IMHO.

**Comment by CharlieEtienne** [comment]
> Those hover colors should be defined in the themes, as they're different to the default "Windows" theme. Couldn't you find these in the theme?

I don't think so, as they're the same in Carbon and Dark Windows 10 themes, but I will look again.

> The data type colors have their own presets, in Preferences > Grid formatting

I know, it is more about consistency, as a text theme should pair with global theme, and moreover, we shouldn't have two different text themes. I think SQL colors should be the same as grid formatting colors. Especially when you change the global theme and all custom grid formatting colors are gone. But it's not a bug, more a little improvement.

> Shadows behind forms - are these defined in the theme? I have no clue. Probably defined in the bitmap style designer somewhere?

I searched for it and I couldn't find it. And again, other themes doesn't seem to have shadow. I asked google but there isn't a lot of things about that, except [some code snippets](https://stackoverflow.com/a/18346275/6743056).

**Comment by Zbee** [comment]
Adding to this also, selecting text in the query editor does not give it a background or even change some text colors, making it very challenging to identify what text is selected.

![khzqmv3 - imgur](https://user-images.githubusercontent.com/1582821/51273650-7e7fd980-198a-11e9-910f-c0d259689238.gif)

**Comment by CharlieEtienne** [comment]
> Adding to this also, selecting text in the query editor does not give it a background or even change some text colors, making it very challenging to identify what text is selected.

@Zbee You can open an issue in https://github.com/CharlieEtienne/material-vcl since Material Theme is responsible for this bug (if I'm not mistaken)

**Comment by ansgarbecker** [comment]
I'm closing this issue, as it should be solved within the theme. @zbee if not please shout.
