### ISSUE TITLE
Add SQL Formatting color preset for old/legacy color scheme

### ISSUE THREAD

**Issue by igitur** [HeidiSQL/HeidiSQL#475]
Follow-up from https://github.com/HeidiSQL/HeidiSQL/issues/425#issuecomment-451951914

## Current behavior

Legacy color scheme unavailable

## Expected behavior

Legacy color scheme to be available

## Possible solution

Add legacy color scheme as a color preset

## Environment

Win7 64b

* **HeidiSQL version:** 
 9.5.0.5442 64bit

**Comment by ansgarbecker** [comment]
Think I revert the current "Light" preset to the previous default colors.
