### ISSUE TITLE
CSV layout detection for table creation or import

### ISSUE THREAD

**Issue by dazlari** [HeidiSQL/HeidiSQL#477]
## Steps to reproduce this issue

I see benefit here for two parts of this application:
1. The existing Import CSV file tool requires a destination table to pre-exist. 
2. The existing Create New Table tool does not support the detection of an existing layout from an external source - such as the content of a CSV file.

## Current behavior

Lack of layout detection in a CSV forces the creation of this layout as a new table with attributes that will undoubtedly require further refinement. 

## Expected behavior

Detection of the layout of a CSV file to prepare a CREATE TABLE statement with compatible fields - including named fields if provided.

## Possible solution

A routine that would scan a target file (such as a CSV, although it may not strictly be limited to this in future) and detect its internal data structure. It returns either a complete CREATE TABLE statement or field listing with field attributes. 

The new table layout could then be previewed for refinement (via the existing New Table screen? ), and then created as a destination target in advance of the Import CSV. 

I'll leave it up to the devs to work out the best method to solve it, but here's my 2c. 
I think at a minimum a 'detect from file'  addition to the '+ Add' columns function in the CREATE NEW TABLE would be a good starting point. Then later extend the Import CSV with a destination of '*New table*' which would imply activating this new feature in advance of the Import. 

HeidiSQL appears happy to play with very large CSV export. It should do the same for import scanning. I can offer the following advice here.
1. Don't assume the file will be small. Think Big Data. 
2. A pre-scan doesn't need to store the entire content (leave that for the database), it only needs to refine its internal structure as it parses the file in pieces. Shouldn't take up too much RAM if written efficiently.
3. If the structure doesn't change after a large number of rows, it is not as likely to change further. So if you have 10M rows and you've scanned 100K with no changes to the layout and you have 9M to go, you might consider calling it quits (this is a 'partial best scan' ). Offering the option to do a full scan vs. partial best vs. first n rows would be awesome!
4. Keep in mind that if scanning is stopped because the file appears to have a problem (eg bad char), we're doing the user a disservice if we don't tell them what was found. After scanning 1M rows and returning 'bad CSV file' would be a major disappointment. The tool should help solve. Return the line#, file offset, offending characters etc. Maybe offer the ability to ignore erroneous rows.

## Environment

* **HeidiSQL version:** 
  
9.5.0.5444
* **Database system and version:** 
  
MS SQL Server 2016
* **Operating system:** 
  
Windows 10

**Comment by outwebbed** [comment]
Would love to see this!

**Comment by ansgarbecker** [comment]
I just started working on that, here's the user interface I have so far:

![grafik](https://user-images.githubusercontent.com/7986591/99440535-02080a00-2917-11eb-953f-d93958293e08.png)

I think I'll overtake your idea with a "New table" item in the table drop-down.

**Comment by dazlari** [comment]
Great stuff! Can't wait to see the result.

**Comment by ansgarbecker** [comment]
First attempt of that new dialog is available in the next build. But there are quite some issues left:
* Detection relies on the control characters the user defined in the import dialog. Users may expect these characters to be auto-detected as well.
* Detection is limited to text, integer and float column types. No date/time, enum, binary columns yet. This may be sufficient here, I suppose these basic column types are already very helpful, the user may refine the table design later.
* Creating the detected table design refreshes the database object list in the back, so the new table shows up in the table drop-down. This refresh deletes internal objects to which the main form still has references. Closing the import window will crash the main window most of the time then.

**Comment by ansgarbecker** [comment]
Ah, and another one:
* detection is limited to MySQL and MariaDB currently. MSSQL, PostgreSQL and SQLite will detect some invalid column types, or in the best case `TEXT` types only.

**Comment by FleppS** [comment]
Hi ... I downloaded the NightlyBuild Revision 11.1.0.6139 but cannot see the "Auto Create"-Button in "Tools"->"Import CSV".
Please advise .. 

Thank you
br
Philippe

**Comment by ansgarbecker** [comment]
I removed that auto-create button, and created a "<New table>" item in the table drop-down, at the very end. I thought that is more intuitive.

**Comment by FleppS** [comment]
Thank you for your quick reply.
It works .. a little buggy but in the end it did the job.

PS: I know it was a nightly build .. but one thing would be nice to have, the column name identification :)

br
Philippe

**Comment by FleppS** [comment]
Thank you for your quick reply.
It works .. a little buggy but in the end it did the job.

br
Philippe

**Comment by ansgarbecker** [comment]
You have to provide valid control characters in the import dialog. And set the "ignore first x lines", if the file contains a header to detect column names.

**Comment by FleppS** [comment]
Thank you ... figured it out by myself :)
Great job.

**Comment by ansgarbecker** [comment]
Crash after table creation in main form should be fixed now.

I'd like to add some support for date/time fields as well.

Also, the CSV detector only workds well with MariaDB and MySQL. On MS SQL, PG and SQLite the detected column types will most likely be too large or too generic.

**Comment by ansgarbecker** [comment]
`DATE` and `DATETIME` columns should now be detected in the next build.
@FleppS could you please say what you experienced as buggy?
Maybe the detection dialog should show an info that it relies on the control characters defined in the import dialog?

**Comment by FleppS** [comment]
Dear @ansgarbecker ,
as I use HeidiSQL on in a production environement, there are not much possibilities to play around with :) ... As soon as I have any news for you on this topic, I will let you know. br. Philippe

**Comment by ansgarbecker** [comment]
@FleppS I will close this now as there is no further feedback, and I planned to release v11.2 soon. For you and me the layout detector worked in some way, while I guess there will be more feedback after the next release, in new tickets then.

**Comment by seungyuno77** [comment]
How to do this with query?
