### ISSUE TITLE
Action bar resize problem while moving window between screens

### ISSUE THREAD

**Issue by Saibamen** [HeidiSQL/HeidiSQL#479]
## Steps to reproduce this issue

1. Move HeidiSQL window to next monitor/screen
2. Move HeidiSQL window to previous monitor/screen

## Current behavior
Action bar got bigger and bigger

![wfwfw](https://user-images.githubusercontent.com/905878/50968769-5d2b7300-14dc-11e9-8a3c-b3c43cb01883.PNG)

![www](https://user-images.githubusercontent.com/905878/50968809-88ae5d80-14dc-11e9-9ecd-c1d13d2fd466.PNG)

## Expected behavior
Action bar width and height are in default 

## Environment

* **HeidiSQL version:** 
9.5.0.5445
* **Operating system:** 
Windows 10.0.17763

**Comment by Saibamen** [comment]
Still existing in 9.5.0.5457

**Comment by flashydreams** [comment]
Just an updated.
This is no longer an issue with version 10.1 (10.10.5469)

**Comment by ansgarbecker** [comment]
Oh really? There are seveal other high dpi issues, and especially about this one I was totally unclear how to solve it. Would be nice to see a screenshot after moving to a different screen.

**Comment by ansgarbecker** [comment]
c31cae206042ae00b97e41f43baf7421693d2e46 now removes all tweaks for high DPI monitors. I'm giving up here, this does all not work good enough, even different computers and Windows versions behave differently. It's a mess. So, now HeidiSQL is zoomed by Windows again, like it was in earlier v9.5. This does at least display all controls and fonts in the right dimensions.
