### ISSUE TITLE
EAccessViolation in SynTextDrawer.InitETODist due to logging translated string with critical character

### ISSUE THREAD

**Issue by Alexsey** [HeidiSQL/HeidiSQL#48]
## Expected behavior

No error

## Current behavior

Error occurs when I execute a query and than another one when I'm clicking on result

## Failure information (for bugs)

I have established a connection to remote MySQL v5.6.36 and tried to execute `SELECT @@version`. Than I have saved a bug report and clicked on result - another error occurred - this one in form of alert wit text "Can't determine the table name" (it's translation - I'm using non-english HeidiSQL)

### Steps to reproduce

1. Connect to MySQL db
2. Execute `SELECT @@version`
3. Click 'Save Bug Report'
4. Click on result row

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.4.0.5194
* Database system + version: mysql 5.6.36-cll-lve
* Operating system: Windows 8

### Failure Logs

Please include any relevant log snippets or files here.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1565058/bugreport.txt)

**Comment by ansgarbecker** [comment]
Which language did you select in Heidi?
The callstack is deep in the code of [SynEdit](https://github.com/SynEdit/SynEdit), and looks a bit as if it is caused by painting some international character into the log panel.

**Comment by Alexsey** [comment]
I've got "Autodetect" and it was Russian. Now I switched to English and see no error. Looks like your guess turned out to be correct

**Comment by Alexsey** [comment]
I cann't reproduce it any more - Russian and Autodetect works fine

**Comment by ansgarbecker** [comment]
Well, I guess that was magic then :) Thanks for your quick feedback!

**Comment by ansgarbecker** [comment]
Seems there are more people having this issue.

**Comment by ansgarbecker** [comment]
I could never reproduce this issue. Please shout if it's still present in latest build.
