### ISSUE TITLE
Missing and/or mis-placed buttons 'Help', 'Discard', 'Save' & 'Run routine(s)' while editing SP

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#482]
## Steps to reproduce this issue
1. Create `test` DB;
2. Create SP in the `test` DB;
3. Click at `information_schema` DB in tree (or any database other than the `test` database you just created on step 1) and choose any table in the DB, for example `CHARACTER_SETS`;
4. Press F5 to refresh list so now you should have the only `information_schema` DB opened in the tree on the left and table `CHARACTER_SETS` is selected on the right;
5. Click on the `test` DB to open it in the tree (not on the chevron!) and then click on the SP you created on step 2;

## Current behavior

"Help", "Discard", "Save" buttons are missing and "Run routine(s)..." button missed or mis-aligned (depend on your screen resolution).
![heidi_missingbuttons](https://user-images.githubusercontent.com/7234987/51092562-7dad4300-17e4-11e9-9f23-f99e59325538.png)
You can try to resize HeidiSQL's window and see that "Run routine(s)..." button moving when you are resizing window.

## Expected behavior

I expect to see buttons on their places, otherwise you cannot use them.

## Possible solution

As a workaround you can click any other table in the DB after SP's modification and use confirmation dialog to save or discard changes.

## Environment

* **HeidiSQL version:** 9.5.0.5453 x64

**Comment by ansgarbecker** [comment]
#440 was a similar thing, in the table editor.
