### ISSUE TITLE
Themed window title buttons not centered, and status bar clipped

### ISSUE THREAD

**Issue by geki007** [HeidiSQL/HeidiSQL#483]
## Steps to reproduce this issue

1. use a not standard theme (e.g. dark win 10)
2. maximize the heidisql window
3. Then the windows minimize, maximize, close buttons look not correct (not in the middle), also the status bar of heidisql looks not as nice as it looks if heidi is not maximized (cutted at bottom)

## Current behavior

Looks not very nice

## Expected behavior

Looks like with standard theme or not maximized

## Environment

* **HeidiSQL version:** 
  9.5.0.5454
* **Operating system:** 
  Win 10 x64 - 1809

**Comment by ansgarbecker** [comment]
Please attach a screenshot for explaining what "looks not very nice" exactly means...

**Comment by geki007** [comment]
Hope this helps

![screenshot](https://user-images.githubusercontent.com/427671/51167229-4d2ddd80-18a6-11e9-910f-d5c387ce7c77.jpg)

**Comment by ansgarbecker** [comment]
That looks quite normal to me. The buttons are where I would expect them, and the status bar looks ok, doesn't it?

**Comment by geki007** [comment]
The position is normal, only the Text/Icons in it are not.
Just compare the top icons (min,max,close) with the Windows Explorer

Top:
- X is not vertical centered (don't maximize the window and it looks a little different)

Statusbar:
- At the bottom of the text in the statusbar should be a small padding like it's at the top of the text (also only vertical centered and little bit higher?)

**Comment by ansgarbecker** [comment]
Ok. Then that's how the theme is defined. I did not create these myself, and I'm sure there are lots of such small glitches in them. You could of course report them to Embarcadero, but I guess the best thing is just to create a new theme without such glitches, like @CharlieEtienne did with the [Material theme](https://github.com/CharlieEtienne/material-vcl).

**Comment by geki007** [comment]
Also the nice Material theme has this problem.
All themes has the problem except "Windows"!
Is there a difference (since it's not in styles.rc)?

**Comment by CharlieEtienne** [comment]
Also Material Theme is based on Windows 10 Dark, so I easily could have include the bug. 
However it doesn't happen with FMX Style Viewer (Bitmap Syle Designer Test Window), so it could come from HeidiSQL as well. I'll look on how Default Windows theme is made and update Material Theme if I can.

**Comment by ansgarbecker** [comment]
> All themes has the problem except "Windows"!
> Is there a difference (since it's not in styles.rc)?

"Windows" is not a theme, it's just the absence of a VCL style, and it's the default "style".

**Comment by ansgarbecker** [comment]
We can use this issue for trying to fix these buttons and status bar.

**Comment by CharlieEtienne** [comment]
1. After some Google searches, it could have something to do with "borders", since they are removed when maximizing (not sure about that). 

2. It seems that Windows remove 8px on each side of a maximized form. (See [here](https://blogs.msdn.microsoft.com/oldnewthing/20120326-00/?p=8003/))

3. It doesn't happen when "snapping" the form to edges of screen. (Even when you snap to the top or bottom to make the form automatically full height as you can do it in Windows 7+)

4. Maybe (I don't know if it's a good idea nor if it's possible) you could try to add some "padding" to a maximized form (using vcl style)...

**Comment by ansgarbecker** [comment]
I'm pretty sure we're running into this VCL bug: https://quality.embarcadero.com/browse/RSP-14081

**Comment by ansgarbecker** [comment]
I just added the theme helper units from https://github.com/RRUZ/vcl-styles-utils to their latest version. Unfortunately, this does not yet fix this issue.

**Comment by ansgarbecker** [comment]
Could someone please also check the status bar height in the newest build? At least it has the right height in high-DPI modes.

**Comment by geki007** [comment]
Sorry for the bad news bad everything is as bad as it was bevor ( not high-dpi ! )
Build: 10.2.0.5614

**Comment by ansgarbecker** [comment]
Please update HeidiSQL to the latest build and re-test. https://quality.embarcadero.com/browse/RSP-14081 says that should be fixed.

**Comment by geki007** [comment]
Looks fixed and good ... thanks!
