### ISSUE TITLE
Material theme, windows have no distinction

### ISSUE THREAD

**Issue by Zbee** [HeidiSQL/HeidiSQL#485]
## Steps to reproduce this issue

1. Select Material Theme
2. Open settings, or another window
3. Be confused about where the border of that window is

## Current behavior

There is no drop shadow, border, highlight, or any other separation around windows in at least the Material theme, making it nearly impossible to distinguish it from its background.

![heidisql](https://user-images.githubusercontent.com/1582821/51272367-298e9400-1987-11e9-9b8f-5874db95aad7.jpg)

## Expected behavior

There should be some sort of separation on windows from their background.

## Possible solution

Add a 1 pixel black border, add a few pixel black drop shadow.

## Environment

* **HeidiSQL version:** 9.5.0.5456
  
* **Database system and version:** Irrelevant
  
* **Operating system:** Windows 10 1809 (17763.253)

**Comment by ansgarbecker** [comment]
I recall @CharlieEtienne already saw that, and asked about how to add shadows.

**Comment by ansgarbecker** [comment]
I'm not sure whether this issue should move to https://github.com/CharlieEtienne/material-vcl

**Comment by ansgarbecker** [comment]
There's a shadow bug in the VCL library: https://quality.embarcadero.com/browse/RSP-11751 Set to "wontfix", so ...

**Comment by Zbee** [comment]
Found that ticket (#471), thank you. Contributed another find there; closing this.

I have no idea, I would _assume_ that him opening it here would somewhat indicate how he thought it should be handled.

**Comment by Zbee** [comment]
Oh that is very unfortunate. I guess a border will be the way to go then. Is that defined here, or in CharlieEtienne/material-vcl?

**Comment by ansgarbecker** [comment]
I'd recommend to file a new issue on CharlieEtienne/material-vcl
