### ISSUE TITLE
Can't double click on foreign key

### ISSUE THREAD

**Issue by Ramonlord** [HeidiSQL/HeidiSQL#486]
## Steps to reproduce this issue

1. Open any table with foreign key;
2. Double click on the foreign key column;
3. Nothing happened;

## Current behavior
Currently nothing is happened, you can edit it only if click twice(with some delay between click)

## Expected behavior
Double click should open dropdown

## Environment

* **HeidiSQL version:** 
9.5.0.5196
  
* **Database system and version:** 
  
* **Operating system:** 
Windows

**Comment by ansgarbecker** [comment]
> Double click should open dropdown

There is no dropdown to show in the "Key name" column. So what do you mean here?

**Comment by Ramonlord** [comment]
Hi, sorry for the delay.
I mean this functionality 
![image](https://user-images.githubusercontent.com/6492169/51646041-95708e00-1f7f-11e9-84aa-817db318e5d2.png)
Here is small demo
![animation 0](https://user-images.githubusercontent.com/6492169/51646128-fb5d1580-1f7f-11e9-8350-1cfa70b7c975.gif)

**Comment by ansgarbecker** [comment]
Ah, thanks. Can confirm that.

**Comment by Ramonlord** [comment]
Also sometimes it shows just regular input field with number inside instead of dropdown, but i can't reproduce it, seems like its happen randomly

**Comment by ansgarbecker** [comment]
[Virtual-Treeview](https://github.com/Virtual-TreeView/Virtual-TreeView) has internal support for activating its edit mode on doubleclick. I just had to enable that option.
Please update to the next build and report back if that works for you.
