### ISSUE TITLE
PostgreSQL: Multiple select queries run in row fails

### ISSUE THREAD

**Issue by RJanata** [HeidiSQL/HeidiSQL#489]
## Steps to reproduce this issue

1. Connect to PSQL (10.3 in my case)
2. Create 2 SELECT queries (simple queries are enough)

```
SELECT 1;
SELECT 2;
```

3. Run them at once (F9) -> ERROR

However, if I run each separately (Ctrl+Shift+F9), both work well.

## Current behavior

I'm getting this error:
> exception class    : EStringListError
> exception message  : List index out of bounds (2).

Error and call stack attached.

## Expected behavior

No error is displayed.

## Possible solution

N/A

## Environment
* **HeidiSQL version:** 
9.5.0.5457, also reproducible in my previous 5337 I used

* **Database system and version:** 
PostgreSQL 10.3
libpq.dll: 10.0.4.18127 or 11.0.1.18320

* **Operating system:** 
Windows 10

**Comment by RJanata** [comment]
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2774120/bugreport.txt)

**Comment by RJanata** [comment]
I've upgraded from 9.5 to 10.3 and this problem is fixed. Thanks.

**Comment by ansgarbecker** [comment]
Oh, thanks for the update. And good to hear this is fixed now.
