### ISSUE TITLE
Hangs on connection if a table is locked

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#49]
## Expected behavior

The software would connect an open normally.

## Current behavior

The connnection window jams.

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. In the first instance, create a table and fill it with lots of data
2. In the second instance, while the first insert datas, try to connect to the DB.
3. you get it...

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.x (latest)
* Database system + version: MariaDB 10.x
* Operating system: WIndows 10.x

**Comment by ansgarbecker** [comment]
I could guess you have disabled multiple application instances? Please check that and report back.
![multiple-app-instances](https://user-images.githubusercontent.com/7986591/34223084-4844ff7c-e5be-11e7-9d91-526adfbf42aa.PNG)

**Comment by sirber** [comment]
It's checked.

The problem is when a table is locked in a "CREATE TABLE AS SELECT" way, you cannot execute show tables, which is executed after a successful connection. I get the same issue with phpMyAdmin with the same conditions.

A workaround would be to check is that kind of query is currently running before asking a SHOW TABLES;

Also, please don't close a ticket if there are no resolution yet.

**Comment by ansgarbecker** [comment]
Thanks for the details. And sorry for closing it, I'm just handling some forum threads and issues with very little information in them, and asking multiple times can be a pain. But the feedback you provided here is excellent.

If I add some check for currently running queries, it would depend on the user privileges which processes are returned, so these may not be those who run a locking query. Anyway, at least Heidi could try. But then again, this `CREATE TABLE AS SELECT` is not the only critical one, is it?

**Comment by sirber** [comment]
>  this CREATE TABLE AS SELECT is not the only critical one, is it?

What do you mean? It's the only scenario I encountered yet that does this.

**Comment by ansgarbecker** [comment]
I prefer to have a more generic solution to this issue. So I thought it's a good thing to run such a query to find out if a database can be safely queried: `SHOW OPEN TABLES FROM mydatabase WHERE in_use`. At least this returns the two involved tables (table_a + table_b) while another instance is running some `CREATE TABLE table_a AS SELECT * FROM table_b`.

**Comment by ansgarbecker** [comment]
I just added some code which does what I wrote above.
Please update to the latest build and report back if that works for you.

**Comment by sirber** [comment]
I'll report back when I get in that situation again (once a week utualy)

**Comment by sirber** [comment]
Updated. Here's the connection logs. I have currently no locks.

/* Delimiter changed to ; */
/* Connecting to 172.16.1.2 via MariaDB (TCP/IP), username root, using password: Yes ... */
SELECT CONNECTION_ID();
/* Connected. Thread-ID: 215610 */
/* Characterset: utf8mb4 */
SHOW STATUS;
SHOW VARIABLES;
SHOW DATABASES;
SHOW OPEN TABLES FROM datamart WHERE in_use!=0;
USE `datamart`;
/* Entering session "datamart" */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='datamart';
SHOW TABLE STATUS FROM `datamart`;
SHOW FUNCTION STATUS WHERE `Db`='datamart';
SHOW PROCEDURE STATUS WHERE `Db`='datamart';
SHOW TRIGGERS FROM `datamart`;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='information_schema';
SHOW TABLE STATUS FROM `information_schema`;
SHOW FUNCTION STATUS WHERE `Db`='information_schema';
SHOW PROCEDURE STATUS WHERE `Db`='information_schema';
SHOW TRIGGERS FROM `information_schema`;
SHOW EVENTS FROM `information_schema`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='datamart';
/* Access is denied */
