### ISSUE TITLE
Assert security issue does not hit HeidiSQL

### ISSUE THREAD

**Issue by antoniopaisfernandes** [HeidiSQL/HeidiSQL#491]
Hi @ansgarbecker,

I've just came across with https://gwillem.gitlab.io/2019/01/20/sites-hacked-via-mysql-protocal-flaw/ and wanted to give you a heads up with it.

Don't know Delphi so I cannot easily assert the impact/code.

Best regards,
António

**Comment by ansgarbecker** [comment]
Is this an actual issue in HeidiSQL?
Is this a request for finding out if HeidiSQL has an issue?

**Comment by antoniopaisfernandes** [comment]
Hello,

I cannot say. I've just found the link (it was just published) and wanted to share the information.

Best regards,
Amtónio

**Comment by KOTRET** [comment]
as a summary:
an evil server you connect to can tell the client to upload a local file.
The news is about unsecured adminer (php administration-frontend), installed on server. The attacker used it to connect an remote server (under attackers control) and the server told adminder to upload a file from the target system - like my.ini.

**Comment by ansgarbecker** [comment]
Yes, I read about that in conjunction with Magento. But I'm still a bit unsure if HeidiSQL is potentially affected, maybe because the underlying libmariadb.dll and/or libmysql.dll is affected.

**Comment by ansgarbecker** [comment]
I'm closing this issue now, due to lack of information.
If there is more, please just shout. I'll reopen it again if there is a todo in HeidiSQL.
