### ISSUE TITLE
auth_gssapi_client.dll getting loaded from the wrong path

### ISSUE THREAD

**Issue by Teejer** [HeidiSQL/HeidiSQL#492]
## Steps to reproduce this issue

1. Step 1; Use auth_gssapi_cleint.dll during login IE user@REALM
2. Step 2; Get error, auth_gssapi_client.dll can not be loaded

## Current behavior

Using Procmon I can see its trying to load the dll from C:\Program Files\MySQL\MySQL Server 5.6\lib\plugin instead of C:\Program Files\HeidiSQL\plugins.

Copying the file to the Mysql folder fixes the error, but should probably get the path fixed on the code side of things so others don't have the error.

## Expected behavior

auth_gssapi_client.dll should be loaded from C:\Program Files\HeidiSQL\plugins.

## Possible solution

Change the path to the correct one.

## Environment
Windows 2016 Standard.

* **HeidiSQL version:** 
9.5.0.5196
* **Database system and version:** 
  Mariadb 10.3.12
* **Operating system:** 
 Windows Server 2016.

**Comment by ansgarbecker** [comment]
Duplicate, which has already been fixed. See #163 and #54 .

**Comment by ansgarbecker** [comment]
Please use the latest build before reporting bugs.
