### ISSUE TITLE
Suppress auto-uppercase for column and table names which are also keywords

### ISSUE THREAD

**Issue by lbuchs** [HeidiSQL/HeidiSQL#494]
## Steps to reproduce this issue

1. Make a table with a column called "Name"
2. Write a query: Write `tablename.`  then select the column "Name" from autocomplete list
3. Heidi writes now `tablename.Name`. 
4. If you add a Space it gets converted to `tablename.NAME`

## Current behavior

HeidiSQL converts column name to uppercase.

## Expected behavior

autocomplete should write ``tablename.`Name` `` . It works for many keywords like `start`, `end`, `type`, `select` but not for `Name`. 

## Possible solution

autocomplete should add grave accent (`) to the all column names if it is a keyword which gets converted to uppercase. 

## Environment
* **HeidiSQL version:**  Version 10.0.0.5460 (64 Bit)
* **Database system and version:** 10.2.18-MariaDB
* **Operating system:** Win 10

**Comment by lbuchs** [comment]
There is a list of all keywords: https://dev.mysql.com/doc/refman/8.0/en/keywords.html - would be nice if all this keywords gets quoted, independent if its written in upper- or lowercase.

Here is the keyword list as text: [mysql8_keywords.txt](https://github.com/HeidiSQL/HeidiSQL/files/2802074/mysql8_keywords.txt)

**Comment by fifonik** [comment]
I do not like the idea to have these backquotes everywhere without reason.
I believe, that if column was auto-completed, the auto upper-scaling must be skipped for this.

I have quite a few columns named Data, Time, Name etc and I'm "forcing" to type queries with the backquote to prevent the columns upperscaling

**Comment by ansgarbecker** [comment]
You can of course disable auto-uppercasing:
![grafik](https://user-images.githubusercontent.com/7986591/52039698-82d4f680-2535-11e9-8d5e-5ed03e0f3b3b.png)

Ok, that's not really a solution. But it seems quite tricky up to impossible to reliably remember identifiers which were auto-completed. Perhaps words preceded by a dot should not be uppercased.

**Comment by fifonik** [comment]
I do like auto uperscaling for words like 'select', 'from' and even 'date'!
However, when I'm typing select * from table where table.d<space for auto-complete> I'd like the auto-completed 'Date' would not auto-upercased. If I understand correctly, the auto-upercase only do it for last edited word, not for whole previously entered string. At least I can go back to the auto-upercased 'DATE', change it to 'Date' and then use arrows or mouse to skip another auto upercasing.

**Comment by lbuchs** [comment]
Maybe you can just auto uppercase if the reserved word is "stand-alone" (just white space, line break or no char before the reserved word).

So if you typing ` Select<space-for-uppercase>` it get's converted to uppercase, if you write `xxx.Select<space-for-uppercase>` it get's not converted because there is a point before the reserved word.

**Comment by Val870** [comment]
Just to be sure as it has not been mentioned but when you say "_don't convert_", you mean not uppercasing it **and** quoting it, right ? 
Because if it's not quoted, it will be colored as any keyword usually is. And so, a column name could be mistaken for a keyword at first glance.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build. I am now checking the character left besides the token in question, and don't uppercase it if it's a dot.

Also, backspace does not trigger uppercasing now, e.g. when you have a table named `countries`, and you backspace the right chars so you have `count` only - this was immediately uppercased up to now.
