### ISSUE TITLE
Main window cut at left side when taskbar is docked left

### ISSUE THREAD

**Issue by Ziggizag** [HeidiSQL/HeidiSQL#495]
New themes render poorly while window is maxed on the secondary monitor. The windows is uncomplete on the left side. Please, have a look here:

http://i.imgur.com/s4Sl7Pp.png

![grafik](https://user-images.githubusercontent.com/7986591/70719487-61ff3500-1cf2-11ea-99eb-008da73941ef.png)

**Comment by ansgarbecker** [comment]
Could you please test whether the window paints differently if you move your taskbar to the bottom again.

**Comment by Ziggizag** [comment]
@ansgarbecker 

Indeed - while taskar is docked in the bottom, window renders well even while maxed. But left-side taskbar is so convinient - you know :-) Please, improve!

**Comment by ansgarbecker** [comment]
@Ziggizag please update to the latest build and do a new test. HeidiSQL is now built with the next Delphi version, which has several fixes for styles, so maybe this is already fixed.

**Comment by ansgarbecker** [comment]
Seems fixed to me:

![grafik](https://user-images.githubusercontent.com/7986591/84379041-78287800-abe5-11ea-8579-d23c1e3efbeb.png)

Even when switching taskbar while HeidiSQL runs, then HeidiSQL refits its window to the taskbar.
