### ISSUE TITLE
Add option to reset session background colour

### ISSUE THREAD

**Issue by leon-v** [HeidiSQL/HeidiSQL#497]
## Steps to reproduce this issue

1. Set session background colour to a session in default theme.
2. Change to dark theme.
3. Session colour looks ugly now, so you want to reset it to default.
4. No way to reset session background colour.

## Current behaviour

No option to reset session background colour.

## Expected behaviour

Able to reset session background colour.

## Possible solution

Add option to reset session background colour.

## Environment
Win 10 x64

* **HeidiSQL version:** 
10.0.0.5460

**Comment by ansgarbecker** [comment]
Related to #360 - I planned to add a "None" color in a dropdown there.

**Comment by ansgarbecker** [comment]
I just moved the color setting to the session manager's "Advanced" tab. This includes a "None" option, so now users can remove a color without having to select "white" or other non-transparent colors which don't fit to all themes.

![grafik](https://user-images.githubusercontent.com/7986591/55273958-b8e2ec80-52d2-11e9-9c5a-dc05cc66f11c.png)
