### ISSUE TITLE
Incomplete Chinese translation with auto-detected system language

### ISSUE THREAD

**Issue by id0612** [HeidiSQL/HeidiSQL#498]
## Current behavior

The default state, does not specify the application language for simplified Chinese, that is: automatic detection

## Expected behavior

When the system default language is detected to be simplified Chinese, the entire application USES simplified Chinese and does not need to be specified as: simplified Chinese

## Environment

Application language:  Auto detect

* **HeidiSQL version:** 
  10.0  Revision 5461
* **Database system and version:** 
  
* **Operating system:** 
  Win 10  Chinese

**Comment by id0612** [comment]
![tim 20190125153445](https://user-images.githubusercontent.com/2449459/51731812-12eaea00-20b7-11e9-90d7-71424fe639f0.png)
![tim 20190125153534](https://user-images.githubusercontent.com/2449459/51731813-12eaea00-20b7-11e9-98a6-11208c1a145e.png)
![tim 20190125153659](https://user-images.githubusercontent.com/2449459/51731814-13838080-20b7-11e9-9f02-40a57b6af9e3.png)


When set to auto detection, only a few are displayed in Chinese.

When set to Chinese, all are displayed as Chinese, indicating that the language package is complete.

**Comment by ansgarbecker** [comment]
We have simplified and traditional Chinese in the language selector. Could it be that one of them is incomplete and you manually selected the other one which is translated completely? Please please test by selecting the other Chinese option.

**Comment by id0612** [comment]
The problem is that the previous version 9.5.0 does not exist, and it will be automatically upgraded. It started from one version, but I can't remember which version it is. All the way to 10.0. The question remains.

**Comment by ansgarbecker** [comment]
I suppose a good idea for debugging is to find out what the auto-detection does in the back. Will try to add the detected language in the dropdown item.

**Comment by ansgarbecker** [comment]
So the language drop down in the preferences dialog now shows the current locale abbreviation. For me it is "de_DE". Please update to the next build and post what you see there.

![grafik](https://user-images.githubusercontent.com/7986591/54389000-603f0d00-469f-11e9-9235-36f87541b17f.png)

**Comment by id0612** [comment]
![1](https://user-images.githubusercontent.com/2449459/54400392-7aa7d380-46fd-11e9-8dfb-df4b0231c714.png)

Auto detect (zh_CN)

**Comment by ansgarbecker** [comment]
I just updated the translation unit from https://sourceforge.net/p/dxgettext/ , which should fix some potentially important missing compiler directives. Please test again with the next build.

**Comment by id0612** [comment]
The defect is still in 5499

![image](https://user-images.githubusercontent.com/2449459/54414493-4ac7f280-4734-11e9-8793-e306087efba6.png)

**Comment by ansgarbecker** [comment]
Oh you tested exactly one build too early :) Sorry for the confusion. Please update again now, the relevant build is now downloadable.

**Comment by id0612** [comment]
![image](https://user-images.githubusercontent.com/2449459/54414991-edcd3c00-4735-11e9-89e7-53f74043ea26.png)

In 5500

**Comment by ansgarbecker** [comment]
I just found that, besides zh_CN and zh_TW, we have a third language: "zh". I'm not sure why it's not listed in the language dropdown, but the translation file is there, and it is more complete than zh_CN:

![grafik](https://user-images.githubusercontent.com/7986591/54450074-cc794980-474f-11e9-8147-27331630cf5b.png)

**Comment by ansgarbecker** [comment]
On Transifex, zh_CN is missing yet 1000 translations:
![grafik](https://user-images.githubusercontent.com/7986591/54454627-30087480-475a-11e9-8dd7-3805eaa93226.png)

To me both zh and zh_CN look different, so zh_CN may be relevant, although it's just incomplete. In that case the translation should just be completed by anyone (feel free :). The other issue is to add zh_CN to the language selector in HeidiSQL's preferences dialog - this is just missing.

**Comment by kotori2** [comment]
Same here. Is there any possibility to redirect "zh" to "zh-CN"? Because it is meaningless as the different between "en" and "en-US".

**Comment by ansgarbecker** [comment]
That's what I asked for, as I'm not aware of Chinese writing. If zh_CN is highly incomplete, and if it's the same language as `zh` which is translated completely, then I can remove zh_CN from Transifex. Or maybe there's a way to disable it.

**Comment by ansgarbecker** [comment]
I just removed zh_CN, after making a local backup. So the next build should auto-detect `zh` instead of `zh_CN` which more exact but no longer there.

**Comment by fangludi** [comment]
@ansgarbecker I download the latest version which is 10.2.0.5999 but the system default language is still detected to be zh_CN instead of zh
![2019-07-08_14-30-18](https://user-images.githubusercontent.com/4664680/60787634-0e118280-a18d-11e9-9818-336e10e81087.png)

**Comment by ansgarbecker** [comment]
Thanks for your feedback. I had the impression this is fixed as there was no more feedback until now.

**Comment by id0612** [comment]
@ansgarbecker Hi, Ansgar Becker, zh: Chinese in general. It includes simplified Chinese and traditional Chinese in various regions. Perhaps because the language pack comes from contributors in multiple parts of the world, it is more complete. Before consulting my proposal, please refer to the following information:


1.
Locale 	Description
-------------------------------
zh 	 	Chinese (China)
zh-CN 	Chinese (Simplified, PRC)
zh-SG 	Chinese (Simplified, Singapore)
zh-TW 	Chinese (Traditional, Taiwan)
zh-HK 	Chinese (Traditional, Hong Kong S.A.R.)
zh-MO 	Chinese (Traditional, Macao S.A.R.)

2.
Traditional Chinese, zh-Hant, it includes: zh-TW、zh-HK、zh-MO
Simplified Chinese, zh-Hans, it includes: zh-CN、zh-SG

3.
Reference: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

%%
Type: language
Subtag: zh
Description: Chinese
Added: 2005-10-16
Scope: macrolanguage
%%
%%
Type: redundant
Tag: zh-Hant
Description: traditional Chinese
Added: 2003-05-30
%%
%%
Type: redundant
Tag: zh-Hans
Description: simplified Chinese
Added: 2003-05-30
%%
%%
Type: region
Subtag: CN
Description: China
Added: 2005-10-16
%%


zh-CN, which includes all Chinese in mainland China, such as big dialects, small dialects, traditional Chinese, simplified Chinese, not just simplified Chinese.

=================================
Based on the above information, I suggest making the following changes to the language options without emphasizing specific regions:

1. zh: Chinese(Simplified) modified to zh: Chinese(China)
2. zh_CN: Chinese(China) modified to zh-Hans: Chinese(Simplified)
3. zh_TW: Chinese(Traditional) modified to zh-Hant: Chinese(Traditional)

For the problem of automatic detection of location language package, since zh is more complete, all Chinese is located to it by default. Zh_CN does not need to be deleted, and it may be complete in the near future.

**Comment by fangludi** [comment]
I think we should remove those unmaintained languages (like zh_CN) first.

**Comment by ansgarbecker** [comment]
zh_CN was previously recreated at some point in the recent weeks. And also, my build process did not delete translation files if they were left out by the download process. They just were not updated, and the old content got baken into heidisql.exe. Now I', firing a `rmdir /Q /S out\locale` to get rid of all translation files, and then pull fresh copies with `tx.py35.exe pull -a -s`.

Current build does not have zh_CN any longer.

**Comment by id0612** [comment]
@ansgarbecker Good ,However, there are still some improvements to be made.
![image](https://user-images.githubusercontent.com/2449459/61029567-e8cf7f00-a3ed-11e9-91ab-d5444f7d77e0.png)

**Comment by ansgarbecker** [comment]
You mean, the auto-detect still says "zh_CN", or ...?

Is that screen taken from a new build?

**Comment by id0612** [comment]
Yes, it's the latest version, just a display problem.

**Comment by ansgarbecker** [comment]
If zh_CN is still there, then this is not just a display problem. Or am I misunderstanding you?

**Comment by id0612** [comment]
The auto-detected language package is now zh and zh_CN is no longer in the language option. It's just that there's still a zh_CN after the automatic detection.

![image](https://user-images.githubusercontent.com/2449459/61094340-61335000-a481-11e9-8677-94867e3dc74c.png)

**Comment by ansgarbecker** [comment]
Oh I see. The gettext unit detects this language code, while I can't fix it to the one which is offered as a language selection.

**Comment by id0612** [comment]
Maybe it doesn't show it, after "Auto detect", like before I asked this issue, it just display "Auto detect".

**Comment by id0612** [comment]
Zh_CN is shown, but it is not in the option, which is not very friendly.
