### ISSUE TITLE
Windows Defender SmartScreen prevented an unrecognized app from starting

### ISSUE THREAD

**Issue by CharlieEtienne** [HeidiSQL/HeidiSQL#501]
When I download HeidiSQL v10 and launch .exe, I get a warning from Windows Defender SmartScreen.

I don't know if it is related to version 10 or if it was the same with previous versions...

![2019-01-25_11h00_23](https://user-images.githubusercontent.com/9772943/51738866-6dbd1b00-2090-11e9-9ef4-2913b00af589.png)

**Comment by ansgarbecker** [comment]
That's #152 . v9.5 had a code signature which expired last year, and I could not yet find a good (cheap) alternative to Certum.pl
