### ISSUE TITLE
Use one mysql connexion per query tab

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#503]
## Steps to reproduce this issue

1. Execute a long query in a query tab
2. Click elsewhere (another table, etc)
3. Then the UI jam until the query in step 1 finishes

## Current behavior

The UI jams

## Expected behavior

Be able to browse elsewhere in the database, for the tables my query isn't locking.

## Possible solution

Use a distinct connexion for query tabs, or a connexion pool. 

## Environment

* **HeidiSQL version:** 
  
9.5.0.5437
* **Database system and version:** 
  
mariaDb 10.3.11
* **Operating system:** 
windows 10 x64

**Comment by lubomihailov** [comment]
it's reproducible if we rung long query on one tab and HeidiSQL is locked until its finish

**Comment by ansgarbecker** [comment]
The reason for a single connection approach is to keep variables the user may have set for the particular one. They would be lost in a second connection.

**Comment by sirber** [comment]
that's how mysql works, same with temporary tables.

I'd prefer a responsive application instead of session variable keeping which I can recreate as needed.
