### ISSUE TITLE
Hopefully the experience is better in 4K screens

### ISSUE THREAD

**Issue by id0612** [HeidiSQL/HeidiSQL#504]
## Steps to reproduce this issue

First experience after installation

1. After opening a database connection: The UI doesn't display well
![2](https://user-images.githubusercontent.com/2449459/51795200-4a25dc00-221a-11e9-9527-4f06008a743a.png)

2. Window maximized: left navigation bar too narrow.
![3](https://user-images.githubusercontent.com/2449459/51795248-1c8d6280-221b-11e9-9a24-7676d67d3e87.png)

3. Open data table index or column management: row height too high
![4](https://user-images.githubusercontent.com/2449459/51795266-5b231d00-221b-11e9-8085-65cf0a992c45.png)

4. Click on the Query TAB: SQL input area is too small
![5](https://user-images.githubusercontent.com/2449459/51795301-a2111280-221b-11e9-926a-157a752eb5e6.png)

5. Pull the SQL input area higher: The right side of the SQL input area is too small and the display is incomplete.
![0](https://user-images.githubusercontent.com/2449459/51795338-53b04380-221c-11e9-91de-6216ead2c4c5.png)

6. The default popup window for column editing is small and incomplete.
![6](https://user-images.githubusercontent.com/2449459/51795378-421b6b80-221d-11e9-8703-fcd58463595e.png)

## Current behavior

First use without any adjustment to the interface.

## Expected behavior

By default

## Possible solution

Compatible with 4K screen

## Environment

* **HeidiSQL version:** 
  10.1.0.5464
* **Database system and version:** 
  
* **Operating system:** 
Windows 10 64-bit simplified Chinese
![7](https://user-images.githubusercontent.com/2449459/51795380-4778b600-221d-11e9-9aba-5e4b1771ac8b.png)

**Comment by ansgarbecker** [comment]
Please watch out there are already reported issues here which you reported again. And please one issue per ticket.
