### ISSUE TITLE
Unable correct insert row in postgres

### ISSUE THREAD

**Issue by radekhanus1** [HeidiSQL/HeidiSQL#506]
Hi, 

the problem is that in postgre SQL is not possible to insert row whet there is serial number.
This problem is KO factor for using new version of this nice database tool.

Steps to reproduce this issue
create table with serial primary key
for example:
```
CREATE TABLE test
(
id serial NOT NULL,
a text,
PRIMARY KEY (id)
)
WITH (
OIDS=FALSE
);

```
insert row via editor (autoincrement field is nextval...)
do insert 5 times
after insert is id not incremented by 1 (step is more one than 1)

![image](https://user-images.githubusercontent.com/47090713/51807302-85112980-2285-11e9-8657-afeda5d7e537.png)

Current behavior
id is not incement by 1

Expected behavior
id must be increment by 1

Possible solution
in version 9.5.0.5196 is behavior OK

Environment

HeidiSQL version: 10.0.1
Database system and version: postgres 9.4 but it is not depend on version postre database
Operating system: windows

**Comment by randalla0622** [comment]
It appears that when you go into insert mode, or on insert, it's calling nextval(...) once for every row including the new one. This will cause an exponential increase in the serial value as new rows are added.

**Comment by ansgarbecker** [comment]
I could not see an exponential incrementation for that serial number when inserting 3 rows in the above described table:
![grafik](https://user-images.githubusercontent.com/7986591/57596216-c0d8b200-7549-11e9-95c0-138b6aaa1784.png)

Also I see no error message when inserting a row, on my PostgreSQL 10.3. The only issue I see is the grid does not show the auto-incremented id after the `INSERT` was fired. I had to press F5 to see it.

So I suppose this is server version specific, or you have some specific setup.

@radekhanus1 please post the last 10 lines from the SQL log panel after you inserted a new row into that table using the data grid.

**Comment by ansgarbecker** [comment]
@radekhanus1 Please give feedback so we can sort this out for the next release.
Also please update to the latest build, as I have pushed a fix for another PostgreSQL related bug this morning, which I suspect could be the causing problem here.

**Comment by radekhanus1** [comment]
Hi Ansgar, 

I download latest nightly build and it is working now:
![image](https://user-images.githubusercontent.com/47090713/57986953-9a4fd500-7a7b-11e9-8cf3-9d66f3db83b1.png)

thanks for solving this problem.

Radek

here is log from console:

`CREATE TABLE test
(
id serial NOT NULL,
a text,
PRIMARY KEY (id)
)
WITH (
OIDS=FALSE
);
/* Affected rows: 0  Nalezené řádky: 0  Varování: 0  Doba vykonávání 1 dotaz: 0,000 sec. (+ 0,078 sec. network) */
SELECT *, pg_table_size(QUOTE_IDENT(t.TABLE_SCHEMA) || E'.' || QUOTE_IDENT(t.TABLE_NAME))::bigint AS data_length, pg_relation_size(QUOTE_IDENT(t.TABLE_SCHEMA) || E'.' || QUOTE_IDENT(t.TABLE_NAME))::bigint AS index_length, c.reltuples, obj_description(c.oid) AS comment FROM "information_schema"."tables" AS t LEFT JOIN "pg_namespace" n ON t.table_schema = n.nspname LEFT JOIN "pg_class" c ON n.oid = c.relnamespace AND c.relname=t.table_name WHERE t."table_schema"=E'public';
/* Unknown datatype oid #1034 for "nspacl". Fall back to UNKNOWN. */
/* Unknown datatype oid #1034 for "relacl". Fall back to UNKNOWN. */
/* Unknown datatype oid #1009 for "reloptions". Fall back to UNKNOWN. */
SELECT "p"."proname", "p"."proargtypes" FROM "pg_catalog"."pg_namespace" AS "n" JOIN "pg_catalog"."pg_proc" AS "p" ON "p"."pronamespace" = "n"."oid" WHERE "n"."nspname"=E'public';
SELECT   DISTINCT a.attname AS column_name,   a.attnum,   a.atttypid,   FORMAT_TYPE(a.atttypid, a.atttypmod) AS data_type,   CASE a.attnotnull WHEN false THEN E'YES' ELSE E'NO' END AS IS_NULLABLE,   com.description AS column_comment,   def.adsrc AS column_default,   NULL AS character_maximum_length FROM pg_attribute AS a JOIN pg_class AS pgc ON pgc.oid = a.attrelid LEFT JOIN pg_description AS com ON (pgc.oid = com.objoid AND a.attnum = com.objsubid) LEFT JOIN pg_attrdef AS def ON (a.attrelid = def.adrelid AND a.attnum = def.adnum) WHERE   a.attnum > 0   AND pgc.oid = a.attrelid   AND pg_table_is_visible(pgc.oid)   AND NOT a.attisdropped   AND pgc.relname = E'test' ORDER BY a.attnum;
WITH ndx_list AS (    SELECT pg_index.indexrelid, pg_class.oid    FROM pg_index, pg_class    WHERE pg_class.relname = E'test'    AND pg_class.oid = pg_index.indrelid  ),  ndx_cols AS (    SELECT pg_class.relname, UNNEST(i.indkey) AS col_ndx,    CASE i.indisprimary WHEN true THEN E'PRIMARY' ELSE CASE i.indisunique WHEN true THEN E'UNIQUE' ELSE E'KEY' END END AS CONSTRAINT_TYPE,    pg_class.oid    FROM pg_class    JOIN pg_index i ON (pg_class.oid = i.indexrelid)    JOIN ndx_list ON (pg_class.oid = ndx_list.indexrelid)  )SELECT ndx_cols.relname AS CONSTRAINT_NAME, ndx_cols.CONSTRAINT_TYPE, a.attname AS COLUMN_NAME FROM pg_attribute a JOIN ndx_cols ON (a.attnum = ndx_cols.col_ndx) JOIN ndx_list ON (ndx_list.oid = a.attrelid AND ndx_list.indexrelid = ndx_cols.oid);
SELECT  "id",  SUBSTR("a", 1, 256) FROM "public"."test" LIMIT 1000;
SELECT   DISTINCT a.attname AS column_name,   a.attnum,   a.atttypid,   FORMAT_TYPE(a.atttypid, a.atttypmod) AS data_type,   CASE a.attnotnull WHEN false THEN E'YES' ELSE E'NO' END AS IS_NULLABLE,   com.description AS column_comment,   def.adsrc AS column_default,   NULL AS character_maximum_length FROM pg_attribute AS a JOIN pg_class AS pgc ON pgc.oid = a.attrelid LEFT JOIN pg_description AS com ON (pgc.oid = com.objoid AND a.attnum = com.objsubid) LEFT JOIN pg_attrdef AS def ON (a.attrelid = def.adrelid AND a.attnum = def.adnum) WHERE   a.attnum > 0   AND pgc.oid = a.attrelid   AND pg_table_is_visible(pgc.oid)   AND NOT a.attisdropped   AND pgc.relname = E'test' ORDER BY a.attnum;
WITH ndx_list AS (    SELECT pg_index.indexrelid, pg_class.oid    FROM pg_index, pg_class    WHERE pg_class.relname = E'test'    AND pg_class.oid = pg_index.indrelid  ),  ndx_cols AS (    SELECT pg_class.relname, UNNEST(i.indkey) AS col_ndx,    CASE i.indisprimary WHEN true THEN E'PRIMARY' ELSE CASE i.indisunique WHEN true THEN E'UNIQUE' ELSE E'KEY' END END AS CONSTRAINT_TYPE,    pg_class.oid    FROM pg_class    JOIN pg_index i ON (pg_class.oid = i.indexrelid)    JOIN ndx_list ON (pg_class.oid = ndx_list.indexrelid)  )SELECT ndx_cols.relname AS CONSTRAINT_NAME, ndx_cols.CONSTRAINT_TYPE, a.attname AS COLUMN_NAME FROM pg_attribute a JOIN ndx_cols ON (a.attnum = ndx_cols.col_ndx) JOIN ndx_list ON (ndx_list.oid = a.attrelid AND ndx_list.indexrelid = ndx_cols.oid);
INSERT INTO "public"."test" ("a") VALUES (E'a');
SELECT "id", "a" FROM "public"."test" WHERE  "id"=0;
INSERT INTO "public"."test" ("a") VALUES (E'b');
SELECT "id", "a" FROM "public"."test" WHERE  "id"=0;
INSERT INTO "public"."test" ("a") VALUES (E'c');
SELECT "id", "a" FROM "public"."test" WHERE  "id"=0;
INSERT INTO "public"."test" ("a") VALUES (E'd');
SELECT "id", "a" FROM "public"."test" WHERE  "id"=0;
SELECT  "id",  SUBSTR("a", 1, 256) FROM "public"."test" LIMIT 1000;
SELECT   DISTINCT a.attname AS column_name,   a.attnum,   a.atttypid,   FORMAT_TYPE(a.atttypid, a.atttypmod) AS data_type,   CASE a.attnotnull WHEN false THEN E'YES' ELSE E'NO' END AS IS_NULLABLE,   com.description AS column_comment,   def.adsrc AS column_default,   NULL AS character_maximum_length FROM pg_attribute AS a JOIN pg_class AS pgc ON pgc.oid = a.attrelid LEFT JOIN pg_description AS com ON (pgc.oid = com.objoid AND a.attnum = com.objsubid) LEFT JOIN pg_attrdef AS def ON (a.attrelid = def.adrelid AND a.attnum = def.adnum) WHERE   a.attnum > 0   AND pgc.oid = a.attrelid   AND pg_table_is_visible(pgc.oid)   AND NOT a.attisdropped   AND pgc.relname = E'test' ORDER BY a.attnum;
WITH ndx_list AS (    SELECT pg_index.indexrelid, pg_class.oid    FROM pg_index, pg_class    WHERE pg_class.relname = E'test'    AND pg_class.oid = pg_index.indrelid  ),  ndx_cols AS (    SELECT pg_class.relname, UNNEST(i.indkey) AS col_ndx,    CASE i.indisprimary WHEN true THEN E'PRIMARY' ELSE CASE i.indisunique WHEN true THEN E'UNIQUE' ELSE E'KEY' END END AS CONSTRAINT_TYPE,    pg_class.oid    FROM pg_class    JOIN pg_index i ON (pg_class.oid = i.indexrelid)    JOIN ndx_list ON (pg_class.oid = ndx_list.indexrelid)  )SELECT ndx_cols.relname AS CONSTRAINT_NAME, ndx_cols.CONSTRAINT_TYPE, a.attname AS COLUMN_NAME FROM pg_attribute a JOIN ndx_cols ON (a.attnum = ndx_cols.col_ndx) JOIN ndx_list ON (ndx_list.oid = a.attrelid AND ndx_list.indexrelid = ndx_cols.oid);`

**Comment by ansgarbecker** [comment]
Thanks a lot for coming back here!
