### ISSUE TITLE
Multi-select from results does ot work

### ISSUE THREAD

**Issue by TheStav** [HeidiSQL/HeidiSQL#508]
## Steps to reproduce this issue

1. Step 1; Either select something or go to the data of a table
2. Step 2; Try to select several records (by clicking control)

3. Then I get... Only one result is selected. I cannot select several records/results

## Current behavior
Only one record is selected at a time

## Expected behavior
All records that are selected if control is held should be selected

## Possible solution
Allow multi-select

## Environment

* **HeidiSQL version:** 10.1.0.5464
  
* **Database system and version:** 
  
* **Operating system:** Win 10

**Comment by ansgarbecker** [comment]
I guess the "selected" background color is just not visible (enough) to separate them from non-selected rows. Please verify. E.g. rightclick and click "Export grid rows", where the dialog tells you how many rows are selected.

**Comment by TheStav** [comment]
I belive you are correct!
It does have to do with the selected color. Only the last row that I click on has the blue 'selected' color.
When I tired to export, the export screen does inlude all the selecterd rows.

Is there a way to change the color of the selected rows?

**Comment by ansgarbecker** [comment]
You could mention which theme you selected, I guess not the default "Windows" theme?

That color depends on the selected theme.

**Comment by TheStav** [comment]
I am using the "Windows" theme.
On closer inspection I think it's a combination of the background color not being visible enough (like you said) and one of my monitors not being sharp enough.
Thanks for your responses !

**Comment by ansgarbecker** [comment]
Thanks for you input. I suppose if there are more users then I should change that color calculation in some way.
