### ISSUE TITLE
Crash when dropping a table

### ISSUE THREAD

**Issue by btry** [HeidiSQL/HeidiSQL#510]
## Steps to reproduce this issue

1. Open a local database
2. Try to drop a table
3. Confirm the action in the dialog
4. see the crash

## Current behavior

a crash with debug info (see below)
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2803293/bugreport.txt)

## Expected behavior

well.. a successful deletion

## Environment
* **HeidiSQL version:** 
  10.1.0.5464 configured with dark material theme

* **Database system and version:** 
  mariadb  Ver 15.1 Distrib 10.3.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* **Operating system:** 
Debian Sid / wine-4.0-rc6 (Debian 4.0~rc6-1) / xfce 4 (with a dark theme)

**Comment by ansgarbecker** [comment]
Relevant part of the callstack:

```
exception class    : EAccessViolation
exception message  : Access violation at address 00007F2D5A10CFE9 in module 'comctl32.dll'. Read of address 0000000000000008.

main thread ($32):
7f2d5a10 comctl32.dll
7f2d5b91 user32.dll                                          CallWindowProcW
7f2d5b88 user32.dll                                          DefDlgProcW
7f2d5b91 user32.dll                                          CallWindowProcW
00c7a1c8 heidisql.exe Vcl.Styles.Utils.SysStyleHook  579  +1 TSysStyleHook.CallDefaultProc
00c7be65 heidisql.exe Vcl.Styles.Utils.SysStyleHook 1254 +99 TSysStyleHook.WndProc
00d201d8 heidisql.exe Vcl.Styles.Utils.Forms        2591 +78 TSysScrollingStyleHook.WndProc
00d1cc7f heidisql.exe Vcl.Styles.Utils.Forms        1327 +46 TSysDialogStyleHook.WndProc
0055c293 heidisql.exe System.Classes                         StdWndProc
7f2d5b8c user32.dll                                          TranslateAccelerator
7f2d5b8c user32.dll                                          SendMessageW
7f2d5b90 user32.dll                                          DestroyWindow
7f2d5b89 user32.dll                                          DialogBoxIndirectParamAorW
7f2d5b89 user32.dll                                          DialogBoxIndirectParamW
7f2d5a10 comctl32.dll                                        TaskDialogIndirect
004a4088 heidisql.exe Winapi.CommCtrl                        TaskDialogIndirect
00772891 heidisql.exe Vcl.Dialogs                            TCustomTaskDialog.DoExecute
00772d68 heidisql.exe Vcl.Dialogs                            TCustomTaskDialog.Execute
00772d2f heidisql.exe Vcl.Dialogs                            TCustomTaskDialog.Execute
009d0b9b heidisql.exe apphelpers                    2565 +80 MessageDialog
00d99730 heidisql.exe Main                          3279 +52 TMainForm.actDropObjectsExecute

```

**Comment by ansgarbecker** [comment]
Does that happen with the default "Windows" theme as well? I guess no...

**Comment by btry** [comment]
You're right, with the regular theme, I could add then drop a table successfully.

**Comment by goffyara** [comment]
+1. Just praised the dark theme... Crash with `Access violation at address 00007FF80900D9F9 in module 'comctl32.dll'` when delete row...

**Comment by exuvo** [comment]
I am still having these crashes after confirm dialogs (even editing preferences that require restart with warning popup) if if use any theme other than Windows (tried like 5 others).
Using wine 4.8 (as that does not have the redraw bug) and heidisql 11.0.0.6098, 11.0.0.6107.

**Comment by btry** [comment]
Hi

I'm now running Ubuntu 20.04 + wine and HeidiSQL 11.0.0.5919.

Deleting a table works well for me now. However, upon deletion, some components of the main window change their background color to white (or nearly white). The test was done with the Windows 10 dark theme.

- Background og left treeview for DBs and tables
- background color of toobar buttons when mouse hovers them (randomly ?)
- background color of labels on buttons of dialogs.

**Comment by ansgarbecker** [comment]
Please shout if still present with v12.0
