### ISSUE TITLE
Dark theme highlighting colour

### ISSUE THREAD

**Issue by harry-synergi** [HeidiSQL/HeidiSQL#512]
## Steps to reproduce this issue

1. Edit a column or data field
2. Highlight the text within the column or data field
2. The highlighted text will appear no different despite being highlighted

## Current behavior

When highlighting text whilst editing it, the highlighted text remains the same colour as the non highlighted text whilst on the dark theme (Material).
![2019-01-28_15-19-12](https://user-images.githubusercontent.com/44359670/51845826-32c91a80-2310-11e9-992d-58b2512bc1e9.gif)

## Expected behavior

The highlighted text should have a recognisable difference in colour when highlighted

## Environment

* **HeidiSQL version:** 
  10.1.0.5464 (64 bit)
* **Operating system:** 
  Windows 10

**Comment by btry** [comment]
Hi

I observe the same under linux 

## Environment
* **HeidiSQL version:** 
  10.1.0.5464 configured with dark material theme

* **Database system and version:** 
  mariadb  Ver 15.1 Distrib 10.3.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* **Operating system:** 
Debian Sid / wine-4.0-rc6 (Debian 4.0~rc6-1) / xfce 4 (with a dark theme)

**Comment by CharlieEtienne** [comment]
Fixed in Material Theme version 1.2. Updated in [this commit](https://github.com/HeidiSQL/HeidiSQL/commit/7dd603fa0b8e56aa3157b3eb229eec4ad86900c6)

**Comment by ansgarbecker** [comment]
@harry-synergi + @btry: please give feedback after updating to the latest build.

**Comment by btry** [comment]
The same : it works

![image](https://user-images.githubusercontent.com/14139801/51898527-5db77b00-23b1-11e9-8d4e-a5d676d85b84.png)

**Comment by ansgarbecker** [comment]
Great! Thanks for your feedback.
