### ISSUE TITLE
Add Theme Preview 

### ISSUE THREAD

**Issue by adhayward** [HeidiSQL/HeidiSQL#513]
When choosing a theme it would be useful to have a preview of some kind to show what the theme would look like. 

## Current behavior
To see a theme you must select it in the preferences and restart Heidi. 

## Possible solution
Either an image next to the dropdown in the preferences showing a screenshot with the selected theme or a page in the help documentation listing all themes with screen shots. 

* **HeidiSQL version:** 
  10.1

**Comment by CharlieEtienne** [comment]
Another simple and elegant solution might be a "color palette" of the theme's main colors, like the one you can find in WordPress profile edit page

![2019-01-30_19h00_29](https://user-images.githubusercontent.com/9772943/52002109-64cdae80-24c1-11e9-9bfa-2999c84a99e3.png)

 or a very basic illustration like in Slack settings.

![2019-01-30_18h58_47](https://user-images.githubusercontent.com/9772943/52001988-16b8ab00-24c1-11e9-920a-bf3e513bb3d1.png)

**Comment by funderbenz** [comment]
Hi, this feature would be useful for sure....it's a bit annoying to restart the app every time :/

Unfortunately I'm out of time otherwhise I would collaborate for this. 

Bye

**Comment by SherylHohman** [comment]
..Or at least include a link to screenshots on the website!
Do you have screenshots on the website (my initial search didn't find any) ?  
If not, that would be a huge help!

With no previews Anywhere, there is a huge disconnect with time and effort people have devoted to creating themes, and the ability for users to actually use them.

If there is a webpage (anywhere) showing the themes, can somebody please include a link here - google search did not turn up any such page, but did bring up this one :-)
Thanks.

**Comment by billom** [comment]
How about we help create the screen shots to save the coders some time.  I will start the collection with 5 screen shots.  

If you can contribute, please let's all use the same shot.  Open the Information_Schema database, scroll down until Events is the last item in the tree, select the TABLES table.  Grab a screen shot.  

Can we agree on 1920 x 1080?  Then whoever can grab them all and do a blog or webpage can make things look uniform.  I will come back and add more next week as time permits.

Amakrits
![Amakrits](https://user-images.githubusercontent.com/52833371/61145146-52a66200-a49c-11e9-9b22-3ddcd26c01f6.png)

Amethyst Kamri
![Amethyst Kamri](https://user-images.githubusercontent.com/52833371/61145147-52a66200-a49c-11e9-9f93-e60341d10da0.png)

Aqua Graphite
![Aqua Graphite](https://user-images.githubusercontent.com/52833371/61145148-533ef880-a49c-11e9-849f-73a31813ea2f.png)

Aqua Light Slate
![Aqua Light Slate](https://user-images.githubusercontent.com/52833371/61145149-533ef880-a49c-11e9-8c17-9601c82b7252.png)

Auric
![Auric](https://user-images.githubusercontent.com/52833371/61145150-533ef880-a49c-11e9-8f62-ac378f2f6ae7.png)

**Comment by billom** [comment]
Heck, it didn't take long to do the first ten so here are the rest... Enjoy

Emerald Light Slate
![Emerald Light Slate](https://user-images.githubusercontent.com/52833371/61149263-5fc84e80-a4a6-11e9-8cc4-e695c7684377.png)

Glossy
![Glossy](https://user-images.githubusercontent.com/52833371/61149264-6060e500-a4a6-11e9-9093-809243f271e3.png)

Glow
![Glow](https://user-images.githubusercontent.com/52833371/61149265-6060e500-a4a6-11e9-935b-42e1483ee313.png)

Golden Graphite
![Golden Graphite](https://user-images.githubusercontent.com/52833371/61149561-07de1780-a4a7-11e9-8c41-48ffac9c4b2f.png)

Iceberg Classico
![Iceberg Classico](https://user-images.githubusercontent.com/52833371/61149267-6060e500-a4a6-11e9-8895-aaa85b47e804.png)

Lavender Classico
![Lavender Classico](https://user-images.githubusercontent.com/52833371/61149268-6060e500-a4a6-11e9-9793-dbd048f044b0.png)

Light
![Light](https://user-images.githubusercontent.com/52833371/61149269-6060e500-a4a6-11e9-82b7-8043b6eb4314.png)

Luna
![Luna](https://user-images.githubusercontent.com/52833371/61149270-6060e500-a4a6-11e9-8e20-7297f0f80050.png)

Material
![Material](https://user-images.githubusercontent.com/52833371/61149271-60f97b80-a4a6-11e9-879c-46fa4fe79413.png)

Metropolis UI Black
![Metropolis UI Black](https://user-images.githubusercontent.com/52833371/61149272-60f97b80-a4a6-11e9-856b-de97e1378993.png)

Metropolis UI Blue
![Metropolis UI Blue](https://user-images.githubusercontent.com/52833371/61149273-60f97b80-a4a6-11e9-9ae9-0a1f18d10cf0.png)

Metropolis UI Dark
![Metropolis UI Dark](https://user-images.githubusercontent.com/52833371/61149275-60f97b80-a4a6-11e9-96db-0bf640679fea.png)

Metropolis UI Green
![Metropolis UI Green](https://user-images.githubusercontent.com/52833371/61149276-60f97b80-a4a6-11e9-82e0-98bd703fb5e2.png)

Obsidian
![Obsidian](https://user-images.githubusercontent.com/52833371/61149277-60f97b80-a4a6-11e9-9103-b5d422b9d77b.png)

Onyx Blue
![Onyx Blue](https://user-images.githubusercontent.com/52833371/61149278-60f97b80-a4a6-11e9-9c4c-36988fe0a9d6.png)

Ruby Graphite
![Ruby Graphite](https://user-images.githubusercontent.com/52833371/61149279-61921200-a4a6-11e9-9026-61ffc8d13f83.png)

Sapphire Kamri
![Sapphire Kamri](https://user-images.githubusercontent.com/52833371/61149281-61921200-a4a6-11e9-920d-0c379a43571e.png)

Silver
![Silver](https://user-images.githubusercontent.com/52833371/61149282-61921200-a4a6-11e9-8022-1a730448ea2b.png)

Sky
![Sky](https://user-images.githubusercontent.com/52833371/61149283-61921200-a4a6-11e9-90a4-fdbbd438f1df.png)

Slate Classico
![Slate Classico](https://user-images.githubusercontent.com/52833371/61149284-61921200-a4a6-11e9-9a03-ca2aae28ae45.png)

Smokey Quartz Kamri
![Smokey Quartz Kamri](https://user-images.githubusercontent.com/52833371/61149285-61921200-a4a6-11e9-9e95-91f628cbd6cd.png)

Tablet Light
![Tablet Light](https://user-images.githubusercontent.com/52833371/61149286-61921200-a4a6-11e9-8f4a-acab3e65a7d0.png)

TabletDark
![TabletDark](https://user-images.githubusercontent.com/52833371/61149287-622aa880-a4a6-11e9-90b2-3949ab2ec532.png)

Turquoise Gray
![Turquoise Gray](https://user-images.githubusercontent.com/52833371/61149288-622aa880-a4a6-11e9-9a24-33183b5cd45b.png)

Windows
![Windows](https://user-images.githubusercontent.com/52833371/61149289-622aa880-a4a6-11e9-968a-9db67ddc8934.png)

Windows10
![Windows10](https://user-images.githubusercontent.com/52833371/61149296-62c33f00-a4a6-11e9-84e2-a3abeba50552.png)

Windows10 Blue
![Windows10 Blue](https://user-images.githubusercontent.com/52833371/61149290-622aa880-a4a6-11e9-8983-3d7169af083c.png)

Windows10 Dark
![Windows10 Dark](https://user-images.githubusercontent.com/52833371/61149291-622aa880-a4a6-11e9-9917-4584acf23dd8.png)

Windows10 Green
![Windows10 Green](https://user-images.githubusercontent.com/52833371/61149292-622aa880-a4a6-11e9-93b0-fc210992b588.png)

Windows10 Purple
![Windows10 Purple](https://user-images.githubusercontent.com/52833371/61149294-622aa880-a4a6-11e9-825c-72a504a849e4.png)

Windows10 SlateGray
![Windows10 SlateGray](https://user-images.githubusercontent.com/52833371/61149295-62c33f00-a4a6-11e9-800e-852f55d3a9c1.png)

**Comment by ansgarbecker** [comment]
Hey @billom , thanks for the whole bunch of work, that's nice!

I just thought I can integrate them in two ways: have them on heidisql.com on a theme preview page, plus create a preview button/dialog in the preferences window, like this:

![grafik](https://user-images.githubusercontent.com/7986591/61169632-decd8d80-a55f-11e9-853f-dbe3770450c6.png)

**Comment by ansgarbecker** [comment]
Here's the just created overview web page: https://www.heidisql.com/themes.php

**Comment by ansgarbecker** [comment]
How's that?

![grafik](https://user-images.githubusercontent.com/7986591/61172655-78f4fc00-a587-11e9-909b-40467bf147e0.png)

* The image gets downloaded from heidisql.com each time you select one from the dropdown
* That preview image gets scrollbars, and scrolling via mouse-wheel is supported.
* The image is not stretched because I totally failed in stretching the image in a high quality manner.
* The "Windows" theme does not have a preview, as this relies on the user selected styles in his system settings

**Comment by ansgarbecker** [comment]
For testing yourself, please update to the latest build.

And shout if there is something broken there. For me it works good (enough) currently.

**Comment by billom** [comment]
The preview worked great!  Thank you.   The only thing you may want to change is when we select "Windows", show something like the following screen shot.  As it is now, the background stays to the one last selected.

![Windows](https://user-images.githubusercontent.com/52833371/61175549-4b07bb80-a577-11e9-879f-27d0999b61e5.png)

**Comment by ansgarbecker** [comment]
Yes - I just uploaded that image too, so HeidiSQL should show it.

**Comment by billom** [comment]
Very nice - worked like a charm.  Thank you for such an awesome tool.

**Comment by funderbenz** [comment]
Hi @ansgarbecker, the preview is lookin cool!

I'm thinking...is it possible to show it in a window which doesn't have the title bar, and has the classical windows 10 shadowed borders? 
A callout would be nice... I'm linking an image to give an idea: [example](https://i.stack.imgur.com/fmir3.png)
I've suggested to remove the title bar, because that kind of "callout design" is good when you want to show some content, and in order to close it, the users has just to click anywhere outside the preview area.

Cheers ;)

**Comment by ansgarbecker** [comment]
The borders of that window has shadows on my Win10:
![grafik](https://user-images.githubusercontent.com/7986591/61268556-23456d00-a79c-11e9-9b05-ad9535612bae.png)

Setting the form's `BorderStyle` to `bsNone` removes the title bar, but also its shadows, and even the possibility to resize the dialog:
![grafik](https://user-images.githubusercontent.com/7986591/61268836-0d847780-a79d-11e9-81d1-1aff183fb083.png)

Well, this is not web design...
