### ISSUE TITLE
MemSQL connection fails to show tables in database tab

### ISSUE THREAD

**Issue by stocks81** [HeidiSQL/HeidiSQL#516]
## Steps to reproduce this issue

1. connect to memsql server
2. click on + left of Database name to see tables.
3. Also happens if you click on the database name and then try and click on the tab where tables would be listed.
4. I get the attached error report.

## Current behavior

Unable to see tables in the database.

## Expected behavior

To be able to see listed tables in the database.

## Possible solution

Of the SQL commands listed in the log of commands, they all run fine so not sure what is trying to be run when those areas are being clicked on.  

## Environment

* **HeidiSQL version:** 
  10.1.0.5464
* **Database system and version:** 
  MemSQL 6.7

**Comment by ansgarbecker** [comment]
Forgot to attach the file?

Aso, I don't have a MemSQL server available, and although I just registered at memsql.com, I am not really able to quickly set up one. So if I get this fixed somehow you will have to test and report back here.

**Comment by stocks81** [comment]
[MemSQL-bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2809480/MemSQL-bugreport.txt)

**Comment by stocks81** [comment]
Yes, I can get you access to a dev setup.   lets work on how to get you access to this.

**Comment by ansgarbecker** [comment]
Please send me some read-only credentials for a MemSQL server to my email address mentioned on [my imprint](https://www.heidisql.com/imprint.php).

**Comment by stocks81** [comment]
It has been sent, thank you.

Josh

**Comment by ansgarbecker** [comment]
Got them, thanks!

Do you know on what MySQL or MariaDB version MemSQL is based on? Could be a bit older, or?

**Comment by ansgarbecker** [comment]
Next build should run without errors when retrieving tables.

You could be so nice and help testing whether there are more things to fix for MemSQL.

**Comment by stocks81** [comment]
Looks Great!  Thank you for all the work on getting this added in.

So far the only other then thing that I have found is when I tried to edit a data in a column in data view.

UPDATE `DB`.`Table` SET `Done`='2' WHERE  `Year`=2019 AND `Month`='02' AND `Day`='15' AND `Done`=0 LIMIT 1;
/* SQL Error (1749): Feature 'UPDATE...LIMIT must be constrained to a single partition' is not supported by MemSQL Distributed. */

I was able to run it with out the limit just fine.  I will test with a table that has a primary key to make sure that it happens only in this case.

Again Thank you,
Josh

**Comment by ansgarbecker** [comment]
Josh, could you test whether you get that `UPDATE...LIMIT` error also on tables with primary keys?

**Comment by ansgarbecker** [comment]
I'm closing this issue now, as I already fixed the actual problem in the database tab.

For that LIMIT problem, please give feedback whether it works on tables with primary keys. If yes, there should be no change in HeidiSQL, maybe apart from a warning message, saying we can't update because LIMIT is unsupported by MemSQL.
