### ISSUE TITLE
Crash when connecting to unavailable ms sql database

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#517]
## Steps to reproduce this issue

1. Select an unavailable ms sql connexion
2. Double click on it
3. Then I get a crash

## Current behavior

![image](https://user-images.githubusercontent.com/3911428/51929204-a416d500-23c5-11e9-8b1d-2ceba2ed49a3.png)

## Expected behavior

A nice cannot connect popup.

## Environment

* **HeidiSQL version:** 
  
10.1.x
* **Operating system:** 
  
Windows 10 x64

**Comment by sirber** [comment]
Same for bad login, I get a crash.

**Comment by ilpssun** [comment]
Yep, if you enter the wrong credentials (e.g. wrong password), I get the same crash on my Heidi 10.1 connecting to MSSQL.

**Comment by matthttam** [comment]
Can confirm that even with correct credentials but using a non-existent database this crash will occur.

**Comment by ansgarbecker** [comment]
Seems the thrown exception changed as I switched the OLEDB driver for MSSQL. Just fixed that.

**Comment by ilpssun** [comment]
For me, this is fixed in 10.1.0.5489 (“nightly” build as of March 7, 2019).
