### ISSUE TITLE
SOLVED PREMISSION PROBLEM can't switch tabs inside procedures

### ISSUE THREAD

**Issue by alezm00** [HeidiSQL/HeidiSQL#518]
## Steps to reproduce this issue

1. Connect to a database.
2. Select a procedure;
3. cannot switch trought tabs or make any interraction inside it;

## Current behavior

cannot switch trought tabs or make any interraction inside it;
![ezgif-4-1575d1b74813](https://user-images.githubusercontent.com/31077802/51931799-fecc2300-23fd-11e9-8a11-c2bdf0ca3c47.gif)

## Environment

* **HeidiSQL version:**  10.1.0.5464
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
So this issue is solved somehow due to a permission problem or what does that mean?
