### ISSUE TITLE
Access Violation after remove of sort column

### ISSUE THREAD

**Issue by lubber-de** [HeidiSQL/HeidiSQL#520]
## Steps to reproduce this issue

1. Step 1; Connected to a PerconaDB Instance
2. Step 2: Open some table
3. Step 3: Sort by 2 columns via "Sort-Button" in the menubar
4. Step 3: Remove 1 sort column via "Sort-Button" in the menubar

## Current behavior
Access Violation. See attached bugreport.txt

## Expected behavior

Resort the table

## Environment
* **HeidiSQL version:** 
10.1.0.5471

* **Database system and version:** 
 Percona 5.6.26

* **Operating system:** 
 Win 10 x64

## Bugreport
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2813237/bugreport.txt)

**Comment by fifonik** [comment]
Are you talking about "Sorting" dropdown on Data tab?
I played with the sorting dropdown but was not able to re-produce the issue. Works fine. Sorting by clicking on headers works fine as well.

**Comment by lubber-de** [comment]
Yes, it happened on the sorting dropdown in the data tab.

**Comment by jweultjes** [comment]
Very same issue on version 10.1.0.5481

1. Click on a header to sort.
2. Open the sorting dropdown and remove a sorting option.
3. Access Violation pops up.

I can continue using the application and the sorting option is removed from the sorting dropdown. I have also attached a bugreport

## Bugreport
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2880566/bugreport.txt)

**Comment by ansgarbecker** [comment]
Your both bug reports have a similar but unequal callstack. The one crashed here:
`006a86ca heidisql.exe Vcl.Controls          TWinControl.WndProc`
... while the other one did it here:
`0040e853 heidisql.exe System                GetDynaMethod`
... which is 6 steps further.

But I guess @jweultjes already clicked on the "continue" button several times.

However, that crash lies deep within the VCL sources, which makes it nearly impossible for me to fix.

Is there at least some way to reliably reproduce the crash?

**Comment by fifonik** [comment]
I was able to re-produce the issue when I changed theme from Windows to Turquose Gray and started to play with the Sorting dropdown (I opened the dropdown a few times and each time made some changes by adding/removing columns). Got the crash.

The issue gone when I switched back to Windows theme.

Hope this help.

P.S. I believe Reset & Add Col buttons in the dropdown should be on top. Otherwise it is hard to add multiple columns as while you just clicked Add Col button it went down and you have to move mouse to target it again. Not a big deal as I never use the dropdown in real life.

**Comment by ansgarbecker** [comment]
Ok, so this is one more theme related bug. Sigh...

**Comment by fifonik** [comment]
Sorry for that. I'm just a messenger :)

**Comment by jweultjes** [comment]
Ah yes, I was working on the material theme. On the Windows theme it hasn't crashed so far.

**Comment by JulianRaya** [comment]
The crash happens regardless of the theme. It is not a theme issue.

To reproduce, you have to remove ALL of the sort filters by clicking the Xs in the dropdown menu. You will see the crash only when you remove the final sort filter. All the other filters will not cause problems. It's only the last one that has trouble. This will reliably reproduce the issue.
 
I suppose its worth mentioning that removing the filters by clicking the headers works fine.

**Comment by michael-coffey** [comment]
Will this issue ever be fixed?

**Comment by nem8** [comment]
I can confirm that this issue has nothing to do with themes (as far as i can see).
It is consistently happening when you remove all sorting filters.

Extremely inconvenient. I have finally started to remember this, but when it is fixed i have to learn that its OK to remove all again..

**Comment by ansgarbecker** [comment]
For me this only crashes if I selected a theme other than the default "Windows" theme. So this is still relevant.

**Comment by ansgarbecker** [comment]
Just retested with v12.0 - still crashing when removing the last sort column with a non-default theme.

**Comment by ansgarbecker** [comment]
... and still crashing after the latest compiler updates.

**Comment by Delphichem** [comment]
Change the btnDelete  from TButton to TSpeedButton fix the issue.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build, with the refresh done via timer, not directly per button-click event. I recalled it's causing crashes often when you destroy a button in its own button-click event.
