### ISSUE TITLE
Crash when trying to delete a row

### ISSUE THREAD

**Issue by robsch** [HeidiSQL/HeidiSQL#524]
## Steps to reproduce this issue

Open the data view of an InnoDB table. Select a row, right click on it and try to delete the row.

## Current behavior

Error dialog will be shown.

## Expected behavior

Deleting of the row.

## Possible solution

No idea. 

## Environment

Fedora 29 in a virtual machine. 

```
date/time          : 2019-02-01, 12:17:20, 719ms
computer name      : localhost
user name          : colop01 <admin>
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : German
system up time     : 16 hours 52 minutes
program up time    : 28 seconds
processors         : 4x Intel(R) Pentium(R) 4 CPU 2.40GHz
physical memory    : 3157/5935 MB (free/total)
free disk space    : (C:) 82,81 GB
display mode       : 2560x1380, 32 bit
process id         : $2a
allocated memory   : 42,58 MB
largest free block : 130809,89 GB
executable         : heidisql.exe
exec. date/time    : 2019-01-26 07:17
version            : 10.1.0.5464
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $82ddc7dc, $61aace05, $61aace05
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 00007FBFFB90E729 in module 'comctl32.dll'. Read of address 0000000000000008.

main thread ($2b):
7fbffb90 comctl32.dll
00c7a1c8 heidisql.exe Vcl.Styles.Utils.SysStyleHook  579  +1 TSysStyleHook.CallDefaultProc
00c7be65 heidisql.exe Vcl.Styles.Utils.SysStyleHook 1254 +99 TSysStyleHook.WndProc
00d201d8 heidisql.exe Vcl.Styles.Utils.Forms        2591 +78 TSysScrollingStyleHook.WndProc
00d1cc7f heidisql.exe Vcl.Styles.Utils.Forms        1327 +46 TSysDialogStyleHook.WndProc
0055c293 heidisql.exe System.Classes                         StdWndProc
004a4088 heidisql.exe Winapi.CommCtrl                        TaskDialogIndirect
00772891 heidisql.exe Vcl.Dialogs                            TCustomTaskDialog.DoExecute
00772d68 heidisql.exe Vcl.Dialogs                            TCustomTaskDialog.Execute
00772d2f heidisql.exe Vcl.Dialogs                            TCustomTaskDialog.Execute
009d0b9b heidisql.exe apphelpers                    2565 +80 MessageDialog
009d0159 heidisql.exe apphelpers                    2451  +1 MessageDialog
00d9dac7 heidisql.exe Main                          3797  +8 TMainForm.actDataDeleteExecute
0055ae20 heidisql.exe System.Classes                         TBasicAction.Execute
00676085 heidisql.exe Vcl.ActnList                           TCustomAction.Execute
0055ab14 heidisql.exe System.Classes                         TBasicActionLink.Execute
008249e7 heidisql.exe Vcl.Menus                              TMenuItem.Click
008271de heidisql.exe Vcl.Menus                              TMenu.DispatchCommand
00829505 heidisql.exe Vcl.Menus                              TPopupList.WndProc
00829405 heidisql.exe Vcl.Menus                              TPopupList.MainWndProc
0055c293 heidisql.exe System.Classes                         StdWndProc
0084e07e heidisql.exe Vcl.Forms                              TApplication.ProcessMessage
0084e0f3 heidisql.exe Vcl.Forms                              TApplication.HandleMessage
0084e541 heidisql.exe Vcl.Forms                              TApplication.Run
00dd74ba heidisql.exe heidisql                        85 +26 initialization
```
This is just one problem. Errors happen with the new version 10.1 at different places. Did not have those problems with version 9.5. May have something to do with the UI?

**Comment by ansgarbecker** [comment]
Your callstack tells me this is related to the theme you have selected.

I suppose the default "Windows" theme does not crash. Probably other themes too. Which one did you select?

**Comment by robsch** [comment]
You're right. Didn't know, that 'Windows' is the _old_ theme. I tried different themes, like 'Material', but I think with all others I get this exception. 

With the 'Windows' theme I don't have to go back to the older version. Is there another theme that I should try for your information?

**Comment by robsch** [comment]
`wine --version` outputs **wine-4.0 (Staging)**

**Comment by ansgarbecker** [comment]
"Windows" is the default one, all others are customized themes, and will most likely have the same issues on Wine. I suppose it'd be a good idea to disable all themes when running on Wine, as this seems highly unstable. What do you think?

**Comment by robsch** [comment]
Might be that others don't have any problems, so I wouldn't disable them in general (could also depend on the compability setting?). A hint in the settings dialog and the installer would be sufficient, in my opinion. Not a nice thing... but I guess most users appreciate that it can be used with wine at all, since HeidiSQL is a great tool and they understand that you cannot consider all environments. You could make the 'Windows' option the first entry in the dropdown to make clear it works different than the others. Something like that...

**Comment by ansgarbecker** [comment]
There's a chance this is fixed now, as one other theme related issue also looks fixed, with the latest build.

**Comment by ansgarbecker** [comment]
Please shout if issue is still reproducible with v12.0
