### ISSUE TITLE
v10 SSL connection unexpected or badly formatted

### ISSUE THREAD

**Issue by Eldair** [HeidiSQL/HeidiSQL#529]
## Steps to reproduce this issue

1. Try to connect to a database via SSL (works in latest v9)

## Current behavior

SSL connection error: The message received was unexpected or badly formatted.

## Expected behavior

Connect to the database

## Environment

Using heidi on windows 10

* **HeidiSQL version: 10.1.0.5474** 
* **Database system and version: 8.0.13**

**Comment by ansgarbecker** [comment]
Can you please look at #215 and close this here as a duplicate if the issue is the same.

**Comment by Eldair** [comment]
Hi, yes, it seems to be the same issue
