### ISSUE TITLE
Virtual columns on "duplicate row"/"export Insert,Replace" error

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#53]
## Expected behavior

When we insert/update/replace data in tables with virtual columns, we don't put this columns on the statements.

## Current behavior

Heidi places the virtual column in the insert when we use "Duplicate Row", or "Export Grid Rows" to Insert, Delete/Insert and Replace on grid.

I think its a good idea we have a option "Export virtual columns?" like "Include auto increment column", because sometime the server is not compatible with virtual columns.

### Steps to reproduce
1. create a table with virtual columns
![24537-1-capturar3](https://user-images.githubusercontent.com/11230133/34214852-cd9725ee-e58a-11e7-8236-95e471ddec98.png)
2. insert some data
3. try to duplicate the row with "Duplicate" functionality
![24537-2-capturar1](https://user-images.githubusercontent.com/11230133/34214861-d7de66fc-e58a-11e7-9fc0-f1ae9202bafa.png)
4. error log...
![24537-3-capturar2](https://user-images.githubusercontent.com/11230133/34214875-dfae7cd2-e58a-11e7-950e-854e29ac83ec.png)

### Context
* HeidiSQL version: 9.5,
* Database system + version: MySQL 5.7 and MariaDB 10.1
* Operating system: Windows 10

**Comment by ansgarbecker** [comment]
In the latest build Heidi does now not copy values when duplicating a row.

For that export dialog I'd like to solve that without another new checkbox "_include virtual columns_". Such an option would only be useful for the SQL formats, but not for the many other formats the dialog supports.

**Comment by ansgarbecker** [comment]
The grid export dialog should now also exclude virtual columns in the various SQL formats. (Not so for CSV, HTML etc.)
I just straightened the code a bit, so please have an eye on new bugs, and report these. Thanks!

**Comment by lukinhaspm** [comment]
Great @ansgarbecker , its works very good!
I'll use more to validate.
Thank you!
