### ISSUE TITLE
change delimiter ' ;; ' to  ' ; '

### ISSUE THREAD

**Issue by atmanegara** [HeidiSQL/HeidiSQL#531]
default delimiter is ' ; ' , but i'm change to ' ;; ' is work ,then  i'm change again to ' ; ' but is not work
![image](https://user-images.githubusercontent.com/9096711/52389281-a831a980-2acd-11e9-84c3-a409c5d38e03.png)

**Comment by ansgarbecker** [comment]
This is a misunderstanding. The delimiter setting is used for splitting your commands in the query editor. The Log panel is read only, and just represents what was fired.
