### ISSUE TITLE
HeidiSql Crash while editing data in cell

### ISSUE THREAD

**Issue by miketubby** [HeidiSQL/HeidiSQL#532]
HeidiSQL version 10.1.0.5464
Windows 10
MariaDB

HeidiSQL crashes with an exception while editing data in the table 'data' view if you mouse click in the cell when the data is already selected.

How to produce:

1. Start HeidiSQL
2. Open a DSN
3. Select a table
4. Switch to 'data' view
5. Click on an item you wish to edit - focus on cell
6. Click again on cell to select data in cell - turns reverse (white on blue_
7. Enter a number
8. Change your mind (want to enter a different number)
9. Click the cell again (while selected)
10. I get segmentation fault/exception

Expected behaviour would be to allow the item to be edited again. The application should not segfault.

Video of behaviour here:

https://www.youtube.com/watch?v=S26PPSfpqOQ

Mike

**Comment by ansgarbecker** [comment]
I just tried to reproduce that, with no luck. Please attach the bugreport.txt from the crash dialog here.

**Comment by edvanleeuwen** [comment]
I seem to have the same problem. Bugreport attached.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2876983/bugreport.txt)

**Comment by ansgarbecker** [comment]
While this might be related to a [forum thread from Oct 2018](https://www.heidisql.com/forum.php?t=25418#p25767), I still cannot reproduce it with v10.1 and the latest builds.

If anyone is able to reproduce this with the latest build, please attach the bug report here, so I can check them.
