### ISSUE TITLE
Crash when trying to select a partially hidden column checkbox in register "Data"

### ISSUE THREAD

**Issue by andipfaff** [HeidiSQL/HeidiSQL#534]
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2848879/bugreport.txt)
![picture1](https://user-images.githubusercontent.com/4201912/52534068-ec76b100-2d3c-11e9-89e9-1892652bb1d2.png)
![picture2](https://user-images.githubusercontent.com/4201912/52534070-f00a3800-2d3c-11e9-8b60-a2b2655ca55b.png)

## Steps to reproduce this issue

choose a table with many columns (at least 15),
click on the register "Data"
click on "Columns" to select which columns should be displayed in the grid
click on the lowest element which must already be partially invisible (see screenshot)
Heidi crahes. I am using 10.1.0.5478 but this behaviour is old

Best regards
Andi

**Comment by ansgarbecker** [comment]
Somehow I cannot reproduce that. However, I'll try to fix this blindly, so you will have to check.

Relevant part of the callstack:
```

exception class    : EStringListError
exception message  : List index out of bounds (-1).

main thread ($2210):
006cf010 heidisql.exe   Vcl.StdCtrls             .TListBoxStrings
7fefd6eb KERNELBASE.dll                          RaiseException
004107cd heidisql.exe   System                   @RaiseAtExcept
0053a45c heidisql.exe   System.Classes           TStrings.Error
0053c9e4 heidisql.exe   System.Classes           TStringList.Delete
00d2ddec heidisql.exe   column_selection 161  +6 TColumnSelectionForm.chklistColumnsClickCheck
```

**Comment by andipfaff** [comment]
It seems that you first have to disable some fields, than restart Heidi, display the grid again and then deactivate the lowest field.

**Comment by andipfaff** [comment]
Found a way to reproduce it: disable ALL fields first, then enable the lowest.

**Comment by andipfaff** [comment]
Thank you! This problem is solved but now if you click on this partially hidden checkbox in the list, HeidiSQL will mark the next one instead of the one I have clicked.
