### ISSUE TITLE
Can't close tabs

### ISSUE THREAD

**Issue by coeko50** [HeidiSQL/HeidiSQL#536]
## Steps to reproduce this issue

1. Step 1;  double click on a table in the table list, table will open in new tab
2. Step 2; right click on the tab to get drop down menu
3. Step 3; close open is greyed out
4. Then I get...

## Current behavior

close tab option is greyed out 

## Expected behavior

close option to be valid

## Environment

* **HeidiSQL version:** 
10.1.0.5749
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
That menu item is labelled "Close query tab", while the "Data" tab is not a query tab. You cannot close the Data tab - that's intentionally.

**Comment by id0612** [comment]
He's talking about the Query TAB

Check the “Reopen previously used SQL files and unsaved content in tabs”，After each boot, the previously used files are reopened. The first one won't close. There is always one that cannot be closed.


![image](https://user-images.githubusercontent.com/2449459/56492025-0bec4000-651d-11e9-8516-fe13b944e2a8.png)
![image](https://user-images.githubusercontent.com/2449459/56492073-2aead200-651d-11e9-8378-966be50a0ece.png)
![image](https://user-images.githubusercontent.com/2449459/56492086-3ccc7500-651d-11e9-9ad5-1c0e9c51e640.png)
