### ISSUE TITLE
Chocolatey package not up to date

### ISSUE THREAD

**Issue by connerbw** [HeidiSQL/HeidiSQL#537]
## Steps to reproduce this issue

1. Install choco: https://chocolatey.org
2. `choco install heidisql` (or `choco upgrade heidisql`)

## Current behavior

HeidiSQL 9.5

## Expected behavior

Latest version of HeidiSQL

## Possible solution

Update https://chocolatey.org/packages/HeidiSQL please?

+ https://chocolatey.org/docs/package-triage-process
+ https://chocolatey.org/packages/HeidiSQL/ContactOwners

**Comment by insanityinside** [comment]
Updated, should be live soon.

**Comment by connerbw** [comment]
Resolved. Thanks!
