### ISSUE TITLE
Why can't the new version choose Chinese?

### ISSUE THREAD

**Issue by liupeng328** [HeidiSQL/HeidiSQL#539]
新版本不能选择中文简体？默认英文？

**Comment by ansgarbecker** [comment]
I'm not sure why Chinese is sorted onto the end of the language list, but there are even two in v10.1: traditional and simplified

![grafik](https://user-images.githubusercontent.com/7986591/52900645-99977080-31f8-11e9-936e-0f625bf376e5.png)

**Comment by liupeng328** [comment]
Thanks very much
Problem solved

In addition, make a suggestion:

Can you open multiple tab pages at the same time to operate two tables at the same time?
It's not very convenient to operate two tables at the same time. Would you consider adding this function? Okami

My English is not good，so again by chinese：


非常感谢，问题解决了，另外，提一个建议：
能不能同时打开多个tab页，方便同时操作两张表
![image](https://user-images.githubusercontent.com/19989280/52910861-9673b180-32d8-11e9-8f11-14c174eab3b9.png)

**Comment by GitHubAdminis** [comment]
I hope I can edit multiple tables at the same time, instead of only one table at the same time.
希望能同时编辑多张表, 而不是同时只能操作一张表
