### ISSUE TITLE
undo is broken

### ISSUE THREAD

**Issue by datacubed** [HeidiSQL/HeidiSQL#541]
## Steps to reproduce this issue

Example One
Step 1
Write the following SQL:
SELECT 1;

Step 2:
Press "ctrl+z".

Example Two:
Step 1:
Write the following SQL:
SELECT 1;
SELECT 2;
SELECT 3:

Step 2:
Run

Step 3:
Press "ctrl+z" to undo.

Write a couple different lines of SQL, then press 

## Current behavior
Example One:
Undo removes "SELECT" and ";" while leaving the "1":
SELECT 1;
> undo
1

Example Two:
Undo only behaves on the last sql statement. So I have 3 queries in the window, but only the last one is acted on - however it behaves exactly the same as Example One:
SELECT 1;
SELECT 2;
SELECT 3;
> undo
SELECT 1;
SELECT 2;
 3

## Expected behavior

In both Examples:
Undo should remove the last character first, and continue until the Text Field is empty.

## Environment

* **HeidiSQL version:** 
10.1.0.5464

* **Database system and version:** 
5.5.61

* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
I suppose that the auto-uppercase feature breaks the undo history in the SynEdit's.
Can you please verifiy that, by disabling it in Preferences > SQL > "Auto uppercase reserved words and functions".

**Comment by fifonik** [comment]
I'm not OP, but looks like the auto uppercasing option messing up the undo. 
When switched of everything looks OK.

**Comment by rentalhost** [comment]
I could confirm. The auto uppercase brokes undo.

**Comment by datacubed** [comment]
Hey all,
I had assumed this was fixed - but turns out I had also turned off "auto uppercase".
So I would say this is the issue causing Undo to behave oddly - as seen by others here.

**Comment by ansgarbecker** [comment]
Should hopefully and finally be fixed in the upcoming nightly build.

Also supports auto-fixing wrong written case of known database objects.

**Comment by ansgarbecker** [comment]
![auto-uppercase-undo](https://user-images.githubusercontent.com/7986591/65271063-b7291180-db1c-11e9-93be-3fad1374dcff.gif)

**Comment by tomasvanrijsse** [comment]
I've still got issues when I'm using CTRL-Z to undo my deletes.
You can see that after each undo the auto-uppercase is triggered, which seems unnecessary when going back in history.

![CTRL-Z-error](https://user-images.githubusercontent.com/1403466/81401157-07e28e80-912f-11ea-91c5-1dcd01111751.gif)

**Comment by ansgarbecker** [comment]
Cannot reproduce that here, with a similar query. Could you please update to the latest build, try again and file a new issue if that is still reproducible?

**Comment by ReBae** [comment]
@ansgarbecker, would you have any update on this? This is still a BIG sore point. **Ctrl +Z**-ing ends up deleting code that **Ctrl + Y** doesn't restore! In fact there are no UNDO, REDO menu buttons itself! v 11.2.0.6213,

**Comment by SamKur** [comment]
Yes, pls give a fix . Using latest v12.4.0.665
