### ISSUE TITLE
Table tools, search of text not working on postgres

### ISSUE THREAD

**Issue by juanlugil** [HeidiSQL/HeidiSQL#543]
## Steps to reproduce this issue

1. Step 1; Open table tools
2. Step 2; Search of text
3. Step 3; Checkbox selecting table
4. Step 4; Type text to search and tipye of column
5. Then I get...  Message with Skipped Table does'nt have columns with the choosen type.

## Current behavior

Search of text is not getting to work.

## Expected behavior

Get the registers where the text I am looking for is stored.

## Environment

* **HeidiSQL version:** 
10.1.0.5479
PostgreSQL 9.1.20 on i686-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 32-bit
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : Spanish
system up time     : 6 hours 17 minutes
program up time    : 1 hour 50 minutes
processors         : 4x Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz
physical memory    : 11250/16297 MB (free/total)
free disk space    : (C:) 64,79 GB
display mode       : 1920x1200, 32 bit
process id         : $660
allocated memory   : 155,26 MB
largest free block : 8181,38 GB
executable         : heidisql.exe
exec. date/time    : 2019-02-10 14:53
version            : 10.1.0.5479
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0

**Comment by ansgarbecker** [comment]
Yes, that's intentionally when the selected data type group is not in the table:

![grafik](https://user-images.githubusercontent.com/7986591/53037776-6284c180-347b-11e9-8651-ad51367adde5.png)

If you select "All data types" you should definitely get results. Do you?

**Comment by ansgarbecker** [comment]
Ok, in that case there may be a bug regarding column types in PostgreSQL.

Or, also possible - that translated text from the dropdown is compared with a non-translated string and fails. You could check if that works after switching to English in Tools > Preferences > General (plus restart)

**Comment by juanlugil** [comment]
Same error with english interface.

![heidi_find](https://user-images.githubusercontent.com/46778105/53096213-eba10480-351e-11e9-9899-fd55d76a9147.jpg)

**Comment by ansgarbecker** [comment]
Ok, got it. There was a semicolon in a switch/case block, leading to an unwanted "else" block, effectively disabling the SQL code generation in Postgres mode.
