### ISSUE TITLE
SSL connection error: ASN1 bad tag value met on v10.1

### ISSUE THREAD

**Issue by Gutza** [HeidiSQL/HeidiSQL#545]
## Steps to reproduce this issue
1. Step 1; Generate certs per https://serverfault.com/questions/783861/enabling-ssl-in-mysql-when-using-windows-as-a-server-and-client#784040

2. Step 2; Attempt connecting to the server

## Current behavior
Error message: SSL connection error: ASN1 bad tag value met.

## Expected behavior
Successful connection.

## Possible solution
Attempted to use libmysql.dll from MariaDB with no success.

## Environment

* **HeidiSQL version:** 
10.1.0.5464 (nightly version currently at 5484).

* **Database system and version:** 
10.3.12-MariaDB

* **Operating system:** 
Windows Server

**Comment by spajak** [comment]
I can confirm this bug: ASN1 bad tag value met

**HeidiSQL version**: 10.1.0.5464
**Database**:  MySQL 8.0.16

MySQL Workbench works well with same cert/key

**Comment by JustAShoeMaker** [comment]
Seeing this as well, 10.1.05560

Seems similar to https://github.com/HeidiSQL/HeidiSQL/issues/4

Have tried every permutation of certs and keys (since they aren't all required) and all self-signed.

**Comment by ansgarbecker** [comment]
I pushed 51da7c8efc890ebdb394dfa53f911b64223a53e8 yesterday, which now allows all TLS versions up to v1.3. Probably that helps here.

**Comment by ansgarbecker** [comment]
Please shout if still present with v12.0

**Comment by gnd** [comment]
Hello i am experiencing this issue with v12.3.0.x
