### ISSUE TITLE
v10.1 freezes where v9.5 is super fast

### ISSUE THREAD

**Issue by paulvi** [HeidiSQL/HeidiSQL#548]
HeidiSQL has been the fastest GUI tool.

## Steps to reproduce this issue

1. Install v10.1 on Windows 10  
2. Open databases with images in a table row of size 3 to 40 MB  
3. Then I get window is unresponsive, CPU is 25% used (1 core used 100%) for 2-3 and more minutes;
data is refreshed 1 row in few (3-5) second, so it is like animation of getting data from db.

## Current behavior

Once: No responce, no shown data after 2-3 minutes.  
Once: Animation: showing data at speed 1 row in 3-5 seconds, CPU high.

## Expected behavior

 v9.5 installed works super fast on the same PC

## Possible solution

regression, needs to know what actually was changes in 10.1 related to fetching table data that has images in BLOB

## Environment

* **HeidiSQL version:**  10.1
  
* **Database system and version:** 
MySQL 5.7 
  
* **Operating system:** 
Windows 10

**Comment by carloselectro** [comment]
Version 10 is indeed really slow compared to 9.5  with BLOB (WAV in my case), a table will only a few rows of data with BLOB is making it unusable.

**Comment by ansgarbecker** [comment]
This could have been introduced by 2f2e21b30042239437be259cd9db343c78625581 or a7c0883e9ac81bb62fcc517e95dfd9c57342bec5, see issue #422 and #429.

**Comment by paulvi** [comment]
#422 and #429 are both issues raised by me, but they are both related to Image Preview view, that is not visible by default in v10.1 and v9.5.

I second @carloselectro as the issues is definitely BLOB related.

I had to downgrade to v9.5 and warn colleagues not to upgrade.

2f2e21b30042239437be259cd9db343c78625581  has check for what button is pressed

```pascal
    if SendingControl = btnPreviewCopy then begin
      imgPreview.Picture.SaveToClipBoardFormat(ClpFormat, ClpData, APalette);
      if (imgPreview.Picture.Graphic <> nil)
```

a7c0883e9ac81bb62fcc517e95dfd9c57342bec5 is similar for only has changes for Image Preview

While what I saw, is was very slow showing row of data in table view.

If there is logic to call Image Preview refresh after drawing each line in the table, that is just wrong.  
I think, table should fully display query data, then other views should be refreshed depending on current line within the table.

**Comment by ansgarbecker** [comment]
One reason for that slowness is definitely 651b485af375d53dfed9627ea1dc57777699d055, which I am going to revert partially now. That will make the grid load the first 256 bytes from BLOBs, and load the rest when a row gets focus. Currently, the grid loads the entire BLOB contents of all visible rows into the grid, with a dumb `SELECT * FROM mytable` .

**Comment by ansgarbecker** [comment]
@paulvi please report back if the upcoming build fixes this slowness for you also. For me it works, apart from the faulty detection of not yet loaded images, but that is a different issue.

**Comment by paulvi** [comment]
Is it possible to install/try beta without affecting currently used version?

**Comment by ansgarbecker** [comment]
You can download the new build from the downloads page manually, and put it into the same folder as heidisql.exe, where the new build has the filename heidisql.xyz.exe . They should both run and not affect each other.

**Comment by paulvi** [comment]
OK, so it is trying out other build exe'cutable side-by-side with main one.

**Comment by ansgarbecker** [comment]
Could you already test if my change effectively enhanced speed?

**Comment by paulvi** [comment]
OK, just tell when there is build that has this issue fixed.

For me it means that newer version should not be worse then previous.

**Comment by ansgarbecker** [comment]
On the [downloads page](https://www.heidisql.com/download.php#nightlybuilds)

**Comment by paulvi** [comment]
OK, but there were no commits for this issue....

**Comment by ansgarbecker** [comment]
Yes, there is - the third one from top currently, build 10.1.0.5485. Watch out for the issue number 548 in the comment. I recommend downloading the very latest one.

**Comment by paulvi** [comment]
Well, latest build worked quick, but there are other regressions over v9.5 

- when showing BLOB content
- and HeidiSQL is freezing when trying Image Preview view

![image](https://user-images.githubusercontent.com/1614482/53879472-8df5d780-4049-11e9-9fb1-df23cb525777.png)

**Comment by ansgarbecker** [comment]
Weren't these mentioned in other tickets? Are they directly related to this issue about speed?

**Comment by paulvi** [comment]
well, these 2 should be other non-related  tickets for 10.x
