### ISSUE TITLE
Comment syntax, inconsistent behavior

### ISSUE THREAD

**Issue by mbomb007** [HeidiSQL/HeidiSQL#549]
## Steps to reproduce this issue

1. Paste the following query into a new query window:

```
select 1
--comment
from dual
```

## Current behavior

The syntax highlighter shows the comment as a comment, with gray and italics, but when run it throws an error "SQL Error (1054): Unknown column 'comment' in 'field list'". Adding a space after the two hyphens allows it to run fine.

## Expected behavior

The comment should be interpreted as a comment and the SQL should be executed as expected.

## Possible solution

Fix it. Otherwise, make it so the hyphens without a space after them is not marked up like a valid comment. If it's valid, run it. If not, underline it in red and don't make it gray.

## Environment

* **HeidiSQL version:** 
  Revision 5484, compiled 2019-02-20

**Comment by ansgarbecker** [comment]
Such comments have to be followed by a space. SynEdit's hightlighting does it wrong here. You can report it [there](https://github.com/SynEdit/SynEdit).

**Comment by ilpssun** [comment]
This is arguably not a bug because `--comment` without a space is valid syntax for MSSQL server.

See also https://github.com/SynEdit/SynEdit/issues/42.

**Comment by ansgarbecker** [comment]
Yes, I recall SynEdit in Heidi v9.5 was patched so it only detects the space-version as a comment. Not so in Heidi 10.x where I updated the SynEdit sources, reverting my own patch.
But if only the space version is valid for MySQL and MariaDB, and for MSSQL also the non-space-version, it's still a bug in SynEdit, isn't it? The mentioned "dialect" is set as follows in Heidi:

      case FActiveDbObj.Connection.Parameters.NetTypeGroup of
        ngMySQL:
          SynSQLSynUsed.SQLDialect := sqlMySQL;
        ngMSSQL:
          SynSQLSynUsed.SQLDialect := sqlMSSQL2K;
        ngPgSQL:
          SynSQLSynUsed.SQLDialect := sqlPostgres;

Shouldn't SynEdit disallow the space version for `sqlMySQL`?

**Comment by ilpssun** [comment]
Yep, in that case, it sounds like the MySQL dialect in SynEdit is faulty.

**Comment by ansgarbecker** [comment]
I have shed some light on this in the mentioned issue on SynEdit.

**Comment by ansgarbecker** [comment]
SynEdit/SynEdit#42 was fixed, and I just updated the SynEdit code in HeidiSQL.
