### ISSUE TITLE
Exception occured when I connect to PostgreSQL database

### ISSUE THREAD

**Issue by kitora** [HeidiSQL/HeidiSQL#55]
## Expected behavior

Open without error

## Current behavior

Error dialog popped up
I could not manage PostgreSQL database via HeidiSQL

## Failure information (for bugs)

```
version            : 9.5.0.5197
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $1a5a691c, $1f8a4a7b, $1f8a4a7b
exception number   : 4
exception class    : EConvertError
exception message  : Format '"%s" の不明なデータ型 oid #%d です。%s にフォ' invalid or incompatible with argument.

main thread ($41c4):
0047305d heidisql.exe System.SysUtils            ConvertErrorFmt
0047701c heidisql.exe System.SysUtils            FormatError
00478015 heidisql.exe System.SysUtils            WideFormatBuf
00477080 heidisql.exe System.SysUtils            FormatBuf
004772cd heidisql.exe System.SysUtils            FmtStr
00477205 heidisql.exe System.SysUtils            Format
004771d7 heidisql.exe System.SysUtils            Format
0097e0ee heidisql.exe helpers          2638   +2 f_
00a8c9bb heidisql.exe dbconnection     1547  +17 TDBConnection.GetDatatypeByNativeType
00ab29ca heidisql.exe dbconnection     5689  +42 TPGQuery.Execute
00aa038b heidisql.exe dbconnection     3471  +20 TDBConnection.GetResults
00aaa2a8 heidisql.exe dbconnection     4641  +14 TPgConnection.FetchDbObjects
00aa6437 heidisql.exe dbconnection     4357  +22 TDBConnection.GetDBObjects
00c6b5ab heidisql.exe Main             7894  +24 TMainForm.DBtreeInitChildren
008e261f heidisql.exe VirtualTrees    20178   +3 TBaseVirtualTree.DoInitChildren
008e89ad heidisql.exe VirtualTrees    22620   +4 TBaseVirtualTree.InitChildren
008fed89 heidisql.exe VirtualTrees    31903 +128 TBaseVirtualTree.ToggleNode
008e747b heidisql.exe VirtualTrees    22169  +68 TBaseVirtualTree.HandleMouseDblClick
008dbcd5 heidisql.exe VirtualTrees    17161   +6 TBaseVirtualTree.WMLButtonDblClk
0040cb1e heidisql.exe System                     TObject.Dispatch
008ef388 heidisql.exe VirtualTrees    25260  +19 TBaseVirtualTree.WndProc
0069b48a heidisql.exe Vcl.Controls               TWinControl.MainWndProc
005dbdc3 heidisql.exe System.Classes             StdWndProc
7ffb1457 USER32.dll                              DispatchMessageW
0081469f heidisql.exe Vcl.Forms                  TApplication.ProcessMessage
00814713 heidisql.exe Vcl.Forms                  TApplication.HandleMessage
00814bff heidisql.exe Vcl.Forms                  TApplication.Run
00ca08d7 heidisql.exe heidisql           80  +24 initialization
7ffb1447 KERNEL32.DLL                            BaseThreadInitThunk
7ffb1479 ntdll.dll                               RtlUserThreadStart
```

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. Start HeidiSQL
2. Select PostgreSQL connection on session manager dialog
3. push "Open"
4. Error dialog pop-up

### Context

* HeidiSQL version: 9.5.0.5197
* Database system + version: PostgreSQL 9.6 , 10
* Operating system: Windows 10 Pro x64

**Comment by ansgarbecker** [comment]
This looks like an error in the Japanese app translation. I'll go and write the translator a message. Or even better, I could introduce numeric indexes for placeholders in translation strings, so these are not mixed up (%d and %s have the wrong order here:
> "%s" の不明なデータ型 oid #%d です。%s にフォールバックします。.
> Unknown datatype oid #%d for "%s". Fall back to %s.

**Comment by ansgarbecker** [comment]
As a workaround in the meantime, you can switch to English or whatever you can read. Just click "More" on the session manager dialog, then click "Preferences", then select a language on the "General" tab.

**Comment by ansgarbecker** [comment]
I just introduced argument indexes for the Format() function in Delphi, so a translation string can specify the index of a placeholder argument in a language where the grammar dictates a different order as in English. The new nightly build will have this particular string untranslated, but should not crash any longer. A new translation is coming from the Japanese translator in the future I guess.

**Comment by kitora** [comment]
Thank you I confirmed this was fixed on r5200!
