### ISSUE TITLE
If updating fails you receive no information

### ISSUE THREAD

**Issue by zbee** [HeidiSQL/HeidiSQL#550]
## Steps to reproduce this issue

1. Have a version of HeidiSQL that is out of date
2. Attempt to update (without run privileges for `AppData/Local/Temp`)
3. Update fails
4. Restart to make sure
5. Same version as before, update definitely failed, but you were not told

## Current behavior
Attempting to update without full rights to do so gives you no indication of failure.

## Expected behavior
You get a pop-up saying the update failed.

## Possible solution
Show an error dialog, at least.

Optimally, unpack somewhere other than AppData/?/Temp/? assuming that is what is being used. IT Manager said that that folder is blocked in-domain.

## Environment

* **HeidiSQL version:** 
  10.1.0.5464
* **Operating system:** 
  Windows 10 Pro (1809)

**Comment by ansgarbecker** [comment]
What's your suggestion then where to unpack the new file, if your own AppData folder is non-writable for HeidiSQL? I wonder if you even can store session log files, and snippet files?

**Comment by zbee** [comment]
The problem in my particular case (which is apparently relatively common?) is that `AppData/Local/Temp` is blocked from executing anything. And that temp folder doesn't have the same advantage of `/tmp` of being cleared continuously, it's only when almost manually done by the user. So there is the rest of `AppData` available that will have the same advantage of being out of the way and stored with user data, but also that at least a few additional users will be able to update and logs won't get accidentally deleted.

**Comment by ansgarbecker** [comment]
Yes, a message box saying something like "update failed - could not move heidisql.exe to xyz" feels reasonable. I wonder why there is no message yet.

**Comment by zbee** [comment]
The updater also works if the updater executable resides in `/Program Files/` alongside the other program files instead of in `/AppData/Local/Temp`. I think this would actually be a reasonable change, and would fix the issue.

**Comment by ansgarbecker** [comment]
That would not work in most cases, as most users don't run Heidi with admin privileges, which you need for writing into `C:\Program Files\`. That would require to raise the privileges of the running heidisql.exe process, as this is responsible for the download into that folder. The later extracted updater.exe is started with admin privileges but not so HeidiSQL itself.

**Comment by zbee** [comment]
Wouldn't it be the exact same process though? Just an update to put the updater executable in `/Program Files/`, and then the updater would be started with admin privileges all the same. The updated `HeidiSQL.exe` could still be downloaded to `/AppData/Local/Temp` and the updater could move it as it does now, but there would be no executing from the temp folder.

**Comment by ansgarbecker** [comment]
You already need admin privileges to store the updater.exe in `/Program Files/...`. HeidiSQL has the updater as a resource inside the heidisql.exe, and extracts it when you click the build update button.

However, is there anything which changed here in the last release? I guess not but did you try it again lately?

**Comment by zbee** [comment]
I am no longer in that IT environment so I do not believe I could reliably re-test.
