### ISSUE TITLE
Feature request: run current query by default

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#552]
Currently the default is trun all query. but in a day to day scenario, running the current query is more usefull as default. Could it be the default or be configurable?

Thank you!

**Comment by ansgarbecker** [comment]
You can already define their shortcuts. F9 is by default "Run all", but you can easily assign it to whatever you want.

Please use the bugtracker for bugs and requests, not for discussions.

**Comment by sirber** [comment]
it was a originaly request, not a discussion, as I didn't know it was possible to change shortcuts.
thank you!
