### ISSUE TITLE
Text labels for Toolbar, Enhancement

### ISSUE THREAD

**Issue by jabcreations** [HeidiSQL/HeidiSQL#553]
## Current behavior

The toolbars do not have text labels (at all / on the right).

## Expected behavior

The toolbars should have the ability to have text labels, at least on the right (🖫 Save). Lame, GitHub doesn't support Unicode? This would enhance usability; I have a 32" 4K screen and the buttons are super-rinky-dinky; I can and would happily afford to have every button have text to the right of each icon.

## Possible solution

Have an option for a text label to the right and below the icons (below is better for larger non-widescreen aspect ratios).

I'd tag this as an enhancement though I'm not seeing any GUI for that here.

**Comment by ansgarbecker** [comment]
Just tried that, setting `Toolbar.ShowCaptions := True`, plus setting `Button.AutoSize := True` for each button. This shows the captions by default below the icon, and uses as much space as the caption needs:

![grafik](https://user-images.githubusercontent.com/7986591/53472210-55616700-3a67-11e9-85a6-0dc55991a82c.png)

We would need an approach to have shorter captions, without making them unclear in the menu which shows the same captions.

**Comment by ansgarbecker** [comment]
Adding `Button.Style := tbsTextButton` moves their captions to the right side, and takes even more horizontal space. Please ignore the `tlbSep1` buttons - they should just be vertical lines. Both screens have 1920px width:

![grafik](https://user-images.githubusercontent.com/7986591/53472488-ff40f380-3a67-11e9-8bc5-3b2d80dfa58c.png)

Also, this breaks buttons with a dropdown menu, like the refresh button.

**Comment by jabcreations** [comment]
Where are these settings...set? A file in the installation path, AppData or the registry in example?

**Comment by ansgarbecker** [comment]
This is hardcoded - you cannot customize that. I was thinking both screens are too bad looking, so it makes no sense to let the user chose that. We need a better approach here.

**Comment by jabcreations** [comment]
Why not simply add an external file with the menu settings and fallback to internal settings if it's format is malformed or missing? I'd rather have an imperfect option than not. Plus if there is a build (I can't compile right now) I could test I'd be more than happy to go through and work on the menu's text labels and titles myself.

**Comment by ansgarbecker** [comment]
I can add a registry hack for this, until it's good enough to be presented to all users.

**Comment by jabcreations** [comment]
WOOT! That would be amazing!  I use HeidiSQL everyday I work on code and this would greatly ease the usability. I'll provide two arrays (labels and titles (presuming that the code terminology matches HTML)). Please let me know what I can help out with if anything else, when/where that build will be available for download and obviously the registry hack would be useful too please! Thank you!

**Comment by ansgarbecker** [comment]
Ok, just did that. Just update to the next nightly build and add a new registry value:

1. start regedit.exe
2. navigate to `HKEY_CURRENT_USER\Software\HeidiSQL`
3. rightclick, then click "New", then click "Dword (32bit)" value
4. name it `ToolbarShowCaptions`
5. set its value to 1 (decimal)
6. (re)start heidisql.exe

**Comment by ansgarbecker** [comment]
Please report back what you think about it, probably with suggestions on how to improve broken things.

**Comment by jabcreations** [comment]
This is implemented via the Registry, would it be easy to have the text labels and titles saved there by default too so they could be reasonably easily edited by users?

**Comment by ansgarbecker** [comment]
No, that's not a viable idea for any user. Noone wants to edit button labels himself. We definitely need a better idea here. I also have none, so we're probably stuck here.

**Comment by jabcreations** [comment]
You could make a `menu.ini` file inside of the program's directory. It's more direct, there is no digging, "regular" users could easily get in and you could implement some sort of fallback internally (if you want) for malformed options. Please keep in mind that the vast majority of users here are going to be at least moderately technical.

**Comment by ansgarbecker** [comment]
Yes, users of HeidiSQL may have technical background. But that does not mean they want to be bothered with having to modify button labels. Also that's much work for me, and only a very limited number of users will use it.
