### ISSUE TITLE
新版字段行之间太窄了，看着难受

### ISSUE THREAD

**Issue by yotoai** [HeidiSQL/HeidiSQL#557]
可以的话，麻烦您修改下
![image](https://user-images.githubusercontent.com/24404458/53611917-2e439a80-3c0b-11e9-81b1-35ec8aa91d70.png)

**Comment by WesleyM77** [comment]
Translation courtesy of Google Translate...
Title: The new version of the field line is too narrow, looking uncomfortable.
Comment: If you can, please fix it.

**Comment by ansgarbecker** [comment]
I already did that for #468 , and now increased the node height again, this time by 2 pixels.
