### ISSUE TITLE
Some toolbar icons completely grayed out

### ISSUE THREAD

**Issue by lourdas** [HeidiSQL/HeidiSQL#560]
## Steps to reproduce this issue

1. Download the latest 5487 build.
2. Start HeidiSQL
3. Some toolbar icons are missing.

## Expected behavior

All icons should appear normally.

## Environment

Linux, Wine 3.21, 64-bit using portable HeidiSQL.

* **HeidiSQL version:** 
Build 5487
* **Database system and version:** 
MariaDB 10.1
* **Operating system:** 
Linux 64-bit, Wine 3.21.

Screnshot attached.

![heidisql-no-icons](https://user-images.githubusercontent.com/397916/53816200-d6d75e80-3f6b-11e9-8477-a8c93e72268f.png)

**Comment by ansgarbecker** [comment]
These greyed out buttons are disabled on startup, and also with the database tab active. You should test whether they change if you for example go to the data tab and click a cell in it.

**Comment by lourdas** [comment]
Yes, that's the case. But having them grayed out and activating them in different occasions is pretty ugly. I don't know if this could be a Wine issue or something. Couldn't they just be blurred or something instead of being grayed out?

**Comment by ansgarbecker** [comment]
This must be a Wine issue. On Win 10 they _are_ greyed out:
![grafik](https://user-images.githubusercontent.com/7986591/53833756-9a1a6000-3f89-11e9-9771-bed8fc7c3c62.png)

Did you try to switch to Wine before 3.15 or after 4.1 ?

**Comment by lourdas** [comment]
Oh, I see. I'll try to upgrade to 4.1 or newer and see how it works out.

**Comment by lourdas** [comment]
Upgrading to 4.0 (current stable in Gentoo) unfortunately did not help. Same behaviour.

**Comment by ansgarbecker** [comment]
Forum user zootal recently found out some Wine things related to HeidiSQL: https://www.heidisql.com/forum.php?t=26556
Conclusion was to use Wine up to v3.14 or v4.2 and above, although the issue was unrelated to buttons, but who knows, I would at least give v3.14 a try.

**Comment by lourdas** [comment]
> Conclusion was to use Wine up to v3.14 or v4.2 and above, although the issue was unrelated to buttons, but who knows, I would at least give v3.14 a try.

I just launched HeidiSQL in my laptop which has wine-vanilla 3.0.3 and still the icons are grayed out. I'm in the process of upgrading to 4.4 and will report back.

**Comment by lourdas** [comment]
And same with wine 4.4...

**Comment by sirber** [comment]
Same with wine-3.6

**Comment by PriyankMotivaras** [comment]
everything work fine for me in latest wine version and i change theme in HeidiSql in linuxmint 20

**Comment by lourdas** [comment]
Revisiting this old issue, I see now that everything is fine:

![Screenshot_20240302_093140](https://github.com/HeidiSQL/HeidiSQL/assets/397916/1a566025-0fc6-44ab-a7a3-94cd9aeffd66)

Using Wine 9.0. Feel free to close this issue.

**Comment by ansgarbecker** [comment]
Thanks for your feedback!
