### ISSUE TITLE
Problem while copying table from another database

### ISSUE THREAD

**Issue by mlnlmsl** [HeidiSQL/HeidiSQL#561]
I am using HeidiSQL in laragon. 
I have a table name in server name like, "tbl_Person_Something"  and copy database from server, it automatically convert table name into small case like,"tbl_person_something". It created a conflict with old code and new code that I have written.
Is it developed like this or an issue??

**Comment by ansgarbecker** [comment]
No, this is not a feature of HeidiSQL, but I also suppose that conversion is not done by HeidiSQL itself, but by the server.

How exactly did you copy that table?
How does the SQL look like when copying that table?

**Comment by ansgarbecker** [comment]
And what does this query give you as a result?
```sql
SHOW VARIABLES LIKE 'lower_case_table_names';
```

**Comment by mlnlmsl** [comment]
`CREATE TABLE `tbl_Person_Listing`` is query in sql file. I just loaded the sql file and run it. 
I didn't look  the sql file before. and my table is tbl_person_listing`
It might be the due to server too.

**Comment by ansgarbecker** [comment]
Ok, then please also report the result of my above `SHOW` query.

**Comment by ansgarbecker** [comment]
Closing due to no feedback.

Most likely, your "lower_case_table_names" variable is set to automatically convert table names to lowercase, which you can change as you like. However, this is not directly a todo for HeidiSQL, but by yourself.
