### ISSUE TITLE
Question: How to enter (NULL) ?

### ISSUE THREAD

**Issue by paulvi** [HeidiSQL/HeidiSQL#562]
Question: when editing table manually (a-la Excel) how to enter `null` value?

Trying `(NULL)` makes it "(NULL)" string, not `(NULL)` value.

Of course there is SQL way to use `UPDATE`...

**Comment by ansgarbecker** [comment]
<kbd>Shift+Ctrl+N</kbd>, or use the context menu:

![grafik](https://user-images.githubusercontent.com/7986591/53873852-83175480-4001-11e9-909d-ebd95c9596da.png)
