### ISSUE TITLE
Question: Impossible to download build - page keep saying to disable AdBlocker

### ISSUE THREAD

**Issue by paulvi** [HeidiSQL/HeidiSQL#563]
Impossible to download buidl over page saying to disable AdBlcoker.

AdBlocker is disabled, but to google server are set non-Trusteted as they are not available in China

See https://no-google-in-china.github.io/

![image](https://user-images.githubusercontent.com/1614482/53878499-fe4f2980-4046-11e9-9263-5a1319174da3.png)

**Comment by ansgarbecker** [comment]
Please read the text in the red box - there is always a way to download. Just rightclick the link and click "Save target as..."

**Comment by paulvi** [comment]
Well, the answer answer did help me.

But the message to users is incorrect as it is not about AdBlock only.

And Chinese user without VPN (that is most of them) cannot just get anything from Google servers.

Just don't think that Google is everywhere and it is fast.
It is not.

When there are no Google server in China, google.com is slow thing.
