### ISSUE TITLE
Portable HeidiSQL just cannot run without some files

### ISSUE THREAD

**Issue by paulvi** [HeidiSQL/HeidiSQL#564]
Portable HeidiSQL just cannot run without some files

![image](https://user-images.githubusercontent.com/1614482/53879176-c3e68c00-4048-11e9-8839-9acd05ccf610.png)

**Comment by paulvi** [comment]
I know how to solve, but it should be stated on the web site.

**Comment by ansgarbecker** [comment]
As stated on the download page:
> Just download and overwrite your existing C:\Program Files\HeidiSQL\heidisql.exe

You downloaded a build executable, not the portable package, by the way.

**Comment by paulvi** [comment]
Indeed
