### ISSUE TITLE
Does not show the table

### ISSUE THREAD

**Issue by mmkulikov** [HeidiSQL/HeidiSQL#565]
Windows 10
Does not show a table in the list. Although it works without problems
**select * from oms30.User**
In INNODB_SYS_TABLES there is a table

**Comment by ansgarbecker** [comment]
Please check the favorites button, the one with a yellow star on it, right besides the table filter.

**Comment by mmkulikov** [comment]
It's not about the filters. The table is also not visible in the console (SHOW TABLES;). But direct calls to the table work.

**Comment by ansgarbecker** [comment]
Ok, then how is the CREATE code for that table? Perhaps I can tell you more if I see it. Or the table is broken somehow, and needs to be repaired with `OPTIMIZE TABLE oms30.User`.

**Comment by mmkulikov** [comment]
Optimization did not help.
>>Table does not support optimize, doing recreate + analyze instead
The table itself is working. Since is used in the system and users successfully work and log in.

**Comment by ansgarbecker** [comment]
What about the CREATE code for it?
`SHOW CREATE TABLE User` will show it.

**Comment by mmkulikov** [comment]
-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.6.43 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.1.0.5487
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table oms30.User
DROP TABLE IF EXISTS `User`;
CREATE TABLE IF NOT EXISTS `User` (
  `UserID` int(11) NOT NULL AUTO_INCREMENT,
  `OldID` int(11) DEFAULT NULL,
  `UserEnabled` tinyint(1) NOT NULL,
  `Login` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `Password` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Created` datetime NOT NULL,
  `Email` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `CompID` int(11) DEFAULT NULL,
  `OfficeID` int(11) DEFAULT NULL,
  `Name` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `Surname` varchar(32) COLLATE utf8_unicode_ci NOT NULL,
  `Timezone` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `PasswordActivated` tinyint(1) NOT NULL,
  `Position` varchar(100) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PhoneMobile` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PhoneOffice` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `PhoneFax` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Signature` longtext COLLATE utf8_unicode_ci,
  `TGID` int(11) DEFAULT NULL,
  `UserType` enum('OMSUser','ClientUser','APIUser') COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE KEY `UNIQ_2DA1797740F4AD69` (`TGID`),
  KEY `IDX_2DA17977EEDB0FB6` (`CompID`),
  KEY `IDX_2DA17977F3AF6F` (`OfficeID`),
  CONSTRAINT `FK_8D93D649EEDB0FB6` FOREIGN KEY (`CompID`) REFERENCES `Companies` (`CompID`) ON DELETE SET NULL,
  CONSTRAINT `FK_8D93D649F3AF6F` FOREIGN KEY (`OfficeID`) REFERENCES `Office` (`OfficeID`)
) ENGINE=InnoDB AUTO_INCREMENT=4679 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Data exporting was unselected.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;

**Comment by ansgarbecker** [comment]
I just copied that code and created the table on my MariaDB 10.3 successfully, and  I can also see it in the database tab and in the tree afterwards.

I wonder how you managed to export it if it's not visible in the tree? You must have checked it in the tree for the export?

**Comment by mmkulikov** [comment]
> I wonder how you managed to export it if it's not visible in the tree? You must have checked it in the tree for the export?

Export is not. This is from the initial dump when creating the base.

> I just copied that code and created the table on my MariaDB 10.3 successfully, and I can also see it in the database tab and in the tree afterwards.

Initially was visible. Then disappeared. There are already ideas, but we still need to check. Rather, the problem is in ubuntu windows 10

**Comment by ansgarbecker** [comment]
Please test and post the results here:
* `SHOW CREATE TABLE User`
* `SHOW TABLES LIKE 'User'`
* `SHOW TABLE STATUS LIKE 'User'`
* `SHOW VARIABLES LIKE '%lower%'`

And also please look into the error log file in your MySQL folder.

**Comment by mmkulikov** [comment]
The question can be closed. There was a physical destruction of the table files. I had to restore from backup. The mysql widows were to blame for this and access to it from wsl windows 10

**Comment by ansgarbecker** [comment]
Thanks for your feedback.
