### ISSUE TITLE
Error while import file

### ISSUE THREAD

**Issue by kvantstudio** [HeidiSQL/HeidiSQL#566]
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2949530/bugreport.txt)
Exception message  : No mapping for the Unicode character exists in the target multi-byte code page.

**Comment by ansgarbecker** [comment]
Which encoding did you select in the file-open dialog?
"Auto-detect" mostly fails to detect the right one, so it is important to select "UTF-8" for example when the file has such an encoding.

**Comment by kvantstudio** [comment]
This error occurs in any encoding mode. However, the error only occurs when importing without loading into the editor. If you download the file to the editor and import the error does not occur.

**Comment by ansgarbecker** [comment]
Any chance you could share the file in question? Or at least send it per mail? (see the imprint page on heidisql.com for my email address)

**Comment by narthkain** [comment]
After loading the sql file into a text editor, specify it as utf-8(no signature) to save it and use Import.

When the same error occurred, it was resolved using notepad++ or emeditor.

P.S I think it's a bug that keeps the cancel window on when you click the Cancel button after an error like this... I hope you read this article and correct it.

**Comment by ansgarbecker** [comment]
@narthkain please file a separate issue report for your P.S. - keep it one issue here.

**Comment by narthkain** [comment]
If the sql file is not saved using the utf-8 no signature method, the application will receive an error while importing the file.

If utf-8 is an utf-8 signature method, it will be either an application error or a syntax error.

When an error occurs, the application continues to be clicked to continue using the application. When the processing window opens and the cancel is pressed, the processing window continues to work.

When you press close the window, the message changes alternately between processing and canceling.

It can be difficult to read by using a translator. I'm sorry.

**Comment by torleif** [comment]
I have the same issue. I can't change the encoding as this happens via an external companies tool.

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3052251/bugreport.txt)

**Comment by ansgarbecker** [comment]
I am closing this one as a duplicate to #515, which has slightly more details, and also a test case.

**Comment by Nottt** [comment]
I'm still having the same issue. My only solution is to import the .sql file from terminal

**Comment by zghlx** [comment]
i have the save issue too.

**Comment by ansgarbecker** [comment]
@zghlx please update to the latest release and ensure you have the correct encoding selected in the file-open-dialog.
