### ISSUE TITLE
v9.5.0.5196 wrong number of lines in db overview

### ISSUE THREAD

**Issue by paulvi** [HeidiSQL/HeidiSQL#569]
After backup and restoring (using mysql command line tools), I found this bug:

v9.5 Rows in table overview shown wrong number

restored
![image](https://user-images.githubusercontent.com/1614482/54251645-e1ed4880-4582-11e9-8888-c767f3cd0a4a.png)

original ( 55 < 54 )
![image](https://user-images.githubusercontent.com/1614482/54251659-edd90a80-4582-11e9-906e-0911faaf76a3.png)

However in both db

`select count(*) from t_table;`

return 58.

So this is bug of v9.5.0.5196

**Comment by ansgarbecker** [comment]
Please use the latest build only when reporting bugs. v9.5 is more than a year old. And please don't delete the whole issue template.

The number of rows is an estimation done by the server for InnoDB tables. You receive these wrong numbers when firing `SHOW TABLE STATUS`. This is not a bug in HeidiSQL.

From the [docs](https://dev.mysql.com/doc/refman/8.0/en/innodb-restrictions.html#innodb-table-restrictions):
> SHOW TABLE STATUS does not give accurate statistics on InnoDB tables except for the physical size reserved by the table. The row count is only a rough estimate used in SQL optimization.
