### ISSUE TITLE
EAccessViolation in TSynCustomHighlighter.Next

### ISSUE THREAD

**Issue by CodeTrailblazer** [HeidiSQL/HeidiSQL#57]
When i run a query the higlighter seems to crash. I've been experiencing this issue since i started using heidi under windows 10 either with build  9.4.0.5169 or the new 9.5.0.5196.

Unfortunately i cant seem to find a pattern to the crash. The most consistent way for me to try and reproduce it is to run a query, change to focus to other applications and after some time turn back to heidi. Simply running a query, new or previously run, triggers the crash.

The bug report follows as attachement.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1582146/bugreport.txt)

**Comment by ansgarbecker** [comment]
The relevant code in SynEdit was changed quite a few times, by me, or by some update to the latest SynEdit sources. See the [commit history](https://github.com/HeidiSQL/HeidiSQL/commits/master/components/synedit/Source/SynEditHighlighter.pas).

I can not do much here, but the latest sources have at least some minor changes in the relevant procedure, so a SynEdit synchronization may help here.

**Comment by ansgarbecker** [comment]
I have just pushed the latest SynEdit updates to HeidiSQL. Please check the latest HeidiSQL build if the crash is still happening. Thanks!

**Comment by CodeTrailblazer** [comment]
Hi, i've updated to the sugested build but the problem persists. The call stack is pretty much the same, the current report follows as attachement. 
Thanks for the feedback.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1600004/bugreport.txt)

**Comment by kasnol** [comment]
I have the same issue running in Windows 10; tested both portable and latest nightly builds

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1633543/bugreport.txt)
[bugreport2.txt](https://github.com/HeidiSQL/HeidiSQL/files/1633569/bugreport2.txt)

**Comment by lieszkol** [comment]
Same issue here. Seems to be related to the app losing the connection to the database. Win 7 64 bit, Heidi 9.5.0.5226, MySQL 5.7 and Mariadb 10.2...

[bugreport2.txt](https://github.com/HeidiSQL/HeidiSQL/files/1670111/bugreport2.txt)
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1670112/bugreport.txt)
[bugreport3.txt](https://github.com/HeidiSQL/HeidiSQL/files/1670113/bugreport3.txt)

**Comment by Mc-Pain** [comment]
After fixing that I start catching this error on startup.
9.5.0.5203 is the latest version which still works

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1925468/bugreport.txt)

**Comment by iangregory** [comment]
I have the same issue 9.5.0.5264. HeidiSQL reliably crashes when executing a query after a period of inactivity (likely that the connection to the server has gone away).

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1997572/bugreport.txt)

**Comment by r3verser** [comment]
Same error, have tried different versions old and newest 9.5.0.5278, same problem. With any simple select query, sometimes(often) drops Access Violation. Most often after short inactivity (15 sec or more). Windows 7 64, MySQL 5.7.20.

**Comment by sundagy** [comment]
Crash when execute any custom query((

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2158460/bugreport.txt)

**Comment by sundagy** [comment]
Is there any version without SynEdit?

**Comment by chabberwock** [comment]
Would be really nice to have an option to turn of that TSynCustomHighlighter it would greatly improve user experience. not being able to highlight expressions in query window is bad, but making software completely unusable because of crashes is much worse.

**Comment by energizer77** [comment]
Having same issue here on 9.5.0.5340 with TSynCustomHighlighter when reconnecting.

**Comment by ansgarbecker** [comment]
Hopefully finally fixed in eb1b46d5e94b1a1b5cf366833a6110d88cf3877a

**Comment by sort84** [comment]
date/time          : 2021-02-27, 06:14:21, 539ms
computer name      : 
user name          : 
registered owner   : 
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : Russian
system up time     : 17 days 14 hours
program up time    : 13 minutes 19 seconds
processors         : 4x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
physical memory    : 20730/32649 MB (free/total)
free disk space    : (C:) 25,79 GB
display mode       : 1920x1080, 32 bit
process id         : $4cb4
allocated memory   : 120,26 MB
largest free block : 8181,04 GB
executable         : heidisql.exe
exec. date/time    : 2021-01-24 12:00
version            : 11.2.0.6213
compiled with      : Delphi 10.4 Sydney
madExcept version  : 5.1.0
callstack crc      : $6a267d27, $d8d19677, $d8d19677
exception number   : 4
exception class    : EListError
exception message  : Duplicates not allowed.

thread $3ffc:
00bf9b0e heidisql.exe dbconnection      57   +0 {System.Generics.Collections}TDictionary<System.string,dbconnection.TTableColumnList>.Add
00bf148f heidisql.exe dbconnection    8979   +3 TDBObject.GetTableColumns
00f2aa0d heidisql.exe Main            9199  +59 TMainForm.DBtreeFocusChanged
0096d954 heidisql.exe VirtualTrees   20050   +2 TBaseVirtualTree.DoFocusChange
00974bee heidisql.exe VirtualTrees   22813 +281 TBaseVirtualTree.HandleMouseDown
00967735 heidisql.exe VirtualTrees   17446   +6 TBaseVirtualTree.WMLButtonDown
0040f052 heidisql.exe System                    TObject.Dispatch
0097c262 heidisql.exe VirtualTrees   25774  +19 TBaseVirtualTree.WndProc
006d3c7a heidisql.exe Vcl.Controls              TWinControl.MainWndProc
00568fd3 heidisql.exe System.Classes            StdWndProc
777b956d USER32.dll                             DispatchMessageW
0088c25e heidisql.exe Vcl.Forms                 TApplication.ProcessMessage
0088c2d3 heidisql.exe Vcl.Forms                 TApplication.HandleMessage
0088c721 heidisql.exe Vcl.Forms                 TApplication.Run
00f4dfd8 heidisql.exe heidisql         104  +41 initialization
778b556b kernel32.dll                           BaseThreadInitThunk
77a1372b ntdll.dll                              RtlUserThreadStart
