### ISSUE TITLE
Bug report: wrong table sorting

### ISSUE THREAD

**Issue by LutzT** [HeidiSQL/HeidiSQL#570]
How to reproduce:
1. execute the commands below
2. select database HeidiSQL_bugreport at left panel
3. go to right panel and order tables by name
4. you will find, that tables are not order alphabetically (see screenshot attached) image description

```
DROP DATABASE  HeidiSQL_bugreport;
CREATE DATABASE HeidiSQL_bugreport;
CREATE TABLE HeidiSQL_bugreport.`40AB_Abc` (
    `dummy` VARCHAR(32) NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
CREATE TABLE HeidiSQL_bugreport.`2SN_beta` (
    `dummy` VARCHAR(32) NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
CREATE TABLE HeidiSQL_bugreport.`2SN100_beta` (
    `dummy` VARCHAR(32) NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
CREATE TABLE HeidiSQL_bugreport.`2SN100_gamma_3` (
    `dummy` VARCHAR(32) NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
CREATE TABLE HeidiSQL_bugreport.`2SN100_alpha_1` (
    `dummy` VARCHAR(32) NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
CREATE TABLE HeidiSQL_bugreport.`lorem` (
    `dummy` VARCHAR(32) NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
CREATE TABLE HeidiSQL_bugreport.`ipsum` (
    `dummy` VARCHAR(32) NOT NULL
)
COLLATE='utf8_general_ci'
ENGINE=MyISAM
;
```

## Current behavior

wrong ordering of tables

## Expected behavior

correct ordering of tables

## Possible solution

unknown

## Environment

* **HeidiSQL version:** 
10.1.0.5464
* **Database system and version:** 
MySQL 5.6
* **Operating system:** 
Windows

**Comment by ansgarbecker** [comment]
Confirmed. Seems my sorting algorithm removes non-digits from names which start with a digit. If you do that virtually here, the names look as follows:

    2
    40
    2100
    21001
    21003
    ipsum
    lorem

This is of course wrong.

**Comment by ansgarbecker** [comment]
Should be fixed within the next HeidiSQL build.
