### ISSUE TITLE
Bug: error dialog doesn't show up

### ISSUE THREAD

**Issue by chrysler5798** [HeidiSQL/HeidiSQL#572]
## Steps to reproduce this issue

1. Trigger SQL error
2. If you see the dialog, then try to uncheck the setting, reboot Heidi, check the setting and reboot again Heidi.

Not sure how to reproduce it tho, just found out that on my version even with the setting checked there is no dialog showing up.

Here is a little demo (you can see 5492 version here but after updating to 5494 there is still the issue) :
![2019-03-14_14-49-33](https://user-images.githubusercontent.com/7657777/54362554-69ad8280-4669-11e9-8f7b-d96029f9698c.gif)

## Current behavior
Error dialog not showing up.

## Expected behavior
Error dialog should show up for more visibility.

## Environment

* **HeidiSQL version:** 10.1.0.5494
* **Database system and version:** MySQL 5.7.22
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
The "Show query warnings" checkbox in the preferences dialog is meant for displaying a warning when you run potentially unsafe `UPDATE` or `DELETE` queries without a `WHERE` clause.

You need to re-activate the "Stop on errors in batch mode" button in the toolbar to get that dialog again:

![grafik](https://user-images.githubusercontent.com/7986591/54384777-56b0a780-4695-11e9-9c08-106991a97fcd.png)
