### ISSUE TITLE
EInvalidOperation exception on Ctrl + Tab in "Sessions management" window

### ISSUE THREAD

**Issue by bolduz** [HeidiSQL/HeidiSQL#574]
## Steps to reproduce this issue

1. Open HeidiSQL
2. Press `Ctrl+Tab`

## Current behavior

An exception is thrown, bug report is attached.

## Expected behavior

It shouldn't crash, even though I don't know what would be focused by pressing `Ctrl+Tab`. Since the first screen is the _Settings_ tab, I would probably expect it to switch to the _Advanced_ tab.

## Possible solution

Maybe it happens because it tries to focus an element which doesn't exist? If so, checking for its existence could be a possible solution.

## Environment

`Windows 10 x64 build 17134` (even though the older versions of HeidiSQL see it as `Windows 8 x64 build 9200`).

**HeidiSQL version:** 
Tried with `9.1`, `9.2`, `9.3`, `9.5`, `10.1`, `10.1.0.5494`. Bug reports are attached below.

* [bugreport_HeidiSQL_9.1.txt](https://github.com/HeidiSQL/HeidiSQL/files/2966823/bugreport_HeidiSQL_9.1.txt)
* [bugreport_HeidiSQL_9.2.txt](https://github.com/HeidiSQL/HeidiSQL/files/2966824/bugreport_HeidiSQL_9.2.txt)
* [bugreport_HeidiSQL_9.3.txt](https://github.com/HeidiSQL/HeidiSQL/files/2966825/bugreport_HeidiSQL_9.3.txt)
* [bugreport_HeidiSQL_9.5.txt](https://github.com/HeidiSQL/HeidiSQL/files/2966826/bugreport_HeidiSQL_9.5.txt)
* [bugreport_HeidiSQL_10.1.txt](https://github.com/HeidiSQL/HeidiSQL/files/2966821/bugreport_HeidiSQL_10.1.txt)
* [bugreport_HeidiSQL_Nightly_10.1.0.5494.txt](https://github.com/HeidiSQL/HeidiSQL/files/2966822/bugreport_HeidiSQL_Nightly_10.1.0.5494.txt)

Keep up the good work!

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.

Thanks for reproducing it with all these versions!

**Comment by bolduz** [comment]
Thank you for addressing this issue so fast 👍
