### ISSUE TITLE
Crash adding new column

### ISSUE THREAD

**Issue by ReginaldBull** [HeidiSQL/HeidiSQL#575]
[20190315.txt](https://github.com/HeidiSQL/HeidiSQL/files/2969912/20190315.txt)
## Steps to reproduce this issue

1. Step 1; Opening existing database.
2. Step 2; Going to the table view.
3. Step 3; Select column.
4. Step 4; Pressing button new to add new column.

## Current behavior
The program has a crash, bug report is shown.

## Expected behavior
Adding a new column doesn't crash the program.

## Environment

* **HeidiSQL version:** 
  Version 10.1.0.5464 (32 bit)
* **Database system and version:** 
  MariaDb 10.2
* **Operating system:** 
  Windows 10 1803

**Comment by ansgarbecker** [comment]
Please verify the latest build also has this issue. I recall I fixed something in the inplace editor, and I cannot reproduce that crash here. So please update your HeidiSQL to the latest build and report back whether the problem persists.

**Comment by ReginaldBull** [comment]
As far as I see, 10.1.0.5464 is the latest stable release - excluding the nightly builds.

**Comment by ansgarbecker** [comment]
Please use the latest build, not the release, when reporting stuff here. Thanks!

**Comment by ansgarbecker** [comment]
No feedback for several weeks now.
