### ISSUE TITLE
SSH tunnel shows dialog with Plink output before connecting

### ISSUE THREAD

**Issue by snuggeman** [HeidiSQL/HeidiSQL#577]
## Steps to reproduce this issue
1. Step 1; use SSH tunnel with Putty 0.71
2. Step 2; connect
3. Dialog box appears: 'Plink: using username "root"'
4: When dialog is dismissed, connection succeeds and works as usual

## Environment
HeidiSQL 10.1.0.5464
Putty 0.71 (64bit)
Windows 10

**Comment by ansgarbecker** [comment]
Can you please attach a screenshot here.

**Comment by snuggeman** [comment]
![Skärmklipp](https://user-images.githubusercontent.com/26237810/54495209-1db94280-48e2-11e9-8db0-4aed8f421776.PNG)

**Comment by ansgarbecker** [comment]
Ok, thanks.

If you connect via SSH yourself, let's say by PuTTY, does that "_Using username root_" wait for input? That would explain why HeidiSQL displays it as a dialog. But it could easily be a bug in HeidiSQL. Probably the server flushes that text, waits a few milliseconds, then sends the next output, which my implemenation expects to be a prompt, worth to be displayed in a dialog.

**Comment by snuggeman** [comment]
When connecting with Putty, no such dialog is shown.

I forgot to mention, I'm using Pageant for authentication.
Putty, Pageant, Plink are all from Putty 0.71 (just released)

**Comment by ansgarbecker** [comment]
Ok, but I suppose there's a short waiting time after that "Using username..." output, before the next text from comes in?

**Comment by snuggeman** [comment]
I never use Plink manually so I would not know if this has changed. But:
when using cmd.exe (and not cygwin, which I normally use) shell, I get a prompt when manually starting Plink:

>Plink.exe root@host
Using username "root".
Access granted. Press Return to begin session.

**Comment by vbojan** [comment]
This appears to be specific to Plink 0.71 as the same version of HeidiSQL (10.1.0.5489) did not show that dialog with Plink 0.70. I'm using private key for authentication without Pageant. Just upgraded to 10.1.0.5505 and it behaves the same.

When the above error is shown I have to click on OK button to close the dialog after which it connects to the server just fine (as before).
It feels as if some logic in HeidiSQL needs to be adjusted to the new version of Plink and not show the error dialog. Or if there was indeed an error then show actual error details.

**Comment by swiffer** [comment]
same here since updating to Plink 0.71 (pubkey auth)

**Comment by ansgarbecker** [comment]
The next build should just show that new informational output from plink in the log panel, without an error dialog.

Interesting though that plink sends this "_Using username xyz_" to the error pipe, not to the normal output pipe.
