### ISSUE TITLE
Indexes not always displaying while switching table

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#578]
## Steps to reproduce this issue

1. Create 3 tables using the following script:
```
CREATE TABLE `t1` (
	`a` INT(11) NULL DEFAULT NULL,
	INDEX `idx_t1_a` (`a`)
);

CREATE TABLE `t2` (
	`b` INT(11) NULL DEFAULT NULL,
	INDEX `idx_t2_b` (`b`)
);

CREATE TABLE `t3` (
	`c` INT(11) NULL DEFAULT NULL
);
```
2. Refresh database (F5)
3. Click at `t1` table in tree and select 'Indexes' tab => you'll see index `idx_t1_a` => OK
4. Click at `t2` table in tree, your default tab will be 'Indexes' and you will see index `idx_t2_b` => OK
5. Click at `t3` table in tree, your default tab will be 'Indexes' and you will not see any indexes as the table does not have any => OK
6. Click at `t1` table in tree again. Your default tab will be 'Indexes', but this time you will NOT see the index `idx_t1_a` => ISSUE
7. Click at `t2` table in tree again. Still no index `idx_t2_b` => ISSUE
etc

You need to switch from 'Indexes' tab to another tab and back to be able to see table's indexes again.

## Current behavior

Indexes not displaying when switching from table that does not have any indexes to table that does have them.

## Expected behavior

I believe you should be able to see indexes.

## Possible solution

As a workaround you can to switch from 'Indexes' tab to another tab ('Basic' for example) and back. 
Unfortunately, you have to do this every time when you see no indexes to be sure that there is no actually indexes on the table.

## Environment

* **HeidiSQL version:** 10.1.5498
* **Database system and version:** MySQL 5.7.23, MariaDB 10.1.14
* **Operating system:** Windows 10 x64

**Comment by fifonik** [comment]
Looks like nobody using indexes :)

**Comment by fifonik** [comment]
I noticed the same issue on 'Foreign keys' tabs.

It looks like just Repaint is missed somewhere as when switching table while on the Indexes tab, the Clear button on the left becoming active and if Add button on the left is clicked, the new index added AND already existing indexes appeared.

**Comment by ansgarbecker** [comment]
Problem was indeed a missing repaint/invalidation in the initialization method. That repaint then indirectly sets the number of root nodes in both index and foreign key editors.
Previously, if there were 0 nodes in the previous table, the next table did never set it to 1 (or whatever number), unless the user clicked "Add" or some other button.
