### ISSUE TITLE
sort encodings in Import CSV File modal?

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#579]
by either most common or alphabetical?

my go-to is `UTF-8 Unicode (utf8)`, which is probably a sane default to have, too.

![sort_encoding](https://user-images.githubusercontent.com/43234/54509670-4eb46a00-4918-11e9-80c5-17fd3cb7bd93.png)

thanks!

**Comment by ansgarbecker** [comment]
I suppose the default should still be what the database is set to. Probably the second item should then be utf-8. For the rest I suppose it's a good idea to move the short names to the left, then sort them alphabetically:

* latin1: Database default
* utf8mb4: UTF-8 Unicode
* armscii8: ARMSCII-8 Armenian
* ascii: US ASCII
* ...

**Comment by leeoniya** [comment]
maybe it makes sense to just keep them strictly alphabetical, pre-select the database default, and add something to the settings to override the pre-selected default. having them be in quasi-alphabetical order is still kind of hard to look at, IMO.

**Comment by ansgarbecker** [comment]
Yes, sounds reasonable. Just pushed that, a quite large commit for just having a different sorting here, but I had to reinvent some wheels in the code:

![grafik](https://user-images.githubusercontent.com/7986591/54557633-efa83100-49bb-11e9-8d06-673f7775a6b0.png)

**Comment by leeoniya** [comment]
ah, much better now. thanks a ton, as always! 💯
