### ISSUE TITLE
Edit input bug

### ISSUE THREAD

**Issue by valeriy-efimov** [HeidiSQL/HeidiSQL#580]
Why ctr+a not working  in edit input?
![image](https://user-images.githubusercontent.com/5989188/54531218-68dc5f80-498d-11e9-866a-b110eb1486ad.png)
Also does not work with mouse =/

HeidiSQL 10.1.0.5464

**Comment by ansgarbecker** [comment]
Works both here, for the name input and for the comment:

![grafik](https://user-images.githubusercontent.com/7986591/54547559-43a81b00-49a6-11e9-846d-c43cd77c2cfa.png)

Windows 10 here, maybe that's a difference?

**Comment by ansgarbecker** [comment]
Ah... I recall the theme you are using does not really make selected text visible as such. The text _is_ selected, you just can't see a difference to normal text. You should update to the latest build, as stated in the issue template, and then try again. And also try with another theme.

**Comment by valeriy-efimov** [comment]
@ansgarbecker  Yes it's true! On the standard theme, everything works. Thank you very much.
