### ISSUE TITLE
Can't connect to local SQL Server Express 2017

### ISSUE THREAD

**Issue by Wichart009** [HeidiSQL/HeidiSQL#581]
I used the lastest version of HeidiSQL_10.1_64_Portable to connect MS SQL Server EXPRESS on the localhost and got an error. Could you please check for me?
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2984119/bugreport.txt)

**Comment by ansgarbecker** [comment]
The callstack has quite little information about the issue:

```
exception class    : Unknown
exception message  : Unknown.

main thread ($3508):
00a9ccff heidisql.exe Data.Win.ADODB           TADOConnection.DoConnect
```
Do you have some more details about the server (version)?

Also, please update to the latest nightly build.

**Comment by Wichart009** [comment]
Here is my SQL Server on my machine.
![HeidiSQL](https://user-images.githubusercontent.com/12468949/54664176-124e5d00-4b16-11e9-8c00-fddfcc647a09.jpg)

**Comment by ansgarbecker** [comment]
Please update to the latest build and try again.

Also, please verifiy your MS SQL Server is set up to support TCP/IP connections. This can be checked in the SQL Server configuration program.

**Comment by Wichart009** [comment]
I had already enabled and set both TCP/IP & Name Pipe.
![HeidiSQL_1](https://user-images.githubusercontent.com/12468949/54746926-0a6ae780-4c00-11e9-85a8-530e99f344c4.jpg)

**Comment by Wichart009** [comment]
I changed the host value from "localhost" to <ComputerName>\<InstanceName>, it working now.
![SQLServer-HeidiSQL](https://user-images.githubusercontent.com/12468949/55665021-61a8c300-5862-11e9-8b3e-f096eddc642f.jpg)

**Comment by ansgarbecker** [comment]
Ok, thanks for your feedback!

**Comment by Wichart009** [comment]
Thank you too. Do you have a plan to make HeidiSQL support NoSQL Database or not?

**Comment by ansgarbecker** [comment]
No, I did not plan to support NoSQL for HeidiSQL. I suppose that would even require more modifications than the MSSQL and PostgreSQL support.
