### ISSUE TITLE
Crash with time format column from MS SQL Server

### ISSUE THREAD

**Issue by kaurkook** [HeidiSQL/HeidiSQL#582]
## Steps to reproduce this issue

1. Step 1; MSSQL server Table with column formated Time Length/Set (0)
2. Step 2; Select query
3. Step 3; Select col1, col2, ... , col(x) (this column in time format) - column doesn't appears n answer
4. Step 4; Select col(x) - answer appears and in all rowsa are text "Node"
5. Step 5; Select col1, col2, .., col(x), col(n) - Then I get Crash and bugreport
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
   10.1.0.5505 Windows10 SlateGray (tried also with Amakrits)
* **Database system and version:** 
   Microsoft SQL Server 2012 (SP1) - 11.0.3401.0 (X64) 
	Jan  9 2014 13:22:15 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.2 <X64> (Build 9200: ) (Hypervisor)

* **Operating system:** 
   WIN10

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/2987100/bugreport.txt)
![Columns](https://user-images.githubusercontent.com/48750416/54669312-b970cb80-4af9-11e9-8586-371402e4c3f7.PNG)
![Crash](https://user-images.githubusercontent.com/48750416/54669315-bbd32580-4af9-11e9-928c-2f387e5f891b.PNG)
![IntegerAndTime](https://user-images.githubusercontent.com/48750416/54669319-bd9ce900-4af9-11e9-9c9f-6ad7781ad86b.PNG)
![JustTime](https://user-images.githubusercontent.com/48750416/54669324-bf66ac80-4af9-11e9-816b-3f1c3d00c999.PNG)

**Comment by kaurkook** [comment]
With MySQL crash doesnt appear. And when convert Time ti Varchar, then all works

**Comment by ansgarbecker** [comment]
Most probably a duplicate to #423, or #496
