### ISSUE TITLE
Error dropdown list.

### ISSUE THREAD

**Issue by Tecnicasoft** [HeidiSQL/HeidiSQL#583]
![erro](https://user-images.githubusercontent.com/16633547/54688496-79f7ae80-4afc-11e9-9cb8-5577575c1924.png)
Good morning, this error is occurring when choosing from the drop-down list, I can not see the names of the list.

**Comment by ansgarbecker** [comment]
But you can resize that list, or?

Please read [this forum post](https://www.heidisql.com/forum.php?t=26729).

**Comment by Tecnicasoft** [comment]
não aparece a opção para redimensionar, a largura e fixa

**Comment by Tecnicasoft** [comment]
does not appear the option to resize, the width and fixed

**Comment by Tecnicasoft** [comment]
in previous versions before using the dark theme this problem did not happen

**Comment by Tecnicasoft** [comment]
I managed to put the theme windows and resizing the window, I guess I went back to the dark theme, but using the dark theme does not appear to be zeta to be able to change the size of the window.

**Comment by ansgarbecker** [comment]
Closing as this has to be fixed in SynEdit, not directly in HeidiSQL.

**Comment by ansgarbecker** [comment]
Just file another ticket, in Rodrigos vcl-styles project: https://github.com/RRUZ/vcl-styles-utils/issues/262
