### ISSUE TITLE
Error showing tables when database name contains '-'

### ISSUE THREAD

**Issue by wangyuanle** [HeidiSQL/HeidiSQL#584]
when the database name contains characters '-', The database will not connect properly .

![image](https://user-images.githubusercontent.com/20235259/54897187-5cfb1b00-4f02-11e9-8e93-9243203501cb.png)

**Comment by ansgarbecker** [comment]
It should, definitely, due to the backticks used by HeidiSQL. So what is causing the error?

Do you probably have ANSI SQL mode on?
Please post the output of this query here:

    SHOW VARIABLES LIKE 'sql_mode'

**Comment by ansgarbecker** [comment]
No feedback provided since several weeks now.
