### ISSUE TITLE
Query editor selection bug

### ISSUE THREAD

**Issue by winsys** [HeidiSQL/HeidiSQL#585]
## Steps to reproduce this issue

1. Type or paste long query into Query editor. 30-40 lines;
2. Try to select large block of text using mouse or keyboard;

## Current behavior

Selection stops at random point.
Cursor sometimes disappears. 

Screen capture: http://winsys.lv/tmp/20190325_165509.mp4

## Expected behavior

Obvious.

## Environment

* **HeidiSQL version:** 
  
Version 10.1.0.5505 (64 Bit)

* **Operating system:** 
  
Windows 10 Pro (64bit)

**Comment by fifonik** [comment]
Hm. I do not have the issue on the same HeidiSQL version and Win 10 Pro 1803 (pasted 160+ lines from queries log then 800+ lines from notepad++).

**Comment by ansgarbecker** [comment]
Just tried on my old work computer running Win7 - no bug here. Selecting flickers a bit but without problem on larger blocks. Even with a theme other then the default "Windows". Themes were recently reported to cause random GUI issues quite often.
I guess I can reproduce that on my Win10 computer at home. Will check.

**Comment by winsys** [comment]
Just tried on another Win Pro 64, also do not have problem there.
It seems some system config/app causes this bug. But I have no idea how to detect this problem.

**Comment by ansgarbecker** [comment]
Me neither - no issue on Win10 with the latest nightly of HeidiSQL.

Maybe you have some special mouse app running in the background?
Is the issue also there if you select via keyboard? (<kbd>Shift + Up/Down</kbd>)

**Comment by winsys** [comment]
Yes, via keyboard the same problem. And sometimes cursor disappears.
It seems this is problem of my Windows at work.
I will try to remove device drivers one by one. 
Let you know if I find which app causes this problem.

**Comment by winsys** [comment]
I found the problem.
I am using 4K monitor, and for previous versions of HeidiSQL used system scaling settings for HighDPI.
I just turned it off and now works perfect. 

On screenshot below modes causing this problem selected with yellow color.

![image](https://user-images.githubusercontent.com/6884536/55411461-5c036280-556e-11e9-80aa-76777fc4ec76.png)

**Comment by ansgarbecker** [comment]
c31cae206042ae00b97e41f43baf7421693d2e46 now removes all tweaks for high DPI monitors. I'm giving up here, this does all not work good enough, even different computers and Windows versions behave differently. It's a mess. So, now HeidiSQL is zoomed by Windows again, like it was in earlier v9.5. This does at least display all controls and fonts in the right dimensions.

Having done that, you no longer need to override the DPI settings for HeidiSQL - they are "System" by default now.
