### ISSUE TITLE
Unable to connect to localhost\sqlexpress

### ISSUE THREAD

**Issue by igitur** [HeidiSQL/HeidiSQL#587]
## Steps to reproduce this issue

1. Ensure MS SQL Server Express is installed on localhost
2. Create a new connection to:
-  Network type: `Microsoft SQL Server (TCP/IP)`
-  Hostname: `localhost\sqlexpress`
-  Use Windows authentication
3. Click Open

## Current behavior
Unable to connect to server. After a while I receive an error:

> SQL Error (0): SQL Server Network Interfaces: Error Locating Server/Instance Specified [xFFFFFFFF]Login timeout expired

## Expected behavior

Successfully connect to `localhost\sqlexpress` server. 

## Possible solution

Until HeidiSql v9.5 I could successfully connect to SQL Express. The new TLS driver seems to have broken this. 

## Environment

* **HeidiSQL version:** 
  10.1.0.5505 (64 bit)
* **Database system and version:** 
  Microsoft SQL Server Express
* **Operating system:** 
  Windows 7 64b

**Comment by ansgarbecker** [comment]
Are you probably missing the [newer OLE DB driver](https://www.microsoft.com/en-us/download/confirmation.aspx?id=56730), mentioned on the download page?

**Comment by igitur** [comment]
@ansgarbecker No, I already have the very latest version.

**Comment by igitur** [comment]
Have you tried reproducing the error on your side? SQL Express is free to download and install.

**Comment by ansgarbecker** [comment]
Yes, I have no problems connecting to my local SQL Express installation. That's why I was asking for the driver. Indeed if you hadn't installed the OLE DB driver, HeidiSQL would see that and fall back to the older one.

So I have no clue currently. Maybe activate debug log messages in preferences and see if there's some relevant stuff?

**Comment by igitur** [comment]
Ok, to which file does the debug messages write?

Also, since you can connect successfully, I will check out firewall and anti-virus. But as I say, SSMS can connect successfully. Weird.

**Comment by ansgarbecker** [comment]
You can open the preferences dialog from the session manager's "More" button, than enable debug messages and writing to file:
![grafik](https://user-images.githubusercontent.com/7986591/56377608-0932d780-620b-11e9-98d6-4e715bca1363.png)

I just tried these hosts and all of them work:
* DESKTOP-P7OHKGH\SQLExpress (my computername)
* DESKTOP-P7OHKGH\sqlexpress
* localhost\SQLExpress
* localhost\sqlexpress

But I just realize I am connecting via named pipe, not TCP/IP.

I remember I had to once open TCP/IP for connecting, in the SQL Server Configuration manager, under network > protocols:
![grafik](https://user-images.githubusercontent.com/7986591/56377848-a42bb180-620b-11e9-8d1e-6946bb3aa490.png)

**Comment by LukeARG** [comment]
Anyone else reading this and looking for an answer -- make sure SQL Browser is enabled. If it's grayed out for you to enable, go to start, search "SERVICES" find SQL SERVER BROWSER, right click Properties, switch "Disabled" to "Automatic" or whatever your preference is

**Comment by igitur** [comment]
@LukeARG  Thanks! That was my problem too. My SQL Server Browser service was set to disabled.

**Comment by warrenlbrown** [comment]
None of this helps me yet. Using latest drivers and trying to connect to local dev sqlexpress has not worked since the Heidisql TLS upgrade  Thank you.

**Comment by jpwits** [comment]
Hi make sure it is the right path, use .\sqlexpress, instead, could be that the localhost should be in brackets (localhost)\sqlexpress, check if the sqlexpress is correct, by going to Services (admin), scroll down and check the name(s) by the MSQLSERVER services, different versions of SQLExpress have different default db names.

**Comment by Hafeezullah2023** [comment]
> Anyone else reading this and looking for an answer -- make sure SQL Browser is enabled. If it's grayed out for you to enable, go to start, search "SERVICES" find SQL SERVER BROWSER, right click Properties, switch "Disabled" to "Automatic" or whatever your preference is

Thank you bro for saving my day.

**Comment by eeskildsen** [comment]
Here's what worked for me:

1. <kbd>Win</kbd>+<kbd>R</kbd> > sqlservermanager16.msc > <kbd>Enter</kbd>
3. SQL Server Network Configuration > Protocols for SQLEXPRESS
4. Right-click *TCP/IP*
5. Click *Enable*
6. <kbd>Win</kbd>+<kbd>R</kbd> > services.msc
7. Right-click *SQL Server (SQLEXPRESS)*
8. Click *Restart*
9. Double-click *SQL Server Browser*
10. Change startup type to *Automatic*
11. Click *Start*
12. Click *OK* and close open windows
13. In HeidiSQL, create a new connection
14. Set *Network type* to *Microsoft SQL Server (TCP/IP)*
15. Set *Library* to *MSOLEDBSQL*
16. Set *Hostname / IP* to *(local)\SQLEXPRESS*
17. Tick *Use Windows authentication*
18. Click *Open*
19. Save the connection when prompted
