### ISSUE TITLE
Appending quick column filter expects Shift pressed on message dialog

### ISSUE THREAD

**Issue by CMMoreira** [HeidiSQL/HeidiSQL#588]
If i made just like you said, shift+click, will add the filter (print With shift+click).

But, adding a filter such as "Like" or "=" , when it show the messagebox to fill the parameter, will only add that filer and don't combine with the last sintax (print last).

![image](https://user-images.githubusercontent.com/49067535/55239332-5c2df600-522e-11e9-8da9-f2041b385fe1.png)

![image](https://user-images.githubusercontent.com/49067535/55239335-5e905000-522e-11e9-8b60-74c529c31e3b.png)

![image](https://user-images.githubusercontent.com/49067535/55239339-605a1380-522e-11e9-8ab7-3292f0673b52.png)

**Comment by ansgarbecker** [comment]
I assume you did not press <kbd>Shift</kbd> when you clicked the "OK" button on the input dialog?

I also did not so at first, and then found if I do it works as expected. But that's not really intuitive, so I should change that.

**Comment by CMMoreira** [comment]
In all options you press shift key, but in diaglog boxes will clear the string you have filtered.
