### ISSUE TITLE
Minimize to system tray

### ISSUE THREAD

**Issue by nikunjbhatt** [HeidiSQL/HeidiSQL#59]
Please add an option to allow minimizing the HeidiSQL window to Windows' system tray.
This option can be added in Tools > Preferences dialog > General tab

### Context

* HeidiSQL version: **9.4.0.5174**
* Operating system: Windows 7

**Comment by ansgarbecker** [comment]
HeidiSQL is loaded quicky via taskbar button or start menu.
So what's the goal of having it permanently running in the system tray?

**Comment by nikunjbhatt** [comment]
When closing window, if there is any unsaved data or anything else, the user will need to either save it or let it get destroyed.
And if window is kept open (it's normal for a developer to have many other windows open at a time), it will occupy space in taskbar.
I am using other applications like Skype, Outlook, IPMsg, XAMPP etc. - and they all have such option for convenience to the developers.

**Comment by ansgarbecker** [comment]
> I am using other applications like Skype, Outlook, IPMsg, XAMPP etc. - and they all have such option for convenience to the developers.

I guess that's not only for developers, but for all users. And these messaging and server applications all have some reason to run in the background. For example they poll messages or run a webserver. HeidiSQL does just nothing in the background, except for holding your unsaved scripts in the editor. That's the reason why most text editors, web browsers, games etc. don't have a tray-icon.

There are some tools out there who can place any running application to your tray, like TrayIt: http://download.cnet.com/TrayIt/3000-2094_4-75728730.html
Probably this is helpful.

**Comment by nikunjbhatt** [comment]
I agree. Thanks a lot for the TrayIt pointer, although I now installed similar application - RBTray.

**Comment by ansgarbecker** [comment]
Thanks for your consistent feedback!
