### ISSUE TITLE
"Find Text" tool does not show up on Remote Server

### ISSUE THREAD

**Issue by Dibbyo456** [HeidiSQL/HeidiSQL#590]
## Steps to reproduce this issue

1. Connect to a remote MariaDB server.
2. Select database/table
3. Click Search -> Find text  OR  Find or replace again OR Replace text

## Current behavior

Nothing shows up..!

## Expected behavior

Expecting the tool/interface.
But it works fine when using local server. (ie server of my xampp)

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 10.1.0.5511 (64 bit)
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
This is probably a misunderstanding, or maybe a usability issue. That search / replace actions only work when you have either a query tab with content focused, or a reult grid.

**Comment by Dibbyo456** [comment]
Oh, yes. You are right.
Thank you, closing it.
