### ISSUE TITLE
SSL Connection Error: no cipher match

### ISSUE THREAD

**Issue by saulhudson** [HeidiSQL/HeidiSQL#594]
## Steps to reproduce this issue

1. Open Heidi
2. From the session manager select "open" to connect to the database
3. The error is displayed

![1](https://user-images.githubusercontent.com/789556/55393369-078fc100-5535-11e9-9091-69f9baa81872.png)
![2](https://user-images.githubusercontent.com/789556/55393375-09598480-5535-11e9-9d40-6bb034381fe1.png)

## Current behavior

When connecting to a Google Cloud MySQL 2nd Gen 5.7 with SSL enabled I can't connect to the database because I get an "SSL Connection Error: no cipher match" error. Connections to other databases with or without SSL work fine so I suspect this is an issue relating to Heidi accessing Google Cloud SQL instances with SSL enabled.

## Expected behavior

I would expect to be able to connect to the database fine. I've tried connecting to the same database using SQLYog and MySQL workbench, both of which work fine with the same SSL settings & certs etc so it feels like Heidi isn't handling something in quite the same way as other database clients.

## Environment

* **HeidiSQL version:** 
  10.1. Tried using nightly builds up to 5511

* **Database system and version:** 
  Google Cloud MySQL 2nd Gen 5.7 

* **Operating system:** 
  Windows 10

**Comment by nstr10** [comment]
Not a solution but a possible workaround might be to use SSH port forwarding to provide a safe encrypted tunnel to work in, then you wouldn't need to worry about SSL cipher support issues (btw, this is probably an issue with the server and client libraries Google and HeidiSQL respectively are using).

**Comment by ansgarbecker** [comment]
@saulhudson please update to the latest build and give it another try. I pushed 51da7c8efc890ebdb394dfa53f911b64223a53e8 yesterday, which should now allow all TLS versions up to v1.3. Probably that helps here.

**Comment by RLHawk1** [comment]
I have the same issue using version 5594.

**Comment by bftrock** [comment]
I just upgraded to 10.2.0.5599 and now I cannot connect to an AWS Aurora (MySQL) instance because SSL is required, and I am getting this error. No issue before I upgraded.

**Comment by NPSF3000** [comment]
I also upgraded to I just upgraded to 10.2.0.5599 from I just upgraded to 10.2.* and running into this issue with GCP databases protected by SSL.  Been running fine until now.

**Comment by ansgarbecker** [comment]
After an update to the latest build, you could try out in the session settings to select the library libmysql.dll, instead of the default libmariadb.dll. Probably this helps in some cases, as libmysql also solved one other connection related issue.

**Comment by RLHawk1** [comment]
When I change to libmysql.dll I get a different error, "SSL connection error: ASN: bad other signature confirmation" but it still doesn't work
![image](https://user-images.githubusercontent.com/1224305/61242066-cd78b280-a712-11e9-9da9-6fd44d8f27ef.png)

**Comment by ansgarbecker** [comment]
Ok, we should probably try a newer libmysql, as the one shipped with HeidiSQL is a bit old (5.6). Maybe you could download one from mysql.com any try out?

**Comment by ansgarbecker** [comment]
@RLHawk1 Any chance you try out the latest built Heidi installer from https://www.heidisql.com/installers/HeidiSQL_10.2.0.5652_Setup.exe , and check whether the new libmysql-6.1.11 works? In #722 the reporter already said that worked.

**Comment by RLHawk1** [comment]
@ansgarbecker Yes! Thank you! As long as I use that dll file it works again. I appreciate the fix very much!

**Comment by ansgarbecker** [comment]
I'm closing this right now, though I'm a bit unsure if the other SSL issues are fixed with the new installer as well.

@bftrock @NPSF3000 @nstr10 @saulhudson perhaps some of you could also verify it works now, using the latest built installer https://www.heidisql.com/installers/HeidiSQL_10.2.0.5663_Setup.exe ?

**Comment by bftrock** [comment]
@ansgarbecker I can successfully connect to AWS Aurora (MySQL) when I select libmysql-6.1.dll. The other two choices in my list don't work. These are libmysql.dll and libmariadb.dll. Thanks for providing this fix!
