### ISSUE TITLE
Overlapping text in completion proposal with high DPI

### ISSUE THREAD

**Issue by dudumiquim** [HeidiSQL/HeidiSQL#596]
## Steps to reproduce this issue

1. Change the resolution to 3840x2160 and define all the suggestion of windows 10
2. Open Heidi and connect to MySQL server
3. Start to write a SQL Query (SELECT * FROM )
4. After "FROM", press CTRL + SPACE

## Current behavior
The list of databases and functions comes with formatting problem. I took one print...
https://i.imgur.com/KoQ7QOL.png
Using Full HD resolution, works well.

## Expected behavior
I was expecting the list of databases and functions readable 

## Possible solution
In my case, I need change the font size when I'm using 4k and return to default when I'm using FullHD.

## Environment

* **HeidiSQL version:** 10.1.0.5464 (64 bit)
  
* **Database system and version:** MySQL 5.7.12 (AWS RDS Aurora)
  
* **Operating system:** Windows 10 1809

**Comment by ansgarbecker** [comment]
The resolution itself is not the problem - it's the custom DPI setting over 100% which increases the font size and therefore causes lots of problems.

**Comment by ansgarbecker** [comment]
c31cae206042ae00b97e41f43baf7421693d2e46 now removes all tweaks for high DPI monitors. I'm giving up here, this does all not work good enough, even different computers and Windows versions behave differently. It's a mess. So, now HeidiSQL is zoomed by Windows again, like it was in earlier v9.5. This does at least display all controls and fonts in the right dimensions.
