### ISSUE TITLE
HEIDI will empty the wrong table/view

### ISSUE THREAD

**Issue by bensch808** [HeidiSQL/HeidiSQL#598]
## Current behavior

I want to delete a view and in the end, it deleted all the data in a table I clicked before.

Please see the video.

https://www.dropbox.com/s/714ztehtdbpz9zi/L%C3%B6schen%20der%20DB.mp4?dl=0

I hope the quality is not too bad.

//Here the explanation in words

1. I click on the table Results with the left mouse
2. Then I click on a view which was created with the left mouse.
3. Then I click on this view with the right mouse and choose "Empty table" ("Tabelle(n) leeren" in german)
4. A Popup will ask if I want to empty 1 tabel or view and the name of the view.
5. I choose "yes" and all the data in the table Results are deleted.

## Possible solution

Fix the bug

## Environment

* **HeidiSQL version:** 
 It happend with an older Version, but also with the newest one.
* **Database system and version:** 
 Microsoft SQL Server 2014
* **Operating system:** 
 Win 7

**Comment by ansgarbecker** [comment]
Hm, that sounds very odd. In you video you can see the `DELETE` query HeidiSQL fired, and it looks like the right one, or?

![grafik](https://user-images.githubusercontent.com/7986591/55575117-6ceada00-570e-11e9-8ad2-0e12f4386b77.png)

**Comment by bensch808** [comment]
That's true. "Barcode" is the name of the view I actually want to delete. But the view stays and the content of the table "result" is deleted. 
Do you think it is an issue of Microsoft SQL Server 2014

**Comment by ansgarbecker** [comment]
If you want to delete the view itself, click on "Drop", not on "Empty table(s)".

I suppose the data in the view is just a selection of that "result" table. In that case it's very normal that the data in the table was deleted. A view itself does not own rows.
