### ISSUE TITLE
Multiple backtick issues

### ISSUE THREAD

**Issue by evilworm** [HeidiSQL/HeidiSQL#6]
## Expected behavior

Autocomplete should put an ending backtick if you have one in the beginning of the column name. Suggestions should be shown even if I wrap the column name with backticks.

## Current behavior

Autocomplete wraps the column name in backticks even if you have already put one backtick by yourself. Also all the suggestions are removed if you start the column name with backtick in the query, but the popup remains open and empty.

### Steps to reproduce

1. start typing sql query and have an autocomplete window pop up for available columns
2. start your column name by putting ` (backtick), then type the column name and then press enter
3. you get something like ```column`

### Context

HeidiSQL version: 9.4.0.5186
Video of the issue: https://www.youtube.com/watch?v=0A6grLiXB_w
(unfortunately the video does not show the autocomplete popup for some reason, but it's there)

**Comment by ansgarbecker** [comment]
There is no need to write a backtick for column names, as the proposal inserts a backtick automatically if required (read: if the column name is a reserved SQL keyword or has spaces).

But you're right, the proposal should not be empty when you type a backtick, and it should not quote backticks with even more backticks.
