### ISSUE TITLE
Publish in Windows Store

### ISSUE THREAD

**Issue by ansgarbecker** [HeidiSQL/HeidiSQL#60]
## Expected behavior

HeidiSQL available in Windows Store.

## Current behavior

Not found there.

With Microsoft's DesktopAppConverter, it should be possible to wrap the HeidiSQL installer in what they expect to be in a .appx file.

Some docs for this conversion:
* MS DesktopBridge:
  * https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter
  * https://blogs.msdn.microsoft.com/appconsult/2016/10/17/desktop-bridge-converting-an-installer/
* InnoSetup's command line parameter: http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline

After that "conversion", it should be published.

**Comment by ansgarbecker** [comment]
[Here](https://www.heidisql.com/forum.php?t=22106)'s a forum reporter asking for that too.

What I yet did was:
1. download the Windows 10 SDK
2. install [Desktop App Converter from the store](https://www.microsoft.com/store/productId/9NBLGGH4SKZW)
3. activated the "Container" feature, in "Activate Windows features" dialog
4. downloaded the latest Win10 image container from https://aka.ms/converterimages
5. start DesktopAppConverter with admin privileges
6. extend the downloaded image using this ps-command:
`DesktopAppConverter -Setup -BaseImage C:\Users\Ansgar\Downloads\Windows_InsiderPreview_DAC_16299
.wim`
7. try to create the appx package with this command:
`DesktopAppConverter -Installer c:\heidisql\apxtemp\HeidiSQL_9.5.0.5196.exe -Destination c:\heidisql\app
x\ -PackageName "HeidiSQL" -InstallerArguments "/VERYSILENT /LOG=<log_folder>\install.log"
 -Publisher "CN=Ansgar Becker" -Version 9.5.0.5196 -MakeAppx -Verbose`

The converter starts and complains about nothing, but then hangs at this message:
> [2017-12-29T15:37:28] Running installer command in Isolated Environment
> [2017-12-29T15:37:28] Command line: "C:\shared\installer\HeidiSQL_9.5.exe" /VERYSILENT /LOG=C:\shared\logs\install.log /DIR=expand:{userpf}\HeidiSQL
> [2017-12-29T15:37:30] Waiting for installer process to complete inside Isolated Environment

So, my guess is the isolated image environment starts the HeidiSQL installer but then the `/VERYSILENT` flag does not work as expected somehow.

**Comment by ansgarbecker** [comment]
Looks like the isolated container asks for admin privileges.
How do I prevent the UAC prompt waiting forever?

**Comment by ansgarbecker** [comment]
Ok, there are obvously two things to fix in the [Setup] section of an InnoSetup install script:
* `DefaultDirName={userpf}\{#ProgName}`
* `PrivilegesRequired=lowest`

The first one says: use `C:\Users\MyName\AppData\Local\Programs\` as default target directory, not `C:\Program files\`.
The second one tells the installer not to request an UAC dialog to come up.

Additionally, in the `[Registry]` section, writing to registry keys other then `HKEY_CURRENT_USER` results in warning messages. These can be suppressed/ignored by using `Flags: noerror`.

I have just created a separate installer with the above configuration: https://www.heidisql.com/downloads/installers/HeidiSQL_9.5_appx.exe
But using the Desktop App Converter, I just still get this damned waiter:

> AUSFÜHRLICH: Running installer command in Isolated Environment
> AUSFÜHRLICH: Command line: "C:\shared\installer\HeidiSQL_9.5_appx.exe" /VERYSILENT /LOG=C:\shared\logs\install.log
> AUSFÜHRLICH: Waiting for installer process to complete inside Isolated Environment

and then... nothing happens any more. :(

**Comment by ansgarbecker** [comment]
I just got some steps further.
I managed to create an appx package, by not using the installer:

    DesktopAppConverter -Installer c:\heidisql\apxtemp\ -AppExecutable heidisql.exe
      -Destination c:\heidisql\appx\ -PackageName "HeidiSQL" -Publisher "CN=Ansgar Becker"
      -Version 0.0.0.0 -MakeAppx -Verbose -Sign

I uploaded that package in the dev center, and got various errors.
* One was that I was not allowed to submit packages converted with the DesktopBride, so I asked MS per form to give me this privilege. Just waiting for an answer now.
* Another error was that the -Version parameter must not contain something other than 0.0.0.0 - very strange.
* Then, my publisher name contained a comma "Ansgar Becker, Software Development", but commas are not allowed in one publisher name. So I changed my publisher name in the dev center to "Ansgar Becker", saved it, but I still get this error. Perhaps this takes some time to finalize.
* The last one which I cannot find a workaround for is this one:
> Package acceptance validation error: You don't have permissions to specify the following namespaces in the appx manifest file of the package HeidiSQL.appx: restricted namespace: http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities

**Comment by ansgarbecker** [comment]
Just uploaded the first valid package in Microsoft's dev center, with the help of Marc - thanks a lot for his help here.

Now HeidiSQL awaits certification.

**Comment by wwelborn** [comment]
Hey @ansgarbecker, HeidiSQL is showing up in the store (at least in the US) but hitting the Get button and trying to download it throws this error:
![image](https://user-images.githubusercontent.com/35716211/36441617-1d919fca-1641-11e8-8cb6-d7960aa5eef7.png)

Based on the error message, it might be something you want to open a ticket against with MS. :)

**Comment by ansgarbecker** [comment]
Here in Germany it is not even listed, at least not as an app page in the store, only in the auto-suggest-pulldown on the search menu. The status of the review process in the dev center is still:
* Can get packages: yes
* Can see Store listing: pending

**Comment by wwelborn** [comment]
I just tried again and this time it was able to download and install. Isn't global CDN propagation fun?
![image](https://user-images.githubusercontent.com/35716211/36449277-5afce588-1658-11e8-8f9e-96e43dbc2962.png)

Thank you for releasing it through the store as well!

**Comment by ansgarbecker** [comment]
Yes!! See it now! Hehe, but that CDN is definitely **no** fun! :)
