### ISSUE TITLE
HeidiSQL cannot add new user with MariaDB 10.4

### ISSUE THREAD

**Issue by Candunc** [HeidiSQL/HeidiSQL#600]
## Steps to reproduce this issue

1. Login to MariaDB 10.4 using root user
2. Open the user manager
3. Click past 'column "user" is not available'
4. Click 'add user'

## Current behavior

HeidiSQL crashes.

## Expected behavior

HeidiSQL prompts for username, password, privileges ext.

## Possible solution

Unsure if the issue is with MariaDB 10.4 (Can add a user through command line) or with HeidiSQL.

## Environment

Server version: 

* **HeidiSQL version:** 10.1.0.5464
  
* **Database system and version:** 10.4.3-MariaDB-1:10.4.3+maria~stretch-log mariadb.org binary distribution
  
* **Operating system:** Debian Stretch
  

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3046330/bugreport.txt)

**Comment by ansgarbecker** [comment]
I suppose this is the same as #599, which I fixed 2 days ago. Please update your HeidiSQL to the latest build and report back if the problem persists.

**Comment by Candunc** [comment]
My bad. I downloaded the stable rather than the latest nightly.

**Comment by cece46** [comment]
https://mariadb.com/kb/en/library/mysqluser-table/

In MariaDB 10.4

![image](https://user-images.githubusercontent.com/32593390/56675722-1d6c4e00-66bd-11e9-817a-e17087916763.png)

**Comment by ansgarbecker** [comment]
@cece46 please update to the latest HeidiSQL build. That error should be fixed then.
