### ISSUE TITLE
Command line switch for named pipe truncated

### ISSUE THREAD

**Issue by tbayart** [HeidiSQL/HeidiSQL#601]
HeidiSQL 10.1.0.5464 (64 bits)
Environment : Windows 10 + Local SQL server

1: Start MSSQLLocalDB: 
"SqlLocalDB.exe start"
2: Retrieve LocalDB named pipe: 
"SqlLocalDB.exe info MSSQLLOCALDB"
3: Start HeidiSQL using command line switch: 
"heidisql.exe -n3 -S\\.\pipe\LOCALDB#04F38D45\tsql\query -W"
4: HeidiSQL error: Can't open named pipe to host: .
pipe: \\.\pipe\LOCALDB#04F38D45\tsql\q (2)

**Comment by ansgarbecker** [comment]
Is that "(2)" part of the error message?

**Comment by ansgarbecker** [comment]
Please retry with v12.0 and provide more feedback if still reproducible
