### ISSUE TITLE
SSH tunnel error dialog with plink.exe ver 7.1

### ISSUE THREAD

**Issue by yz778** [HeidiSQL/HeidiSQL#605]
## Steps to reproduce this issue

1. Setup SSH tunnel
2. Specify plink.exe location that points to plink release 0.71
3. Enter additional info and Open the connection

## Current behavior

Error dialog pops up with message
PLink: Using username "xxx"
Closing the error box, the connection works as expected

## Expected behavior

The error dialog should not pop up.

## Possible solution

Problem is that Plink release 0.71 behaves differently than previous versions (e.g. release .60). Running this:
plink.exe -ssh xxx@127.0.0.1 -P 22 -i "xxx.ppk" -N -L 3311:127.0.0.1:3306

Plink 0.71 returns:
Using username "xxx".
Access granted. Press Return to begin session.

whereas Plink 0.60 returns:
Using username "xxx".

HeidiSQL is not processing the default Plink .71 output properly. One possible (but maybe insecure) solution is add the parameter -no-antispoof when calling plink.exe. For example:

plink.exe -ssh xxx@127.0.0.1 -P 22 -i "xxx.ppk" -N -L 3311:127.0.0.1:3306 -no-antispoof

## Environment

Windows 10, running Plink 0.71.

* **HeidiSQL version:** 
10.1.0.5464 (64 bit)
* **Database system and version:** 
MySQL 5.7.25

**Comment by ansgarbecker** [comment]
See #577 - I already fixed that.

But thanks for the hint on `-no-antispoof`!
