### ISSUE TITLE
PostgreSQL JSONB type not recognized

### ISSUE THREAD

**Issue by yz778** [HeidiSQL/HeidiSQL#606]
## Steps to reproduce this issue

1. Create Table, add Column. JSONB is not in the dropdown.
2. Create table by SQL:
```
CREATE TABLE test (
    val1 JSON,
    val2 JSONB
)
```
3. Verify table created successfully:
```
SELECT
	column_name,
	data_type
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE table_name = 'test';
```
Shows
```
column_name   data_type
val1          json
val2          jsonb
```
4. Refresh DB browser, Edit table - Datatype for val2 column listed as UNKNOWN. Also in logs we see: `/* Unknown datatype "JSONB" for "val2". Fall back to UNKNOWN. */`

## Current behavior

JSONB data type not recognized.

## Expected behavior

JSONB data type should be recognized, it's  functionally equivalent to JSON.

## Possible solution

Add JSONB as valid datatype for PostgreSQL.

## Environment

* **HeidiSQL version:** 
10.1.0.5464
* **Database system and version:** 
psql (PostgreSQL) 10.7 (Ubuntu 10.7-0ubuntu0.18.04.1)

**Comment by albertotn** [comment]
Just found this blocking problem, when creatign a table with jsonb type, column is UNKNOWN:

![immagine](https://user-images.githubusercontent.com/12526457/81156811-9ec01700-8f86-11ea-90ce-cc5a72174dd0.png)

configuration order is jsonb type

**Comment by noxonsu** [comment]
same problem

**Comment by bpasha7** [comment]
same problem

**Comment by ansgarbecker** [comment]
Next build now supports `JSONB` columns:
![grafik](https://user-images.githubusercontent.com/7986591/102684423-a6ac8e80-41d8-11eb-9256-b43c49f9d37d.png)

However, not sure if editing such columns in the data grid or query grid fails, as it's binary data.
