### ISSUE TITLE
Window top and bottom not showing when maximizing on ubuntu.

### ISSUE THREAD

**Issue by phiter** [HeidiSQL/HeidiSQL#608]
## Steps to reproduce this issue

1. Open HeidiSQL 10.1.0.5520 on Ubuntu 18.10
2. If your window is not maximized, try to maximize it;
3. The top and bottom of the window may not appear

## Current behavior

The top parts of the window are not showing up

## Expected behavior

The window should look ok when you maximize it.

* **HeidiSQL version:** 
10.1.0.5520
* **Database system and version:** 
MySQL
* **Operating system:** 
Ubuntu 18.10

Relevant gif:

https://imgur.com/a/rNG2A9S

**Comment by ansgarbecker** [comment]
Does that also happen with the default "Windows" theme?

**Comment by phiter** [comment]
Nope! It works fine with the default theme.

![image](https://user-images.githubusercontent.com/12252332/55978710-d31fb180-5c66-11e9-97a9-70f069624b04.png)


By the way, the error with the Material theme only happens on my secondary display. On the primary display  (it's a laptop) it's fine. My secondary display's resolution is 1920 x 1080, my primary is 1366x768.

So I'm not sure if it is a resolution issue, but if I press Windows key + Up arrow instead of clicking the maximize button, it goes fullscreen nicely.

With the Windows theme, everything works alright.

**Comment by ansgarbecker** [comment]
Thanks for your feedback. I suppose this is another theme related issue then. Sigh..

**Comment by phiter** [comment]
Same thing happening on Windows10 Dark Theme.

![image](https://user-images.githubusercontent.com/12252332/55979233-0ca4ec80-5c68-11e9-8328-8a2f16765566.png)

**Comment by ansgarbecker** [comment]
@phiter could you please update HeidiSQL to the latest build and re-test? HeidiSQL is now compiled with the newest Delphi 10.4 version, which has several bugfixes for themes/styles. Probably related: #495

**Comment by isneep** [comment]
The issue remains on Ubuntu 18.04 LTS with wine 5.x and HeidiSQL 11.1

![image](https://user-images.githubusercontent.com/17259827/101358672-780aeb80-389b-11eb-83a1-8d8ecc10bf54.png)

![image](https://user-images.githubusercontent.com/17259827/101358750-94a72380-389b-11eb-82db-9d56b34390bd.png)

**Comment by ansgarbecker** [comment]
Closing this older issue, as I still have no clue how to fix it. My recommendation for Wine is just to use the default "Windows" theme. These themes all have issues, not only on Wine, also when you run them on Windows with a high DPI setting. Related: #1503
