### ISSUE TITLE
MySQL VIEW definition's UTF-8 problem

### ISSUE THREAD

**Issue by endo64** [HeidiSQL/HeidiSQL#61]
UTF-8 chars are broken in MySQL / MariaDB View definitions when open in HeidiSQL View Editor:

## Expected behavior

UTF-8 chars should be correct on view editor, db export to a file and to another database.

## Current behavior

UTF-8 chars are broken.

## Failure information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to reproduce

Create a view:

```sql
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `v_test` AS
select 'ĞÜŞİÖÇ' AS `col1`,'ğüşıöç' AS `col12`
```

Click on that view in HeidiSQL and see that Turkish characters are broken, shown as

```sql
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `v_test` AS
SELECT
    'ÄÃœÅÄ°Ã–Ã‡' AS col1,
    'ÄŸÃ¼ÅŸÄ±Ã¶Ã§' AS col12 ;
```

This can be fixed by using below SQL:

```sql
SELECT CAST(LOAD_FILE(
    CONCAT(
        IFNULL(@@GLOBAL.datadir, CONCAT(@@GLOBAL.basedir, 'data/')),
        'test/v_test.frm'
    )
) AS CHAR CHARACTER SET utf8);
```

related forum post: https://www.heidisql.com/forum.php?t=24623

* HeidiSQL version: 9.5.0.5201 (64bit)
* Database system + version: 10.2.10-MariaDB / MySQL 5.7
* Operating system: Windows 8.1 x64

**Comment by ansgarbecker** [comment]
Should be working in the next HeidiSQL build.

One thing I also want to fix along with this issue is that the .frm file on the server's hard disk has some encoding for international characters like ü, ö etc. HeidiSQL tries to load 'testü.frm' but the file is named 'test@1o.frm'. Perhaps I'll find a way to fix that.

**Comment by ansgarbecker** [comment]
There seems to be no handy SQL function for encoding an identifier just like MySQL or MariaDB do it when storing .frm files with international characters.

I found a helpful [blog article from Kolbe Kegel at MariaDB, about demystifying identifier mappings](https://mariadb.com/resources/blog/demystifying-identifier-mapping). But to repeat his steps HeidiSQL would need some internal mapping table for characters and probably even a own procedure. Even better would be a native Delphi procedure which does the same encoding. But that is too much effort only for getting the original formatted VIEW code in cases where the view name has international characters.

**Comment by endo64** [comment]
I'm not sure if this helps but, in MySQL Reference Manual, it says 

> The character_set_filesystem system variable controls interpretation of file names that are given as literal strings.

Please see https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_load-file and especially https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_character_set_filesystem which says: 

> The file system character set. This variable is used to interpret string literals that refer to file names, such as in the LOAD DATA INFILE and SELECT ... INTO OUTFILE statements and the LOAD_FILE() function. Such file names are converted from character_set_client to character_set_filesystem before the file opening attempt occurs. The default value is binary, which means that no conversion occurs. For systems on which multibyte file names are permitted, a different value may be more appropriate. For example, if the system represents file names using UTF-8, set character_set_filesystem to 'utf8'.

which could help.
If not we might consider integrating an external SQL command line formatter tool, something like http://architectshack.com/PoorMansTSqlFormatter.ashx (or a similar one)
