### ISSUE TITLE
I think you can open alipay donation, paypal is too cumbersome to use in China.

### ISSUE THREAD

**Issue by king-wyx** [HeidiSQL/HeidiSQL#611]
I think you can open alipay donation, paypal is too cumbersome to use in China.

**Comment by ansgarbecker** [comment]
According to its German Wikipedia page, Alibaba repeatedly gave user's data to the government of China. Are you aware of that?

**Comment by king-wyx** [comment]
Sorry, I am not quite sure.However, it is recommended to have a convenient way of donating in China.

**Comment by ansgarbecker** [comment]
I have just set up an account on Alipay. Now I don't know how to receive donations there. Could you help me with that?

**Comment by king-wyx** [comment]
You can download an Alipay app, find your own payment code, save the image to the local, and then put the image on the donation page.

**Comment by ansgarbecker** [comment]
I downloaded two different Alipay apps onto my smartphone, one was for Hongkong I think. In both I can't login with my email / password combination, which is accepted on their website.

**Comment by king-wyx** [comment]
You can enter your mobile phone number and choose International to register in the Alipay app used in Hangzhou.

**Comment by ansgarbecker** [comment]
That was it! Here's my QR code from the "collect" area in the app, perhaps you could be so nice and test if it's possible to use it at all?
![grafik](https://user-images.githubusercontent.com/7986591/68964180-0451f880-07d9-11ea-8186-b892901ff9bb.png)

**Comment by king-wyx** [comment]
The two-dimension code is correct, but when the transfer is in accordance with China's legal regulation, you need to carry out real-name certification, so that I can transfer the two-dimensional code.

**Comment by ansgarbecker** [comment]
OK I just entered my real name and country in the settings area, then the app asked me to add a bank card. The only one I have is a Visa card, but the app says that number is not supported.

**Comment by king-wyx** [comment]
You can find a bank card supported by Alipay or consult Alipay customer service.

**Comment by ansgarbecker** [comment]
I don't think I will get this working. I even don't know how to contact their customer service.

**Comment by Ameng0229** [comment]
On November 6, Visa China announced that it has reached a cooperation with Tencent to provide WeChat payment services for international Visa cardholders. Yu Xueli, president of Visa Greater China, said this is not only good news for consumers who travel to mainland China, but also exciting news for the entire payment industry.

It's not just WeChat Pay that makes this change. On November 6, Alipay, a subsidiary of Ant Financial, posted a message on its Twitter account that foreign tourists entering the mainland of China can register with a foreign mobile phone number and choose to use Alipay ’s international version, using QR codes to pay, consume or travel .
By Sohu NEWS 2019.11

Although Alibaba provides information to the government, it is limited to criminals, and normal citizens do not have to worry about information leakage. This my opinion

**Comment by ansgarbecker** [comment]
I recently created a payment page where you can donate via credit cards: https://www.heidisql.com/donate-stripe.php

**Comment by ernesthenry** [comment]
Hello @ansgarbecker , Were you able to sort this issue

**Comment by ernesthenry** [comment]
I am working on integrating Alipay donations into my website. Does Alipay support donations? I would be glad if anyone out there can share their opinion.

**Comment by ansgarbecker** [comment]
@ernesthenry no, I gave it up after failing with the integration of my Visa card into my Alipay account.
