### ISSUE TITLE
Creating event with BEGIN END fails

### ISSUE THREAD

**Issue by victorpapp** [HeidiSQL/HeidiSQL#613]
## Steps to reproduce this issue

1. Connect to a MySQL database
2. Create new event, name it __my_event
3. Add an UPDATE query between BEGIN and END
4. Set Timing EVERY 1 MINUTE, or any other value

## Current behavior

The event is never fired, bcs in the information_schema.events table in the EVENT_DEFINITION field the value the BEGIN keyword is not separated with space from the query itself (see attached screenshot). If I remove the BEGIN and END, the event is firing, but without BEGIN and END it is not possible to execute more than one query.

## Expected behavior

In the information_schema.events column the BEGIN should be separated with space.
The event should be able to execute 2 or more queries.

![01](https://user-images.githubusercontent.com/49681591/56207938-a39ee980-6058-11e9-99d5-5d1e6427cb82.png)

![02](https://user-images.githubusercontent.com/49681591/56207939-a39ee980-6058-11e9-91e0-def44ac7010d.png)

## Possible solution

Fix updating information_schema.events table, EVENT_DEFINITION field.

## Environment

Heidi SQL Portable 64-bit

* **HeidiSQL version:** 
  
10.1.0.5532

* **Database system and version:** 
  
MySQL 8.0.11

* **Operating system:** 
  
Windows 10

**Comment by ansgarbecker** [comment]
In IS.events, the event_definition contains line feeds for me. HeidiSQL just does not show these in its single line cells. But if I hover over it I can see it:
![grafik](https://user-images.githubusercontent.com/7986591/56230263-356c1e00-607c-11e9-8ccc-002a1f877cc0.png)

Also, if I later edit this event, the code still contains these line feeds.

The reason why my event is not fired is the disabled scheduler:
![grafik](https://user-images.githubusercontent.com/7986591/56230414-75cb9c00-607c-11e9-9117-d4318b58c0db.png)

Now that I enabled it, the event runs again and again, as expected.

Can you reproduce that?

**Comment by victorpapp** [comment]
1. Yes, on hover over event_definition i see line breaks. Confirmed,
2. The event_scheduler var was ON, other events worked fine.
3. Now I upgraded to latest build 5535, now events work perfectly, problem solved.
