### ISSUE TITLE
save content of tab Query despite query field is empty

### ISSUE THREAD

**Issue by andipfaff** [HeidiSQL/HeidiSQL#614]
1. Open HeidiSQL, do a manual query like "show table status;"
2. Clear the query field (Strg-A, DEL)
3. Quit HeidiSQL
4. You'll be asked if you want to save the query

Using newest nightly build on Win10 64bit

**Comment by andipfaff** [comment]
![Unbenannt](https://user-images.githubusercontent.com/4201912/56209116-07261880-6053-11e9-978b-6a66b4d689fb.png)

**Comment by ansgarbecker** [comment]
Yes, indeed, if a tab contains just unsaved text and you remove it, Heidi should not ask to save it to a (new) file. Even the tab restore feature should discard such tabs.

**Comment by ansgarbecker** [comment]
Related commit: fdd73b1ffbd81a277fc2454bbf8656383d8049fc
