### ISSUE TITLE
SQL Error (0): Operation is not allowed when the object is closed

### ISSUE THREAD

**Issue by igitur** [HeidiSQL/HeidiSQL#615]
## Steps to reproduce this issue

- Open HeidiSQL
- Connect to a database from the session manager
- Browse to a table and select the `Data` tab to view the table's contents
- Close the selected database connection from the menu bar.
- Open a different database on a different server from the session manager
- Browse to a table and select the `Data` tab to view the table's contents

## Current behavior

An error occurs:

![image](https://user-images.githubusercontent.com/145854/56219902-d3092280-6067-11e9-8b16-1bad0fc166d4.png)

## Expected behavior

No error occurs

## Possible solution

Obviously the connection management is slightly flawed.

## Environment

* **HeidiSQL version:** 
10.1.0.5532
* **Database system and version:** 
MS SQL 2016
* **Operating system:** 
Windows 7 64b

**Comment by igitur** [comment]
@ansgarbecker Can you replicate this?

**Comment by ansgarbecker** [comment]
Yes, I can reproduce a crash, although the exact place is a different one:

```
008cb1c7 heidisql.exe dbconnection    6910  +3 TDBQuery.Modified
00ab0253 heidisql.exe Main            8460 +10 TMainForm.DBtreeFocusChanged
0075e0f2 heidisql.exe VirtualTrees   19854  +2 TBaseVirtualTree.DoFocusChange
00754c3b heidisql.exe VirtualTrees   14574  +5 TBaseVirtualTree.SetFocusedNode
007e1243 heidisql.exe apphelpers      1636  +5 SelectNode
00aabcf0 heidisql.exe Main            7049 +12 TMainForm.SetActiveDatabase
00a9ecfa heidisql.exe Main            3977 +30 TMainForm.InitConnection
009a0e9e heidisql.exe connections      358  +8 Tconnform.btnOpenClick
```

**Comment by ansgarbecker** [comment]
I just fixed some potential causes for this issue. Not sure where exactly that happens for you, but I don't get an exception any longer with the new build.

**Comment by igitur** [comment]
Thanks. So far it's looking solved. I'll keep monitoring.

**Comment by igitur** [comment]
Ok, this is solved. Makes my life a lot easier! Thanks
