### ISSUE TITLE
Double-click on Save button: crash in TfrmRoutineEditor.ApplyModifications

### ISSUE THREAD

**Issue by victorpapp** [HeidiSQL/HeidiSQL#616]
## Steps to reproduce this issue

1. Connect to MySQL database
2. Create new Stored Procedure
3. Enter its name, add some statements to body
4. Click Save, then while save is in progress, click Save again

## Current behavior
I see a runtime error, see attached

## Expected behavior
2nd Save click should ignored

## Possible solution
Disable Save button until save completed

## Environment

* **HeidiSQL version:** 
Portable 10.1.0.5535, but I seen this behaviour on previous versions as well

  
* **Database system and version:** 
5.5.59, 8.0.11

  
* **Operating system:** 
Windows 10
![save_stored_procedure](https://user-images.githubusercontent.com/49681591/56235351-f051e700-608f-11e9-83e5-5b15beaadbdf.png)

**Comment by rentalhost** [comment]
Reproducible on **r5560**.

[bugreport-issue616.txt](https://github.com/HeidiSQL/HeidiSQL/files/3174967/bugreport-issue616.txt)
