### ISSUE TITLE
Revamp sorting icon

### ISSUE THREAD

**Issue by Qrokqt** [HeidiSQL/HeidiSQL#618]
## Steps to reproduce this issue

1. Sort a column
2. See sort direction indicator

## Current behavior

It shows a narrow arrow with the letters A and Z.

## Expected behavior

I preferred the simple triangle or chevron.

## Possible solution

Add option to change it back to the old icon.

## Environment

* **HeidiSQL version:** 10.1.0.5464

**Comment by ansgarbecker** [comment]
That won't be a preference option. But I am thinking the same - the simple icon was more readable than the new one.

**Comment by leeoniya** [comment]
@ansgarbecker 

i would also prefer a more obvious icon of some kind. the current arrow is very difficult to see especially on high-dpi displays when you're trying to make out the couple pixels in the tiny arrowhead. speaking for myself, the AZ/ZA is just clutter, i always prefer a clear arrow and no other symbols. if i need further clarification i just visually scan the data in the grid.

the current arrows look like this:

🠑 🠓

some options available in unicode http://xahlee.info/comp/unicode_arrows.html:

▲ ▼  // my preference
⮝ ⮟ // also good (less heavy)
🠝 🠟
🡅 🡇
🡹 🡻

the reason i came here is because there's actually an issue with the current arrow, where it does not invert direction when the column is sorted and always remains downward-pointing.

![image](https://user-images.githubusercontent.com/43234/85294934-d9154300-b464-11ea-948f-b1e72e88ad95.png)

**Comment by ansgarbecker** [comment]
I made the arrows thicker now, that should do it. Please note you can also use the Icons8 icon set, in Tools > Preferences, which also has quite clear sorting arrows.
If there is an issue with a remaining downward icon, I can't reproduce it here.

**Comment by leeoniya** [comment]
thanks, thats a big improvement. i still think that both ZA/AZ *and* arrows together are unnecessary and single triangle would be both cleaner and more clear. but i'll live with it!

what i've done in my UIs with multi-column sorting uses an arrow and sorting position superscript, which i find helpful to see at a glance than having to drop down a "sorted by" to see this.

```
|    ¹▲ first_name   |       ²▼ last_name      |
```

**Comment by ansgarbecker** [comment]
These superscript numbers are indeed helpful, for knowing which comes first, second and so on. HeidiSQL just needs icons for these, not just some character. But that would be doable if I restrict that to the first 9 ones, plus one with an "x" on it maybe.

**Comment by leeoniya** [comment]
i think these are quite elegant and can be converted to images from svg:

https://fontawesome.com/icons/chevron-up?style=solid
https://fontawesome.com/icons/chevron-down?style=solid

**Comment by ansgarbecker** [comment]
I picked up your idea and put some hours into it. Here's how it looks in the next build:
![grafik](https://user-images.githubusercontent.com/7986591/85978989-03747c80-b9e0-11ea-9f45-16e859daf8ef.png)

* Sort icons are now text, not images like I said before
* Index icons can be displayed seperately to the sort icons. Up to now, only one icon was shown.
* All headers are now left aligned, including numeric columns. The cell text of numeric columns is however still right aligned.

**Comment by ansgarbecker** [comment]
I think I have the arrows in the wrong direction now...

**Comment by leeoniya** [comment]
nice!

it blends a bit much with the column text now that everything is black. can the arrow + superscript get another color, like purple?

also, in your image it looks too close to `delta`, too. making it look like `delta³`. maybe it's worth experimenting with putting the index keys on the left side of the column name (and stick them to the left) and the sorting arrow+index on the right (and stick it to the right). and simply center-align the text.

![col](https://user-images.githubusercontent.com/43234/86020548-a8e21d00-b9ed-11ea-8675-07f046bf99c6.png)

**Comment by ansgarbecker** [comment]
> it blends a bit much with the column text now that everything is black

It's not black - it's the "Gray text" system color, which is medium gray in most cases. Probably it should get even lighter, but purple is a bad choice, as that can be mixed up with binary data in cells which are also purple.

I also had more space to the left of the superscript number, and saw that this raises the chance many headers get an ellipsis:
![grafik](https://user-images.githubusercontent.com/7986591/86021261-3000b680-ba29-11ea-8fc0-3cd1da3a9b74.png)

With the icons on the left I think is bad user experience, as then there are icons on both sides, which can confuse the eyes if you have many columns.

Well, we could keep discussing this for ages I guesss :)

**Comment by leeoniya** [comment]
another option might be something like this (if possible) and the sorting arrow's size is increased:

![image](https://user-images.githubusercontent.com/43234/86025167-8521d580-b9f3-11ea-9621-56931380be5b.png)

**Comment by ansgarbecker** [comment]
Here's how that number would look like with a biggest possible triangle:

![grafik](https://user-images.githubusercontent.com/7986591/86047297-fc388780-ba4e-11ea-9cb1-08cb94a5c54a.png)

I searched on Google for other ideas, and this one was the only one I found. Looks like only very few had that idea before:
https://vaadin.com/docs/v8/framework/components/components-grid.html

But I think I got it now, I just moved the number right besides the arrow, nearer at the arrow, and made its color slightly lighter:

![grafik](https://user-images.githubusercontent.com/7986591/86051539-dd89bf00-ba55-11ea-8898-2484aa702617.png)

**Comment by leeoniya** [comment]
not sure why the subscript variant is not showing up for me.

![image](https://user-images.githubusercontent.com/43234/86053810-b49a0780-ba1e-11ea-8079-85ab7ef77ccc.png)

> and made its color slightly lighter:

i really think the icon is too light and hurts usability - it should be as obvious as it was with Z/A & arrow. now that there's clear separation between the superscript and the column name, i would say leave it the same color as the rest of the text.

**Comment by ansgarbecker** [comment]
> not sure why the subscript variant is not showing up for me.

That's because your selected font does not have the subscript characters. I have to find a way to use the normal numbers with a smaller font size.

> i would say leave it the same color as the rest of the text.

Agreed.

**Comment by ansgarbecker** [comment]
Decreasing the font size somehow doesn't have an effect, I can't find out why. However, here's what I have now:

![grafik](https://user-images.githubusercontent.com/7986591/86089170-05097780-baa8-11ea-99be-20068505729e.png)

Here once again with the gray text color, isn't that less intrusive?

![grafik](https://user-images.githubusercontent.com/7986591/86089482-9aa50700-baa8-11ea-825b-445e133765f9.png)

**Comment by leeoniya** [comment]
the superscript seems to work fine tho and can be used for both ASC and DESC. and i definitely prefer it instead of the huge numbers.

can you just leave it as superscript and middle-align both triangles (right now the up triangle looks middle-aligned but the down triangle is raised). the light blue looks okay but it somewhat clashes with the numeric cells, and it might not work well with custom colors if it's not configurable. i would leave it same as text unless it can be made configurable via pref.

**Comment by ansgarbecker** [comment]
Here we go:

![grafik](https://user-images.githubusercontent.com/7986591/86091830-d5a93980-baac-11ea-945e-9bb93be347a6.png)

**Comment by leeoniya** [comment]
yep, that's a winner.

**Comment by ansgarbecker** [comment]
Tada, we have a new Wine issue.
