### ISSUE TITLE
Add column SRID restriction

### ISSUE THREAD

**Issue by Qrokqt** [HeidiSQL/HeidiSQL#619]
## Steps to reproduce this issue

1. Want to add SRID to column
2. ???

## Current behavior

There doesn't seem to be a way to make a spatial column restricted to a SRID.

## Expected behavior

A way to restrict a column's SRID allowing spatial indexes to work.

## Possible solution

Add another column in the table editor to set the SRID.

According to this: https://dev.mysql.com/doc/refman/8.0/en/spatial-type-overview.html it should be as simple as `CREATE TABLE geom (g GEOMETRY NOT NULL SRID 4326);`

## Environment

* **HeidiSQL version:** 10.1.0.5464
  
* **Database system and version:** MySQL 8.0.15

**Comment by stefano-xy** [comment]
This is indeed still a problem in v12.8: support to set a SRID for `GEOMETRY` columns (but also for `POINT`, `POLYGON`, ...) at table creation or modification time doesn't seem to be available.

**Comment by ansgarbecker** [comment]
Next build has a new "SRID" column in the table editor, which shows an existing SRID, and which can be changed textwise:

![grafik](https://github.com/user-attachments/assets/a83f955e-837b-4a1b-935c-12373c3202d6)

I noticed I could not find the exact MySQL version which started support for that, so I assumed it was v8.0 - is that correct?

Would be nice if you give the next build a test and give feedback.

**Comment by stefano-xy** [comment]
So I'm using MySQL 8.0, and it indeed refuses to create spatial indices if the column doesn't have any SRID set. I can easily test when I see SRID support added.

**Comment by ansgarbecker** [comment]
Current build is compiled some minutes ago. You may update in HeidiSQL through Help > Check for updates.

**Comment by stefano-xy** [comment]
Ok, tested, it works but the column disappears when I change table or view. I have to make it visible all the time. Logically, I would put it next to the column type, like where the length is.

**Comment by ansgarbecker** [comment]
Are you really sure it disappears? Or is it _out of sight_, visible when scrolling to the right?

**Comment by stefano-xy** [comment]
Ok, it works as expected. I was somehow confused.

**Comment by ansgarbecker** [comment]
Ok I'll close this then.
