### ISSUE TITLE
Column comments are not visible

### ISSUE THREAD

**Issue by halmai** [HeidiSQL/HeidiSQL#62]
## Expected behavior

If I add a comment to a table column then the comment is not shown in heidisql.

## Current behavior

I want to see all the column comments, even if they are multiline comments. 

### Steps to reproduce

Steps for reproducing the issue:

1. I create a table:
```sql
CREATE TABLE x (v int);
```

2. 
I add a comment to the column:
```sql
COMMENT ON COLUMN x.v IS 'blah';
```

3. The CREATE code shows empty comment in heidisql:

```sql
CREATE TABLE "x" (
	"vs" TEXT NULL DEFAULT NULL
)
;
COMMENT ON COLUMN "x"."vs" IS E'';
```

### Context

Heidi build: 5201
postgres: PostgreSQL 10.1, compiled by Visual C++ build 1800, 64-bit
Win7 Pro SP 1

**Comment by ansgarbecker** [comment]
Related change from 2014, not yet touched again: 3d29d13b426f1b1eaf3f0755829c50d763d16760

**Comment by ansgarbecker** [comment]
Issue is caused by quoted strings being prepended by an `E`, see https://www.heidisql.com/forum.php?t=18657 for the reason.

**Comment by ansgarbecker** [comment]
So the next build does not use that `E` prefix for strings any longer. Instead, HeidiSQL just escapes as follows:
* `'` => `''`
* for `LIKE` strings:
  * `%` => `\%`
  * `_` => `\_`

For these 2 backslash usages, PostgreSQL does not seem to require that `E` prefix.
