### ISSUE TITLE
Second export to clipboard causes crash (OutOfMemoryError)

### ISSUE THREAD

**Issue by DAC-Tony** [HeidiSQL/HeidiSQL#620]
## Steps to reproduce this issue

1. Step 1; Open any DB with any table.
2. Step 2; Switch to Data tab
3. Step 3; Right click datas and select Export grid rows
4. Step 4; Choose Copy to clipboard, Excel CSV and Complete and click OK.
5. First time do the above is OK but second time will cause crash.

## Current behavior
First time is OK but second time will cause crash.

## Expected behavior
The second copy should override the first copy.

## Possible solution
I guess the second copy didn't override the first copy but append to the first copy in clipboard, which caused OutOfMemoryError
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3093176/bugreport.txt)

## Environment
* **HeidiSQL version:** 
HeidiSQL Portable 10.1.0.5538
* **Database system and version:** 
MySQL 5.5.53
* **Operating system:** 
Windows 10 x64

**Comment by anselal** [comment]
I confirm that too !!!
This is a very annoying bug.
Waiting for the hotfix !!!

**Comment by lucashtc** [comment]
The same error occurs to me.
I always use this function for csv format.
Waiting for correction.

**Comment by lifof** [comment]
+1

**Comment by ansgarbecker** [comment]
Should be fixed with 155cedace9102c06d4f68f7095f3ffb3ab0f0275 - reverts a part of 406ab56060f370c2414c5041d766203cd3b75c32 . Crossing fingers I did not introduce another crash now.
