### ISSUE TITLE
putty  -unknown option batch

### ISSUE THREAD

**Issue by webdbase** [HeidiSQL/HeidiSQL#621]
![hp](https://user-images.githubusercontent.com/11588031/56498996-0ab31700-650d-11e9-919e-9ec805364569.png)

I haven't used this option (a tunneled DB connection via putty) for a while, but roday I noticed the problem.
I picked a random older version, like 5507 and everything works fine.
My putty is the latest version - 0.71

**Comment by ansgarbecker** [comment]
You should recheck if you're using the latest `plink` version. You are by the way not using `plink`, but `putty.exe`. That's not supported by HeidiSQL.

**Comment by ansgarbecker** [comment]
![grafik](https://user-images.githubusercontent.com/7986591/56500917-071f9000-650d-11e9-929d-157fea61d188.png)

**Comment by webdbase** [comment]
Yes, you are right. I was using putty, not plink, but it worked fine with putty before, until you introduced the 'batch' option.
Anyway, thank's for the tip :) I'm using plink now.
