### ISSUE TITLE
Error on file export (csv)

### ISSUE THREAD

**Issue by rafaelmb** [HeidiSQL/HeidiSQL#625]
## Steps to reproduce this issue

The bug happens at the time at second file export. It looks like #620 but I don't get Out Of Memory error.

1. Step 1; Export csv data
2. Step 2; run query
3. Step 3;  Export again
4. Then I get Access Violation

## Current behavior

Access Violation and I'm unable to export files until HeidiSQL restarts

## Expected behavior

Was able to export a lot of csv files on 10.0

## Environment

In the bug report below

* **HeidiSQL version:** 
Tested in 10.1.0.5545 
* **Database system and version:** 
Mysql 5.7.25
* **Operating system:** 
Windows 10

date/time          : 2019-04-25, 11:22:04, 223ms
computer name      : DESKTOP-2V44G4I
user name          : ZECA
registered owner   : ZECA / Microsoft
operating system   : Windows 10 Tablet PC x64 build 17134
system language    : Portuguese
system up time     : 4 days 20 hours
program up time    : 14 minutes 30 seconds
processors         : 4x Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
physical memory    : 1964/16298 MB (free/total)
free disk space    : (C:) 13,61 GB
display mode       : 1920x1080, 32 bit
process id         : $4bb0
allocated memory   : 113,64 MB
largest free block : 131025,95 GB
executable         : heidisql.exe
exec. date/time    : 2019-04-23 09:39
version            : 10.1.0.5545
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $9d4a93f6, $28964eb2, $28964eb2
exception number   : 2
exception class    : EAccessViolation
exception message  : Access violation at address 000000000040E235 in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF.

main thread ($2268):
0040e235 heidisql.exe System                  TObject.Free
00541a41 heidisql.exe System.Classes          TStringStream.Destroy
0054163b heidisql.exe System.Classes          TStringStream.Create
00d39462 heidisql.exe exportgrid      563 +40 TfrmExportGrid.btnOKClick
006a2231 heidisql.exe Vcl.Controls            TControl.Click
006d96e6 heidisql.exe Vcl.StdCtrls            TCustomButton.Click
006da612 heidisql.exe Vcl.StdCtrls            TCustomButton.CNCommand
0040e9d2 heidisql.exe System                  TObject.Dispatch
006a1b2d heidisql.exe Vcl.Controls            TControl.WndProc
006a8a0a heidisql.exe Vcl.Controls            TWinControl.WndProc
006d9130 heidisql.exe Vcl.StdCtrls            TButtonControl.WndProc
006a1620 heidisql.exe Vcl.Controls            TControl.Perform
006a8bf9 heidisql.exe Vcl.Controls            DoControlMsg
006a9d63 heidisql.exe Vcl.Controls            TWinControl.WMCommand
008449a3 heidisql.exe Vcl.Forms               TCustomForm.WMCommand
0040e9d2 heidisql.exe System                  TObject.Dispatch
006a1b2d heidisql.exe Vcl.Controls            TControl.WndProc
006a8a0a heidisql.exe Vcl.Controls            TWinControl.WndProc
0083fe7d heidisql.exe Vcl.Forms               TCustomForm.WndProc
00abe940 heidisql.exe SizeGrip        256 +36 TSizeGrip.NewWndProc
006a7c3a heidisql.exe Vcl.Controls            TWinControl.MainWndProc
0055c5a3 heidisql.exe System.Classes          StdWndProc
7ff84b51 USER32.dll                           SendMessageW
006e938f heidisql.exe Vcl.StdCtrls            TButtonStyleHook.DoClick
006e9826 heidisql.exe Vcl.StdCtrls            TButtonStyleHook.WMLButtonUp
0040e9d2 heidisql.exe System                  TObject.Dispatch
007c7df4 heidisql.exe Vcl.Themes              TStyleHook.WndProc
007c8154 heidisql.exe Vcl.Themes              TMouseTrackControlStyleHook.WndProc
006e9482 heidisql.exe Vcl.StdCtrls            TButtonStyleHook.WndProc
007c73a5 heidisql.exe Vcl.Themes              TStyleHook.HandleMessage
00bb6ba9 heidisql.exe Vcl.Styles              TStyleEngine.HandleMessage
007c2e1c heidisql.exe Vcl.Themes              TStyleManager.HandleMessage
006a60c4 heidisql.exe Vcl.Controls            TWinControl.DoHandleStyleMessage
006a8195 heidisql.exe Vcl.Controls            TWinControl.WndProc
006d9130 heidisql.exe Vcl.StdCtrls            TButtonControl.WndProc
006a7c3a heidisql.exe Vcl.Controls            TWinControl.MainWndProc
0055c5a3 heidisql.exe System.Classes          StdWndProc
7ff84b51 USER32.dll                           DispatchMessageW
0084dffe heidisql.exe Vcl.Forms               TApplication.ProcessMessage
0084e073 heidisql.exe Vcl.Forms               TApplication.HandleMessage
008470c3 heidisql.exe Vcl.Forms               TCustomForm.ShowModal
00da5612 heidisql.exe Main           3224  +4 TMainForm.actExportDataExecute
0055b130 heidisql.exe System.Classes          TBasicAction.Execute
006763c5 heidisql.exe Vcl.ActnList            TCustomAction.Execute
0055ae24 heidisql.exe System.Classes          TBasicActionLink.Execute
00824967 heidisql.exe Vcl.Menus               TMenuItem.Click
0082715e heidisql.exe Vcl.Menus               TMenu.DispatchCommand
00829485 heidisql.exe Vcl.Menus               TPopupList.WndProc
00829385 heidisql.exe Vcl.Menus               TPopupList.MainWndProc
0055c5a3 heidisql.exe System.Classes          StdWndProc
7ff84b51 USER32.dll                           DispatchMessageW
0084dffe heidisql.exe Vcl.Forms               TApplication.ProcessMessage
0084e073 heidisql.exe Vcl.Forms               TApplication.HandleMessage
0084e4c1 heidisql.exe Vcl.Forms               TApplication.Run
00de5c35 heidisql.exe heidisql         86 +27 initialization
7ff84b8e KERNEL32.DLL                         BaseThreadInitThunk
7ff84bd4 ntdll.dll                            RtlUserThreadStart

main thread ($2268), inner exception level 1:
>> EAccessViolation, Access violation at address 000000000048DB2E in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF
0048db2e heidisql.exe System.SysUtils TEncoding.GetBytes

**Comment by ansgarbecker** [comment]
I'm very sure the cause was the same, which should now be fixed. Please update and test yourself. I can no longer reproduce the issue.

**Comment by rafaelmb** [comment]
Tested now, it's fixed. Thank you!
