### ISSUE TITLE
Wrong word in Danish translation

### ISSUE THREAD

**Issue by petersone** [HeidiSQL/HeidiSQL#627]
## Steps to reproduce this issue

1. Select lines in command window
2. Right click selection

## Current behavior

"Kør" is a wrong translation of Cut.
![Right-click-error-DK](https://user-images.githubusercontent.com/12168546/56788569-20238c00-6800-11e9-84a3-4a803629e24a.png)

## Expected behavior

Use the Danish word "Klip"

## Possible solution

Fix it!

## Environment

DK translation of user interface.

* **HeidiSQL version:** 
  10.1.0.5546

* **Operating system:** 
  Windows 10

**Comment by ansgarbecker** [comment]
Translation are managed on Transifex. Danish has quite a large pool of yet untranslated strings. Probably you could help out here?
If yes: you will need to log into https://www.transifex.com/david.proweb/heidisql/dashboard/ , then navigate to the Danish translation.
If no, I can myself fix this one word as you proposed, but my Danish is a bit rusty... ;) so I won't be able to get it fully translated.

**Comment by WesleyM77** [comment]
Might I suggest putting that Transifex link in the readme and on Heidi's site (not in a forum post) so people can find the way to contribute easier?

**Comment by ansgarbecker** [comment]
Yes of course. It's already in the [credits section of the help page](https://www.heidisql.com/help.php#credits), but I guess you mean in the [readme.md](https://github.com/HeidiSQL/HeidiSQL/blob/master/readme.md) ?

**Comment by WesleyM77** [comment]
Yeah, that would probably be a good place for it since most people looking to contribute in some way are going to read that. Also didn't realize it was in the credits section.

**Comment by ansgarbecker** [comment]
I just added a note to the readme file.

So I guess I can close this issue. The danish word in question may still be wrong translated, but probably you are going to fix that on Transifex now?

**Comment by petersone** [comment]
I tried to translate multiple strings... but they end up in the group of "not approved" words - where many other Danish translations also reside (right now 836 translations).
It's fair not to be able to approve own translations... but I should then approve translations done by others - but how do I do that - I cannot find the "approve button"... ;-)

**Comment by ansgarbecker** [comment]
I was not aware of the fact that reviewing cannot be done by translators. I wonder how the current strings were reviewed, as I did not do so.

However, I changed your role from translator to reviewer, and I hope you still can translate now:
![grafik](https://user-images.githubusercontent.com/7986591/57397565-4c121a80-71cd-11e9-8e71-9721480fd2a1.png)

Could you please test if you still can translate new strings, and if you can mass-review unreviewed translations?

**Comment by ansgarbecker** [comment]
Did we both think your done translations were not overtaken into the latest builds? They are there, and I see `Klip` as a translation for `Cut`. Unfortunately there is also `Cu&t`, which translates to `&Kør`. Maybe that was just the misunderstanding? I should again change your role to translator..

**Comment by petersone** [comment]
Looking at Transifex now... I'm not a reviewer.
![Transifex](https://user-images.githubusercontent.com/12168546/57431986-ce81f500-7234-11e9-82e6-72e6512d00ae.png)

**Comment by ansgarbecker** [comment]
Yes, you said so, and you are right - some are not approved. But as said, I'm sure they don't _need_ to be approved. And be aware we have "Cut" and "Cu&t", of which the latter one is translated to "Kør". Only "Cut" is translated to "Klip". You need to fix the wrong translation for "Cu&t".

**Comment by petersone** [comment]
Where can I read about the use of & as part of keys?

**Comment by ansgarbecker** [comment]
The & is a Delphi thing. It tells the compiler to use the following character as a hotkey. Nothing special for the translation.

**Comment by petersone** [comment]
Cu&t has been translated.

Q: How should "we" handle the & operator, when the DK word doesn't have the same characters as in EN?
Example: Cut -> Klip
So Cu&t marks "t" as hotkey... what to do in the DK translation?

**Comment by ansgarbecker** [comment]
Ah, good question.

The simplest thing is just to leave that & away from it in the translated word. You could (but I don't recommend) adding a & before a character you like, but you will never know if that collides with other hotkeys. So, just leave it away I'd say.
