### ISSUE TITLE
Feature Request: Bind parameters text field to expand wider

### ISSUE THREAD

**Issue by WesleyM77** [HeidiSQL/HeidiSQL#629]
## Steps to reproduce this issue

1. Write a query using a parameter or two.
2. Check the bind parameters checkbox in the UI block to the right of the query tab.
3. Widen the UI block & observe the "Set Value" fields not expanding to take up white space between the parameter name and the beginning of the field. 
![2019-04-26_10-08-58](https://user-images.githubusercontent.com/22208037/56814061-5109be00-680c-11e9-9ecf-285711be3ab0.gif)

## Current behavior

The field pretty much stays the same width.

## Expected behavior

I would expect the field to widen to take up the room given.

## Possible solution

Give more room to the fields and allow them to widen given the space. I think the parameter diamonds could move to the left a bit to give more space to the text field.

## Environment

* **HeidiSQL version:** 
10.1.0.5546
* **Operating system:** 
Win 10

**Comment by WesleyM77** [comment]
Still an issue in 10.2.0.5616

**Comment by ansgarbecker** [comment]
Normally this is not a real problem or?

**Comment by WesleyM77** [comment]
Not often, but when working with dates and datetimes, it's a little cramped, especially when editing. I know you can click the three dots to open a dialog box to a bigger editor, but that get's a little annoying when you're entering a bunch of params.

Examples:
![heidisql_2019-07-09_08-02-03](https://user-images.githubusercontent.com/22208037/60886527-3a2a1380-a220-11e9-839f-86d4b0c6ff09.png)
![heidisql_2019-07-09_08-00-35](https://user-images.githubusercontent.com/22208037/60886528-3a2a1380-a220-11e9-9bce-9a1f944e89b6.png)

**Comment by WesleyM77** [comment]
Just checking back in with this request. Editing dates in the fields is rather annoying,

**Comment by ansgarbecker** [comment]
Looking at the right place in the code, I believe that was a bug - I used the smaller pixel value of `tree.width/3` and `100`. I just changed that to using the bigger value, which now makes the column wider when the helpers box is widened. Please check the next build.

**Comment by WesleyM77** [comment]
Much better! Would prefer `tree.width/2` but it's not that big of a deal either way. Thanks for looking into this!
