### ISSUE TITLE
System Error. Code: 1400. Invalid window handle

### ISSUE THREAD

**Issue by jhansen31** [HeidiSQL/HeidiSQL#63]
## Expected behavior
Upon closing app version 9.5.0.5204 the app presented a crash dialog

## Current behavior
One time event - works fine after restarting

## Failure information (for bugs)
N/A

### Steps to reproduce

Please provide detailed steps for reproducing the issue.
1. Upgraded to 9.5.0.5204
2. Move a few columns around on a MariaDB database on a Synology NAS
3. When done with editing data simply closed app by clicking on the X upper right hand corner
4. At this point the app presented a crash dialog with ability to save enclosed report.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.5.0.5204
* Database system + version: Synology NAS MariaDB 10.0.32
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/1596122/bugreport.txt)

* Operating system: Windows 10 x64 build 16299

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by ansgarbecker** [comment]
The callstack says the error is somewhere in the Windows API, without a hint to a specific line of code in HeidiSQL itself.

Perhaps you have some tool installed which tweaks the look or the behaviour of a window? Is HeidiSQL the only application which crashes? No clue, just guessing.

**Comment by jhansen31** [comment]
Ansgar
I do have a start menu tweak called ClassicShell. That is the only app that modifies the behavior. The only app that crashes is HeidiSQL but to be truthful it just happened once and has behaved ever since. It happened right after the update and after I opened it, used it and then closed it is when it crashed. Has not happened since.
I will continue to monitor and report any other crashes if they happen.
Keep up the good work.

John Hansen
jwhansen@live.com
________________________________

**Comment by ansgarbecker** [comment]
Ok, thanks for the update!

I'm closing this issue as it's not yet reproducible. Just report back as you said when the crash happens again.
