### ISSUE TITLE
Wine 4.6 + HeidiSQL 10.1 - Access violation ... in module 'user32.dll'

### ISSUE THREAD

**Issue by hrvoj3e** [HeidiSQL/HeidiSQL#630]
## Error
> Access violation ... in module 'user32.dll'

See image bellow.

**Cannot save dump because it opens 20+ windows in a few seconds and save button doesn't respond.**

## Steps to reproduce this issue

```
wine ~/.heidisql/heidisql.exe


0027:fixme:dwmapi:DwmIsCompositionEnabled 0x6dbd1518
002c:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x69ebd3de, context 0x956520, init_notify 0, handle 0x124fa10): stub
0042:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
0042:err:winediag:gnutls_initialize failed to load libgnutls, no support for pfx import/export
0042:err:winediag:schan_imp_init Failed to load libgnutls, secure connections will not be available.
0042:fixme:dwmapi:DwmIsCompositionEnabled 0x6d5d3018
0044:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0cb608, context 0x9d8860, init_notify 0, handle 0x121fc88): stub
0042:err:module:load_builtin_dll failed to load .so lib for builtin L"winegstreamer.dll": libgstvideo-1.0.so.0: cannot open shared object file: No such file or directory
wine: configuration in '/home/adax/.wine' has been updated.
0009:fixme:thread:GetThreadUILanguage : stub, returning default language.
0009:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x33d958, (nil) 0x33d980
0009:fixme:nls:get_dummy_preferred_ui_language (0x38 0x33d958 (nil) 0x33d980) returning a dummy value (current locale)
0009:fixme:nls:GetThreadPreferredUILanguages 00000038, 0x33d958, 0x13719b0 0x33d980
0009:fixme:nls:get_dummy_preferred_ui_language (0x38 0x33d958 0x13719b0 0x33d980) returning a dummy value (current locale)
0009:fixme:msg:ChangeWindowMessageFilterEx 0x20050 400 1 (nil)
0009:fixme:wtsapi:WTSRegisterSessionNotification Stub 0x1007a 0x00000000
0009:fixme:wincodecs:BitmapScaler_Initialize unsupported mode 4
0009:fixme:wincodecs:BitmapScaler_Initialize unsupported mode 4
0009:fixme:wincodecs:BitmapScaler_Initialize unsupported mode 4


```

## Tried
`winecfg` change Default = `Windows 10` - before it was `Windows 7`

## Possible solution

This is some Wine error maybe - don't know.
Others with the sam issue: https://aur.archlinux.org/packages/heidisql/#comment-690748

**Downgrading wine to version 4.5 works.**

## Environment
* **HeidiSQL version:** 
10.1.0.5547   =   heidisql32.r5547.exe
* **Operating system:** 
```
Arch + KDE 5.57 + x86_64 Linux 5.0.9-2

> wine --version
wine-4.6
```

![screenshot 2019-04-29 08-54-32](https://user-images.githubusercontent.com/4988133/56880696-0aab9d80-6a5e-11e9-8675-0a19044ce1d0.png)

**Comment by hrvoj3e** [comment]
https://forum.winehq.org/viewtopic.php?f=8&t=32337

**Comment by rmi1974** [comment]
No need for bisect, it's caused by building Wine with **GCC 8.x** and **-O2** and https://source.winehq.org/git/wine.git/commit/cf8193df5b4c5a09208e40d8f3183c00187c8bd0 which caused GOT/PIC register loads emitted at win32 API entries. **madExcept** used by HeidiSQL can't cope with it.

https://bugs.winehq.org/show_bug.cgi?id=47027

Specifically:

https://bugs.winehq.org/show_bug.cgi?id=47027#c15

It's already fixed. Build Wine from current source (Git) or wait for 4.8 release 

Regards

**Comment by L-U-T-i** [comment]
I have just installed wine-4.8-2.fc29.i686, HeidiSQL (latest nightly build, as well as 10.1 release) is still crashing. Reverted back to wine-4.5-1.fc29.i686, and it launches OK.

**Comment by ansgarbecker** [comment]
Could someone please check v10.2 or even better the latest build?
My just pushed change 6695a31eaed81db234c4b6496c10942e2cdf3072 may also help here, although unlikely.

**Comment by ixnewton** [comment]
Still using HeidiSQL on Linux (Arch/Manjaro) under Wine now v6.4 I can confirm that v10.1.0.5464 is the last version to work and allow my continued access to MySQL/Maria and PostgreSQL. Something must have changed in calls to user32.dll after this version resulting in access violation fatal errors. V10.1 remains a good working version. Could I suggest a development branch using QT or GTK for a native application?

**Comment by hrvoj3e** [comment]
Just to let everyone know. It works for me now.
```
wine-6.4
heidisql64.r6250.exe
``` 
In the meantime I reinstalled my OS and wine, and heidisql.

Also, I am running only the portable version with symlinks to dlls.

```
├── builds
│   ├── heidisql64.r6250.exe
├── heidisql.exe -> ./builds/heidisql64.r6250.exe
├── libmariadb.dll -> /usr/share/heidisql/libmariadb.dll
├── libmysql.dll -> /usr/share/heidisql/libmysql.dll
├── plugins -> /usr/share/heidisql/plugins/
```


Here is the script I used to fix problems with dlls.
```
git clone --depth 1 https://github.com/HeidiSQL/HeidiSQL.git HeidiSQL.github
```
```
cd HeidiSQL.github
git pull
cd ..
sudo rsync -Pr HeidiSQL.github/out/plugins64/ /usr/share/heidisql/plugins/

sudo rsync -P HeidiSQL.github/out/libeay32-64.dll /usr/share/heidisql/libeay32.dll
sudo rsync -P HeidiSQL.github/out/libiconv-264.dll /usr/share/heidisql/libiconv-2.dll
sudo rsync -P HeidiSQL.github/out/libintl-864.dll /usr/share/heidisql/libintl-8.dll
sudo rsync -P HeidiSQL.github/out/libmariadb64.dll /usr/share/heidisql/libmariadb.dll
sudo rsync -P HeidiSQL.github/out/libmysql-6.1-64.dll /usr/share/heidisql/libmysql-6.1.dll
sudo rsync -P HeidiSQL.github/out/libmysql64.dll /usr/share/heidisql/libmysql.dll
sudo rsync -P HeidiSQL.github/out/libpq64.dll /usr/share/heidisql/libpq.dll
sudo rsync -P HeidiSQL.github/out/ssleay32-32.dll /usr/share/heidisql/ssleay32.dll 
```

**Comment by ixnewton** [comment]
Thanks! 
I have managed to get HeidiSQL_11.3.0.6295 working on Wine 6.15 after syncing the dlls. All working nicely on Manjaro (Arch) with KDE Plasma. I need all the latest updates so I can work on a Postgres backend project. Silk icon-set plays best with the display.

**Comment by ansgarbecker** [comment]
Please shout if still an issue with v12.0

**Comment by ixnewton** [comment]
Wine 7.5 just came down the line for Arch Linux! Together with Heidi v12.0 all works very well. Almost like a native app, seems interface rendering is faster.
