### ISSUE TITLE
Read-only mode for grid cell editors

### ISSUE THREAD

**Issue by magnetik** [HeidiSQL/HeidiSQL#631]
## Steps to reproduce this issue
1. Connect to a  MySQL 8 server
2. In query tab, do `SHOW ENGINE INNODB STATUS`
3. Double click on the first row, in `Status` column that containts a lot of text

## Current behavior

```
Grid editing error

Could not determine name of table.
```

## Expected behavior

Window to show full content of this field.

## Environment

* **HeidiSQL version:** 10.1.0.5549
* **Database system and version:** MySQL 8
* **Operating system:**  Windows 10

**Comment by Ivan-Perez** [comment]
What I do in those cases as a workaround is to copy the cell and paste the contents into the editor of your choice.

**Comment by magnetik** [comment]
That's what I'm doing, but I find the little editor in heidisql quite convenient so it would be cool if it worked.

**Comment by ansgarbecker** [comment]
This was a topic several times already. And I suppose it's time to create some solution here.

see
* a discussion in [ticket 2494](https://sourceforge.net/p/heidisql/tickets/2494/) on Sourceforge
* a [short forum thread](https://www.heidisql.com/forum.php?t=23038) on the same topic

Actually, HeidiSQL blocks all editing in any situation where my database layer cannot find an underlying table plus column name. I understand you did not intend to change the contents, but for HeidiSQL, the popup text editor is strictly for editing, not just for displaying purposes.

So, my idea is to support a read-only mode in all the different grid cell editors if the database says there is no table column involved here.

**Comment by magnetik** [comment]
Oh yes, I was not expecting for this to be such a large change. 

This seems like a great solution indeed !

Thanks for your time and your fast response :) 👍

**Comment by ansgarbecker** [comment]
Next build finally has a read-only mode in query grids, allowing the text editor and other editors to pop up:

![grafik](https://user-images.githubusercontent.com/7986591/73933534-ed550b00-48dc-11ea-9ec7-5e4c3858d6aa.png)

**Comment by magnetik** [comment]
awesome ! Thanks a lot 👍
