### ISSUE TITLE
Search and Replace generates HTML

### ISSUE THREAD

**Issue by cookieguru** [HeidiSQL/HeidiSQL#634]
## Steps to reproduce this issue

1. Search and replace for a URL
2. Replace all occurrences

![Search and replace screenshot](https://user-images.githubusercontent.com/1888809/57037010-cd384300-6c0a-11e9-9499-bd1f5b1ce7df.png)

## Current behavior

Dialog shows HTML

## Expected behavior

Text in dialog does not contain HTML _or_ HTML is rendered.

In the above example I would expect to see
```plain
Text "http://www.example.com/" 1 times replaced.
```

## And also

`Text "%s" %s times replaced.` would make more sense to be reworded as `Text "%s" replaced %s times.`

* **HeidiSQL version:** 10.1.0.5550

**Comment by rentalhost** [comment]
Reproduced at **r5560**.

Replacement suggestion PR as #648.

About the issue itself, it seems to be related to this line:

**Comment by ansgarbecker** [comment]
Probably also need to remove `tfEnableHyperlinks` from `Dialog.Flags` in such cases, and don't apply the regex.

**Comment by ansgarbecker** [comment]
Problem solved, by fixing the HTML anchors generated through a regular expression:
* previously:
`Text "https://test.de" replaced 1 times` => `Text "<a href="https://test.de"">https://test.de"</a>" replaced 1 times`
* now:
`Text "https://test.de" replaced 1 times` => `Text "<a href="https://test.de">https://test.de</a>" replaced 1 times`

Result:
![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/e3a6c8b4-e681-4d4c-9a8f-ba67b4608bb6)
