### ISSUE TITLE
Procedure or Function Alter Query

### ISSUE THREAD

**Issue by hkaraoglu** [HeidiSQL/HeidiSQL#635]
When edit body of a procedure or function, heidisql doesnt give us to an alter code for edited procedure/function

## Steps to reproduce this issue

1. Create a procedure
2. Then update procedure body.

## Current behavior

Alter code is no available. 

## Expected behavior

Alter code is should be showed on top side.

## Possible solution

Alter code is should be showed on top side.

## Environment

* **HeidiSQL version:** 
 10.1.0.5464

**Comment by ansgarbecker** [comment]
The reason why there is no `ALTER code` tab is that MariaDB just does not support an `ALTER` command with all required changes. There is an `ALTER PROCEDURE` command, but it does not you cannot change the parameters or body of a stored procedure using that. HeidiSQL instead recreates the whole procedure, after testing the code in it.
