### ISSUE TITLE
Subsequent openings of Export Grid Rows Dialog causes lists to have ever-increasing padding between items

### ISSUE THREAD

**Issue by kwalterps** [HeidiSQL/HeidiSQL#636]
## Steps to reproduce this issue

1. View a table's data
2. Right-click and select Export grid rows
3. Close the dialog;
4. Repeat steps 2 and 3 

## Current behavior

Every time steps 2 and 3 are repeated, the items in the list grow farther apart and the window grows larger in all directions

## Expected behavior

I expect that the dialog stays the same size at all times.

## Environment

* **HeidiSQL version:** 
  
10.1.0.5464
* **Operating system:** 
  
Windows 10 3840x2160 200% scaling

![image](https://user-images.githubusercontent.com/31418709/57086640-81e66900-6ccc-11e9-95a3-248326006671.png)

**Comment by ansgarbecker** [comment]
Is this just this dialog with such an issue, or are there more?

**Comment by kwalterps** [comment]
I don't know of any others.

**Comment by ansgarbecker** [comment]
Can you please update to the latest build, and then test whether the dialog Tools > "Import CSV file" has the same issue. That dialog has the same logic with regard to storing and restoring its width and height.

I am not able to reproduce the issue on Win7 with 150% scaling.

**Comment by kwalterps** [comment]
I closed and opened the Import CSV dialog three times and this is what I ended up with.
![image](https://user-images.githubusercontent.com/31418709/57093277-7189ba80-6cdb-11e9-931e-75ec295404aa.png)

**Comment by ansgarbecker** [comment]
So the import dialog _has_ the same issue then, or was that the size which you have manually set?

Did you update to the latest build prior to testing?

**Comment by kwalterps** [comment]
With each close and re-open the dialog grows and spaces the items out. Do you want me to update to the nightly build 5550?

**Comment by ansgarbecker** [comment]
> Do you want me to update to the nightly build 5550?

Yes, that is the latest nightly build currently. Reporting issues should always be done based on the latest build, as there may already be fixed things which you are about to report.

**Comment by kwalterps** [comment]
I have updated to 5550 and the issue still exists on both dialogs.
![image](https://user-images.githubusercontent.com/31418709/57093941-2ffa0f00-6cdd-11e9-8805-9c7c468169ca.png)
![image](https://user-images.githubusercontent.com/31418709/57093961-3daf9480-6cdd-11e9-83e1-f4c2157e05fc.png)
![image](https://user-images.githubusercontent.com/31418709/57093968-456f3900-6cdd-11e9-8c2a-ea28b85420ef.png)

**Comment by ansgarbecker** [comment]
c31cae206042ae00b97e41f43baf7421693d2e46 now removes all tweaks for high DPI monitors. I'm giving up here, this does all not work good enough, even different computers and Windows versions behave differently. It's a mess. So, now HeidiSQL is zoomed by Windows again, like it was in earlier v9.5. This does at least display all controls and fonts in the right dimensions.
