### ISSUE TITLE
Application Crashes When Trying to Rename a Column

### ISSUE THREAD

**Issue by andrfgs** [HeidiSQL/HeidiSQL#638]
## Steps to reproduce this issue
1: Right click on table to edit it
2: On the edit table click on "Insert new Column"
3: Double click the column name to change it
4: Press enter when done

## Current behavior
Application crashes

## Expected behavior
For the application to actually rename the column.

## Environment

* **HeidiSQL version:**  9.5.0.5196
  
* **Database system and version:** MariaDB 10.3
  
* **Operating system:** Windows 10 Pro 1803 (Build 17134.706)

**Comment by ansgarbecker** [comment]
> HeidiSQL version: 9.5.0.5196

That version is outdated. Please update to the current release, then make an additional update to the latest build, before reporting bugs. I recall I already fixed that issue.
