### ISSUE TITLE
Cannot create a view with postgres

### ISSUE THREAD

**Issue by chadalen** [HeidiSQL/HeidiSQL#64]
## Expected behavior

Create a view

## Current behavior

Get an error message saying undefined sql security definer view 

## Failure information (for bugs)

![https://i.imgur.com/l6XYzZ3.png](https://i.imgur.com/l6XYzZ3.png)

### Steps to reproduce

 Use postgres and create a view

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version: 9.5.0.5196
* Database system + version: Postgres 10
* Operating system: Windows 10

### Failure logs

```
/* ERROR:  syntax error at or near "ALGORITHM"
LINE 1: CREATE ALGORITHM = UNDEFINED SQL SECURITY DEFINER VIEW "play...
               ^ */
CREATE ALGORITHM = UNDEFINED SQL SECURITY DEFINER VIEW "player_view" AS  SELECT player.member_id,
    lower((player.data ->> 'username'::text)) AS player_name,
    jsonb_pretty((player.data)::jsonb) AS player_properties,
    to_char(player.created_on, 'Mon DD, YYYY HH:MI AM'::text) AS created_on,
    to_char(player.last_save, 'Mon DD, YYYY HH:MI AM'::text) AS last_saved
   FROM player
  ORDER BY (player.data ->> 'username'::text);  
```

**Comment by ansgarbecker** [comment]
Same problem as described in #39

**Comment by fgma** [comment]
I've got the same problem running Postgres 11.5 and HeidiSQL 10.2.0.5599 on Windows 10.

**Comment by fgma** [comment]
Fixed in https://github.com/HeidiSQL/HeidiSQL/issues/39#issuecomment-561328823

Tested using latest release 10.3.0.5771. Works now for me running Postgres 11.5.

**Comment by ansgarbecker** [comment]
Thanks for your feedback!
