### ISSUE TITLE
"CREATE code" tab crashes if table has a descending index.

### ISSUE THREAD

**Issue by lewa** [HeidiSQL/HeidiSQL#640]
## Steps to reproduce this issue

Open "CREATE code" tab of the following table:

```sql
CREATE TABLE test (
	id INT,
	INDEX id (id DESC)
);
```

## Current behavior

Application crashes.

## Environment

* **HeidiSQL version:** 10.1.0.5555
* **Database system and version:** MySQL 8.0.15
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
You will need to attach the crash report here, otherwise there's no way to debug for me.
Spontaneously, I cannot reproduce that crash here.

**Comment by lewa** [comment]
Here you go.
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3149201/bugreport.txt)

**Comment by ansgarbecker** [comment]
The crash should be healed in the next nightly build.

Only there's no support for `DESC/ASC` key columns in HeidiSQL yet. If you like you can open another issue for that.

**Comment by lewa** [comment]
Thanks a lot! I definitely can live without DESC/ASC key columns.

**Comment by dcelasun** [comment]
The feature request is in #1512.
