### ISSUE TITLE
mssql: foreign key support

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#641]
## Steps to reproduce this issue

1. Create a database with SSMS
2. Create two table and a FK
3. Open the DB in HeidiSQL
4. HeidiSQL: the selected engine 'server default' doesn't support foreign key

## Current behavior

![image](https://user-images.githubusercontent.com/3911428/57296082-0acd1e00-709a-11e9-9d1e-a6bcdfc6a447.png)

## Expected behavior

Manage foreign keys

## Environment

* **HeidiSQL version:** 
10.1.0.5464
* **Database system and version:** 
MSSQL 14
* **Operating system:** 
Windows 10 x64

**Comment by ansgarbecker** [comment]
This is related to #150 which provides a query for retrieving foreign keys for a table.

**Comment by ansgarbecker** [comment]
Should work now, please check the next build. See https://github.com/HeidiSQL/HeidiSQL/issues/150#issuecomment-578544848
