### ISSUE TITLE
CTRL+Click on FK = jump to referenced table&value

### ISSUE THREAD

**Issue by markdza** [HeidiSQL/HeidiSQL#643]
This has been brought up many times (#156, #364, [20427](https://www.heidisql.com/forum.php?t=20427)) over the past few years and I think it would be great to have. Just wanted to bring it up again. Thanks.

![](https://www.heidisql.com/uploads/20499-1-sequel-pro.png)

**Comment by ansgarbecker** [comment]
Please don't create even more duplicates for this request. Let's leave the first one open.

**Comment by markdza** [comment]
Agreed. Let's make it happen please! It was originally requested more than [3 years ago](https://www.heidisql.com/forum.php?t=20427).
