### ISSUE TITLE
App Crash at column selection

### ISSUE THREAD

**Issue by H4NNE5** [HeidiSQL/HeidiSQL#644]
## Steps to reproduce this issue

1. Right click on column to get to the column selection menu
2. Clicking on the last visible checkbox in the list (list must probably extend below the visible area).
3. Then the "error occured" window pops up and the checkbox below the desired one gets selected.

## Current behavior

The desired checkbox is not selected.
In attached picture the bar where I selected the checkbox is still highlighted but the checkbox below is selected.

## Expected behavior

Exactly the checkbox the user clicks on should be selected.

## Environment

* **system information:** 
  
date/time          : 2019-05-09, 18:22:41, 422ms
computer name      : DAJA
user name          : jh
registered owner   : cntxuser
operating system   : Windows 10 x64 build 17763
system language    : German
system up time     : 23 days 9 hours
program up time    : 3 hours 14 minutes
processors         : 4x Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz
physical memory    : 16034/23994 MB (free/total)
free disk space    : (C:) 343,56 GB
display mode       : 1920x1080, 32 bit
process id         : $3fb0
allocated memory   : 79,95 MB
largest free block : 131025,95 GB
executable         : heidisql.exe
exec. date/time    : 2019-01-26 08:17
version            : 10.1.0.5464
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $564ebdfb, $de5d6dd5, $de5d6dd5
exception number   : 1
exception class    : EStringListError
exception message  : List index out of bounds (-1).

main thread ($1c20):
006ceff0 heidisql.exe   Vcl.StdCtrls             .TListBoxStrings
7ff9af3f KERNELBASE.dll                          RaiseException
004107cd heidisql.exe   System                   @RaiseAtExcept
0053a45c heidisql.exe   System.Classes           TStrings.Error
0053c9e4 heidisql.exe   System.Classes           TStringList.Delete
00d266cc heidisql.exe   column_selection 161  +6 TColumnSelectionForm.chklistColumnsClickCheck
00b290c0 heidisql.exe   Vcl.CheckLst             TCheckListBox.ClickCheck
00b29088 heidisql.exe   Vcl.CheckLst             TCheckListBox.ToggleClickCheck
00b28fb1 heidisql.exe   Vcl.CheckLst             TCheckListBox.MouseDown
006a205b heidisql.exe   Vcl.Controls             TControl.DoMouseDown
006a20d5 heidisql.exe   Vcl.Controls             TControl.WMLButtonDown
006de10c heidisql.exe   Vcl.StdCtrls             TCustomListBox.WMLButtonDown
0040e9d2 heidisql.exe   System                   TObject.Dispatch
006a17cd heidisql.exe   Vcl.Controls             TControl.WndProc
006a86aa heidisql.exe   Vcl.Controls             TWinControl.WndProc
006ddef2 heidisql.exe   Vcl.StdCtrls             TCustomListBox.WndProc
006a78da heidisql.exe   Vcl.Controls             TWinControl.MainWndProc
0055c293 heidisql.exe   System.Classes           StdWndProc
7ff9afa4 USER32.dll                              DispatchMessageW
0084e07e heidisql.exe   Vcl.Forms                TApplication.ProcessMessage
0084e0f3 heidisql.exe   Vcl.Forms                TApplication.HandleMessage
0084e541 heidisql.exe   Vcl.Forms                TApplication.Run
00dd74ba heidisql.exe   heidisql          85 +26 initialization
7ff9b0a0 KERNEL32.DLL                            BaseThreadInitThunk
7ff9b24c ntdll.dll                               RtlUserThreadStart

![Heidi_Selection_Bug](https://user-images.githubusercontent.com/13788309/57470291-c18ef100-7288-11e9-97f9-a94779929923.jpg)

**Comment by ansgarbecker** [comment]
Current build is 5559, which is nearly 100 builds ahead of yours. Could you please update and report back if the crash still happens?

**Comment by rentalhost** [comment]
Could not reproduces even using r5464. Possibly related to the column naming.

Can you provide your CREATE TABLE for this table?

**Comment by H4NNE5** [comment]
Ok strange, after this problem occurred 3 times in a row, now I cannot reproduce it either :(
Seems it was a very singular problem.
