### ISSUE TITLE
Can't create new user with mariadb 10.4.4 - user column not found

### ISSUE THREAD

**Issue by rspadim** [HeidiSQL/HeidiSQL#645]
I'm using mariadb 10.4.4 and trying to include a new user 

The problem is the gui interface running the background SQL. 

Mariadb 10.4.4 don't have "user" column, it have "User" column Maybe a strtolower() in some where could help here

SHOW COLUMNS FROM `mysql`.`user`;
COLUMNS
---
| Field | Type | Null | Key | Default | Extra | 
| --- | --- | --- | --- | --- | --- | 
| Host | char(60) | NO |  |  |  | 
| User | char(80) | NO |  |  |  | 
| Password | longtext | YES |  | \N |  | 
| Select_priv | varchar(1) | YES |  | \N |  | 
| Insert_priv | varchar(1) | YES |  | \N |  | 
| Update_priv | varchar(1) | YES |  | \N |  | 
| Delete_priv | varchar(1) | YES |  | \N |  | 
| Create_priv | varchar(1) | YES |  | \N |  | 
| Drop_priv | varchar(1) | YES |  | \N |  | 
| Reload_priv | varchar(1) | YES |  | \N |  | 
| Shutdown_priv | varchar(1) | YES |  | \N |  | 
| Process_priv | varchar(1) | YES |  | \N |  | 
| File_priv | varchar(1) | YES |  | \N |  | 
| Grant_priv | varchar(1) | YES |  | \N |  | 
| References_priv | varchar(1) | YES |  | \N |  | 
| Index_priv | varchar(1) | YES |  | \N |  | 
| Alter_priv | varchar(1) | YES |  | \N |  | 
| Show_db_priv | varchar(1) | YES |  | \N |  | 
| Super_priv | varchar(1) | YES |  | \N |  | 
| Create_tmp_table_priv | varchar(1) | YES |  | \N |  | 
| Lock_tables_priv | varchar(1) | YES |  | \N |  | 
| Execute_priv | varchar(1) | YES |  | \N |  | 
| Repl_slave_priv | varchar(1) | YES |  | \N |  | 
| Repl_client_priv | varchar(1) | YES |  | \N |  | 
| Create_view_priv | varchar(1) | YES |  | \N |  | 
| Show_view_priv | varchar(1) | YES |  | \N |  | 
| Create_routine_priv | varchar(1) | YES |  | \N |  | 
| Alter_routine_priv | varchar(1) | YES |  | \N |  | 
| Create_user_priv | varchar(1) | YES |  | \N |  | 
| Event_priv | varchar(1) | YES |  | \N |  | 
| Trigger_priv | varchar(1) | YES |  | \N |  | 
| Create_tablespace_priv | varchar(1) | YES |  | \N |  | 
| Delete_history_priv | varchar(1) | YES |  | \N |  | 
| ssl_type | varchar(9) | YES |  | \N |  | 
| ssl_cipher | longtext | NO |  |  |  | 
| x509_issuer | longtext | NO |  |  |  | 
| x509_subject | longtext | NO |  |  |  | 
| max_questions | bigint(20) unsigned | NO |  | 0 |  | 
| max_updates | bigint(20) unsigned | NO |  | 0 |  | 
| max_connections | bigint(20) unsigned | NO |  | 0 |  | 
| max_user_connections | bigint(21) | NO |  | 0 |  | 
| plugin | longtext | NO |  |  |  | 
| authentication_string | longtext | NO |  |  |  | 
| password_expired | varchar(1) | NO |  |  |  | 
| is_role | varchar(1) | YES |  | \N |  | 
| default_role | longtext | NO |  |  |  | 
| max_statement_time | decimal(12,6) | NO |  | 0.000000 |  |

**Comment by rspadim** [comment]
Show create table mysql.user:


CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `user` AS select `global_priv`.`Host` AS `Host`,`global_priv`.`User` AS `User`,if(json_value(`global_priv`.`Priv`,'$.plugin') in ('mysql_native_password','mysql_old_password'),ifnull(json_value(`global_priv`.`Priv`,'$.authentication_string'),''),'') AS `Password`,if(json_value(`global_priv`.`Priv`,'$.access') & 1,'Y','N') AS `Select_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 2,'Y','N') AS `Insert_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 4,'Y','N') AS `Update_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 8,'Y','N') AS `Delete_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 16,'Y','N') AS `Create_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 32,'Y','N') AS `Drop_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 64,'Y','N') AS `Reload_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 128,'Y','N') AS `Shutdown_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 256,'Y','N') AS `Process_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 512,'Y','N') AS `File_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 1024,'Y','N') AS `Grant_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 2048,'Y','N') AS `References_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 4096,'Y','N') AS `Index_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 8192,'Y','N') AS `Alter_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 16384,'Y','N') AS `Show_db_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 32768,'Y','N') AS `Super_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 65536,'Y','N') AS `Create_tmp_table_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 131072,'Y','N') AS `Lock_tables_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 262144,'Y','N') AS `Execute_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 524288,'Y','N') AS `Repl_slave_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 1048576,'Y','N') AS `Repl_client_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 2097152,'Y','N') AS `Create_view_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 4194304,'Y','N') AS `Show_view_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 8388608,'Y','N') AS `Create_routine_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 16777216,'Y','N') AS `Alter_routine_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 33554432,'Y','N') AS `Create_user_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 67108864,'Y','N') AS `Event_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 134217728,'Y','N') AS `Trigger_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 268435456,'Y','N') AS `Create_tablespace_priv`,if(json_value(`global_priv`.`Priv`,'$.access') & 536870912,'Y','N') AS `Delete_history_priv`,elt(ifnull(json_value(`global_priv`.`Priv`,'$.ssl_type'),0) + 1,'','ANY','X509','SPECIFIED') AS `ssl_type`,ifnull(json_value(`global_priv`.`Priv`,'$.ssl_cipher'),'') AS `ssl_cipher`,ifnull(json_value(`global_priv`.`Priv`,'$.x509_issuer'),'') AS `x509_issuer`,ifnull(json_value(`global_priv`.`Priv`,'$.x509_subject'),'') AS `x509_subject`,cast(ifnull(json_value(`global_priv`.`Priv`,'$.max_questions'),0) as unsigned) AS `max_questions`,cast(ifnull(json_value(`global_priv`.`Priv`,'$.max_updates'),0) as unsigned) AS `max_updates`,cast(ifnull(json_value(`global_priv`.`Priv`,'$.max_connections'),0) as unsigned) AS `max_connections`,cast(ifnull(json_value(`global_priv`.`Priv`,'$.max_user_connections'),0) as signed) AS `max_user_connections`,ifnull(json_value(`global_priv`.`Priv`,'$.plugin'),'') AS `plugin`,ifnull(json_value(`global_priv`.`Priv`,'$.authentication_string'),'') AS `authentication_string`,'N' AS `password_expired`,elt(ifnull(json_value(`global_priv`.`Priv`,'$.is_role'),0) + 1,'N','Y') AS `is_role`,ifnull(json_value(`global_priv`.`Priv`,'$.default_role'),'') AS `default_role`,cast(ifnull(json_value(`global_priv`.`Priv`,'$.max_statement_time'),0.0) as decimal(12,6)) AS `max_statement_time` from `global_priv`

**Comment by rspadim** [comment]
SHOW TABLE STATUS FROM `mysql`;

TABLES
---
| Name | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time | Update_time | Check_time | Collation | Checksum | Create_options | Comment | Max_index_length | Temporary | 
| --- | --- | ---: | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | --- | --- | ---: | --- | --- | ---: | --- | 
| column_stats | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_bin | \N | transactional=0 | Statistics on Columns | 2305843009213685760 | N | 
| columns_priv | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | utf8_bin | \N | page_checksum=1 transactional=1 | Column privileges | 2305843009213685760 | N | 
| db | Aria | 10 | Page | 7 | 2340 | 16384 | 17592186011648 | 24576 | 0 | \N | 2019-04-30 21:53:40 | 2019-05-09 18:22:01 | \N | utf8_bin | \N | page_checksum=1 transactional=1 | Database privileges | 2305843009213685760 | N | 
| event | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_general_ci | \N | transactional=1 | Events | 2305843009213685760 | N | 
| func | Aria | 10 | Page | 5 | 3276 | 16384 | 17592186011648 | 16384 | 0 | \N | 2019-04-30 21:53:40 | 2019-04-30 22:23:24 | 2019-04-30 21:53:40 | utf8_bin | \N | page_checksum=1 transactional=1 | User defined functions | 2305843009213685760 | N | 
| general_log | CSV | 10 | Dynamic | 2 | 0 | 0 | 0 | 0 | 0 | \N | \N | \N | \N | utf8_general_ci | \N |  | General log | 0 | N | 
| global_priv | Aria | 11 | Page | 9 | 1820 | 16384 | 17592186011648 | 16384 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | \N | utf8_bin | \N | transactional=1 | Users and global privileges | 2305843009213685760 | N | 
| gtid_slave_pos | InnoDB | 10 | Compact | 0 | 0 | 16384 | 0 | 0 | 0 | \N | 2019-03-11 09:58:29 | \N | \N | latin1_swedish_ci | \N |  | Replication slave GTID position | 0 | N | 
| help_category | Aria | 10 | Page | 39 | 420 | 16384 | 17592186011648 | 24576 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | \N | utf8_general_ci | \N | transactional=0 | help categories | 2305843009213685760 | N | 
| help_keyword | Aria | 10 | Page | 464 | 52 | 24576 | 17592186011648 | 24576 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_general_ci | \N | transactional=0 | help keywords | 2305843009213685760 | N | 
| help_relation | Aria | 10 | Page | 1028 | 47 | 49152 | 17592186011648 | 32768 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_general_ci | \N | transactional=0 | keyword-topic relation | 9007199254732800 | N | 
| help_topic | Aria | 10 | Page | 508 | 903 | 458752 | 17592186011648 | 24576 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_general_ci | \N | transactional=0 | help topics | 2305843009213685760 | N | 
| index_stats | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_bin | \N | transactional=0 | Statistics on Indexes | 2305843009213685760 | N | 
| innodb_index_stats | InnoDB | 10 | Dynamic | 643 | 280 | 180224 | 0 | 0 | 0 | \N | 2019-04-30 21:53:39 | \N | \N | utf8_bin | \N | stats_persistent=0 |  | 0 | N | 
| innodb_table_stats | InnoDB | 10 | Dynamic | 127 | 129 | 16384 | 0 | 0 | 0 | \N | 2019-04-30 21:53:39 | \N | \N | utf8_bin | \N | stats_persistent=0 |  | 0 | N | 
| plugin | Aria | 10 | Page | 4 | 4096 | 16384 | 17592186011648 | 16384 | 0 | \N | 2019-04-30 21:53:40 | 2019-04-30 22:23:24 | \N | utf8_general_ci | \N | transactional=1 | MySQL plugins | 2305843009213685760 | N | 
| proc | Aria | 10 | Page | 0 | 0 | 49152 | 17592186011648 | 16384 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:55:58 | 2019-04-30 21:53:41 | utf8_general_ci | \N | transactional=1 | Stored Procedures | 2305843009213685760 | N | 
| procs_priv | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | utf8_bin | \N | page_checksum=1 transactional=1 | Procedure privileges | 2305843009213685760 | N | 
| proxies_priv | Aria | 10 | Page | 1 | 16384 | 16384 | 17592186011648 | 24576 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | \N | utf8_bin | \N | transactional=1 | User proxy privileges | 2305843009213685760 | N | 
| roles_mapping | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | utf8_bin | \N | transactional=1 | Granted roles | 2305843009213685760 | N | 
| servers | Aria | 10 | Page | 1 | 16384 | 16384 | 17592186011648 | 16384 | 0 | \N | 2019-04-30 21:53:40 | 2019-04-30 22:23:25 | 2019-04-30 21:53:40 | utf8_general_ci | \N | transactional=1 | MySQL Foreign Servers table | 2305843009213685760 | N | 
| slow_log | CSV | 10 | Dynamic | 2 | 0 | 0 | 0 | 0 | 0 | \N | \N | \N | \N | utf8_general_ci | \N |  | Slow log | 0 | N | 
| spider_link_failed_log | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:55:58 | 2019-04-30 21:55:58 | \N | utf8_bin | \N | transactional=1 |  | 137438945280 | N | 
| spider_link_mon_servers | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:55:58 | 2019-04-30 21:55:58 | 2019-04-30 21:55:58 | utf8_bin | \N | transactional=1 |  | 2305843009213685760 | N | 
| spider_table_crd | Aria | 10 | Page | 252 | 97 | 24576 | 17592186011648 | 16384 | 0 | \N | 2019-04-30 22:42:15 | 2019-05-03 08:01:43 | \N | utf8_bin | \N | transactional=1 |  | 2305843009213685760 | N | 
| spider_table_position_for_recovery | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 22:42:15 | 2019-04-30 22:42:15 | \N | utf8_bin | \N | transactional=1 |  | 2305843009213685760 | N | 
| spider_table_sts | Aria | 10 | Page | 9 | 1820 | 16384 | 17592186011648 | 16384 | 0 | \N | 2019-04-30 22:42:15 | 2019-05-03 08:01:43 | \N | utf8_bin | \N | transactional=1 |  | 2305843009213685760 | N | 
| spider_tables | Aria | 10 | Page | 9 | 1820 | 16384 | 17592186011648 | 32768 | 0 | \N | 2019-04-30 22:42:15 | 2019-05-03 08:01:43 | \N | utf8_bin | \N | transactional=1 |  | 2305843009213685760 | N | 
| spider_xa | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:55:58 | 2019-04-30 21:55:58 | 2019-04-30 21:55:58 | utf8_bin | \N | transactional=1 |  | 2305843009213685760 | N | 
| spider_xa_failed_log | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:55:58 | 2019-04-30 21:55:58 | 2019-04-30 21:55:58 | utf8_bin | \N | transactional=1 |  | 2305843009213685760 | N | 
| spider_xa_member | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:55:58 | 2019-04-30 21:55:58 | 2019-04-30 21:55:58 | utf8_bin | \N | transactional=1 |  | 2305843009213685760 | N | 
| table_stats | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_bin | \N | transactional=0 | Statistics on Tables | 2305843009213685760 | N | 
| tables_priv | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | utf8_bin | \N | page_checksum=1 transactional=1 | Table privileges | 2305843009213685760 | N | 
| time_zone | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | 1 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | \N | utf8_general_ci | \N | transactional=1 | Time zones | 9007199254732800 | N | 
| time_zone_leap_second | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_general_ci | \N | transactional=1 | Leap seconds information for time zones | 9007199254732800 | N | 
| time_zone_name | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | 2019-04-30 21:53:40 | utf8_general_ci | \N | transactional=1 | Time zone names | 2305843009213685760 | N | 
| time_zone_transition | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_general_ci | \N | transactional=1 | Time zone transitions | 9007199254732800 | N | 
| time_zone_transition_type | Aria | 10 | Page | 0 | 0 | 8192 | 17592186011648 | 8192 | 0 | \N | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | 2019-04-30 21:53:41 | utf8_general_ci | \N | transactional=1 | Time zone transition types | 9007199254732800 | N | 
| transaction_registry | InnoDB | 10 | Dynamic | 0 | 0 | 16384 | 0 | 49152 | 0 | \N | 2019-03-11 09:58:29 | \N | \N | utf8_bin | \N | stats_persistent=0 |  | 0 | N | 
| user | \N | \N | \N | \N | \N | \N | \N | \N | \N | \N | \N | \N | \N | \N | \N | \N | VIEW | \N | \N |

**Comment by rentalhost** [comment]
@rspadim I am running MariaDB 10.3.13, and it also returns `User` column (ucfirsted) and I got no errors when opening the user management dialog.

Could you please tell what you are doing step-by-step and what error you are getting and what you are expecting?

Thanks!

**Comment by ansgarbecker** [comment]
This is a duplicate to #599 which I recently fixed. Please always update to the latest build before reporting bugs, so we don't get duplicates here.
