### ISSUE TITLE
Windows10 SlateGray theme problems in "Save as snippet..." and "Save as..."

### ISSUE THREAD

**Issue by anselal** [HeidiSQL/HeidiSQL#649]
## Steps to reproduce this issue

1. Set the Style Theme to `Windows10 SlateGray`
2. Right click on a query window and select "Save as snippet..." or "Save as..."

## Current behavior

The left tree and the items on the dropdown list while typing a new appear in white.

![2019-05-13_12h13_31](https://user-images.githubusercontent.com/8732668/57610357-57709780-7579-11e9-95e5-004f0da1f2f6.png)

## Expected behavior

The items on the window should all adopt the themes properties

## Possible solution

Don't know

## Environment

* **HeidiSQL version:** 
10.1.0.5555
* **Operating system:** 
Windows 10 64bit 1809

**Comment by WesleyM77** [comment]
Also having this issue with Material.  Thought this was due to my session background setting, but I changed it from 'Default' to 'None' and it didn't seem to change anything. On Heidi 10.2.0.5629. 
![heidisql_2019-07-15_11-26-01](https://user-images.githubusercontent.com/22208037/61228233-ddcd6500-a6f3-11e9-8d07-51d53d8fcd20.png)

**Comment by ansgarbecker** [comment]
I cannot reproduce that white panel any more, for some reason:

![grafik](https://user-images.githubusercontent.com/7986591/61587558-aeec3e80-ab8c-11e9-954a-7ff4adb34287.png)

I am going to push updates from the [vcl-styles-utils project](https://github.com/RRUZ/vcl-styles-utils.git).

**Comment by ansgarbecker** [comment]
cfe412e12c155c4a8d86a4802272332cb92094a5 has various updates for themes. Please test by updating to the latest build of HeidiSQL in a few minutes.

**Comment by anselal** [comment]
Yeap,

that fixed the background.

Thanks a lot !!!

**Comment by anselal** [comment]
Although the white background remains the in dropdown when you type a filename.
I guess this is not related to any bug of the software so we can close this issue ??

**Comment by ansgarbecker** [comment]
I'm not sure. According to https://github.com/RRUZ/vcl-styles-utils/issues/249 the edit and dropdown boxes should be painted in the right color, not in white.

**Comment by anselal** [comment]
Updated to the latest 10.2.0.5728 but the issue still remains

**Comment by anselal** [comment]
Updated to the latest 10.2.0.5736.

The issue is not completely resolved. When I start typing the background has the desired color (not white) 

![2019-11-04_08h34_14](https://user-images.githubusercontent.com/8732668/68103054-fd281200-fedd-11e9-8146-6cb58a5e86ae.png)

but when I don't type anything and expand the dropdown then the background is still white.


![2019-11-04_08h34_39](https://user-images.githubusercontent.com/8732668/68103066-0b762e00-fede-11e9-9dcb-26e4ed7a3caa.png)

**Comment by ansgarbecker** [comment]
I'll have a look if the changed file from https://github.com/salvadordf/vcl-styles-utils/commit/16730fd00f7426b1985d53565c1f6e8209fd7ff5 is really used in HeidiSQL.

**Comment by ansgarbecker** [comment]
The dialog for loading an SQL file is a `TOpenTextFileDialog`, while e.g. the session manager's startup script selector is a `TOpenDialog`. The latter one paints correctly, so there is some difference in their code which is apparently not caught up by the above mentioned fix.

**Comment by ansgarbecker** [comment]
Sorry for the confusion - I mixed up the save dialog with the open dialog. The save dialog has this wrong background color in the dropdown. The open text file dialogs have even more issues - they look like in old XP.

I could go and exchange the old-style open dialog with a newer dialog and extend it like described in [this blog post](https://akirabbq.wordpress.com/2009/02/06/mess-with-vistas-common-file-dialog/), but to be honest, that is too much effort for now.

For these background colors on the save dialog, I suppose we just accept that. I have no clue how to fix that.

**Comment by anselal** [comment]
If it is too much trouble that is ok. I just pointed out the issue.

It would be nice to be fixed but the main reason I use HeidiSQL is not the dark themes but it's features !!
