### ISSUE TITLE
https on internally called web pages don't load on WinXP

### ISSUE THREAD

**Issue by ansgarbecker** [HeidiSQL/HeidiSQL#65]
## Expected behavior

Donator check and update check working on all Windows versions.

## Current behavior

On WinXP, both don't work since 10668bc370c4779246afaf39316492da6422f50a

### Steps to reproduce

* HeidiSQL version: 5192
* Operating system: WinXP

### Failure Logs

> /* Die Internet Adresse konnte nicht geöffnet werden: https://www.heidisql.com/some-url */

**Comment by danitxo** [comment]
Windows XP's native SSL/schannel library doesn't have support for [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication).

If this is the problem, the only way to solve this is to make the request by HTTP only if the operating system is specifically Windows XP, or to have an IP associated to heidisql.com's SSL certificate and domain.
