### ISSUE TITLE
Possible Bug in Stored Procedures for MariaDB

### ISSUE THREAD

**Issue by andrfgs** [HeidiSQL/HeidiSQL#650]
## Steps to reproduce this issue

1. Attempt to create the stored procedure on the query tab:
```
CREATE PROCEDURE `NotificationLogp`(
  IN `Timestamp` BIGINT,
  IN `UnitID` INT,
  IN `Content` VARCHAR(50),
  IN `LEVEL` TINYINT,
  IN `Solved` INT,
  IN `Sector` TINYINT
)
MODIFIES SQL DATA
BEGIN
  DECLARE `newId` INT;
  INSERT INTO `logs`
  VALUES (NULL, `Timestamp`, `UnitID`);
  SET `newId` = LAST_INSERT_ID();
  INSERT INTO `notificationlogs`
  VALUES (`newId`, `Content`, `Level`, `Solved`, `Sector`);
END;
```

## Current behavior

Application reports error: 

> SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 11 

## Expected behavior

I believe, if I'm not mistaken, that stored procedures can be declared on the query tab, or do they have to be explicitly created using the GUI tool?

The GUI tool works fine. But I was just wondering if the query tab has this limitation or if this is a bug. I do know there is a similar issue solved and that the problem may be due to delimiters, but I can't seem to find any place where that would be a problem.

The SQL code works fine here: https://dbfiddle.uk/?rdbms=mariadb_10.3&fiddle=8c771e678e9fb130c7b3ecadf8e405dd

## Environment

* **HeidiSQL version:** 10.1.0-5464
  
* **Database system and version:** MariaDB 10.3.14
  
* **Operating system:** Windows 10 Pro x64

**Comment by rentalhost** [comment]
I could reproduces your code without issues at **r5560** and **r5464**.

Could you update to the nightly version and test your code again? Too double check if you are pasting exactly the example code.

**Comment by andrfgs** [comment]
I am sorry. I forgot this Issue. This was eventually solved by reinstalling the program.
