### ISSUE TITLE
Improper Quoting of Binary Data in "Quick Filter" Expressions

### ISSUE THREAD

**Issue by BourgeoisBear** [HeidiSQL/HeidiSQL#651]
## Steps to reproduce this issue

When bringing up "Quick Filter" from the context menu on a binary column...

## Current behavior

...it single-quotes the hexadecimal value--which is the wrong syntax for arbitrary-length hex literals--and returns the wrong result.

![image](https://user-images.githubusercontent.com/8608535/57821017-927af280-7754-11e9-9651-76ee7153c8d8.png)

## Expected behavior

Ideally, arbitrary-length hex literals should be left unquoted.

## Possible solution

Add extra logic to skip quoting binary literals when displayed in hexadecimal format.

## Environment

HeidiSQL 10.1.0.5464 / Windows 10
10.1.38-MariaDB-0+deb9u1 / Debian GNU/Linux 9.9 (stretch) (4.9.0-9-amd64)

**Comment by rentalhost** [comment]
I could confirm at **r5565**.

**Comment by ansgarbecker** [comment]
I think I fixed these recently, along with some related stuff,  in #1540
