### ISSUE TITLE
Inline edit and  and copy of blob data, content is cut off

### ISSUE THREAD

**Issue by pprossi** [HeidiSQL/HeidiSQL#652]
## Steps to reproduce this issue

1. Open Typo3 Database;
2. edit blob field;
3. Then I get cut off data in inline editor and popup editor...

maybe related to #428 

## Current behavior

Typo3 stores serialized php arrays inside of blob fields.

### Inline edit gives:
```
O:48:"TYPO3\CMS\Scheduler\Task\FileStorageIndexingTask":7:{s:10:"storageUid";i:1;s:10:"
```
![2019-05-16 09_tx_scheduler_task_3 - HeidiSQL 10 1 0 5464](https://user-images.githubusercontent.com/23215844/57836996-28993200-77c2-11e9-955a-1557dfa946fa.png)

### Popup edit gives:
![2019-05-16 09_tx_scheduler_task_ - HeidiSQL 10 1 0 5464](https://user-images.githubusercontent.com/23215844/57837079-4f576880-77c2-11e9-96a5-66c8724aa27c.png)

## Expected behavior

Original data is and should be at copy, edit:
```
O:32:"TYPO3\CMS\Extbase\Scheduler\Task":9:{s:20:" * commandIdentifier";s:20:"lang:language:update";s:12:" * arguments";a:1:{s:15:"localesToUpdate";s:0:"";}s:11:" * defaults";a:1:{s:15:"localesToUpdate";s:0:"";}s:10:" * taskUid";i:1;s:11:" * disabled";b:0;s:12:" * execution";O:29:"TYPO3\CMS\Scheduler\Execution":6:{s:8:" * start";i:1479539718;s:6:" * end";s:1:"0";s:11:" * interval";i:0;s:11:" * multiple";s:1:"0";s:10:" * cronCmd";s:9:"4 0 * * *";s:23:" * isNewSingleExecution";b:0;}s:16:" * executionTime";i:1556582640;s:14:" * description";s:0:"";s:12:" * taskGroup";i:1;}
```
![2019-05-16 09_tx_scheduler_task_2 - HeidiSQL 10 1 0 5464](https://user-images.githubusercontent.com/23215844/57837033-36e74e00-77c2-11e9-84c9-7bd2c7da014f.png)

## Possible solution

no idea :)

## Environment

* **HeidiSQL version:** 
10.1.0.5464

* **Database system and version:** 
5.7.25-0ubuntu0.16.04.2
on different ones the same

* **Operating system:** 
Windows 10
Windows 7

**Comment by rentalhost** [comment]
Actually it is a dupe from #202.
