### ISSUE TITLE
Frequent CRASHES running long queries or loading SQL files with no default THEME

### ISSUE THREAD

**Issue by robman70** [HeidiSQL/HeidiSQL#654]
## Steps to reproduce this issue

1. Run a long query (maybe only loading SQL files but I'm not sure about this);

## Current behavior

Frequent crashes occur using a non default theme (e.g. Windows 10 Dark)

## Expected behavior

No crashes... :-)

## Environment

* **HeidiSQL version:** 
  HeidiSQL 10.1
* **Database system and version:** 
 MariaDB 10.1
* **Operating system:** 
  Windows 10 Pro

**Comment by WesleyM77** [comment]
Do you have a crash log or call stack to help locate the issue?

**Comment by DizzyC** [comment]
I can confirm this issue.
Happens every time I 'Run SQL script'. Consistently reproduces.

**Comment by robman70** [comment]
At the beginning I also thought the same thing but then some scripts crashed even using the default theme ... :-(

**Comment by jjasoncool** [comment]
I have the same problem, this will happen after executing the mysql dump file.
And the delete button sometimes fails, you can only use the backspace key to delete the string in the editor.
[Video_2019-07-05_165640.zip](https://github.com/HeidiSQL/HeidiSQL/files/3361899/Video_2019-07-05_165640.zip)

**Comment by aruldd** [comment]
Experiencing the same issue with the same theme. It crashes consistently.

**Comment by WesleyM77** [comment]
Can confirm this issue. I've experienced it multiple times with the Material theme.

**Comment by ansgarbecker** [comment]
I found the myriad of refreshes after each query can confuse the application, so my just pushed change reduces that from one call per SQL command down to one call per second. It helps at least here, in case of one bigger file with many short queries.
Please update to the latest build and report back if that already helped.

**Comment by DizzyC** [comment]
@ansgarbecker I'm sorry to report the last build has not fixed the problem. (running 10.2.0.5684 (64 Bit))

I'm having the exact same issues. Noticed that at about 1 mil, 1.2 mil imported rows the UI breaks.
(I encounter this issue when importing bigger dumps, 200MB plus, dumps generated also by heidisql)

Thanks for the effort!

**Comment by WesleyM77** [comment]
Still an issue. Seems to break the UI before it actually finishes running the file.

**Comment by ansgarbecker** [comment]
Please update to v10.3 and report back if this is fixed. In #654 there is comment saying this is fixed, but it may have a different cause.

**Comment by DizzyC** [comment]
Sadly no change for me :(

Tested on version 10.3 and the behavior was exactly the same for me, no change, no improvement.

Let me know if I can assist further.

**Comment by WesleyM77** [comment]
Yup, still an issue.

**Comment by WesleyM77** [comment]
Still seems to be an issue even after I've done what the comment on #499 mentioned.

**Comment by michalwoz** [comment]
this bug is still present in 11.0.0.5937 while running ~80MB .sql files

**Comment by ansgarbecker** [comment]
I just pushed various updates for this progress dialog. Only a single instance of that progress dialog is used for multiple files. Also, there are no more refreshes in the background. For more technical details, see #338

Also related: the progress dialog no longer uses the user selected theme, which makes it more stable I hope. See 43a114c2cfb039297c8f71995bb33dcac0f8797c

My tests with 20mb SQL files were without errors, but someone should check the dialog with some larger file.

**Comment by michalwoz** [comment]
80MB import:
Previously it didn't crash only once per ~20 attempts.
Now 5/5 success!
So it seems to be fixed.

**Comment by WesleyM77** [comment]
Tested twice with a ~350Mb import. Didn't crash on either. Agree that it appears to be fixed!

**Comment by ansgarbecker** [comment]
Cool!

**Comment by lefin17** [comment]
I have same problem, but in my case when try to send big query from different clients the problem is the same. When query is short (ex. less then 1000 symbols) every is ok, but when I have long query (for me more then 2k symbols) the system (application) is not recieve any answer from remote sql server. But not from any workplace. From linux station is ok, from notebook with w11 - is ok, but remote terminal servers (WS2019) and WS2013 - has problem with long queries... and some of them via VPN, some in same network...
