### ISSUE TITLE
Crashes on a query when I use Export Grid Rows twice

### ISSUE THREAD

**Issue by Sapking** [HeidiSQL/HeidiSQL#655]
date/time          : 2019-05-24, 00:36:44, 58ms
computer name      : 
wts client name    : 
user name          : 
registered owner   : Windows User
operating system   : Windows 10 x64 build 17763
system language    : English
system up time     : 2 days 7 hours
program up time    : 1 day 12 hours
processors         : 2x AMD Opteron(tm) X3216 APU
physical memory    : 2874/7131 MB (free/total)
free disk space    : (C:) 189.53 GB
display mode       : 1536x864, 32 bit
process id         : $1088
allocated memory   : 130.92 MB
largest free block : 131025.95 GB
executable         : heidisql.exe
exec. date/time    : 2019-04-16 11:47
version            : 10.1.0.5532
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $9d4a93f6, $bef384e4, $41d3f446
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 000000000040E235 in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF.

main thread ($16a0):
0040e235 heidisql.exe System                  TObject.Free
005418c1 heidisql.exe System.Classes          TStringStream.Destroy
005414bb heidisql.exe System.Classes          TStringStream.Create
00d38f32 heidisql.exe exportgrid      563 +40 TfrmExportGrid.btnOKClick
006a20b1 heidisql.exe Vcl.Controls            TControl.Click
006d9566 heidisql.exe Vcl.StdCtrls            TCustomButton.Click
006da492 heidisql.exe Vcl.StdCtrls            TCustomButton.CNCommand
0040e9d2 heidisql.exe System                  TObject.Dispatch
006a19ad heidisql.exe Vcl.Controls            TControl.WndProc
006a888a heidisql.exe Vcl.Controls            TWinControl.WndProc
006d8fb0 heidisql.exe Vcl.StdCtrls            TButtonControl.WndProc
006a14a0 heidisql.exe Vcl.Controls            TControl.Perform
006a8a79 heidisql.exe Vcl.Controls            DoControlMsg
006a9be3 heidisql.exe Vcl.Controls            TWinControl.WMCommand
00844823 heidisql.exe Vcl.Forms               TCustomForm.WMCommand
0040e9d2 heidisql.exe System                  TObject.Dispatch
006a19ad heidisql.exe Vcl.Controls            TControl.WndProc
006a888a heidisql.exe Vcl.Controls            TWinControl.WndProc
0083fcfd heidisql.exe Vcl.Forms               TCustomForm.WndProc
00abe530 heidisql.exe SizeGrip        256 +36 TSizeGrip.NewWndProc
006a7aba heidisql.exe Vcl.Controls            TWinControl.MainWndProc
0055c423 heidisql.exe System.Classes          StdWndProc
7ff867f7 USER32.dll                           SendMessageW
7ff867f7 USER32.dll                           CallWindowProcW
006a8a12 heidisql.exe Vcl.Controls            TWinControl.DefaultHandler
006a275c heidisql.exe Vcl.Controls            TControl.WMLButtonUp
0040e9d2 heidisql.exe System                  TObject.Dispatch
006a19ad heidisql.exe Vcl.Controls            TControl.WndProc
006a888a heidisql.exe Vcl.Controls            TWinControl.WndProc
006d8fb0 heidisql.exe Vcl.StdCtrls            TButtonControl.WndProc
006a7aba heidisql.exe Vcl.Controls            TWinControl.MainWndProc
0055c423 heidisql.exe System.Classes          StdWndProc
7ff867f7 USER32.dll                           DispatchMessageW
0084de7e heidisql.exe Vcl.Forms               TApplication.ProcessMessage
0084def3 heidisql.exe Vcl.Forms               TApplication.HandleMessage
00846f43 heidisql.exe Vcl.Forms               TCustomForm.ShowModal
00da5032 heidisql.exe Main           3222  +4 TMainForm.actExportDataExecute
0055afb0 heidisql.exe System.Classes          TBasicAction.Execute
00676245 heidisql.exe Vcl.ActnList            TCustomAction.Execute
0055aca4 heidisql.exe System.Classes          TBasicActionLink.Execute
008247e7 heidisql.exe Vcl.Menus               TMenuItem.Click
00826fde heidisql.exe Vcl.Menus               TMenu.DispatchCommand
00829305 heidisql.exe Vcl.Menus               TPopupList.WndProc
00829205 heidisql.exe Vcl.Menus               TPopupList.MainWndProc
0055c423 heidisql.exe System.Classes          StdWndProc
7ff867f7 USER32.dll                           DispatchMessageW
0084de7e heidisql.exe Vcl.Forms               TApplication.ProcessMessage
0084def3 heidisql.exe Vcl.Forms               TApplication.HandleMessage
0084e341 heidisql.exe Vcl.Forms               TApplication.Run
00de55a5 heidisql.exe heidisql         86 +27 initialization
7ff86743 KERNEL32.DLL                         BaseThreadInitThunk
7ff869b2 ntdll.dll                            RtlUserThreadStart

main thread ($16a0), inner exception level 1:
>> EAccessViolation, Access violation at address 000000000048D9AE in module 'heidisql.exe'. Read of address FFFFFFFFFFFFFFFF
0048d9ae heidisql.exe System.SysUtils          TEncoding.GetBytes
7ff867f9 USER32.dll                            GetMessageW
004ef778 heidisql.exe madExcept                HandleException
004fb6e1 heidisql.exe madExcept                InterceptAHandleExcept
006a7ade heidisql.exe Vcl.Controls             TWinControl.MainWndProc
0055c423 heidisql.exe System.Classes           StdWndProc
7ff867f7 USER32.dll                            SendMessageW
7ff867f7 USER32.dll                            CallWindowProcW
006a8a12 heidisql.exe Vcl.Controls             TWinControl.DefaultHandler
006a275c heidisql.exe Vcl.Controls             TControl.WMLButtonUp
0040e9d2 heidisql.exe System                   TObject.Dispatch
006a19ad heidisql.exe Vcl.Controls             TControl.WndProc
006a888a heidisql.exe Vcl.Controls             TWinControl.WndProc
006d8fb0 heidisql.exe Vcl.StdCtrls             TButtonControl.WndProc
006a7aba heidisql.exe Vcl.Controls             TWinControl.MainWndProc
0055c423 heidisql.exe System.Classes           StdWndProc
7ff867f7 USER32.dll                            DispatchMessageW
0084de7e heidisql.exe Vcl.Forms                TApplication.ProcessMessage
0084def3 heidisql.exe Vcl.Forms                TApplication.HandleMessage
00846f43 heidisql.exe Vcl.Forms                TCustomForm.ShowModal
00da5032 heidisql.exe Main            3222  +4 TMainForm.actExportDataExecute
0055afb0 heidisql.exe System.Classes           TBasicAction.Execute
00676245 heidisql.exe Vcl.ActnList             TCustomAction.Execute
0055aca4 heidisql.exe System.Classes           TBasicActionLink.Execute
008247e7 heidisql.exe Vcl.Menus                TMenuItem.Click
00826fde heidisql.exe Vcl.Menus                TMenu.DispatchCommand
00829305 heidisql.exe Vcl.Menus                TPopupList.WndProc
00829205 heidisql.exe Vcl.Menus                TPopupList.MainWndProc
0055c423 heidisql.exe System.Classes           StdWndProc
7ff867f7 USER32.dll                            DispatchMessageW
0084de7e heidisql.exe Vcl.Forms                TApplication.ProcessMessage
0084def3 heidisql.exe Vcl.Forms                TApplication.HandleMessage
0084e341 heidisql.exe Vcl.Forms                TApplication.Run
00de55a5 heidisql.exe heidisql          86 +27 initialization
7ff86743 KERNEL32.DLL                          BaseThreadInitThunk
7ff869b2 ntdll.dll                             RtlUserThreadStart

**Comment by ansgarbecker** [comment]
Duplicate to  #620

**Comment by ansgarbecker** [comment]
This was already fixed, by the way. Please update to the latest build to check that,
