### ISSUE TITLE
MySQL `LOAD` causes /* SQL Error (2027): Malformed packet */

### ISSUE THREAD

**Issue by denchat** [HeidiSQL/HeidiSQL#656]
## Steps to reproduce this issue

1. Set import csv input to a utf-8 file (BOM or no-BOM yield the same error)
2. Skip 1st row and select LOAD mode

## Current behavior

4. Then I get...
/* SQL Error (2027): Malformed packet */
5. Then the app seems unresponsive a minute
6. Then
/* Connection to xxx.xxx.xxx.xxx closed at [datetime] */
7. Then the app seems working once again but the import not succeeded.

## Environment

* **HeidiSQL version:** 
  
10.1.0.5575
* **Database system and version:** 
  
* **Operating system:** 
  

## Remark
- not reproducable in 5464
- Client mode works fine.

**Comment by ansgarbecker** [comment]
I cannot reproduce that here on MariaDB 10.3 / Windows. My LOAD command looks as follows:

    LOAD DATA LOCAL INFILE 'C:\\heidisql\\temp\\z.csv' INTO TABLE `test3`.`patrolgoliveservers` CHARACTER SET utf8 FIELDS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\r\n' IGNORE 1 LINES (`SERVER_NAME`);

The file just contains 1 column header and 1 row with 1 value. The value gets inserted correctly and there is no server error.

Please provide more details, e.g.
* the whole LOAD command
* the file itself (if it does not contain sensitive data)
* server version

**Comment by denchat** [comment]
From an old [thread](https://www.heidisql.com/forum.php?t=13487)

> * Downgrade libmysql.dll to a MariaDB-5.3.12 version. Fixes issue #3343 ("malformed packet" on LOAD DATA). All 5.5 versions seem to be affected, not so 5.3.x. Required tests for the next time I'm updating libmysql.dll: * Ensure LOAD DATA LOCAL INFILE works, and does not throw SQL error 2027/malformed packet * Ensure it's a .dll from the 32bit server version * Ensure it's a MariaDB version, so pluggable authentication still works
> * Update libmysql again with a version from MariaDB 5.5.33a. Fix SQL error 2027 "malformed packet", when firing LOAD DATA command. See http://www.heidisql.com/forum.php?t=13454 and issue #3262.
> 

Perhaps it's just my MySQL 5.7 which causes this issue. Maybe it's time to upgrade. You may now close this.

**Comment by ansgarbecker** [comment]
Thanks for feedback!
