### ISSUE TITLE
 Access violation at address 0069E7EC in module 'heidisql.exe'. Read of address 00E41000. Everytime I load the data to Heidi it shows me this error. Do I need to change any of the settings in Heidi? This is very frustrating because my data is around 7.5Gb which I am trying to import in Heidi and it takes around 2hrs to load the data and afterwards this error gets popped up. Please help!

### ISSUE THREAD

**Issue by pratyusaray** [HeidiSQL/HeidiSQL#658]
## Steps to reproduce this issue

1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
Please fill out the issue template.

Also, please update to the latest build and try again if not already done.

**Comment by pratyusaray** [comment]
date/time          : 2019-05-27, 09:05:14, 918ms
computer name      : OTTRAYP
user name          : rayp
registered owner   : Windows User
operating system   : Windows 8.1 x64 build 9600
system language    : English
system up time     : 2 days 15 hours
program up time    : 2 days 15 hours
processors         : 8x Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
physical memory    : 25225/32692 MB (free/total)
free disk space    : (C:) 856.06 GB
display mode       : 1680x1050, 32 bit
process id         : $1964
allocated memory   : 121.45 MB
largest free block : 1.37 GB
executable         : heidisql.exe
exec. date/time    : 2017-12-19 16:45
version            : 9.5.0.5196
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $e48ec0e1, $d98df469, $d98df469
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 0069E7EC in module 'heidisql.exe'. Read of address 00E41000.

main thread ($1980):
0069e7ec heidisql.exe SynEditHighlighter 1177   +9 TSynCustomHighlighter.Next
0069e8e7 heidisql.exe SynEditHighlighter 1229   +5 TSynCustomHighlighter.SetLineExpandedAtWideGlyphs
006be3ca heidisql.exe SynEdit            3618 +150 PaintLines
006be80c heidisql.exe SynEdit            3746  +53 TCustomSynEdit.PaintTextLines
006bc2f9 heidisql.exe SynEdit            2602  +61 TCustomSynEdit.Paint
005bba37 heidisql.exe Vcl.Controls                 TCustomControl.PaintWindow
005b5d71 heidisql.exe Vcl.Controls                 TWinControl.PaintHandler
005ba017 heidisql.exe Vcl.Controls                 TWinControl.WMPrintClient
005b1085 heidisql.exe Vcl.Controls                 TControl.WndProc
005b5ba5 heidisql.exe Vcl.Controls                 TWinControl.WndProc
006c3b6a heidisql.exe SynEdit            6330  +22 TCustomSynEdit.WndProc
005b0cc0 heidisql.exe Vcl.Controls                 TControl.Perform
005b65e7 heidisql.exe Vcl.Controls                 TWinControl.WMPaint
005bb9d1 heidisql.exe Vcl.Controls                 TCustomControl.WMPaint
005b1085 heidisql.exe Vcl.Controls                 TControl.WndProc
005b199a heidisql.exe Vcl.Controls                 TControl.WMMouseMove
005b1085 heidisql.exe Vcl.Controls                 TControl.WndProc
005b5ba5 heidisql.exe Vcl.Controls                 TWinControl.WndProc
006c3b6a heidisql.exe SynEdit            6330  +22 TCustomSynEdit.WndProc
005b51e8 heidisql.exe Vcl.Controls                 TWinControl.MainWndProc
0053c6d4 heidisql.exe System.Classes               StdWndProc
77c907d4 ntdll.dll                                 KiUserCallbackDispatcher
75daa984 user32.dll                                PeekMessageW
00686100 heidisql.exe Vcl.Forms                    TApplication.ProcessMessage
00686222 heidisql.exe Vcl.Forms                    TApplication.HandleMessage
0068655d heidisql.exe Vcl.Forms                    TApplication.Run
75817c02 KERNEL32.DLL                              BaseThreadInitThunk

**Comment by ansgarbecker** [comment]
That crash report says you are using an outdated version. Please update, as advised.
