### ISSUE TITLE
MySQL procedure 'create code' invalid code

### ISSUE THREAD

**Issue by sirber** [HeidiSQL/HeidiSQL#659]
## Steps to reproduce this issue

1. Create a stored procedure with the wizard and save it
2. Grab the code from the 'CREATE code' tab
3. Paste the code in a query tab and run it
4. Then I get wierd sql error about ''

## Current behavior

cannot create procedure

## Expected behavior

create a procedure

## Environment

* **HeidiSQL version:** 
10.1.0.5577
  

* **Database system and version:** 
MySQL 5.6.43
  
* **Operating system:** 
Windows 10

**Comment by sirber** [comment]
I have to add :
`delemiter //`

and change END for END//

**Comment by ansgarbecker** [comment]
Yes, that's it. That delimiter is set internally by the procedure editor, so you cannot just run the CREATE code without setting the delimiter. That's not a bug, is it?

**Comment by sirber** [comment]
Not a bug indeed, just something to know.
Thank you!
