### ISSUE TITLE
Old icons please

### ISSUE THREAD

**Issue by kingofnull** [HeidiSQL/HeidiSQL#662]
The new icon set is great but they did not pixel designed and remind me some of Chinese shitty softwares.
If there will be an option to select icon sets it would be awesome. I use HeidiSQL for years and used to old icons please bring back them to us, please 🙏.

Kind regards.

**Comment by ansgarbecker** [comment]
You reacted on your own post with thumbs up? Hehe...

The old Silk icons are still there, you can select them in Tools > Preferences > General: "Icon pack".

**Comment by kingofnull** [comment]
Thanks man I owe a world to you. And sorry about thumbs up I just try to encourage others to like issue.
 You made a tool that make our life a lot easier. We really appreciate it.
