### ISSUE TITLE
Selection not shown in dark material design config

### ISSUE THREAD

**Issue by ajuanjojjj** [HeidiSQL/HeidiSQL#663]
## Steps to reproduce this issue

1. Install HeidiSQL;
2. Select dark material design appearance;
3. Select any text either with mouse or with ctrl+arrows;

## Current behavior
Selection isnt shown

## Expected behavior
Selection is somehow marked

## Possible solution
I guess it has to do with the selecion color either not being set or being the same as background

## Environment
Clean install

* **HeidiSQL version:** 
HeidiSQL 10.1.0.5464
* **Operating system:** 
Win 10

**Comment by ansgarbecker** [comment]
Please update to the latest build. This was fixed after the last official release, and you can see it fixed in the nightly builds.
