### ISSUE TITLE
EAccessViolation - Access violation at address FFFFFFFFFA7768E0

### ISSUE THREAD

**Issue by ZachariasBrou** [HeidiSQL/HeidiSQL#665]
[bugreport1.txt](https://github.com/HeidiSQL/HeidiSQL/files/3247843/bugreport1.txt)

## Steps to reproduce this issue

1. Startup application
2. Alternatevily Startup app, on error window press continue, try to perform a search with table complete (ctrl+Space)
3. In both cases I get a pop-up window with " An error occured in the application"

## Current behavior

The problem started with the installation of the latest windows updates as these have been released on May 2019. This includes the following Microsoft security patches.

KB4498961,
KB4499164,
KB4498206,
KB890830,
KB4499406

## Environment

* **HeidiSQL version:** 
10.1.0.5464
* **Database system and version:** 
10.2.11-MariaDB
* **Operating system:** 
Windows 7 x64 Service Pack 1 build 7601

**Comment by ansgarbecker** [comment]
I committed a modification which could fix the issue. I only was not able to reproduce it, so please update to the latest build and test it.

**Comment by ZachariasBrou** [comment]
Hi, 

I installed it. 
Program starts (process is there in the Task Manager) but I cannot see it running as an app. There is no relevant icon in my task bar also. When I start it I can see it for tenths of a second and then disappears.

At least it does not crash.

Regards,
Zacharias

**Comment by ansgarbecker** [comment]
Ok, so you updated HeidiSQL to the latest build, and then it started with that immediate exit?

Could you perhaps restart your computer, so we can be sure there is nothing interfering going on?
