### ISSUE TITLE
table copy > rows total

### ISSUE THREAD

**Issue by atmanegara** [HeidiSQL/HeidiSQL#666]
## Steps to reproduce this issue

```sql
CREATE TABLE `issue-666` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`id`)
)
ENGINE=InnoDB;
```

1. Run the query above;
2. Go to Database tab and update (F5);
3. Open created table and go to Data tab;
4. Insert a new row;
5. Right-click on created table on left panel and go to Copy Table option;

https://www.youtube.com/watch?v=8Xz4YCJf3bw

## Current behavior

Data option is disabled and counting 0 row.

## Expected behavior

Data option should be enabled with the current number of rows.

## Possible solution

Before Copy Table dialog be displayed it should update the table informations.

## Environment

* **HeidiSQL version:**  r5585
* **Database system and version:** MariaDB 10.3.13
* **Operating system:** Windows 10 x64

**Comment by rentalhost** [comment]
I could reproduce it on **r5585** (I have updated the original post to use issue template).

_PS. on next time, please fill the issue template to help us._

**Comment by ansgarbecker** [comment]
Evil bug id... :o
