### ISSUE TITLE
Exporting data while auto-refresh active fails. 

### ISSUE THREAD

**Issue by paullupa** [HeidiSQL/HeidiSQL#669]
## Steps to reproduce this issue

1. Step 1; Create a database with  2 tables that have data
2. Step 2; Turn on "Auto Refresh"  ( 10 seconds )
3. Step 3; Right click on the  the database created in Step 1 
4: Step 4: Select "Export Database as SQL"
5: Step 5: Wait more than 10 seconds. (see step 2)
6: Step 6:  Click on the "Export" button.

## Current behavior
    Does not export the tables. 
       (note that if you manage to push the export button before a 'refresh' happens you 
        might get data)

## Expected behavior

   Should export the data.

## Possible solution

   1:  disable refresh while the export box is open.
   2:  export the data.

## Environment

  n/a

* **HeidiSQL version:** 
       10.1.0.5464  (64bit)   
              I originally had "I am not" but meant to say that "I have *NOT* downloaded the latest nightly build and tried it. "   ( sorry about that. ) 
* **Database system and version:** 
     MySQL 8.0.16
* **Operating system:** 
    Windows 10

**Comment by ansgarbecker** [comment]
Could you please repost your used HeidiSQL version? "I am not" was not the name of any release if I recall right :)

**Comment by rentalhost** [comment]
@ansgarbecker he is not too wrong:

```text
* **HeidiSQL version:** 
  <!-- Check if you are running the last available nightly version. -->
```

Anyway, I think that the rows auto refresh is not more available (or at least I could not found this option anymore haha).
