### ISSUE TITLE
Program crashes if run a new query after some time of program inactivity

### ISSUE THREAD

**Issue by Maxillus** [HeidiSQL/HeidiSQL#67]
### Steps to reproduce
1 - run any query 
2 - do nothing for some minutes eg. 5 minutes
3 - run again any  query and program crashes

it doesnt depends on query type
simple query as 
select  * from tables limit 1  crashes

### Context

* HeidiSQL version:   9.5.0.2506  - 64 bit
* Database system + version:
mysql  Ver 15.1 Distrib 10.2.8-MariaDB, for Linux (x86_64) using readline 5.1
* Operating system:
Linux Centos 6.9 

### Failure Logs

date/time          : 2018-01-02, 10:00:50, 59ms
computer name      : DESKTOP-0T8VTJP
user name          : paler
registered owner   : Utente Windows
operating system   : Windows 10 x64 build 16299
system language    : Italian
system up time     : 16 days 1 hour
program up time    : 16 minutes 58 seconds
processors         : 8x Intel(R) Core(TM) i7-4790S CPU @ 3.20GHz
physical memory    : 7102/12227 MB (free/total)
free disk space    : (C:) 696,35 GB
display mode       : 1920x1080, 32 bit
process id         : $2858
allocated memory   : 64,82 MB
largest free block : 131029,99 GB
executable         : heidisql.exe
exec. date/time    : 2017-12-19 16:46
version            : 9.5.0.5196
compiled with      : Delphi XE5
madExcept version  : 4.0.12
callstack crc      : $409e6063, $c23ff79a, $c23ff79a
exception number   : 1
exception class    : EAccessViolation
exception message  : Access violation at address 000000000083937E in module 'heidisql.exe'. Read of address 00000000000827AE.

main thread ($d5c):
0083937e heidisql.exe SynEditHighlighter 1177   +8 TSynCustomHighlighter.Next
00934885 heidisql.exe SynHighlighterSQL  1782  +34 TSynSQLSyn.Next
0083950c heidisql.exe SynEditHighlighter 1229   +5 TSynCustomHighlighter.SetLineExpandedAtWideGlyphs
00869510 heidisql.exe SynEdit            3618 +150 PaintLines
00869c7d heidisql.exe SynEdit            3746  +53 TCustomSynEdit.PaintTextLines
008652fc heidisql.exe SynEdit            2602  +61 TCustomSynEdit.Paint
006a5736 heidisql.exe Vcl.Controls                 TCustomControl.PaintWindow
0069c4e3 heidisql.exe Vcl.Controls                 TWinControl.PaintHandler
006a2f6d heidisql.exe Vcl.Controls                 TWinControl.WMPrintClient
0040cb1e heidisql.exe System                       TObject.Dispatch
00694b83 heidisql.exe Vcl.Controls                 TControl.WndProc
0069c24e heidisql.exe Vcl.Controls                 TWinControl.WndProc
00871f46 heidisql.exe SynEdit            6330  +22 TCustomSynEdit.WndProc
00694660 heidisql.exe Vcl.Controls                 TControl.Perform
0069d433 heidisql.exe Vcl.Controls                 TWinControl.WMPaint
006a56c8 heidisql.exe Vcl.Controls                 TCustomControl.WMPaint
0040cb1e heidisql.exe System                       TObject.Dispatch
00694b83 heidisql.exe Vcl.Controls                 TControl.WndProc
0069c24e heidisql.exe Vcl.Controls                 TWinControl.WndProc
00871f46 heidisql.exe SynEdit            6330  +22 TCustomSynEdit.WndProc
0069b48a heidisql.exe Vcl.Controls                 TWinControl.MainWndProc
005dbdc3 heidisql.exe System.Classes               StdWndProc
7ff86180 ntdll.dll                                 KiUserCallbackDispatcher
7ff85f13 user32.dll                                PeekMessageW
0081459c heidisql.exe Vcl.Forms                    TApplication.ProcessMessage
00814713 heidisql.exe Vcl.Forms                    TApplication.HandleMessage
00814bff heidisql.exe Vcl.Forms                    TApplication.Run
00ca0637 heidisql.exe heidisql             80  +24 initialization
7ff85f61 KERNEL32.DLL                              BaseThreadInitThunk
7ff8617c ntdll.dll                                 RtlUserThreadStart

**Comment by ansgarbecker** [comment]
This is the same callstack as in #57. Please go to that issue, verify you have the latest HeidiSQL build with the updated SynEdit code and recheck. I'm not sure on which HeidiSQL version you are, as you had a typo: "9.5.0.2506" doesn't exist.

**Comment by Maxillus** [comment]
version is 9.5.0.5206  is the last HeidiSQL build
