### ISSUE TITLE
[Feature request] Highlight all occurences of selected word in query editor

### ISSUE THREAD

**Issue by slorandus** [HeidiSQL/HeidiSQL#670]
## Steps to reproduce this issue
Double click any word in sql query editor.

## Current behavior
The double-clicked word will be selected.

## Expected behavior
The double-clicked word will be selected + highlight all other occurences of the same word using a different color than selected text.

## Possible solution
The same behavior like in Notepad++.

## Environment
* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
Next build highlights matching words with the color setting for matching braces:

![grafik](https://user-images.githubusercontent.com/7986591/158051895-2debb3f0-7628-405c-af28-dcae935a135e.png)
