### ISSUE TITLE
EAccessViolation - Access violation at address 000000000093C531

### ISSUE THREAD

**Issue by penhs** [HeidiSQL/HeidiSQL#672]
Although I saw other EAccessViolation issues posted previously, my issue is triggered differently. If I make a change to a column, click "Save" at the bottom (next to "Help" and "Discard") and switch over to another table, then there is no issue. However, if I make a change to a column without hitting that "Save" button, attempt to switch over to another table, and instead click "Yes" when the save confirmation window pops up, then I get the issue.

## Steps to reproduce this issue

1. I log into my school's VPN
2. Run HeidiSQL version 10.1.0.5587
2. Connect to a previously saved session with network type: MariaDB or MySQL (TCI/IP)
3. Have at least two tables
3. Click on a table on the left sidebar
4. Make a modification to a column, such as checking "Allow NULL"
5. Click on a different table on the left sidebar
6. When the PhiDB: Confirm alert pops up asking to save modified table, click Yes
![image](https://user-images.githubusercontent.com/46614782/59142991-24a0a000-897b-11e9-9065-4f1904ed0d94.png)
7. Error occurs
![error_general](https://user-images.githubusercontent.com/46614782/59143210-50bd2080-897d-11e9-860f-ca5ab218b72a.PNG)
![error_call_stack](https://user-images.githubusercontent.com/46614782/59143211-5286e400-897d-11e9-8b66-6c96a225b659.PNG)

## Current behavior

The modifications to the tables are actually saved but the error message will continue if I click "continue application".

## Expected behavior

I expected the modifications to the table to save and then the application switches over to the other table I selected.

## Possible solution

N/A

## Environment

* **HeidiSQL version:** 10.1.0.5587
  
* **Database system and version:** mysql  Ver 15.1 Distrib 10.1.38-MariaDB, for Linux (x86_64) using readline 5.1
  
* **Operating system:** Windows 10 x64 build 17763
  

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3268271/bugreport.txt)

**Comment by rentalhost** [comment]
Confirmed at **r5590**.

**Comment by ansgarbecker** [comment]
No longer reproducible, I guess fixed.
