### ISSUE TITLE
material theme cursor is not visible in query tab

### ISSUE THREAD

**Issue by tipasergio** [HeidiSQL/HeidiSQL#674]
## Steps to reproduce this issue

1. Open HendiSql;
2. Select meterial theme from tools-> preference-> style theme if is note selected ;
3. Restart program 
4. Open Query tab
5. Click on text area.

## Current behavior
cursor not visible on Query tab
## Expected behavior
shuld be visible
## Possible solution

maybe change background color

## Environment
* **HeidiSQL version:** 
10.1.0.55902

**Comment by ansgarbecker** [comment]
Cannot reproduce that. My cursor is visible:

![grafik](https://user-images.githubusercontent.com/7986591/59548099-01ad5780-8f4a-11e9-8ce8-79f39420c8eb.png)

Did you probably customize your text cursor in your Windows "_Cursor and pointer_" settings?

**Comment by tipasergio** [comment]
Hi. Thanks for response.
The problem apears only on exist tab. No problem in new one.
I think that the problem apears after error which appears when prgramm starts. For every exist query tab
![image](https://user-images.githubusercontent.com/6435956/59740832-ec9a3680-9271-11e9-9f72-7c104642f35e.png

**Comment by ansgarbecker** [comment]
Could we then please examine that access violation?

You could be so nice and check whether you have the following folder:
> C:\Users\xrusa...\AppData\Roaming\HeidiSQL\Backups\

And then please check if there are files, and if you are able to create some new file there without getting an error.

**Comment by ansgarbecker** [comment]
Ok, just reading your update. So HeidiSQL stores and restores your query tabs without errors now?

**Comment by tipasergio** [comment]
yeap. thank you for your time

**Comment by tipasergio** [comment]
shuld I close Issue by my self?

**Comment by ansgarbecker** [comment]
Doesn't matter, I'm doing that right now :)

**Comment by tipasergio** [comment]
Ok. Have a nice day.
