### ISSUE TITLE
Separate MySQL from MariaDB connection types

### ISSUE THREAD

**Issue by ansgarbecker** [HeidiSQL/HeidiSQL#677]
## Steps to reproduce this issue

Try to support a MySQL-only feature in "MariaDB/MySQL" connection type.

## Current behavior

Does not work, due to libmariadb loaded on any of these connections. See #296 for an example (cleartext authentication plugin is just a dummy on MariaDB)

## Possible solution

Separate MySQL from MariaDB connection types, so the user is able to prefer libmysql over libmariadb, and vice versa.

**Comment by ansgarbecker** [comment]
Related commits:
* a77eedde58cc9e62e9b7248fa3937f83956e481c TDbLib instance for each MySQL/MariaDB session
* a6ea858880d1f178b098a8b51c490fe4f8f79328 the same for PostgreSQL

**Comment by ansgarbecker** [comment]
This could alternatively be solved by providing a "Library" dropdown in the session manager, which auto-selects the best fitting one based in the last server version, unless the user selects one himself:
* libmysql (5.6.6)
* libmysql (5.7.x)
* libmariadb (10.1.x)
* ...

Would that be a feature for the "Advanced" tab, or more for the "Settings" tab?

**Comment by ansgarbecker** [comment]
![grafik](https://user-images.githubusercontent.com/7986591/60698325-2f554300-9eef-11e9-86d0-5186f36f19c6.png)

**Comment by zufuliu** [comment]
Please allow selecting system wide libmariadb.dll or libmysql.dll that comes with mariadb or mysql.
After using the single HeidiSQL.exe for many years, this no longer works since 10.2.0.5611. One have to put HeidiSQL.exe inside the bin folder in order to select the dlls, I think previously HeidiSQL automatically loads the dll without manually selecting.

**Comment by ansgarbecker** [comment]
Oh you rely on a libmysql/mariadb.dll somewhere on your harddisk? You should be experiencing random bugs in that case. Was there any benefit from using a lib that comes with mariadb or mysql?

You can also do it the other way around - copy the lib to your HeidiSQL directory.

**Comment by zufuliu** [comment]
No, I'm sure there only one on my system, which is in mariadb's bin folder.

> Was there any benefit from using a lib that comes with mariadb or mysql?

I don't know, since I use update to date mariadb release in local machine, possible there are bug fixes in lib.

**Comment by ansgarbecker** [comment]
Use any libmysql/mariadb you want, though that's neither supported nor recommended, as I already experienced incompatibilities betwen libraries and server versions. I already have two different libraries, libmysql can only be used for older servers, while it has SSL issues on newer ones. libmariadb can be used for newer servers only, and has problems with MySQL 4.0, see #697 .

**Comment by zufuliu** [comment]
I think #697 may indicates that it's better to use a libmysql/mariadb.dll that matches the server (e.g. same major? version) being connecting, some feature used by old server may be removed in newer client lib.

**Comment by ansgarbecker** [comment]
Yes, this is what this issue is about. The user now has the ability to select a different library if the default one does not work. In the future there may be even more than these two, only currently these work with any server version of which I know of.

**Comment by ansgarbecker** [comment]
Current state looks ok to me.
