### ISSUE TITLE
CrossVCL dependency

### ISSUE THREAD

**Issue by anerjan** [HeidiSQL/HeidiSQL#678]
Cant compile code without CrossVCL and its proprietary.

**Comment by ansgarbecker** [comment]
Never heard about CrossVCL.

Please explain more detailed, and answer at least some of the issue template questions.

**Comment by anerjan** [comment]
Can not resolve these dependencies Vcl.VirtualImageList, Vcl.BaseImageCollection, Vcl.ImageCollection I thought these are from CrossVCL, I was wrong can you help me resolve these dependencies. I'm using latest code with 10.2 Tokyo.

**Comment by ansgarbecker** [comment]
10.2 is not new enough. You need Delphi 10.3 at least, which has VirtualImageList. Better use 10.3.1.
