### ISSUE TITLE
MariaDB integer field can not be set to 0 by default,and the comment can not be set successfully

### ISSUE THREAD

**Issue by ajisheng** [HeidiSQL/HeidiSQL#68]
MariaDB integer field can not be set to 0 by default,and the comment can not be set successfully.
My MariaDB version is 10.2.8
My HeidiSQL version is 9.5.0.5209

**Comment by ansgarbecker** [comment]
The issue template should not be just removed, but filled out :)
You could at least explain what's _exactly_ happening when you try to set a default "0". For example whether there is some error message.

**Comment by ajisheng** [comment]
![heidisql](https://user-images.githubusercontent.com/25262830/34593036-56ff4058-f203-11e7-9b1a-ac2ef1f4f970.png)
![phpmyadmin](https://user-images.githubusercontent.com/25262830/34593047-64bdc02a-f203-11e7-95c4-74c627302404.png)

**Comment by ansgarbecker** [comment]
Thanks for the self-explanatory screenshots!

I have difficulties to reproduce that though. Could you post the result of `SHOW CREATE TABLE ds_department` code here?

**Comment by ajisheng** [comment]
`CREATE TABLE `ds_department` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL DEFAULT '',
  `org_id` int(11) DEFAULT 0 COMMENT '从属学校/机构的id',
  `parent_id` int(11) DEFAULT 0 COMMENT '上级部门id',
  `chief_userid` int(11) DEFAULT 0 COMMENT '负责人userid',
  `deputy_userid` int(11) DEFAULT 0 COMMENT '副负责人userid',
  `building_id` int(11) DEFAULT 0 COMMENT '楼宇id',
  `floor_id` int(11) DEFAULT 0 COMMENT '楼层id',
  `room_id` int(11) DEFAULT 0 COMMENT '房间id',
  `tel` varchar(15) DEFAULT '' COMMENT '电话号',
  `tel_ext` int(6) DEFAULT NULL COMMENT '电话分机',
  `fax` varchar(15) DEFAULT NULL COMMENT '传真',
  `fax_ext` int(6) DEFAULT NULL COMMENT '传真分机',
  `remark` varchar(200) DEFAULT '' COMMENT '备注',
  `create_time` timestamp NULL DEFAULT current_timestamp() COMMENT '创建时间',
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp() COMMENT '更新时间',
  `create_userid` int(11) DEFAULT 0 COMMENT '创建人userid',
  `create_ip` char(15) DEFAULT '' COMMENT '创建ip',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='部门表';`

**Comment by ansgarbecker** [comment]
After copying your CREATE code and running it on my local mysql 5.7.9 server, I can see all column comments:
![table-editor-chinese-comments](https://user-images.githubusercontent.com/7986591/34643303-64646262-f322-11e7-9626-c3f574a71f43.png)

Probably this issue is related to some charset setting on your side. Could you please fire the following query on your server and post the results here (rightclick -> export grid rows -> copy to clipboard in markdown format):

    SHOW VARIABLES LIKE '%character_set%'

Here are my results for the that query:

| Variable_name | Value | 
| --- | --- | 
| character_set_client | utf8mb4 | 
| character_set_connection | utf8mb4 | 
| character_set_database | utf8 | 
| character_set_filesystem | binary | 
| character_set_results | utf8mb4 | 
| character_set_server | latin1 | 
| character_set_system | utf8 | 
| character_sets_dir | C:\Wamp\mysql-5.7.9-winx64\share\charsets\ |

**Comment by Gemorroj** [comment]
Maybe problem reproduced only in `mariadb`
I use mariadb 10.2.12
Hidesql 9.0.5.5196

```sql
SHOW CREATE TABLE orders;

CREATE TABLE `orders` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `facebook_id` bigint(20) unsigned NOT NULL COMMENT 'Facebook ID',
  `date_create` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'Дата создания записи',
  `currency` char(3) NOT NULL COMMENT 'Валюта. Справочник ISO 4217',
  `total_cost` decimal(12,2) unsigned NOT NULL COMMENT 'Общая стоимость заказа',
  `is_legal_person` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Юридическое лицо',
  `attributes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin COMMENT 'Произвольные атрибуты в JSON',
  PRIMARY KEY (`id`),
  CONSTRAINT `orders_attributes_json_valid` CHECK (json_valid(`attributes`))
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='Заказы'
```
![hidesql](https://user-images.githubusercontent.com/885731/34643700-da7a7fc4-f339-11e7-8bfd-eed91d266858.png)
![character](https://user-images.githubusercontent.com/885731/34643726-2e4703a2-f33a-11e7-882d-d208b2a98a18.png)

**Comment by ajisheng** [comment]
Only exists in MariaDB，you can try use MariaDB.

**Comment by ansgarbecker** [comment]
I can finally reproduce that, on MariaDB 10.2.12 - curious

**Comment by ansgarbecker** [comment]
Should work now. Please check that in the new nightly build.

**Comment by Gemorroj** [comment]
HeidiSQL 9.5.0.5219 works well on my case.
Except that doesn't work `CONSTRAINT`. see #75

**Comment by ajisheng** [comment]
HeidiSQL 9.5.0.5219，Solve the problem, thank you very much!
