### ISSUE TITLE
Go-To action for "Multi Column Filter"

### ISSUE THREAD

**Issue by H4NNE5** [HeidiSQL/HeidiSQL#681]
## Steps to reproduce this issue

No issue, just a "nice to have" feature

## Current behavior

User has to click into edit field

## Expected behavior

User should also have a keyboard command for that purpose

## Environment

* **HeidiSQL version:** 
10.1.0.5559

**Comment by ansgarbecker** [comment]
Just added that to the "go to" menu.

See also the related issue #698
