### ISSUE TITLE
Table Comment disappears when saved

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#683]
## Steps to reproduce this issue

1. Go to Table Basic tab
2. Type a comment in the appropriate field.
3. Press Save button.
4. A comment field text unexpectedly returns to the previously saved text (but anyway, new comment seemes to be saved correctly).
5. Reload table and now I see my new comment.

## Expected behavior

Comment does not back to the previous.

## Environment

Windows 10 64 bit with last update.

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
Please post versions of HeidiSQL and server.

**Comment by AlexLunyov** [comment]
I'm using HeidiSQL 10.2.0.5606 with 5.5.31-MariaDB running on Ubuntu Server 16.04.

**Comment by davekc** [comment]
I experience something that may be related: if I save this "\.\-" as a comment it saves as "\\.\\-" then saves as "\\\\.\\\\-" when I save again...

HeidiSQL 10.2.0.5599 with 10.3.16-MariaDB

**Comment by id0612** [comment]
@ansgarbecker I reproduced this bug in the latest version.    10.2.0.5683

**Comment by ansgarbecker** [comment]
This is caused through my solution for #196

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.

**Comment by AlexLunyov** [comment]
Yes, it works, thanks!
