### ISSUE TITLE
"Run unsafe queries without a WHERE clause" when update statement is commented out!

### ISSUE THREAD

**Issue by somethingweird** [HeidiSQL/HeidiSQL#685]
HeidiSQL Version 10.2.0.5599

## Steps to reproduce this issue

1.  In Query tab - just entered "# UPDATE ANYTABLE SET FIELD=1" 
2.  Execute Query
3.  Confirmation Dialog will pop up "Run unsafe queries without a WHERE clause"

Should it bring up the confirmation dialog even 
if the update SQL statement is commented out?

**Comment by ansgarbecker** [comment]
This is certainly a bug. HeidiSQL obviously does not check whether the update or delete command is just a comment.

**Comment by somethingweird** [comment]
Update, addition bugs related to this issue.

1. In Query Tab - enter 
# UPDATE ANYTABLE SET FIELD=1 WHERE 1=1
UPDATE ANYTABLE SET FIELD=1

2. bypass the confirmation dialog - "Run unsafe queries without a where clause"

This also is true if you have two uncommented update statements, first statement with a where clause and second statement has no where clause.

**Comment by decadence** [comment]
I ran into this problem today with this query:

```sql
# UPDATE import_row
# SET category_id = (
	SELECT id 
	FROM bank_categories 
	ORDER BY RAND()
	LIMIT 1
# )
```
