### ISSUE TITLE
random code

### ISSUE THREAD

**Issue by Liubaoen** [HeidiSQL/HeidiSQL#686]
I found a bug where I was using it !!
version : 10.1.0.5487
SQL：select * FROM bowen.credit_pointslogs procedure analyse(250,1024);
problem：I found garbled codes in Chinese in the results of execution .
Please refer to the attachment for details !
We hope the engineers can solve it !!! thanks !!!
[bug_picture.docx](https://github.com/HeidiSQL/HeidiSQL/files/3319933/bug_picture.docx)

**Comment by ansgarbecker** [comment]
Please follow the instructions in the issue template.
