### ISSUE TITLE
Restoring unsaved queries should also restore the bound parameters

### ISSUE THREAD

**Issue by WesleyM77** [HeidiSQL/HeidiSQL#689]
## Steps to reproduce this issue

1.  close Heidi with an unsaved query that used parameters and had them bound.
2. Open Heidi and have it restore that query
3. The bound parameters are missing. 

## Current behavior

Does not restore bound parameters on unsaved queries.

## Expected behavior

It probably should?

**Comment by ansgarbecker** [comment]
Bind parameters are now stored and restored with other query tab related stuff, including the activation state on/off.

Would be nice to get feedback if that works for you, before the v10.3 release in mid of December.

**Comment by WesleyM77** [comment]
Seems to be working as expected. Thank you!

**Comment by ansgarbecker** [comment]
Thanks for your feedback!
