### ISSUE TITLE
Comment field re-escape escaped characters

### ISSUE THREAD

**Issue by davekc** [HeidiSQL/HeidiSQL#690]
## Steps to reproduce this issue

1. Save a table comment as "&#92;-&#92;."
2. The comment saves correctly (which is perfect) but is shown as "&#92;&#92;-&#92;&#92;." (which is wrong)
3. Then same again (even without modifying the comment itself)
3. The comment saves as "&#92;&#92;-&#92;&#92;." (which becomes a problem)

## Current behavior

Comment field re-escape escaped characters (visually then on save)

## Expected behavior

Comment field should show and save as entered

## Possible solution

Manually unescape re-escaped characters before saving

## Environment

* **HeidiSQL version:** 
  10.2.0.5607
* **Database system and version:** 
  10.3.16-MariaDB

**Comment by ansgarbecker** [comment]
Heidi takes the table comment from the most recent result of `SHOW TABLE STATUS`, to not include unwanted create options, like described in #196.
However, backslashes are not double-escaped here, on MariaDB 10.3.12 . But maybe you can post the result of these both queries:
```
SHOW TABLE STATUS LIKE 'yourtable';
SHOW CREATE TABLE yourtable;
```

**Comment by davekc** [comment]
Here's the requested informations:
[heidi.txt](https://github.com/HeidiSQL/HeidiSQL/files/3330952/heidi.txt)

Also, to simply let you know that it works (without escaping issue) under an old Navicat MySQL version I have (v9.1.12) even if I am using MariaDB...

Thanks a lot!

**Comment by ansgarbecker** [comment]
Are we now talking about a column comment?
In the opening comment you said it's a table comment.

**Comment by davekc** [comment]
So sorry, my mistake... always been a column comment! 😳

**Comment by ansgarbecker** [comment]
Ok no problem. That explains my confusion while testing that. However, column comments should work in the latest build - I fixed the incomplete un-escape logic.

**Comment by davekc** [comment]
Yes it is, working like a charm now. Thanks a lot!
