### ISSUE TITLE
enhancement: see full sql in query history

### ISSUE THREAD

**Issue by khorsky** [HeidiSQL/HeidiSQL#693]
1. Run any query in query window
2. Look at query history
3. hover over any query in history

## Current behavior
I can see only first line of the query sql, which is helpful only for short/easy queries. I often use (formatted) queries that are 10-15 lines long - the only difference are their conditions. Conditions are on the end of the query - so the query hint is not useful at all for this use case.

The only way is to open the query one by one - that works, but takes time.

## Expected behavior
I would like to be able to see complete query sql in query history hint.

**HeidiSQL version:** 
AFAIK all versions

**Comment by WesleyM77** [comment]
I feel like putting the entire query in a tooltip could potentially cause some issues, especially with long ones as you mentioned. I know some of mine get quite large as well. Might I suggest that it would show a preview of the query in the query tab where it will be placed? If done this way, it might be a good idea to keep the tooltip as-is to reinforce to the user that the preview is shown as a result of where the cursor is.

**Comment by ansgarbecker** [comment]
Sounds reasonable. I recall I already tried to do that, but had probklems in setting up the VirtualTree instance in a way that tooltips are only shown when necessairy, but I should definitely give it a new try.

**Comment by ansgarbecker** [comment]
These tooltips were just clipped when displayed, while they were always fully loaded. I just changed the `HintMode` for that tree to `hmHint`, so it's now capable of displaying multiple lines in a tooltip.
Not sure why I did not activate that by default for all other trees, except for data grids.

**Comment by khorsky** [comment]
It works perfectly. Thanks.
