### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yagizher** [HeidiSQL/HeidiSQL#694]
Hi. Im trying to connect to a database using HeidiSQL. I opened my sql port using Xampp.But when i try to open a database, im getting 'Host 'localhost' is not allowed to connect to this MariaDB server' error. Please help me.
![Screenshot_2](https://user-images.githubusercontent.com/52376710/60397159-9de27b80-9b52-11e9-91ff-19a146fd961f.png)

**Comment by ansgarbecker** [comment]
Not an issue in HeidiSQL directly. The message means, your user account lacks the privilege to connect from "localhost". You will have to change the host for this account on the server to "localhost", or to a wildcard "%". The internet has some help for this very common error: https://stackoverflow.com/questions/25003590/host-localhost-is-not-allowed-to-connect-to-this-mysql-server
