### ISSUE TITLE
Losing focus on double-click on Default cell

### ISSUE THREAD

**Issue by al2k4** [HeidiSQL/HeidiSQL#695]
## Steps to reproduce this issue

1. Go to Table view.
2. Quickly double-click any cell in the "Default" column.

## Current behavior

Application loses focus to the previously active application.

## Expected behavior

Application should still have focus.

## Environment

* **HeidiSQL version:** 10.2.0.5610
  
* **Operating system:** Win 10 1903 64-bit

**Comment by ansgarbecker** [comment]
Seems to be caused by a redraw message sent to the underlying main window:
https://github.com/HeidiSQL/HeidiSQL/blob/a9fd8be2f3734bacdd35fc4329a91a07c84ed124/source/grideditlinks.pas#L244

**Comment by User756675678** [comment]
Bug still appear in latest official version: v11.0.0.5919 (64 Bit).

It's been over a year now. Many versions were released, the bug was confirmed, the developer even announced where the problem is, down to a specific line of code, but the bug still exists.

Any chance fix it?

**Comment by ansgarbecker** [comment]
Well, sorry for the delay. I think I was hesitating because there was a reason for this redraw message, which I just don't recall. But I removed it for now, to see if that does not introduce another issue.
See my old commit 6d338d515f03e0537053909c647231f250c7851d where I moved that redraw message from `PrepareEdit` to the constructor.

**Comment by ansgarbecker** [comment]
Please re-check with the next nightly build. Do not just use the stable release when reporting bugs.

**Comment by User756675678** [comment]
If 6d338d5 will be mention here then someone can check and tell about problem stay here.
In any case - thanks, problem (switch to previous app) fixed.
Exists another problems with this double click, but it for another issue.
