### ISSUE TITLE
Why not support connected by ssh public key??

### ISSUE THREAD

**Issue by jiafeijiang** [HeidiSQL/HeidiSQL#696]
## Steps to reproduce this issue

1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
This is not a valid issue or enhancement report. This is a bugtracker, not a discussion forum. Please follow the guide in the issue template.
