### ISSUE TITLE
Unable to create a connection using a Mysql 4 database

### ISSUE THREAD

**Issue by djib123456** [HeidiSQL/HeidiSQL#697]
[bugreport_heidiSQL.txt](https://github.com/HeidiSQL/HeidiSQL/files/3350143/bugreport_heidiSQL.txt)

## Steps to reproduce this issue

1. Step 1: Install and start Mysql4 on your computer
2. Step 2: Create a database in Mysql 4 
3. Step 3: Start HeidiSQL and try to connect to the previously created database
4. Then you get a error message saying : << Column 'Name' not available >>

## Current behavior

Error message saying : << Column 'Name' not available >>

## Expected behavior

We should be able to connect without issue, just like in the previous Heidi versions. 

## Environment

No particular setup is related to that issue, I use a basic windows computer, everything was working perfectly, then I updated HeidiSQL, and all my bases using Mysql 4 are not usable anymore (only in HeidiSQL).

* **HeidiSQL version: 10.2.0.5599 **

**Comment by ansgarbecker** [comment]
The code from the callstack is only executed when the server has a version > 5.0.10. Could you please post the result of `SELECT VERSION()` here.

**Comment by djib123456** [comment]
The result is 4.0.27-nt

**Comment by ansgarbecker** [comment]
Ok, that should normally avoid running that `SHOW TRIGGERS` query. Unless the version variables say something else. Could you please telll what the "version" and "version_comment" says on that server:

    SELECT @@version, @@version_comment

**Comment by djib123456** [comment]
I get the error " unknown system variable 'version_comment' "

**Comment by ansgarbecker** [comment]
Ah well, then what is @@version then? I suppose the same as what `SELECT VERSION()` returned?

**Comment by djib123456** [comment]
Yes it is the same result.

Mohamed Diarra
Technical Support Specialist
Aircraft Maintenance Systems RD Inc.
[cid:image006.png@01CC6701.60EC2A20]
www.aircraftms.com<http://www.aircraftms.com/> | Phone: +1 514-508-7022 | Toll Free : Free: +1 888-471-0252<tel:%2B1%20888-471-0252>
Mohamed.D@aircraftms.com<mailto:Mohamed.D@aircraftms.com>
Please take note of AMS' official Technical Support help line number: (1) 514-508-7022. Starting August 1, 2018, it will be the only number to reach us at.
Veuillez prendre note qu'en date du 1er août 2018, le seul numéro pour contacter le département de Support Technique sera le suivant: (1) 514-508-7022

**Comment by djib123456** [comment]
![image](https://user-images.githubusercontent.com/52455887/60604312-6b6c9480-9d85-11e9-86e5-048760220b6e.png)

**Comment by djib123456** [comment]
Yes, it is the same result

**Comment by ansgarbecker** [comment]
Just started my good old MySQL 4.0 instance, and I can now reproduce the error. Even worse, in some cases HeidiSQL is terminated without any error message.

**Comment by ansgarbecker** [comment]
When forcing HeidiSQL to use libmysql.dll instead of the newer libmariadb.dll, that works as expected.

**Comment by ansgarbecker** [comment]
If you rename or delete libmariadb.dll from your HeidiSQL folder, you should be fine for the moment. This is a workaround, not a solution. The newer lib is required for other things like TLS >1.0 connections.

**Comment by djib123456** [comment]
Good to know that you’ve been able to reproduce it. When deleting the libmariadb.dll it also works or me, so for now I’m good now. Looking forward to a permanent solution.

**Comment by ansgarbecker** [comment]
Just tried some newer libmysql libraries:
* libmysql.dll from server 5.7.26 - same problems as libmariadb.dll with a 4.0 server
* libmysql.dll from C Connector 6.1.11 - same problems

I suppose #677 is the way to go - or even some approach which detects the server version automatically.

**Comment by ansgarbecker** [comment]
The next build has a library dropdown on the session manager, so you can select the right dll from there, if the default one (libmariadb.dll) does not work.

**Comment by ansgarbecker** [comment]
@djib123456 could you please update to the latest build and check if your connection works, after selecting "libmysql.dll" in the new "Library" dropdown on the session manager?

**Comment by djib123456** [comment]
I just tried and it is working when I choose "libmysql.dll", thank you for your quick fix

**Comment by ansgarbecker** [comment]
Great!
