### ISSUE TITLE
Enhancement: keyboard shortcut to switch to results area

### ISSUE THREAD

**Issue by eliasak** [HeidiSQL/HeidiSQL#698]
This request is to add a keyboard shortcut to jump to the Results tab, from the SQL editor area, and the same key should rotate back to the SQL editor, if its in the Results tab.

 FYI, SSMS uses the "F6" keyboard key for this switch between Editor, Results (and in ssms, Output Messages)

 I saw the request in the forums (https://www.heidisql.com/forum.php?t=27210), but there was no existing ticket.

**Comment by ansgarbecker** [comment]
I just added a "Switch to query/results" item to the "Go to" menu, with the default shortcut <kbd>F6</kbd>. See the next build.

**Comment by ansgarbecker** [comment]
Update: "Switch to query/results" now also supports the similar thing in the "Data" tab if that is active: toggling between filter and result grid.
