### ISSUE TITLE
Multiple screen display problem

### ISSUE THREAD

**Issue by geszabo** [HeidiSQL/HeidiSQL#699]
### **Connection settings view**
![image](https://user-images.githubusercontent.com/46504192/60571495-00669200-9d74-11e9-925a-f94888a0cc1b.png)

![image](https://user-images.githubusercontent.com/46504192/60571669-563b3a00-9d74-11e9-8faa-23f9458571ae.png)

### **Table option view**
![image](https://user-images.githubusercontent.com/46504192/60571994-e8dbd900-9d74-11e9-9fd1-ed0d47322cf8.png)

### **Settings view**
![image](https://user-images.githubusercontent.com/46504192/60572309-9fd85480-9d75-11e9-8fc2-fbe880f4d877.png)

and other.....

### **Display settings**
![image](https://user-images.githubusercontent.com/46504192/60572560-268d3180-9d76-11e9-919c-87fd440de219.png)

**Comment by ansgarbecker** [comment]
Could you please say in words what your screenshots shall express?

**Comment by geszabo** [comment]
this is a little problem, just Labels are not fit.

**Comment by geszabo** [comment]
Thank for 10.2.0.5636 and 10.2.0.5637 revisions. Problem is solved.
