### ISSUE TITLE
Autocomplete sort order

### ISSUE THREAD

**Issue by evilworm** [HeidiSQL/HeidiSQL#7]
## Expected behavior

Two possible behaviors:
1) autocomplete should sort by alphabetical order (or it should be an option in the settings)
2) autocomplete should complete the text only when I press "enter" and not when I press "space"

## Current behavior

Autocomplete does not sort columns, they are displayed in the same order as you have them in the table. Therefore you might pick wrong column name from the popup in certain situations.

## Failure information (for bugs)

If you have several columns with similar names, it could lead to autocomplete picking wrong item when you press space-bar.

### Steps to reproduce

1. create a table with two columns "column_a" and "column"
2. write a query and have autocomplete to show you suggestions for the table
3. type "column" and press space... your text will be changed to "column_a"

### Context

* HeidiSQL version: 9.4.0.5186
* Operating system: Windows 10

### Failure Logs

(pressing space at this moment will autocomplete with the "field_b" column name which was not intended)
![screenshot_7](https://user-images.githubusercontent.com/5744459/32602988-dac92c3a-c550-11e7-9cae-2fbeb5dbc0b0.jpg)

**Comment by ansgarbecker** [comment]
Ok, there are even more key strokes which trigger the completion, e.g. the <kbd>Tab</kbd> key does the same as <kbd>Enter</kbd>. <kbd>Space</kbd> indeed does the same + it inserts a space after the completed word. I wouldn't say this is wrong, but a matter of being used to.

For the non-alphabetical order, this is intentionally left as columns are created in the table. Typing first characters will normally find what you want.

Do issues support some voting here on GitHub? I'd like to leave this open and wait for comments from other users.

**Comment by evilworm** [comment]
It would also be OK if the autocomplete would not be triggered on `Space`. This is really annoying ... if you have the column names in a wrong order then you are stuck with pressing `ESC ` key every time when you write the shortest column name.

**Comment by oliveru** [comment]
Some additions: 
If I'm on the data tab for a table, I can add filters which is nice without typing a whole query. Usually the columns also refer to only that table in view. Would be nice if the autocomplete triggers when typing automatically because it is obvious that I meant to type one of the columns of this table. At least if not by default, maybe per option.

Also:
I would agree with the sorting option.

**Comment by ansgarbecker** [comment]
Todos here:
[ ] sort items alphabetically
[ ] look for a way to prevent completion when user presses space

**Comment by ansgarbecker** [comment]
@oliveru one thing: in the meantime, the filter box in the Data tab has that auto complete box. Just press <kbd>Ctrl+Space</kbd> to trigger it:
![grafik](https://user-images.githubusercontent.com/7986591/70548722-55a09e00-1b73-11ea-9868-942eb3b7dbc7.png)

**Comment by ansgarbecker** [comment]
* items are sorted alphabetically, mixing columns, tables, functions etc. together
* <kbd>space</kbd> no longer overtakes the focused item in the proposal

The latter one feels wrong somehow, especially because the proposal is not closed. So you need to press <kbd>Esc</kbd> to get rid of the now useless proposal.

Additionally, the option `scoEndCharCompletion` does not do the same, where I expected that. This is probably a bug in SynEdit, not sure. Anyway, my removal of <kbd>space</kbd> should do the same. Hopefully that does not break something else.

Please update HeidiSQL and test this well.

**Comment by evilworm** [comment]
on version 5871, still seeing the same behavior
![2020-02-07_12-50](https://user-images.githubusercontent.com/5744459/74023532-8bfa6e00-49a8-11ea-80f5-fb107e3f9946.png)

it does the same auto-complete when I type "field" and press space... the field is autocompleted to "field_b"

additionally I started to get TCustomForm.SetActiveControl error when editing table structure and trying to erase column name by backspace

![2020-02-07_12-46](https://user-images.githubusercontent.com/5744459/74023655-d7148100-49a8-11ea-8a30-d98161a5082a.png)

I'm running this on ubuntu through wine, tho. Will test it on windows later today...

**Comment by ansgarbecker** [comment]
Oh you need one further update, please use build 5872.

The backspace issue has nothing to do with these changes. However, these were reported before and seem to be limited to Wine.

**Comment by ansgarbecker** [comment]
@evilworm could you please update and test the proposal in conjunction with pressing <kbd>space</kbd>?

**Comment by evilworm** [comment]
Just tested version 5877. I did notice that the auto-complete popup does not close after pressing space which you already mentioned. It is kept open without any items in it. If you don't press ESC but for example type "equal" sign and the column name has a special meaning then the column is wrapped in quotes including the space.
Here is a test case:
```SELECT * FROM testxxx rr WHERE rr.`field `=```

**Comment by evilworm** [comment]
Btw another proposal is to sort the auto-complete popup entries by shortest first. I'm using VSCode for development and also PHPStorm and those editors always show shortest words first. An example below.
1) if you press space in vscode, it doesn't autocomplete the word, the popup is closed and the typed word is left as-is
2) if you press enter, it will autocomplete the currently selected word
3) if you continue to write something after pressing enter then the auto-complete popup will show again
4) so to type AnimationEffect you can type An, press enter, type E, press enter
![Screenshot_154](https://user-images.githubusercontent.com/5744459/74281343-f3a51600-4d26-11ea-84ee-d4b1100b5501.jpg)

**Comment by ansgarbecker** [comment]
I think I will revert the new sorting in the completion proposal. I got negative feedback from another [user in the forum](https://www.heidisql.com/forum.php?t=35659) and to me personally it also feels wrong somehow.
