### ISSUE TITLE
Remember last-used collation when creating new database

### ISSUE THREAD

**Issue by Beep6581** [HeidiSQL/HeidiSQL#702]
HeidiSQL 10.2.0.5599

When I create a new database, I have to keep searching for and selecting `utf8mb4_unicode_ci`. It would be nice if HeidiSQL remembered the last-used collation and automatically selected that.

**Comment by ansgarbecker** [comment]
Currently HeidiSQL auto-selects the server's default collation, which is also displayed in a label below the dropdown:

![grafik](https://user-images.githubusercontent.com/7986591/60681615-37ca6100-9e90-11e9-95f0-377843f2185e.png)

Probably it makes sense to override that at least if the user already created a database earlier.
