### ISSUE TITLE
No/wrong sorting of items in bulk table editor comboboxes

### ISSUE THREAD

**Issue by Beep6581** [HeidiSQL/HeidiSQL#703]
HeidiSQL 10.2.0.5599

The contents of the following comboboxes are unsorted or incorrectly sorted:
- Change table engine
- Change default collation
- Convert to charset

![screenshot_20190704_144615](https://user-images.githubusercontent.com/5844619/60667917-fc696b80-9e6a-11e9-8228-92b07099a316.png)
![screenshot_20190704_144855](https://user-images.githubusercontent.com/5844619/60667918-fc696b80-9e6a-11e9-9d20-60a8bc63ee76.png)

**Comment by felixpenrose** [comment]
+1 I've definitely wasted a fair amount of time trying to find `utf8mb4_unicode_ci` in these lists as there's very little sense to the order, and there's a *lot* of them to scroll through.

It would be a great help if these combo boxes could be sorted alphabetically, and would be even better if we could filter items by typing.

An example of what I mean can be seen in the select 2 JS plugin: https://select2.org/appearance

**Comment by leeoniya** [comment]
this looks like an overlooked case of https://github.com/HeidiSQL/HeidiSQL/issues/579

**Comment by ansgarbecker** [comment]
Collations are sorted in the next build, while charsets need a bit more effort, as these use an internal list where the index is important to keep.

**Comment by ansgarbecker** [comment]
Character set pulldown is now also sorted alphabetically, and moves the charsets description from left of the name to the right of it:

![grafik](https://user-images.githubusercontent.com/7986591/70849927-411b1900-1e85-11ea-9220-f73713ab0a0b.png)

**Comment by Novocaine88** [comment]
Good stuff, many thanks!

**Comment by Beep6581** [comment]
Thank you.
