### ISSUE TITLE
Support SSL option for PostgreSQL

### ISSUE THREAD

**Issue by madankumark** [HeidiSQL/HeidiSQL#704]
## Steps to reproduce this issue

1. Select Network Type as PostgreSQL (TCP/IP) and this will disable use SSL in Advanced Tab.

## Current behavior

Doesn't support passing SSL certificate for connecting to PostgreSQL

## Expected behavior

Should enable use SSL option for PostgreSQL (TCP/IP)

## Environment

* **HeidiSQL version:** 10.2.0.5599 (64 Bit)
  
* **Database system and version:** PostgreSQL 9.6
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
Could you give some hints on how to enable SSL communication using the C API?

**Comment by ansgarbecker** [comment]
Documentation on how to connect via SSL is available on [postgresql.org](https://www.postgresql.org/docs/9.1/libpq-connect.html)

My just pushed change adds support for SSL on PG. So, the checkbox on the "Advanced" tab is enabled now for PG connections, and the first 3 edit boxes get passed to `PQconnectdb`. Only the last one is yet unused - the list of permissible ciphers. In MySQL this is supported, but for PG I can't find anything in the docs about such an option. Or did I miss it?

My own attempt to connect with SSL just failed:
![grafik](https://user-images.githubusercontent.com/7986591/62046061-47c32f80-b207-11e9-981f-766f70ded93b.png)

**Comment by Dionyzos73** [comment]
Hello,

I connect with several software to my PostgreSQL server successfully (EMS SQL Manager, DATAGrip, pgAdmin, ...), using SSL files (key, ca cert and client cert)

But with the last HeidiSQL version it's impossible ! This is the error message when i try : ![error message](https://www.heidisql.com/uploads/34330-1-screen_hsql3.png)

And my parameters connection : ![params1](https://www.heidisql.com/uploads/34330-2-screen_hsql1.png) & ![params2](https://www.heidisql.com/uploads/34330-3-screen_hsql2.png)

I don't understand why HeidiSQL don't want connect to my server :-(

Thanks

**Comment by ansgarbecker** [comment]
Maybe there is another missing setting which must be set, in the pqconnectdb call.

I should have a look at the code of some other client which uses the c api.

**Comment by ansgarbecker** [comment]
I can't find an example C program to look at the SSL configuration. On postgresql.org they provide some [example programs](https://git.postgresql.org/gitweb/?p=postgresql.git;a=tree;f=src/test/examples;hb=HEAD), but they all do nothing with ssl.

pgAdmin has some example JSON configuration, which makes use of a "ssl-crl" setting, which HeidiSQL not yet does. Does anyone know what this *.crl file does on the connection? SSL compression is also yet unused by HeidiSQL but I guess that does not make any difference.
```
                ...
                "SSLMode": "require",
                "SSLCert": "/path/to/sslcert.crt",
                "SSLKey": "/path/to/sslcert.key",
                "SSLRootCert": "/path/to/sslroot.crt",
                "SSLCrl": "/path/to/sslcrl.crl",
                "SSLCompression": 1,
                ...
```

**Comment by ansgarbecker** [comment]
Just found it in the documentation:
> sslcrl
>    This parameter specifies the file name of the SSL certificate revocation list (CRL). Certificates listed in this file, if it exists, will be rejected while attempting to authenticate the server's certificate. The default is ~/.postgresql/root.crl.

So if that's not passed by HeidiSQL, this cannot cause the mentioned connection problem.

I am stuck - please post more ideas and probably deeper connection debugging results here.

**Comment by germu** [comment]
played around with the Nightly Build of 08 Oct 2019. Your current implemenation works well with SSL. The problem here is: On Windows PostgreSQL strips out path delimiters unless you escape them - refer [PostgreSQL connection require a valid client certificate](https://stackoverflow.com/questions/51793317/postgresql-connection-require-a-valid-client-certificate)
If I insert the cert & key with e.g. C:\\certs\\client.cer then the connetion by SSL gots established. Woold be good if you pickup the path and escape that within your code.

**Comment by ansgarbecker** [comment]
@germu please update to the latest build and retest - backslashes now get escaped with backslash. Or perhaps one of the other reporters here @Dionyzos73 or @madankumark ?

**Comment by germu** [comment]
_Regarding my old comment: I had inserted two slashes in my orgin comment and seen then that one was stiped away. So I edited the old comment again and added a thrid slash ..._

**Now it works well with one slash under heidisql64.r5713!** 
My connetion is done by SSH tunnel & SSL. All my system works with pre-authentication banners. They will be popped up as an error (most time) where I must click on OK. This should be an INFO and at least it would be great to e.g. make a switch to disable that pop up and show the output only in the console window on the button. Sometimes it is part there like the screenshot below shows:
![grafik](https://user-images.githubusercontent.com/56381542/66704104-8900b100-ed19-11e9-8264-f72c0fa5a4bb.png)

But most time it is shown as pop up and must be accepted by OK:
![grafik](https://user-images.githubusercontent.com/56381542/66704113-9453dc80-ed19-11e9-9e31-de4fa3939d10.png)

**Regarding PLINK** It would be good to add the **“-batch”** switch, as starting with version 0.7x a prompt appears. This could be disable by the switch.
![grafik](https://user-images.githubusercontent.com/56381542/66704289-bbf77480-ed1a-11e9-858a-aa607a567a20.png)

Finally I get this Warning Pop up which I have to accept:
![grafik](https://user-images.githubusercontent.com/56381542/66704131-b188ab00-ed19-11e9-9cc7-99ac4d7a585e.png)
 
That is not the truth, as my postgres could only connected by SSL. Where does that message comes from? Postgres himself don't show any error.

Thanks

**Comment by ansgarbecker** [comment]
`-batch` is a problem when the server wants to ask you for accepting a yet unaccepted host key. See 2854c74d134ce3a3d48468dee43987031412f7ba and #639 

That "SSL not used" is a bug, the message works correct in MySQL mode, in PostgreSQL it always shows if you activate SSL. I just pushed a change which now checks the result of `SHOW ssl` to avoid that dialog. Please update and recheck.

Regarding these banner messages, I pushed a second change which detects exactly such messages starting with "_Pre-authentication banner_ " now. I suppose it's right to still show them as a message dialog.

The one which could be missing now is the shorter message you posted ("Keyboard-interactive authentication prompt..."). Looks strange as there is no real message in it.

**Comment by germu** [comment]
Tested with heidisql64.r5716 = SSL warning away.
Also Pre-authenticate & prompt no longer pop's up - the pre-authenticate is now always part of the console window (3 Tests):
![grafik](https://user-images.githubusercontent.com/56381542/66732728-56f86780-ee5d-11e9-9407-6784390d3dbb.png)

**Regarding -batch:**
PuTTY/PLINK introduced with 0.71 this prompt only as can be seen from the release notes in the PIC:
![grafik](https://user-images.githubusercontent.com/56381542/66732826-af2f6980-ee5d-11e9-9537-539ca4cbf1cf.png)

Finally - pre-auth is now no longer pop up and prompt accept is not shown (autoaccepted by HeidiSQL?) - so no interaction is neccessary now, which is fine for me! => GREAT!

**Comment by ansgarbecker** [comment]
Thanks for your quick feedback and screenies!

I suppose this can be closed now.
