### ISSUE TITLE
'Same text background' color should highlight same data in same row, not only same column as selected cell

### ISSUE THREAD

**Issue by yphastos** [HeidiSQL/HeidiSQL#707]
## Steps to reproduce this issue

1. Step 1; make sure the "Same text background" option (under "grid formatting") is set to a noticeable color.
2. Step 2; have some results with several rows and columns and same data on other rows, AND also other columns
3. Step N; select a single cell which has same data in same column of other rows, but also same data on other columns of selected row
4. Then I get... 

## Current behavior

The cells from the other rows in the same column with the same data as currently selected get highlighted as expected, but the cells in other columns, but in the SAME row with the SAME data do not get highlighted as expected.

![image](https://user-images.githubusercontent.com/13773388/60826290-21afef80-a173-11e9-8a6b-ad6dfdbb05c9.png)

Here the cells with '2' in other rows and same column get highlighted, but the cells with '2' in the SAME row don't get highlighted, they remaing with the 'selected row' gray background color.

## Expected behavior

All the cells in the same ROW and COLUMN with the same data as the current selected cell should be highlighted. i.e. among the 'cross' formed by the current row and column

## Possible solution

Just guessing, maybe the option correctly detects same data, but when it attempts to paint them, the 'selected row' background gets a higher priority and overrides the "same text background" color. 

i.e. the 'same text background' color should have higher priority over the currently selected row, for cells with matching data of course

## Environment

* **HeidiSQL version:** 10.2.0.5599
  

* **Operating system:** MacOS 10.13.6, running heidi under Wine

**Comment by yphastos** [comment]
Additional comments.

It would be VERY useful on cases in which we need to compare data in several columns, where navigating the results with the keyboard would easily highlight matching data in other columns, instead of having to make custom queries like `if(a = b,'match','no match') as a_matches_b`

Highlighting the same data in the whole result table (not only selected row/column) would be useful sometimes, but i guess it would be more 'expensive' to process and would be visually messy, so it is not that important. or maybe as a toggleable option?

**Comment by ansgarbecker** [comment]
I agree it's useful and worth it to take the focused row into account. But doing that on the whole grid would break it somehow. So I'll go and apply it on the row first.

**Comment by yphastos** [comment]
Thanks! 

Although it would be nice to have it sooner than 10.4. but I'm happy you will eventually implement it.

**Comment by ansgarbecker** [comment]
Well, then let's try it for 10.3. I just wanted to limit the pressure on myself for the next release. These remaining high-dpi issues are such a pain in the ass.

**Comment by yphastos** [comment]
Wow thanks! I really appreciate it.

**Comment by ansgarbecker** [comment]
This is how that looks like in the next build:

![grafik](https://user-images.githubusercontent.com/7986591/67836046-d3d94180-faeb-11e9-864a-49d8b21c7036.png)

We should test that for some time, maybe there are reasons to highlight same cells in the whole grid. But for now I don't think so, especially when looking at this particular table.
