### ISSUE TITLE
Data grids: Highlight fields with same value as in focused field

### ISSUE THREAD

**Issue by ansgarbecker** [HeidiSQL/HeidiSQL#71]
## Expected behavior

Highlight unfocused fields which have the same value as the focused field. (perhaps with some background color). This helps analyzing data, when the user [can't see the forest for trees](https://www.urbandictionary.com/define.php?term=can%27t%20see%20the%20forest%20for%20the%20trees).

See images for examples.
![grid-highlight-same-values-2](https://user-images.githubusercontent.com/7986591/34559719-1bb79808-f143-11e7-9d15-530bf88a98ae.png)
![grid-highlight-same-values-1](https://user-images.githubusercontent.com/7986591/34559720-1bd0051e-f143-11e7-86d8-60a3c687907d.png)

**Comment by rgka** [comment]
Sounds useful. Would be nice to be able to turn it on/off somewhere in the settings.

**Comment by ansgarbecker** [comment]
Notepad++ for example also does that:

![grafik](https://user-images.githubusercontent.com/7986591/34819160-4f1de376-f6bd-11e7-8189-dcec35a6e75a.png)

**Comment by rgka** [comment]
Do you think about highlighting only within the selected column or all matches in the whole grid?

**Comment by ansgarbecker** [comment]
Only in the selected column. I found that I am often searching for the same values in one column - not everywhere. Highlighting in the whole grid would create too much noise in many cases.

**Comment by rgka** [comment]
Agreed.

**Comment by ansgarbecker** [comment]
Just worked on this, and also added a checkbox in Preferences > Grid formatting, where one can disable this feature.

**Comment by albertdick** [comment]
> Just worked on this, and also added a checkbox in Preferences > Grid formatting, where one can disable this feature.

Please also add an option to change the highlight color.
