### ISSUE TITLE
Close other/right tabs

### ISSUE THREAD

**Issue by kp2019** [HeidiSQL/HeidiSQL#710]
please add features like in Chrome (right click on tab):
* Close other tabs
* Close tabs to the right
very helpful when open many tabs

**Comment by ansgarbecker** [comment]
Any default keystrokes you recommend for these both actions?

**Comment by kp2019** [comment]
mouse right-click on a tab

**Comment by ansgarbecker** [comment]
I meant _keyboard_ shortcuts.

**Comment by WesleyM77** [comment]
How would this interact with issue #365? Also, would this bring the ability to reposition tabs?

**Comment by ansgarbecker** [comment]
As the title says, this issue is only for closing tabs at the right, and tabs other than the current one.

**Comment by kp2019** [comment]
I have no recommendations for hotkeys.
for issue #365:
Close other tabs - close all tabs except the elected, the elected becomes the main
Close tabs to the right - just closed the tabs after the current

**Comment by mbomb007** [comment]
> I meant _keyboard_ shortcuts.

Even Chrome doesn't have shortcuts for that. There is an extension that adds them. https://chrome.google.com/webstore/detail/keyboard-shortcuts-to-clo/dkoadhojigekhckndaehenfbhcgfeepl

* Alt-Shift-O: Close Other Tabs
* Alt-Shift-R: Close Tabs to the Right
* Alt-Shift-P: Pin Tab

**Comment by UncleJazzmus** [comment]
I'd just like to be able to close tabs. Any tab. All tabs.

**Comment by ansgarbecker** [comment]
Got it in for the next nightly build:
![grafik](https://user-images.githubusercontent.com/7986591/120882837-7025cd00-c5da-11eb-95c5-d044ca640204.png)
