### ISSUE TITLE
MySQL SSH Tunnel Issue - plink v0.71 incompatibility

### ISSUE THREAD

**Issue by vuther** [HeidiSQL/HeidiSQL#711]
## Steps to reproduce this issue

1. Configure HeidiSQL to use MySQL SSH tunnel
2. Use PuTTY v0.71
3. Receive error "Can't connect to MySQL server on '127.0.0.1' (10061)

## Current behavior

HeidiSQL doesn't work with PuTTY v0.71. I spent a good amount of time troubleshooting this issue because my company is moving towards an SSH solution and I had to figure out what the root issue was. Other previous versions of PuTTY work with HeidiSQL.

Also, this isn't directly related but setting plink.exe timeout makes the entire connection take that much time regardless if it connects before specified timeout.

## Expected behavior

It should connect :-)

## Possible solution

Not sure what the root issue here is. Seems like HeidiSQL isn't correctly communicating with plink because of a change in v0.71.

## Environment

* **HeidiSQL version:** 
10.2.0.5621
* **Database system and version:** 
5.7.22
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
Please post the plink command line from the log panel here, of course with anonymized credentials. For me, plink 0.71 works good. My command line looks like this one:

> C:\Software\plink.exe -ssh myuser@myhost -P 22 -i "C:\Users\becker\.ssh\mykey.ppk" -N -L 3307:127.0.0.1:3306

**Comment by vuther** [comment]
> Connecting to $server via Percona (SSH tunnel), username $db_user, using password: Yes ... 
> SSL parameters successfully set.
> Attempt to create plink.exe process, waiting 6s for response ... 
> C:\Program Files\PuTTY\plink.exe -ssh $ssh_user@$ssh_server -P 22 -i "D:\Users\Desktop\key.ppk" -N -L 3306:$database_server:3306
> PLink: Using username "$ssh_user"
> Can't connect to MySQL server on '127.0.0.1' (10061)
> Closing plink.exe process #12384 ...

**Comment by ansgarbecker** [comment]
That "Using username..." is just a new output in the new plink version, should not matter.

Did you notice your local SSH tunnel port is set to 3306? The one in front of $database_server. You should try 3307 in the "SSH tunne" tab, at least if you have a local MySQL/MariaDB server installed.

**Comment by vuther** [comment]
I've tried numerous ports. Heidi will increment the port by 1 if it's in-use anyway from what I've noticed.

**Comment by ansgarbecker** [comment]
Can you please open a command prompt and fire that plink command by hand, to see what happens? And afterwards try to connect with Heidi on 127.0.0.1 / 3306.

**Comment by vuther** [comment]
It works fine if done manually by command prompt.

**Comment by ansgarbecker** [comment]
And Heidi does not say "Can't connect to MySQL server on '127.0.0.1'" with that plink in a command prompt?

If so, please check via taskmgr if the plink.exe process runs when you try again with Heidi's built-in plink setup.

**Comment by vuther** [comment]
Whenever I ran plink via command prompt, it creates the tunnel. Here's the verbose log output:

> We claim version: SSH-2.0-PuTTY_Release_0.71
Remote version: SSH-2.0-SSHD-CORE-1.7.0
Using SSH protocol version 2
No GSSAPI security context available
Doing ECDH key exchange with curve nistp256 and hash SHA-256 (unaccelerated)
Host key fingerprint is:
ssh-rsa 2048 $hash
Initialised AES-256 SDCTR (AES-NI accelerated) outbound encryption
Initialised HMAC-SHA-256 (unaccelerated) outbound MAC algorithm
Initialised AES-256 SDCTR (AES-NI accelerated) inbound encryption
Initialised HMAC-SHA-256 (unaccelerated) inbound MAC algorithm
Reading key file "D:\Users\Desktop\key.ppk"
Using username "sdfsfsdf@server".
Offered public key
Offer of public key accepted
Authenticating with public key "imported-openssh-key"
Sent public key signature
Access granted
Local port 3306 forwarding to $db_server:3306

I can then connect with Heidi on 127.0.0.1 with no issue.

**Comment by vuther** [comment]
Any update on this, @ansgarbecker? Would like to be able to use latest PuTTY version.

**Comment by ansgarbecker** [comment]
No changes here yet.
But could you please verify this is still an issue with the latest build - 5621 is a bit old already.
Also, your plink output is different from mine - mine starts with a "Looking up host ..." line. That may be due to you using a key which I don't. Is that the original plink.exe from https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html ?

**Comment by ansgarbecker** [comment]
Ah and please activate "Debug messages" in Preferences > Logging before you try to connect. So we probably get some more details.

**Comment by vuther** [comment]
So.. after upgrading to to 10.2.0.5599, I no longer have connection issues. That's strange if it works when you didn't change anything specifically for it. I'll have others test and see if it works for them as well.

Thanks!

**Comment by ansgarbecker** [comment]
Ok, 5599 is the 10.2 release, but older than 5621 (the one you reported above), so there may be now other things not working for you.
Would be nice if you once again update, but to the latest build, through Help > Check for updates.

**Comment by vuther** [comment]
I'm now on 10.2.0.5678 and it still works.

**Comment by ansgarbecker** [comment]
Didn't expect that, but.. cool :)
So I guess I can close this.
Thanks for your feedback!

**Comment by XianwuLin** [comment]
There has some useful information: https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/vuln-auth-prompt-spoofing.html

plink 0.71 add a new security policy, I have to use add -batch option to bypass this problem.
