### ISSUE TITLE
Inconsistent/counterintuitive count of rows and columns in results between tab title and selected cell in toolbar

### ISSUE THREAD

**Issue by yphastos** [HeidiSQL/HeidiSQL#712]
## Steps to reproduce this issue

1. Have a query which results in a different amount of rows vs amount of columns
2. The result tab shows the number of the query, and the count of items, in the form:

`Result #<n> (<columns> x<rows>)`

![imagen](https://user-images.githubusercontent.com/13773388/61091817-386f7400-a409-11e9-9dcd-0aabeb960331.png)

3. In the bottom bar (don't know how it is called), when you click on any cell, it shows the 'coordinates', but the format is inverted, it shows it as:

`<row> : <column>`

![imagen](https://user-images.githubusercontent.com/13773388/61091838-4f15cb00-a409-11e9-9e6e-fd042af7a953.png)

## Current behavior

The row/column count is inconsistent in order, because one show column then row, and the other the opposite. Plus, it is not intuitive to deduce which number is row or column

## Expected behavior

Both cases should show at least be in the same order. Or better, to indicate what each number means.

## Possible solution

Change the order of either one to match the other. This has the disadvantage of still not being intuitive to recognize each.

Additionally, just add a label indicating which case each number means, e.g.

In tab: 
`Result # 1 (3 columns x 79 rows)` or with just a letter, e.g.: `Result #<n> (3c x 79r)`

and in status bar:
`row 79 : col 3`, or with a letter: `r79 : c3`

This way with only a glimpse it would be clear, both the global count and the current selection coordinates.

## Environment

* **HeidiSQL version:** 10.2.0.5599

**Comment by ansgarbecker** [comment]
What about using some Unicode arrow characters for that purpose:

![grafik](https://user-images.githubusercontent.com/7986591/65068068-2faa9980-d988-11e9-9cd6-6ed004b2db22.png)

Whether that does not show a broken character will depend on the selected font, and probably Wine has problems with it, not sure. But at least Tahoma and Segoe on Windows 10 seem to support these arrows.

Check out the next build to see it yourself.

**Comment by ansgarbecker** [comment]
By the way, these are
* &#8596; `&#8596;` / `&harr;` and
* &#8597; `&#8597;` / `&updownarrow;`

Found them on the greatest page for Unicode characters on the web from NDP Software and Andrew J. Peterson: http://www.amp-what.com/unicode/search/arrow

**Comment by yphastos** [comment]
Perfect!
They DO work in wine, in the results tab:

![image](https://user-images.githubusercontent.com/13773388/65070425-39b1a580-d952-11e9-847b-479b8ba24f14.png)

But wasn't it supposed to also show them on the status bar? Because in there it still shows `<column> : <row>` but without the arrow characters:

![image](https://user-images.githubusercontent.com/13773388/65070559-75e50600-d952-11e9-9f0a-45697773c8f3.png)

Could it be maybe because the status bar uses a different font? (I have no idea)

Thanks!

**Comment by ansgarbecker** [comment]
Hm, it seems the status bar shows a space instead of the arrow. Comparing your new screenshot with your old one reveals that - look at the increased space between "3" and ":"
![grafik](https://user-images.githubusercontent.com/7986591/65117669-85b02900-d9ea-11e9-80e8-068e46514027.png)
![grafik](https://user-images.githubusercontent.com/7986591/65117682-88ab1980-d9ea-11e9-8a0e-44ae2fc55bdb.png)

Could be a Wine issue then, although the font is the same.

Could you please go to Tools > Preferences > General, and select a different GUI font, to see if that makes a difference?

I can also try and use hex codes instead of real Unicode characters in the code, to prevent read errors.

**Comment by leeoniya** [comment]
i too experience this confusion (most often with small result sets where the numbers are close), but i'm not a huge fan of the proposed solution. the arrows are tiny and the vertical one resembles a "1" which is even worse. in addition, i very rarely care about the column count in a grid or query result and *always* care about the row count. IMO, rows should always come first and if you feel that columns are important enough to always show, then maybe `75,509 rows (11 cols)` or  `75,509 x 11 cols`. additionally, if there was an option to disable column counts, i would have it permanently enabled.

my $0.02

**Comment by ansgarbecker** [comment]
Well ok, it was worth an attempt, because there is not much space for more text. But I see they make new problems.

So, Notepad++ displays this in the status bar, taking quite much horizontal space:
![grafik](https://user-images.githubusercontent.com/7986591/65142923-0a636d00-da14-11e9-863e-3ecd7338b875.png)
PHPStorm does it very compact, which may also be not intuitive:
![grafik](https://user-images.githubusercontent.com/7986591/65142899-00416e80-da14-11e9-90cf-7013ea66d429.png)
MS Notepad does it similar to Notepad++, but with less spaces:
![grafik](https://user-images.githubusercontent.com/7986591/65142874-f586d980-da13-11e9-8bac-eeac3e48b1c0.png)

Note that we're talking about two different places. The above screens are all from the status bar. Heidi also has the result tabs, and I start to think they need different approaches.

**Comment by yphastos** [comment]
Update, this time I am trying from a windows machine, and here it does show them correctly:

![image](https://user-images.githubusercontent.com/13773388/65159623-01fe3880-d9fa-11e9-8699-fc11274445be.png)

So I guess it is indeed a Wine / fonts related problem.
Regarding changing the GUI font, I will try it tomorrow, when I get back to my Mac. 

However, as leeoniya mentions, it may be better to just use standard characters instead of unicode. This way you'd have the most compatibility.

As I initially suggested, a better choice would be to just use 'r' and 'c' for rows and columns:
`r79 : c3` or `79r : 3c`.  I also prefer the row count first. And this way you can save the spaces between the counters and the letters.

IMO it is fairly understandable. Plus you could add a tooltip to clarify, e.g. show `79 rows : 3 columns` when the user hovers the text.

---

Somehow unrelated. When I tried to install with the HeidiSQL_10.2.0.5693_Setup.exe file (at Windows), my Avast Antivirus detected it as a possible threat. I managed to install it by adding the installer to a white list, but then, running the program (not the installer), it again reported it as a possible threat. I overcame that by temporarily disabling the Avast shields.

This didn't happen before, but the Avast program/definitions have recently updated so I am fairly sure it is a false positive.

**Comment by leeoniya** [comment]
`r79 : c3` seems too cursor/positional to me. like row 79 col 3. `79r : 3c` is better but still has the same problem. `:` usually represents position the `goto` command in text editors is frequently asked for in `[line] : [col]` form.

maybe `107r x 13c` in results tabs and `r107 : c13` in status bar.

either way, i think showing te rows before columns is uncontroversial.

**Comment by yphastos** [comment]
> maybe `107r x 13c` in results tabs and `r107 : c13` in status bar.

Sounds good to me. In the tab it shows as the fixed count of resulted rows and columns, and in the status bar it means the CURRENT selected cell (or the total as well if no cell is selected).

Funny, until now, I haven't noticed that if instead of the results you click/move the prompt in the query editor, the status bar also shows the current cursor position (coordinates).

---

And about Avast antivirus, I just got a notification that the installer has been scanned by them and found to be harmless. I guess their database didn't have such installer 'validated' yet

**Comment by ansgarbecker** [comment]
> > maybe `107r x 13c` in results tabs and `r107 : c13` in status bar.
> 
> Sounds good to me.

That's it now. See the next build.
