### ISSUE TITLE
Panel Size Ratios are not maintained when dragging window

### ISSUE THREAD

**Issue by aSystemOverload** [HeidiSQL/HeidiSQL#713]
## Steps to reproduce this issue

1. Step 1;  Move window from one monitor to another with different resolutions.
2. Step 2; 
3. Step N;
4. Then I get...

## Current behavior

Once Window is moved, the query/results panels reset their size ratio.

## Expected behavior

All Panels should maintain their size ratio when windows are moved.

## Possible solution

When window is dragged, track size ratios, so that when it is dropped, they can be re-applied.

## Environment

I'm specifically using Win 10 Enterprise

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
Can you please attach two screenshots which explain visually what you mean.

**Comment by ansgarbecker** [comment]
c31cae206042ae00b97e41f43baf7421693d2e46 now removes all tweaks for high DPI monitors. I'm giving up here, this does all not work good enough, even different computers and Windows versions behave differently. It's a mess. So, now HeidiSQL is zoomed by Windows again, like it was in earlier v9.5. This does at least display all controls and fonts in the right dimensions.
