### ISSUE TITLE
MSSQL TCP/IP: Support other ports than 1433

### ISSUE THREAD

**Issue by jostrn** [HeidiSQL/HeidiSQL#714]
## Current behavior

If connection type Microsoft SQL Server (TCP/IP) is selected, HeidiSQL sets the port input field to 1433 and disables it, so no other port can be configured than 1433.

## Expected behavior

Since it is possible that a MSSQL instance uses a different port than standard port 1433, HeidiSQL should be able to connect to other ports than 1433. Thank you very much.

## Possible solution

Enable the port input field and pass its value to DBNETLIB.

* **HeidiSQL version:** 
10.2.0.5599 (64 Bit)

**Comment by ansgarbecker** [comment]
Here's quite an old story about why the port is disabled then: https://sourceforge.net/p/heidisql/tickets/2767/
It basically says the port is enabled for TCP/IP, but disabled in case the hostname contains a backslash, which means it is a so called named instance.

Is it still a valid approach to disable the port input when the host is a named instance of SQL Server? If yes, HeidiSQL still has the issue that this does not update when you change the network type from something to "_Microsoft SQL Server (TCP/IP)_". But probably you say one cannot use named instances with TCP/IP?

**Comment by jostrn** [comment]
> Is it still a valid approach to disable the port input when the host is a named instance of SQL Server?

We have a MSSQL named instance running on port 1433 locally but this port is exposed to the internet on a different port using port forwarding. Microsoft states that this ["is not considered a robust security measure"](https://docs.microsoft.com/de-de/sql/database-engine/configure-windows/configure-a-server-to-listen-on-a-specific-tcp-port?view=sql-server-2017) but it adds a little bit additional security.

Thank you for adding the functionality as milestone for the next sub version.

**Comment by ansgarbecker** [comment]
Ok, so you still have a port for a named instance. The old ticket reads as if a named instance over TCP/IP should not be connected per port at all. But in that case I will just revert 1c76c2ecc0ed7d87cda822228802bedf48a143fe.
