### ISSUE TITLE
not found http.dll

### ISSUE THREAD

**Issue by matheuw** [HeidiSQL/HeidiSQL#715]
## Steps to reproduce this issue

I'll connect via TCP / IP put all the data to log in, then an error message appears ("Plugin http could not be loaded")then it was looks in the plugins folder is that file is not there
![Capturar](https://user-images.githubusercontent.com/16859104/61244733-467f0680-a721-11e9-8e71-e20f25085b9c.PNG)

## Environment

* **HeidiSQL version:** 10.2.0.5599(32 bits)
  
* **Database system and version:** Mysql 5.6
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
Is the user you are trying to connect with maybe bound to a specific login method, on the server? You probably need to ask the administrator. Some plugins are loaded automatically, when the user account requires them.

**Comment by dankoman30** [comment]
if anyone else runs into this issue in the future, it can be resolved by removing the "http://" or "https://" prefix from the hostname.

**Comment by AhmedElTabarani** [comment]
> if anyone else runs into this issue in the future, it can be resolved by removing the "http://" or "https://" prefix from the hostname.

Also, Make sure to remove any trailing slashes (/) from the end of the path if they are present
