### ISSUE TITLE
MySQL connection failure - Internal error 126

### ISSUE THREAD

**Issue by vbojan** [HeidiSQL/HeidiSQL#716]
Starting with HeidiSQL 10.2.0.5611 all the way to the current 10.2.0.5629 I cannot connect to any MySQL server using TCP/IP, named pipe or SSH tunnel connection.
I also tried portable versions and got the same error.

## Steps to reproduce this issue
1. Select a session that uses MariaDB or MySQL
2. Click the Open button
3. HeidiSQL instantly shows the following error:

![image](https://user-images.githubusercontent.com/2696314/61309933-d754f100-a7b8-11e9-9ea3-ce18bbc4fa97.png)

The last version that doesn't show this error on Windows 7 Pro SP1 is 10.2.0.5610.

**Comment by ansgarbecker** [comment]
This message was introduced for #677 , since I introduced a library selector. By default, libmariadb.dll is selected. If HeidiSQL fails, then you are missing that file probably?

**Comment by ansgarbecker** [comment]
![grafik](https://user-images.githubusercontent.com/7986591/61316799-fe83e080-a801-11e9-9a8c-6b545e72d72c.png)

**Comment by vbojan** [comment]
Thank you Ansgar for your quick reply.
I have that file and it's the same version as in the portable package: 3.0.0.7
Actually all files are identical as in "HeidiSQL_10.2_64_Portable.zip".
I assume it's looking for DLLs in the same folder.
If I drop in nightly build of heidisql.exe 10.2.0.5610 or older in the same folder everything works fine with the same DLLs. Not sure which DLL it uses for MySQL. I gues libmysql.dll?
I didn't try nightly install version. Does it have the same DLL files?

**Comment by vbojan** [comment]
I figured what the issue is.
I noticed Library combobox being empty. Then I looked into portable ZIP package again and noticed all files being lowercase whereas some of DLLs in my installation were mix of upper/lower case.
It was probably like that since I installed HeidiSQL and replacing files in W7 doesn't change the case if the file has the same name, so it's been like this for a long time.
After flipping all of them to lowercase and restarting HeidiSQL the combobox got populated with libmariadb.dll and libmysql.dll so everything works fine now.
Thank you for your help!

I guess you might want to make it case insensitive when looking for DLLs just in case someone has the same issue.

**Comment by ansgarbecker** [comment]
Indeed, the search for libmysql/libmariadb was case sensitive. They may have some postfix, like "libmysql5.6.dll", or whatever, but I did not think of different cases. Just made it case insensitive, so others should not have the same. Thanks for your finding and feedback!
