### ISSUE TITLE
Shortcut support is not perfect, Bug? Or it is not provided.

### ISSUE THREAD

**Issue by id0612** [HeidiSQL/HeidiSQL#719]
## Steps to reproduce this issue

1. Step 1;
Close unsaved query labels.
2. Step 2;
When prompted to save, press Y, N, or C to indicate Yes, No, or Cancel。

## Current behavior

When the buttons are displayed in English, those buttons trigger the corresponding function. For example, use the software language: en or zh_CN (the current version of the deleted language package, because it is incomplete, so these buttons are also shown as English), but this is not valid when the language we are using makes the text displayed on these buttons not English. For example: zh, ja

## Expected behavior

It is recommended that this feature be well supported and not affected by language. It will be more convenient to use.

## Possible solution

With the support of the operating system, like the operating system menu, dialog button support common single-letter shortcut keys.

**Comment by ansgarbecker** [comment]
Next build uses strings from user32.dll in your Windows folder. These are translated even when HeidiSQL cannot provide a translation. Also, some of them have hotkeys.

I had to guess a little what you mean, but I'm nearly sure you were talking about exactly these localized buttons and shortcuts. I found this is a good idea, as this even works without a manual translation.

**Comment by id0612** [comment]
Great, you made it happen.
