### ISSUE TITLE
Column default value shows wrong value

### ISSUE THREAD

**Issue by KN4CK3R** [HeidiSQL/HeidiSQL#721]
## Steps to reproduce this issue

1. Open table view
2. Have a look at the default value column

## Current behavior

The default value is parsed/displayed incorrect. The string value `TX` is displayed as `('TX')` for example. This leads to errors while generating INSERT statements too.

![table2](https://user-images.githubusercontent.com/1666336/61523833-6a8a6280-aa15-11e9-8d8e-9cae11008247.JPG)
![insert2](https://user-images.githubusercontent.com/1666336/61523846-6e1de980-aa15-11e9-8968-c435fa98a8a1.JPG)

## Expected behavior

The default value should just show `TX`.

![table1](https://user-images.githubusercontent.com/1666336/61523868-77a75180-aa15-11e9-9608-21048f838f11.JPG)
![insert1](https://user-images.githubusercontent.com/1666336/61523871-78d87e80-aa15-11e9-869e-40191d4ad3f2.JPG)
(Screenshots are from HeidiSQL 10.1.0.5464)

## Environment

* **HeidiSQL version:** 
10.2.0.5637
* **Database system and version:** 
MS SQL
* **Operating system:** 
Windows 10

**Comment by KN4CK3R** [comment]
Looking at the code I think commit 9fc7150 for issue #74 is the reason for this behaviour.

**Comment by ansgarbecker** [comment]
Problem is here. default values can also contain expressions, like `(getdate())`, or `(sysdatetimeoffset())`. If I extract the contents between `(` and `)`, then I still need to differentiate these from ordinary strings or numbers. like `((0))` or `('TX')`.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.
