### ISSUE TITLE
Mysql 5.7 SSL Problem

### ISSUE THREAD

**Issue by assachs** [HeidiSQL/HeidiSQL#722]
Hello,
i have a problem connecting with ssl to a mysql 5.7 server.

- Mysql 5.7.27 (and before) on debian 9
- Heidisql 10.2.0.5646 (and before, not with 10.1) on Windows 10
- SSL-CA-Certificate specified

(SSL private key, SSL Certificate and SSL Verschlüsselung empty)

With libmysql: SSL connection error: ASN: bad other signature confirmation
With libmariadb.dll: Unknown SSL error (0x80090308)

Without a CA-Cert it is working.

Thanks 
Andi

**Comment by ansgarbecker** [comment]
Heidi is shipped with a libmysql.dll from MySQL 5.6. Could you please try to put a newer libmysql into your HeidiSQL folder (with a different filename, to avoid confusion). Then start HeidiSQL and select that lib to test if that works? Note you need to use a 64bit dll if you use HeidiSQL 64 bit, and vice versa for 32bit.

**Comment by assachs** [comment]
Hello Ansgar, i can confirm that it is working with libmysql 6.1.11.0. Thanks for your help.

**Comment by ansgarbecker** [comment]
This is great news, as this can solve some other SSL related issues as well. I just have to provide that newer libmysql in the installer to get these fixed.

**Comment by ansgarbecker** [comment]
I added libmysql v6.1.11 to the installer, and also an additional hint for the user in the such SSL error messages, an advice to select a different library.
