### ISSUE TITLE
Pressing "backspace" in a data cell change current tab to "host"

### ISSUE THREAD

**Issue by jdeniau** [HeidiSQL/HeidiSQL#723]
## Steps to reproduce this issue

1. Go into "data" tab on a table
2. Go into edit mode (F2)
3. Press backspace

## Current behavior

When pressing backspace, the current tab is changed from "data" to "host"

See the following video to watch the current behavior:

https://vimeo.com/349625201

## Expected behavior

Stay on "data" tab and remove the character before the cursor :)

## Environment

* **HeidiSQL version:** 
10.2.0.5645
  
* **Operating system:** 
Linux Fedora 30 with wine 4.12.1

**Comment by WesleyM77** [comment]
Doesn't seem to be an issue on windows 10 with the newest version of Heidi. Also, that link is broken, try this one: https://vimeo.com/349625201

**Comment by gmtrejo** [comment]
I have the same issue

**Comment by dcelasun** [comment]
Same issue with wine-staging 4.12.1 with latest HeidiSQL.

**Comment by AlecVoid** [comment]
Same issue with wine-4.10 on Linux Mint 18.1 and the latest HeidiSQL (10.2.0.5599)

**Comment by hrvoj3e** [comment]
Same issue - really annoying

**Comment by V13Axel** [comment]
Same issue here, HeidiSQL 10.2.0.5599 and wine-4.13 (staging).

**Comment by cpazaras** [comment]
+1

Must be something to do with a change in Wine.

As a temporary workaround - and unless there are other factors in your system that render this a bad idea - try downgrading Wine to version 4.1-1. Fixed the issue for me on Linux Manjaro.

**Comment by liuanxin** [comment]
same issue

Debian bullseye/sid
wine-5.0-rc1
HeidiSQL 10.3.0.5771

**Comment by ansgarbecker** [comment]
Hm, if you say that happens with v10.2 also, this should not be caused by changes #144 . 

Could someone check the Wine tracker for tickets related to backspace?

**Comment by liuanxin** [comment]
No keyboard settings found in wine
![Peek 2020-01-03 10-44](https://user-images.githubusercontent.com/2647495/71704624-5648ef00-2e16-11ea-9ff9-5a47348344f0.gif)


In addition, it is strange that it is only available when editing columns, and there is no problem using backspace elsewhere.
![Peek 2020-01-03 10-49](https://user-images.githubusercontent.com/2647495/71704746-28b07580-2e17-11ea-8878-8c21c21ba016.gif)

**Comment by piegus** [comment]
same issue
```
 wine --version
wine-5.0
 uname -a
5.3.0-28-generic #30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by danbadjar** [comment]
+1
Same here

Archlinux
wine-5.2
heidisql32.r5901.exe

**Comment by V13Axel** [comment]
Honestly with this being so widespread I'm surprisd there hasnt been any dev attention on this issue.

I stopped using HeidiSQL because of this and have since moved on to Jetbrains Datagrip.

**Comment by ansgarbecker** [comment]
Believe me I already paid attention here, but I'm clueless how to solve that. Wine 4.1 does not have the issue, according to a parallel [forum discussion](https://www.heidisql.com/forum.php?t=34351)

Could someone please testwise remove the shortcut for _Go to > Tab 1_ ?
![grafik](https://user-images.githubusercontent.com/7986591/75607476-e4301600-5af7-11ea-972d-e6e1d409abd9.png)
You can edit or remove it in Tools > Preferences > Shortcuts:
![grafik](https://user-images.githubusercontent.com/7986591/75607502-22c5d080-5af8-11ea-8549-ae6d1ffd9d8c.png)

**Comment by jdeniau** [comment]
Same issue without the shortcut.
if I change it to something else, then the bug is still the same.
If I remove the shortcut, same bug.
If I try to "backspace" when I am in the input, then... I am moved into the first tab (general) ! (and the backspace shortcut is functionnal)

**Comment by liuanxin** [comment]
@ansgarbecker I don't understand what the hotkey `Strg` is.

I tried to change the shortcut key to `none`, but it didn't take effect.It has been reflected in the figure above. Changing it to `ctrl + shift + alt + 1`, also had the same problem.

![2020-03-02](https://user-images.githubusercontent.com/2647495/75642041-1d41c500-5c75-11ea-8b61-7579126e9865.gif)

**Comment by pminspire** [comment]
Same issue here. Extremely annoying :(
HeidiSQL 11.0.0.5919
Wine: 5.0
Ubuntu 18.04

**Comment by ansgarbecker** [comment]
@liuanxin <kbd>Strg</kbd> is <kbd>Ctrl</kbd> on German keyboards.

**Comment by ansgarbecker** [comment]
I just spent 2 hours of debugging with a HypeV Ubuntu box and Wine 5.0 and v5.5. Compiled various modifications, where some hotkey handler in HeidiSQL could probably interfere with the typed backspace. Nothing helped here.
So I searched for known similar issues in the Wine bugtracker, and found [this one](https://bugs.winehq.org/show_bug.cgi?id=47508#c7), which also has a backspace problem - with a different effect.

**Comment by ansgarbecker** [comment]
Ah, does anyone know the exact Wine version in which this issue started? I just heard 4.0 worked and 4.12.1 not. With that information, we could probably help the Wine developers to track the issue down to some exact modification.

**Comment by gmtrejo** [comment]
For me worked with wine 4.1

**Comment by PaulBGD** [comment]
So I went ahead and compiled a few versions, and found out that Wine 4.9 introduces the issue that causes this. I'm going to try and figure out what change caused it.

**Comment by PaulBGD** [comment]
Ok according to git bisect, the offending commit is this one: https://github.com/wine-mirror/wine/commit/4a6e69ad3aff6fff2817b05ee2cdcc7e94f960a5

I'm not really sure why that causes the backspace issue, but it's definitely the offending commit.

**Comment by ansgarbecker** [comment]
This is great news - I just posted that into the [Wine tracker issue](https://bugs.winehq.org/show_bug.cgi?id=47508#c8) I mentioned before. Hoping to get some solution here.

**Comment by yapsr** [comment]
I can confirm the backspace issue is resolved by using Wine 4.8.

Until the Wine developers have fixed the issue, I used these commands to install Wine 4.8 in Debian Buster:

`wget https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-amd64/wine-staging_4.8~buster_amd64.deb`


`sudo apt-get install wine-staging-i386=4.8~buster wine-staging-amd64=4.8~buster`

`sudo dpkg -i ./wine-staging_4.8~buster_amd64.deb`

Wine 4.8 will be installed in /opt/wine-staging/

**Comment by ameenross** [comment]
> I'm not really sure why that causes the backspace issue, but it's definitely the offending commit.

Could it be that the backspace triggers a rerender of the table, calling sorts and other stuff? That in consequence triggering some other bug?

**Comment by ameenross** [comment]
For me, CTRL+BkSp has the same behavior, and the odd thing is that ALT+BkSp has the "Delete Last  Word" behavior.

There are 2 other oddities: I have 2 entries for "Delete last character", and I can't change the shortcut key for them:

`/* Could not apply SynEdit keystroke shortcut "Shift+Ctrl+Alt+Z" (or secondary: "") to ecDeleteLastChar. Shortcut already exists. Please go to Tools > Preferences > Shortcuts to change this settings. */`

![Screenshot from 2020-06-08 16-20-27](https://user-images.githubusercontent.com/859737/84041313-fb5a8b80-a9a3-11ea-9f85-79a9fee65fc1.png)

**Comment by mspindelhirn** [comment]
In the bug thread mentioned by @ansgarbecker a wine dev has confirmed its a known issue on there end and they are working on a solution.

**Comment by gcarreno** [comment]
Hey there,

Adding my 2c and saying that it's still present in Ubuntu 20.10 with wine 5.0.

But from what @mspindelhirn mentions, looks like the ball is on wine's court now.

Cheer,
Gus

**Comment by mkukushkin35** [comment]
Tried wine 6.0 on UBUNTU 20.04. Problem still exists

**Comment by fnkr** [comment]
It works for me since Fedora 33 (Wine 6.0).

@mkukushkin35 Are you sure you're using Wine 6.0? Because Ubuntu 20.04 ships Wine 5.0: https://packages.ubuntu.com/focal/wine

**Comment by mkukushkin35** [comment]
I instaled wine 6.0 `(https://computingforgeeks.com/how-to-install-wine-on-ubuntu-linux/)
`wine --version
wine-6.0
`

**Comment by cpazaras** [comment]
Problem still persists for me as well (Linux Manjaro, Wine version 6.0, Gnome version 3.38.3, HeidiSQL version 11.0.0.5919)

@fnkr Would you give us more details about the system where it works, i.e. which desktop environment you are using, which HeidiSQL version etc?

**Comment by fnkr** [comment]
Fedora 33, Wine 6.0 / 6.1, i3 4.19 on X.org / GNOME 3.38.3 on Wayland, HeidiSQL 11.2.0.6213 64-Bit. Clean Wine profile - new and w/o any modifications. Using Firejail:
```sh
firejail --profile=/etc/firejail/wine.profile --private-dev --private-tmp --private=. wine heidisql.exe
```
I tried multiple fields that were problematic, including data cells, table search, and table column editor. Backspace, Ctrl+Backspace, Ctrl+A, Shift+Left/Right, Ctrl+Shift+Left/Right ... everything works fine now.

**Comment by ameenross** [comment]
Can confirm it's fixed in FC33 with Wine 6. I'm using a pre-existing wine prefix.

**Comment by dcelasun** [comment]
Likewise on Arch Linux with wine staging 6.1 and existing prefix, works perfectly.

**Comment by yapsr** [comment]
Success on Debian 10 with wine-staging 6.1~buster-1

Failure on Debian 10 with wine-stable 6.0.0~buster-1

**Comment by ameenross** [comment]
It looks to me like this must be the commit that fixed it:
https://github.com/wine-mirror/wine/commit/cd8eaef47e00aacecbf8c6d3a61c971724cbebf4

**Comment by mkukushkin35** [comment]
Tried wine 6.1 on UBUNTU 20.04. Problem still exists (https://tipsonunix.medium.com/install-wine-6-1-in-ubuntu-20-04-linux-mint-72893cbe5b2c)
maybe I'm doing something wrong?

**Comment by cpazaras** [comment]
Success on Manjaro with wine-staging 6.1.

Failure on Manjaro with wine 6.1 (not staging).

Default settings in both cases, tried HeidiSQL versions 10.2.0.5599 and 11.1.0.6116, same behavior in both.

**Comment by mkukushkin35** [comment]
with wine-staging 6.1 all work correctly. 
thanks

**Comment by jdeniau** [comment]
I do confirm that this issue is fixed in wine-6.1 (staging) too (Fedora 33).
Closing this.

Thanks @ansgarbecker for your implication :+1:

**Comment by piegus** [comment]
The issue is resolved on **Ubuntu 20.04 and wine-staging 6.1.
**

```
$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

$ wine --version
wine-6.1 (Staging)
```

**Comment by pm-inspire-dev** [comment]
This bug is back in Wine 6.4

**Comment by jebeaudet** [comment]
For anyone looking for a workaround, install playonlinux, install a specific wine version (I used 3.0.4) and install heidi through playonlinux by specifying a wine version, works like a charm

![image](https://user-images.githubusercontent.com/3722096/125322852-3009e680-e30c-11eb-92a4-612d09fddcd0.png)

**Comment by kakenbok** [comment]
wine 7.4, 7.5, 7.6 (today released) this still happens

**Comment by andrasbari** [comment]
> So I went ahead and compiled a few versions, and found out that Wine 4.9 introduces the issue that causes this. I'm going to try and figure out what change caused it.
> 
> For anyone who just wants it to work, Wine 4.8 seems to work great.

With PlayOnLinux and Wine 4.8 it works great! Above this Wine version the backspace bug appears again.

**Comment by piegus** [comment]
I just installed wine version 7.7 staging and backspace problem seems fixed

```
$ wine --version
wine-7.7 (Staging)
```

**Comment by goffyara** [comment]
@piegus, thx for notice.
It's working! Has not passed three years...) But the habit of not using backspace in Heidi remains

```
wine --version
wine-7.6 (Staging)
```

**Comment by TakeruDavis** [comment]
Neither recently mentioned 7.7 nor 7.6 were available in staging version. But 7.11 version, _not staging_, worked for me

**Comment by JackThird** [comment]
Ubuntu 22.04.1 LTS
kernel 5.15.0-52-generic
wine 7.0.0
HeidiSQL 12.1.0

Issue persist

**Comment by tmichelbrink** [comment]
I am currently using `wine-7.21 (Staging)`, and the backspace issue is gone (WOOT), but I am now seeing that when I hit a period /dot in the query window it no longer does an auto-lookup for table names.  `SELECT * from my_table.`, that should produce a popup, but I get nothing.

I am assuming it has to do with the key mapping that has now 'fixed' the backspace issue, but now we get this.

Anyone else experiencing it?

**Comment by daemonk12** [comment]
Hi, I just tested with wine-7.22 with ubuntu 22.10 and the issue is gone and I am not getting the . (period) in query tab issue.
