### ISSUE TITLE
Focus input box when opening a new tab

### ISSUE THREAD

**Issue by nummacway** [HeidiSQL/HeidiSQL#724]
## Steps to reproduce this issue

1. Click somewhere in the tree view;
2. Click the new tab button;

## Current behavior

Tree view still has the focus

## Expected behavior

Focus input box

## Environment

* **HeidiSQL version:** 
10.2.0.5599

**Comment by ansgarbecker** [comment]
I just obviously fixed that in c29e78c8afc3ed1e6c1f054e31bbb58672e72481, which was actually intended to fix #725 .
