### ISSUE TITLE
The software crashed while entering a field remark

### ISSUE THREAD

**Issue by chainray01** [HeidiSQL/HeidiSQL#726]
## Steps to reproduce this issue

1. Step 1 please see below gif;
2. Step 2;
3. Step N;
4. Then I get...

## Current behavior

please see below gif
[http://chuantu.xyz/t6/702/1564567913x1033347913.gif](http://chuantu.xyz/t6/702/1564567913x1033347913.gif)

## Environment

* **HeidiSQL version:** 
10.2.0.5668
* **Database system and version:** 
  mysql 5.7.25 log community server
* **Operating system:** 
  win7

**Comment by ansgarbecker** [comment]
Probably disable that auto-suggest window and try if that helps?

**Comment by chainray01** [comment]
> Probably disable that auto-suggest window and try if that helps?

yes , may be it's case by the chinese input software i used , other input software works well 。HeidiSQL not crashed again
