### ISSUE TITLE
Grid editor does not show right value, resulting in corrupt data when editing

### ISSUE THREAD

**Issue by rvanlaak** [HeidiSQL/HeidiSQL#727]
## Steps to reproduce this issue

When working with PHP serialized data, the grid editor is not able to show the correct value. While the read state shows a longer value:

![image](https://user-images.githubusercontent.com/2707563/62281637-67986480-b44e-11e9-9f5c-8e83f9314eb8.png)

When editing, only the part until an unsupported utf8mb4 character is shown. The rest of the data is gone.

![image](https://user-images.githubusercontent.com/2707563/62281671-797a0780-b44e-11e9-88d5-edcf5e49d52f.png)

## Current behavior

Editing will result in a corrupt value. Maybe the grid editor solely supports ANSI?

## Expected behavior

The shown value should be in the right charset, which probably also will allow saving the right value.

## Possible solution

* Query the fresh value when opening the text editor popup.
* Detect charset of grid editor based on table collation
* Having a HeidiSQL preference for the charset (ANSI / UTF8) of the data editors

## Environment

* **HeidiSQL version:** HeidiSQL 10.2.0.5668
  
* **Database system and version:** Percona 8.0.15
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
These grids support Unicode characters since several years now. I'm just not 100% sure whether there is a mismatch between MySQL's utf8mb4 charset and Delphi's Unicode charset.

Could you please post the corrupted value in hex format here:
```
SELECT HEX(payoutDetails) FROM ... WHERE ...
```
You should probably remove sensitive details from the result before posting.

**Comment by rvanlaak** [comment]
Thank you for your quick reply! 

A combination of substr / left did allow us to pass you a hex value without sensitive details. 

> LEFT(SUBSTR(field_with_error, 30), 100)

The problem lies in the red underlined characters.

![image](https://user-images.githubusercontent.com/2707563/62287674-d2e83380-b45a-11e9-8bff-ddbab27d5d5c.png)

HEX

```
6E766F69636544657461696C735C5061796F757444657461696C735C4942414E44657461696C73223A333A7B733A31363A22002A006D696E696D756D5061796F7574223B4F3A31313A224D6F6E65795C4D6F6E6579223A323A7B733A31393A22004D6F6E
```

**Comment by ansgarbecker** [comment]
Can confirm that now. We have a NULL character at the critical place, so this is not a character set issue, but rather some issue with null-terminated strings in Delphi. And their conversion between pointers and non-pointers. You can see the escaped NULL char when you export your data with HeidiSQL's SQL export dialog:
```
INSERT INTO `issue727` (`id`, `paymentDetails`) VALUES
	(1, 'nvoiceDetails\\PayoutDetails\\IBANDetails":3:{s:16:"\0*\0minimumPayout";O:11:"Money\\Money":2:{s:19:"\0Mon');
```
The [PHP documentation](https://www.php.net/manual/en/function.serialize.php) says that results of `serialize` may have null characters:
> Object's private members have the class name prepended to the member name; protected members have a '*' prepended to the member name. These prepended values have null bytes on either side.

So one recommendation is you should use some binary data type for storing PHP-serialized stuff. I'm not sure if I will find a workaround for getting text editing in HeidiSQL with null characters.

**Comment by ansgarbecker** [comment]
#202 is basically the same issue as this one.

**Comment by rvanlaak** [comment]
I'm affraid resolving this on the PHP side is quite impossible, as it is deeply nested in the Symfony / Doctrine frameworks.

We found out that MySQL workbench is able to show the value, and shows these as small `NUL` characters with a black background. Would this then be a difference in coding language?

**Comment by ansgarbecker** [comment]
> Would this then be a difference in coding language?

No, this is just a feature of the underlying editor component which Workbench has, and the one which HeidiSQL uses does not support such a thing.

Maybe I find a way to fix that cut text for editing, but we should definitely keep that all in issue #202 - I'll remark this one as a duplicate.
