### ISSUE TITLE
Table editor: columns widths gradually increased

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#728]
## Steps to reproduce this issue

1. Create table and view in one database:
```
CREATE TABLE t1 (id INT);
CREATE VIEW v1 AS SELECT * FROM t1;
```
Any existing table and view in DB would do the trick.

2. Refresh tree;
3. Click at table in the tree, and notice current columns widths in table editor;
I see this (after deleting heidi related values in registry)
![1](https://user-images.githubusercontent.com/7234987/62434246-3637d580-b77b-11e9-828d-a865dd70a1c2.png)

4. Click the view in the tree.
5. Click on the table in tree and notice that now all columns in table editor are wider
Now I see this (notice Comment is not displayed any longer and Default is barely fin in editor's view):
![2](https://user-images.githubusercontent.com/7234987/62434281-4059d400-b77b-11e9-93fd-4b1f564270bc.png)
The table editor become unusable after just a few more switches from View/SP to Table as only Name and Datatype visible and I have to scroll to the right for everything else.

## Current behavior
In table editor columns becoming wider and wider over time.

Every time you restart Heidi or switch from View/SP editor to Table editor columns in the Table editor becoming wider (you can check value ColWidths_frmTableEditor.listColumns in registry) 
In the example above, the ColWidths_frmTableEditor.listColumns value changes from:
27,125,230,113,75,81,63,178,163,210,125,125
to:
27,156,288,141,94,101,79,223,204,263,156,156
after switching from t1 to v1 and then back to t1.

## Expected behavior
Column should keep their widths

## Environment
Win 10 64bit, 1803
Display settings: 125%
To rid off blurenes, compatibility settings were set up for heidisql.exe to 'Override high DPI scaling behavior. Scaling performed by: Application' (<del>the issue exists without the High DPI override as well</del>)
HeidiSQL Theme: Windows

* **HeidiSQL version:** 
10.2.0.5636, 10.2.0.5637 and the latest nightly (10.2.0.5669)

There is no such issue in 10.2.0.5599, 10.2.0.5632, 10.2.0.5634, 10.2.0.5635.
Looks like removing the DPI awareness caused the issues.

**Comment by fifonik** [comment]
No one having the issue?

Anyway, I rolled back further to the 10.2.0.5613.
In the 10.2.0.5635 there is no issue with Table editor, but it has the similar issue with Session Managed window. Just open/close Session Manager a few times (Ctrl + N then Esc) and the window will be smaller and smaller every time you do this if you have not 100% display scaling.

5613 is the latest version where the size of Session Manager is not shrinking.

**Comment by ansgarbecker** [comment]
Your screens look as if you have activated application controlled zooming in your shortcut to heidisql.exe - if so, that's a self-baken issue.

**Comment by fifonik** [comment]
Could you explain, what are you talking about?
The screenshots in original post were taken with 'Override high DPI scaling' set to Application.
However, as I mentioned, the issue is here even when I disable it:

![3](https://user-images.githubusercontent.com/7234987/63974122-8e01fc00-caef-11e9-8519-0e044ce0094d.png)
Looking on table after manually deleting Heidi's settings in registry:
![4](https://user-images.githubusercontent.com/7234987/63974584-7ecf7e00-caf0-11e9-8c18-700e99969813.png)
When I switched from table to view and back 3 times.
![5](https://user-images.githubusercontent.com/7234987/63974596-842cc880-caf0-11e9-8d2f-37c1d9d78762.png)

**Comment by ansgarbecker** [comment]
Please update to the latest build and check again - you are using build 5636 which is ~50 changes behind the current state.

**Comment by ansgarbecker** [comment]
Ah and yes, I meant that setting _Override high DPI scaling_ - activating that breaks several control dimensions, same issues as HeidiSQL had while I tried to support high DPI settings.

**Comment by fifonik** [comment]
I'll try to check the most recent build on Monday.
However, I was reading changelog regularly and have not seen DPI related changes since then. It is possible that I missed something.

**Comment by ansgarbecker** [comment]
Your screens are from build 5636, and I removed DPI awareness one commit later, in build 5637. Also there were some additional fixes even later, so the update is required. The fonts on your screens look naturally sharp, which also tells me that was a DPI aware build.

**Comment by fifonik** [comment]
Checked with the latest build (5683 at this moment) and there is no such issue when Override high DPI scaling is not used.
Fonts blurred, but everything else looks normal (columns widths and session manager window size not changed). If I'm trying to set Override high DPI scaling to 'Application' to deal with fonts blurriness, the issue still there but this is another story.

**I double checked with 5637 and there is no issue when Override high DPI scaling as well (there is issue when Override high DPI scaling in on 'Application'). Looks like I have not turned off the Override high DPI scaling during my original testing.**

**Comment by ansgarbecker** [comment]
Ok, so we can close this issue, if I read it right now. If not, please shout.
