### ISSUE TITLE
The log display needs to be optimized because it gives the user an illusion.

### ISSUE THREAD

**Issue by id0612** [HeidiSQL/HeidiSQL#729]
## Steps to reproduce this issue

1. Step 1;
Execute an SQL with newline characters, such as:

![image](https://user-images.githubusercontent.com/2449459/62506809-9e96bd80-b834-11e9-832e-20ad6d8dadea.png)

OR

![image](https://user-images.githubusercontent.com/2449459/62506842-be2de600-b834-11e9-8ffe-c2c637fb83a2.png)

2. Step 2;

Copy the SQL just executed from the log, such as:
![image](https://user-images.githubusercontent.com/2449459/62506909-05b47200-b835-11e9-9e70-0f57ece4c6f2.png)

![image](https://user-images.githubusercontent.com/2449459/62506943-2381d700-b835-11e9-847e-ecae6856fe87.png)

3. Did you see that? Visually, I can't select the last few characters, but when I execute the copy command, the paste is correct. This is the illusion I'm talking about. When SQL statements include line breaks, the display is inconsistent with the copy. Although the user can copy the SQL completely, during the process, the user will repeatedly try to select the last few characters, thinking that he did not choose the complete one.

When we format the SQL statements, or modify the table structure, we can get such SQL statements in the log, including the SQL statements of newline characters.

## Current behavior

When the executed SQL statement includes a newline character, when it is copied from the log, the selection is not complete visually, but the replication result is complete, which can cause some confusion to the user.

## Expected behavior

There is no need to change the SQL statement for this, which is fine, but it is necessary to fix the problem just now, so that users can clearly know that they have selected the desired SQL statement in such a scenario.

## Environment

win 10 chs

* **HeidiSQL version:** 
10.2.0.5669

**Comment by ansgarbecker** [comment]
That's what I introduced intentionally, and called it SingleLineMode. That's for better readability.

Disabling this single line mode would in my eyes blow up the log panel. 

Were's the real problem with this?

**Comment by id0612** [comment]
I just want the display to be consistent with the actual copy of the content in the current mode. Don't let the user mistakenly think they didn't choose the full SQL and try to select it again and again.

**Comment by id0612** [comment]
This is not a serious problem, just the user experience is not very good. Trying to select multiple lines, the user can still choose a complete statement, but only if he needs to know that he must do so. Otherwise, some users will go crazy here, complaining that they can't fully select SQL. ^ - ^

**Comment by ansgarbecker** [comment]
Well, I must say I prefer that single-line-mode for usability reasons. Having linebreaks within one query would break the idea that each command is a line there.
