### ISSUE TITLE
Add informative log message when maximum result sets exceeded

### ISSUE THREAD

**Issue by srsbiz** [HeidiSQL/HeidiSQL#73]
## Expected behavior

Show result tab for every query that returns any data.

## Current behavior

Only first 10 result tabs are present to view selected data, but all queries are executed

![heidisql-more-than-10-results](https://user-images.githubusercontent.com/1525842/34645104-4707e23e-f345-11e7-8883-526eceb2ea7e.png)

### Steps to reproduce

search in database for anything that will be present in more than 10 tables and click button to se results or execute more than 10 selects in query tab:

```
select 1;
select 2;
select 3;
select 4;
select 5;
select 6;
select 7;
select 8;
select 9;
select 10;
select 11;
```

### Context

* HeidiSQL version: 9.5.0.5216 (64bit)
* Database system + version: MySQL 5.6.15
* Operating system: 10.0.16299.192

**Comment by ansgarbecker** [comment]
This is definitely a feature, not a bug :) If you look at Tools > Preferences > SQL, you will find a setting called "Maximum result sets", which defaults to 10. You can increase this to get more results. It is important to limitate the number, for cases in which the user loads some huge scripts with thousands of SELECTs.

I only think when the maximum has been exceeded, some log message should appear in the log panel.

![grafik](https://user-images.githubusercontent.com/7986591/34648588-12e08c02-f39c-11e7-85b2-3bacdc2e78d4.png)

**Comment by srsbiz** [comment]
Awesome, thanks!
