### ISSUE TITLE
Switching the label changes the display language of the label

### ISSUE THREAD

**Issue by id0612** [HeidiSQL/HeidiSQL#730]
## Steps to reproduce this issue

1. Connect to the database and select a database and then switch to the host tag. Look, the database tag is already displayed in English.
![image](https://user-images.githubusercontent.com/2449459/62515517-183ea380-b855-11e9-8e66-b1e6b952c846.png)

2. Switch several other tags, you will discover this magical change process.
![image](https://user-images.githubusercontent.com/2449459/62515600-66ec3d80-b855-11e9-9c12-46e46182b722.png)

![image](https://user-images.githubusercontent.com/2449459/62515622-77041d00-b855-11e9-8b62-58cfc4e18a7a.png)

![image](https://user-images.githubusercontent.com/2449459/62515655-88e5c000-b855-11e9-808a-fa99c94129c4.png)

![image](https://user-images.githubusercontent.com/2449459/62515680-97cc7280-b855-11e9-9c5a-af8601e9cd29.png)

3. Finally, this set of tags is displayed in English until the next time you open the software, they will revert to the software language, and if you switch them again, they will repeat the above process.

## Current behavior

A magical phenomenon: Switching these tags automatically changes the language of their name to English, regardless of the language used.

## Expected behavior

Any operation that is not related to changing the software language should not switch the corresponding display language.

## Environment

![image](https://user-images.githubusercontent.com/2449459/62515912-38bb2d80-b856-11e9-9a6d-1bf835ab5427.png)

**Comment by ansgarbecker** [comment]
This seems to be a problem with translation via code. Will check that.

**Comment by ansgarbecker** [comment]
Fixed!

**Comment by id0612** [comment]
Ok, I will try it after the release.
