### ISSUE TITLE
Index adds comment keyword and then does not display index in software

### ISSUE THREAD

**Issue by sowork** [HeidiSQL/HeidiSQL#732]
1. Create a table
```
CREATE TABLE IF NOT EXISTS `test` (
  `str` varchar(50) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
2. Add an index
```
ALTER TABLE `test` 
 ADD INDEX `idx_str`(`str`) USING hash COMMENT 'xxxxxxx';
```

## Current behavior
No index is visible in the software

## Expected behavior

Ability to view indexes in software

## Environment
heidisql version: 10.2.0.5599
mysql version: 5.7
operating system: Microsoft Windows [版本 10.0.18945.1001]

**Comment by ansgarbecker** [comment]
Index comments are apparently a new feature in MySQL?
The next build should at least display such indexes. Please update and report back.
