### ISSUE TITLE
some values look like empty,but not empty

### ISSUE THREAD

**Issue by ninghongju** [HeidiSQL/HeidiSQL#734]
## Steps to reproduce this issue

value is JSON string and datasize > 1.3MB
![image](https://user-images.githubusercontent.com/23132816/62763955-52ab7900-babf-11e9-9a4d-6b4f8f0db7a3.png)

![image](https://user-images.githubusercontent.com/23132816/62764060-9b633200-babf-11e9-8b3c-6ad445889a5d.png)

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
I recall I saw these empty cells too, especially with large contents. But in v12.0 I can no longer reproduce this.
Please shout if you still encounter that issue.
