### ISSUE TITLE
Crash with EInvalidOp when parsing big number as time

### ISSUE THREAD

**Issue by iggyvolz** [HeidiSQL/HeidiSQL#735]
## Steps to reproduce this issue

1. Create table test with a BIGINT column: `CREATE TABLE test (time BIGINT(20));`
2. Insert a large number into the table: `INSERT INTO test VALUES( 9223372036854775807 );`
3. Open the Data tab for the table, right-click the column and check "This is a UNIX timestamp column" (or, if it's already interpreted as a UNIX timestamp, open the data tab)

## Current behavior

HeidiSQL crashes with the following crash (EInvalidOp: Invalid floating point operation).

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3494352/bugreport.txt)

## Expected behavior

HeidiSQL displays the cell as normal (with an absurdly large year)

## Possible solution

This appears to be some sort of overflow.

## Environment

* **HeidiSQL version:** 10.2.0.5599 (64 bit)

  
* **Database system and version:**  MariaDB 10.4.7
  
* **Operating system:**  HeidiSQl running on Microsoft Windows [Version 10.0.17763.437]; database running on WSL1, Ubuntu 18.04 distribution

**Comment by ansgarbecker** [comment]
Next build catches more than the previously only EConvertError exception, so this may heal this issue. Only there are some limitations on the internal date/time types, which will lead such big numbers to be converted to 1970-01-01.
Please check and report back.

**Comment by iggyvolz** [comment]
Confirmed, the bug is no longer appearing in 10.2.5675.  Thanks for the quick fix!
