### ISSUE TITLE
I found an interface layout defect on WIN7.

### ISSUE THREAD

**Issue by xiaoxing598** [HeidiSQL/HeidiSQL#736]
![image](https://user-images.githubusercontent.com/5615719/62999291-852eea80-bea0-11e9-9ec5-e5dc3ca218c8.png)

![image](https://user-images.githubusercontent.com/5615719/62999299-8c55f880-bea0-11e9-9a4d-a925f914b625.png)

**Comment by ansgarbecker** [comment]
This is how it looks like here, with the current build:
![grafik](https://user-images.githubusercontent.com/7986591/63074291-e9978b80-bf2c-11e9-888c-c4e1aff433c2.png)

As you deleted the whole issue template, I can only guess you are using an older build. Please use the latest build when reporting bugs, and fill in what the issue template asks for.

**Comment by xiaoxing598** [comment]
I am using the latest version, the screenshot below can prove this.

![image](https://user-images.githubusercontent.com/5615719/63088876-bedb2080-bf88-11e9-8308-29965cb66bcb.png)
