### ISSUE TITLE
Interface is blurry after latest build update 

### ISSUE THREAD

**Issue by T2L** [HeidiSQL/HeidiSQL#737]
## Steps to reproduce this issue

Just open the app :)

## Current behavior

Interface is pretty blurry; was not the case before. I think my previous build was from end of June.

![image](https://user-images.githubusercontent.com/492138/63013820-cd94db00-be95-11e9-9da3-8cc97a2c6131.png)

## Expected behavior

Make everything sharp again

## Possible solution

Revert back any DPI changes since June (?)

## Environment

I'm using 27" 4K display running @ 4k resolution with 150% font size. 

![image](https://user-images.githubusercontent.com/492138/63013452-eea8fc00-be94-11e9-9f29-c9876cdd7e0f.png)

* **HeidiSQL version:** 
Version 10.2.0.5675 (64 Bit)

* **Operating system:** 
Windows 10

**Comment by T2L** [comment]
After some looking around I came up with this comment: https://github.com/HeidiSQL/HeidiSQL/commit/c31cae206042ae00b97e41f43baf7421693d2e46#commitcomment-34421870

This setting does make everything sharp again.

**Comment by ansgarbecker** [comment]
Sharp - yes, but many controls will behave buggy with that setting.

c31cae2 removed all tweaks for high DPI monitors, after spending lots of hours into this. See also all the [high dpi tickets](https://github.com/HeidiSQL/HeidiSQL/issues?q=is%3Aissue+label%3Ahigh-dpi)

**Comment by glen-84** [comment]
It's so much better with that setting enabled – quite unfortunate that this is no longer the default.
