### ISSUE TITLE
The lower label of the host label, the label is abnormal when refreshed.

### ISSUE THREAD

**Issue by id0612** [HeidiSQL/HeidiSQL#739]
## Steps to reproduce this issue

1. Step 1;
Connect to the database and enter the host interface，Refresh the Database tab, it is normal.
![image](https://user-images.githubusercontent.com/2449459/63091479-0f567c00-bf91-11e9-8edb-8c27714dffe5.png)
2. Step 2;
Switch to another tab and repeat the refresh operation.
![image](https://user-images.githubusercontent.com/2449459/63091557-517fbd80-bf91-11e9-9669-b73cf25147a9.png)
![image](https://user-images.githubusercontent.com/2449459/63091600-6ceac880-bf91-11e9-9c09-f7d8e8885792.png)
3. Then I get...
see it? In addition to the Database tag, each time the other tags are refreshed, the content displayed on the tag will be incremented by a digital display. I didn't update the numbers as I hoped.

## Current behavior

When some tags are refreshed, the tag displays an exception.

## Expected behavior

When refreshing, the numeric display of the number of data lines of the current page is updated instead of being additionally displayed later.

## Possible solution

Small problem, fix it.  ^-^

## Environment

![image](https://user-images.githubusercontent.com/2449459/63091810-31043300-bf92-11e9-8cd8-dd3126143709.png)

**Comment by ansgarbecker** [comment]
My fault - caused by my fix for #730

**Comment by ansgarbecker** [comment]
Fixed for the next nightly build.
