### ISSUE TITLE
Default values (expressions) are shown wrong in "CREATE CODE" tab for MariaDB 10.2

### ISSUE THREAD

**Issue by vaintroub** [HeidiSQL/HeidiSQL#74]
## Expected behavior
HeidiSQL's "create code" tab for the table's DDL  should be semantically equivalent to "show create table" SQL command.  Also in case where  DEFAULT column values  is an expressions (which is new  MariaDB 10.2 feature, but also SQL standard one) , "Create Code" should show the expression correctly.

## Current behavior
when DEFAULT for a COLUMN is an expression, HeidiSQL's "create code" does not understand it, and makes a character string instead of expression. In the "steps to reproduce" below, functions curdate(),curtime() are converted to character strings 'curdate' and 'curtime', and expression  (rand()*4) ) is converted to character string 'rand'

## Failure information (for bugs)

https://github.com/HeidiSQL/HeidiSQL/commit/f5d9603549f877e030c166577e67fa3204c20955
provides partial fix for special cases.

### Steps to reproduce
1. create a table in mariadb like this
```sql
Create table t (
dt date default curdate(),
tm time default curtime(),
d int default (rand()*4) );
```
2.  Rightclick on table in the tree, Edit, Choose "Create code" TAB to see how heidiSQL  interprets it
```sql
CREATE TABLE `t` (
	`dt` DATE NULL DEFAULT 'curdate',
	`tm` TIME NULL DEFAULT 'curtime',
	`d` INT(11) NULL DEFAULT 'rand'
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
```

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version - 9.5.0 Revision 5219 
* Database system + version: MariaDB 10.2 
* Operating system: Windows

**Comment by rentalhost** [comment]
**Same as #29.**

Possible solutions when client is MariaDB 10.2:

* **Solution 1:** on the `Custom:` input on `Default` column on Table editor should have an nested checkbox like `Run as function`;
* **Solution 2:** create a new option below `Custom:` like `Run as function:`;
* **Solution 3:** just create a checkbox without label on right-side of `Custom:` input with a hint that defines what it mean;
* **Solution 4 (danger workaround):** if `Custom:` have any `(` identify it directly as an function. But it could conflicts with a real definition from user "as text" that have `(` on the content;

**To be discarded:** as in #29 is suggested that we have a context menu with available options, but it will not works once that you could use an expression like the example above `(rand() * 4)`.

**Comment by ansgarbecker** [comment]
Sorry for the long delay. But I just spent some of the lazy easter hours on this topic, where HeidiSQL's table editor is quite broken yet.

In the table editor, I just removed the radio button for the very specific `CURRENT_TIMESTAMP` and the checkbox for the `ON UPDATE CURRENT_TIMESTAMP` clause. Instead, we now have an "Expression" input field, along with an "On update" field:

![grafik](https://user-images.githubusercontent.com/7986591/56470938-9fa20b80-644c-11e9-840d-d5aadd16f573.png)

In its parsing, HeidiSQL also supports expressions other than `CURRENT_TIMESTAMP`. I'm just yet unsure about which expressions require parentheses around them. Looks like normal functions don't need + want them, while an expression like `1 + 3` requires them. So HeidiSQL does not yet automatically add parentheses around the expression, the user has to manually enter them:

![grafik](https://user-images.githubusercontent.com/7986591/56471020-ae3cf280-644d-11e9-84b7-d654b8fa9a3f.png)

**Comment by zufuliu** [comment]
Hi @ansgarbecker  can you bring back the old quick checkbox for CURRENT_TIMESTAMP? or add CURRENT_TIMESTAMP, CURRENT_DATE and CURRENT_TIME (and other keywords that represents a value) into the dropdown box?
I think the three items should be the first candidate for a TIMESTAMP/DATETIME, DATE and TIME column. The very long list of only functions are hard to pick, the current_timestamp() function for MariaDB is even not in the list.

MySQL
![MySQL](https://user-images.githubusercontent.com/2289926/69773029-a526b780-11cc-11ea-89b2-648f92bc64a1.png)

MariaDB
![MariaDB](https://user-images.githubusercontent.com/2289926/69773031-a8ba3e80-11cc-11ea-961b-07ba761c2cf3.png)

**Comment by ansgarbecker** [comment]
@zufuliu Indeed that `CURRENT_TIMESTAMP` was missing, I just added it to that dropdown again. Check the next build.

By the way, you can also use `NOW()`, which is a synonym for `CURRENT_TIMESTAMP()`.

Bringing back the old dedicated radio buttons does not make much sense, apart from seeing them quicker probably. But `CURRENT_TIMESTAMP()` is just one out of many expressions supported by MariaDB/MySQL. And that would make this dialog even longer than it is.

**Comment by zufuliu** [comment]
@ansgarbecker Thank you.

**Comment by ansgarbecker** [comment]
I'm closing this for now. Further problems or enhancements should get a new ticket.
