### ISSUE TITLE
MySQL 5.7.18 0 - Cannot create user...

### ISSUE THREAD

**Issue by niglezakis** [HeidiSQL/HeidiSQL#740]
## Steps to reproduce this issue

1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by niglezakis** [comment]
Hi. just download the latest (10.2.0.5599 ) version ( 32 / 64 ) and try 32bit version on Windwos 2016 Server. Connect as root. When press "Manage user authentication and privileges" a popup comes out saying...

SQL Error (1146): Table 'mysql.servers' doesn't exists

The installation of MySQL works for at least 4 years now... NO problems...

what i saw now is that 'mysql.server' exists BUT is a (probably) INNODB file, thus since the program looks for MyISAM files, it cannot locate the 'mysql.server' even though the file DOES exists in the 'mysql' directory.... hmmm

**Comment by ansgarbecker** [comment]
Are you sure the message complains about `mysql.servers`, not `mysql.user`?
There is no internal query in HeidiSQL directly accessing `mysql.servers`, but there is a query which selects usernames from `mysql.user`, which is used to check if you have permissions.
Please also post the last 10 lines from the query log panel, as soon as you click on the user manager button.

**Comment by ansgarbecker** [comment]
Closing due to missing feedback.
