### ISSUE TITLE
Slow start ~

### ISSUE THREAD

**Issue by vioulo** [HeidiSQL/HeidiSQL#742]
Click this to run , it will take about 1 minute or more.
win7 / HeidiSQL version 10.2.0.5683 
It’s probably starting from 10.2.0.5*，I can't remember the specific version.
Also, i turned off automatic update checking :crying_cat_face:

**Comment by ansgarbecker** [comment]
Could you at least go one build backwards, by downloading it from the [builds section](https://www.heidisql.com/download.php#nightlybuilds)?

**Comment by vioulo** [comment]
yes, i downloaded version is HeidiSQL_10.2.0.5683_Setup.exe

**Comment by ansgarbecker** [comment]
No, I meant one earlier than the latest build, which is currently 5682. Please download the right heidisql.exe and place it in your HeidiSQL directory, then run it and see if that still is slow.

**Comment by vioulo** [comment]
Oh, today it seems to be starting normally, maybe it's a problem with my network, but i turned of update checking ,does this affect it ?

**Comment by ansgarbecker** [comment]
Yes, update checking fires a http request in the interval you have set in preferences. Disabling that might have solved it, although the check is normally very quick.
Please play with the update-check settings and report back the results.

**Comment by vioulo** [comment]
Now i truned on update-check settings, it really took more time start.

**Comment by ansgarbecker** [comment]
Ok, then this is just due to a slow network connection. I guess we can close this then.
