### ISSUE TITLE
Duplicate shortcut crashes Heidi

### ISSUE THREAD

**Issue by cautionbug** [HeidiSQL/HeidiSQL#744]
## Steps to reproduce this issue

Possibly related to #733?

i did this from the initial launch dialog, no open connections. Call stack attached.

1. Open Preferences
1. Go to Shortcuts
1. Attempt to change or set a keyboard shortcut already in use.
   * Example: try setting "SQL > Reformat SQL" to *Ctrl+Alt+F* (by default assigned to "Various > Filter Panel")
1. First try sets the shortcut to *(None)*
1. Second try, crash:
   * Exception Class: `EInvalidOperation`
   * Exception Message: `Cannot focus a disabled or invisible window.`

## Current behavior

Crash

## Expected behavior

Any of these:
1. Kill operation - *Shortcut already in use by "Other Thing".* Force manual removal/reset.
1. Prompt: *Shortcut already in use by "Label". Set here and clear "Other Thing"?*
1. Prompt: *Shortcut already in use by "Label". Set here and switch to "Other Thing" next?*

## Environment

* **HeidiSQL version:** 10.2.0.5683 (no newer nightly available)

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3567327/bugreport.txt)

**Comment by ansgarbecker** [comment]
I have now modified the shortcut editor to prompt the user if the wanted shortcut is in use by another action. So this is taken from your second idea from above:
![grafik](https://user-images.githubusercontent.com/7986591/102818482-04f09180-43d2-11eb-9f28-09864c701a9d.png)

But... this does not fix the crash you mentioned. It seems a pressed shortcut still triggers its assigned action before the shortcut editor handles it. I suppose I have to catch some message in this special dialog.

**Comment by cautionbug** [comment]
Thanks for the update! i like the confirmation message.

**Comment by ansgarbecker** [comment]
The next build now "suspends" the actions which listen to various shortcuts, as long as the preferences dialog is open. That should at least heal crashing shortcuts in the preferences dialog. I'll close this now, would be nice if you re-check once.

**Comment by cautionbug** [comment]
Clever bypass. i'll get the latest build and take a look. You do amazing work!
