### ISSUE TITLE
Session background color not updated on save

### ISSUE THREAD

**Issue by Joey79100** [HeidiSQL/HeidiSQL#745]
## Steps to reproduce this issue

1. Open the session manager
2. Select a session
3. Change its background color
4. Save the session settings

## Current behavior

The currently opened session background color remains the same. It only changes if I restart HeidiSQL, or reopen the session.

## Expected behavior

The currently opened session background color gets updated as soon as I save the new session settings.

## Possible solution

I'm wondering if this was intentional or not. If it was, you could add a checkbox next to the background color selector: "Also update color for already open sessions".

## Environment

* **HeidiSQL version:** 10.2.0.5683 (2019-08-26 12:06:41)
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
There is no setting which applies to an open session. E.g. the password and whatever only applies for newly opened sessions. But I guess making an exception here can be ok for harmless things like the color.

**Comment by ansgarbecker** [comment]
I just pushed a change which applies the color in the back when you press the save button.

Are there more settings which should be applied to a living connection?
