### ISSUE TITLE
Table Editor not updated after adding a comment to a table

### ISSUE THREAD

**Issue by andipfaff** [HeidiSQL/HeidiSQL#747]
## Steps to reproduce this issue

1. Step 1; choose a table in the tree
2. Step 2; click on Register "table"
3. Step 3; click on Register "Basic"
4. Step 4: add a comment
5. Step 5: click on save
Then comment will disappear. Change the table an go back to the modified table then the comment will be visible.

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by andipfaff** [comment]
Version 10.2.0.5678 on Win10

**Comment by ansgarbecker** [comment]
That was already reported. Please see #683 - and also on the roadmap for the next release.
