### ISSUE TITLE
Installer downloads from heidisql.com are really slow

### ISSUE THREAD

**Issue by nkmathew** [HeidiSQL/HeidiSQL#749]
## Steps to reproduce this issue

1. Go to HeidiSQL's website: https://www.heidisql.com/download.php
2. Click on the "Installer, 32/64 bit combined" link and download the installer
3. It starts downloading, crawls to a stall and then timesout

## Current behavior

Downloads take forever to finish(haven't been able to download one). The download times out with a download manager line IDM.

## Expected behavior

It should at least finish the download or it shouldn't be this slow. I'm not exactly on a slow connection given I can watch YouTube in 720p.

## Possible solution

Use Github releases as a mirror for the binary builds

## Environment

Windows and Chrome

---

![](https://i.imgur.com/rmQfPG4.png)

![](https://i.imgur.com/D1o61If.png)

**Comment by ansgarbecker** [comment]
Please try downloading without download manager.

**Comment by decadence** [comment]
I downloaded version 10.2 yesterday from site and speed was fine

**Comment by ansgarbecker** [comment]
For me too, all download links are very quick.

The downloads just don't support resuming and parallell connections, required by your download manager. Please download them with just your browser download feature.

**Comment by willnode** [comment]
Hello, If anyone still stumbe upon this issue... I'm here in Asian part of the world and downloads is super slow.

If I download from my server that lives in New York it's super fast.
