### ISSUE TITLE
Idle Connections

### ISSUE THREAD

**Issue by ProffiCV** [HeidiSQL/HeidiSQL#751]
## Steps to reproduce this issue

1 - Working Normal
2 - Do other stuffs in computer and let the HeidiSQL app running (no focus)
3 - After a while, get back to HeidiSQL and try to do anything
4 - On Execute I get "Dialog Need to Restart"

## Current behavior
App just crash and display dialog to restart (the only possible solution), if the connection is idle

## Expected behavior

Continue normal work, just dealing with idle connection, display reconnect if can't connect
## Possible solution
Refresh connection if idle for long, before the Dialog asking to Restart

## Environment

* **HeidiSQL version:** 
9.4.0.5125
  
* **Operating system:** 
  
Windows 7

**Comment by ansgarbecker** [comment]
Please update to the latest build and report back with the crash report from the dialog, if the problem persist. Will reopen then.
