### ISSUE TITLE
Support for plugin client_ed25519

### ISSUE THREAD

**Issue by hrvoj3e** [HeidiSQL/HeidiSQL#754]
## Steps to reproduce this issue
1. Try to connect to MariaDB server with user created with 
`CREATE USER aaa@127.0.0.1 IDENTIFIED VIA ed25519 USING PASSWORD('aaa');`
4. Then I get...
> Plugin client_ed25519 could not be loaded

## Possible solution

There should be a plugin DLL in portable versions but I can't find it. Or ??

## Environment
* **HeidiSQL version:** 10.2.0.5695
* **Database system and version:** mysql  Ver 15.1 Distrib 10.4.8-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
* **Operating system:** arch + wine-4.15

**Comment by ansgarbecker** [comment]
Plugins are in the portable version as well, in the plugins folder. These are those from the current portable release v10.2:
![grafik](https://user-images.githubusercontent.com/7986591/66398682-854df100-e9de-11e9-9816-4738697f86da.png)

Is that `ed25519` plugin somewhere available? What exactly does it?

**Comment by hrvoj3e** [comment]
I am talking about the fact that HeidiSQL asks for a `client plugin ed25519` when I am trying to connect to MariaDB with a user created with server `auth_ed25519` authenication plugin.

https://mariadb.com/kb/en/library/authentication-plugin-ed25519/

![screenshot 2019-10-08 15-26-55](https://user-images.githubusercontent.com/4988133/66399540-18d3f180-e9e0-11e9-83d3-1ed94be3dc5a.png)

I expected to see in dir `plugins/` something like `auth_ed25519_client.dll`. Or am I totally lost here :question:

**Comment by ansgarbecker** [comment]
Well that's what I meant - the folder should be there, unless you deleted it. But that special auth_ed25519_client.dll file is not yet there, because I did not yet add it. And I did not even hear anything about it until you reported that.

I hope that file can be obtained separately, and is not statically linked into some libmariadb.dll. I'm just searching for it.

**Comment by ansgarbecker** [comment]
Just found them in the Windows packages on https://downloads.mariadb.com/MariaDB/mariadb-10.4.8/

Next nightly built installers should have them. Unfortunately, I am creating the portable only for the official releases, so I cannot give you a zip file. But you could [download the relevant file](https://github.com/HeidiSQL/HeidiSQL/raw/master/out/plugins32/client_ed25519.dll) yourself and put it into your heidisql/plugins folder.

Please report back if that works for you then.

**Comment by hrvoj3e** [comment]
It works now.

I used:
 - nightly build: [`heidisql64.r5712.exe`](https://www.heidisql.com/builds/heidisql64.r5712.exe)
 - new 64 bit plugin [`client_ed25519.dll`](https://github.com/HeidiSQL/HeidiSQL/raw/master/out/plugins64/client_ed25519.dll)
 - updated 64 bit [`mariadb.dll`](https://github.com/HeidiSQL/HeidiSQL/raw/master/out/libmariadb64.dll)

**Comment by ansgarbecker** [comment]
Perfect! Thanks for your quick feedback!
