### ISSUE TITLE
Links in help when using 'dark' theme are illegible

### ISSUE THREAD

**Issue by alystair** [HeidiSQL/HeidiSQL#755]
## Steps to reproduce this issue
1. Open HeidiSQL
2. Enable dark theme
3. Utilize SQL help functions
4. Observe any URLs in text

## Current behavior
Links are totally illegible.
![image](https://user-images.githubusercontent.com/159109/65676373-cb3da900-e01d-11e9-9f9f-1b560ec3af55.png)

## Expected behavior
Links should be readable.

## Possible solution
Change link coloring in dark theme to something lighter.

* **HeidiSQL version:** 
10.2 .0.5599

**Comment by ansgarbecker** [comment]
Any idea which link color fits good on dark themes?

**Comment by alystair** [comment]
#5db0d7 seems nice, although you could always match an existing color in the theme for consistency, such as the color used by table names in the SQL log.

**Comment by ansgarbecker** [comment]
I think the identifier color is not the right one, as this by default reddish, quite uncommon for hyperlinks. But your color looks ok to me:

![grafik](https://user-images.githubusercontent.com/7986591/65717406-8eb39100-e0a1-11e9-9bcf-2086c6692f1a.png)
