### ISSUE TITLE
Set @@SQL_NOTES to 0 to silence warnings in export file

### ISSUE THREAD

**Issue by decadence** [HeidiSQL/HeidiSQL#756]
## Steps to reproduce this issue
1. Export database as SQL
2. Load this file into new database
3. Run SQL

SQL example: [tal.txt](https://github.com/HeidiSQL/HeidiSQL/files/3661798/tal.txt)

## Current behavior
Database is imported but with warnings. One of them is this:
![2019-09-27_11-25-18](https://user-images.githubusercontent.com/1434668/65754927-c579bd80-e11a-11e9-9550-0b0778d054c7.png)

## Expected behavior
I expect that sql dump exports/imports without warnings.
If I create dump with mysqldump it imports ok.
It happens on single MySQL server.

## Possible solution
I don't know

## Environment
HeidiSQL: 10.2.0.5599
MySQL: 5.6.37
OS: Windows 10

**Comment by ansgarbecker** [comment]
That is just a warning, caused by these `ALTER` commands:
```
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
/*!40000 ALTER TABLE `users` ENABLE KEYS */;
```
So I suppose InnoDB does not support disabling/enabling keys.

**Comment by ansgarbecker** [comment]
mysqldump does exactly the same, but it also silences these warnings, by setting `SQL_NOTES` to zero:

```
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
...
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
```

I guess then HeidiSQL should do the same, or even better: for InnoDB tables don't generate these `ALTER` commands.

**Comment by decadence** [comment]
Thanks

**Comment by decadence** [comment]
Yes this is just a warnings but anyway this is disturbing.
