### ISSUE TITLE
Opening SQL file produces Chinese text in query window

### ISSUE THREAD

**Issue by kovacsvx** [HeidiSQL/HeidiSQL#757]
## Steps to reproduce this issue

1. Open a sql file via Ctrl-o and pick any SQL file;
2. Then I get Chinese text in the SQL area.

## Current behavior

SQL window gets a bunch of nonsense Chinese characters.
If I leave the file open but close HS and then restart HS, the
query tabs restore with the SQL being correct.

## Expected behavior

My SQL file should show up.

## Possible solution

No idea.

## Environment

Running on Windows 10.  Have 4 language keyboards installed, including Chinese.

Images below show what happens after opening file, then the regular results from closing and reopening Heidi.

* **HeidiSQL version:** 

Updated to nightly 5700 and behaviour is the same.

![HeidiSQLChinese](https://user-images.githubusercontent.com/21371249/65794135-8147e680-e135-11e9-9e80-f470069af693.png)
![HeidiSQLChineseAfterCloseAndReopen](https://user-images.githubusercontent.com/21371249/65794370-f9aea780-e135-11e9-8689-ac4f9f656034.png)

**Comment by ansgarbecker** [comment]
Which file encoding did you select in the file-open-dialog? Don't use "Auto-detect"...

**Comment by kovacsvx** [comment]
That was it.  I changed it from autodetect and now it's fine.  Closing.
