### ISSUE TITLE
SQL crashes after update to newest version from today 01.10.2019

### ISSUE THREAD

**Issue by andipfaff** [HeidiSQL/HeidiSQL#758]
After doing the recommende update which appears when starting HeidiSQL I can no longer connect to my MySQL servers. See attached log which will be shown after clicking on OK to connect to any server in the list.
![Unbenannt](https://user-images.githubusercontent.com/4201912/65958501-ccbd0600-e44f-11e9-9a72-e9cb49642082.png)

**Comment by andipfaff** [comment]
please close this, seems to be a problem on my client
best regards
andi

**Comment by decadence** [comment]
@andipfaff
You can close it by yourself
