### ISSUE TITLE
Heidi crashes viewing table contents after changing to another database

### ISSUE THREAD

**Issue by andipfaff** [HeidiSQL/HeidiSQL#759]
Requirement: two different DB servers
Start HeidiSQL
connect to the first DB server
select a a database and a table in the tree
click on the register "Data" to view the table records
click on the button "Close selected database connection"
connect to the second DB server
select a a database and a table in the tree
click on the register "Data" to view the table records
HeidiSQL will crash

v10.2.0.5703 and previous versions too
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3676004/bugreport.txt)

**Comment by ansgarbecker** [comment]
Related to #692

**Comment by ansgarbecker** [comment]
Small glitches with bad effects in new features... Should be fixed in the next build.
