### ISSUE TITLE
Cannot drop "databases" in PostegreSQL

### ISSUE THREAD

**Issue by Zulgrib** [HeidiSQL/HeidiSQL#76]
## Expected behavior
Dropping scheme using "DROP" from contextual menu should drop it

## Current behavior

Scheme is not dropped, throws error.

## Failure information (for bugs)

ERROR, database does not exist
SET search_path TO E'OpenConcerto42', E'public';
DROP DATABASE "OpenConcerto42";
/* ERREUR:  la base de données « OpenConcerto42 » n'existe pas */

### Steps to reproduce

1. Connect to a PostgreSQL database with proper privileges (I used postgres account)
2. Drop a scheme from the contextual menu by right clicking on it
3. Confirm you are sure you want to drop it
4. Face error

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version:9.5.0.5196
* Database system + version:PostegreSQL 9.6
* Operating system:Windows 7 (client) Windows Server 2008 R2 (server)

### Failure Logs

ERROR, database does not exist
SET search_path TO E'OpenConcerto42', E'public';
DROP DATABASE "OpenConcerto42";
/* ERREUR:  la base de données « OpenConcerto42 » n'existe pas */

**Comment by Zulgrib** [comment]
As what are shown as databases are schema, the correct command would be

`DROP SCHEMA "$name";`

When dropping a schema, HeidiSQL should ask if we want to drop objects that depends on the one we're dropping, if the user accept, "CASCADE" should be added at the end of the query.

https://www.postgresql.org/docs/current/static/sql-dropschema.html

**Comment by ansgarbecker** [comment]
`DROP SCHEMA ...` is now used for PG, since the next nightly build.
