### ISSUE TITLE
Can't change case of session name

### ISSUE THREAD

**Issue by decadence** [HeidiSQL/HeidiSQL#760]
## Steps to reproduce this issue

1. Trying to rename session with case change of one letter. For example rename "super" to "Super"
2. Getting error "session already exists"

## Current behavior
Can't rename session if I change only case of the letters

![2019-10-03_14-32-10](https://user-images.githubusercontent.com/1434668/66123412-9c5d9f00-e5ea-11e9-8b21-b6276fc72be3.png)

## Expected behavior
Session should be renamed without error and double renaming.

## Environment
OS: Windows 10
HeidiSQL: 10.2.0.5599

**Comment by ansgarbecker** [comment]
HeidiSQL uses the underlying `TRegistry.MoveKey` method, which does not do any rename when I change the case of a key. So this would involve a second rename first, just with some postfix, just to be sure it's different from the final one. I tend to say this double renameingis not worth it. Is it fair to say: please name the session differently before changing it again with different case?

**Comment by decadence** [comment]
If it's hard to fix to we can handle this by ourselfs of course :)

**Comment by ansgarbecker** [comment]
I decide to leave this untouched. The benefit of being able to change the case is not worth the risk of losing session settings due to a probale crash inside that process.

**Comment by GPHemsley** [comment]
Would it be possible to make the error message more clearly indicate that this is intentional?

**Comment by ansgarbecker** [comment]
Yes, that's a good idea. How's that:
![grafik](https://user-images.githubusercontent.com/7986591/91206169-000f2000-e707-11ea-9ecf-462b41328fef.png)

**Comment by GPHemsley** [comment]
Works for me. :)
