### ISSUE TITLE
Not compatible with Postgres 12 due to use of obsolete and now-removed def.adsrc

### ISSUE THREAD

**Issue by chk-mk** [HeidiSQL/HeidiSQL#763]
## Steps to reproduce this issue

1. Try viewing a table on a postgres 12 DB

## Current behavior

Nothing shown but errors in console:

`ERROR:  column def.adsrc does not exist`

## Expected behavior

Works.

## Possible solution

Stop using adsrc or put a note that postgres 12 isn't supported.

See https://github.com/dbcli/pgcli/issues/1058

## Environment

* **HeidiSQL version:** 
10.2.0.5599 at least but most likely all.
* **Database system and version:** 
Postgres 12 beta1 and newer.

**Comment by ansgarbecker** [comment]
Using `pg_get_expr(def.adbin, def.adrelid)` from the next build on.

Thanks for the link to the pgcli issue - solution was easy this way.
