### ISSUE TITLE
App crash when using F1 key (the build-in help for SQL)

### ISSUE THREAD

**Issue by budiony** [HeidiSQL/HeidiSQL#764]
## Steps to reproduce this issue
Pressing F1 key while in query editor (for example over keyword "DATE_FORMAT")

1. Step 1; Pressing F1 key while in query editor (for example over keyword "DATE_FORMAT").
4. Then I get application crash TMainForm.CallSQLHelpWithKeyword (see the attached crash log).

## Environment

* **HeidiSQL version:** 
10.0.2.0.5709
  
* **Database system and version:** 
  
* **Operating system:** 
Windows 10
[F1-help.txt](https://github.com/HeidiSQL/HeidiSQL/files/3696845/F1-help.txt)

**Comment by budiony** [comment]
This worked fine in previous version 10.2.0.5706

**Comment by ansgarbecker** [comment]
Cannot confirm that here on a running MariaDB connection, but I'll recheck at home. And will check the line referenced in your callstack.

**Comment by ansgarbecker** [comment]
Hm, my second pc also does not crash here.

Is that crash reproducible for you or was it a one-timer perhaps?

**Comment by budiony** [comment]
Strangely enough after today's update (build 5710) I no longer can reproduce the issue.

**Comment by ansgarbecker** [comment]
Ok, I just retried reproducing it with multiple connections in a window, MS SQL and MySQL, with no luck.

I'll close this for now. Just reopen this ticket if you find a reproduction recipe at some point.
