### ISSUE TITLE
Tab key won't go to next cell in the data editor

### ISSUE THREAD

**Issue by okneloper** [HeidiSQL/HeidiSQL#765]
## Steps to reproduce this issue

1. Connect to a (MariaDB) database, select a table, and select the `Data` tab;
2. Right-click the data area and select "Insert new row"
3. Edit a text or a date field - type something
4. While the field is still focused and in editing mode, press the `Tab` key on the keyboard

## Current behavior
Nothing happens. 

## Expected behavior
The focus switches to the next cell in the row.
It works fine when editing a dropdown field. Also, I am pretty sure (although not 100%) that it worked fine previously. 

## Environment
* **HeidiSQL version:** 
10.2.0.5709
* **Database system and version:** 
MariaDB (don't think this is relevant)
* **Operating system:** 
Win 10 x64

**Comment by ansgarbecker** [comment]
Saw the same today and scratched my head...

**Comment by ansgarbecker** [comment]
Caused by 355db1403aff5c7d061962f3ca21c62bcd8001f8, to enable <kbd>Ctrl+Backspace</kbd> for #144.

**Comment by okneloper** [comment]
Awesome! Thanks for the quick turnaround :)

**Comment by ansgarbecker** [comment]
Unfortunately the solution for #144 is broken, and I have to find a better one.
