### ISSUE TITLE
Error editing row with JSON column

### ISSUE THREAD

**Issue by mets11rap** [HeidiSQL/HeidiSQL#769]
## Steps to reproduce this issue

1. Step 1: Create a table where a column has a JSON type
2. Step 2: Insert a row with the JSON column filled out with valid JSON
3. Step 3: Edit any column of that row
4. Error:
![Error](https://i.imgur.com/40O0TIg.png)

## Current behavior

It's giving me an error no matter what I do or edit. It doesn't have to be the JSON column being edited.

## Expected behavior

The row updating correctly.

## Possible solution

I have no clue
EDIT: This can be fixed with a primary key column, however, this should still not error.

## Environment

* **HeidiSQL version:** 
10.2.0.5712
  
* **Database system and version:** 
PostgreSQL v11.4
  
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
Problem seems to be the WHERE clause on a JSON column, which is included on UPDATEs if the underlying table has no primary key:

     WHERE  "json-column"='[1,2]'

I suppose there is again some specialty for comparing JSON values in PostgreSQL.

@mets11rap  Do you perhaps know how to manually update your row?

**Comment by mets11rap** [comment]
> Do you perhaps know how to manually update your row?

What do you mean by this?

**Comment by ansgarbecker** [comment]
If you know how to update your row by hand, with an `UPDATE ...` query, in a query tab?

**Comment by mets11rap** [comment]
Yes, I do. The problem is resolved for me anyway because I actually forgot to specify the ID column as a PKey, but this may be a problem for others.

**Comment by ansgarbecker** [comment]
It would be nice if you share that UPDATE here, so I can probably fix this in HeidiSQL for others.

**Comment by mets11rap** [comment]
Hope this helps!

https://popsql.com/learn-sql/postgresql/how-to-query-a-json-column-in-postgresql/

**Comment by ansgarbecker** [comment]
Well that explains how to query inner structure of a json field. I could not yet find a way to circumvent that "Operator does not exist: json = unknown"

**Comment by mets11rap** [comment]
Hm, this might be it.
https://www.postgresql.org/docs/10/datatype-json.html
![img](https://i.imgur.com/Q3ZpPd5.png)

Other than that, I don't know how to check for the full JSON value.

You could try looking through this, but that's pretty much it. I can't seem to find anything.
https://www.postgresql.org/docs/9.5/functions-json.html

**Comment by ansgarbecker** [comment]
I tried several approaches, which did not work (`j` is a JSON field in a table):
* `j = '[1,2]'`
* `j @> '[1,2]'`
* `j @> '[1,2]'::json`

The only one which works for me on PG 10.3 is this one:
* `j::text = '[1,2]'`

Please do a similar test on your server, and share your results here.

**Comment by ansgarbecker** [comment]
@mets11rap please update HeidiSQL to the latest build to get this fix, and please report back if that works for you, like it does for me.

**Comment by mets11rap** [comment]
@ansgarbecker Yeah, it works great! Thanks!
