### ISSUE TITLE
HeidiSQL toolbar button are on top of toolbar's menues

### ISSUE THREAD

**Issue by Zulgrib** [HeidiSQL/HeidiSQL#77]
## Expected behavior

Being able to clic text menu

## Current behavior

Buttons appears on top of text menues

## Failure information (for bugs)

![Bug image](https://lut.im/0jqJ3MU3ZF/7gV9UhegeAP9Id1Y.PNG)

### Steps to reproduce

Start HeidiSQL

### Context

* HeidiSQL version:9.5.0.5196
* Database system + version: Not applicable
* Operating system:Windows 10
High contrast theme enabled

### Failure Logs

No log found in %localappdata%\HeidiSQL and %appdata%\HeidiSQL

**Comment by ansgarbecker** [comment]
Very strange, indeed

**Comment by rentalhost** [comment]
Could not reproduce here. 
Windows 10 (FC) with high constrast theme enabled (four types).

@Zulgrib When you disable the high constrast theme it works normally?

**Comment by ansgarbecker** [comment]
Closing due to no feedback for a long time now.
