### ISSUE TITLE
will Multi-Tab be supported in future?

### ISSUE THREAD

**Issue by zinwalin** [HeidiSQL/HeidiSQL#771]
thanks a lot.

**Comment by WesleyM77** [comment]
What do you mean by this? Having multiple query tabs? That's already a feature.

**Comment by decadence** [comment]
https://github.com/HeidiSQL/HeidiSQL/issues/748

**Comment by ansgarbecker** [comment]
This is not a valid request or issue report.

Please follow the issue template, and prefer the forum on heidisql.com for questions and discussions.
