### ISSUE TITLE
a recent update broke query result grid interaction

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#776]
updated to r5721 and now interacting with any query result grid crashes HeidiSQL.

e.g. when focusing a cell and pressing Ctrl+C or right clicking a row to pull up a context menu.

the data grid still works ok, so this seems to just have impacted the query result grids.

think i was on r5711 before.

**Comment by ansgarbecker** [comment]
I suppose r5718 was it, but I cannot reproduce that here myself. So, please [download builds](https://www.heidisql.com/download.php#nightlybuilds) r5717 and r5718, and try to reproduce with both builds to verify that.

**Comment by ansgarbecker** [comment]
And please provide a callstack from the bugreport.txt file in the crash handler.

**Comment by MirshaKai** [comment]
I had the same issue with the 64 bit r5721. Rolling back to r5720 made the issue go away.

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3755525/bugreport.txt)

**Comment by leeoniya** [comment]
yep, r5720 works fine. my bug report is identical to @MirshaKai

**Comment by ansgarbecker** [comment]
Fixed - please update.

**Comment by leeoniya** [comment]
that did it. thanks! 👍
