### ISSUE TITLE
"Comment" keyboard shortcut in Quick filter doesn't work anymore

### ISSUE THREAD

**Issue by Joey79100** [HeidiSQL/HeidiSQL#777]
## Steps to reproduce this issue

1. Select any table, and select the Data tab.
2. Open the Quick filter area.
3. Type something in it.
4. Press your keyboard shortcut for "Comment line" to comment what you've typed.

## Current behavior

Nothing happens: the line isn't commented as expected.

## Expected behavior

The current line should be commented.

In the previous version, it used to work but threw an exception everytime. I reported this exception using the integrated error reporting system a few days/weeks ago (can't remember), but now the shortcut is completely disabled in this context. It is working in a normal query tab. I wonder if this is related, but I did not see a commit mentionning this so I'm not sure.

## Environment

* **HeidiSQL version:** 10.2.0.5722
* **Operating system:** Windows 10 1809

**Comment by ansgarbecker** [comment]
I just fixed the exception, as I was trying to reproduce that. My "un/comment" works now as expected here.

Probably you clicked somewhere else where I did not click, to get the action disabled. Please post where you exactly clicked, if the action still does nothing for you in the next build.

**Comment by Joey79100** [comment]
Okay, I've just tried again, the shortcut is working, and the exception is actually still there. I'm really sorry, this is the second time I post an issue and it was actually my fault. Well, at least this time it won't be useless since you fixed the exception, but still, I'll have to be more careful next time. Thank you.

**Comment by ansgarbecker** [comment]
No problem, as long as you provide feedback quickly.

I suppose the exception is fixed for you also in the new build?
