### ISSUE TITLE
PostgreSQL over SSH is missing

### ISSUE THREAD

**Issue by Zulgrib** [HeidiSQL/HeidiSQL#78]
## Expected behavior

Being able to use PostgreSQL over SSH tunnel, like MySQL/MariaDB

## Current behavior

Not available as connection type

### Steps to reproduce

Create new session
Clic network type

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* HeidiSQL version:9.5.0.5196
* Database system + version:PostgreSQL
* Operating system:Any

**Comment by ansgarbecker** [comment]
Next nightly build should have a new network type "PostgreSQL (SSH tunnel)", which you could be so nice to test :) It's the first attempt, so be patient if it does not yet work as expected.

**Comment by ansgarbecker** [comment]
Would be nice to get some feedback here, as this involves a lot of yet unsupported logic.

**Comment by ansgarbecker** [comment]
@Zulgrib , could you please report back if you tested that with the latest build of HeidiSQL?
I will have to leave this untested otherwise for the upcoming 10.2 release.

**Comment by ansgarbecker** [comment]
Closing this due to no feedback at all. That's frustrating.
