### ISSUE TITLE
Table comment displays [view] is not BASE TABLE

### ISSUE THREAD

**Issue by fyrye** [HeidiSQL/HeidiSQL#781]
## Steps to reproduce this issue

1. open connection in HeidiSQL as `root@localhost`
2. Selected library is `libmariadb.dll`
3. Issue the following queries using the HeidiSQL GUI:
```sql
CREATE DATABASE `foo_bar` /*!40100 COLLATE 'utf8mb4_general_ci' */;
CREATE TABLE `foo` (
	`id` INT NOT NULL,
	PRIMARY KEY (`id`)
)
COMMENT='some comment'
COLLATE='utf8mb4_general_ci'
;
CREATE ALGORITHM = UNDEFINED SQL SECURITY DEFINER VIEW `bar` AS SELECT * FROM foo; ;
```
4. Press F5 to refresh database/tables 
5. Focus database `foo_bar`
6. Witness discrepancy in comment
7. Focus "Tables" list
8. Witness discrepancy in comment
9. Focus table `foo` in basic tab
10. Witness discrepancy in comment

## Current behavior

Comment displayed as `'foo_bar.bar' is not BASE TABLE`

---

**Database Overview**

![database-overview](https://user-images.githubusercontent.com/302306/67700926-509ddb80-f985-11e9-9ec7-a9ae4d7e0b71.PNG)

**Table Overview**

![table-overview](https://user-images.githubusercontent.com/302306/67700930-5398cc00-f985-11e9-97b3-00e95074b0d5.png)

## Expected behavior

Comment to be displayed as `some comment`

## Possible solution

This appears to be a Percona 8 related issue, that did not exist in <= 5.7 and when `TABLE STATUS` or `INFORMATION_SCHEMA.TABLES` lists a view(s) prior to base tables.  Would like confirmation if this is isolated, but I have 3 separate systems with the same issue.

The query used by HeidiSQL to retrieve the comments, displays the erroneous comment
```sql
SHOW TABLE STATUS FROM `foo_bar`;
```

However issuing the following queries displays the correct comment
```sql
SHOW TABLE STATUS FROM `foo_bar` WHERE Engine IS NOT NULL;
```
```sql
SHOW TABLE STATUS WHERE Name='foo';
```
```sql
SELECT *
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME = 'foo' AND table_schema='foo_bar';
```
```sql
SELECT *
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE' AND table_schema='foo_bar';
```

## Environment

* **HeidiSQL version:** 10.2.0.5728 x64
  
* **Database system and version:** percona-server-server.x86_64-8.0.16-7.1.el7
  
* **Operating system:**  
**Host**: CentOS Linux release 7.7.1908 x64
**Client**: Windows 10 Pro x64 version 1903 build 18362.418

**Comment by ansgarbecker** [comment]
On MariaDB 10.3, the comment is displayed as it should:

![grafik](https://user-images.githubusercontent.com/7986591/67704419-63300900-f9b5-11e9-9578-3a6174536279.png)

Are you sure that `SHOW TABLE STATUS FROM foo_bar` returns that wrong comment? And `SHOW TABLE STATUS FROM foo_bar WHERE Engine IS NOT NULL` does not?

**Comment by fyrye** [comment]
@ansgarbecker Correct, see below images. It seems to only occur when a view is displayed in the list prior to a table.

![image](https://user-images.githubusercontent.com/302306/67726255-9d040e00-f9bb-11e9-9374-83768ca22917.png)



![image](https://user-images.githubusercontent.com/302306/67726305-bb6a0980-f9bb-11e9-8f86-053b153b7c8f.png)

---

The strange ones.

![image](https://user-images.githubusercontent.com/302306/67726510-71cdee80-f9bc-11e9-8874-80205e0896ab.png)

Same queries as above, but explicit table_name and table_comment columns.

![image](https://user-images.githubusercontent.com/302306/67726568-9cb84280-f9bc-11e9-8f05-e052aed30acc.png)


---

The issue appears to be isolated to Percona Server 8.
I am unable to reproduce the issue for MySQL 8 community server for el-6
Updated initial comment.

**Comment by fyrye** [comment]
Seeing as the erroneous comments are output in the `mysql` console, it does not appear need to be addressed in HeidiSQL 
Submitted a bug report to Percona https://jira.percona.com/browse/PS-6030

**Comment by ansgarbecker** [comment]
Thanks a lot for your feedback. Indeed this seems like an issue in Percona.
