### ISSUE TITLE
HeidiSQL can't reconnect without to crash

### ISSUE THREAD

**Issue by martijintro** [HeidiSQL/HeidiSQL#782]
## Steps to reproduce this issue

1. Connect with HeidiSQL to your mysql/mariadb server
2. Restart the mysql/mariadb daemon many time
3. After a few daemon restarts, HeidiSQL will crash with the error i attached

## Current behavior
Please look to point 3. above

## Expected behavior
HeidiSQL should reconnect in background without to crash, so the user will not see anything about that problem. 

## Possible solution

Reconnection in exception handling, but i don't know your sources.

## Environment

Client: Windows 10 1983, Server: Debian Linux Stretch (most current version) with backports-kernel and mariadb installed

* **10.2.0.5728** 
  
* **MariaDB 10.1** 
  
* **Debian Stretch amd64 with backports-kernel**

**Comment by martijintro** [comment]
Here is the bug report:

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/3783435/bugreport.txt)

**Comment by martijintro** [comment]
-> I also use connection compressen, maybe it's relevant..?

**Comment by ansgarbecker** [comment]
Compression is unlikely to break anything.

You say you are on HeidiSQL build 5728, but your bugreport says it's 10.2.0.5713 from Oct 11. Can you please verify this happens with the latest build as well.

**Comment by martijintro** [comment]
Hallo Ansgar

 

Ja, mir ist dann aufgefallen dass ich dazu aufgefordert wurde es erst mit der neusten Version zu versuchen. Trotzdem habe ich den Bug-Report dann abgesendet, da ich 100% davon ausgegangen bin dass das Problem auch damit besteht – was sich nachträglich auch bewahrheitet hat.

(Das Problem besteht in etwa so lange, wie ich HeidiSQL kenne, aus diesem Grund war ich mir ziemlich sicher..)

Dann werde ich es mal ohne Kompression versuchen, vielen Dank für den Tipp! 😊

 

 

Gruss, Jan



 

--

Mit freundlichen Grüssen / With kind regards

Jan Marti
Development


xaxada AG
Langfeldstrasse 24
CH-4528 Zuchwil

Phone:  +41 32 580 04 03
E-Mail:  <mailto:dev@xaxada.ch> dev@xaxada.com  
Skype:  live:dev_4909

 

Von: Ansgar Becker <notifications@github.com> 
Gesendet: Dienstag, 29. Oktober 2019 20:11
An: HeidiSQL/HeidiSQL <HeidiSQL@noreply.github.com>
Cc: martijintro <dev@intro.ch>; Author <author@noreply.github.com>
Betreff: Re: [HeidiSQL/HeidiSQL] HeidiSQL can't reconnect without to crash (#782)

 

Compression is unlikely to break anything.

You say you are on HeidiSQL build 5728, but your bugreport says it's 10.2.0.5713 from Oct 11. Can you please verify this happens with the latest build as well.

**Comment by martijintro** [comment]
Seems to work MUCH MORE better without compression!! ;-)

(In your case, i would think about to remove that compression option in HeidiSQL...?)

Thank you very much.

**Comment by martijintro** [comment]
Do you know why we can see our mail communicaton here, the mail i wrote you to?

**_"Hallo Ansgar

Ja, mir ist dann aufgefallen dass ich dazu aufgefordert wurde es erst mit der neusten Version zu versuchen. Trotzdem habe ich den Bug-Report dann abgesendet ..."_**


I don't think it's for public...!!

-> https://gitmemory.com/issue/HeidiSQL/HeidiSQL/782/547782154

**Comment by martijintro** [comment]
Reopened

**Comment by ansgarbecker** [comment]
When you reply to comment notifications via email, then you the mail goes to github.com, not directly to the commenter. If you want to delete something, you can edit your own comments here using the 3-dot menu at the right of the toolbar.

**Comment by martijintro** [comment]
Oh, that's dangerous... post was deleted now.

Sorry and thank you very much for your fast feedback!

**Comment by martijintro** [comment]
Closed
