### ISSUE TITLE
Better formatting for release notes

### ISSUE THREAD

**Issue by albertotn** [HeidiSQL/HeidiSQL#784]
## Steps to reproduce this issue

1. Step 1; run heidiSql
2. Step 2; help
3. Step 3; check update

## Current behavior

Release notes is small and hard to read, without proper formatting: 

![immagine](https://user-images.githubusercontent.com/12526457/67785254-34756980-fa6d-11e9-8596-40276a393ddb.png)

## Expected behavior

Easy to read release notes, in order to evaluate properly if I want to update heidisql or not

## Possible solution

Enlarge this window and use a bigger font with proper formatting too

## Environment

* **HeidiSQL version:** 
  
See before

**Comment by ansgarbecker** [comment]
I wonder if the "View changelog" button shouldn't be the better choice anyway:

![grafik](https://user-images.githubusercontent.com/7986591/67863646-93e28080-fb24-11e9-926b-02265239f4a4.png)

**Comment by ansgarbecker** [comment]
Perhaps I can exchange the current plain text memo control with a rich edit control, which has some basic formatting support.

**Comment by ansgarbecker** [comment]
I just learned some words of the RTF formatting language, and I must say that looks blown up for that notes box. An alternative would be a HTML box, e.g. with https://github.com/BerndGabriel/HtmlViewer , but that also looks like much overhead for such a small feature.
I think I will go with
* adding a resize grip, so the box can get larger
* probably use a fixed pitch font, like Consolas or Courier, so I can rely on the character width and format the text more readable
