### ISSUE TITLE
Make it more clear which is the selected session, e.g. for firing queries

### ISSUE THREAD

**Issue by albertotn** [HeidiSQL/HeidiSQL#785]
## Steps to reproduce this issue

1. Step 1; start program
2. Step 2; connect to a server ( localhost or remote )

## Current behavior

Current query host/connection information is not prominent

![immagine](https://user-images.githubusercontent.com/12526457/67873933-8634f700-fb34-11e9-861c-e2ad1fd3b1b0.png)

## Expected behavior

User interface could possible highlight current query target ( localhost / aws in my example).
Imagine query tabs with query on multiple connections, could be potentially very confusing to understand where a query is executed.

## Possible solution

In query tab before query name (query 1). display also connection name, so it's easy to spot where a query is executed.

## Environment

* **HeidiSQL version:** 
  

Last version, 10.2.0.5730

**Comment by ansgarbecker** [comment]
> In query tab before query name (query 1). display also connection name, so it's easy to spot where a query is executed.

Having the session name in each query tab would make the user think these tabs are bound to that session, which is not true. As soon as you navigate to another session, any query fired in any tab runs on that selected session.

What if the tree on the left would gray out unselected sessions even more than they are now?

Other ideas?

**Comment by albertotn** [comment]
> Having the session name in each query tab would make the user think these tabs are bound to that session, which is not true. As soon as you navigate to another session, any query fired in any tab runs on that selected session.

Totally missed that, my bad. I must be more cautious on this, good to know!

> What if the tree on the left would gray out unselected sessions even more than they are now?
> Other ideas?

Add an option for users to activate a "only one connection at time", so it's more hard to mess things up

**Comment by ansgarbecker** [comment]
I should probably also make the selected database and its root node bold:

![grafik](https://user-images.githubusercontent.com/7986591/67963364-bfd23480-fbfe-11e9-820b-99ccc6f0aca1.png)

**Comment by ansgarbecker** [comment]
Next build has bold text for any node in the focused database tree path.

Your idea also sounds not bad, to limit the number of simultaneous connections to 1, optionally. I just wonder if that will be used by more than a very few users.

**Comment by ansgarbecker** [comment]
With the solved above mentioned issue #1045 - I think this is solved now.
