### ISSUE TITLE
More untranslated strings

### ISSUE THREAD

**Issue by webdbase** [HeidiSQL/HeidiSQL#787]
Some more strings that can not found at transiflex..
![h-str](https://user-images.githubusercontent.com/11588031/67965762-5573c100-fc0b-11e9-82f6-5570d7975b6a.jpg)

**Comment by ansgarbecker** [comment]
I'm afraid that second line and the title caption are both part of this system dialog. The MiB and whatever byte units don't support translations, as this would break some sorting algorithm in HeidiSQL.
I wonder ... is your Windows system all in english?

**Comment by webdbase** [comment]
> I wonder ... is your Windows system all in english?
Yes, it is.

**Comment by ansgarbecker** [comment]
Then this is why these strings are in english too. You need to install your preferred Windows language pack to solve that. There is no way to translate them in the code of HeidiSQL.
