### ISSUE TITLE
crash in table view when adding new row

### ISSUE THREAD

**Issue by cengizhan** [HeidiSQL/HeidiSQL#788]
## Steps to reproduce this issue

1. Step 1; Open a database
2. Step 2; Open a table.
3. Step 3; Open data view tab.
4. Step 4: Press "Down Arrow Key" until you reach last row. Press again to create an empty row. Press down key again
5. Then I get... Program crashes

## Current behavior

I think program tries to create two new empty rows
## Expected behavior
Only one new empty row should be created.

## Environment

* **HeidiSQL version:** 
  
10.2.0.5730 (64bits)
* **Database system and version:** 
  
MySQL version 8.0.16 64bits, 
* **Operating system:** 
  
Windows 10 version 1909 64 bits

**Comment by ansgarbecker** [comment]
Should be fixed.
