### ISSUE TITLE
Hightlight is not correctly rendered in dark themes

### ISSUE THREAD

**Issue by szmcdull** [HeidiSQL/HeidiSQL#789]
## Steps to reproduce this issue

1. In Tools > Preferences, change Style Theme to `Cobalt XEMedia`;
2. Close and restart HeidiSQL to apply the theme;
3. The Session manager comes up;
4. Notice that the selected and hovered items in the session name list are not correctly highlighted.
5. The same issue applies to many other places. E.g., the table list (the left pane), all pages in the Host tab, the Database tab, column list in the Table tab;
6. The same issue applies to other dark themes, although not so noticeable (all highlights are rendered as black bars instead of the color specified by themes).

## Current behavior

![image](https://user-images.githubusercontent.com/2098590/68014177-bc57af80-fcc9-11e9-96bf-81e29e900bb3.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/2098590/68014140-a77b1c00-fcc9-11e9-8bc9-1c854a3d3849.png)

## Environment

* **HeidiSQL version:** Probably all nightly builds listed in https://www.heidisql.com/download.php (5681-5730). The stable release is fine.
  
* **Database system and version:** MySQL 5.5
  
* **Operating system:** Windows 10 1903

**Comment by ansgarbecker** [comment]
Yes, can confirm that. Probably an issue in VirtualTree, which I should update for the next release. Even other similar components like checklist-boxes have a lighter selection background:

![grafik](https://user-images.githubusercontent.com/7986591/68026372-d2587680-fcaf-11e9-993b-6798e0a47e32.png)

**Comment by ansgarbecker** [comment]
With the latest update in 1f17ed80c3e949f42411eae5fcdbc1fb34c5ac30, selected nodes have that lighter background, at least as long as they have focus:

![grafik](https://user-images.githubusercontent.com/7986591/68034005-32a3e400-fcc1-11e9-92c2-c6e3bea85c97.png)

However, it seems normal that they get black background again when they lose focus.

**Comment by ansgarbecker** [comment]
The (dark) themes seem to have that black color for unfocused selected nodes. I tried to override that color with a custom one, but that did not work, it just uses black background again:
```
VT.Colors.UnfocusedSelectionColor := clHighlight;
VT.Colors.UnfocusedColor := clHighlightText;
```

However, I suppose the dark themes seem to do this by intention. At least some of them show a different color which is then noticable enough, e.g. the Material theme.
