### ISSUE TITLE
Procedure entry point IsThreadAFiber could not be located in the dynamic link library KERNEL32.dll

### ISSUE THREAD

**Issue by Beep6581** [HeidiSQL/HeidiSQL#79]
Hey

All builds of HeidiSQL up to and including 9.5.0.5216 install and run fine in Windows XP, but as of build `HeidiSQL_9.5.0.5217_Setup.exe` clicking "OK" in the session manager leads to this crash:

```
---------------------------
heidisql.exe - Entry Point Not Found
---------------------------
The procedure entry point IsThreadAFiber could not be located in the dynamic link library KERNEL32.dll. 
---------------------------
OK   
---------------------------
```
and then
```text
Cannot find a usable libmysql.dll. Please launch heidisql.exe from the directory where you have installed it.
```

Windows XP version 2002 SP3 (running in VirtualBox).

**Comment by ansgarbecker** [comment]
Build 5216 just loads a newer libmariadb.dll and adds a fallback to loading libmysql.dll if the first one does not exist. Nothing more. So my guess is that the call to LoadLibrary('libmariadb.dll') crashes on WinXP.

If that's the case, I cannot do very much, as the newer library is required to [fix SSL bugs](https://www.heidisql.com/forum.php?t=19494).

**Comment by vaintroub** [comment]
It is possible to avoid the popups with SetErrorMode, as in https://stackoverflow.com/questions/4058303/silently-catch-windows-error-popups-when-calling-loadlibrary . (No idea how this can be used from Delphi though)

**Comment by Beep6581** [comment]
@ansgarbecker I'm familiar with MariaDB but not with `libmariadb.dll`. Is it possible that the fix you're referring to is available in a version of the dll compatible with XP? It would be great if there was a solution to keep new HeidiSQL builds working on XP, as most third-world countries still use XP, ergo we develop on XP, and it's a neat and responsive little OS when run in a virtual machine from Linux, as opposed to running say Windows 10 from a VM.

**Comment by ansgarbecker** [comment]
SetErrorMode() seems to be a Win32 function, and should be directly callable in a Delphi VCL app.

Another approach would be to deploy an older (XP-compatible) library together with the newer one, detect XP at startup, and load the older library in that case.

**Comment by Beep6581** [comment]
I'm happy to test.

**Comment by ansgarbecker** [comment]
Just added the libmysql.dll from MySQL 5.6.6 again, and a suppression of errors when trying to load the new libmariadb.dll on an old Win XP, so Heidi should proceed to loading libmysql.dll again. Also, libmysql.dll is installed via setup again, so you probably need to run the nightly built installer once again to get the old library again.

Would be nice to get some feedback if that all works, as I don't have a WinXP here for testing purposes.

**Comment by Beep6581** [comment]
@ansgarbecker I will report as soon as a build pops up!

**Comment by Beep6581** [comment]
@ansgarbecker I confirm, `HeidiSQL_9.5.0.5220_Setup.exe` installed and ran fine in Windows XP SP3. Thank you!

**Comment by ansgarbecker** [comment]
Great!
