### ISSUE TITLE
Can't save sql file on my pc (Heidi SQL)

### ISSUE THREAD

**Issue by guillaumelafrance** [HeidiSQL/HeidiSQL#790]
![Capture](https://user-images.githubusercontent.com/57274035/68059633-87505a80-fcd3-11e9-892a-5c32b0409083.PNG)
![Capture](https://user-images.githubusercontent.com/57274035/68059667-b4047200-fcd3-11e9-87a6-d35c5455d37f.PNG)

Please help me with this. I can't save a sql file on my pc. It says that I don't have the autorazition from the administrator. But when i go see in the properties in My Documents, it says that i have total control (read, write, etc.). I can just save the file in the Download file. The error appears just with sql file, not with excel, word or text file.

Thanks.

**Comment by ansgarbecker** [comment]
You should definitely update to the latest build at first, as told in the issue template.

**Comment by jjasoncool** [comment]
Try to use install version or put your portable version to C:/
