### ISSUE TITLE
Multiple table filter support

### ISSUE THREAD

**Issue by darklonely** [HeidiSQL/HeidiSQL#792]
In many cases we need to select multiple tables or databases before write some "join" sql.
Is it possible to support this?
Maybe using comma as the delimiter, like `order,user`.

**Comment by lukinhaspm** [comment]
It's a good idea, some times I need this too.
Other stuff be a list of fields and keys above the table list in tree view like this:
![image](https://user-images.githubusercontent.com/11230133/68208556-27e29b00-ffb0-11e9-9ff9-857591b99b4d.png)

**Comment by ansgarbecker** [comment]
Are you referring to the table filter above the database tree? Or the filter panel below the right panel?
Both filter boxes support regular expressions, allowing you to write complex expressions for filtering, e.g. `(order|user)`.

**Comment by darklonely** [comment]
Are you referring to the table filter above the database tree?
Yes. 

Both filter boxes support regular expressions, allowing you to write complex expressions for filtering, e.g. (order|user).
Wow, this is what i expect. thanks for the tip.
