### ISSUE TITLE
Export stored procedure has some blank lines

### ISSUE THREAD

**Issue by arikanorh** [HeidiSQL/HeidiSQL#794]
## Steps to reproduce this issue

1. Step 1; Create a procedure with parameters
2. Step 2; Then right click and export it
3. Step N; Then paste it to editor
4. Then I get blank lines after parameters

## Current behavior
There are blank lines

## Expected behavior
There shouldn't be any blank lines

## Possible solution
Remove blank lines

## Environment

* **HeidiSQL version:** 
10.2.0.5599
  
* **Database system and version:** 
  
* **Operating system:** 
Wİndows 10

  
![image](https://user-images.githubusercontent.com/17791032/68273608-ffbe6f00-0077-11ea-87df-9f9dcdbcfee1.png)

**Comment by ansgarbecker** [comment]
Can you please compare the code with what the server gives you for `SHOW CREATE PROCEDURE xyz`.

**Comment by arikanorh** [comment]
It is same with blank lines included

**Comment by ansgarbecker** [comment]
Ok, then this cannot be considered as a bug in HeidiSQL. You could remove these blank lines and store the procedure. Unless they come back again afterwards, this is all very normal.
