### ISSUE TITLE
I can't access query tab

### ISSUE THREAD

**Issue by starker-xp** [HeidiSQL/HeidiSQL#795]
## Steps to reproduce this issue

1. Step 1; Connect to database
2. Step 2; Go to 'Query' tab 

## Current behavior

I can't write query and i can't resize
https://ibb.co/TYPw2mk

## Expected behavior
 I would like write my query

## Possible solution
Add scrollbar for resizing

## Environment

* **HeidiSQL version:** 10.2.0.5738 (64 Bit)
* **Database system and version:** SQL Server With MSOLEDBSQL
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
Ok, can you please do the following to see if that fixes it:
* exit all HeidiSQL instances
* run "regedit.exe" from the start menu
* navigate to `HKEY_CURRENT_USER\Software\HeidiSQL\`
* delete the value `querymemoheight`

**Comment by starker-xp** [comment]
I have already remove all key in `HKEY_CURRENT_USER\Software\HeidiSQL\`. Problem persists.

**Comment by ansgarbecker** [comment]
You removed the _keys_ ub `...HeidiSQL\`? So you deleted your configured sessions, but not the value which is responsible for this issue. Please watch out for a _value_ called `querymemoheight`, delete it, then start HeidiSQL.

**Comment by starker-xp** [comment]
I had to perform this manipulation before opening this ticket.
I also delete the key following your request and the problem is still there.

**Comment by aktasfatih** [comment]
I am having exactly the same problem. I deleted ```querymemoheight``` from the registry, however, the problem still exists. Even though deleting increased the height of the query section, I can't see it fully. What it looks like happening in the query window starts from behind the pane at the left. Any other suggestions?
<img width="300" src="https://i.ibb.co/yQ018G2/Screenshot-2.png" />

**Comment by aktasfatih** [comment]
Removing all the values in ```...HeidiSQL``` also gives the same result as above.

**Comment by aktasfatih** [comment]
The only workaround that works is going to the compatibility settings by right-clicking the .exe file > Click on ```Change high DPI settings``` > Enable ```Override high DPI scaling behaviour``` > Select ```Application``` and the expand the window from there. It brings up everything back.

**Comment by starker-xp** [comment]
Thank's you @aktasfatih your tips working as well :P

**Comment by starker-xp** [comment]
After a restart, the problem is again present and the scaling of DPIs no longer works :/

**Comment by ansgarbecker** [comment]
High DPI is anyway unsupported in HeidiSQL currently.
Could you please just disable DPI scaling for HeidiSQL and try:
* exit all heidisql.exe instances
* start regedit and go to `HKEY_CURRENT_USER\Software\HeidiSQL`
* delete the value `queryhelperswidth` (different one than I noted above!)
* restart HeidiSQL

**Comment by aktasfatih** [comment]
Your solution also solves my problem. Thanks!

**Comment by ansgarbecker** [comment]
Thanks for your feedback!
