### ISSUE TITLE
feature request: trim input in connection manager

### ISSUE THREAD

**Issue by EmilObermayr** [HeidiSQL/HeidiSQL#797]
## Steps to reproduce this issue

1. enter new connection 
2. get hostname by copy and paste accidently with a sorounding whitespace "  test.com  "
3.  try to connect

## Current behavior

connection fails as the hostname ist resolved including the whitespace

## Expected behavior

should work like on the command shell (when using no quotes)

## Possible solution

1) trim whitespace

2) show whitespaces as centered dots

## Environment

* **HeidiSQL version:** 
Revision 5740 (Ihre: 5740)

**Comment by ansgarbecker** [comment]
Good idea. But please also look at the other fields - which one may also be trimmed, and which not?

**Comment by EmilObermayr** [comment]
As far as I know, whitespaces are not allowed in hostnames and DNS-names.
I am not so sure about usernames.
Maybe is showing whitespaces as centered dots the better option. 
Additionally there could be a yellow warning triangle with tooltip "string contains unusual characters".

Another tricky character in those strings (including the password) is the backslash \ . The backslash is evaluated differently depending on quotes and such.

So for a straight forward UX, display those dots and show the yellow triangle with tooltip in hostname and username and only the triangle in passwords.

BTW: Database-names are already effectively trimmed.

**Comment by ansgarbecker** [comment]
Text in most of the input fields on the session manager now gets trimmed when you exit the field.
