### ISSUE TITLE
Autocomplete dialog not handling UI scaling

### ISSUE THREAD

**Issue by winternet-studio** [HeidiSQL/HeidiSQL#798]
## Steps to reproduce this issue

1. Select a table
2. Go to Query tab
3. Press Ctrl-Space
4. When I use UI scaling I can hardly read the text.

![image](https://user-images.githubusercontent.com/5200270/68380130-8abe6880-014f-11ea-926b-b3e639a0f324.png)

## Environment

Using 200% UI scaling in the display settings of Windows.

* **HeidiSQL version:** 
  10.2.0.5599
* **Operating system:** 
  Windows 10

**Comment by ansgarbecker** [comment]
Please update to the latest build before reporting bugs.

I recently removed the code for scaling on high-dpi screens, so in the current builds you should see scaling done by Windows itself. A bit blurry, but text should have the right dimensions everywhere. Please test.

**Comment by winternet-studio** [comment]
Ahh, I had understood you already removed some UI scaling code in the latest release and that this was some leftover issue.

What is your plan for UI scaling - if any?

**Comment by ansgarbecker** [comment]
No further plans for native high DPI support I'm afraid. There is no other topic for which I fell onto the face so many times. Ask me once more in two years, when I forgot about it :)
