### ISSUE TITLE
Add "UTF-8 with BOM" encoding option in grid export

### ISSUE THREAD

**Issue by rvanlaak** [HeidiSQL/HeidiSQL#800]
## Steps to reproduce this issue

1. Query utf-8 dataset
2. open Export grid rows window
3. choose .csv output, utf-8 encoding and export file

## Current behavior

The .csv created by HeidiSQL does not have the Byte Object Mark. 

Opening the .csv will result in corrupt characters

## Expected behavior

HeidiSQL could add a BOM character to the .csv. Right now we open the .csv in Notepad++ to add the BOM.

![image](https://user-images.githubusercontent.com/2707563/68468835-1f40cd80-0219-11ea-91f3-7c2ca72038f9.png)

## Possible solution

* Add BOM character when exporting .csv as UTF-8
* Detect encoding

## Environment

* **HeidiSQL version:** 10.2.0.5710

**Comment by ansgarbecker** [comment]
I my experience it is highly unusual to have a BOM in utf8 files. I recall there were bug reports for HeidiSQL where I accidentally modified code in a way that it writes a BOM.

Here is one related forum thread: https://www.heidisql.com/forum.php?t=4622

> The [Unicode consortium](http://unicode.org/faq/utf_bom.html#bom10) says that in UTF-8 usage of a BOM is permitted, but not reccomended - exactly because of such mismatches

**Comment by rvanlaak** [comment]
Interesting. It is actually Microsoft Excel in our case where the missing BOM causes problems.

**Comment by ansgarbecker** [comment]
Ah, understand. I suppose you selected "Delimited text" as export output type, and imported that in Excel, right?

For Excel, I added the "Excel CSV" output, which requires the encoding to be ANSI:
![grafik](https://user-images.githubusercontent.com/7986591/69549332-6230ce00-0f99-11ea-8f16-1ec83cea6a43.png)

**Comment by rvanlaak** [comment]
Yes, we're using the Excel .csv output option 👍 Excel actually does support UTF-8 .csv files nowadays but does still need the BOM.

Would a solution be to solely add the BOM in case "Excel CSV" is used? Right now we manually have to do that using Notepad ++ every time we export grid rows.

**Comment by ansgarbecker** [comment]
Yes I could add a "UTF-8 with BOM" item in the encoding pulldown. I'm unsure why I never added that yet, probably even removed it from an earlier version.

**Comment by ansgarbecker** [comment]
Solution for #1077 now was to silently add the UTF8 BOM in Excel/utf8 mode, in the grid export. Should fix this as well.
