### ISSUE TITLE
Wrong code highlighting for incorrect mySql / MariaDB comments

### ISSUE THREAD

**Issue by WolfgangJacques** [HeidiSQL/HeidiSQL#801]
## Steps to reproduce this issue

type in query window:

    SELECT * 
    FROM tbl_schritt sch
    --WHERE sch.ID > 1000
    GROUP BY sch.Notiz

## Current behavior
Third line is greyed out to highlight this as a comment, although comments require a space after the two dashes.

## Expected behavior
Highlighting should only occur when comment is formatted correctly as "-- " so it is easier to spot the error.

## Possible solution
Fix highlighting rules

## Environment

* **HeidiSQL version:** 
10.2.0.5717
* **Database system and version:** 
MariaDB 10.54.8 on Windows
* **Operating system:** 
Windows 10 Professional 1903

**Comment by ansgarbecker** [comment]
I already fixed that some years ago, but apparently my fix got lost during an update of SynEdit:
* http://www.heidisql.com/forum.php?t=15621
* 8aa3e82cd8d2010bedcce63a22add56ae22d515d and c4e66fbb3274d0a9ac566a4c9b936507104c7a86 provided a fix
* d0a61d207a97243e6f61a418f5d6b27892cd677d also supports tab after double minus
* 6da2bd6d4363c19f06f1653d18d5a18758018612 from Dec 2017 reverted the whole fix

I will update the SynEdit sources in HeidiSQL. If that fix is not already in SynEdit itself, I will reapply my old one.

**Comment by ansgarbecker** [comment]
In MSSQL, the space after double dash is not required. See also https://www.heidisql.com/forum.php?t=20196#p23529

**Comment by ansgarbecker** [comment]
This has to be fixed in SynEdit: https://github.com/SynEdit/SynEdit/issues/42
