### ISSUE TITLE
Exporting in MSSQL is slow for large data sets

### ISSUE THREAD

**Issue by tylernathanreed** [HeidiSQL/HeidiSQL#804]
## Steps to reproduce this issue

1. Connect to MSSQL
2. Run a query that yields a large (100k+ rows) data set
3. Right Click > Export

## Current behavior

There are two slow parts to this, one I don't understand, the other is questionable, but still seems slower than it should be.

The first part is just bringing up the dialog box to select the export format. This can take 5+ minutes, and I literally have no idea why (as this isn't the part that actually exports the result into my clipboard).

The second part is the actual export, which can take just as long, if not longer (it's been 10 minutes and going for my current query, which currently has 184k rows, 7 columns, and quoted as 28.2 MiB, or 160 B per row). I understand that with large results this should take time, but 10+ minutes is excessive, and personally I'd expect this to run in under a minute or two.

## Expected behavior

I would like to see the first part (opening the dialog box) to open almost instantaneously, as there shouldn't be too much work to be done (unless something under the hood is happening that I don't understand).

I would like to see the second part have much better performance. I ran the same process in SSMS, and got the following times:

* Query Runtime: 2m 50s
* Rows: 184,997
* Export Time: 5s

## Possible solution

For the first part, I'm almost wondering if the full query is running to get a count and size of the first record (so that the dialog box and previous this information). Given that the query already executed, and you cannot export the results until the query is executed, I would imagine that it would be possible to use the existing result set to build the metrics.

For the second part, if there's chunking going on, I would advise to build a temp table and use the row number to impose a limit (since the actual "limit" keyword doesn't exist in all MSSQL versions).

## Environment

* **HeidiSQL version:** 10.2.0.5599
* **Database system and version:** Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64)

**Comment by ansgarbecker** [comment]
Reason is the size calculation for the both radio buttons, which loops through the entire grid result. There is nothing in the code which I can optimize away without breaking that functionality:

![grafik](https://user-images.githubusercontent.com/7986591/69007159-755cf180-093a-11ea-9627-dfaa615af905.png)

This can be called a nice-to-have, but it's quite useful sometimes, so I should not remove that size entirely. Perhaps I can interpolate this size by just looping over the first 1000 rows and use their average size.

More ideas?

**Comment by tylernathanreed** [comment]
@ansgarbecker 

The only real variance in size per row would be the columns of variable length (i.e. varchar, varbinary, blob, etc). You could probably find the columns that use a fixed size (i.e. integer, decimal, date, etc.) and the estimate the variable length columns based on a smaller sample size.

Another suggestion would be to use the existing results already shown in Heidi (if you're not doing this already), rather than making a new SQL query. If you're using the existing results, you could also grab a proper random sample (since this would be random-access at this point) and grab 100 or records at random (I say random here because it would be a better sample than the top X rows, as someone could be sorting by length) and use their sizes to estimate the variable length columns.

In either case, once the rows or data becomes sufficiently large, since the sizes are shown in units that indicate order of magnitude (i.e. KiB, MiB, etc.), the actual accuracy for the larger sizes isn't as important (so long as it's within the ballpark, and I'd rather over estimate than under estimate).

I know that for most of the recons I do, I export the data into a CSV, and then let the file size represent the data size, since I typically have to email these around to people. I really only use Heidi's reported selection size give me a feel for how long it's going to take to export. Of course, I'm not the only one that uses Heidi, so take my opinion with a grain of salt.

**Comment by ansgarbecker** [comment]
I think I will just use the first 1000 rows and interpolate the size of all rows in the grid, if there are more. That's not too much effort, and sufficient in most cases, with regard to the minor importance of this feature.
