### ISSUE TITLE
Error "Caption cannot be empty" after theme change on mint/wine

### ISSUE THREAD

**Issue by dpugulo** [HeidiSQL/HeidiSQL#805]
Hi,
When i change theme show this error, **exception message  : Caption cannot be empty.**

--------------------
date/time          : 2019-11-13, 12:27:33, 369ms
computer name      : gvarol-HP-250-G
user name          : gvarol <admin>
operating system   : Windows 7 x64 Service Pack 1 build 7601
system language    : Turkish
system up time     : 2 hours 20 minutes
program up time    : 15 seconds
processors         : 8x Intel(R) Pentium(R) 4 CPU 2.40GHz
physical memory    : 8846/15927 MB (free/total)
free disk space    : (C:) 69,97 GB (Z:) 69,97 GB
display mode       : 1920x1080, 32 bit
process id         : $30
allocated memory   : 41,10 MB
largest free block : 438,48 MB
executable         : heidisql32.r5747.exe
exec. date/time    : 2019-11-13 10:27
version            : 10.2.0.5747
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $ca59e356, $ac49ef80, $ac49ef80
exception number   : 2
exception class    : Exception
exception message  : Caption cannot be empty.

main thread ($31):
00631b6c heidisql32.r5747.exe Vcl.Dialogs TTaskDialogBaseButtonItem.SetCaption
7e82f52a user32.dll                       ArrangeIconicWindows
7e7f1ee7 user32.dll                       DispatchMessageW
7e8217d6 user32.dll                       GetParent
7b42bc8c KERNEL32.dll                     GlobalFindAtomW

--------------------

## Steps to reproduce this issue

1. Step 1; open program
2. Step 2; open settings
3. Step 3; change theme
4. Then I get... error

**Comment by dpugulo** [comment]
![Seçim_005](https://user-images.githubusercontent.com/55461451/68751202-3ebd6900-0612-11ea-9405-98cb9e469fe0.png)

**Comment by ansgarbecker** [comment]
Could be just a translation issue, with an empty button caption.

**Comment by ansgarbecker** [comment]
Ah, by the way, which Wine version are you running?

**Comment by ansgarbecker** [comment]
May also be caused by my solution for #719

**Comment by ansgarbecker** [comment]
Please update to the next build and try again.

**Comment by dpugulo** [comment]
Congratulations, solved with the latest version
Thanks

**Comment by ansgarbecker** [comment]
Thanks for your feedback
