### ISSUE TITLE
Show how many rows are selected in grids

### ISSUE THREAD

**Issue by kanevbg** [HeidiSQL/HeidiSQL#806]
Eg, here I have selected some rows, I'd like to see somewhere how many:

![image](https://user-images.githubusercontent.com/11477130/68938165-7826dd80-07a6-11ea-9993-cc75432c11be.png)

**Comment by ansgarbecker** [comment]
The status bar shows selected rows, plus x and y offset in grid cells:

![grafik](https://user-images.githubusercontent.com/7986591/68946812-28e7a980-07b4-11ea-986b-4a2716c713d1.png)

**Comment by ansgarbecker** [comment]
That table in your screenshot looks like `catalog_product_entity_media_gallery` from Magento :)
