### ISSUE TITLE
multi tab tables

### ISSUE THREAD

**Issue by gerendo** [HeidiSQL/HeidiSQL#808]
open tables in multi tab

**Comment by ansgarbecker** [comment]
Do you think that is enough information for a feature request?

**Comment by gerendo** [comment]
sorry for not explaining what i meant ...  i just love your app because the simple and way of using functions of MYSQL without other complications in the others app ... but 
this feature i think is very important to make the user able to open a lot of table in and process what he need in every table individually 
![image](https://user-images.githubusercontent.com/6280674/69902045-d69cb000-1391-11ea-8d37-fbf8f84fb300.png)
in my humble opinion sir if you ask  .. first : you could move the data tab from above to inside the table tab , second : work on the feature i mention above 
my apologies again for not explain sir
