### ISSUE TITLE
Triple-click and quadraple click, 5x click

### ISSUE THREAD

**Issue by halmai** [HeidiSQL/HeidiSQL#81]
## Expected behavior

In the SQL query editor, if I click one then the cursor is positioned and if I doubcle-click then one word is selected. I would like to take it forward:
- a triple click should select the current line, 
- a quadruple click should select the current query 
- a quintuple (5x times) click should select the content of the whole editor

## Current behavior

More than duouble clicks are treated as if it were some double clicks plus potentially a single one.

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. Enter some longer queries into the query editor, like:
```
SELECT *
    FROM t1
    WHERE id < 5;

SELECT *
    FROM t1
    WHERE id > 99;
``` 
2. triple-click on the number "99"
3. nothing will be selected. 

By contrast, I would like to get the whole line selected
```
[    WHERE id > 99;]
```

### Context

* HeidiSQL version: build 5201
* Database system + version: PostgreSQL 10.1, compiled by Visual C++ build 1800, 64-bit
* Operating system: Win7

**Comment by ansgarbecker** [comment]
That cannot be done directly in HeidiSQL, as the editor is a separately developed component called [SynEdit](https://github.com/SynEdit/SynEdit). Please report that in their tracker.

**Comment by halmai** [comment]
I asked the feature from them: https://github.com/SynEdit/SynEdit/issues/85

Please read it and add your comments if you have any. :) Thanks.
