### ISSUE TITLE
new design for 10.x versions THIS IS NOT GOOD

### ISSUE THREAD

**Issue by isam-os** [HeidiSQL/HeidiSQL#810]
please return old design !!! 10.x omg this is not acceptable !!! 

<!--

**Comment by leeoniya** [comment]
then use something else.

**Comment by rentalhost** [comment]
Please make constructive criticism. Your post is too vague, so I'm closing.

**Comment by isam-os** [comment]
9 to 10 disihgn chnged ??? YES!!!! what constructive u need yet ???

**Comment by rentalhost** [comment]
What is the impact from 9 to 10 on the usage? 

Just remeber: you are still free to use version 9. https://www.heidisql.com/download.php then click to "Previous installers".
