### ISSUE TITLE
Installer fails, when users home directory is on a network share

### ISSUE THREAD

**Issue by chrisblech** [HeidiSQL/HeidiSQL#811]
## Steps to reproduce this issue

1. My Windows users default home directory was moved to a network share
2. I'm trying to install HeidiSQL via default installer Package

## Current behavior

Error during install: "Failed to expand shell folder constant userdocs"

## Possible solution

First hit on Google: https://www.unifiedremote.com/tutorials/how-to-fix-failed-to-expand-shell-folder-constant-userdocs

## Environment

My Windows users default home directory was moved to a network share

* **HeidiSQL version:** 
  10.2.0.5599
* **Operating system:** 
  Windows 10 Pro

**Comment by ansgarbecker** [comment]
Could it be the administrator account which executes the installer does not have access to your network drive? At least that was the case for me in a similar situation.

**Comment by chrisblech** [comment]
My account is an administrator account, so I'm only asked if I want to grant admin privileges to the installer (yes/no), I'm not asked to provide other credentials.

**Comment by ansgarbecker** [comment]
My question went towards whether your administrator account has access to your network share. To test that, you should run a net use comnand before running the installer:

    net use /persistent:no X: \\yourserver\share yourpassword /user:yourdomain\yourusername

**Comment by chrisblech** [comment]
This command reported an error: 

> Mehrfache Verbindungen zu einem Server oder einer freigegebenen Ressource von demselben Benutzer unter Verwendung mehrerer Benutzernamen sind nicht zulässig. Trennen Sie alle früheren Verbindungen und versuchen Sie es erneut.

I also opened the share to allow all read/write requests to public (without credentials), and the error (while installing) persists unfortunately.

**Comment by pmbranco** [comment]
Same here -  same error on windows 10 64 bits. I am an administrator of the machine too. Was going to test it.... failed installation with same error message: "Failed to expand shell folder constant userdocs"

**Comment by ansgarbecker** [comment]
It could be important whether the home directory is redirected to a network drive, which may cause this issue. It should be an url like `\\server\RedirectedUserFolders\SOME-USER\My Documents`.

**Comment by ansgarbecker** [comment]
Is this still an issue with v12.0?

**Comment by Buster-de** [comment]
Why does the installer wants to write to "My Documents" in the first place? How is this supposed to work in classroom environments?
If access to "My Documents" is used to update some examples for snippets, then they should be saved in a directory accessible to all users. Updating them in the administrator's documents folder wont help other users. Does the installer overwrite files in "My Documents"? What if the user customized the snippet?

**Comment by jifb** [comment]
@Buster-de When I search for "Documents" in this github repo, I essentially get two uses for the Documents folder: 
* Initial Dir of file selector (read-only)
* Folder which contains HeidiSQL\Snippets. (See also issue #1751 which is the reason why I came here)

**Comment by ansgarbecker** [comment]
Next installer has an option for the snippets, showing the used path, and which can be unchecked by the user:

![grafik](https://user-images.githubusercontent.com/7986591/213555715-47ceec9b-22c3-4d93-a0f3-80164f6b7287.png)
