### ISSUE TITLE
Network Types on Build 5757

### ISSUE THREAD

**Issue by rwilliams** [HeidiSQL/HeidiSQL#812]
## Steps to reproduce this issue

1. Download Nightly Build
2. Go to Session Manager
3. Only MySQL/MariaDB options are available

## Current behavior
Session manager
![image](https://user-images.githubusercontent.com/29144/69442304-309dd580-0d01-11ea-8bec-c1e7b79e4713.png)

## Expected behavior

From build 5599
![image](https://user-images.githubusercontent.com/29144/69442167-f03e5780-0d00-11ea-9421-efdd5cd7bd78.png)

## Environment

* **HeidiSQL version:** 
5757
  
* **Database system and version:**
PGSQL Debian 11.5-3.pgdg90+1
  
* **Operating system:** 
Windows 10 64 build 19028. DB is running under WSL2 in a docker container.

**Comment by rwilliams** [comment]
It looks like just the labels are messed up connections work fine.

**Comment by ansgarbecker** [comment]
Was caused by 9b23baec85639524b3b6dbde600e33c3322560bd for #802

**Comment by ansgarbecker** [comment]
... and is fixed in the next build.
