### ISSUE TITLE
virustotal reports 2 malwares

### ISSUE THREAD

**Issue by sINusBob** [HeidiSQL/HeidiSQL#813]
1. www.virustotal.com;
2. Uploaded file: \HeidiSQL_10.2_64_Portable.zip\heidisql.exe;
3. Then I get...
- W64.HfsAutoB.
- Trojan.Agentb.dxl

**Comment by ansgarbecker** [comment]
Hm, I'm quite sure there is no virus in it. There were quite a few false positive detections in the past. The current build also does not show any of them: https://www.virustotal.com/gui/url/9bdf50e3ba593045c7db9dd9b971302f06d0fcd7ff194ad1f8ada3f6293ea54d/detection

**Comment by sINusBob** [comment]
Thank you very much for your quick return. Really I believe about possible false positive, however, I thought it would be appropriate to report on it. And thank you so much for developing HeidiSQL

**Comment by ansgarbecker** [comment]
Yes, of course it's worth to report them, for security reasons. Might be a true positive some day.
