### ISSUE TITLE
wrong IP address dislayed when incorrect password provided

### ISSUE THREAD

**Issue by jbhatami** [HeidiSQL/HeidiSQL#814]
## Steps to reproduce this issue

1. Step 1; Create a new connection (I used Maria/MySQL)
2. Step 2; Provide a valid hostname or IP address but an invalid password
3. Step 3; click Connect

## Current behavior
The wrong IP address is displayed in the error message. This was especially confusing because I was providing a hostname that is configured in my hosts file. After checking the file, I tested with an actual IP address and see the same behavior.

![image](https://user-images.githubusercontent.com/36491644/69492441-b764c680-0e57-11ea-9629-4a1b0136e7b0.png)

## Expected behavior
The correct IP address should be displayed.

## Possible solution

NA

## Environment
Win10 64 bit

* **HeidiSQL version:** 
10.2.0.5599
  
* **Database system and version:** 
MySQL-Server 5.7
  
* **Operating system:** 
Ubuntu 18.04

**Comment by ansgarbecker** [comment]
The error message is generated on the server, HeidiSQL just displays it on your computer. The IP address in the message is _your_ one, not the one of the server.
