### ISSUE TITLE
syntax error when opening in windows sql query created in linux

### ISSUE THREAD

**Issue by 3pm** [HeidiSQL/HeidiSQL#816]
1. Write query SELECT CURRENT_TIMESTAMP in Pgadmin SQL editor in linux OS. Save it as file.
2. Open saved query in Windows OS with HeidiSQL (10.2.0.5760). 
4. Try execute it - will receive (SQL error 102): Incorrect syntax near "".
5. Delete first symbol- will execute fine.

**Comment by ansgarbecker** [comment]
Sounds like an encoding issue, the file may have a BOM at the very beginning. Please ensure you load the file in the same encoding in which you stored it.

You need to follow the issue template. As stated, such issues will normally be closed.

**Comment by ansgarbecker** [comment]
No feedback since 3 weeks. I'm closing this now. I can reopen when you retried with the right encoding selected in the file-open-dialog.

**Comment by 3pm** [comment]
Not working with manual either. Tried all provided encodings One by one.

Ansgar Becker <notifications@github.com> (šajā datumā: Ot, 2019. gada 17.
dec. 13:18) rakstīja:

**Comment by ansgarbecker** [comment]
Please update to v10.3 and retry.

**Comment by 3pm** [comment]
A checked on ver. 10.3.0.5771

Ansgar Becker <notifications@github.com> (šajā datumā: Ot, 2019. gada 17.
dec. 16:54) rakstīja:
