### ISSUE TITLE
No warning on pressing the red X button in text field editor

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#817]
## Steps to reproduce this issue

1. In a table Data tab double click on some text cell.
2. Click on the appeared cell edit button.
3. Make some edits.
4. Suppose you are hurrying and while clicking green Tick button carelessly click the little red X button to the left.
5. So, all the edits were lost without any warnings.

## Current behavior

Unexpected impossibility to recover edits of a text cell on single click the X button.

## Expected behavior

At least some warning message in case there were any changes.

## Possible solution

Make those buttons (Save and Abandon) apart from each other. Or make a warning message.

## Environment

* **HeidiSQL version:** 
  
nightly build 10.2.0.5762 64bit
* **Database system and version:** 
  
MariaDB 10.4
* **Operating system:** 
Windows 10 Pro (1809)

**Comment by ansgarbecker** [comment]
I get a message dialog here when I click the red X:

![grafik](https://user-images.githubusercontent.com/7986591/69859632-ce127f80-1294-11ea-8fce-7f73f5e293ec.png)

Please ensure you are on the latest HeidiSQL build, as told in the issue template, and report back if the problem persists for you.

**Comment by AlexLunyov** [comment]
Confirm the latest updates. The problem persists. I have never seen the warning shown in the attachment before, though I have been using HeidiSQL for several years (great program).

**Comment by AlexLunyov** [comment]
I should add some info: I do receive that warning on pressing standard Windows close X button in the upper right corner.

**Comment by ansgarbecker** [comment]
Oh I was thinking you meant the red X on the top right of the window :)

In that case I have to say that pressing this button intentionally does not show a confirmation, whereas I am suddenly unsure if that's right, now that you're asking for one. We'll leave this open, perhaps some input from others could help here.

**Comment by AlexLunyov** [comment]
OK, let's wait. Thank you!

**Comment by WesleyM77** [comment]
I think this makes sense, but if you were to make the confirmation on that red X, would you also need to add a confirmation on the green check? Also, should the red X default to the "No" option for confirming changes instead?

**Comment by AlexLunyov** [comment]
Wesley, thank you for the comment. It seems it could be dangerous to set No default option. We still have a possibility to cancel our changes later pressing Esc on the cell before committing.
Having this after-edit committing functionality I suppose there is no actual need for red X and green V buttons... It may be useful to make one Exit button instead. IMHO.

**Comment by ansgarbecker** [comment]
I just modified that cancel button so it shows an apply-modifications confirm dialog. Just makes sense:

![grafik](https://user-images.githubusercontent.com/7986591/163783355-a62b82df-6191-44fc-b5ff-5a450d9138dc.png)
