### ISSUE TITLE
UI bugs on scaled monitors

### ISSUE THREAD

**Issue by coderovich** [HeidiSQL/HeidiSQL#818]
There is some UI ugliness on large monitors with 150% scale.

1) Ultra large font in header
2) Ultra small "close" and "question" buttons.

![Clip2net_191201165019](https://user-images.githubusercontent.com/11044347/69912357-e59b6500-145a-11ea-9ced-93ad6aeec16d.png)

**Comment by ansgarbecker** [comment]
Please use the latest build before reporting bugs. And don't delete the whole issue template.

Please update and report back.

**Comment by ansgarbecker** [comment]
HeidiSQL is not DPI aware any more so I suppose this was done with an older build.
