### ISSUE TITLE
Find Text tool currently does not support regular expression's case changing replace

### ISSUE THREAD

**Issue by denchat** [HeidiSQL/HeidiSQL#819]
## Steps to reproduce this issue

1. Suppose we have 
    `1234hello1234`
2. Want to change into
    `1234HELLO1234`
3. match with
    `([\d]{4})([a-z]{5})([\d]{4})`
4. replace with
    `$1\U$2$3`

## Current behavior

result:  `1234Uhello1234
`
## Expected behavior

result: `1234HELLO1234`
https://regex101.com/r/0h6YEG/1

## Possible solution

I'm not sure whether changing current regex back-end is needed.
The webste below states that Delphi doesn't support case changing context `\U$match`.
https://www.regular-expressions.info/refreplacecase.html
Instead Delphi supports `\U0` - `\U99` but it doesn't work either.

## Environment

* **HeidiSQL version:** 
  
   
   Rev. 10.2.0.5766
   Commit: [097a902]

**Comment by ansgarbecker** [comment]
HeidiSQL makes use of https://github.com/SynEdit/SynEdit/blob/master/Source/SynRegExpr.pas , not the Delphi own one, as that was introduced later. But I'm afraid the SynEdit implementation does not support that either. Even there is no such a feature request in their tracker, but you could file one.

Probably I need a more extensive regex backend in HeidiSQL, but until now I had very few problems only here, so I'm unsure if it's worth, and which one should I take.

**Comment by denchat** [comment]
[`SynRegExpr.pas`](https://github.com/SynEdit/SynEdit/blob/master/Source/SynRegExpr.pas) is appearently [`TRegExp`](https://regex.sorokin.engineer/en/latest/tregexpr.html#substitute), which is a work of Andrey Sorokin
https://github.com/andgineer/TRegExpr/blob/master/src/RegExpr.pas

I think `TRegExp` does support case replacement

> `'\U$1\\r'` transforms into `'<Match[1] in uppercase>\r'`

https://regex.sorokin.engineer/en/latest/tregexpr.html#substitute
https://github.com/andgineer/TRegExpr/blob/master/docs/tregexpr.rst

I notice `SynsRegExpr.pas` is a few hundred lines shorter than original `RegExpr.pas`.
Moreover `RegExpr.pas` seems have an LGPL option also

Well, I will try file an issue at `SynEdit` and refered back to this then.

**Comment by ansgarbecker** [comment]
I just had a quick look and saw `TRegExpr` is actively developped, which I was not aware of. I could easily exchange the library in Heidi's back, it should still be compatible. But after the v10.3 release. And we'll also wait what the SynEdit guys say there.

**Comment by ansgarbecker** [comment]
I just realize that I can apply the newer `TRegExpr` for most things in HeidiSQL, but not for the search/replace dialog for searching in SQL code:
![grafik](https://user-images.githubusercontent.com/7986591/79042901-d512ac80-7bfb-11ea-90e0-e8510bd8911d.png)
In the latter case SynEdit's internal TRegExpr lib gets used. Perhaps we can file an issue there to get that updated too.

**Comment by ansgarbecker** [comment]
I have just forked the SynEdit code into https://github.com/HeidiSQL/SynEdit, so I can update the SynRegExpr unit and probably post that as a pull request later in the original repo.

**Comment by ansgarbecker** [comment]
Just pushed the above mentioned update into the forked SynEdit project, and overtook the same code into HeidiSQL. Please check the next build - I already successfully tested :)

![regexpr-replace-uppercase](https://user-images.githubusercontent.com/7986591/79116420-b857af80-7d88-11ea-9b3b-9dacaa2bea48.gif)

**Comment by ansgarbecker** [comment]
The hints in the tooltip of the "Regular expression" checkbox now moved to a dropdown menu right besides the search and replace buttons.
