### ISSUE TITLE
Copyable heidisql version number is needed

### ISSUE THREAD

**Issue by halmai** [HeidiSQL/HeidiSQL#82]
## Expected behavior

The version number from the About dialog should be copyable. 

## Current behavior

I cannot select the version number and build info (and hence can't even copy it to the clipboard). 

### Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. step Go to the Help -> About HeidiSQL... dialog
2. step Try to select the version number
3. you cannot. :)

### Context

If I make a bug report then I have to copy it manually which is cumbersome. :)

* HeidiSQL version: v9.5.0.5.5201
* Database system + version: irrelevant
* Operating system: Win7

**Comment by ansgarbecker** [comment]
I just added a right-click menu on the various labels there, with a "Copy" item on it.
