### ISSUE TITLE
Clicking too fast on folder will open connection instead of collapse/expand

### ISSUE THREAD

**Issue by pauljura** [HeidiSQL/HeidiSQL#820]
## Steps to reproduce this issue

1. Step 1; Open a new window
2. Step 2; Have a connection selected
3. Step 3; Expand / collapse a folder quickly

## Current behavior

Highlighted connection is opened, as if I had double clicked on it

## Expected behavior

Folder should expand / collapse without opening connection

## Possible solution

Check if the click was on folder or connection

## Environment

* **HeidiSQL version:** 
10.2.0.5766 (64 bit)
* **Operating system:** 
Windows 10 64 bit
![image](https://user-images.githubusercontent.com/42629973/69935602-1d6ce000-1521-11ea-8fa1-1074f18989ec.png)

**Comment by ansgarbecker** [comment]
Can't reproduce this issue here. I am clicking like a beast on the folder symbol, on the open/close symbol left besides it, and on the name of the folder. But HeidiSQL still just expands or collapses the folder. I will double-check this at work, on another pc.

**Comment by pauljura** [comment]
Hi, I made a little gif that will hopefully explain:

1. If you have a connection selected but you click on the folder name, it will de-select the connection and the problem doesn't occur.
2. Without a connection selected, clicking on the > symbol works as expected.
3. But if you have a connection selected and double click on the > symbol then the selected connection gets opened.

![heidi](https://user-images.githubusercontent.com/42629973/70096359-a47d9d80-1672-11ea-8127-03b40736d647.gif)

**Comment by rentalhost** [comment]
Yep, I could reproduce using your last method now.

**Comment by ansgarbecker** [comment]
Yes, I overread one has to select a connection first, not a folder. I can also reproduce that here now.

**Comment by ansgarbecker** [comment]
Commit b333de2913b5032ebb95f38b2df32e1de9e35a41 updates the VirtualTrees to their latest v7.3. But I'm afraid that doesn't fix this issue.

**Comment by ansgarbecker** [comment]
Found a fix for it, and just pushed it. Double click on the expand/collapse icons should no longer open a session.
