### ISSUE TITLE
Detect Changes to Open Files - Change from Constantly to On Focus Only

### ISSUE THREAD

**Issue by aSystemOverload** [HeidiSQL/HeidiSQL#821]
## Steps to reproduce this issue

1. Open existing (or SAVE new) SQL Statement in Heidi
2. Open same file in other editor such as Notepad++
3. Make changes in other editor and save those changes
4. Make additional changes in editor and save those (3 or 4+ times)
5. Return to Heidi.  There will be a prompt "Changes Detected - Reload?" for each time you saved the file in the other editor.

## Current behavior

 "Changes Detected - Reload?" prompt spawned for each change saved in other editor.

## Expected behavior

Do not attempt to check for changes to loaded files until Heidi has focus.

## Possible solution

Unknown - Insufficient technical knowledge.

## Environment

Win 10

* **HeidiSQL version:** 
 Heidi v10.2.0.5689
* **Database system and version:** 
Not Relevant to Issue
* **Operating system:** 
Win 10

**Comment by ansgarbecker** [comment]
Next build will prevent multiple prompts for one loaded file.
