### ISSUE TITLE
Incomplete SQL to DB engine

### ISSUE THREAD

**Issue by Ejsstiil** [HeidiSQL/HeidiSQL#823]
## Steps to reproduce this issue

1. Step 1; Create a table:
```sql
CREATE TABLE ref (
	`fee` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL,
	`original_fee` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL,
	`deletable` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1'
);
```
2. Step 2; Paste this TRIGGER SQL to Query tab:
```as
CREATE TRIGGER `ref_bu` BEFORE UPDATE ON `ref` FOR EACH ROW IF NEW.fee != NEW.original_fee THEN
	SET NEW.deletable = 0; END IF;
```
3. Step 3; Execute

## Current behavior

**SQL error 1064**
Console output:
```as
CREATE TRIGGER `ref_bu` BEFORE UPDATE ON `ref` FOR EACH ROW IF NEW.fee != NEW.original_fee THEN
	SET NEW.deletable = 0;
/* Affected rows: 0  Found rows: 0  Warnings: 1  Duration for 1 of 3 queries: 0,000 sec. */
```
Incomplete SQL was sent to the DB. Because the last statement is missing:
```console
END IF;
```

## Expected behavior

No error; code should be executed at once but splitting queries might occurs here.

## Possible solution

Do not split queries by ';' before they are sent to DB .
Try execute this in native console:
```sql
DELIMITER ;
CREATE TABLE ref (
	`fee` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL,
	`original_fee` DECIMAL(10,2) UNSIGNED NULL DEFAULT NULL,
	`deletable` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1'
);

DROP TRIGGER IF EXISTS `ref_bu`;
CREATE TRIGGER `ref_bu` BEFORE UPDATE ON `ref` FOR EACH ROW IF NEW.fee != NEW.original_fee THEN
	SET NEW.deletable = 0; END IF;
DELIMITER ;
```
It will work normally but not in Heidi.
## Environment

* **HeidiSQL version: 10.2.0.5767 (64bit)** 
  
* **Database system and version: MariaDB 5.5.56**

**Comment by ansgarbecker** [comment]
This is very normal, you cannot execute compound statements in the query tabs without setting the query delimiter:
![grafik](https://user-images.githubusercontent.com/7986591/70261098-04b73100-1792-11ea-92ac-2b91cb7caf8f.png)
Then, set the delimiter to something unique, which is not semicolon, e.g. //:
![grafik](https://user-images.githubusercontent.com/7986591/70261152-21ebff80-1792-11ea-93e0-d8962646623d.png)
That tells HeidiSQL to split queries where you have that // , not at semicolon. The query should execute as one in the end.
