### ISSUE TITLE
heidi window cut

### ISSUE THREAD

**Issue by ptofladif** [HeidiSQL/HeidiSQL#824]
FYI

when we have two monitor in expand mode and the windows main bar is on side, if maximize the heidi window will cut the size of the main bar.
![Capturar](https://user-images.githubusercontent.com/10712577/70710612-72ee7d00-1cd7-11ea-8bfc-bc77e36b2b30.PNG)

Thank you!

**Comment by ansgarbecker** [comment]
Duplicate of #495
