### ISSUE TITLE
Add session search filter

### ISSUE THREAD

**Issue by Anyqax** [HeidiSQL/HeidiSQL#826]
What I would love to see is a session search filter above the session panel which filters on input all displayed sessions (folders and connections, when a matching entry is "found", all parent folders would need to be shown as well)

**Comment by ansgarbecker** [comment]
This is it now:

![grafik](https://user-images.githubusercontent.com/7986591/70869150-3bf2c280-1f88-11ea-8c9e-17ee34bcf30b.png)
