### ISSUE TITLE
Applying multicolumn filter issue

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#829]
## Steps to reproduce this issue

1. Open a table and write in the multicolumn filter some text to find it in the table.
2. Press Enter, the results are then showed in the list, it's OK.
3. Change the table and try to apply the same filter text to find. It seems something happens but the resulting list is not changed.

## Current behavior

To apply the filter again I have to change the text in the filter box: type something and then bring my initial text back. Then press Enter to apply the filter.

## Expected behavior

The filter should be ready to apply when the table is changed.

## Environment

* **HeidiSQL version:** 
, last nightly HeidiSQL version (10.3.0.5783).
  
* **Database system and version:** 
  
MariaDB 10.4
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
Can confirm. The text in the box on the right stays when switching tables, but no filter is created through click on "Apply filter". I guess the most intuitive would be to generate the filter text on "apply" click in that case, right before applying it on the grid view.

**Comment by AlexLunyov** [comment]
Looking forward to the fix!

**Comment by ansgarbecker** [comment]
Stumbled over this old report, which I fixed in 2009: https://sourceforge.net/p/heidisql/tickets/987/

This was still broken in case there is an old filter text. Now fixed for the next build.
