### ISSUE TITLE
Error finding libmariadb.dll or libmysql-6.1dll libraries with Windows Store version

### ISSUE THREAD

**Issue by jsn-m** [HeidiSQL/HeidiSQL#830]
## Steps to reproduce this issue
1. Install HeidiSQL from Windows Store (v10.0.3.5771);
2. Create a new session in the Connection Manager;
3. Select the libmariadb.dll or libmysql-6.1.dll library;
4. Error message: 'Library libmariadb.dll could not be loaded. Please select a different one. Internal error 126: The specified module could not be found'.

## Current behavior

Error finding libmariadb.dll or libmysql-6.1dll libraries. I have checked that they are in fact in the application install directory in  C:\Program Files\WindowsApps\...AnsgarBeckerSoftware...\

## Expected behavior

Expected no error when selecting a library other than libmysql.dll from Connection Manager.

## Environment

Fresh install of Windows. I did hack at C:\Users\User\AppData\Local\Packages\...AnsgarBeckerSoftware...\ to try restore config files, before I opened HeidiSQL for the first time.
EDIT: I did uninstall and reinstall the app from the Store to try resolve the problem.

* **HeidiSQL version:** 
Windows Store 10.0.3.5771
* **Operating system:** 
Windows 10 1903

**Comment by ansgarbecker** [comment]
I just got a mail from another user who reported the same problem, and fixed it by installing vc runtime libraries from https://aka.ms/vs/16/release/vc_redist.x64.exe . Could you please do the same and report back if that works then?

**Comment by vfandrea** [comment]
I had the same issue, and I confirm that installing VC Runtime fixes the problem

**Comment by ansgarbecker** [comment]
Thanks for your feedback!

**Comment by jsn-m** [comment]
Also can confirm that VC Runtime does fix the problem.

**Comment by cemichele** [comment]
Same for me. I've installed **HeidiSQL 11.1.0.6116** on my new laptop (Windows 10 20H2) and I had an error saying: "_Library libmariadb.dll could not be loaded. Please select a different one._". VC Runtime fixed it. Thanks
