### ISSUE TITLE
Generating ER diagram of database structure

### ISSUE THREAD

**Issue by xiaoxing598** [HeidiSQL/HeidiSQL#832]
The ER diagram allows us to better understand the design intent of the database table structure. I hope that it can be automatically generated. This exists in similar tools, but I hope that this feature will also be included in this tool. I look forward to this.

**Comment by ansgarbecker** [comment]
What about the issue template?

This is a complex request. Would be good if you post some more input here, probably there is some half ready solution out there, which can be integrated in HeidiSQL.

**Comment by xiaoxing598** [comment]
I hope my thoughts have been expressed clearly, my English level is not good, please forgive me!

**Comment by ansgarbecker** [comment]
Such a diagram feature needs much more details than one or two sentences in a feature request. Your english is perfect, compared to many other reporters here. Please help out here, find examples, think about ways to integrate them into HeidiSQL.

**Comment by xiaoxing598** [comment]
I'm very sorry, I'm just a web developer, so I don't know about the development of desktop applications. I don't think I can provide specific help myself, because this field is new to me. I hope other colleagues can suggest For specific implementation suggestions, I will thank him.

**Comment by ansgarbecker** [comment]
You requested an ER diagram, but you don't know what you actually want to do with it and how it should work? Sorry, in that case I will close this issue. Please report back if you have more details about your request.

**Comment by surfmuggle** [comment]
I totally understand that this closed for now. 

Lucidchart has options to create a chart online. I created [a tiny sample](https://www.lucidchart.com/invitations/accept/50b8db12-3621-4650-acac-3daf96a63795) : 

![ER Diagramm](https://user-images.githubusercontent.com/1271555/75898291-27f98700-5e3a-11ea-9d41-e51dc2ea2adc.png)


I am aware that this is not enough but it may be a starting point to discuss this further

**Comment by ansgarbecker** [comment]
I don't think such a graphical mega feature will get done by me. But probably we can use the API of some online diagram tool. I can make HeidiSQL pass the structure over to that tool. I see quite some security problems when doing that, but it's just an idea.

**Comment by madox81** [comment]
@ansgarbecker You are totally right its a mega feature, so I think if the structure can be converted to plantUML code , more clear converting sql into plantuml code then the user copy this code and pasted on an online plantuml server to have the diagram. please kindly refer to https://github.com/bmrussell/sql2puml as an example, Thank you and my apology for for any inconvenience
