### ISSUE TITLE
Blurry UI on 4K (High DPI) display on Windows 10

### ISSUE THREAD

**Issue by brhaka** [HeidiSQL/HeidiSQL#833]
This is happening for some releases, so I decided to open this issue because it's really annoying and I want to contribute with HeidiSQL community.

## Steps to reproduce this issue

HeidiSQL must be opened on any High DPI display (I just have a Windows 10 computer, so I can't test on older versions).

## Current behavior

HeidiSQL UI is blurry.

## Expected behavior

I expected a clean and defined UI, as it was on older versions.

## Possible solution

In most cases, this can be fixed by scaling the UI based on the DPI.

## Environment

This is happening at a 4K 28" display.

* **HeidiSQL version:** 
10.3.0.5786
  
* **Operating system:** 
Windows 10 Pro 10.0.18363

**Comment by ansgarbecker** [comment]
I gave up high DPI support some months ago, after finding out this causes too many new issues, some of them in conjunction with themes. You can still activate dpi awareness in HeidiSQL though: https://github.com/HeidiSQL/HeidiSQL/issues/825#issuecomment-565506299

**Comment by leeoniya** [comment]
> You can still activate dpi awareness in HeidiSQL though

sadly, it resets on every update, since the exe is replaced :(

i wonder if there's a way for the updter to read and set this metadata automatically on the new exe?
