### ISSUE TITLE
Gray background field is too small

### ISSUE THREAD

**Issue by kpeters58** [HeidiSQL/HeidiSQL#834]
![mariabug](https://user-images.githubusercontent.com/54696028/71565508-2d1a0e80-2a64-11ea-906f-47c987cbdf51.png)

Windows 10

**Comment by rentalhost** [comment]
The gray background size is relative to the greatest value. In case, 7.9 Mib is 43.2% of 18.3 Mib (the greatest value, as from "public" database). So the background size should be 43.2% of the column size too.

**Comment by ansgarbecker** [comment]
I suppose this is a misunderstanding.

I just measured the pixel width in Paint.net, and recalculated the value - looks correct to me.
