### ISSUE TITLE
Number of result rows doesn't show well on short width monitor

### ISSUE THREAD

**Issue by boily** [HeidiSQL/HeidiSQL#836]
## Steps to reproduce this issue

1. Reduce the Heidisql app window to about 1100 px width.
2. Create a database and table with long names (long names are optionals: it depends on the viewing app width);
3. Show and filter data;
4. The result number shows : "database_name.table_name: xxx rows total (approximately), yyy rows match to filter" but the text goes on 2 lines and we can't see the number of matched rows.

## Current behavior

![immagine](https://user-images.githubusercontent.com/16082159/71658250-9be8b780-2d43-11ea-822e-621f392e1c57.png)

## Expected behavior

![immagine](https://user-images.githubusercontent.com/16082159/71658979-2205fd80-2d46-11ea-9775-b61e77a0ebff.png)

## Possible solution

I see different possible solutions:
1. add an overflow vertical scroll bar (prefered and maybe easiest solution)
2. prepend the number of matched rowsat the bigining of the text.
3. show the number also somewhere else in the GUI (maybe status bar)
4. increase the text box height
## Environment

* **HeidiSQL version:** 
  
v.10.3.0.5804

**Comment by ansgarbecker** [comment]
I think a vertical scrollbar would be ugly. What about displaying a tooltip to that label, which displays when the mouse hovers over it?

**Comment by ansgarbecker** [comment]
Ah, and I had another idea, which does not work, however: using the "Small Fonts" Windows font on that label. But I failed when searching for that font in my Windows 10 installation, so others won't have it too.

**Comment by ansgarbecker** [comment]
Oh i just found that font, must have overseen it. So here's a comparison (above: Tahoma 8pt, below: Small Fonts 6pt)

![grafik](https://user-images.githubusercontent.com/7986591/73126259-c16a8900-3fb0-11ea-87c3-ce4fea560af8.png)

**Comment by boily** [comment]
Hi Ansgar. Thanks again for your execellent work.
I think this font is too small and would not resolve the problem in extreme situation (long database and table names and tiny width display).
A tooltip on that label on mouse over would to be prefered. It could be also shown in the status bar on mouse over.
I would suggest also to remove the word "approximately" (people should know) or abreviate it to "approx."
Regards
