### ISSUE TITLE
Table name `UnknownTable` in Export grid rows

### ISSUE THREAD

**Issue by preart81** [HeidiSQL/HeidiSQL#837]
## Steps to reproduce this issue

1. Connect to database;
2. Select table;
3. Goto Data tab and select any row;
4. Tools --> Export grid rows;
5. Copy to clipboard; SQL REPLACEs; 
6. Then I get: REPLACE INTO `UnknownTable` - the table name is `UnknownTable` instead of the real name

## Current behavior

The table name in generated SQL code is `UnknownTable`

## Expected behavior

The table name must match the selected table. 

* **HeidiSQL version:** 
   10.3.0.5804 (64 Bit) 
* **Database system and version:** 
 MySQL 5.5.44

**Comment by ansgarbecker** [comment]
Oh good that you report this now. I already suspected an error in my recent commit 7fc55c5da7a4a2e0e95e916add48828711c1107d . Will check that.

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.
