### ISSUE TITLE
BUG: virtual columns lost when copying a table

### ISSUE THREAD

**Issue by vonp** [HeidiSQL/HeidiSQL#84]
## Expected behavior
copy

## Current behavior
error 1906

## Failure information (for bugs)
should fix like done for #53: do not try to insert generated field data

### Steps to reproduce

select copy table from context menu

## sys
mariadb version 10.2.12-1 on centos 2.6.32-696.18.7
heidi version 9.5.0.r5220 on win7/64

**Comment by lukinhaspm** [comment]
I reproduce this and it's not ok.

@ansgarbecker as follow the steps to reproduce:

1 - Create table with virtual columns
2 - Put some data
3 - Right click on the table, and go to New->Table Copy

The new table will be created, but when Heidi try to put data, they put all colunms.

Thanks

**Comment by rentalhost** [comment]
Actually, the `Virtual` column on `Table Editor` create an `ALTER TABLE` SQL but it don't include the `VIRTUAL` code. So when you save, the `VIRTUAL` is not applied to table. Maybe it be the root of the problem. Or then it is a new issue (if you can confirm that, please, tell me to I fill a new ticket).

**Comment by alesvaupotic** [comment]
Also, Ansgar, while you're at the generated columns, please adjust for the MySQL syntax of STORED instead of PERSISTENT from MariaDB. Percona also uses this keyword. Thanks!

Excerpt from https://dev.mysql.com/doc/refman/5.7/en/create-table-generated-columns.html

> 
> Generated column definitions have this syntax:
> ```
> col_name data_type [GENERATED ALWAYS] AS (expression)
>   [VIRTUAL | STORED] [NOT NULL | NULL]
>   [UNIQUE [KEY]] [[PRIMARY] KEY]
>   [COMMENT 'string']
> ```
