### ISSUE TITLE
option "None" for background color is missing

### ISSUE THREAD

**Issue by dim-d** [HeidiSQL/HeidiSQL#840]
heidisql 10.2.0.5599
menu->tools->preferences->Sql tab->Background dropbox
option "None" for background color is missing
Once a background color is set there is no way to reapply no background color.
(in the portable installation folder, editing the portable-settings.txt and placing value 536870911 as background restores the "none" color)
 but 
It should be added the "None" color option to the background dropbox

**Comment by ansgarbecker** [comment]
Confirmed. Although `cbIncludeNone` is activated: https://github.com/HeidiSQL/HeidiSQL/blob/0d0c6df599cb534444930426962c8c3ce0bd8fbb/source/options.dfm#L741

**Comment by ansgarbecker** [comment]
Got it - there is a funny property "NoneColorColor" in that color dropdown component, which was set to black, but needs "clNone" to be shown.
