### ISSUE TITLE
Schema columns become too wide

### ISSUE THREAD

**Issue by uaoleg** [HeidiSQL/HeidiSQL#841]
## Steps to reproduce this issue

1. Create a new table or open an existing one
2. Go to table's schema tab

## Current behavior

Column width of the table "Columns" is too wide:

![image](https://user-images.githubusercontent.com/1773775/71818570-10985a80-3092-11ea-9762-15c385faf458.png)

## Expected behavior

Column width should be much more narrow

## Possible solution

Fit column width by the most long value length (the same as for data table)

## Environment

* **HeidiSQL version:** 
10.3.0.5771
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
What about resizing via mouse?

**Comment by ansgarbecker** [comment]
I just noticed you are using a high-dpi setting, which you must applied manually. That wrong column width was one of the issues for which I removed support for high-dpi settings. You need to switch back to "system scaling" to fix that.

**Comment by uaoleg** [comment]
@ansgarbecker could you please suggest what should be changed?

![image](https://user-images.githubusercontent.com/1773775/71902257-59bbdd80-316a-11ea-8fc2-d8bff83abf42.png)

**Comment by uaoleg** [comment]
@ansgarbecker you were right, thank you! Here what I've done and that fixed the issue

![image](https://user-images.githubusercontent.com/1773775/71902636-2af23700-316b-11ea-9963-ac4a919966a6.png)

**Comment by ansgarbecker** [comment]
Super :)
