### ISSUE TITLE
Error choosing table fields with aliases

### ISSUE THREAD

**Issue by vjulca** [HeidiSQL/HeidiSQL#848]
## Steps to reproduce this issue

1. Step 1;

I create the sentence with * to show me all the fields.

SELECT * FROM ADUANAS.REPORTES A WHERE A.CODIGO = '2269' ORDER BY A.CODIGO DESC, A.NROCAMP ASC;

2. Step 2;

I use the alias of the table to choose only the fields I need.

SELECT A. FROM ADUANAS.REPORTES A WHERE A.CODIGO = '2269' ORDER BY A.CODIGO DESC, A.NROCAMP ASC;

## Current behavior

When writing the point I get the following error:

"An error ocurred in the application."

## Expected behavior

When writing the point, the fields in the table should be shown, as has always happened.

## Possible solution

I have no idea.

## Environment

* **HeidiSQL version:** 

10.3.0.5812

* **Database system and version:** 

MySQL 5.6.38

* **Operating system:** 

Windows 10 x64 build 18363

**Comment by ansgarbecker** [comment]
Should be fixed. Though I now need to create some cache for recurring SQL queries I suppose.

**Comment by vjulca** [comment]
I have done some tests and it is working fine. Thank you.
