### ISSUE TITLE
portable version 10.03 not working with postgre

### ISSUE THREAD

**Issue by dsultanr** [HeidiSQL/HeidiSQL#850]
## Steps to reproduce this issue

1. Step 1;
download portable version https://www.heidisql.com/downloads/releases/HeidiSQL_10.3_64_Portable.zip
2. Step 2;
create postgresql connection in session manager
3. Then I get...

## Current behavior
empty library select box 

## Expected behavior
libpq.dll in the library select box

## Possible solution
download full version https://www.heidisql.com/installers/HeidiSQL_10.3.0.5771_Setup.exe
install it
copy libpq.dll from %program files%\heidi to portable location

## Environment
windows 10 64 bit
vcredist installed

**Comment by ansgarbecker** [comment]
I just downloade the portable from your link, and got this in the zip file:

![grafik](https://user-images.githubusercontent.com/7986591/72372379-79bd4500-3706-11ea-865f-1a1b17e7874d.png)

**Comment by dsultanr** [comment]
Yep. It is there but it is not working. When I try to create postgre session - there is no option to choose that DLL. 

![image](https://user-images.githubusercontent.com/1683476/72373041-8ea2d400-3718-11ea-86b3-e4388619fd55.png)

**Comment by dsultanr** [comment]
replacing the DLL from "full install" version solves the issue

**Comment by ansgarbecker** [comment]
Ah, no, I now see you just need to save your session once before HeidiSQL shows the right libraries in the dropdown.

**Comment by dsultanr** [comment]
just saving doesnt help. saving and reopening whole Heidi helped. Thanks

**Comment by ansgarbecker** [comment]
021d78d135ccaeb967400d55acd9ce1402946eed was the fix for this.
