### ISSUE TITLE
Not possible by double click to select Cyrillic words in editor

### ISSUE THREAD

**Issue by 116581658** [HeidiSQL/HeidiSQL#851]
## Steps to reproduce this issue

1. Navigate to "Tools=>Preferences=>SQL (tab)";
2. Set the "Editor fort" = "Consolas";
3. In the editor write some Cyrillic words: "АБВГДЕЖ" ;
4. Try to select the word by double clicking on it;

## Current behavior

Not possible to select the word. Nothing happens.

## Expected behavior

As with Latin words to be possible to select the whole word.

## Environment
Windows 10

* **HeidiSQL version:**  10.3.0.5819 (32 bit)

**Comment by ansgarbecker** [comment]
This was already a report in the SynEdit project for this issue: https://github.com/SynEdit/SynEdit/issues/111 . I just applied the proposed solution (activated `SYN_UNISCRIBE`) but that still did not work. You could mention your sample word in a comment there.
I will close this issue as I cannot do much here.
