### ISSUE TITLE
Painfully slow table navigation after recent update(s)

### ISSUE THREAD

**Issue by WesleyM77** [HeidiSQL/HeidiSQL#852]
## Steps to reproduce this issue

1. Connect to db (local or remote)
2. Click on relatively small table.
3. Wait a while (UI freezes, title bar says "Not Responding", then table loads after a bit).
4. Click on data tab, Repeat step 3. 

## Current behavior

Step 3 from above.

## Expected behavior

Snappier table loads like before. 

## Environment

* **HeidiSQL version:** 
  10.3.0.5819
* **Database system and version:** 
  MySQL
* **Operating system:** 
  Windows 10

## Bug Report
Got a crash during step 3 at one point. 
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4059907/bugreport.txt)

**Comment by ansgarbecker** [comment]
Related: https://www.heidisql.com/forum.php?t=35380

**Comment by ansgarbecker** [comment]
I just separated the join for foreign key retrieval into two separate queries, which seem to fire faster now.

But I need to invent some caching mechanism, as these many queries are fired several times for one table click.

**Comment by WesleyM77** [comment]
This definitely brought back the snappiness of the table/data loads. Hopefully you can figure something out to get your desired result without sacrificing performance.

**Comment by lukinhaspm** [comment]
its good, BUT, definitely slower than before ...
I think you should:
Once a database has been loaded, the information_schema tables will be written to Heidi's cache, and every time you use that cache, if you create or modify the structure, you should ask to update the cache, just like SQL Management Studio does - very very fast

**Comment by lukinhaspm** [comment]
I saw when I use a remote connection, Heidi does several times the same query, maybe they don`t wait the result?
![image](https://user-images.githubusercontent.com/11230133/72542958-bc486400-3863-11ea-8d0c-71a6180635b6.png)

**Comment by ansgarbecker** [comment]
I just pushed a cache solution now, reusing the internally collected columns, keys and foreign keys. That should minimize the internal queries. Please recheck with the next build.

**Comment by lukinhaspm** [comment]
Now its VERY fast! More than before! Thanks a lot!

**Comment by WesleyM77** [comment]
Just updated and it seems just as fast as before! Thank you very much!
