### ISSUE TITLE
Data in wrong columns only in Data tab

### ISSUE THREAD

**Issue by DavideDA** [HeidiSQL/HeidiSQL#854]
## Steps to reproduce this issue

1. Connect to local/remote DB;
2. Click on schema name and expand tables list;
3. Click on a specific table;
4. Click on **Data** tab

## Current behavior

Data are in wrong columns.
If I fetch those data using a query, data are in the correct columns

## Expected behavior

Data are in correct columns even if I watch them in **Data** tab

## Environment

* **HeidiSQL version:** 
  
Heidi 10.3.0.5821 (64 Bit)
* **Database system and version:** 
  
MySql Server 8.0. Both Windows and Linux versions present this issue
* **Operating system:** 
  
Windows 10.0 (1909)

**Comment by ansgarbecker** [comment]
Must be related to MySQL 8 in some way. On MariaDB I see no issue.

**Comment by DavideDA** [comment]
Another symptom: other tables on other DBs have columns shown in an unusual order.
I use HeidiSQL since 2017, I have never seen those issues. Maybe some regression in last minor/patch versions?
The problem occurs both with HeidiSQL libmysql.dll, libmysql-6.1.dll and libmariadb.dll

**Comment by ansgarbecker** [comment]
The wrong sorting was due to the unordered appearance of columns in `IS.columns`, most likely only in MySQL 8 but probably on others too. Just fixed that by adding an `ORDER BY` clause.
