### ISSUE TITLE
Error using database tree with SQL Server 

### ISSUE THREAD

**Issue by ug-code** [HeidiSQL/HeidiSQL#855]
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4069542/bugreport.txt)

## Steps to reproduce this issue

1. Step 1;Select database
2. Step 2; Select table
3. Then I get this error : invalid object name 'information_schema.COLUMNS'

![image](https://user-images.githubusercontent.com/17679067/72497750-70cf8f00-383e-11ea-9671-0dd5e59f9f07.png)

## Current behavior
Step 3 from above.

## Possible solution
it should be uppercase (INFORMATION_SCHEMA)
this query should be as follows:
![image](https://user-images.githubusercontent.com/17679067/72498397-3e269600-3840-11ea-8d08-6e380a9c2a84.png)

## Environment
HeidiSQL version:10.3.0.5824
Database system and version:SQL Server 2017,
Operating system:windows 10

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
Thanks for the hint. I still had "information_schema" hardcoded in ~50 places in the code. The next build has a unified name here, uppercase on MSSQL and lowercase on all others.
Please test and report back.

**Comment by ug-code** [comment]
I have done test  and it is working fine. Thank you.
