### ISSUE TITLE
MYSQL table primary key to be automatic UNIQUE INDEX

### ISSUE THREAD

**Issue by oguzsaka** [HeidiSQL/HeidiSQL#856]
Firts: Sorry for some type errors, English is not my main language.

does not accept my edit and again to be UNIQUE INDEX,All primary keys in my database were UNIQUE INDEX, This happened after the last 3 updates

Version : 10.3.0.5828

**Comment by ansgarbecker** [comment]
Ok, then please post
* the result of `SHOW CREATE TABLE mytable`
* and your MySQL server version

**Comment by oguzsaka** [comment]
CREATE TABLE `region` (
  `regid` int(11) NOT NULL AUTO_INCREMENT,
  `Sütun 4` char(50) DEFAULT '-',
  PRIMARY KEY (`regid`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=latin1
![wiw](https://user-images.githubusercontent.com/7862838/72616366-d52a4580-3947-11ea-83d3-05a6358dbe08.PNG)

**Comment by oguzsaka** [comment]
MYSQL VERSİON 5.7
![MYS](https://user-images.githubusercontent.com/7862838/72616969-0bb49000-3949-11ea-8d1c-29eb7b44f095.PNG)

**Comment by ansgarbecker** [comment]
> MYSQL VERSİON 5.7

Your screenshot says you are on MariaDB 10.3.16 ? What's the correct version?

I created your table here two times. The first one was the code from you above, showing me a primary key in the table designer:
![grafik](https://user-images.githubusercontent.com/7986591/72618577-b3c35c80-393b-11ea-9464-bf3cfcc5fce6.png)

The second table got a unique key via "create table", and then the table designer displays a unique key. So, I see no problem here:
![grafik](https://user-images.githubusercontent.com/7986591/72618544-9db59c00-393b-11ea-82fb-62afd401dca1.png)

But probably we're really on MySQL 5.7?

**Comment by oguzsaka** [comment]
previously used as the primary key in the table designer

HEİDİSQL TAB Create Code click
CREATE TABLE `region` (
	`regid` INT(11) NOT NULL AUTO_INCREMENT,
	Sütun 4` CHAR(50) NULL DEFAULT '-' COLLATE 'latin1_swedish_ci',
	**UNIQUE INDEX `PRIMARY` (`regid`) USING BTREE**
)
COLLATE='latin1_swedish_ci'
;
they are the same thing but , Why does UNIQUE INDEX not show as PRIMARY KEY instead of `PRIMARY`

**Comment by ansgarbecker** [comment]
Ok, you just _named_ a unique key "PRIMARY". That is still a unique key, not a primary key, which is a different thing.
I'm confused about the bug here. Was that now a misunderstanding or..? Where exactly do you see a bug, and which server version is it - MySQL 5.7 or MariaDB 10.3?

**Comment by oguzsaka** [comment]
![72618577-b3c35c80-393b-11ea-9464-bf3cfcc5fce6](https://user-images.githubusercontent.com/7862838/72642129-b98d6200-397c-11ea-9afe-367be5afe628.png)

should always be displayed as above. requesting indexs should be able to change the tab type now it cannot be changed as UNIQUE INDEX even if I update it as the primary key heidisql

I'm using mysql 5.7 but when I use heidisql when connecting to heidisql he sees it as mariadb heidisql was fast but some different events developed after the last updates you did not used to

**Comment by oguzsaka** [comment]
navicat mysql is not the primary key I am not having such a problem but heidisql is changing its auto UNIQUE INDEX

**Comment by oguzsaka** [comment]
![72618577-b3c35c80-393b-11ea-9464-bf3cfcc5fce6](https://user-images.githubusercontent.com/7862838/72643171-2275d980-397f-11ea-8138-8ad8db74b1af.png)
I want this

**Comment by oguzsaka** [comment]
![wiw](https://user-images.githubusercontent.com/7862838/72643217-3ae5f400-397f-11ea-95a8-0a3e1181b03d.PNG)

not this

**Comment by ansgarbecker** [comment]
I understand your primary keys are wrongly detected as unique keys in HeidiSQL.
I just cannot reproduce that here, neither on MariaDB 10.3 nor on MySQL 5.7 - both just tested:
![grafik](https://user-images.githubusercontent.com/7986591/72660402-7f987c00-39cd-11ea-9009-086ef96e0c96.png)
Probably there is some more stuff to examine, for example the SQL modes you have set. You could post the result of `SELECT @@sql_mode` here.

**Comment by ansgarbecker** [comment]
Could someone else please also try to reproduce that?

**Comment by oguzsaka** [comment]
![fff](https://user-images.githubusercontent.com/7862838/72668150-bc4b8e00-3a34-11ea-9f0a-47d429e29e56.PNG)

**Comment by ansgarbecker** [comment]
Same report here: https://www.heidisql.com/forum.php?t=35431
I am still unable to reproduce this.

**Comment by ansgarbecker** [comment]
Please post the result of the following query:

```
SHOW INDEXES FROM `region`;
```

**Comment by oguzsaka** [comment]
![CFFF](https://user-images.githubusercontent.com/7862838/72751943-fe5e0680-3bd1-11ea-8c3c-950e130e168e.PNG)

**Comment by oguzsaka** [comment]
I think there is a problem with the Heidisql indexs detection engine

**Comment by oguzsaka** [comment]
I'm in the latest version. actual . Version 9 does not have such a problem

**Comment by oguzsaka** [comment]
NewKey.Name := KeyQuery.Col('Key_name');
can you show the incoming values ​​by testing. because it might perceive the incoming value differently

**Comment by ansgarbecker** [comment]
Good idea. Next build will have a debug output in the lower log panel, saying `NewKey.Name="PRIMARY"`. As this is a debug message, you need to activate these in preferences:

* rightclick log panel, and click "Logging preferences":
![grafik](https://user-images.githubusercontent.com/7986591/72829886-e47afd00-3c7f-11ea-94d7-3fe31cd14df7.png)
* activate debug messages:
![grafik](https://user-images.githubusercontent.com/7986591/72829933-f65ca000-3c7f-11ea-98d7-1e1c6bc5e7d7.png)
* apply options, and watch out for such a line in the log panel (you may need to scroll up a bit after clicking a table):
![grafik](https://user-images.githubusercontent.com/7986591/72830023-22782100-3c80-11ea-8721-3eff6f87a9c1.png)

**Comment by oguzsaka** [comment]
`/* Detected column type for Temporary: VARCHAR */
/* Ping server ... */
SHOW FUNCTION STATUS WHERE `Db`='portal';
/* Result #1 fetched. */
/* Detected column type for Db: VARCHAR */
/* Detected column type for Name: VARCHAR */
/* Detected column type for Type: VARCHAR */
/* Detected column type for Definer: VARCHAR */
/* Detected column type for Modified: DATETIME */
/* Detected column type for Created: DATETIME */
/* Detected column type for Security_type: VARCHAR */
/* Detected column type for Comment: TEXT */
/* Detected column type for character_set_client: VARCHAR */
/* Detected column type for collation_connection: VARCHAR */
/* Detected column type for Database Collation: VARCHAR */
/* Ping server ... */
SHOW PROCEDURE STATUS WHERE `Db`='portal';
/* Result #1 fetched. */
/* Detected column type for Db: VARCHAR */
/* Detected column type for Name: VARCHAR */
/* Detected column type for Type: VARCHAR */
/* Detected column type for Definer: VARCHAR */
/* Detected column type for Modified: DATETIME */
/* Detected column type for Created: DATETIME */
/* Detected column type for Security_type: VARCHAR */
/* Detected column type for Comment: TEXT */
/* Detected column type for character_set_client: VARCHAR */
/* Detected column type for collation_connection: VARCHAR */
/* Detected column type for Database Collation: VARCHAR */
/* Ping server ... */
SHOW TRIGGERS FROM `portal`;
/* Result #1 fetched. */
/* Detected column type for Trigger: VARCHAR */
/* Detected column type for Event: VARCHAR */
/* Detected column type for Table: VARCHAR */
/* Detected column type for Statement: TEXT */
/* Detected column type for Timing: VARCHAR */
/* Detected column type for Created: DATETIME */
/* Detected column type for sql_mode: VARCHAR */
/* Detected column type for Definer: VARCHAR */
/* Detected column type for character_set_client: VARCHAR */
/* Detected column type for collation_connection: VARCHAR */
/* Detected column type for Database Collation: VARCHAR */
/* Fetching objects in information_schema db ... */
/* Ping server ... */
/* Ping server ... */
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='information_schema';
/* Result #1 fetched. */
/* Detected column type for DEFAULT_COLLATION_NAME: VARCHAR */
/* Ping server ... */
SHOW TABLE STATUS FROM `information_schema`;
/* Result #1 fetched. */
/* Detected column type for Name: VARCHAR */
/* Detected column type for Engine: VARCHAR */
/* Detected column type for Version: BIGINT */
/* Detected column type for Row_format: VARCHAR */
/* Detected column type for Rows: BIGINT */
/* Detected column type for Avg_row_length: BIGINT */
/* Detected column type for Data_length: BIGINT */
/* Detected column type for Max_data_length: BIGINT */
/* Detected column type for Index_length: BIGINT */
/* Detected column type for Data_free: BIGINT */
/* Detected column type for Auto_increment: BIGINT */
/* Detected column type for Create_time: DATETIME */
/* Detected column type for Update_time: DATETIME */
/* Detected column type for Check_time: DATETIME */
/* Detected column type for Collation: VARCHAR */
/* Detected column type for Checksum: BIGINT */
/* Detected column type for Create_options: VARCHAR */
/* Detected column type for Comment: VARCHAR */
/* Detected column type for Max_index_length: BIGINT */
/* Detected column type for Temporary: VARCHAR */
/* Ping server ... */
SHOW FUNCTION STATUS WHERE `Db`='information_schema';
/* Result #1 fetched. */
/* Detected column type for Db: VARCHAR */
/* Detected column type for Name: VARCHAR */
/* Detected column type for Type: VARCHAR */
/* Detected column type for Definer: VARCHAR */
/* Detected column type for Modified: DATETIME */
/* Detected column type for Created: DATETIME */
/* Detected column type for Security_type: VARCHAR */
/* Detected column type for Comment: TEXT */
/* Detected column type for character_set_client: VARCHAR */
/* Detected column type for collation_connection: VARCHAR */
/* Detected column type for Database Collation: VARCHAR */
/* Ping server ... */
SHOW PROCEDURE STATUS WHERE `Db`='information_schema';
/* Result #1 fetched. */
/* Detected column type for Db: VARCHAR */
/* Detected column type for Name: VARCHAR */
/* Detected column type for Type: VARCHAR */
/* Detected column type for Definer: VARCHAR */
/* Detected column type for Modified: DATETIME */
/* Detected column type for Created: DATETIME */
/* Detected column type for Security_type: VARCHAR */
/* Detected column type for Comment: TEXT */
/* Detected column type for character_set_client: VARCHAR */
/* Detected column type for collation_connection: VARCHAR */
/* Detected column type for Database Collation: VARCHAR */
/* Ping server ... */
SHOW TRIGGERS FROM `information_schema`;
/* Result #1 fetched. */
/* Detected column type for Trigger: VARCHAR */
/* Detected column type for Event: VARCHAR */
/* Detected column type for Table: VARCHAR */
/* Detected column type for Statement: TEXT */
/* Detected column type for Timing: VARCHAR */
/* Detected column type for Created: DATETIME */
/* Detected column type for sql_mode: VARCHAR */
/* Detected column type for Definer: VARCHAR */
/* Detected column type for character_set_client: VARCHAR */
/* Detected column type for collation_connection: VARCHAR */
/* Detected column type for Database Collation: VARCHAR */
/* Fetching objects in information_schema db ... */
/* Ping server ... */
/* Ping server ... */
SHOW EVENTS FROM `information_schema`;
/* Result #1 fetched. */
/* Detected column type for Db: VARCHAR */
/* Detected column type for Name: VARCHAR */
/* Detected column type for Definer: VARCHAR */
/* Detected column type for Time zone: VARCHAR */
/* Detected column type for Type: VARCHAR */
/* Detected column type for Execute at: DATETIME */
/* Detected column type for Interval value: VARCHAR */
/* Detected column type for Interval field: VARCHAR */
/* Detected column type for Starts: DATETIME */
/* Detected column type for Ends: DATETIME */
/* Detected column type for Status: VARCHAR */
/* Detected column type for Originator: BIGINT */
/* Detected column type for character_set_client: VARCHAR */
/* Detected column type for collation_connection: VARCHAR */
/* Detected column type for Database Collation: VARCHAR */
/* Ping server ... */
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='portal';
/* Result #1 fetched. */
/* Detected column type for EVENT_CATALOG: VARCHAR */
/* Detected column type for EVENT_SCHEMA: VARCHAR */
/* Detected column type for EVENT_NAME: VARCHAR */
/* Detected column type for DEFINER: VARCHAR */
/* Detected column type for TIME_ZONE: VARCHAR */
/* Detected column type for EVENT_BODY: VARCHAR */
/* Detected column type for EVENT_DEFINITION: TEXT */
/* Detected column type for EVENT_TYPE: VARCHAR */
/* Detected column type for EXECUTE_AT: DATETIME */
/* Detected column type for INTERVAL_VALUE: VARCHAR */
/* Detected column type for INTERVAL_FIELD: VARCHAR */
/* Detected column type for SQL_MODE: VARCHAR */
/* Detected column type for STARTS: DATETIME */
/* Detected column type for ENDS: DATETIME */
/* Detected column type for STATUS: VARCHAR */
/* Detected column type for ON_COMPLETION: VARCHAR */
/* Detected column type for CREATED: DATETIME */
/* Detected column type for LAST_ALTERED: DATETIME */
/* Detected column type for LAST_EXECUTED: DATETIME */
/* Detected column type for EVENT_COMMENT: VARCHAR */
/* Detected column type for ORIGINATOR: BIGINT */
/* Detected column type for CHARACTER_SET_CLIENT: VARCHAR */
/* Detected column type for COLLATION_CONNECTION: VARCHAR */
/* Detected column type for DATABASE_COLLATION: VARCHAR */
/* Detected column type for Db: VARCHAR */
/* Detected column type for Name: VARCHAR */
/* editDatabaseTableFilterChange */
/* editDatabaseTableFilterChange */
/* Erişim engellendi */
/* Restoring tab setup from C:\Users\oguzs\AppData\Roaming\HeidiSQL\tabs.ini */
/* Loading file "C:\Users\oguzs\AppData\Roaming\HeidiSQL\Backups\query-tab-2020-01-17_16-32-58-442.sql" (260 B) into query tab #1 ... */
/* ListTablesBeforePaint */
/* Saving backup file to "C:\Users\oguzs\AppData\Roaming\HeidiSQL\Backups\query-tab-2020-01-17_16-32-58-442.sql"... */
/* SetActiveDBObj(region) */
/* DBtreeFocusChanged, Node level: 2, FTreeRefreshInProgress: 0 */
/* SetDatabase(portal), FDatabase: portal */
/* Getting columns from database cache for `portal`.`region` */
/* Getting fresh columns for `portal`.`region` */
/* Fetching objects in information_schema db ... */
/* Ping server ... */
/* Fetching objects in information_schema db ... */
/* Ping server ... */
/* Fetching objects in information_schema db ... */
/* Ping server ... */
/* Ping server ... */
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='portal' AND TABLE_NAME='region' ORDER BY ORDINAL_POSITION;
/* Result #1 fetched. */
/* Detected column type for TABLE_CATALOG: VARCHAR */
/* Detected column type for TABLE_SCHEMA: VARCHAR */
/* Detected column type for TABLE_NAME: VARCHAR */
/* Detected column type for COLUMN_NAME: VARCHAR */
/* Detected column type for ORDINAL_POSITION: BIGINT */
/* Detected column type for COLUMN_DEFAULT: TEXT */
/* Detected column type for IS_NULLABLE: VARCHAR */
/* Detected column type for DATA_TYPE: VARCHAR */
/* Detected column type for CHARACTER_MAXIMUM_LENGTH: BIGINT */
/* Detected column type for CHARACTER_OCTET_LENGTH: BIGINT */
/* Detected column type for NUMERIC_PRECISION: BIGINT */
/* Detected column type for NUMERIC_SCALE: BIGINT */
/* Detected column type for DATETIME_PRECISION: BIGINT */
/* Detected column type for CHARACTER_SET_NAME: VARCHAR */
/* Detected column type for COLLATION_NAME: VARCHAR */
/* Detected column type for COLUMN_TYPE: TEXT */
/* Detected column type for COLUMN_KEY: VARCHAR */
/* Detected column type for EXTRA: VARCHAR */
/* Detected column type for PRIVILEGES: VARCHAR */
/* Detected column type for COLUMN_COMMENT: VARCHAR */
/* Detected column type for IS_GENERATED: VARCHAR */
/* Detected column type for GENERATION_EXPRESSION: TEXT */
/* GetDatatypeByName: "int(11)" : int */
/* GetDatatypeByName: "varchar(50)" : varchar */
/* GetDatatypeByName: "varchar(50)" : varchar */
/* GetDatatypeByName: "char(50)" : char */
/* GetDatatypeByName: "char(50)" : char */
/* Getting keys from database cache for `portal`.`region` */
/* Getting fresh keys for `portal`.`region` */
/* Ping server ... */
SHOW INDEXES FROM `region` FROM `portal`;
/* Result #1 fetched. */
/* Detected column type for Table: VARCHAR */
/* Detected column type for Non_unique: BIGINT */
/* Detected column type for Key_name: VARCHAR */
/* Detected column type for Seq_in_index: BIGINT */
/* Detected column type for Column_name: VARCHAR */
/* Detected column type for Collation: VARCHAR */
/* Detected column type for Cardinality: BIGINT */
/* Detected column type for Sub_part: BIGINT */
/* Detected column type for Packed: VARCHAR */
/* Detected column type for Null: VARCHAR */
/* Detected column type for Index_type: VARCHAR */
/* Detected column type for Comment: VARCHAR */
/* Detected column type for Index_comment: VARCHAR */
/* Getting foreign keys from database cache for `portal`.`region` */
/* Getting fresh foreign keys for `portal`.`region` */
/* Ping server ... */
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='portal'   AND TABLE_NAME='region'   AND REFERENCED_TABLE_NAME IS NOT NULL;
/* Result #1 fetched. */
/* Detected column type for CONSTRAINT_CATALOG: VARCHAR */
/* Detected column type for CONSTRAINT_SCHEMA: VARCHAR */
/* Detected column type for CONSTRAINT_NAME: VARCHAR */
/* Detected column type for UNIQUE_CONSTRAINT_CATALOG: VARCHAR */
/* Detected column type for UNIQUE_CONSTRAINT_SCHEMA: VARCHAR */
/* Detected column type for UNIQUE_CONSTRAINT_NAME: VARCHAR */
/* Detected column type for MATCH_OPTION: VARCHAR */
/* Detected column type for UPDATE_RULE: VARCHAR */
/* Detected column type for DELETE_RULE: VARCHAR */
/* Detected column type for TABLE_NAME: VARCHAR */
/* Detected column type for REFERENCED_TABLE_NAME: VARCHAR */
/* Ping server ... */
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   CONSTRAINT_SCHEMA='portal'   AND TABLE_NAME='region'   AND REFERENCED_TABLE_NAME IS NOT NULL;
/* Result #1 fetched. */
/* Detected column type for CONSTRAINT_CATALOG: VARCHAR */
/* Detected column type for CONSTRAINT_SCHEMA: VARCHAR */
/* Detected column type for CONSTRAINT_NAME: VARCHAR */
/* Detected column type for TABLE_CATALOG: VARCHAR */
/* Detected column type for TABLE_SCHEMA: VARCHAR */
/* Detected column type for TABLE_NAME: VARCHAR */
/* Detected column type for COLUMN_NAME: VARCHAR */
/* Detected column type for ORDINAL_POSITION: BIGINT */
/* Detected column type for POSITION_IN_UNIQUE_CONSTRAINT: BIGINT */
/* Detected column type for REFERENCED_TABLE_SCHEMA: VARCHAR */
/* Detected column type for REFERENCED_TABLE_NAME: VARCHAR */
/* Detected column type for REFERENCED_COLUMN_NAME: VARCHAR */
/* Setting up TSynMemo "SynMemoQuery" */
/* Setting up TSynMemo "SynMemoFilter" */
/* Setting up TSynMemo "SynMemoProcessView" */
/* Setting up TSynMemo "SynMemoSQLLog" */
/* Setting up TSynMemo "SynMemoPartitions" */
/* Setting up TSynMemo "SynMemoCREATEcode" */
/* Setting up TSynMemo "SynMemoALTERcode" */
/* TfrmTableEditor.Init, using object "region" */
/* Fetching list of table engines ... */
/* Ping server ... */
/* Ping server ... */
SHOW ENGINES;
/* Result #1 fetched. */
/* Detected column type for Engine: VARCHAR */
/* Detected column type for Support: VARCHAR */
/* Detected column type for Comment: VARCHAR */
/* Detected column type for Transactions: VARCHAR */
/* Detected column type for XA: VARCHAR */
/* Detected column type for Savepoints: VARCHAR */
/* Fetching list of collations ... */
/* Ping server ... */
/* Ping server ... */
SHOW COLLATION;
/* Result #1 fetched. */
/* Detected column type for Collation: VARCHAR */
/* Detected column type for Charset: VARCHAR */
/* Detected column type for Id: BIGINT */
/* Detected column type for Default: VARCHAR */
/* Detected column type for Compiled: VARCHAR */
/* Detected column type for Sortlen: BIGINT */
/* Ping server ... */
SHOW CREATE TABLE `portal`.`region`;
/* Result #1 fetched. */
/* Detected column type for Table: VARCHAR */
/* Detected column type for Create Table: VARCHAR */`

**Comment by oguzsaka** [comment]
[000005.log](https://github.com/HeidiSQL/HeidiSQL/files/4094041/000005.log)

**Comment by ansgarbecker** [comment]
Even in your log I see now _NewKey.Name="PRIMARY"_, and I'm sure in lowercase that's "primary". I'm lost here.

**Comment by oguzsaka** [comment]
ALTER TABLE `companies_sectors`
	DROP INDEX `PRIMARY`,
	ADD PRIMARY KEY (`csecid`) USING BTREE;
![11](https://user-images.githubusercontent.com/7862838/73273868-b05e8980-41f5-11ea-8ca4-7bc16f38c0f8.PNG)
![2](https://user-images.githubusercontent.com/7862838/73273883-b5bbd400-41f5-11ea-9bbd-329e4f850177.PNG)
![3](https://user-images.githubusercontent.com/7862838/73273897-ba808800-41f5-11ea-8a8c-9bfb2ebc14e2.PNG)

**Comment by oguzsaka** [comment]
**`if NewKey.Name.ToLower = 'primary' then
        NewKey.IndexType := 'PRIMARY'
      else if KeyQuery.Col('Non_unique') = '0' then
        NewKey.IndexType := 'UNIQUE'**
      else
        NewKey.IndexType := 'KEY';`
![4](https://user-images.githubusercontent.com/7862838/73275012-958d1480-41f7-11ea-8e87-4290815921fb.PNG)

I think it gives the value in the last condition because it satisfies two conditions
`     NewKey.Name := KeyQuery.Col('Key_name');
      NewKey.OldName := NewKey.Name;
      if NewKey.Name.ToLower = 'primary' then
        NewKey.IndexType := 'PRIMARY'
      else if KeyQuery.Col('Non_unique') = '0' and NewKey.Name.ToLower != 'primary' then
        NewKey.IndexType := 'UNIQUE'
      else
        NewKey.IndexType := 'KEY';`

**Comment by ansgarbecker** [comment]
No, the `if ... else ...` construct prefers the first one if that already matches. It cannot prefer both.

**Comment by oguzsaka** [comment]
Can you print NewKey.IndexType as log?

**Comment by ansgarbecker** [comment]
Next build should show some more details, like this:
```
/* NewKey.Name="PRIMARY", NewKey.Name.ToLower="primary", NewKey.IndexType="PRIMARY" */
```

**Comment by oguzsaka** [comment]
`/* NewKey.Name="PRIMARY", NewKey.Name.ToLower="prımary", NewKey.IndexType="UNIQUE" */`

**Comment by ansgarbecker** [comment]
Ok, your "prımary" has an "i" without dot on it, which is I guess a localization issue in the `ToLower` method. Will try to change that without locale.

**Comment by ansgarbecker** [comment]
Got it, hopefully. Preferring `ToLowerInvariant` now, as described on https://stackoverflow.com/questions/6225808/string-tolower-and-string-tolowerinvariant - that thread talks about exactly the same character differences, in the Turkish "i".

Please check in the next build.
