### ISSUE TITLE
Export Create table problem

### ISSUE THREAD

**Issue by lukinhaspm** [HeidiSQL/HeidiSQL#857]
## Steps to reproduce this issue

1. Step 1; Export one table with FK for some table in the same database
2. Step 2; Export "Create table"

## Current behavior

Heidi concat the database + table name, its a problem when you export table from localdatabase to remote database

## Expected behavior

concat only if database are diffetent from current database

## Possible solution

![image](https://user-images.githubusercontent.com/11230133/72638115-7cf04500-3941-11ea-8989-9aafdb820d9a.png)

![image](https://user-images.githubusercontent.com/11230133/72638149-91344200-3941-11ea-84c9-1739cf6d6c0e.png)

## Environment

* **HeidiSQL version:** Current
  
* **Database system and version:** MariaDB 10.2.30
  
* **Operating system:** Windows

**Comment by ansgarbecker** [comment]
That should be fixed in the latest build. Please check.

**Comment by lukinhaspm** [comment]
Hey @ansgarbecker !
When you export is OK
When you use "CREATE CODE", its not OK yet....

SHOW CREATE TABLE...
![image](https://user-images.githubusercontent.com/11230133/72688989-638afc80-3aeb-11ea-9675-fe77d5fc2c54.png)


CREATE CODE
![image](https://user-images.githubusercontent.com/11230133/72689002-82898e80-3aeb-11ea-91be-25b07c711dd2.png)

Thanks
