### ISSUE TITLE
SQLite Type detection issue: CHAR type is not detectedted correctly in SQLite table

### ISSUE THREAD

**Issue by fduenas** [HeidiSQL/HeidiSQL#858]
## Steps to reproduce this issue

1. Step 1;
Create a Table like this:
```
CREATE TABLE [catScian](
  [claveCVE] CHAR(20) PRIMARY KEY ON CONFLICT FAIL NOT NULL, 
  [claveCVEPadre] CHAR(20), 
  [nombre] CHAR(255) COLLATE NOCASE, 
  [descripcion] CHAR COLLATE NOCASE, 
  [incluye] CHAR COLLATE NOCASE, 
  [excluye] CHAR COLLATE NOCASE, 
  [productos] CHAR COLLATE NOCASE, 
  [claveCVEVisual] CHAR(20), 
  [nivelJerarquiaID] INTEGER, 
  [nivelRiesgoID] INTEGER DEFAULT 1, 
  [observaciones] TEXT COLLATE NOCASE, 
  [estatusRegistroID] INTEGER(2) DEFAULT 1);
```
2. Step 2;
Read the table with latest HeidiSQL

## Current behavior

The fiels with type Char(N) or Char will be bad detected like 'UNKNOWN' and size 'N)'.
Example: Char(20) will be read as 'UNKNOWN' and size '20)'

## Expected behavior

In the tables it should say Type 'CHAR' and size 20
## Possible solution

Maybe the current code only detects VarChar types

## Environment

SQLite new experimental driver

* **HeidiSQL version:** 
  
Still happens in 10.3.0.5828

* **Operating system:** 
  
Windows 10

**Comment by ansgarbecker** [comment]
That `CHAR` type was simply not yet detected. Just fixed that for the next build.
