### ISSUE TITLE
show rowid in grids

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#861]
rowid is essentially sqlite's internal primary key. i'm not sure how common `WITHOUT ROWID` tables are, but i think it can be used in many cases as the unique identifier for various operations.

https://www.sqlite.org/rowidtable.html
https://www.sqlite.org/withoutrowid.html

 #12

**Comment by ansgarbecker** [comment]
As there most probably are tables without rowid, they can only be used if there's a fallback.

Is there a use case you have in mind?

**Comment by leeoniya** [comment]
since i get rowid "for free", i typically prefer to use rowid for deletes, updates, upserts, pagination, etc rather than making an additional unique column & index.

from: https://www.sqlite.org/rowidtable.html

> Access to records via rowid is highly optimized and very fast.

but as a counter-point:

> All of the complications above (and others not mentioned here) arise from the need to preserve backwards compatibility for the hundreds of billions of SQLite database files in circulation. In a perfect world, there would be no such thing as a "rowid" and all tables would following the standard semantics implemented as WITHOUT ROWID tables, only without the extra "WITHOUT ROWID" keywords. Unfortunately, life is messy. The designer of SQLite offers his sincere apology for the current mess.

honestly i have not thoroughly checked what the perf or storage difference is of rowid vs an additional column with a primary key. but rowid behaves as an autoincrement while the docs explicitly discourage the actual AUTOINCREMENT:

https://www.sqlite.org/autoinc.html

> 1. The AUTOINCREMENT keyword imposes extra CPU, memory, disk space, and disk I/O overhead and should be avoided if not strictly needed. It is usually not needed.

at the end of the day, rowid may be too weird to fit neatly into Heidi's architecture, so if this is not something simple, then probably don't bother. i do have a bunch of code that uses rowid and it would be nice to see it in the data grid for visual reference.

**Comment by leeoniya** [comment]
i should add that contrary to the assumption in https://github.com/HeidiSQL/HeidiSQL/issues/12#issuecomment-576212315 (that rowid is immutable), it behaves mostly as a normal column with some minor datatype restrictions:

https://www.sqlite.org/lang_createtable.html#rowid

> Rowid values may be modified using an UPDATE statement in the same way as any other column value can, either using one of the built-in aliases ("rowid", "oid" or "_rowid_") or by using an alias created by an integer primary key. Similarly, an INSERT statement may provide a value to use as the rowid for each row inserted. Unlike normal SQLite columns, an integer primary key or rowid column must contain integer values. Integer primary key or rowid columns are not able to hold floating point values, strings, BLOBs, or NULLs.

so there's no need to create a special read-only column in the gird to accommodate it.

**Comment by leeoniya** [comment]
@ansgarbecker is this likely to happen in the near future?

**Comment by ansgarbecker** [comment]
Not very likely I guess. This rowid is only valid for SQLite, and I have a bunch of issues for the more major used databases to fix.

**Comment by ansgarbecker** [comment]
I just pushed a change which now shows a row id in grids for all server types, not only for SQLite. The row id is just a static read-only value, indexed through the underlying grid, nothing which is retrieved from the server. The column is fixed to the screen, so it does not scroll with the normal columns:

![grafik](https://github.com/HeidiSQL/HeidiSQL/assets/7986591/1cdc7548-e01e-4a2f-8b62-025c17450ad6)

I hope this is useful for you.
There is also a [discussion in the forum](https://www.heidisql.com/forum.php?t=22407) about that, but if you find issues please post them here.

**Comment by boily** [comment]
Nice feature, but I did not find a way to not display this row id in grids. 
I expected to find an option in Preferences->Grid formatting.
Thank you

**Comment by ansgarbecker** [comment]
Well, only a small set of features is customizable in HeidiSQL. I'm thinking the row id is quite useful and should not bother anyone, does it?

**Comment by boily** [comment]
I understand that in many circumstances it can be very useful. 
I have many numeric columns to show, having one more column makes data reading harder. 
Also i should mention that this row id is absolutely useless for my daily use.
Anyway i will try to get used to it. Thank you.

**Comment by ansgarbecker** [comment]
Next build has a new checkbox "Show static row id column", in Preferences > Grid formatting.
