### ISSUE TITLE
Creating a connection with a second instance of MSSQL server just connects to the primary instance instead.

### ISSUE THREAD

**Issue by leonjanzen-work** [HeidiSQL/HeidiSQL#862]
## Steps to reproduce this issue

1. Step 1; Create a connection to a secondary instance of MSSQL Server using TCP/IP with an instance name that contains a backslash (e.g. DRSRV\DEV).
2. Step 2; Connect

## Current behavior

Instead of connecting with the second instance, it connects with the primary instance, in my case called "DRSRV". It actually ignores everything after the backslash when connecting. I can put whatever text I want after the backslash and it ignores it and connects to my primary instance.

## Expected behavior

It should connect to the second instance instead.

## Possible solution

No idea, but HeidiSQL 9.5 connects to my second instance correctly.

## Environment

* **HeidiSQL version:** 10.3.0.5838
  
* **Database system and version:** Microsoft SQL Server 13.0.5101.9
  
* **Operating system:** Windows 10, build 1909

**Comment by ansgarbecker** [comment]
The newer builds and releases have a new "Library" setting in the session manager:

![grafik](https://user-images.githubusercontent.com/7986591/73126070-751e4980-3fae-11ea-8720-ec10d8a9038b.png)

Can you please test changing the library to the other one. HeidiSQL 9.5 internally always used the first option "SQLOLEDB". So, maybe that helps here.

I am not sure what is going wrong if it's not that driver library.

**Comment by leonjanzen-work** [comment]
I tried using both of the libraries, and had the same results with both libraries, unfortunately. (I meant to include that detail, but had already downgraded my version to try it, and couldn't remember what those had been called in the new version.)

**Comment by leonjanzen-work** [comment]
Just for information, I updated to the latest nightly build, revision 5861, and still cannot connect to the second SQL Server instance on my server, using either the MSOLEDBSQL library (currently using version 18.3.0), or the older SQLOLEDB library. Not sure if anything can be done (it may be a library issue), but I thought I'd update this anyway.

**Comment by ansgarbecker** [comment]
Thanks for the update. I just compared the connection code from v9.5 to the current state, and see no effective change, except for that additional `MSOLEDBSQL` and some irrelevant changes.

We could compare the connection strings. Once you have a connection, you can see that by click on the status bar panel which shows the server + version:

![grafik](https://user-images.githubusercontent.com/7986591/73775398-11ea9f00-4786-11ea-85e4-ca51c8c2975c.png)

Note that my net type is like follows:

![grafik](https://user-images.githubusercontent.com/7986591/73775494-43fc0100-4786-11ea-9270-8f4fb07eab0e.png)

**Comment by leonjanzen-work** [comment]
I'll start by saying that using the Network type "Microsoft SQL Server (named pipe)" works to connect to my second instance!
Named Pipe doesn't connect at all to my primary instance (see error below), which is why I never even attempted it for the second instance:
![image](https://user-images.githubusercontent.com/6565814/73777385-8d2c6080-4746-11ea-9dd6-7edda980a0e0.png)

Here's the connection string when unsuccessfully connecting to my second instance using TCP/IP (it connects to my first instance instead):
![image](https://user-images.githubusercontent.com/6565814/73777622-0a57d580-4747-11ea-9f63-73bb25bdda2f.png)

And here's the connection string when successfully connecting to my second instance using Named Pipe:
![image](https://user-images.githubusercontent.com/6565814/73777691-278ca400-4747-11ea-9251-e46feb958d76.png)

The only differences are that for TCP/IP, the port number is appended to the "Data Source=" value, and for TCP/IP the "Network Library=DBMSSOCN", whereas for named Pipe "Network Library=DBNMPNTW".

So I'm not sure if there's still a bug here or not, but using Named Pipes does allow me to connect to my second instance.

**Comment by ansgarbecker** [comment]
That sounds as if the both TCP configuration were using the same port, just a different hostname, or? If so, that looks quite normal, apart from the fact that your TCP host is resolvable with 2 different hostnames.

If you still have the v9.5 running, you could check there if the second instance really connects with TCP.

But I guess we can just close this then, problem was solved anyway.

**Comment by leonjanzen-work** [comment]
Yes, it seems this was a knowledge issue on my part, and that Named Pipe is the normal way to connect to a second instance. But with v9.5 it does successfully connect to my second instance using TCP/IP, so I never thought to try named pipe.
Thanks for your help with this!
