### ISSUE TITLE
MS SQL: no column lenght

### ISSUE THREAD

**Issue by FlavioSuarez** [HeidiSQL/HeidiSQL#864]
## Steps to reproduce this issue

1. Step 1; Open a table on MS SQL Server. 
2. Step 2; Go to table structure tab
3. Step N;
4. Then I get... 

## Current behavior

- The columns lenght isn't shown
- The CREATE TABLE code don't have the columns lenght

## Expected behavior

To see the columns lenght

## Possible solution

On the v10.3.0.5782 it was ok..

## Environment

Using the MSOLEDBSQL driver

* **HeidiSQL version:** 
Latest (v10.3.0.5843)
  
* **Database system and version:** 
SQL Server 2012 (SP3), V11.0.6020.0

  
* **Operating system:** 
  
Windows 8.1 64bits

![10 3 0 5843](https://user-images.githubusercontent.com/12549794/72892983-a53bc300-3cf6-11ea-83c7-f9d03de22d9d.jpg)
![10 3 0 5782](https://user-images.githubusercontent.com/12549794/72892984-a53bc300-3cf6-11ea-986b-2554609d33eb.jpg)

**Comment by ansgarbecker** [comment]
Should be fixed in the next build
