### ISSUE TITLE
Feature Request: Option to duplicate sessions

### ISSUE THREAD

**Issue by WesleyM77** [HeidiSQL/HeidiSQL#865]
## Steps to reproduce this issue

1. Want to copy a session, but with one minor change
2. Have to manually copy over information

My use case is that I need to make 12 copies of QA environment for work because these environments all have the same settings, just different port numbers.  Being able to duplicate a session would save some time. I'm just creating the sessions as I need them currently.

## Current behavior

No option to duplicate/copy a session pre-set

## Expected behavior

Option to duplicate/copy a session pre-set

**Comment by ansgarbecker** [comment]
Did you see the right-click menu item "_Save as..._"?

**Comment by WesleyM77** [comment]
I must've looked right past that, or thought that wouldn't do what I need it to do. Would changing "Save as..." to "Copy" or "Duplicate" make it more clear?

**Comment by ansgarbecker** [comment]
Not sure, "Save as" seems quite common to me. "Copy" would make me think this is copying to clipboard. "Duplicate" may be ok, less common than "Save as", but ok. What about "Duplicate / save as..." ? Though I tend to think I'd just leave it as it is.

**Comment by WesleyM77** [comment]
I would opt for the "Duplicate/Save As..." change, but if you're leaning towards keeping it as is, would it be possible to show a tooltip that could explain what that button does? It's just that when I see "Save as..." in this context, I got the impression of saving that session as like a backup or something, not that it was going to save a copy of the session pre-set to the screen I'm already on.

**Comment by ansgarbecker** [comment]
> ... like a backup or something

That convinced me. I just changed it, see the next build.
