### ISSUE TITLE
Comment before Load Data causes an error

### ISSUE THREAD

**Issue by arielvsp** [HeidiSQL/HeidiSQL#866]
## Steps to reproduce this issue

1. Write script as below (the comment line is important! also assumes the file, the table and the table fields all exist and are correct)
\# some comment
LOAD DATA LOCAL INFILE 'myfile.csv' INTO TABLE role_temp FIELDS TERMINATED BY ',' IGNORE 1 LINES (`username`,`role`);

2. Execute the script.

3. Then I get this error (Load data local infile forbidden):
![image](https://user-images.githubusercontent.com/6899480/73020369-26e23c80-3e2e-11ea-8f9c-6d1ae5a4a920.png)

## Current behavior

The same script worked for me for over a year, nothing has changed in my environment AFAIK (updated HeidiSQL a week ago or so). All of a sudden I got a consistent error. Removing the comment line resolves the problem!

## Expected behavior

Expected the script to perform with no error thrown.

## Possible solution

No idea, you really have to look into this.

## Environment

* **HeidiSQL version:** 
10.3.0.5847
  
* **Database system and version:** 
MySQL (Amazon RDS - latest)
  
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
Could you please check if you have "libmariadb.dll" selected as library in your session, and whether any of the alternatives fixes the problem? Another user [said that helped](https://www.heidisql.com/forum.php?t=35152#p35157).

**Comment by arielvsp** [comment]
That's a good point. I was not aware of the default MariaDB selection (I guess it was not that way before). Selecting mysql resolves the issue! Many thanks for a prompt response on that!
