### ISSUE TITLE
"SQL help" window does not open

### ISSUE THREAD

**Issue by preart81** [HeidiSQL/HeidiSQL#868]
## Steps to reproduce this issue

1. Type the word in SQL query tab
2. Select keyword on SQL query tab
3. Press F1
4. "SQL help" window does not open

## Current behavior

"SQL help" window does not open

## Expected behavior

"SQL help" window opens

## Environment

* **HeidiSQL version:** 

HeidiSQL portable 10.3.0.5848

* **Database system and version:** 
  MySQL 5.5.44

**Comment by ansgarbecker** [comment]
Please post the last 10 lines from SQL log panel here. There should be some error message I can probably analyze.

**Comment by preart81** [comment]
Query tab keyword on wich i press F1
`select`

SQL log panel

> HELP 'CONTENTS';
> HELP 'select';
> HELP 'Account Management';
> HELP 'Administration';
> HELP 'Compound Statements';
> HELP 'Data Definition';
> HELP 'Data Manipulation';
> HELP 'SELECT';

**Comment by ansgarbecker** [comment]
I just downloaded the same MySQL version and tried to reproduce this issue, with no luck. The help window shows up immediately:

![grafik](https://user-images.githubusercontent.com/7986591/73133797-041e7680-402e-11ea-8418-adb55ad65e31.png)

So this is apparently not a server specific issue. Maybe the window opens at a position outside your actual screen. You could use your keyboard to try moving it into the visible area again: https://www.sevenforums.com/tutorials/77361-move-window-keyboard.html
(I recommend using the <kbd>Windows key + Left/Right/Up/Down Arrow</kbd>

**Comment by preart81** [comment]
You are right - the window appeared off the screen!
I'm sorry to have spent your time!
Thank you very much for your help!

**Comment by ansgarbecker** [comment]
Thanks for your quick feedback!
