### ISSUE TITLE
why comma in field length for int big int

### ISSUE THREAD

**Issue by mailparikshit** [HeidiSQL/HeidiSQL#869]
## Steps to reproduce this issue

1. Step 1; open any database for mysql 8.0
2. Step 2; create a table having double(10,3) , int(10), enum (Y,N)

## Current behavior

after table is created when you see table details in editor it displays comma separator in field length for int and bigint which is giving error.
also enum default value appears without single quote crashing down query for alter table, create table code

current appearance
`INT(10,3)`
enum default value **`N`** 

## Expected behavior

enum default value should appear with single quote `'N'`
int and bigint length should appear without comma .

## Possible solution

should be as expected output

## Environment

wnidows 10 pro 64 bit

* **HeidiSQL version:** 
  heidisql 10.3.0.5850
* **Database system and version:** 
 database mysql 8.0.19
* **Operating system:** 
  windows 10 pro 64 bit

**Comment by fifonik** [comment]
I could not re-produce the comma issue. Everything as expected.

As per quoted for the default enum, I can confirm it.

**Comment by marthieme** [comment]
Same here. 
I Have to remove the part after the comma everytime before i can save the table which makes HeidiSQL practically unusable. 

![image](https://user-images.githubusercontent.com/25841949/77075565-d123ae00-69f2-11ea-9545-a142af3fc455.png)

mysql version 8.0.19

**Comment by ansgarbecker** [comment]
Is that reproducible with HeidiSQL 11.0?

**Comment by rentalhost** [comment]
@ansgarbecker I could not reproduce at r5919 (11.0). I will check when it was fixed.

**Comment by marthieme** [comment]
> Is that reproducible with HeidiSQL 11.0?

I edited my comment above. I use HeidiSQL version 11.0.0.5919 (64Bit).

**Comment by rentalhost** [comment]
@ansgarbecker @marthieme @mailparikshit 

Ok, I could reproduce with MySQL 8.0.19 at least, using r5919. But `INT(10, 0)` will not cause any error, except if you try to rename the column, for instance.

In this case, it will generate the following code:

```sql
ALTER TABLE `test_869`
	CHANGE COLUMN `int` `int2` INT(10,0) NULL DEFAULT NULL AFTER `double`;
```

---

About the `ENUM` case, I still can't reproduce. In case, I am setting the default value as "custom text", and it wrap with a single quote correctly.

![image](https://user-images.githubusercontent.com/421851/77096029-805d8680-69ed-11ea-9aa4-efb6d98858f6.png)

```sql
ALTER TABLE `test_869`
	CHANGE COLUMN `enum` `enum` ENUM('Y','N') NULL DEFAULT 'N' COLLATE 'utf8mb4_general_ci' AFTER `int`;
```

**Comment by ansgarbecker** [comment]
I already broke something here for #876. Just pushed a modification which should now never add that numeric scale value to integer typed columns. Please update to the latest build and retry.

**Comment by rentalhost** [comment]
Fix checked and now works fine.

**Comment by ansgarbecker** [comment]
@rentalhost  thanks for all your feedback, also in other threads!
