### ISSUE TITLE
Upgrade autocompletion feature: Always show the autocomplete dropdown after typing table. or table_alias. (and continue to show as I type the column name)

### ISSUE THREAD

**Issue by jaredlt** [HeidiSQL/HeidiSQL#87]
## Current state

When using autocompletion after an alias there is a delay of half a second before the autocomplete list appears.

## Problem

This means you have to wait for the list to appear before typing the first few letters. Otherwise if you start typing the alias and a period and type straight away, the autocomplete will never appear (which can be an interruption to your typing flow).

![demo](https://user-images.githubusercontent.com/8590311/34850395-7d3b542c-f71d-11e7-9de4-2319b5fe9d87.gif)

(Demo above: the first "c." shows the delay, the second, shows that the autocomplete list does not appear when you keep typing immediately)

## Suggested solution

~~Allow the autocompletion TimerInterval to be customizable in the settings dialog.~~

~~Example setting text:~~

~~`Autocompletion delay (ms): [ 500 ]`~~

UPDATE from [discussion below](https://github.com/HeidiSQL/HeidiSQL/issues/87#issuecomment-357791967):

- Don't introduce another setting
- Instead, improve the feature that sits behind the existing `Enable autocompletion` setting

Updated feature should:

 - Always show the autocomplete dropdown after typing `table.` or `table_alias.` (already exists but currently has 500ms delay).
 - Continue to show autocomplete dropdown as a user types ahead from `table.` or `table_alias.` , filtering the results
 - If the autocomplete dropdown is dismissed (pressing ESC or clicking elsewhere), re-activate the dropdown automatically if another valid character is entered eg. `table.col` > ESC > `table.colu` (should show dropdown again, filtered)

Demo of implemented feature in DataGrip

![datagrip-autocomplete](https://user-images.githubusercontent.com/8590311/34907631-7a7ac27e-f879-11e7-8854-098eeb2d7d08.gif)

----

Issue origin: https://www.heidisql.com/forum.php?t=24719#p24726

**Comment by fifonik** [comment]
You can always use Ctrl + Space to open the autocomplete manually (this works in may IDE).
Not sure that the timeout option is really required.

**Comment by jaredlt** [comment]
@fifonik I am aware that you can manually invoke the autocomplete dialog using CTRL + Space. However, what I'd like to control is _when_ the dialog appear automatically after a table alias and a period are typed.

Once you type a table alias and the period, there are only a set number of valid inputs that can proceed (ie. the table column names). HeidiSQL already knows this and presents the list of table names after you type the period. However, you have to wait half a second for the list to appear. For tables I use frequently, I often know the name of the column, I just want to use the autocomplete dialog as a type-ahead helper. I'd like to be able to keep typing immediately after the period and for the autocomplete list to appear and filter down to the remaining valid entries as I keep typing. Then as you say, I can hit enter and I'm done. 

Having to invoke CTRL + Space every time is something I'd like to avoid. Especially when HeidiSQL actually already has the feature I want to use (just with a small delay that interrupts flow). It's a great productivity booster when you're using the tool all day.

@ansgarbecker perhaps the issue title is a bit solution-heavy. It's really all about "Option to always show the autocompletion dialog after a table alias and period" (although I'm guessing setting the TimerInterval to 0 will do just that).

As an aside, DataGrip is the only tool I've used that implements this feature well (however, I find HeidiSQL much more intuitive than DataGrip). Their implementation works well because even if you cancel out of the autocomplete dialog (after beginning to type part of the column name), if you type another letter it will again bring up the dialog with all remaining matches.

![datagrip-autocomplete](https://user-images.githubusercontent.com/8590311/34907631-7a7ac27e-f879-11e7-8854-098eeb2d7d08.gif)

**Comment by fifonik** [comment]
I'm not saying that we do not need improvements in Heidi's autocomplete. 
I said that the timeout before triggering autocomplete option looks very strange. And I do not like programs with hundreds of strange options because in this case it is hard to find across them useful...
I do not remember that I ever see such option (timeout before triggering autocomplete dropdown) anywhere. Not in Notepade++, not in VS (I don't use recent versions, it might be there), not in Visual Studio Code.

If I know the column name and I'd like to substitute it, I'm keying in 'table.co' and then pressing Ctrl + Space, Ctrl + Enter. Job's done (I have 'table.column' substituted). And I do not need to wait anything at all.

Instead of the timeout I'd prefer to see in Heidi the following changes related to autocomplete:
- Timeout changed to 0.2 - 0.3 sec
- Filtered autocomplete dropdown shown when timeout reached even if something else was keyed in after the dot. This allow you to continue type and not wait for the dropdown.
- Automatic column substitution with Tab (as in many other editors). This allow me to type 'table.co' and press the key to substitute 'table.column' and there is only one matched entry or open the dropdown if there is more than one.

**Comment by jaredlt** [comment]
@fifonik ok I'm with you now and I agree. In summary:

- Don't introduce another setting
- Instead, improve the feature that sits behind the existing `Enable autocompletion` setting

Updated feature should:

 - Always show the autocomplete dropdown after typing `table.` or `table_alias.` (already exists but currently has 500ms delay).
 - Continue to show autocomplete dropdown as a user types ahead from `table.` or `table_alias.` , filtering the results
 - If the autocomplete dropdown is dismissed (pressing ESC or clicking elsewhere), re-activate the dropdown automatically if another valid character is entered eg. `table.col` > ESC > `table.colu` (should show dropdown again, filtered)

I've left out the TimeInterval change as it feels like an implementation detail.

NB. Pressing `Tab` from the autocomplete dropdown works for me.

**Comment by ansgarbecker** [comment]
Well I'm afraid this is not some wish list here - I have to use what SynEdit offers here. I will see what I can do here.

**Comment by jaredlt** [comment]
@ansgarbecker understood. Thanks 👍

**Comment by ansgarbecker** [comment]
Please note that #972 is finished in v11.1, so now you can use a custom shortcut to trigger the code completion:
![grafik](https://user-images.githubusercontent.com/7986591/101086503-3a634580-35b1-11eb-8eb2-6121f4cf26e3.png)

**Comment by ansgarbecker** [comment]
Closing as discussed in #1691.
