### ISSUE TITLE
[SQLITE] HeidiSQL should show field type Char, varchar, Nvarchar as is and not all as Varchar, etc even if all of them have affinity to  TEXT

### ISSUE THREAD

**Issue by fduenas** [HeidiSQL/HeidiSQL#870]
## Steps to reproduce this issue

1. Step 1;
Create table with the folloring query
```
CREATE TABLE [catScian](
  [claveCVE] CHAR(20) PRIMARY KEY ON CONFLICT FAIL NOT NULL, 
  [claveCVEPadre] CHAR(20), 
  [nombre] CHAR(255) COLLATE NOCASE, 
  [descripcion] VARCHAR(255) COLLATE NOCASE, 
  [incluye] CHAR COLLATE NOCASE, 
  [excluye] CHAR COLLATE NOCASE, 
  [productos] CHAR COLLATE NOCASE, 
  [claveCVEVisual] CHAR(20), 
  [nivelJerarquiaID] INTEGER, 
  [nivelRiesgoID] INTEGER DEFAULT 1, 
  [observaciones] TEXT COLLATE NOCASE, 
  [estatusRegistroID] INTEGER(2) DEFAULT 1);

```
2. Step 2;
Read the table with heidiSQL, 

## Current behavior

HeidiSQL detect CHAR type fields and VarCHAR and maybe other text types as VARCHAR. this also can affect other similar types.

## Expected behavior

claveCVE should be show as 'CHAR' type
descripcion should be of VARCHAR
## Possible solution

Please check point 3.1.1 in https://www.sqlite.org/datatype3.html

In other sqlite managers like SQLite Expert those types are showed correctly
## Environment

* **HeidiSQL version:** 
  
Heidi Version 10.3.0.5851 (64 Bit)
* **Database system and version:** 
  
SQLITE
* **Operating system:** 
  
Windows 10

**Comment by ansgarbecker** [comment]
You should really write shorter titles. I just separated CHAR from VARCHAR, but I left NVARCHAR detected as VARCHAR. Even in other RDBMS there is little up to no difference between VARCHAR and NVARCHAR.

**Comment by fduenas** [comment]
Sorry, I promise to write shorter ttitles. :)
