### ISSUE TITLE
[PostgreSQL] Foreign Key does not appear on the list

### ISSUE THREAD

**Issue by prunusnira** [HeidiSQL/HeidiSQL#871]
## Preliminary

I know it is recently fixed about adding foreign key ( https://github.com/HeidiSQL/HeidiSQL/issues/158 ) but this is different issue.

## Steps to reproduce this issue

1. Step 1: Add foreign key from HeidiSQL
( Actually it didn't work from adding constant... so I manually added unique constraint )
( Please check this issue https://github.com/HeidiSQL/HeidiSQL/issues/321 )

2. Step 2: Check Foreign key list from HeidiSQL -> It disappears and does not show anything after adding foreign key

3. Step 3: I tried to add foreign key again from HeidiSQL, and it says same foreign key is already there

4. Step 4: So, I checked foreign key list from pgAdmin4, which showed correctly

(It means, HeidiSQL can add foreign key successfully, just not showing them on the list)

## Current behavior

Foreign Key List from HeidiSQL (10.3.0.5853)
(Sorry for the language in the screenshot, anyway this is empty Foreign Key list after adding one)

![foreignkey1](https://user-images.githubusercontent.com/10396020/73415038-05b0ad00-4354-11ea-8220-9b20a75578f8.png)

Foreign Key List from pgAdmin4

![foreignkey2](https://user-images.githubusercontent.com/10396020/73415549-989e1700-4355-11ea-818c-b646b32acea1.png)

## Expected behavior

Showing Foreign Key list

## Environment

* **HeidiSQL version:** 10.3.0.5853
  
* **Database system and version:** PostgreSQL 10.11
  
* **Operating system:** Windows 10 1903 (x64)

**Comment by ansgarbecker** [comment]
This is already on my todo list for the next release, see #158 .
Maybe you can help out with a query I wrote there to retrieve the foreign keys of one table?
