### ISSUE TITLE
Create Table Copy broken

### ISSUE THREAD

**Issue by honsberg** [HeidiSQL/HeidiSQL#873]
i want to create an table copy. 
it says "default value invalid".

the default value is Current timestamp, but heidi uses this with quotes. 

![grafik](https://user-images.githubusercontent.com/12712721/73531492-dc0e8900-441a-11ea-9f70-3b0bff01d589.png)

i think, the create code and the displayed default values are wrong too.

**Comment by honsberg** [comment]
Using 
HeidiSql 10.3.0.5855
Windows 10 1909
(hosted) MySQL 5.6.19-67.0-log

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.
