### ISSUE TITLE
Visual bug when cell edit and new tab

### ISSUE THREAD

**Issue by chrysler5798** [HeidiSQL/HeidiSQL#874]
Hello, I found a little visual bug.

# Steps to reproduce this issue

1. Edit a cell
2. Click on new tab

Gif example:
![7KnLSNhLtC](https://user-images.githubusercontent.com/7657777/73534601-c94b8280-4421-11ea-8248-410a014d4c6d.gif)

## Current behavior
Cell editing keeps displaying.

## Expected behavior
Cell editing should hide.

## Environment
* **HeidiSQL version:** 10.3.0.5855

**Comment by chrysler5798** [comment]
Sorry duplicated #725

**Comment by ansgarbecker** [comment]
Thanks for your update, and that gif !
