### ISSUE TITLE
MariaDB - unable to ALTER TABLE with DOUBLE

### ISSUE THREAD

**Issue by cedbesafilm** [HeidiSQL/HeidiSQL#876]
## Steps to reproduce this issue

1. Create a table with a column of double type (or open an existing table with a column of double type); 
![image](https://user-images.githubusercontent.com/55377336/73789911-eecce900-479f-11ea-8736-9996a009059a.png)
2. Add a column after the column;
3. The query result is 
```
 ALTER TABLE `test`
	ADD COLUMN `colonna_2` DOUBLE(22) NULL DEFAULT NULL AFTER `colonna_1`;
```
so the save fails with sql error
![image](https://user-images.githubusercontent.com/55377336/73789977-073d0380-47a0-11ea-8ead-91af1739e8e8.png)

4. Copy the query from Code ALTER tab and remove the `(22)` in the query and execute it
5. The query run without error
![image](https://user-images.githubusercontent.com/55377336/73790113-38b5cf00-47a0-11ea-848a-4320e24131d9.png)

## Current behavior
The query created in the Code ALTER table is wrong

## Expected behavior
The query run without error

## Possible solution
Remove length of field in the alter table query

## Environment
* **HeidiSQL version:** 10.3.0.5862
* **Database system and version:** MariaDB 10.4.12 
* **Operating system:** Windows 10

**Comment by rentalhost** [comment]
Could not reproduce as specified, but I could reproduce on try moving `colonna_2` above `colonna_1`. So `ALTER `code is (that is invalid):
 
```sql
ALTER TABLE `test`
	CHANGE COLUMN `colonna_2` `colonna_2` DOUBLE(22) NULL DEFAULT NULL FIRST;
```

**Comment by rentalhost** [comment]
**Identified first at:** `r5845` after #864.
