### ISSUE TITLE
Crash when mouse moved over data grid after losing connection

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#878]
## Steps to reproduce this issue

1. Open HeidiSQL, connect to MySQL server and open any DB in tree;

2. Click at table in the DB and then click at 'Data' tab:
![HeidiSQL Lost Connection Data](https://user-images.githubusercontent.com/7234987/73801335-db546900-4805-11ea-9c82-789fa90cf88e.png)

3. Open MySQL CLI and connect to the same server;

4. In MySQL CLI issue query 'show processlist;' and notice the process id of HeidiSQL connection. In the MySQL CLI issue 'KILL <x>;' to disconnect HeidiSQL from the server;

5. Switch to HeidiSQL and in a few seconds you should see in log 'Connection to <xyz> closed at ...'. 

6. Now start to move mouse and HeidiSQL will crash as soon as you "touch" the data in the grid:
![HeidiSQL Lost Connection Data Crash](https://user-images.githubusercontent.com/7234987/73801345-e0191d00-4805-11ea-9554-5bb8eea1ab7a.png)

## Current behavior
Crash

## Expected behavior
No crash

## Possible solution
Data grid might be grayed out or HeidiSQL might try to re-connect.

## Environment

* **HeidiSQL version:** 
HeidiSQL x64 10.3.0.5862 (the latest one at the time of writing)
* **Database system and version:** 
MySQL 5.7.23 (the same issue with MariaDB 10.1)
* **Operating system:** 
Windows 10 1803

**Comment by ansgarbecker** [comment]
I believe this is an older issue. Didn't you see that in older versions?

**Comment by fifonik** [comment]
Sure, it is not new to the version mentioned. 
Heidi crashed avery morning when I woken up my work PC (with Heidi running).
I just recently found a way to reproduce the issue and then upgraded Heidi to the latest version to check if the issue is still exist.

**Comment by ansgarbecker** [comment]
I just pushed a fix for this crash, now disabling the data grid and displaying a label "No data available".

There may be some more side effects on a disconnected session, so just shout if there are more crashes when you wake up your pc.
