### ISSUE TITLE
[10.3.0.5571] EReadError: Stream read error while "Run SQL file"

### ISSUE THREAD

**Issue by Commifreak** [HeidiSQL/HeidiSQL#879]
## Steps to reproduce this issue

1. Run specific sql file, dumped with mysqldump;
2. Then I get an Excpetion while reading the file

## Environment

* **HeidiSQL version:** 10.3.0.5571
  
* **Database system and version:** MySQL 5.5.62 & 10.4.6-MariaDB
  
* **Operating system:** Win10 LTSC x64
  

I just send an bug report via the internal bug reporter as well (kontakt at kluthr dot de).

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4157826/bugreport.txt)

**Comment by Commifreak** [comment]
Also happens with 10.3.0.5862: 
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4157835/bugreport.txt)

**Comment by Commifreak** [comment]
Ok, I got it. Instead of "UTF-8" as ecnoding option in the "Run SQL file"-dialog, I had to select ANSI.

Autodetect was not working either.

**Comment by ansgarbecker** [comment]
Yes, "Auto detect" is working very poorly, I admit. I should probably remove that option. However, thanks for your feedback!

**Comment by Commifreak** [comment]
Wouldnt it be a nice feature if HeidiSQL tries all options until a complete read was successful?

* Select file with Auto-Detect
* loop through all encodings
* If error occurs, discard and continue until file can be read
* Execute the content

?

**Comment by ansgarbecker** [comment]
Detecting a file's encoding is quite tricky, and even more tricky to detect whether the detection was correct :) So, I should either remove that auto-detect, or maybe rewrite it, using a more stable approach.
