### ISSUE TITLE
PostgreSQL information_schema.REFERENTIAL_CONSTRAINTS.TABLE_NAME

### ISSUE THREAD

**Issue by zilzila** [HeidiSQL/HeidiSQL#880]
## Steps to reproduce this issue

1. Open new PG (v12.1) connection;
2. Click on any table in DB tree;

## Current behavior

HeidiSQL (in log below):
`SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='test'   AND TABLE_NAME='test_table'   AND REFERENCED_TABLE_NAME IS NOT NULL;`
`/* ERROR:  column "table_name" does not exist
LINE 1: ...CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='test'   AND TABLE_NAME... ^ */`

## Expected behavior

No SQL error

## Possible solution

Change `TABLE_NAME` to `CONSTRAINT_NAME` and `REFERENCED_TABLE_NAME` to `UNIQUE_CONSTRAINT_NAME` or use a different query

## Environment

* **HeidiSQL version:** 
  
HeidiSQL x64 portable 10.3.0.5867
* **Database system and version:** 
  
PostgreSQL (12.1)

**Comment by ansgarbecker** [comment]
That's what I am working on in issue #158 . Feel free to help out - just read the last few comnents there, HeidiSQL needs a query which gives the source and reference columns for all foreign keys in a table.
