### ISSUE TITLE
SQL editor: cursor does not stop on a non-ASCII word when Ctrl+Left/Right

### ISSUE THREAD

**Issue by zilzila** [HeidiSQL/HeidiSQL#882]
## Steps to reproduce this issue

1. Type (copy/paste) in the SQL editor text of non-ASCII characters:
`-- This is test comment. Курсор не останавливается на не-ASCII слове при Ctrl+Left/Right`
`-- This is test comment. Ο δρομέας δεν σταματά στο μη-ASCII λέξη με Ctrl+Left/Right`
`-- This is test comment. Курсор се не зауставља на не-ASCII речи када Ctrl+Left/Right`
`-- This is test comment. 커서가 Ctrl+왼쪽/오른쪽으로 비 ASCII 단어에서 멈추지 않습니다`
`select 'Test comment. Курсор не останавливается на не-ASCII слове при Ctrl+Left/Right';`
`select 'Test comment. Ο δρομέας δεν σταματά στο μη-ASCII λέξη με Ctrl+Left/Right';`
`select 'Test comment. Курсор се не зауставља на не-ASCII речи када Ctrl+Left/Right';`
`select 'Test comment. 커서가 Ctrl+왼쪽/오른쪽으로 비 ASCII 단어에서 멈추지 않습니다';`
2. Try moving the cursor over words using Ctrl+Left/Right;

## Current behavior

The cursor jumps over words of non-ASCII characters

## Expected behavior

The cursor stops at each word, as in the case of ASCII characters

## Environment

* **HeidiSQL version:** 
  
HeidiSQL 10.3.0.5867
* **Operating system:** 
  
Windows 7, 10 x64

**Comment by ansgarbecker** [comment]
That's https://github.com/SynEdit/SynEdit/issues/111, and a duplicate to #851
