### ISSUE TITLE
Error(0) : provider cannot be found

### ISSUE THREAD

**Issue by jiichen** [HeidiSQL/HeidiSQL#883]
## Steps to reproduce this issue

1. Step 1; install HeidiSQL version HeidiSQL_10.3.0.5771_Setup.exe
2. Step 2; try connect MS SQL Server 2012
3. Step 3; appera error dialog : Error(0) provider cannot be found
4. Step 4; I re-install old version , HeidiSQL_10.2.0.5599_Setup.exe , and I correct connected.

so, I think 10.3.0.5771 is something wrong.

## Environment

Windows 8.1

* **HeidiSQL version:** 
  HeidiSQL_10.3.0.5771_Setup  is wrong.
  and I has update beat version also is wrong.

  
* **Database system and version:** 
  
* **Operating system:** 
  

thanks you , HeidiSQL is very nice.

**Comment by ansgarbecker** [comment]
That sounds as if your system is missing the newer `MSOLEDBSQL` for some reason. Please try the old `SQLOLEDB` in your session settings:

![grafik](https://user-images.githubusercontent.com/7986591/74006185-2ba10780-497b-11ea-87a1-8e8daede66b5.png)

And probably install the newer one from https://www.microsoft.com/en-us/download/confirmation.aspx?id=56730

**Comment by jiichen** [comment]
@ansgarbecker 

I modify HeidiSQL connection setting , Old setting is "SQLOLEDB" , then I change this to "MSOLEDBSQL" .
Yes , HeidiSQL_10.3.0.5771_Setup.exe now can work correct.

ps: Before I commit this issue, I has installed msoledbsql_18.3.0.0_x64.exe

Thank your answer , this issue can closed.
--
Hope HeidiSQL nice better than better.

**Comment by ansgarbecker** [comment]
Thanks for your quick feedback!
