### ISSUE TITLE
Error when editing MSSQL table with TEXT-field

### ISSUE THREAD

**Issue by lakebranch** [HeidiSQL/HeidiSQL#885]
## Steps to reproduce this issue
1. Create table in MSSQL with atleast one TEXT-field
2. Insert some data
3. Try to edit a row in this table using HeidiSQL
4. Error: SQL Error (402): The data types text and varchar are incompatible in the equal to operator.

## Current behavior
SQL Error (402): The data types text and varchar are incompatible in the equal to operator.

## Expected behavior
No error and successful edit

## Possible solution
_Please note: The TEXT and NTEXT datatypes are deprecated in favor of VARCHAR(MAX) and NVARCHAR(MAX) and will be removed in a future version of MS SQL Server according to Microsoft. This potentially makes this "bug" a_ **wontfix** _I guess..._

The editor formats the SQL as follows:

    UPDATE TOP(1) "TestDB"."dbo"."TestTable2" SET "TextField"='Test2' WHERE  "Id"=1 AND "TextField"='Test';

Changing it to the following works:

    UPDATE TOP(1) "TestDB"."dbo"."TestTable2" SET "TextField"='Test2' WHERE  "Id"=1 AND CONVERT(VARCHAR,"TextField")='Test';

OR

    UPDATE TOP(1) "TestDB"."dbo"."TestTable2" SET "TextField"='Test2' WHERE  "Id"=1 AND "TextField" LIKE 'Test';

## Environment
* **HeidiSQL version:** 10.3.0.5876
* **Database system and version:** MSSQL
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
Did I understand right that this just affects the `WHERE` clause in the `UPDATE`?
Which means, there is no primary key in that table, for why HeidiSQL puts all columns into the `WHERE` clause.

**Comment by lakebranch** [comment]
It affects the `WHERE` clause, yes. I wondered about the primary key thing as well, but this table has a primary key.

![image](https://user-images.githubusercontent.com/1404888/74334698-b11d2100-4d9a-11ea-8dc2-f28cd9114586.png)

    UPDATE TOP(1) "TestDB"."dbo"."TestTable2" SET "TextField"='Test4' WHERE  "Id"=1 AND "TextField"='Test3';
    /* SQL Error (402): The data types text and varchar are incompatible in the equal to operator. */

**Comment by lakebranch** [comment]
All fields present in the `WHERE` clause is also affecting #867 (apart from the MSSQL related problem).

**Comment by ansgarbecker** [comment]
Thanks for the finding. This must definitely be fixed soon.

**Comment by lakebranch** [comment]
Verified, using the SQL log in the program, that the generated "key statement" really returns the correct primary key for my test table:

    SELECT *
    FROM "INFORMATION_SCHEMA"."KEY_COLUMN_USAGE" AS col,
    "INFORMATION_SCHEMA"."TABLE_CONSTRAINTS" AS con
    WHERE col.TABLE_SCHEMA='dbo' AND col.TABLE_NAME='TestTable2' AND
        col.TABLE_SCHEMA=con.TABLE_SCHEMA AND col.TABLE_NAME=con.TABLE_NAME AND
        col.CONSTRAINT_NAME=con.CONSTRAINT_NAME;

Returns 1 row with `COLUMN_NAME=Id` and `CONSTRAINT_TYPE=PRIMARY KEY`.

**Comment by ansgarbecker** [comment]
Yes, I suppose the key is just not used due to some wrong logic. Will check that.
