### ISSUE TITLE
Tiny error window with no close button dark theme

### ISSUE THREAD

**Issue by neobenedict** [HeidiSQL/HeidiSQL#886]
## Steps to reproduce this issue

1. Step 1; Open Postgresql with dark theme
2. Step 2; Run a query producing an error
4. Then I get...

## Current behavior
https://i.imgur.com/Tfb5IjH.png

## Expected behavior
A working error box

## Possible solution
Fix the error box

## Environment
n/a

* **HeidiSQL version:** 
  
10.3.0.5876
* **Database system and version:** 
Postgresql but not relevant I think
  
* **Operating system:** 
Windows 10

**Comment by ansgarbecker** [comment]
Which theme is it exactly?

**Comment by zilzila** [comment]
Style Theme: "Carbon"
Icon pack: "Silk"
Windows 7 (classic theme, non-aero)

![изображение](https://user-images.githubusercontent.com/29956070/74275154-74164780-4d24-11ea-9804-01229bda4c5a.png)

In the "Carbon" theme, the form looks normal

**Comment by ansgarbecker** [comment]
Ok, then which theme is _not_ working then?

**Comment by neobenedict** [comment]
I can't reproduce this now, it fixed itself after a reboot, closing.
