### ISSUE TITLE
Default brace matching background too bright for dark themes

### ISSUE THREAD

**Issue by zilzila** [HeidiSQL/HeidiSQL#887]
## Steps to reproduce this issue

1. Open Preferences;
2. Choose style theme "Carbon";
3. Restarrt HeidiSQL;

## Current behavior

All in one picture :)
![изображение](https://user-images.githubusercontent.com/29956070/74277547-ca858500-4d28-11ea-9c0e-dd31415eab48.png)

1. When you select an entry in the tree list, the text remains white on a light background - nothing is visible. 
![изображение](https://user-images.githubusercontent.com/29956070/74279640-5816a400-4d2c-11ea-8ff2-feb2c091e942.png)

2. The background of the paired brackets selection is too bright.
3. Dark text on a dark background
4. Light text on a light background
5, 6 - no comments, everything is obvious :)
...and 7. URL text is too dark on dark background
![изображение](https://user-images.githubusercontent.com/29956070/74279778-a035c680-4d2c-11ea-8ff4-632bfeeb689c.png)

I looked at other dark themes, it's all about the same.

## Expected behavior

More user-friendly colors

## Environment

* **HeidiSQL version:** 
  
HeidiSQL 10.3.0.5877
* **Operating system:** 
  
Windows 7 x64 SP1 in VirtualBox. Classic windows theme or aero - does not matter, the same result.

**Comment by zilzila** [comment]
In Windows 10, everything is the same except for the cursor background - it's OK there.
![изображение](https://user-images.githubusercontent.com/29956070/74281493-9792bf80-4d2f-11ea-8eac-c84b10ee433f.png)
BTW, display mode in Windows 10 host is 1920x1080 actually, like in guest Windows 7...

**Comment by ansgarbecker** [comment]
I guess VirtualTree does not support Windows 7 with these too light colors. Feel free to ask in their tracker.

Colors in points 3, 4 and 7 look ok to me.

Point 5 and 6 are unclear to me. If you mean that crash, that must go in a different ticket, along with the callstack text file.

**Comment by zilzila** [comment]
> Point 5 and 6 are unclear to me. If you mean that crash, that must go in a different ticket, along with the callstack text file.

No, I did not mean this crash, it is only to show the color in these forms, how these forms look with a dark theme

**Comment by ansgarbecker** [comment]
The crash window is part of the madExcept handler, an external component which I cannot modify.
The only part I should fix is the brace matching color, which I should set to a fitting color for dark themes:

![grafik](https://user-images.githubusercontent.com/7986591/74409153-6cdf5e80-4e36-11ea-9e28-38c1269762a7.png)

**Comment by ansgarbecker** [comment]
New matching brace colors for dark themes:
![grafik](https://user-images.githubusercontent.com/7986591/157182007-2351ab8a-5054-431e-a190-1b977120ab7f.png)

Please reset your theme once after updating to the latest nightly.
