### ISSUE TITLE
Unable to select the "Export Grid Rows" feature in HiediSql v10.3.0.5771

### ISSUE THREAD

**Issue by torressam333** [HeidiSQL/HeidiSQL#888]
## Steps to reproduce this issue

1. Sign in to your mysql DB using HiediSQL client
2. Highlight one or more rows in any one of your DB tables.
3. Go to Tools
4. Try to select the "Export Grid Rows" option under Tools.

## Current behavior

When I open a mysql database and go to a particular table and then highlight the row I want to export as an INSERT in order to use in another schema, the option under the Tools menu is grayed out.

## Expected behavior

I expect the "Export Grid Rows" option to not be grayed out in order to allow me to export specific rows in my db as INSERT statements to be used in other schemas.

## Possible solution

Unsure why this option is grayed out under "Tools->Export Grid Rows"

## Environment

Using Windows, Heidisql v 10.3.0.5771

* **HeidiSQL version:** 
  
* **Database system and version:** 
  Heidisql v 10.3.0.5771

**Comment by ansgarbecker** [comment]
Please (always) use the latest build when reporting bugs. That ensures the issue is not already fixed, which was the case numerous times.

**Comment by zilzila** [comment]
HeidiSQL v10.3.0.5877 - not confirmed.
Option "Export Grid Rows" is not grayed out. Tested in MySql and PostgreSQL connections.

**Comment by ansgarbecker** [comment]
Thanks for your feedback! I suppose that was already fixed then.

**Comment by torressam333** [comment]
Updated and it worked just fine. Thank you for your response.
