### ISSUE TITLE
Primary Key column in results show truncated numbers

### ISSUE THREAD

**Issue by yphastos** [HeidiSQL/HeidiSQL#889]
## Steps to reproduce this issue

1. Step 1;
Make a query to any table including a primary key PK of type integer.

2. Result
It is not common, but sometimes, in the results section, the PK column shows visually truncated numbers:

![image](https://user-images.githubusercontent.com/13773388/74288085-20d6d180-4cf1-11ea-83fd-1688bbadded7.png)
(the last digits in the ID column appears truncated)

Sometimes it even happens only in some rows even in the same result set

![image](https://user-images.githubusercontent.com/13773388/74289572-0e5e9700-4cf5-11ea-9f74-dccc244e8f83.png)

And sometimes some digits are hidden completely:

![image](https://user-images.githubusercontent.com/13773388/73312915-75f1ee00-41ef-11ea-87cc-436c8ea2e98f.png)

Here, the first id should be 192810 (but it shows as 19281, with the last 0 hidden),
and the 3rd from bottom (192803) is slightly moved, triming a bit of the last '3'
Note that in the first row, since the 'local number format' option is used, it is evident that it is missing a digit, since the comma should have 3 digits to the right, so `192,81` looks 'wrong'.

I thought it only happened when using the 'local number format' option, but apparently is not the case: Here the option is turned off:

![image](https://user-images.githubusercontent.com/13773388/73313269-5e673500-41f0-11ea-95bc-783d74f3e1eb.png)

Note that despite how it shows, the data itself, if copied, does contain the correct whole numbers. It is only that it SHOWS truncated numbers.

I had another case in which ALL rows are missing the whole last digit, but I couldn't screenshot it.

## Current behavior
(see above)

Also, the problem sometimes 'fixes' itself. Sometimes it is enough to just hover over the results, or clicking on the 'wrong' cells, or simply re-running the query, scrolling if there are a lot of results, or even changing among query tabs.
but sometimes nothing seems to fix it for the particular query, and they stay like that until a new query is run.

I haven't found a consistent way of either replicating the issue, or to fix it.

## Expected behavior

The results should always show complete numbers, regardless of the 'local number format' option (which, as I mentioned before, seems to be irrelevant anyway)

![image](https://user-images.githubusercontent.com/13773388/74288183-5aa7d800-4cf1-11ea-954d-e8c72789a77b.png)

![image](https://user-images.githubusercontent.com/13773388/74288167-51b70680-4cf1-11ea-8187-3528a73a601f.png)

## Notes

It's been happening since quite a few builds now, more than 6 months ago, or even more, but haven't reported it before.
I'm not sure if it has always happened since 'local number format' is available, or since a particular build.

Also, I have only seen it on primary key columns, but I couldn't tell if it could happen in other columns (or of other data types).

I am using HeidiSQL with wine (4.0.3), so it may be part of the issue.

## Environment

* **HeidiSQL version:** 10.3.0.5869
  
* **Database system and version:** MySQL 5.1.73 and 5.5.62 
  
* **Operating system:** MacOS 10.14 (Mojave), using Wine 4.0.3 and also Wine 5.0

**Comment by ansgarbecker** [comment]
Looks like a font issue. Could you try a different font for grids? In Tools > Preferences > Grid formatting.

**Comment by yphastos** [comment]
Ok.

I've changed it to Verdana (from Tahoma before), and see what happens.

![image](https://user-images.githubusercontent.com/13773388/74350048-c2eecc00-4d7a-11ea-96c6-ddc3c8b67cec.png)

Just FYI...
Sadly a lot of fonts look wrong due to excessive anti-aliasing (I think), specially using a small size (7 in my case, which I prefer so more data fits on screen), so that is the one that looks good enough.

e.g. 

Monaco:
![image](https://user-images.githubusercontent.com/13773388/74350108-dbf77d00-4d7a-11ea-91fa-7c49aef63c65.png)

Consolas (hard to read):
![image](https://user-images.githubusercontent.com/13773388/74350378-44def500-4d7b-11ea-8e9d-dce96303a368.png)

JetBrains Mono (hard to read):
![image](https://user-images.githubusercontent.com/13773388/74350546-7952b100-4d7b-11ea-860b-3d63c64407c8.png)


Default (I guess Heidi chooses it, and looks like Tahoma), the numbers truncate:
![image](https://user-images.githubusercontent.com/13773388/74350285-22e57280-4d7b-11ea-9c5c-ca71e43d42e1.png)

I'll stick to Verdana and try.

Since the problem happens randomly (or haven't found out a certain way to replicate it), I'll let you know if I notice something.

Thanks.

**Comment by ansgarbecker** [comment]
Thanks for the update.

I will close this issue then, and mark it as documentation. Don't think I can do anything here.
