### ISSUE TITLE
Text editor doesn't fit to screen

### ISSUE THREAD

**Issue by chrysler5798** [HeidiSQL/HeidiSQL#89]
Hi !

## Expected behavior

When I open the text editor it should fit to the screen.

## Current behavior

When I open the text editor, it doesn't fit to the screen.
See this screen : 
https://image.noelshack.com/fichiers/2018/02/5/1515777125-2018-01-12-18-09-09.png
What's more buttons are hidden behind the Windows bar.

### Steps to reproduce

1. Click on a text field in a table
2. Click again to edit this
3. Click on 3 dots to open text editor.

### Context

I have 3 screens, and it probably comes from this, but as an intensive user of HeidiSQL, I use this text editor really often.

* HeidiSQL version: 9.5.0.5220
* Database system + version: MySQL 5.5.58
* Operating system: Windows 10

If you can fix this it would be awesome, otherwise, nevermind it's still the best database manager 😄 
Keep doing this amazing work !

(If you can add CTRL + S to save in text editor it would be so marvellous 👍 )

**Comment by chrysler5798** [comment]
Ah nice, didn't know about this shortcut.
Thanks for your quick answer 😄

**Comment by rentalhost** [comment]
**Confirmed:** the maximized status is not recovered after reopen the Text Editor.

**Comment by ansgarbecker** [comment]
The next build should restore the previous window size much better
* maximized state
* dimensions are stored only when not maximized - so if you set the window from "maximized" to "normal" it should have the same dimensions as it had when it was not maximized before. This was buggy yet - the maximized dimensions were restored.

**Comment by ansgarbecker** [comment]
What I thought is missing is restoring the _position_ of the window. I left that for now as it is (always centered on screen), as this may have implicit problems with multiple monitors.
