### ISSUE TITLE
Add field, select expression: UNIX_TIMESTAMP, syntax error.

### ISSUE THREAD

**Issue by id0612** [HeidiSQL/HeidiSQL#891]
## Current behavior

![image](https://user-images.githubusercontent.com/2449459/74315937-7b386680-4db3-11ea-8b36-01618232edfc.png)

## Environment

![image](https://user-images.githubusercontent.com/2449459/74316001-973c0800-4db3-11ea-9564-82f15fb0721c.png)

**Comment by ansgarbecker** [comment]
As far as I know, MySQL only allows `CURRENT_TIMESTAMP()` for date/time columns. `UNIX_TIMESTAMP()` returns an integer, not a valid date.
