### ISSUE TITLE
Support Unix linebreaks when saving SQL file

### ISSUE THREAD

**Issue by zilzila** [HeidiSQL/HeidiSQL#892]
## Steps to reproduce this issue

1. Open new Query tab;
2. Type several lines of SQL;
3. Save as SQL file;
4. Then I get... SQL file with CRLF

## Current behavior

Files are saved with Windows linebreaks (CRLF) and there is no option to save with UNIX linebreaks (LF)

## Expected behavior

Saving an SQL file with linebreaks set in Preferences

## Possible solution

Adding to Preferences the "Default linebreak style" option for the "SQL" tab, as for the "Data editors" tab, where you could select the linebreak style for saving the file.

**Comment by ansgarbecker** [comment]
As a Windows app, HeidiSQL of course uses Windows style line breaks.

Where's the use case for having other line breaks? Keep in mind that this would not affect the data in tables, only the remaining line breaks in the file.

**Comment by zilzila** [comment]
For example, when committing to a Git repository on UNIX.
Although Git can be configured with the "autocrlf" option to automatically convert, the files in the project will remain with CRLF.

And it doesn’t look very attractive if you look in the editor:
![изображение](https://user-images.githubusercontent.com/29956070/74342565-ba1dea80-4dba-11ea-8e7a-5d113d0e3a43.png)
This is not critical, just a suggestion. Many Windows [dev] programs have a linebreak option.

**Comment by zilzila** [comment]
Another example, about affecting data in tables:
If we save this (or similar) query to `crlftest.sql`
```sql
select
    '
     string1
     string2
     string3
    '
;
```
and then use it in command line `psql < crlftest.sql` or script, we'll receive result:
```sql
?column?
-------------
 \r            +
      string1\r+
      string2\r+
      string3\r+

(1 row)
```
Although the linebreak LF (UNIX) is set on the "Data editors" tab, and we sure that CR line endings should not appear in the data... but here it is.

**Comment by ansgarbecker** [comment]
Quite special special use case, that `psql` thing. Hmm.

For the editor issue displaying "^M", I'd say the issue is that the editor does not handle Windows linebreaks.

However, I will leave this open, as that does not sound so bad to have a linbreak option. I would only prefer having that option in the save-as dialog, not in the preferences window.

**Comment by zilzila** [comment]
Ok, thanks!
It would be great if the selected linebreak style would be saved in the settings (portable_setting.txt or Windows Registry).

**Comment by ansgarbecker** [comment]
Yes, once set, it should be restored the next time one saves a file.
Also, the setting must be internally stored for cases where one presses <kbd>Ctrl+S</kbd> to save the opened file without the dialog.
