### ISSUE TITLE
Set default value NULL for a field type text of a mysql table doesn't works (v10.3)

### ISSUE THREAD

**Issue by yourchoice** [HeidiSQL/HeidiSQL#893]
Set default value NULL for a field type text of a mysql table doesn't works (v10.3.5877)

MySql version 5.7.26

![image](https://user-images.githubusercontent.com/531720/74335225-6a342900-4da4-11ea-861a-d8f870aee2a0.png)

Another strange thing, even I set collation utf8_general on the entire database, now (with the last version) I see on export for each field (text, varchar) add this collation.

Sorry, now I see, was .5877 is a nigthly build. So i rolled bak to the previous and all ok

**Comment by ansgarbecker** [comment]
Ok, I'll close this one, as you say it's already fixed.
