### ISSUE TITLE
Feature request: Set default sql-file name for "Export database"

### ISSUE THREAD

**Issue by Commifreak** [HeidiSQL/HeidiSQL#894]
Currently, Heidi remebers the last path & filename for the Export-option. On top of that it would be great, if heidi could just replace the filename with the database name to be exported. :)

![Unbenannt](https://user-images.githubusercontent.com/87267/74408613-3228f680-4e35-11ea-96f9-202385d3adc0.JPG)

**Comment by ansgarbecker** [comment]
This is already doable, with the filename patterns I added in 4662ebf31ebcebf289bd1f19654dd06d742e87b8:

![grafik](https://user-images.githubusercontent.com/7986591/74428013-80032600-4e58-11ea-99fa-4efc8bdf6d99.png)
