### ISSUE TITLE
Autoclosing of Search and Replace is inconvenient

### ISSUE THREAD

**Issue by AlexLunyov** [HeidiSQL/HeidiSQL#896]
## Current behavior

Find and Replace window automatically closes after pressing buttons in it. Mostly it is inconvenient.

![image](https://user-images.githubusercontent.com/43061117/74511012-0893cc00-4f16-11ea-86de-8551ffb7ce81.png)

## Expected behavior

Should have a checkbox like "autoclosing".

## Environment

* **HeidiSQL version:** 
10.3.0.5877

  
* **Database system and version:** 
  
* **Operating system:** 
Windows 10 Pro

**Comment by AlexLunyov** [comment]
Please, fix it if possible. Thanks.

**Comment by ansgarbecker** [comment]
Next build does not auto-close the dialog if the search did not find occurrences.

**Comment by omzy** [comment]
> Next build does not auto-close the dialog if the search did not find occurrences.

That's useful but it would be even more useful if the search and replace dialog did not autoclose even when searches ARE found.

Sometimes I need to perform multiple different replacements and it's a bit annoying having to reopen the dialog each time.
