### ISSUE TITLE
last active/selected session no longer scrolled into view on startup

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#897]
[session manager]

looks like a regression from 10.2 -> 10.3 (latest build)

**Comment by ansgarbecker** [comment]
Please don't delete the issue template. Issue reports tend to get shorter and more unclear here.

Well, in this case I know what you mean. So, I just checked that and saw `ScrollIntoView` is still called. But the recent update of VirtualTree to v7.3 contained a change in that procedure, for https://github.com/Virtual-TreeView/Virtual-TreeView/issues/897 . I suppose I now need to call `ScrollIntoView` later, when its handle is allocated.
