### ISSUE TITLE
Provide column names of selected table in query auto completer

### ISSUE THREAD

**Issue by Koopzington** [HeidiSQL/HeidiSQL#9]
I know this has been discussed before in the forum but i'd really like to see autocompletion for columns inside the Query Editor window without having to prefix everything with table names beforehand.
In the old discussion there were concerns about performance since some users might have databases with thousands of columns and therefore i'd like to offer a compromise:

If you have a table selected in the tree, the columns of the currently selected table are actually available in the list right next to the query editor. So why not add the columns of the currently selected table to the autocompletion list? 
PhpMyAdmin actually does this when you use the query tab while working 'inside a table'.
In addition to that you could also add columns from more tables once they're mentioned in the query.
The autocompletion process might also be able to decide to optionally prefix a column with the table name in case it is ambigious.

**Comment by ansgarbecker** [comment]
Finally.. got them:

![grafik](https://user-images.githubusercontent.com/7986591/86639771-c6a91680-bfd9-11ea-99fa-19e2832ac317.png)
