### ISSUE TITLE
Increase max dropdown item count in MySQL collation ComboBox

### ISSUE THREAD

**Issue by zufuliu** [HeidiSQL/HeidiSQL#90]
## Expected behavior
There are many collations in MySQL starts with same letter, it's not easy to select one from the short drop down list. Make the list longer will make it easy for scroll and select.

```sql
SHOW COLLATION LIKE 'u%';                    -- 175 collations
SHOW COLLATION LIKE 'utf8\_%';             -- 34 collations
SHOW COLLATION LIKE 'utf8mb4\_%';      -- 33 collations
```

## Current behavior

Only 8 collations in the drop down list.

## Context

* HeidiSQL version: 9.5.0.5200
* Database system + version: MariaDB 10.2.12
* Operating system: Win10

The collation ComboBox  appears in Table Options -> Default collation and Columns Collation.

**Comment by fifonik** [comment]
I'd like this to be implemented as using so small dropdown is not an easy task and I'm specifying collations for some columns quite often.

**Comment by ansgarbecker** [comment]
Reasonable

**Comment by zufuliu** [comment]
Sadly, just tried Version 9.5.0.5223 (64 Bit), the drop down item count in ComboBox  for Collation column in Table Columns list/grid remains 8, while it's 16 in Default collation ComboBox.

**Comment by ansgarbecker** [comment]
I knew there are more collation drop downs. Well, I can change that :)

**Comment by ansgarbecker** [comment]
Next build has 16 drop down items in all grid pulldowns - not only on the collations, but also in all data and query grids as well.
