### ISSUE TITLE
Saving snippet in the default empty tab - then cannot close tab

### ISSUE THREAD

**Issue by pwrfix** [HeidiSQL/HeidiSQL#901]
## Steps to reproduce this issue

1. Create SQL code in the default open empty SQL tab
2. Save the SQL code as a snippet
3. Cannot close the tab, there is no "X". So opening app results in the snippet file being opened each time and not being able to be closed.

## Current behavior

Snippet remains in tab after program restart. I would assume that disabling this feature would circumvent this, however.

## Expected behavior

Upon program start, the default tab is always blank and ready to use. If the snippet needs to be opened, create a new tab that can then be closed.

## Environment

Environment: Windows v10.0

* **HeidiSQL version:** 

Version 10.3.0.5771 (64 Bit)
Compiled on: 2019-12-11 10:26:17

**Comment by ansgarbecker** [comment]
This is intentionally. You can, however, unload the text by double-click on the tab. But the default tab cannot be closed, so especially newbies always see where to run some query. If you want it to close, this is a duplicate to issue #365

**Comment by pwrfix** [comment]
Thank you.
