### ISSUE TITLE
Cannot see SP's body changes when Parameters tab is active

### ISSUE THREAD

**Issue by fifonik** [HeidiSQL/HeidiSQL#903]
## Steps to reproduce this issue

1. Create blank SP 'x';
2. Switch to Parameters tab and key in 'asd'. You will not see cursor in SP's body nor types characters;
3. Switch to Options tab and you will instantly see that the 'asd' were actually added in the SP's body;

## Possible solution

* **HeidiSQL version:** 
10.3.0.5887
* **Operating system:** 
Windows 10 1803

**Comment by ansgarbecker** [comment]
I suppose Heidi is lost in an endless loop somewhere, as my task manager says it uses a full processor core when the parameters tab is active:

![grafik](https://user-images.githubusercontent.com/7986591/75092396-57291200-5577-11ea-91f6-4b9475332e14.png)

**Comment by ansgarbecker** [comment]
Should be fixed in the next build.
