### ISSUE TITLE
Feature Request: Multi-Line editing

### ISSUE THREAD

**Issue by WesleyM77** [HeidiSQL/HeidiSQL#905]
## Current behavior

Can only edit one line at a time.

## Expected behavior

Allow us to edit text on multiple lines at once.

## Example

![2020-02-19_08-38-03](https://user-images.githubusercontent.com/22208037/74840495-16ba6180-52f5-11ea-9440-d2acc6758352.gif)

My example is rather rudimentary, but there have been plenty of instances in more complex queries where I've wanted to have multi-line editing. In the case of PHPStorm, a middle click and drag will put multiple cursors, as well as alt-clicking.

**Comment by ansgarbecker** [comment]
This should be rather posted to the [SynEdit tracker](https://github.com/SynEdit/SynEdit), which is the underlying component of that SQL editor in HeidiSQL.
