### ISSUE TITLE
Consider column header text in "Size All Columns to Fit"

### ISSUE THREAD

**Issue by Dibbyo456** [HeidiSQL/HeidiSQL#906]
This is what Columns looks like at first after opening heidisql:

![heidisql_2020-02-22_12-00-07](https://user-images.githubusercontent.com/18257605/75087845-5d18f600-556b-11ea-8448-b625cc521de9.png)

This is what Columns looks like at first clicking "Size All Columns to Fit":

![heidisql_2020-02-22_12-00-28](https://user-images.githubusercontent.com/18257605/75087860-85a0f000-556b-11ea-9808-5ef095dc7ccb.png)

This is what Columns **should look like** after fitting:

![heidisql_2020-02-22_12-00-59](https://user-images.githubusercontent.com/18257605/75087873-aa956300-556b-11ea-9ca6-8a57b05c1c01.png)

Version: 10.3.0.5771 (64 Bit)
Windows 10 (64 Bit)

**Comment by ansgarbecker** [comment]
Confirmed - column headers should be considered, not only the values.

**Comment by Dibbyo456** [comment]
> Confirmed - column headers should be considered, not only the values.

I think column headers and column values both should be considered.

**Comment by Dibbyo456** [comment]
Hello. I was wondering if you had the time to fix it.
It is probably on very low priority, but I use this feature every single time.

**Comment by ansgarbecker** [comment]
Since July 2019, (https://github.com/JAM-Software/Virtual-TreeView/commit/b6e5e549e1c884a198f77cea1423b166facb2d18) this seems to be supported directly in VirtualTree. I will just have to activate `hoAutoResizeInclCaption`

**Comment by ansgarbecker** [comment]
This looks a bit funny now:
https://www.heidisql.com/files/auto-resize-with-caption.gif

**Comment by Dibbyo456** [comment]
Looks perfect now.
