### ISSUE TITLE
Comment error (in mysql) (sql error 1064)

### ISSUE THREAD

**Issue by anselal** [HeidiSQL/HeidiSQL#907]
## Steps to reproduce this issue

1. Step 1; Comments in sql are double dashes followed by a space
2. Step 2; If you start a line with double dashes and no space, the line will be displayed as a comment
3. If you run your code you will get a SQL Error 1064 on that line

This is happening since at least version 9 of HeidiSQL

## Current behavior

Comments are not properly validated. Double dash is parsed as a comment

## Expected behavior

double dash followed by a space should be treated as a comment.

## Possible solution

Do not display the line as a comment if it starts with just double dashes (--) and no space after.

## Environment

I don't think that this issue is cause by my env but just in case

HeidiSQL 10.3.0.5896
Windows 10 Pro 64bit
MySQL 5.5.62

**Comment by ansgarbecker** [comment]
This should be fixed in the underlying SynEdit component, see https://github.com/SynEdit/SynEdit/issues/42
