### ISSUE TITLE
auto_increment is disappearing 

### ISSUE THREAD

**Issue by ecxod** [HeidiSQL/HeidiSQL#909]
## Steps to reproduce this issue

1. Make this : ALTER TABLE `table`
	CHANGE COLUMN `id` `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT FIRST;
2. Heidi  sets the AUTO_INCREMENT
[...]
3. Heidi "eats" it immediately.

## Current behavior

it don't let you set auto_increment

## Expected behavior

let you set auto_increment

## Possible solution
 dunno

## Environment

Revision 5896
Compiled: 2020-02-23
Windows 6.1

**Comment by leeoniya** [comment]
just ran into this in 5901, so 👍 from me.

another related issue with this is that manually created/added records in the data grid fail to populate the auto-increment column (it remains empty).

**Comment by ansgarbecker** [comment]
Should be fixed in the next build

**Comment by ecxod** [comment]
no hurry:)
what GUI do you use for development?

**Comment by ansgarbecker** [comment]
Delphi 10.3
