### ISSUE TITLE
"Ask for credential" to use SSH private key

### ISSUE THREAD

**Issue by Zulgrib** [HeidiSQL/HeidiSQL#91]
## Expected behavior

Being able to not store private key's password in HeidiSQL and have the software ask for it before each use.

## Current behavior

There are no radio button for end user to allow this in SSH tab.

**Comment by ansgarbecker** [comment]
Should there be some password box in the SSH tab, or...?

**Comment by endo64** [comment]
I think @Zulgrib means password box for private key file. But I don't think it is necessary to keep password for private key file in HeidiSQL's settings, if you need to use your key file without password then you have to remove it [How to remove a private key password using OpenSSL
](https://knowledge.rapidssl.com/support/ssl-certificate-support/index?page=content&id=SO5292)

**Comment by Firesphere** [comment]
I don't want to remove the password from my SSH key. But I can't enter the password for my SSH key in the HeidiSQL popup, it would be nice if that could be fixed, as it's, for now, the only reason I still sometimes start MySQLWorkbench

**Comment by ansgarbecker** [comment]
Related: #129

**Comment by ansgarbecker** [comment]
Prompting for key passphrase is handled in #284 - and already on the roadmap for the next release.
