### ISSUE TITLE
Add option to export grid rows with blank NULL value

### ISSUE THREAD

**Issue by stephenkreusch** [HeidiSQL/HeidiSQL#910]
## Steps to reproduce this issue

1. Run query.
2. Export grid rows.
3. Set output format to Excel CSV.
4. Choose any NULL value, e.g. NUL character.
5. Select OK.
6. Open CSV in Excel or any other program.

## Current behavior

CSV contains NULL value like \0.

## Expected behavior

Should have option to set NULL value to blank, so that characters like \0, \b, etc. do not appear in the CSV output.

## Possible solution

Add option to set NULL value to <blank>.

## Environment

HeidiSQL version: 10.3.0.5771

**Comment by ansgarbecker** [comment]
Did you try to just leave the value blank?

![grafik](https://user-images.githubusercontent.com/7986591/75277143-c6b53080-5807-11ea-9ba3-ee6289fcaf77.png)

**Comment by stephenkreusch** [comment]
Thanks, didn't try this.  Seems to work OK.
