### ISSUE TITLE
DATE column gets length 65535 when following a TEXT column

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#918]
## Steps to reproduce this issue

also DATETIME is detected with length 0.

i actually cannot reproduce it when creating new tables with the same CREATE code, so i'm not sure what black magic Heidi uses to detect and display this. would be happy to provide any additional logs.

i discovered this through a potential side-effect in the data grid: when setting a DATE field in the grid (from NULL), Heidi defaults to `2020-02-27.000000000000000000000000000....` (total length with all zeros is 65,546) instead of `2020-02-27`.

## Current behavior

![image](https://user-images.githubusercontent.com/43234/75469113-08eb8880-5954-11ea-91e2-6330a610de9e.png)

## Expected behavior

![image](https://user-images.githubusercontent.com/43234/75469264-536d0500-5954-11ea-9d0a-37bd26b5857b.png)

## Environment

* **HeidiSQL version:** 10.3.0.5901
  
* **Database system and version:** Percona 5.6.21
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
Please post the result of `SHOW CREATE TABLE yourtable` here. There must be some additional setting for that DATE column, as I too cannot reproduce it here.

**Comment by leeoniya** [comment]
i managed to reduce it:

```sql
CREATE TABLE `orders_test5` (
  `comments` text,
  `invoice_date` date DEFAULT NULL,
  `shipped_on` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT
```

however, heidi's `CREATE code` tab shows:

```sql
CREATE TABLE `orders_test5` (
	`comments` TEXT(65535) NULL DEFAULT NULL COLLATE 'latin1_swedish_ci',
	`invoice_date` DATE NULL DEFAULT NULL,
	`shipped_on` DATETIME(0) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
ROW_FORMAT=COMPACT
;
```

removing the `comments` field seems to "fix it" in the table editor. so maybe a CREATE parsing issue, then?

**Comment by ansgarbecker** [comment]
Embarassing bug, just fixed it, plus made some additions to prevent length of "0" for date/time columns.

**Comment by leeoniya** [comment]
thanks!

DATETIME still seems to allow Length/Set editing in the table editor, while DATE has Length/Set properly disabled.

**Comment by ansgarbecker** [comment]
Yes, the DATETIME or TIMESTAMP types can include a trailing fractional seconds part in up to microseconds (6 digits) precision. (taken from the [docs](https://dev.mysql.com/doc/refman/5.7/en/datetime.html))

**Comment by leeoniya** [comment]
touché
