### ISSUE TITLE
Feature Request: MSSQL via SSH tunnel

### ISSUE THREAD

**Issue by cehser** [HeidiSQL/HeidiSQL#921]
Currently, there is no option to connect to MSSQL via SSH tunnel as there is for MySQL/MariaDB and PostgeSQL. This means I have to run plink.exe manually before connecting to the DB (which is working perfectly btw). 

It would be great if there was a built-in option to connect to MSSQL(TCP/IP) via SSH tunnel.

**Comment by ansgarbecker** [comment]
Related:
* #78
* https://www.heidisql.com/forum.php?t=35740

**Comment by mindc** [comment]
Any progress with this?

**Comment by ansgarbecker** [comment]
I am on the way to add SSH support for MS SQL. I suppose it makes sense to enable support for the network type "Microsoft SQL Server (TCP/IP)" only. Or does it make sense to support the other ones as well, like named pipe, SPX/IPX etc.?

**Comment by cehser** [comment]
Great news. Yes, it only makes sense for TCP/IP. Thanks for catching up on this!

Christoph
________________________________
Von: Ansgar Becker ***@***.***>
Gesendet: Tuesday, January 10, 2023 7:56:02 PM
An: HeidiSQL/HeidiSQL ***@***.***>
Cc: cehser ***@***.***>; Author ***@***.***>
Betreff: Re: [HeidiSQL/HeidiSQL] Feature Request: MSSQL via SSH tunnel (#921)


I am on the way to add SSH support for MS SQL. I suppose it makes sense to enable support for the network type "Microsoft SQL Server (TCP/IP)" only. Or does it make sense to support the other ones as well, like named pipe, SPX/IPX etc.?

**Comment by ansgarbecker** [comment]
Next build has the SSH tunnel checkbox enabled for SQL Server TCP/IP. Activating it requires to add user and password or key file. Note the SSH host is unlikely to support these named instances which SQL Server locally supports, so you will need to enter an IP or hostname.

![grafik](https://user-images.githubusercontent.com/7986591/211644208-e82314a1-247c-4408-a345-09353e3ee2c7.png)

**Comment by ansgarbecker** [comment]
Closing this.

If there is anything which does not work as expected please shout. I'm currently not able to test this myself here.
