### ISSUE TITLE
Remove fractions of seconds from Excel CSV format

### ISSUE THREAD

**Issue by nummacway** [HeidiSQL/HeidiSQL#922]
## Steps to reproduce this issue

1. Execute a query that returns a date/time datatype that has fractions of seconds. I'm using MSSQL datetime datatype in this example.
2. Export to Excel CSV.
3. Open in Excel. I'm using 2016.

## Current behavior

Date/time values are considered strings by Excel.

## Expected behavior

Date/time values are considered date/time values by Excel.

## Possible solution

Remove fractions of seconds in Excel CSV format OR add an option to do that. In a feature that says "Excel CSV", I'd expect a format that is interpreted correctly by Excel always or by default.

## Current workaround

Manually select `CONVERT(varchar, columnname, 20) columnname` (MSSQL) instead. 20 is the name of the correct format.

## Environment

* **HeidiSQL version:** 5906 (current nightly)
* **Database system and version:** MSSQL

**Comment by igitur** [comment]
I can't replicate your problem. My Excel recognises the clipboard contents as valid date time values. 

What is your regional settings for date formats?

**Comment by nummacway** [comment]
Do you actually have fractions of seconds in your result? If so, please post a line of your export.

As an example, create the following CSV file and open with Excel:
`"2018-01-01 10:10:10.000"`
Opening that file in Excel results in a Text-type cell.

I found out that Excel does support centiseconds but fails with milliseconds, so HeidiSQL might drop/round fractional digits until there's only 2 of them.

**Comment by igitur** [comment]
Here is my clipboard contents after copying from HeidiSQL and what I paste into Excel:
```
"COLUMN1"
"2020-03-04 23:09:48.167"
"2020-03-04 23:09:48.167"
"2020-03-04 23:09:48.167"
"2020-03-04 23:09:48.167"
"2020-03-04 23:09:48.167"
"2020-03-04 23:09:48.167"
"2020-03-04 23:09:48.167"
"2020-03-04 23:09:48.167"
```
And then I see
![image](https://user-images.githubusercontent.com/145854/75955220-122da580-5ebe-11ea-9873-c0b957f25c8c.png)

which after formatting properly is:
![image](https://user-images.githubusercontent.com/145854/75955260-270a3900-5ebe-11ea-9c53-da304b0be637.png)

**What is your regional settings for date formats?**

**Comment by nummacway** [comment]
German (Germany).

**Comment by igitur** [comment]
When I set my region format to `German (Germany)` I get the same problem as you. If I change the clipboard contents and replace the `.` with `,`, then Excel recognises it. Example, this works in German locale:

```
"COLUMN1"
"2020-03-04 23:09:48,167"
"2020-03-04 23:09:48,167"
"2020-03-04 23:09:48,167"
"2020-03-04 23:09:48,167"
"2020-03-04 23:09:48,167"
"2020-03-04 23:09:48,167"
"2020-03-04 23:09:48,167"
"2020-03-04 23:09:48,167"
```



@ansgarbecker I assume you're deliberately using ISO8601 date format here. I can't find any documentation on what the ISO8601 format is when milliseconds are included. One would think the second to millisecond symbol would be locale agnostic?

**Comment by igitur** [comment]
From https://stackoverflow.com/a/50570660/179494

```
 If necessary for a particular application the lowest order component may have a decimal fraction. The decimal fraction shall be divided from the integer part by the decimal sign specified in ISO 31-0: i.e. the comma [,] or full stop [.]. Of these, the comma is the preferred sign. If the magnitude of the number is less than unity, the decimal sign shall be preceded by a zero (see ISO 31-0);
```

So, @ansgarbecker , it looks like you should be using the configured locale to format the decimal symbol.

**Comment by nummacway** [comment]
Does comma work on English locale?

**Comment by igitur** [comment]
> Does comma work on English locale?

No

**Comment by ansgarbecker** [comment]
Excel now gets the locale decimal point (here with German locale):

```
"SERVER_NAME"	"DECOMM_ON"	"CREATION_TIME"
"qq"	"2020-08-03 12:21:04,026"	"2020-08-03 12:21:10"
```

**Comment by ansgarbecker** [comment]
I will modify this solution and entirely remove milliseconds for Excel. Thanks to Excel I could not get any time format with milliseconds to display as it should.

**Comment by ansgarbecker** [comment]
Then please tell me what you are doing differently than me in Excel? I can't get such values displayed correctly, I just get decimal numbers or some other shit.

**Comment by ansgarbecker** [comment]
My remove was probably an over-reaction . But I definitely want to produce files with date/time values being displayed in Excel not as floats or such. I wonder what such a file looks like in your Excel?

**Comment by igitur** [comment]
> My remove was probably an over-reaction . But I definitely want to produce files with date/time values being displayed in Excel not as floats or such. I wonder what such a file looks like in your Excel?

I'll get back to you on this soon.

**Comment by igitur** [comment]
@ansgarbecker Please share your Windows locale setup, i.e. these settings in your control panel:

![image](https://github.com/user-attachments/assets/483f7300-1208-45ee-9e76-003899731128)
![image](https://github.com/user-attachments/assets/f648e19c-02a9-4be6-a747-075996ffe7c5)

**Comment by ansgarbecker** [comment]
Here we go:

![grafik](https://github.com/user-attachments/assets/790ac580-005f-4e76-bd13-22068b6f0f38)

![grafik](https://github.com/user-attachments/assets/09090e26-9d2f-4efc-a514-1844eed0085e)

**Comment by ansgarbecker** [comment]
@droni1234 I tried and failed several times. Thanks to Excel I could not get any time format with milliseconds to display as it should.
If you know how to format a time with milliseconds for Excel then please shed some light on that.

**Comment by ansgarbecker** [comment]
Let's discuss further things in #2098
