### ISSUE TITLE
Dont use Serif for the logo

### ISSUE THREAD

**Issue by gemal** [HeidiSQL/HeidiSQL#924]
Nice with a new logo but having Serif as the font in the logo does no good for it.

I really think the readability on small icons and screens the logo could be improved if you used Sans Serif

![image](https://user-images.githubusercontent.com/69105/75690172-ae7b6080-5ca2-11ea-9729-0cbb0c1ce562.png)

Also I see no Serif other places:
![image](https://user-images.githubusercontent.com/69105/75690092-9277bf00-5ca2-11ea-88ab-3146a5697072.png)

![image](https://user-images.githubusercontent.com/69105/75690249-cc48c580-5ca2-11ea-9acd-c6e596019c12.png)

**Comment by ansgarbecker** [comment]
Really?

Sigh.. well I see you're point.

**Comment by rentalhost** [comment]
Really, make sense. But taking advantage of the topic, the new icon, although more elegant, is practically unreadable in 16x16 (the upper part).

![image](https://user-images.githubusercontent.com/421851/75717201-6c0c5080-5caf-11ea-8e2e-f05b9414c45d.png)

**Comment by leeoniya** [comment]
FWIW, i liked the yellow in the previous logo more than the white in the new one.

/$0.02

**Comment by wrufeger** [comment]
The "new" logo in my opinion is ugly and almost unreadable. Fortunately the old one is still used in the uninstaller and I could use that one instead.

**Comment by ansgarbecker** [comment]
So you say I should bring back the old one?

**Comment by gemal** [comment]
I actually like the new logo, just with a minor "fix" for the serif font :)

**Comment by wrufeger** [comment]
I would return to the old icon as it was a recognizable CI for the last years. But in the end its your decision and its just an icon. Features, performance and stability are way more important.

**Comment by ansgarbecker** [comment]
Here's a new attempt, bringing most of the old style back:

![grafik](https://user-images.githubusercontent.com/7986591/76012192-2a311380-5f16-11ea-9f95-6bb27ad5e44c.png)

... here's the now less problematic 16px version:

![grafik](https://user-images.githubusercontent.com/7986591/76012230-41700100-5f16-11ea-833c-6add5cc770a0.png)

**Comment by rentalhost** [comment]
Maybe you can keep the new version, but for small versions (16px and 32px) you outline with a white color, so HS will be highlighted anyway.

How I don't have the source, so I did an (ugly) draft of Photoshop:

>32px version (keep same, but with Sans-serif):

![image](https://user-images.githubusercontent.com/421851/76016856-5a6bb880-5efc-11ea-9494-b25ddc7bd9e8.png)

32px version:

![image](https://user-images.githubusercontent.com/421851/76016893-6c4d5b80-5efc-11ea-8488-a63f3b178aee.png)

16px version:

![image](https://user-images.githubusercontent.com/421851/76016919-75d6c380-5efc-11ea-8e16-ada51308bbae.png)

The radius of white outline could be reduced for 32px version, and the letter could be increased for 16px version a very bit.

**Comment by eletroe** [comment]
Speaking of an icon that is practically unreadable in 16x16, in windows10 shortcuts it is missing.

But I really want to report the main ERROR: The Program is closing (does not respond) when the connection to the bank drops (Ex .: in cases of IP change)

**Comment by leeoniya** [comment]
> But I really want to report the main ERROR: The Program is closing (does not respond) when the connection to the bank drops (Ex .: in cases of IP change)

@eletroe please keep the discussion here on-topic.

https://github.com/HeidiSQL/HeidiSQL/issues/877 is already open for this - you would see this if you did a 30s issue search first. if you want to report something different than what's described there, please open a new issue.

**Comment by leeoniya** [comment]
no worries, i was not offended.

**Comment by ansgarbecker** [comment]
@rentalhost Thanks for your input. I just pushed exactly what you suggested, see the pdn file for Paint.net in the above commit. I think that's it.

**Comment by rentalhost** [comment]
@ansgarbecker what is the font family?
