### ISSUE TITLE
Create table code does not escape the string

### ISSUE THREAD

**Issue by lucashtc** [HeidiSQL/HeidiSQL#928]
## Steps to reproduce this issue
The default is not escaped in quotes, generating the error

1. Create a table or use an existing one;
2. Add a column of type ENUM;
3. Add default of one of the options inserted in the enum;
4. Save and try to use the generated create code
`
CREATE TABLE test (
	COLUMN_NAME ENUM("Y","N") NULL DEFAULT Y COLLATE 'latin1_swedish_ci'
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB;
`
The `NULL DEFAULT Y` section has the Y without the quotes, which causes the error
When using the option to copy the table, it also generates an error

## Current behavior
Create table code does not escape the string

## Expected behavior
default must enclose the string in quotes

* **HeidiSQL version:10.3.0.5906** 
  
* **Database system and version: Ubuntu 18 Mysql 5.7** 
* **Operating system:Windows 10**

**Comment by ansgarbecker** [comment]
My recent commit 43aec429c2fda09f787980231b5a1af1f1579971 should have fixed that. Please update HeidiSQL and report back if that now works.
Related forum link: https://www.heidisql.com/forum.php?t=35746

**Comment by lucashtc** [comment]
Problem solved.
Thanks. 
Sorry, I had not seen this issue.
