### ISSUE TITLE
MsSQL invalid value of timestamp field

### ISSUE THREAD

**Issue by netdoggy** [HeidiSQL/HeidiSQL#93]
Probably this is an overflow, the type of timestamp on the manual consists of 8 bytes

![mssql](https://user-images.githubusercontent.com/3543540/35014301-2157c43a-fb21-11e7-87a5-29d71518b68d.PNG)

**Comment by rentalhost** [comment]
Seems to be related to #34.

**Comment by netdoggy** [comment]
like the truth 
![heidi_binary](https://user-images.githubusercontent.com/3543540/36216066-cec9ffd0-11be-11e8-8717-f92d359dd9f3.PNG)

**Comment by rentalhost** [comment]
Thanks for you tests and report!

**Closing:** duplicated #34.
