### ISSUE TITLE
Highlight UI for remote server connections

### ISSUE THREAD

**Issue by rentalhost** [HeidiSQL/HeidiSQL#932]
**I must confess:** I already modified production server data due to human fault (in this case, my own human faults) and I had mini-strokes after. But who ever?

I wanted to suggest that it was possible to modify the HeidiSQL UI if the connection was from a remote server. In order to make it very clear that the change can cause irreversible damage if it is misapplied.

**So I would suggest the following modifications:**

- If hostname is `127.0.0.1`, `localhost` or `[::1]` should consider as local server, else all should be considered a remote server;
- If hostname is a local server or any modifications are safe (such as a remote test environment), but not matches with above possibilities, so we can [**check a box**](https://user-images.githubusercontent.com/421851/76096795-5fd10d80-5fa5-11ea-9546-b053de4a5862.png) (image) to consider as local server;
- During a remote server session, somethings should be changed:
  - The UI should be affected with a good highlight (like this [**ugly example image**](https://user-images.githubusercontent.com/421851/76097347-51372600-5fa6-11ea-9a37-1b36aae880cd.png) showing a red border around the main content);
  - Any first write procedure of current session should be confirmed ([**example image**](https://user-images.githubusercontent.com/421851/76097785-108bdc80-5fa7-11ea-9f57-658149351d36.png)). Eg.: when any operation like `TRUNCATE`, `DELETE`, `INSERT`, `ALTER`, `DROP`, `GRANT`, `SHUTDOWN`, `KILL` (and maybe for `CREATE`, `EXECUTE`, `LOCK TABLES`). Read-only operations should be allowed. So it will basically includes also when you try to edit some table or data;
  - You will be ask everytime, except if you mark "_do not ask anymore for this current session_". But should be considered if you are connected in two different sessions on same instance (so for each one you should be asked);

**FAQ**

- **Q: But why you are connecting with a full permission user if you want only to read on a remote server?**
  R: Not all servers are configured for read-only user, most that I worked on always give full permission (including `SHUTDOWN`).

**Comment by leeoniya** [comment]
i use mysql through a putty ssh tunnel, so the production server appears local but actually is not (it connects to 127.0.0.1:3307). if this is considered, then it should be possible to tag any server/session as "production".

another thing i've suggested before it to isolate query tabs to a specific server. if you're switching between staging and prod, it's easy to make a mistake. but a warning when executing dangerous queries against a server tagged "production" would also solve this nicely and i imagine with less effort. (but make sure the warning has a default focus on "Cancel").

**Comment by ansgarbecker** [comment]
Did you both ever use the session color setting? I am always using that to have a noticable visual hint on which server I am.

**Comment by rentalhost** [comment]
@leeoniya maybe instead of a checkbox, a select box like "Environment type: [automatic, production, development]", so you can force the mode.

@ansgarbecker I have tried, but it seems not be enough. The session color will only modify the background color of left side. I can use a red color, for instance, but it will be too much vivid and the text color will not be adapted. And write-SQL will not be avoided too.

**Comment by hthyme** [comment]
From my point of view it would be a big improvement, if the background color on the left side would match the background of the sql tab/query sheet on the right (maybe as an option to be set). Of course it would not prevent from doing wrong, but it's a great indicator. 
The background color of the query sheet would change if you change sessions - for that a 'pinned-to-session' or 'sticky' query option would help. But for me - in case I need multiple connections in parallel - I simply open multiple HeidiSQL instances. In that case the background colour would not 'switch' all the time... and (of course) the sticky querytabs are not needed.

**Comment by ansgarbecker** [comment]
Query result tabs now use the session color:

![grafik](https://user-images.githubusercontent.com/7986591/122939623-13fdcf80-d374-11eb-97cf-4c1184a743f3.png)

**Comment by hthyme** [comment]
Perfect, thanks for the implementation. That really helps.

In case you want to enhance the visual hints for execution of SQL as well and not only for query results, maybe the complete background-colouring of the SQL Edit window would help ... just an idea.

In the current version the background (and foreground/style) is defined 'by element', so a general "use session background YES/NO" checkbox could control whether or not to use the session coloring as SQL-edit-window background for all text elements by overriding the element-background setting - or not. 

![2021-06-22 16_36_47-Einstellungen](https://user-images.githubusercontent.com/73108725/122944869-73f67500-d378-11eb-8d9d-041dd780cc0d.png)

Please don't tell me it's already there and I did not manage to find it ... ;) 

As said, just an idea to enhance HeidiSQL even further. Colored Tabsheets already is a big plus.

**Comment by ansgarbecker** [comment]
Next build has the query gutter in the custom color:

![grafik](https://user-images.githubusercontent.com/7986591/122986963-5ccb7d80-d3a0-11eb-9dfd-212a68e857ec.png)

Note that the screen shows a result from the inactive (yellow) session, while the gutter follows the active (blue) session.

Using a "session background" setting for SQL color backgrounds would be an idea. The user just has to remember to set it again after switching the theme/style (from the general tab), as this auto-sets colors without asking the user.
