### ISSUE TITLE
Several productivity issues

### ISSUE THREAD

**Issue by doubledeej** [HeidiSQL/HeidiSQL#934]
There are several issues with HeidiSQL that are hampering my productivity.

1. The constant crashing... this has been ongoing for a very long time, and it seems to be getting worse, not better.  Even the non-beta releases are really bad about this. The application crashes on me _many_ times per day, mostly after it has been sitting unused for some period of time, but that isn't the only cause.  I often send bug reports, so hopefully the cause can be located.

2. Data editor doesn't stay in edit mode: Once I press F2 to enter edit mode, it doesn't stay in edit mode as I navigate to other cells in the grid.  I have to press F2 for every column.  This not only gets really tedious, but if I forget to tap F2 and start typing into a cell, it usually navigates away to another row, often leaving an incomplete row of data in the table.

3. Lack of support for UTC in date/time columns in the Insert Value context menu. Most datetime values in my databases are in UTC, as I support an international user base (seems as though this would be pretty common for websites).  There's a Date and Time option in the menu, but no UTC equivalent, so I have to mentally do the math and manually enter those values. I would think this would be an easy fix that many people would appreciate.

Thanks!

**Comment by ansgarbecker** [comment]
Please use the issue template, do not just delete it and report several issues in one ticket. Also, provide reproduction recipes, as exact as possible.
