### ISSUE TITLE
No UTC date options

### ISSUE THREAD

**Issue by doubledeej** [HeidiSQL/HeidiSQL#936]
## Steps to reproduce this issue

1. Right-click datetime column
2. Highlight Insert Value

There are no UTC date options

## Current behavior

There is an option to insert the local date and time, but no option for UTC date and time.

## Expected behavior

A "UTC Date and Time" option in the Insert Value submenu

Most developers utilize UTC dates and times in their databases. Without an option to insert this automatically, we have to do the mental math to calculate, then manually type in the value

## Possible solution

A "UTC Date and Time" option in the Insert Value submenu

## Environment

HeidiSQL version: All

**Comment by ansgarbecker** [comment]
I just added datetime, date, time and unix timestamp menu items in UTC versions, below the local items. I think the year option makes not so much sense for UTC. And gave them a "world" icon for a better distinction:

![grafik](https://user-images.githubusercontent.com/7986591/86946574-deec7300-c14a-11ea-9a83-a263546a003c.png)

**Comment by doubledeej** [comment]
Thank you, thank you!  Another donation coming your way...

**Comment by ansgarbecker** [comment]
Thank you!

**Comment by ryno1234** [comment]
@ansgarbecker, I have never noticed this before, but the UTC dates shown are not accurate for me and are showing a future time.

Here is the situation:

- My local system is in the Pacific Time Zone - it is currently 5:47
- My server is set to UTC where it is 13:47
- When I view the Heidi menu for inserting a UTC time, the time looks to be the actual UTC time + the time necessary to get from my local time to UTC time, thus putting the time into the future (8 hours).

I've never noticed this before and not sure if there is a setting I need to change or if there is a bug.

<img width="1892" height="885" alt="Image" src="https://github.com/user-attachments/assets/eb5ca8c2-8041-4f48-a4c0-cd08c0790195" />
