### ISSUE TITLE
Data editor doesn't stay in edit mode with Tab key

### ISSUE THREAD

**Issue by doubledeej** [HeidiSQL/HeidiSQL#937]
## Steps to reproduce this issue

1. Navigate to a table, or run a query
2. Click in the data grid to select a cell
3. Press F2 to edit the cell, make changes
4. Press Tab to move to the next cell

## Current behavior

HeidiSQL exits Edit mode, so F2 must be pressed again to edit the new cell

## Expected behavior

HeidiSQL stays in Edit mode so additional cells can be edited

## Possible solution

Once F2 has been pressed to enter Edit mode, stay in Edit mode until navigating to a new row, or the Enter key is pressed

## Environment

HeidiSQL version: 10.3.0.5913

**Comment by moving-bits** [comment]
Generally I really like this proposal, would be very useful indeed.

> Once F2 has been pressed to enter Edit mode, stay in Edit mode until navigating to a new row, or the Enter key is pressed

Can we stay in edit mode when entering a new row (and just leave it on pressing "enter" or maybe "ESC")? Would make multiple row edits much easier.

**Comment by ansgarbecker** [comment]
Related: #765 and #144

**Comment by ansgarbecker** [comment]
Just just tested several builds between v10.2 and v11.0, and could track it down to my update of VirtualTrees on Feb 05: b333de2913b5032ebb95f38b2df32e1de9e35a41 . Have to check the causing code change in that update.

**Comment by ansgarbecker** [comment]
The addition of `SetFocus()` on the tree, from https://github.com/JAM-Software/Virtual-TreeView/commit/de863b4417dfd98caffe8d0c283959b4842d2a82#diff-f0e42fc71610dd3d1ac9a5e4a9cdde2fR19256 causes the editor to end up immediately after it has been started.

**Comment by ansgarbecker** [comment]
This is fixed - unfortunately I am now causing a crash on Wine when leaving grid cell editor using <kbd>Enter</kbd>, reported in #1107

**Comment by mcvlad2000** [comment]
Main.pas
procedure TMainForm.AnyGridKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState);
...
 VK_NEXT: if (g = DataGrid) and (g.FocusedNode = g.GetLast) then actDataShowNext.Execute;
    else if Assigned(g.FocusedNode) then
     begin
       keybd_event(Key, 0, 0, 0);
       g.EditNode(g.FocusedNode, g.FocusedColumn);
     end;
  end;

**Comment by squarestar** [comment]
This is not functioning as intended in Version 12.1.0.6537 (64 Bit, Portable, Windows 10)

**Comment by RikaiDesign** [comment]
version 12.3.0.6654  not functioning as intended

**Comment by Makkeysn** [comment]
@ansgarbecker You posted, that this issue is fixed since Aug 6, 2020
I'm still having trouble with this issue using HeidiSQL 12.5.0.6677
So, am I doing something wrong? Or is there a setting to change the behavior of the editing mode?

**Comment by ansgarbecker** [comment]
My fix from 2020 there failed to solve the issue, so forget it.
This issue was already reopened by #1831 .
I spent so much time on this one I can't tell you if I find a solution ever.

**Comment by Makkeysn** [comment]
Well...sometimes the causes for small issues are the hardest du find :)
Anyways, thank for your great work!
