### ISSUE TITLE
Allow sorting by column name (and other columns) in the table structure view

### ISSUE THREAD

**Issue by mkoske** [HeidiSQL/HeidiSQL#939]
## Steps to reproduce this issue

1. Step 1; View table columns / structure
2. Step 2; How to sort column names alphabetically?
3. Seems not to be possible

## Current behavior

It seems not possible to sort column names alphabetically by column name (or other columns in structure view)

## Expected behavior

User should be able to sort columns by name (or by other fields like is the column nullable or not?)

## Environment

* **HeidiSQL version:**  10.3.0.5771 (64bit)
  
* **Database system and version:** MariaDB 10.4.11
  
* **Operating system:**  Windows 10 Pro 64bit

**Comment by ansgarbecker** [comment]
This was discussed in #115 . Please read that discussion and add relevant comments there.

**Comment by mkoske** [comment]
Ah, ok, thanks!
