### ISSUE TITLE
Black/invisible new and more buttons on Ubuntu 16.04 and Wine 2.0.4

### ISSUE THREAD

**Issue by ipkpjersi** [HeidiSQL/HeidiSQL#94]
## Expected behavior

I am expecting to see the new and more buttons.

## Current behavior

I see black new and more buttons, and then after a few seconds they become invisible.

## Failure information (for bugs)

This is a bug, just open the client and it happens. It seems that it happens only for the buttons with the drop-down menus.

### Steps to reproduce

1. Open HeidiSQL

### Context

* HeidiSQL version: 9.5
* Database system + version: any DB
* Operating system: Ubuntu 16.04 and Wine 2.0.4 (winehq-stable)

### Failure Logs
When you open it, it looks like this:
![](https://i.imgur.com/1SL3pxT.png)
Then after a few seconds like this:
![](https://i.imgur.com/KISW5ga.png)
This is the output in the terminal: 
![](https://i.imgur.com/T27nvJT.png)

**Comment by ragnar-lodbrok** [comment]
@ipkpjersi It may be related to your video driver, not HeidiSQL
As a workaround try to run Heidi in WindowsXP mode: type winecfg in the terminal 
You may also try wine staging (some apps) https://wine-staging.com/installation.html

**Comment by ipkpjersi** [comment]
Your comment helped me a lot, thank you. I found out that running in Windows XP mode DOES help, and I never knew about winecfg, only winetricks. It turns out I can make it so that my wine system level is Windows 10 and this specific application is Windows XP. I must admit that I am a bit perplexed why anything newer than XP/2003 results in this bug, but it does narrow it down and you did provide me with a suitable solution for my use case. Thanks again for the help.

**Comment by ansgarbecker** [comment]
This is probably still this one here: https://sourceforge.net/tracker/index.php?func=detail&aid=902470&group_id=74086&atid=539908

**Comment by ansgarbecker** [comment]
Hm, the above mentioned issue was not a _Wine_ issue but mainly on Windows, but it sounds so similar...
![grafik](https://user-images.githubusercontent.com/7986591/35771886-1c2534d6-0934-11e8-8f22-6cf5333098c6.png)

My just committed change may or may not help here. Please test the next build on Wine.

**Comment by ipkpjersi** [comment]
I'm unsure how to build it and likely don't have the time but if you can send me an EXE of it I can test it out.

**Comment by ansgarbecker** [comment]
The builds are automatically created via script on heidisql.com - so the exe is already there - please download from https://www.heidisql.com/download.php#nightlybuilds . Or, if that works, click Help > "Check for updates" in HeidiSQL, after connecting to some server.

**Comment by ipkpjersi** [comment]
Yup, that fixed it. Nice job! I will now close this issue.

**Comment by ansgarbecker** [comment]
Cool
