### ISSUE TITLE
"Restore defaults" doesn't work in Preferences

### ISSUE THREAD

**Issue by mbomb007** [HeidiSQL/HeidiSQL#942]
## Steps to reproduce this issue

1. Go to Tools -> Preferences
2. Click "Restore defaults"
3. Click OK

## Current behavior

Keybindings for Shortcuts stayed the same.

## Expected behavior

It resets them to defaults.

## Possible solution

Fix the Shortcuts Keybindings. They don't work. Also, I can't get a custom Redo keybinding to ever work.

## Environment

* **HeidiSQL version:** 10.3.0.5918 (64-bit)
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
You have to restart HeidiSQL in order to finish the "Restore defaults" process. Is that what you were missing?

**Comment by mbomb007** [comment]
Yes. It would be nice if there was a message explaining that...

**Comment by mbomb007** [comment]
Since I also mentioned Redo not working, I made it a separate issue.
