### ISSUE TITLE
First database name in the tree structure hardcoded to Main

### ISSUE THREAD

**Issue by sombraguerrero** [HeidiSQL/HeidiSQL#948]
![tree](https://user-images.githubusercontent.com/24618934/77266083-7dbc9480-6c6c-11ea-93f5-b078b06dd73f.png)

**Steps to reproduce this issue**
1. Select SQLite type.
2. Load either singular or multiple database files.
3. Open the session.

**Actual behavior**

Whether loading a single file or multiple, the first database name in the tree seems to be hardcoded to display as "main" rather than capturing the actual name of the database file, but yet when opening multiple databases, the database names are captured off their respective file names.

To illustrate the point, if I import the same file twice in the same pipe delimited string, like:
D:\Users\rsett\Documents\sqlite_test\25122.db|D:\Users\rsett\Documents\sqlite_test\25122.db|D:\Users\rsett\Documents\sqlite_test\63532.db|D:\Users\rsett\Documents\sqlite_test\65123.db|D:\Users\rsett\Documents\sqlite_test\stats.db

I'll get "main" in the first name, but 25122 will appear as another instance of that same file.

**Expected Behavior**
First database name and all subsequent database names should populate based off their filenames.

## Possible solution

Remove hardcoding.

## Environment

* **HeidiSQL version:** 
  Major Release 11 Revision 5922 (yours: 5922)
* **Database system and version:** 
  SQLite3
* **Operating system:** 
Windows 10 x64 1909

**Comment by ansgarbecker** [comment]
That "main" was hardcoded before I added support for multiple databases. Now the PostgreSQL library is queried for the database names:
```
SELECT * FROM pragma_database_list;
```
This returns "main" for the first opened database.

**Comment by sombraguerrero** [comment]
Oh, I see what you're saying now. I looked back at it in SQLite DB Browser. So that's literally just how the pragma gets defined when you use the database attachment feature. Got it.

**Comment by ansgarbecker** [comment]
So I suppose I could change that "main" to let's say the base filename of the database using the `sqlite3_db_config()` function, like described here: https://www.sqlite.org/c3ref/db_config.html
I think that's quite worth it, to have a more distinguishable database name in the tree.

**Comment by sombraguerrero** [comment]
I wasn't going to try and convince you, but I'm glad you agree!

**Comment by ansgarbecker** [comment]
Just having some problems with these pointers in Delphi.. again. Feel free to reply to my question: https://stackoverflow.com/questions/60862196/delphi-usage-of-sqlite3-db-config

**Comment by ansgarbecker** [comment]
Fixed!
