### ISSUE TITLE
Tab Key during table editing doesn't work

### ISSUE THREAD

**Issue by rlinhart** [HeidiSQL/HeidiSQL#950]
## Steps to reproduce this issue

1. Step 1; Click Add button from table column view
2. Step 2; Enter name of column
3. Step 3: Hit Tab Key on keyboard
4. Doesn't Tab to Database column, making it necessary for me to use my mouse, which slows me down.

## Current behavior

Hitting Tab Key doesn't advance to next column in Columns grid for table

## Expected behavior

Hitting Tab Key should advance to next column

## Environment

Windows 10 Professional

* **HeidiSQL version:** 
11.0.0.5919

* **Operating system:** 

Windows 10 Professional

**Comment by ansgarbecker** [comment]
Looks like a duplicate of #937 . Please shout if it's different.

**Comment by rlinhart** [comment]
different.

**Comment by ansgarbecker** [comment]
Well, in what way different then?
