### ISSUE TITLE
load and execture sql is not optimal

### ISSUE THREAD

**Issue by serak** [HeidiSQL/HeidiSQL#951]
is import and execute query using buffer_reader because i have an sql query of 1Gb and it took an hour to start executing it was loading and splitting query

**Comment by ansgarbecker** [comment]
Please fill out the fields in the issue template, do not just delete it.

I understand it took long to load a 1gb SQL file, but you really need to report more details, e.g. the used HeidiSQL version and the server version. If you report it, I'll reopen this issue.

**Comment by serak** [comment]
new case #954
