### ISSUE TITLE
Support project via GitHub Sponsors 

### ISSUE THREAD

**Issue by dunhamjared** [HeidiSQL/HeidiSQL#952]
I've been using this application professionally for years now and would love to sponsor it via GitHub Sponsors. 

Or sponsor @ansgarbecker directly? 

https://github.com/sponsors

**Comment by ansgarbecker** [comment]
Recently I decided to limit sponsoring to the existing Paypal and bank transfer methods, described on [heidisql.com](https://www.heidisql.com/donate.php#howto). So this Github program is not I want to participate as well.
