### ISSUE TITLE
load and execture sql is not optimal

### ISSUE THREAD

**Issue by serak** [HeidiSQL/HeidiSQL#954]
## Steps to reproduce this issue

is import and execute query using buffer_reader because i have an sql query of 1Gb and it took an hour to start executing it was loading and splitting query

1. Step 1; Right click on Query window and select load sql file
2. Step 2; select "Run files Directly"

## Current behavior

Then the whole HeidiSQL will hung

## Expected behavior

the query file should execute no matter the size of the file 

## Possible solution

it should commit on the desired number of queries

## Environment

* **HeidiSQL version:** 11.0.0.5919
  
* **Database system and version:**  MSSQL 2014
  
* **Operating system:**  Windows 10 v1909

**Comment by ansgarbecker** [comment]
Ok, much better now.

What does that 1gb file contain - I suppose many single INSERTs?
Please don't post sensitive data here, I just need to know the format.

**Comment by serak** [comment]
~1,000,000 Insert Queries and ~750,000 Update Queries, All single line

**Comment by serak** [comment]
Oh men the query was not having ";" at the end of each statement. i guess HeidiSQL is parsing that flag :( sorry you might close the issue after i did find and replace '\n' with ';\n' it is processing without any issue and without any hung.

**Comment by ansgarbecker** [comment]
Ah yes that explains it. HeidiSQL searches for semicolon, and eats all memory if it's after 1gb.
Thanks for your update!
