### ISSUE TITLE
Error during install process

### ISSUE THREAD

**Issue by enzodev** [HeidiSQL/HeidiSQL#955]
## Steps to reproduce this issue

1. Close HeidiSQL 10;
2. Open HeidiSQL_11.0.0.5919_Setup.exe; (I tried also with admin privileges, same behaviour)
3. Leave the default options;
4. Then I get an Access denied error while setup tries to access to "C:\Program Files\HeidiSQL\unins000.exe"

## Current behavior

Can't upgrade

## Expected behavior

Upgrade successful

## Environment

Windows 8.1 Pro 64bit ita

* **HeidiSQL version:** 
  
11.0.0.5919
* **Operating system:** 
  
  Windows 8.1 Pro 64bit ita
![screenshot](https://user-images.githubusercontent.com/7984553/77533360-074faa80-6e97-11ea-9b7d-57a86e6ed848.png)

**Comment by ansgarbecker** [comment]
Is that reproducible somehow? I cannot reproduce this issue, at least not on Win10.

**Comment by enzodev** [comment]
> Is that reproducible somehow? I cannot reproduce this issue, at least not on Win10.

I don't know, I just rebooted my OS and I still have the same issue. Maybe it's related to Win 8, I don't know.

**Comment by ansgarbecker** [comment]
Ok, but admin privileges should normally fix any kind of access denied problems when deleting a file, except if the file is in use or locked somehow. Could you delete your c:\Program Files\HeidiSQL\ folder (or move it elsewhere), and then try to reinstall?
Your settings are stored in the registry, not in that folder, so deleting the folder will not reset settings.

**Comment by enzodev** [comment]
I successfully renamed "C:\Program Files\HeidiSQL" as "C:\Program Files\HeidiSQL2" but when I launch install I get the same error in the screenshot

**Comment by ansgarbecker** [comment]
Oh, in that case this is indeed strange.

Not having a real clue why that happens. So I will update the InnoSetup installer from the currently used v6.0.3 to v6.0.4 . We will see if that helps.

**Comment by ansgarbecker** [comment]
@enzodev Meanwhile there was an update for InnoSetup 6.0.5, which I am now using for the current and coming builds. You could update then once again and test: https://www.heidisql.com/installers/HeidiSQL_11.0.0.6050_Setup.exe

**Comment by enzodev** [comment]
Comodo Antivirus detected a trojan in you exe and I can't install :(

**Comment by ansgarbecker** [comment]
I just checked on virustotal.com, and they say it's clean, according to various different anti virus engines: https://www.virustotal.com/gui/url/53b324629cd1cdb6bc8237cdf0a0a18716740667107c6f98d2097bf7d8619f8b/detection . Even "Comodo Valkyrie Verdict" says so, although I'm unsure if that's the same as yours.

**Comment by enzodev** [comment]
I update the virus database and I did a new scan of the file and this time no virus or trojan. I can launch the installer and install process worked fine.

**Comment by enzodev** [comment]
I can close this issue if you agree, new setup works fine

**Comment by ansgarbecker** [comment]
Super, thanks for feedback!
