### ISSUE TITLE
Multiple query result tabs in Material Dark theme are indistinguishable

### ISSUE THREAD

**Issue by renderse7en** [HeidiSQL/HeidiSQL#956]
## Steps to reproduce this issue

1. In a single blank Query tab, write multiple SELECT queries (e.g., "select top 100 * from table1; select top 100 * from table2; select top 100 * from table3, ...") 
2. Execute them.

## Current behavior

It makes individual tabs for each query below the SQL editor textbox, e.g., [table1 (1r x 21c)] [table2 (2r x 9c)] [table3 (10r x 49c)]
but there is no visual way to distinguish which tab is active. The tabs _above_ the editor box have a light blue strip at the bottom to show which tab is active, but the result tabs _below_ the editor do not.

## Expected behavior

The result tabs below the SQL editor textbox should get the same "active" styling as the tabs above it; that is, a light blue strip at the bottom of the tab.

![image](https://user-images.githubusercontent.com/25567567/77576358-163c5a00-6ea3-11ea-9d68-3e20a95dae4d.png)

## Environment

* **HeidiSQL version:** 
  11.0.0.5919 (though the issue was also present going back to 10.0)
* **Database system and version:** 
  SQL Server 2017
* **Operating system:** 
  Windows 10 x64

**Comment by ansgarbecker** [comment]
Please report that to https://github.com/CharlieEtienne/material-vcl

**Comment by renderse7en** [comment]
Will do, thanks!
