### ISSUE TITLE
Wrong width of buttons, labels for localized strings

### ISSUE THREAD

**Issue by WinterSilence** [HeidiSQL/HeidiSQL#957]
Cut localized strings:
![изображение](https://user-images.githubusercontent.com/3521094/77596340-ceeab380-6f0c-11ea-9150-34fd27ae8de9.png)
![изображение](https://user-images.githubusercontent.com/3521094/77596888-54bb2e80-6f0e-11ea-9ad6-2349a287431c.png)

**Need fix width of labels and buttons for localizations or/and add full local text as alt/hints displayed on hover.**

Version 10.0.0.5926
Windows 10
Locale ru_RU

**Comment by ansgarbecker** [comment]
Will widen these labels on the session manager and on the settings dialog. That's the easiest solution I see.

**Comment by ansgarbecker** [comment]
Next build leaves more space on the left labels. I suppose that does it.
