### ISSUE TITLE
How activate default snippets "Generate ..."?

### ISSUE THREAD

**Issue by WinterSilence** [HeidiSQL/HeidiSQL#958]
This menu items always readonly, how use it?
![изображение](https://user-images.githubusercontent.com/3521094/77597987-9ef1df00-6f11-11ea-9480-46e02faa620c.png)

**Comment by ansgarbecker** [comment]
These "Generate..." menu items use the selected column names within the top node "Columns in table...". You also need to have a table selected in the left database tree (which you did in your screenshot):

![grafik](https://user-images.githubusercontent.com/7986591/77614772-0ddd3100-6f2e-11ea-9697-8edb858be0b5.png)

**Comment by WinterSilence** [comment]
@ansgarbecker please, add this to manual 👍

**Comment by ansgarbecker** [comment]
Done - see https://www.heidisql.com/help.php#queries
