### ISSUE TITLE
Problem with Dark theme - Tooltip (minor)

### ISSUE THREAD

**Issue by Yousha** [HeidiSQL/HeidiSQL#96]
## Expected behavior

Tooltip background color must uses native system color, not WHITE
(when using dark themes in Windows)

## Current behavior

Tooltip background color and its text are white!
Check the screenshot:
![grafik](https://user-images.githubusercontent.com/7986591/35197726-e48c798a-fee3-11e7-8a72-ea501acdeeee.png)

## Failure information (for bugs)

None.

### Steps to reproduce

1. Change your Windows theme to Dark
2. Open HeidiSQL
3. Move pointer on a tooltip icon (bottom panel)

### Context

* HeidiSQL version: 9.4 (or ANY OTHER VERSION)
* Database system + version: MySQL 5.5
* Operating system: Windows 7 Pro 64-bit

### Failure Logs

None.

**Comment by ansgarbecker** [comment]
Is it just the one tooltip, over the bottom panel with the server version, or are there others as well?
I guess the normal buttons in the main toolbar show correctly, don't they?

**Comment by Yousha** [comment]
Yea, just one on bottom panel

**Comment by ansgarbecker** [comment]
According to [this forum thread at Embarcadero](https://forums.embarcadero.com/thread.jspa?threadID=116443), the background color of the `TBalloonhint` is hardcoded and unchangable. But this should only be a problem when you disable Aero theming in Windows - as you have according to the screenshot. Can you perhaps verify the issue gets fixed when activating Aero theming in Windows?

**Comment by Yousha** [comment]
Yea, fixed when using **Aero** themes

**Comment by ansgarbecker** [comment]
Ok, thanks.

I am closing this as I am unable to fix that. In the end it's Embarcadero which ships such broken features with a 1000€ product.
