### ISSUE TITLE
typing into snippets section should confine search/focus to snippets

### ISSUE THREAD

**Issue by leeoniya** [HeidiSQL/HeidiSQL#961]
## Steps to reproduce this issue

1. unfold snippets (or any) section in side panel
2. focus an entry starting with e.g. "n"
3. type "a"
4. the side panel automatically unfolds an unrelated section like Functions and finds and focuses an entry with "a"

## Current behavior

the panel will unfold an unrelated section to the one you're working in if the letter you type is found elsewhere in the panel.

## Expected behavior

the search should be confined to the active ubfolded section (snippets)

## Possible solution

this is probably a side-effect of the way the filtering field works above (globally), but in my experience is quite distuptive for my workflow, since i only live inside numerous snippets and would like to navigate between just them via typing to get focus without random unrelated sections unfolding.

## Environment

* **HeidiSQL version:** 

any. this behavior has been around forever.

**Comment by ansgarbecker** [comment]
VirtualTree does not offer an option to limit incremental searching to a parent node. This is all I can do here:

![grafik](https://user-images.githubusercontent.com/7986591/77772400-60127500-7048-11ea-823d-671578ecf5e3.png)

Limiting it to visible nodes probably comes close to what you want - collapsed nodes won't be searched. What about that?

**Comment by leeoniya** [comment]
> collapsed nodes won't be searched. What about that?

sounds reasonable.

**Comment by leeoniya** [comment]
works well, thanks!
