### ISSUE TITLE
the sql editor font not work better in linux-wine(2.6)

### ISSUE THREAD

**Issue by ladixiu** [HeidiSQL/HeidiSQL#962]
![image](https://user-images.githubusercontent.com/43605070/77822517-8579ae80-712e-11ea-9f34-25993d21dfcd.png)
could you help me find a way

**Comment by ansgarbecker** [comment]
The SynEdit components can use fixed fonts only. Try out other fixed fonts, on Tools > Preferences > SQL.

**Comment by ladixiu** [comment]
![image](https://user-images.githubusercontent.com/43605070/77823945-c4f9c800-7139-11ea-94c2-465d4e6692ad.png)
it works

at the begining , i doubt is the inputter in "2-byte input mode", but the key words display as blue

**Comment by ansgarbecker** [comment]
Thank you for the quick and helpful feedback!
