### ISSUE TITLE
On linux (mint) some icons are missing from the toolbar

### ISSUE THREAD

**Issue by iahim** [HeidiSQL/HeidiSQL#964]
## Steps to reproduce this issue

1. I have downloaded heidiSQL portable x64 and install it using wine on Linux Mint (Ubuntu bionic);

## Current behavior

Some of the icons on the toolbar are not displayed. Please see attached file.

## Expected behavior

All icons should be displayed

## Possible solution

Not sure if is related to wine / linux. Heidi works, just some icons are totally missing.

## Environment

* **HeidiSQL version:** 
11.0.0.5919
  
* **Database system and version:** 
Not relevant to this issue
  
* **Operating system:** 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19
DISTRIB_CODENAME=tara
DISTRIB_DESCRIPTION="Linux Mint 19 Tara"
NAME="Linux Mint"
VERSION="19 (Tara)"
UBUNTU_CODENAME=bionic
WINE version: wine-3.6 (Ubuntu 3.6-1)

![Screenshot_7](https://user-images.githubusercontent.com/1051201/77829254-282b3080-7121-11ea-8d14-ff624c3ba09f.jpg)

**Comment by ansgarbecker** [comment]
Same as #560 I guess.

Is there some idea how to solve that? I suppose it depends on the Wine version.
