### ISSUE TITLE
Microsoft Store still has an outdated version of HeidiSQL (10.3)

### ISSUE THREAD

**Issue by slaFFik** [HeidiSQL/HeidiSQL#965]
## Current behavior

MS Store version is still v10.3.0.0.

## Expected behavior

MS Store version should be v11.

## Possible solution

Upload a new version to MS Store.

**Comment by slaFFik** [comment]
@ansgarbecker Is it possible to have MS Store version of the app to be updated regularly?

**Comment by agund** [comment]
@ansgarbecker: pls

**Comment by ansgarbecker** [comment]
Today I published v11 in the store.
