### ISSUE TITLE
Can't connect to MS SQL after update

### ISSUE THREAD

**Issue by sdAtree** [HeidiSQL/HeidiSQL#967]
## Steps to reproduce this issue

1. I updated to HeidiSQL 11.0.0.5919
2. After launching the HeidiSQL, I got a notification about needing a new OLE DB driver
3. Downloaded and installed the driver from the Microsoft download page
4. Try opening a MS SQL connection via TCP/IP

## Current behavior

First, it took me a while to figure out it actually added a driver (instead of updating it). If I kept the SQLOLEDB driver selected, it would keep giving me the same update notice, and get stuck.

![afbeelding](https://user-images.githubusercontent.com/62642127/77883492-8829f000-7263-11ea-9eff-298c1d7dc682.png)

When I noticed and tried the new MSOLEDBSQL driver, it gave me the following error. While those credentials worked before, and I'm still able to log in to the server using MS SQL Management Studio with the same credentials and from the same computer.

![afbeelding](https://user-images.githubusercontent.com/62642127/77883926-5bc2a380-7264-11ea-8a7c-fb547ceb9bb1.png)

## Expected behavior

Being able to connect.

## Possible solution

I have no idea what's wrong
## Environment

* **HeidiSQL version:** 11.0.0.5919
  
* **Database system and version:** MS SQL 14.0.1000.169
  
* **Operating system:**  Windows 10

**Comment by ansgarbecker** [comment]
The first message is just a warning. You should have noticed the connection works fine after pressing OK, did you?

**Comment by sdAtree** [comment]
After that first warning, the interface got stuck. I now waited a while longer, and eventually an error appears about not being able to connect.

Note that this is with the SQLOLEDB library, not the newly installed MSSQLOLEDB. But it worked fine before the upgrade of HeidiSQL (or the installation of MSSQLOLEDB).

![afbeelding](https://user-images.githubusercontent.com/62642127/77888435-8f093080-726c-11ea-913d-458c7af19960.png)

PS. thanks for the quick reply

**Comment by budiony** [comment]
I am able to connect without problems to my MS SQL server after installing the new driver from Microsoft site. Are you sure you downloaded the correct driver for your platform? Keep in mind that after installing the driver, you have to restart your PC.

**Comment by sdAtree** [comment]
I worked on this further, and it looks like I can connect to my localhost, but not to any machine on our company network over VPN.

This used to work without issues and I can still connnect to those servers using Management Studio with the same credentials, but it does take longer to connect to the remote machines than the local machine.

Is it possible that the timeout to connect was altered, and I just can't connect within the given time?

**Comment by ansgarbecker** [comment]
> but it does take longer to connect to the remote machines

About how long?

**Comment by sdAtree** [comment]
Around 4 to 5 seconds, while connecting to localhost is almost immediate.

**Comment by ansgarbecker** [comment]
Did HeidiSQL v12.0 change anything here, or can this be closed? I'm not sure if your remote connections just take longer or don't work at all.

**Comment by budiony** [comment]
The connection to MSSQL in v.12.0 works just fine now.

**Comment by ansgarbecker** [comment]
Thanks for your feedback!
