### ISSUE TITLE
Blurry fonts on Windows 10 (Lenovo ThinkPad L390)

### ISSUE THREAD

**Issue by aslingga** [HeidiSQL/HeidiSQL#968]
## Current behavior

The fonts are blurry

![image](https://user-images.githubusercontent.com/1251391/77896217-1fae3380-72a2-11ea-90af-53708ade0cbe.png)

## Possible solution

App is not compatible with Windows 10 version

![image](https://user-images.githubusercontent.com/1251391/77896454-859abb00-72a2-11ea-8877-e9736d273e60.png)

## Environment

* **HeidiSQL version:** 11.0.0.5931
  
* **Database system and version:** MySQL 5
  
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
Duplicate to #213 - which I tried to solve, with limited luck. In the end I rolled back due to more issues than before. Having blurry fonts was harmless compared to the other issues.

Note that fonts are blurry because you are running Windows in some high DPI mode.
