### ISSUE TITLE
Table editor crashes when opening non connected federated table

### ISSUE THREAD

**Issue by Commifreak** [HeidiSQL/HeidiSQL#969]
## Steps to reproduce this issue

1. Create federated table which is not connected
2. Open the connection
3. Heidi shows warning (correct), then crahses

![Unbenannt](https://user-images.githubusercontent.com/87267/77991132-5bd5a880-7323-11ea-81ae-74a0df46f89b.JPG)

## Current behavior

If you try to open a federated table which is currently not connected, Heidi says that and then crashes with the attached report.

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4406980/bugreport.txt)

## Expected behavior

Warning about not connected table and NO crash :)

## Environment

* **HeidiSQL version:** 11.0.0.5919
  
* **Database system and version:** MySQL 5.7
  
* **Operating system:** Win10x64

**Comment by ansgarbecker** [comment]
Crash should no longer happen with the next build.
