### ISSUE TITLE
Error message while closing 

### ISSUE THREAD

**Issue by Guzoran** [HeidiSQL/HeidiSQL#97]
When I closing the HeidiSQL I get this error table!
close.

![heidisql_2018-01-19_13-32-46](https://user-images.githubusercontent.com/35600705/35152084-2f321f86-fd21-11e7-9662-f6274c721b02.png)

**Comment by ansgarbecker** [comment]
`EOSError`  that can be _anything_. Though I never heard that from other users, so this is probably some issue on your Windows installation. For example some Windows Update problem. I have no clue.

**Comment by ansgarbecker** [comment]
Is that reproducible for you or was it a one-timer?

**Comment by Guzoran** [comment]
Hi Ansgar Becker!

I did  upgrade my Win.10 op.system.
Now I have not problem.
There will be no problem, I hope... maybe not...

Sincerely,

Attila Guzoran

**Comment by ansgarbecker** [comment]
Ok, thanks. I'll close this issue - just shout if it appears again.

**Comment by Guzoran** [comment]
Hi Ansgar Becker!

Oh...

Thank you!

Sincerely,

Attila Guzoran
