### ISSUE TITLE
11.0.0.5919

### ISSUE THREAD

**Issue by gzw13999** [HeidiSQL/HeidiSQL#970]
date/time          : 2020-04-01, 04:16:16, 487ms
computer name      : LAPTOP-1FGGIPR6
user name          : xysh
registered owner   : xysh
operating system   : Windows 10 Tablet PC x64 build 17763
system language    : Chinese (Simplified)
system up time     : 2 days 8 hours
program up time    : 5 hours 55 minutes
processors         : 8x Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
physical memory    : 3988/8038 MB (free/total)
free disk space    : (C:) 12.62 GB (D:) 181.98 GB
display mode       : 1500x1000, 32 bit
process id         : $3664
allocated memory   : 192.94 MB
largest free block : 131025.95 GB
executable         : heidisql.exe
exec. date/time    : 2020-03-17 19:05
version            : 11.0.0.5919
compiled with      : Delphi 10.3 Rio
madExcept version  : 5.0.0
callstack crc      : $74cd3f58, $e3aec484, $e3aec484
exception number   : 8
exception class    : EInvalidOperation
exception message  : Cannot focus a disabled or invisible window.

main thread ($27ec):
00863b4d heidisql.exe Vcl.Forms                TCustomForm.SetActiveControl
00863cc8 heidisql.exe Vcl.Forms                TCustomForm.FocusControl
006caf5d heidisql.exe Vcl.Controls             TWinControl.SetFocus
00947526 heidisql.exe VirtualTrees   19860 +11 TBaseVirtualTree.DoEndEdit
00958925 heidisql.exe VirtualTrees   26617  +2 TBaseVirtualTree.EndEditNode
00b6e408 heidisql.exe grideditlinks    438  +1 TBaseGridEditorLink.DoEndEdit
006c86e0 heidisql.exe Vcl.Controls             TWinControl.DoExit
006c98fb heidisql.exe Vcl.Controls             TWinControl.CMExit
0040e952 heidisql.exe System                   TObject.Dispatch
006bfa8d heidisql.exe Vcl.Controls             TControl.WndProc
006c674a heidisql.exe Vcl.Controls             TWinControl.WndProc
006c597a heidisql.exe Vcl.Controls             TWinControl.MainWndProc
00564c73 heidisql.exe System.Classes           StdWndProc
7ff95594 USER32.dll                            SendMessageW
0085b364 heidisql.exe Vcl.Forms                SendFocusMessage
00863fa4 heidisql.exe Vcl.Forms                TCustomForm.SetFocusedControl
006c6180 heidisql.exe Vcl.Controls             TWinControl.WndProc
00955dd8 heidisql.exe VirtualTrees   25609 +32 TBaseVirtualTree.WndProc
006c597a heidisql.exe Vcl.Controls             TWinControl.MainWndProc
00564c73 heidisql.exe System.Classes           StdWndProc
7ff956b0 ntdll.dll                             KiUserCallbackDispatcher
00864200 heidisql.exe Vcl.Forms                TCustomForm.SetWindowFocus
00863b82 heidisql.exe Vcl.Forms                TCustomForm.SetActiveControl
00863cc8 heidisql.exe Vcl.Forms                TCustomForm.FocusControl
006caf5d heidisql.exe Vcl.Controls             TWinControl.SetFocus
00dfd8d8 heidisql.exe Main            5517 +15 TMainForm.PageControlMainChange
0073b020 heidisql.exe Vcl.ComCtrls             TCustomTabControl.Change
0073d289 heidisql.exe Vcl.ComCtrls             TPageControl.Change
0073c066 heidisql.exe Vcl.ComCtrls             TCustomTabControl.CNNotify
0040e952 heidisql.exe System                   TObject.Dispatch
006bfa8d heidisql.exe Vcl.Controls             TControl.WndProc
006c674a heidisql.exe Vcl.Controls             TWinControl.WndProc
006bf580 heidisql.exe Vcl.Controls             TControl.Perform
006c6939 heidisql.exe Vcl.Controls             DoControlMsg
006c7ad6 heidisql.exe Vcl.Controls             TWinControl.WMNotify
0040e952 heidisql.exe System                   TObject.Dispatch
006bfa8d heidisql.exe Vcl.Controls             TControl.WndProc
006c674a heidisql.exe Vcl.Controls             TWinControl.WndProc
006c597a heidisql.exe Vcl.Controls             TWinControl.MainWndProc
00564c73 heidisql.exe System.Classes           StdWndProc
7ff95594 USER32.dll                            SendMessageW
7ff94117 comctl32.dll                          #342
7ff95594 USER32.dll                            CallWindowProcW
006c68d2 heidisql.exe Vcl.Controls             TWinControl.DefaultHandler
006c0351 heidisql.exe Vcl.Controls             TControl.WMLButtonDown
0073e266 heidisql.exe Vcl.ComCtrls             TPageControl.WMLButtonDown
0040e952 heidisql.exe System                   TObject.Dispatch
006bfa8d heidisql.exe Vcl.Controls             TControl.WndProc
006c674a heidisql.exe Vcl.Controls             TWinControl.WndProc
006c597a heidisql.exe Vcl.Controls             TWinControl.MainWndProc
00564c73 heidisql.exe System.Classes           StdWndProc
7ff95594 USER32.dll                            DispatchMessageW
0086e88e heidisql.exe Vcl.Forms                TApplication.ProcessMessage
0086e903 heidisql.exe Vcl.Forms                TApplication.HandleMessage
0086ed51 heidisql.exe Vcl.Forms                TApplication.Run
00e31401 heidisql.exe heidisql          93 +32 initialization
7ff955db KERNEL32.DLL                          BaseThreadInitThunk
7ff956ac ntdll.dll                             RtlUserThreadStart

**Comment by ansgarbecker** [comment]
Please retry with the latest release. If still an issue, please fill out the issue template.
