### ISSUE TITLE
Missing quotes in ALTER-statements over VARCHAR fields

### ISSUE THREAD

**Issue by maickelw** [HeidiSQL/HeidiSQL#971]
## Steps to reproduce this issue

1. Create a table with 2 fields with field1 having default value 'test'.
This results in the following statement:
```
CREATE TABLE `test_table` (
	`ID` INT NOT NULL,
	`field1` VARCHAR(50) NOT NULL DEFAULT 'test',
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
;
```

2. Rename `field1` to `field2` using the Heidi interface.
This results in the following erroneous statement:

```
ALTER TABLE `test_table`
	CHANGE COLUMN `field1` `field2` VARCHAR(50) NOT NULL DEFAULT test COLLATE 'latin1_swedish_ci' AFTER `ID`
;

```
3. Resulting in the following error-dialog:

`SQL Error (1064): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'test COLLATE 'latin1_swedish_ci' AFTER `ID`' at line 2
`

## Current behavior

Quotes around the default value of the VARCHAR field in the ALTER-statement are missing.

## Expected behavior

Re-add quotes to the default value of the VARCHAR-field

* **HeidiSQL version:** 
  
Heidi 11.0.0.5918

* **Database system and version:** 
  
5.5.57-MariaDB, MariaDB Server, x86_64 on QNAP NAS

* **Operating system:** 
  
Windows 10 64 bit

**Comment by ansgarbecker** [comment]
Could it be you are missing the information_schema.columns table? Or is that by default not present on MariaDB 5.5?

**Comment by maickelw** [comment]
The information_schema.columns table is present on the MariaDB install and contains the aformentioned column. I just tested it on a Windows MySQL 5.6.x, and the issue does not occur there.

Some further observations:
1. The difference is already visible in the Default column in the fields Editor. On MariaDB, after I save the table, the default-values in the Default column lose the quotes they were in right after adding the field. In MySQL the quotes are kept after saving the modified table structure.
2. The `SHOW CREATE TABLE test_table;` statement does display the quotes.
3. The Create new > Table copy function from the context menu doesn't work either because of the missing quotes around the default value

**Comment by ansgarbecker** [comment]
Should be solved in the next build. I found some more details on https://mariadb.com/kb/en/create-table/#default-column-option for when MariaDB started to support expressions.
