### ISSUE TITLE
Customizable shortcut for SQL completion proposal (Ctrl+Space)

### ISSUE THREAD

**Issue by lygoing** [HeidiSQL/HeidiSQL#972]
This shortcut key conflicts with the input method switch key of the Windows 10 system, and the Windows 10 shortcut key cannot be modified, so I can only seek a way to modify heidisql, please tell me. Thank you

**Comment by ansgarbecker** [comment]
There is no way to change this hotkey in HeidiSQL.

But the hotkey for switching input methods in Windows is not <kbd>Ctrl+Space</kbd>, but <kbd>Win+Space</kbd> , did you notice that?

**Comment by lygoing** [comment]
@ansgarbecker

**Comment by lygoing** [comment]
@ansgarbecker  Thank you for your reply. I don't know the situation in other locales. I use the Chinese input method. It uses Ctrl + space to switch. This makes me unable to use HeidiSQL's auto-complete input when editing SQL. Unfortunately, I can only think of other ways. Thank again.

**Comment by lygoing** [comment]
Explanation:
1. The keyboard has windows keys
2. Using the Chinese input method that comes with windows 10

![image](https://user-images.githubusercontent.com/5944432/78155040-8cc2f400-746f-11ea-9115-2be5986f7984.png)

**Comment by lygoing** [comment]
A small proposal,
It would be nice if the hotkeys were configurable. Honestly, if HeidiSQL can open the prompt box immediately without using hot keys, I think it is perfect. This can greatly improve efficiency. But everyone has different preferences.

Thanks for your great work.

**Comment by ansgarbecker** [comment]
Of course, you can already define your own shortcuts, besides many others also for that "Launch command line", in Tools > Preferences > Shortcuts:

![grafik](https://user-images.githubusercontent.com/7986591/78159668-27f1a480-7443-11ea-865b-7b89277c95d3.png)

Just that special hotkey for the completion proposal is not yet contained there, as this is a special component. So I will have to add that.
