### ISSUE TITLE
Access violation at address 0000000000AFB540 in module 'heidisql.exe'

### ISSUE THREAD

**Issue by budiony** [HeidiSQL/HeidiSQL#973]
## Steps to reproduce this issue

1. Creating table LIKE other table (`CREATE TABLE LIKE xxx statement`) from interface;
2. Right click on table, choose `Create table copy`;
3. Check everything from options in next dialog window;
4. Then I get Access violation at address 0000000000AFB540 in module 'heidisql.exe' (see attached bugreport.txt)

[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4415360/bugreport.txt)
## Expected behavior
Application doesn't crash.

## Environment

* **HeidiSQL version:** 
11.0.0.5931
  
* **Database system and version:** 
MySQL 5.6.33
  
* **Operating system:** 
Windows 10 x64 build 18363

**Comment by lukinhaspm** [comment]
I try and works fine in MariaDB

**Comment by caugner** [comment]
@lukinhaspm Have you tried changing the library to `libmysql.dll` in the connection settings?

![grafik](https://user-images.githubusercontent.com/495429/79451024-1f25d480-7fe6-11ea-8d79-412d6627a507.png)

**Comment by budiony** [comment]
It seems that changing the library in the connection settings solved the problem, at least I didn't receive this error since 15th of April.

**Comment by ansgarbecker** [comment]
Thanks for your feedback.
