### ISSUE TITLE
The application cant run querry with comments inside

### ISSUE THREAD

**Issue by mihaifcristian** [HeidiSQL/HeidiSQL#974]
## Steps to reproduce this issue

**Querry do not work**

SELECT u.id, u.name, v.idClient, v.idLabelVeh, v.idPlateVeh 
--rm.idVeh, rm.idOwnMsg 
FROM users u 
LEFT JOIN sat_vehicle v ON v.idClient = u.id
--LEFT JOIN sat_vehRefMsg rm ON v.idVeh = rm.idVeh
WHERE u.id = 14 

**Querry works well**
SELECT u.id, u.name, v.idClient, v.idLabelVeh, v.idPlateVeh
FROM users u 
LEFT JOIN sat_vehicle v ON v.idClient = u.id
WHERE u.id = 14

## Current behavior
He returns me a message Sql Error (1064) You have an error in your Sql syntax;
I cant see the syntax error on my querry this is why i made a copy with no comments inside and it`s work very well. 
HeidiSQl can`t run querry with commets. He cant ignore the comments. 

## Expected behavior

It`s important to handle this type of querry so do not need to copy the entire querry and remove comments just to run it. 

* **HeidiSQL version:** 
 11.0.0.5934(64 Bit)
* **Operating system:** 
 Windows 10 x64

**Comment by ansgarbecker** [comment]
You ignored the "Database system and version" in the issue template, and I suppose it's MySQL or MariaDB? These expect a space after the double dash comment. See https://dev.mysql.com/doc/refman/5.7/en/comments.html

**Comment by ansgarbecker** [comment]
See also #549, which changes the highlighting of double minus comments
