### ISSUE TITLE
Exception on loosing focus while Table > Columns > Information is still selected

### ISSUE THREAD

**Issue by MixaMasta** [HeidiSQL/HeidiSQL#975]
## Steps to reproduce this issue

1. Want to copy a column name to insert in a query;
2. A Table is selected;
3. On tab "Table" under "Columns" a column information is selected;
4. Right-click on "Name" and choose Copy;
5. Change to the Query tab while the column information is still selected;
6. An exception occurs;

## Current behavior

An exception occurs:
```
exception class : EInvalidOperation
exception message  : Cannot focus a disabled or invisible window.
```
[bugreport.txt](https://github.com/HeidiSQL/HeidiSQL/files/4433700/bugreport.txt)
[bugreport.zip](https://github.com/HeidiSQL/HeidiSQL/files/4433701/bugreport.zip)

## Expected behavior

It should not throw an exception.

## Possible solution

Maybe a check on the "selected column information" when loosing focus...

## Environment

* **HeidiSQL version: 11.0.05919 64bit** 
  
* **Operating system:** 
  Windows 10 Pro

**Comment by ansgarbecker** [comment]
I already fixed that, as this was mentioned in https://github.com/HeidiSQL/HeidiSQL/issues/935#issuecomment-604302774 . Marking this as duplicate. Please update to the latest build.
