### ISSUE TITLE
"copy all" data from a SELECT query fails

### ISSUE THREAD

**Issue by piula** [HeidiSQL/HeidiSQL#978]
## Steps to reproduce this issue

1. open a new Query tab
2. perform an arbitrary SELECT query returning at least 2 rows and/or 2 columns
3. click in the result table
4. "Edit > Select all"
5. "Edit > Copy"
6. Open notepad.exe and paste

## Current behavior

Only a single cell is being copied.

## Expected behavior

The whole result table should be copied.

## Possible solution

When more than a single cell is being selected, all selected cells should be placed in the clipboard.

## Environment

* **HeidiSQL version:** 
11.0.0.5937*
**Database system and version:** 
Issue occurring with SQLite; not tested with other database systems.

**Comment by ansgarbecker** [comment]
This is how it is intended to work. "Copy" copies the focused cell. And "Copy selected rows" copies the selected rows, as the name says:

![grafik](https://user-images.githubusercontent.com/7986591/78827331-3e6ba300-79e3-11ea-8640-0ffe882b4f1c.png)

To define the format used by that "Copy selected rows", you will have to once open up the "Export grid rows" dialog and click the "Save clipboard settings" when you're done.
