### ISSUE TITLE
No updates on the default column after change.

### ISSUE THREAD

**Issue by howardfun** [HeidiSQL/HeidiSQL#981]
Steps to reproduce this issue

1. Create a table

CREATE TABLE `table1` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`timestamps` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;

2. Step 2;
Change on update to "CURRENT_TIMESTAMP" on the GUI and SAVE...
![image](https://user-images.githubusercontent.com/53899971/78988254-02f7e280-7b63-11ea-8ff4-944e07a9316b.png)

3. Then I get...
The GUI displayed without on update statement.

![image](https://user-images.githubusercontent.com/53899971/78987967-2b331180-7b62-11ea-87f9-fc50e33249d7.png)

## Current behavior

But, if you alter it using the following codes, the GUI updated acts normal. 

ALTER TABLE `table1`
	CHANGE COLUMN `timestamps` `timestamps` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `id`;

## Expected behavior

Expect to see

![image](https://user-images.githubusercontent.com/53899971/78988223-e9ef3180-7b62-11ea-9a66-c87dcd1d9cff.png)

## Environment

* **HeidiSQL version:** 11.0.0.5919
  
* **Database system and version:**  MySQL Community 8.0.16
  
* **Operating system:** Windows 10 Home

**Comment by ansgarbecker** [comment]
Could you please update to the latest build and retry. I recently fixed some issues with that default editor, so this may already be fixed.

**Comment by howardfun** [comment]
I have tried the build version "HeidiSQL 11.0.0.5950 64 Bit", but the issue still exists. Thank you!

**Comment by howardfun** [comment]
As I checked the 12.0.0.6428 version, the issue is already resolved. Thank you very much!

**Comment by ansgarbecker** [comment]
Thanks for your feedback!
