### ISSUE TITLE
Could you format sql script for view?

### ISSUE THREAD

**Issue by coffeehunger** [HeidiSQL/HeidiSQL#982]
## Steps to reproduce this issue

1. Step 1;
2. Step 2;
3. Step N;
4. Then I get...

## Environment

* **HeidiSQL version:** 
  
* **Database system and version:** 
  
* **Operating system:**

**Comment by ansgarbecker** [comment]
You can use HeidiSQL's builtin reformat button:
![grafik](https://user-images.githubusercontent.com/7986591/79042659-e2c73280-7bf9-11ea-924e-d53db11b35fd.png)

I just added that to the context menu in the view editor, so future builds will shows this there as well:

![grafik](https://user-images.githubusercontent.com/7986591/79042665-f1154e80-7bf9-11ea-9095-718a8f440a99.png)
