### ISSUE TITLE
Save current DB in HeidiSQL when switched to DB, not when closing HeidiSQL

### ISSUE THREAD

**Issue by slaFFik** [HeidiSQL/HeidiSQL#983]
## Current behavior

When you switch between databases HeidiSQL saves the current DB only when you correctly close the app.

## Expected behavior

Save the current DB in HeidiSQL settings every time you switch to a DB, not when you close the app.

When a crash happened (using MS Store v10.3) HeidiSQL can be restarted manually when the "Restart" button is clicked on the exception window. But in this case current DB is NOT saved, because the app was not closed correctly.
I switch between DB very often and have a long list of them, so search for a DB takes time and very inconvenient, especially because those crashes are happening very often.

## Environment

* **HeidiSQL version:** 
  
Installed via Microsoft Store.
![image](https://user-images.githubusercontent.com/282234/79020545-c7b8dc00-7b81-11ea-90bb-4ad1cf15fcaf.png)

* **Operating system:** 
Windows 10 Pro.

**Comment by ansgarbecker** [comment]
There are many other settings which are also stored at the end of a session as well. But I think for this one it makes sense.
