### ISSUE TITLE
Weird display in session manager in french language

### ISSUE THREAD

**Issue by MilleMiles** [HeidiSQL/HeidiSQL#984]
## Steps to reproduce this issue
1. Step 1; open the app

## Current behavior
![h_sql](https://user-images.githubusercontent.com/16926238/79065374-29776400-7cb0-11ea-9c90-4b4d6b4561da.png)
Some buttons are too small.

## Environment
French language

    HeidiSQL version: HeidiSQL 11.0.0.5919
    Operating system: Windows 10

**Comment by ansgarbecker** [comment]
These buttons get the width of the above list, so if you wide that, the labels should match. Also, in newer builds, the buttons on the bottom right are widened slightly - in case their labels are wider.
