### ISSUE TITLE
[Feature Request] Record/log changes

### ISSUE THREAD

**Issue by timint** [HeidiSQL/HeidiSQL#985]
Hi, I would love to see a feature to record all my changes being made.

I could use it for creating migration patches (meaning doing the same actions in other machines).

**Comment by ansgarbecker** [comment]
Isn't the SQL log what you want? That log can also be recorded to a file per session, please look at it in the context menu, or in the preferences dialog:
![grafik](https://user-images.githubusercontent.com/7986591/79109112-01ebce80-7d78-11ea-958d-4d0beb4ceb65.png)

**Comment by timint** [comment]
Not really but thanks for trying :) 
That log consists of all the selects and UI clickarounds. I am thinking a log of changes written only.

**Comment by timint** [comment]
And now that you mentioned session I want to take this idea further...

How about this for an alternative to a recording/pause button:
- A profile based log that appends to a log file being set in the Session Manager profile.
- The ability to pick Writing events only (create/alter/insert/update/delete/truncate).
- Date variables supported in the filename such as C:\Folder\Project\migrations\%Y%m%d.sql

**Comment by ansgarbecker** [comment]
Well then let's move this discussion to the earlier requested #397
