### ISSUE TITLE
Create function/procedure depending on menu

### ISSUE THREAD

**Issue by WouterVanNifterick** [HeidiSQL/HeidiSQL#987]
This is more of a feature request than a bug report, but I'll stick to the bug report format.

#648  Steps to reproduce this issue
1. Right click `Functions`
2. Choose new/stored routine

## Current behavior

Always creates a stored procedure

## Expected behavior

Creates a function when invoked from "functions" menu
Creates a procedure when invoked from "procedures" menu

## Possible solution

Two suggestions:
1. Use the context to create the right thing. It's the most intuitive solution, and keeps UI uncluttered.

2. Have two separate actions in the popup menu: one to create a function, one for a procedure. Right now, the menu shows a "procedure" icon, having two separate actions could be more clear here.

## Environment
N/A

**Comment by ansgarbecker** [comment]
Should do it:

![grafik](https://user-images.githubusercontent.com/7986591/104844668-d92dd200-58d1-11eb-9cc0-a773d1d60916.png)
