### ISSUE TITLE
Windows Authentication for MariaDB connection

### ISSUE THREAD

**Issue by christophvw** [HeidiSQL/HeidiSQL#991]
## Steps to reproduce this issue

1. Open Connection Manager
2. Select MariaDB or MySQL (TCP/IP)
3. Enter a hostname of a MariaDB Server with gssapi plugin enabled
4. Try to connect (without Username and Password)

## Current behavior

-checkbox "Use Windows Authentication" cannot be enabled
-connect fails without username and password
-connect works with username only (no password)

## Expected behavior

-connect should work without specifying a username when checkbox "Use Windows Authentication" is enabled

## Environment

* **HeidiSQL version:** 
  10.3.0.5771 (64 Bit)
* **Database system and version:** 
  MariaDB 10.4 with gssapi plugin loaded
* **Operating system:** 
  Windows 10 Enterprise / MariaDB on Windows Server 2019 Standard

**Comment by ansgarbecker** [comment]
Do you know how to accomplish such an authentication using the MySQL C-API ?

**Comment by christophvw** [comment]
The authentication itself works, you just need to pass the username of the current user.
When I fill in the username manually it works.

**Comment by ansgarbecker** [comment]
Well I meant what do I have to change in the underlying authentication logic within the code of HeidiSQL.
But as far as I understand the [documentation](https://mariadb.com/kb/en/authentication-plugin-gssapi/#client-authentication-plugins), you just need to use libmariadb.dll v3.0.1 or newer, which is included in the current HeidiSQL v11.
You did not perhaps select libmysql in the "Library" dropdown?

**Comment by ansgarbecker** [comment]
Grm... you were using HeidiSQL v10.3 - please update.

**Comment by christophvw** [comment]
Oh, sorry. Didn't notice the new version.
Now it seems to work without a username.

**Comment by christophvw** [comment]
Still a bit confusing that you cannot enable the checkbox for windows authentication - which then clears and disables the username and password textboxes.

**Comment by ansgarbecker** [comment]
Yes, I should enable that checkbox in MySQL/MariaDB mode. Or should I only enable it when libmariadb is selected? The other libraries don't support that gssapi.

**Comment by christophvw** [comment]
Then enable it for libmariadb only.

For MySQL I only found this so far:
https://dev.mysql.com/doc/refman/8.0/en/windows-pluggable-authentication.html

Looks like it applies to Enterprise version only.

**Comment by christophvw** [comment]
Oops - with empty username it fails to connect with version 11 too.
So you have to fill in the current username when Windows Authentication is selected.

**Comment by ansgarbecker** [comment]
Does it matter if it's the wrong username then, so the user may be anything, or does it have to be the correct one? I suspect the library to override the username anyway, so this may be interesting.

**Comment by christophvw** [comment]
It has to be the correct one.

I created two users on the server: user1 and user2.

When I am loggon on on my local machine with user1 and specify user2 in the connection dialog I get an error.

GSSAPI name mismatch, requested user2@domain, actual name user1@domain.

**Comment by christophvw** [comment]
And you have to provide just the username in the connection dialog. Not the upn.

so just "user", not "user@domain"

**Comment by ansgarbecker** [comment]
So the only thing is to disable the password field when the user checks the "Windows authentication" checkbox. Would that really be helpful for the user then?

**Comment by christophvw** [comment]
disable username and password field - and pass the current username to the driver

**Comment by ansgarbecker** [comment]
Next build enables the Windows auth checkbox on MySQL/MariaDB connections, and sends the current system user name and a blank password to the driver. Please check if that works, especially I am not aware whether the username contains some "@domain". The [documentation](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getusernamew) is not that clear to me in that point.

**Comment by gwselke** [comment]
Works like a charm -- great work!
(Which implicitly resolves the unclarity of "@domain".)

**Comment by gwselke** [comment]
Minor observation: the username/password choice in the connection management window is now actually tri-state, since specifying username/password AND using Windows authentication does not make sense.  Visually, this is not carried by using two (seemingly independent) check boxes, which stipulates there might be four possibilities in total. 
I don't think, however, this would seriously confuse anyone.

**Comment by vaintroub** [comment]
Specifying username does make sense, only password does not 
MariaDB user name is not necessarily the same as GSSAPI/SSPI/Windows user name, it can be, but does not have to.
