### ISSUE TITLE
Dark mode: "More infos" link hard to read in error message dialog

### ISSUE THREAD

**Issue by caugner** [HeidiSQL/HeidiSQL#993]
# Steps to reproduce this issue

1. Set HeidiSQL to dark mode.
2. Go to a table.
3. Add a nullable auto-increment column.
4. Save the change.
5. Get an error message dialog.

## Current behavior

The "More infos" link at the bottom of the error message dialog does not show properly:
![grafik](https://user-images.githubusercontent.com/495429/79449739-0fa58c00-7fe4-11ea-8ea3-fed52a296f39.png)

## Expected behavior

It should be readable also in dark mode.

## Possible solution

Change the link color in dark mode.

## Environment

* **HeidiSQL version:** 11.0.0.5919 (64-bit)
* **Database system and version:** MySQL 8.0.19
* **Operating system:** Windows 10

**Comment by ansgarbecker** [comment]
Yes, this is indeed worth trying to find a way to set a different link color.

**Comment by ansgarbecker** [comment]
Next build has white link color in these dialogs.
