### ISSUE TITLE
Dark mode: Buttons in bug report dialog hard to read

### ISSUE THREAD

**Issue by caugner** [HeidiSQL/HeidiSQL#994]
## Steps to reproduce this issue

1. Enable dark mode.
2. Cause an error in the application (tricky to reproduce).

## Current behavior

Buttons are either too dark or too bright:

![grafik](https://user-images.githubusercontent.com/495429/79450817-bdfe0100-7fe5-11ea-88a8-a52d8a25e5f2.png)

## Expected behavior

The buttons should be readable.

## Possible solution

Change text or background color of the buttons.

## Environment

* **HeidiSQL version:**  11.0.0.5919
* **Database system and version:** MySQL 8.0.19
* **Operating system:**  Windows 10

**Comment by ansgarbecker** [comment]
I'm afraid I cannot fix that, as the crash handler is an external component. See [its webpage](http://www.madshi.net/madExceptDescription.htm). Probably the author can fix that.

**Comment by caugner** [comment]
@ansgarbecker You couldn't make the external component use the default (light) theme either?

**Comment by ansgarbecker** [comment]
Good idea. I just asked in their forum: http://forum.madshi.net/viewtopic.php?f=4&t=28806
