### ISSUE TITLE
connection manager does not store changes on disc immediately on pressing save

### ISSUE THREAD

**Issue by assachs** [HeidiSQL/HeidiSQL#997]
Heidisql does not save the connection settings on disc if you press save. They are stored internally and are only saved to disc if you close heidisql.

## Steps to reproduce this issue
-Start Heidisql
-Change connection settings
-press save
-start second instance
-the changed connection has the old values.

Sometimes you also loose the changes, depending on the order how you close heidisql instances.

## Expected behavior
The changes should be written to disc immediately.
Only the changed connection should be changed in the file, to prevent overriding of changes, done by another instance.

## Possible solution
I would prefer a directory with a file for each connection. The filename does not need to contain the name of the connection. Maybe a uuid or something similar. On every start of connection manager all files are loaded. If a connection is changed, the file is written to disc.

**Comment by assachs** [comment]
Maybe it's only a problem of the portable version. I have not tried, if i can reproduce the same problem with registry stored connection settings.

**Comment by ansgarbecker** [comment]
The portable version reads its settings once it starts, and writes everything in one bunch when you exit Heidi. Between start and end, every change is written to a temporary registry key. This is the way it is implemented. I recommend not to open multiple application instances with the portable version. It's more reliable to open multiple connections in one instance instead.

**Comment by assachs** [comment]
The use case for opening multiple instances is to compare tables or to copy single rows from a production to a testing system.

Thanks for explaining. I found out, that multiple portable instances don't share a temporary registry key. So there doesn't seem to be an easy solution. The topic is not that important. I have to be careful when I change connections. 
You can close the issue.

**Comment by ansgarbecker** [comment]
Thanks for your feedback!
