### ISSUE TITLE
x ) or y ) are converted to uppercase

### ISSUE THREAD

**Issue by assachs** [HeidiSQL/HeidiSQL#998]
Hello,
sorry for opening so many bug reports. I have time now and use it very often. I like heidisql and i hope it is getting even better with the bug reports. Thanks for your work.

If you write the following sql the last x will be concverted to upper case after pressing ")":

select * from (select x.test from tablename x )
->
SELECT * FROM (SELECT x.test FROM tablename X )

The same with y but not with other letters (e.g. a).

The SQL is not valid (column x.test not found).

11.0.0.5958
Mysql 5.7
windows 10

Thanks
Andi

**Comment by ansgarbecker** [comment]
Well, `x` is a [MariaDB function](https://mariadb.com/kb/en/st_x/), and you may have activated uppercasing reserved words:
![grafik](https://user-images.githubusercontent.com/7986591/79630762-6d58e600-8154-11ea-88e3-5aac784b227f.png)

Also, please never delete the issue template, as told in the template itself such issues will be closed.

**Comment by assachs** [comment]
Ok, it's not a big problem. Don't put too much effort into it.
Is there an easy possibility to edit the list of reserved words (to remove x and to add UDFs)? 
or to select a SQL dialect?
