### ISSUE TITLE
Please add the .res-Files to the repositories.

### ISSUE THREAD

**Issue by DelphiFreak** [HeidiSQL/HeidiSQL#999]
I tried to compile HeidiSQL but got stuck, because the .res-files for assets,icons,updater are missing.

Would be nice if you could add these files.

Thank you.

**Comment by ansgarbecker** [comment]
Just execute the `build-res.bat` from the root directory. However, `brcc32.exe` and `cgrc.exe` need to be detectable via path environment variable.
